### ISSUE TITLE
Ledger timer resetting

### ISSUE THREAD

**Issue by msp1111111** [brave/browser-laptop#3696] opened 2016-09-03 17:31 UTC
My ledger timer resets every once in a while, so some of the time I've spent on certain sites is gone. Also, some of the sites that I marked to not include are back. I don't see an obvious pattern to the sites that have been reset and the sites that are not.
Win7
ver 0.11.6

**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
- Brave Version:
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by Aeyoun** [comment] 2016-09-05 00:20
I can confirm this issue. (Have been screenshotting my ledger to keep an eye on changes.)

I’ve only seen it happen to websites with less than 1 minute on record. Not sure if that is significant. It happen right after midnight local time (CEST).

**Comment by msp1111111** [comment] 2016-09-05 17:41
For me, there is one site that I visit a lot. It should have a few hours on the timer, but right now it's showing 48 seconds. There is another site that I visited once a couple days ago, but then put my computer to sleep with the site open for a couple hours. That one is still there, showing 2h 23min.

**Comment by mrose17** [comment] 2016-09-05 23:23
@msp1111111 & @Aeyoun -- hmmm. i think i may have tracked that down. when we push a new beta, is it OK to point you both at it to try it out? thanks!

**Comment by Aeyoun** [comment] 2016-09-06 00:00
I’m glad to hear that. Hope you’ll release a new beta soon.

I’m game for a 64-bit RPM build. Can dig up a Mac or Win PC if need be, but it will get less testing.

**Comment by mrose17** [comment] 2016-09-06 01:38
we have a linux build too!

**Comment by mrose17** [comment] 2016-09-06 19:32
@Aeyoun & @msp1111111 - can you check out the builds on https://github.com/brave/browser-laptop/releases/tag/0.12.0dev and see if you are still seeing this issue?

@Aeyoun - can you also see if https://github.com/brave/browser-laptop/issues/3716 is addressed by this as well?

thanks and _good luck!_

**Comment by msp1111111** [comment] 2016-09-06 21:40
Yes, thanks for the super-quick response!



Date: Tue, 6 Sep 2016 12:32:20 -0700

**Comment by mrose17** [comment] 2016-09-06 22:00
@msp1111111 - sorry, couldn't quite parse your note. just checking:

are you able to run the new release?
if so, does it fix this issue?

thanks (and sorry for the confusion)

**Comment by Aeyoun** [comment] 2016-09-06 22:01
Oh, look at that. I’ve seen mentions of favicons in the code, but now they show up on the ledger list too. It also counts +1 view per page view, didn’t do that before (wasn’t sure it was expected to either!) 

I don’t like that it’s counting every time I switch back and forth between two tabs a “view”. “A pageview” in every other context is one loaded page, and not literally how many times the loaded page is displayed in a tab without a round-trip to a server. Maybe I’m old fashioned that way.

#3716 seems to be resolved as well.

**Comment by mrose17** [comment] 2016-09-06 22:02
@Aeyoun - thanks. i am sensitive to your issue about whether switch tabs back and forth should count as a view or not (though i suspect we agree that the timer should keep running). let me look into that...

**Comment by alexwykoff** [comment] 2016-09-06 22:12
Please make sure to add a concise outline the steps for QA to confirm any changes. Thanks!

**Comment by msp1111111** [comment] 2016-09-06 22:19
I have just a few moments ago updated to 0.12.0. I'll keep an eye on the site timer and see if anything gets reset again.
Thanks!


Date: Tue, 6 Sep 2016 15:00:55 -0700

**Comment by Aeyoun** [comment] 2016-09-06 22:25
> @Aeyoun - thanks. i am sensitive to your issue about whether switch tabs back and forth should count as a view or not (though i suspect we agree that the timer should keep running). let me look into that...

Timer should run, view count counter should only increment once after the lad when the tab first become focused. 

I.e. load Site 1 in Tab A, and Site 2 in Tab 2. That should be one view per tab regardless of how often I switch between them. Only count views on load. Background tabs should only be counted as a view when/if they’re brought to the foreground. (I may close a background tab without ever activating it if I change my mind about reading it.) The same goes for session restores during start-up, I think. Don’t count tabs from a restored session as an additional view.

How people think of this stuff may be different from person to person, but the above seems logical to me and how I use the browser.

**Comment by Aeyoun** [comment] 2016-09-07 14:09
Hm, noticing a problem but not sure if it’s the same, new, or different issue.

So I have 29 sec on record and 1 visit for NPR.org. When I visit NPR.org and wait a 50 seconds, and then go back to check the ledger it will still display 29 sec and 1 visit. I can restart Brave and try again, but NPR.org stays on that one visit of 29 seconds. [LEDGER_PUBLISHER_DEBUG output](https://gist.github.com/Aeyoun/0b6bcc0a3bf2b59fe00dd697705d4d07) provided here.

I’ve noticed the same issue with six other domains. The majority of websites seems to work now, however.

**Comment by msp1111111** [comment] 2016-09-07 14:31
As far as I can tell, the timer is working for me now correctly on the blogs that I visit. There is a video site, viki.com, that I watch entire hour-long episodes on and that doesn't time correctly. Perhaps the timer excludes media playing?

**Comment by mrose17** [comment] 2016-09-07 22:09
@msp1111111 - thanks. i am able to watch a video on viki -- _dramaworld_ -- and it looks like that it is being counted...

<img width="831" alt="1" src="https://cloud.githubusercontent.com/assets/400552/18330241/3cc4ab26-750c-11e6-98ec-3e9904b2c0f2.png">

still investigating.

**Comment by mrose17** [comment] 2016-09-07 22:11
also, just fyi: if you want to check to see if a URL is considered a publisher, go to https://ledger.brave.com/documentation#!/v1/getV1PublisherIdentity and enter the URL.

**Comment by mrose17** [comment] 2016-09-07 22:13
@msp1111111 - just a thought (that @bridiver can confirm). i believe that tabs have a maximum duration associated with them (akin to an inactivity timer).

so here's my question: did [viki.com](viki.com) show up at all or just for 30s or something like that? thanks!

**Comment by bsclifton** [comment] 2016-09-07 22:14
@msp1111111 can you set an environment variable to help collect more info?

We need to set: LEDGER_PUBLISHER_DEBUG=true

You probably already know how to set environment variables, but just in case:
* Hit Windows key, type environment
* Pick "Edit the system environment variables" from the list
* Click the "Environment Variables" button
* Under "System variables" click "New..." button
* enter the variable (in this case, name=LEDGER_PUBLISHER_DEBUG, value=true)

**Comment by bridiver** [comment] 2016-09-07 22:15
there is an idle timer that stops the clock if you lock your computer or have no mouse/keyboard activity for 15 minutes. The inactivity monitor applies to the entire OS, not just Brave

**Comment by mrose17** [comment] 2016-09-07 22:17
@bridiver - so, we'd expect 15m to be the maximum unless the mouse is being moved?

**Comment by bridiver** [comment] 2016-09-07 22:25
Yep, but we may want to increase that time if the page is displaying video and only stop the timer on screen lock

**Comment by mrose17** [comment] 2016-09-07 22:31
@Aeyoun - thanks, so there is one very interesting thing going on here. when i go to that URL, my logging looks like this:

        locations[http://www.npr.org/2011/08/04/138719111/microstyle-marketing-slogans-for-the-self]={
          "timestamp": 1473286993249,
          "protocol": "http:",
          "publisher": "npr.org"
        } duration=895 msec

which indicates that the URL was recognized as being associated with a publisher. your logging doesn't show that. since (i know) that we haven't changed the status of NPR on the ledger, and since [this](https://ledger.brave.com/documentation#!/v1/getV1PublisherIdentity) shows that NPR is considered a publisher, the only explanation is that the javascript that does the publisher lookup is blowing up. we can check for that!

let's try an experiment: run your test again, do an 'inspect element' in that tab and look at the console. any errors there relating to `pageInformation.js` ?

if you see `NOT a string` as a console entry, that means that the code ran fine, but the ledger says it's not a publisher... sorry for the back-and-forth, thanks!

**Comment by msp1111111** [comment] 2016-09-07 23:06
@mrose17 I watched viki yesterday for about an hour total. The timer shows about 5 min. I believe the page count is correct, however.

@bsclifton I set that environment variable as you instructed, but am not sure how to access the log, sorry.

Also, just a thought -- viki shows their ads within their videos (which are blocked by Brave), not on the page in general, if that makes any difference.

**Comment by Aeyoun** [comment] 2016-09-07 23:21
I’ve seen the 15 minute idle timer, and haven’t said anything. I personally feel no more than 3–5 minuets inactivity of _Brave_ (except when in fullscreen API for media playback) should stop the counter.

I feel like I have to actively open a new blank tab before going to the bathroom or change to another program. Stressful micro-management that I really shouldn’t have to deal with.

**Comment by Aeyoun** [comment] 2016-09-07 23:24
> let's try an experiment: run your test again, do an 'inspect element' in that tab and look at the console. any errors there relating to pageInformation.js ?

No such error.

**Comment by mrose17** [comment] 2016-09-08 00:17
well, i don't know why "it works for me, but not for you". the "tell" is the lack of publisher information in the logging. i'll add some more logging to the next version and perhaps we can get a better understanding.

**Comment by mrose17** [comment] 2016-09-08 00:17
i like the idea of 90s timer.

**Comment by bridiver** [comment] 2016-09-08 01:09
the 15 minute timer only applies if Brave is in the foreground so it's basically a Brave activity timer. We're not set on 15 minutes either, it just seemed like a reasonable place to start

**Comment by mrose17** [comment] 2017-01-19 23:13
closed due to lack of focus.

**Closed by mrose17** 2017-01-19 23:13 UTC
Labels: bug, feature/ledger
