### ISSUE TITLE
Google Hangouts doesn't work

### ISSUE THREAD

**Issue by AluminumOvercast** [brave/browser-laptop#11993] opened 2017-11-16 04:03 UTC
### Description
 Google hangouts won't send and upload messages to the server, but incoming messages can be displayed from server.

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by srirambv** [comment] 2017-11-16 08:10
Please provide steps to reproduce the issue

**Comment by qippur** [comment] 2017-11-20 13:43
Here are mine.

Other settings: fingerprinting protection enabled (disabled for gmail - see screenshot), italian adblock list enabled.

Regards

--

<img width="499" alt="screen shot 2017-11-20 at 14 39 39" src="https://user-images.githubusercontent.com/11455441/33021130-085eac70-ce01-11e7-868a-b278678f9bef.png">

**Comment by hugobuddel** [comment] 2017-11-21 15:32
You need to allow 3rd party cookies, then hangouts works fine, see #10862.

A simple search for 'hangouts' in the issues would have shown this.

**Comment by qippur** [comment] 2017-11-21 15:40
well... hangouts not working took me to where i posted my settings. Not so
obvious.
But it's fine as there is a workaroud.

--



On Tue, Nov 21, 2017 at 4:32 PM, Hugo Buddelmeijer <notifications@github.com

**Comment by bsclifton** [comment] 2017-11-28 08:33
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/10862

**Closed by bsclifton** 2017-11-28 08:33 UTC
Labels: needs-info, webcompat
