### ISSUE TITLE
Replace input and select elements with <FormTextbox> and <FormDropdown> in .bookmarkFormTable

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6777] opened 2017-01-20 10:09 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Bookmark hanger items are not properly aligned & text looks blurry

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	fefd17c

## Steps to reproduce:
    1. Visit any site
    2. Use keyboard shortcut to add bookmark / click on the bookmark button to add
    3. The element alignment is off
    4. Text on the bookmark mark hanger looks blurry 
    
- Actual result:
Drop down list is left aligned with the title whereas Title & location text and input element is not aligned with the heading. Text on the bookmark hanger looks blurry with system DPI set at 125%

- Expected result:
All elements should be properly aligned and text on the bookmark hanger should not look blurry

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/22144868/17598f3c-def7-11e6-8415-7cd1b56d2731.png)

  Text compared to the tab looks blurry
  ![image](https://cloud.githubusercontent.com/assets/17010094/22144967/6720fc08-def7-11e6-922c-ebaee1aeef5b.png)

- Any related issues:

## Test plan

https://github.com/brave/browser-laptop/pull/6947#issue-204375502

**Comment by luixxiul** [comment] 2017-01-20 10:30
I think this will be fixed with https://github.com/brave/browser-laptop/pull/6689

CC @bsclifton for a comment

**Comment by bsclifton** [comment] 2017-01-20 17:54
@luixxiul that is correct :smile: I also believe this will be fixed when we find the root cause / close out https://github.com/brave/browser-laptop/issues/6462 and https://github.com/brave/browser-laptop/issues/6698

See the image at https://github.com/brave/browser-laptop/issues/6462#issuecomment-269812168 for another example of text going from crisp to blurry

**Comment by luixxiul** [comment] 2017-02-04 06:28
Bookmark hanger items are still not properly aligned.

It seems that #6084 did not include the fix under https://github.com/brave/browser-laptop/pull/6084/commits/fd0c10af0de5e76fb4bbe803a907f168ba4414d2#diff-57a5fbf005ecc202d1e7e08c11f73b93R58 for the bookmark hanger, which should have been like this: https://github.com/brave/browser-laptop/pull/6084#issuecomment-266302675

**Comment by luixxiul** [comment] 2017-02-04 06:29
The issue was reopened and renamed as the text blurry issue was fixed.

**Comment by Liunkae** [comment] 2017-03-04 06:26
The UI controls in the bookmark popup look very different from the UI controls elsewhere (e.g. preferences):
![image](https://cloud.githubusercontent.com/assets/19424103/23576663/1bed03f8-0071-11e7-941a-bb9d31d37b97.png)
![image](https://cloud.githubusercontent.com/assets/19424103/23576664/21342b02-0071-11e7-9fa5-89fd281e04d4.png)

**Comment by luixxiul** [comment] 2017-03-04 09:05
@Liunkae I am sorry if it was not obvious but that is actually what I wanted to make clear on https://github.com/brave/browser-laptop/issues/6777#issuecomment-277423095

**Comment by luixxiul** [comment] 2017-04-26 07:09
Fixed with https://github.com/brave/browser-laptop/pull/8443 (https://github.com/brave/browser-laptop/pull/8136)

**Closed by luixxiul** 2017-04-26 07:09 UTC
Labels: bug/dpi, QA/steps-specified, refactoring/aphrodite, release-notes/include
