### ISSUE TITLE
Regression : Flash plugin not loading after authorized to run

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3906] opened 2016-09-12 05:52 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
After authorizing the Flash plugin, it did not load.

**Expected behavior:**
The plugin should work and display content appropriately.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X and Windows 7 x64. Only found the issue on Windows x64

- Brave Version:
0.12.1 Preview1 & 0.12.1 Preview3

- Steps to reproduce:
    1. Visit a site with Flash (ex: http://homestarrunner.com/)
    2. Authorize Flash

- Screenshot if needed:
![flash_authorized_issue](https://cloud.githubusercontent.com/assets/1434040/18425944/209ab11e-7883-11e6-9350-d11876a69776.gif)

- Any related issues:

**Comment by srirambv** [comment] 2016-09-12 14:53
Verified with 0.12.1 Dev Preview 3 build. Flash content doesn't load on Windows 10 x64

**Comment by diracdeltas** [comment] 2016-09-12 23:15
caused by the same issue as https://github.com/brave/browser-laptop/issues/3878, so i'm marking as a dupe

**Closed** 2016-09-12 23:15 UTC
Labels: duplicate
