### ISSUE TITLE
I can't set up my homepage

### ISSUE THREAD

**Issue by takujun** [brave/browser-laptop#6096] opened 2016-12-08 19:04 UTC
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by takujun** [comment] 2016-12-08 19:10
All sudden  , today 12/8/16 My home page that I was set up didn't work .
Instead when I open Brave,it goes Brave.exe on file library and make me choosing save file.
Even I did do again that I'd like to set my homepage address for copy /paste to address bar for set up  .

**Comment by bradleyrichter** [comment] 2016-12-08 20:01
@takujun Can you please share your brave version and OS?

**Comment by takujun** [comment] 2016-12-08 20:09
Thank you .
This is my Brave version and OS . I hope this is.  

Brave	0.12.13
os.arch	x64
os.platform	win32
os.release	6.1.7601

**Comment by bradleyrichter** [comment] 2016-12-08 20:11
baton pass to: @alexwykoff

**Comment by takujun** [comment] 2016-12-08 20:16
So, this person tell me that solution ?

**Comment by josiah-keller** [comment] 2016-12-08 20:17
This sounds like a duplicate of #6075

**Comment by bradleyrichter** [comment] 2016-12-08 20:21
@takujun Sorry to be vague. CC'd Alex to monitor with a support ticket. 

Sounds like we have a deeper issue based on #6075

**Comment by bsclifton** [comment] 2016-12-08 20:41
Let's track this with https://github.com/brave/browser-laptop/issues/6075 :smile: Closing this issue

**Closed** 2016-12-08 20:40 UTC
Labels: duplicate

**Comment by takujun** [comment] 2016-12-08 20:53
Thank you .

I fixed that. I just left comment on #6075.




Yuriko


________________________________
$B:9=P?M(B: Brian Clifton <notifications@github.com>
$BAw?.F|;~(B: 2016$BG/(B12$B7n(B8$BF|(B 12:41
$B08@h(B: brave/browser-laptop
CC: takujun; Mention
$B7oL>(B: Re: [brave/browser-laptop] I can't set up my homepage (#6096)


Let's track this with #6075<https://github.com/brave/browser-laptop/issues/6075> ?? Closing this issue

-
