### ISSUE TITLE
how to run it on debian?

### ISSUE THREAD

**Issue by Zeipt** [brave/browser-laptop#212] opened 2016-01-20 22:52 UTC
npm run watch gives
...
"webpack: bundle is now VALID."
and notification with "Brave undefined. Build success." And nothing happens..

npm start gives
npm start

> brave@0.7.7 start /home/zeipt/reps/browser-laptop
> node ./tools/start.js --debug=5858 -enable-logging --v=0 --enable-dcheck

electron "/home/zeipt/reps/browser-laptop" --debug=5858
Error opening app
The app provided is not a valid Electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/v0.36.2/docs

Error: Cannot find module '/home/zeipt/reps/browser-laptop/node_modules/sqlite3/lib/binding/node-v47-linux-x64/node_sqlite3.node'

May be this b/c of Node version? Installed 4.2.4

**Comment by diracdeltas** [comment] 2016-01-20 23:24
Yep, pretty sure this is a duplicate of #209. This might do the trick: https://github.com/brave/browser-laptop/issues/209#issuecomment-173369741

**Closed** 2016-01-20 23:31 UTC
Labels: duplicate
