### ISSUE TITLE
no tab close icon is shown for the active tab on Windows

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#10123] opened 2017-07-25 16:19 UTC
Active tab should show close icon always on hover for default tabs and always visible for small tabs.

Reported by @bbondy and seems like a DPI issue/Windows specific. May be related to #9779 and across platforms. Moving both to 0.18.x as this makes tabs almost unusable.

**Comment by bbondy** [comment] 2017-07-25 17:40
I think it will be fixed by the same fix as https://github.com/brave/browser-laptop/issues/9872 and that fix will also help some users that have tear off sensitivity problems.

**Comment by bsclifton** [comment] 2017-08-16 16:46
@bbondy is there a specific DPI you're using for this? I'm not able to reproduce the issue at 125% (maybe I'm not doing the correct steps).

What I'm trying:
- Tab page size is set to 20
- I open lots of tabs
- switch back to tab page 1
- resize the window to be super small

This is using 0.19.x and Muon 4.4.x

**Comment by bbondy** [comment] 2017-08-18 12:07
I see this on my surface book and desktop which are both set to 150% DPI

**Comment by bsclifton** [comment] 2017-08-18 18:30
OK reproduced 😄   Here are the steps!
1. Set tab page to 20
2. Maximize window
3. Create enough tabs that you get a second page (21 tabs)
4. switch back to tab page 1
5. click one of the tabs to make it the active tab
6. Hover over the other tabs and notice there is no X button
7. Close a few tabs- enough that you see the tab breakpoint size change
8. Hover over tabs and X now shows again

**Comment by cezaraugusto** [comment] 2017-08-20 06:56
after above comment this seems related to tab breakpoints so I'm taking this one

**Comment by jenn-rhim** [comment] 2017-09-12 18:04
It happens consistently once the tab count reaches to 16 on my **Mac laptop (osX 10.12.6)**.

![screen shot 2017-09-12 at 11 02 40 am](https://user-images.githubusercontent.com/4369856/30341223-1afee990-97aa-11e7-9c74-f73df6b57008.png)

**Closed** 2017-09-21 08:06 UTC
Labels: feature/tabsbar, OS/Windows, sprint/1
