### ISSUE TITLE
If state contains a [null] key, all actions will fail with little log evidence

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#13239] opened 2018-02-21 21:46 UTC
### Description
It's possible, although undesired, to have a javascript object or Immutable Map with a key of [null]. This causes immutabediff to throw an error as it only supports strings as keys. This then further causes all subsequent state updates to not be sent to renderer windows, and a crash log to be generated upon every single action, which halts the browser momentarily.

One instance of this was caught and fixed in #13234, but there could be more, and if there are, we should log and report something more helpful, such as the exact key path where a null key was found.

**Comment by bsclifton** [comment] 2018-02-22 05:58
Marking as `QA/no-qa-needed` since there isn't a clear way to reproduce this condition; however, @petemill gives steps to force it to happen, which the reviewers can do 😄

**Closed** 2018-02-23 06:43 UTC
Labels: QA/no-qa-needed, initiative/reduce-bugs, release-notes/include
