### ISSUE TITLE
Move noscript into the URL bar

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#5792] opened 2016-11-22 15:10 UTC
Red square highlighted below is not draggable because of the no-script icon (even if it's not shown)
![image](https://cloud.githubusercontent.com/assets/13509546/20528857/aa9d56be-b082-11e6-9b56-b6896adc154f.png)

It should be moved into the URL bar

## Test plan

1. Make sure the non-draggable area specified in #5792 is draggable
2. Make sure every button on the navigation bar is clickable
3. Open https://jsfiddle.net/
4. Block scripts from the top right lion icon
5. Make sure the noScript button on the navigation bar is clickable

**Comment by bradleyrichter** [comment] 2016-11-22 22:32
This is only present on new-tab and brave about:pages.

**Comment by Liunkae** [comment] 2016-11-22 22:58
It's an empty browser button:
`<div class="endButtons">`
`  <span class="browserButton"></span>`
`</div>`
It exists on all pages, but it only becomes larger when on about: pages. 😕

**Comment by bbondy** [comment] 2016-12-01 17:03
@bsclifton I think you added that button previously, (not sure sorry if not!! :)) could you take a look?

**Comment by luixxiul** [comment] 2016-12-01 17:08
it contains `noscript` button.

**Comment by bradleyrichter** [comment] 2016-12-01 17:22
@bsclifton we need to move this button inside the URL bar and use the new icon from the PNG sprite.

**Comment by bsclifton** [comment] 2016-12-03 09:53
Moving this to 0.13.1 (which is where the sprite issue currently is)

**Comment by bbondy** [comment] 2016-12-21 15:38
@luixxiul could you verify if this works now? If so pls move to 0.13.0 and close.

**Comment by luixxiul** [comment] 2016-12-21 15:47
I thought it cannot be closed yet (as the empty browserButton issue @Liunkae mentioned above is not resolved) / cc: @bsclifton for a comment

**Comment by Liunkae** [comment] 2016-12-21 18:40
The empty button still exists, but the zone can now be dragged.

**Comment by luixxiul** [comment] 2017-01-16 18:22
Test plan:

Make sure the non-draggable area specified in the 1st post is draggable

**Comment by srirambv** [comment] 2017-01-20 15:56
Still an issue with 0.13.0 RC1 
![5792](https://cloud.githubusercontent.com/assets/17010094/22155890/f765df14-df28-11e6-98d3-bd2f99b90854.gif)

@bbondy should this be moved to 0.13.1 ?

**Comment by luixxiul** [comment] 2017-01-20 16:05
I found the cause. I'll fix it quite soon

**Comment by luixxiul** [comment] 2017-01-20 17:11
This is the more complex issue than it seemed to me at first. I think it would be better to fix this by including `.endButtons` inside the URL bar.

**Closed** 2017-04-11 22:01 UTC
Labels: bug, feature/URLbar, QA/steps-specified, release-notes/include
