### ISSUE TITLE
"Pin" & "Delete" buttons are not being aligned when long YT entries are added

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11978] opened 2017-11-15 18:32 UTC
### Description

When long YT entries are added into the ledger, both the "Pin" and "Delete" buttons won't align correctly and will appear on two separate lines. This makes it very difficult to click on either the "Pin" or "Delete" buttons for websites that are in the middle of the ledger... It takes a few seconds to make sure you're correctly clicking on the correct button... This is definitely a usability regression and makes the ledger a lot harder to use/manage.

### Steps to Reproduce

  1. launch brave and create/enable a wallet
  2. visit several websites so they appear in the ledger
  3. watch a clip from https://www.youtube.com/user/TheLateLateShow
  4. take a look at the ledger table and you'll notice the alignment issues

**Actual result:**

<img width="454" alt="screen shot 2017-11-15 at 1 09 27 pm" src="https://user-images.githubusercontent.com/2602313/32853252-aafde38a-ca08-11e7-9864-b0f32b2c2806.png">

Both the "Pin" & "Delete" buttons are not being aligned and are being displayed on separate lines

**Expected result:**

Both the "Pin" & "Delete" buttons should be correctly aligned and appear in a single line

**Reproduces how often:**

100% reproducible using the above STR

### Brave Version

**about:brave info:**

> Brave: 0.19.93 
> rev: 25085d0b5a0a6cf8a740cac8b246ebf1a97146f7 
> Muon: 4.5.16 
> libchromiumcontent: 62.0.3202.94 

**Reproducible on current live release:**

Nope, the YT feature isn't present within `0.19.88`

### Additional Information

Related Bug: https://github.com/brave/browser-laptop/issues/11960

**Comment by kjozwiak** [comment] 2017-11-15 18:39
@srirambv checked Russian and the ledger table looks great:

![image](https://user-images.githubusercontent.com/2602313/32853765-4df35ccc-ca0a-11e7-9160-ceeed8eb4ee7.png)

We should make sure that English looks like the above table as it's probably the main language being used right now...

**Comment by bsclifton** [comment] 2017-11-15 20:43
Fixed with https://github.com/brave/browser-laptop/commit/22c2aee81d11fb2ddb77cc237c3953632ffe2e39

@luixxiul can you help me confirm that this is NOT needed on 0.20, 0.21, and master? I manually tested and I believe the change is only needed for 0.19.x

**Closed by bsclifton** 2017-11-15 20:43 UTC
Labels: 0.19.x, bug, feature/ledger

**Comment by luixxiul** [comment] 2017-11-16 14:12
If you could not reproduce the issue on those branches, I assume refactoring works on sortableTable have taken care of it.
