### ISSUE TITLE
Many tabs open, set to open tabs from where I left off, close and reopen, tabs don't load automatically

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#10818] opened 2017-09-06 09:13 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
If I have any number of tabs open, set to open tabs from where I left off, close and reopen, only the last active tab opens automatically, while the other tabs don't load automatically. (The tab title shows the URL, then when you hover over it or click on it, the tab begins to load).

Brave: 0.18.23 
rev: 36ae2ec06efed0057ae16351108bf4d4c10a7ab4 
Muon: 4.3.10 
libchromiumcontent: 60.0.3112.90 
V8: 6.0.286.52 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Linux 
OS Release: 4.10.0-33-generic 
OS Architecture: x64

- Steps to reproduce:
    1. Open any number of tabs in a window (on any OS: I've experienced this on Win 10 and Ubuntu 16.04 LTS), with the window set to open from where I left off, and with no other windows open.
    2. Close and reopen the window.

- Actual result:
The last active tab from the last session automatically loads, while the other tabs don't. Instead, they show the favicon and the URL. You have to hover over them or click on them to load the tabs, which causes the tab name to change from the URL to the page title, and clicking on the tab causes it to initially show a blank screen, then load the page.
- Expected result:
All tabs automatically load.
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
As above, you need to set the window to open from where I left off (I haven't tried opening a specific set of pages).
- Is this an issue in the currently released version?
Yes.
- Can this issue be consistently reproduced?
It seems so, on two computers with different OSs. I will upload the results from the other work computer on Monday when I am next at the Sungrow office.
- Extra QA steps:
None that come to mind.

- Screenshot if needed: N/A

- Any related issues:
What is likely to be related and a worse issue that occurred on the same day is that all other tabs do not respond when I try to open them, needing to close and reopen to be able to open the tabs, which occurred several times today at work. This issue occurred with about ten tabs open, while it seems that the frequency that the issue occurs is proportional to the number of tabs open. However, I frequently use multiple pages over a work day, so it's more convenient to leave them open. This related issue is a critical issue that is a bit of a deal-breaker to using Brave—it is manageable, but something that I prefer not to frequently experience.

**Comment by Samuel0Paul** [comment] 2017-09-08 02:34
Duplicate of #10806

**Comment by Samuel0Paul** [comment] 2017-09-08 02:36
Duplicate of #10806

**Comment by bsclifton** [comment] 2017-09-08 04:59
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/10806

**Closed by bsclifton** 2017-09-08 04:59 UTC
