### ISSUE TITLE
Reopening last closed tab or window does not retain back/forward ability

### ISSUE THREAD

**Issue by chrisbarber** [brave/browser-laptop#12890] opened 2018-01-28 18:16 UTC
### Description

Reopening a tab via Ctrl/Cmd+Shift+T does not retain that tab's local history. That is, the "History" contains the pages as expected, but the tab loses its back/fwd history. The same applies for reopening a closed window.

### Steps to Reproduce

  1. Open a new tab (or window)
  2. Navigate a few links
  3. Optionally use back and forward buttons
  4. Close tab
  5. History > Reopen Last Closed Tab (or Window)

**Actual result:**

Back/fwd buttons grayed out.

**Expected result:**

Back/fwd state restored to when the tab/window was closed.

**Reproduces how often:**

Always.

### Brave Version

**about:brave info:**

 
Brave: 0.19.147 
rev: f1b90a31643cad8f4d76a4f729939d4f303b9a00 
Muon: 4.7.6 
libchromiumcontent: 64.0.3282.119 
V8: 6.4.388.40 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Reproducible on current live release:**

**Comment by srirambv** [comment] 2018-01-29 02:52
Duplicate of #2702

**Closed by srirambv** 2018-01-29 02:52 UTC
