### ISSUE TITLE
Extension widgets not shown on the menu

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12340] opened 2017-12-20 14:42 UTC
### Description
Extension widgets not shown on the menu bar

### Steps to Reproduce

  1. Clean install 0.20.7 
  2. Enable any extension from `about:preferences#extensions`
  3. No visible widget on the menu bar

**Actual result:**
![extension_widget](https://user-images.githubusercontent.com/17010094/34212244-aac1f266-e593-11e7-9f66-7f754451b510.gif)

**Expected result:**
Should show widget when the extension is enabled

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.7
-- | --
V8 | 6.2.414.42
rev | a2ba3e8
Muon | 4.5.16
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 62.0.3202.94

**Reproducible on current live release:**
No

**Comment by LaurenWags** [comment] 2017-12-20 17:54
Reproduced on MacOS:
Brave | 0.20.8
V8 | 6.3.292.48
rev | 015a3db
Muon | 4.5.28

**Comment by bsclifton** [comment] 2017-12-22 18:15
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/11142

**Closed by bsclifton** 2017-12-22 18:15 UTC
Labels: 0.20.x, bug, feature/extensions, priority/P2, regression, release/blocking
