### ISSUE TITLE
Brave doesn't display Slideshare slides (but does show thumbs)

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#674] opened 2016-02-09 03:03 UTC
http://www.slideshare.net/Sky7777/the-best-startup-pitch-deck-how-to-present-to-angels-v-cs

Doesn't seem to be a flash object?

**Comment by psimyn** [comment] 2016-02-09 09:04
Working for me

![screen shot 2016-02-09 at 20 03 27](https://cloud.githubusercontent.com/assets/1731922/12911674/3f658b24-cf68-11e5-9db4-986f4a281977.png)

**Comment by bridiver** [comment] 2016-02-09 16:34
working for me as well

**Comment by bbondy** [comment] 2016-02-09 16:52
ditto, works for me.
@bradleyrichter is this consistently failing for you?

**Comment by bradleyrichter** [comment] 2016-02-09 17:30
They work fine in electron but not brave. Perhaps its a strange conflict of running both?

![screen shot 2016-02-09 at 9 28 51 am](https://cloud.githubusercontent.com/assets/13509546/12924579/b0e76d02-cf0f-11e5-84cc-4e332b39b014.png)

**Comment by bbondy** [comment] 2016-02-09 18:01
Maybe  your data file is corrupted so it's blocking things it shouldn't be. Please try closing Brave and then do this in a terminal:
`rm -f ~/Library/Application\\ Support/Brave/ABPFilterParserData.dat`
`rm -f ~/Library/Application\\ Support/Brave/TrackingProtection.dat`

Then restart the browser and try to reproduce again. If it doesn't work I'll post for better handling / detection of a corrupted data file.

**Comment by luixxiul** [comment] 2016-05-13 10:02
@bradleyrichter how about with the latest version?

**Comment by luixxiul** [comment] 2017-09-13 09:53
Closing as it works.

**Closed by luixxiul** 2017-09-13 09:53 UTC
