### ISSUE TITLE
Unable to disable Google Widevine Support

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5535] opened 2016-11-10 12:24 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Unable to disable Google Widevine extension

**Expected behavior:**
Should be able to disable Google Widevine extension

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 x64

- Brave Version: 0.12.9 Preview 1

- Steps to reproduce:
    1. Do a clean install of 0.12.9 Preview 1 build
    2. Go to settings and enable Google Widevine support extension
    3. Try to disable, doesn't disable console throws error

- Screenshot if needed:
![widevine](https://cloud.githubusercontent.com/assets/17010094/20176586/6230aa02-a740-11e6-8571-a35a882774f6.gif)

- Any related issues:
#5509 
 cc: @bbondy

**Comment by bbondy** [comment] 2016-11-11 15:08
I think this is a dupe of:
https://github.com/brave/browser-laptop/issues/5563

Please re-open after the next preview build (or RC) if it is not. 
I'll keep the milestone set so it goes through testing.

**Closed by bbondy** 2016-11-11 15:08 UTC
Labels: feature/extensions, release/blocking
