### ISSUE TITLE
Network requests from a script on a different domain have an incorrect referrer header

### ISSUE THREAD

**Issue by countingtoten** [brave/browser-laptop#3067] opened 2016-08-09 21:36 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When making an ajax request from a script with a different hostname than the current website, the Referer header has the script's url instead of the site's url. This only happens when visiting the https version of the site.

**Expected behavior:**
Visit website
Make ajax request from a script whose origin is a different domain than the website
Respond with html content whose links should contain the referrer's url
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10, macOS
- Brave Version:
  0.11.3
- Steps to reproduce:
  I fixed this in our website. I'll make an example project tomorrow that you can test.

**Comment by bbondy** [comment] 2016-08-10 01:05
I believe we do this on purpose for extra privacy. CC @diracdeltas
Not sure why it is only for https  though.

**Comment by diracdeltas** [comment] 2016-08-10 14:28
We spoof cross-origin referer when '3rd party cookie block' is on. It should happen on both http and https though.

**Comment by diracdeltas** [comment] 2017-05-17 22:25
Closing since it is expected behavior.

**Closed by diracdeltas** 2017-05-17 22:25 UTC
