### ISSUE TITLE
Takes too long to load

### ISSUE THREAD

**Issue by QuickWhitt7** [brave/browser-laptop#7696] opened 2017-03-14 03:01 UTC
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Brave takes a little over 4 seconds to even get the window up. My computer is an HP Pavilion 500-223w with 8 GB of RAM and a 3.4GHz processor.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Both computers run Windows 10
- Brave Version (revision SHA):
Brave 0.13.5
- Steps to reproduce:
    1. Double-click the icon
    2. Wait for the window to pop up
    
- Actual result:
Took 4 seconds to load the window
- Expected result:
Takes less than a second to load and bring up my home page
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Probably not. My guess is that Brave was not tested on certain hardware environments.
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Probably.

**Comment by Liunkae** [comment] 2017-03-14 05:00
@TheFallenOneGOTH How does Brave's performance compare to other browsers on your system?

**Comment by TheFallenOneGOTH** [comment] 2017-03-14 08:01
Google Chrome loads faster than Brave does, if that's any help.

**Comment by bsclifton** [comment] 2018-08-25 07:09
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/3025

**Closed by bsclifton** 2018-08-25 07:09 UTC
Labels: bug, perf
