### ISSUE TITLE
Scrolling fails on http://urbanologymag.com/

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13439] opened 2018-03-14 10:47 UTC
### Description
Reported in community 
Scrolling fails on http://urbanologymag.com/

### Steps to Reproduce

  1. Visit http://urbanologymag.com/gavin-sheppard-the-remix-project/
  2. Two finger scroll doesn't work
  3. Mouse wheel scroll doesn't work

**Actual result:**
Scrolling fails on http://urbanologymag.com/

**Expected result:**
Should be able to scroll

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
Brave: 0.21.18
V8: 6.4.388.41
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89
Muon: 4.8.2
OS Release: 17.4.0
Update Channel: Release
OS Architecture: x64
OS Platform: macOS
Node.js: 7.9.0
Brave Sync: v1.4.2
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:**
Yes

### Additional Information
https://community.brave.com/t/brave-incompatiblity-for-creative-magazine-site-urbanology-com/17699

**Comment by jasonrsadler** [comment] 2018-03-23 01:58
Does not scroll on chrome either

**Comment by snyderp** [comment] 2018-10-01 04:44
not able to reproduce in beta

**Comment by Ikinique** [comment] 2018-10-05 20:12
Def only works on Safari but not on Chrome or Brave browser.

**Comment by bsclifton** [comment] 2018-10-09 06:00
Closing as fixed-with-brave-core

You can grab a copy here (latest at this moment is Beta channel):
https://brave.com/download-beta

**Closed by bsclifton** 2018-10-09 06:00 UTC
Labels: bug, webcompat
