### ISSUE TITLE
Menu should not be activated with ALT key

### ISSUE THREAD

**Issue by Superbest** [brave/browser-laptop#5775] opened 2016-11-21 19:21 UTC
## Original issue description
**Did you search for similar issues before submitting this one?**
Tried looking for "Alt D new tab" but got nothing relevant.

**Describe the issue you encountered:**
I open Brave with one blank tab. I want to go to `www.example.com`. I press Alt+D to focus URL bar (as in  many other browsers). I type "www.example.com", press enter. The site URL opens as expected, but Brave immediately opens a new tab and focuses it. I then have to close this new tab to view the site I just opened.

The problem is not due to Alt+D but specifically due to Alt which focuses the menu bar. Pressing Alt makes the menu bar visible, if enter is pressed while it is visible a new tab will be opened. It can be avoided by pressing Esc after Alt+D but before pressing enter, this de-focuses the menu bar (it remains visible) and prevents the unexpected tab opening.

**Expected behavior:**
I expect the browse to behave the same as if I clicked the URL bar instead of used Alt+D - no new tab opened.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Happens on both Windows 7 and Arch Linux.

- Brave Version:
Confirmed on 0.12.9-10 but happened on a few other versions (can't recall exactly which now). I think it's a 0.12.* issue. This bug wouldn't happen in older versions, at least as far back as 0.9, and since I only noticed it recently I don't think it happened in 0.11.*.

- Steps to reproduce:
    1. Open Brave.
    2. Press Alt+D to focus URL bar.
    3. Type in address (or just leave whatever is there).
    4. Press enter.
    5. New tab opens.

Alternatively:
    1. Click URL bar and type something.
    2. While URL bar still has focus press Alt, bringing up the menu.
    3. Press Enter.
    4. New tab opens. If before Enter you press Escape, it won't.

**Comment by Liunkae** [comment] 2016-11-21 19:55
Possibly related to #5540.

As a workaround, you can use the shortcut <kbd>Ctrl+L</kbd> instead.

**Comment by JAffleck** [comment] 2016-11-27 00:17
I noticed the same behavior as alt+d opening a new tab by doing ctrl + enter to add the '.com' to the end of an address.  
The .com is added, but then another tab is created.

**Comment by Superbest** [comment] 2016-12-01 00:25
@Liunkae `Ctrl+L` does not have the problem for me as well. I had noticed that also, but forgot to put in original post.

Also, yes, related to #5540 but don't think it's quite the same thing. Incidentally, I cannot reproduce #5540 (see that thread) but can reproduce #5775 on Brave 0.12.10.

@JAffleck I had noticed that as well. I think the culprit is solely the `Alt` issue I describe. If you use my or @Liunkae 's workaround before pressing `Ctrl+Enter` then everything works as expected.

**Comment by JAffleck** [comment] 2016-12-01 02:30
Thanks @Liunkae! I'll do that until I see it fixed

**Comment by bsclifton** [comment] 2016-12-03 22:45
+1 from Twitter:
https://twitter.com/brave/status/799358465428713472

**Comment by bsclifton** [comment] 2016-12-03 22:46
Another +1 involving menu bar antics from Twitter:
https://twitter.com/BrendanEich/status/804429129751752704

**Comment by bsclifton** [comment] 2017-02-22 06:30
+1 with https://github.com/brave/browser-laptop/issues/7323
> the menu shows up when I simply Alt+Left/Right to navigate to Next/Prev pages or Shift+Alt to switch kbd layout.

**Comment by valtih1978** [comment] 2017-02-28 08:44
I wonder why you leave this narrow issue open while closing the general one? The problem is that Alt activates the main menu and this causes all kinds of problems, including Alt+Left/Right to navigate, Shift+Alt to switch the language, Alt+D to enter the URL and got knows what. This makes Brave absolutely unusable. Why do you close the general issue #7323 yet leave Alt+D issue open? This is very unscientific to specialize on narrow symptom instead of curing the root.

**Comment by bsclifton** [comment] 2017-02-28 08:51
@valtih1978 you are correct- I apologize for not renaming the issue.  I intended for this issue here to be a catch-all for "ALT showing menubar on Windows" issues.  Several use cases are captured above, I had forgotten to rename the issue

**Comment by bsclifton** [comment] 2017-03-04 00:44
Got a PR up for the issue! Thanks for all the great information, folks 😄 

My fix will only work on Windows.  For linux, we have a separate issue captured here:
https://github.com/brave/browser-laptop/issues/5540

**Comment by bsclifton** [comment] 2017-03-14 21:44
[After restoring the shortcuts](https://github.com/brave/browser-laptop/commit/5a889ccd6198906537f0c29d4b28067292a4ef78), I realized this fix didn't completely fix the issue. Re-opening...

**Comment by Tenvolin** [comment] 2017-05-16 18:37
I'm on Windows 10, using the (x64) version 0.15.2 and can reproduce this ALT key issue.
Pressing down ALT + d still activates the menu and makes browsing a little annoying when entering search terms or new addresses.

**Comment by stonysam** [comment] 2017-08-14 07:27
I confirm this issue is still happening for me on Windows 10 (x64) on version 0.18.14 and is quite annoying.

**Comment by luixxiul** [comment] 2017-09-25 06:16
Added the issue to the milestone in case.

**Comment by orschiro** [comment] 2017-09-25 07:55
I would suggest a setting by which the user can enable or disable the Alt menu key trigger.

**Comment by eljuno** [comment] 2017-09-25 18:28
+1 from community https://community.brave.com/t/tabs-getting-dragged-when-switching-tabs-with-mouse-clicks-also-alt-d-opens-up-the-menu-after-going-to-the-address-bar/8151/3?u=eljuno

>when pressing alt+d, it goes to the address bar but it also somehow opens the menus, (tried it on another browser it just direct me to the address bar everything seems normal)

Windows 8.1

Brave: 0.18.36
rev: 7ab85e97318fef041433b0c3d73b457205fae805
Muon: 4.3.22
libchromiumcontent: 61.0.3163.79
V8: 6.1.534.32
Node.js: 7.9.0
Update Channel: dev
OS Platform: Microsoft Windows
OS Release: 6.3.9600
OS Architecture: x64

**Comment by grand-lotus-iroh** [comment] 2018-02-21 05:12
(L) ALT + D = broken
(R) ALT + D = works

https://streamable.com/r3hqq

I do not wish to use CTRL+L or F6.

---

Windows 10
Latest Brave

**Comment by nashuatek** [comment] 2018-03-30 09:34
For me ALT+D is something I've trained by Chrome and makes sense when my right hand is on the mouse. While CTRL+L works it requires taking hand off the mouse and while doesn't impact functionality, does impact usability.

**Comment by eljuno** [comment] 2018-05-18 18:19
+1 from community https://community.brave.com/t/alt-d-on-windows-user-experience/22279?u=eljuno

> The Alt+d keyboard shortcut is useful for putting your cursor in the Address bar & highlighting the text. This works, but it also causes the file menu to appear on the browser.

**Comment by tanev** [comment] 2018-07-25 08:29
+1 here as well - with dual keyboard layouts, one would need to switch to a different layout frequently in different tabs. Triggering the menu bar on `ALT+SHIFT` now requires an additional `ALT` keypress afterwards to hide the menu bar.

**Comment by msherman64** [comment] 2018-08-02 17:02
+1 here, still happening on version 0.23.73 with windows 10 Version 10.0.17134 Build 17134. Issue is with alt+d combo, alt+arrows seem to work.

**Comment by bsclifton** [comment] 2018-08-13 20:43
I know this isn't the best news, but I don't think we'll fix this with `browser-laptop`. We're shifting development efforts towards [brave-core](https://github.com/brave/brave-browser) where this is already solved (since there is no menu on Windows)

For those interested, it's still in an experimental stage, [but there are builds available](https://github.com/brave/brave-browser/releases) in case you'd like to preview what's coming soon

**Closed by bsclifton** 2018-08-13 20:43 UTC
Labels: OS/Windows, bug, feature/keyboard-shortcuts, fixed-with-brave-core, priority/P3, product/user-happiness, regression, windows-important, wontfix

**Comment by JonathanDavidArndt** [comment] 2018-09-29 17:09
This is still an issue in Brave 0.23.105 for Windows 7
