### ISSUE TITLE
Overdue payments and incorrect backup key

### ISSUE THREAD

**Issue by MatthewDLudwig** [brave/browser-laptop#12538] opened 2018-01-07 06:37 UTC
I am the owner of a Brave wallet that has transitioned from the original BTC wallet as well as taken money from the UGP.  Originally I was unable to take UGP or submit a payment, and upon checking my backup key saw it was incorrect.  I backed up the wallet manually from my original code and I was then able to take from UGP but the payment was no longer available.  The history showed no transaction and I was hoping to submit this month.

Currently my payment is overdue and my backup key is simply "a".  If there's anything I can do to help the team with this issue before backing up, I would like to do what I failed to do last time.  Also, if there's any way to still go through with my contribution rather than backing up and missing another month I would love to support the platform!

**Comment by MatthewDLudwig** [comment] 2018-01-07 06:40
For all current (and future) additional information:
Intel I5 CPU running Windows 10.

![brave key broken](https://user-images.githubusercontent.com/6557206/34647249-a955ad62-f34b-11e7-8bb1-0f036f93e28a.png)

**Comment by bsclifton** [comment] 2018-01-08 06:07
@MatthewDLudwig there is a known issue with restore (which we have fixed in an upcoming release, captured with https://github.com/brave/browser-laptop/issues/11383)

Do you still have your keywords saved? If so, our next version should have this fixed.  If not, do you have a backup of your `ledger-state.json` file?

I'll close this issue as a duplicate of  https://github.com/brave/browser-laptop/issues/11383 but I'd love to help you work through this.  Apologies that you ran into it ☹️

**Closed by bsclifton** 2018-01-08 06:07 UTC
