### ISSUE TITLE
Folder structure is not maintained on sync for imported data on both Pyramid 0 & Pyramid 1

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9174] opened 2017-05-31 11:39 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Imported data in not properly sync'd between Windows machines

- Platform (Win7, 8, 10? macOS? Linux distro?):
Pyramid 0 Windows 10 x64
Pyramid 1 Windows 7 ia32

- Brave Version (revision SHA):
Both running
```
Name	Version
Brave	0.15.312
rev	cc653ff
Muon	3.0.202
libchromiumcontent	58.0.3029.110
V8	5.8.283.38
Node.js	7.9.0
Update Channel	dev
os.platform	win32
os.release	6.1.7601
os.arch	ia32
```

- Steps to reproduce:
    1. Enable Sync on pyramid 0 and sync with pyramid 1 using secret code
    2. Import Chrome data on pyramid 0, shows folder `Imported from Chrome`
    3. After pyramid 1 sync's and receives data folder structure is lost on pyramid 1
    4. Pyramid 0 recreates the import data similar to pyramid 1 (due to #8508) 
    
- Actual result:
Folder structure is not maintained on sync for imported data on both Pyramid 0 & Pyramid 1

- Expected result:
Should retain folder structure

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Need to verify but could be a regressed issue

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
Pyramid 0 after sync 
![image](https://cloud.githubusercontent.com/assets/17010094/26630326/1ddfcd3a-45fe-11e7-898f-7bb6506eb60e.png)
Pyramid 1 after sync
![image](https://cloud.githubusercontent.com/assets/17010094/26630249/c9e34d06-45fd-11e7-8187-67b9c5051b12.png)

- Any related issues:

**Comment by bsclifton** [comment] 2017-05-31 22:17
Closing; this is a dupe of https://github.com/brave/browser-laptop/issues/8454

**Closed by bsclifton** 2017-05-31 22:17 UTC
Labels: bug, feature/sync, needs investigation, OS/Windows, QA/steps-specified
