### ISSUE TITLE
2 issues with native JavaScript dialogs on Windows

### ISSUE THREAD

**Issue by scunliffe** [brave/browser-laptop#549] opened 2016-02-02 01:11 UTC
I noticed (at least on Windows) that on the native JavaScript dialogs: alert(), confirm(), and prompt() that:

1. The title has "brave" in it vs. "Brave" (lowercase)
2. The prompt(msg, default) method appears to not be implemented... while not too comonly used these days, it will likely break any site  depending on it.

**Comment by luixxiul** [comment] 2016-05-15 00:51
Would you please create a test case for these or indicate an example URL? thanks.

**Comment by scunliffe** [comment] 2016-05-16 01:19
I've created a test case for alert, confirm, prompt, and print that exhibit the issues.

[jsDialogs.zip](https://github.com/brave/browser-laptop/files/265403/jsDialogs.zip)

**Comment by diracdeltas** [comment] 2016-05-18 01:30
prompt not implemented is duplicate of #94

**Comment by luixxiul** [comment] 2016-05-18 01:44
OK, thanks both of you

**Comment by cezaraugusto** [comment] 2016-06-16 14:53
Closed as duplicated.

**Closed by cezaraugusto** 2016-06-16 14:53 UTC
Labels: duplicate
