### ISSUE TITLE
payment history not viewable

### ISSUE THREAD

**Issue by msp1111111** [brave/browser-laptop#7650] opened 2017-03-10 22:24 UTC
Clicking on the pdf links in payment history flashes the history for a second, then disappears. It was working properly (opening a downloadable pdf in another tab) before the last payment on Feb. 28. I checked to see if it was a problem with the pdf reader, but other sites work fine.
0.13.4 and 0.13.5 
Windows 7 x64

**Comment by bsclifton** [comment] 2017-03-10 22:53
@msp1111111 thanks for the report! This was recently fixed and will be released in our next version

I'll go ahead and close this issue as a duplicate of https://github.com/brave/browser-laptop/issues/7416, but keep your eyes peeled over the next week for version 0.13.6

**Closed** 2017-03-10 22:53 UTC
Labels: duplicate, OS/Windows
