### ISSUE TITLE
Windows has odd display color for some users after updating to 0.23.73

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14894] opened 2018-08-01 15:29 UTC
### Description
Reported via community:
https://community.brave.com/t/upgraded-to-v0-23-73-and-brave-is-now-a-garish-yellow/28765
https://community.brave.com/t/odd-discoloration-on-windows-10-v1803-after-0-23-73-update/28766
https://community.brave.com/t/entire-window-has-orange-yellow-tint/28786

Some users are reporting that after updating to 0.23.73 on Windows Brave has an odd color in the URL bar/ bookmarks bar/ tool bar area.

### Steps to Reproduce

  1. Have 0.23.73
  2. Launch Brave
  3.

**Actual result:**
Some users are reporting an odd color in the URL bar, bookmarks bar, and tool bar area. A screenshot is in these posts:
https://community.brave.com/t/upgraded-to-v0-23-73-and-brave-is-now-a-garish-yellow/28765/11
https://community.brave.com/t/odd-discoloration-on-windows-10-v1803-after-0-23-73-update/28766

Also, here is a side by side of Chrome/Brave on the same page: https://community.brave.com/t/upgraded-to-v0-23-73-and-brave-is-now-a-garish-yellow/28765/13

**Expected result:**
No discoloration

**Reproduces how often:**
Unknown

### Brave Version

**about:brave info:**
0.23.73

**Reproducible on current live release:**
For some users, yes

### Additional Information
Only reported on Windows so far, @kjozwiak has not reproduced.

**Comment by btsfav** [comment] 2018-08-01 16:35
same bug as in chrome... I wonder if you test that stuff before you fork?

**Comment by Brave-Matt** [comment] 2018-08-01 17:29
+1 from Reddit: https://www.reddit.com/r/brave_browser/comments/93q4ud/is_there_a_reason_there_is_such_a_warmred_hue_to/

**Comment by bsclifton** [comment] 2018-08-01 18:10
Here's the fix I had identified before:
https://community.brave.com/t/colors-are-not-showing-correctly-how-can-i-fix-this/27401/2

Basically, forcing the color profile to be `srgb` via the command line param:
`--force-color-profile=srgb`

@btsfav can you please try this out? I am unsure why this would pop up all of the sudden for folks- the detection code has been there since Chromium 61 or so, IIRC

**Comment by jonathansampson** [comment] 2018-08-01 18:15
Others have reported similar issues with Google Chrome in the past, and found that disabling _hardware acceleration_ often resolved the issue.

**Comment by bsclifton** [comment] 2018-08-01 21:50
For folks experiencing this problem who are NOT resolved by the `--force-color-profile=srgb` work-around, can you please try the following?
- In Brave, load up `chrome://gpu/`
- In Chrome, load up `chrome://gpu/`
- Compare the two screens - look for any differences

I suspect that Muon is not running all of the code for detecting driver bug work-arounds (or similar) and that folks will see differences between the output in Brave and Chrome

Here's what the `chrome://gpu/` screen looks like (for those curious):
![screen shot 2018-08-01 at 2 46 41 pm](https://user-images.githubusercontent.com/4733304/43550997-457ce408-959a-11e8-9ed5-75148d053322.png)

**Comment by btsfav** [comment] 2018-08-02 16:02
in chorme color profile fixed it, DO NOT disable hardware acceleration

**Comment by bsclifton** [comment] 2018-08-09 20:30
Closing issue as `wontfix`. Chromium using your system's color profile (by default) is expected behavior and it does happen with Chrome also. We could force `srgb` or expose the setting in our preferences, but when discussing with the team, we didn't think those changes would be worthwhile, since [brave-core](https://github.com/brave/brave-browser) is around the corner

The above comments show a work-around to alter your color profile (forcing srgb) and [brave-core](https://github.com/brave/brave-browser) does support `chrome://flags/#force-color-profile`

**Closed by bsclifton** 2018-08-09 20:30 UTC
Labels: 0.23.x, OS/Windows, addressed-with-brave-core, bug, cr68, wontfix
