### ISSUE TITLE
When a site is pinned, the 'Include' toggle should be ON automatically simultaneously.

### ISSUE THREAD

**Issue by jenn-rhim** [brave/browser-laptop#11905] opened 2017-11-11 00:56 UTC
### Description

A site can be pinned in the Payments table of visited sites even if it's not included. Then the 'Include' should be turned on as the user pins the site.
### Steps to Reproduce

  1. Settings > Payments
  2. Select a site that has not been included
  3. Pin the site: it is pinned but not included.

**Actual result:**

Pinned but still indicated that the site is not included in the payment.

**Expected result:**
All pinned sites should be included: Pin to pay, not just pin to locate them at the top.

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

### Additional Information

![screen shot 2017-11-10 at 4 36 26 pm](https://user-images.githubusercontent.com/4369856/32684417-1fd5c58a-c638-11e7-817a-080f179fc1e0.png)

**Comment by NejcZdovc** [comment] 2017-11-11 04:57
@jenn-rhim not sure that I see from the print screen what the problem is. DDG (which is pinned) has include set to ON.

**Comment by jenn-rhim** [comment] 2017-11-11 05:32
@NejcZdovc I'm not sure if you're seeing the server data that is set to On, but on the UI, the toggle is off.  Attaching another one. Brave version: 0.19.88

![image](https://user-images.githubusercontent.com/4369856/32686669-92afca26-c65e-11e7-8d19-c220717e9736.png)

**Comment by NejcZdovc** [comment] 2017-11-11 07:51
@jenn-rhim this is not off, this is disabled state, so that users can't un-toggle (set to OFF) pinned items. At the bottom you can see OFF state where gray is more intense then for disabled state

**Comment by jenn-rhim** [comment] 2017-11-11 18:20
2 things:
1. Disabled state of 'ON' button should still be showing the color that means ON. That means dimmed orange. I didn't even realize that the toggle was to the right because it's totally gray, my eye follows the color rules.

2. But more fundamentally, I don't think this toggle should be disabled. This makes the UI inflexible and create extra steps if user wants to exclude the site: you'd need to first unpin and then turn off include. Keeping it enabled doesn't harm the system.  I'd propose our UI to be flexible and make it easy for user to follow their intent:
- keep the 'include' toggle enabled at all times
- if user pins the unincluded site, include it as well as pin it.
- if user exclude the pinned site, unpin it and exclude at the same time
- if user unpin the site, unpin and keep it include.

**Comment by NejcZdovc** [comment] 2018-02-19 06:42
This was fixed in 0.22 https://github.com/brave/browser-laptop/issues/7321

**Closed by NejcZdovc** 2018-02-19 06:42 UTC
Labels: feature/ledger, priority/P5, product/user-happiness, usability

**Comment by srirambv** [comment] 2018-06-19 22:21
Verified on Windows 10 x64 using
* 0.23.11 - 6565c06
* Muon - 7.1.0
* libchromiumcontent - 67.0.3396.87
