### ISSUE TITLE
Brave won't start: Uncaught Exception

### ISSUE THREAD

**Issue by pinaf** [brave/browser-laptop#6909] opened 2017-01-28 18:33 UTC
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:

Brave won't start after upgrade to 0.13.0. Uncaught Exception.

```
$ brave 
An uncaught exception occurred in the main process Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/.org.chromium.Chromium.6XTSbz)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:600:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/brave/resources/app.asar/app/adBlock.js:8:40)
    at Module._compile (module.js:573:32)
Waiting 60 seconds for process to load
Process failed to load within 60 seconds
```

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux MInt 17.2 Cinnamon 64-bit

- Brave Version (revision SHA):
0.13.0

- Steps to reproduce:
    1. Simply start brave. If launched through a terminal, the error message above shows up. If through a UI shortcut, nothing happens.
    
- Actual result:
Uncaught exception above.

- Expected result:
Brave starts normally.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
Yes, in 0.13.0.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment] 2017-01-29 02:52
We got another report here: https://community.brave.com/t/brave-0-13-not-starting-on-ubuntu-14-04/902

**Comment by bbondy** [comment] 2017-02-01 03:51
This seems to be caused by us using 16.0.4 ubuntu to do the ci builds, we moved to 14.0.4 and it seems to work on both 14.0.4 and 16.0.4. I'm marking this as closed.  There is no code landing but I'm leaving it for tracking int his milestone since there was a ci change.

**Closed by bbondy** 2017-02-01 03:51 UTC
Labels: OS/linux-distros
