### ISSUE TITLE
Unable to change minimum visits in ledger advance settings

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5637] opened 2016-11-15 16:55 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Unable to change minimum visits in ledger advance settings

**Expected behavior:**
Should allow to change the minimum visits in advance settings

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.04

- Brave Version:
0.12.9 RC1

- Steps to reproduce:
    1. Do a clean install of 0.12.9 RC1
    2. Launch browser from console
    3. Try changing the minimum visits, console shows error

- Screenshot if needed:
![ledger_error](https://cloud.githubusercontent.com/assets/17010094/20314945/f4458496-ab53-11e6-90c3-3937f66d94f2.PNG)

- Any related issues:

**Comment by srirambv** [comment] 2016-11-15 17:57
Setting milestone 0.12.10 @alexwykoff also reported this on Mac.

**Comment by jkup** [comment] 2016-11-15 20:14
This is a dupe of #4822 right?

**Closed** 2016-11-15 20:15 UTC
Labels: feature/ledger, OS/linux-distros, QA/checked - macOS
