### ISSUE TITLE
Setting for how long I want browsing history to be stored

### ISSUE THREAD

**Issue by daquinons** [brave/browser-laptop#7890] opened 2017-03-25 11:57 UTC
- Did you search for similar issues before submitting this one?
Yes.
- Describe the issue you encountered:
Right now browsing history is only stored for 3 days and another time length cannot be set.
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS, Windows, Linux.
- Brave Version (revision SHA):
1db81cb
- Steps to reproduce:
    1. Enter a website
    2. Don't enter again
    3. After four days it won't appear in history or url suggestions
    
- Actual result:
I'm not able to adjust how long I want my browsing history to stay, so it's always 3 days.
- Expected result:
I would like to set a longer timeframe. See this "Remove history items" menu in Safari where you get some predefined options and a manual option too.
![](https://i.imgur.com/XGwdfCo.png)

#5590

**Comment by luixxiul** [comment] 2017-06-04 16:13
That issue is tracked at: #5590

**Comment by bsclifton** [comment] 2017-06-05 08:35
This would be a great setting to have 😄   I updated #5590 to have a more descriptive title.  The root cause for this issue (entries disappearing) is that only the last 500 entries are shown.  This would be a perfect setting to compliment history when it gets fixed (captured with https://github.com/brave/browser-laptop/issues/1864)

**Comment by bsclifton** [comment] 2018-09-09 08:37
Closing in favor of https://github.com/brave/brave-browser/issues/1059

**Closed by bsclifton** 2018-09-09 08:37 UTC
Labels: feature/history, open-in-brave-core, settings, suggestion, wontfix
