### ISSUE TITLE
Prevent browser detection via navigator.plugins

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9728] opened 2017-06-27 01:33 UTC
**Describe the issue you encountered:**
See the thread: https://twitter.com/xopek59/status/879354346311471105
Also: https://github.com/gaborgulyas/are_you_brave

The issue seems to have been fixed with #8365, while I am not sure if the code reported on the tweet is blocked.

- Brave Version (revision SHA): 0.16.9

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by jonathansampson** [comment] 2017-06-27 03:31
@luixxiul Dupe of this, no? https://github.com/brave/browser-laptop/issues/8323

**Comment by luixxiul** [comment] 2017-06-27 04:39
I think so, if this code does not detect the browser:
````
if(Object.getOwnPropertyDescriptor(Object.getPrototypeOf(navigator), "plugins").get.toString().indexOf("native") == -1) {
// brave
}
````
See the tweet above.

**Closed** 2018-09-18 22:10 UTC
Labels: misc/fingerprinting, post-v1, priority/P4, privacy
