### ISSUE TITLE
Help/Submit Feedback doesn't give a way to do that

### ISSUE THREAD

**Issue by DavidDailey** [brave/browser-laptop#2966] opened 2016-08-05 01:15 UTC
**Did you search for similar issues before submitting this one?**
No -- I'm not sure how one would search for similar issues.

**Describe the issue you encountered:**
I wanted to give feedback and ask questions about Brave, but when I went to Help/Submit Feedback, I chose Brave to open the feedback (but not "always use this app") and nothing appeared into which I could submit feedback.

**Expected behavior:**
I expected a form to open with something like a "submit" button.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version:
Tonight's release August 4. 
- Steps to reproduce:
    1. Tried it once
    2. Tried it again
    3.

- Screenshot if needed:

- Any related issues: Is there some address wherein questions about Brave's development strategy might be directed?

**Comment by luixxiul** [comment] 2016-08-20 12:26
You can ask here if you don't mind. All developers at Brave receive the notification 

Also I confirmed the issue following the steps to reproduce

**Comment by bbondy** [comment] 2016-10-04 20:14
Marking this as a dupe of this:
https://github.com/brave/browser-laptop/issues/4487

**Closed by bbondy** 2016-10-04 20:14 UTC
Labels: bug
