### ISSUE TITLE
when you drag the tab and drop it exactly where 🚫 is displayed, the drop is canceled (follow-up of #6033)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6863] opened 2017-01-26 02:50 UTC
**Describe the issue you encountered:**
https://github.com/brave/browser-laptop/issues/6033#issuecomment-275295053

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): a37f260

- Steps to reproduce:

> ![dnd](https://cloud.githubusercontent.com/assets/3362943/22318117/77649bec-e3bb-11e6-8516-e90e5de1f904.gif)

1. Open a tab (Tab A)
2. Open another tab (Tab B)
3. Open another tab (Tab C)
4. Grab Tab C
5. Try to drop Tab C between Tab A & B, ie exactly where :no_entry_sign: is displayed

Actual result: Tab C cannot be dropped there

Expected result: Tac C should be dropped there

- Any related issues: #6033

**Comment by NejcZdovc** [comment] 2017-01-26 06:20
I can't reproduce this on MacOs on the latest master commit 96eb071

**Comment by luixxiul** [comment] 2017-01-26 06:53
Do you think the issue was fixed or does something behave differently between Windows and macOS?

**Comment by bsclifton** [comment] 2017-01-26 06:56
@luixxiul it works for me too? Let me try the latest RC on Windows

**Comment by bsclifton** [comment] 2017-01-26 07:01
LGTM on Windows 10 😄 
![drag](https://cloud.githubusercontent.com/assets/4733304/22322620/176d9400-e352-11e6-82b2-6962627699b5.gif)

**Comment by bsclifton** [comment] 2017-01-26 07:02
Notice: it will only cause the move animation if you drag in that half of the tab. This is expected. So in order to move the first tab, you have to move past the middle of the tab

**Comment by luixxiul** [comment] 2017-01-26 07:03
How about after pinning a couple of tabs?

**Comment by bsclifton** [comment] 2017-01-26 07:07
@luixxiul that looks great too (on both Windows and macOS; here's Windows)

![drag2](https://cloud.githubusercontent.com/assets/4733304/22322749/01e3a326-e353-11e6-83e8-3c046d87f016.gif)

**Comment by luixxiul** [comment] 2017-01-26 07:08
Oh really? Let me check later..

**Comment by luixxiul** [comment] 2017-01-26 07:20
@bsclifton can you drop the tab exactly where :no_entry_sign: is displayed?

**Comment by bradleyrichter** [comment] 2017-01-28 06:12
We don't need to display the :no_entry_sign: icon since the ability to drop is indicated by the tab movement.

**Comment by luixxiul** [comment] 2017-01-28 11:31
but actually I cannot drop the tab there and that's exactly the issue I think which should be fixed.

**Comment by bbondy** [comment] 2017-01-28 19:02
I don't have a 🚫 icon either, do you think you can find out why you have it @luixxiul so that others can reproduce better? Thanks. Moving to 0.13.2 for now.

**Comment by luixxiul** [comment] 2017-02-05 04:04
I think maybe this is specific to Windows. :no_entry_sign: appears several times in the gif by @bsclifton above as well: https://github.com/brave/browser-laptop/issues/6863#issuecomment-275321239

The issue here is that when you drag the tab to where :no_entry_sign: is displayed and try to drop it there, the drop is canceled, while the tab animation indicates as if you could drop it there.

**Comment by luixxiul** [comment] 2017-02-25 11:47
@NejcZdovc would you mind checking the issue?

**Comment by NejcZdovc** [comment] 2017-02-25 13:20
Will check it out

**Comment by bsclifton** [comment] 2017-04-19 04:38
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/6242

**Closed by bsclifton** 2017-04-19 04:38 UTC
Labels: feature/tabsbar, misc/drag-and-drop, OS/Windows

**Comment by luixxiul** [comment] 2017-04-26 02:24
It seems that on the latest RC build the issue has been solved; I don't see 🚫 anymore.
