### ISSUE TITLE
File menu pops up issue

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#15222] opened 2018-09-21 06:44 UTC
### Description
Issue is reported by community.
https://community.brave.com/t/navigation-issue-menu-pops-out/32813

When user enters any website in the URL bar, after hitting ctrl+enter a File menu pops up automatically.

### Steps to Reproduce

  1. Launch Brave
  2. Press Alt+D shortcut key.
  3. Verify that the focus goes into the address bar, also File menu options pops up
  4. Enter a website e.g: cnet.com in the address bar
  5. Click on Ctrl+Enter

**Actual result:**
Upon clicking Ctrl+Enter, the File menu pops up automatically

![file menu pops up issue](https://user-images.githubusercontent.com/38657976/45864244-fe0fea00-bd96-11e8-9a5a-1f33bd7f84b3.gif)

**Expected result:**
File menu should not display

**Reproduces how often:**
Always

### Brave Version
0.24.0
**about:brave info:**
 
Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Reproducible on current live release:**
Yes

### Additional Information
Issue is reported by community

**Comment by bsclifton** [comment] 2018-09-21 06:58
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/5775

**Closed by bsclifton** 2018-09-21 06:58 UTC
Labels: bug
