### ISSUE TITLE
New Tab text on Linux needs to be more clear 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6610] opened 2017-01-11 15:21 UTC
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
N & E in `New Tab` looks stuck to each other on Linux
![image](https://cloud.githubusercontent.com/assets/17010094/21853126/ba5eb2b6-d80d-11e6-8b69-4098b166f454.png)

**Expected behavior:**
Should look similar to one on Windows
- Platform (Win7, 8, 10? macOS? Linux distro?):
Debian 8

- Brave Version (revision SHA):
0.12.15

- Screenshots 
Font size set at 11.5px (default)
![image](https://cloud.githubusercontent.com/assets/17010094/21853991/094a1188-d811-11e6-9556-75c9dd0ba691.png)

  Font size set at 12px  
 ![image](https://cloud.githubusercontent.com/assets/17010094/21853969/f82c34b2-d810-11e6-96bc-2e9aa394f9a2.png)

- Any related issues:
cc: @bradleyrichter 
 Please change milestone if required

**Comment by bradleyrichter** [comment] 2017-01-11 16:03
This is a strange regression. I changed tab font size to 12 for all platforms. I'll dig up the commit. 

Cc @bsclifton

**Comment by Liunkae** [comment] 2017-01-27 19:42
Looks good with 0.13.0 (Linux Ubuntu 16.04):
![image](https://cloud.githubusercontent.com/assets/19424103/22384977/5619f26c-e496-11e6-843c-9d6f90125569.png)

**Comment by bbondy** [comment] 2017-01-28 19:24
@srirambv since @Liunkae said it's working I'll close this, but leave in this milestone for testing. If it's still broken please just push it to a future milestone and re-open. Thanks!

**Closed by bbondy** 2017-01-28 19:24 UTC
Labels: design, feature/newtab, OS/linux-distros, release/not-blocking
