### ISSUE TITLE
can't switch pages after selecting 'View Page Source' when Payments enabled

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13377] opened 2018-03-03 01:21 UTC
### Description
After selecting 'View Page Source' from context menu, I am unable to switch tabs. I have to restart Brave to fix this.

### Steps to Reproduce

  1. Enable Payments.
  2. Open a new tab and navigate to a site.
  3. Select 'View Page Source' from the context menu.
  4. New tab opens and displays information
  5. Try to close this tab.

**Actual result:**
Unable to close new tab. Can't switch back to original tab.

From terminal:
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'publishersInfo' of undefined
    at Object.verifiedP (/Users/laurenwagner/Brave Documents/Laptop/0.21+C65/Brave-Beta.app/Contents/Resources/app.asar/app/browser/api/ledger.js:606:12)
    at Object.checkVerifiedStatus (/Users/laurenwagner/Brave Documents/Laptop/0.21+C65/Brave-Beta.app/Contents/Resources/app.asar/app/browser/api/ledger.js:814:26)
    at saveVisit (/Users/laurenwagner/Brave Documents/Laptop/0.21+C65/Brave-Beta.app/Contents/Resources/app.asar/app/browser/api/ledger.js:744:26)
    at addSiteVisit (/Users/laurenwagner/Brave Documents/Laptop/0.21+C65/Brave-Beta.app/Contents/Resources/app.asar/app/browser/api/ledger.js:722:10)
    at addNewLocation (/Users/laurenwagner/Brave Documents/Laptop/0.21+C65/Brave-Beta.app/Contents/Resources/app.asar/app/browser/api/ledger.js:839:15)
    at Object.pageDataChanged (/Users/laurenwagner/Brave Documents/Laptop/0.21+C65/Brave-Beta.app/Contents/Resources/app.asar/app/browser/api/ledger.js:980:13)
    at ledgerReducer (/Users/laurenwagner/Brave Documents/Laptop/0.21+C65/Brave-Beta.app/Contents/Resources/app.asar/app/browser/reducers/ledgerReducer.js:328:29)
    at reducers.reduce (/Users/laurenwagner/Brave Documents/Laptop/0.21+C65/Brave-Beta.app/Contents/Resources/app.asar/js/stores/appStore.js:191:24)
    at Array.reduce (<anonymous>)
    at applyReducers (/Users/laurenwagner/Brave Documents/Laptop/0.21+C65/Brave-Beta.app/Contents/Resources/app.asar/js/stores/appStore.js:189:68)

**Expected result:**
Able to close the tab or switch back to original tab.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.21.654
V8 | 6.5.254.26
rev | bc6272c
Muon | 5.1.3
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.88

**Reproducible on current live release:**
could not reproduce on 0.21.18

### Additional Information
Could not reproduce when Payments was not enabled.

**Comment by arsalankhalid** [comment] 2018-03-04 02:03
Happy to take this! Assuming it;'s available? :)

**Comment by arsalankhalid** [comment] 2018-03-04 18:26
I find that I'm able to re-create this on master, however it is possible to close the tab. But in order to do so, seems buggy. After user clicks on the tab, the (X) hover finally pops up, and can be clicked 
Sadly my view doesn't show me clicking, but i had clicked a total of 4 times to see the X. 

![mar-04-2018 13-24-10](https://user-images.githubusercontent.com/5307218/36948907-5e523728-1faf-11e8-8216-bc6a8410d326.gif)

**Comment by NejcZdovc** [comment] 2018-03-12 16:17
@LaurenWags can you please try it again, can't reproduce it

**Comment by LaurenWags** [comment] 2018-03-12 17:54
Could not reproduce with newer version 0.21.656

**Comment by NejcZdovc** [comment] 2018-03-12 18:04
let's close it for now and reopen if needed

**Closed by NejcZdovc** 2018-03-12 18:04 UTC
Labels: 0.21.x, bug, feature/ledger
