### ISSUE TITLE
Mixed Content on http://us.coopertire.com

### ISSUE THREAD

**Issue by frankadomitis** [brave/browser-laptop#5634] opened 2016-11-15 14:31 UTC
The map doesn't show on this page:

http://us.coopertire.com/Customer-Care/Dealer-Locator.aspx?form=locator_search&addressline=92346

However, it works using Edge

Im trying to find a tire retailer for tires for my wife's car

**Did you search for similar issues before submitting this one?**

No

**Describe the issue you encountered:**

See above.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

Win 10

- Brave Version:
 
0.12.8

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by getsetbro** [comment] 2016-11-15 21:01
Brave is blocking insecure scripts:
![image](https://cloud.githubusercontent.com/assets/442793/20323868/24564662-ab44-11e6-9bda-28b6e26767c4.png)
The page would work if you turned off the shields in the top-right dropdown menu.
![image](https://cloud.githubusercontent.com/assets/442793/20323756/b0f7f760-ab43-11e6-81f4-53fd0a22eb93.png)

**Comment by luixxiul** [comment] 2016-11-16 02:34
The issue is caused because the content is blocked due to Mixed Content.

````
The page at 'https://hosted.where2getit.com/coopertire/index-test.html?form=locator_search&addressline=92346&aliaspath=%2fCustomer-Care%2fDealer-Locator' was loaded over HTTPS, but requested an insecure stylesheet 'http://static.where2getit.com/w2gi/css/style210.css'. This request has been blocked; the content must be served over HTTPS.
````

A temporary solution is to disable HTTPS Everywhere on the panel.

**Comment by frankadomitis** [comment] 2016-11-16 13:32
Thank you.  Love it.

**Comment by diracdeltas** [comment] 2017-06-28 22:44
fixed by latest https://github.com/brave/https-everywhere-builder, update will be pushed shortly

**Closed by diracdeltas** 2017-06-28 22:44 UTC
Labels: feature/HTTPSEverywhere, webcompat
