### ISSUE TITLE
HTTPS Everywhere breaks thehill.com

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#11431] opened 2017-10-11 03:21 UTC
### Description
Due to a bad cert, HTTPS Everywhere prevents https://thehill.com from loading.

### Steps to Reproduce
With HTTPS Everywhere enabled, navigate to https://thehill.com.

**Actual result:**
Site fails to load.

**Expected result:**
Site loads.

**Reproduces how often:**
Consistently.

### Brave Version
0.19.37

### Additional Information
Similar issue to #11303

**Comment by Liunkae** [comment] 2017-10-14 04:20
Same as #10586?

**Comment by diracdeltas** [comment] 2017-10-18 19:55
closing as dupe of https://github.com/brave/browser-laptop/issues/10586

**Closed by diracdeltas** 2017-10-18 19:55 UTC
Labels: bug, feature/HTTPSEverywhere
