### ISSUE TITLE
Extensions should have folder and list it automatically

### ISSUE THREAD

**Issue by raisty** [brave/browser-laptop#13518] opened 2018-03-20 14:18 UTC
### Description

The extensions should have folder to drop it in and should be loaded automatically.
Is nonsense to ask for any extansion.

### Steps to Reproduce

We should:
  1. drop extension into specific folder
  2. restart brave browser
  3. enable extension

**Actual result:**

Ask for extension in forum.

**Expected result:**
Auto list extensions from folder.

**Reproduces how often:**

Always

### Brave Version

**about:brave info:**

V8	6.5.254.36
Update Channel	Release
rev	19c78a1
OS Release	17.4.0
OS Platform	macOS
OS Architecture	x64
Node.js	7.9.0
Muon	4.9.3
libchromiumcontent	65.0.3325.162
Brave Sync	v1.4.2
Brave	0.21.24

**Reproducible on current live release:**

yes

**Comment by bsclifton** [comment] 2018-08-24 08:11
Closing as duplicate of https://github.com/brave/browser-laptop/issues/253

In that issue, I do share an experimental branch where I did get this desired functionality working (ex: use a command line tool, download extensions to a folder, enable them in Brave)

Moving forward (with brave-core), the extensions screen will be fairly close to Chromium and Chrome Web Store is supported

**Closed by bsclifton** 2018-08-24 08:11 UTC
Labels: duplicate, feature/extensions, suggestion
