### ISSUE TITLE
Download progress not showing after resume

### ISSUE THREAD

**Issue by shakeeltariq** [brave/browser-laptop#1341] opened 2016-04-12 06:52 UTC
I had a failed download pending in download list, showing in status bar. I closed Brave, restarted later and tried to restart the download, it asked for file save location but then the progress widget just vanished from the status bar as well as from about:downloads page. However the download file in question was being downloaded behind the scene as the file size was being increased progressively when checked in windows Explorer.

Hope this report helps make Brave, Braver :)

**Comment by cezaraugusto** [comment] 2016-06-17 15:59
Thanks for reporting it @shakeeltariq.

I tried to reproduce things you said with no success. Could you tell which Brave version and Operating System are you using?

**Comment by luixxiul** [comment] 2017-01-02 08:22
Closing this ticket due to lack info. Please leave a comment if you have the same issue yet, thanks. @shakeeltariq

**Closed by luixxiul** 2017-01-02 08:22 UTC
Labels: feature/download, info-needed
