### ISSUE TITLE
Instant wallet creation doesn't ask to set password instead prompts password to unlock

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14988] opened 2018-08-10 14:14 UTC
### Description
Instant wallet creation doesn't ask to set password instead prompts password to unlock

### Steps to Reproduce
  1. Clean profile from 0.25.401
  2. Enable ETH wallet  and wait for iframe to load
  3. Before you can click anything a new wallet is created and asks to unlock the wallet with a password which isn't asked to set in the first place

**Actual result:**
![instant wallet](https://user-images.githubusercontent.com/17010094/43962316-5eaa0d06-9c85-11e8-9af1-bf9f82d2ffe6.gif)

**Expected result:**
Should first ask to set a password and then create the wallet. Otherwise best would be to have a placeholder text as mentioned in #14961 when a new wallet is created before showing it. This way it helps set password when enabled and doesn't run into any race condition.

**Reproduces how often:**
Intermittent issue. Sometimes on new profile it doesn't even create a new wallet and clicking on New ETH wallet doesn't instantly create wallet. 

### Brave Version

Brave | 0.25.401
-- | --
V8 | 6.8.275.24
rev | 248c4e4
Muon | 8.0.6
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
N/A

### Additional Information
#14961 
Issue reproduced by @GeetaSarvadnya as well on Windows.
cc: @LaurenWags @kjozwiak to check if it reproduces on mac as well

**Comment by Slava** [comment] 2018-08-11 01:07
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/14990 (look like the same issue to me, correct me if they are different)

**Closed by Slava** 2018-08-11 01:07 UTC
Labels: QA/test-plan-specified, bug, feature/ETH-Wallet, release-notes/exclude, release/blocking

**Comment by GeetaSarvadnya** [comment] 2018-08-14 09:35
Verified on Windows x64 with
• 0.23.100 5e197a1a877c9967aecc838b9a7ca528ee5b46bd
• Muon 8.0.8
• libchromiumcontent 68.0.3440.84
