### ISSUE TITLE
AltGr treated as Ctrl+Alt in Win32

### ISSUE THREAD

**Issue by ralesk** [brave/browser-laptop#6915] opened 2017-01-29 21:33 UTC
There's a very sad legacy in the Windows API which makes the <kbd>AltGr</kbd> key appear as if <kbd>Left Ctrl</kbd> and <kbd>Right Alt</kbd> had been pressed simultaneously.  This sets Windows apart from every other OS in that handling the Third Level is utterly broken in it unless desktop and web site programmers pay attention to get around it.

The actual issue I noticed while running version 8ca0127 was that pressing <kbd>AltGr</kbd>+<kbd>U</kbd> (to type ú on the layout I use) brought up the View Source tab on the website I was interacting with.

This tells me two things:
* Brave does not pay attention to Windows's crippled legacy behaviour and mistakenly handles <kbd>AltGr</kbd> presses as <kbd>Ctrl</kbd>+<kbd>Alt</kbd> presses.
* Brave does not pay attention whether <kbd>Alt</kbd> is pressed or not, when expecting <kbd>Ctrl</kbd>+<kbd>U</kbd> for View Source (or, I suspect, any other <kbd>Ctrl</kbd>-based browser shortcut).

It is very likely that nobody wants to send <kbd>Ctrl</kbd> when they're trying to type a Level Three character, so I suspect the solution would be to catch any occurrence of fake Windows <kbd>AltGr</kbd> and swallow the fake <kbd>Ctrl</kbd> key press event that emanates from it.  This is probably not as easy and straightforward as easy it is to say :)

**Comment by bsclifton** [comment] 2017-01-31 17:12
@ralesk thanks for the report 😄   I believe I understand the issue...

With our framework, we can't directly capture Alt vs AltGr.  However, we have the ability to check if it was the left or right (so two variables to check; key and location).  I am positive this is the case for the issue you've discovered

Just for reference (in case you were interested in looking at the code), here is the pull request where I updated the menu to ignore AltGr.  This shows the method which you can use for detecting it
https://github.com/brave/browser-laptop/pull/4628

**Comment by rickersilva** [comment] 2018-02-06 23:51
This is back. I´mhaving the same issue today at my home PC, so typing things like the sharp or the at sign,in my spanish keyboard are annoying.

**Comment by bsclifton** [comment] 2018-02-07 22:17
@rickersilva was it working in previous releases?

**Comment by rickersilva** [comment] 2018-02-08 16:32
Yes. The problem is with the hash and at symbols, so I use them daily
signing up on many sites and writing emails

**Comment by bsclifton** [comment] 2018-09-07 17:00
This appears to be fixed with our [Developer channel release](https://brave.com/download-dev) 😄 👍

**Closed by bsclifton** 2018-09-07 17:00 UTC
Labels: OS/Windows, bug, feature/keyboard-shortcuts, fixed-with-brave-core, wontfix
