### ISSUE TITLE
iheart.com website radios do not play

### ISSUE THREAD

**Issue by VirgilRoussos** [brave/browser-laptop#953] opened 2016-02-29 20:17 UTC
From support:

http://www.iheart.com

**Comment by luixxiul** [comment] 2016-05-14 03:08
Confirmed. This seems to be due to blocking some scripts which violate the CSP directive. Open Devtool and reload,

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-Dfz9LHfiGbhbi5p8YLt4zjwhoWGJzCyCzMeBNplMnRE='), or a nonce ('nonce-...') is required to enable inline execution.

and so on.

CC: @bbondy

**Comment by diracdeltas** [comment] 2016-05-19 17:50
@luixxiul that's because you have noscript enabled, please turn it off before testing

**Comment by diracdeltas** [comment] 2016-05-19 17:52
in Chrome, this requires flash to work. so i think it won't work in Brave until we support Flash

**Comment by luixxiul** [comment] 2016-05-28 09:12
Closing for now

**Closed by luixxiul** 2016-05-28 09:12 UTC
