### ISSUE TITLE
Scroll down jumps to the end of page when page opened in a new tab 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4515] opened 2016-10-04 20:30 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Scroll down jumps to the end of page when page opened in a new tab 

**Expected behavior:**
Should scroll smoothly up/down

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.x onwards

- Steps to reproduce:
    1. Open brianbondy.com
    2. Click on Twitter icon to open twitter page in  a new tab
    3. Scroll down using mouse, one turn of the mouse wheel makes the page jump to the end. Same issue when doing two finger scrolling on the same page

- Screenshot if needed:

- Any related issues:
#4502

**Comment by raggmann** [comment] 2016-10-04 21:08
Same problem since the latest update was performed. Using latest version of win 10 x32

**Comment by admiral142** [comment] 2016-10-04 21:33
Same issue since update.  And scrolling alltogether breaks sometimes on new tab opened.

**Comment by Jakewk** [comment] 2016-10-04 22:20
Same issue after updating today.

**Comment by bsclifton** [comment] 2016-10-04 22:52
@srirambv is this a dupe of https://github.com/brave/browser-laptop/issues/4472?

**Comment by bsclifton** [comment] 2016-10-05 00:07
Closing for now as a duplicate (please reopen if it's not)

Please see https://github.com/brave/browser-laptop/issues/4472 for the latest status

**Closed by bsclifton** 2016-10-05 00:07 UTC
Labels: bug, duplicate
