### ISSUE TITLE
Changing tabset count messes up tab favicon and close button

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9779] opened 2017-06-29 15:35 UTC
## Test plan

https://github.com/brave/browser-laptop/pull/10134#issue-245571404

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Changing tabset count messes up tab favicon and close button

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.17.12
rev	0095c35
Muon	4.1.6

- Steps to reproduce:
    1. Set tab count to 20 and  set homepage to reddit.com/r/random
    2. Open more than 100 tabs by pressing ctrl+t, ensure there are 5-6 tabset
    3. With all these tabs set tabcount to 100, close button and favicon on tabs gets messed up as the breakpoint is not properly calculated
    
- Actual result:
Changing tabset count messes up tab favicon and close button

- Expected result:
Tab breakpoint should be properly calculated

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/27695137-f8d48a36-5ce5-11e7-874d-48e6773238be.png)
- Any related issues:
cc: @cezaraugusto

**Comment by cezaraugusto** [comment] 2017-06-29 17:18
dooh me they were the same, thanks Sri

**Comment by cezaraugusto** [comment] 2017-07-08 05:01
I referenced this issue in #9809 but that's wrong. #9809 solved #8429. I referenced the wrong issue by mistake. Re-opening

**Comment by LaurenWags** [comment] 2018-01-04 16:43
@cezaraugusto - noticing that the tabs from the first tab set don't have their favicon resized the way the tabs from the other tab sets do. Could you take a look? 
![screen shot 2018-01-04 at 11 41 34 am](https://user-images.githubusercontent.com/28145373/34574105-6923a086-f144-11e7-8328-1ebc5f00d396.png)

**Comment by cezaraugusto** [comment] 2018-01-04 16:49
could you share your STR? I think I know what's happening

**Comment by LaurenWags** [comment] 2018-01-04 16:59
just tried to confirm my steps were the same as from the description, but now i'm seeing this :( 
![screen shot 2018-01-04 at 11 58 41 am](https://user-images.githubusercontent.com/28145373/34574844-ada60ada-f146-11e7-90d5-9b0cc6889455.png)

**Comment by LaurenWags** [comment] 2018-01-11 22:33
Reopening per https://github.com/brave/browser-laptop/issues/9779#issuecomment-355337558 - I no longer see a tab favicon when I set the tab count to 100.

**Comment by cezaraugusto** [comment] 2018-01-17 19:08
@LaurenWags depending of your window size a tab with no icons is expected. However https://github.com/brave/browser-laptop/issues/9779#issuecomment-355332544 is not. I'm not able to reproduce following @srirambv STR:

![jan-17-2018 17-05-51](https://user-images.githubusercontent.com/4672033/35061613-e90fc6ee-fba8-11e7-9bd5-9b3dd5ce5a12.gif)

I have a guess-fix but hard to know it's working without reproducing. Let me know if there's something I'm missing

**Comment by cezaraugusto** [comment] 2018-01-17 19:08
^ sorry for the bad GIF quality

**Comment by cezaraugusto** [comment] 2018-01-17 19:12
also, could you tell me which version `rev` are you on? I'm on de5970f003ca534c0ff0718ac4b06cacd752408b

**Comment by LaurenWags** [comment] 2018-01-23 17:10
So to recap some slack convos - can no longer repro https://github.com/brave/browser-laptop/issues/9779#issuecomment-355332544 I only see https://github.com/brave/browser-laptop/issues/9779#issuecomment-355337558 which makes sense as discussed because at some point the tabs are too small to display a favicon. 

However, (maybe this needs a new issue?) If I have a full screen window, and 100 tabs, no favicons. But, if I restart Brave the favicons do display: 
![9779-blanktabsuntilrestart](https://user-images.githubusercontent.com/28145373/35289752-3d9b343c-0036-11e8-93fb-e47167dc348a.gif)

This is using:
Brave | 0.20.19
V8 | 6.4.388.29
rev | 3d05e91
Muon | 4.7.3
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.99

**Comment by cezaraugusto** [comment] 2018-01-23 22:42
@LaurenWags what happens in that state you mentioned in https://github.com/brave/browser-laptop/issues/9779#issuecomment-359861434 if you keep changing the number of tabs per tab set? does at that window size the icons are shown or just keep the same?

per your screenshot, you reached a point where icons should be visible, but if you have resized the window before by increasing the width, it might not be updated at the right time given the number of tabs. 

The time for icons to update based on tab size is variable and depends on how fast you resize, for slow resizing, components take more time to update given the operation cost in CPU. Fast resizes usually update instantly. An app restart as you did force the update which is why you see the icons.

If changing tab set size with the window at the same width do update the icons IMO we can close this. The delay of updating icons on window resize is variable and while not really a bug, could be improved over time and best take would be opening another issue.

**Comment by LaurenWags** [comment] 2018-01-23 23:05
Thanks @cezaraugusto and will open up something separate 😄

**Closed by LaurenWags** 2018-01-23 23:05 UTC
Labels: QA/test-plan-specified, bug, feature/tabsbar, misc/button, misc/favicon, release-notes/include
