### ISSUE TITLE
When you use Cmd + F to search a page, then exit out of the search bar...the highlights persist

### ISSUE THREAD

**Issue by emresurmeli** [brave/browser-laptop#2476] opened 2016-07-13 19:10 UTC
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
When you use Cmd + F to search a page, then exit out of the search bar...the highlights persist
**Expected behavior:**
The highlights on matched search text should disappear when the find (cmd+f) bar is exited
- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS 
- Brave Version:
0.11.0
- Steps to reproduce:
    1. Open a website and click Command + F to search the page
    2. Search some words and notice the highlights
    3. Exit out of the search, and the highlights do not disapear

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment] 2016-07-13 20:33
Dupe of https://github.com/brave/browser-laptop/issues/2374 which is fixed in 0.11.1 due out early next week.

**Closed by bbondy** 2016-07-13 20:33 UTC
