### ISSUE TITLE
Many errors in stdout after creating an autofill entry in about:autofill

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#13553] opened 2018-03-22 01:53 UTC
### Steps to Reproduce

  1. Clean Install
  2. Create an entry in about:autofill

**Actual result:**
```
[6760:3760:0322/024530.222:ERROR:connection.cc(1945)] Web sqlite error 5, errno           33: database is locked, sql: PRAGMA auto_vacuum
[6760:3760:0322/024530.224:ERROR:connection.cc(1945)] Web sqlite error 5, errno           33: database is locked, sql: PRAGMA journal_mode = TRUNCATE
[6760:3760:0322/024531.264:ERROR:connection.cc(1945)] Web sqlite error 5, errno           33: database is locked, sql: PRAGMA cache_size=32
[6760:3760:0322/024531.266:ERROR:connection.cc(1945)] Web sqlite error 5, errno           33: database is locked, sql: SELECT name FROM sqlite_master WHERE type=? AND nam          e=? COLLATE NOCASE
[6760:3760:0322/024531.268:ERROR:connection.cc(1945)] Web sqlite error 5, errno           33: database is locked, sql: SELECT name FROM sqlite_master WHERE type=? AND nam          e=? COLLATE NOCASE
[6760:3760:0322/024531.270:ERROR:connection.cc(1945)] Web sqlite error 5, errno           33: database is locked, sql: SELECT COUNT(*) FROM sqlite_master
[6760:3760:0322/024531.272:ERROR:connection.cc(1945)] Web sqlite error 5, errno           33: database is locked, sql: SELECT name FROM sqlite_master WHERE type=? AND nam          e=? COLLATE NOCASE
[6760:3760:0322/024531.274:ERROR:connection.cc(1945)] Web sqlite error 5, errno           33: database is locked, sql: CREATE TABLE meta(key LONGVARCHAR NOT NULL UNIQUE P          RIMARY KEY, value LONGVARCHAR)
[6760:3760:0322/024531.274:ERROR:web_database_backend.cc(113)] Cannot initialize           the web database: 1

```
**Expected result:**
No errors

**Reproduces how often:**
100%

### Brave Version
```
Brave: 0.22.6 
V8: 6.5.254.36 
rev: e6ff4ea43ed740d1449a4c72005e22ce5235447e 
Muon: 5.1.0 
OS Release: 6.1.7601 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162
```

### Additional Information
Despite the errors autofill works as expected.
Also reproducible after clearing autofill in about:preferences#security -> Clear Browser Data Now

cc @bsclifton @kjozwiak @LaurenWags @srirambv

**Comment by kjozwiak** [comment] 2018-03-22 02:22
I've seen similar output several times in the terminal on macOS when running `0.21.24` 19c78a1. @darkdh mentioned that it was due to  multiple processes accessing the database at same time.

@darkdh @bridiver is this an issue? Could we be losing data/state when one process doesn't manage to access the database?

```
[9472:11204:0320/000738.613:ERROR:connection.cc(1945)] Web sqlite error 5, errno 33: database is locked, sql: PRAGMA auto_vacuum
[9472:11204:0320/000738.616:ERROR:connection.cc(1945)] Web sqlite error 5, errno 33: database is locked, sql: PRAGMA journal_mode = TRUNCATE
[9472:11204:0320/000739.684:ERROR:connection.cc(1945)] Web sqlite error 5, errno 33: database is locked, sql: PRAGMA cache_size=32
[9472:11204:0320/000739.687:ERROR:connection.cc(1945)] Web sqlite error 5, errno 33: database is locked, sql: SELECT name FROM sqlite_master WHERE type=? AND name=? COLLATE NOCASE
[9472:11204:0320/000739.690:ERROR:connection.cc(1945)] Web sqlite error 5, errno 33: database is locked, sql: SELECT name FROM sqlite_master WHERE type=? AND name=? COLLATE NOCASE
[9472:11204:0320/000739.693:ERROR:connection.cc(1945)] Web sqlite error 5, errno 33: database is locked, sql: SELECT COUNT(*) FROM sqlite_master
[9472:11204:0320/000739.696:ERROR:connection.cc(1945)] Web sqlite error 5, errno 33: database is locked, sql: SELECT name FROM sqlite_master WHERE type=? AND name=? COLLATE NOCASE
[9472:11204:0320/000739.700:ERROR:connection.cc(1945)] Web sqlite error 5, errno 33: database is locked, sql: CREATE TABLE meta(key LONGVARCHAR NOT NULL UNIQUE PRIMARY KEY, value LONGVARCHAR)
[9472:11204:0320/000739.700:ERROR:web_database_backend.cc(113)] Cannot initialize the web database: 1
```

**Comment by bsclifton** [comment] 2018-07-23 17:14
Unable to reproduce this on latest beta - closing

**Closed by bsclifton** 2018-07-23 17:14 UTC
Labels: 0.22.x, feature/autofill
