### ISSUE TITLE
Twitter and other publishers are included even though the auto-include is disabled

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14245] opened 2018-05-24 18:27 UTC
### Description
Twitter and other publishers are included even though the auto-include is disabled

### Steps to Reproduce

1. Launch Brave with   clean profile from CLI
2. Enable payment
3. Open twitter in new tab and click on Add   to payments icon in the url bar
4. Verify twitter publisher is included in   ledger list
5. Delete twitter from ledger list ( delete from show deleted list as well)
6. Disable auto-include
7. Open twitter in new tab, spend default 8   sec in viewing the video

**Actual result:**

Twitter publishers are included even though the auto-include is disabled

**Expected result:**

Twitter publishers should be listed instead of include when the auto-include is disabled

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.22.801

**Reproducible on current live release:**
Yes

### Additional Information
Able to reproduce the issue on twitter consistently

**Comment by GeetaSarvadnya** [comment] 2018-05-24 18:36
![ledger issue](https://user-images.githubusercontent.com/38657976/40504650-757e7dea-5faf-11e8-89af-4c67ba04632e.gif)

**Comment by jasonrsadler** [comment] 2018-05-29 14:15
Duplicate of #13283?

**Closed** 2018-05-29 19:50 UTC
Labels: bug, feature/rewards, release-notes/include

**Comment by LaurenWags** [comment] 2018-05-30 17:39
Verified with macOS 10.12.6 using
* 0.22.723 edb3e88
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
