### ISSUE TITLE
Allow me to block all notifications requesting permission 

### ISSUE THREAD

**Issue by jaxidian** [brave/browser-laptop#12467] opened 2018-01-02 21:47 UTC
### Description
I'd like to have a global setting that blocks (or automatically declines) all future requests for permission to send notifications to me in the Windows Brave application. Seriously, every blog and their mother these days wants to pipe notifications to me to get me to come back so they get more ad revenue. It's getting ridiculous!

(Beware: incoming eyerolls)

### Steps to Reproduce
  1. Go to nearly any site (or their mother's blog) and you'll be prompted to allow them to send notifications to you.
  2. I get annoyed and rage close the tab.
  3. I go to another site and get the same prompt.
  4. I get further annoyed, rage quit the internet, and go eat a pint of ice cream sitting on the floor in the corner of my office.

**Actual result:**
I gain 10 lbs.

**Expected result:**
I never see a request again for notification permission.

**Reproduces how often:**
Only 100% of the time on every site that I would never want to grant this permission to.

**Comment by eljuno** [comment] 2018-01-24 19:07
+1 from community https://community.brave.com/t/remove-noisy-allow-notifications-from-this-site-in-all-sites/14665?u=eljuno

> Or at least a “block/deny all notifications and not being asked again” button.

**Comment by bsclifton** [comment] 2018-01-24 21:47
@jaxidian great suggestion 😄 If anyone wants to grab this, please let me know and I can help answer questions

**Comment by jaxidian** [comment] 2018-01-25 18:24
Less snarky commentary aside, a suggestion for a possible solution:

1. When a notification permission is requested, always deny the permission when there is no history of the permission having been granted in the past (otherwise, honor the prior grant).
2. When a notification permission is requested, whether previously approved or denied, show a notification badge somewhere in the UI with a status of green checkmark or red x (I'm not sure where the best place would be - perhaps a badge in the address bar or along side my plugin icons - I'm not sure, but the blocked popup icon comes to mind in Chrome as an example to draw inspiration from). Whatever it is, make it 100% emotionally non-intrusive and very ignorable (the current behavior is ignorable but it's very emotionally intrusive to a user, or at least to me).
3. If the permission has been denied but I interact with the badge to approve it, if possible, signal to the page that the permission has been granted. (For this step, I'm not sure if there are appropriate callbacks that can be triggered or perhaps prompt me if I want to refresh the page? I'm not real sure what's appropriate - somebody smarter than me would have to flush the details of this out.)

Stretch Goal: When I grant the permission, allow me to optionally specify a period of time it may be granted for. For example, I might like to have notifications for 24 hours but that's it.

**Comment by jonathansampson** [comment] 2018-03-15 03:17
Firefox recently shipped this feature: https://arstechnica.com/gadgets/2018/03/the-new-firefox-lets-you-stop-websites-from-asking-to-send-you-notifications/.

**Comment by eljuno** [comment] 2018-06-17 18:47
+1 from community https://community.brave.com/t/bunch-of-feautures/24018?u=eljuno

@bsclifton we can have it for free with brave-core? :smile:

**Comment by srirambv** [comment] 2018-06-17 19:33
@eljuno  I don't think its out of the box feature but it does to a certain extent. Blocked notification at global setting still asks for camera/location access notification but that would be for tab specific

**Comment by Steve-of-Indiana** [comment] 2018-07-09 06:42
I do not have a microphone or camera on my computers because I value my privacy. I have found my "location" appears where my ISP connects to the Internet (a couple hundred miles from here) but even that is more information than I want revealed. Like some others who have posted on this thread I think that my location is nobody's business but my own. While this may sound a bit Draconian, I would like a switch on the shields that would cause Brave to not provide a location or, if that is not possible, map my location to something like Andronica Island (yes it exists.)

**Comment by jaxidian** [comment] 2018-07-10 18:57
@Steve-of-Indiana - That is likely impossible, or at least incredibly difficult. I'm going to explain why very simply because I'll assume you do not understand the reasons, so please do not get offended if this is too "dumbed down".

When your computer requests a web page, your computer communicates with the server. In order for two computers to communicate over the internet, they have to share their "IP Addresses" with one another. Otherwise, the server has no clue where to send the bits and bytes for the web page for you to view. It is impossible to hide this IP address from that server, so if nothing else is shared, this IP address is now available.

Using this IP Address, people can use lookup tables to figure out generally where you are. Kinda like if I called you on your phone number of 317-123-4567, I can make an educated guess about your location knowing that 317 is an Indiana area code and 123 is a Greenwood exchange. That doesn't mean you are in Greenwood, but it's still information that I could use to guess about your location.

This level of guessing is what it sounds like you're describing, just with your IP address instead of your phone number. Certain IP addresses, for example, are known to be used by Spectrum in the city of Chicago, which might be shared with Indianapolis customers as well, because they share the same infrastructure.

Does this make sense?

----

On another note, I hedged my words there with "or at least incredibly difficult", because technically, Brave could build out a VPN infrastructure and use that VPN infrastructure as a "Proxy" for your web traffic so all traffic goes through their proxy. This isn't just a feature but would require a bunch of servers and data centers for Brave to offer just this one piece of new functionality in the browser. If they were to do this, then the IP addresses that the outside web servers would see would then be Brave's data centers and not your house.

However, this is likely a large effort with a large expense for Brave to handle on their own. Maybe they'll get there, but I don't believe it's currently an option for them. On the other hand, however, there's nothing preventing you from doing more-or-less the same thing. You could always purchase a VPN service and connect to the internet through that service. There are a TON of them out there and I can't suggest a good one, but there are many options available (some very good and some very bad). If you were to use such a VPN service, then you would effectively accomplish the same thing for yourself.

**Comment by Steve-of-Indiana** [comment] 2018-07-11 07:08
Actually it makes perfect sense & is a reminder I should not post when I am tired (as I am now) but part of my request still stands. It would still be nice if Brave provided an option in shields or some other convenient spot for a global decline of location requests. Again I am tired so I do not recall the specifics but I have Firefox installed on a system with options set to gen up a bogus location. I will probably have to modify that setting or just add a VPN client to the Linux box that works as a router for the in-house network but I was trying to get ad filtering working on that first.

**Comment by jaxidian** [comment] 2018-07-11 13:44
Would this be an appropriate translation of your request?

As a web browsing user who wishes to remain more anonymous, I want to have my browser transmit a configurable false location to the web servers for location requests so that when they use modern/advanced location APIs over IP Address-mapping, they will get less useful information about me.

This would have the following qualities:

1. If they simply do an IP Address lookup as I described above, nothing would change
2. If they asked your browser for its location using more advanced location APIs, they would see the falsified location that you specified and not an actually representative location for you
3. If they prefer the location API over an IP lookup (many do this), then the falsified location would be what they would use and this would effectively be the same as bullet point 2.
4. If they store both (many do this), then it would be a combination of the first two bullet points above, and they could decide which to act upon.

---

On a side note, this issue is the wrong place for this request to go. Instead, you should reproduce this in a new Issue to help the Brave folks keep things organized.

**Comment by Steve-of-Indiana** [comment] 2018-07-12 23:08
Your rephrase is essentially what I am asking. In my initial post I did not make the link between IP address & location as my ISP is some distance from my house but others are not as fortunate. 
The reality is it appears we are limited to having browsers refuse to provide a location or to provide faux location. I will likely put my household ad block server on hold & setup a VPN client/router (a will have to review the terms of service for the VPN that I use.)
At the moment I am not at home & replying on my phone so I cannot be sure of all of the settings on my PCs but I believe I set Firefox to limit what information it provides about location using about:config maybe 1-2 years ago. 
My apologies for posting in the wrong place. I did a Google search for how to deny location requests in Brave & thought I was in an ongoing discussion of the issue. 

Steven Read

On Wednesday, July 11, 2018, 9:45 AM, Shane Milton <notifications@github.com> wrote:


Would this be an appropriate translation of your request?

As a web browsing user who wishes to remain more anonymous, I want to have my browser transmit a configurable false location to the web servers for location requests so that when they use modern/advanced location APIs over IP Address-mapping, they will get less useful information about me.

This would have the following qualities:
   
   - If they simply do an IP Address lookup as I described above, nothing would change
   - If they asked your browser for its location using more advanced location APIs, they would see the falsified location that you specified and not an actually representative location for you
   - If they prefer the location API over an IP lookup (many do this), then the falsified location would be what they would use and this would effectively be the same as bullet point 2.
   - If they store both (many do this), then it would be a combination of the first two bullet points above, and they could decide which to act upon.

On a side note, this issue is the wrong place for this request to go. Instead, you should reproduce this in a new Issue to help the Brave folks keep things organized.

**Comment by bsclifton** [comment] 2018-08-14 21:49
Closing in favor of https://github.com/brave/brave-browser/issues/751

We won't be able to address this in `browser-laptop`, but we will in [brave-core](https://github.com/brave/brave-browser) 😄

**Closed by bsclifton** 2018-08-14 21:49 UTC
Labels: feature/notificationbar, priority/P4

**Comment by arooni** [comment] 2018-12-05 17:55
would be nice if you showed us *how* to find the feature you implemented.  not sure where to look to do this on brave core

**Comment by bsclifton** [comment] 2018-12-31 17:05
Locking conversation as this is tracked in the NEW version of Brave. Please subscribe to (and feel free to comment on) https://github.com/brave/brave-browser/issues/751
