### ISSUE TITLE
Refine Time Spent Calculation

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7486] opened 2017-03-04 02:17 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
_Time Spent_ is presently too lenient. One site, left open when I walked away from my machine for the evening, was granted a _Time Spent_ amount of over 10 hours. Other users report similarly skewed reports for domains in their list. See https://twitter.com/givanse/status/837495337455501313.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.13.x

- Steps to reproduce: (_Unconfirmed_)
    1. Open multiple tabs for a single domain
    2. Leave browser open, and leave computer
    
- Actual result:
Brave would factor in some length of inactivity when calculated _Time Spent_ on a particular page.

- Expected result:
Brave appears to focus more on how long the page was open, rather than how long the user was interacting with the page.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
N/A

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by Liunkae** [comment] 2017-03-04 03:29
0.13.5 has already shipped. 😄  Moving to 0.13.6.

**Comment by jonathansampson** [comment] 2017-03-04 03:52
@Liunkae Haha. My mistake. Thank you for correcting.

**Comment by mrose17** [comment] 2017-03-04 04:49
appears to be a duplicate of https://github.com/brave/browser-laptop/issues/6826

**Closed by mrose17** 2017-03-04 04:49 UTC
Labels: bug, feature/ledger
