### ISSUE TITLE
comments section on breitbart.com won't load in Brave but loads fine in Safari

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1373] opened 2016-04-14 23:50 UTC
https://twitter.com/JakeBryanDev/status/760232415956721664

**Comment by bsclifton** [comment] 2016-04-26 06:38
I could be wrong, but main issue is by design, right? Disqus (the commenting system) uses tracking and 3rd party cookies, which are blocked by default by Brave.

I did notice that if you tried to allow those by:
* turning off `Block 3rd Party Cookies`
* picking `Allow Ads and Tracking`

then the following error will show up in the JavaScript console:
`Uncaught TypeError: Cannot read property 'toLowerCase' of undefined`

The Disqus system should show with those settings. This error does not seem to occur in Chrome.

**Comment by aekeus** [comment] 2016-05-30 19:01
Potentially add option to default allow social widgets i.e. Disqus

**Comment by diracdeltas** [comment] 2016-06-01 00:47
this works fine in chrome with 3p cookies disabled so pretty sure it's not cookies-related

**Comment by diracdeltas** [comment] 2016-06-01 01:22
breitbart shows `Uncaught TypeError: Cannot read property 'toLowerCase' of undefined` and doesn't load fully even with all shields disabled. so either lowering shields doesn't fully work, or there is some weird difference in how the site treats Brave and other browsers.

**Comment by aekeus** [comment] 2016-06-01 01:27
Another example:

http://blog.dilbert.com/post/145205211401/billionaire-branding-mistakes

Does not show Disqus comments with Shields Up. Shields Down enables comments.

**Comment by diracdeltas** [comment] 2016-06-01 01:46
@aekeus thanks, fixed that case in 1ff038c307b3f43bc327f9492366a441c0c9743e

**Comment by cezaraugusto** [comment] 2016-06-17 15:50
Using Shields Up I could see Disqus comments on http://blog.dilbert.com/post/145205211401/billionaire-branding-mistakes but not on http://breitbart.com

**Comment by bbondy** [comment] 2016-08-02 05:29
https://twitter.com/JakeBryanDev/status/760232415956721664

**Comment by lukemulks** [comment] 2017-06-20 04:05
One note regarding Disqus that is worth factoring into cases like this and others. 

Disqus has a native ad product named Reveal that is fairly low profile. 

Product FAQ:
https://help.disqus.com/customer/portal/articles/2069645-reveal-f-a-q-

Placement details:
https://help.disqus.com/customer/portal/articles/1969476

The ads do have the option to opt-out, but is required by the publisher and involves the publisher contacting Disqus to disable. 

I took some screenshots from the link above to help with identification, but in a nutshell there are 3 primary ad types:

- Sponsored placement

- Sponsored text

- Sponsored tile grid

Screenshots of ad types:
![screenshot_2017-06-19-20-45-28](https://user-images.githubusercontent.com/8979240/27316044-1614f79a-5532-11e7-917e-798a9bba9340.png)
![screenshot_2017-06-19-20-45-39](https://user-images.githubusercontent.com/8979240/27316048-204d750c-5532-11e7-8a19-44789f154c38.png)

Placement locations:
![screenshot_2017-06-19-20-46-01](https://user-images.githubusercontent.com/8979240/27316065-37ad0410-5532-11e7-8e87-36c23369c501.png)

The main point, aside from the info re: ads is that Disqus might be applying multipurpose requests for ads and comments in their product (similar to how Google will use gstatic domain requests for tracking and for graphics in Drive).

If there's a better place for this note, lmk. Thanks!

**Comment by bsclifton** [comment] 2018-09-07 17:37
Confirmed this is fixed with [brave-core](https://github.com/brave/brave-browser)

**Closed by bsclifton** 2018-09-07 17:37 UTC
Labels: bug, fixed-with-brave-core, site-bug, webcompat

**Comment by bsclifton** [comment] 2018-11-20 17:50
@MisinformedDNA you should be able to just install the new version of Brave via https://brave.com/download

You'll then need to import your data. We'll be rolling out an update soon that automatically does the update and import if you wanted to wait
