### ISSUE TITLE
Tab stops to respond and can't be closed

### ISSUE THREAD

**Issue by puzzledbytheweb** [brave/browser-laptop#13286] opened 2018-02-23 19:59 UTC
### Description

Every time I use Brave after some time, one or more opened tabs stops responding and when hovered displays a gray background instead of the respective page contents. On top of that it also does not respond when I try to close it by clicking and just stays there for ever until that browser window is closed. 

### Steps to Reproduce

1. Open browser
2. Use it for normal activity for some time (can't precise exactly)
3. Try to open a tab and find it unresponsive

**Actual result:** Unresponsive Tab

![issuebrave](https://user-images.githubusercontent.com/35262512/36614014-2f116480-18d3-11e8-9b6b-8fd61adc6c0a.jpg)
![issuebrave1](https://user-images.githubusercontent.com/35262512/36614026-3b84f3e4-18d3-11e8-90b8-2faa8c86be21.jpg)

**Expected result:** Open tab

**Reproduces how often:** Every time I use the browser

### Brave Version

**about:brave info:**

 
Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: ia32 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
**Reproducible on current live release:** Yes

**Comment by Lythimus** [comment] 2018-02-27 03:41
I believe this is a duplicate of https://github.com/brave/browser-laptop/issues/9242. @puzzledbytheweb you may want to move this issue to that thread.

**Closed** 2018-03-19 18:13 UTC
Labels: bug, feature/tabsbar
