### ISSUE TITLE
Tab sets not clickable on maximized window on windows

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#8292] opened 2017-04-13 13:28 UTC
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
It is not possible to change tab sets when window is maximized
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64
- Brave Version (revision SHA):
0.14.1 but is the same in 0.14.2 Preview 2 too
- Steps to reproduce:
    1. Open 2 or more tab sets
    2. Have the window minized and change between the tab sets (Works as expected)
    3. Have the window maximized and change between tha tab sets (Nothing happends)
    
- Actual result:
Nothing happends when you click on the tab sets
- Expected result:
It should change tab set
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1. Open 2 or more tab sets
    2. Have the window maximized and change between tha tab sets
    3. Should work
    

- Screenshot if needed:
![2017-04-13_15-20-19](https://cloud.githubusercontent.com/assets/25466657/25006587/c97b4c62-205d-11e7-9fd8-31dce4f63b0d.gif)

- Any related issues:

**Comment by NoxDeleo** [comment] 2017-04-28 09:07
I've had the same issue for a while, however for me when the window is maximized, I can select the tab groups by pointing just below the rectangle. The click area is slightly offset.

**Comment by Jacalz** [comment] 2017-05-05 16:16
Okay sorry for late reply, I don´t have any where to click it when maximized :confused:

**Comment by bsclifton** [comment] 2017-05-09 06:48
Closing this issue as a duplicate of https://github.com/brave/browser-laptop/issues/7641

**Closed by bsclifton** 2017-05-09 06:48 UTC
Labels: bug, feature/tabsbar, OS/Windows
