### ISSUE TITLE
address bar input ignored if no default search engine set

### ISSUE THREAD

**Issue by allenwb** [brave/browser-laptop#3254] opened 2016-08-18 22:20 UTC
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
URL typed into address bar is ignore (after typing return) if a default search engine is not set

**Expected behavior:**
Resolve URL and display page

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version:
Brave: 0.11.5
- Steps to reproduce:
    1. using the Preferences>Search page, make sure that no search engine has a check mark in the default column. (I'm not sure how I initially got into this state because once I selected a default I couldn't get it back into the no-default set state.
    2.In a new tab, type a known good url such as brave.com into the address bar and then hit the return key
    3. nothing happens
    4. go back to the preferences?search page and select some search engine as the default
    5. repeat step ii
    6.  The requested page is display

- Screenshot if needed:

- Any related issues:

**Comment by Sh1d0w** [comment] 2016-08-19 05:07
There was a bug with an earlier version of Brave, when you update the browser to a newer version it was forgetting your default engine, so you were left in a state with no default engine. But this was fixed in version 0.11.4 if I am not mistaken.

Can you tell me if you updated Brave to a new version, right before this happened?

**Comment by mcalello** [comment] 2016-08-19 15:40
It's definitely a problem, as I thought Brave was broken.

**Comment by bbondy** [comment] 2016-08-20 00:17
@darkdh can we ask him to check something in his session file? how can users not have a default set?

**Comment by darkdh** [comment] 2016-08-20 01:06
@allenwb could you open `~/Library/Application Support/brave/session-store-1` and see what value is of the `search.default-search-engine`?

**Comment by allenwb** [comment] 2016-08-20 05:37
> "search.default-search-engine":"DuckDuckGo"

But note this is after I found, by looking at the Preferences>Search Engines page, that none of the search engines had the default check next to them.  I then set DuckDuckGo as the default and that corrected the problem.

I don't have the session-store-1 state from before that.

>how can users not have a default set?

That would seem to be the question of the hour...

**Comment by darkdh** [comment] 2016-08-20 08:21
@allenwb thanks for pointing out the display problem which will be fixed in https://github.com/brave/browser-laptop/pull/3275. However, we cannot reproduce the urlbar problem you mentioned

**Comment by darkdh** [comment] 2016-08-20 08:25
QA steps:
1. Make sure brave is closed
2. Remove `~/Library/Application Support/brave/session-store-1`
3. Open brave and go to `about:preferences#search`
4. Google should be the default search engine

**Closed** 2016-08-20 12:46 UTC
Labels: info-needed, qa-steps-specified

**Comment by Liunkae** [comment] 2016-10-16 21:10
Noting the original issue: #2956
