### ISSUE TITLE
The system cannot find message text for message number 0x%1 in the message file for %2

### ISSUE THREAD

**Issue by prkeshri** [brave/browser-laptop#1797] opened 2016-05-18 06:11 UTC
I know this is a duplicate of #350 but I could not get any solution!

This is happening with tracking-protection.

[Content]
Uncaught Exception:
Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\?\C:\win\browser-laptop\node_modules\tracking-protection\build\Release\tp_node_addon.node
at Error (native)
at process.module.(anonymous function) as dlopen
at Object.Module._extensions..node (module.js:440:18)
at Object.module.(anonymous function) as .node
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at Object. (C:\win\browser-laptop\app\trackingProtection.js:8:28)
at Module._compile (module.js:413:34)

Any solution?

What I am using is:
Node. v6.1.0
VS-2013

The tracking-protection is compiled for the same arch. (32-bit) only. Same is the case with abp-parser-cpp too! Any solution?

**Comment by luixxiul** [comment] 2016-05-18 07:50
Try to use Node v5 as README says and tell us if it still goes wrong

**Comment by prkeshri** [comment] 2016-05-18 10:24
Yes, it still persists.
Using Node v5.6.0.

**Comment by bbondy** [comment] 2016-05-18 14:03
looks like you're using a 64bit build but building that module as 32-bit.

**Comment by prkeshri** [comment] 2016-05-19 05:30
But my Windows is 32 bit. The electron-prebuilt's brave.exe is 32 bit as well as I have compiled the modules (tracking-protection, abp-filter-parser-cpp as well as spellchecker) from my native system only.
 The dumpbin utility shows about tracking-protection.node and other modules when invoked with /headers flags as follows:
PE signature found

File Type: DLL

FILE HEADER VALUES
             14C machine (x86)  : It says it's 32-bit.
... <other values>

For the electron-prebuilt too, the FILE HEADER VALUES shows x86.

**Comment by gopi1989** [comment] 2016-07-14 14:53
Hi all,

I am facing the same error.But i am using node v4.4.0

**Comment by bsclifton** [comment] 2016-09-08 07:50
Closing as issue is a dupe of https://github.com/brave/browser-laptop/issues/350

**Closed by bsclifton** 2016-09-08 07:50 UTC
Labels: duplicate
