### ISSUE TITLE
Mouse interaction with address bar seems off

### ISSUE THREAD

**Issue by cdax** [brave/browser-laptop#489] opened 2016-01-31 06:19 UTC
I'm running the current master branch on OS X El Capitan, and here are the STR:

- I cannot reproduce this issue when the browser window is full-screen, so make sure the window isn't full-screen.
- Click on the address bar, so that you can edit the text inside it.
- Move your mouse pointer vertically across the address bar, from top to bottom. The mouse pointer alternates between an arrow (near the top) and a text selector (near the bottom).
- When I try to select the address bar text while the pointer is an arrow, it just moves the browser window around.
- I'm still able to edit/select text when the pointer is a text selector. However, like I pointed out this only works in the bottom half of the address bar.

**Comment by bbondy** [comment] 2016-01-31 07:03
Dupe of #118. We'll try to get a fix soonish.

**Closed by bbondy** 2016-01-31 07:03 UTC
