### ISSUE TITLE
Can not create new Docs/Sheets/Slide via Google Drive

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#10327] opened 2017-08-07 22:03 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
From community https://community.brave.com/t/nothing-happens-new-document-in-google-drive/5322

>When I in Google Drive try to create a new document, nothing happens. I click “New” and then “Google Docs”. I have also tried to extend it at the arrow for the little option that comes up between “blank document” and “from a template”. None of them work.

It seems Brave blocked the pop-up window. Here's the notification that I get when try it using Firefox:
![firefox-doc-pop-up](https://user-images.githubusercontent.com/25360853/29047603-8f5bd444-7bf6-11e7-8674-b52ad7576b84.png)
Allowing pop-up will open a new tab and create a new doc.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10. Reproduce in Win 8.1

- Brave Version (revision SHA):
Brave: 0.18.14
rev: ad92d029e184c4cff01b2e9f4916725ba675e3c8
Muon: 4.3.6
libchromiumcontent: 60.0.3112.78
V8: 6.0.286.44
Node.js: 7.9.0
Update Channel: dev
OS Platform: Microsoft Windows
OS Release: 10.0.15063
OS Architecture: x64

- Steps to reproduce:
    1. Open Google Drive
    2. Click `New` > `Google Docs` or click `New` > `Google Docs` > `Blank document/From a template`
    3. Nothing happens
    
- Actual result:
Nothing happens

- Expected result:
It's open and create a new docs

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by eljuno** [comment] 2017-08-07 22:06
Other user reported that it's work fine in Linux Ubuntu
https://community.brave.com/t/nothing-happens-new-document-in-google-drive/5322/2?u=eljuno

**Comment by bsclifton** [comment] 2017-08-08 23:20
I believe this is the root cause:
https://github.com/brave/browser-laptop/issues/3752

I'd like to close this as duplicate. Maybe it works OK in Ubuntu because Google Apps serve different content based on the OS?

**Closed by bsclifton** 2017-08-08 23:20 UTC
Labels: webcompat
