### ISSUE TITLE
Missing context menu for find in page edit dialog

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#2749] opened 2016-07-28 13:53 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When using the find on page functionality, a dialog opens for the user to input text to match. 

**Expected behavior:**
Editable fields should have a context menu for cut/copy/paste.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on OSX
- Brave Version:
  0.11.2
- Steps to reproduce:
  1. Navigate to a site with text.
  2. Open the find on page dialog.
  3. Right-click on the dialog to open a context menu.
- Screenshot if needed:
- Any related issues:

**Comment by Liunkae** [comment] 2016-11-20 00:26
Duplicate of #4975, which was fixed with d7d2718.

**Closed by Liunkae** 2016-11-20 00:26 UTC
Labels: bug/good-first-bug
