### ISSUE TITLE
God tabs? Can't close, mute, open in new window, or click on these tabs?! [Windows 10] [Desktop]

### ISSUE THREAD

**Issue by TheCNixon** [brave/browser-laptop#11839] opened 2017-11-08 06:46 UTC
Essentially I can't click on, mute or close tabs that are acting like this, having to completely close the browser AND FORCE CLOSE BACKGROUND PROCESSES OF BRAVE TO GET THE SOUND TO STOP???! On top of that I can still see what they're doing if I mouse over them, but this is my only hope to see it without doing all I said a moment ago.

Here is a link to what is happening, I messed up when going to record my audio but the issue is still clearly seen as I can't even drag these tabs to their own window.
https://www.youtube.com/watch?v=4fZRIMMfPMw

Running:
```
WIndows 10 on an SSD
FX 8350
8gb Ram
GTX 970
```

Brave about:
```
Name | Version
-- | --
Brave | 0.19.80
rev | 7d07299
Muon | 4.5.13
libchromiumcontent | 62.0.3202.75
V8 | 6.2.414.36
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.14393
OS Architecture | x64
```

**Comment by luixxiul** [comment] 2017-11-08 07:09
That'll be fixed with 0.20 release.

**Comment by TheCNixon** [comment] 2017-11-08 07:56
Thank you!

**Comment by luixxiul** [comment] 2017-11-08 08:55
Closing for now. Please try the latest beta and see if the issue is still experienced. Please don't forget to create a backup when you test the beta!

On our community site there is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!

https://community.brave.com/

**Closed by luixxiul** 2017-11-08 08:55 UTC
Labels: bug, duplicate, feature/tabsbar

**Comment by TheCNixon** [comment] 2017-11-09 08:21
These are still persistant in the new beta, it occurs usually after the pc has been on sleep for the night. They show up as grey and are still resistant to closing, clicking or hovering over with the only option being to reload and lose our data.
`

Name | Version
-- | --
Brave | 0.20.6

`
