### ISSUE TITLE
JavaScript error prevents history page search component from working

### ISSUE THREAD

**Issue by gartz** [brave/browser-laptop#14872] opened 2018-07-30 23:28 UTC
### Description
The history page `about:history` the component to search on the top right corner is not working, seems to be some kind of bad data binding that prevents the component to allow typing any word to search.

### Steps to Reproduce
  1. Navigate to multiple different websites, using multiple tabs and some pin tabs
  2. Open the `about:history`
  3. Try to type any word in the search box (it won't display anything typed and won't search)

**Actual result:**
<img width="252" alt="history 2018-07-30 16-26-44" src="https://user-images.githubusercontent.com/99608/43428878-67af07b2-9415-11e8-87e5-8539a45e1f70.png">

**Expected result:**
Allow to type and filter the list of results as the word match it.

**Reproduces how often:**
100% of time in my Brave

### Brave Version

**about:brave info:**
 
Brave: 0.23.39 
V8: 6.7.288.46 
rev: 3ee14b026f09d7d71c1985b4a9c9a11d78ab8f49 
Muon: 7.1.6 
OS Release: 18.0.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**

**Comment by bsclifton** [comment] 2018-08-14 21:57
@gartz I can't reproduce - do you have any more info? Maybe you can open up the console? (ex: push Cmd + Opt + I) and see if any JavaScript errors are being logged

**Comment by gartz** [comment] 2018-08-14 22:53
<img width="456" alt="about-history html 2018-08-14 15-46-46" src="https://user-images.githubusercontent.com/99608/44122548-4aff4d82-9fd9-11e8-92dc-524e0515585e.png">
```
            searchedSiteDetails(e, n) {
                return n.filter(n=>(n.get("title") + n.get("location")).match(new RegExp(e,"gi")))
            }
```

I guess that a workaround could be:

```
            searchedSiteDetails(e, n) {
                return n.filter(n=>`${n.get("title")||""}${n.get("location")||""}`.match(new RegExp(e,"gi")))
            }
```

But probably the problem is that `title` and `location` of `n` are both `undefined` for some reason in my list and that result in `NaN` instead of a string.

**Comment by bsclifton** [comment] 2018-09-07 06:48
Unfortunately, this is one we won't fix with our current code-base... but it should be working great in our developer channel build if you wanted to give it a shot:
https://brave.com/download-dev

**Closed by bsclifton** 2018-09-07 06:48 UTC
Labels: bug, feature/history, fixed-with-brave-core, wontfix
