### ISSUE TITLE
Opening about page in a new tab on about:about does not display the tab title correctly

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7956] opened 2017-03-29 09:47 UTC
**Describe the issue you encountered:** Opening about page in a new tab on about:about does not display the tab title correctly. The tab title starts with `chrome-extensions://`. The issue cannot be reproduced by opening the tab with the middle mouse button.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.14.0 RC1

- Steps to reproduce:
    1. Clear your profile and start the browser
    2. Open about:about
    2. Open any about page with "Open Link in New Tab"
    
- Actual result:
  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/24448904/8acc0f46-14b0-11e7-8545-35d031a6199c.jpg)

- Expected result: the tab title should be displayed correctly

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment] 2017-03-29 09:54
Updated the description.

**Comment by cezaraugusto** [comment] 2017-06-08 04:54
is this still happening to you? seems fixed in master

**Comment by bsclifton** [comment] 2017-06-26 20:47
I believe this is a dupe of https://github.com/brave/browser-laptop/issues/7765

**Closed by bsclifton** 2017-06-26 20:47 UTC
Labels: bug, feature/about-pages, feature/context-menu, QA/required, regression
