### ISSUE TITLE
disable swipe between pages

### ISSUE THREAD

**Issue by broros** [brave/browser-laptop#6975] opened 2017-02-01 05:39 UTC
- Did you search for similar issues before submitting this one? yes

- Describe the issue you encountered:  disable directional scroll, browser will go to previous page when swiping left or right even when swipe between pages is turned off in macOS settings.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): 0.13.0

- Steps to reproduce:
    1.  move finger left or right on magic mouse
    2. browser will  go to previous page
    3.
    
- Actual result: browser will  go to previous page

- Expected result: no scrolling to previous page

- Is this an issue in the currently released version? yes

- Can this issue be consistently reproduced? yes

**Comment by luixxiul** [comment] 2017-02-01 10:18
Dupe of #5907

**Closed by luixxiul** 2017-02-01 10:18 UTC
