### ISSUE TITLE
Can't cut & paste

### ISSUE THREAD

**Issue by Suzbeck** [brave/browser-laptop#4490] opened 2016-10-04 04:44 UTC
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
tried several times to cut & paste info from websites into word docs or salesforce, nothing happens.
**Expected behavior:**
should paste characters in appropriate fields

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac os Yosemite
- Brave Version:
newest

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by jkup** [comment] 2016-10-04 06:45
Can reproduce on macOS. Cut does not work but Copy does.

**Comment by bsclifton** [comment] 2016-10-04 07:25
@Suzbeck @jkup do you have more info? Cut is not working inside input fields? 

Asking because I noticed that `Edit -> Cut` is still available from the menu, even though it shouldn't be.

**Comment by jkup** [comment] 2016-10-04 07:31
@bsclifton both Edit -> Cut as well as cmd + x are not working as far as I can tell anywhere. For example if I highlight the word info and cmd + x and then Edit -> Cut nothing new gets put in my clipboard.

**Comment by bsclifton** [comment] 2016-10-04 07:58
@jkup comparing behavior to Chrome, we seem to be matching it. Cut should only be copying text at the expense of deleting the text that was selected (IMO). If the text is read only, technically you shouldn't be allowed to cut

We could remove cut from the menu and then trigger a beep so the user knows they can't do it

cc: @bradleyrichter

**Comment by jkup** [comment] 2016-10-04 23:48
@bsclifton you are totally right. I must have messed up last night (I thought Chrome copied when it couldn't Cut).

@Suzbeck Are you able to Cut inside text fields?

**Comment by Liunkae** [comment] 2016-10-05 05:13
Cutting from text fields here on GitHub and pasting into TextEdit works fine for me. Menubar Edit > Cut, context menu Cut, and Cmd+X all work. Brave 0.12.3 on macOS 10.12.

**Comment by jkup** [comment] 2016-10-05 05:14
I'm gonna go ahead and close this for now. @Suzbeck if you are unable to Cut from an input let me know and I'll reopen!

**Closed by jkup** 2016-10-05 05:14 UTC
