### ISSUE TITLE
URL suggestions do not go away on clearing history without quitting app

### ISSUE THREAD

**Issue by patrick99e99** [brave/browser-laptop#9884] opened 2017-07-06 02:42 UTC
From the search bar:

I visit americanbandstand.com
I visit americandiet.com

The next time I type in enter into the search bar: "amer", I will be presented americanbandstand.com and americandiet.com as options from my history.

I go to History > Show History

I choose "clear browser data" and turn on browser history, and click clear.

I close the history page.

I click the URL bar and type "amer" I will be presented americanbandstand.com and americandiet.com as options from my history.

In order to make them go away, I have to quit and relaunch Brave.

**Comment by Liunkae** [comment] 2017-07-07 21:23
+1 from me with Brave 0.17.13 on macOS 10.12.x.

**Comment by bsclifton** [comment] 2017-07-12 23:52
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/9736

**Closed by bsclifton** 2017-07-12 23:52 UTC
Labels: bug, feature/history, privacy
