### ISSUE TITLE
Black screen only

### ISSUE THREAD

**Issue by mjank75** [brave/browser-laptop#336] opened 2016-01-26 15:50 UTC
Windows 7 64bit.  Go through the install and it just comes up with a black screen.  Right click option are view page source and reload.  They don't do anything.  
![image](https://cloud.githubusercontent.com/assets/16901635/12585573/40c843aa-c412-11e5-8fa8-20b38c7f9b27.png)

**Comment by bbondy** [comment] 2016-01-26 16:04
Dupe of #189 thanks for posting though.  We'll try to fix soon so we can get extra testing on Windows.

**Closed by bbondy** 2016-01-26 16:04 UTC
