### ISSUE TITLE
Can't push button in Widevine notification bar on Netflix

### ISSUE THREAD

**Issue by pullingour** [brave/browser-laptop#11200] opened 2017-09-28 12:04 UTC
### - Did you search for similar issues before submitting this one?
Yes

### - Describe the issue you encountered:
When I visit to Netflix, Google Widevine popup is appeared.
push "allow" button, nothing happen. Videos are can be played but popup has never gone.
When I enter Full-screen mode popup would be hidden and all fine but when I escape full-screen mode, Widevine popup still exist under the tabs.
This problem is always happen even though restart Brave or OS.

### - Platform (Win7, 8, 10? macOS? Linux distro?):
OS X El Capitan 10.11.6

### - Brave Version
7ab85e9

### Screen Shot
![out](https://user-images.githubusercontent.com/7346730/30965757-73580c0e-a491-11e7-9a64-f597161f4dd2.gif)

**Comment by bsclifton** [comment] 2017-09-28 17:49
@pullingour when this happens, do any errors show in the browser developer tools? You can open this up by pressing Shift + F8 (if you're on a laptop, you may need to press fn + shift + F8)

**Comment by bsclifton** [comment] 2017-09-28 17:52
actually it seems this is a dupe of https://github.com/brave/browser-laptop/issues/11054.  This will be fixed in our next release 😄 

per comment by @bbondy:
> you'd have to use fresh profile because problem is at the point of the notification bar displaying, and if you have it already saved it won't hit that code.

**Closed by bsclifton** 2017-09-28 17:52 UTC
Labels: feature/notificationbar

**Comment by pullingour** [comment] 2017-09-28 23:42
@bsclifton 
> when this happens, do any errors show in the browser developer tools? 
<img width="836" alt="screen shot 2017-09-29 at 08 30 23" src="https://user-images.githubusercontent.com/7346730/30994767-c76205fc-a4f0-11e7-9f90-de07daf47b85.png">  
I couldn't find #11054 😅 I'm looking forward to next release. Thank you for dev 😄

------   

@luixxiul Thanks for fix title. It's not popup but notification bar 😳

**Comment by pullingour** [comment] 2017-10-13 07:35
It fixed now! de939f6
Thank you for developers~ :-D
