### ISSUE TITLE
Allow dragging a bookmark from the bookmark manager into the toolbar

### ISSUE THREAD

**Issue by evq** [brave/browser-laptop#7640] opened 2017-03-09 02:16 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
I was trying to reorder a bookmark and one of the methods I attempted was to drag and drop from the bookmark manager directly into the bookmarks toolbar, which works on Chrome.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS / Linux

- Brave Version (revision SHA):
7373a01

- Any related issues:
Possibly can be considered part of #6245 / #6246?

**Comment by Liunkae** [comment] 2017-03-12 23:54
Also works with Firefox. Tagged for parity.

**Comment by bsclifton** [comment] 2017-04-19 04:43
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/8067 (which has a much larger scope)

**Closed by bsclifton** 2017-04-19 04:43 UTC
Labels: feature/bookmarks, misc/drag-and-drop, parity
