### ISSUE TITLE
Address Bar Freezes GUI

### ISSUE THREAD

**Issue by disbelieveordoubt** [brave/browser-laptop#15297] opened 2018-10-18 12:44 UTC
### Description
Typing into the address bar (still) results in an approximately 3-4 second full-browser freeze, sometimes giving a "brave.exe is not responding" message from Windows in the top left corner.  All GUI elements become unresponsive, and text input is occasionally lost when the browser resumes again.

### Steps to Reproduce
  1. Ensure you have imported bookmarks/passwords from Chrome and that Brave Payments are enabled.
  2. Ensure a page is loaded.  
  3. Click on (or press alt+D) the address bar and begin typing.  (CPU usage should rise, you may hear your fan spin up.)
  4. Watch the browser come to a complete halt for 3-4 seconds, looks like a database is freezing on lookup
  5. Visit any new webpage to repeat steps 2 and 3.

**Actual result:**
Brave.exe freezes on text input to the address bar.  It cannot be closed or given inputs for 3-4 seconds afterward on a modern desktop.

**Expected result:**
Brave.exe does not freeze, accepts text input without issues.

**Reproduces how often:**
99.999%

### Brave Version

Brave | 0.25.2
-- | --
V8 | 6.9.427.23
rev | 8ea2a9c
Muon | 8.1.8
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.100

**Reproducible on current live release:**
Yes.

### Additional Information
You may need to have a webpage loaded already to generate this bug.  Brave.exe seems to freeze a lot, making it unusable as a primary browser.  Ctrl+F and text selection result in freezes as well.  The payments screen freezes almost every time I try to access it following an import of data from Chrome.  Removing all but ~25 bookmarks did not resolve any of these issues.

**Comment by bsclifton** [comment] 2018-10-18 17:31
Thanks for the report @disbelieveordoubt! I'm going to those this report as this is a duplicate of issue https://github.com/brave/browser-laptop/issues/12975

Our recommendation at this point is to switch over to our new code-base, which is on the Beta channel (and will have a Release channel build coming soon).  The problem is fixed there and you can import your existing profile. You can download this new version here:
https://brave.com/download-beta

**Closed by bsclifton** 2018-10-18 17:31 UTC
