### ISSUE TITLE
Add links to our wiki to the menus

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6559] opened 2017-01-06 16:41 UTC
**Describe the issue you encountered:**
Add links to our wiki (https://github.com/brave/browser-laptop/wiki) to menu.js and contextMenus.js

https://community.brave.com/t/brave-help-add-a-help-manual-module-to-brave/259

**Expected behavior:**

- Brave Version (revision SHA): 0.12.15

- Any related issues: #6499. The links would be added based on what was deleted with https://github.com/brave/browser-laptop/pull/6499/commits/cd4af19c258b21db66d136eb1b04ef9fea239381 of the PR

**Comment by rnsjunkmail** [comment] 2017-01-16 03:02
I downloaded and am using 0.12.15, but I do not see a HELP option under HELP or anywhere else for that matter.

**Comment by bsclifton** [comment] 2017-05-12 06:04
Closing this as a dupe of https://github.com/brave/browser-laptop/issues/6940 (which has more info).  I think the wiki may be too technical

@rnsjunkmail sorry for the super late reply here- if you still use Brave, I'm guessing you're on Windows. You can toggle the menu showing by pressing ALT

**Closed by bsclifton** 2017-05-12 06:04 UTC
Labels: suggestion
