### ISSUE TITLE
Alexa.com won't load CSS with Brave ads blocked

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#3436] opened 2016-08-26 02:01 UTC
![image](https://cloud.githubusercontent.com/assets/13509546/17991732/2093396a-6af6-11e6-8082-680fcc8026d1.png)

**Comment by srirambv** [comment] 2016-08-26 12:44
same as #2838

**Comment by Liunkae** [comment] 2017-02-03 06:48
Closing as a duplicate of #2838.

**Closed by Liunkae** 2017-02-03 06:48 UTC
Labels: webcompat
