### ISSUE TITLE
payments 'show all' button position is off

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#9129] opened 2017-05-29 18:52 UTC
Brave: 0.15.310 
rev: 6b5e4e2d300959848e0e848817aa40385447f2eb 
Muon: 3.0.201 
libchromiumcontent: 58.0.3029.110 
V8: 5.8.283.38 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: darwin 
os.release: 15.6.0 
os.arch: x64

in about:preferences#payments, the 'show all' button is too high up:
![screen shot 2017-05-28 at 1 22 56 pm](https://cloud.githubusercontent.com/assets/549654/26559550/352e9178-4465-11e7-83ea-06c7ff8c68ee.png)

**Comment by srirambv** [comment] 2017-05-29 18:59
Dupe of #8869

**Closed by srirambv** 2017-05-29 18:59 UTC
Labels: feature/ledger

**Comment by diracdeltas** [comment] 2017-05-29 19:01
thanks @srirambv. sorry i couldn't find the dupe.

**Comment by luixxiul** [comment] 2017-05-30 03:32
just fyi trying google instead is easier to find dupes: `:g github brave show all button ledger` as long as they've been indexed, which is likely.
