### ISSUE TITLE
OSX update silently fails

### ISSUE THREAD

**Issue by Sjors** [brave/browser-laptop#8029] opened 2017-04-01 09:17 UTC
I've experienced this with two version updates so far.

I see "A Brave update was just released", I click on Update, the browser restarts and a few minutes later it shows the same update again. This goes on forever, until I manually download and install the new version.

My current Brave version is 0.13.5 (1db81cb) and it's prompting me for the 0.14.1 update.

```
Brave: 0.13.5 
rev: 1db81cb18b6919535792bb7e198ab87276bd67ea 
Muon: 2.56.8 
libchromiumcontent: 56.0.2924.87 
V8: 5.6.326.50 
Node.js: 7.4.0 
Update Channel: dev 
os.platform: darwin 
os.release: 16.4.0 
os.arch: x64
```

My Mac has multiple users and I'm logged in as a user who does not have admin rights. It's also not prompting me for admin login details, which other applications do when they request an upgrade.

My guess would be that Brave doesn't check for permission and just crashes and restarts. It's not generating a crash report though; the last crash report is from 2017-03-19, which was some other issue.

**Comment by Liunkae** [comment] 2017-04-02 02:42
Related to/duplicate of #2184.

**Comment by Sjors** [comment] 2017-04-02 07:55
@Liunkae thanks, I must have used the wrong search terms.

**Comment by Liunkae** [comment] 2017-04-03 03:02
@Sjors: Thanks. Closing as a duplicate of #2184.

**Closed by Liunkae** 2017-04-03 03:02 UTC
Labels: bug, installation, OS/macOS
