### ISSUE TITLE
 Brave quits when New Tab command issued without window

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#8575] opened 2017-04-29 16:24 UTC
A Brave Community contributor reported the following Issue: 

>*Brave quits when New Tab command issued without window*

**Brave Community thread:**
https://community.brave.com/t/brave-quits-when-new-tab-command-issued-without-window/2509

>*Details below have been extracted from the Community thread*

**Browser Profile**
```
macOS 10.12.4 
Macbook Pro
Brave v0.15.0 
rev 71fb730
```

**Steps to Repro:** 

- Open Brave
- Close all open tabs. 
- Brave should still be open (in macOS, you'll see the "Brave" application menu) but there are no windows (confirm in the Window menu).
- Go to File > New Tab, or in macOS, type Cmd-T.
- Brave quits.

**Potentially related to:** 
This may be related to another unexpected behavior:  
- Open Location command (macOS = Cmd-L) when there is no open window. 
- If there are no open windows and I type Cmd-L, I expect Brave to create a window and give focus to the location bar. 
- But it does nothing. 
- It was after this failed that I tried Cmd-T and found the bug.

**Expected Behavior**
Both New Tab and Open Location should create a new window if no window exists at the moment.

**Comment by rucksack-texnology** [comment] 2017-04-29 18:32
Not just a laptop issue. Same misbehavior occurs on iMac running same version of macOS (10.12.4) and same version of Brave (0.15.0).

**Comment by bsclifton** [comment] 2017-05-03 08:53
Confirmed

**Comment by bsclifton** [comment] 2017-05-03 08:54
Moving to 0.15.2; if we don't have time, we can push back. But wanted to tentatively pull in since it does cause a crash

**Comment by bsclifton** [comment] 2017-05-06 07:20
```
2017-05-06 00:19:52.876 Brave Helper[5875:1106224] Couldn't set selectedTextBackgroundColor from default ()
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'id' of null
    at getCurrentWindowId (/Users/clifton/Documents/browser-laptop/app/common/commonMenu.js:33:43)
    at click (/Users/clifton/Documents/browser-laptop/app/common/commonMenu.js:78:19)
    at MenuItem.click (/Users/clifton/Documents/browser-laptop/node_modules/electron-prebuilt/dist/Brave.app/Contents/Resources/electron.asar/browser/api/menu-item.js:59:9)
    at Function.executeCommand (/Users/clifton/Documents/browser-laptop/node_modules/electron-prebuilt/dist/Brave.app/Contents/Resources/electron.asar/browser/api/menu.js:121:15)
```

**Closed** 2017-05-06 07:51 UTC
Labels: crash, OS/macOS
