### ISSUE TITLE
Submit feedback under helpful hints opens about:blank page and not community webpage

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6252] opened 2016-12-16 12:18 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Submit feedback under helpful hints opens about:blank page and not community webpage

**Expected behavior:**
Should launch https://community.brave.com/ when click on submit feedback

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 4

- Steps to reproduce:
    1. Open preferences page
    2. Click on Submit feedback link under helpful hints
    3. Opens about:blank tab but doesn't open community webpage
    4. Select Submit Feedback/Report an issue from menu, opens up community webpage
    5. Select Submit Feedback/Report an issue from hamburger menu, opens up community webpage

- Screenshot if needed:
![feedback](https://cloud.githubusercontent.com/assets/17010094/21262533/adecc5a6-c389-11e6-882d-3402b9a62de6.gif)

- Any related issues:

**Comment by luixxiul** [comment] 2016-12-16 15:13
I think this is duping to #6152

**Comment by bsclifton** [comment] 2016-12-19 17:13
#5880 had a similar issue, but perhaps not the same.  It was resolved with https://github.com/brave/electron/commit/bd3e9a225bf087998c4ffe85b22e36489b9f4a3f

The root cause for this may be it's trying to load from inside an extension (the Brave extension)

**Comment by bridiver** [comment] 2016-12-19 20:20
dup #6152

**Closed by bridiver** 2016-12-19 20:20 UTC
Labels: chromium54
