### ISSUE TITLE
Deleting saved password still shown until page refresh

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8906] opened 2017-05-17 11:14 UTC
## Test plan

https://github.com/brave/browser-laptop/pull/9085#issue-231739942

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Deleting saved password still shown until page refresh

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.304
rev	b872523
Muon	3.0.103

- Steps to reproduce:
    1. Keep Brave builtin password manager
    2. Visit any site and save the login details
    3. Open about:passwords, click on the delete button next to the saved entry, doesn't clear, reload the page and the entry is gone
    
- Actual result:
Deleting saved password still shown until page refresh

- Expected result:
Should clear the entry from table after clicking the delete button

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![passwords](https://cloud.githubusercontent.com/assets/17010094/26151353/5e2679d4-3afa-11e7-87e9-d8759290191e.gif)

- Any related issues:

**Comment by diracdeltas** [comment] 2017-05-17 21:26
dupe of #8874 item 1

**Closed** 2017-06-09 23:51 UTC
Labels: bug, duplicate, feature/about-pages, feature/password-manager, QA/steps-specified, regression
