### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by tysc** [brave/browser-laptop#764] opened 2016-02-14 04:10 UTC
Windows 10 x64, installed, uninstalled, reinstalled multiple times. Still nothing.

**Comment by tysc** [comment] 2016-02-14 04:13
Also, it just opens and I get the white window outline at the top and it kind of tints my screen black then closes. No task in taskmngr

**Comment by Charletg** [comment] 2016-02-15 15:33
Same problem with windows 7 Entreprise SP1 x64

**Comment by tysc** [comment] 2016-02-15 21:01
No update in 2 days ffs

**Comment by bbondy** [comment] 2016-02-15 21:10
Could you try renaming this folder out of the way:
%appdata%\brave

and then start up again?

**Comment by Charletg** [comment] 2016-02-16 10:57
I tried but same behaviour.

**Comment by bbondy** [comment] 2016-02-16 12:51
@aekeus know how we can geta hold of this crash dump?

**Comment by aekeus** [comment] 2016-02-16 13:34
I will investigate where the local crash files are stored in Windows.

**Comment by weems** [comment] 2016-02-16 14:57
likely AppData folder, right @bbondy?

**Comment by bbondy** [comment] 2016-02-16 15:59
I think it's likely somewhere in appdata, Aubrey will confirm where more specifically.

**Comment by tysc** [comment] 2016-02-17 00:06
didnt work @bbondy (renaming %appdata% brave)

**Comment by bmaisonn** [comment] 2016-02-26 08:31
Hi all,
I've encounters the same crash on windows 7 with version 0.7.16. I just see it open and close.
Tried to rename %appdata%\brave but it still crashes.
Strange because it worked fine before i close and stop my laptop.

**Comment by luixxiul** [comment] 2016-05-14 11:08
Does this problem appear on the latest version too?

**Comment by luixxiul** [comment] 2016-05-16 01:43
Should be fixed, closing for now. Please download the latest version and try again. If this error still exist please leave a comment to reopen this. Thanks.

**Closed by luixxiul** 2016-05-16 01:43 UTC

**Comment by remillc** [comment] 2016-05-20 20:42
Yes, the problem is still present on the latest version.
