### ISSUE TITLE
brave tries to save brave.exe when opened

### ISSUE THREAD

**Issue by msieng** [brave/browser-laptop#6075] opened 2016-12-07 21:11 UTC
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by icecoldsquirrel** [comment] 2016-12-07 22:09
Facing the same problem with Win 8.1 Browser/Laptop 0.12.13 via Update.

**Comment by josiah-keller** [comment] 2016-12-08 05:05
I can reliably reproduce this on Windows 10.  On app launch, the first tab navigates to `file:///C:/Users/Josiah/AppData/Local/brave/app-0.12.13/Brave.exe`, which launches the Save As... dialog.  However, this only occurs from my taskbar shortcut.  Launching Brave from my Start tile opens the browser to the New Tab page as expected.

The taskbar shortcut points to: `C:\Users\Josiah\AppData\Local\brave\Brave.exe --processStart "Brave.exe"`

The start shortcut points to: `C:\Users\Josiah\AppData\Local\brave\Update.exe --processStart "Brave.exe"`

**Comment by msp1111111** [comment] 2016-12-08 12:35
Same. Win 7 0.12.13. Also is making it so my preferences won't open and passwords (saved by Brave) won't load.

**Comment by srirambv** [comment] 2016-12-08 15:06
+1 from [support ](https://linkbubble.zendesk.com/agent/tickets/7201)

**Comment by mbretttx** [comment] 2016-12-08 15:06
Experiencing same on Windows 7 ver 6.1.7601. Brave ver 0.12.13. Brave does start & have not found any issues. I saved the brave.exe file and tried to run it which gave me the error 'The program can't start because node.dll is missing from your computer.

Did some quick research & found the following info:
We don't advise to download the node.dll file and copy it to the Windows system directory. The software's creators almost never circulate the DLL files, they are always part of an installation set. It's the installation set's task to perform the sufficient verifications before the installation. An incorrectly installed DLL file may cause the system's complete inability to function.
If you need a DLL file in spite of the above for the sake of restoring a system, then download it from a reliable source, possibly from the manufacturer's site.

**Comment by bsclifton** [comment] 2016-12-08 17:23
May or may not be related to https://github.com/brave/browser-laptop/issues/5749

**Comment by bsclifton** [comment] 2016-12-08 17:27
@mbretttx `node.dll` should already be included; if you were up for troubleshooting, I can help you with some next steps

Basically, you should be able to navigate to:
`%userprofile%\AppData\Local\brave`

From there, you'll see Update.exe.  That's the executable that should be launching when you have Brave pinned (specifically, the pinned shortcut should be executing `C:\Users\brian\AppData\Local\brave\Update.exe --processStart "Brave.exe"` (except with your path of course)

Try opening the 0.12.13 folder and inspecting what's there. You should see both the Brave.exe and node.dll (among other files)
![screen shot 2016-12-08 at 10 27 22 am](https://cloud.githubusercontent.com/assets/4733304/21020253/f882e7bc-bd30-11e6-9699-dec0d6def59a.png)

Let me know how that looks

**Comment by takujun** [comment] 2016-12-08 20:35
I just found my file Brave.exe and BraveSetup-x64.exe. So I click on BraveSetup-x64 one, it came out good.
It is seems like fix it !

**Comment by msp1111111** [comment] 2016-12-08 22:10
I had Brave pinned to my taskbar and clicking on that made this error happen. When I clicked on the desktop shortcut that Brave created when updating, it worked fine. I got rid of my taskbar shortcut and replaced it with the new one, now everything is OK. Not sure what the old pinned taskbar shortcut was pointing to.

**Comment by mbretttx** [comment] 2016-12-08 23:31
@bsclifton I looked at 0.12.13 as you suggested everything looked ok. However, when I opened the file location that my desktop shortcut was pointing to it was not the same. The file location did not contain app-0.12.13. It only had app-01.12.11 . I removed the pinned shortcut, then ran BraveSetup-x64 as suggested by @takujun. The problem went away, startup worked as it should.  I then re-pinned the shortcut to the task bar, shutdown Brave and restarted it using the new pinned shortcut. There were no problems, everything worked as it should. Also, the new shortcut is now pointing to the correct set of files.  Looks like running BraveSetup-x64 fixed the problem. So now that we have a fix, perhaps tech support might be able to figure out the cause, so that we don't have a re-occurrence in the future.

**Comment by gabriel1313** [comment] 2016-12-09 00:39
Have been using the pinned taskbar Brave icon for the last few days without problem. Only just now, 8:34pm 8 Dec 16, on opening Brave tried to save a new copy of itself to the Downloads folder. Closed Brave, removed the pinned taskbar icon. Opening Brave from the Start menu works fine. Pinned this icon to the taskbar and closed Brave. The new pinned Brave taskbar icon works without problems. (Using Windows 10 64bit, Classic Start Menu, Brave 0.12.13).

**Comment by srirambv** [comment] 2016-12-09 09:12
+1 from [support ](https://linkbubble.zendesk.com/agent/tickets/7210)

**Comment by srirambv** [comment] 2016-12-09 09:28
I tried upgrading from 0.12.11 and 0.12.12 but cannot repro this. It always opens up the browser with no prompt to save.

**Comment by mbretttx** [comment] 2016-12-09 10:20
@srirambv It looks like everyone the problem was with 0.12.13, rather than 0.12.12. When I looked at my problem I found that my pinned shortcut was pointing to the files for 0.12.11 rather than 0.12.13. This was resolved by deleting the shortcut running the x64 exe and producing a new shortcut. In fact, during my process of troubleshooting, I found nothing on my system regarding 0.12.12.

**Comment by srirambv** [comment] 2016-12-09 15:18
@mbretttx There were couple of reports stating after upgrade to 0.12.13 the issue started to happen hence I tried upgrading from the previous two version to see if it can be reproduced but with no luck. 

+1 from [support ](https://linkbubble.zendesk.com/agent/tickets/7219)

**Comment by srirambv** [comment] 2016-12-09 15:20
1 more from [support](https://linkbubble.zendesk.com/agent/tickets/7218)

**Comment by jonathansampson** [comment] 2016-12-11 06:52
I too am facing this on Windows 10, 14393.

**Comment by msieng** [comment] 2016-12-11 11:38
It is related to the update.  As soon as Brave updated, the pinned icon led to the file save.  I deleted and repinned, problem solved.

**Comment by srirambv** [comment] 2016-12-12 11:42
+1 from [support ](https://linkbubble.zendesk.com/agent/tickets/7258)

**Comment by srirambv** [comment] 2016-12-12 12:43
More from support 

https://linkbubble.zendesk.com/agent/tickets/7245
https://linkbubble.zendesk.com/agent/tickets/7242
https://linkbubble.zendesk.com/agent/tickets/7240
https://linkbubble.zendesk.com/agent/tickets/7234
https://linkbubble.zendesk.com/agent/tickets/7233

**Comment by bsclifton** [comment] 2016-12-12 21:39
My characterization of the issue:
- Squirrel is the auto-updater used to install/update Brave
- Squirrel is supposed to automatically download the latest version of Brave and prompt you to upgrade (which requires quitting and restarting Brave)
- Somehow, Squirrel thinks it has updated Brave to a newer version (but it didn't). It can't find the executable
- Squirrel prompts you to locate the executable

**Comment by bsclifton** [comment] 2016-12-12 21:59
Issue opened in Squirrel repo:
https://github.com/Squirrel/Squirrel.Windows/issues/900

If you see this issue, please help us capture as much detail as possible.  For example:
- Did this occur after an upgrade you were prompted for?
- What version were you on before (if you know)?
- What version is Brave looking for?
- What does your Brave shortcut point to? (right click, properties- target)

Thanks :smile:

**Comment by bsclifton** [comment] 2016-12-12 23:40
OK nice- I was able to reproduce...

**Comment by Liunkae** [comment] 2016-12-13 03:53
Two more reports: #6167 and #6168

**Comment by Liunkae** [comment] 2016-12-13 03:57
I'll quote @Jes4Kix from https://github.com/brave/browser-laptop/issues/6167#issuecomment-266604151:
> I looked at the toolbar Brave Icon properties/target field and found the following
C:\Users\Keith\AppData\Local\Brave\Brave.exe -process Brave.exe
The Desktop Brave Icon properties/target field has the following
C:\Users\Keith\AppData\Local\Brave\Brave.exe
Desktop Icon launches Brave as expected.
When "-process Brave.exe" is removed from the properties/target field Brave launches as expected.
Guess the question is, How did "-process Brave.exe" get written to the icon properties/target field?

**Comment by bsclifton** [comment] 2016-12-13 04:16
Awesome, thanks for the triage, @Liunkae 

Folks- I believe I understand the root cause and will be working on a fix tonite.  If we can confirm this fix works, we'll be able to roll out a new version tomorrow :smile: 

As a work-around for anyone reading this, you'll be able to launch brave just fine if you update your shortcut to point at Update.exe.

For example, when I right click the taskbar, pick properties, and look at the target, mine is set to:
`C:\Users\brian\AppData\Local\brave\Brave.exe --processStart "Brave.exe"`

To fix myself, I can update this to be:
`C:\Users\brian\AppData\Local\brave\Update.exe --processStart "Brave.exe"`

Another easy fix would be to just delete the folder containing Brave (this does not have you session data). Navigate to %USERPROFILE%\AppDir\Local\ and delete the Brave folder.  Then, you should be able to re-install and be back in business

**Comment by bsclifton** [comment] 2016-12-13 06:56
If you're really bored, here's an overview I just typed up about how the auto update process works:
https://github.com/brave/browser-laptop/wiki/How-auto-updates-for-Brave-work-on-Windows

We should be able to deliver a fix tomorrow! :smile: Hang in there please

**Comment by bbondy** [comment] 2016-12-13 14:50
moved to 0.12.15

**Closed** 2016-12-13 15:11 UTC
Labels: bug, OS/Windows, priority/high, release/blocking

**Comment by hockey97** [comment] 2016-12-13 18:08
Yes, tried the fix and it works. 

My shortcut / launcer target was Brave.exe. 

I changed it to Update.exe by itself didn't work until I added --processStart "Brave.exe"  with it and it now works perfectly can launch the browser as I normally would.

**Comment by bsclifton** [comment] 2016-12-14 01:16
+3 from folks here:
https://github.com/brave/browser-laptop/issues/6189

**Comment by Liunkae** [comment] 2016-12-14 06:12
@bsclifton: Does fa23dfb fix the problem? If not, should this issue be reopened for now?

**Comment by bsclifton** [comment] 2016-12-14 15:57
@Liunkae actually, it's fixed by https://github.com/brave/browser-laptop/commit/701bd8938d59eb188b41f184a51c86e7af51eb0b

We'll be testing this morning :smile: BTW- I can't find a way to contact you, but you're more than welcome to join our community Slack. Send me an email at `clifton@brave.com` if you're interested in an invite

**Comment by Jes4Kix** [comment] 2016-12-14 19:37
Keep up the great work! it's greatly appreciated and doesn't go unnoticed

**Comment by bsclifton** [comment] 2016-12-14 20:58
OK folks! If you can grab the latest update, the issue should be fixed :smile: Please let us know how it goes!

@Jes4Kix thank you :smile: It was not an easy one to pin down, but @aekeus and I did find it! Big thanks to @paulcbetts for the Squirrel fix

cc: @josiah-keller @msieng @icecoldsquirrel @jonathansampson @mbretttx @gabriel1313 @msp1111111 @oohjhu @gordonq @Skiiowa @bdukes, @Brendon-Coombes

**Comment by takujun** [comment] 2016-12-14 21:05
Well.............I just did updating ( automatically noticed on above bookmarks bar) to Version 0.12.15.

Then I tried closing, and open.......it still let me save Brave. exe.


Why is that?!


Yuriko


________________________________
$B:9=P?M(B: Brian Clifton <notifications@github.com>
$BAw?.F|;~(B: 2016$BG/(B12$B7n(B14$BF|(B 12:58
$B08@h(B: brave/browser-laptop
CC: takujun; Mention
$B7oL>(B: Re: [brave/browser-laptop] brave tries to save brave.exe when opened (#6075)


OK folks! If you can grab the latest update, the issue should be fixed ?? Please let us know how it goes!

@Jes4Kix<https://github.com/Jes4Kix> thank you ?? It was not an easy one to pin down, but @aekeus<https://github.com/aekeus> and I did find it! Big thanks to @paulcbetts<https://github.com/paulcbetts> for the Squirrel fix

cc: @josiah-keller<https://github.com/josiah-keller> @msieng<https://github.com/msieng> @icecoldsquirrel<https://github.com/icecoldsquirrel> @jonathansampson<https://github.com/jonathansampson> @mbretttx<https://github.com/mbretttx> @gabriel1313<https://github.com/gabriel1313> @msp1111111<https://github.com/msp1111111> @oohjhu<https://github.com/oohjhu> @gordonq<https://github.com/gordonq> @Skiiowa<https://github.com/Skiiowa> @bdukes<https://github.com/bdukes>, @Brendon-Coombes<https://github.com/Brendon-Coombes>

-

**Comment by bsclifton** [comment] 2016-12-14 21:47
@takujun can you right click the shortcut that you use to launch Brave and pick "Properties"? I am curious what the target field looks like.  For example, mine is like this:

![screen shot 2016-12-14 at 2 46 42 pm](https://cloud.githubusercontent.com/assets/4733304/21202586/2cb7c7d4-c20c-11e6-90de-0af949f6934c.png)

**Comment by takujun** [comment] 2016-12-14 21:51
Yes, same as yours.




Yuriko


________________________________
$B:9=P?M(B: Brian Clifton <notifications@github.com>
$BAw?.F|;~(B: 2016$BG/(B12$B7n(B14$BF|(B 13:47
$B08@h(B: brave/browser-laptop
CC: takujun; Mention
$B7oL>(B: Re: [brave/browser-laptop] brave tries to save brave.exe when opened (#6075)


@takujun<https://github.com/takujun> can you right click the shortcut that you use to launch Brave and pick "Properties"? I am curious what the target field looks like. For example, mine is like this:

[screen shot 2016-12-14 at 2 46 42 pm]<https://cloud.githubusercontent.com/assets/4733304/21202586/2cb7c7d4-c20c-11e6-90de-0af949f6934c.png>

-

**Comment by takujun** [comment] 2016-12-14 21:53
Thank you !  I just did click on Brave Icon on my screen as everybody said. It is works !! I should more deeply reading and carefully to do that !

Thank you !!



Yuriko


________________________________
$B:9=P?M(B: Brian Clifton <notifications@github.com>
$BAw?.F|;~(B: 2016$BG/(B12$B7n(B14$BF|(B 13:47
$B08@h(B: brave/browser-laptop
CC: takujun; Mention
$B7oL>(B: Re: [brave/browser-laptop] brave tries to save brave.exe when opened (#6075)


@takujun<https://github.com/takujun> can you right click the shortcut that you use to launch Brave and pick "Properties"? I am curious what the target field looks like. For example, mine is like this:

[screen shot 2016-12-14 at 2 46 42 pm]<https://cloud.githubusercontent.com/assets/4733304/21202586/2cb7c7d4-c20c-11e6-90de-0af949f6934c.png>

-

**Comment by josiah-keller** [comment] 2016-12-14 23:43
My taskbar shortcut got changed to `C:\Users\Josiah\AppData\Local\brave\app.ico --processStart "Brave.exe"` and I had to change it back to `Update.exe`. @bsclifton

**Comment by ChrisW001** [comment] 2017-01-07 20:14
Since Brave doesn't have a real support section I can ask for help from, I had to go to that "Community" messageboard where they just kept telling me to unpin it from the taskbar and repin it.  Since new users are limited in the number of comments they can make per day, I've already run out of times to say "I've been trying that for over twenty hours and it still hasn't worked."

Ok, I've changed "Brave.exe" to "Update.exe" on the shortcut.  Now, instead of trying to save itself in the Download folder, a screen starts to open and fades away a split-second later.  I've uninstalled it and reinstalled it, I've pinned and unpinned it from the taskbar.  I am not happy with Brave right now, and it's taken me nearly a day to even get a response.  Last night, I went to Internet Explorer and within 30 seconds, there was someone asking how they could help me.

**Comment by bsclifton** [comment] 2017-01-09 03:46
@ChrisW001 Apologies that Brave isn't working as intended.  Please understand:

- We have provided the best troubleshooting steps that we can. You've let us know loud and clear that they don't work.  We appreciate that you tried the steps and reported back. This gives us more data

- Brave is a work in progress and all of us are doing our best (there are only so many of us and only so many hours in a day)

Because you've had so much trouble, I'd recommend not using Brave yet. Use another browser for now and track issues you care about here on GitHub.  When those issues are fixed, you can try it again and see if Brave is the right browser for you

**Comment by Skiiowa** [comment] 2017-01-09 14:26
Thanks.

I like Brave but agree that another Browser that is de-bugged is a better option now. I will look for updates at least once a month. Keep up the good work.

Steve Lansing
407-234-3265

[Chi rho][american-dream[1]]
           Faith, Family, Community, and Work  =
             Ordo Amoris   /   Eudaimonia
