### ISSUE TITLE
White Screen Tracking Issue

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7619] opened 2017-03-08 23:54 UTC

**Comment by osilvab** [comment] 2017-03-09 12:05
Starting Brave browser just give a full white screen (no bars), still one can change the vertical limits of its size. and respond to the alt+f4 to close it and ctrl+n to open a new one. the new one opens perfectly.

windows 10
Brave	0.13.5
rev	1db81cb
Muon	2.56.8
libchromiumcontent	56.0.2924.87
V8	5.6.326.50
Node.js	7.4.0
Update Channel	dev
os.platform	win32
os.release	10.0.14393
os.arch	x64

it happens every time i need to open the browser. and start happening after lat update.

**Comment by bsclifton** [comment] 2017-03-10 07:15
@osilvab do you have payments enabled? We found and [recently fixed an issue which causes similar symptoms](https://github.com/brave/browser-laptop/pull/7498), but it would only affect folks who have payments enabled

**Comment by osilvab** [comment] 2017-03-10 09:15
yes I have it enabled. without balance thought.  I just deactivated the payments and it works well now.

**Comment by bsclifton** [comment] 2017-03-10 09:19
@osilvab awesome- hang in there 😄  We'll have a fix with our next version. Thanks for verifying!

**Comment by bsclifton** [comment] 2017-03-14 08:52
Since this is a tracking issue and there is no action to take (other than to investigate), I'm going to remove the milestone

**Comment by bsclifton** [comment] 2017-03-14 22:53
+1 report from https://github.com/brave/browser-laptop/issues/4113#issuecomment-284947413 (which would be fixed with https://github.com/brave/browser-laptop/pull/7498)

possible +1 report from https://github.com/brave/browser-laptop/issues/7706 (root cause not known)

**Comment by luixxiul** [comment] 2017-03-24 10:37
Another report here:

https://community.brave.com/t/fatal-draging-issue/1801?u=suguru

**Comment by appurist** [comment] 2017-03-26 08:51
I have the same white screen on startup. I think I may have enabled payments just prior to the problem too, and don't have a balance set up, so similar to the comments above. Is there a way to disable that when Brave won't even start? (e.g. config file somewhere?)  Is the problem known/understood now? Fix coming?

**Comment by osilvab** [comment] 2017-03-26 17:23
@appurist what I did was on the white screen press Ctrl+n and then i got a usable new page where I could set up everything

**Comment by appurist** [comment] 2017-03-26 18:53
@osilvab Thanks for that, it sounded like a great idea. Unfortunately, it didn't have the same effect in my case. It created a new staggered blank white screen. 

In the image below, I pressed Ctrl-N twice. The image only captures the top-left corner here, but the rest of the screen was all white except for the top and left edges of these new layers.  (There are actually 3 windows below, you the top-left window doesn't show an edge since it goes to screen edge.)

![Top-left corner after pressing Ctrl-N twice](https://i.gyazo.com/ea4ee354867f53347e03956b06015e82.png)

**Comment by appurist** [comment] 2017-03-26 19:04
This really sucketh greatly since it means I can't use Brave at all. I've tried full uninstalls, nuking AppData, etc. Nothing seems to reset it.  Since Ctrl-N helped in @osilvab's case, I'm thinking this may indicate there is a race condition here (or it's just a completely different problem).

I should mention that I have other Electron-based apps installed (e.g. Atom, VS Code, etc) and they start fine.  Also that this is a Windows 10 Pro, 64-bit, 16GB i7 developer machine with an nVidia 980 for graphics and lots of tools installed (VS2015, VS2017, many JetBrains tools, etc).

And finally, I read somewhere that Brave uses port 8080, and won't work if it's in use. Is that accurate? I almost certainly often have something on port 8080 with my various web work. If Brave is relying on port 8080 being open, I'd suggest that change to something a lot more obscure, as it is very common for it to be in use.

**Comment by appurist** [comment] 2017-03-26 19:20
Also, I forgot to mention that Ctrl-Alt-J has no effect.

**Comment by appurist** [comment] 2017-03-26 19:55
FYI, I've also now tried [Brave 0.14.0 Preview 3](https://github.com/brave/browser-laptop/releases/tag/v0.14.0dev-Preview3) and the same problem persists. Just a plain white screen; no _visible_ window borders, titlebar, min/max/close buttons, nothing.

I also tried uninstalling, then nuking, the brave subfolders from both AppData/Local and AppData/Roaming before installing 0.14.0 Preview 3, and that didn't help.

**Comment by NejcZdovc** [comment] 2017-03-26 20:01
@appurist thank you for a really extensive report. Can you please try with our development version? This way we can see all errors in the browser console (shift+f8) and cmd.

Here are steps how to build it on Windows:  https://github.com/brave/browser-laptop/wiki/(setup)-Windows-build-guide

Thank you very much for your help

**Comment by appurist** [comment] 2017-03-26 20:37
@NejcZdovc I'm running through that now. I already had most of that installed, including version matches. Having a bit of trouble with that "__pfnDliNotifyHook2: redefinition" problem, but I ran `npm run win-fixnpm` and hopefully taking care of things. Hopefully have some results for you soon, although I need to go out for errands in about 30 minutes.  If you don't get a reply before then, I'll see what I can do later tonight.

**Comment by NejcZdovc** [comment] 2017-03-26 20:59
@appurist Thank you, much appreciated

**Comment by appurist** [comment] 2017-03-26 21:10
@NejcZdovc no luck yet. I have VS2015 and VS2017 (Community Ed for both) installed, and I found when I ran the VS2015 setup -> Modify that I didn't have the 8.1 SDK installed (I had 10.0 SDK installed though).  That seemed to be a hint when reading [this](https://github.com/nodejs/node-gyp/issues/802) which seems related since it's the `nodegyp rebuild` that seems to be generating the error.  So I installed the 8.1 SDK for VS2015, started a VS2015 MSBuild shell, and reran `npm config -g set msvs_version 2015` just to be safe, and `npm install bloom-filter-cpp` is still failing with the "__pfnDliNotifyHook2: redefinition" problem. I also ran `npm run win-fixnpm` again just in case it needed all this before it ran. No luck yet.

A couple of things to note. I do have the "anniversary update" of Windows 10 installed.  I have VS2017 installed, and with the optional web tools in VS2017 and even VS2015, I may have another version of node installed.  If I just start a command prompt or gitbash it reports node 7.6.0 though.  I need to run out now but I'll check in again later. Hopefully we can learn something about why I'm getting the white screen.

**Comment by NejcZdovc** [comment] 2017-03-26 21:27
@appurist what python version are you using? You need python 2.7 https://github.com/brave/browser-laptop/wiki/(setup)-Windows-build-guide#python-27

**Comment by appurist** [comment] 2017-03-27 01:18
I have Python 2.7.13 installed, and that's what comes back in a `python --version`.

I followed that build guide as close as possible, which is how I got to the `nodegyp rebuild` phase (in `npm install bloom-filter-cpp`).  Maybe something in this screenshot will stand out to someone:
![npm install bloom-filter-cpp](https://i.gyazo.com/7ee759ea0493d7c7ea934cb34b8dc631.png)
At least I can see it's running the VS 14.0 version of things.

Hey wait, that's from the 14.0/include folder. It it supposed to be picking that up from the Windows 8.1 or 10 SDK?

**Comment by NejcZdovc** [comment] 2017-03-27 06:35
cc @bsclifton

**Comment by appurist** [comment] 2017-03-27 06:51
ok, I realized the path to node-gyp was the global npm storage. I tried a `node uninstall node-gyp -g` followed by a `node install node-gyp -g` and got the same error. So then I thought something in my global npm installation was conflicting. So I tried another `node uninstall node-gyp -g` followed by a _non-global_ `node install node-gyp`. _That one_ installed smoothly.

So I think that means something in the node-gyp dependency chain, installed globally, is conflicting in some way.  And I'm wondering if it's possible to do a Brave dev build without node-gyp installed globally.

**Comment by appurist** [comment] 2017-03-27 07:17
Note: I have found that I can install node-gyp globally but not if I leave off the -g, as the brave installation does.

And since I can install node-gyp globally, I thought I'd try just running `node-gyp rebuild` directly to see if I got the same error. it was a different one: `binding.gyp not found`

![binding.gyp not found](https://i.gyazo.com/c29fa50db753423605b8d480b6361350.png)

Maybe that's a clue, maybe it's just a sign that something is terribly amiss on my setup. Or maybe it's related to why I get the blanks white screen for Brave. I'm going to stop poking at it for a while, and let those who know a lot more about it comment. ;)

**Comment by LaurenWags** [comment] 2017-06-30 19:15
+1 from community https://community.brave.com/t/facebook-not-displaying/4403

**Comment by appurist** [comment] 2017-06-30 19:39
It's been a while so I thought I'd try another uninstall / reinstall and poke at it.

No luck.

I did notice that it was installed under AppData/Local/Brave so I thought I'd run the uninstall and then clean up any left-over files.  The uninstaller just flashes briefly and is gone (less than a second). But the uninstaller did remove the files from AppData/Local/Brave and put a .dead file in there instead, so that seemed like it worked. However, it did leave a ton of files under AppData/Roaming/Brave, including cached files and a numbered extension, so I was optimistic that removing them might allow a fresh install to start the browser.  

It did not.  Even after removing the AppData/Roaming/Brave and running the installer, I get a white screen (I assume the installer is auto-launching Brave at the end).  Task manager indicates [several instances](https://i.gyazo.com/41f82d146e6532039440e590911a9cad.png) running.

I thought it might be something specific to the 64-bit installation so I uninstalled again and reinstalled, this time 32-bit Brave. Again, no luck.  Blank white screen.  I did notice however that it was resizable, by grabbing the corners of the white borderless window.  I can resize the window, and Alt-F4 closes it cleanly, so it's like it's working but it is unable to render _anything_.

**Comment by appurist** [comment] 2017-06-30 20:06
Another quick update: I thought it might be a problem with the updater maybe running when I started the browser so I renamed Updater.exe to xUpdater.exe, but that didn't help.  

I also found a BraveDefaults.exe under AppData\Local\brave\app-0.17.13\ and thought that sounded like something that might reset my configuration back to something that worked. It didn't help either, same white window.

One thing I did notice and appreciate is that Brave now seems to remember your window size and placement (although in my case it's all white with no borders).  But that's a tweak I've been wanting since Day One with Brave. Thanks folks.

**Comment by bsclifton** [comment] 2017-07-01 06:39
@appurist can you please try editing the shortcut on your desktop, so that you can add `--ignore-gpu-blacklist` or `--disable-gpu`?

For more info, see https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page

**Comment by appurist** [comment] 2017-07-01 07:23
Thanks for the suggestion. I first tried `--ignore-gpu-blacklist`, then I tried `--disable-gpu`, then I tried both options together.

Unfortunately none of these attempts changed the behavior. Just a solid white window.

**Comment by bsclifton** [comment] 2017-07-02 00:21
@appurist here's one last suggestion... can you try running the program as administrator? You should be able to change the shortcut so that it has this permission (we did have some reports of this being necessary). If that doesn't work, I believe there are some compatibility options you can try to launch with

Worst case scenario, you should be able to launch Chrome and (if it works), you can look at the following screens for clues:
`chrome://gpu/` - this will show any driver work-arounds that Chrome needed to do. We may need to implement these.
`chrome://flags/` - here you'll find specific options (which Brave has too, via Chromium) which can be passed to Chromium (or Brave) with the `--flagname=value` syntax.  You might look for ones which don't have the default setting to help determine what Chrome detected and auto-adjusted

**Comment by appurist** [comment] 2017-07-02 02:55
I tried running as Administrator, and no change again with the behavior. Whatever factor is causing this problem, I think we're missing it completely.

I have no problem using Chrome (I'm using it now to provide this update) and other apps with Chromium / CEF.

I've grabbed a copy of the `chrome://gpu/` output and it shows one significant disabled status: 
`Native GpuMemoryBuffers: Software only. Hardware acceleration disabled`
The [full output (text-only)](https://gist.github.com/appurist/46ed7a0f8142723036d8b1cc77bd4820#file-gpu-txt) and [the full output (formatted HTML)](https://gist.github.com/appurist/46ed7a0f8142723036d8b1cc77bd4820#file-gpu-htm).
  
The `chrome://flags/` output looked like all defaults, but I pressed the button to reset to defaults anyway, restarted Chrome, and tried to launch Brave. Same blank white window problem still.

**Comment by anyong** [comment] 2017-08-27 17:35
Just tried installing brave on Windows 10, and only see a white screen. I also tried building from source, and also only see a white screen.

I would be happy to help debug this if anyone wants to tell me what steps to try. (Haven't read through all the comments here yet but it seems the cause is still unknown?)

**Comment by appurist** [comment] 2017-08-27 18:34
@anyong That you are having the same trouble strengthens my suspicion that this problem is more likely to affect developer folks, that it is related to something we have installed.  Brave may be indirectly using the search path to find something it provides and finding _another_ (perhaps older version) ahead of the one it needs, or something like that.

I have so many dev tools installed that I can't really begin to take guesses at it.  But to highlight the most significant: VS2017 with all the web dev and several plugins, plus WebStorm and PHPStorm. Probably an old older versions of cli tools like ionic, etc.  And Firestorm and Chrome on Windows 10. Also ESET Internet Security.

**Comment by bsclifton** [comment] 2017-08-28 07:12
@anyong can you try the steps here?
https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page

**Comment by anyong** [comment] 2017-08-29 02:51
@bsclifton `--disable-gpu` had no effect - still blank white screen.

**Comment by eduardocorral** [comment] 2017-08-29 20:02
Same here, `--disable-gpu` and `--ignore-gpu-blacklist` have no effect. 
Happening frequently in
```
Brave: 0.19.3 
rev: 053c863b789c864bc83782520818ae91e4b7df49 
Muon: 4.4.9 
libchromiumcontent: 60.0.3112.101 
V8: 6.0.286.54 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Linux 
OS Release: 4.10.0-33-generic 
OS Architecture: x64
```

This is in dmesg
```
[ 7438.735157] traps: brave[28429] trap int3 ip:1af009d sp:7ffedda41550 error:0
[ 7438.735165]  in brave[400000+5e38000]
```
glxinfo

```
$ glxinfo | egrep -i "vendor|renderer"
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile
```
Card

```
$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
02:00.0 VGA compatible controller: NVIDIA Corporation GK208M [GeForce GT 730M] (rev a1)
```

**Comment by anyong** [comment] 2017-09-12 02:24
I finally did get this working, not sure what I did differently or what changed but a fresh clone and npm install worked, I can now launch brave from source... still can't launch it from the package installer though. I'll try to look into the issue if I have some time.

**Comment by appurist** [comment] 2017-09-12 05:13
That makes me think this is related to having other (probably incompatible) versions of some of the key files on my machine somewhere, perhaps in my search path. 

So I updated the PATH to put `c:\Users\Paul\AppData\Local\brave\` first in the list, but I still have the same problem. Now there's only really the `Brave.exe` file there, but if it searched the path for key dependencies in a relative way, I was hoping that might result in a different response.  No luck. I realized there was a second `Brave.exe` in the app directory and I tried adding the `--disable-gpu` and `--ignore-gpu-blacklist` directly to a shortcut directly there, but again no improvement.

I also noticed that there were two `app-0.nn.nn` folders, so I removed the older 0.17 version, didn't help. I then uninstalled it all, and downloaded and reinstalled the latest. Also tried running the `BraveDefaults.exe` but still no joy.

So it doesn't seem to be anything in my path; perhaps just an incompatible version of something installed somewhere else like the system folder.  Or it's not related to files installed at all but perhaps my hardware (although I would assume a Dell XPS box with an i7 processor and an nvidia 980 would be pretty common).

**Comment by anyong** [comment] 2017-09-25 04:05
Alright, I have solved this issue - at least for myself. I haven't started to look through the code yet, but somewhere there is code that runs differently with `NODE_ENV === 'development'` and causing this issue. This should be fixed & development stuff needs to be removed from release builds.

If I get more time I will try digging through code to see if I can find anything.

**Comment by appurist** [comment] 2017-09-25 04:32
@anyong You are the hero of the issue! Working for me now too, after I removed my `NODE_ENV` environment variable set to `'development'`.  I did indeed have that set.  This is indeed exactly the kind of environmental setting that I suspected but couldn't figure out which setting was troublesome.

Note that after I removed it, the new installer still opened a white window, so at first I thought it didn't work. However, when I launched it manually/directly from the desktop shortcut created by the installer, it opened just fine. I closed it and repeated that, and again it was fine. It looks like this is indeed somehow triggering the problem.  So at least that gives the Brave developers something to test with, to try to reproduce the problem locally.

Much appreciate the update with the workaround!

**Comment by luixxiul** [comment] 2017-09-25 04:37
CC @bsclifton for investigation.

**Comment by Roobyx** [comment] 2017-09-28 10:10
Amazing !!! I can confirm the exact same result as @appurist and @anyong. Changing the global NODE_ENV does fix the problem (after you run the browser from the shortcut, not the initial start)

**Comment by jonathansampson** [comment] 2017-10-11 01:58
I was just coming to file an issue after I too realized that `NODE_ENV = 'development'` was causing a white-box/hang during startup. I tried several other values (`' '`, `'production'`, etc), which didn't reproduce the issue. Only _development_ repro'd, which makes sense.

**Comment by s-horn** [comment] 2018-01-25 15:11
Had the same symptoms: completely white screen, no bars. Responded to resizing, ALT+F4, and CTRL+N. In the developer console, there were two errors:

```
localhost:9017/gen/app.entry.js Failed to load resource: net::ERR_CONNECTION_REFUSED
localhost:9017/gen/lib.devTools.js Failed to load resource: net::ERR_CONNECTION_REFUSED
```

I noticed that in the `npm run watch` window, it had two different ports logged:

```
Project is running at http://localhost:8081/
webpack output is served from http://localhost:9017/gen/
Content not from webpack is served from C:\Users\Stephen\Documents\git\browser-laptop\app\extensions\brave
```

ran `npm config set brave:port 8081`, and now it comes up fine. The message from `npm run watch` is now

```
Project is running at http://localhost:8081/
webpack output is served from http://localhost:8081/gen/
Content not from webpack is served from C:\Users\Stephen\Documents\git\browser-laptop\app\extensions\brave
```

I hope this is useful to anyone else experiencing the same issue.

**Comment by knowler** [comment] 2018-05-03 04:38
We are experiencing this issue with Webpack/Browsersync running in [Sage](https://github.com/roots/sage) on both Windows and macOS. I was able to reproduce it in a Laravel Mix (Webpack)/Browsersync setup as well. The above `NODE_ENV=production` fix worked in both situations.

Related thread: https://discourse.roots.io/t/blank-browsersync/12362?u=knowler

**Comment by bsclifton** [comment] 2018-07-25 07:44
Since we have a [documented workaround](https://community.brave.com/t/window-is-solid-black-or-solid-white-looks-like-a-blank-page/10003) and also because we're moving to [Brave Core](https://github.com/brave/brave-browser) and won't be addressing this before then, I believe it makes sense to close this issue

**Closed by bsclifton** 2018-07-25 07:44 UTC
Labels: bug/driver, needs-investigation, project-tracking

**Comment by okebaja** [comment] 2018-08-06 19:52
I have this issue after a *first time* install of Brave on my iMac. Documented workaround doesn't document a workaround for Max. What to do?

**Comment by LaurenWags** [comment] 2018-08-06 20:31
@okebaja what version of Mac are you seeing this with? not sure if it will work, but you could try closing Brave, opening up your Activity Monitor and seeing if there are any zombie Brave processes. If so, kill them and try launching Brave again. or just restart your machine and see if that does the trick?

**Comment by bsclifton** [comment] 2018-08-06 21:21
@okebaja do you happen to have the `NODE_ENV` set globally? I know this can interfere with things

**Comment by okebaja** [comment] 2018-08-07 17:53
@bsclifton No I do not have it set. echo $[NODE_ENV] yields '0' on my system, and PRINTENV does not list NODE_ENV.
@LaurenWags I am running High Sierra on an early 2009 Mac. Activity Monitor shows 1 Brave process and 6 Brave helper processes. Pls note that I had this issue even at first run.

To add to this: it seems to be a system wide problem. Chrome does not web pages anymore nor does it show it own settings pages. Links are present, I see them when I move the mouse around and accidentally hover on them. Clicking the link even loads it, but yields another white (or the same) white screen. Also toolbar apps who use web tech (like Crashplan) do not show anything anymore (except the 'ghost' links).

**Comment by bsclifton** [comment] 2018-08-07 18:17
@okebaja can you try launching Brave via the command line? You can try the disable GPU flag to see if that helps. The command would look like:
`/Applications/Brave.app/Contents/MacOS/Brave --disable-gpu`

**Comment by okebaja** [comment] 2018-08-07 18:36
Hi @bsclifton, did as you suggested. This is the output of the command:
[1090:775:0807/203144.054996:ERROR:gpu_process_transport_factory.cc(1016)] Lost UI shared context.
Crash reporting enabled
[1090:775:0807/203149.984756:ERROR:display_ca_layer_tree.mm(89)] Frame had neither valid CAContext nor valid IOSurface.
[1090:775:0807/203149.987186:ERROR:display_ca_layer_tree.mm(89)] Frame had neither valid CAContext nor valid IOSurface.

the last error is repeated over and over again after this.

**Comment by bsclifton** [comment] 2018-08-07 19:10
@okebaja no change in the user interface after launching? (ex: still white inside the GUI?)

**Comment by okebaja** [comment] 2018-08-07 19:27
@bsclifton Nope, the GUI does never shows. The process in the terminal shows some 10 ~ 20 errors (all the same) then stops. As said, GUI does not show. If terminal process is terminated, a popup shows saying that Brave stopped responding.

**Comment by Roobyx** [comment] 2018-08-09 11:13
My problem was the NODE_ENV (some other people had it too) Brave worked depending on the PROD or DEV environment setting. 
I am glad to say that that seems like its not a problem anymore. I have not changed anything on my system since the start of this problem, but Brave works now!

**Comment by strider72** [comment] 2018-08-24 16:19
I got the same issue (transparent or white windows in Brave) after installing the latest version of Duet Display. (v1.5.3.2) www.duetdisplay.com .  Running Brave with `--disable-gpu` fixes the issue.  I've submitted an issue with Duet as well.  As Duet emulates a display (specifically, uses an iPad as a display), I would guess it's a driver-related issue.
