### ISSUE TITLE
Homepage preference isn't being respected

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8278] opened 2017-04-13 05:21 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When setting the homepage and then setting new tab to use homepage, it was found that the about:newtab was still being displayed. Quitting and restarting Brave did not alleviate the issue.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.14.2 (f07c142)

- Steps to reproduce:
    1. Open preferences, set homepage value
    2. Set new tab to open homepage
    3. Open a new tab with a keyboard (cmd+t)
    
- Actual result:
about:newtab is displayed

- Expected result:
your homepage should be displayed

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by NejcZdovc** [comment] 2017-04-13 10:07
Can't reproduce this on dev-channel branch.

![13](https://cloud.githubusercontent.com/assets/9574457/25000465/b5ba70a2-2041-11e7-82cc-0f1dc9773530.gif)

**Comment by srirambv** [comment] 2017-04-13 11:11
Works fine on Windows with packaged build of preview 3

**Comment by NejcZdovc** [comment] 2017-04-13 11:16
Closing as can't reproduce, but if @alexwykoff you can still reproduce it please let me know and reopen this issue

**Closed** 2017-04-13 21:27 UTC
Labels: bug
