### ISSUE TITLE
Easier feedback for bad ads

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#5125] opened 2016-10-25 18:43 UTC
From support: https://linkbubble.zendesk.com/agent/tickets/5598

> - Easier feedback for bad ads. Since the baseline is to block all ads, 
>   ads that get through should be easier to flag.

**Comment by bsclifton** [comment] 2018-09-03 04:56
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/1370

**Closed by bsclifton** 2018-09-03 04:56 UTC
Labels: design, feature/adblock, suggestion
