### ISSUE TITLE
Autofill suggestions only shows while typing

### ISSUE THREAD

**Issue by Zuzu-Typ** [brave/browser-laptop#5265] opened 2016-10-30 09:35 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When I try to type in an e-mail address into a login form, the suggestion appears for a split second.

**Expected behavior:**
It should be showing all the time
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win10 x64
- Brave Version:
  0.12.8dev Prev1
- Steps to reproduce:
  1. Log out of Facebook if currently logged in,
  2. Go to https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Ffavicon.ico%3F_rdr%3Dp
  3. Enter your login data.
  4. If you don't have any suggestions yet, click on login (with invalid login data, you don't actually want to log in) and reload the page. Then go back to step 3.
- Screenshot if needed:
  ![honeycam 2016-10-30 10-02-07](https://cloud.githubusercontent.com/assets/20467351/19837920/4f0b3b92-9ec4-11e6-929d-04438fbae2ea.gif)
- Any related issues:

**Comment by Liunkae** [comment] 2016-11-27 21:06
Duplicate of #5438. This bug is planned to fixed in the next release, 0.13.0.

**Closed by Liunkae** 2016-11-27 21:06 UTC
Labels: feature/autofill
