### ISSUE TITLE
0.13.5 preview  builds size is more compared to normal builds

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7352] opened 2017-02-22 14:21 UTC
0.13.5 preview 2 is almost 30Mb more than usual. 
![image](https://cloud.githubusercontent.com/assets/17010094/23215410/2e2ded8e-f90a-11e6-9200-a1c5e700b870.png)

**Comment by bsclifton** [comment] 2017-03-14 08:48
moving to 0.13.7

**Comment by bsclifton** [comment] 2017-03-27 18:31
duplicate of https://github.com/brave/browser-laptop/issues/7896

**Closed by bsclifton** 2017-03-27 18:31 UTC
Labels: dev-setup
