### ISSUE TITLE
Menu should not be activated with ALT key

### ISSUE THREAD

**Issue by valtih1978** [brave/browser-laptop#7323] opened 2017-02-20 15:00 UTC
**Describe the issue you encountered:** the menu shows up when I simply Alt+Left/Right to navigate to Next/Prev pages or Shift+Alt to switch kbd layout.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows

- Brave Version (revision SHA): 0.13.4

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result: the menu shows up

- Expected result:  the menu should not show up

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

Probably, menu should show up only when nothing other is pressed between the Alt press-release pair of events.

**Comment by luixxiul** [comment] 2017-02-20 17:09
We are sorry for the issue you experience. We will investigate the issue as soon as possible. Sincerely.

**Comment by diracdeltas** [comment] 2017-02-21 20:29
This also happens on Linux, but it is the expected behavior there.

**Comment by bsclifton** [comment] 2017-02-22 06:31
We've definitely been getting more of these and I'd like to try to solve the problem on Windows. @valtih1978 you can track the progress with https://github.com/brave/browser-laptop/issues/5775 (we've bumped up priority recently)

@diracdeltas that is correct, Linux is expected and the change may be more difficult.  The Linux version of the issue is captured with https://github.com/brave/browser-laptop/issues/5540

I'll go ahead and close this particular issue as a dupe.  Thanks 😄

**Closed by bsclifton** 2017-02-22 06:31 UTC
Labels: OS/Windows, suggestion
