### ISSUE TITLE
Window off screen when monitors change

### ISSUE THREAD

**Issue by shortstuffsushi** [brave/browser-laptop#9461] opened 2017-06-14 16:58 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
I frequently switch between a few monitor setups --  sometimes just laptop, sometimes a dock with two screens, and sometimes just one screen when I'm at home. Frequently when I switch with Brave open, the window will end up rendered off screen with no way to recover it except by closing and restarting Brave. Today, though, it seems to have become permanently off screen and I can't find a way to recover it with and of the usual tricks. My question isn't so much about "how can I get my window" back, but rather why is this happening? I don't have this issue with any of my other applications.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10, Lenovo ThinkPad W530

- Brave Version (revision SHA):
Can't actually open it to look at the moment, but I think it's 16.9

I'm not sure of a good way to provide repro steps on this. Basically, launch Brave in one monitor setup, put the window into one of external displays, and then detach. That's what doesn't it for me. Specifically, I usually close my laptop on the dock before disconnecting (which puts it to sleep), then wake it in another display configuration. That may be the problem.

Also, if I hit F11 to go full screen, I can see it again, but it's gone once I exit full screen.

**Comment by OlivierAlves** [comment] 2017-06-16 17:52
I just had the same problem, just open brave on a new windows and change screen configuration and then it will be reopen on the last screen even if it's not there.

**Comment by shortstuffsushi** [comment] 2017-07-21 20:14
Just wanted to bump this issue, since it's still occurring regularly for me. I frequently go between different display setups (multiple times per day), and almost every time I have to kill and restart Brave. Unfortunately, I've reached a point where I can't get my window to show up even after restarting at this point, but I think a reboot fixed that last time.

**Comment by BitMechanic** [comment] 2017-08-19 15:37
Yeah I'm using it on a Razer laptop, fresh install. The browser has disappeared off screen after setup. I cant get it back again. I've rebooted the computer, re-installed Brave. I can see it if I hit Task View but there's no way of getting back on screen.

**Comment by luixxiul** [comment] 2017-08-19 15:42
@BitMechanic would you mind removing the profile folder (`/Users/[Your User Name Here]/AppData/Roaming/brave`) and try again?

**Comment by BitMechanic** [comment] 2017-08-19 15:48
@luixxiul couldn't see a profile folder in there, but I removed a file called session-store-1. That worked

**Comment by BitMechanic** [comment] 2017-08-19 16:01
@luixxiul Thinking now that maybe you wanted me to remove the whole folder? Anyway, I wonder if session-store-1 is related to imports from other browsers. Like Chrome and Firefox?

**Comment by luixxiul** [comment] 2017-08-19 16:13
`session-store-1` is the file where the personal data like bookmarks and history is stored. So actually removing the file or the profile folder is the last resort to fix a persistent issue. I asked you to do so as you have finished the install just now and therefore no personal info was basically stored there.

**Comment by BitMechanic** [comment] 2017-08-19 16:20
As well as installing the software, I also imported bookmarks, history etc from Chrome and Firefox. If that data is stored in that file, then the bug is in the imported data?

**Comment by luixxiul** [comment] 2017-08-19 16:21
I'm not sure but I don't think so (as we have not heard such a case). If you could find steps to reproduce the issue, please let us know, thanks.

**Comment by bsclifton** [comment] 2017-08-21 06:25
@BitMechanic this is definitely a bug on our side... We save the coordinates for the windows and try to restore them.  If you switch monitors, we aren't checking if those coordinates are offscreen when restoring the windows ☹️   This is why moving the `session-store-1` file worked (since that file had your window coordinates).

**Comment by bsclifton** [comment] 2017-08-21 06:25
Closing this as a duplicate of https://github.com/brave/browser-laptop/issues/3558

**Closed by bsclifton** 2017-08-21 06:25 UTC
Labels: bug
