### ISSUE TITLE
Drag & Drop for Images and Files Broken (causes screen to go white)

### ISSUE THREAD

**Issue by KevDoy** [brave/browser-laptop#7266] opened 2017-02-15 18:05 UTC
- Did you search for similar issues before submitting this one?
Yes.
- Describe the issue you encountered:
I am unable to drag any images or files into the browser for websites designed to accept this feature (ie. Hangouts; Google Drive)
- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS X El Capitan
- Brave Version (revision SHA):
0.13.3 b4cb1f5
- Steps to reproduce:
    1. Open Google Drive. 
    2. Drag file from Finder and Drop in Browser Window.
    3. Nothing happens.
    
- Actual result:
Nothing.
- Expected result:
File would begin uploading to, for example, Google Drive
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
untested
- Is this an issue in the currently released version?
Yes, just updated
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment] 2017-02-15 21:58
File uploading here on GitHub is working fine for me with Brave 0.13.4 on macOS 10.12.x.

Have you tried disabling shields? Click the lion icon in the top right and switch Shields to Down.

**Comment by KevDoy** [comment] 2017-02-16 00:13
I restarted the browser, without change. Tried it one more time and it did. I'm not sure what the reason was.

**Comment by KevDoy** [comment] 2017-02-16 17:49
This continues to happen for me, terminating the Brave task does the trick, but this is definitely new.

**Comment by alexwykoff** [comment] 2017-02-20 06:11
While this was not observed in prior builds for me, I have noticed it with a local run of e259d61b8b05041961bbff1ce456004f4dab3e4e.

**Comment by bsclifton** [comment] 2017-02-25 07:33
I can't repro using master and it works great with 0.13.4... We can retest once a new preview build is cut.  It does fail with 0.13.5 preview 1.

Sites which I tried drag and drop using master:
- twitter.com
- GitHub.com
- outlook.com

**Comment by bsclifton** [comment] 2017-02-27 21:39
Closing- this appears to work great with 0.13.5 preview 3. Let's re-open if it happens again

I'll keep the milestone just so we can confirm that it works during testing (if it's already in our test plan, we can remove milestone)

**Comment by bsclifton** [comment] 2017-02-28 00:41
Re-opening after seeing the issue again in 0.13.5 preview 3 ☹️ 

I experienced the problem here on GitHub and I believe I have better repro steps:
- I move Brave window out of the way (over to the left or something)
- I click the desktop. Brave does not have focus
- I drop the image file into the text area in GitHub
- The UI shows an animation of the image which was dragged being returned to the desktop
- The entire window goes white and becomes unusable

**Comment by NejcZdovc** [comment] 2017-02-28 06:48
@bsclifton I tried these steps, but I couldn't reproduce this error. I experience this kind of error already on 0.13.4, but for now I don't have reproduction steps, it happened 3 or 4 times till now.

**Comment by NejcZdovc** [comment] 2017-02-28 06:52
Ok I managed to crash it again (0.13.4). I managed to crash it only after brave was running for a long time, the whole day.

**Comment by bsclifton** [comment] 2017-02-28 23:02
I spent about 90 minutes trying to make this happen (in which I ran into issues caused by the Amazon S3 services being down).  Regardless of those, I could not get an error to happen.  Everything always worked OK.  I looked at crash reports on stats.brave.com and didn't see any reports which I believe were mine OR which had information which could be helpful.

Since the steps to repro aren't nailed down, I'm going to push this to 0.13.6.  We should definitely keep eyes out for it

**Comment by KevDoy** [comment] 2017-03-01 00:11
Here's how it happens for me

I have Google Hangouts in a pinned tab.

I open Brave (new session after completely exiting).
Open Hangouts tab. Drag & Drop works. I open a new normal tab, and navigate to Google.com.
I click off of Brave. 
Click back on the Pinned Hangouts tab and Drag & Drop stops working on all tabs.

**Comment by bsclifton** [comment] 2017-03-01 21:26
screenshot courtesy of @echosa:
<img width="1478" alt="screen shot 2017-03-01 at 11 30 47 am" src="https://cloud.githubusercontent.com/assets/133786/23472704/6905bbf8-fe73-11e6-8214-f5f54b2ebbe5.png">

**Comment by echosa** [comment] 2017-03-01 21:40
I just tried Imgur, GitHub, Jira, and Dropbox. All of them worked flawlessly. Of course they did, since I'm trying to capture the error. :-/ I recently closed and restarted Brave. Maybe it needs to be open for a while before the drag-and-drop error occurs? (Some kind of memory leak or something maybe?) If I can get the issue to happen during a recording, I'll post it here.

**Comment by gregnyc** [comment] 2017-03-03 16:17
I reproduced this just now and captured it on video.

Video 1: single tab, could not reproduce
https://youtu.be/_KogzGSvESI

Video 2: multiple tabs, immediately reproduced
https://youtu.be/Q5PUHFNbyuk

(not sure if the # of tabs is just coincidence or meaningful)

Context:
- My Brave browser window had 15 tabs open (2 gmail, 3 github, 2 google drive, 1 google sheet, 1 google calender, 3 google documents, 1 pivotal tracker, 1 zendesk)
- I attempted to drag a PNG file from my desktop onto the Zendesk tab into a designated drop zone
- Upon releasing the mouse click, the file icon snapped back to the desktop, but the browser didn't immediate crash
- I then attempt to drag it onto the browser again, the icon snapped back to the desktop, I got the Mac beachball, and then in about 2 seconds Brave went white (NOTE: the video did not capture the beach ball, not sure why)
- I force quit Brave, although I'll mention that it was *not* listed as 'Not Responding' (I've never seen it listed in that state when this bug occurs)

Immediately prior to this, I had launched a new Brave window with just a single fresh tab (also Zendesk), and was able to drag/drop that same file twice without issue.

Specs:
Mac 10.11.4
Brave	0.13.4
rev	71d8ffc
Muon	2.56.4
libchromiumcontent	56.0.2924.87
V8	5.6.326.50
Node.js	7.4.0
Update Channel	dev
os.platform	darwin
os.release	15.4.0
os.arch	x64

**Comment by gregnyc** [comment] 2017-03-07 16:06
One more observation: today Brave had been open for a while with a bunch of tabs.  I needed to transfer some image files from an SD card to Google Photos, so I opened a Firefox window so that I could use drag-drop.  The act of dragging images from my SD Card (via Finder) onto the Firefox browser, without interacting with Brave directly at all, caused Brave to crash with the white screen exactly as I've observed when dragging files onto Brave itself.

**Comment by KevDoy** [comment] 2017-03-07 16:48
@gregnyc I can confirm this happened to me, too. Not with Firefox, but with Photoshop.

**Comment by bsclifton** [comment] 2017-03-08 17:48
@KevDoy @gregnyc @echosa @NejcZdovc do you all have Brave Payments enabled? I am just fixing a bug which (when it happens) causes a crash.  I don't think it's related, but I'm curious

**Comment by gregnyc** [comment] 2017-03-08 17:49
I have payments disabled.

**Comment by echosa** [comment] 2017-03-08 17:52
Payments are currently off, but I think I had the same issue when I had them turned on, as well.

**Comment by bbondy** [comment] 2017-03-16 23:40
I'm taking a look

**Comment by bbondy** [comment] 2017-03-17 01:25
Reproduces: 0.13.3 (also 0.13.4, 0.13.5, 0.14.0)
Chromium: 56.0.2924.87

Does not reproduce: 0.13.2
Chromium: 54.0.2840.100


Conclusive steps to reproduce:
1. Start a fresh instance
2. Load github.com and create an issue
3. Try to drop a file, works.
4. Drag a bookmark or a tab, you pick.
5. Try to drop a file, does not work.

**Comment by bbondy** [comment] 2017-03-17 01:26
Removing all drag and drop handlers completely from our front end still reproduces. So seems like something from the chromium upgrade.

**Comment by bbondy** [comment] 2017-03-17 01:44
Verified this does not reproduce on Linux and Windows

**Comment by bbondy** [comment] 2017-03-17 13:23
This is the commit that introduces the bug:
https://chromium.googlesource.com/chromium/src.git/+/0678253f9e9c12a1cc704721ae6e013860bb909e

In particular isValidDragTarget returns false but only after having dragged a bookmark or tab or some other UI element from the window.   I think maybe something like the RenderWidget host gets set to the parent window and not the webview.  Still investigating .

**Comment by bbondy** [comment] 2017-03-17 17:54
fixed here:
https://github.com/brave/muon/commit/abc37bfadd2ab72cac941db7e08591e8235c7058

**Closed by bbondy** 2017-03-17 17:54 UTC
Labels: misc/drag-and-drop, needs investigation, OS/macOS, priority/high

**Comment by gregnyc** [comment] 2017-03-17 18:00
Awesome, thanks!

**Comment by bsclifton** [comment] 2017-03-17 20:11
Awesome job, @bbondy! 😄
