### ISSUE TITLE
Suggestions - Firefox User

### ISSUE THREAD

**Issue by bigdogchris** [brave/browser-laptop#3097] opened 2016-08-10 22:58 UTC
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10 x64

- Brave Version:
.11.4

I know this isn't the best spot for suggestions but I'm not sure where else to submit them with no forum.

As a Firefox user I think that Brave, so far, is a fantastic browser that is exceptionally quick. I can see myself switching one day as it matures.

However, like other Chromium based browsers I find the bookmark functionality to be lacking. I like having a bookmark button that I click and have a drop down of my bookmarks and bookmark folders. I know there is a bookmark toolbar available but that just takes up more screen space and is ugly. There's a lot of blank empty/wasted space on the Brave UI between the back/forward buttons and the URL/search box. Can't we at least have the option to add a bookmark button there like Firefox has? Lack of proper bookmark button is the reason I haven't already switched to Chrome or Vivaldi.

The other comment I have is regarding the AdBlocker. I like the idea of being able to get paid to see ads and I look forward to full implementation. But in the mean time, is there also plans to add the ability to customize the ad blocking? For example, Brave does not block "Sponsored links" on websites like Yahoo.com where ABP for Firefox does. It would be nice to be ale to add our own blocks in for ads that Brave misses.

Finally, I think it would be great to be able to disable the automatic tab styling/coloring based on site color. Vivaldi has this feature and I think it would be great addition to Brave. I prefer the browser colored/gray tabs easier to read compared to ones filled with color.

Thanks.

**Comment by bsclifton** [comment] 2016-08-11 15:31
Hi @bigdogchris 

Regarding the bookmarks menu, I do have a pull request open to add this :smile: So that will be coming soon:
https://github.com/brave/browser-laptop/pull/3055
This is tracked with issue https://github.com/brave/browser-laptop/issues/1993

Your issue regarding the UI- I know there have been similar complaints, some of which are captured with https://github.com/brave/browser-laptop/issues/2386.  The bookmark button in particular is being redesigned and is being tracked with the following issue (which also includes the popup that comes up after clicking the bookmark button):
https://github.com/brave/browser-laptop/issues/2894

The sponsored links aren't blocked because they are first party- only 3rd party (ex: images or scripts on another domain) would be blocked.  This is by design.

Your last issue CAN be fixed, although perhaps it's not the easiest to find.  If you open prefs and go to the "Tabs" tab, you'll see the preference you can disable:
`Show tabs in page theme color`

Hope this post is helpful :smile: Since there are issues for everything you called out, I'm going to go ahead and close this issue.  Please feel free to re-open or continue commenting if you have more feedback.  Thanks!

**Closed** 2016-08-11 15:31 UTC
Labels: design, suggestion
