### ISSUE TITLE
Pref change restart doesn't relaunch the browser

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5938] opened 2016-11-30 13:02 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Pref change restart doesn't relaunch the browser

**Expected behavior:**
Should relaunch the browser when Yes is selected from notification bar

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 2

- Steps to reproduce:
    1. Do a clean install of 0.13.0 preview 2
    2. Enable setting which prompts for browser restart
    3. Click on Yes causes the browser to close but doesn't restart on its own

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment] 2016-12-15 22:05
Unable to reproduce this one with 0.13.0 preview 3 or with HEAD (chromium54 on browser-laptop with fresh npm install).  I'll close for now, but we should verify (via test plan) that this scenario is covered when next build comes out

**Comment by srirambv** [comment] 2016-12-16 14:14
Able to reproduce this on 0.13.0 Preview 3. Reopening the issue. 
![5938](https://cloud.githubusercontent.com/assets/17010094/21265566/f36e828a-c399-11e6-9fcb-f276c65a3406.gif)

**Comment by bridiver** [comment] 2016-12-19 07:36
@srirambv can you limit the scope of this based on OS? It does not appear to be reproducible on mac

**Comment by srirambv** [comment] 2016-12-20 10:17
@bridiver  This is on Windows 10 x64. Am able to reproduce this with 0.13.0 Preview 5 as well.

**Comment by bridiver** [comment] 2016-12-20 15:41
@srirambv sorry, I read  (Win7, 8, 10? macOS? Linux distro?) as something you added, but that is just the default example

**Comment by bsclifton** [comment] 2016-12-21 00:53
Reproduced issue; when app starts back up, it crashes with the following:
```
Crash reporting enabled
[5712:744:1220/165126:ERROR:crash_reporter_win.cc(190)] Cannot initialize out-of-process crash handler
null
null
```

**Comment by bsclifton** [comment] 2016-12-21 22:33
Will be fixed by https://github.com/brave/electron/pull/127

I manually tested and it's working great :smile: Hang in there for the next build

**Closed by bsclifton** 2016-12-21 22:33 UTC
Labels: chromium54, OS/Windows, release/blocking, settings

**Comment by luixxiul** [comment] 2017-01-16 18:17
Test plan:

Enable setting which prompts for browser restart
Click "Yes"
The browser is restarted
