### ISSUE TITLE
none of the captcha works in Brave

### ISSUE THREAD

**Issue by commandline-be** [brave/browser-laptop#15240] opened 2018-09-28 07:55 UTC
### Description
Any of the sites i visit which offer a Captcha shows the captcha but there is no interaction possible with it

### Steps to Reproduce

  1. Visit a website with a captcha ( submit a file here for example https://www.reverse.it/ )
  2. try and click on the captcha
  3. nothing happens

**Actual result:**

Nothing to show, just a screenshot of a website with a captcha

**Expected result:**

the captcha is available for interaction

**Reproduces how often:**

each website form with a captcha i encountered (5 or more)

### Brave Version

**about:brave info:**

 
Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Reproducible on current live release:**

### Additional Information

submitting a file to the website provided is adequate to demonstrate, it will not work because the captcha fails

**Comment by eljuno** [comment] 2018-09-28 08:13
It may be caused by _Site isolation_ that enabled under Preferences > Security.

**Comment by bsclifton** [comment] 2018-09-28 20:32
Likely a duplicate of https://github.com/brave/browser-laptop/issues/14765 - as @eljuno recommends, I'd try disabling strict site isolation

You could also try our new Beta here:
https://brave.com/download-beta

**Closed by bsclifton** 2018-09-28 20:32 UTC
