### ISSUE TITLE
restoring old state when crashing instead of the state before the crash

### ISSUE THREAD

**Issue by despairblue** [brave/browser-laptop#5630] opened 2016-11-15 11:13 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Sometimes (usually every two days) I get an unexpected error where brave restores the state to how it was when I started it. Thus I loose all newly opened tabs and all the input.

**Expected behavior:**
Restore the state brave hat before the crash, at least the open tabs.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS Sierra 10.12.1

- Brave Version:
Brave: 0.12.8
Electron: 1.4.23
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev

- Steps to reproduce:
    1. Make it crash somehow. I haven't been able to find steps that repeatable crash brave.

**Comment by Liunkae** [comment] 2016-11-19 07:38
Duplicate of #5512 (Brave should restore session gracefully after a crash).

**Closed by Liunkae** 2016-11-19 07:38 UTC
