### ISSUE TITLE
Brave keeps relaunching until you disable default browser check

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6490] opened 2016-12-31 10:59 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Brave keeps relaunching until you disable default browser check

**Expected behavior:**
Should not relaunch after closing the browser

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
``` 
Brave: 0.13.0 
rev: 0c7a64d6917b6e7e72d074b05e1d7488466418a9 
Muon: 2.0.8 
libchromiumcontent: 54.0.2840.100 
V8: 5.4.500.41 
Node.js: 7.0.0 
Update Channel: dev 
os.platform: win32 
os.release: 6.2.9200 
os.arch: x64
```

- Steps to reproduce:
    1. Do a clean install of 0.13.0 Preview 7
    2. On browser first launch do not disable `Always check on startup` switch
    3. Click on Not now button and wait for the newtab image to load and then close the browser
    4. Browser process is still running after closing the browser which relaunches it again
    5. Keeps relaunching the browser until the `Always check on startup` switch is turned off

- Screenshot if needed:
http://sendvid.com/2txeca11 (from installation, Verified it couple of time with a clean install)

- Any related issues:
cc: @bridiver @bsclifton

**Comment by bbondy** [comment] 2017-01-01 17:55
The always check on startup switch I don't think would have any effect on this.  I tried to reproduce on Windows 10 with 0.13.0 preview7 with a clean profile but it doesn't restart for me. @srirambv could you test a little more to confirm you can remove the correlation of default browser since I don't think it's related?

**Comment by bbondy** [comment] 2017-01-01 17:56
Also please detail the way that you launch the browser, like is it from desktop shortcut or from a different place?

**Comment by bbondy** [comment] 2017-01-01 18:00
Also if you're using a desktop shortcut, please paste in the shortcut properties details like the target of the shortcut.

**Comment by bsclifton** [comment] 2017-01-02 04:12
I did encounter problems with Brave staying open if I ran from the command line and then quit.  I don't think it's closing properly in that case

**Comment by srirambv** [comment] 2017-01-02 08:55
@bbondy This happens after installation. The full video is captured here http://sendvid.com/2txeca11. After installation when the browser launches, if I close that it automatically relaunches itself because the process is not completely killed after closing. Each time it's the scenario, until I turn off the switch it keeps a process running and keeps relaunching.

As for the desktop shortcut path this is what it contains
![image](https://cloud.githubusercontent.com/assets/17010094/21586360/2d0a716c-d0c8-11e6-8b3d-8d7d6cdaeac4.png)

I am not using the desktop shortcut to launch the browser.

**Comment by bbondy** [comment] 2017-01-03 02:23
OK I see, I think maybe it has to do with it auto launches after install, and maybe it gets in a bad state at that time, but not to do with default browser check.

**Comment by bbondy** [comment] 2017-01-03 06:02
@srirambv I followed the steps exactly but am not able to reproduce. I tried clearing my profile and install completely first. Are you able to reproduce again or was this a fluke? I'm wondering if you can still reproduce, could you provide more information on ways you can get it to reproduce vs ways you can get it to not reproduce?

**Comment by bsclifton** [comment] 2017-01-06 06:42
@srirambv did you have more information about this?

**Comment by srirambv** [comment] 2017-01-06 09:18
@bsclifton I am not able to repro the steps now. I was able to consistently reproduce the issue at the time the defect was logged.

**Comment by bbondy** [comment] 2017-01-08 14:21
I'll close this for now but if you see it again please re-open.

**Closed by bbondy** 2017-01-08 14:21 UTC
Labels: bug, chromium54, info-needed, needs investigation, OS/Windows
