### ISSUE TITLE
Black page after DevTools was disconnected from the page.

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#1603] opened 2016-05-07 00:34 UTC
Reproducible steps:

1. Go to any page, e.g. www.brave.com
1. Open DevTools (or inspect any element), and switch to _Network_ tab.
1. Reload the page (OS X: CMD-R)

Reasult:

Website becomes black, icon shows it's loading endlessly and Developer Tools shows the following message:

> DevTools was disconnected from the page.

> Once page is reloaded, DevTools will automatically reconnect.

Refreshing page again does the same thing.

Could be related: #1053

**Comment by luixxiul** [comment] 2016-05-08 09:14
Same here on Windows 10.

**Comment by diracdeltas** [comment] 2016-05-09 07:05
I've noticed this too on recent OS X versions

**Comment by diracdeltas** [comment] 2016-05-09 21:19
Closing as dupe of #1588

**Closed by diracdeltas** 2016-05-09 21:19 UTC
