### ISSUE TITLE
About pages not loading in private tab

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#4823] opened 2016-10-15 15:24 UTC
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**

If you try to open an about page while you are browsing a private tab you get stuck with a blank page.

**Expected behavior:**

The page should open

- Platform (Win7, 8, 10? macOS? Linux distro?): all

- Brave Version: 0.12.5

- Steps to reproduce:
    1. Open new private tab
    2. Type about:adblock
    3. See the page stays blank

**Comment by bbondy** [comment] 2016-10-15 23:48
dupe of https://github.com/brave/browser-laptop/issues/1817

**Closed by bbondy** 2016-10-15 23:48 UTC
Labels: bug, duplicate
