### ISSUE TITLE
History appears to be completely broken

### ISSUE THREAD

**Issue by FrancisTurner** [brave/browser-laptop#505] opened 2016-02-01 04:11 UTC
This is related to Issue #444 

It looks like in recent builds (I haven't had the ability to try older ones) for both Windows and Linux, history is not working at all.

In addition to the non functional CTRL-Y and the related lack of functionality of the History menu, CSS related to the "A:Visited" CSS object is not displayed even when the user has visited a link and then returned to the original page. This is NOT a CSS issue because (for example) the A:Hover CSS works fine 

Step to reproduce. 

1. Google Something e.g. "brave issues"
2. Go to the page of one of the hits
3. Go back to the gogole search page
4. Note that the link you visitied is still blue not purple as it is with any other browser

In addition while indiviual back/forward actions are possible, the standard behavior of a long click on the back (or where relevant forward) button providing a pull down list of recent history doesn't work.

Using 0.7.11 on windows and whatever the build is retrieved at approx 0:00 UTC on Feb 1 for LInux

**Comment by bbondy** [comment] 2016-02-01 04:56
History is not implemented yet, I'm going to close this as a dupe of #444 and adjust the title there a bit more to make it more clear.

**Closed by bbondy** 2016-02-01 04:56 UTC
Labels: design

**Comment by FrancisTurner** [comment] 2016-02-01 05:27
That explains it :)

**Comment by bbondy** [comment] 2016-02-01 05:34
Would you mind posting the link stuff you wrote into a new issue? I'm not aware of an issue like that on file so that one would be good in a new issue just for that if you don't mind. Thanks!
