### ISSUE TITLE
Alt+left/right_arrow_key opens menu bar every time on Fedora Workstation 28  

### ISSUE THREAD

**Issue by NachiketaVadera** [brave/browser-laptop#15235] opened 2018-09-27 15:52 UTC
### Description
The (alt+left/right_arrow_key) that is used to navigate to the back/front page, the menu bar opens up every time. This dose not happen in Windows.

### Steps to Reproduce

  1. I use Fedora 28 Workstation with the latest version of Brave installed as of today. 
  2. Open brave and go to any webpage.
  3. Try to navigate back using the alt+left_arrow_key and see the menu bar pop up.

**Actual result:**

Menu bar gets displayed every time in Linux but not in Windows.  

**Expected result:**

I use the latest Brave update as of posting of this issue.

**Comment by eljuno** [comment] 2018-09-27 19:50
Duplicate of #5775?

**Comment by bsclifton** [comment] 2018-09-28 07:06
@eljuno yup- I do believe this is a duplicate of https://github.com/brave/browser-laptop/issues/5775

@NachiketaVadera if you'd like to try out Beta, this issue should be resolved. You can check it out here:
https://brave.com/download-beta/

**Closed by bsclifton** 2018-09-28 07:06 UTC
