### ISSUE TITLE
Implement hamburger menu

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#218] opened 2016-01-21 02:19 UTC

**Comment by diracdeltas** [comment] 2016-01-22 04:06
is this like on Chrome where the hamburger menu is just a duplicate of commonly-used app menu items?

**Comment by diracdeltas** [comment] 2016-01-22 04:07
![screen shot 2016-01-21 at 20 06 58](https://cloud.githubusercontent.com/assets/549654/12502184/8d4b1450-c07a-11e5-89c8-a92576b76a34.png)

**Comment by bbondy** [comment] 2016-01-22 04:34
The button itself was in the design spec but not specified what's in it.  Something like that makes sense to me.

**Comment by bradleyrichter** [comment] 2016-01-27 00:20
Here is a menu definition that captures some of the top-level functions, and also introduces the top level items from the Bravery menu which will soon be used on a per-site basis. I omitted the standard chrome-style zoom and edit items for now to save space, as they are the most known keyboard shortcuts. If we find out that they are needed, we can add them later.

@diracdeltas Please migrate the current windows/mac kbd shortcuts in case these are mislabeled.

![brave_hamburger_menu](https://cloud.githubusercontent.com/assets/13509546/12599635/81c0d990-c448-11e5-84c8-095df6a5c8ab.png)

**Comment by jonathansampson** [comment] 2016-01-27 03:07
Am I correct that the button, for now, is entirely non-operable? I was clicking it, and seeing no response. I suspected it might have been a bug, but this ticket is making me think otherwise :)

**Comment by bbondy** [comment] 2016-01-27 03:40
snatching this, hope you didn't already start Yan

**Comment by bbondy** [comment] 2016-01-27 03:49
The button does nothing before 0.7.10.
It will be fixed in 0.7.10 when we do that release.

**Closed** 2016-01-27 03:48 UTC
