### ISSUE TITLE
Regression : Reload and Bookmark icons are misaligned vertically

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3921] opened 2016-09-12 16:23 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
In the latest build, the reload and bookmark icons are misaligned.

**Expected behavior:**
All items on the primary nav should be centered vertically.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X.

- Brave Version:
0.12.1 Preview3

- Steps to reproduce:
    1. Open the latest build

- Screenshot if needed:
<img width="1154" alt="screen shot 2016-09-12 at 11 18 18 am" src="https://cloud.githubusercontent.com/assets/1434040/18443551/034b6b64-78db-11e6-894c-cb5cdb927a9d.png">

- Any related issues:

**Comment by bbondy** [comment] 2016-09-12 16:43
Dupe of something Brad recently posted:
https://github.com/brave/browser-laptop/issues/3917

**Closed by bbondy** 2016-09-12 16:43 UTC
