### ISSUE TITLE
Brave processes do not close (randomly?) when the main window is closed.

### ISSUE THREAD

**Issue by gophren** [brave/browser-laptop#1334] opened 2016-04-11 10:55 UTC
After some extensive browsing (many sites, one hour or more of browsing), some of the brave.exe processes are still showing in Task Manager after closing the main windows. I am not talking about looking in the Task Manager the first 5 seconds after I close the windows, but after 30+ minutes of pause.
TCPView does not show any existing connection at that time (that is, 30+ minutes after closing the main window), but immediately after exiting the application it was still showing some connections.

This remanent processes do not occur every time, I tried to quickly reproduce it by launching gmail, youtube, closing Brave after a few minutes and everything went all right. I am not sure what kind of content (or what manipulation) triggers the abnormal behaviour.

![brave01](https://cloud.githubusercontent.com/assets/12759138/14424943/a941c134-ffec-11e5-9268-df86f474c39b.JPG)
![brave02](https://cloud.githubusercontent.com/assets/12759138/14424874/2b7918ba-ffec-11e5-89a7-545ddbb5b0b2.JPG)
![brave03](https://cloud.githubusercontent.com/assets/12759138/14424873/2b752ad4-ffec-11e5-94b4-5ad56607bea5.JPG)

**Comment by bbondy** [comment] 2016-04-11 12:56
Thanks for the report I've noticed some extra processes sometimes too, I'll take a look.

**Comment by gophren** [comment] 2016-04-11 13:33
Not sure if this helps or not, but I managed to catch it again and I looked at it with Process Explorer:

![brave04](https://cloud.githubusercontent.com/assets/12759138/14428738/097a2af8-0003-11e6-8d37-1e408d2856a9.JPG)

**Comment by bbondy** [comment] 2016-04-19 18:33
This might be fixed with electron upstream which @bridiver is working on getting us rebased to.  If not then I'm leaving this open to look into for 0.9.3.

**Comment by bbondy** [comment] 2016-05-13 11:46
this is a dupe of https://github.com/brave/browser-laptop/issues/1540 and it should be fixed in 0.9.6

**Closed by bbondy** 2016-05-13 11:46 UTC
