### ISSUE TITLE
Shortcuts missing Brave logo

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6322] opened 2016-12-20 10:09 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Shortcuts missing Brave logo

**Expected behavior:**
Shrotcuts should contain Brave logo

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 5

- Steps to reproduce:
    1. Do a clean install of 0.13.0 Preview 5
    2. Desktop shortcut doesn't contain Brave logo
    3. Launch Brave, taskbar doesn't contain Brave logo 

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/21346127/dfeddcc0-c69a-11e6-8118-e6da212b8a1f.png)

- Any related issues: #6313

**Comment by srirambv** [comment] 2016-12-20 10:26
cc: @aekeus @bsclifton 

![shortcut](https://cloud.githubusercontent.com/assets/17010094/21346962/964e8f7a-c69e-11e6-87cf-95b0cf3a55e1.gif)

**Comment by bsclifton** [comment] 2016-12-20 16:58
dupe of https://github.com/brave/browser-laptop/issues/6313; I'll capture some notes in there

**Closed by bsclifton** 2016-12-20 16:58 UTC
Labels: OS/Windows, regression, release/blocking
