### ISSUE TITLE
change styling of box outline and fonts in private tabs page

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#14167] opened 2018-05-17 22:28 UTC
current:

![image](https://user-images.githubusercontent.com/13509546/40206838-8f3b356c-59e6-11e8-9d23-f4dac29101f4.png)

proposed:

![image](https://user-images.githubusercontent.com/13509546/40206869-a3116cc8-59e6-11e8-926b-05e0ff780832.png)

needs: CSS replacent

**Comment by diracdeltas** [comment] 2018-05-17 22:36
@rossmoody are you doing the restyling? if so you should work off of the `tor/0.23.x` branch

note that the 'Learn more...' text should be kept even though it's missing in the mockup

**Comment by rossmoody** [comment] 2018-05-17 22:39
I'm getting up to speed on git process and this is my trial ticket Brad's helping me with. I'm going to attempt a restyling of sorts here but ty for the heads up on both fronts there.

**Comment by diracdeltas** [comment] 2018-05-17 22:42
@rossmoody cool. FYI the object you will want to edit is `styles` in js/about/newprivatetab.js

**Comment by diracdeltas** [comment] 2018-05-22 16:43
fixed by https://github.com/brave/browser-laptop/commit/4ebc04b7882da1c210186aee6cf8d97e981585f3

**Closed by diracdeltas** 2018-05-22 16:43 UTC
Labels: design, feature/tor

**Comment by kjozwiak** [comment] 2018-06-20 15:48
Verified on macOS 10.13.4 x64 using the following build:

* `0.23.11` 6565c0689f8bfbd6f4d03e2e8c68c9381da157f6 
* muon: `7.1.0`
* libchromiumcontent: `67.0.3396.87`

Example:

<img width="1346" alt="screen shot 2018-06-20 at 11 48 00 am" src="https://user-images.githubusercontent.com/2602313/41669446-ce40df74-747f-11e8-80eb-94e79ec5c797.png">

**Comment by kjozwiak** [comment] 2018-06-20 16:15
@bradleyrichter the current text differs from the `proposed` screenshot in the original comment. Can you please confirm that the one I added above is the expected text/design?

**Comment by bradleyrichter** [comment] 2018-06-22 21:40
this needs to defer to @flamsmark and @mandar-brave because it has changed a few times since the original screen shot that has become git-stale.

**Comment by diracdeltas** [comment] 2018-06-22 21:48
@bradleyrichter i can confirm this is using the latest text that @flamsmark drafted (to the best of my knowledge)

**Comment by bradleyrichter** [comment] 2018-06-22 21:50
ok. And it looks fine to me anyway.

cc @kjozwiak

**Comment by kjozwiak** [comment] 2018-06-23 02:14
Thanks @bradleyrichter @diracdeltas 👍 

@srirambv @btlechowski @GeetaSarvadnya looks like what we're currently seeing is the correct text.

**Comment by kjozwiak** [comment] 2018-06-23 02:16
Verified using `macOS 10.13.4 x64` using the following build:

* `0.23.14` f4da85553f32e2c31539bab6cfbf32619ef0a936 
* muon: `7.1.1`
* libchromiumcontent: `67.0.3396.87`
