### ISSUE TITLE
Browser loses start up position

### ISSUE THREAD

**Issue by dhocker** [brave/browser-laptop#389] opened 2016-01-28 20:40 UTC
Environment:
OS X 10.11.3
Dual monitor system (left and right)

Steps to recreate:
1. Start Brave (appears on the left monitor).
2. Move the browser window to the right monitor.
3. Quit Brave
4. Start Brave.

Expected: Brave should start on the monitor where it was last closed.
Actual: Brave appears always starts on the left monitor.
Severity: Minor, cosmetic.

**Comment by bbondy** [comment] 2016-01-28 20:53
Thanks for the report, we have another copy of this though.
Dupe of #146

**Closed by bbondy** 2016-01-28 20:53 UTC
