### ISSUE TITLE
Browser window adds 1px noise on top making it hard to restore/maximize the window

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14434] opened 2018-06-15 19:24 UTC
### Description
Browser window adds 1px noise on top making it hard to restore/maximize the window

### Steps to Reproduce
No exact steps to reproduce. Happens once a while

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/41485773-e30fa4cc-70af-11e8-9e99-954af87ab75e.png)

**Expected result:**
Should not add noise on browser window

**Reproduces how often:**
~80%

### Brave Version

**about:brave info:**

Brave | 0.22.810
-- | --
V8 | 6.7.288.43
rev | 8f30eeb
Muon | 7.0.6
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.71

**Reproducible on current live release:**
Yes

### Additional Information
Slack also has this problem but doesn't happen as often as in Brave.

**Comment by bsclifton** [comment] 2018-06-18 06:48
I believe this is a duplicate of https://github.com/brave/browser-laptop/issues/7211 - closing

**Closed by bsclifton** 2018-06-18 06:48 UTC
Labels: OS/Windows, bug, needs-investigation
