### ISSUE TITLE
Not saving the ledger statement and closing browser causes background process to keep running

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8466] opened 2017-04-24 11:09 UTC
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Not saving the ledger statement and closing browser causes background process to keep running. Subsequent browser launch fails due to the existing background process
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64
- Brave Version (revision SHA):
Brave	0.15.0
rev	8e63cc0
- Steps to reproduce:
    1. Enable ledger payments and ensure you have payment history
    2. Click on any of the staments to open the statment in a new tab
    3. Click cancel in the file save prompt
    4. Close the browser window and start it from terminal
    5. Browser doesn't launch shows error message about GPU
    6. Open task manager, right click  on the first background process and end task
    7. Save file prompt is opened, console shows `Windows crash. Reloading...` 
    8. Have to kill other background process so that everything is cleared and only then can re-launch the browser
    
- Actual result:
Not saving the ledger statement and closing browser causes background process to keep running
- Expected result:
Process should be killed when the browser is quit. 
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![ledgercrash](https://cloud.githubusercontent.com/assets/17010094/25334503/b5ecc0a4-28e6-11e7-9703-62a442ccc8fe.gif)

- Any related issues:
cc: @bridiver @bbondy

**Comment by bsclifton** [comment] 2017-05-02 17:28
@srirambv does this happen if you do file > save as on a regular page and then close the tab?

**Comment by bsclifton** [comment] 2017-05-02 18:06
Closing as a dupe of https://github.com/brave/browser-laptop/issues/8629

**Closed by bsclifton** 2017-05-02 18:06 UTC
Labels: bug, feature/ledger, OS/Windows, QA/steps-specified
