### ISSUE TITLE
Focus switches to pinned tab when a tab is closed

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8547] opened 2017-04-28 10:13 UTC
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Focus switches to pinned tab when a tab is closed
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7 ia32
- Brave Version (revision SHA):
Brave	0.15.1
rev	0598ddf
- Steps to reproduce:
    1. Clean install 0.15.0 
    2. Pin a site and open 4-5 new tabs / visit sites in them
    3. Upgrade to 0.15.1 while the browser window is opened
    4. Wait for the browser to close and upgrade and relaunch
    5. Ensure the tabs are still available after upgrade
    6. Close one of the tabs, focus doesn't switch to the parent tab(default setting), instead focus goes to the pinned tab
    
- Actual result:
Focus switches to pinned tab when a tab is closed
- Expected result:
Focus should be based on the selection done in `about:preferences#tabs`
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes, Was able to reproduce in 0.15.0 upgrade from  RC5 to RC6 
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1. After upgrade focus on any of the normal tabs 
    2. Close the tab, focus is on pinned tabs
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment] 2017-05-02 17:39
May be fixed by https://github.com/brave/browser-laptop/pull/8580; @srirambv can you recheck with 0.15.2 preview 2 (or master)

**Comment by srirambv** [comment] 2017-05-02 20:19
This is still an issue on 0.15.2 preview 2 when the browser is relaunched  closing any tab switches it to the last pinned tab.

**Comment by bsclifton** [comment] 2017-05-12 17:55
Moving to 0.15.3xx since this is a regression from the 0.15.2 that was released (0.15.2 mentioned above ended up turning into 0.15.3xx)

**Comment by bbondy** [comment] 2017-05-16 15:52
@bridiver did you fix this already?

**Comment by alexwykoff** [comment] 2017-05-16 15:52
@srirambv let's retest this after the latest builds

**Comment by bsclifton** [comment] 2017-05-16 18:58
Looks good to me 😄  Fixed with https://github.com/brave/browser-laptop/pull/8863

**Closed by bsclifton** 2017-05-16 18:58 UTC
Labels: bug, feature/pinned-tabs, feature/tabsbar, QA/steps-specified, regression
