### ISSUE TITLE
Youtube notifications does not work

### ISSUE THREAD

**Issue by Crossoni** [brave/browser-laptop#4504] opened 2016-10-04 16:25 UTC
**Did you search for similar issues before submitting this one?**
Yes.
**Describe the issue you encountered:**
Youtube notifications do not work, they do not show up and when I press the notification "bell" it just shows up a blank screen.
**Expected behavior:**
Should show up new notifications.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 7
- Brave Version:
I don't know, newest there is now.
- Steps to reproduce:
    1. Open youtube
    2. Click notifications
    3.

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment] 2016-10-04 17:55
Closing as duplicate of #2320 #3152 #3994

**Closed by srirambv** 2016-10-04 17:55 UTC

**Comment by bsclifton** [comment] 2016-10-04 18:25
@Crossoni please track by subscribing to one of the issues that @srirambv posted :smile: 

As a work-around, you can try turning shields off (click the lion head in top right, toggle off). However, please note that disabling this will disable it for the entire domain (all of youtube.com in this example)
