### ISSUE TITLE
Dead tabs when system wakes up from sleep

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9865] opened 2017-07-05 11:36 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Dead tabs when system wakes up from sleep

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.17.13
rev	f7242c7
Muon	4.1.7

- Steps to reproduce:
    1. Install 0.17.3 build
    2. Use browser normally and ensure there is enough browsing history and multiple tabs opened with backgrounded tabs
    3. With browser window active put computer to sleep -> Start -> Power button -> Sleep
    4. Wake up system from sleep and try to switch to tabs, none are useable
    5. Quit and restart browser, able to switch to all tabs
    
- Actual result:
Dead tabs when system wakes up from sleep

- Expected result:
Tabs should work normally and should be able to switch when system wakes up from sleep

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Mostly yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
cc: @bbondy

**Comment by bridiver** [comment] 2017-07-05 13:22
@srirambv is this a new issue or can you repro in previous releases?

**Comment by srirambv** [comment] 2017-07-05 13:55
@bridiver Couldn't reproduce the same on 0.16.9.

**Comment by bridiver** [comment] 2017-07-05 13:58
Thanks @srirambv. Does it go back to earlier 0.17 versions? If we know the exact version it was introduced in it will be easier to track down the problem

**Comment by bbondy** [comment] 2017-07-11 17:38
@srirambv

**Comment by srirambv** [comment] 2017-07-12 06:11
@bridiver I wasn't able to consistently reproduce this on all the previous 0.17.x versions. It did happen once on 0.17.9 during which I found #9972.

**Comment by bridiver** [comment] 2017-07-13 02:18
@srirambv couldn't reproduce consistently or couldn't reproduce at all?

**Comment by srirambv** [comment] 2017-07-13 08:35
@bridiver  couldn't reproduce on all versions except 0.17.9. Out of 3 attempts only once it happened on 0.17.9. 

+1 from community user(Numpty) https://community.brave.com/t/brave-freezes-completely-after-a-while-of-non-usage/3444/

**Comment by bridiver** [comment] 2017-07-13 23:00
0.17.9 went from muon 4.1.3 to 4.1.4, but this was the only change https://github.com/brave/muon/commit/2befbb73253124c71ec0fd8e9b25f9e6bccb165f
I'll try on master and see if I can repro

**Comment by zentagonist** [comment] 2017-09-05 17:21
Punting back to Sriram - can you still repro this issue?

**Comment by srirambv** [comment] 2017-09-07 16:25
@zentagonist  I haven't seen this happen on the 0.18.x build. Have tried on both new profile and existing profile but haven't seen dead tabs.

**Comment by ricardosaracino** [comment] 2017-09-08 21:25
i just got back home opened up from sleep

closed brave and process list looks like this
![image](https://user-images.githubusercontent.com/759253/30231815-bc922d3c-94ba-11e7-87c4-8f7da80247b4.png)

**Comment by srirambv** [comment] 2017-10-05 11:54
Just reproed this on 0.19.29. Dead tabs after system woke up from sleep. Unable to switch to pinned tabs or other tabs. Unable to quit or close had to kill via task manager

cc: @bridiver

**Comment by mattnewport** [comment] 2017-11-24 05:10
I see this pretty consistently on 0.19.95 but it doesn't seem to affect all tabs. 'Dead' tabs cannot be selected, tabbed to or closed.

**Comment by srirambv** [comment] 2017-12-05 11:11
+1 from https://community.brave.com/t/tabs-freeze-all-the-time/11568 on 0.19.105

**Comment by vitorschwartz** [comment] 2017-12-11 01:56
Dear Brave community, 
Any estimate of when this will be fixed? IMO, this is one of the most annoying bugs of Brave =/
I'm back using Chrome because I get these zombie tabs so often with Brave, and I was wasting too much time to reopen the browser a couple times per day...
Thank you very much!

**Comment by jonathansampson** [comment] 2017-12-21 17:37
+1 from Twitter: https://twitter.com/christianbute/status/943897324237008898

**Comment by jonathansampson** [comment] 2018-01-21 03:09
I just received another +1 from Twitter over DM.

**Comment by AwesomeTech10** [comment] 2018-02-01 00:03
I think this issue got fixed

**Comment by NejcZdovc** [comment] 2018-02-14 06:09
@petemill is this one still open?

**Comment by petemill** [comment] 2018-02-14 06:12
@NejcZdovc Technically not, since we disabled the feature that's causing the issue, but if we re-enable the feature the problem is still there, and I'm working on it in #13120

**Comment by NejcZdovc** [comment] 2018-02-14 06:14
@petemill can you please add closing keyword for this issue into #13120?

**Comment by petemill** [comment] 2018-02-20 20:46
I'm actually closing this as it's covered pretty well in #10673

**Closed by petemill** 2018-02-20 20:46 UTC
Labels: OS/Windows, bug, feature/tabsbar, needs-info, priority/P3

**Comment by srirambv** [comment] 2018-02-23 12:47
@petemill shoudl #10673 and this be marked as `QA/no-qa-needed`  based on https://github.com/brave/browser-laptop/issues/10673#issuecomment-367114377

**Comment by LaurenWags** [comment] 2018-02-27 14:43
+1 from community DM
