### ISSUE TITLE
Clearing 'All site cookies' also clears Extension data in localStorage

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#13098] opened 2018-02-12 01:36 UTC
### Description
Users who have configured Brave to _Clear site cookies_ when the browser closes will also find that their extension-related local storage is also cleared. This causes them to be logged out of extensions like LastPass.

### Steps to Reproduce
1. Configure Brave to _clear all site cookies_ on close in _about:preferences#security_.
2. Enable and sign-into the LastPass extension
3. Restart Brave

**Actual result:**
LastPass thinks that it was just enabled, and prompts the user for credentials.

**Expected result:**
LastPass is able to persist state-related data between browsing sessions.

**Reproduces how often:**
Always

### Brave Version
0.20.39

**about:brave info:**
```Brave: 0.20.36 
V8: 6.4.388.41 
rev: bba0b928164f8b3056a1d9be02c738c66202807c 
Muon: 4.7.10 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
```

**Reproducible on current live release:**
Yes

### Additional Information
This issue was recently reported to us by [Joe Weaver, on Twitter](https://twitter.com/JoeWeaverDev/status/961761247203962880). If and when this issue is resolved, we should reach out to inform the user:

![image](https://user-images.githubusercontent.com/815158/36081946-4dfb88a2-0f6a-11e8-8d52-b7dfe765d391.png)

**Comment by srirambv** [comment] 2018-02-12 02:15
dupe of https://github.com/brave/browser-laptop/issues/7274?

**Comment by jonathansampson** [comment] 2018-02-12 02:26
@srirambv I would suggest we close #7274 in favor of this one, since this refers to _all extensions_, whereas that issue sounds like it may be limited to one in particular. Your call though :)

**Comment by srirambv** [comment] 2018-02-12 02:36
Sounds good. Closed it in favour of this

+1 from @whitgroves @newm-newm @twhiting via #7274

**Closed** 2018-08-28 18:45 UTC
Labels: feature/cookies, feature/extensions, fixed-with-brave-core, privacy, sec-low, wontfix
