### ISSUE TITLE
Brave frequently logs users out of various websites while logged in

### ISSUE THREAD

**Issue by Brave-Matt** [brave/browser-laptop#14959] opened 2018-08-06 22:19 UTC
**Have you searched for similar issues?** 
Yes [see below]

### Description
There have been several reports across support channels that Brave terminates users login sessions for various websites after they've logged in (with or without login information saved). Most people reporting the behavior cite Facebook, Google, Youtube, Yahoo!, Luminosity, Medium and several others, but the issue doesn't seem to be limited to any particular set of sites (if you can log into it, this error could occur). 
This issue is similar to a few others, but unlike those the behavior seems to be [somewhat] intermittent and without obvious cause, which is why I created a separate issue.
Related:
#13030 <--- Error occurs _when closing/reopening Brave_
#14781 <--- Error occurs _when clicking on something within the same tab/site_
#14444 <--- Error occurs _after browser crash or close_

### Steps to Reproduce
  1. Open Brave, navigate to a site that requires login credentials 
  2. Enter credentials and confirm you're logged in [to your account]
  3. Open new tabs and do other stuff (visit other websites, download something, etc)

**Actual result:**
The website that was logged into has ended your session and logged  you out. You must reenter credentials. 

**Expected result:**
You are not logged out of the website 

**Reproduces how often:**
Randomly/intermittently

### Brave Version
[See user posts below]

**Reproducible on current live release:**
Yes

### Additional Information
Its worth mentioning that I personally have not had this issue (so far) and thus am unable to reproduce it. Users also seem unable to find any specific cause. I've linked to 3 reports of the behavior below, however I've seen this in at least 3 more threads which I'll dig them up and add them as I find them:
[From Community [1]](https://community.brave.com/t/logouts-happening-for-no-reason/24013)
[From Community [2]](https://community.brave.com/t/pages-randomly-refresh-drastically-wiping-cookies/26571/7)
[From Twitter](https://twitter.com/BluprintStudio_/status/1025501417660928000)

**Comment by bsclifton** [comment] 2018-08-13 06:41
This may be a duplicate of https://github.com/brave/browser-laptop/issues/13030

**Comment by Brave-Matt** [comment] 2018-08-13 16:07
@bsclifton, the behavior is roughly the same but reproducing it is different. In #13030, users are logged out on close whereas this issue seems to log users out while browsing.

> This issue is similar to a few others, but unlike those the behavior seems to be [somewhat] intermittent and without obvious cause, which is why I created a separate issue.

I imagine the fix is probably the same but that it was worth noting that it presenting in more than one way.

**Comment by Brave-Matt** [comment] 2018-08-14 16:58
+1 from Reddit: https://www.reddit.com/r/brave_browser/comments/96r1w8/cookies_on_brave/e44ih9x

**Comment by LaurenWags** [comment] 2018-08-21 13:11
+1 from community: https://community.brave.com/t/getting-auto-logged-out-browser-crash/30386

**Comment by Brave-Matt** [comment] 2018-08-28 17:45
+1 from Reddit, I'm going to include an excerpt from the actual report as it goes into decent detail (minus the shade thrown at Chromium): https://www.reddit.com/r/brave_browser/comments/9ar3lp/constantly_logged_out_of_everything/

> I have third party cookies and third party fingerprinting disabled, so to my understanding, it should keep me logged in. it seems like the main problem is that it's built on chromium, which force closes all tabs the split second you step away from them, and then reloads them when you return. upon return to the tab, the reload fails in many ways:
> 
> it typically logs you out
> 
> it typically spins forever, and never loads the page
> 
> if it manages to load the page, it would load only some things, like on youtube, it may load the video, but fail to load comments
> 
> if you're using tor tab, you literally must not leave the tab, cause the moment you do, chrome shuts it down, and when you come back to it and it reloads, it seems to be forgetting it is supposed to be reloading via tor, or the tab is simply disconnected from tor network, either way, the only way to go back to the page, is to open new tor tab and go back to the page in it, but that just means you can't leave this tab now cause it's new, and same thing would happen.
> 
> it seems at this point this would be a good browser, if only it wasn't built on crappy chrome.
> 
> I found online that adding --disable-automatic-tab-discarding to brabe target should prevent tabs from being force closed, and it did seem to work for a few hours, but it doesn't work any more. maybe I should close and reopen entire browser. at any rate, this constant reloading of pages is a huge problem, and if someone knows how to prevent it, please let me know

**Comment by bsclifton** [comment] 2018-10-19 06:58
Thanks for the report - I'd like to ask if folks experiencing this can try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser

**Closed by bsclifton** 2018-10-19 06:58 UTC
Labels: bug, needs-info
