### ISSUE TITLE
wallet preference page is not refreshing itself when a bitcoin handler is registered

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6770] opened 2017-01-20 07:10 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When executing the ledger regression tests, it was found that https://jsfiddle.net/LnwtLckc/5/ did not appear to have registered appropriately. Upon further investigation, it was discovered that the real issue was that the preference page was not updating when the handler was being registered/unregistered like it had in prior releases. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.13.0 Preview 10 (c60b783)

- Steps to reproduce:
    1. clear your session, open brave
    2. open preferences, create a wallet
    3. in a new tab, visit https://jsfiddle.net/LnwtLckc/5/, click on register
    4. switch tabs back to preferences, check add funds modal, notice lack of 'transfer btc' button
    
- Actual result:
'transfer btc' button does not appear in the modal

- Expected result:
'transfer btc' button should appear in the modal

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
no

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![btc_handler](https://cloud.githubusercontent.com/assets/1434040/22139680/29c54944-dead-11e6-8564-aacb74561db9.gif)

- Any related issues:

**Comment by luixxiul** [comment] 2017-01-21 02:17
Confirmed on 0.13.1 RC4 on Windows 10 32 bit

**Comment by mrose17** [comment] 2017-01-27 00:00
the issue appears to be that [updateAboutDetails](https://github.com/brave/browser-laptop/blob/master/js/components/frame.js#L90) is invoked when a tab is created, but not when you switch to it.

looking at earlier versions, e.g., https://github.com/brave/browser-laptop/blob/0_12_14_release_notes/js/components/frame.js#L93 it looks like a looser test was used.

@bbondy - `git blame` suggests that i ask you about the intent here. thanks!

**Comment by bbondy** [comment] 2017-01-27 16:06
howdy mrose, you'll have to pass in props for if it's registered, I'm a bit concerned about a perf problem here though.  Maybe we should  add an event when a protocol is registered and handle it? @bridiver

**Comment by mrose17** [comment] 2017-01-27 17:02
@bbondy - i am sensitive to the performance issue. since this code is 90% browser internals and 10% ledger-related, i'd like to have it re-assigned to someone who knows the internals and can make a performant/correct fix.

**Closed** 2017-03-02 21:37 UTC
Labels: bug, feature/ledger, regression

**Comment by srirambv** [comment] 2017-03-03 07:59
Working on 0.13.5 RC3
