### ISSUE TITLE
Consistent blank pages (possible driver issue)

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4928] opened 2016-10-19 01:53 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user from support is experiencing consistent blank pages with Brave, other browsers are displaying appropriately. 

**Expected behavior:**
Brave should behave the same as other browsers. (User confirmed Firefox and Edge are working appropriately.)
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:
  https://linkbubble.zendesk.com/agent/tickets/5821

**Comment by privatzee** [comment] 2016-10-19 16:05
I did get a blank page once. IIRC, it was from "Open Link in New Window"

**Comment by privatzee** [comment] 2016-10-19 19:11
Speak of the devil, it just happened again and definitely from ""Open Link in New Window". No blinking, btw; just plain, solid white.

**Comment by seanms** [comment] 2016-10-27 16:05
This is happening regularly to me on Fedora 23 x86_64.  It always starts by opening a link in a new tab.  Once the browser is in this state:
- All new tabs are rendered blank until the browser is restarted.  Existing tabs will continue to display properly when refreshed.
- The developer tools show all the page elements are present.
- If you mouse over (invisible) links within the page, you can see the link pop-op display in the lower right corner.  If you click on the link, you can follow it.  The resulting new page will still be blank.
I hope someone can look into this soon; it's the one issue preventing me from using Brave as my default browser.

**Comment by brianpatrickreavey** [comment] 2016-10-27 17:56
I am experiencing this same issue on Fedora 24 x86_64.  If I open a new window (not restart Brave) the tabs work for a time in that new window until the "blank" tabs start appearing again.  I experience all the same issues and behavior as @seanms .  This occurred on both 0.12.4 and now on 0.12.6.

**Comment by bsclifton** [comment] 2016-10-28 07:05
@seanms @brianpatrickreavey can you try going into preferences > advanced and disabling hardware acceleration? (after value is changed, it would require you to exit and re-launch Brave)
I'm curious if this setting is causing the issue

**Comment by seanms** [comment] 2016-10-28 15:04
Disabling hardware acceleration doesn't help.

**Comment by brianpatrickreavey** [comment] 2016-10-28 15:25
Same for me.  It occurs with and without hw acceleration.

**Comment by bsclifton** [comment] 2016-10-28 15:29
doh- ok thanks for checking

**Comment by bsclifton** [comment] 2016-11-06 07:24
This issue may be related to https://github.com/brave/browser-laptop/issues/4113

**Comment by bsclifton** [comment] 2016-11-06 07:30
also may be related to https://github.com/brave/browser-laptop/issues/1471

**Comment by luixxiul** [comment] 2016-11-06 09:25
Whether this is duping to #1471 can be diagnosed on the steps specified here: https://github.com/brave/browser-laptop/issues/1471#issuecomment-251916315

**Comment by seanms** [comment] 2016-11-06 17:40
Following the steps in #1471 comment #3787 reproduces this.

**Comment by brianpatrickreavey** [comment] 2016-11-09 19:10
Confirmed as well.  Navigating to http://www.quirksmode.org/html5/tests/video.html#link2 causes the issue to occur immediately.

**Comment by NQAT** [comment] 2016-11-11 06:41
I'm getting these all the time now. I think it has something to do with the hover effect on tabs and the transition between tabs. You can still click stuff but not see anything. Happening a lot when I right click search something.

**Comment by ConorIA** [comment] 2016-11-28 06:07
Just thought I'd chime in. I experience this bug on my desktop with the open source radeon driver. 
I do not experience the bug on my laptop with the Nvida proprietary driver. 
I also did not experience it on my desktop before moving from the proprietary Catalyst driver to the FLOSS driver.

**Comment by brianpatrickreavey** [comment] 2016-11-30 16:16
I am also using the open source radeon driver.  This persists on Fedora 25 under Wayland and X.org, on Brave 0.12.10.

**Comment by brianpatrickreavey** [comment] 2016-12-01 16:12
I have removed the Radeon card from my system, and am using the onboard Intel graphics.  So far, I have been unable to reproduce the error.  Everything is now working as expected.

**Comment by brianpatrickreavey** [comment] 2016-12-01 16:19
More specifically, even using the onbaord graphics card, if the Radeon card was still in the system (and hence the driver was being loaded), the issue would persist.

**Comment by bsclifton** [comment] 2016-12-01 17:02
@brianpatrickreavey wow- thanks for the updated notes.  It's really unusual that it happened for you with and without hardware acceleration... but then works after removing the card.  It may be an issue with AMD's driver? I'll see if I can find any way to report this to them (so we can find the root cause)

**Comment by sroerick** [comment] 2016-12-01 23:20
I have the same issue, using the open source (not proprietary) drivers.

**Comment by bsclifton** [comment] 2016-12-10 16:56
OK folks- I have a possible work-around that you can try; cc: @sroerick @brianpatrickreavey @NQAT @ConorIA 

Please try launching Brave with extra arguments, specifically adding `--ignore-gpu-blacklist`

You can see my full response here: https://github.com/brave/browser-laptop/issues/1471#issuecomment-266158825

**Comment by seanms** [comment] 2016-12-18 00:32
I've been running with this work-around for several days, and no blank tabs.  Thanks for tracking this down @bsclifton.

**Comment by bsclifton** [comment] 2016-12-18 08:47
@seanms awesome! thanks for the update :smile:

**Comment by luixxiul** [comment] 2017-01-22 15:44
We got another report here: https://community.brave.com/t/brave-wont-launch/280/8?u=suguru

Is there any way of avoiding the issue on Windows? I am not sure how to set flags as you do on Linux.

**Comment by lukemulks** [comment] 2017-04-09 07:54
We've had a report of a user getting a blank white tab after clicking a preview image to view the original in a new tab: https://community.brave.com/t/adblock-not-blocking-ads-can-someone-please-help-and-give-me-example-blocked-url-image-format/1607/16?u=luke.mulks

The issue provided above matches the feedback provided higher up in this thread.

**Comment by bsclifton** [comment] 2017-04-27 19:20
Possibly related
- Chromium reported bug: https://bugs.chromium.org/p/chromium/issues/detail?id=661596
- Electron bug: https://github.com/electron/electron/issues/4380#issuecomment-295602306

**Comment by szmer** [comment] 2017-05-25 10:25
Hello, I'm experiencing this on Fedora 24 x86_64, with Intel Haswell GPU (as the only card). More observations that might be relevant, might be not:
1. Links (invisible) still cause the cursor to become a "pointing hand" and are clickable, but the opened page is still blank.
2. I can make the page appear again when I detach the tab into a new window. But then the tab bar in this new window becomes a mess (see screenshot). In the second screenshot I try to access the "About Brave" page.
I will try to use '--ignore-gpu-blacklist' for a bit just to see if it solves the problem.
![brave1](https://cloud.githubusercontent.com/assets/4512761/26446540/c814a74e-4144-11e7-88aa-c2bcb17eb446.png)
![brave2](https://cloud.githubusercontent.com/assets/4512761/26446575/e95fbae2-4144-11e7-9e81-46df93f952d7.png)

**Comment by bsclifton** [comment] 2018-07-25 07:21
Since we have a [documented workaround](https://community.brave.com/t/window-is-solid-black-or-solid-white-looks-like-a-blank-page/10003) and also because we're moving to [Brave Core](https://github.com/brave/brave-browser) and won't be addressing this before then, I believe it makes sense to close this issue

**Closed by bsclifton** 2018-07-25 07:21 UTC
Labels: bug/driver
