### ISSUE TITLE
Automatically suspend inactive tabs

### ISSUE THREAD

**Issue by rafaelribeiro** [brave/browser-laptop#6251] opened 2016-12-16 12:11 UTC
**Did you search for similar issues before submitting this one?**
Yes

Would be good if brave could suspend inactive tabs to save memory.

With this feature, users like me, who can't let go some tabs, but want to visit them later and not consider them too important to save in bookmarks.

**Comment by Liunkae** [comment] 2016-12-16 18:25
Duplicate of #800.

**Comment by bradleyrichter** [comment] 2017-01-05 04:21
@rafaelribeiro Can you let me know when you think they should unload? We can have options as well.

- after 8 hours
- after 1 day
- after 5 days

**Comment by droplab** [comment] 2017-03-04 04:18
I'm a heavy user of the great suspender chrome extension which works really well. Would it be possible to have a config setting to put the number of minutes in with like a default of 30? Thanks for all the work on a great browser. Once you guy gets the react dev tools extension functional I will full make the jump over to brave from chrome.

**Comment by Liunkae** [comment] 2017-03-04 05:49
@droplab FYI, you can track the progress of React Dev Tools here: #5429.

**Comment by srirambv** [comment] 2017-05-10 08:45
+1 from communtiy https://community.brave.com/t/tab-suspension-priority-feature/2823

**Comment by fastf0rward** [comment] 2017-05-26 09:44
+1, Great Suspender is a must have!

**Comment by amandaporto** [comment] 2017-06-01 20:11
+1

**Comment by luzmcosta** [comment] 2017-07-19 23:03
+1 for having a time span option defaulting to 30 minutes.

**Comment by jgarciabu** [comment] 2017-08-10 13:49
+1 for great suspender or similar extension for Brave. If you can get this in place, I can wait for other features to be built in, but this one is critical given how resource hungry modern browsers are.

**Comment by eljuno** [comment] 2017-09-15 20:21
+1 from community https://community.brave.com/t/the-great-suspender-extension-functionality/7693?u=eljuno

**Comment by Midnex** [comment] 2017-09-21 20:58
+1 to this idea, since finding it for Chrome its a must have plug in. I been looking at hot to enable chrome extensions within Brave but a bit over my abilities at the moment, and time isn't permitting. But one way or another this would be amazing. for support of the great suspender.

**Comment by NumDeP** [comment] 2017-10-14 15:07
+1 I also commented about this issue further here #10717

**Comment by jdbener** [comment] 2017-10-17 01:44
+1 this is the one feature that is tethering me to chrome. It appears that I am most likely not alone.

**Comment by bradleyrichter** [comment] 2017-11-30 00:41
@NumDeP I'm the genius. ;   )

I'm of the belief that this can be set in a way that just works without having to think about manually putting tabs to sleep as Firefox Snooze is suggesting. I have not personally seen the use case where I wanted to schedule a tab to sleep for x days and reopen at this specified time. (seems like they are mixing "remind me" with tab suspension. ) 

I tried The Great Suspender and removed it after 2 days. It was far too invasive for me. 

Ideally we would be able to first suspend unused tabs, and then even close them into a tab-history place where you could find them again if needed. 

I'd love to hear more of your thinking about how suspend tabs should work. Both as a default setting and advanced settings.

**Comment by NumDeP** [comment] 2018-03-23 03:07
Personally, @bradleyrichter probably like most people I like the energy-efficient aspect to most implementations and features, so if your ideal of being able 
> to first suspend unused tabs, and then even close them into a tab-history place where you could find them again if needed.

reduces memory consumption as the original issue contributor stipulates, excellent.

**Comment by m1nkeh** [comment] 2018-04-12 08:57
in terms of memory usage, this is a must have... i have tons of tabs open in chrome and i *really* want to transition to brave for everything... my current workaround is to order more ram! 👍

**Comment by andybp85** [comment] 2018-05-01 09:44
👍

**Comment by andupotorac** [comment] 2018-07-03 01:00
I'm also using The Great Suspender to browse, which is very helpful on Chrome. Please add something like this to Brave!

**Comment by bsclifton** [comment] 2018-08-06 20:02
Closing as `wontfix` since [Brave Core](https://github.com/brave/brave-browser) supports extensions and folks can use `Great Suspender` or another extension

There already is some functionality in Chromium that will "discard" the tabs after a set amount of time. This is live in our current release.

**Closed by bsclifton** 2018-08-06 20:02 UTC
Labels: perf, suggestion

**Comment by m1nkeh** [comment] 2018-08-06 21:20
can you add some steps for the workaround please?

**Comment by bsclifton** [comment] 2018-08-06 21:25
@m1nkeh you can see existing releases of Brave Core here:
https://github.com/brave/brave-browser/releases

I don't believe we've opened the extension store up yet, so you may not be able to install Great Suspender

If you wanted to manually discard tabs in the existing Muon browser, you can launch from the CLI with the following environment variable set:
`BRAVE_ENABLE_DEBUG_MENU=true`

This will enable a debug menu where you can pick `Allow manual tab discarding`. After picking this, you'll notice an extra option when right-clicking tabs. You can then pick this to manually discard the tab

I don't know the criteria used by Chromium offhand for when a tab is discarded... but I believe it will happen automatically after a few minutes of not being active
