### ISSUE TITLE
Pinned tabs are not retaining their user-defined order after restart

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9087] opened 2017-05-27 04:10 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
If I pin two tabs, then swap their order, then restart Brave, they return to the order in which they were pinned.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X, reported by community. 

- Brave Version (revision SHA):
0.15.310

- Steps to reproduce:
    1. Pin two tabs
    2. Change their order
    3. Restart Brave
    
- Actual result:
The order returns to the way in which they were pinned.

- Expected result:
The user-defined order should persist.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by eljuno** [comment] 2017-06-03 20:09
+1 [from community](https://community.brave.com/t/pinned-tabbed-get-reorders-when-starting-brave/3452)

**Comment by bsclifton** [comment] 2017-06-05 16:01
Closing as a dupe of https://github.com/brave/browser-laptop/issues/8543

**Closed by bsclifton** 2017-06-05 16:01 UTC
Labels: bug, feature/pinned-tabs
