### ISSUE TITLE
[Mac] Partial garbage in session tab icon title tip

### ISSUE THREAD

**Issue by mozjag** [brave/browser-laptop#1393] opened 2016-04-17 14:18 UTC
![screen shot 2016-04-17 at 15 24 29](https://cloud.githubusercontent.com/assets/496769/14587691/9cf704dc-04b7-11e6-87b1-79b5f7ac6662.png) ![screen shot 2016-04-17 at 15 24 33](https://cloud.githubusercontent.com/assets/496769/14587692/9cf8706a-04b7-11e6-8343-ca95c15cf9a1.png)

1) Create new session tab
2) Mouse over session icon

Observed: extra (garbage) characters in the title tip
Expected: just the tip

OS: Mac OS X 10.9.5
Brave: 0.9.1
Electron: 0.37.3
libchromiumcontent: 49.0.2623.108
V8: 4.9.385.33
Node.js: 5.10.0
Update channel: dev

**Comment by bbondy** [comment] 2016-04-18 13:40
Is it all strings or just this one?  It appears fine for me.  Did you do a custom build by chance?

**Comment by mozjag** [comment] 2016-04-18 17:36
Nope, just a straight up download of Brave + a few automatic updates.

All other title tips seem to work fine (I tested UI buttons, bookmark items in the manager, the page's &lt;title/&gt; on the tab itself):
![screen shot 2016-04-18 at 18 38 01](https://cloud.githubusercontent.com/assets/496769/14613338/3913f66a-059c-11e6-9792-5f2391f8908d.png)
![screen shot 2016-04-18 at 18 38 47](https://cloud.githubusercontent.com/assets/496769/14613289/05655700-059c-11e6-885d-e09eada7c681.png)

I checked a few of the other template strings (basic auth, fullscreen, cmd+f -> "i of n") and no (visible) funny characters there. Could it have something to do with the nested template substitution?

**Comment by bbondy** [comment] 2016-04-19 14:37
When 0.9.2 is released, please re-test this.  We're changing from l20n to l10n which is compatible with Transifex.  So I think this might be auto fixed by nature of redoing the translation code.

**Comment by mozjag** [comment] 2016-04-22 20:59
Just tested Brave 0.9.2, still seeing this.

**Comment by bbondy** [comment] 2016-04-22 21:03
ok thanks for checking, strange since it's a whole new format for the localization files.

**Comment by bbondy** [comment] 2016-04-22 21:03
CC @aekeus in case he has ideas.

**Comment by aekeus** [comment] 2016-04-22 21:08
Can't reproduce on my side either. Will look around the interface for similar anomalies.

**Comment by mozjag** [comment] 2016-04-22 22:18
Maybe it's an older Mac OS X thing? Still back on 10.9.5 here.

BTW, I checked the Bookmarks Manager and for a bookmark from a partition/session I see the following: 
![screen shot 2016-04-22 at 23 20 37](https://cloud.githubusercontent.com/assets/496769/14755194/e47f3f40-08e0-11e6-9dec-f3983a5c7473.png)

Looking at bookmarks.js I was expecting a space before the parenthesized session, like:
"reddit: the front page of the internet (Session 3) - https://www.reddit.com/"

Related issue?

**Comment by bbondy** [comment] 2016-04-25 04:46
Fixed the spacing one mentioned https://github.com/brave/browser-laptop/issues/1393#issuecomment-213607451

**Comment by bbondy** [comment] 2016-04-25 04:50
It would help if you could send a screenshot of the Elements inspector for the browser chrome.
To get that use:
Command+Alt+J, then use the top left icon in the dev tools to select an element, and select the session tab.  Then it should show you the location's html.  (Sorry if you already know how to do these steps)

**Comment by mozjag** [comment] 2016-04-25 16:11
I knew about the inspector, didn't realize it could inspect the UI. Woo!

```
MacBook-Air:~ jag$ hexdump -C /tmp/tab-session-snippet.txt 
00000000  3c 64 69 76 20 63 6c 61  73 73 3d 22 74 61 62 41  |<div class="tabA|
00000010  72 65 61 22 3e 3c 64 69  76 20 63 6c 61 73 73 3d  |rea"><div class=|
00000020  22 74 61 62 20 61 63 74  69 76 65 22 20 64 61 74  |"tab active" dat|
00000030  61 2d 66 72 61 6d 65 2d  6b 65 79 3d 22 31 31 39  |a-frame-key="119|
00000040  22 20 64 72 61 67 67 61  62 6c 65 3d 22 74 72 75  |" draggable="tru|
00000050  65 22 20 74 69 74 6c 65  3d 22 42 72 61 76 65 20  |e" title="Brave |
00000060  53 6f 66 74 77 61 72 65  20 7c 20 42 75 69 6c 64  |Software | Build|
00000070  69 6e 67 20 61 20 42 65  74 74 65 72 20 57 65 62  |ing a Better Web|
00000080  22 20 73 74 79 6c 65 3d  22 63 6f 6c 6f 72 3a 20  |" style="color: |
00000090  62 6c 61 63 6b 3b 20 62  61 63 6b 67 72 6f 75 6e  |black; backgroun|
000000a0  64 3a 20 72 67 62 28 32  35 35 2c 20 32 35 35 2c  |d: rgb(255, 255,|
000000b0  20 32 35 35 29 3b 22 3e  3c 64 69 76 20 64 61 74  | 255);"><div dat|
000000c0  61 2d 6c 31 30 6e 2d 61  72 67 73 3d 22 7b 26 71  |a-l10n-args="{&q|
000000d0  75 6f 74 3b 70 61 72 74  69 74 69 6f 6e 4e 75 6d  |uot;partitionNum|
000000e0  62 65 72 26 71 75 6f 74  3b 3a 32 7d 22 20 64 61  |ber&quot;:2}" da|
000000f0  74 61 2d 6c 31 30 6e 2d  69 64 3d 22 73 65 73 73  |ta-l10n-id="sess|
00000100  69 6f 6e 49 6e 66 6f 54  61 62 22 20 63 6c 61 73  |ionInfoTab" clas|
00000110  73 3d 22 70 72 69 76 61  74 65 49 63 6f 6e 20 66  |s="privateIcon f|
00000120  61 20 66 61 2d 75 73 65  72 22 20 74 69 74 6c 65  |a fa-user" title|
-----
00000130  3d 22 e2 81 a8 54 68 69  73 20 74 61 62 20 75 73  |="...This tab us|
00000140  65 73 20 73 65 73 73 69  6f 6e 20 32 e2 81 a9 22  |es session 2..."|
-----
00000150  3e 3c 2f 64 69 76 3e 3c  64 69 76 20 63 6c 61 73  |></div><div clas|
00000160  73 3d 22 74 61 62 49 63  6f 6e 22 20 73 74 79 6c  |s="tabIcon" styl|
00000170  65 3d 22 6d 69 6e 2d 77  69 64 74 68 3a 20 31 36  |e="min-width: 16|
00000180  70 78 3b 20 77 69 64 74  68 3a 20 31 36 70 78 3b  |px; width: 16px;|
00000190  20 68 65 69 67 68 74 3a  20 31 36 70 78 3b 20 63  | height: 16px; c|
000001a0  6f 6c 6f 72 3a 20 62 6c  61 63 6b 3b 20 62 61 63  |olor: black; bac|
000001b0  6b 67 72 6f 75 6e 64 2d  69 6d 61 67 65 3a 20 75  |kground-image: u|
000001c0  72 6c 28 26 71 75 6f 74  3b 68 74 74 70 73 3a 2f  |rl(&quot;https:/|
000001d0  2f 62 72 61 76 65 2e 63  6f 6d 2f 66 61 76 69 63  |/brave.com/favic|
000001e0  6f 6e 2e 69 63 6f 26 71  75 6f 74 3b 29 3b 20 62  |on.ico&quot;); b|
000001f0  61 63 6b 67 72 6f 75 6e  64 2d 73 69 7a 65 3a 20  |ackground-size: |
00000200  31 36 70 78 3b 22 3e 3c  2f 64 69 76 3e 3c 64 69  |16px;"></div><di|
00000210  76 20 63 6c 61 73 73 3d  22 74 61 62 54 69 74 6c  |v class="tabTitl|
00000220  65 22 3e 42 72 61 76 65  20 53 6f 66 74 77 61 72  |e">Brave Softwar|
00000230  65 20 7c 20 42 75 69 6c  64 69 6e 67 20 61 20 42  |e | Building a B|
00000240  65 74 74 65 72 20 57 65  62 3c 2f 64 69 76 3e 3c  |etter Web</div><|
00000250  73 70 61 6e 20 64 61 74  61 2d 6c 31 30 6e 2d 69  |span data-l10n-i|
00000260  64 3d 22 63 6c 6f 73 65  54 61 62 42 75 74 74 6f  |d="closeTabButto|
00000270  6e 22 20 63 6c 61 73 73  3d 22 63 6c 6f 73 65 54  |n" class="closeT|
00000280  61 62 20 66 61 20 66 61  2d 74 69 6d 65 73 2d 63  |ab fa fa-times-c|
00000290  69 72 63 6c 65 22 20 74  69 74 6c 65 3d 22 43 6c  |ircle" title="Cl|
000002a0  6f 73 65 20 74 61 62 22  3e 3c 2f 73 70 61 6e 3e  |ose tab"></span>|
000002b0  3c 2f 64 69 76 3e 3c 2f  64 69 76 3e 0a           |</div></div>.|
```

Two characters there which I think might be the issue: ```e2 81 a8 'FIRST STRONG ISOLATE'``` and ```e2 81 a9 'POP DIRECTIONAL ISOLATE'```. If I remove those two through the inspector the problem goes away.

I'm not sure where those came from, I don't see them in the other ```title``` attributes above, nor in ```app.properties```.

```
MacBook-Air:~ jag$ hexdump -C ~/Applications/Brave.app/.../en-US/app.properties
...
00000f10  64 65 0a 73 65 73 73 69  6f 6e 49 6e 66 6f 43 6f  |de.sessionInfoCo|
00000f20  6d 6d 6f 6e 3d 54 68 69  73 20 74 61 62 20 75 73  |mmon=This tab us|
00000f30  65 73 20 73 65 73 73 69  6f 6e 20 7b 7b 70 61 72  |es session {{par|
00000f40  74 69 74 69 6f 6e 4e 75  6d 62 65 72 7d 7d 0a 73  |titionNumber}}.s|
00000f50  65 73 73 69 6f 6e 49 6e  66 6f 3d 7b 7b 73 65 73  |essionInfo={{ses|
00000f60  73 69 6f 6e 49 6e 66 6f  43 6f 6d 6d 6f 6e 7d 7d  |sionInfoCommon}}|
00000f70  0a 73 65 73 73 69 6f 6e  49 6e 66 6f 54 61 62 2e  |.sessionInfoTab.|
00000f80  74 69 74 6c 65 3d 7b 7b  73 65 73 73 69 6f 6e 49  |title={{sessionI|
00000f90  6e 66 6f 43 6f 6d 6d 6f  6e 7d 7d 0a 66 69 6e 64  |nfoCommon}}.find|
...
```

Screenshot as requested:

![screen shot 2016-04-25 at 17 28 03](https://cloud.githubusercontent.com/assets/496769/14789798/809c3778-0b0e-11e6-9cdb-0cd26562fdcb.png)

**Comment by Liunkae** [comment] 2016-09-26 06:37
Is this still happening with the latest version of Brave?

**Comment by mozjag** [comment] 2016-09-26 08:22
I'm not sure. I stopped using Brave shortly after I filed this issue and I've since upgraded my OS to El Capitan. Though I can't reproduce it with the latest version of Brave, it could also be El Capitan vs. Mavericks. I tried looking for a download for Brave 0.9.2 without much success.

**Comment by Liunkae** [comment] 2016-09-28 06:37
OK, then. Since there haven't been any recent reports, I'll go ahead and close this issue.

**Closed by Liunkae** 2016-09-28 06:37 UTC
Labels: OS/macOS
