### ISSUE TITLE
Crash on Homedepot.ca site

### ISSUE THREAD

**Issue by ElenaZhuk** [brave/browser-laptop#2146] opened 2016-06-09 16:11 UTC
**Did you search for similar issues before submitting this one?** 
Yes, you have issues with Crash, but for another sites.
Maybe, it is the same issue. It is easy to reproduce, so you can check it very quickly.

**Describe the issue you encountered:**
When I open homedepot.ca site and select any department - Brave crashes

**Expected behavior:** 
Open page with selected department

- Platform (Win7, 8, 10? OS X? Linux distro?):
Win 10
- Brave Version:
0.10.3
- Steps to reproduce:
    1. Run Brave browser
    2. Open site: homedepot.ca - the site is opened
    3. Select in menu 'Shop by department' -> Father's Day Event

Actual result: Brave closes.

Note: You can select any department.... 

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment] 2016-06-09 16:30
cc @bridiver reproducible on os x too

**Comment by bbondy** [comment] 2016-06-09 16:35
Appears to be because of the notification bar and then navigating. I think it's the same as #1726 so closing this one.

**Closed by bbondy** 2016-06-09 16:35 UTC
Labels: crash, verified

**Comment by bbondy** [comment] 2016-06-09 16:43
Pressing share location or deny the share location prompt at the start before navigating is a work around by the way.

**Comment by ElenaZhuk** [comment] 2016-06-09 16:50
Yes, it helps, thanks!
