### ISSUE TITLE
Error: HTTP response 503 for GET /v3/publisher/timestamp

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11881] opened 2017-11-09 16:27 UTC
### Description
Console throws Error: HTTP response 503 for GET /v3/publisher/timestamp 

### Steps to Reproduce

  1. Install 0.19.87 and enable payments
  2. Ensure wallet is created
  3. Close browser and launch from console
  4. Shows the error 

**Actual result:**
```
Error while retrieving publisher timestamp Error: HTTP response 503 for GET /v3/publisher/timestamp
```

**Expected result:**

**Reproduces how often:**
Consistently 

### Brave Version

**about:brave info:**

Brave | 0.19.87
-- | --
rev | b002c68
Muon | 4.5.15

**Reproducible on current live release:**
No

### Additional Information
cc: @evq

**Comment by bsclifton** [comment] 2017-11-14 16:08
Closing as a dupe of https://github.com/brave/browser-laptop/issues/11590

**Closed by bsclifton** 2017-11-14 16:08 UTC
Labels: 0.19.x, feature/ledger
