### ISSUE TITLE
Maximized MainWindow too large

### ISSUE THREAD

**Issue by benjaminsuch** [brave/browser-laptop#7997] opened 2017-03-31 04:26 UTC
Hello,

I got 2 Monitors and when I maximize Brave on one of them, the Window of Brave is 15px too large on either left or right side.

About Brave:
Brave	0.14.0
rev	c23efa3
Muon	2.57.7
libchromiumcontent	57.0.2987.110
V8	5.7.492.65
Node.js	7.4.0
Update Channel	dev
os.platform	win32
os.release	10.0.14393
os.arch	x64

Screenshot: https://picload.org/image/rcgdipia/brave.jpg

**Comment by bsclifton** [comment] 2017-04-11 07:25
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/5159

Thanks for the report (including the screenshot); this helped narrow it down 😄

**Closed by bsclifton** 2017-04-11 07:25 UTC
Labels: OS/Windows
