### ISSUE TITLE
Autocomplete does not work well

### ISSUE THREAD

**Issue by ezyang** [brave/browser-laptop#3049] opened 2016-08-09 00:19 UTC
**Did you search for similar issues before submitting this one?** I browsed the issues labeled autocomplete. #883 is sort of related but there are more issues than just described in that ticket.

**Describe the issue you encountered:** So, in general, I find brave's autocomplete to be far less useful than Firefox's/Chrome's. This is a bit hard to quantify, but let me describe some concrete problems which I have noticed:

1. Brave only ever seems to offer two autocomplete suggestions from history. This is too few. Chrome by default offers five; Firefox offers ten. This is far more useful!

2. Brave doesn't seem to update the autocomplete list based on frequency of access. For example, I access the URL https://github.com/ezyang/cabal less frequently than https://github.com/haskell/cabal but somehow I have poisoned my cache so that it only offers an autocomplete to ezyang (frustratingly, due to (1), I only ever get two autocompletes, both of which are ezyang! If Brave showed enough completes that I could find the one I wanted, this would be less of an issue.)

3. Brave keeps forgetting my history. I notice this because after a while, history autocompletes that used to be provided disappear (not sure if this is correlated with closing the browser). I can't tell if this is just because Brave doesn't really keep history, for some reason my "Show All History" button has always been greyed out. I didn't see any tickets describing this, so I assumed it was just something not implemented on Linux.

- Platform (Win7, 8, 10? macOS? Linux distro?): Ubuntu Linux Xenial, running Xmonad window manager

- Brave Version: 0.10.4

**Comment by bradleyrichter** [comment] 2016-08-09 18:42
@ezyang Thanks for submitting this request. We are filling in many of the missing history features for our 1.0 launch so this should improve.

We can certainly add at least 2 more entrees for autocomplete matches which will also help solve this issue.

cc @bbondy

**Comment by bsclifton** [comment] 2016-08-11 15:45
I too have this issue... I have a great example which I can share

I will sometimes go to https://google.com/analytics or similar.  When I type in google.com, it' auto-completes that entire URL instead of preferring the shorter google.com :frowning:

**Comment by Sh1d0w** [comment] 2016-09-06 07:41
Autocomplete currently feels very clunky and broken. It does not always seems to autocomplete correctly. For example I am typing `npmjs` and it autocmpletes it to `npmjs.com` ( I have never visited such webiste) . Instead I countinue to type `npmjs.org` and I visit this website. If I open a new tab and again start to type `npmjs` it again autocompletes to `npmjs.com` despite the fact I have never visited this site. It should autocomplete to `npmjs.org` because I have visited this site recently.

STR: http://webm.land/media/69AV.webm

Also Brave frequently forgets my history for some reason in a while.

cc @bbondy

**Comment by bradleyrichter** [comment] 2016-09-06 14:32
@alexwykoff The above reports are from Linux so let's confirm this behavior is tri-platform. I think it is.

**Comment by bradleyrichter** [comment] 2016-09-06 14:44
funny...apparently FX needs some work too:

(typing mens hair and getting mens shoes?)
![image](https://cloud.githubusercontent.com/assets/13509546/18278108/b84479be-7405-11e6-93b6-1a30448a9e8b.png)

**Comment by Sh1d0w** [comment] 2016-09-06 14:52
@bradleyrichter These are search suggestions from your default search engine. It is up to it what it will return as search results so this is no a browser issue.

The bug that I reported for Brave can be clearly seen in the screen cast I have provided. The suggested url is by Brave's autocomplete rather than from the search engine.

Try repeating the same steps as mine under Chrome or FF. Both will suggest the mosy recent or most visited website as highlighted text, but Brave doesn't.

**Comment by Sh1d0w** [comment] 2016-09-06 14:52
@bradleyrichter These are search suggestions from your default search engine. It is up to it what it will return as search results so this is no a browser issue.

The bug that I reported for Brave can be clearly seen in the screen cast I have provided. The suggested url is by Brave's autocomplete rather than from the search engine.

Try repeating the same steps as mine under Chrome or FF. Both will suggest the mosy recent or most visited website as highlighted text, but Brave doesn't.

**Comment by bradleyrichter** [comment] 2016-09-06 15:11
@Sh1d0w not sure why google is giving FX those strange results but chrome and brave are fine with the same steps. 

But anyway - your bug above is duly noted and certainly a different issue. We will work on it. Thanks...

**Comment by alexwykoff** [comment] 2016-09-27 04:00
Win 7 : 0 results
![autocomplete_win7](https://cloud.githubusercontent.com/assets/1434040/18859567/e5a1744e-843a-11e6-84df-74f999736be6.gif)

Ubuntu : 3 results
![autocomplete_ubuntu](https://cloud.githubusercontent.com/assets/1434040/18859684/1c8bb4a0-843c-11e6-8678-a6e229952978.gif)

OS X : 0 results
![autocomplete_osx](https://cloud.githubusercontent.com/assets/1434040/18859790/05b0bff4-843d-11e6-9c2a-83abbba882cd.gif)

**Comment by Sh1d0w** [comment] 2016-10-19 05:47
This does not seem to work for me. I've built it from master https://github.com/brave/browser-laptop/commit/497ecf8679e0bc14ae7d1e05e38f3b5a00733071 and installed it on my system. 

I've did the following:

1. Typed `tw` in the url bar
2. Those two entries appeared under History autocomplete in the following order: https://www.twilio.com/ and https://www.twitter.com
3. I choosed https://www.twitter.com and visited the website
4. In new tab I repeated the same but the order of the websites did not changed.
5. I repeated steps 1-3 several times resulting no change even after browser restart

Should I delete all brave related session files in order that to work? It should altomatically work after updating Brave to newest version without requiring any further steps.

Please close if I did something wrong and this report is not valid.

**Comment by aekeus** [comment] 2016-10-19 12:58
The ordering of the websites is controlled by a count attribute that is stored with each history item. The history items will be ordered by the count (highest first) with some decay based on the last time the website is accessed.

I just tested with a new session file, accessing twilio.com and then twitter.com. Each history item has a count of one.

<img width="554" alt="screen shot 2016-10-19 at 8 55 09 am" src="https://cloud.githubusercontent.com/assets/210240/19519443/1385fa8c-95da-11e6-8d5f-1468942514d5.png">

Twitter is the first entry in the list as it was accessed most recently.

Thanks for the test. Please let us know if you are seeing something different than what I described.

**Comment by Sh1d0w** [comment] 2016-10-19 16:34
@aekeus I understand this and it is working just perfectly if I remove session-store-1.

The problem is the following:

When we update Brave, the session store file is not removed. It stays as it is, and when you are accessing websites `count` entry is not created under the visited entry, as it is already in the session file.

To sum it up - everything from your PR is working if I delete session-store-1 file, but you can't expect the users to delete it after the upgrade as they will loose all of their settings and history. The issue is that if you already have session-store-1 file, your PR is not working since the count entry is not appended to the already existing history entries, only to new ones.

Sorry for reopening this again.

**Comment by aekeus** [comment] 2016-10-19 17:13
Hi, Thanks for checking this for us again. I will try and reproduce and fix.

**Comment by aekeus** [comment] 2016-10-19 17:41
Ok, I can reproduce the issue you are seeing although the root cause is different.

The count attribute is added to existing entries in an existing session file. I confirmed this multiple times by removing the count attribute, opening the browser, navigating to a site, closing the browser and inspecting the session file.

In the specific instance you noticed above the history item have the following locations:

- twitter.com
- www.twilio.com

When you enter the characters `twi` the locations match on the first portion of twitter.com but later in www.twilio.com. twitter.com will always show up first regardless of the number of times you navigate to www.twilio.com.

I am going to close this issue and open another that specifically fixes the prefix issue described above.

Thanks again for looking into this for us.

**Closed by aekeus** 2016-10-19 17:41 UTC
Labels: enhancement, feature/autocomplete, parity
