### ISSUE TITLE
Chevron button is missing in Bookmarks Toolbar when "Favicon only" chosen

### ISSUE THREAD

**Issue by kolya182** [brave/browser-laptop#11478] opened 2017-10-12 03:13 UTC
### Description
Chevron button missing of the screen when chose to show "Favicons only":
<img width="340" alt="screenshot 2017-10-11 20 09 08" src="https://user-images.githubusercontent.com/3277207/31477299-0f7ba018-aec0-11e7-9dce-16cf3433f5d8.png">

### Steps to Reproduce
![brave tabs bag](https://user-images.githubusercontent.com/3277207/31477023-7532c50a-aebe-11e7-9a04-6942232fc563.gif)

**Expected result:**
Bookmarks that do not feet in Bookmark Toolbar would show up when click on chevron button
like in Chrome:
<img width="504" alt="screenshot 2017-10-11 20 10 56" src="https://user-images.githubusercontent.com/3277207/31477371-8444787a-aec0-11e7-8a42-67113e1b0da0.png">

### Brave Version

Name | Version
-- | --
Brave | 0.18.36
rev | 7ab85e9
Muon | 4.3.22
libchromiumcontent | 61.0.3163.79
V8 | 6.1.534.32
Node.js | 7.9.0
Update Channel | dev
OS Platform | macOS
OS Release | 17.0.0
OS Architecture | x64

**Comment by srirambv** [comment] 2017-10-12 09:28
Could you add the steps to reproduce it. The gif image doesnt quite give out enough info

**Comment by srirambv** [comment] 2017-10-12 09:31
This addressed in 0.20.x release. Closing as dupe of https://github.com/brave/browser-laptop/issues/6869

**Closed by srirambv** 2017-10-12 09:31 UTC
Labels: feature/bookmarks, needs-info
