### ISSUE TITLE
Links followed from Feedly show RSS feed URL

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#591] opened 2016-02-03 10:11 UTC
Opened a link from Feedly and its URL was:

http://rss.nytimes.com/c/34625/f/640387/s/4d511e70/sc/28/l/0L0Snytimes0N0C20A160C0A20C0A30Cbusiness0Cuber0Edrivers0Eand0Eothers0Ein0Ethe0Egig0Eeconomy0Etake0Ea0Estand0Bhtml0Dpartner0Frss0Gemc0Frss/story01.htm

It should have been this (which is what you get if you copy above and paste into new tab address bar):

http://www.nytimes.com/2016/02/03/business/uber-drivers-and-others-in-the-gig-economy-take-a-stand.html?partner=rss&emc=rss

I also have seen this with Reuters URLs.

**Comment by trongthanh** [comment] 2016-02-03 16:13
I think it's same for Cmd+Click a link on Google search result page to open new tab. The newly opened tab shows the redirecting URL of google.com, not the target URL.

**Comment by stshank** [comment] 2016-02-03 20:55
In other browsers, when I right-click on a Feedly RSS entry title and open the link in a new tab, I get the non-RSS URL in the address bar.

**Comment by luixxiul** [comment] 2016-05-15 00:49
I cannot reproduce this. Should be fixed now, closing.

**Closed by luixxiul** 2016-05-15 00:49 UTC
