### ISSUE TITLE
after 0.20.x update Brave is slow/sluggish

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13087] opened 2018-02-09 18:48 UTC
### Description
Reports of Brave being slow/sluggish/lagging after update to 0.20.x. Some users are experiencing slowness immediately after opening (@Jacalz on Windows 10) others are seeing the slowness after having Brave open for several days (@davidtemkin and @kjozwiak on MacOS). Sometimes a restart fixes the problem.

### Steps to Reproduce

STR seem to vary: some users experience this immediately and others have had Brave open and operating normally for a few days.

**Actual result:**
Slowness and lagging

**Expected result:**
No changes to browsing experience

**Reproduces how often:**
Unknown

### Brave Version

**about:brave info:**
0.20.30

**Reproducible on current live release:**
Yes

### Additional Information
Could be related to https://github.com/brave/browser-laptop/issues/13079

**Comment by Jacalz** [comment] 2018-02-09 18:52
Has happened to me 2 times after just opening the browser and one time from using it for like 30 minutes 👎

**Comment by Jacalz** [comment] 2018-02-09 18:54
Restart allays fixed the problem for me

**Comment by Liunkae** [comment] 2018-02-09 19:19
Maybe related: #13016

**Comment by hugobuddel** [comment] 2018-02-09 20:08
Maybe related, maybe not: Brave grinds to a halt (like taking seconds to register clicking on a tab) when it goes into a crash loop as described in #12995 and a restart fixes it. Perhaps other slowdowns are caused by similar crash loops?

**Comment by Jacalz** [comment] 2018-02-09 20:09
+1 from community https://community.brave.com/t/brave-gets-so-laggy/15716

**Comment by LaurenWags** [comment] 2018-02-09 21:30
+1 from twitter: https://twitter.com/AngelClarkSays/status/959578540214833152

**Comment by LaurenWags** [comment] 2018-02-12 22:13
+1s from community: https://community.brave.com/t/brave-gets-so-laggy/15716

**Comment by LaurenWags** [comment] 2018-02-12 22:57
+1 from community: https://community.brave.com/t/brave-randomly-slows-down-to-the-point-its-unusable/15918

**Comment by karolszafranski** [comment] 2018-02-13 12:43
Same issue:
```
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119
```
Is there a way how can we help to nail down the issue? Like enabling additional logging?

**Comment by benjibee** [comment] 2018-02-13 14:56
This has been driving me crazy recently. Eventually YouTube playback is as slow as a first-gen MacBook Air and just today it's become all-together unresponsive at some point, new tabs open in the tab bar but never produce a window, clicking on inputs takes ages, etc. etc. Relaunching Brave does indeed fix the issues temporarily.

````
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Comment by djmaze** [comment] 2018-02-13 15:11
When this problem occurs for me (on Linux), I can almost everytime see in the task manager that there is one of Brave's subprocesses (`brave --type renderer ..`) which takes up alnost 100% CPU. If I kill this process, Brave continues to run while, for the time being, the slowness goes away. 

I hope Brave does not do cryptomining in the background..

```
Brave | 0.20.29
V8 | 6.4.388.40
rev | 4fc3c8f
Muon | 4.7.9
OS Release | 4.15.2-2-ARCH
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119
```

**Comment by lukemulks** [comment] 2018-02-13 17:07
I'm running into the issue as well. 
``` 
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119
```
![brave-memory-win10-02122018](https://user-images.githubusercontent.com/8979240/36163040-01bbcd4c-109d-11e8-8b64-04584d934fd4.PNG)

As opposed to relaunching Brave - if I close the lid on my laptop and re-open to wake the computer back up, it resolves the issue for 1-2 days before it is noticeable again.

**Comment by calebv** [comment] 2018-02-13 20:03
Wanted to sound off hear as well. Experiencing very similar issues. Details:

Brave: 0.20.30
V8: 6.4.388.40 
rev: [8b78402e7b3b91d44d8146cbe4dc8013592c33fd](https://github.com/brave/browser-laptop/commit/8b78402e7b3b91d44d8146cbe4dc8013592c33fd)
Muon: 4.7.9 
OS Release: 17.4.0
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119
Machine: MacBook Pro (15-inch, 2016)
Processor: 2.9 GHz Intel Core i7
Memory: 16 GB 2133 MHz LPDDR3
OS: macOS High Sierra Version 10.13.3 (17D47)

Some days it takes only minutes for Brave to start slowing down, others it could take a couple hours, but it always seems to slow down at some point. Behavior results in an extreme lag in switching or opening new tabs (sometimes as long as 10 seconds, others shorter but still very noticeable). Additionally, I start to see even a delay in text recognition, where I will start typing and the browser isn't picking it up until after I've gotten halfway through a sentence. I haven't noticed any spike in CPU usage through Activity Monitor, but it does seem as though Brave begins to slow down all processes on my machine when it's begun to slow down.

**Comment by bsclifton** [comment] 2018-02-14 17:21
+1 from @LethalManBoob via https://github.com/brave/browser-laptop/issues/13016
> There's not much more to it. I run brave for about 20 minutes and then
suddenly it runs at 3fps. A reboot being required. Cpu does spike and stay
at 30% on my 6700k though. I reinstalled and haven't had the issue since.
But it could happen at any moment so i dunno. I tried turning on and off
the experimental security option but no change.
>
> My Brave Stats
>
> Brave: 0.20.30
> V8: 6.4.388.40
> rev: 8b78402
> Muon: 4.7.9
> OS Release: 10.0.16299
> Update Channel: Release
> OS Architecture: x64
> OS Platform: Microsoft Windows
> Node.js: 7.9.0
> Brave Sync: v1.4.2
> libchromiumcontent: 64.0.3282.119
>
> My system stats straight from my dxdiag text save file
> https://pastebin.com/raw/XnAhvgZf
>
> Also when i said reboot I meant relaunch the browser.

**Comment by bsclifton** [comment] 2018-02-14 23:49
I believe the majority of the impact for this issue was caused by recent changes to tab discarding.
https://github.com/brave/browser-laptop/pull/12917
https://github.com/brave/browser-laptop/pull/12977

@petemill is looking into this along with @bridiver.  I've done some profiling of the app and haven't found any red flags in the code (yet)

**Comment by kevinp2** [comment] 2018-02-15 04:46
I'm seeing the same issue on Windows 7.  I think it may be related to a memory leak.  This did not happen in earlier releases.

Brave | 0.20.30
-- | --
V8 | 6.4.388.40
rev | 8b78402
Muon | 4.7.9
OS Release | 6.1.7601
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

After having Brave open for some hours, it becomes unbearably slow.  I noticed that the Brave.exe processes were consuming well over 1.5 GB of RAM.  After closing all but one tab, and then changing that one tab to be about:blank, there were still three Brave.exe processes consuming 1.5GB of RAM!  See the attached screeenshot.

![bravememoryleak](https://user-images.githubusercontent.com/609677/36240920-d5623e24-11d8-11e8-9a7e-021f19216aae.png)

**Comment by NejcZdovc** [comment] 2018-02-20 18:22
1) start browser (make sure you have a folder with at least 20 bookmarks)
2) open YouTube player
3) right click on a folder and select `Open all in tabs`
4) then immediately after they are opened start closing them with mouse middle button or cmd+w
5) youtube starts lagging and then if you just click on a youtube page (on white section) video lags

**Comment by bsclifton** [comment] 2018-02-23 23:42
I believe the majority of this was solved with https://github.com/brave/browser-laptop/pull/13234

We'll definitely see some UI gain when https://github.com/brave/browser-laptop/issues/11515 is addressed

**Closed by bsclifton** 2018-02-23 23:42 UTC
Labels: 0.20.x, bug, needs-investigation, perf, priority/P1, usability
