### ISSUE TITLE
uNABLE TO POST PICTURES ON COMMENTS IN fACEBOOK - HELP??

### ISSUE THREAD

**Issue by raysmith45** [brave/browser-laptop#5626] opened 2016-11-15 05:36 UTC
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment] 2016-12-02 16:25
I'm going to close this issue for now because of lack of details, but I'd encourage you to re-open if you can provide more information

One work-around you can try is to click the lion head (in the top right) and then disable shields to see if the site works.  If that does work, you can re-enable shields and then try turning off features like fingerprint protection one at a time until it works for you.  The changes you make are only saved for that domain (facebook.com), so other browsing won't be affected.

**Closed by bsclifton** 2016-12-02 16:25 UTC

**Comment by ThatBrickster** [comment] 2017-02-17 16:27
I'd like to reopen this issue but I'd also like to propose a rephrased title.

Title:
Unable to post image comments on Facebook

Summary:
I'm unable to upload images as comments or direct messages on Facebook. Disabling shields has no effect.
This is being observed on Brave 0.13.4 running on Windows 7 SP1 (both x64).

Steps to reproduce:
1. Log in to Facebook
2. Select someone from the chat sidebar to bring up a direct message box
3. Attempt to upload an image (or multiple images)

Expected result:
After selecting file(s) from the file explorer, the image(s) upload and post.

Actual result:
After selecting file(s) from the file explorer, nothing happens.

Related issues:
None by number but copying an image and pasting it into a direct message box only pastes a link rather than the image itself. Works in Firefox and Chrome.

This also appears in the web console.

![brave_2017-02-17_16-25-00](https://cloud.githubusercontent.com/assets/4836781/23073529/cce6ab9a-f52d-11e6-8b60-af6fc0d90e10.png)
