### ISSUE TITLE
Crashing after most recent update

### ISSUE THREAD

**Issue by 0therBarry** [brave/browser-laptop#14975] opened 2018-08-09 11:31 UTC
Per a twitter interaction with Sampson, I asked if the crashes were still happening for others. He requested I open a github issue. 
### Steps to Reproduce

  1. Open Browser
  2. Open multiple tabs
  3. Wait for crash

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

0.23.77

**Reproducible on current live release:**

Yes

### Additional Information

Here are my Crash Ids (dont know if it helps) These all occurred on 08/09
 Crash Report ID f19601cbcc86c893 (Local Crash ID: a9b78076-f86d-48ed-bb0f-7e336ef6dd40)
Uploaded Crash Report ID f636c0121b041b5f (Local Crash ID: b6ea3410-a595-4aeb-9266-426565881cb1)
Uploaded Crash Report ID c27f79b598c50d55 (Local Crash ID: 330abcf2-7901-4dcb-90f4-29691f0217a7)

**Comment by bsclifton** [comment] 2018-08-09 17:36
Thanks for the report, @0therBarry 😄 👍 I took a look at the stacktrace and confirmed this is a duplicate of https://github.com/brave/browser-laptop/issues/14955

We have a fix and are working on getting it out the door. Stay tuned 😄

**Closed by bsclifton** 2018-08-09 17:36 UTC
