### ISSUE TITLE
Can't log into Soundcloud using Google 

### ISSUE THREAD

**Issue by daloonik** [brave/browser-laptop#13545] opened 2018-03-21 13:58 UTC
### Description

There is an option to use your Google account to log into Soundcloud but this option doesn't work on Brave browser.

### Steps to Reproduce

1. Click on the button to log into Soundcloud
2. Use Google to log in
3. Second window pops up for you to log into Google
4. Enter your login credentials and log into Google normally

**Actual result:**
Window goes blank after authentication is completed. The blank window doesn't closed and the callback fails. Logging into Soundcloud also fails.

**Expected result:**
Window closes, callback works and the user is logged into Soundcloud

**Reproduces how often:**
Every time I try to log in

### Brave Version

**about:brave info:**
Brave | 0.19.95
rev | cc0ebad
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Linux
OS Release | 4.13.0-37-generic
OS Architecture | x64

**Reproducible on current live release:**

**Comment by diracdeltas** [comment] 2018-03-21 20:42
Can you confirm that Strict Site Isolation is disabled in about:preferences#security ?

**Comment by daloonik** [comment] 2018-03-23 17:05
Yes, I can confirm that this option (Strict Site Isolation) is unchecked. Error still persists in 0.21.24.

**Comment by bsclifton** [comment] 2018-09-18 21:57
Closing as duplicate of https://github.com/brave/browser-laptop/issues/15196

**Closed by bsclifton** 2018-09-18 21:57 UTC
Labels: needs-info, webcompat
