### ISSUE TITLE
Brave does not open new tab

### ISSUE THREAD

**Issue by saitam1** [brave/browser-laptop#12362] opened 2017-12-21 17:49 UTC
### Description
Does not open new tab when clicking: right mouse --> Open Link in new Tab
Or: strg + click on link

**Actual result:**
Nothing happens. Terminal tells me: "No tab found"

**Expected result:**
Opening new tab 

**Reproduces how often:**
Most of the time

### Brave Version

Brave | 0.19.122
-- | --
rev | 009e792
Muon | 4.5.31
libchromiumcontent | 63.0.3239.108
V8 | 6.3.292.48
Node.js | 7.9.0
Update Channel | Release
OS Platform | Linux
OS Release | 4.10.0-42-generic
OS Architecture | x64

**Reproducible on current live release:**
No

### Additional Information
I am using elementary OS (0.4.1 „Loki“)

**Comment by chadmichaels** [comment] 2017-12-23 23:19
I am experiencing the same behavior on OSX 10.13.1 with Brave version 0.19.122

**Comment by igormiletic** [comment] 2017-12-28 10:48
Same here:

Brave	0.19.122
rev	009e792
Muon	4.5.31
libchromiumcontent	63.0.3239.108
V8	6.3.292.48
Node.js	7.9.0
Update Channel	Release
OS Platform	macOS
OS Release	17.3.0
OS Architecture	x64

Just was ready to completely switch from Chrome, but... :)

**Comment by shones34** [comment] 2018-01-05 22:48
Same Issue for me but I am noticing it when clicking on links in Atlassian's JIRA. 
It seems to be working fine for link results in a google search.

Brave	0.19.123
rev	f45cb3a
Muon	4.5.31
libchromiumcontent	63.0.3239.108
V8	6.3.292.48
Node.js	7.9.0
Update Channel	Release
OS Platform	Microsoft Windows
OS Release	10.0.16299
OS Architecture	x64

**Comment by kasu207** [comment] 2018-01-08 19:03
Same issue:
`

Brave | 0.19.123
-- | --
rev | f45cb3a
Muon | 4.5.31
libchromiumcontent | 63.0.3239.108
V8 | 6.3.292.48
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

`

**Comment by rsletta** [comment] 2018-01-11 11:54
I'm experiencing the same issue from time to time. Seems that a restart of Brave fixes it temporarily, until the next time it happens. 

Version Informations:
Brave: 0.19.131 
rev: da2f34787e51eb44190a7a77249e100fb2368306 
Muon: 4.5.36 
libchromiumcontent: 63.0.3239.132 
V8: 6.3.292.49 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.3.0 
OS Architecture: x64

**Comment by pongraczi** [comment] 2018-01-12 08:56
Same here. Sometimes middle click or right click+open url in new tab does not work. Restarting brave solves this. I did not find any reproducible steps, it just happens.
 
Brave: 0.19.131 
rev: da2f34787e51eb44190a7a77249e100fb2368306 
Muon: 4.5.36 
libchromiumcontent: 63.0.3239.132 
V8: 6.3.292.49 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.13.0-26-generic 
OS Architecture: x64

**Comment by pongraczi** [comment] 2018-01-12 12:41
Ok, first I thought, I found something, but as I replayed the scenario, it did not provide the same result.

The theory was: When I middle-click on a long URL, it does not work, while a shorted URL works as expected.

Example:

- Here is a search result from google ([open it now in new window](https://www.google.hu/search?dcr=0&ei=XaRYWt34I8HEsgHV85qgAQ&q=Non-blocking+PostgreSQL+client+for+laravel+notify&oq=Non-blocking+PostgreSQL+client+for+laravel+notify&gs_l=psy-ab.3..33i160k1.110704.111695.0.111921.7.7.0.0.0.0.172.830.0j6.6.0....0...1c.1.64.psy-ab..1.5.712...33i21k1.0.dvkSL-dS1Go))
- [Clicking on this link](https://www.postgresql.org/docs/9.5/static/sql-notify.html) with middle click should work from the result page above
- [But clicking on this link with middle-mouse](https://www.google.hu/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwjPmIfGsdLYAhUCDSwKHXOHBEIQFggmMAA&url=http%3A%2F%2Fwww.npgsql.org%2Fdoc%2Fwait.html&usg=AOvVaw2q73ZWUEF1s2A9jYP4-DAk) should not work

Results:

- Originally when I searched and I tried to open the URLs as I wrote, it did not work.
- As I reopen the search URL via the link I provided above, when I clicked on URLs, it was working.

Sucks. I did not find proven step-by-step procedure to reproduce the issue.

**Comment by bart747** [comment] 2018-01-15 21:33
Same experience here. 
In @pongraczi 's example you can also notice that the URL of the site you'll go to is not the URL you're clicking on. It might mean that it's some security thing problem/feature. If that's true, a warning message with a "go" and "don't go" buttons would be useful.

**Comment by abourdon** [comment] 2018-01-24 15:01
Same experience here.

Note this is only located to a given tab and not to all currently opened tabs. So restarting Brave is not necessary, just closing the bugged tab is enough.

A minimal "workaround" could be:
- Copy the link
- Manually open a new tab
- Paste the copied link

In addition, this bug seems to be related to any kind of tab opening. Indeed, "open link in new private tab" and "open link in new session tab" actions are also broken. However, it is still possible to "open link in new window".

My configuration:

Brave: 0.19.139 
rev: 99aa17da28e040543b4ba217d2c4dd6633bf1446 
Muon: 4.7.2 
libchromiumcontent: 64.0.3282.85 
V8: 6.4.388.20 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.3.0 
OS Architecture: x64

Regards,
Aurélien

**Comment by paul-go** [comment] 2018-02-28 19:23
Same behavior as the others. Has been an issue since I started using Brave. The only extension I have installed is 1Password. Can someone from Brave please look into this?

Mac OS 10.13.3

Name | Version
-- | --
Brave | 0.20.46
V8 | 6.4.388.41
rev | 5eb035c
Muon | 4.8.2
OS Release | 17.4.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Comment by vallka** [comment] 2018-03-05 10:34
Same behaviour. Windows 10

Brave | 0.21.18
-- | --
V8 | 6.4.388.41
rev | 580be78
Muon | 4.8.2
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Comment by rabus** [comment] 2018-03-05 11:36
Hello

Same as above, only works while using Google search.

 
Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Comment by Neecko** [comment] 2018-05-06 06:42
Just got this issue today. Not a problem on my desktop, but on my laptop.

**Comment by bsclifton** [comment] 2018-09-21 05:16
I've tried to reproduce this issue, but have been unable to (must be missing something on my end). For folks that are experiencing this, I'd suggest trying our developer channel release:
https://brave.com/download-dev

**Closed by bsclifton** 2018-09-21 05:16 UTC
Labels: 0.19.x, bug
