### ISSUE TITLE
adblock regional and custom filters don't seem to work

### ISSUE THREAD

**Issue by sdsucks** [brave/browser-laptop#6243] opened 2016-12-15 23:41 UTC
**Did you search for similar issues before submitting this one?**
ya
**Describe the issue you encountered:**

**Expected behavior:**
ads should be gone
- Platform (Win7, 8, 10? macOS? Linux distro?):
win10
- Brave Version:
app-0.12.15
- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:
http://s27.postimg.org/qmze59uxv/brave_ilbe_com.jpg
- Any related issues:

**Comment by bbondy** [comment] 2016-12-20 21:21
Which list are you using? 
What is the site that displays that jpg?

**Comment by sdsucks** [comment] 2016-12-21 03:44
using these regional filter lists:
KOR: Korean Adblock List
KOR: Fanboy's Korean
I see no ads at all using these filter lists in ublock-origin on Chrome

site's address is:
www.ilbe.com

**Comment by bbondy** [comment] 2016-12-21 15:36
Requires investigation but my best guess is because of cosmetic filters which we aren't using yet.

**Comment by srirambv** [comment] 2017-03-20 09:43
Possibly similar issue with custom adblock filters
https://community.brave.com/t/ad-blocking-filters-possibly-not-working/1750/3

**Comment by onmyouji** [comment] 2017-09-21 13:42
I have the same problem, custom filter doesn't work on this website. The filter works fine when using Chrome + uBlock Origin

Platform: Windows 7 x64
Brave version: 0.18.36

Website: 
http://suikoden.wikia.com/wiki/Crowley

Filter: 
suikoden.wikia.com##.mq-wrapper

Screenshot:
I want to filter the scrolling text with red background.


![2f9bdcdc813b523397b09632876a20c9ff3acea6](https://user-images.githubusercontent.com/8424198/30698773-1fbb58dc-9f0d-11e7-8c47-27ef62fe1690.png)

**Comment by benjibee** [comment] 2018-01-30 15:03
I've spent a while trying to get my custom filters working. I have some pretty basic ones I've used for years before I switched to Brave. I think the Custom filters area of the `about:adblock` page should be disabled until it's working properly to avoid frustration and confusion.

**Comment by bsclifton** [comment] 2018-10-01 03:06
Duplicate of https://github.com/brave/browser-laptop/issues/12308

**Closed by bsclifton** 2018-10-01 03:06 UTC
Labels: bug, feature/adblock
