### ISSUE TITLE
Significant lag between browser history and ledger listing

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3451] opened 2016-08-26 14:08 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When visiting sites, they show up in the browser history, but do not appear in the ledger, or appear after a significant delay (10 minutes and counting).

**Expected behavior:**
The visited sites should appear within a reasonable window.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.11.6 pre-beta4

- Steps to reproduce:
    1. Have Brave payments turned on.
    2. Visit a lot of sites in quick succession (I use news.ycombinator.com) .
    3. Check the browser history.
    4. Wait for a couple minutes, check the ledger.

- Screenshot if needed:
![ledger_lag](https://cloud.githubusercontent.com/assets/1434040/18008111/73edb09c-6b6c-11e6-9ab6-8931e5404b33.gif)

- Any related issues:

**Comment by mrose17** [comment] 2016-08-27 00:43
@alexwykoff - before i dig into this, let me verify a few things:

- you have to be on a page for at least 8 seconds before it gets considered a "visit"

- you have to leave the page (sometime) after those 8 seconds before it gets considered a "visit"

can you verify that this is what you're seeing? thanks!

**Comment by alexwykoff** [comment] 2016-08-27 17:26
I'll post back after the investigation. Thanks!

**Comment by alexwykoff** [comment] 2016-08-28 18:05
It would appear that ledger listings are not occuring until navigation events.

![payment_time](https://cloud.githubusercontent.com/assets/1434040/18035686/0cdbef8a-6d20-11e6-8e4a-cd7621b44fe2.gif)

**Comment by mrose17** [comment] 2016-08-29 19:55
@BrendanEich & @bbondy - @alexwykoff and i had a hangout in which we found out that it works for MTR but not for alex. this is true regardless of whether i'm using a build or an `npm start`.  all i can suggest at this point is that we get more people trying this out and seeing if they see the same problem. both @alexwykoff and i tested on a mac. worked for me, not for him. very odd...

**Comment by bbondy** [comment] 2016-08-30 01:01
@mrose17 can you provide him with a logged build? Or ask him to open a console and check for something? /cc @diracdeltas

**Comment by BrendanEich** [comment] 2016-08-30 01:04
Need other folks than @alexwykoff to reproduce too (or not). More than two people testing is needed to move forward here, unless code inspection finds a bug. Thanks.

**Comment by mrose17** [comment] 2016-08-30 05:05
as part of the PR above, when `process.env.LEDGER_PUBLISHER_DEBUG === true`, you will be able to see how page views are encountered. the guru on this is @bridiver who implemented the event store, specifically https://github.com/brave/browser-laptop/blob/master/js/stores/eventStore.js#L49

**Comment by bridiver** [comment] 2016-08-30 14:41
the updates come in to the event store in real-time, but I have no idea how that data is used to update the interface

**Comment by mrose17** [comment] 2016-08-30 14:44
@bridiver - cf., https://github.com/brave/browser-laptop/blob/master/app/ledger.js#L231

**Comment by bridiver** [comment] 2016-08-30 15:38
it looks like `visit` calls `updatePublisherInfo` which should update the appState if `synopsis` is not null/undefined, so I would start by making sure that the appState is updated for each new visit and then track the state through the components

**Comment by bradleyrichter** [comment] 2016-08-30 16:26
I don't see this problem myself. @alexwykoff  - can you close this yet?

**Comment by diracdeltas** [comment] 2016-08-30 17:46
not seeing this problem on os x either

**Comment by alexwykoff** [comment] 2016-08-30 18:54
I am somehow capable of repro on os x and linux. However, since I am the odd duck, I will move this out to 1.0 and assign it back to me for investigation.

**Comment by bridiver** [comment] 2016-08-31 19:12
initially I thought I could repro, but I wasn't staying on the site for at least 8 seconds. When I stayed long enough to register a visit, the ledger state updated immediately

**Comment by mrose17** [comment] 2016-09-07 17:51
@alexwykoff - can you retry this to see if it's in the current build? thanks!

**Comment by mrose17** [comment] 2016-09-21 04:36
unable to reproduce after repeated attempts.

**Closed by mrose17** 2016-09-21 04:36 UTC
Labels: ledger integration
