### ISSUE TITLE
Browser becomes inactive with get property error 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14261] opened 2018-05-28 17:03 UTC
### Description
Browser becomes unresponsive with get property error

### Steps to Reproduce
  1. Visit goatdee.net 
  2. Click on any link that is listed on the page, opens up in the same tab 
  3. Wait till the ad countdown finishes 
  4. Click on the close advertisment button a new tab opens. You may be able to close it
  5. Click on Install Flash link, another tab opens in background and browser becomes unresponsive
  6. Context menu doesn't work, cant open a new tab, cant close any tabs, only way is to restart the browser 

**Actual result:**
Browser becomes inactive. Unable to open new tab or switch tab. Browser console shows this error 
![image](https://user-images.githubusercontent.com/17010094/40623845-1176eff6-6277-11e8-992b-643e633650da.png)

**Expected result:**
Browser should be active

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.721
-- | --
V8 | 6.6.346.32
rev | bfe7cdd
Muon | 6.0.12
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.170

**Reproducible on current live release:**
Yes

### Additional Information
cc: @btlechowski @kjozwiak @LaurenWags to keep an eye on this on mac/Linux
Edit: found steps and updated the issue 
cc: @bsclifton

**Comment by btlechowski** [comment] 2018-05-28 17:49
Reproduced on Ubuntu 17.10 v0.22.721

The browser becomes unresponsive after step 4.

**Comment by bsclifton** [comment] 2018-05-29 04:16
@kjozwiak SGTM 👍

**Comment by bsclifton** [comment] 2018-05-31 06:47
This is a pretty crazy issue- great find/STR, @srirambv!

Here's what I'm seeing after doing some investigating:
- ad countdown happens
- click the X to hide the ad banner; new tab opens
- sometimes I need to go back to the original tab and click where the countdown was
- problem happens: over 90 tabs are created! this includes web contents, etc. I suspect these are popups
- during the web contents add, the code exits out:
    https://github.com/brave/browser-laptop/blob/9b102d8312cba7dca2d5f947936ce22dd37d2e0c/app/browser/tabs.js#L464-L467
- web contents still exists but there is no frame associated with this
- frameStateUtil.findNonPinnedDisplayIndexForTabId gets fired somehow for this web contents / tab (which doesn't have a frame) and causes the reported console error pictured. Specifically, the object is undefined (and not an Immutable object containing frame data) so there is no `get` method

**Comment by bridiver** [comment] 2018-05-31 19:16
@srirambv - "Click on any link which opens in a new tab" - please be very specific in the instructions. I don't know which links open in a new tab so now I'm just trying to click through a bunch of them.

**Comment by bridiver** [comment] 2018-05-31 19:50
I pushed a fix for this to C67, but I recommend that anyone trying to repro this use a vm snapshot. This site is loaded with malware.

**Comment by bridiver** [comment] 2018-05-31 19:51
@srirambv I was confused because none of the links opened in a new tab, but in general I think it's best to specify a specific link so there is no ambiguity.

**Comment by bsclifton** [comment] 2018-05-31 19:54
Fixed with https://github.com/brave/muon/commit/117fe111a79b4ccb279874b85891040bac3d519d (needs verification when new Muon build available)

**Closed by bsclifton** 2018-05-31 19:54 UTC
Labels: 0.22.x, bug, needs-investigation

**Comment by srirambv** [comment] 2018-06-04 19:27
Verified on Windows x64 using
* 0.22.806 0d30970
* muon 7.0.3
* libchromiumcontent 67.0.3396.62
