### ISSUE TITLE
When opening new tabs web pages are not shown.

### ISSUE THREAD

**Issue by MorganDark21798** [brave/browser-laptop#3787] opened 2016-09-07 10:23 UTC
Love this browser. I use it on all of my machine across many different operating system. This problem seems to only occur when I am working on Linux. Unfortunately this means now when ever I am doing important work on a Linux distribution I have to use a alternative. I am sorry if this has already been addressed in this form. I really hope this is fixed soon for the Linux plat form. If anyone knows why this is happening.

I am running Linux mint 18 Cinnamon?

**Comment by Aeyoun** [comment] 2016-09-07 11:13
I can confirm the issue on Fedora 24 64-bit.

I’ve only notice it happen when I open a new tab and type in a URL. The content area remains white and don’t update. Closing the tab doesn’t help and any tab I open thereafter will remain white. Already opened tabs remain functional.

I’d guesstimate that it happens as often as 1-in-6 tabs. No error messages reported from Brave.

I’ve confirmed that the page has actually loaded in the tab by opening the developer tools and inspecting the current tab’s DOM. The content area just remains white and refuses to paint until I restart Brave. My [complete glxinfo](https://gist.github.com/Aeyoun/f0586d5c8c627b198270b59b70248de4).

**Comment by MorganDark21798** [comment] 2016-09-07 17:41
Thanks for the reply. I do not understand this bug my self. I would like to see it fixed soon. I know that this might get in the way of some peoples browsing expierence.

**Comment by Aeyoun** [comment] 2016-09-07 20:42
New windows still render, but I can’t get the old window to recover no matter what I do (except restart Brave).

**Comment by Aeyoun** [comment] 2016-09-07 21:21
See screenshots. This is different than to what I normally see, but possibly related.

The illustrated issue was triggered with the right timing of hovering in the tab bar with the mouse while opening a new tab and loading a website in it using the keyboard. I suspected that this might be what triggered the original issue, and considering that I was able to trigger a graphic corruption like the attached screenshot, I think I’ll say that there is probably something there.

![screenshot-1](https://cloud.githubusercontent.com/assets/1102886/18328972/c363332e-7551-11e6-869d-ab4fd22552dd.png)

![screenshot-2](https://cloud.githubusercontent.com/assets/1102886/18328783/aa278ca8-7550-11e6-8a2f-3dc8c37fb022.png)

**Comment by MorganDark21798** [comment] 2016-09-08 07:38
I not sure what it is to be honest. I really hope this bug gets fixed soon. It is starting to get a lot more frequent. Each time it happens the only solution that I know works is restarting the browser. Do you know of any other solution?

**Comment by Aeyoun** [comment] 2016-09-21 13:42
100% reproducible test case:

1. Open a tab and navigate to http://www.quirksmode.org/html5/tests/video.html#link2
2. Open a new tab and go to http://example.com/

**Comment by Aeyoun** [comment] 2016-10-06 08:50
Any chance this issue could be prioritized? Forces me to restart Brave a few times per hour every day.

**Comment by luixxiul** [comment] 2016-10-06 09:07
I think this is related with #1471 while this issue happens on Fedora too as @Aeyoun says.

**Comment by juanluperez** [comment] 2016-10-11 10:09
I can confirm this issue linked in https://github.com/brave/browser-laptop/issues/1471#issuecomment-251916315

**Comment by dmp1ce** [comment] 2016-10-18 18:18
I'm experiencing the same issue using Manjaro using the AUR package here: https://aur.archlinux.org/packages/brave-bin/

My current version is: 0.12.4

**Comment by mxdlx** [comment] 2016-10-26 13:39
I had this issue with OpenSuse Leap, gave feedback via email. Now also happens on Ubuntu 16.04 LTS. My current version is 0.12.6. Is there any systematic way to investigate this issue properly? I don't have the necessary skills but I really want to use this browser.

**Comment by AlexGilleran** [comment] 2016-11-29 10:56
Same with https://aur.archlinux.org/packages/brave 0.12.10 - those reproduction instructions cause it reliably but it happens pretty consistently after four or five tabs get opened.

**Comment by bsclifton** [comment] 2017-01-30 07:01
I've created a [brand new wiki entry](https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page) which I hope helps 😄  Folks, can you please try the following steps for me?

1. Install latest version of Brave (as of now, this is 0.13.0)
2. See if you have the issue; Chromium always includes bug fixes which may resolve the issue
3. If you still have the issue, please close Brave and edit your shortcut to add the command line argument `--ignore-gpu-blacklist`. Relaunch and see if this resolves the issue
4. If this does not resolve the issue, please edit the shortcut and instead try `--disable-gpu`

Thanks in advance to anyone who can try this- your time is very much appreciated and will help other users.

cc: @AlexGilleran @mxdlx @dmp1ce @da2x @MorganDark21798

**Comment by mxdlx** [comment] 2017-01-31 19:59
I was having no issue until I opened inbox.google.com which always seems to trigger the bug for me.
But, step 3 flag `--ignore-gpu-blacklist` seems to be a fix so far. I've been 'testing' (just browsing) for 20 minutes and all is good. 
I'm writing this from brave actually.
I'll keep testing tomorrow, thanks @bsclifton!

**Comment by bsclifton** [comment] 2017-01-31 22:32
@mxdlx awesome! thanks for the report 😄

**Comment by The13thDoc** [comment] 2017-02-01 15:10
@bsclifton, @MorganDark21798, both `--ignore-gpu-blacklist` and `--disable-gpu` appear to work.

I will update if something changes. Thank you very much for this workaround. We should try to spread the word somehow. This bug is a major pain on Linux. They also mention this solution on #1471.

**Comment by DivineOmega** [comment] 2017-02-01 15:20
@The13thDoc If both work, I believe you will get better performance from using `--ignore-gpu-blacklist` as it will allow you to continue using graphical acceleration.

**Comment by mxdlx** [comment] 2017-02-01 15:34
@DivineOmega just out of curiosity, using these flags means we should experience performance or rendering issues?

**Comment by DivineOmega** [comment] 2017-02-01 15:41
@mxdlx My knowledge of these flags is as follows.

* `--ignore-gpu-blacklist` will force Chromium to try to use your graphics card even if it is not official supported/tested. You might experience graphical issues or performance problems in some cases, but it my experience this is very rare.
* `--disable-gpu` will force Chromium to attempt to use software rendered (not use your graphics card), which will put a greater strain your CPU. This may cause performance problems, but this depends on what you are viewing and the speed of your processor.

**Comment by bsclifton** [comment] 2018-07-25 07:45
Since we have a [documented workaround](https://community.brave.com/t/window-is-solid-black-or-solid-white-looks-like-a-blank-page/10003) and also because we're moving to [Brave Core](https://github.com/brave/brave-browser) and won't be addressing this before then, I believe it makes sense to close this issue

**Closed by bsclifton** 2018-07-25 07:45 UTC
Labels: OS/unix-like/linux, bug/driver
