### ISSUE TITLE
Unable to move tabs from one tab set to the next one

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2984] opened 2016-08-05 13:13 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Tabs created in one tab set can only be moved across in the same tab set. 

**Expected behavior:**
Should be able to move tabs from one tab set to the other
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Guessing its on all platforms
- Brave Version:
  0.11.2 Dev RC2
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment] 2016-09-22 10:26
Does this issue still exist?

**Comment by srirambv** [comment] 2016-09-22 10:42
Works only if you pull the tab on the new tabset and drop it. Just by dragging it after the last tab doesn't move to the next tabset.

**Comment by Liunkae** [comment] 2016-11-19 19:17
Duplicate of #557.

**Closed by Liunkae** 2016-11-19 19:17 UTC
