### ISSUE TITLE
Every time I un-minimize the browser, all tabs reload and start playing videos.

### ISSUE THREAD

**Issue by TheCNixon** [brave/browser-laptop#11990] opened 2017-11-16 01:05 UTC
### Description
Every time I un-minimize the browser, all tabs reload and start playing videos.

### Steps to Reproduce
  1. Open many tabs
  2. Minimize browser for around 30 minutes
  3. Open browser

**Actual result:**
![image](https://user-images.githubusercontent.com/10780361/32868418-6c9040da-ca2f-11e7-9204-983de1ec83e0.png)

**Expected result:**
Nothing would reload until I hover over or click on it.

**Reproduces how often:**
Every time.

### Brave Version

**about:brave info:**
```
Name | Version
-- | --
Brave | 0.19.88
rev | c29eca6
Muon | 4.5.15
libchromiumcontent | 62.0.3202.89
V8 | 6.2.414.40
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.14393
OS Architecture | x64
```

**Reproducible on current live release:**
Ye

**Comment by TheCNixon** [comment] 2017-11-16 01:06
Should also be noted that this has been happening for around 2 days, I've tried to see if it would go away but reproduces every time, even after restarting both my computer and the browser multiple times.

**Comment by Jacalz** [comment] 2017-11-16 19:33
This issue has been for a long time and it is a duplicate of #8749

**Closed by Jacalz** 2017-11-16 19:33 UTC
