### ISSUE TITLE
Window is too wide when maximized

### ISSUE THREAD

**Issue by Zuzu-Typ** [brave/browser-laptop#5274] opened 2016-10-30 16:09 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Having a dual-monitor setup, the Brave window, when maximized on the rigth monitor and in focus, has a white / black (varying) border on the left.

**Expected behavior:**
It should not be there.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win10 x64
- Brave Version:
  0.12.8dev Prev1
- Steps to reproduce:
  1. Have two screens connected to your pc.
  2. Maximize Brave on the right one
  3. If you can't see the Border, have the left screen show a dark colored picture fort better contrast (remember to have the Brave window in focus)
- Screenshot if needed:
  ![brave](https://cloud.githubusercontent.com/assets/20467351/19837861/988267d8-9ec3-11e6-99b1-278a63821fd5.png)
- Any related issues:

**Comment by Zuzu-Typ** [comment] 2016-11-05 21:35
I have an updated picture, because it seems my issue wasn't reproduceable.

You can clearly see the black border.
![border](https://cloud.githubusercontent.com/assets/20467351/20033718/be53ee1c-a3a7-11e6-851d-647986ec5979.png)

**Comment by mcollins451** [comment] 2016-11-16 17:33
I was going to submit this same issue, but when I searched, I found this.  It happens on my computer with the same setup.

**Comment by Superbest** [comment] 2016-11-21 19:10
Duplicate of #5159

**Comment by Zuzu-Typ** [comment] 2017-01-15 19:47
Appears to be fixed in Prev8.

**Closed** 2017-01-16 03:30 UTC

**Comment by bsclifton** [comment] 2017-01-16 04:01
We captured (and fixed) the same issue with https://github.com/brave/browser-laptop/issues/6258 

The issue you link to @Superbest is related, but is different. I'm curious if it's fixed too
