### ISSUE TITLE
General Settings: "Brave starts with" setting

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2104] opened 2016-06-06 23:20 UTC
Task: Edit strings to match spec, and add functionality if needed.

Functionality:
"my windows/tabs from last time"
 - when brave starts, it returns all views to the same place (where you left off) including windows, tabs in each window, and each window position, including which monitor. The last selected page is shown again. This page is loaded but other pages are suspended until clicked again.

"my home page"
- while the previous pages are retained in history, the browser starts with a single page, and a single tab which loads with the users home page (which is set in this same settings panel.)

"a new tab"
- while the previous pages are retained in history, the browser starts with a single page, and a single tab which loads with the current new-tab content. (a blank page as of this writing.)

Label string:  
"Brave Starts with"

Selection strings:
"my windows/tabs from last time"
"my home page"
"a new tab"

General Settings spec image: (this issue indicated by blue rectangle)
![image](https://cloud.githubusercontent.com/assets/13509546/15840953/51ed335e-2c02-11e6-835c-7e664181c327.png)

Menu:
![image](https://cloud.githubusercontent.com/assets/13509546/15840966/78cc7ff2-2c02-11e6-8bb7-dcbd3ab1d7bf.png)

**Comment by the-puddlejumper** [comment] 2016-06-09 23:53
In Preferences I have " Brave Starts With " set to " Show My Windows / Tabs From Last Time ".
The problem is that when I close Brave and resume at a later time only " One " window opens. Everything else in other windows is lost.

**Comment by bsclifton** [comment] 2016-10-08 19:16
Closing as it looks like this has been done for quite some time :smile:

**Closed by bsclifton** 2016-10-08 19:16 UTC
Labels: documentation, settings
