### ISSUE TITLE
Hidden history entries appear by deleting the latest entry

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4224] opened 2016-09-23 09:03 UTC
**Describe the issue you encountered:** Hidden history entries appear by deleting the latest entry.

![history](https://cloud.githubusercontent.com/assets/3362943/18780254/9a9c1a9c-81b7-11e6-8c91-8305723acf15.gif)

5:50:14 PM -> 5:50:22 PM -> 5:51:04 PM -> 5:51:06 PM

I am not sure of steps to reproduce the issue.

**Expected behavior:** No history entries should be hidden.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.1
- Any related issues:

**Comment by luixxiul** [comment] 2016-10-05 01:30
Sometimes these hidden entries appear at one time after browsing some pages.

**Comment by aekeus** [comment] 2016-10-24 20:38
I cannot reproduce this bug. Are there any other steps required for the STR?

**Comment by bsclifton** [comment] 2016-11-04 17:52
Closing. Please do reopen if there are some clear STR.  Thanks :smile:

**Comment by luixxiul** [comment] 2016-11-05 01:17
Though not sure of STR I still experience the bug both on macOS and WIndows.

**Comment by luixxiul** [comment] 2016-11-05 01:19
I would close the issue if I confirmed the issue has been fixed in some way.

**Comment by bsclifton** [comment] 2016-11-05 01:39
@luixxiul would you be able to back up your session file so we don't lose it and then remove entries one at a time until there is no sensitive info? If you're open to sharing privately, hit me up on Slack with the file :smile:

**Comment by bsclifton** [comment] 2016-11-11 08:44
I'm going to close this issue; the root cause is likely solved with https://github.com/brave/browser-laptop/pull/5559 and there are not clear steps to repro / no example session file.

Please reopen after https://github.com/brave/browser-laptop/pull/5559 is accepted and in master (or a preview/release candidate) and it can be confirmed that it's not fixed.  Thanks :smile:

**Comment by luixxiul** [comment] 2016-11-14 11:22
@bsclifton Is this fixed with #5600?

**Comment by bsclifton** [comment] 2016-11-15 05:11
Hi @luixxiul, it's not fixed with that PR, thanks for the follow up

I suspect I have an idea of what the root cause might be- maybe you can help me try to reproduce? 😄 

Basically, history and bookmarks are combined. When you delete a history entry, there is still a bookmark for it. Also, if you remove the bookmark, there is still a history entry for it.

Would you try some combinations of visiting a site, making sure it shows in history, bookmarking it, making sure bookmark shows in bookmark manager.. then deleting the history entry?

I'll reopen issue in the meantime

**Comment by NejcZdovc** [comment] 2017-07-20 12:30
This should be fixed with #9978

**Closed** 2017-08-04 16:17 UTC
Labels: bug, feature/history
