### ISSUE TITLE
url for current webpage is not available

### ISSUE THREAD

**Issue by patrick99e99** [brave/browser-laptop#14367] opened 2018-06-09 17:57 UTC
### Description
Viewing a youtube video.. turns out it's hilarious and I want to share it with someone.. I click the url bar to copy the url-- and there is no url there!

### Steps to Reproduce
don't think I can reproduce it.. all I did was go to youtube and visit a link and then click the url bar.  I do that all the time and this usually does not happen.

**Actual result:**
as you can see, the window shows a url:
<img width="1280" alt="screen shot 2018-06-09 at 10 54 54 am" src="https://user-images.githubusercontent.com/28946/41194647-d0bf8ec6-6bd3-11e8-8fa7-1bcda15cbdf1.png">

but once I click the url bar, it's not there...
<img width="1280" alt="screen shot 2018-06-09 at 10 54 56 am" src="https://user-images.githubusercontent.com/28946/41194648-d2250610-6bd3-11e8-8a03-a57f5c2e6d2f.png">

### Brave Version

**about:brave info:**
 
Brave: 0.22.727 
V8: 6.6.346.32 
rev: 2c94bbad00d70b87328f04574725979960e18f9f 
Muon: 6.0.12 
OS Release: 17.3.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Comment by eljuno** [comment] 2018-06-11 21:27
For temporary workaround, you can hit `Esc` on keyboard to bring it back. :smile:

**Comment by bsclifton** [comment] 2018-06-11 22:04
Definitely ran into this myself- thanks for the report, @patrick99e99 😄

**Comment by bsclifton** [comment] 2018-08-13 20:35
Closing as a dupe of https://github.com/brave/browser-laptop/issues/14513 (which has steps to reproduce! 😄 )

**Closed by bsclifton** 2018-08-13 20:35 UTC
Labels: bug, feature/URLbar
