### ISSUE TITLE
Swipe back on macOS

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5907] opened 2016-11-29 16:58 UTC
From support
> I regularly find my web page going back to the previous in my history because it seems like Brave has introduced gestures and I'm accidentally swiping backwards on my touch pad.
> 
> Is it possible to make that a preference that can be switched off?

#2548

**Comment by darkdh** [comment] 2016-11-30 10:58
We will respect this system setting if user turn it off.
<img width="640" alt="screen shot 2016-11-30 at 18 57 15" src="https://cloud.githubusercontent.com/assets/11330831/20749818/dbcef46a-b72e-11e6-95cb-49fd7e3cba25.png">

**Comment by pixelass** [comment] 2016-11-30 17:30
I can confirm that it works with the system settings. It's the first thing I disable when I get a new macbook. Never had problems in the last two months of using brave.

**Comment by tcr** [comment] 2016-11-30 20:22
They may be triggering this issue more often than intended: two-finger "back" can be triggered on horizontally scrolling elements, where in other browsers the element swallows the swipe.

**Comment by Liunkae** [comment] 2016-11-30 23:26
I think the user in the support ticket wants an override setting for gestures in Brave. That way, the user can disable gestures in Brave only but leave gestures enabled in system preferences.

**Comment by ENDelt260** [comment] 2017-01-30 21:54
Brave 0.13.0 on MacOS 10.12.3 does not appear to respect the system setting.

I have "Swipe between pages" disabled in my Mouse System Preferences, but Brave navigates my history w/ left/right swipes anyway.

**Comment by DocWatson** [comment] 2017-02-07 02:40
Seeing the same issue as the poster above me, but I am on brave 0.13.2 and MacOS 10.11.6. I don't like/want this behavior, and would love for a way to disable it if the system settings cannot be used.

**Comment by d-fay** [comment] 2017-02-09 02:52
I also would like the option to disable this feature within Brave. I disabled the gesture on my Mac trackpad settings and the gesture still works in Brave, but I would like it disabled.

**Comment by bsclifton** [comment] 2017-02-09 05:50
Per the above, it should be respecting the setting (on macOS)... cc: @darkdh

**Comment by darkdh** [comment] 2017-02-09 06:18
system preferences is removed because of chromium 54 upgrade changes(node removal)
https://github.com/brave/browser-laptop/blob/master/js/components/main.js#L257-L258

**Comment by luixxiul** [comment] 2017-02-11 10:55
@darkdh would you reset the milestone if you would work on this issue, thanks!

**Comment by benjaminkitt** [comment] 2017-02-27 17:13
Just to reiterate, the swipe gesture should not trigger when scrolling horizontally. Using a wide Google Sheet for example is maddening because whenever you scroll to the left, you trigger the back swipe action.

**Comment by itslenny** [comment] 2017-03-01 06:07
I regularly have this happen. It's incredibly sensitive sometimes I'm barely even scrolling when it happens. This happens to me multiple times every single day. It's gotten so frustrating that I have to stop using brave until it's fixed.

**Comment by Liunkae** [comment] 2017-03-01 21:13
Everyone with the accidental swipe problem: please see issue #7100 (Horizontal scrolling with two-finger gesture is also treated as page navigation).

**Comment by Liunkae** [comment] 2017-03-18 17:40
I'm going to close this since we already have issues for the problems described here.

Back/forward gesture does not respect system preferences: #3299
Horizontal scrolling with two-finger gesture is also treated as page navigation: #7100

Please subscribe to those issues for further updates.

**Closed by Liunkae** 2017-03-18 17:40 UTC
Labels: OS/macOS
