### ISSUE TITLE
Geo location not detected on CR64

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12651] opened 2018-01-15 03:32 UTC
### Description
Geo location not detected on CR64

### Steps to Reproduce
  1. Clean install CR64 build 0.19.135
  2. Visit https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation, Click on Show my location, shows `Unable to retrieve your location`
  3. Visit https://browserleaks.com/geo, Click `Allow` in the notification bar, times out but doesn't show the location.

**Actual result:**
![geo](https://user-images.githubusercontent.com/17010094/34925932-75f07e4c-f9d2-11e7-9182-d634fdf4cee1.gif)

**Expected result:**
Should retrieve user location

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.135
-- | --
rev | 1f3af75
Muon | 4.7.0
libchromiumcontent | 64.0.3282.71
V8 | 6.4.388.12
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
No

**Comment by srirambv** [comment] 2018-01-15 03:50
Broken on Linux as well

**Comment by kjozwiak** [comment] 2018-01-15 17:40
Reproduced the issue on `macOS 10.13.2 x64` using `0.19.136` 1659471cf1b1016568f63a6ab3e35b604d7e3db3.

**Comment by bridiver** [comment] 2018-01-16 01:43
what about windows?

**Comment by srirambv** [comment] 2018-01-16 02:55
@bridiver  broken on all platforms. Originally reported for Windows then reproduced on Linux and macOS

**Comment by srirambv** [comment] 2018-01-17 09:19
Still broken on https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation  but works https://browserleaks.com/geo
![geo1](https://user-images.githubusercontent.com/17010094/35034832-78eab2d8-fb95-11e7-8e52-cd3ab16e6b28.gif)

**Comment by srirambv** [comment] 2018-01-17 09:41
Opening the codepen/jsfiddle  link from https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation shows the location but not the mozilla link

**Comment by srirambv** [comment] 2018-01-17 11:17
Same behaviour on Windows and Linux as mentioned in the previous comment

**Comment by bsclifton** [comment] 2018-01-17 21:38
Geo functionality is working as expected- however another issue was found (see https://github.com/brave/browser-laptop/issues/12692).  Closing this issue as resolved

**Closed by bsclifton** 2018-01-17 21:38 UTC
Labels: 0.19.x, bug, cr64, regression, release-notes/exclude, release/blocking

**Comment by LaurenWags** [comment] 2018-01-18 18:23
See https://github.com/brave/browser-laptop/issues/12692#issuecomment-358481465 for more information.

**Comment by kjozwiak** [comment] 2018-01-18 23:15
As per @LaurenWags's above comment, I also ensured that visiting https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation produces the following warning/error in the browser console:

`Geolocation_Live_Example?revision=1322517:49 Geolocation access has been blocked because of a Feature Policy applied to the current document. See https://goo.gl/EuHzyv for more details.`
