### ISSUE TITLE
Incorrect Cmd-Shift- shortcuts in Dvorak layout in macOS

### ISSUE THREAD

**Issue by jni** [brave/browser-laptop#13299] opened 2018-02-25 01:24 UTC
### Description

In macOS, `Cmd-Shift-{` and `Cmd-Shift-}` should be previous tab and next tab, `Cmd-Shift-_` and `Cmd-Shift-+` should be zoom out and zoom in. Using a US keyboard layout, they are, but with the [Dvorak keyboard layout](https://en.wikipedia.org/wiki/Dvorak_Simplified_Keyboard), these specific keys are not remapped.

Oddly, this is only true with `Cmd-Shift`. For example, `Cmd-[` is interpreted as "back" correctly, `Cmd-=` is correctly interpreted as zoom in, etc.

### Steps to Reproduce

  1. Set the macOS keyboard layout to "English" > "DV - Dvorak"
  2. Open a bunch of tabs in Brave
  3. Press the Dvorak key combo `Cmd - Shift - }` (the `}` key is on the `+ =` key is a US English keyboard)

**Actual result:**

The content of the current tab is enlarged

**Expected result:**
The next tab is selected.

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

 
Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:**

Not sure...

### Additional Information

None

**Comment by bsclifton** [comment] 2018-09-01 05:15
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/15132

**Closed by bsclifton** 2018-09-01 05:15 UTC
Labels: OS/macOS, feature/keyboard-shortcuts
