### ISSUE TITLE
URL bar drops last 2 characters when typing fast (not related to auto suggestions or history)

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#5189] opened 2016-10-27 13:43 UTC
Start with a new tab.

1 type a new URL (not already in history) in a normal, but fast cadence.

2 hit enter to commit the string.

3 Notice that the "om" in ".com" was missing.

View the GIF recording and open the file in Mac Preview. This will reveal frames where an unwanted sequence is occurring which may be causing the dropped characters.

(gif shows same URL entered in same cadence in chrome with no issues)

![missingcharacters_in_url](https://cloud.githubusercontent.com/assets/13509546/19769514/af045ddc-9c29-11e6-8490-521001f1a9f6.gif)

cc @diracdeltas 
cc @bbondy

**Comment by bradleyrichter** [comment] 2016-10-27 13:48
actual frames from GIF file above:

![image](https://cloud.githubusercontent.com/assets/13509546/19769666/5869641c-9c2a-11e6-8c12-c1639c2cadd4.png)


![image](https://cloud.githubusercontent.com/assets/13509546/19769678/61a64da6-9c2a-11e6-98df-796d4b94462e.png)

![image](https://cloud.githubusercontent.com/assets/13509546/19769684/6b9c1638-9c2a-11e6-912a-3c85aeeb6e89.png)

![image](https://cloud.githubusercontent.com/assets/13509546/19769692/74a47f54-9c2a-11e6-993f-4be317c62698.png)

![image](https://cloud.githubusercontent.com/assets/13509546/19769704/82ad6142-9c2a-11e6-8a12-321683fb082f.png)

**Comment by jkup** [comment] 2016-10-27 22:58
Is this a dupe of https://github.com/brave/browser-laptop/issues/4731? If so then the fix is in master!

**Comment by bbondy** [comment] 2016-10-28 13:09
Brad reproduced again so still valid, but seems things changed with the sequence of GIF frames when you hit enter.

**Comment by bradleyrichter** [comment] 2016-10-28 13:15
It doesn't seem to happen with random characters. Only in the suffix. 

![missingcharacters_in_url2](https://cloud.githubusercontent.com/assets/13509546/19807623/fa44e81e-9cee-11e6-8a3d-451559295310.gif)

![missingcharacters_in_url3](https://cloud.githubusercontent.com/assets/13509546/19807630/00511d22-9cef-11e6-975c-6fe4a91dd837.gif)

**Comment by bradleyrichter** [comment] 2016-10-28 13:17
![image](https://cloud.githubusercontent.com/assets/13509546/19807672/3854a7ac-9cef-11e6-8e02-8da252bab7b3.png)

![image](https://cloud.githubusercontent.com/assets/13509546/19807688/453fbdd0-9cef-11e6-8143-215b5c6ea71e.png)

![image](https://cloud.githubusercontent.com/assets/13509546/19807700/4f45ed4a-9cef-11e6-974d-c2f16c2bdf6f.png)

**Comment by mideava** [comment] 2016-10-29 01:19
I have the same problem, but I only lose the last single character. For example, when I type a ".org" domain fast enough, Brave supresses the "g" and adds the final "/", so I end up with ".or/".

**Comment by BrendanEich** [comment] 2016-10-29 04:41
Is there something sampling .length on the string in the URL bar in a racy way, then using that later to truncate the string? Just a guess.

**Closed** 2016-11-01 00:23 UTC
Labels: bug, feature/search, feature/URLbar, release/blocking
