### ISSUE TITLE
calls to appActions.updateLedgerInfo() does not update about:preferences#payments for wallet creation

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#6440] opened 2016-12-28 01:40 UTC
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
1. start the browser without a wallet
2. go to about:preferences#payments
3. tell the browser to create the wallet
4. nothing *appears* to happen

**Expected behavior:**
the wallet should be created, and the about:preferences#payments page should re-populate accordingly

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/c27eb0b1241587cb3478f253c8e8c685135d38a7

- Steps to reproduce:
    1. see above

- Screenshot if needed:
not needed

- Any related issues:
if, after doing the 4 steps above, you then close the about:preferences#payments tab (but not the browser), then open a new tab, then go back to about:preferences#payments you will see the wallet has been created.

cc: @alexwykoff

**Comment by jkup** [comment] 2016-12-30 04:52
@mrose17 @alexwykoff I believe this behavior was caused by some of the muon/cr54 updates that were causing setTabIndex errors in the console. Now that @bbondy has updated browser-laptop can you try wallet creation with the latest master and see if it's still an issue?

**Comment by alexwykoff** [comment] 2016-12-30 15:34
@jkup wallet creation and ledger appear to be working fine. if there are no other followups related to any code cleanup, i'd say it's fine to close this.

**Closed** 2016-12-30 15:47 UTC
Labels: release/blocking, settings

**Comment by bbondy** [comment] 2016-12-31 19:58
Whenever closing, if no code lands please remove label, I did it this time though. Thanks!
