### ISSUE TITLE
Bookmark Folders Are Blank

### ISSUE THREAD

**Issue by pureooze** [brave/browser-laptop#3636] opened 2016-09-01 16:24 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
After the 0.11.6 my bookmarks folders are all blank (see screenshots) even though I have assigned them names. Even when I change the name it is still not updated.

**Expected behavior:**
The bookmarks  folders should display their assigned names

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux, OpenSUSE Tumbleweed

- Brave Version:
0.11.6

- Steps to reproduce:
    1. Use Brave pre 0.11.6
    2. Create some bookmark folders
    3. Upgrade to 0.11.6

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/2337524/18175211/8131620e-703e-11e6-86e6-89fb205a43b7.png)

![image](https://cloud.githubusercontent.com/assets/2337524/18175250/a59b9b14-703e-11e6-9029-65c612ec497d.png)

- Any related issues:
No, bookmarks are still displayed properly, just that the folder names are blank

**Comment by luixxiul** [comment] 2016-09-01 17:16
I think this is dupe of #3622 
Will you please disable "show only favicon" option and confirm the titles appear?

**Comment by pureooze** [comment] 2016-09-01 17:17
Ah that fixed it, I didnt realize it was related. Sorry for the dup report.

**Comment by luixxiul** [comment] 2016-09-01 17:24
Nevermind, thanks for the feedback :-)

**Closed** 2016-09-24 04:12 UTC
Labels: bookmarks, duplicate
