### ISSUE TITLE
Right-click Search for ... pastes the entire search URL in Google Search Engine search field

### ISSUE THREAD

**Issue by unsystemizer** [brave/browser-laptop#5083] opened 2016-10-24 05:28 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**

I tried to search for selected text on Github:

![image](https://cloud.githubusercontent.com/assets/13134193/19634406/4f9859ea-99ed-11e6-9a40-24e900529223.png)

**Expected behavior:**

GSE results for the text selected
- Platform (Win7, 8, 10? macOS? Linux distro?):

Win 10
- Brave Version:

0.12.5
- Steps to reproduce:
  1. Select text
  2. Search for selected text>
  3. Switch to GSE tab
- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/13134193/19634432/9ba6eb76-99ed-11e6-8fce-4755c9cb75c2.png)

**Comment by Liunkae** [comment] 2016-11-16 01:19
+1 from #5646. Also, I have confirmed this issue myself with Brave 0.12.9 on macOS 10.12.x.

Here are the conditions I have found so far:

- It only happens with Google as the default search engine.
- It only happens with text containing certain characters (such as a period `.`).

**Comment by bsclifton** [comment] 2017-03-13 23:04
@Liunkae can you retest this? I know we did recently fix (maybe 0.13.0-ish) the behavior of URLs which have a decimal in them. #5627 still happens and is an issue, but this issue may be resolved 😄

**Comment by Liunkae** [comment] 2017-03-14 04:29
@bsclifton I cannot reproduce anymore with 0.13.5. Closing as fixed!

**Closed by Liunkae** 2017-03-14 04:29 UTC
Labels: feature/search, needs investigation, verified
