### ISSUE TITLE
Favicon bug for reddit bookmark

### ISSUE THREAD

**Issue by gravitycrusher7** [brave/browser-laptop#2238] opened 2016-06-18 20:20 UTC
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
It show wrong favicon. First of all it didnt show favicon, but when I click reddit post that link into twitter it show twitter favicon for my reddit bookmark.

This issue happen when I bookmark without favicon option, then I turn on option bookmark with favicon. It started the issue. 

New bookmark with favicon option didnt result an issue.

Sorry for bad grammar.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 7
- Brave Version:
Latest brave version

#1646

**Comment by cezaraugusto** [comment] 2016-06-20 22:58
Hi @gravitycrusher7 thanks for pointing this.

I couldn't reproduce your issue, but since it's the same as #1646 and other users are also reporting the same thing, I'll close it in favor of that.

**Closed by cezaraugusto** 2016-06-20 22:58 UTC
