### ISSUE TITLE
Add support for Enpass password manager. 

### ISSUE THREAD

**Issue by webbson** [brave/browser-laptop#2608] opened 2016-07-20 11:02 UTC
I really like your browser, the only thing I'm missing is support for Enpass password manager ([enpass.io](https://www.enpass.io)).

Is this something that might be implemented? I would like this support in Brave on Windows, iOS and Android.

**Comment by luixxiul** [comment] 2016-08-10 12:53
+1 from support

**Comment by stefnats** [comment] 2016-12-20 14:39
+1 would be great

**Comment by bbondy** [comment] 2017-01-26 05:01
dupe of https://github.com/brave/browser-laptop/issues/5097 ?

**Comment by bsclifton** [comment] 2017-01-26 05:45
Yup, https://github.com/brave/browser-laptop/issues/5097 is a dupe of this! 😄  Closing issue

**Closed by bsclifton** 2017-01-26 05:45 UTC
Labels: feature/password-manager, suggestion
