### ISSUE TITLE
export snapshots of single pages as pdf/png/jpeg.. print doesn't let me save as pdf, might as well just add a pdf export button there.

### ISSUE THREAD

**Issue by JAD1932** [brave/browser-laptop#13175] opened 2018-02-18 12:46 UTC

**Comment by srirambv** [comment] 2018-02-19 03:48
Could you please edit the issue by adding relevant details rather than such a big issue title

**Comment by bsclifton** [comment] 2018-02-19 06:13
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/12139

**Closed by bsclifton** 2018-02-19 06:13 UTC
Labels: needs-info
