### ISSUE TITLE
Crash when switching between menu items on Linux

### ISSUE THREAD

**Issue by hugobuddel** [brave/browser-laptop#13014] opened 2018-02-05 11:33 UTC
Perhaps similar: https://github.com/brave/browser-laptop/issues/4061

### Description
Moving around between menus crashes brave.

### Steps to Reproduce
  1. Click on e.g. the 'Window'-menu
  2. Move the mouse to e.g. the 'Shields'-menu and 'Bookmarks'-menu

**Actual result:**
Brave segfaults. In fact, entire window manager (gnome shell) hangs. Needed to run 'xkill' to get the WM to respond again, even though Brave had already crashed at that point.

**Expected result:**
Brave stays open.

**Reproduces how often:**
Seems to be reproducible all the time.

### Brave Version

**about:brave info:**
 
Brave: 0.19.134 
rev: 316cfa522ffe6a558fe9f2f3f299c0c602dfb691 
Muon: 4.5.38 
libchromiumcontent: 63.0.3239.132 
V8: 6.3.292.49 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 3.10.0-693.11.6.el7.x86_64 
OS Architecture: x64

**Reproducible on current live release:**
Don't know, unable to download the latest Brave version, see #13013.

### Additional Information
Running on Scientific Linux 7.4 using Gnome 3. Brave installed as binary, and ran without sandbox because I don't have root access on this machine.

**Comment by hugobuddel** [comment] 2018-02-05 11:50
Also happens in 0.20.30. It is still possible to use the menu though, by ensuring you close the open menu before opening the next one.
 
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 3.10.0-693.11.6.el7.x86_64 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Comment by hugobuddel** [comment] 2018-02-05 18:21
Can also be reproduced on Ubuntu 16.04 using MATE. Just move around the menus a bit. Brave seems to crash when you move out of the menu.

Console output:

> Crash dump id: 9951c95869318371
> Segmentation fault (core dumped)

dmesg output (perhaps different crash):

> traps: brave[26613] general protection ip:32f4af0 sp:7ffff4c10f78 error:0 in brave[19a6000+4851000]

Popup I got once (out of ~10 crashes): 

![bravecrash](https://user-images.githubusercontent.com/1306453/35821531-8a007eea-0aa9-11e8-99ed-72bf375ac47a.png)

**Comment by kjozwiak** [comment] 2018-03-11 02:02
I've ran into this a bunch of times as well when using Ubuntu 17.10 x64 with `0.21.18` 580be782bc37ed8580dd22f79e1d2d355fddfb89 using the following STR:

* launch brave and ensure that you have the menu bar visible
* start switching through the different menu's very quickly and Brave will eventually crash

Crash Reports: (accessible to Brave dev's only)

* https://stats.brave.com/dashboard#crash/5aa48ca13744d6001f4963fa
* https://stats.brave.com/dashboard#crash/5aa48ce9c502b2001f876ccd
* https://stats.brave.com/dashboard#crash/5aa48d395ab0a3001fbfdf2e

Example of the crash occurring:

![linuxcrash](https://user-images.githubusercontent.com/2602313/37248670-48074430-24a6-11e8-9f4e-c816a8513ee6.gif)

**Comment by hugobuddel** [comment] 2018-04-25 07:54
Still happens on 0.22.22
Crash dump id: bce0a5f23994170d
 
Brave: 0.22.22 
V8: 6.5.254.41 
rev: 63033109963be0a995b3d1ed9723870beeb191c4 
Muon: 5.1.2 
OS Release: 3.10.0-693.21.1.el7.x86_64 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Comment by kjozwiak** [comment] 2018-05-03 16:33
Still reproducible with `0.22.669` which included C66. Was hoping we could get a free fix from C66! Tested on the following distro's:

* Ubuntu 17.10 x64 - Reproduced
* Mint 18.3 x64 - Reproduced

Used the following build for the above checks:

 ```
Brave: 0.22.669 
V8: 6.6.346.24 
rev: 6cda2e84f749e66409e9e3bca63f5796422e7edf 
Muon: 5.2.7 
OS Release: 4.13.0-39-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.117
```

**Comment by tlhunter** [comment] 2018-06-28 17:51
Still happening in 0.22.721. 100% reliably.

Linux karbonate 4.14.49-041449-generic #201806112130 SMP Mon Jun 11 21:32:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Linux Mint, Openbox, no compositor.

**Comment by hugobuddel** [comment] 2018-06-29 13:36
Also happening on 0.23.19
 
Brave: 0.23.19 
V8: 6.7.288.46 
rev: 178c3fbc045a0cbdbe098db08307503cce952081 
Muon: 7.1.3 
OS Release: 3.10.0-862.3.2.el7.x86_64 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Tor: 0.3.3.7 (git-035a35178c92da94) 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.87

**Comment by bsclifton** [comment] 2018-09-18 22:32
Closing as `wontfix`; with `brave-core`, this should be completely fixed

For folks experiencing this, I'd recommend giving it a download:
https://brave.com/download-dev

**Closed by bsclifton** 2018-09-18 22:32 UTC
Labels: 0.19.x, OS/unix-like/linux, crash, fixed-with-brave-core, priority/P2, wontfix

**Comment by hugobuddel** [comment] 2018-09-19 07:44
Thanks for the develop link @bsclifton. I was starting to feel a bit disenfranchised. All these closed issues took (some) effort to report. I don't have much discretionary time, but I find the Brave project worthwhile. The issues are being closed in favor for brave-browser (and rightly so), but I had no realistic way of actually running the new browser.

Could you please add that link to the brave-browser README.md? Instead it currently states that
> We're not offering downloads yet for this next generation desktop browser.

This almost made me give up in despair: either use a browser riddled with 'stale' bugs, or spend days trying to compile the new browser from source.

By the way, that README.md also still states that
> You can visit our website to get the latest stable release of our existing browser which is still in active development.

Is it time to remove that line? I'd say that 'active development' would include fixing crashes like these.

**Comment by bsclifton** [comment] 2018-09-19 18:06
@hugobuddel I definitely understand how you feel. As I (and others) have been going through these issues, we're taking extra care to migrate over the issues which are still a problem with the new code-base (or features that would be great to add to the new code-base). The issue log has grown from ~230 to almost 500 in that process so far:
https://github.com/brave/brave-browser/issues

Thanks for the heads up about not having a way to run the new browser- I didn't realize (or I had forgot) that we don't have a link to how Linux folks can get setup. I'm going to share that feedback with the team to see if we can have a more friendly experience. In the meantime, we have binaries available on our release page and we also have an install guide (which we should probably be linking to, on the dev landing page):
https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

I'm personally still working on the Muon based browser and we will be fixing bugs and crashes. We should have a new release soon with Chromium 69 actually 😄 But I think we're at a stage where we need to "pick the battles" with the current product, since the resources available to fix these issues are limited. I know it's not an ideal situation

Lastly, I want to let you know that I appreciate all of the time you've put into Brave. Even if issues have been closed, you personally have done a lot to help improve the quality of the product. Thank you very much for the detail you've put into the issues you've created or responded to, it's been extremely helpful 😄
