### ISSUE TITLE
Can't down arrow into dropdown for remembered username

### ISSUE THREAD

**Issue by ShivanKaul** [brave/browser-laptop#3744] opened 2016-09-05 22:13 UTC
**Did you search for similar issues before submitting this one?**
Yeah.

**Describe the issue you encountered:**
I have Autofill enabled, and am using Brave Built-In Password Manager. I had the same issue with Shields down (Fingerprinting, scripts etc turned off).

I start typing my username in Gmail, and a dropdown containing my previously entered username shows up. However, I try to press down and select it, and nothing happens. Selecting via mouse works.

**Expected behavior:**
Should be able to press down and get into suggested username. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS X

- Brave Version:
![image](https://cloud.githubusercontent.com/assets/5284154/18257547/b8835f2a-7393-11e6-97fd-7272df57e54a.png)

- Steps to reproduce:
    1. Go to gmail.com and try to login
    2. Start typing and a suggested username should show up
    3. Press down arrow

- Screenshot if needed:
<img width="785" alt="screen shot 2016-09-05 at 6 10 18 pm" src="https://cloud.githubusercontent.com/assets/5284154/18257594/52fab648-7394-11e6-967b-231cd2def334.png">

**Comment by srirambv** [comment] 2016-09-05 22:28
Duplicate of #1302 #3402

**Closed by srirambv** 2016-09-05 22:28 UTC
