### ISSUE TITLE
Add delete confirmation to downloads bar

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#5969] opened 2016-12-01 16:51 UTC
Deleting files is destructive and can not be undone. Thus, it needs a minimal confirmation.

Adding this to the delete bar UI keeps the confirmation focused at the point of interaction rather than opening a dialog. 

To cancel, click outside of the popup box.

![image](https://cloud.githubusercontent.com/assets/13509546/20803042/c33828ee-b7a2-11e6-80a7-2ec61398c854.png)

**Comment by bsclifton** [comment] 2016-12-03 22:32
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/2604

Love the pic! I copied it and your text over to #2604

**Closed by bsclifton** 2016-12-03 22:32 UTC
Labels: design, enhancement, parity
