### ISSUE TITLE
Form autocomplete not keyboard accessible

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#4873] opened 2016-10-17 20:15 UTC
I swear there was already an issue for this but I cannot find it.

When filling out a form our autocomplete suggestions require a mouse click, you should be able to use the arrow keys to scroll through suggestions and then hit enter or tab to select.

**Comment by Liunkae** [comment] 2016-11-19 08:24
Duplicate of #1302.

**Closed by Liunkae** 2016-11-19 08:24 UTC
Labels: feature/keyboard-shortcuts, parity
