### ISSUE TITLE
Cannot set property 'enabled' of null when launching or closing Brave.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13991] opened 2018-05-02 17:44 UTC
### Description
Cannot set property 'enabled' of null when launching from brave

### Steps to Reproduce

  1. Build from 9306021
  2. Launch from console 
  3. Throws error when browser is launched

**Actual result:**
```
$ npm run start

> brave@0.22.700 start C:\work\browser-laptop
> node ./tools/start.js --user-data-dir-name=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck

Crash reporting enabled
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot set property 'enabled' of null
    at setMenuItemAttribute (C:\work\browser-laptop\app\browser\menu.js:647:23)
    at updateShareMenuItems (C:\work\browser-laptop\app\browser\menu.js:664:5)
    at doAction (C:\work\browser-laptop\app\browser\menu.js:690:11)
    at reducers.reduce (C:\work\browser-laptop\js\stores\appStore.js:188:24)
    at Array.reduce (<anonymous>)
    at applyReducers (C:\work\browser-laptop\js\stores\appStore.js:186:68)
    at handleAppAction (C:\work\browser-laptop\js\stores\appStore.js:253:16)
    at callbacks.forEach (C:\work\browser-laptop\js\dispatcher\appDispatcher.js:107:7)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (C:\work\browser-laptop\js\dispatcher\appDispatcher.js:106:20)
```

**Expected result:**
Shouldn't show the error

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.22.700 9306021
* libchromiumcontent 66.0.3359.139
* muon: 6.0.7

**Reproducible on current live release:**
No

### Additional Information
Reproduced on macOS by @LaurenWags

**Comment by bsclifton** [comment] 2018-05-02 19:49
Likely caused by https://github.com/brave/browser-laptop/pull/13933 - I did have to do a manual merge

**Comment by kjozwiak** [comment] 2018-05-02 19:51
You'll get the above silent crash when you close Brave as well. Those crashes are also being logged within `chrome://crashes`.

**Comment by bsclifton** [comment] 2018-05-02 21:15
Fixed with https://github.com/brave/browser-laptop/commit/1b312a25e4b7cba19ebfda0120068516484bb3bd

**Closed by bsclifton** 2018-05-02 21:15 UTC
Labels: bug, crash, release-notes/exclude

**Comment by GeetaSarvadnya** [comment] 2018-05-03 14:27
Verified on Windows x64 
* 0.22.702 e4a853d* libchromiumcontent 66.0.3359.139
* muon: 6.0.7
