### ISSUE TITLE
WebExtension windows.create API not working

### ISSUE THREAD

**Issue by flyswatter** [brave/browser-laptop#8013] opened 2017-03-31 23:21 UTC
- Did you search for similar issues before submitting this one?

Yes

- Describe the issue you encountered:

I develop a WebExtension that uses the [windows.create](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/windows/create) API, but it does not seem to be working.

I'm unable to debug the specific cause because of [a lack of an inspector](https://github.com/brave/browser-laptop/issues/8012).

- Platform (Win7, 8, 10? macOS? Linux distro?):

Mac OS 10.12.4

- Brave Version (revision SHA):

Brave	0.14.0
rev	215cba3

- Steps to reproduce:
    1. Install an extension that triggers a new window with some action (like MetaMask).
    2. Perform an action that triggers this new window creation (like initiating a transaction in MetaMask).
    
- Actual result:

No visible popup (could be related to [popping up off screen](https://github.com/brave/browser-laptop/issues/7051)).

- Expected result:

A visible popup.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes

- Is this an issue in the currently released version?

Yes

- Can this issue be consistently reproduced?

Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by jonathansampson** [comment] 2017-05-04 01:36
Appears to be a dupe of #6789

**Closed by jonathansampson** 2017-05-04 01:36 UTC
Labels: feature/extensions
