### ISSUE TITLE
rarbg.to manages to create a pop-under

### ISSUE THREAD

**Issue by hugobuddel** [brave/browser-laptop#11503] opened 2017-10-13 09:22 UTC
### Description
Decided to do some tests after getting bitten by the pop-up blocker (#3752).

Turns out that rarbg.to manages to create a pop-under once in a while. That is, it has a search field, and when you click on it, it opens a new tab in which it reloads the site itself, and subsequently puts an add in the original tab. Try it on another browser to see it; works in Brave only 1/20 times or so.

### Steps to Reproduce
  1. Go to rarbg.to (warning: torrent site)
  2. Click on the 'Search Torrents' textfield
  3. Repeat, because the add is usually blocked.

**Actual result:**
![rarbgbrave](https://user-images.githubusercontent.com/1306453/31539333-8d69c268-b008-11e7-8fc2-391070763d60.png)

**Expected result:**
No add being loaded.

**Reproduces how often:**
About 1 in 20.

### Brave Version
0.19.45 on Windows 10
0.18.36 on Ubuntu 16

**Reproducible on current live release:**
Don't know what this means.

### Additional Information
Actual add may be NSFW. Site itself might also be NSFW.

**Comment by srirambv** [comment] 2017-10-13 09:41
Observed this on other sites as well. Chrome with ublock origin handles it as a popup and closes the tab immediately when it opens.

cc: @bbondy @lukemulks

**Comment by srirambv** [comment] 2018-07-04 15:30
+1 from https://community.brave.com/t/block-popup-tabs/26986 regarding popup created on several sites.

**Comment by srirambv** [comment] 2018-09-03 13:42
Looks like the issue is fixed on browser-laptop too for this site. I don't see any popup opened for the site on b-l. Navigated around the site and no popups shown. Same on Chrome as well. 

Closing the issue as the site is fixed.

**Closed by srirambv** 2018-09-03 13:42 UTC
Labels: parity, webcompat
