### ISSUE TITLE
pinning session tab opens a newtab

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13731] opened 2018-04-04 20:55 UTC
### Description
If you drag a session tab out into its own window and try to pin it, the tab doesn't pin and a new tab (with the same session #) opens in the original window.

### Steps to Reproduce

  1. Launch 0.22.103 with a clean profile
  2. Open a session 1 tab and navigate to a site (I used twitter)
  3. Open a session 2 tab and navigate to a site (I used twitter)
  4. Drag the session 2 tab out into its own window.
  5. Try to pin the session 2 tab

**Actual result:**
session 2 tab is not pinned, a new tab is opened in the original window:
![sessiontabs-pin](https://user-images.githubusercontent.com/28145373/38334078-695d4e64-3828-11e8-8ff3-cac7673b37b5.gif)

**Expected result:**
session 2 tab should be pinned
![sessiontabs-pin02213](https://user-images.githubusercontent.com/28145373/38334087-6fef6c80-3828-11e8-88a7-bc50d5bde17b.gif)

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
0.22.103

**Reproducible on current live release:**
no

**Comment by petemill** [comment] 2018-04-04 21:03
Can't reproduce on current dev so I think this will be fixed in the next build. Let's verify when that is available.

**Comment by btlechowski** [comment] 2018-04-05 08:59
Verified Win7 x64 v0.22.105

**Closed by btlechowski** 2018-04-05 08:59 UTC
Labels: 0.22.x-single-webview, PR/pending-review, bug, feature/session-tabs
