### ISSUE TITLE
Middle click on pinned tab causes other tabs to get pinned and loses the original pinned tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11825] opened 2017-11-07 15:12 UTC
### Description
Middle click on pinned tab causes other tabs to get pinned and looses the original pinned tab

### Steps to Reproduce
   1. Clean install 0.20.6
   2. Open 4-5 tabs and visit sites in each of them
   3. Pin one of the tabs
   4. Middle click on the pinned tab, all other tabs get pinned momentarily and the original pinned tab is lost 
    5. Relaunch browser, pinned tab is lost permanently 

**Actual result:**
![pintab](https://user-images.githubusercontent.com/17010094/32500628-c423f278-c3cd-11e7-9b5c-691028cb696d.gif)

**Expected result:**
Should not do anything to pinned tabs or other open tabs

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.6
-- | --
V8 | 6.2.414.36
rev | 18f7d1e
Muon | 4.5.14
OS Release | 10.0.15063
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 62.0.3202.75

**Reproducible on current live release:**
N/A

**Comment by alexwykoff** [comment] 2017-11-29 18:04
@srirambv could you give this another go? Thanks!

**Comment by petemill** [comment] 2017-11-29 18:17
Just reproduced on master

**Comment by srirambv** [comment] 2017-12-22 13:21
Side effect of this issue is captured here https://github.com/brave/browser-laptop/issues/12379

**Comment by cezaraugusto** [comment] 2017-12-26 21:41
bug confirmed but btw closing the pinned tab with middle click is the expected behavior

**Comment by petemill** [comment] 2017-12-26 21:47
surely if middle-click to close should work, then cmd(or ctrl)-w should also, since they do the same thing? It must be both or neither, I would imagine, since they are the same 'shortcut'.

**Closed** 2017-12-27 23:12 UTC
Labels: 0.20.x, bug, feature/pinned-tabs, needs-investigation, OS/Windows, release-notes/exclude, release/blocking
