### ISSUE TITLE
Recovery seed is "a"

### ISSUE THREAD

**Issue by spacecitizen** [brave/browser-laptop#12725] opened 2018-01-19 10:34 UTC
### Description
The recovery seed is still "a"

### Steps to Reproduce

  1. about:preferences#payments
  2. Go to Advanced settings
  3. Back up your wallet

**Actual result:**
![image](https://user-images.githubusercontent.com/29564492/35146804-6f874404-fd0c-11e7-8d72-f3c262d0067b.png)

**Expected result:**
recovery seed

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
Brave: 0.19.134 
rev: 316cfa522ffe6a558fe9f2f3f299c0c602dfb691 
Muon: 4.5.38 
libchromiumcontent: 63.0.3239.132 
V8: 6.3.292.49 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.14393 
OS Architecture: x64

**Reproducible on current live release:**
yes

**Comment by NejcZdovc** [comment] 2018-01-19 11:17
thank you  for your report. We have a fix for this here https://github.com/brave/browser-laptop/pull/12677 and it will be shipped in the next release.

It's dupe of #12672

**Closed by NejcZdovc** 2018-01-19 11:17 UTC

**Comment by bsclifton** [comment] 2018-01-19 21:08
@spacecitizen do you have a backup of your keywords?  Like @NejcZdovc has said, we have a fix for this... but it hasn't shipped yet.  When it does, you'll be able to do a restore and it will be fixed 😄 👍

**Comment by spacecitizen** [comment] 2018-01-22 08:08
Hi @bsclifton, unfortunately I don't have a backup. I just installed the last upgrade 1.19.139 but the fix mentioned by @NejcZdovc seems wasn't add to the latest release.
I am not concerned, I have few BAT on my Brave wallet and I love the Brave technologies!
