### ISSUE TITLE
Tab Carrying & Tab Sharing

### ISSUE THREAD

**Issue by hasanhuseyincakir** [brave/browser-laptop#438] opened 2016-01-29 17:00 UTC
Usually I'm using 2 different monitors & running 2 different processes of browsers. On other browsers I can carry my tabs between these 2 different browser processes. Brave doesn't support this yet.

Also I would like to "push" my tab into my phone or from my phone to my laptop. Like firefox's tab syncing between android/pc versions but I just want to push spesific tab, if it's possible with a note. 
For instance I'm on the road & checked something and I need to reply it (via comment or sth else), I want to push this tab into my computer with a note to remember what to do, (I don't like typing WoTs on my phone).

**Comment by Tombsmen** [comment] 2016-01-29 17:05
The top two sentences are the same design sugestion as ticket [#405](https://github.com/brave/browser-laptop/issues/405)  I think  #405 should be merged with this ticket.

**Comment by Liunkae** [comment] 2016-11-16 18:20
Duplicate of #405.

**Closed by Liunkae** 2016-11-16 18:20 UTC
Labels: suggestion
