### ISSUE TITLE
Minimizing the browser window leaves the tooltip open

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#8697] opened 2017-05-04 15:20 UTC
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Originaly from the community but I can comfirm that I have the same issue :+1:
https://community.brave.com/t/minimizing-the-brave-browser-window-leaves-the-minimize-tooltop-balloon-up/2649
The tooltip that says "Minimize" is still stuck on the screen after minimizing the browser window.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10
- Brave Version (revision SHA):
0.15.1
- Steps to reproduce:
    1. Open a window
    2. Minimize it with a fast click, don´t wait for the tooltip to appear
    3. See that the tooltip still shows
    
- Actual result:
Tooltip is stuck on the screen
- Expected result:
Tooltip should fade away
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Will see later
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
![brave](https://cloud.githubusercontent.com/assets/25466657/25710940/01335bc2-30ee-11e7-9de8-986a23438a1c.gif)

**Comment by jonathansampson** [comment] 2017-05-19 00:25
+1 from https://gab.ai/UncleKennyTx/posts/7909336

**Comment by legendarynacar** [comment] 2017-05-21 11:01
I can confirm too. It is annoying. I can only prevent it with rightClick to top bar , selecting minimize. Or just dont minimze it and use alt+tab etc.

I hope you fix it soon.
Regards.

**Comment by jonathansampson** [comment] 2017-05-22 16:48
@legendarynacar If you allow the tooltip to fully appear before clicking _minimize_, it will go away. You just need to hover over the button for 1-2 seconds before clicking.

**Comment by legendarynacar** [comment] 2017-05-23 07:39
Yeah, it works as you said. But I am not used to wait. If I want to do something I just click and do. Why do I need to wait for it. No other programs has that problem. So it means they can fix it. I do not want to wait 1-2 for each time. Actually it is a lot of time if you imagine a workflow.

**Comment by jonathansampson** [comment] 2017-05-25 15:37
@legendarynacar We certainly aren't asking you to be okay with waiting; we will see to it that this issue is resolved in a future release. My advice was meant only as a way to handle this bug for the time being. I too minimize quickly, and often see that pesky tooltip linger.

**Comment by Foofy1** [comment] 2017-06-17 02:41
+1 
Wanted to add that I can avoid the bubble by minimizing via taskbar button.

**Comment by Liunkae** [comment] 2017-06-20 20:38
+1 from #9599

**Comment by bsclifton** [comment] 2017-07-11 23:44
Looks like this may be an upstream issue; for more info see https://github.com/electron/electron/issues/9943

It's reported in Chromium's tracker with https://bugs.chromium.org/p/chromium/issues/detail?id=724538

**Comment by eljuno** [comment] 2017-07-14 19:54
+1 [from community](https://community.brave.com/t/the-minimize-crouton-becomes-stuck-on-desktop-after-minimizing-browser-window/4750/)

**Comment by bsclifton** [comment] 2017-07-19 20:43
+1 from @bhuettmann via https://github.com/brave/browser-laptop/issues/10067 (minimize tooltip goes to the other monitor)

**Comment by Licenser** [comment] 2017-07-26 21:44
+1 from here too and cheers for a wonderful description of the bug that was easy to find before reporting it again ;)

**Comment by Jacalz** [comment] 2017-07-30 17:17
+1 from the community

**Comment by Jacalz** [comment] 2017-07-30 17:19
+1 [from the community](https://community.brave.com/t/minimizing-the-brave-browser-window-leaves-the-minimize-tooltop-balloon-up/2649/20?u=jacalz)

**Comment by Jacalz** [comment] 2017-07-30 17:20
+1 [from the community](https://community.brave.com/t/minimizing-the-brave-browser-window-leaves-the-minimize-tooltop-balloon-up/2649/19?u=jacalz)

**Comment by Jacalz** [comment] 2017-07-30 17:21
+1 [from the community](https://community.brave.com/t/minimizing-the-brave-browser-window-leaves-the-minimize-tooltop-balloon-up/2649/23?u=jacalz)

**Comment by Jacalz** [comment] 2017-07-30 17:21
+1 [from the community](https://community.brave.com/t/minimizing-the-brave-browser-window-leaves-the-minimize-tooltop-balloon-up/2649/24?u=jacalz)

**Comment by Jacalz** [comment] 2017-07-30 17:22
+1 [from the community](https://community.brave.com/t/minimizing-the-brave-browser-window-leaves-the-minimize-tooltop-balloon-up/2649/26?u=jacalz)

**Comment by Jacalz** [comment] 2017-07-30 17:23
+1 [from the community](https://community.brave.com/t/minimizing-the-brave-browser-window-leaves-the-minimize-tooltop-balloon-up/2649/27?u=jacalz)

**Comment by Jacalz** [comment] 2017-07-30 17:24
Sorry for the spam but I had forgot to +1 a lot of comments :sweat_smile:

**Comment by Jacalz** [comment] 2017-08-01 15:35
+1 from the community
https://community.brave.com/t/ux-disabling-tooltips-on-brave/5181

**Comment by bsclifton** [comment] 2017-08-01 23:26
Because the underlying issue is in Chromium, I put together a fix we can use until that is fixed. The fix is to simply remove the tooltip. Under the hood, there is still an [aria-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute) in the case that a screenreader is looking for information

Pull request is up here and (if approved) would be in our next release 😄 
https://github.com/brave/browser-laptop/pull/10243

**Closed** 2017-08-01 23:45 UTC
Labels: bug, OS/Windows, upstream
