### ISSUE TITLE
In address bar, some letters are not correctly written when writing.

### ISSUE THREAD

**Issue by Benstrange** [brave/browser-laptop#4963] opened 2016-10-19 20:39 UTC
**Did you search for similar issues before submitting this one?**
No
**Describe the issue you encountered:**
In address bar, some letters are not correctly written when writing.
**Expected behavior:**
See all letters :)
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10
- Brave Version:
0.12.5
- Steps to reproduce:
    1.Open Brave
    2.Click in address bar
    3.Type google drive => sometimes brave get google dive or googl drive, etc

- Screenshot if needed:

- Any related issues:

**Comment by diracdeltas** [comment] 2016-10-19 20:49
dupe of https://github.com/brave/browser-laptop/issues/4731

**Closed** 2016-10-19 21:02 UTC
Labels: duplicate
