### ISSUE TITLE
Change of language should prompt/restart 

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#2245] opened 2016-06-20 19:44 UTC
Changing the language requires a restart to take full effect. We should notify the user when they change it and prompt to restart the browser

**Comment by diracdeltas** [comment] 2016-06-20 23:42
there's a couple other settings (Flash, DNT) that require restart. Instead of just writing it in the pref description, we should show a notification bar to restart the browser.

**Comment by luixxiul** [comment] 2016-06-20 23:51
Dupe of #1705

**Closed by luixxiul** 2016-06-20 23:51 UTC
Labels: enhancement, l10n
