### ISSUE TITLE
regression: history entries cannot be deleted with Private Data options

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5199] opened 2016-10-27 18:38 UTC
**Describe the issue you encountered:** regression: history entries cannot be deleted with Private Data options. Though the toggle to delete the browsing history is enabled, the entries appear on autocomplete pulldown on the URL bar

**Expected behavior:** 
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.7 RC1
- Any related issues:

**Comment by bbondy** [comment] 2016-10-28 02:07
>  history entries cannot be deleted with Private Data options. 

What does that mean? How do you reproduce?

**Comment by bbondy** [comment] 2016-10-28 02:07
Moving to 0.12.8

**Comment by luixxiul** [comment] 2016-10-28 03:28
>>  history entries cannot be deleted with Private Data options. 
>
> What does that mean? How do you reproduce?

By enabling the option to delete "Browsing histories" on ``about:preferences#security``.

**Comment by bbondy** [comment] 2016-10-28 15:17
when you clear now or on shutdown?

**Comment by bbondy** [comment] 2016-10-31 20:51
@alexwykoff can you reproduce?

**Comment by bbondy** [comment] 2016-11-04 02:34
I tried with both the clear now and clear on shutdown options and url suggestions didn't happen anymore.

Please take a screenshot if you reproduce again, I suspect maybe a tab was left open so the url suggestion that came up was for the open tab in the open tabs section.  

I'm going to remove from 0.12.8 for now but please feel free to re-add if you have some specific steps to reproduce or can still repro.  If not maybe just close. Thanks.

**Comment by bsclifton** [comment] 2016-11-11 07:25
I have an upcoming PR which is going to fix several history related issues... This may be fixed, but since there are no steps to reproduce, I'm going to close the issue for now.  Please re-open if the upcoming PR does not fix the issue and include specific steps.  Thanks :smile:

**Closed by bsclifton** 2016-11-11 07:25 UTC
Labels: feature/history, regression

**Comment by bsclifton** [comment] 2016-11-11 08:46
Here's a link to the PR which may fix this issue https://github.com/brave/browser-laptop/pull/5559

If the issue persists after this is accepted and there are clear STR, let's reopen :smile:
