### ISSUE TITLE
BraveSetup-x64.msi not installing Brave on Windows

### ISSUE THREAD

**Issue by willy-b** [brave/browser-laptop#6484] opened 2016-12-31 01:25 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
On a Windows 10 VM, I went to Releases page for Brave browser-laptop repo (https://github.com/brave/browser-laptop/releases/tag/v0.13.0dev-Preview7)
and downloaded the Windows installer (BraveSetup-x64.msi) for Preview7.
After running the installer, I observed that Brave was not listed as an installed application.

**Expected behavior:**
After running the installer, Brave should be installed as an app, and visible in the "Ask me anything" start omnibox

**Platform (Win7, 8, 10? macOS? Linux distro?):**
Windows 10 Enterprise v1607 (evaluation)

**Brave Version (revision SHA):**
  tag: v0.13.0dev-Preview7
  rev: 0c7a64d
https://github.com/brave/browser-laptop/releases/tag/v0.13.0dev-Preview7

**Steps to reproduce:**
    1. On Windows 10 go to the Releases page for Brave browser-laptop repo: https://github.com/brave/browser-laptop/releases/tag/v0.13.0dev-Preview7
    2. Click `BraveSetup-x64.msi` and download the installer
    3. Run the installer
    4. Go to the Windows start omnibox at bottom left and type 'Brave'
    5. One should see Brave as an application (on my VM I only saw the files from a dev checkout done earlier, but not the application)

**Screenshot if needed:**
![brave-x64-msi-not-working](https://cloud.githubusercontent.com/assets/6969859/21575043/d8cf95e2-ceb4-11e6-97bf-cc24caa95043.gif)

**Comment by willy-b** [comment] 2016-12-31 02:03
`brave` is also not available from command line (`cmd`) -- pretty sure the `BraveSetup-x64.msi` is not installing Brave at all in Preview7. thanks

**Comment by bsclifton** [comment] 2016-12-31 09:48
Duplicate of https://github.com/brave/browser-laptop/issues/2948; we should probably remove MSI from the page until we have a chance to update documentation. I believe it's installable via `msiexec`

**Closed by bsclifton** 2016-12-31 09:48 UTC
