### ISSUE TITLE
Restored tab (CTRL+SHIFT+T) does not allow browsing its history

### ISSUE THREAD

**Issue by crysman** [brave/browser-laptop#13293] opened 2018-02-24 13:03 UTC
Restored tab (CTRL+SHIFT+T) does not allow browsing its history. I think it used to work before. It is certainly still working in both newest Firefox and Chromium.

Steps to reproduce:

1. open at least two tabs
2. browse something in the second one (follow at least two hyperlinks)
3. close the second one
4. CTRL+SHIFT+T
5. try to go back in history -> does not work
6. you may try this in Firefox and/or other browsers (it works)

Using 
Brave	0.20.42
V8	6.4.388.41
rev	096c7cb
Xubuntu 17.10

**Comment by btlechowski** [comment] 2018-02-24 13:49
Thank you for reporting the issue. This is a know bug.

Duplicate of #2702

**Closed by btlechowski** 2018-02-24 13:49 UTC
Labels: feature/history, feature/tab-page
