### ISSUE TITLE
Right click context menu appears twice

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#8872] opened 2017-05-15 12:49 UTC
- Did you search for similar issues before submitting this one?
Yes, but well githubs search is shit...
- Describe the issue you encountered:
https://community.brave.com/t/minimizing-the-brave-browser-window-leaves-the-minimize-tooltop-balloon-up/2649/21?u=jacalz
Reported from community that the right click context menu appears twice when opening a new tab!
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 and also macOS see comment down below
- Brave Version (revision SHA):
0.15.2
- Steps to reproduce:
    1.  Right click link
    2. Open in new tab
    3. The context menu pops up again 
    
- Actual result:
Context menu appears twice
- Expected result:
Context menu should be removed when clicking "open in new tab"  the first time
- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?

- Screenshot if needed:
![image](https://cdn-standard2.discourse.org/uploads/brave/optimized/2X/7/777dd091c1f82843a850cb67c126577e78754182_1_690x388.gif)
Will fill in more info from community when I get them 😉

**Comment by markwylde** [comment] 2017-05-17 08:36
Can confirm same is happening on my MacBookPro 
<img width="495" alt="os version" src="https://cloud.githubusercontent.com/assets/5929807/26145416/47c21c9a-3ae4-11e7-8d85-1d754af76012.png">

![screen demo of issue](https://cloud.githubusercontent.com/assets/5929807/26145438/4fbcfc9e-3ae4-11e7-8f38-a03ab0bb3ff3.gif)

**Comment by markwylde** [comment] 2017-05-17 08:42
However the issue does appear to be resolved in the latest **Dev Channel Beta v0.15.304dev**

The menu only appears once for the following version:
 
**Brave**: 0.15.304 
**rev**: b872523876e7e53f6e269b546d0eefce6fdacec6 
**Muon**: 3.0.103 
**libchromiumcontent**: 58.0.3029.96 
**V8**: 5.8.283.37 
**Node.js**: 7.9.0 
**Update Channel**: dev 
**os.platform**: darwin 
**os.release**: 16.5.0 
**os.arch**: x64

**Comment by Jacalz** [comment] 2017-05-17 09:59
Great, I can confirm since the context menu only appears once for me and always has 😝

**Comment by Jacalz** [comment] 2017-05-17 13:39
But the issue above is about cklicking open in new tab @markwylde :wink:

**Comment by luixxiul** [comment] 2017-05-28 16:34
I see the issue on http://live.cyclingnews.com/

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26530381/e52c4522-440e-11e7-9247-1b659d16ab6d.gif)

**Comment by luixxiul** [comment] 2017-05-28 16:34
Also I'm on Windows 10.

**Comment by Jacalz** [comment] 2017-05-28 17:34
This is about when you click open in new tab if I understood numpty right 😬 @luixxiul

**Comment by bsclifton** [comment] 2017-06-11 05:23
Closing this issue as I cannot reproduce on Windows or macOS. I believe it was fixed with the new async menu code (ex: https://github.com/brave/muon/pull/161)

**Closed by bsclifton** 2017-06-11 05:23 UTC
Labels: bug, feature/context-menu

**Comment by luixxiul** [comment] 2017-06-11 06:22
I cannot reproduce the issue on the page.
