### ISSUE TITLE
Unable to upload files on Uploaded.net

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4108] opened 2016-09-19 10:53 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Flash content on Uploaded.net doesn't load which blocks uploading file on the site

**Expected behavior:**
Flash content should run and user should be able to upload file on the site
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.1 Dev 
  Shields down
- Steps to reproduce:
  1. Login to Uploaded.net
  2. Click on the upload file icon or the File Upload link 
  3. Doesn't launch the open file browser window when either of them are clicked.
- Screenshot if needed:
  ![1](https://cloud.githubusercontent.com/assets/17010094/18629360/de795b84-7e5c-11e6-9ed0-839e77e112fe.gif)
- Any related issues:

cc: @diracdeltas

**Comment by decode-dev** [comment] 2016-09-19 12:21
I am able to login and upload a file. 
Seeing from the Image the site is loading in "http" rather than "https".

**Comment by Rainskies** [comment] 2018-04-17 21:32
Go to Chrome and type chrome://settings/content. Then go to flash and add site to allow, uploaded.net. That will fix it because the problem is it is not asking for Flash to work.

**Comment by zeffii** [comment] 2018-12-12 10:01
I experience the same issue when trying to upload an image into github issues

**Comment by bsclifton** [comment] 2019-01-03 19:43
Closing as `wontfix`- we should try this with the new version of Brave (https://brave.com/download)

@zeffii I believe you are using the new version of Brave (great!) and the issue you're having is captured with https://github.com/brave/brave-browser/issues/2034 (subscribe for updates!)

**Closed by bsclifton** 2019-01-03 19:43 UTC
Labels: plugin/flash, webcompat
