### ISSUE TITLE
Math operation with decimal point separator bug

### ISSUE THREAD

**Issue by mlambers** [brave/browser-laptop#15168] opened 2018-09-07 10:53 UTC
### Description
So basically if you type something in the URL bar like 2.3 + 2 isnt direct you into whatever search engine you're using. It still consider them as IP and produce URL error. Would like an improvement for this, so we dont have to use decimal comma like how the feature working at the moment.

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**
 2.3 + 2 (Using decimal point)
produce URL error

2,3 + 2 (Using decimal comma)
Working nice.

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by Liunkae** [comment] 2018-09-07 23:58
Looks like a duplicate of #3317. This problem is fixed in [brave-core](https://github.com/brave/brave-browser), which is supposed to be released in the next few months.

**Comment by bsclifton** [comment] 2018-09-08 06:05
Yup, it's a dupe - thanks for finding @Liunkae 😄

**Closed by bsclifton** 2018-09-08 06:05 UTC
