### ISSUE TITLE
Popup window not shown on Game-Debate.com

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3777] opened 2016-09-06 21:46 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Popup window not shown on Game-Debate.com

**Expected behavior:**
Popup window should be allowed to display the report. (Or provide notification that popup is blocked)
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.0 (Clean Install)
- Steps to reproduce:
  1. Visit can I run it on [Game-Debate.com ](http://www.game-debate.com/can-I-run/?EA)
  2. Select any game from any publisher, hardware details
  3. Click on Can I Run it? Popup window should be displayed with the analysis result 
  4. Popup window doesn't show neither notification of a blocked popup is shown.
- Screenshot if needed:
- Any related issues:
  #3143 #2677

**Comment by jonathansampson** [comment] 2016-09-21 04:34
There are some curiosities around the async opening of windows that are currently being investigated. I put together [a small page that details the behavior](https://jonathansampson.github.io/browser-tests/brave/async%20popup/index.html).

**Comment by bsclifton** [comment] 2017-08-14 17:39
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/3752

**Closed by bsclifton** 2017-08-14 17:39 UTC
Labels: webcompat
