### ISSUE TITLE
Black Screen when viewing Yahoo

### ISSUE THREAD

**Issue by LangQuest** [brave/browser-laptop#1761] opened 2016-05-14 16:41 UTC
I am using a Mac with OS 10.11.3 and the latest version of Brave.

Until Monday of last week, Yahoo appeared OK. But starting on Monday, when navigating to the Yahoo home page, the home page appears for about 2 or 3 seconds and then goes black. 

At the bottom left of the screen a web address appears (the background of the  URL is white and the text is black):

https://www.yahoo.com/finance/news/brave-browser-bites-hands-feed-193121076.html

If under the Bravery menu item I check Block Scripts and reload, the yahoo home screen appears, does not go black, but is otherwise unresponsive. That is, you can't scroll, click or do anything except hit the go back button.

All other websites that I visit work normally.

Any idea what is happening?

JIm

**Comment by bbondy** [comment] 2016-05-14 16:44
Are you using 0.9.6 f Brave?

**Comment by LangQuest** [comment] 2016-05-14 16:55
Hi,

Clicking "About Brave" shows 0.9.6.

When I check for updates it tells me there is no update.

Jim
=========================

**Comment by luixxiul** [comment] 2016-05-15 13:40
I cannot reproduce this on Windows 10. Would you please restart your Mac, try again, and tell us if you encounter the same issue? Thanks.

**Comment by LangQuest** [comment] 2016-05-15 15:52
I have tried this many times. Mac has been restarted over several days with always the same result. Also, yesterday I downloaded the Brave browser and reinstalled. All is well with other websites, but with Yahoo the screen goes black. 

I took a Screen shot and attached it to this message. Not much to see except black - 

<img width="2048" alt="screen shot 2016-05-15 at 8 47 07 am" src="https://cloud.githubusercontent.com/assets/19363531/15275211/f2dfe486-1a79-11e6-8c44-f755b4a33f01.png">

I love Brave and hope that this glitch can be solved. Thanks for your help.

Jim

**Comment by luixxiul** [comment] 2016-05-15 15:53
Thanks for the screenshot :-)

**Comment by LangQuest** [comment] 2016-05-15 16:44
I don't know if this is useful to you, but I activated Developer Tools and reloaded the Yahoo Home page. After the screen goes black, an error box appears with this message: "Debugging connection was closed. Reason: Render Process Gone. Reconnect when ready by reopening DevTools."

In the Console part of the debugging screen, the following appears (the word GET and the words net::ERR_BLOCKED_BY_CLIENTC are in red):

DARLA notice: 405
g-r-min.js:1 GET https://s.yimg.com/rq/darla/2-9-9/html/r-csc.html net::ERR_BLOCKED_BY_CLIENTC @ g-r-min.js:1h @ g-r-min.js:1i @ g-r-min.js:4h @ g-r-min.js:1re @ g-r-min.js:1r @ g-r-min.js:4n.fireCSC @ g-r-min.js:4j @ g-r-min.js:3ae @ g-r-min.js:3(anonymous function) @ (index):2607

g-r-min.js:1 GET https://s.yimg.com/rq/darla/2-9-9/html/r-sf.html net::ERR_BLOCKED_BY_CLIENT
==============================
Just to recap:
1] Brave was working perfectly with Yahoo until last week. 
2] Brave works perfectly with other web sites that I visit.
3] Yahoo works fine with both Safari and Firefox.

If there is some other test you would like me to run, please let know and I will try to run it.

Jim

**Comment by bbondy** [comment] 2016-05-15 21:45
The dev tools thing is fixed in 0.9.6

**Comment by LangQuest** [comment] 2016-05-16 15:57
I am using 0.9.6.  Here is the info form the About Brave Menu Selection:

Brave: 0.9.6
Electron: 0.37.8
libchromiumcontent: 50.0.2661.102
V8: 5.0.71.48
Node.js: 5.10.0
Update channel: dev

This software uses libraries from the FFmpeg project under the LGPLv2.1

**Comment by bridiver** [comment] 2016-05-19 23:00
I'm not able to replicate this. Please let us know if the problem persists for you in the 0.10 release. Thanks!

**Closed by bridiver** 2016-05-19 23:00 UTC
Labels: bug
