### ISSUE TITLE
Ledger table is populated twice making it overlap with broken favicons

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12818] opened 2018-01-24 06:58 UTC
### Description
Ledger table is populated twice making it overlap with broken favicons

### Steps to Reproduce
Unsure. Found it when launching the browser 

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/35318524-c26ea16e-0101-11e8-95bf-6116477a5c23.png)

**Expected result:**
Should not have duplicated entries overlapping on each other

**Reproduces how often:**
No idea

### Brave Version

**about:brave info:**

Brave | 0.19.141
-- | --
rev | 87c14cf
Muon | 4.7.3
libchromiumcontent | 64.0.3282.99
V8 | 6.4.388.29
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
Found on Release channel build not sure if it happens on the current release build

### Additional Information
cc: @bsclifton @NejcZdovc @bradleyrichter

**Comment by bsclifton** [comment] 2018-02-19 08:07
Since there is not enough info to reproduce and we have not seen this again, I'm going to close the issue. If it occurs again or we have more info, let's re-open 😄

**Closed by bsclifton** 2018-02-19 08:07 UTC
Labels: 0.19.x, bug, feature/ledger, needs-STR, needs-investigation
