### ISSUE TITLE
Brave icon looks too small on Windows

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#13093] opened 2018-02-10 21:54 UTC
Please see this reddit thread:
https://www.reddit.com/r/BATProject/comments/7whl3r/sorry_if_im_being_too_picky_but_for_such_an/

@jamesmudgett or @bradleyrichter could you assist?

**Comment by bradleyrichter** [comment] 2018-02-11 05:12
I’ll enlarge them in the 0.21.0 builds.

**Comment by bsclifton** [comment] 2018-03-13 21:02
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/13290; icons were updated 😄 👍

**Closed by bsclifton** 2018-03-13 21:02 UTC
