### ISSUE TITLE
Netflix Streaming Error 

### ISSUE THREAD

**Issue by rtloeffler** [brave/browser-laptop#10449] opened 2017-08-12 16:55 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Netflix Streaming Error 

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X: 10.11.6 (15G31) 64bit

- Brave Version (revision SHA):
Brave: 0.18.14

- Steps to reproduce:
    1. Enable Widevine
    2. Go to netflix
    3. Play any movie
    
- Actual result:
```Whoops, something went wrong...

Unexpected Error

There was an unexpected error. Please reload the page and try again.

Error Code: M7121-1331-P7
```

- Expected result:
Play the movie

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by skaeight** [comment] 2017-08-12 20:16
I'm seeing this as well.

I just tried Brave out today.  Did this work previously?  From what I can see searching around it did.

This is Netflix's page on the error:

https://help.netflix.com/en/node/61874?ba=GSButtonClick&q=Error%20Code%3A%20M7121-1331-P7

They're bascially saying that the browser doesn't appear to support HTML 5 playback.

**Comment by bsclifton** [comment] 2017-08-12 23:08
@rtloeffler @skaeight hi folks- do you all have the Widevine Plugin enabled? This is required... you should have been prompted to enable it (if not, maybe we have a bug on our side)

**Comment by rtloeffler** [comment] 2017-08-12 23:10
@bsclifton yes, it's enabled and installed. It prompted me.

**Comment by skaeight** [comment] 2017-08-13 00:44
Yes, I also have widevine enabled. It did prompt me properly.

**Comment by stephenkru** [comment] 2017-08-13 04:34
Getting the same error. Win10. 0.18.14. Disable, Enable wildvine does nothing to fix.

**Comment by bbondy** [comment] 2017-08-13 04:54
Reproduced, I'm in talks with Google It seems that there are no changes in Brave so I suspect something on their end.

**Comment by Zebrazilla** [comment] 2017-08-13 19:57
Can confirm. Win 7 with Widevine plugin enabled.

**Comment by eljuno** [comment] 2017-08-14 22:49
+1 from community https://community.brave.com/t/netflix-crashing-error-m7121-1331-p7-worked-before/5871?u=eljuno

**Comment by bbondy** [comment] 2017-08-15 14:46
No response on Monday, pinged again today.

**Comment by bbondy** [comment] 2017-08-16 20:16
Just to update everyone, after repeated emails I got this information about what broke us:

```
[1] Adding VMP (verified media path) support to the Widevine browser CDM - we need to discuss your Brave browser release process to get a better understanding first.
[2] Correct browser identification - Netflix has added VMP checks for browser platforms, it is insufficient to determine if a browser platform is reliable without VMP detection and unique browser identification (not allowed to masquerade as another browser).  Ultimately, the final call on browser support lies with Netflix.
```

Unfortunately this wasn't communicated to us directly and affected our in production build which wasn't changed for a couple weeks, and was working until the first report which was Friday. 

The soonest they will do a call with us is this coming Monday, where we'll learn what we need to add to regain support.   

Thank you everyone for your patience.

**Comment by bbondy** [comment] 2017-08-21 17:05
Another update,  I sent several emails for the past week asking for Google to confirm a time for the Monday meeting that they promised, but they responded back only today and it doesn't look like they will meet today.  We told them we'd make any time they wanted.

We did bisect and make an educated guess at what we needed to add, and we did that to produce a signature. But I think Google needs to have a public key for that, and Google won't confirm that to us when asked directly.  

Since Widevine is closed source and controlled by Google, we have no control beyond what we've done.

In the meantime Google has sent out an email telling partners about VMP (verified media path) which we learnt about the hard way.

This is a prime example for why free as in beer is not enough.

**Comment by bbondy** [comment] 2017-08-21 17:59
In the meantime you can help by contacting Netflix and asking them to disable VMP (verified media path) until Google releases information to smaller browser vendors like Brave.

https://help.netflix.com/en

**Comment by rtloeffler** [comment] 2017-08-21 18:12
@bbondy Thanks for the continued updates. Typical Google, It's why we all love the Brave Browser, keep up the great work!

**Comment by bbondy** [comment] 2017-08-21 18:51
No problem, updated the above with more detailed info.

**Comment by bbondy** [comment] 2017-08-21 20:35
We were able to escalate through @BrendanEich and had a call with the parties mentioned above.  They said the next step is to get Netflix to recognize as a supported browser since they are the only ones that use VMP today.  

Once they add us to the list of supported browsers, Google will release information about how to generate the `.sig` file which is needed.  They did confirm that we are not able to generate this file without extra help from their end.  They also asked that we enable Brave in the User-Agent for netflix.com so Netflix can identify us, which we'll do.

I asked explicitly why we needed to get Netflix's approval before they shared the `.sig` information but I was told only that because Netflix is the only one that supports it.  I asked that if Amazon Prime supports this later, will we wake up one morning and be broken again because we aren't on the supported browser list. They said no in that case it will just work.  I'm not certain why Netflix is the gate-keeper for the `.sig` Widevine information.  But getting Netflix to agree is the only way Google said they'll release the information to us for the `.sig` file.  

We should be getting an intro email with Google's contacts at Netflix today.

**Comment by darkdh** [comment] 2017-08-21 20:52
We will need to adapt this commit
https://chromium.googlesource.com/chromium/src/+/04848c804fa0df48dcd79a7dfb60ac1d227a1eb9%5E%21/#F0

For mac, we might be able to generate detached signature here
https://github.com/brave/browser-laptop/blob/master/tools/buildInstaller.js#L29
If we are using codesign, we must use `-D, --detached filename` to generate a separate signature for `widevinecdmadapter.plugin`

**Comment by bbondy** [comment] 2017-08-22 13:52
No response yet from Netflix for our replies to the Google-Netflix introduction email .

I'm still not sure why Google is using Netflix as a gatekeeper for the information about how to generate the sig file (i.e. probably how to whitelist our public key). When asked directly they just said because Netflix is the only one using it.  I'll ask again in the meantime while we wait for a response from Netflix.

**Comment by bbondy** [comment] 2017-08-22 14:01
From the August update on the Widevine website:

> For browser vendors, Widevine recommends adding support for VMP.

VMP is being portrayed on the Widevine site as something that they recommend browsers implement,  but we are not able to implement it because Widevine is intentionally withholding information about how to generate these .sig files which VMP requires (or equivalently whitelist our public key).

**Comment by eljuno** [comment] 2017-08-22 19:38
+1 from community https://community.brave.com/t/netflix-doesnt-work-anymore/6458?u=eljuno

**Comment by zentagonist** [comment] 2017-08-24 22:03
Update on this - after checking in with @bbondy it appears we will have the relevant information by tomorrow. Moving this issue into the 0.18.x hotfix release.

**Comment by Samizdata** [comment] 2017-08-30 05:47
Nice.  If we could get this, I could start uninstalling other browsers finally.

Cheers for all the hard work!

**Closed** 2017-08-30 23:55 UTC
Labels: webcompat

**Comment by Struisvogel93** [comment] 2017-08-31 21:33
Got the same issue, Netflix error: M7121-1331-P7. Google Widevine enabled. Here's my specs:

 
Brave: 0.18.24 
rev: 1853c35eeeac8ae271755f5aef71a06ebeef7e83 
Muon: 4.3.14 
libchromiumcontent: 60.0.3112.101 
V8: 6.0.286.54 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Comment by srirambv** [comment] 2017-09-04 02:17
Verified on 0.18.26. Works great on update

**Comment by skaeight** [comment] 2017-09-04 02:42
How do I download 0.18.26?

**Comment by srirambv** [comment] 2017-09-04 03:30
@skaeight you can enable preview builds from advance settings. Keep in mind it is still a preview build and not release build.
