### ISSUE TITLE
Bookmarks import from Firefox fails

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#12166] opened 2017-12-04 08:40 UTC
### Description

Bookmarks import from Firefox fails.

### Steps to Reproduce

  1. Install the latest firefox
  2. Export bookmarks
  3. Import them on Brave

**Actual result:**

Importing fails. 

**Expected result:**

It should not fail.

**Reproduces how often:**

Consistently.

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

### Additional Information

> https://bugs.chromium.org/p/chromium/issues/detail?id=638977#c28
> Chrome also suffers from the same problem now.

**Comment by darkdh** [comment] 2017-12-08 17:48
fix is under review on upstream 
https://chromium-review.googlesource.com/c/chromium/src/+/817435

**Comment by LaurenWags** [comment] 2018-01-29 20:11
Per discussion with @darkdh - reproducible by purging FF profile and creating bookmarks on FF 57 and above.

**Comment by srirambv** [comment] 2018-06-18 16:32
+1 from https://community.brave.com/t/cant-import-from-firefox-firefox-not-selectable/24024/2

**Comment by siavonen** [comment] 2018-08-20 18:41
Any progress on this?

**Comment by riastradh-brave** [comment] 2018-08-20 18:43
Unfortunately, if this is still an issue, we are probably not going to get to this until Brave 1.0.  Fortunately, it may already be fixed in Brave 1.0 if it has been fixed upstream in Chromium!

**Comment by siavonen** [comment] 2018-08-20 18:54
So the problem is from googles programming?

**Comment by bsclifton** [comment] 2018-08-21 05:46
@siavonen it looks like the issue that @darkdh linked to is still under review- the issue itself is still open:
https://bugs.chromium.org/p/chromium/issues/detail?id=638977

It's still in an experimental stage, but if you wanted to give it a shot, you can try our latest release of brave-core (0.54.0):
https://github.com/brave/brave-browser/releases

We are aiming to formally release brave-core (which has a UI based on Chromium) sometime in the next few months. Because that timeline is coming soon and we won't have the resources to fix this here in `browser-laptop`, I'm going to close this issue as `wontfix`.  

Please let us know if it works or fails with brave-core 😄 If it fails too, we'll want to open an issue here:
https://github.com/brave/brave-browser/issues

**Closed by bsclifton** 2018-08-21 05:46 UTC
Labels: feature/importer, upstream
