### ISSUE TITLE
"Unable to load file" on Google Sheets

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2343] opened 2016-06-30 10:06 UTC
**Describe the issue you encountered:** "Unable to load file" on Google Sheets

**Expected behavior:** work as expected

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.10.4

- Steps to reproduce:
    1. Go to https://docs.google.com/spreadsheets/
    2. Start a new spreadsheet
    3. Input any string in a cell
    4. Click somewhere on the sheet

- Screenshot if needed:
![](https://cloud.githubusercontent.com/assets/3362943/16484701/9ba84a46-3ef5-11e6-83c9-ae56c21adc1f.jpg)

- Any related issues:

**Comment by luixxiul** [comment] 2016-07-11 12:51
+1 from support

**Comment by Mordineus** [comment] 2016-07-21 18:50
Confirmed as still a bug on 0.11.1

**Comment by LucaFilipozzi** [comment] 2016-08-06 00:19
Confirmed as still a bug on 0.11.2

**Comment by ayumi** [comment] 2016-08-08 06:30
Can repro. Disabling fingerprinting protection fixes it for me.

**Comment by srirambv** [comment] 2016-08-10 16:29
Confirmed disabling FP protection fixes the issue on Windows 10 as well.

**Comment by syafiqmazli** [comment] 2016-08-22 03:12
I just do as Ayumi did on OS X. Disabling fingerprinting protection and able to loading spreadsheet on Brave 0.11.5 (Windows 10).

**Comment by bsclifton** [comment] 2016-08-22 15:12
Since the work-around is to disable fingerprint protection and this is a known issue, I'd like to close this issue in favor of https://github.com/brave/browser-laptop/issues/2965 (feel free to +1 the parent topic, so we can more visibly see the impact)

Please do reopen this issue if disabling fingerprint protection does NOT solve the issue. Thanks :smile:

**Closed by bsclifton** 2016-08-22 15:12 UTC
Labels: webcompat
