### ISSUE TITLE
Site not added to publisher list even after spending ~10 mins on the site

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11274] opened 2017-10-04 13:50 UTC
### Description
Site not added to publisher list even after spending ~10 mins on the site

### Steps to Reproduce

  1. Install 0.19.28
  2. Enable payments, 
  3. Change min time to 5sec (optional step, I did that)
  4. Visit news.google.com, click on any news entry (i had opened newsweekly)
  5. Browse the site for ~10 mins 
  6. Go back to payments, no entry for visited site.
  7. Open a new tab, visit a different site 
  8. After ~1 min reload preferences tab, entry shown for site visited in step 7

**Actual result:**
Site not added to publisher list even after spending ~10 mins on the site

**Expected result:**
Should add entry in ledger table after min criteria is met
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.19.28
-- | --
rev | 08781a5
Muon | 4.4.25
libchromiumcontent | 61.0.3163.100
V8 | 6.1.534.41
Node.js | 7.9.0
Update Channel | Beta
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**

No
### Additional Information

@kjozwiak was able to repro this on ledger refactor branch

**Comment by srirambv** [comment] 2017-10-04 17:08
This could be the problem. Site load time is shown as 0.00s no matter how many times the page is loaded. 
![image](https://user-images.githubusercontent.com/17010094/31189096-f5a14a58-a92e-11e7-9721-4389df30acd2.png)

**Comment by luixxiul** [comment] 2017-10-04 17:10
related? https://github.com/brave/browser-laptop/issues/4912

**Comment by srirambv** [comment] 2017-10-04 17:13
Not really i opened the site and it was all 0's. Reload showed up correct load time.

**Comment by kjozwiak** [comment] 2017-10-05 07:02
> @kjozwiak was able to repro this on ledger refactor branch

Yup, I've noticed this happen a few times while testing the refactoring branch but could never find any reduced STR... I tried debugging the issue with @NejcZdovc but couldn't find the cause. I usually reproduced the issue using the following work flow:

* launch Brave and enable payments via about:preferences#payments
* once enabled, quickly open a new tab and load cnn.com
* quickly open a new tab, load boardgamegeek.com
* quickly open a new tab, load shutupandsitdown.com and wait till it appears in the ledger table
* switch back to the tab with boardgamegeek.com opened and wait till it appears in the ledger
* switch back  to the tab with cnn.com and wait till it appears in the ledger

Using the above flow, sometimes the websites that were loaded and active for more than 2-3 minutes never appeared in the table.

**Comment by srirambv** [comment] 2017-10-05 09:51
New observation:
When navigating within the same domain even after page loads it shows 0.00s or 0.01s. 

- Visit YouTube and load any video 
- Check the load time in url could be 2.37s
- Click on suggested videos on the right hand side
- Page reloads and video starts
- Check load time, stays at 0.00s most times but could be 0.01s 

Verified on several sites and none of them gets added to the ledger table as it doesnt meet the 8sec criteria and even if it does get added is disabled and shows view as 0 and % as 0

cc: @brave/browser

**Comment by srirambv** [comment] 2017-10-06 11:53
Update:
Visit any site with embedded YT video
Start  the video and click on YouTube button to launch in new tab
Page loads and start streaming, but page load counter is not shown
Select URL and click outside, page load counter is still not shown
Opening a new video shows 0.01s

**Comment by luixxiul** [comment] 2017-10-06 14:58
Is that count on the URL bar actually the same one used for ledger calculation? I don't think so, as that count measures the period between the start and end of the loading of the page, not how long you stay on that page.  I'm not sure how this issue is related with the ledger.

**Comment by luixxiul** [comment] 2017-10-06 14:58
cc @mrose17

**Comment by NejcZdovc** [comment] 2017-10-06 15:12
load time is not connected to the visit time

**Comment by bsclifton** [comment] 2017-10-11 22:35
Moving to 0.19.x release 2

**Comment by NejcZdovc** [comment] 2017-10-12 14:29
changing priority to P3, because sites are not added correctly in a lot of scenarios

**Closed** 2017-10-23 19:02 UTC
Labels: bug, feature/ledger, PR/pending-review, priority/P3
