### ISSUE TITLE
Bookmark table is not full width

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#10474] opened 2017-08-14 11:51 UTC
**Describe the issue you encountered:**
Bookmark manager is not full width. Regressed with this PR #10265.

![image](https://user-images.githubusercontent.com/9574457/29270547-a872cff4-80f7-11e7-835e-c2cbee9c942d.png)

**Comment by luixxiul** [comment] 2017-08-14 11:52
duplicate of #10450

**Closed by luixxiul** 2017-08-14 11:52 UTC
Labels: bug, release/blocking
