### ISSUE TITLE
Video autoplay working without viewing tab

### ISSUE THREAD

**Issue by BXVIII** [brave/browser-laptop#13066] opened 2018-02-08 06:47 UTC
### Description
Minimizing application and re-opening makes the autoplay function work without viewing the tab. 

### Steps to Reproduce
**_Detailed method_**
  1. Open browser application  
  Find a default autoplay video (Youtube video)
  Clone the tab, keeping one pinned. 
  Pause both videos so they aren't playing 
  Open a new tab, remain on that tab. 
  Close application 
  
  2. Open application 
  Do not click on any of the tabs which have videos in it 
  Minimize application 
  Open application
  Pinned tab begins autoplaying
  
  3. Minimize application
  Open application
  Other video tab begins autoplaying

**_Quick method_**
1. Head over to Youtube.com 
2. Find a video middle click > creating new tab (using a mouse).  
Don't click on the new tab remain on current tab
3. Minimize application
Open application 
Video begins autoplaying without viewing the tab. 

**Actual result:**
GIF showing the problem | https://i.imgur.com/z6riHw0.gifv

**Expected result:**
Minimizing the application shouldn't autoplay non viewed tabs.

**Reproduces how often:**
100% | Always

### Brave Version
0.20.33

**about:brave info:**
V8	6.4.388.41
rev	820ba31
Muon	4.7.10
OS Release	10.0.16299
Update Channel	Release
OS Architecture	x64
OS Platform	Microsoft Windows
Node.js	7.9.0
Brave Sync	v1.4.2
libchromiumcontent	64.0.3282.140

**Reproducible on current live release:**
Yes

### Additional Information 
All settings for the  browser are on default as I only installed 1-3 hours ago. 
Hopefully should get what the problem is here. Cheers.

**Comment by eljuno** [comment] 2018-03-16 19:05
Dupe of #8749?

**Comment by bsclifton** [comment] 2018-08-13 20:46
@eljuno yep! 😄

**Closed by bsclifton** 2018-08-13 20:46 UTC
Labels: duplicate
