### ISSUE TITLE
autocomplete for root domain doesn't happen if it's bookmarked.

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#5049] opened 2016-10-22 03:52 UTC
1. Bookmark brianbondy.com (but you already had that done, I'm just being explicit here!)
2. Navigate around (Don't enjoy yourself too much, remember to get back to this issue eventually)
3. Close the brianbondy.com/* tabs
4. Try to go back to brianbondy.com.  

Since it orders bookmarks below history, and it excludes bookmarks from history, it is very hard to get back to the root domain. 

I think the fix here is to allow history items to also be bookmarks. The general rule for history is anything with a last access time defined.

**Comment by Sh1d0w** [comment] 2016-10-22 05:01
@bbondy Dupe of https://github.com/brave/browser-laptop/issues/5024 :)

**Comment by aekeus** [comment] 2016-10-24 20:16
Closing as duplicate

**Closed by aekeus** 2016-10-24 20:16 UTC
Labels: duplicate
