### ISSUE TITLE
Feature Request: Save JS Whitelist

### ISSUE THREAD

**Issue by illuzen** [brave/browser-laptop#14659] opened 2018-07-05 02:31 UTC
So I have JS turned off by default. One of my favorite features of Brave. Then I restart my computer and I have to recreate the whitelist every time. While this is probably a little more secure as accidental additions to the whitelist get removed pretty quickly, it also takes up a lot of my time. Could we make an opt-in persist-preferences-in-a-config-file-somewhere feature?

**Comment by eljuno** [comment] 2018-07-05 22:38
I believe this is what you're looking for #9307

**Comment by bsclifton** [comment] 2018-07-06 16:32
Thanks for the report, @illuzen - I'm going to close this as a duplicate of https://github.com/brave/browser-laptop/issues/9307

**Closed by bsclifton** 2018-07-06 16:32 UTC
