### ISSUE TITLE
specific web page does not load: https://riot.im/app/

### ISSUE THREAD

**Issue by danoctavian** [brave/browser-laptop#13653] opened 2018-03-29 17:20 UTC
### Description

This web page spins indefinitely, without loading. 
https://riot.im/app/

### Steps to Reproduce
Paste URL, in URL bar, press Enter.

  1.
  2.
  3.

**Actual result:**
Page spinner spins indefinitely.
**Expected result:**
Page loads.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Reproducible on current live release:**

**Comment by eljuno** [comment] 2018-03-29 20:44
Dupe of #10685?

**Comment by bsclifton** [comment] 2018-03-30 04:09
Definitely a duplicate- thanks for the report, @danoctavian 😄

**Closed by bsclifton** 2018-03-30 04:09 UTC
