### ISSUE TITLE
Nested bookmark folders should be shown within the browser window 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4892] opened 2016-10-18 12:36 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Too many nested bookmark folders gets hidden when it goes beyond the window

**Expected behavior:**
Nested bookmark folders should be shown within the browser window 

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.12.5 RC4

- Steps to reproduce:
    1. Create multiple nested bookmark folders
    2. Reduce the window size 
    3. Trying to navigate through the nested folder, doesn't show the folders which goes beyond the window

- Screenshot if needed:
Chrome vs Brave behavior
![image](https://cloud.githubusercontent.com/assets/17010094/19477650/ce7c0a1c-955c-11e6-84aa-832f52152546.png)

- Any related issues:
#1187

 Setting milestone as 1.0 for now

**Comment by bsclifton** [comment] 2016-10-18 16:52
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/4745

**Closed by bsclifton** 2016-10-18 16:52 UTC
Labels: design, feature/bookmarks

**Comment by bbondy** [comment] 2016-10-18 18:36
Pls remove milestone marker when closing without code, thx.
