### ISSUE TITLE
Feature request: Add Decentraleyes functionality by default 

### ISSUE THREAD

**Issue by androiduser9** [brave/browser-laptop#14624] opened 2018-07-01 12:04 UTC
Idea:

Just like Brave implements HTTPS Everywhere functionality, it would be interesting if it could implement by default Decentraleyes functionality, the latter is an extension that blocks requests for libraries from CDNs (think google libraries, cdnjs, ...) and serves them locally to prevent tracking by CDNs.

**Comment by androiduser9** [comment] 2018-07-01 12:07
Here's the extension's source code: https://git.synz.io/Synzvato/decentraleyes

**Comment by bsclifton** [comment] 2018-07-02 05:41
Thanks for the request, @androiduser9! I'm going to close this issue as a duplicate of https://github.com/brave/browser-laptop/issues/12836 (please subscribe to that issue for updates). Thanks 😄

**Closed by bsclifton** 2018-07-02 05:41 UTC
