### ISSUE TITLE
thumbnails cannot be removed from dashboard

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10576] opened 2017-08-18 03:52 UTC
**Describe the issue you encountered:**
Thumbnails cannot be removed from dashboard on a new tab. The pinned top sites remain there even if you click the remove button. Reported: https://community.brave.com/t/having-issues-with-new-tab-page/6116?u=suguru. The issue is reproduced for me.

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version (revision SHA): 0.18

- Steps to reproduce:
    1. Open Dashboard
    2. Click a remove button
    
- Actual result: The top site tile is not removed while the message is displayed that it is successfully removed.

- Expected result: It should be removed

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by Liunkae** [comment] 2017-08-18 05:49
Duplicate of #10411

**Comment by NejcZdovc** [comment] 2017-08-18 05:50
@Liunkae you beat me for a few seconds :smiley: I just needed to press enter :rofl:

**Closed** 2017-08-18 05:50 UTC
Labels: duplicate

**Comment by luixxiul** [comment] 2017-08-18 05:56
@NejcZdovc please don't remove the feature label as it makes extremely hard to find duplicates, thanks.

https://github.com/brave/browser-laptop/wiki/(WIP)-Triage-of-issues#how-to-addremove-labels
