### ISSUE TITLE
No image preview of uploaded photo on 500px.com

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2648] opened 2016-07-21 20:04 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
After uploading a photo(drag n drop/browse) in 500px there is no image preview before publishing it.

**Expected behavior:**
Should show image preview
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  0.11.1
- Steps to reproduce:
  1. Upload any photo on 500px
  2. After upload image preview should show in the publish photo frame
- Screenshot if needed: 
  Image preview shown in chrome
  ![500px](https://cloud.githubusercontent.com/assets/17010094/17036979/ae15d30a-4f86-11e6-9eb7-29364840eb8c.PNG)
- Any related issues:

**Comment by luixxiul** [comment] 2016-07-22 01:13
Is NoScript off there?

**Comment by srirambv** [comment] 2016-07-22 05:11
Block HTML Canvas was the culprit. I had enabled the option under shields. Now preview shows after the option is disabled. 

Suggestion: 
If there is content that is being blocked due to one of the settings, then the browser should alert which option is enabled that is blocking the content. This way user can manually turn it off.  Like an alert if the site requires scripts to work and user has enabled blocked scripts. Without alerts user will have no idea what's happening.
cc@bbondy

**Comment by bbondy** [comment] 2016-07-22 15:25
Possible dupe of https://github.com/brave/browser-laptop/issues/2626 ?
CC @diracdeltas

**Comment by diracdeltas** [comment] 2016-07-23 01:19
@srirambv did the bravery panel report fingerprinting blocked?

**Comment by srirambv** [comment] 2016-07-23 05:28
@diracdeltas No the bravery panel didnt report fingerprinting blocked. Surprisingly today when I checked with the Block HTML Canvas enabled in Shields and tried uploading a pic on the site, it did show the preview. 

![preview500px](https://cloud.githubusercontent.com/assets/17010094/17076005/976c0fde-509e-11e6-8e3a-661546545452.PNG)

**Comment by srirambv** [comment] 2017-01-11 16:39
Working as expected as of 0.12.15. Fingerprint block count shows up when an image is uploaded and doesn't show preview. Disabling Fingerprint protection does show the preview. 

Closing the issue.

**Closed** 2017-01-11 16:39 UTC
Labels: webcompat
