### ISSUE TITLE
Clicking on this link causes a crash on OS X, Windows 10

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1726] opened 2016-05-13 15:41 UTC
https://www.eventbrite.com/d/ca--los-angeles/fashion-shows/
Click the list of the first box.

**Comment by luixxiul** [comment] 2016-05-13 16:50
Confirmed on Windows 10.

**Comment by bridiver** [comment] 2016-05-31 01:12
appears to be related to the notification bar. If you close it before clicking the link everything works fine

**Comment by luixxiul** [comment] 2016-06-06 16:47
Not reproducible on 0.10.2 on Windows 10. Has this been fixed?

**Comment by bbondy** [comment] 2016-06-09 14:01
This still reproduces. It has to do with navigating while the permissions bar is open. You probably have a saved permission so you don't reproduce.

**Comment by luixxiul** [comment] 2016-06-09 14:08
Yes you are right. I cleared all permissions and clicked the link, and it caused a crash.

**Comment by bbondy** [comment] 2016-06-09 16:34
another example link: https://www.homedepot.ca/en/home/categories/appliances.html

**Comment by diracdeltas** [comment] 2016-06-14 23:03
i think this just happens if the webcontents are navigated while there is still a reference to the `session.setPermissionRequestHandler` callback. it goes away if the callback is called immediately in https://github.com/brave/browser-laptop/blob/master/app/filtering.js#L316 instead of async. 

this crash also happened with the `certificate-error` event callback at one point.

**Comment by bridiver** [comment] 2016-06-14 23:05
there are actually two issues related to this issue:
1. Notifications appear on all windows and tabs, not just the tab they apply to
2. There is no good way to clear the notifications for a particular tab
I'm working on fixing both

**Comment by diracdeltas** [comment] 2016-06-14 23:12
> 1. Notifications appear on all windows and tabs, not just the tab they apply to

having notifications at the app level was intentional. there's a couple reasons:
* having notifications appear above the tab bar instead of under makes them harder to spoof by the page.
* sometimes a background page requests some permission, and having them be app-level lets you approve/deny them without having to find the tab.
* permissions are for a given origin for the entire app, not just for a tab.

open to changing this but i think this is not what is causing the crash

**Comment by bridiver** [comment] 2016-06-14 23:21
they can still appear above the tab, but right now there is no good way to know which notifications can be dismissed because they are no longer relevant (navigated away or closed the tab). If a permission request comes from a tab it should only appear for that tab. If it comes from a background page then we can display it for the current tab as well, but I can't see any reason why it should appear on every window. It's not the direct cause of the crash, but the inability to automatically dismiss requests that are no longer relevant makes it difficult to fix the crash

**Comment by bridiver** [comment] 2016-06-14 23:23
going to try a quick fix for the crash using WeakMap and maybe we can come back to the notification location issue

**Comment by bridiver** [comment] 2016-06-14 23:38
no luck there unfortunately because the root of the issue is actually the reference in electron. The permission handler has several problems for us, but the main problem is that it expects one webcontents per process and also expects a new webcontents for each navigation. The problem could be fixed in Electron, but it would require a lot of refactoring and it will be a lot easier to just auto deny on tab navigation

**Comment by bridiver** [comment] 2016-06-14 23:39
I'm also not sure what would happen right now if you had two webcontents in the same renderer process if one or both of them had a permission request

**Comment by bridiver** [comment] 2016-06-14 23:49
I take that back, I might be able to fix Electron and keep things backwards compatible with upstream by replacing the map to the process id with a map to the render frame host id

**Comment by diracdeltas** [comment] 2016-06-15 00:00
the workaround i used before for `cert-error` was always deny the permission request immediately unless the user has made a persistent choice, then reload the page after the user has accepted.

**Comment by bridiver** [comment] 2016-06-15 01:25
turned out to be easier than I thought. Somehow I missed that the webcontents are available in the callback handler. I still think it's weird that the notifications show up on all windows and tabs, but I'll create a separate issue for that

**Closed** 2016-06-15 18:00 UTC
Labels: crash, verified
