### ISSUE TITLE
Share on Facebook tab should be closed if "cancel" button is pushed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2087] opened 2016-06-05 06:22 UTC
**Describe the issue you encountered:** Share on Facebook tab should be closed if "cancel" button is pushed.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.15.310

- Steps to reproduce:
    1. Select `Share on Facebook` via `File` and `Share`
    2. Click `Cancel` on the opened tab
    
- Actual result: The URL `https://www.facebook.com/dialog/return/close#_=_` is returned and the tab is not closed

- Expected result: The tab should be closed

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by bsclifton** [comment] 2018-08-07 05:50
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/13370

**Closed by bsclifton** 2018-08-07 05:50 UTC
Labels: feature/share, suggestion
