### ISSUE TITLE
cmd + l appears to be dropping input on urlbar

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7358] opened 2017-02-23 17:25 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
It has been reported by @BrendanEich that we're dropping input on the urlbar when a user selects the field via CMD+L

- Platform (Win7, 8, 10? macOS? Linux distro?):
Observed on OS X, but likely all.

- Brave Version (revision SHA):
0.13.4

- Steps to reproduce:
    1. Have an open tab.
    2. Use CMD+L to shift focus to urlbar.
    3. Rapidly type in some input.
    
- Actual result:
Keystrokes are being dropped.

- Expected result:
All keystrokes after the release of CMD+L should be captured.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by zentagonist** [comment] 2017-09-11 21:25
Unable to reproduce. Checked with @bsclifton and confirmed he's never been able to reproduce.Closing.

**Closed by zentagonist** 2017-09-11 21:25 UTC
Labels: bug, feature/URLbar, perf
