### ISSUE TITLE
Indicator for drag and drop of bookmarks in bookmarks toolbar

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#5958] opened 2016-12-01 04:35 UTC
**Did you search for similar issues before submitting this one?**
Yes.

**Expected behavior:**
There needs to be an indicator while dragging and dropping a bookmark in the bookmarks toolbar.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.12.10

- Steps to reproduce:
    1. Open Brave and show the bookmarks toolbar if necessary.
    2. If necessary, create at least two bookmarks.
    3. Try rearranging the bookmarks by dragging and dropping. Notice that there is little indication of where the bookmark will be relocated.

- Screenshot if needed:
Here is an example from Firefox:
![image](https://cloud.githubusercontent.com/assets/19424103/20781982/423668aa-b74d-11e6-9d48-f21296853a10.png)

- Any related issues:
#5589 (Drag and drop in the Bookmarks Manager)

**Comment by bsclifton** [comment] 2016-12-03 22:06
This would be a great one!  The bookmarks manager has a few visual indicators, like showing an open folder icon when dragged over a folder.  Would be great to see that vertical bar where it will be positioned if you let go too

**Comment by bbondy** [comment] 2016-12-08 14:53
It used to make a gap where it would be dropped but that seems to have regressed at some point. This method sounds fine to me.

**Comment by bsclifton** [comment] 2016-12-08 15:17
@bbondy that is correct (and is captured with https://github.com/brave/browser-laptop/issues/6033). I investigated and found where it broke, but did not find the root cause (yet)

**Comment by bsclifton** [comment] 2017-04-19 04:40
Closing as duplicate of https://github.com/brave/browser-laptop/issues/6245

**Closed by bsclifton** 2017-04-19 04:40 UTC
Labels: design, feature/bookmarks, misc/drag-and-drop
