### ISSUE TITLE
Ctrl + Click on facebook post links cause Brave to Crash(see screen shot)

### ISSUE THREAD

**Issue by Tombsmen** [brave/browser-laptop#411] opened 2016-01-29 04:24 UTC
If you Ctrl + Click on the link (see highlighted link in image) BRave immediately crashes eitehr with and error report or just gone.

![link](https://cloud.githubusercontent.com/assets/16950007/12667153/3554df5c-c605-11e5-8e4f-0fc74111c7e6.png)

**Comment by thepup** [comment] 2016-01-29 04:37
Could you put your system details? I'm running El Capitan and can't reproduce this issue.

**Comment by Tombsmen** [comment] 2016-01-29 04:43
Windows 10 Pro
Version 1511 (OS Build 10586.71)
Intel Core i5-4670K 3.4GHZ
32GB - Kingston Value Ram
Raid 0 - Samsung 850 SSD(2)
MSI - Z87-G45 Gaming (MS-7821)

Not sure what else you would like but feel free to let me know.

**Comment by bbondy** [comment] 2016-01-29 04:44
This will be the same as #412, so I'll close this one.

**Closed by bbondy** 2016-01-29 04:44 UTC
