### ISSUE TITLE
Menu Bar Re-Appears After Restart

### ISSUE THREAD

**Issue by branwerks** [brave/browser-laptop#8293] opened 2017-04-13 13:45 UTC
- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered: With Preferences > Hide the menu bar by default toggled on, the menu bar is showing and to hide it I must toggle off then on again. This does not survive a browser restart. After starting Brave again the menu bar is showing with Preferences > Hide the menu bar by default toggled on, and the above process must be used to hide the menu bar again.

- Platform (Win7, 8, 10? macOS? Linux distro?): Xubuntu 16.04.2/4.4.02-72-generic

- Brave Version (revision SHA): 0.14.1/3de60d5

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment] 2017-06-05 07:28
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/5086

**Closed by bsclifton** 2017-06-05 07:28 UTC
Labels: bug
