### ISSUE TITLE
Feature Request: Set as default browser.

### ISSUE THREAD

**Issue by Sweetie-Belle** [brave/browser-laptop#669] opened 2016-02-08 21:10 UTC
Title is self-explanatory.

Would be nice to be able to set brave as default browser without having to manually edit config.

**Comment by bbondy** [comment] 2016-02-08 21:53
Dupe of https://github.com/brave/browser-laptop/issues/429
This is already working on OSX but pending on Windows.

**Closed by bbondy** 2016-02-08 21:53 UTC

**Comment by mandarvaze** [comment] 2016-02-22 05:54
Am on OSX, Brave version 0.7.15
Can't see the option yet under preferences.
Did you mean "coding for OSX done" (But not yet released) ?

**Comment by bbondy** [comment] 2016-02-22 14:31
You can change the default browser in the system settings. We have an issue on file here:
https://github.com/brave/browser-laptop/issues/813 to get it into preferences.  So you're right that it's not in preferences yet.
