### ISSUE TITLE
Very slow start on macOS

### ISSUE THREAD

**Issue by jfgoncalves** [brave/browser-laptop#5677] opened 2016-11-16 08:40 UTC
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

Since the bitcoin wallet update, starting time went from 2 bounce in the dock to 5 to 6 bounces, even when disabled in the settings.

**Expected behavior:**

Still 2 bounces in the dock.

- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS El Capitan, 10.11.6, MacBook Air Mid-2011

- Brave Version:

Since the wallet update version (still an issue in 0.12.9).

**Comment by Liunkae** [comment] 2016-11-19 07:22
Duplicate of #3025 (improve startup time).

**Closed by Liunkae** 2016-11-19 07:22 UTC
