### ISSUE TITLE
LastPass doesn't load extension properly when choosing for first time

### ISSUE THREAD

**Issue by scot30** [brave/browser-laptop#3109] opened 2016-08-11 04:19 UTC
Right-clicking in the window used to have a LastPass item at the bottom of the menu that comes up, and that LastPass menu item is gone - so no way to access my LastPass Vault or manually select a password to enter if the password doesn't autofill.  I've also noticed that a message comes up at the top of the window asking if I want Brave to remember the password every time a password is entered on a site, even though I have LastPass selected as the password manager in the settings.  If this is a new site I want to save a password for, I get the question asking if I want Brave to save the password and I also get the question asking if I want to save it in LastPass.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS X 10.11.6

- Brave Version: 0.11.4

**Comment by bsclifton** [comment] 2016-08-11 05:58
@scot30 would you be able to change your password manager to something else... Then change it back to LastPass? Let me know if that changes anything. I tested quite a few scenarios, I wonder what happened. If it still does happen and you are open to sharing your session file, I can walk you through a secure way to get it to me so that I can dig deeper

Please let me know- thanks :smile:

**Comment by bsclifton** [comment] 2016-08-11 15:50
(@scot30 If you wanted to share your session file, you can shoot it over to me at `clifton@brave.com`)

**Comment by scot30** [comment] 2016-08-12 03:00
I switched to Brave as the password manager, and then switched back to LastPass.  That seems to have fixed it.  Thanks!!  😄

**Comment by luixxiul** [comment] 2016-08-12 03:10
IIRC I noticed the same issue. 1) select LastPass for the first time, 2) blank page, 3) select the default manager, 4) select LastPass, 5) settings page. So let's leave this open, thanks @scot30

**Comment by bsclifton** [comment] 2016-08-13 08:19
@luixxiul can you explain your steps in more detail?

I cleared my session to ensure everything is fresh and added console logs and tried to reproduce but was unable to.

**Comment by luixxiul** [comment] 2016-08-13 14:48
Will you move AppData\Roaming\brave to other place temporary and try again? It shall reproduce the error. Here is the screenshot:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17643829/52cacbb8-61b0-11e6-9de3-4737b87aed13.png)

cc: @bridiver

**Comment by bsclifton** [comment] 2016-08-13 22:38
@luixxiul interesting... on Mac, it works great. This appears to be Windows only. 

When session is empty and you choose LastPass, the blank window which immediately opens is:
`chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/tabDialog.html?dialog=createAccountSimple`

I don't see any errors in the console (content or electron dev tools).

When the change to active PW manager happens, it triggers the extension to load via a listener on the AppStore:
https://github.com/brave/browser-laptop/blob/master/app/extensions.js#L198

This does load in the sense that it tries to pull up the page. I wonder why that page does not load?

**Comment by bridiver** [comment] 2016-08-13 22:40
the actual loading of that page depends on messages that are sent between it and the extension background page. There may be some slight difference on Windows

**Comment by bridiver** [comment] 2016-08-13 22:43
personally I think it's a little fragile and I might even consider it a LastPass bug because the page also won't load in any browser if you try to navigate to it directly or if you reload it after it has loaded correctly, but we should make it work at least as well as it does on Chrome

**Comment by BCSWowbagger** [comment] 2016-08-18 18:18
This appears to be linked to #2936 (as well as #2916). Based on a report in #2916 , this is affecting at least one Macintosh computer.

**Comment by bsclifton** [comment] 2016-08-29 16:27
Closing this issue as a dupe of https://github.com/brave/browser-laptop/issues/2936

**Closed by bsclifton** 2016-08-29 16:27 UTC
Labels: info-needed, windows-only
