### ISSUE TITLE
Adblock Custom Filters Do Not Work

### ISSUE THREAD

**Issue by Jozer99** [brave/browser-laptop#12308] opened 2017-12-17 15:47 UTC
### Description
Adblock custom filters on about:adblock do not work.  This bug seems to have been reported and closed multiple times before but still exists.  

### Steps to Reproduce
Simple example:
1.  Go to website www.nytimes.com
2.  Verify that NY Times logo image is contained in div class "nyt-logo"
3.  Go to about:adblock and scroll to custom filters
4.  Create custom filter "##.nyt-logo"
5.  Refresh www.nytimes.com

**Actual result:**
The NY Times logo is still visible.

**Expected result:**
The NY Times logo should have disappeared from the NY Times page.  Note that this is just an example, I don't actually want to block the NY Times logo. Tested on Chrome with uBlock Origin and got the correct behavior.  

**Reproduces how often:**
100% of the custom filters I have tried have zero effect, including simple ones such as the example described above.  

### Brave Version

**about:brave info:**
Name | Version
-- | --
Brave | 0.19.116
rev | 139c117
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**

**Comment by Alino** [comment] 2018-02-08 00:20
I confirm this on Mac.

I want to block the annoying ads at the end of a youtube video by adding this rule

_www.youtube.com##.ytp-ce-element_

but it doesn't work

**Comment by Jozer99** [comment] 2018-02-16 13:34
Is this issue ever going to be addressed?  For a browser that advertises its privacy features, having a non-functional content blocker seems like a big deal.

**Comment by lembitk** [comment] 2018-03-14 23:58
Confirming this on Win 10 x64, Brave v0.21.18 (rev 580be78; current live release as of 15.03.2018).

### Description

Custom filters in [`about:adblock`](about:adblock) do not work.

### Steps to Reproduce

  1. Go to [Spotify web player](https://open.spotify.com/) with shields up.
      1. Click "Play" on any music playlist/collection.
      1. Verify that there will be no audio playback/streaming.
  1. Go to [`about:adblock`](about:adblock).
      1. Add `@@audio-fa.scdn.co` custom filter.

**Actual result:**

As the host `audio-fa.scdn.co` still gets blocked, audio playback/streaming is not possible with shields up.

**Expected result:**

The custom adblock filter `@@audio-fa.scdn.co` (and/or `@@scdn.co/audio`) should allow audio streaming from Spotify's CDN.

### Additional Information

  - Another open issue related to custom adblock filters: #6243.
  - Open issue related to Spotify audio playback: #4053.

As I also think this is a rather big deal, taking the liberty to /cc @lukemulks. Thanks.

**Comment by Alino** [comment] 2018-07-18 15:37
Why was this moved to Triage Backlog? I am afraid it will take years to fix this if this is not prioritised. There must be a way to add custom ad-block filters, especially now, when Brave native ad-block is not efficient enough and ignores many ads and keeps them displayed.
Please reconsider the priority for this issue, because even an ad-block chrome extension gives their users the opportunity to add custom filters. If an extension can do this, why a whole browser focused on ad-blocking can't ?

**Comment by notDavid** [comment] 2018-07-20 13:21
If this functionality doesn't work, please remove the custom filter from the about:adblock page.

This just wastes peoples time, trying to figure out why it isn't working...

**Comment by mreza73** [comment] 2018-07-25 15:43
Confirming this on mac os 10.13.5 brave 0.23.39
custom filer doesn't work

**Comment by mitchwagner** [comment] 2018-07-27 22:49
Custom element filters (###hot-network-question for Stack Exchange) do not seem to work for me. I'm using Brave 0.23.39, macOS 10.14 Beta

**Comment by bsclifton** [comment] 2018-10-01 03:06
Closing in favor of https://github.com/brave/brave-browser/issues/403

**Closed by bsclifton** 2018-10-01 03:06 UTC
Labels: feature/adblock
