### ISSUE TITLE
Shortcuts aren't working with non-English keyboard (macOS)

### ISSUE THREAD

**Issue by leshik** [brave/browser-laptop#15175] opened 2018-09-10 07:47 UTC
### Description
I'm on macOS and keyboard shortcuts (such as `Cmd+T`) are only working when the keyboard layout is English.

### Steps to Reproduce
1. Switch to non-English keyboard layout (e.g. Russian)
1. Press `Cmd+T`

**Actual result:**
Nothing happens.

**Expected result:**
New tab should be opened.

**Reproduces how often:**
Always.

### Brave Version
**about:brave info:**
Brave: 0.23.105 
V8: 6.8.275.24 
rev: 9a46f8f5cb22a9daf2af21989aed25911aa6f839 
Muon: 8.0.9 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

### Additional Information
Chrome and Firefox don't have this issue (well, they had in the past, but fixed it long time ago).

**Comment by eljuno** [comment] 2018-09-10 19:09
Duplicate of #11908

**Comment by leshik** [comment] 2018-09-11 01:48
@eljuno Oh thanks, no wonder I didn't notice it as that issue is closed (I assumed that not fixed issues should be open). Dev version (that is Chromium UI based) fixed the issue for me as well as history slowness.

**Comment by bsclifton** [comment] 2018-09-11 06:36
@leshik can you please try our developer channel release?
https://brave.com/download-dev

We're in the process of moving over to a new code-base, which is why we're closing issues that are still happening.  If you're still having the problem with the Dev release, I can help create an issue in that new repo 😄 👍

**Closed by bsclifton** 2018-09-11 06:36 UTC
Labels: duplicate

**Comment by leshik** [comment] 2018-09-11 06:43
I did this already (as I stated in my previous comment) and it works ok. The reason people keep posting is that issues like this one are closed. It's hard to think that the issue was closed without the fix released.
