### ISSUE TITLE
"TypeError: cb is not a function" on https://expired.badssl.com/

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#12107] opened 2017-11-27 08:48 UTC
## Test plan

https://github.com/brave/browser-laptop/pull/11998#issue-274449085

----

### Description

````
1911:2222:1127/034501.334208:ERROR:cert_verify_proc_nss.cc(922)] CERT_PKIXVerifyCert for expired.badssl.com failed err=-8181
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: cb is not a function
    at App.app.on (/usr/lib/brave/resources/app.asar/app/index.js:142:7)
    at emitMany (events.js:132:20)
    at App.emit (events.js:204:7)
````

### Steps to Reproduce

  1. Open https://expired.badssl.com/

**Actual result:**

See above.

**Expected result:**

**Reproduces how often:**

Consistently.

### Brave Version

**about:brave info:**

Brave: 0.19.101 
rev: 30c42b5435b9169b528226608973ddd22679ed59 
Muon: 4.5.18 
libchromiumcontent: 63.0.3239.40 
V8: 6.3.292 
Node.js: 7.9.0 
Update Channel: nightly 
OS Platform: Linux 
OS Release: 4.9.0-3-amd64 
OS Architecture: x64

**Reproducible on current live release:**

No.

**Comment by kjozwiak** [comment] 2017-12-11 04:41
I think this is the same issue I reported in #12231... Didn't notice this one as it was placed in the triage backlog.

**Comment by bsclifton** [comment] 2017-12-11 04:42
This is definitely a dupe of https://github.com/brave/browser-laptop/issues/12231.  Good catch 😄 👍

**Closed by bsclifton** 2017-12-11 04:42 UTC
Labels: 0.19.x, bug, cr63, QA/test-plan-specified, regression
