### ISSUE TITLE
Clicking "Unregister" on https://jsfiddle.net/LnwtLckc/5/ crashes the browser

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11172] opened 2017-09-27 05:34 UTC
### Description

Clicking "Unregister" on https://jsfiddle.net/LnwtLckc/5/ crashes the browser.

### Steps to Reproduce

1. Clear the browser's profile
1. Visit https://jsfiddle.net/LnwtLckc/5/
2. Click `Unregister`

**Actual result:**

The browser crashes

**Expected result:**

It should not crash

**Reproduces how often:** [What percentage of the time does it reproduce?]

Consistently

### Brave Version

**about:brave info:**

Brave: 0.19.20 
rev: d9566ab3cab788c5157a9d281de5201afe27e47e 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Linux 
OS Release: 4.9.0-3-amd64 
OS Architecture: x64

**Reproducible on current live release:**

**Comment by bsclifton** [comment] 2017-09-28 19:06
@luixxiul can you please try to reproduce this again? I can't seem to cause a crash.  This may have been fixed indirectly with https://github.com/brave/browser-laptop/pull/11185

**Comment by luixxiul** [comment] 2017-09-28 20:12
On 0.19.23 the issue can be still reproduced for me.

**Comment by luixxiul** [comment] 2017-10-03 11:47
The issue can be reproduced on 0.19.25. Here is a better STR:

1. Clear the browser's profile
1. Visit https://jsfiddle.net/LnwtLckc/5/
2. Click `Unregister`

The browser crashes.

Brave: 0.19.25 
rev: d4fd17a426fe6e19f1acc225fb64e46d80be2105 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Linux 
OS Release: 4.9.0-3-amd64 
OS Architecture: x64

**Comment by kjozwiak** [comment] 2017-10-05 06:10
Using v0.19.28 rev: 08781a596c1a0a461c8863692e4be51ebb3babf2, I went through each of the following platforms using the STR mentioned in https://github.com/brave/browser-laptop/issues/11172#issuecomment-333817860 and https://github.com/brave/browser-laptop/issues/11172#issue-260852055:

* macOS x64 - couldn't reproduce
* Win 10 x64 - couldn't reproduce
* Ubuntu 16.04 x64 - reproduced
* Ubuntu 17.04 x64 - reproduced

@bsclifton, looks like this is only happening under linux. I got a stack trace using `gdb` but it's not symbolized and I'm not really sure how to do that with Brave...

**Comment by bsclifton** [comment] 2017-10-30 08:40
@bbondy should we pull this into our next release?  I marked as P2 since it does cause a crash

**Comment by bbondy** [comment] 2017-10-31 03:05
if we have a fix but looks like it's already live for a while

**Comment by NejcZdovc** [comment] 2018-04-06 06:39
closing as I can't reproduce it anymore

**Closed by NejcZdovc** 2018-04-06 06:39 UTC
Labels: OS/unix-like/linux, bug, crash, feature/ledger, priority/P2
