### ISSUE TITLE
Duplicate publisher entries in Payments UI

### ISSUE THREAD

**Issue by carson-drake** [brave/browser-laptop#13939] opened 2018-04-25 17:26 UTC
### Description
There are some publishers that are showing up as duplicate entries within the payment ui in preferences. The stats for each entry differ which is what leads me to believe this is not a simple caching issue.

### Steps to Reproduce
This is a bug that I noticed which appeared over time. 

**Actual result:**
The instance I'm experiencing is with a youtube creator [Casey Neistat](https://www.youtube.com/user/caseyneistat/videos). When you click on the link in the UI it directs you to the same Youtube page. The only visible difference (other than the stats) is the publisher's favicon/thumbnail in the UI. 

**Expected result:**
Expected result is that the two entries would be one. Its confusing whether they are different or if I am going to be contributing double to the same creator.

**Reproduces how often:**
Not something I can undo or intentionally reproduce.

### Brave Version

 
Brave: 0.22.22 
V8: 6.5.254.41 
rev: 63033109963be0a995b3d1ed9723870beeb191c4 
Muon: 5.1.2 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**
Yes, Live

### Additional Information
The creator recently updated their youtube branding. Not sure if you guys automated the process of indexing YouTube creators, but the image updates may have caused a small duplicate bug.

**Comment by NejcZdovc** [comment] 2018-04-25 18:08
thank you for your report. I think this is dupe of #13875, but this is something that we will fix asap.

**Closed by NejcZdovc** 2018-04-25 18:08 UTC
