### ISSUE TITLE
Tab click and drag is too sensitive causing it to become its own window

### ISSUE THREAD

**Issue by virtualFudge** [brave/browser-laptop#14947] opened 2018-08-03 20:21 UTC
### Description

Sometimes I click on a tab to change over to it, and instead of selecting the tab, a new window is created for that tab because it thinks that I am dragging it out to create a new window even though the movement is minuscule.

### Steps to Reproduce

  1. Have some tabs open
  2. Click on a different tab with a slight motion 

**Actual result:**

The tab gets its own window.

**Expected result:**
The tab is selected

**Reproduces how often:**

It happens while I'm casually browsing about 1 out of 10 tab clicks.

### Brave Version

**about:brave info:**

version 0.23.73

**Reproducible on current live release:**

**Comment by eljuno** [comment] 2018-08-03 21:40
Duplicate of #9211

**Closed** 2018-08-03 21:53 UTC
