### ISSUE TITLE
No way to unmute tabs

### ISSUE THREAD

**Issue by TheCNixon** [brave/browser-laptop#11849] opened 2017-11-08 10:55 UTC
### Description

No way to unmute tabs. 

### Steps to Reproduce

  1. muted two tabs by right clicking
  2. clicking mute

**Actual result:**

there was no option to umute and if I clicked mute tab again it wouldn't unmute.

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

0.20.5 on Windows 10

**Reproducible on current live release:**

**Comment by luixxiul** [comment] 2017-11-08 11:12
@TheCNixon Thanks for the bug report. From next time, please use the default template to make it possible to troubleshoot 😄 Thanks! 👍

**Comment by hferreiro** [comment] 2017-12-21 10:38
This is a duplicate of #10545.

**Comment by bsclifton** [comment] 2017-12-21 16:51
Great catch, thanks @hferreiro ! 😄

**Closed by bsclifton** 2017-12-21 16:51 UTC
Labels: 0.20.x, bug, feature/tabsbar
