### ISSUE TITLE
Brave crashes when clicking on Disqus verification link in gmail

### ISSUE THREAD

**Issue by FrancisTurner** [brave/browser-laptop#460] opened 2016-01-30 04:28 UTC
Using windows version downloaded yesterday

Steps to reproduce 
1) sign up to disqus.com using a gmail address that has not been used at disqus before
2) make comment somewhere that uses Disqus and force sending of verification email (this step may be omitted if Disqus sends the email automatically, it didn't for me)
3) when you have the disqus confirmation email click on the link
4) Watch brave crash. No errors reported, just gone from 

Note 
Copying the link and pasting it manually into a new blank tab worked fine.

The HTML part of the email (which was what was displayed in gmail) looks like this:

Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head xmlns="http://www.w3.org/1999/xhtml">
<meta name="viewport" content="width=device-width" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>

<style type="text/css">

    /* -------------------------------------
        CSS TO BE LEFT IN THE HEADER
        FOR CLIENTS THAT SUPPORT IT
    ------------------------------------- */

    a:hover,
    a:hover span {
        color: #1188d2!important;
    }

    .button-cta:hover {
        color: #ffffff!important;
        background-color: #1188d2!important;
    }

    .button-cta:hover span {
        color: #ffffff!important;
    }

    /* -------------------------------------
        CLIENT-SPECIFIC HACKS
    ------------------------------------- */

    /*  OUTLOOK
        - Override Outlook's embedded padding issue
        - Fix Outlook's full-width background issue
    */

    #outlook a {
        padding: 0;
    }
    body {
        width: 100% !important;
    }
    .ReadMsgBody {
        width: 100%;
    }
    .ExternalClass {
        width: 100%;
        display:block !important;
    }

    /* -------------------------------------
        PHONE-SIZED DEVICES
    ------------------------------------- */

    @media only screen and (max-device-width: 480px) {
        html {
                -webkit-text-size-adjust: 100%;
            }
            .content {
                width: 100%;
            }
            table {
                border-collapse: collapse;
            }
            h2.headline {
                font-weight: 700;
                font-size: 20px!important;
                margin-bottom: 5px;
            }
            .button-cta {
                display: block!important;
                padding: 0!important;
            }
            div.header {
                padding-top: 20px;
            }
            div.footer {
                padding-bottom: 20px;
            }
        }
    }

</style>

<style type="text/css">
        @media only screen and (max-device-width: 480px) {
            .next-steps td {
                display: block;
                width: 100%;
                padding-bottom: 10px;
            }

        }
    </style>
</head>
<body bgcolor="#FFFFFF" style='-webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100%; height: 100%; margin: 0; padding: 0; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif'>
<span class="preheader" style="color: white; font-size: 1px; display: none; mso-hide: all"></span>

<table class="head-wrap" style="border-collapse: collapse; width: 100%">
<tr style="border-collapse: collapse">
<td style='border-collapse: collapse; color: #353a3d; font-size: 14px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif'></td>
<td class="header container" style='border-collapse: collapse; color: #353a3d; font-size: 14px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; display: block; max-width: 640px; margin: 0 auto; clear: both'>

<div class="content header" style="padding-left: 10px; padding-right: 10px; max-width: 640px; margin: 0 auto; display: block; padding-bottom: 0">
<table style="border-collapse: collapse; width: 100%">
<tr style="border-collapse: collapse">
<td style='border-collapse: collapse; color: #353a3d; font-size: 14px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; vertical-align: middle'>
<a href="https://disqus.com/home/?utm_medium=email&amp;utm_content=logo" class="logo" style="color: #49B3F5; text-decoration: none"><img src="http://a.disquscdn.com/1454013735/images/email/logo.gif" alt="Disqus" width="83" height="18" style="height: auto; outline: none; text-decoration: none; display: block; max-width: 100%; border: none" /></a>
</td>
<td align="right" style='border-collapse: collapse; color: #353a3d; font-size: 14px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; vertical-align: middle'>
<a href="https://disqus.com/home/settings/email/?utm_medium=email" class="settings-link small" style="color: #849097; text-decoration: none; font-size: 85%; font-weight: 500">
<img src="http://a.disquscdn.com/1454013735/images/email/icon-gear.gif" width="12" height="13" style="height: auto; outline: none; text-decoration: none; display: inline-block; max-width: 100%; border: none; margin-bottom: 0; vertical-align: -2px" />
                                    &nbsp;Settings
                                </a>
</td>
<td align="right" width="64" style='border-collapse: collapse; color: #353a3d; font-size: 14px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; vertical-align: middle'>
<a href="https://disqus.com/home/account/?utm_medium=email" class="settings-avatar" style="color: #49B3F5; text-decoration: none">
<img class="avatar" src="http://a.disquscdn.com/uploads/users/19415/4571/avatar92.jpg?1454126452" title="My account" width="24" height="24" style="height: auto; outline: none; text-decoration: none; display: block; max-width: 100%; border: none; border-radius: 2px" />
</a>
</td>
</tr>
<tr style="border-collapse: collapse">
<td colspan="3" class="spacer-30" style='border-collapse: collapse; color: #353a3d; font-size: 14px; font-weight: 400; word-wrap: break-word; line-height: 0; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; vertical-align: middle; padding-bottom: 30px; overflow: hidden'>&nbsp;</td>
</tr>
</table>
</div>
</td>
<td style='border-collapse: collapse; color: #353a3d; font-size: 14px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif'></td>
</tr>
</table>

<table class="body-wrap" style="border-collapse: collapse; width: 100%">
<tr style="border-collapse: collapse">
<td style='border-collapse: collapse; color: #353a3d; font-size: 14px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif'></td>
<td class="container" style='border-collapse: collapse; color: #353a3d; font-size: 14px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; display: block; max-width: 640px; margin: 0 auto; clear: both'>
<img src="https://referrer.disqus.com/juggler/event.gif?category=email&amp;impression=0e314c06-c706-11e5-9217-002590f30436&amp;type=welcome.verify&amp;event=email&amp;behavior=open" alt="" width="1" height="1" style="height: auto; outline: none; text-decoration: none; display: block; max-width: 100%" />

<div class="content marketing-content" style="padding-left: 10px; padding-right: 10px; max-width: 640px; margin: 0 auto; display: block">
<table style="border-collapse: collapse; width: 100%">
<tr style="border-collapse: collapse">
<td style='border-collapse: collapse; color: #353a3d; font-size: 16px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; margin-top: 0; margin-bottom: 5px'>
<div class="marketing-cta" style="text-align: center; padding-top: 10px; padding-left: 10%; padding-bottom: 10px; padding-right: 10%">
<h2 style='font-weight: 500; font-size: 24px; margin-top: 0; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; line-height: 1.4; letter-spacing: -0.045em; color: #5a6267; margin-bottom: 5px; color: #555;'>Welcome to Disqus, <strong>Francis Turner!</strong></h2>
</div>
</td>
</tr>
<tr style="border-collapse: collapse">
<td class="divider-2px" style='border-collapse: collapse; color: #353a3d; font-size: 16px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; padding-top: 30px; padding-bottom: 30px; margin-top: 0; margin-bottom: 5px'>
<hr style="border: none; height: 2px; overflow: hidden; background: #e4e9ec; margin: 0" />
</td>
</tr>
<tr style="border-collapse: collapse">
<td style='border-collapse: collapse; color: #353a3d; font-size: 16px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; margin-top: 0; margin-bottom: 5px'>
<div class="marketing-cta" style="text-align: center; padding-top: 10px; padding-left: 10%; padding-bottom: 10px; padding-right: 10%">
<p style='margin-bottom: 5px; color: #353a3d; font-size: 16px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; margin-top: 0'><a href="http://disq.us/url?url=http%3A%2F%2Fdisqus.com%2Fverify%2F%3Flang%3Den%26token%3DuKzCktjQyoee0bXLbTd9PiYhDWFIaj5f%26user%3D194154571%3A7yU7fgMO9I-ZgcJMB9qLsA8nvhQ&amp;impression=0e314c06-c706-11e5-9217-002590f30436&amp;type=welcome.verify&amp;event=email&amp;behavior=click" class="button-cta" style="color: #fff; text-decoration: none; font-weight: 700; background-color: #4bb3f4; font-size: 18px; padding-top: 8px; padding-left: 16px; padding-bottom: 8px; padding-right: 16px; border-radius: 3px; line-height: 1.5em; display: block; margin-left: auto; margin-right: auto"><span style="color: #fff; font-weight: normal;">Verify &lsquo;</span>REDACTED@gmail.com<span style="color: #fff; font-weight: normal;">&rsquo;</span></a></p>
<br />
</div>
</td>
</tr>
<tr style="border-collapse: collapse">
<td class="centered-cell" style='border-collapse: collapse; color: #353a3d; font-size: 16px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; text-align: center; width: inherit; display: block; margin-top: 0; margin-bottom: 5px'>
<h3 style='font-weight: 300; font-size: 18px; margin-top: 0; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; line-height: 1.4; letter-spacing: -0.045em; color: #5a6267; margin-bottom: 5px'><strong style="color: #333;">Why verify?</strong></h3>
<p style='margin-bottom: 5px; color: #353a3d; font-size: 16px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; margin-top: 0'>Many sites using Disqus require a verified email for commenting to prevent spam. Verifying lets you join discussions quickly and easily.</p>
</td>
</tr>
<tr style="border-collapse: collapse">
<td class="divider-2px" style='border-collapse: collapse; color: #353a3d; font-size: 16px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; padding-top: 30px; padding-bottom: 30px; margin-top: 0; margin-bottom: 5px'>
<hr style="border: none; height: 2px; overflow: hidden; background: #e4e9ec; margin: 0" />
</td>
</tr>
<tr style="border-collapse: collapse">
<td style='border-collapse: collapse; color: #353a3d; font-size: 16px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; margin-top: 0; margin-bottom: 5px'>
<div class="broken-button" style="font-size: 13px; word-break: break-all">
                    Button not working? Paste this link into your browser:<br />
<a href="http://disq.us/url?url=http%3A%2F%2Fdisqus.com%2Fverify%2F%3Flang%3Den%26token%3DuKzCktjQyoee0bXLbTd9PiYhDWFIaj5f%26user%3D194154571%3A7yU7fgMO9I-ZgcJMB9qLsA8nvhQ&amp;impression=0e314c06-c706-11e5-9217-002590f30436&amp;type=welcome.verify&amp;event=email&amp;behavior=click" style="color: #49B3F5; text-decoration: none; font-size: 80%;">http://disq.us/url?url=http%3A%2F%2Fdisqus.com%2Fverify%2F%3Flang%3Den%26token%3DuKzCktjQyoee0bXLbTd9PiYhDWFIaj5f%26user%3D194154571%3A7yU7fgMO9I-ZgcJMB9qLsA8nvhQ&amp;impression=0e314c06-c706-11e5-9217-002590f30436&amp;type=welcome.verify&amp;event=email&amp;behavior=click</a>
</div>
</td>
</tr>
<tr style="border-collapse: collapse">
<td style='border-collapse: collapse; color: #353a3d; font-size: 16px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; margin-top: 0; margin-bottom: 5px'>
<br />
<p style='margin-bottom: 5px; color: #353a3d; font-size: 16px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; margin-top: 0'>Thanks,<br />
                The Disqus team</p>
</td>
</tr>
<tr style="border-collapse: collapse">
<td class="divider-2px" style='border-collapse: collapse; color: #353a3d; font-size: 16px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; padding-top: 30px; padding-bottom: 30px; margin-top: 0; margin-bottom: 5px'>
<hr style="border: none; height: 2px; overflow: hidden; background: #e4e9ec; margin: 0" />
</td>
</tr>
<tr style="border-collapse: collapse">
<td style='border-collapse: collapse; color: #353a3d; font-size: 16px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; margin-top: 0; margin-bottom: 5px'>
<table class="next-steps" style="border-collapse: collapse; width: 100%">
<tr style="border-collapse: collapse">
<td width="50%" valign="top" style='border-collapse: collapse; color: #353a3d; font-size: 16px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; margin-top: 0; margin-bottom: 5px'>
<h4 style='font-weight: 600; font-size: 14px; margin-top: 0; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; line-height: 1.4; letter-spacing: -0.045em; color: #5a6267; margin-bottom: 5px'>Need Help?</h4>
<p style='margin-bottom: 5px; color: #353a3d; font-size: 16px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; display: block; padding-right: 10px; margin-top: 0'><span style="font-size: 13px">Search for answers in our <a href="https://help.disqus.com" style="color: #49B3F5; text-decoration: none">knowledge base</a>, or contact us through our <a href="https://disqus.com/support/?article=verify" style="color: #49B3F5; text-decoration: none">support form</a>. We're here to help.</span></p>
</td>
<td width="50%" valign="top" style='border-collapse: collapse; color: #353a3d; font-size: 16px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; margin-top: 0; margin-bottom: 5px'>
<h4 style='font-weight: 600; font-size: 14px; margin-top: 0; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; line-height: 1.4; letter-spacing: -0.045em; color: #5a6267; margin-bottom: 5px'>Install Disqus</h4>
<p style='margin-bottom: 5px; color: #353a3d; font-size: 16px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; display: block; padding-right: 10px; margin-top: 0'><span style="font-size: 13px">To add Disqus commenting onto your site, visit <a href="https://disqus.com/admin/create" style="color: #49B3F5; text-decoration: none">https://disqus.com/admin/create</a></span></p>
</td>
</tr>
</table>
</td>
</tr>
</table>
</div>
</td>
<td style='border-collapse: collapse; color: #353a3d; font-size: 14px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif'></td>
</tr>
</table>

<table class="footer-wrap" style="border-collapse: collapse; width: 100%">
<tr style="border-collapse: collapse">
<td style='border-collapse: collapse; color: #353a3d; font-size: 14px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif'></td>
<td class="container" style='border-collapse: collapse; color: #353a3d; font-size: 14px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; display: block; max-width: 640px; margin: 0 auto; clear: both'>

<div class="content footer" style="padding-left: 10px; padding-right: 10px; max-width: 640px; margin: 0 auto; display: block">
<table style="border-collapse: collapse; width: 100%">
<tr style="border-collapse: collapse">
<td style='border-collapse: collapse; color: #353a3d; font-size: 14px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif'>
</td>
</tr>
<tr style="border-collapse: collapse">
<td align="right" style='border-collapse: collapse; color: #353a3d; font-size: 14px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif'>
<a href="https://disqus.com/home/account/?utm_medium=email" style="color: #353a3d; text-decoration: none"><img src="http://a.disquscdn.com/1454013735/images/email/logo-gray.gif" alt="Disqus" width="83" height="18" style="height: auto; outline: none; text-decoration: none; display: block; max-width: 100%; border: none" /></a>
</td>
</tr>
</table>
</div>
</td>
<td style='border-collapse: collapse; color: #353a3d; font-size: 14px; font-weight: 400; word-wrap: break-word; line-height: 1.4; font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif'></td>
</tr>
</table>

</body>
</html>

**Comment by bbondy** [comment] 2016-01-31 03:02
Possible dupe of #412

**Comment by FrancisTurner** [comment] 2016-01-31 06:40
Almost certainly related. But note there is no CTRL-Clicking

**Comment by bridiver** [comment] 2016-01-31 16:41
Not a dupe. This is still broken with https://github.com/brave/electron/pull/7

**Closed** 2016-01-31 19:16 UTC
