### ISSUE TITLE
MetaMask 4.6.1 Popup Can't Load

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#14122] opened 2018-05-14 20:22 UTC
### Description
The MetaMask 4.6.1 popup cannot finish loading. It appears to be stuck in some type of loop, which pertains to the popup window size.

![metamask-bug](https://user-images.githubusercontent.com/815158/40021512-ae03d00c-578a-11e8-8e41-e1c72a28f93b.gif)

### Steps to Reproduce
1. Load MetaMask 4.6.1
2. Click the extension's browser button

**Actual result:**
Popup is unusable.

**Expected result:**
Usable popup is presented.

**Reproduces how often:**
Always

### Brave Version
0.22.711

**about:brave info:**
``` 
Brave: 0.22.711 
V8: 6.6.346.26 
rev: 31d6bccb220485dc44f0ce0c65ed797f0160c8a7 
Muon: 6.0.9 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.139
```

**Reproducible on current live release:**
N/A

### Additional Information
MetaMask 4.3 did not have this issue.

**Comment by jonathansampson** [comment] 2018-05-17 17:35
From another channel, the issue is reportedly caused by a #8326. The MetaMask team is going to add a feature-test to ensure this API exists before making a call. That being said, we should explore implementation sooner rather than later.

**Comment by kjozwiak** [comment] 2018-05-18 17:52
We've received +1 from the [community](https://www.reddit.com/r/brave_browser/comments/8k2naw/metamask_window_is_blank_and_flickering/) regarding this issue on MM 4.3.0.

**Comment by jonathansampson** [comment] 2018-05-28 22:28
+1 from [another user](https://twitter.com/JoshBlakeslee/status/1001224425960701952) of 4.3.0.

**Comment by eljuno** [comment] 2018-06-05 18:33
+1 from Twitter with version 4.3.0 https://twitter.com/EkpedemeJohn/status/1003985607599775744

**Comment by euricanti** [comment] 2018-06-06 01:03
I am experiencing it myself. Even reinstalled Brave but nothing happened. Version 4.3.0 but, can't find how to upgrade the version. It happened that on Web3 websited did loaded the address as locked.  Hopefully it can be fixed. Is a bummer. 

Just letting know that this happened to me.

**Comment by GeetaSarvadnya** [comment] 2018-06-07 16:12
Steps to reproduce:
1. Enable MetaMask extension 4.3.0
2. Click on Metamask icon 

Actual: Pop up is shaking and its not stable.
![metamask issue](https://user-images.githubusercontent.com/38657976/41112125-b5497e38-6a9b-11e8-9ecc-db836b470262.gif)

**Comment by eljuno** [comment] 2018-07-01 18:56
+1 from community https://community.brave.com/t/odd-glitch-cant-get-my-metamask-extension-to-work/26748?u=eljuno

**Comment by bsclifton** [comment] 2018-07-23 18:30
Fixed with https://github.com/brave/browser-laptop/pull/14788

Closing as a duplicate of https://github.com/brave/browser-laptop/issues/13633

**Closed by bsclifton** 2018-07-23 18:30 UTC
Labels: bug, feature/extensions, priority/P3
