### ISSUE TITLE
Pocket and LastPass home page aren't loaded after logging into account

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9117] opened 2017-05-29 08:36 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Extension home page doens't load after logging into account

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.16.0
rev	be76cd3
Muon	3.2.101

- Steps to reproduce:
    1. Clean install 0.16.0
    2. Enable Pocket/Lastpass, wait for the login page to load in a new tab
    3. Login to account, page keeps showing loading but login is successful on widget
    
- Actual result:
Extension home page doens't load after logging into account

- Expected result:
Should load the landing page after successful login

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/26542340/72322c74-4451-11e7-89a4-26706a8756d3.png)

- Any related issues:
cc: @kevinlawler @jonathansampson

**Comment by bsclifton** [comment] 2017-06-07 00:15
Able to reproduce. I don't see anything logged to stdout, the electron devtools console, or the regular dev console.  

Quitting and relaunching seems to fix the problem (although, it's not obviously not a great solution)

**Comment by bbondy** [comment] 2017-06-08 13:12
It doesn't look like we're getting a fix for this release so moving to 0.17.x

**Comment by bsclifton** [comment] 2017-07-25 16:19
@jonathansampson this should work now, right? (is this related to the close API?)
cc: @kevinlawler

**Comment by jonathansampson** [comment] 2017-07-25 16:30
@bsclifton Yes, though the title is a little misleading, I think this is a dupe of the close API.

**Comment by jonathansampson** [comment] 2017-07-25 16:31
Closing as dupe of #4687

**Closed by jonathansampson** 2017-07-25 16:31 UTC
Labels: bug, feature/extensions, feature/extensions/LastPass, feature/password-manager, QA/steps-specified

**Comment by srirambv** [comment] 2017-07-25 16:54
Verifed on  67b911b. Login moves on landing page

**Comment by luixxiul** [comment] 2017-07-26 13:23
I changed the milestone to 0.18 based on https://github.com/brave/browser-laptop/issues/4687. The fix works nicely :-D
