### ISSUE TITLE
Icon alignment on mouse hover is not proper 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5566] opened 2016-11-11 20:25 UTC
Icon alignment is wrong on mouse hover

Build - Master

![image](https://cloud.githubusercontent.com/assets/17010094/20229144/b9aa06c2-a84c-11e6-9da8-9d466c8646d6.png)

cc: @jkup @bsclifton @bradleyrichter

**Comment by bradleyrichter** [comment] 2016-11-12 19:41
since all of this alignment is perfect on mac, we MUST make windows-specific additions to the CSS then.

**Comment by bsclifton** [comment] 2016-11-12 19:41
Issue caused by https://github.com/brave/browser-laptop/pull/5526

Can be fixed by updating/creating Windows specific CSS selectors here:
https://github.com/brave/browser-laptop/blob/4898dd57fcb0ddb20fc5f4066e1621d77a7a8d48/less/navigationBar.less#L29

**Comment by bbondy** [comment] 2016-11-14 04:20
<img width="73" alt="screenshot 2016-11-13 23 20 06" src="https://cloud.githubusercontent.com/assets/831718/20253246/bf2cc54c-a9f7-11e6-95aa-c27255d9bdda.png">
<img width="70" alt="screenshot 2016-11-13 23 20 10" src="https://cloud.githubusercontent.com/assets/831718/20253247/bf36e162-a9f7-11e6-9358-5454b8b55829.png">

**Comment by bbondy** [comment] 2016-11-14 04:20
pushing a commit with that ^

**Closed** 2016-11-14 04:23 UTC
Labels: feature/URLbar, OS/Windows
