### ISSUE TITLE
app-0.18.34 -> Broken

### ISSUE THREAD

**Issue by AnthoniG** [brave/browser-laptop#10952] opened 2017-09-14 10:12 UTC
Just upgraded to the new Brave and it won't run.
When I look in the Brave folder under AppData\Local\brave I see two folders in there.

One called 
app-0.18.23
app-0.18.34

The one in app-0.18.34 does not work anymore.
It says that it sends you a crash report, but not sure what is going on.
Thankfully the one .23 works but not sure how to roll back to the working version ?

Windows 7 Pro

**Comment by AnthoniG** [comment] 2017-09-14 10:15
Just seen another one with this exact thing on Windows, sorry

**Comment by luixxiul** [comment] 2017-09-14 10:15
The issue is tracked on https://github.com/brave/browser-laptop/issues/10943

**Comment by luixxiul** [comment] 2017-09-14 10:16
Closing in favor of that.

**Closed by luixxiul** 2017-09-14 10:16 UTC
Labels: duplicate, OS/Windows
