### ISSUE TITLE
Brave Password & Last Pass Plugin

### ISSUE THREAD

**Issue by Tera3yte** [brave/browser-laptop#12279] opened 2017-12-14 09:02 UTC
### Description
If you enable Last Pass Plugin (sure it will happen with all other Plugins) the default password manager will be set to Last Pass, but i want to use Brave's password manager AND Last Pass. But Last Pass will be disabled if it is not the default manager... 

### Steps to Reproduce
  1. enable Last Pass
  2. set password manager to brave, Last Pass will be disabled

**Actual result:**
Can not use Plugin Last Pass AND Brave password manager at once

**Expected result:**
If i enable Last Pass it should allways be enabled and not disabled if it is not the default password manager

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
Brave: 0.19.105 
rev: 51f8ba56ca1c1409ddd0620b12650bb7f81c2f79 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.10.0-42-generic 
OS Architecture: x64

**Reproducible on current live release:**

**Comment by srirambv** [comment] 2017-12-14 19:22
There is an another issue logged for allowing multiple password managers. Closing this as a dupe of #7198

**Closed by srirambv** 2017-12-14 19:22 UTC
