### ISSUE TITLE
Saving torrent file causes crash 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13365] opened 2018-03-02 05:17 UTC
### Description
Saving torrent file causes crash 

### Steps to Reproduce

  1. Clean install 0.21.654
  2. Visit https://webtorrent.io/torrents/big-buck-bunny.torrent
  3. Click on save torrent, browser crashes

**Actual result:**
![torrentcrash](https://user-images.githubusercontent.com/17010094/36884347-765a12c8-1e06-11e8-9efe-f7dacef9bf07.gif)

**Expected result:**
Shouldn't crash when saving torrent file

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.21.654
-- | --
OS Release | 10.0.16299
Muon | 5.1.3
V8 | 6.5.254.26
libchromiumcontent | 65.0.3325.88
Node.js | 7.9.0
rev | bc6272c
Update Channel | Beta
OS Platform | Microsoft Windows
OS Architecture | x64

**Reproducible on current live release:**
No

### Additional Information
Saving an image doesn't cause crash 
 #13350 
cc: @darkdh @bridiver

**Comment by bsclifton** [comment] 2018-03-02 05:51
@darkdh possibly caused by the problem we had with bittorrent-tracker and it's downstream dependency on bufferutils. Maybe we can try removing the lock file and perform npm install using `npm install --no-optional`

**Comment by darkdh** [comment] 2018-03-05 07:00
@bsclifton no, this is because `item->GetWebContents()` is null 
https://github.com/brave/muon/blob/ac452600e5fc77e251155339ea9fb407469a14b6/atom/browser/atom_download_manager_delegate.cc#L139 so it sequentially cause null `window` and finally crash at `window->inspectable_web_contents()`.
Only reproduced in C65

**Comment by ltilve** [comment] 2018-03-06 16:55
It seems to be reproducible also on Linux and Mac.

**Comment by ltilve** [comment] 2018-03-07 10:07
When file download was initiated by adding target="_blank" w/o download property, clicking that link was initiating file download from newly created tab instead of current tab that has that link.

When file download was controlled by download manager, newly created web contents was destroyed. However, brave was trying to find browser window's webcontents to show save dialog on it by using destroyed webcontents. But, it was already null, so can't find window pointer. It caused crash.

We created a PR to fix the issue https://github.com/brave/muon/pull/522

It allows downloading from newly created tab crash to be handled too. In this patch, use last active native window if there is no window related with download item.

**Comment by ltilve** [comment] 2018-03-08 13:15
Updated the PR to move download closing code from browser-laptop to muon. It seems `AtomDownloadManagerDelegate` is the proper place to do it because item's webcontents is used there and after used, we can close it safely.
https://github.com/brave/browser-laptop/pull/13404
https://github.com/brave/muon/pull/522

**Comment by ltilve** [comment] 2018-03-13 12:04
Created a new PR https://github.com/brave/muon/pull/529 to amend the merged https://github.com/brave/muon/pull/522. Just with the already applied patch, the tab 
 would be closed whether it is newtab on download or not.

**Comment by ltilve** [comment] 2018-03-14 09:58
Now that the `muon` PR is merged (https://github.com/brave/muon/pull/529) the `browser-laptop` one https://github.com/brave/browser-laptop/pull/13404 could be merged too.

**Comment by bsclifton** [comment] 2018-03-14 15:35
Fixed with https://github.com/brave/muon/pull/529 and https://github.com/brave/browser-laptop/pull/13404

Thanks, @ltilve 😄 👍

**Closed by bsclifton** 2018-03-14 15:35 UTC
Labels: 0.21.x, cr65, crash, feature/torrent, priority/P2, regression
