### ISSUE TITLE
No sites loading 0.20.x+ - OS Proxy Issue

### ISSUE THREAD

**Issue by TDeisinger** [brave/browser-laptop#12959] opened 2018-01-31 18:17 UTC
### Description

After updating to .20.29, all sites after attempting to load will encounter a connection timeout error. No other network issues or problems with other browsers. Cannot check proxy settings in Brave. 

EDIT: After testing with someone else on the same network, they have the same issue, but it worked on a network with no proxy.  It seems this version is not working correctly with checking system settings for a default proxy.

### Steps to Reproduce

Try to load pages

**Actual result:**

![image](https://user-images.githubusercontent.com/36009507/35639651-7f699bb0-0680-11e8-9b7d-efb6fc501d6d.png)

**Expected result:**
Page load

**Reproduces how often:**

100% - Even after complete re-install of browser

### Brave Version

**about:brave info:**
 
Brave: 0.20.29 
V8: 6.4.388.40 
rev: 4fc3c8ff3bcb6af75088b125e00d3a70382b9bec 
Muon: 4.7.9 
OS Release: 10.0.14393 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Reproducible on current live release:**

Yes

### Additional Information

I have a web-proxy that needs to be active (work machine). I assume Brave uses the system settings, but there is no way to confirm that on the browser settings I can find. This could be the cause of the problem. I have no issues with other browsers.

**Comment by diracdeltas** [comment] 2018-01-31 19:04
i can’t repro this on MacOS - works fine if with my system proxy (Tor). may be a windows-only issue.

**Comment by riastradh-brave** [comment] 2018-01-31 19:08
Do you know what kind of proxy it is?  What are your system proxy configurations?  Do you have a proxy autoconfig file or something that you can share?

**Comment by rebeccahhh** [comment] 2018-01-31 19:10
I'm also having this issue one a windows machine, also similar proxy configs, I can't share any due to privacy agreements.

**Comment by bridiver** [comment] 2018-01-31 19:21
is this new with 0.20? Can't be reproduced with 0.19?

**Comment by TDeisinger** [comment] 2018-01-31 19:33
It was working fine on .19 right before it updated. I'm also gonna have to hold off on specific proxy settings (Company proxy .pac).

Basically if you are on the domain network and don't have the proxy, you cannot get to any external sites. I'm not in that IT group so I don't know specifics.

**Comment by rebeccahhh** [comment] 2018-01-31 20:45
Follow up, experiencing the same problem as @TDeisinger , additionally unable to open Brave via clicking hyperlinks (Brave being default browser) or directly opening application. I will also check off company proxy and report back

**Comment by mkielhauser** [comment] 2018-02-01 03:52
Exactly the same here. Just updated today in the office (Win7) and no sites are loading after refresh. We use a proxy  auto configuration script but due to confidentiality I cannot share this. It was all working before the upgrade to 0.20. I am running Ubuntu in VirtualBox on my desktop and, of course, have to use a proxy to connect outside. The Linux version of Brave works in this environment giving weight to the idea it is a Windows issue.

**Comment by rebeccahhh** [comment] 2018-02-01 14:45
Mine is also a Win7 machine for the office. I checked off proxy and the issue persisted, however, I will uninstall and reinstall an old version, update out of the office, and then check the launch with and without proxy. That might help determine if it's an issue with something from the actual update being blocked by proxy.

**Comment by derekhillhp** [comment] 2018-02-01 14:55
I can reproduce this reliable on a network (corporate) that has a proxy server. I even get warning that the auto-configuration script needs to be used for our network. As soon as I move the machine to a network that doesn't require a proxy, it works. I even went as far as to downgrade to 0.19 and the browser works correctly. There definitively is a problem with 0.20. The same screen shots are already posted above.

It appears that the new version is no longer using the system proxy settings.

Win 10 Enterprise, 1709 build.

**Comment by LaurenWags** [comment] 2018-02-01 15:55
+1s from community:
https://community.brave.com/t/brave-20-update-causing-websites-to-not-load/15218
https://community.brave.com/t/brave-will-not-display-browser-after-update/15176/3

**Comment by TDeisinger** [comment] 2018-02-01 21:26
Just tested .20.30 and still having the problem

**Comment by Kickimanjaro** [comment] 2018-02-02 15:57
Have same issue as described by others here, also cannot share the proxy config (for same reasons). Wanted to mention that items in the proxy bypass list work, but anything that requires traversing the proxy returns "An SSL protocol error has occurred." I note that this is a different message than the timeout shared here but I feel these are related. 

I agree with @derekhillhp, this update should be pulled. It kills the browser as the browser update check uses proxy and fails.

**Comment by derekhillhp** [comment] 2018-02-02 17:21
Just adding more data here. Last nights release 0.20.30 did not fix this. I had also checked the milestones and it doesn't appear that this bug has even been assigned to any of the .0.20 planned hotfixes.

I am adding a couple of screen shots to hopefully make this clear that the 0.20 release broke the proxy integration with the windows system proxy settings. I have tried this with the standard auto configure PAC file as well as hard coding a proxy. 

![brave-error2](https://user-images.githubusercontent.com/5630875/35746006-26658ef4-07fa-11e8-83a1-a2fe238afc21.PNG)

![brave-error1](https://user-images.githubusercontent.com/5630875/35746013-2affbaf2-07fa-11e8-9d7d-4a632704d52a.PNG)

**Comment by rubyisbeautiful** [comment] 2018-02-02 18:18
This definitely also broke proxy on Mac OSX 10.12.6.  I use a pac file for proxy config at system level.  Brave's proxy usage was always weird, as it was the only browser ever (re-)asking for the proxy credentials, but I digress.  The .20.x updates broke it.  I confirm that re-installing the .19.x releases makes it work again.

**Comment by srirambv** [comment] 2018-02-05 14:09
+1 on macOS from https://community.brave.com/t/brave-0-20-30-not-picking-up-system-proxy-settings/15474/2

**Comment by petereit** [comment] 2018-02-05 16:11
Re-installing v0.20.27 resolves the Windows OS proxy issue for me, so it looks like whatever change that broke it started with the v0.20.29 release.

**Comment by rejkube** [comment] 2018-02-06 06:17
where is the custom proxy options for the browser ? definitely windows version 0.20.29 or later is broken with proxy pac urls /auto detection

**Comment by derekhillhp** [comment] 2018-02-06 18:11
It uses the system proxy settings that you configure in IE on Windows and in Systems Preferences -> Network settings for each interface on a Mac.

I have not found any place to set proxy settings inside of Brave.

**Comment by TDeisinger** [comment] 2018-02-06 18:33
Issue is still present on .20.32

**Comment by bjoernbusch** [comment] 2018-02-08 06:10
Still reproducable with v0.22.2.

**Comment by cwbriscoe** [comment] 2018-02-08 16:34
Having same issue.  .19 works.


```
Brave | 0.20.30
V8 | 6.4.388.40
rev | 8b78402
Muon | 4.7.9
OS Release | 6.1.7601
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119
```

**Comment by LaurenWags** [comment] 2018-02-09 14:42
Multiple +1s: https://community.brave.com/t/http-proxy-not-working-after-update/15171

**Comment by perryizgr8** [comment] 2018-02-14 03:51
Still broken on 0.20.40

```
Brave	0.20.40
V8	6.4.388.41
rev	87c8d0c
Muon	4.8.2
OS Release	10.0.16299
Update Channel	Release
OS Architecture	x64
OS Platform	Microsoft Windows
Node.js	7.9.0
Brave Sync	v1.4.2
libchromiumcontent	64.0.3282.140
```

**Comment by TDeisinger** [comment] 2018-02-14 15:56
Still present on .20.41

**Comment by jonathansampson** [comment] 2018-02-14 18:30
@bridiver Appears the issue was introduced with 0.20.29, according to a few users. Reports are that 0.20.27 do not have this issue, and work as expected.

@diracdeltas Do you recall which version of Brave you tested with Tor?

**Comment by bsclifton** [comment] 2018-02-14 20:21
Definitely going to need help finding steps to reproduce this

I've configured both a macOS and Windows 10 machine using a SOCKS proxy and both worked as expected

@TDeisinger @perryizgr8 @cwbriscoe @bjoernbusch @derekhillhp @rejkube do you have more information about your proxy setup? ex: what protocol?  If you're using a public proxy (and not an intranet one), would you be able to share details via email?

**Comment by bjoernbusch** [comment] 2018-02-14 20:23
We have a pac proxy script to configure the settings. Not sure how much of the details I can share there, but I'll check, whether I can share a reduced one.

**Comment by bsclifton** [comment] 2018-02-14 20:28
It's worth noting that there were only 6 commits between 0.20.27 (which is reported as working) and 0.20.30

- Merge pull request #11103 from brave/issue-11101
  - always return copy of parse url and remove option for query as object
  - https://github.com/brave/browser-laptop/commit/498ce5ce8600ffe4c342329c70384596a98eda70
- Merge pull request #12942 from brave/fix/12939
  - firstPartyUrl can be missing in some cases
  - https://github.com/brave/browser-laptop/commit/558d55087a754445439e58320717606cc35148f9
- Merge pull request #12945 from brave/fix/12943
  - workaround for strings passed by muon code
  - https://github.com/brave/browser-laptop/commit/e3786819eeee858e11bd59d4c5a83b938c499c56
- Merge pull request #12944 from brave/issue-12940
  - Fix invalid icon path on Windows
  - https://github.com/brave/browser-laptop/commit/067ef1e8b5b9443b913b4f37e86b3f0aa02ea9b9
- Merge pull request #12954 from brave/0.20.29-release-notes
  - 0.20.29 release notes
  - https://github.com/brave/browser-laptop/commit/7279ac84f69022b1fa0099bcd2c3c26ade08a69e
- Merge pull request #12977 from brave/fix/12976
  - separate rules for whether a tab can be created discarded and whether it can be autoDiscardable)
  - https://github.com/brave/browser-laptop/commit/d53e4381a0dd9d62565ba07192c3f893104b226a

**Comment by TDeisinger** [comment] 2018-02-14 20:35
I have a PAC proxy script as well and I am not the one that manages it..so I am not sure what specifics I could give.

**Comment by bsclifton** [comment] 2018-02-14 20:40
@bjoernbusch @TDeisinger if you are both able to try 0.20.27 to confirm that it does work, that would help for sure 😄 Out of the above, there are two suspect changes which I can try reverting and providing you a custom build to confirm the fix

Here's a download link for 0.20.27 if you were able to try and confirm it works:
https://github.com/brave/browser-laptop/releases/tag/v0.20.27dev

**Comment by bjoernbusch** [comment] 2018-02-14 20:43
I can confirm that 0.20.27 works. It was mentioned earlier, so I tried installing that and I could browse different websites. Unfortunately the auto-update worked as well :)

**Comment by TDeisinger** [comment] 2018-02-14 20:46
Also can confirm .20.27 works. Once it updates to beyond that (.29 I think), auto-update stops working too, basically because I think it can't get any connection out.

**Comment by bsclifton** [comment] 2018-02-14 21:35
And here's the second experimental fix (also Windows only) if folks wanted to try it. This build backs out https://github.com/brave/browser-laptop/commit/498ce5ce8600ffe4c342329c70384596a98eda70
https://github.com/brave/browser-laptop/releases/tag/0.20.x-exp-proxy-fix-2

**Comment by bsclifton** [comment] 2018-02-14 22:23
Awesome, thanks for trying it out @Kickimanjaro! I believe we have narrowed the issue down and I've created a new build which you can try:
https://github.com/brave/browser-laptop/releases/tag/0.20.x-exp-proxy-fix-3

This version should work perfectly

**Comment by TDeisinger** [comment] 2018-02-14 22:35
I have tested and it is working on this version 

 
Brave: 0.20.43 
V8: 6.4.388.41 
rev: 8e71853d5d25b34cddc4b21a2978654221259bc9 
Muon: 4.8.2 
OS Release: 10.0.14393 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Comment by TDeisinger** [comment] 2018-02-14 22:41
.20.45 does not work, it keeps timing out again.

**Comment by Kickimanjaro** [comment] 2018-02-14 22:43
Tested Fix 3 and it failed. Upon redoing my original tests it looks like the brief test I tried for Fix 2 was in error (I must have hit a cached page or something) as Fix 2 now consistently fails. Fix 1 (0.20.43) still works, though. My apologies for that. The following version (fix 1) works:

Brave | 0.20.43
V8 | 6.4.388.41
rev | 8e71853
Muon | 4.8.2
OS Release | 10.0.14393
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Comment by TDeisinger** [comment] 2018-02-14 22:44
Yes I think .43 is the correct one.

**Comment by bsclifton** [comment] 2018-02-14 23:09
Awesome- thanks for the feedback 😄 👍 I'll review the findings with the team and we'll work on a proper fix 😄 In the meantime, you can use the 0.20.43 change and it should work as expected

**Comment by derekhillhp** [comment] 2018-02-15 00:00
Sorry I am late to the party, but I also tried the 0.20.43 fix and can confirm that it works with just some cursory testing using the corporate PAC (auto configurartion script) file.

**Comment by mkielhauser** [comment] 2018-02-15 05:10
Yeah, late here too but 0.20.43 works perfectly for me too. Thank you for the effort in addressing this!

**Comment by bsclifton** [comment] 2018-02-15 05:49
@mkielhauser @derekhillhp @TDeisinger @Kickimanjaro need help testing a possible solution.  The above (0.20.43) has a crash bug.  I've put together a fix which should fix the crash + fix the proxy issue (solution proposed by @diracdeltas)

If you have a minute, please check out:
https://github.com/brave/browser-laptop/releases/tag/0.20.x-exp-proxy-fix-4

**Comment by bjoernbusch** [comment] 2018-02-15 06:08
The latest experimental fix doesn't work for me, it times out again.
 
Brave: 0.20.46 
V8: 6.4.388.41 
rev: bd8046e01a5c6f9e72954f744cec40e159399b70 
Muon: 4.8.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

43 works for me as well.
 
Brave: 0.20.43 
V8: 6.4.388.41 
rev: 8e71853d5d25b34cddc4b21a2978654221259bc9 
Muon: 4.8.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Comment by bsclifton** [comment] 2018-02-15 06:26
@bjoernbusch ok great, thanks for confirming! I'll remove the link

**Comment by koppts** [comment] 2018-02-15 14:36
I can confirm 20.43 working as well (behind corporate fw and suffering since 20.29)

Brave | 0.20.43
V8 | 6.4.388.41
rev | 8e71853
Muon | 4.8.2
OS Release | 10.0.10240
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Comment by derekhillhp** [comment] 2018-02-15 23:38
@bsclifton Do you still need somebody to test the latest file posted: https://github.com/brave/browser-laptop/releases/download/0.20.x-exp-proxy-fix-1/BraveSetup-x64.exe

Don't want to download and break anything unless I have to. :-D

**Comment by bsclifton** [comment] 2018-02-15 23:44
@derekhillhp no testing needed 😄 I had tried another fix without luck. We still have some more work to do- I may ask folks to try another fix sometime soon (stay tuned!)

**Comment by derekhillhp** [comment] 2018-02-15 23:50
Let me know if you need to test on a corporate network. We have one of those here.

**Comment by mkielhauser** [comment] 2018-02-16 00:45
Yeah, same here. Corporate network and PAC script. I am in JST (UTC + 9) so I tend to be up later compared to you guys but I am happy to test any new version. Really like the browser and try to make it my standard for personal browsing.

**Comment by bsclifton** [comment] 2018-02-22 06:52
Although we've narrowed down the code which broke this functionality, we need a solid way to reproduce locally (where we can debug the issue). For our upcoming 0.21.x release, we're focusing on performance issues and likely won't have time to dig into this (yet).

I'm going to move back one release to 0.22.x.  Apologies to folks affected by this ☹️ Any help with steps to reproduce locally would be very much appreciated

Some ways we can use help:
- share a sanitized PAC script (along with how to apply this)? Removing personal/intranet/corporate info of course and replace with dummy IPs/etc. Can be shared here or via email (clifton@brave.com)
- Grab the source code and try it out yourself:
  ```
  git clone git@github.com:brave/browser-laptop.git && cd browser-laptop
  git checkout 0.21.x
  npm install
  ```
  You can then revert https://github.com/brave/browser-laptop/commit/558d55087a754445439e58320717606cc35148f9 and try to add back parts of the fix

**Comment by rejkube** [comment] 2018-02-22 10:14
I was disappointed at one point to go back use the google-chrome ... rev | 8e71853 is a big relief !

**Comment by mkielhauser** [comment] 2018-02-23 03:52
@bsclifton I have sent you a sanitized version of our PAC script. 
Password to access it is Ayaaj0]k8f with a zero not an O. Hope that helps.

**Comment by mkielhauser** [comment] 2018-02-23 08:06
Forgot to show how to apply it, silly me...
![pac](https://user-images.githubusercontent.com/36023161/36584119-cc8c4378-18bb-11e8-9f06-ad7bb345a6da.png)

**Comment by Kickimanjaro** [comment] 2018-02-27 17:08
Using the 0.20.43 fix is now prompting to auto-update to 0.20.46, which I assume will break the proxy again as @bsclifton mentions that the fix for this has been pushed back to 0.22.x. Is this correct? Should we avoid updating until 0.22.x?

**Comment by TDeisinger** [comment] 2018-02-27 17:13
Yes, I tested .20.46 yesterday and it was still broken, so will have to stay on .43 for now.

**Comment by mkielhauser** [comment] 2018-02-28 01:33
Yeah, was hit by the auto-update which broke my working browser. Is there any way to disable the auto-upgrade?

**Comment by bsclifton** [comment] 2018-02-28 07:11
We did have a recent release which unfortunately will trigger the special build above to auto-update

The issue has been pushed back to the 0.23.x milestone- no estimate for investigating / fixing at the moment ☹️ I do have the above info so we can look at reproducing the issue

cc: @davidtemkin

**Comment by petereit** [comment] 2018-02-28 11:20
Rename the update.exe file in the app directory. 

Mark

**Comment by bjoernbusch** [comment] 2018-02-28 12:31
@petereit thank you so much!

**Comment by mkielhauser** [comment] 2018-03-01 01:58
@petereit Many thanks! Now I can keep enjoying Brave at work. :-)

**Comment by TDeisinger** [comment] 2018-03-29 15:45
Will this still be coming out with .23?

**Comment by bsclifton** [comment] 2018-03-30 04:11
@TDeisinger investigation and fix are still planned for 0.23.x 😄 👍

**Comment by TDeisinger** [comment] 2018-05-04 13:59
Is the fix for this in Dev release .23.2?

**Comment by bsclifton** [comment] 2018-05-04 17:07
@TDeisinger fix not found yet - I should be able to shift gears from our 0.22.x release to look at this soon. Thanks for hanging in there (and apologies we haven't found a fix yet)

**Comment by bsclifton** [comment] 2018-05-09 18:09
Hi folks

I'm taking a look at this again and have been trying a few different PAC scripts without success. Would anyone here experiencing the problem feel safe sharing a copy of their PAC script with me? If so, please contact me via clifton@brave.com

Without a clear way to reproduce it's nearly impossible to attempt a fix (which is the major reason this issue hasn't been resolved yet) ☹️

**Comment by derekhillhp** [comment] 2018-05-09 21:34
@bsclifton just sent you a PAC file

**Comment by bsclifton** [comment] 2018-05-16 07:10
@TDeisinger @mkielhauser @derekhillhp and others - I have an attempted fix which you can try
https://github.com/brave/browser-laptop/releases/tag/v0.24.0-exp-proxy-fix

Please note that this build has some experimental features which are not live (you can always revert to the older build by re-downloading from https://brave.com). I'm mostly curious if the changes I made work for you all (I implemented some better error handling / added unit tests)

**Comment by mkielhauser** [comment] 2018-05-16 08:14
Unfortunately I got the error again:
A connection attempt timed out.
https://github.com/brave/browser-laptop/releases/tag/v0.24.0-exp-proxy-fix

 
Brave: 0.24.0 
V8: 6.6.346.26 
rev: 846a591c49a26365e9c87d03fde591663caecdbc 
Muon: 6.0.9 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.139

As soon as I re-install:
 
Brave: 0.20.27 
V8: 6.4.388.40 
rev: 76102c507ba472e25ec6aff1bd01e7008254b991 
Muon: 4.7.9 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

everything is working.

Would it be possible to simple have a filed to add a named proxy server? This would be a workaround that would definitely work in my office environment.

**Comment by TDeisinger** [comment] 2018-05-16 13:51
Still doesn't work for me either. Have to go back to .20.43

**Comment by bsclifton** [comment] 2018-05-16 17:55
Thanks for trying the release folks- unfortunately, this problem is very hard to troubleshoot without being able to accurately reproduce it.  I think WebSense or other proxies may be manipulating headers which is the core of the problem (which is hard for me to reproduce). The actual configs themselves that were shared looked fine

For those reasons, I've reset the milestone ☹️. I highly encourage folks who experience this issue and can help with coding to fork/clone the repo and read the above notes where the commit breaking is introduced (I'd love to help with this). That breaking commit can be reverted and added back a piece at a time (with extra console.log() statements of course) to find the issue

There is some good news though: because this works in Chrome/Chromium, we should get this fixed for free when we move over to Brave Core ([more details available here](https://brave.com/development-plans-for-upcoming-release/)). Thanks for hanging in there folks- and big thanks for providing more info and helping try the attempted fixes

**Comment by mkielhauser** [comment] 2018-05-17 00:50
@bsclifton Thanks a lot for the good news! To come back to my previous question, would it not be easiest to have an option to configure a proxy server? There's quite a few programs that have issues behind a proxy and adding a server manually is all that's needed (Amarok springs to mind). Of course this might cause other issues but I thought I ask :-)

**Comment by ChrisWhealy** [comment] 2018-05-25 09:58
This is still broken in 0.22.721 and its becoming ***REALLY*** tedious.  I need to switch in and out of my company's VPN but every time I connect, I need to remember that I must use an alternative browser because Brave just stops working.

Would adding proxy configuration settings help as per Firefox?

Please fix this as a matter of priority because I'm getting to the point that this ongoing issue is becoming a showstopper for my continued use of Brave.
 
Brave: 0.22.721 
V8: 6.6.346.32 
rev: bfe7cdd026c68013236ebe206a33448db9370fca 
Muon: 6.0.12 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Comment by mkielhauser** [comment] 2018-05-28 01:48
@ChrisWhealy If you want you can install the old version of Brave before the change and immediately rename the update.exe file in the app directory as recommended by Mark (petereit) earlier. I have done that can can use Brave for now w/o issues. I also think a workaround could be to have a proxy configuration but as I am not a programmer (any more) I am not sure how tricky that is.

**Comment by ChrisWhealy** [comment] 2018-05-29 09:13
@mkielhauser Thanks, but I'm running on Mac, and I for me at least, none of the old versions of Brave have ever worked through a VPN.

**Comment by TDeisinger** [comment] 2018-07-10 14:18
Update!

So I was having trouble with my .20.43 version of Brave not starting, and decided to install the latest version then maybe go back again..and funny enough I can get everyone on .23.31

So something was changed which fixed this problem...unless the core was changed and I just didn't know.

Either way if you were having this problem try out .23.31

@bsclifton

**Comment by bsclifton** [comment] 2018-07-10 15:55
@TDeisinger this is great news! Latest version may have fixed the problem 😄 

cc: @mkielhauser @derekhillhp @ChrisWhealy @petereit @Kickimanjaro @rebeccahhh @perryizgr8 @bjoernbusch @rejkube @koppts

**Comment by TDeisinger** [comment] 2018-07-10 16:36
Unknown if it was latest version, I haven't tried any others recently though.

**Comment by mkielhauser** [comment] 2018-07-11 01:57
I can confirm the good news! Just renamed my "update.exe" back and checked for updates. It loaded 0.23.31 (latest) and no more proxy woes!! This is really great. Thank you for delivering a fix, very much appreciated!

**Comment by rubyisbeautiful** [comment] 2018-07-13 13:02
Latest for me also fixes the proxy issue on Mac OS

**Comment by bsclifton** [comment] 2018-07-13 15:41
I'm going to go ahead and close this issue as it seems it's fixed now 😄 Thanks for reporting back here folks! Let's re-open (or leave a comment) if the issue is not actually fixed for you and I can look more into it

**Closed by bsclifton** 2018-07-13 15:41 UTC
Labels: 0.20.x, bug, fixed-with-brave-core, priority/P2
