### ISSUE TITLE
Email Preview Problems

### ISSUE THREAD

**Issue by jian-leopoldo** [brave/browser-laptop#14661] opened 2018-07-05 14:21 UTC
Hello, i´m a Ruby On Rails developer and i have a problem when the RoR trying to open a email preview in HTML on brave. 

My console show this error:
/snap/brave/25/bin/desktop-launch: line 174: de: command not found

Brave Version : 0.23.19

My OS Infos: 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

**Comment by bsclifton** [comment] 2018-08-13 07:10
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/14863

**Closed by bsclifton** 2018-08-13 07:10 UTC
