### ISSUE TITLE
Context menu on bookmark toolbar cannot be shown from toolbar area

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4545] opened 2016-10-05 12:33 UTC
**Describe the issue you encountered:** The context menu on bookmark toolbar cannot be shown from the toolbar area once bookmark toolbar is disabled, because you can only show the system context menu above the tab bar. 

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.3

- Any related issues: #4244

**Comment by bsclifton** [comment] 2017-06-19 06:55
Fixing this properly would require either making the tabs bar non-draggable OR solving https://github.com/brave/browser-laptop/issues/4244

**Comment by bsclifton** [comment] 2017-07-18 17:05
Closing as duplicate of https://github.com/brave/browser-laptop/issues/4244

**Closed by bsclifton** 2017-07-18 17:05 UTC
Labels: feature/context-menu, feature/navbar, feature/titlebar, OS/Windows
