### ISSUE TITLE
Downloaded files have no extension

### ISSUE THREAD

**Issue by bravefan** [brave/browser-laptop#12878] opened 2018-01-27 16:40 UTC
### Description
This has been an ongoing issue for months in Brave, but it is still unresolved. Files downloaded on the Windows version do NOT have file extensions. Users have to manually give the downloaded file names extensions at the time of downloading, or rename the files after downloading.

### Steps to Reproduce

  1. Download a file on the Windows version of Brave
  2. That's all folks

### Brave Version
0.19.147

### Additional Information
Not sure why this hasn't been fixed yet. It's super annoying and it's the only web browser I use that has this issue. I love Brave but this is silly at this point.

**Comment by eljuno** [comment] 2018-01-27 19:25
Duplicate of #1985

**Comment by bsclifton** [comment] 2018-01-28 06:51
Thanks for the report, @bravefan! I've closed this as it is a duplicate

**Closed** 2018-01-28 06:50 UTC
