### ISSUE TITLE
Tabs, toolbar too small - can't customize - if not fixed I'll go back to Edge 

### ISSUE THREAD

**Issue by 2OldMan** [brave/browser-laptop#5741] opened 2016-11-19 23:34 UTC
Can't customize this mess called Brave.  Tabs, toolbar, bookmarks tool bar too small.  No way to adjust.  If it's not fixed I'll go back to Edge.  I don't need this aggravation.

**Comment by bradleyrichter** [comment] 2016-11-23 03:02
@2OldMan Is the main problem the font size?

We will create an option for normal and large fonts soon which will increase the containers as well. 

Are you using Edge in it's normal size or also increased?


Thanks - Brad

**Comment by bsclifton** [comment] 2017-01-31 07:55
@2OldMan are you by chance on Windows? We had a release recently (0.13.0) which may resolve this issue for you.  Please give it a shot and let us know; sorry for the inconvenience ☹️

**Comment by bsclifton** [comment] 2017-01-31 08:07
Closing this issue as a duplicate of https://github.com/brave/browser-laptop/issues/5683

**Closed by bsclifton** 2017-01-31 08:07 UTC
Labels: info-needed
