### ISSUE TITLE
Ads on drudgereport.com with shields up

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#9376] opened 2017-06-09 23:50 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Ads observed on The Drudge Report with shields up 

- Platform (Win7, 8, 10? macOS? Linux distro?):
All platforms, including mobile 

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/51de9af083a50b9d5ceaec34af35ea3c1c9696fc

- Steps to reproduce:
    1. Go to http://www.drudgereport.com
    2. Wait for the page to fully load
    3. See ads display
    
- Actual result:
![brave-drudgereprt-06092017](https://user-images.githubusercontent.com/8979240/26998004-9bf0f44c-4d33-11e7-9c0c-9e04dd80f08b.PNG)

- Expected result:
No ads

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by privatzee** [comment] 2017-06-13 14:47
This is the result of some anti-blocking measures they took several days ago. However, the Drudge site will work just fine (for now) if users simply block all scripts. 

That gives the added benefit of also blocking spying by google scripts there -- which are otherwise _very unfortunately_ allowed by Brave. 

Btw, Drudge has something like 1 **_billion_** pageviews per month ( http://www.intermarkets.net/advertiser-solutions/portfolio/drudge-report/ )

**Comment by diracdeltas** [comment] 2017-06-13 18:19
@privatzee do you know the specific domains or google script sources that we should be blocking? we use upstream lists for blocking but are happy to add more to them.

**Comment by lukemulks** [comment] 2017-06-20 01:46
+1 from community https://community.brave.com/t/ad-blocking-not-working-on-drudgereport-com/4032/5

**Comment by eljuno** [comment] 2017-06-24 19:53
+1 [from community](https://community.brave.com/t/would-like-a-brave-drop-down-bookmarks-list/4236/3?u=eljuno)

>  I notice that at Drudge Report, there's several ads showing. AND, PS, just found the ads on Drdge Report could axed by using the Site Shield settings to eliminate scripts.

**Comment by Jacalz** [comment] 2018-02-08 16:46
Having trouble finding any ads on that site 😓

**Comment by bsclifton** [comment] 2018-02-08 21:54
Unable to reproduce also- may have been fixed by adblock updates.  Let's close for now and re-open if the issue comes back 😄

**Closed by bsclifton** 2018-02-08 21:54 UTC
Labels: feature/adblock, needs-investigation, site-bug
