### ISSUE TITLE
New windows include pinned tabs

### ISSUE THREAD

**Issue by afong94** [brave/browser-laptop#12614] opened 2018-01-11 22:35 UTC
### Description

When creating a new window, the pinned tabs are included. The same behavior occurs even after creating a new tab, then dragging it out of the existing window to create a new window session.

### Steps to Reproduce

  1. Pin a few tabs
  2. Create a new tab and drag it out to create a new window (or create a new window)
  3. Observe the new window with the tabs included

**Actual result:**

Currently, new windows created via the new window (cmd + N) or dragged out of a current window includes pinned tabs.

**Expected result:**
It would be best to only have the pinned tabs under the current window session, to reduce memory usage. 

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

0.19.131

**Reproducible on current live release:**

**Comment by eljuno** [comment] 2018-01-11 22:45
That's the current (expected?) behavior. Duplicate of #5800?

**Comment by flamsmark** [comment] 2018-01-12 00:10
FWIW, this behavior surprised me.

**Comment by afong94** [comment] 2018-01-12 09:48
Ah yes, this is a duplicate, sorry about that.

**Closed** 2018-01-12 16:57 UTC
Labels: duplicate
