### ISSUE TITLE
Do not show GMT+0000 for GMT timezone

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5937] opened 2016-11-30 12:51 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Doesn't make sense to put the +0000 after GMT when user timezone is in GMT

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.13.0 Preview 2

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20752846/5b294c94-b6fb-11e6-8cfd-28af9afd2246.png)

- Any related issues:
cc: @cezaraugusto @bradleyrichter

**Comment by bsclifton** [comment] 2016-11-30 16:11
I believe this is a dupe of https://github.com/brave/browser-laptop/issues/5879.  I'll remove milestone and will be assigning the other issue to myself (see notes in other issue)

**Closed by bsclifton** 2016-11-30 16:11 UTC
Labels: design, feature/newtab, suggestion
