### ISSUE TITLE
Changing color of visited hyperlinks

### ISSUE THREAD

**Issue by SLBondy** [brave/browser-laptop#1038] opened 2016-03-08 18:56 UTC
Comment from Support:

When you are on a web-site, it would be nice if you could turn hyperlinks red if the user has already read them. That makes it easier to scan them for new articles you haven’t seen yet.

Harald H.

**Comment by FrancisTurner** [comment] 2016-03-14 08:50
This is a dupe of #512  and related to  #505  and #444

**Comment by bbondy** [comment] 2016-03-14 13:55
Thanks, closing in favour of #512.

**Closed by bbondy** 2016-03-14 13:55 UTC
