### ISSUE TITLE
Flash support for site X?

### ISSUE THREAD

**Issue by VikramTiwari** [brave/browser-laptop#386] opened 2016-01-28 17:56 UTC
What type of flash support is there in Brave? If none, shouldn't support for PPAPI which is more secure, be there?

Ref: https://support.google.com/chrome/answer/6213033?hl=en

**Comment by bridiver** [comment] 2016-01-28 20:10
We currently don't have plans to support Flash, but a "mobile" view that will trigger many sites to display an HTML5 compatible version of the site targeted towards ios is on the roadmap. If there is enough demand we will revisit the decision, but Flash carries a lot of baggage with it even through PPAPI. So far I haven't personally come across anything I really cared about that didn't have a non-flash alternative, but I know there are some out there and at this point it's a question of how many sites/people it affects.

**Comment by diracdeltas** [comment] 2016-01-28 20:47
+1 for not supporting Flash

**Comment by bbondy** [comment] 2016-01-28 20:52
May be added as an option you can explicitly turn on later, but off by default.
Preference is to just not support it at all though too.

**Comment by bagmangood** [comment] 2016-01-30 15:06
One problem with not supporting flash - a lot of the web still uses flash pretty extensively (portions of YouTube, most streaming sites). 

Flash is awful, but unfortunately still necessary at the moment

**Comment by bridiver** [comment] 2016-01-30 17:14
Can you provide an example from YouTube?

**Comment by bagmangood** [comment] 2016-01-30 17:16
First one I found: https://www.youtube.com/watch?v=qkTzDh8IKNU

**Comment by bridiver** [comment] 2016-01-30 17:20
That plays for me on Brave. What do you see on this page https://www.youtube.com/html5 ?

**Comment by bridiver** [comment] 2016-01-30 17:23
I do understand your point about Flash and I realize that there are sites that won't work, but some sites are more important than others.

**Comment by bagmangood** [comment] 2016-01-30 17:36
I got check marks on everything on the html5 page. Deleted Brave and re-installed (with the latest version from Brave.com) and now the video plays. Guess I should have tried that first.

**Comment by bridiver** [comment] 2016-01-30 17:39
Great! We are interested in reports of popular sites that require Flash so please continue to report any that you find and we will try to address them.

**Comment by bagmangood** [comment] 2016-01-30 18:21
Created a page on the wiki rather than spam a thread https://github.com/brave/browser-laptop/wiki/Non-Supported-Video-Sites

**Comment by bridiver** [comment] 2016-01-30 18:33
Netflix has HTML5 support for Safari, but it does not appear to work on Brave right now. 
https://github.com/brave/browser-laptop/issues/468

**Comment by bridiver** [comment] 2016-01-30 18:53
Not sure about twitch.tv, but anything that plays on mobile Safari should work on Brave at least for SD content (HD has DRM issues) when jwplayer is added

**Comment by Nhoj1983** [comment] 2016-01-31 02:18
So I checked, no hulu, crunchyroll, daisuki, gamespot (video), or funimation available.   Mostly geek related sites but seriously going to be hard to make brave my browser if it doesn't support a large amount of what I use the web for which is streaming.  I really like brave and I agree flash isn't great but it's kind of needed atm.  I realize some sites are more important but I know a lot of people who use at least one of these pretty regularly.

**Comment by weems** [comment] 2016-02-13 04:27
Seconding @diracdeltas to not support flash, though it could be nice to have some sort of option as users definitely desire to use Brave on sites which only work with flash.

**Comment by diracdeltas** [comment] 2016-02-16 19:44
Could anyone who is having trouble with Flash sites like Hulu checkout this branch to see if it fixes the issue: https://github.com/brave/browser-laptop/tree/feature/ua-spoofing

It spoofs the user-agent to iPad (which doesn't run flash by default). Thanks!

**Comment by bridiver** [comment] 2016-02-16 22:08
Netflix works on Safari 9+ without any Flash/Silverlight. Might be a better option for ua spoofing because I think Netflix on ios sends you to their app.

**Comment by bridiver** [comment] 2016-02-16 22:23
Verified that Netflix sends you to a "get the free app" page for ios

**Comment by diracdeltas** [comment] 2016-02-16 22:24
> Netflix works on Safari 9+ without any Flash/Silverlight. Might be a better option for ua spoofing because I think Netflix on ios sends you to their app.

I think that is because of EME support. http://techblog.netflix.com/2014/06/html5-video-in-safari-on-os-x-yosemite.html

I'll change it to desktop safari for now

**Comment by bridiver** [comment] 2016-02-17 00:05
Hmmm... looks like we may need Widevine then. There is already support in Electron for it and according to http://www.widevine.com there are no licensing fees

**Comment by FutureSomeOne** [comment] 2016-02-17 02:11
Twitch.tv !!!!! almost every single gamer go to this site, there will be even more people go to twitch when there is a tournament, if all the gamers (who use computer the most) can't go to their streaming website, they will just switch to other browser

**Comment by bbondy** [comment] 2016-02-17 02:15
See https://github.com/brave/browser-laptop/issues/782

**Comment by weems** [comment] 2016-02-17 02:16
Prioritization for sites with the most usage will be important as more requests for flash / plugin sites are made. Scaling is going to be important.

**Comment by Spammie** [comment] 2016-02-24 23:10
ehm, I wana use spotify website on my laptop but it requires flash what do I do ?

**Comment by bridiver** [comment] 2016-02-24 23:15
I don't have a spotify account to test, but there appears to be an html5 version http://blog.72lions.com/projects/2014/12/8/spotify-web-player
http://play.spotify.com/

**Comment by JuanJalar** [comment] 2016-02-25 01:18
Videos on CNET's web pages won't play in Brave, first because of its built in ad blocking, then even when ad blocking is turned off, because they say they need Flash to play.  For instance, if you scroll past this CNET article on Brave's mobile release today, http://www.cnet.com/news/brave-software-ad-block-browser-clears-google-hurdle/, you come to a video on Facebook reactions that just won't play.  In other instances, CNET says it won't play a video because I have ad blocking on.  Then when I turn it off, I get a message that I need to install Flash.

**Comment by weems** [comment] 2016-02-25 01:24
Confirmed what @Spammie is experiencing in 0.7.16

**Comment by bridiver** [comment] 2016-02-25 01:25
@Spammie did you try http://play.spotify.com instead of the regular home page? There seems to be a lot of conflicting information and the actual status of an html5 version is unclear

**Comment by weems** [comment] 2016-02-25 01:27
There is a  <div id="html5audio"></div> tag, but I think the actual authentication / playing of music is negotiated with a flash plugin.

**Comment by weems** [comment] 2016-02-25 01:28
It is *not* HTML5 (pure at least) tries to use the following: https:\/\/play.spotify.edgekey.net\/client\/9cd7401\/flash\/bridge.swf

**Comment by dscycler** [comment] 2016-02-25 06:48
cbs.com requires flash.

**Comment by dscycler** [comment] 2016-02-25 06:52
Pandora.com requires Flash.

**Comment by dukrat** [comment] 2016-02-25 16:42
VMWare vCenter vSphere Web Client requires Flash.

**Comment by zeg-io** [comment] 2016-03-01 01:03
Foxnews.com watch live requires flash

**Comment by dschneiderch** [comment] 2016-03-08 22:29
http://www.espnfc.us/ seems to require flash although http://espn.go.com/ does not.

**Comment by mdkberry** [comment] 2016-03-09 07:43
cmcmarkets.com.au trading platform needs flash

**Comment by bbondy** [comment] 2016-03-16 18:54
This is our plan for Flash:
https://github.com/brave/browser-laptop/issues/1093

I'm keeping this open though, retitled as Flash support for site X? for now to track the sites we should add to that whitelist.

**Comment by DivineOmega** [comment] 2016-04-11 23:34
Excellent idea on restricting Flash use to predetermined white list.

**Comment by jbshirk** [comment] 2016-04-21 17:30
+1 for html5 (at least)

**Comment by osmestad** [comment] 2016-04-22 13:32
listen.tidal.com also requires Flash

**Comment by bbondy** [comment] 2016-04-22 13:42
Closing this in favour of this wiki:
https://github.com/brave/browser-laptop/wiki/Flash-and-Other-Non-Supported-Plugin-Sites-(Video-and-Non-Video)

And the actual work for this is being done here:
https://github.com/brave/browser-laptop/issues/1093

**Closed by bbondy** 2016-04-22 13:42 UTC

**Comment by stevenado** [comment] 2016-04-28 18:04
the next links doesn't work normaly:
http://ici.radio-canada.ca
the videos doesn't work there cause flash is not activated:
http://ici.radio-canada.ca/rdi
http://ici.radio-canada.ca/audio-video

http://ici.tou.tv/dans-l-oeil-du-dragon

it's a good idea to not activate flash, but can we get the video link to be able to play it directly with an external tool like vlc or mplayer?

**Comment by hucekes** [comment] 2016-05-05 07:03
Amazon Prime Music insists on Flash
Brave 0.9.3 Electron 37.7 Windows 10

**Comment by Copypasty** [comment] 2016-05-19 15:46
Well... I'm sure there's a very small market, but flash gaming sites don't work..
http://www.kongregate.com/
http://armorgames.com/
http://miniclip.com/games/en/
etc.

**Comment by 3CirclesChurchCommunity** [comment] 2016-05-21 15:56
Are you kidding?  No flash support means Brave is useless to me and many, many others.  When I go to Hulu, CBS/ABC/NBC news, or thousands of other sites I CAN'T PLAY A SINGLE VIDEO!!!  USELESS!

**Comment by luixxiul** [comment] 2016-05-21 17:14
> Are you kidding?

I believe 100% that the dev team is not kidding at all, quite serious. And also I believe that there are so many users who are quite serious too. As the comment above (https://github.com/brave/browser-laptop/issues/386#issuecomment-213432518) indicated, please add sites to the wiki. I'll lock the conversation for now.

**Comment by luixxiul** [comment] 2016-06-12 06:58
For the participants: 
> After some discussion on Slack and clarification with Chrome on their Flash plans, here's the latest proposal: https://github.com/brave/browser-laptop/wiki/Flash-Support-Proposal

https://github.com/brave/browser-laptop/issues/1093#issuecomment-224410536
