### ISSUE TITLE
Regression : Changing the number of visits is clearing the ledger site list

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5397] opened 2016-11-04 16:57 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When changing the advanced setting to change the number of visits, my ledger listing of sites visited was cleared.

**Expected behavior:**
If a site met the prior requirements and we have relaxed the constraints (less visits, less time) they should persist. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.8 RC1

- Steps to reproduce:
    1. Visit some sites and have them on the ledger list.
    2. Change the advanced setting from 5 visits to 2.
    3. Observer the ledger list.

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment] 2016-11-04 19:03
Its covered in #5200 which is marked as 0.12.9

**Comment by bbondy** [comment] 2016-11-04 20:18
marking as dupe of that and removing from 0.12.8.

**Closed by bbondy** 2016-11-04 20:18 UTC
Labels: feature/ledger, regression
