### ISSUE TITLE
Cannot add any bookmark in the "Other Bookmarks" folder

### ISSUE THREAD

**Issue by julien-l** [brave/browser-laptop#12018] opened 2017-11-17 18:27 UTC
### Have you searched for similar issues

Yes, related but not the same: #6607, #11893.

### Description

It is impossible to create folders and bookmarks in the "Other Bookmarks" folder.

### Steps to Reproduce

  1. Open the Brave bookmark manager.
  2. Right click on the "Other Bookmarks" folder.
  3. Click "Add Bookmark" (or "Add Folder").
  4. In the creation dialog, the "Folder" drop down list does not contain the "Other Bookmarks" entry.

**Actual result:**

There is no entry for the "Other Bookmarks" in the bookmark creation menu:
![image](https://user-images.githubusercontent.com/1530763/32962455-5b84a76a-cb81-11e7-9119-b73e2b3ea5a5.png)

**Expected result:**
There should be an entry "Other Bookmarks" in the folder drop down menu, next to "Bookmarks Toolbar".

**Reproduces how often:**

Always

### Brave Version

**about:brave info:**

 
Brave: 0.19.95 
rev: cc0ebadfd8950d1b5f454cb39c0c3a64028cc935 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.2.0 
OS Architecture: x64

**Reproducible on current live release:**

Did not try a live build.

**Comment by luixxiul** [comment] 2017-11-18 07:10
maybe duping to https://github.com/brave/browser-laptop/issues/4202?

**Comment by NejcZdovc** [comment] 2018-01-05 15:46
dupe of #4202

**Closed by NejcZdovc** 2018-01-05 15:46 UTC
Labels: feature/bookmarks, needs-info
