### ISSUE TITLE
Brave crashes when tabs are pinned(Intermittent issues)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3760] opened 2016-09-06 10:02 UTC
## Test plan

https://github.com/brave/browser-laptop/pull/10531#issue-250554691

----

**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Brave crashes when tabs are pinned on a clean install build

**Expected behavior:**
Should not crash when tabs are pinned
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.0 RC2 (Clean install)
- Steps to reproduce:
  1. Perform a clean install
  2. Open 5-6 tabs and start pinning each of them
  3. After pinning the first two-three tabs the next tab when pinned browser crashes
- Screenshot if needed:
- Any related issues:

**Comment by bbondy** [comment] 2016-09-06 14:28
Triage related question, is this reproducible with past versions as well?

**Comment by srirambv** [comment] 2016-09-06 15:55
No. Just happened on the RC2 build. Reinstalled and checked but doesn't happen

**Comment by bbondy** [comment] 2016-09-06 17:05
but if you try again with RC2 do you not reproduce as well? Is it more likely to happen in current build vs old builds?

**Comment by srirambv** [comment] 2016-09-06 17:46
Yes tried again with RC2. In fact installed RC1 and then ran RC2 build, then uninstalled completely and did a clean install of RC2 but no luck in reproducing the issue.

**Comment by srirambv** [comment] 2016-09-24 14:00
Able to reproduce consistently on 0.12.2 RC3 build by creating new session folder each time. Number of tabs varies each time the crash happens

![crash](https://cloud.githubusercontent.com/assets/17010094/18808914/5367a8ac-8267-11e6-9637-38309b3af55a.gif)

![crash1](https://cloud.githubusercontent.com/assets/17010094/18808919/69959ca6-8267-11e6-8693-cef337d58c8b.gif)

**Comment by jonathansampson** [comment] 2016-10-03 16:16
This issue was recently encountered by a user on Twitter:

> @brave @BrendanEich Started using Brave today and when I pin a tab the browser closes. It happened 2 times. I'm on Ubuntu 16 (https://twitter.com/ribeiroigao/status/782902088594522114)

**Comment by srirambv** [comment] 2016-10-06 04:00
Able to reproduce on 0.12.4 Preview 2 as well. After pinning 5 tabs browser crashed

**Comment by srirambv** [comment] 2017-01-19 15:16
Browser crashes on each tab that is pinned on 0.13.0 preview 9. Recording from installation 
http://sendvid.com/z4i8fk8z

cc: @bbondy

**Comment by luixxiul** [comment] 2017-01-19 15:22
Setting the next milestone in case it's serious issue

**Comment by bbondy** [comment] 2017-02-01 04:02
Can we mark this as a dupe of:
https://github.com/brave/browser-laptop/issues/6968
?

**Closed** 2017-08-29 07:57 UTC
Labels: crash, feature/pinned-tabs, QA/steps-specified, release-notes/include
