### ISSUE TITLE
Brave prevents the computer from shutting down (macOS-only)

### ISSUE THREAD

**Issue by louity** [brave/browser-laptop#1322] opened 2016-04-10 10:41 UTC
When brave is running on my mac, even if no window is open, when I try to shut my computer down i get this alert message (my computer in in French) (see comment below), which means : Brave interrupted shutting down. Quit Brave and re-try. 

So i have to go and  brave and do a <cmd> + Q to quit brave to be able to shut down the computer.

**Comment by louity** [comment] 2016-04-10 10:43
<img width="1280" alt="capture d ecran 2016-04-10 a 12 35 19" src="https://cloud.githubusercontent.com/assets/14196488/14409645/9663c112-ff19-11e5-9fa1-a933da3ef538.png">

**Comment by endeakidz** [comment] 2016-04-10 13:04
I got this error too

**Comment by 1F506** [comment] 2016-04-16 18:44
can't shut down or log out.

**Comment by luixxiul** [comment] 2016-05-15 05:04
Reproducible? CC'ing @bbondy

**Comment by bbondy** [comment] 2016-05-15 22:45
I think this was fixed with 0.9.6, but please re-open if you still see it.

**Comment by Hazz223** [comment] 2016-05-28 10:39
Hi, I'm running 0.10.0 and found this is still an issue.

**Comment by bbondy** [comment] 2016-05-29 13:49
@bridiver do you think your shutdown fixes will solve this?

**Comment by bbondy** [comment] 2016-05-29 13:49
0.10.2

**Comment by bbondy** [comment] 2016-05-29 14:31
Let's mark as completed for 0.10.1 because there's work here and if it still fails after that we'll reopen

**Comment by bridiver** [comment] 2016-05-29 15:58
this doesn't seem to be related to the shutdown issue because Brave is still visibly running. Perhaps it's not responding to the OS shutdown notification? SIGTERM probably?

**Comment by bbondy** [comment] 2016-05-29 20:58
I was assuming we're getting a quit but we aren't actually quitting.

**Comment by bbondy** [comment] 2016-05-29 20:59
I tried to repro and couldn't before by the way.

**Comment by bbondy** [comment] 2016-07-11 17:24
has anyone seen this again?

**Comment by bridiver** [comment] 2016-07-11 20:10
I was able to replicate last time I tried and I believe this is the problem
```
- (NSApplicationTerminateReply)applicationShouldTerminate:(NSApplication*)sender {
  atom::Browser* browser = atom::Browser::Get();
  if (browser->is_quiting()) {
    return NSTerminateNow;
  } else {
    // System started termination.
    atom::Browser::Get()->Quit();
    return NSTerminateCancel;
  }
}
```

**Comment by bridiver** [comment] 2016-07-11 20:18
it should return `NSTerminalLater` and call `[NSApp terminate:nil]` when shutdown is complete

**Comment by Liunkae** [comment] 2017-01-28 06:48
Is this something that needs to be fixed on the Muon side?

**Comment by bsclifton** [comment] 2018-07-31 07:50
Closing as stale since there haven't been any reports. I haven't experienced this myself- please reopen if you do experience this 😄

**Closed by bsclifton** 2018-07-31 07:50 UTC
Labels: OS/macOS
