### ISSUE TITLE
Hide the menu bar by default stopped working

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#5086] opened 2016-10-24 16:29 UTC
**Did you search for similar issues before submitting this one?**

No

**Describe the issue you encountered:**

Enabling "Hide the menu bar by default" from settings has no effect when you launch new Brave instance.

**Expected behavior:**

Should happen what the setting name suggests.
- Platform (Win7, 8, 10? macOS? Linux distro?): Fedora 24
- Brave Version: https://github.com/brave/browser-laptop/commit/8b00d062f7921dcd3a26a6cd80b6b8529a5830fe
- Steps to reproduce:
  1. Enable "Hide the menu bar by default"
  2. Close Brave
  3. Open Brave
- Screenshot if needed:
  http://webm.land/media/u1Na.webm
- Any related issues:

**Comment by bsclifton** [comment] 2016-10-24 23:59
Works great on Windows; let me try it out on my Ubuntu VM...

**Comment by bsclifton** [comment] 2016-10-25 00:19
I tried on Ubuntu and menu works... but I had forgotten that Unity always shows a system menu (instead of the per-window menu):
![screen shot 2016-10-24 at 5 17 45 pm](https://cloud.githubusercontent.com/assets/4733304/19668639/f90b5eb2-9a0d-11e6-8211-2613c5c35657.png)

I'll have to setup a Fedora VM later tonite and give it a shot

**Comment by bsclifton** [comment] 2016-10-25 00:23
@Sh1d0w can the issue be with the theme you're using? Do you have more information on that? So you're running Fedora 24, which uses Gnome 3 by default... Gnome should be showing the menu at the top of each Window, not at the top of the window manager (ex: where macOS and Ubuntu show it)

**Comment by Sh1d0w** [comment] 2016-10-25 03:50
@bsclifton No it is not from the theme the same applies if I switch back to the default one for Gnome 3.

The setting is working as you can see in the video if I flip the switch off/on again. The problem is that it is not working during first launch (also same applies if I open a new window with CTRL + N).

Please take a look at the video I have captured http://webm.land/media/u1Na.webm

I guess there is a race condition between initial window initialization and the loading of the settings.

**Comment by Sh1d0w** [comment] 2016-10-25 04:21
PS. I think this might be related issue, since it also seems like race condition on startup:

https://github.com/brave/browser-laptop/issues/5109

**Comment by Sh1d0w** [comment] 2016-10-25 05:16
After short investigation it seems the problem is not in the settings. It correctly sets the setting value to true or false.

I think the problem is on Electron side. From the docs:

    autoHideMenuBar Boolean - Auto hide the menu bar unless the Alt key is pressed. Default is false.

If it is `true` then the menu should be hidden, but it is not.

**Comment by bsclifton** [comment] 2016-11-06 07:10
Thanks for the research, @Sh1d0w :smile: I'm going to remove the regression tag and add upstream tag.  Also going to remove from the milestone for the time being. However, I would be up for helping if you (or anyone else) wanted to grab this :smile: It's possible it's already been fixed upstream and we could pull in a commit that fixes it into our brave/electron fork

**Comment by linuxhelmet** [comment] 2016-12-22 17:45
I've tested Brave on several different distros and found that this problem persists regardless the desktop environment on Linux.  Two things I have found while testing this.  One, if you open another window in front of brave after it starts then switch back to brave it will then hide the menu bar. Two, it may have been mentioned but toggling the "hide menu" option does also work.  

I'm no dev but two crude ways to fix this issue would be to either have an invisible window open then close in front of brave after it starts, or have brave start with the hide menu option off then set a script to toggle this option on after startup.

**Comment by srirambv** [comment] 2016-12-28 22:42
![image](https://cloud.githubusercontent.com/assets/17010094/21532581/703586fc-cd49-11e6-8a77-83e1c642645e.png)

This happens on any of the Linux distros which doesn't run Unity. This is on Gnome Debian

**Comment by ChillyHellion** [comment] 2017-04-28 23:55
Seems to happen on any version of Linux running Gnome Shell.  I can reproduce this in Fedora 25 running Gnome 3.22.2.  Going into Brave Browser preferences, turning "hide the menu bar by default" off and then on again will fix the issue.  Also pressing alt will successfully hide the menu bar.  Both of these fixes only work until the next time Brave Browser is launched.  

It's annoying because like Firefox, Brave Browser uses the default GTK system bar at the top of its window which already takes up a lot of screen space.  I don't know how Google Chrome avoids this, but I wonder if Chrome's solution could be replicated in Brave.

**Comment by bsclifton** [comment] 2017-06-05 07:28
+1 from https://github.com/brave/browser-laptop/issues/8293

**Comment by eljuno** [comment] 2017-06-21 20:43
+1 from community

> The only issue I'm currently experiencing is that when I open Brave, the menu bar is showing, even though I have selected that it should be hidden. It does disappear once I press alt, which is fine.

Brave: 0.17.4 
rev: 39c7a5325beafb71ce3475a1bc43c3b6f99b4282 
Muon: 4.1.2 
libchromiumcontent: 59.0.3071.104 
V8: 5.9.211.35 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: linux 
os.release: 4.9.33-1-MANJARO 
os.arch: x64

**Comment by JGH1000** [comment] 2017-06-27 10:28
+1 on Elementary OS

**Comment by skullscream** [comment] 2017-06-27 18:26
+ I have no idea where to disable the menu bar in the preferences? I can hide it with alt but it's not permanent.

**Comment by ChillyHellion** [comment] 2017-06-27 21:14
@skullscream , you can hide the menu bar either by pressing alt or by selecting "Hide the menu bar by default" in Brave's Preferences, under General; however, the issue is that Brave seems to forget this setting whenever its closed and reopened - at least in Gnome shell - causing the menu bar to show up again no matter what method you used to hide it.  

As for your side question, Brave does support sync but I haven't used it, so hopefully someone can correct any details I might have wrong:

Brave does have a sync option in Preferences that supports all desktop versions of Brave - not yet Brave mobile - and all data sent by sync is encrypted and decrypted at the browser level before being stored.  You can find more information here: https://github.com/brave/sync/wiki/Design

**Comment by skullscream** [comment] 2017-06-28 06:15
Yeah I know about the sync but what if I somehow lose my system or hard drive fails for example, I would be lost without my bookmarks if they aren't stored somewhere on cloud safely.

'Hide menu bar by default' unhides it actually, doesn't matter if it was hidden before or shown. It's like it locks it in place.

**Comment by luixxiul** [comment] 2017-06-28 06:52
which desktop environment?

**Comment by skullscream** [comment] 2017-06-28 07:52
Me? Budgie.

**Comment by JGH1000** [comment] 2017-08-10 07:57
Any update on this? A bit annoying..

**Comment by keithkeekw** [comment] 2017-08-14 13:31
Brave: 0.18.14 
rev: ad92d029e184c4cff01b2e9f4916725ba675e3c8 
Muon: 4.3.6 
libchromiumcontent: 60.0.3112.78 
V8: 6.0.286.44 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Linux 
OS Release: 4.12.5-1-ARCH 
OS Architecture: x64

DE: Gnome DE

**Comment by luixxiul** [comment] 2017-08-16 13:23
I experience the same issue. By re-enabling the option after restart, the option starts working.

Brave: 0.18.23 
rev: 36ae2ec06efed0057ae16351108bf4d4c10a7ab4 
Muon: 4.3.10 
libchromiumcontent: 60.0.3112.90 
V8: 6.0.286.52 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Linux 
OS Release: 4.9.0-3-amd64 
OS Architecture: x64

**Comment by rBurgett** [comment] 2017-08-19 14:35
I have used Brave for a long time on Windows and macOS, but I just moved to Ubuntu Gnome and it has gotten really old really fast having to manually flip off the menu over and over again. I hope this can be fixed soon.

Brave: 0.18.23
rev: 36ae2ec
Muon: 4.3.10
libchromiumcontent: 60.0.3112.90
V8: 6.0.286.52
Node.js: 7.9.0
Update Channel: dev
OS Platform: Linux (Ubuntu Gnome 17.04)
OS Release: 4.10.0-32-generic
OS Architecture: x64

**Comment by bsclifton** [comment] 2017-08-21 16:12
Tentatively bumping up to 0.21.x since this is a long standing issue and it's quite annoying

**Comment by eljuno** [comment] 2017-09-06 22:52
+1 from community https://community.brave.com/t/noscript-approach/7240/3?u=eljuno

> my menu bar keeps showing every time I close & reopen the browser, even when I chose to hide it.

**Comment by Jarkolov** [comment] 2017-09-10 10:22
> +1 from community https://community.brave.com/t/noscript-approach/7240/3?u=eljuno
I'm the one who posted from Community. For more details (in case it helps), my OS is the following:
Kubuntu 16.04 x64
KDE Plasma 5.8.7
KDE Frameworks 5.36.0
Qt 5.6.1

Greetings!

**Comment by peakgeek** [comment] 2017-09-15 17:49
Same issue here. It would be great to get his fixed. I've been actively supporting and promoting Brave for the last year, and I find myself using Brave less and less because the menu toggle is a major nuisance. Only started happening with the last few revisions (0.17+). 

Elementary OS 0.4.1
Linux 4.10.0-33-generic
GTK+ 3.18.9

Brave | 0.18.36
rev | 7ab85e9
Muon | 4.3.22
libchromiumcontent | 61.0.3163.79
V8 | 6.1.534.32
Node.js | 7.9.0

**Comment by Jacalz** [comment] 2017-10-21 07:21
+1 from me on Ubuntu Budgie and Ubuntu 17.10 using gnome

**Comment by Jacalz** [comment] 2017-10-21 07:22
This is really annoying especially when Unity is no longer maintained by Canonical at Ubuntu 👎

**Comment by thinkjanis** [comment] 2017-11-02 14:04
Same issue for me. Using Ubuntu 17.10(Gnome) and Ubuntu Budgie 17.10.

Also, when a tab gets pulled out from a Brave instance where the menu bar is hidden, the new window session with the pulled tab shows the menu bar again.

Brave | 0.19.80
rev | 7d07299
Muon | 4.5.13
libchromiumcontent | 62.0.3202.75
V8 | 6.2.414.36
Node.js | 7.9.0
Update Channel | Release
OS Platform | Linux
OS Release | 4.13.0-16-generic
OS Architecture | x64

**Comment by thinkjanis** [comment] 2017-11-03 12:56
Noticed that when Brave is launched, the menu is shown as described above but when the Brave app window is not active (e. g. switching to a different app), the menu bar disappears.

**Comment by BlackRabbit22** [comment] 2017-12-03 00:17
Same thing is happening to me and I'm on ubuntu. Please fix this.

**Comment by Redrobo66** [comment] 2017-12-04 20:11
Same here using Linux Lite 3.6 (XFCE).
I don't mind the menu so much but I use a dark theme and therefore it displays very dark gray text against a back background - looks ugly so hiding it is pretty much essential.

**Comment by OldW1zzrd** [comment] 2017-12-13 03:02
I'm also experiencing this problem. Whenever Brave is reopened, menu bar will be open by default. Even when you go into settings and the "Hide menu bar by default" is already toggled. Toggling it will fix it for the session, but menu bar will be open again when Brave is restarted. 

My system info:
OS _ Linux Mint 18.3 Cinnamon 64-bit
Cinnamon Version _ 3.6.6
Linux Kernel _ 4.10.0-40-generic

Glad the issue is open. Hope is gets resolved! 

Thanks,
OldW1zzrd

**Comment by eljuno** [comment] 2018-01-01 17:31
+3 from community https://community.brave.com/t/hide-the-menu-bar-by-default-setting-is-glitchy/10217?u=eljuno

**Comment by jorkki000** [comment] 2018-01-04 10:30
Same here on Archlinux with openbox. As a workaround I start brave with:
`brave & xte 'sleep 3' 'key Alt_L'`

**Comment by eljuno** [comment] 2018-01-08 19:11
+2 from community https://community.brave.com/t/forward-and-backward-buttons-on-mouse-and-hide-the-menu-bar-by-default-do-not-work-in-brave-on-ubuntu-17-10/13159?u=eljuno

**Comment by bsclifton** [comment] 2018-01-16 18:38
+1 from @insanerwayner
> When I open the Browser it shows the menu bar. I have to right click and put the checkmark on to active the menu bar then right click again to to turn it off, then the menu bar disappears.

and +1 from @hyph3n
> I'm seeing the same behavior on 0.22.0.

**Comment by Mando75** [comment] 2018-02-07 01:40
+1 on Arch Linux running Gnome 3.26.2
It is very annoying

No problem when running on the latest build of Windows 10

**Comment by eljuno** [comment] 2018-02-18 19:01
+1 from community https://community.brave.com/t/menu-bar-showing-on-restart-crash-to-desktop-when-clicking-it/16347?u=eljuno
>Brave	0.20.42
V8	6.4.388.41
rev	096c7cb
OS Release	4.15.3-2-ARCH
Update Channel	Release
OS Architecture	x64
OS Platform	Linux

**Comment by srirambv** [comment] 2018-02-19 03:44
+1 from @ryanmusante via #13179

**Comment by Swashed** [comment] 2018-02-26 12:21
1 year and half after still no solution?

**Comment by Jacalz** [comment] 2018-03-02 14:13
Yeah, this is getting terribly annoying 😐

**Comment by ho3ein-mola** [comment] 2018-03-10 12:30
same problem here . installed by snapy.

**Comment by Dietbrand** [comment] 2018-04-29 20:29
+1
Still happens in Ubuntu Bionic Mate. Installed as a snap

**Comment by eljuno** [comment] 2018-06-03 19:13
+1 from community https://community.brave.com/t/menu-bar-opens-automatically/23192?u=eljuno

**Comment by srirambv** [comment] 2018-06-18 17:48
+1 from https://community.brave.com/t/starting-brave-beta-shows-menu-bar/24111

**Comment by srirambv** [comment] 2018-06-18 17:50
Also this issue would be fixed on brave-core. @bsclifton safe to close this issue?

**Comment by bsclifton** [comment] 2018-06-18 18:06
@srirambv I may be able to deliver a fix for this.  Let's keep it open

**Comment by bsclifton** [comment] 2018-08-13 17:51
This is a super annoying bug, but unfortunately I don't think we'll be able to address it before moving to [brave-core](https://github.com/brave/brave-browser)

**Closed by bsclifton** 2018-08-13 17:51 UTC
Labels: OS/unix-like/linux, fixed-with-brave-core, muon, priority/P3, settings, wontfix

**Comment by bsclifton** [comment] 2018-08-24 06:46
For folks that are willing to try an experimental build, you can grab a copy of brave-core (where this is no longer an issue) from here:
https://github.com/brave/brave-browser/releases
