### ISSUE TITLE
Add Bookmark main button is very slow almost unresponsive

### ISSUE THREAD

**Issue by Geoplace** [brave/browser-laptop#10846] opened 2017-09-07 15:06 UTC
- Did you search for similar issues before submitting this one?
Yes, I search "Add bookmark", is:open is:issuer in:title, body

- Describe the issue you encountered:
1. Click the Star button (top left corner, next to the address bar)
2. The pop-up window takes more than 30-45 seconds to show up.
3. The folder field takes another 30-40 seconds more to show the drop down list.
4. When you clic at Title field you have to wait the browser to respond to modify it.
5. When you clic the Ok button, the same long wait happend.

EXPECTED: More responsive ADD bookmark.

Maybe it's related with a second issued of the EDIT bookmark.

1. Open the Bookmarks Manager.
2. Select a bookmark.
3. Right click and select EDIT bookmark.
4. The same and slugish behavior happend.
5. When I change the bookmark folder it creates a NEW bookmark.
6. The original bookmark stays unchanged.
7. Now I have twice the same bookmark.

EXPECTED: The orginal bookmarks moves to the other assigned FOLDER.

Screen shot of the slow Response (Editing)
![image](https://user-images.githubusercontent.com/8289274/30169134-1b16bf0e-93b1-11e7-848b-7124fbcb2855.png)

> Brave: 0.18.30 
> rev: 795cc102729fc843ea82757c9e9508242fd5830e 
> Muon: 4.3.17 
> libchromiumcontent: 61.0.3163.71 
> V8: 6.1.534.31 
> Node.js: 7.9.0 
> Update Channel: dev 
> OS Platform: Microsoft Windows 
> OS Release: 6.3.9600 
> OS Architecture: x64

- I have around 100 folders arranged at up to 3 levels, (Imported from firefox)
- I have arond 2000 to 3000 bookmarks (I don't know how to count it automatically)

- Is this an issue in the currently released version?
The current 07-Sep-2017 Version has these issues.

- Can this issue be consistently reproduced?
Yes this happend always.

**Comment by Liunkae** [comment] 2017-09-07 15:30
This problem will probably be fixed in the next version, 0.19.x. (#9674)

**Comment by luixxiul** [comment] 2017-09-07 15:34
Agree. Closing in favor of #9674.

**Closed by luixxiul** 2017-09-07 15:34 UTC
Labels: duplicate, feature/bookmarks, perf

**Comment by luixxiul** [comment] 2017-09-07 15:41
@Geoplace After 0.19.x is released (which is not yet), please try again to see if the issue is fixed :-D thanks!

**Comment by Geoplace** [comment] 2017-09-07 17:21
Sure, I will try these vital functionality. 

A side note, today the not seen cursor start working. I update today but at first it didn´t work.
What I did before was dragging and drop a bookmark at the Bookmark manager and deleting a repeted one (I search for them)

Regards
