### ISSUE TITLE
HTTPSE not working correctly 

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12252] opened 2017-12-11 19:55 UTC
### Description
HTTPSE does not seem to be functioning correctly in C63 build. 

### Steps to Reproduce

  1. Clean profile on 0.19.113
  2. Navigate to https://https-everywhere.badssl.com/
  3. Open shields, turn off HTTPS Everywhere.
  4. View page which indicates HTTPSE is off.
  5. Change URL from https to http, page turns red.
  6. Go to shields, enable HTTPSE again.

**Actual result:**
Page remains Red and indicates that HTTPS Everywhere is off or not working.
![httpse019113](https://user-images.githubusercontent.com/28145373/33850754-e8f00d6a-de82-11e7-8e9b-bdfbc53b818e.gif)

**Expected result:**
Page should turn green as you have enabled HTTPS Everywhere again.
This is how this is working in 0.19.105

![httpse019105](https://user-images.githubusercontent.com/28145373/33850789-02abe148-de83-11e7-9369-8c2d94be0ad5.gif)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.19.113
rev | 043c506
Muon | 4.5.25

**Reproducible on current live release:**
no, not reproducible on 0.19.105

### Additional Information
Can also be reproduced with these steps:

  1. Clean profile on 0.19.113
  2. Navigate to https://https-everywhere.badssl.com/
  3. Disable shields.
  4. View page which indicates HTTPSE is off.
  5. Change URL from https to http, page turns red.
  6. Enable shields again. 
  7. Page remains red, indicates HTTPSE is off or not working.

Reproduced on Ubuntu by @kjozwiak 
Found on MacOS.

**Comment by bsclifton** [comment] 2017-12-11 20:35
Confirmed this works great on C62 using 0.19.x (basically, I reverted to Muon 4.5.16 and it works great)

**Comment by diracdeltas** [comment] 2017-12-12 00:16
@darkdh seems that the problem is that the tabId of the mainFrame request is set to `-1` after shields is disabled and enabled again

**Comment by bsclifton** [comment] 2017-12-12 04:40
Fixed with https://github.com/brave/browser-laptop/pull/12255

**Closed by bsclifton** 2017-12-12 04:40 UTC
Labels: 0.19.x, bug, feature/HTTPSEverywhere, regression
