### ISSUE TITLE
Image previews in file chooser

### ISSUE THREAD

**Issue by sirolf2009** [brave/browser-laptop#4013] opened 2016-09-14 22:32 UTC
When a file chooser opens, I would like to have a preview of the image/file I have selected.
E.g.
![pepe](http://i65.tinypic.com/rcr807.jpg)

**Comment by Liunkae** [comment] 2016-09-15 00:37
Linux-only?

**Comment by sirolf2009** [comment] 2016-09-15 13:36
I just tried the latest Brave version on windows, and it doesn't show previews either. I simply provided a linux example
![screenshot from 2016-09-15 09 34 39](https://cloud.githubusercontent.com/assets/3534736/18551776/ef869eba-7b27-11e6-947f-9eff08b68f71.png)

**Comment by srirambv** [comment] 2016-09-15 13:50
Works on Window. 
![image](https://cloud.githubusercontent.com/assets/17010094/18552248/8643d2d4-7b53-11e6-98cd-5d2d555f9ec4.png)
Even when View option is set to show icons never thumbnails
![image](https://cloud.githubusercontent.com/assets/17010094/18552284/a75d3da2-7b53-11e6-94bd-cc9a678e686f.png)

**Comment by Liunkae** [comment] 2017-01-27 17:34
This is still reproducible with Brave 0.12.15 on Linux Ubuntu 16.04. Here is a comparison:
Brave:
![brave](https://cloud.githubusercontent.com/assets/19424103/22380808/7cfc75ce-e484-11e6-8daf-a531e67b2623.png)

Firefox:
![firefox](https://cloud.githubusercontent.com/assets/19424103/22380809/815cea7c-e484-11e6-9b51-94426e2ab5d7.png)

It appears that Firefox uses a different type of open dialog.

**Comment by 9898287** [comment] 2017-07-25 00:08
Just tasted in GNU/Linux. The problem still exists. Major usability issue.

**Comment by Chiiruno** [comment] 2017-09-17 07:43
Still needs to be fixed...

**Comment by bsclifton** [comment] 2017-11-11 06:07
Closing as a dupe of https://github.com/brave/browser-laptop/issues/8854 (which has a better description)

**Closed by bsclifton** 2017-11-11 06:07 UTC
Labels: OS/unix-like/linux
