### ISSUE TITLE
Password notification shown on all tabs

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10200] opened 2017-07-29 18:35 UTC
- Did you search for similar issues before submitting this one?
No

- Describe the issue you encountered:
While verifying #10180, found that Password notification bar is  retained on all tabs

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.19.1
-- | --
rev | 2ee7a49
Muon | 4.4.4

- Steps to reproduce:
    1. Build bc70c2ed71d0f21d904e1b49951c4018488c3d85
    2. Follow steps mentioned in the PR, ensure all notification bars are shown on individual tabs
    3. Switch to tab with autoplay media notification, shows password notification also on the same tab
    
- Actual result:
See screenshot

- Expected result:
Notification bar should be tab specific

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Yet to verify

- Can this issue be consistently reproduced?
Yes 

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/28747358-bedf4570-7494-11e7-9584-4351e3a66c97.png)

- Any related issues:
cc: @cezaraugusto @jonathansampson 
Assigning milestone as per PR #10180

**Comment by kenorb** [comment] 2017-08-15 12:38
Duplicate of #7310

**Closed** 2017-08-31 14:27 UTC
Labels: bug, duplicate, feature/notificationbar, QA/steps-specified
