### ISSUE TITLE
seeing youtube#channel:{channelId} in the about:preferences#payments panel

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#13217] opened 2018-02-21 04:40 UTC
i don't have a STR, but i am still seeing this.

until we get a STR, can we at least have some code that runs when the panel becomes active to look for entries like this and resolve them back to reality, e.g., the underlying URL should be https://www.youtube.com/channel:UCQg4kOKdfzvsxHX4IjSzqTw instead of https://youtube/#channel:UCQg4kOKdfzvsxHX4IjSzqTw and perhaps we can get the actual name of the channel?

<img width="1395" alt="0" src="https://user-images.githubusercontent.com/400552/36463271-a985cc54-167d-11e8-889b-dad71fc14d61.png">

-----

STR
1. enable payments
2. go to https://www.youtube.com/channel/UCd534c_ehOvrLVL2v7Nl61w or https://www.youtube.com/channel/UCtinbF-Q-fVthA0qrFQTgXQ
3. watch video

**Comment by arsalankhalid** [comment] 2018-03-07 14:37
Happy to take this @NejcZdovc is it open?

**Comment by NejcZdovc** [comment] 2018-03-07 15:10
@arsalankhalid yeah but we don't have STR

**Comment by mrose17** [comment] 2018-03-07 15:49
we don't have a STR but i get it a lot. stop by later today and i'll show you what i see and maybe you an figure it out @arsalankhalid - thanks!

**Comment by mrose17** [comment] 2018-03-07 15:49
at the very least we can put in a fix when it does happen...

**Comment by arsalankhalid** [comment] 2018-03-11 19:21
Just caught up with this, happy to do that :) I don't believe I can easily stop by though, since I'm in Toronto. Luckily we can e-meet! I believe you guys use zoom, should we briefly chat there or on Discord?

**Comment by jasonrsadler** [comment] 2018-04-25 21:56
@mrose17 @NejcZdovc Current live release shows that we are getting channel names. Do we have an STR on this yet?

**Comment by mrose17** [comment] 2018-04-25 22:01
there is no STR. however, it happens to me several times a day.

**Comment by NejcZdovc** [comment] 2018-04-26 06:03
I manage to reproduce it and I have STR

**Comment by NejcZdovc** [comment] 2018-04-26 07:07
hmm can't reproduce it anymore :S

**Comment by NejcZdovc** [comment] 2018-04-26 08:35
will be fixed with this PR https://github.com/brave-intl/bat-client/pull/59

**Closed** 2018-04-26 14:12 UTC
Labels: PR/pending-review, feature/ledger

**Comment by srirambv** [comment] 2018-05-03 19:01
Verified on Windows x64 
* 0.22.702 e4a853d
* libchromiumcontent 66.0.3359.139
* muon: 6.0.7

Verified with the two publishers mentioned in original issue. Shows correct name.
