### ISSUE TITLE
Clean private tab on tab close

### ISSUE THREAD

**Issue by hmrodrigues** [brave/browser-laptop#6684] opened 2017-01-16 16:54 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When you close the last incognito tab, the browsing data is stored until the browser is restarted

**Expected behavior:**
Clean incognito browsing data on last incognito tab closed
- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux (Ubuntu 14.04) and Arch Linux
- Brave Version (revision SHA):
0.12.15
- Steps to reproduce:
    1. Open Private Tab
    2. Open page that stores cookies (In my case Odoo that saves login and seleted database)
    3. Close Private Tab
    4. Reopen Private Tab and page.
    5. Page finds cookies and does autologin

**Comment by diracdeltas** [comment] 2017-08-31 19:17
2 options
1. all private tabs that are open at the same time share the same session. when the last private tab is closed and then a new private tab is opened, the new private tab is in a new session. this would achieve the behavior described in this issue.
2. each private tab has its own session

i feel that #2 is more intuitive behavior and also easier for us to implmement

**Comment by diracdeltas** [comment] 2017-08-31 19:20
related: https://github.com/brave/browser-laptop/issues/597

**Comment by diracdeltas** [comment] 2017-08-31 20:22
@bbondy mentions the first option might be harder with tab opener relationships so we could try starting with option 2

**Comment by SilverPuppy** [comment] 2017-09-01 00:11
Having private tabs spawned from links in other private tabs share a session with the tab which spawned them would be expected behavior to most users. Having each private tab use its own session regardless of its origin would be annoying because if someone were signed in in the originating tab, the newly-spawned tab would not be, which would at the least require another sign-in unnecessarily. 

When a new private tab is opened manually, it should create a new session. It should share that session with all tabs descended from the original tab or its children. When the last tab in the session is closed, that session should cease to exist. Other private tabs with different sessions should keep their own sessions alive until the last tab in the session is closed.

From a privacy standpoint, option 2 is definitely preferable to the current implementation, provided that it is amended slightly to read "each private tab has its own session WHICH IS DESTROYED WHEN THE TAB IS CLOSED."

**Comment by diracdeltas** [comment] 2017-09-01 00:13
> @bbondy mentions the second option might be harder with tab opener relationships so we could try starting with option 1

oops, i originally switched options1 and 2 in this comment. it's been corrected.

**Comment by NumDeP** [comment] 2017-09-30 14:39
I'm curious, would the same set of rules apply to TPB as well?

I don't mean to go off topic but I mention this specifically as I think it does sort of pertain to this issue, particularly your 2nd option of each private tab having it's own session that is if you do apply the same rules to the TPB tabs as well when it comes to it during or after 1.2.

I think it's understood that New Private Tab and New Private Session Tab should be the only options available for TPB but when it comes to implementing it in Brave will it be called TPB New Tab and TPB New Session Tab, I only ask because it will be interesting to ascertain how you clever clogs juxtapose the New Tor Circuit on top of that or will the overall menu be changed to consolidate it? 

I imagine having the same session will be better in a privacy context because having a different set of IPs for each New Tab depending on what a user may be doing could be construed as fruitless.

There was an interesting report made by a German duo where they analysed mechanisms and lengths to which industries go to de-anonymizing user data. 
The researcher Dewes called “combinatorial deanonymization”, based on earlier research...published in 2007. This takes advantage of the fact that you only need around 10 URLs to identify someone uniquely – it turns out that people are very different in their browsing habits. So if there is additional information available that links data in those URLs to an identity, it is likely that all of the other URLs also relate to that person too.'

I can't speak to much about the validity of it, though you're probably already aware of it; the report is available on PIA's blog and here - https://community.brave.com/t/browser-extensions-disclose-personal-data/5305

Sorry for boring you; you're welcome to delete this comment if you don't think it aligns with the issue at hand. Thanks.

**Comment by bsclifton** [comment] 2017-12-22 20:04
Moving to 0.21.x since we aren't using Muon 4.6.x yet

**Comment by diracdeltas** [comment] 2017-12-26 20:17
@NumDeP Tor Private Tab will be a new tab type, independent of private/session tabs as they are currently implement. There will be no such thing as 'TPB New Session Tab'; i imagine there will just be a menu item for 'New TPB Tab'. 

My initial thinking on this was that TBP tabs would share the same session state but run in different Tor circuits (same to how tabs in Tor browser work right now). If a user wanted to clear all session state and use fresh circuits, there would be a 'New Identity' button.

**Comment by NumDeP** [comment] 2017-12-26 20:43
Thanks for the reply @diracdeltas 

This is just general curiosity and not a demand in case you think other wise - Why do you reckon not having a separate session will be less beneficial because personally I though it would operate exactly the way New Private Tabs operates currently except with a Tor node on top of it?

As for when a 'New Identity' is created, would I be right in assuming that the browser shouldn't restart  with or without normal session tabs though I suppose it wouldn't matter much if without other tabs alongside it.

Thanks

**Comment by LaurenWags** [comment] 2018-03-14 14:38
+1 via email

**Closed** 2018-09-18 22:30 UTC
Labels: feature/private-tabs, fixed-with-brave-core, priority/P4, wontfix
