### ISSUE TITLE
Youtube Embeded videos on sites does not work (Brave desktop)

### ISSUE THREAD

**Issue by pst1337** [brave/browser-laptop#14613] opened 2018-06-30 07:11 UTC
![static_image](https://user-images.githubusercontent.com/6471860/42122671-ab94e696-7c45-11e8-8b1d-4b8f4a71f546.PNG)

### Description
I have a problem with any site with youtube embeded video included. It's loaded static image whitch I cant open..

Thins I've already tried, but without success:
- set brave shield off
- turn off hardware acceleration
- clear all browser data
- on/off flash plugin
- off all plugins
- reinstall brave

### Steps to Reproduce

  1. Open For example site: https://www.spidersweb.pl/2018/06/apple-pay-wyniki-polska.html
  2. Try to watch youtube video from this site (i have only static message)
  3. Show me your settings or browser version if it works

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

OS: Win 10  x64

Brave | 0.23.19
-- | --
V8 | 6.7.288.46
rev | 178c3fb
Muon | 7.1.3
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Tor | 0.3.3.7 (git-035a35178c92da94)
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.87

**Reproducible on current live release:**

Is this a problem with the live build? It matters for triage reasons.
**Yes**

**Comment by eljuno** [comment] 2018-06-30 18:29
Duplicate of #13716.

**Closed** 2018-06-30 18:53 UTC
Labels: duplicate
