### ISSUE TITLE
"remember password" odd behavior

### ISSUE THREAD

**Issue by diegodoval** [brave/browser-laptop#2957] opened 2016-08-04 19:17 UTC
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
-on some sites the bar flashes in and disappears, on others it never shows up
-on developer.apple.com the 'remember this password?' bar flashes in and goes away. When logging out, it appears again. (verified multiple times, have screen recording if necessary)

That aside: sites that don’t show ‘remember password’ at all
citibank.com
imgur.com
gfycat.com

Sites that behave correctly:
reddit.com
amazon.com

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Mac 
- Brave Version:
  0.11.2
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues: #4276

**Comment by diracdeltas** [comment] 2016-08-04 19:53
the flashing-and-disappearing issue may be due to d1b09e40292c4b2c265c204cde5134827819c105 if the post-login URL is a different origin than the login page

**Comment by bsclifton** [comment] 2016-10-12 00:50
+1 from support
> When I use a new password and the pop-up asks me if I 
want to save it, the pop-up goes away too fast. I don't have enough time 
to drag my mouse over to answer yes.

**Comment by alexwykoff** [comment] 2016-10-19 07:48
+1 from support https://linkbubble.zendesk.com/agent/tickets/6209

**Comment by luixxiul** [comment] 2017-01-08 02:25
Another: https://community.brave.com/t/save-password-button-disappears-too-quickly/580

**Comment by diracdeltas** [comment] 2017-01-10 22:02
seems like a lot of complaints compared to the previous behavior where the password message box lingered until you closed it manually. i can change it back.

**Closed** 2017-01-10 22:15 UTC
Labels: feature/password-manager, info-needed

**Comment by bradleyrichter** [comment] 2017-01-10 22:25
@diracdeltas Is it now tab specific? Or window specific?

Perhaps it can auto-close when the domain changes instead of being page level?

**Comment by diracdeltas** [comment] 2017-01-10 22:32
> Perhaps it can auto-close when the domain changes instead of being page level?

that was the cause of this issue actually

**Comment by bradleyrichter** [comment] 2017-01-10 22:33
Ah..so the only choice is to keep it around until the tab is closed? (assuming it was not acted upon)

**Comment by diracdeltas** [comment] 2017-01-10 22:35
right now it doesn't close unless you close it. at the time this was implemented, there was no good way to specify a particular frame that the message box belonged to. may be possible now.

**Comment by luixxiul** [comment] 2017-01-16 18:41
Test plan: https://github.com/brave/browser-laptop/commit/b466a44394aeb204bbd5e96f5cef3bc59a8032db
