### ISSUE TITLE
Upload photo in linkedin issue

### ISSUE THREAD

**Issue by xixoft** [brave/browser-laptop#783] opened 2016-02-16 08:24 UTC
I have an issue when uploading photo to linkedin suddenly the browser has stopped working.

**Comment by diracdeltas** [comment] 2016-02-16 20:52
which version are you on? worked fine for me just now.

possibly same underlying issue as #784

**Comment by diracdeltas** [comment] 2016-02-17 18:06
marking this as dupe of https://github.com/brave/browser-laptop/issues/475

**Comment by bbondy** [comment] 2016-02-21 20:37
Closing

**Closed by bbondy** 2016-02-21 20:37 UTC
Labels: duplicate
