### ISSUE TITLE
Extra mouse buttons like previous/next have no effect in Brave

### ISSUE THREAD

**Issue by agilob** [brave/browser-laptop#11544] opened 2017-10-15 16:51 UTC
### Description
Extra mouse buttons like previous/next have no effect in Brave

### Steps to Reproduce
  1. Have a mouse with side buttons prev/back
  2. Click back
  3. nothing

**Expected result:**
Pressing back on mouse should move me to previous page in the same tab

### Brave Version

**about:brave info:**
```
Name | Version
-- | --
Brave | 0.19.48
rev | de939f6
Muon | 4.4.28
libchromiumcontent | 61.0.3163.100
V8 | 6.1.534.41
Node.js | 7.9.0
Update Channel | Release
OS Platform | Linux
OS Release | 4.13.5-1-ARCH
OS Architecture | x64
```

**Comment by Liunkae** [comment] 2017-10-15 22:19
Duplicate of #3101.

**Comment by bsclifton** [comment] 2017-10-16 04:46
Thanks for the report, @agilob 😄  I closed this issue since it's a duplicate and gave #3101 a bump on your behalf.  You can subscribe there for updates 😄

**Closed** 2017-10-16 04:45 UTC
