### ISSUE TITLE
Going to a webpage results in a blank window for a long long long time with NO feedback.

### ISSUE THREAD

**Issue by patrick99e99** [brave/browser-laptop#14363] opened 2018-06-09 01:31 UTC
### Description
This has been a bug since I started using Brave last year, and has driven me quite crazy.  It happens for both on the iOS and desktop versions of Brave.

I open a tab.. I put in a url.  the page is blank.. for 5-10 seconds.  There is no progress bar, spinner, or anything letting me know something is happening. 

**Actual result:**
<img width="1280" alt="screen shot 2018-06-08 at 6 25 47 pm" src="https://user-images.githubusercontent.com/28946/41186368-f5f1449e-6b49-11e8-8dfb-033232e587a8.png">

**Expected result:**
That the webpage loads sooner than 5-10 seconds, or Brave shows a spinner / progress indicator in the url bar to let me know stuff is loading.

**Reproduces how often:**

### Brave Version

**about:brave info:**
Brave: 0.22.727 
V8: 6.6.346.32 
rev: 2c94bbad00d70b87328f04574725979960e18f9f 
Muon: 6.0.12 
OS Release: 17.3.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Comment by bsclifton** [comment] 2018-06-15 08:31
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/14207 which was recently fixed with https://github.com/brave/browser-laptop/pull/14384 (but is not available yet). This will ship with version 0.23.x

**Closed by bsclifton** 2018-06-15 08:31 UTC
