### ISSUE TITLE
New Tab Always gets focus when "Switch to new tabs immediately" is disabled

### ISSUE THREAD

**Issue by rjventrone** [brave/browser-laptop#3068] opened 2016-08-10 00:08 UTC
Every time open a new tab it takes focus. Even when "Switch to new tabs immediately" is disabled.

Expected behavior:
I expect the new tab not to get focus when "Switch to new tabs immediately" is disabled. 
- Platform: 
  OSX 10.11.6 
- Brave Version: 
  0.11.3
- Steps to reproduce:
  1. make sure "Switch to new tabs immediately" is disabled
  2. ctrl + t

**Comment by bsclifton** [comment] 2016-11-26 09:33
I'm going to close this issue as `won't fix`, but I welcome feedback from folks
cc: @bradleyrichter @bbondy 

The "Switch to new tabs immediately" setting (if set to true) was intended to switch focus to a newly created tab when you middle click a link or click a link which has a target of _blank.  It's not related to what happens when you create a new tab.

This issue is specifically asking for that setting to be respected when opening a new empty tab by clicking the + in the tabs area or by pressing Ctrl + T / Cmd + T.  The impact would be: opening a new tab does not switch to it. You'd have to manually click the empty tab or use a keyboard shortcut to switch the tab

**Closed by bsclifton** 2016-11-26 09:33 UTC
Labels: wontfix
