### ISSUE TITLE
Suggestion: add a session manager

### ISSUE THREAD

**Issue by JIVS** [brave/browser-laptop#10453] opened 2017-08-13 04:11 UTC
I would suggest this feature to be built-in into Brave in the future

As for layout and functionality I think the Session Buddy extension for Chromium browsers is a good example of a session manager done right

Session sync would be a good feature too

**Comment by Liunkae** [comment] 2017-08-14 05:17
Related: #5388 (Create about:sessions for session-management)

**Comment by bsclifton** [comment] 2017-11-22 18:05
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/5388

**Closed by bsclifton** 2017-11-22 18:05 UTC
Labels: duplicate, suggestion
