### ISSUE TITLE
Brave keeps asking to be the default browser

### ISSUE THREAD

**Issue by GGurtner** [brave/browser-laptop#10295] opened 2017-08-04 09:12 UTC
- Did you search for similar issues before submitting this one?

Yes, there does not seem to be anything related to that

- Describe the issue you encountered:

Brave keeps asking if it should be the default browser even though it already is.

- Platform (Win7, 8, 10? macOS? Linux distro?):

Linux Mint 17.1 and 17.2

- Brave Version (revision SHA):

ad92d02

- Steps to reproduce:
    1. Set Brave as default browser
    2. Close all Brave windows
    3. Open Brave
    
- Actual result:

Get message to put Brave as default browser

- Expected result:

No more message

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Not tested with a fresh profile

- Is this an issue in the currently released version?

yes

- Can this issue be consistently reproduced?

yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

![brave-bug](https://user-images.githubusercontent.com/7604528/28962263-0ab84ade-78fd-11e7-9d24-cf3a0d9d9def.png)

- Any related issues:

**Comment by bsclifton** [comment] 2017-08-10 06:57
cc: @darkdh

**Comment by bsclifton** [comment] 2017-09-08 22:38
I believe this is a duplicate of https://github.com/brave/browser-laptop/issues/1336.  I'll close this so we can track there

**Closed by bsclifton** 2017-09-08 22:38 UTC
Labels: bug, settings

**Comment by darkdh** [comment] 2017-09-14 05:27
@GGurtner 
do you have `~/.local/share/applications/brave.desktop`?
If so, try to rename or remove it to see if the problem go away

**Comment by GGurtner** [comment] 2017-09-14 07:09
No, I have no such file (maybe that's the problem?).
