### ISSUE TITLE
Brave disappears on pinning thestar.com

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-laptop#831] opened 2016-02-19 20:34 UTC
- type thestar.com in urlbar and hit enter, it redirects to https://www.thestar.com;
- go to urlbar and edit the url to http://thestar.com and hit enter, it redirects to https://www.thestar.com;
- pin that tab.

**Comment by bbondy** [comment] 2016-02-19 21:28
Also happening with http://nytimes.com 
![Uploading Screenshot 2016-02-19 15.40.10.png…]()
You need to pin / unpin several times and then happens.

Seems possibly related to invalid urls.  CC @bridiver likely a crash in electron because front end code doesn't usually crash the browser.

**Comment by aekeus** [comment] 2016-02-20 15:55
This seems to be some type of race condition in the Electron code.

If I walk through the code in the debugger the pin / unpin does not cause an error. Breaking at the pin code then allowing the process to continue allows the crash to happen.

**Comment by aekeus** [comment] 2016-02-24 21:53
Fixed in 0.7.16. Cannot reproduce error.

**Closed by aekeus** 2016-02-24 21:53 UTC

**Comment by bridiver** [comment] 2016-02-24 22:16
not sure what fixed it, but great!

**Comment by bbondy** [comment] 2016-02-24 22:18
there was a ton of refactoring for pinned sites so could be something that we just aren't triggering anymore.

**Comment by aekeus** [comment] 2016-02-24 23:17
The best type of fixes!
