### ISSUE TITLE
Brave 0.13.2 on linux won't open links from external apps

### ISSUE THREAD

**Issue by jsgibson** [brave/browser-laptop#7237] opened 2017-02-14 11:23 UTC
- Did you search for similar issues before submitting this one?

I'd like to think I'm not the only person who has this issue and this is a dupe, but ... This has been an issue for me since 0.13.1.

- Describe the issue you encountered:

Links from external applications, (franz, kde, etc) open up a brave window, but will not actually follow the link.

- Platform (Win7, 8, 10? macOS? Linux distro?):

Manjaro KDE Linux. 16.10.2

- Brave Version (revision SHA):

 Brave: 0.13.2 
rev: 25b1199fb6154b089cbad37926483239495b9800 
Muon: 2.0.19 
libchromiumcontent: 54.0.2840.100 
V8: 5.4.500.41 
Node.js: 7.0.0 
Update Channel: dev 
os.platform: linux 
os.release: 4.9.6-1-MANJARO 
os.arch: x64

- Steps to reproduce:
    1. Click on a link in another application
    2. If brave is open, it comes to the front, but does not open the page
    3. If Brave is not open it opens and I get the speed dial page
    
- Actual result:

If brave is open, it comes to the front, but does not open the page
If Brave is not open it opens and I get the speed dial page

- Expected result:

Link opens in  a new tab/window in brave.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

I have not yet tried re-installing brave, I've been waiting to see if it corrected itself in an update or to find a fix somewhere online.

- Is this an issue in the currently released version?

Current AUR version has this issue.

- Can this issue be consistently reproduced?

Yes.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by aironou** [comment] 2017-02-15 02:32
Maybe, related: #6994

Creating a local bin for Brave, passing `--` before the URL argument, works for me.

**Comment by bsclifton** [comment] 2017-09-29 05:56
This should be working great now 😄  Closing this as a duplicate of https://github.com/brave/browser-laptop/issues/9193

**Closed by bsclifton** 2017-09-29 05:56 UTC
Labels: OS/unix-like/linux
