### ISSUE TITLE
Window Maximize/Restore needs better animation

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7959] opened 2017-03-29 11:13 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Window Maximize/Restore needs better animation

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.0
rev	e6fba42

- Steps to reproduce:
    1. Install 0.14.0 RC1
    2. Click on maximize button, window animation is bad
    3. Click on restore button from a maximized window, animation is horrible
    
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![maximize](https://cloud.githubusercontent.com/assets/17010094/24451968/f6be534a-1478-11e7-8437-ddf087d9a48d.gif)

- Any related issues:
#7825
cc: @bsclifton

**Comment by bsclifton** [comment] 2017-04-04 16:11
Closing this issue as a duplicate of https://github.com/brave/browser-laptop/issues/586

**Closed by bsclifton** 2017-04-04 16:11 UTC
Labels: misc/fullscreen-option, QA/steps-specified, regression, release/not-blocking
