### ISSUE TITLE
Minimize popup persists

### ISSUE THREAD

**Issue by svenified** [brave/browser-laptop#9599] opened 2017-06-20 15:27 UTC
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Clicking the minimize button on the top right of Brave browser before the popup "Minimize" appears, the main window will minimize ,however the minimize popup appears then persists over all other windows/desktop.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win7 Ultimate
- Brave Version (revision SHA):
Brave	0.16.9
rev	fba98fc
- Steps to reproduce:
    1. Click Minimize in top right before popup appears.
    2. When broswer minimizes, the popup appears, and won't fade.
    
- Actual result:
Popup persists and will not go away until browser is brought to focus.
- Expected result:
Popup should not appear if the window is already minimized.
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.
- Is this an issue in the currently released version?
Yes.
- Can this issue be consistently reproduced?
Yes.
- Extra QA steps:
    1. Popup successfully goes away if it is created BEFORE the window minimizes.
    2. Popup appears after window is minimized if button is clicked quickly enough.

- Screenshot if needed:
[https://i.imgur.com/vSYD0dZ.png](url)
- Any related issues:

**Comment by Liunkae** [comment] 2017-06-20 20:38
@svenified Thanks for the report! This is a duplicate of an existing issue, #8697. I'll close this issue and make a note in the other issue.

You can follow future progress by subscribing to that issue. This bug is expected to be fixed by version 1.0.0.

**Closed by Liunkae** 2017-06-20 20:38 UTC
