### ISSUE TITLE
Open html file with drag and drop

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#3819] opened 2016-09-08 12:28 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
In chrome and FF if you drag and drop an HTML file from a folder to the Browser header section (where the tabs are located) they correctly open the local file in a new tab so you can preview it.
In Brave this is currently not possible.

**Expected behavior:**
Brave should open local html files for preview via drag and drop.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  0.12.0
- Steps to reproduce:
  1. Open a folder containing html files
  2. Drag one of the to the Brave's header section
  3. Nothing happens

- Screenshot if needed:
- Any related issues:

## Test Plan:
1. Open folder with a local file
2. Drag and drop one to the header section
3. File is opened

**Comment by bsclifton** [comment] 2017-01-23 20:35
Fixed with https://github.com/brave/browser-laptop/pull/6404

**Comment by luixxiul** [comment] 2017-02-04 03:39
The file path is instead searched:

![searched](https://cloud.githubusercontent.com/assets/3362943/22615369/f0650fd2-ead6-11e6-93fc-3d65e5a59fab.gif)

**Comment by NejcZdovc** [comment] 2017-02-04 06:15
I see where the problem is. If you dnd on tab section it will be loaded correctly, but if you dnd it into URL bar, path will be searched. This of corse happens only when you add link that doesn have space in path for example. Will fix it.

**Comment by bsclifton** [comment] 2017-02-04 07:17
PR merged after confirming fix; It will be in the next RC 👍

**Comment by luixxiul** [comment] 2017-02-04 07:24
> if you dnd it into URL bar

Sorry for the bad gif demonstration, but the error can happen as well dragging the file onto the tab:

![dnd](https://cloud.githubusercontent.com/assets/3362943/22616733/69dd1bc4-eaf6-11e6-8338-03240f182212.gif)

**Comment by luixxiul** [comment] 2017-02-04 07:25
Reopened just in case; please close this if #7057 has fixed it too.

**Comment by alexwykoff** [comment] 2017-02-04 07:32
confirmed this is an issue in rc3 on win ia-32

cc: @bsclifton

**Comment by NejcZdovc** [comment] 2017-02-04 12:56
@alexwykoff @luixxiul this fix is not in rc3 yet, please try it in the next RC

**Comment by luixxiul** [comment] 2017-02-04 13:12
@NejcZdovc I thought you have fixed the drag and drop on the URL bar. I just wanted to make sure you have fixed the drag and drop on the tabs bar as well.

**Comment by NejcZdovc** [comment] 2017-02-04 13:26
Will try all scenarious and see if I can reproduce this with the latest code

**Comment by bsclifton** [comment] 2017-02-04 16:37
@luixxiul https://github.com/brave/browser-laptop/pull/7057 fixes the issue for sure; I didn't try the tabs bar

@NejcZdovc if it works as expected for you in master, please close out the issue 😄  Like @NejcZdovc is saying, this was fixed with the PR (https://github.com/brave/browser-laptop/pull/7057) so it's not in a release candidate yet

**Comment by bbondy** [comment] 2017-02-05 01:56
I think this works as it was spec'ed originally so I'm going to close this.

For follow up work though I posted this one as a spin off:
https://github.com/brave/browser-laptop/issues/7079

**Closed by bbondy** 2017-02-05 01:56 UTC
Labels: misc/drag-and-drop, QA/steps-specified, release-notes/include
