### ISSUE TITLE
Contribution notification message shows undefined text next to contribution value

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14410] opened 2018-06-14 19:24 UTC
### Description
Contribution notification message shows undefined text next to contribution value

### Steps to Reproduce

  1. Open brave with clean profile
  2. Add sites to ledger
  3. Perform contribution to added sites

**Actual result:**
After contribution the notification message shows undefined text next to contribution value

"Hello! Your contribution of 47.5 undefined has been processed. Thanks for supporting your favorite websites!"
![image](https://user-images.githubusercontent.com/38657976/41433310-1d00d324-7036-11e8-8fc2-e63e30a3b3f5.png)

**Expected result:**
Message should be displayed as "Hello! Your contribution of 47.5 BAT has been processed. Thanks for supporting your favorite websites!"

**Reproduces how often:**
Easy

### Brave Version
0.23.8
**about:brave info:**
 
Brave: 0.23.8 
V8: 6.6.346.32 
rev: 06c657bb7ee5530f93c37f51cc6b7bf158912d04 
Muon: 6.1.5 
OS Release: 10.0.17134 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.181

**Reproducible on current live release:**
No

**Comment by LaurenWags** [comment] 2018-06-14 20:59
Duplicate of https://github.com/brave/browser-laptop/issues/14417

**Closed by LaurenWags** 2018-06-14 20:59 UTC
Labels: duplicate
