### ISSUE TITLE
Submitting form crashes the browser consistently

### ISSUE THREAD

**Issue by DavidRBailey** [brave/browser-laptop#13954] opened 2018-04-26 15:26 UTC
### Description
Submitting an TripIt hotel edit form crashes the browser consistently.

### Steps to Reproduce

  1. Go to TripIt.com
  2. Attempt to edit hotel form and click submit.

**Actual result:**

Browser stops responding, color wheel of death, and crashes. Form is never actually submitted.

**Expected result:**
Completes the form submission successfully.

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

Brave 0.22.667
Mac OS X 10.13.4 (17E199)
MacBook Pro (15-inch, 2017)

**Reproducible on current live release:**

Unknown.

### Additional Information

Restarting browser doesn't resolve problem. Restarting computer doesn't resolve problem.

**Comment by srirambv** [comment] 2018-04-26 15:39
Dupe of https://github.com/brave/browser-laptop/issues/13947. Issue is already fixed and should be available soon.

**Closed by srirambv** 2018-04-26 15:39 UTC
