### ISSUE TITLE
Question: what is the state of HSTS preload support in brave?

### ISSUE THREAD

**Issue by agilob** [brave/browser-laptop#11599] opened 2017-10-18 20:17 UTC
I tried to search for hsts on github and there were no results.

 I would like to know if Brave makes use of [Mozilla](https://hg.mozilla.org/mozilla-central/file/tip/security/manager/ssl/nsSTSPreloadList.inc) or [Google](https://cs.chromium.org/codesearch/f/chromium/src/net/http/transport_security_state_static.json?cl=a846624a2b753809bc91e125c74332d8c8f9a2c0) HSTS preloads lists? Is HSTS preloading supported? Does Brave use the same code as Chrome for it?

**Comment by luixxiul** [comment] 2017-10-19 04:12
https://github.com/brave/browser-laptop/issues/1680#issuecomment-320075433

> we already support HSTS and HSTS preloading

**Comment by srirambv** [comment] 2017-10-20 10:55
Closing as the issue is marked as dupe. Can continue conversation and reopen if required

**Comment by agilob** [comment] 2017-10-20 16:31
Is still didn't get answers to my questions, so please continue...

**Comment by luixxiul** [comment] 2017-10-20 16:46
You got one answer that HSTS preloading was supported, so about the two which remain:

- if Brave makes use of Mozilla or Google HSTS preloads lists
- if Brave use the same code as Chrome for it

@diracdeltas: would you mind answering to the two? thanks!

**Comment by diracdeltas** [comment] 2017-10-23 21:16
We use the exact same as Chrome's preload list.

**Closed by diracdeltas** 2017-10-23 21:16 UTC
Labels: duplicate, question
