### ISSUE TITLE
Ctrl+click closes Brave Browser in Gmail

### ISSUE THREAD

**Issue by vinay898** [brave/browser-laptop#510] opened 2016-02-01 07:54 UTC
Under windows 10. 
When using gmail. on clicking a message with Ctrl key pressed ( to open in a new window ) closes the browser.

**Comment by bbondy** [comment] 2016-02-01 12:24
Duplicate of https://github.com/brave/browser-laptop/issues/412 which will be fixed in 0.7.12 coming out today.

**Closed by bbondy** 2016-02-01 12:24 UTC
