### ISSUE TITLE
Stop auto play on ALL videos

### ISSUE THREAD

**Issue by AnthoniG** [brave/browser-laptop#8432] opened 2017-04-21 22:58 UTC
Is it possible to turn off (via an option or plugin etc) to stop ALL videos from auto playing, no where they are.

For example go here http://www.wpmarketertools.com/autotube-2/ and it starts playing the video and I do not want it to. Especially if I have multiple tabs open then all the videos start playing and the voices overlap.

It's really **infuriating**.

**Comment by Liunkae** [comment] 2017-04-22 17:06
@AnthoniG Thanks for the report! I'll close this as a duplicate of #2227 (Block autoplay videos). Please subscribe to that issue for any further updates. See also #4045 (Add option to enable/disable HTML5 autoplay) and #7663 (All video in Brave should default with autoplay=false, w/site level opt-in exceptions).

**Closed by Liunkae** 2017-04-22 17:06 UTC
