### ISSUE TITLE
Delete history entry gets added back 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9715] opened 2017-06-26 13:45 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Delete history entry gets added back when sync is enabled

- Platform & Brave Version (revision SHA):
0.17.9 (Pyramid 0) - Windows 10x64
rev	2606974
Muon	4.1.4

  0.17.6 (Pyramid 1) - Debian 8.0
  rev	30a3eee
  Muon	4.1.2

- Steps to reproduce:
    1. Enable Sync on Pyramid 0
    2. Sync pyramid 1 with pyramid using code words
    3. Enable browsing history on both pyramids
    4. Visit a site and ensure the history entry shows up on both devices
    5. Delete history entry on pyramid 0, adds an entry after the oldest history entry without date
    6. Delete history entry on pyramid 1, same as previous step
    
- Actual result:
Delete history entry gets added back when sync is enabled

- Expected result:
Should only delete and not add back

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Not sure need to check on older builds

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![bmk_sync](https://user-images.githubusercontent.com/17010094/27541829-45104c48-5a7d-11e7-98b4-b84e36804939.gif)

- Any related issues:
cc: @bsclifton please change milestone if required

**Comment by ayumi** [comment] 2017-06-26 18:06
fwiw almost nobody syncs history because that's the default

**Comment by diracdeltas** [comment] 2017-07-12 00:23
I see the same bug on a fresh profile without sync enabled. If you click 'delete history entry', the history entry just gets added back at the bottom of the list.

**Comment by bsclifton** [comment] 2017-07-12 01:08
Similar behavior reported with https://github.com/brave/browser-laptop/issues/9736

**Comment by bsclifton** [comment] 2017-07-12 23:55
@srirambv does this clear if you exit the browser? I believe the root cause is that history isn't cleared until you exit the browser (see https://github.com/brave/browser-laptop/issues/9736)

**Comment by Liunkae** [comment] 2017-07-13 00:03
I think this is a duplicate of #8761

**Comment by bsclifton** [comment] 2017-07-13 00:04
@Liunkae good find! Possibly also the same as https://github.com/brave/browser-laptop/issues/9736 and https://github.com/brave/browser-laptop/issues/9715

**Comment by srirambv** [comment] 2017-07-13 08:12
@bsclifton quitting and restarting the browser doesn't clear the history unless clear history on exit is set

**Comment by diracdeltas** [comment] 2017-07-13 19:03
closing as duplicate of https://github.com/brave/browser-laptop/issues/8761 since the behavior is the same with and without sync enabled

**Closed by diracdeltas** 2017-07-13 19:03 UTC
Labels: bug, feature/history, feature/sync, info-needed
