### ISSUE TITLE
Dashlane plug-in doesn't work on Windows 10

### ISSUE THREAD

**Issue by iamaya** [brave/browser-laptop#13479] opened 2018-03-16 18:35 UTC
### Steps to Reproduce

  1. Open Preferences -> Extensions
  2. Turn On Dashlane Plugin
  3. Dashlane icon (greyed out) shows up in the top bar
  4. Opens an empty tab when clicked on the Dashlane icon and nothing happens

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by eljuno** [comment] 2018-03-16 18:58
Duplicate of #13384. :)

**Comment by Tomatoshadow2** [comment] 2018-03-16 19:17
Also in the other bug comments, post what Brave version you are using.

**Closed** 2018-03-18 07:35 UTC

**Comment by yar05** [comment] 2018-05-06 14:40
[ Posting here as it appears first in google results ]

To fix this problem :

Open : https://app.dashlane.com in the brave browser as normal page, log in, restart browser.
Extension should start working.

If that doesn’t work :

type chrome-extension://fdjamakpfbbddfjaooikfcpapjohcfmg/login in the address bar then log in. Restart browser.

Extension should be working now.

PS. got few core dumps on linux trying to user the extension so might actually be unstable.
