### ISSUE TITLE
Bug : Brave Suddenly shows full white page

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1671] opened 2016-05-11 06:52 UTC
Hello Dev Team,

The browser suddenly shows full white blank page and all tabs and toolbars are not accessible.
This happened when i was accidently moving a hyperlink.

OS : windows 7 64 bit (SP1)
Brave : 0.9.4

As you can see below:

![bravesuddenlystopped](https://cloud.githubusercontent.com/assets/17910355/15172320/12d84694-175e-11e6-88f4-810083020cb0.png)

**Comment by diracdeltas** [comment] 2016-05-11 14:26
Do you remember where you dragged the hyperlink?

**Comment by Haze-Aulaian** [comment] 2016-05-11 14:36
@diracdeltas , i dragged exactly 5 pixels to the right corner from its placed position in the screen it was a bit in the middle , i didnt drag it to the to the tab or the url section if this is your question.

**Comment by Haze-Aulaian** [comment] 2016-05-16 10:15
@diracdeltas  

i was able to reproduce the issue and found out when its triggered.

1- highlight any amount of a text in the webpage.
2- Hit Ctrl+C.
3- Drag the highlighted text anywhere in the page and boom , the browser becomes plain white.

**Comment by bbondy** [comment] 2016-05-16 13:56
Can you confirm if your steps to reproduce are consistent or not? I have seen this happen before but I can't reproduce when I try 99% of the time.

**Comment by Haze-Aulaian** [comment] 2016-05-16 13:57
@bbondy  yes its consistent i can reproduce it many times as you want.

**Comment by bbondy** [comment] 2016-05-16 13:59
So I tried on this github page with text in your steps to reproduce, that reproduces for you too?

**Comment by Haze-Aulaian** [comment] 2016-05-16 14:00
@bbondy yes i did that , tried on facebook , tried on jiveon.com

**Comment by bbondy** [comment] 2016-05-16 14:05
Darn, I really want steps to reproduce but I tried on both OS X and Windows 7 x64 and cannot reproduce following the steps above.  Which version of windows are you using?

**Comment by Haze-Aulaian** [comment] 2016-05-16 14:05
@bbondy  64bit sp1

**Comment by luixxiul** [comment] 2016-05-16 14:06
Might be related with a video driver?

**Comment by Haze-Aulaian** [comment] 2016-05-16 14:07
will try it with my windows 7 32bit later and report it back , im using Nvidia 5400m NVS

**Comment by diracdeltas** [comment] 2016-05-16 18:57
@Haze-Aulaian thanks. one more thing - are you able to open the browser devtools (ctrl+alt+j) after the page goes blank? if so, what is the value of `window.location.href`?

**Comment by Haze-Aulaian** [comment] 2016-05-16 21:25
@diracdeltas @bbondy , i found out that this is triggered when i copy text from jiveon.com.
if i dont load that site or use it the issue doesnt happen thats why you are not able to reproduce it at your end.but a user on issue #1782 has mentioned that he experienced the same in a different behavior. and you can see below when i reproduce it the dev tools is not able to do anything:

![whitepage](https://cloud.githubusercontent.com/assets/17910355/15304374/ab4ce2de-1bc5-11e6-9614-f73983196d8e.PNG)

**Comment by Haze-Aulaian** [comment] 2016-05-16 21:58
to add , the bug will not get triggered if i open the dev tools before i reproduce it.
which makes it more confusing :S

**Comment by diracdeltas** [comment] 2016-05-24 06:18
this may be partially fixed by https://github.com/brave/browser-laptop/commit/dd62f0538398ed45e44d57bc3469a3b5e2ce8571

**Comment by bridiver** [comment] 2016-05-25 00:48
I think we also need better handling of a main window renderer crash

**Comment by bridiver** [comment] 2016-05-25 01:48
the above commit is not a fix for the issue, but should make the browser usable again if this is a main window renderer crash. A main window renderer crash will now trigger a reload of the saved state and a notification of the crash.

**Comment by bridiver** [comment] 2016-05-25 06:34
I'm not able to replicate on mac, win 7 or win 10

**Closed** 2016-05-26 18:17 UTC
Labels: info-needed

**Comment by Haze-Aulaian** [comment] 2016-05-26 18:24
btw this is still happening on 0.10.0

**Comment by bridiver** [comment] 2016-05-26 18:30
should be fixed in master and will be in 0.10.1

**Comment by Haze-Aulaian** [comment] 2016-05-26 18:31
ok
