### ISSUE TITLE
Ctrl+ Click on link from Twitter Brave crashes

### ISSUE THREAD

**Issue by Tombsmen** [brave/browser-laptop#412] opened 2016-01-29 04:33 UTC
Ctrl+ Click on link on Twitter brave will instantly crash, see screen shot showing link
![links](https://cloud.githubusercontent.com/assets/16950007/12667298/c9fb0c5c-c606-11e5-80c2-9e8dca487603.PNG)

**Comment by thepup** [comment] 2016-01-29 04:37
Could you put your system details? I'm running El Capitan and can't reproduce this issue.

**Comment by Tombsmen** [comment] 2016-01-29 04:43
Windows 10 Pro
Version 1511 (OS Build 10586.71)
Intel Core i5-4670K 3.4GHZ
32GB - Kingston Value Ram
Raid 0 - Samsung 850 SSD(2)
MSI - Z87-G45 Gaming (MS-7821)

Not sure what else you would like but feel free to let me know.

**Comment by bbondy** [comment] 2016-01-29 04:43
Reproduced on Windows. CC @bridiver  I think some background tab code might be messed on Windows again, maybe from the rebase?

**Comment by bbondy** [comment] 2016-01-29 04:43
Thanks for the report!

**Comment by Tombsmen** [comment] 2016-01-29 04:48
Wasn't sure if these two issues were seperate or the same problem thus two tickets.

**Comment by mkwardakov** [comment] 2016-01-29 07:10
I can reproduse most links on various sites (Google, Facebook, Twitter, Yahoo, AppStore etc).
Cannot see any regularity in that. Devtools windows closes too.

**Comment by mkwardakov** [comment] 2016-01-29 07:35
Looks like brave crashes on ctrl+click on links that are designed to be open in new tab on simple click and works with other links.

**Comment by flienteen** [comment] 2016-01-29 15:21
Seems more like a bug on [brave/electron-prebuilt](https://github.com/brave/electron-prebuilt) because it works fine when running it with [mafintosh/electron-prebuilt](https://github.com/mafintosh/electron-prebuilt)

Duplicate of #398

**Comment by ppetrov** [comment] 2016-01-29 16:54
I think it's because of the href target attribute set to _blank (target="_blank") and with the Ctrl+Click it's like open in new "double" tab.

**Comment by bridiver** [comment] 2016-01-29 17:12
I'm looking at this right now. We made changes to Electron to make window.opener work correctly and this is likely related. I think another change I have been working on will likely fix this.

**Comment by bridiver** [comment] 2016-01-31 07:51
https://github.com/brave/electron/pull/7

**Closed** 2016-01-31 16:27 UTC

**Comment by bbondy** [comment] 2016-01-31 16:36
This will be in 0.7.12
