### ISSUE TITLE
YouTube videos loaded by clicking thumbnails or autoloaded are not added to about:history

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3700] opened 2016-09-04 04:01 UTC
### Description

YouTube videos loaded by clicking thumbnails or autoloaded are not added to `about:history`.

### Steps to Reproduce

  1. Clear the browser's profile
  2. Restart the browser
  1. Open https://www.youtube.com/bravesoftware/ (which should be available on the Dashboard)
  2. Play "This Is Brave" 🦁 
  3. Enjoy it until the next videos are loaded
  4. Open about:history

**Actual result:**

The played video URLs are not available (not logged there). The latest entry is https://www.youtube.com/bravesoftware/

**Expected result:**

Those URLs should be logged as well

**Reproduces how often:**

Consistently.

### Brave Version

**about:brave info:**

Brave: 0.20.5 
V8: 6.2.414.36 
rev: 0cc4f80e759d303fa109ab427ce862d5720dd97b 
Muon: 4.5.14 
OS Release: 4.9.0-3-amd64 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 62.0.3202.75

**Reproducible on current live release:**

Yes.

**Comment by luixxiul** [comment] 2017-11-07 21:02
The 1st post was edited based on the latest template and information.

**Comment by luixxiul** [comment] 2017-11-07 21:03
I'm not quite sure if this is a bug or not (maybe YT handles the page transition differently than other sites).

**Comment by bsclifton** [comment] 2018-05-14 06:55
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/13634

**Closed by bsclifton** 2018-05-14 06:55 UTC
Labels: bug, feature/history
