### ISSUE TITLE
Non-ASCII character for system profile names causes problems with Brave profile

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9425] opened 2017-06-13 18:02 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Non-ASCII character for system profile names causes problems with Brave profile

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 

- Brave Version (revision SHA):
Brave	0.16.9
rev	fba98fc
Muon	4.0.3

- Steps to reproduce:
    1. Create a Windows User account with non-ASCII characters
    2. Install Brave, Bave doesn't get listed as one of the default browsers
    3. Extensions don't get listed and even if enabled doesnt show the preferences page
     
- Actual result:
Non-ASCII character for system profile names causes problems with Brave profile

- Expected result:
Brave should be installed properly irrespective of how the user account name is created 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes, Confirmed by @jonathansampson 

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
https://community.brave.com/t/cant-access-lastpass-account-preferences/3518/11
cc: @bbondy @jonathansampson

**Comment by jonathansampson** [comment] 2017-06-13 18:09
I created a Windows user named Şąሐየ፴ọⴷ. I then signed-in, and downloaded Brave.

Upon loading Brave, I found a broken shortcut for BraveDefaults.exe on my desktop. Once Brave loaded -up, it asked me to set my default browser. Windows did not list Brave as one of the options.

In Brave, I navigated to about:preferences#extensions, and enabled LastPass. LastPass never became enabled, and was never listed in about:extensions.

I suspect there are more issues, but this was the tip of the iceberg.

**Comment by jonathansampson** [comment] 2017-06-13 19:06
cc @bsclifton, who also had thoughts about what may be to blame.

**Comment by hawkunsh** [comment] 2017-06-14 08:10
Nice to see that my 30+ years of experience as a software developer pays off  ;)

Kudos to you for your handling of this issue both at https://community.brave.com/t/cant-access-lastpass-account-preferences/3518/11 and here.

By the way, in my case the profile name was `Håkan`, so many fairly common usernames ([Windows-1252](https://en.wikipedia.org/wiki/Windows-1252)) are affected, not only Chinese, Arabic etc.

**Comment by bsclifton** [comment] 2017-06-15 18:39
Since this has been an issue for a while (I also saw similar reported issues for Electron), I'm going to remove the milestone.  I do agree this is high priority though!  We can probably identify a good amount of impact by looking at the open issue log for Electron and sharing issues here

**Comment by bsclifton** [comment] 2017-06-15 18:41
Bumping down to impact medium since most Brave users are likely not running into this

I'm if there's any impact on macOS or Linux? or if this is Windows only (which it sounds like)

**Comment by jonathansampson** [comment] 2017-09-13 02:30
Likely a +1 from Twitter: https://twitter.com/BraveSampson/status/907637719282700290

The user's name is Sébastien. The é alone, I believe, is enough to prevent much of Brave's core functionality.

**Comment by jonathansampson** [comment] 2017-09-13 17:55
@bsclifton Do you have a link to the Electron issue? I came across a couple commits that appear to be addressing similar issues:

- https://github.com/resin-io/etcher/commit/fd109b5770d2148f6fdf52a1e22b5b7ffa805824
- https://github.com/electron/electron/commit/86338290fb41f4993c2859d920e581b49c75723d

**Comment by tdeinha** [comment] 2017-11-14 13:47
+1. Brazilian name with "é" which is pretty common and without the extensions Brave becomes unusable for me.

**Comment by jonathansampson** [comment] 2017-11-28 17:20
May be related to #5369.

**Comment by mzKas** [comment] 2017-12-06 15:59
Got the same problem with my name "Luís" on Windows profile name.
Have tried on another machine with just "Luis" and it works fine...
Any resolution on this?

**Comment by jonathansampson** [comment] 2017-12-07 17:06
@mzKas No fix at this time, but we will have this addressed in a future release. Apologies for the inconvenience.

**Comment by jacobahlin** [comment] 2018-01-10 15:12
Brave browser installs as default but extensions dont work.

**Comment by mzKas** [comment] 2018-01-16 17:00
Still waiting for a fix for this....
Its unbelievable that you want a stable browser and you have a bug that none of the other chromium based browsers have...

**Comment by savehansson** [comment] 2018-01-16 18:16
I agree @mzKas. This should be easy to fix. Low hanging fruit!

**Comment by mzKas** [comment] 2018-01-24 12:55
aaaaaaaaand guess what?
nothing,..
im about go give up on this browser because of a stupid bug that doesnt exist elsewhere...

**Comment by bsclifton** [comment] 2018-01-24 23:08
@mzKas @savehansson apologies this hasn't been fixed yet ☹️ It is definitely an important one to fix. I don't think it's low hanging fruit though- I am suspecting this needs a patch in the Muon level, like the one @jonathansampson linked to:
https://github.com/electron/electron/commit/86338290fb41f4993c2859d920e581b49c75723d

I'll share with the team and see if there's anything we can do to expedite this

**Comment by bsclifton** [comment] 2018-01-25 04:35
@mzKas @savehansson can you describe the impact in more detail?

Are you just not able to set default browser / configure extensions? Or is nothing being saved at all (bookmarks, etc)?  How bad is it?

**Comment by mzKas** [comment] 2018-01-29 11:38
@bsclifton I have uninstalled it and wont be trying it for a while...
I remember i had trouble setting it as "not-default" because it kept asking for it so it wasnt saving that particular option.

**Comment by Soryathena** [comment] 2018-05-31 22:07
So, I installed Brave earlier coz it sounds like a cool idea.  I can buy into that.  So... I've spent the last couple of hours trying to figure out why none of the extensions work (only three are even installed).  I can see now it's this.  It's not only an issue for international users -- my name is Zoë.  I'm a native English speaker from the UK.  I'm used to my name causing issues with stuff online, but I didn't expect it to break my browser, lol. 

Anyways I'd really like to support this project.  I'm not enthusiastic enough to scrap my entire Windows profile over it.  I see it's been a known issue for like a year now so I hope it can be fixed soon.

**Comment by SilverPuppy** [comment] 2018-06-08 00:57
I have been working around bugs to support this project for well over a year now. I have provided constructive criticism and feedback; I wish I could provide more, but I just lack the code skills.

This project is being undertaken by a dedicated team who really are trying to do some amazing things, which I believe will shape internet history in a great way. This is growing pains. :D My suggestion would be to open it up once in awhile just to check for updates, and hopefully soon it will get an update that makes it work as intended.

I will say that there is a workaround for this particular issue, which is simply to turn of the option to view PDFs in the browser. This will give you a download which can then be opened in an external viewer. I have been using this solution to work around another bug which I would hope can be resolved soon. However, that assumes that PDF.js is the only extension you would ever actually use, as it is in my case.

**Comment by jonathansampson** [comment] 2018-06-09 17:41
@SilverPuppy This issue impacts more than just PDF viewing. The lack of support for non-ASCII characters results in Brave having no ability to remember which extensions are enabled, and many other issues. See my comment here: https://github.com/brave/browser-laptop/issues/9425#issuecomment-308201580

**Comment by bsclifton** [comment] 2018-07-26 16:30
Unfortunately, this is not an issue we'll be able to fix before moving to [Brave Core](https://github.com/brave/brave-browser). However, once we do make the move, this bug will be fixed 😄 (it's not a problem w/ Brave Core- only in our Muon codebase)

**Closed by bsclifton** 2018-07-26 16:30 UTC
Labels: OS/Windows, bug, fixed-with-brave-core, l10n, needs-investigation, priority/P2, windows-important, wontfix
