### ISSUE TITLE
Enable Regional Adblocking to match Android

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#14209] opened 2018-05-22 17:32 UTC
We'd like to have regional adblocking enabled just like Android.

The specific regional adblockers which are enabled by default in Android should be reflected in the desktop.

**Comment by petemill** [comment] 2018-05-22 17:33
Is this a replacement for #4500

**Comment by bsclifton** [comment] 2018-06-01 06:51
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/4500

**Closed by bsclifton** 2018-06-01 06:51 UTC
Labels: priority/P4
