### ISSUE TITLE
Update ledger list control to support new features for 1.0

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#7347] opened 2017-02-21 19:12 UTC
![image](https://cloud.githubusercontent.com/assets/13509546/23180508/8121d62a-f826-11e6-8237-b1278d199176.png)

Item 1: Update column headers to match this config. The rank number column has been removed, and an actions column has been added.

Item 2: Create a new grouped column for action buttons. The delete button moves here, and "Pin site" will be added. Eventually, a tweet button may be added.

Item 3: The percent column needs to support an edit box with active and inactive states.

Item 4: Add ability to show permanent positioned items by adding sort hierarchy. This will allow sorting by "pinned state" and then column.

**Comment by NejcZdovc** [comment] 2017-03-09 12:51
@bradleyrichter 
User will be able to set percentage only for pinned publishers? 

How will the user set default value again? Just delete everything in the input and press enter/unselect and default value will be inserted?

**Comment by NejcZdovc** [comment] 2017-03-09 12:58
When user deletes one publisher, how can he retrieve it back? 
I noticed that include is disabled when item is pinned, so user can't toggle it when publisher is pinned?
@bradleyrichter

**Comment by mrose17** [comment] 2017-03-09 19:19
if you remove a publisher (e.g., click under the "Remove" column -or- right-click for "Never include this site...") you can re-enable the publisher by going to shields and removing the blocking entry there. 

note that this won't recover the previous history ... that's gone forever, by design. it will allow the publisher to be considered going forward.

**Comment by NejcZdovc** [comment] 2017-03-10 13:51
@mrose17 @bradleyrichter  I am testing the current version I noticed that when you exclude one site, this site still have percentage. Shouldn't excluded site percentage be set to 0 and percentages for other sites be recalculated?

**Comment by bradleyrichter** [comment] 2017-03-10 15:05
The percentage is tied to the usage data but now we must change it to mean "percentage of funds" for this UI to work and make sense.  

This is the same case if/when we use sliders.

**Comment by NejcZdovc** [comment] 2017-03-10 16:41
@bradleyrichter Ok, so I need to change this as well I guess

**Comment by bsclifton** [comment] 2017-03-30 15:15
@NejcZdovc could you post the steps to test in the original post here? Thanks 😄

**Closed** 2017-03-30 15:15 UTC
Labels: feature/ledger, QA/steps-required, release-notes/include

**Comment by luixxiul** [comment] 2017-05-29 05:28
@NejcZdovc with the commit you closed the issue you deleted `minimumPercentage` and I am not sure why.

https://github.com/brave/browser-laptop/commit/3515e99f5f47fcb9a83265831c4f45ce88a23f66#diff-6e336f58ebfb0aaf5268c68f492d5c9cL64

**Comment by NejcZdovc** [comment] 2017-05-29 05:45
@luixxiul because we added show all button instead

**Comment by luixxiul** [comment] 2017-05-29 06:28
and we cannot hide 0 % sites once you push the button as we don't have the hide button

**Comment by luixxiul** [comment] 2017-05-29 06:42
As a result of that:

![alot](https://cloud.githubusercontent.com/assets/3362943/26539056/52217140-4485-11e7-8f27-4924fd6eebac.gif)

**Comment by NejcZdovc** [comment] 2017-05-30 16:48
Let's continue the discussion in #9137
