### ISSUE TITLE
main menu "flickers" during app state changes

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#3048] opened 2016-08-08 23:26 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While the browser was loading my previously opened tabs, I tried to access the main menu and it kept closing on me and "flickering". This can also happen when loading a tab during normal usage.

**Expected behavior:**
Menu should not close during state changes

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version:
0.11.3

- Steps to reproduce:
    1. Open a new tab and load any page
    2. Reload the page and immediately open any main menu item

- Screenshot if needed:

- Any related issues:

cc: @bsclifton

**Comment by bridiver** [comment] 2016-08-08 23:27
related https://github.com/brave/browser-laptop/issues/3022

**Comment by bbondy** [comment] 2016-08-09 16:52
I think this can be closed as a dupe of https://github.com/brave/browser-laptop/issues/3022

**Closed** 2016-08-09 16:58 UTC
