### ISSUE TITLE
Google account sign in (e.g. email) signs in wrong account !!!

### ISSUE THREAD

**Issue by joshvito** [brave/browser-laptop#1323] opened 2016-04-10 13:45 UTC
When I sign in with my google id to one of their services, it logs me in with wrong account.

see screens below.
![image](https://cloud.githubusercontent.com/assets/1249866/14410544/79c4cf38-ff00-11e5-8cdc-82c5e97422a7.png)
I click the top choice.

![image](https://cloud.githubusercontent.com/assets/1249866/14410550/9638118e-ff00-11e5-9cff-79902407c2ed.png)

Then it logs me in as the other account.
![image](https://cloud.githubusercontent.com/assets/1249866/14410565/b5b9478a-ff00-11e5-962e-bcf5b69f231d.png)

I don't have this problem in other browsers, both accounts have different passwords, so I know it is not a user error.

**Comment by luixxiul** [comment] 2016-05-13 07:05
Is this still reproducible after update to the latest version?

**Comment by joshvito** [comment] 2016-05-13 10:18
I will try, and respond to the thread the results.

**Comment by joshvito** [comment] 2016-05-13 22:32
I checked this today after allowing the application to update, and it is still reproducable:
![image](https://cloud.githubusercontent.com/assets/1249866/15263551/0dfa87b8-1939-11e6-9df4-e54662ea1f8c.png)

**Comment by luixxiul** [comment] 2016-05-14 01:30
Would you please clear cookies and try again? It is not reproducible on my PC.

CC: @bbondy

**Comment by joshvito** [comment] 2016-05-14 17:46
I can't find a setting rollout to clear cookies in the Brave browser.
I can confirm that the problem persists in a "prive" tab too

**Comment by luixxiul** [comment] 2016-05-14 23:39
Push ``alt`` and select ``History`` on the menubar, and please select ``Clear All Cookies and Site Data``.

**Comment by joshvito** [comment] 2016-05-15 14:37
I cleared the cookies and the problem persists.
Looks like another update was pushed too.
![image](https://cloud.githubusercontent.com/assets/1249866/15274783/06d710b8-1a89-11e6-9d6b-12526d25446d.png)

**Comment by bridiver** [comment] 2016-05-19 23:12
I tried logging in and out of both account across various services and couldn't replicate the problem. I also tried in a pinned tab to see if that made any difference. Does this happen for you every time or just some of the time? Works correctly on Chrome?

**Comment by joshvito** [comment] 2016-05-19 23:49
@bridiver ,the error happens every time in Brave. It works correctly in Chrome every time.

**Comment by diracdeltas** [comment] 2016-05-31 22:20
I think I saw this exactly once in my Google account but haven't since

**Comment by diracdeltas** [comment] 2016-05-31 22:25
@joshvito are you using any password manager? after you enter the password, are you logged into both accounts simultaneously or just the second one?

**Comment by joshvito** [comment] 2016-06-01 01:31
I am not using a password manager. The problem persists when only one
instance of Brave is open and I have one tab open. I don't believe I am
logged into both accounts simultaneously.

**Comment by diracdeltas** [comment] 2016-06-01 01:54
just Googled for similar issues; seems like it's not uncommon. 
https://productforums.google.com/forum/#!topic/gmail/YUZtBx-xW6c
https://productforums.google.com/forum/#!topic/gmail/_vwRkLNfRZo
https://support.mozilla.org/en-US/questions/999768

**Comment by Ironmatt71** [comment] 2016-06-09 17:41
This exact problem just started for me as well; I used Gmail for about a week, then opened one of my infrequently accessed accounts also hosted by Google, and now I cannot get back to my primary account!  Even when I enter the primary account info and PW, same as the original poster...  Works fine, switches seamlessly in Chrome and InternetExploder.

**Comment by bbondy** [comment] 2016-06-27 14:17
I'm having a similar problem that just started.

I keep trying to signout with my brave.com so I can add bbondy@gmail.com as my main one.  It keeps replacing with my brian@brave.com email though.  I can't seem to get bbondy@gmail.com to work without it always getting overwritten by brian@brave.com.

**Comment by cezaraugusto** [comment] 2016-06-27 14:29
Also related #2001

**Comment by luixxiul** [comment] 2016-07-22 14:33
The same thing as @bbondy has experienced happens to me. Here is STR:

- Clear cookie
- Log in on youtube with a normal google account
- Log in on youtube with a google app account
- Change account to the gapp account
- Log out from the gapp account
- Log in on youtube with the normal google account
- (The password should be filled automatically)

And then logged in with the gapp account.

Even I remove the gapp account on https://accounts.google.com/ServiceLogin, I keep logging in with that account. cc: @bridiver @diracdeltas

**Comment by luixxiul** [comment] 2016-07-31 16:46
It must be related with log in credentials of Google Apps. On #2829 I cannot even log in to an Google Apps account if I have logged in to other normal google accounts.

**Comment by luixxiul** [comment] 2016-08-06 16:58
+1 from support

**Comment by luixxiul** [comment] 2016-09-02 16:43
Setting a milestone for now as it seems to be a critical issue.

**Comment by bridiver** [comment] 2016-09-02 19:46
are we sure this is a Brave issue? @diracdeltas posted links where people are having the same problem in Chrome

**Comment by bsclifton** [comment] 2016-09-02 21:56
I unfortunately have this issue and can reproduce at any given time :frowning: I don't have the issue in Chrome

**Comment by bridiver** [comment] 2016-09-02 22:04
that still doesn't necessarily make it a Brave issue. The people who are seeing it on Chrome and Firefox may not see it on Brave. It could just be something about the local browser state. Can you replicate every time if you start from a fresh user data dir?

**Comment by bridiver** [comment] 2016-09-02 22:06
it's certainly possible that it is a Brave issue or maybe it's worse on Brave for some reason, but if it's happening on other browsers it feels like a Google issue

**Comment by luixxiul** [comment] 2016-09-03 14:52
I haven't seen this either FF or Chrome.

**Comment by capouch** [comment] 2016-09-28 06:31
I just experienced this issue for the first time Linux Slackware 0.12.1.  I am running on a VirtualBox instance and also have Chrome installed.  I've been happily using Brave for 2-3 weeks now, logging in many times a day with both accounts active, without problem.  No problems whatsoever on Chrome.  

I had to log out of my main Google account and then remove both accounts from the Google account picker, then go to the built-in password manager and remove the password for my main account (the secondary account password used to be there but was not anymore) and now I'm back in, but I see the password manager isn't storing either of them.

A coincident weirdness that had me searching the issue tracker: for an hour or so ahead of this incident, I noticed that my URL-bar completion quit working for sites I go to all the time, i.e. www.facebook.com would normally autofill after a few characters (but separately just typing facebook.com has never autocompleted) but it stopped working that way.  Then this happened.

Also glad to help gather debug info if I can be of use.

**Comment by luixxiul** [comment] 2016-10-07 17:06
It still happens. When I try to log in one of my gmail accounts from another account which has been logged in already, whose password is the same with the other, the password notification bar for that account is displayed, and I am redirected to the account.

![gmail](https://cloud.githubusercontent.com/assets/3362943/19198407/f84aa620-8cf9-11e6-9735-4174ca7cfdb6.gif)

**Comment by bridiver** [comment] 2016-10-07 19:04
maybe it's a 3rd-party cookie or referrer blocking issue. Can you replicate with shields down?

**Comment by luixxiul** [comment] 2016-10-08 02:03
Yes, I can reproduce the issue after disabling the shields.

**Comment by darkdh** [comment] 2016-10-11 04:22
+1 from support
https://linkbubble.zendesk.com/agent/tickets/5729

**Comment by luixxiul** [comment] 2016-10-19 16:16
This is the STR I shared with the team.
>
1. Setup two Google accounts which have the same password with your Google Apps account (eg temp1@gmail.com and temp2@gmail.com)
2. Delete your brave folder
3. Open mail.google.com
4. Login with temp1@gmail.com (ignore the notification bar)
5. "Add account" from the top right button
6. Login with temp2@gmail.com (ignore the notification bar)
7. "Add account" from the top right button
8. Login with your Google Apps account with two-factor authentication
9. Sign out from the top right button
10. Push 3 Yes buttons
11. Select 1st tab
12. Sign out from the top right button
13. Login with your Google Apps account -> redirected to temp1@gmail.com
>

**Comment by srirambv** [comment] 2016-10-20 08:54
@luixxiul I tried the above steps but was unable to repro. Here's what I tried and worked.
1. Login to temp1@gmail.com, save the password
2. Login to temp2@gmail.com, shows notification to save temp1@gmail.com 
3. Click No in the notification bar
4. Click login with temp2@gmail.com userid/password
5. Logs you into temp1@gmail.com account even though you have entered temp2@gmail.com credentials

this is on 0.12.6 Preview 1 build

**Comment by luixxiul** [comment] 2016-10-20 13:13
@srirambv did you try with your Google Apps account with two-factor authentication, and so on? From 1 to 5 in your STR, which is from 4 to 7 in mine, it works properly as mine says. I think you would need 2 normal account and 1 Google Apps account at least, which covers from 8 to 13 in mine.

**Comment by darkdh** [comment] 2016-10-21 04:20
+1 from support
https://linkbubble.zendesk.com/agent/tickets/5897

**Comment by alexwykoff** [comment] 2016-10-22 11:17
+1 from support : https://linkbubble.zendesk.com/agent/tickets/5024

**Comment by bridiver** [comment] 2016-10-23 02:54
does this only happen when the accounts have the same password?

**Comment by srirambv** [comment] 2016-10-23 03:25
@bridiver  The steps I mentioned above had different password for each account. Even if I enter the correct password for the second account it still logged me into the first account.

**Comment by luixxiul** [comment] 2016-12-22 14:12
Maybe is this related with the default password manager? I'm not quite sure but I think I haven't seen it on Dashlane.

**Comment by CliqueBait** [comment] 2016-12-23 13:51
@luixxiul Yeah. That was my hunch when I first saw this ticket. I run Ubuntu and I know there are ongoing issues for some Ubuntu users surrounding google login where the web authentication dialogue keeps popping up relentlessly so I didn't mention it here. StackOverflow hacks seemed to alleviate the problem for me but I imagine this issue holds accross multiple platforms.

My install:
Brave:	0.12.15
Muon:	1.4.31
libchromiumcontent:	53.0.2785.143
V8:	5.3.332.47
Node.js:	6.5.0
Update Channel:	dev
os.platform:	linux
os.release:	4.8.0-32-generic
os.arch:	x64

**Comment by srirambv** [comment] 2017-01-31 22:22
+1 from community https://community.brave.com/t/multiple-google-account-passwords/966

**Comment by srirambv** [comment] 2017-02-20 12:36
+1 from community https://community.brave.com/t/strange-behavior-trying-to-log-into-inbox-google-com/1297

**Comment by bridiver** [comment] 2017-02-23 19:53
I am currently able to replicate this on Brave, Chrome and Safari on mac

**Comment by bridiver** [comment] 2017-02-23 19:55
the fact that it is happening in all 3 browser simultaneously and the inclusion of Safari in that list leads me to believe that this is a google bug and may or may not be related to browser code

**Comment by luixxiul** [comment] 2017-02-24 03:14
@bridiver If so, let's close this for now until anyone would see this only happen on Brave.

**Comment by bsclifton** [comment] 2017-02-24 03:54
@luixxiul maybe we can tag this as upstream and report a bug officially to Google

**Comment by ncbaihly** [comment] 2017-03-19 19:25
I recently came across the bug in Brave. Chrome seems to work but I haven't checked this specific pattern that I've been able to replicate a couple times in Brave.
1.I logged in with xx@gmail.com ( Didn't save credentials )
2. logged out of xx@gmail.com
3. logged into yy@gmail.com
4. save yy@gmail.com credentials
5. logged out of yy@gmail.com
6. Tried to log into xx@gmail.com
7. was logged into yy@gmail.com not xx@gmail.com

Looking at the POST request yy@gmail.com's info was sent. 

This is from a total outsider perspective that hasn't worked on a web browser or anything before, but could the password manager be hijacking the request and just shoving whatever saved info into it?

I'm going to try and replicate this chrome and will post my results.

**Comment by ncbaihly** [comment] 2017-03-19 19:32
Tried replicating the same steps I used to reproduce the bug in Brave in Chrome and the bug did not occur and I was able to login into the correct account.

**Comment by luixxiul** [comment] 2017-05-11 16:07
Do we still see the error? cc @joshvito @CliqueBait

**Comment by joshvito** [comment] 2017-05-11 22:29
@luixxiul I cannot reproduce the error on the following version
Thanks
 
Brave: 0.15.2 
rev: af7ef42ad622f899312a38bdd0e2138154393627 
Muon: 2.58.9 
libchromiumcontent: 58.0.3029.96 
V8: 5.8.283.37 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64

**Comment by luixxiul** [comment] 2017-05-27 12:12
OK I'm going to close the issue for now. Let's reopen it if we will start to experience the issue.

**Closed by luixxiul** 2017-05-27 12:12 UTC
Labels: info-needed, needs investigation, site-bug
