### ISSUE TITLE
Can Not Load Google Sheets Document

### ISSUE THREAD

**Issue by aubbie82** [brave/browser-laptop#4471] opened 2016-10-03 17:34 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Can not load Google Sheets document. I confirmed it does open in other browsers.

**Expected behavior:**
Google Sheet document should load when opened

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win10

- Brave Version:
0.12.3

- Steps to reproduce:
    1. Log in to Google account.
    2. Go to Google Drive
    3. Select one of my Google Sheets documents

- Screenshot if needed:
![brave - google sheets](https://cloud.githubusercontent.com/assets/22598939/19046968/7f9bcba6-8965-11e6-8a5d-1e4ad6db546e.jpg)

- Any related issues:
No

**Comment by luixxiul** [comment] 2016-10-03 22:59
Dupe of #2343. The work-around is to disable fingerprint protection.

**Closed by luixxiul** 2016-10-03 22:59 UTC
