### ISSUE TITLE
Share settings/bookmarks across devices

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#4784] opened 2016-10-14 15:42 UTC
From support: https://linkbubble.zendesk.com/agent/tickets/5595

> - Synch: Perhaps a synch account so settings/bookmarks can be shared across devices. I understand this means data storage and all the potential headaches, a la Yahoo this week, so perhaps something simpler like a cache file that is accessed in a user’s existing cloud storage (Dropbox, iCloud, etc.)?

**Comment by bbondy** [comment] 2016-10-14 16:14
Marking as a duplicate of:
https://github.com/brave/browser-laptop/issues/1854

**Closed by bbondy** 2016-10-14 16:14 UTC
Labels: suggestion
