### ISSUE TITLE
Can't enter URLs or search in the bar

### ISSUE THREAD

**Issue by Fahrradflucht** [brave/browser-laptop#3886] opened 2016-09-11 10:38 UTC
**Describe the issue you encountered:**
I can't enter anything into the URL-/searchbar. If I type something in there, it will appear like it should but when I hit `Enter` The bar just clears out and nothing happens.

I can however open websites by copying a URL and then using the "Paste & Go" feature in the right-click menu.

**Expected behavior:**
Function as normal.

- Platform:
macOS 10.11.6

- Brave Version:
0.12.0

- Steps to reproduce:
    1. Open Brave
    2. Type something in URL bar
    3. hit enter

**Comment by Liunkae** [comment] 2016-10-16 21:27
Likely a duplicate of #3254. Please change your search engine setting and try again.

**Closed by Liunkae** 2016-10-16 21:27 UTC

**Comment by Fahrradflucht** [comment] 2016-10-17 10:41
Yes that fixed it by why was it possible for me to have no default search engine in the first place and why should that mean that I can't open URLs?

**Comment by Liunkae** [comment] 2016-10-17 19:22
@Fahrradflucht 1) There was a bug in a previous version (0.11.2) that caused this. 2) As I've mentioned in another issue, the urlbar in Brave apparently works under the assumption that there is a default search engine set. I'm not sure if removing this assumption is easy to fix/worth fixing. I don't know much beyond this (I'm not a Brave developer), so this is just my understanding of the issue.
