### ISSUE TITLE
Extension API: chrome.i18n.getMessage

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#4755] opened 2016-10-13 22:13 UTC
https://developer.chrome.com/extensions/i18n#method-getMessage

Blocks #8327, #6366, #9828

**Comment by jonathansampson** [comment] 2016-10-13 22:31
I'm temporarily working around this issue by providing a stub with the methods I need. The following defines responses for [_predefined messages_](https://developer.chrome.com/extensions/i18n#overview-predefined), and returns the message key for all other messages.

```js
Browser.i18n = chrome.i18n || { getMessage: function (string) {
    switch (string) {
        case "@@extension_id":
            return "pioclpoplcdbaefihamjohnefbikjilc";
        case "@@ui_locale":
            return "en-US";
        case "@@bidi_dir":
            return "ltr";
        case "@@bidi_reversed_dir":
            return "rtl";
        case "@@bidi_start_edge":
            return "left"
        case "@@bidi_end_edge":
            return "right";
        default:
            return string.toString();
    }
}}
```

**Comment by Liunkae** [comment] 2016-10-14 07:10
Related to/duplicate of #4474.

**Comment by jonathansampson** [comment] 2017-05-10 15:29
Reopening as we are now tracking these issues on a more granular level.

**Comment by bsclifton** [comment] 2018-06-18 07:14
I think it's fair to say we won't be implementing this. We'll get this for free when switching over to Brave Core. Marking as `wontfix` since the fix won't happen in browser-laptop

**Closed by bsclifton** 2018-06-18 07:14 UTC
Labels: feature/extensions
