### ISSUE TITLE
Feature Request: Right click menu on pinned tab / close option

### ISSUE THREAD

**Issue by modusops** [brave/browser-laptop#12480] opened 2018-01-03 17:08 UTC
**Description**
Right click to close a pinned appears to be missing the option to close. Seems like an easy win to include this. Checked against Chrome, they have it for pinned tab.

**Steps to Reproduce**

  1. Open a new tab
  2. Pin it
  3. Right click

**Actual result:**
No option to close a pinned tab

**Expected result:**
Option to close a pinned tab

![screen shot 2018-01-03 at 12 00 02 pm](https://user-images.githubusercontent.com/7923023/34530930-9efdedae-f07e-11e7-87fc-eb30d969364a.jpg)

 
Brave: 0.19.123 
rev: f45cb3a2b308ea1c893f8b2db6143958b8e8d0ac 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.3.0 
OS Architecture: x64

**Comment by eljuno** [comment] 2018-01-03 18:54
Duplicate of #4063?

**Comment by cezaraugusto** [comment] 2018-01-04 22:42
hey @modusops that's a thing! we did it in #10997 and we'll be landing it in the next (0.20.0) version. Stay tuned!

@eljuno thanks for checking ya it's a dupe. Closing as fixed. Thanks!

**Closed by cezaraugusto** 2018-01-04 22:42 UTC
