### ISSUE TITLE
Browser window hangs and keeps blinking during startup

### ISSUE THREAD

**Issue by hopitas** [brave/browser-laptop#4943] opened 2016-10-19 06:06 UTC
**Did you search for similar issues before submitting this one?**

yes

**Describe the issue you encountered:**

After update 0.12.5 and restarting the browser, the window keeps blinking black/white during startup.

**Expected behavior:**

Seeing some web page...

- Platform (Win7, 8, 10? macOS? Linux distro?):

Win10

- Brave Version:

0.12.5

- Steps to reproduce:
    1. Update to version 0.12.5
    2. Restart the browser

**Comment by hopitas** [comment] 2016-10-19 06:13
Maybe it has something to do with pinning the tabs, because I tried to close all my tabs, but wasn't able to unpin my pinned ones. The screen just keeps blinking.

**Comment by hopitas** [comment] 2016-10-19 06:16
I removed the application, removed all app data, reinstalled and now the blinking went epileptic.

**Comment by bsclifton** [comment] 2016-10-19 07:05
@hopitas we have received reports which are similar to what you're seeing, starting with version 0.12.3: https://github.com/brave/browser-laptop/issues/4502

One thing you can try, if the UI lets you, is to go into preferences and disable hardware acceleration (under Advanced).  If that doesn't work, it would be helpful to know some more info:
- system details (video card, etc). You can get this by doing Start > Run > dxdiag
- what is shown on the screen when the blinking happens? is it trying to show an error page? or does it happen no matter what you do?

Thanks in advance for any info you can provide- I'm hoping we can narrow it down and close it out! :smile:

**Comment by hopitas** [comment] 2016-10-19 07:21
Can't go to preferences because the blinking.

It says about:error in tab, other than that it just keeps blinking...

[DxDiag.txt](https://github.com/brave/browser-laptop/files/538194/DxDiag.txt)

**Comment by hopitas** [comment] 2016-10-19 09:41
After another reboot, the problem was gone o.O

**Comment by bsclifton** [comment] 2016-10-20 15:44
@hopitas wow- ok please let us know if this happens again.  If you want to track the issue, please follow this older issue we have created https://github.com/brave/browser-laptop/issues/4502

I'm going to close this issue as a duplicate and add the details there :smile: Thanks again for the report and apologies for it happening :frowning_face: The root cause is likely with the new Frameless window we're using from electron. Basically, we now custom render the entire window, versus using the standard Windows titlebar and caption buttons

**Closed by bsclifton** 2016-10-20 15:44 UTC
Labels: needs investigation, OS/Windows
