### ISSUE TITLE
Hotkeys doesn't work

### ISSUE THREAD

**Issue by Kasmetski** [brave/browser-laptop#9514] opened 2017-06-16 10:37 UTC
- Did you search for similar issues before submitting this one?
There are similar problems, but not the same
- Describe the issue you encountered:
Some of the hotkeys doesn't work. "Back" button of the mouse for an example. Nothing happened, but it's working with Firefox, Chromium & etc. The other buttons working fine (like ctrl+w for closing tabs) 
- Platform (Win7, 8, 10? macOS? Linux distro?):
Kubuntu 16.10
- Brave Version (revision SHA):
latest
- Steps to reproduce:
    1. Open websites
    2. Click mouse "back button"

- Is this an issue in the currently released version?
It was always like that on my system

**Comment by bsclifton** [comment] 2017-11-27 22:49
Thanks for the report! I'm going to close this issue as a duplicate of https://github.com/brave/browser-laptop/issues/3101

**Closed by bsclifton** 2017-11-27 22:49 UTC
