### ISSUE TITLE
Some visual indicator when swiping to go back or forward.

### ISSUE THREAD

**Issue by jamesmudgett** [brave/browser-laptop#10663] opened 2017-08-25 16:20 UTC
- Did you search for similar issues before submitting this one?
Yes 
- Describe the issue you encountered:
Swipe back or forward on mac to navigate, don't see any indicator that browser is doing anything other than small reload on tab icon. There should be something more obvious. Other browsers have more visual animations or design around this activity.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Any
- Brave Version (revision SHA):
All
- Steps to reproduce:
    1. navigate a few websites in same tab
    2. swipe back
    3. swipe forward
    
- Actual result:
goes back and forward
- Expected result:
no obvious visual indicators that suggest my actions were causing anything to happen.
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by NejcZdovc** [comment] 2017-08-25 17:49
@jamesmudgett we already added this and should be available in 0.20.x (#9617). Is this what you were looking for?

**Comment by Liunkae** [comment] 2017-08-25 18:36
Duplicate of #2477.

**Comment by NejcZdovc** [comment] 2017-08-25 18:44
Closing as a dupe, if @jamesmudgett you have any suggestions or want to improve it please reopen it

**Closed by NejcZdovc** 2017-08-25 18:44 UTC
Labels: design, enhancement
