### ISSUE TITLE
Unable to bookmark the sites into toolbar subfolders

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14556] opened 2018-06-26 08:06 UTC
### Description
If we try to Add bookmarks to sub folders ( Toolbar folders-kk/kkk), unable to add add bookmarks to second level folders (e.g kkk). Please watch attached recorded video in Actual results for clear understanding

### Steps to Reproduce

  1. Launch Brave with clean profile
  2. Create toolbar bookmarks
  3. Create toolbar bookmark folders and sub folders
  4. Import bookmarks
  5. Add bookmarks to toolbar folders
  6. Pull the imported bookmarks folder into toolbar folder (e.g Toolbar-kk folder)  
  5. Try to add multiple bookmarks to sub folders  (e.g Toolbar-kk/kkk folder)

**Actual result:**
Able to add only one bookmark to sub folder, unable to add multiple bookmarks to subfolder
![book mark issue1](https://user-images.githubusercontent.com/38657976/41897710-ae6d5dce-7945-11e8-949a-2d87a109f894.gif)

**Expected result:**
Should be able to add multiple bookmarks to folders and sub folders which are created on toolbar

**Reproduces how often:**
Easily

### Brave Version
0.23.17

**about:brave info:**
 
Brave: 0.23.17 
V8: 6.7.288.46 
rev: bc754ebe4dd8d8f59a322660e8af1962a99753ea 
Muon: 7.1.2 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Tor: 0.3.3.7 (git-035a35178c92da94) 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.87

**Reproducible on current live release:**
Yes

**Comment by joelwass** [comment] 2018-06-27 16:17
Seems this has been fixed in master, or at least i was not able to reproduce 

![nonbug](https://user-images.githubusercontent.com/7344422/41986428-162295ec-7a04-11e8-90a0-b9e0b56af995.gif)

**Comment by rebron** [comment] 2018-09-07 16:44
Closing. Looks like this is fixed in brave-core. https://brave.com/download-dev

**Closed** 2018-09-07 17:19 UTC
Labels: bug, feature/bookmarks
