### ISSUE TITLE
Mute tabs on all windows option in tab context menu 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10906] opened 2017-09-12 03:40 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Provide mute tabs on all windows option in tab context menu option  when multiple windows are opened

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):

Brave | 0.18.32
-- | --
rev | e94738d
Muon | 4.3.18

- Steps to reproduce:
    1. Open two windows
    2. Play video in one tab of window 1
    3. Switch to window 2 and right click and mute other tabs,  video on window 1 doesn't mute
    
- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment] 2017-09-12 07:10
Should picking "Mute other Tabs" mute other windows too? Or should we have a different option (only available if you have more than 1 window) called "Mute other Windows"?

cc: @bradleyrichter @jenn-rhim @alexwykoff

**Comment by WausauBill** [comment] 2018-01-05 17:39
Would be good to have a "mute all windows" option.  Also, when I went to unmute my tabs on this, I assumed that I should right click like I did to mute them.  Took me a minute to figure out to left click on the tab.  You might want to consider adding a context item when tabs are muted to "unmute" all tabs (and/or windows depending on how you handle this).

**Comment by eljuno** [comment] 2018-02-23 19:44
Same like #8384?

**Comment by bsclifton** [comment] 2018-08-06 20:08
@eljuno yup! closing as dupe of #8384

**Closed by bsclifton** 2018-08-06 20:08 UTC
Labels: feature/context-menu, needs-info, suggestion
