### ISSUE TITLE
Width of top border should be wider to make it easy to resize window

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4782] opened 2016-10-14 15:40 UTC
**Describe the issue you encountered:** the width of the top edge of the window is so narrow (1 or 2px?) that it is hard to grab it and resize the window. 

**Expected behavior:** The width should be wider.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.4
- Any related issues:

**Comment by luixxiul** [comment] 2016-10-30 09:38
@bsclifton would you please take this?

**Comment by bsclifton** [comment] 2016-10-30 20:07
@luixxiul can you show me an example of this? Not 100% clear what you mean.  Is it hard to get the cursor to show as the resize cursor?

**Comment by luixxiul** [comment] 2016-10-31 04:37
@bsclifton yes it is, while the other borders are easy to grab, the top border is hard to do so. Here is an example:

![border](https://cloud.githubusercontent.com/assets/3362943/19844300/a58d6030-9f6e-11e6-8f6b-628f255f2b2c.gif)

![border](https://cloud.githubusercontent.com/assets/3362943/19844326/f8760766-9f6e-11e6-9472-6f4d5cfa0673.gif)

Do the gifs make it clear?

**Comment by bsclifton** [comment] 2016-11-08 01:09
This one is definitely not an easy one. The reason being is that it has to do with drag area.  Changing this behavior will more often than not cause a regression.

I'm going to un-assign a milestone; let's work with @bradleyrichter or @bbondy if we want to reassign it into a milestone

**Comment by bradleyrichter** [comment] 2016-11-08 01:11
if you add one pixel, it will be a 2x improvement.  ;   )

**Comment by luixxiul** [comment] 2016-11-29 16:27
https://linkbubble.zendesk.com/agent/tickets/6980

> I figured out why it is so hard to resize a Brave window!  You have a 1 pixel handle to hit the activate cursor. How about 4 as what appears microsoft Excel or Word use?  The are easier to use.

**Comment by bsclifton** [comment] 2016-12-22 06:06
+1 per https://github.com/brave/browser-laptop/issues/6333

> Sometimes its difficult to resize window from the top left corner. The other sides its easy to resize. Sometimes the resize pointer changes and instead of resizing the window it just moves the browser window. (Intermittent issue)

**Comment by privatzee** [comment] 2016-12-22 13:44
I've been using Brave less and less because of this, as the irritation factor accumulates. It wouldn't be so bad if browser resizing would stick.

**Comment by bsclifton** [comment] 2016-12-22 23:16
@privatzee sorry to hear :frowning_face: I know the top is sensitive.  

The challenge there is that Windows requires a hit-test in order for the behavior to change.  The cursor moving causes a hit test to be done.  This checks the area the mouse is over:
- if near the edge, returns "this area is resizable"
- if it's draggable, it returns "this is a caption area"

The problem here is that the draggable property is taking precedence over the resize. In order to fix this, we'd need to dedicated 5 or so pixels around the edges to be non-draggable.  Since there are already complaints about the drag area being minimal, this is a very hard compromise.

cc: @bradleyrichter for a recommendation.  It would be useful to see a mock up of the top area and what is acceptable for drag / no drag.

**Comment by privatzee** [comment] 2016-12-23 19:46
@bsclifton Thanks for the considerate reply. How about making the top resize area bigger when the Menu Bar is being displayed (which is always true for me)? There should be plenty of room available in that case.

**Comment by srirambv** [comment] 2017-03-13 08:03
+1 from community https://community.brave.com/t/resize-window-from-the-top-border/1662

**Comment by luixxiul** [comment] 2017-04-17 11:17
It is possible to solve the issue by adding `padding-top` to `.top` (I tried by myself), but it makes the padding area on the top of the window caption buttons unclickable.

Though there should be better solutions, it would work for a while. @bsclifton what do you think?

**Comment by luixxiul** [comment] 2017-04-19 04:01
It seems that my proposal above looks similar with Slack client.
![slack](https://cloud.githubusercontent.com/assets/3362943/25162744/0ac89228-2500-11e7-85a7-3e2075acc8cf.gif)

Is it OK to implement the padding-top?

**Comment by zedgoat** [comment] 2017-08-06 23:21
+1. Love brave but it's crazy hard to manage the window size, especially from the top or corners. Have a friend with old hands who had to switch back to Chrome because it was stressing them out trying to size the window.

**Comment by bradleyrichter** [comment] 2017-08-07 04:41
Adding padding would only help in the window button area and not the entire top bar?

I think this is at least an improvement.

**Comment by luixxiul** [comment] 2017-08-07 05:13
> Adding padding would only help in the window button area and not the entire top bar?

I could make it work on the entire top bar.

**Comment by luixxiul** [comment] 2017-08-15 16:08
It looks like that lately the Slack client on Windows 10 also suffers the same issue: 

![slack](https://user-images.githubusercontent.com/3362943/29324513-44b87d82-821f-11e7-9994-ae530181855f.gif)

**Comment by Alan-FGR** [comment] 2017-11-18 15:20
Related I guess:
![17-11-18-81](https://user-images.githubusercontent.com/8399299/32981932-0af6a9dc-cc63-11e7-8477-d3432142af9a.gif)
Just installed on Win7 HP 64.
Looking for a decent alternative to the terrible Firefox 57. Brave is good but UI has some issues, also lack of 'tabs on top' and customizability is a major one for me. Default UI has too much wasted space in my opinion.

**Comment by Alan-FGR** [comment] 2017-11-18 15:28
I think the problem there is that Win7 windows have that rounded part and Brave doesn't add the resizing thing around that... not a problem in Win10 of course.

**Comment by jonathansampson** [comment] 2017-12-18 05:17
+1 from Twitter: https://twitter.com/OppressorBot/status/942592059512209408

![image](https://user-images.githubusercontent.com/815158/34090980-5cd8d1b0-e380-11e7-8c79-7ae7382ffd75.png)

**Comment by hkps4jj** [comment] 2018-02-13 03:17
Sign up for this thread: problem has not been solved in 2018 :(

**Comment by jonathansampson** [comment] 2018-02-13 03:20
@hkps4jj We're working on some things that will resolve this issue. You can expect to see it resolve in the not too distant future.

**Comment by srirambv** [comment] 2018-03-14 06:02
+1 from https://community.brave.com/t/unable-to-resize-browser-window-from-top-center-edge/17766

**Comment by srirambv** [comment] 2018-07-05 14:20
+1 from https://community.brave.com/t/make-the-top-edge-resize-area-bigger-in-windows/27052

**Comment by bsclifton** [comment] 2018-07-10 21:57
Fixing this in our current Muon codebase is not trivial. I'm going to close this issue as `wontfix` since `browser-laptop` is our Muon codebase.

However, coming soon, the Muon product will be replaced with Brave Core (which forks the Chromium UI). This *does* fix the issue. Here's a live demo of resizing in Brave Core
![top-cursor](https://user-images.githubusercontent.com/4733304/42539961-9171d7c4-8451-11e8-8635-d3c560c650bc.gif)


**_Stay tuned for a proper fix_**

**Closed by bsclifton** 2018-07-10 21:57 UTC
Labels: OS/Windows, feature/titlebar, fixed-with-brave-core, windows-important, wontfix
