### ISSUE TITLE
about:blank flashes briefly when opening a new tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8378] opened 2017-04-18 11:49 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Open a new tab/private tab using shortcut cut or the + button, `about:blank` is retained sometimes

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.2
rev	632a9bc

- Steps to reproduce:
    1. Open a new tab using Ctrl+T/ Ctrl+Shift+P
    2. While tab is loading, you'll see "about:blank" in the URL bar
    
- Actual result:
about:blank retained on new tabs

- Expected result:
Should not retain `about:blank`

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment] 2017-04-19 06:43
Not specific to Windows- I've been getting this a lot recently (and I mostly create using the mouse, clicking the +).  Thanks for capturing this 😄

**Comment by srirambv** [comment] 2017-04-24 10:09
Update title. Easy repro steps captured. Consistently reporduced
![8378](https://cloud.githubusercontent.com/assets/17010094/25332468/762d1c6e-28de-11e7-8eea-c586557b9d05.gif)

**Comment by diracdeltas** [comment] 2017-05-16 21:08
taking a look at this

**Comment by bsclifton** [comment] 2017-05-16 21:19
duplicate of https://github.com/brave/browser-laptop/issues/8850

**Comment by diracdeltas** [comment] 2017-05-16 21:22
@bsclifton i thought this issue was for when 'about:blank' flashes then disappears on new tabs, which is still an issue. is there an issue for that?

**Comment by bsclifton** [comment] 2017-05-16 21:30
@diracdeltas let's use this issue to track that 😄   I'll reopen and update the title

**Comment by diracdeltas** [comment] 2017-05-16 21:32
cool. i think Sriram's other issue (about:blank showing up in tab 1 after tab 2 is closed) is now fixed.

**Comment by bsclifton** [comment] 2017-08-30 16:31
Closing as I believe this is fixed (unable to repro on Windows or macOS w/ 0.18.23)

**Closed by bsclifton** 2017-08-30 16:31 UTC
Labels: bug, feature/newtab, QA/steps-specified
