### ISSUE TITLE
Adding bookmarks creates multiple entries(Intermittent issue)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6510] opened 2017-01-03 14:21 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Adding bookmarks creates multiple entries

**Expected behavior:**
Should only create one bookmark entry

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	0c7a64d

- Steps to reproduce:
    1. Open bookmark manager in normal tab
    2. Open bookmark manager in session tab
    3. Add about:bookmark in session tab as a bookmark from URL bar, adds two entry for bookmark

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment] 2017-01-03 16:27
Is this also present in .12.15?

**Comment by srirambv** [comment] 2017-01-03 16:36
No doesn't happen on 0.12.15

**Comment by bbondy** [comment] 2017-01-09 02:32
I tested this but it only adds 1 entry from the session tab for me. 
Note that if the steps to reproduce were meant to say click add bookmark in the url bar for both tabs, then that works as expected. I'm going to remove the milestone since I can't reproduce and since this seems like an edge case, but maybe it should be closed or re-added based on ore info you provide @srirambv

**Comment by luixxiul** [comment] 2017-11-03 13:20
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/adding-bookmark-creates-multiple-entries/10108

Let's reopen this issue if we find it is reproduced widely 👍

**Closed by luixxiul** 2017-11-03 13:20 UTC
Labels: bug, feature/bookmarks, needs-investigation
