### ISSUE TITLE
Autofill suggestion is way off when UI scale and default zoom is changed from default setting

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8870] opened 2017-05-15 09:40 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Autocomplete suggestion is way off 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.303
rev	04ceba3

- Steps to reproduce:
    1. Login/ Enter details in a input field to save auto suggestions
    2. Click on the input field to list the auto suggestions, position is way off
    3. 
    
- Actual result:
Autocomplete suggestion is way off 

- Expected result:
Should be below the input field

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/26051467/2c074902-395a-11e7-8a81-a18d9793fb1c.png)

- Any related issues:
cc: @darkdh

**Comment by darkdh** [comment] 2017-05-15 16:00
This will be fixed by #8369

**Comment by srirambv** [comment] 2017-05-16 18:20
Still an issue on Windows.
![image](https://cloud.githubusercontent.com/assets/17010094/26121591/b52b2c54-3a6c-11e7-8a63-bceadd7ca408.png)

**Comment by darkdh** [comment] 2017-05-16 23:57
still can't reproduce on windows 10 with either package build or development build
<img width="1674" alt="screen shot 2017-05-16 at 4 55 59 pm" src="https://cloud.githubusercontent.com/assets/11330831/26132965/94574f8a-3a58-11e7-911b-c7994b92b0b1.png">

**Comment by luixxiul** [comment] 2017-05-17 14:36
@srirambv would you mind opening the devtool and paste the context menu div like this? It should be just under `<div id="window">"`.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26159417/7eda63de-3b59-11e7-808a-6d399dadae57.jpg)

**Comment by srirambv** [comment] 2017-05-17 14:44
@luixxiul 
![image](https://cloud.githubusercontent.com/assets/17010094/26159885/b1eed30a-3b17-11e7-8127-2c50270455b8.png)

**Comment by bsclifton** [comment] 2017-05-17 15:51
Just so that we have the notes here: @darkdh did test at different DPI sizes without luck.  He tested at 125%, 150%, 175%, 200%

**Comment by bsclifton** [comment] 2017-05-17 15:52
@srirambv are there any other steps you can think to try?  In your screenshot, you have two tab pages. Does this matter?

**Comment by srirambv** [comment] 2017-05-17 15:53
The root cause for the issue is the change in default zoom and UI scale. I had the UI scale set to `Smaller` and default zoom set to `90%`.

**Comment by srirambv** [comment] 2017-05-17 16:05
Changing either default zoom or UI scale causes the issue

**Comment by bsclifton** [comment] 2017-05-17 16:20
Great job narrowing this down, @srirambv 😄

**Comment by bradleyrichter** [comment] 2017-05-19 15:18
I think this may be related?

![image](https://cloud.githubusercontent.com/assets/13509546/26254534/c2bdb7d2-3c6b-11e7-8077-866828162354.png)

**Comment by bsclifton** [comment] 2017-05-19 18:30
Moving to 0.15.400 per conversation between @darkdh and @bbondy

**Comment by bsclifton** [comment] 2017-05-19 18:34
Seems to only happen when updating the Toolbar and UI elements scale; I can update the page zoom and nothing happens. Technically, this is just a bug, not a regression (since this functionality is new)
![screen shot 2017-05-19 at 11 33 31 am](https://cloud.githubusercontent.com/assets/4733304/26261713/1c4f3346-3c87-11e7-80f6-8fb42a4020f6.png)

**Closed** 2017-05-22 19:40 UTC
Labels: bug, feature/autofill
