### ISSUE TITLE
Weird color issue

### ISSUE THREAD

**Issue by pmo** [brave/browser-laptop#12059] opened 2017-11-22 08:50 UTC
### Description
I have noticed that blue color looks purple'ish on brave.
At first i thought it was my monitor as i just got a new one, but noticed that Firefox and Edge have the correct blue color, while edge does not.

### Steps to Reproduce
  1. open brave
  2. go to a site with blue color, i tested with facebook
  3. compare blue with other browser.

![capture](https://user-images.githubusercontent.com/571139/33117903-69d95530-cf6a-11e7-89f7-5466d2ba29b9.PNG)

**Expected result:**

Expected to be blue.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
cc0ebad

**Comment by bsclifton** [comment] 2018-01-08 06:40
Closing as unable to reproduce. I tried several browsers and it looks the same.  I know Facebook did change the colors somewhat recently- I suspect the browser in bottom screenshot either had styles cached or FB didn't roll out new style for yet

**Closed by bsclifton** 2018-01-08 06:40 UTC
Labels: needs-info

**Comment by jjhampton** [comment] 2018-06-17 02:54
@bsclifton I am also experiencing this while using Brave, **with Ubuntu v16.04**, with my laptop connected to an external monitor.  Blue unvisited link colors in search engines such as Google are rendered as a purple color:

![selection_065](https://user-images.githubusercontent.com/8835055/41504248-36f3172e-71b7-11e8-98bd-1d64794be853.png)

I've previously encountered this same issue while using Chrome on Ubuntu 16.04, and was able to solve the issue by disabling color correct rendering by setting `chrome://flags/#enable-color-correct-rendering` to Disable.  

Is it possible that Brave has this bug due to how it's based on Chromium / Blink? Being able to disable the "correct color rendering" would be nice to have, either via a `://flags` section, or some other way in the GUI.

References from others experiencing this same issue on Chrome w/ Linux:

- https://productforums.google.com/forum/#!topic/chrome/aovCd0JQ3j0;context-place=topicsearchin/chrome/ubuntu
- https://www.reddit.com/r/Fedora/comments/74h5yh/blue_shows_as_purple_in_chrome/
- https://productforums.google.com/forum/#!msg/chrome/p8Dig8f8SPo/gR713211AQAJ

**Comment by bsclifton** [comment] 2018-07-09 22:57
@pmo @jjhampton I believe there is a solution, can you try this?

When launching Brave via the CLI, add this extra param:
`--force-color-profile=srgb`

**Comment by bsclifton** [comment] 2018-07-09 22:58
Marked as duplicate since this is also reported with https://github.com/brave/browser-laptop/issues/14688

**Comment by jjhampton** [comment] 2018-07-11 01:12
@bsclifton The CLI solution works for my use case - thanks for looking into this and posting a solution. :+1:
