### ISSUE TITLE
Brave does not react on arrow keys while showing username suggestions on logins

### ISSUE THREAD

**Issue by GoldwingStudios** [brave/browser-laptop#3811] opened 2016-09-08 07:55 UTC
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
I'm trying to input a username which I have previously saved in brave. But as soon as I have enough letters typed in to get suggested usernames (which have been saved/used before) Brave isn't recognizing the default Chrome behaviour of navigating through the username suggestions via arrow keys. There is no response from brave with this function.

**Expected behavior:**
In Chrome this function enables the user to navigate through the suggested Usernames for a login which have been saved in Chrome

- Platform (Win7, 8, 10? macOS? Linux distro?):
W7

- Brave Version:
0.12.0

- Steps to reproduce:
    1. Save a uswername and password combination on a login site
    2. reload the site
    3. and type some of the letters for the username
    4. try to navigate via "up" and "down" button of the arrow keys

- Screenshot if needed:
I think I have covered it very well above.

- Any related issues:
...

**Comment by srirambv** [comment] 2016-09-08 08:05
Duplicate of #1302

**Closed by srirambv** 2016-09-08 08:05 UTC
