### ISSUE TITLE
Manually entered URL as bookmark doesn't show the bookmarked(orange) icon

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4273] opened 2016-09-24 20:57 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Manually entered URL as bookmark doesn't show the bookmarked(orange) icon

**Expected behavior:**
Should show the bookmarked icon when the link is opened

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.04

- Brave Version:
0.12.2 RC4

- Steps to reproduce:
    1. Add a new bookmark from bookmark toolbar
    2. Manually enter the webpage address and save
    3. Click on the bookmark icon, page loads but doesn't show the bookmarked icon (orange). Still shows the unbookmarked icon(gray)

- Screenshot if needed:
![bookmark](https://cloud.githubusercontent.com/assets/17010094/18811217/8aaf8430-82a1-11e6-9f07-ce52df281054.gif)

- Any related issues:

**Comment by alexwykoff** [comment] 2016-09-25 03:10
closing as a duplicate of https://github.com/brave/browser-laptop/issues/4260

**Closed by alexwykoff** 2016-09-25 03:10 UTC
Labels: bookmarks, duplicate
