### ISSUE TITLE
Cookies issue with Salesforce site

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1109] opened 2016-03-17 17:28 UTC
Hello Dev team,

at work we are using an internal site for salesforce and unless i allow the cookies by unticking "3rd party cookies" some parts of the sites won't load.

is it possible to have block 3rd party cookies option be per site/ per tab ?

Regards,
Haze

**Comment by bradleyrichter** [comment] 2016-03-17 19:56
@Haze-Aulaian 

We are planning on adding site-specific settings for cookies, ad blocking/replacement and HTTPSEv.

How often are you running into this, not including your obviously important salesforce need?


Thanks,
Brad

**Comment by Haze-Aulaian** [comment] 2016-03-17 20:18
i still didnt run into this on other than salesforce so far , but a friend of mine also mentioned that when it comes to internal work and confidential sites the browser is failing to load all the components completely. is there a way we can send you a debug output or a loading flow of the page without breaking confidentiality of our company ?

**Comment by bradleyrichter** [comment] 2016-03-17 21:48
@diracdeltas Can you help us with this one? Tx...

**Comment by diracdeltas** [comment] 2016-03-17 22:10
@Haze-Aulaian does the page work in Chrome with 3rd party cookies disabled? (Go to about:settings > Show advanced settings > Content settings > Block 3rd party cookies and site data.)

If it works in Chrome with that setting, the problem is most likely 3rd party referer blocking (which is grouped together in the menu with 3rd party cookies, we just don't expose it directly), not 3rd party cookie blocking.

**Comment by Haze-Aulaian** [comment] 2016-03-17 22:37
i will test that tomorrow at work again and let you know , thanks

**Comment by Haze-Aulaian** [comment] 2016-03-20 14:38
@diracdeltas , i have tested what you asked me to , when i enable "Block 3rd party cookies and site data"
The broken file symbol appear in Chrome but the site is partially loaded like in Brave.
Can you advise further ?

**Comment by diracdeltas** [comment] 2016-03-21 06:06
If it's broken in the same way in Chrome and Brave with 3p cookies blocked, then I think it's an issue with cookies not referer.

Unfortunately I don't think this is urgent for us to fix specifically for this site (since it's Salesforce-internal) but I do think we should site-specific settings by 0.9 so you can whitelist the page.

**Comment by bbondy** [comment] 2016-04-28 15:31
Closing this in favour of more generalized task for the site specific settings

**Closed by bbondy** 2016-04-28 15:31 UTC
