### ISSUE TITLE
Find (Ctrl+F) is extremely slow on Github

### ISSUE THREAD

**Issue by tcr** [brave/browser-laptop#5948] opened 2016-11-30 20:34 UTC
**Did you search for similar issues before submitting this one?** Yes.

**Describe the issue you encountered:** The find dialog takes upwards of 8s to load on Github.com.

**Expected behavior:** It is instantaneous.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.12.10

- Steps to reproduce:
    1. Go to https://github.com/brave/browser-laptop, particularly any long code or file preview
    2. Hit Command+F.
    3. Wait several seconds for the find dialog to appear.

- Screenshot if needed:

- Any related issues:

**Comment by Superbest** [comment] 2016-12-01 00:36
I can't reproduce this on the same version, although I have an i7 so it may be compensating. What hardware do you have? Also can you give a specific long page that causes this?

**Comment by tcr** [comment] 2016-12-01 01:22
https://github.com/brave/browser-laptop/blob/master/LICENSE.txt

I can open that and it takes about 4s for Ctrl+F to respond with the dialog.

> MacBook Pro (Retina, 15-inch, Mid 2015)
> Processor 2.5 GHz Intel Core i7

Weird that it's taking so long on my machine.

**Comment by tcr** [comment] 2016-12-01 01:26
Update: I closed all my tabs, opened a new window, and opened Github, and it was faster (around ~2s on first Ctrl+F). I had these tabs open when I opened a new Github tab to test it:

```
https://github.com/
https://www.getfpv.com/checkout/cart/
https://www.concursolutions.com/signin.asp
https://www.amazon.com/
https://internals.rust-lang.org/t/rust-and-gnome-meeting-notes/4339
http://www.fullchipdesign.com/
https://www.youtube.com/
https://github.com/brave/brave-laptop/
https://changelog.com/rfc/11
https://www.reddit.com/
http://forums.ni.com/t5/LabVIEW/FPGA-FIFO-Flip-flops-lut-block-memory/td-p/3215545
http://zone.ni.com/reference/en-XX/help/371599L-01/lvfpgaconcepts/fpga_implementation_options/
http://www.indienative.com/
```

**Comment by r3wt** [comment] 2016-12-01 06:10
Unable to repro:

Hardware:

i5-3230m/4gb
Opensuse 42.2 Tumbleweed (Linux)

**Comment by Superbest** [comment] 2016-12-01 20:16
@tcr yeah, that page is less than 0.3 secs for me. I'm on an i7-4790K w/ 4GHz.

**Comment by tcr** [comment] 2016-12-01 23:55
It may be related, but with no tabs open except for Github and little browser interaction, Brave is using 30% in two processes at a minimum. When typing, CPU spikes up to 50% for one of the processes. 
![image](https://cloud.githubusercontent.com/assets/80639/20817795/b7b547ea-b7f7-11e6-8b68-155b487f7b13.png)

**Comment by bsclifton** [comment] 2017-06-14 15:44
Awesome, great to hear! 😄  I'm going to close this issue, but I encourage folks having the issue to reopen and include details.  Thanks! 😄

**Closed by bsclifton** 2017-06-14 15:44 UTC
Labels: impact/high, needs-triage, perf
