### ISSUE TITLE
control + scroll to zoom needs to change

### ISSUE THREAD

**Issue by broros** [brave/browser-laptop#14172] opened 2018-05-18 15:04 UTC
### Description
control + scroll to zoom should be changed to ( command + scroll )
This is how it works on all other browsers, not sure why it is different on brave browser.

this is problematic especially on the mac since I need to do ( control key to right click on a web page )

**Comment by bsclifton** [comment] 2018-05-25 16:14
Thanks for the report, @broros! Closing as a duplicate of your existing issue: https://github.com/brave/browser-laptop/issues/10201

**Closed by bsclifton** 2018-05-25 16:14 UTC
