### ISSUE TITLE
Submit Feedback menu item doesn't do anything

### ISSUE THREAD

**Issue by justgrooving** [brave/browser-laptop#4559] opened 2016-10-05 19:08 UTC
Windows 7 on HP Elitebook

Wanted to send in a feedback suggestion

Just checked, Brave version is latest one 10/05/2016

**Comment by charbelrami** [comment] 2016-10-06 00:42
Reproduced. v0.12.4dev-Preview2, Win 10 64-bit

**Comment by diracdeltas** [comment] 2016-10-06 03:49
duplicate of #4487

**Closed** 2016-10-06 16:26 UTC
Labels: duplicate, verified
