### ISSUE TITLE
Zooming in/out with the menu does not work stable

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6796] opened 2017-01-21 03:23 UTC
**Describe the issue you encountered:**
Zooming in/out with the menu does not work stable

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.13.0 RC4

- Steps to reproduce:
    1. Open a page
    2. Zoom in with the buttons on the kabob menu
    
- Actual result: 100% -> 500%

- Expected result: 100% -> 110%

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
They do not reproduce. This issue may be an edge case

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![zoom](https://cloud.githubusercontent.com/assets/3362943/22171567/1e7257da-dfd4-11e6-8d52-f2471f235dac.gif)

- Any related issues:

**Comment by luixxiul** [comment] 2017-01-21 03:25
FWIW zooming in/out with the mouse wheel seems to be working as it should

**Comment by luixxiul** [comment] 2017-01-21 13:48
I set the milestone in case

**Comment by bbondy** [comment] 2017-01-21 14:07
wow nice find, ya we should fix it.

**Comment by luixxiul** [comment] 2017-01-21 14:17
@bbondy because this cannot be reproduced with a fresh profile, this may be an edge case

**Comment by bbondy** [comment] 2017-01-21 15:41
darn I did see it once but I can't reproduce it anymore, any other hints on how to repro?

**Comment by luixxiul** [comment] 2017-01-21 15:44
@bbondy how about enabling extensions to make the CPU usage of 1 core to 25%? #6799

**Comment by bbondy** [comment] 2017-01-22 13:20
doesn't happen in dev for me but happens in release, copied release profile to dev location and still doesn't happen in dev.

**Comment by luixxiul** [comment] 2017-01-22 13:33
> but happens in release

Should we add `release/blocking` label then?

**Comment by bbondy** [comment] 2017-01-22 13:39
I don't think we'll block on it but I'd like a fix if we can find it.  I can only reproduce on my release profile when pocket is enabled.  On my dev even if I enable pocket it doesn't reproduce.

**Comment by bbondy** [comment] 2017-01-22 14:11
should be fixed now, I tested with a production build.

**Closed** 2017-01-22 14:10 UTC
Labels: bug, help wanted, needs investigation

**Comment by luixxiul** [comment] 2017-01-22 14:51
@bbondy do you think e22b87c fixed #6799 as well?

**Comment by bbondy** [comment] 2017-01-22 21:16
I don't think so? But you can try.
