### ISSUE TITLE
Disable notifications about wallet (without enabling payments to uncheck notify)

### ISSUE THREAD

**Issue by rolandixor** [brave/browser-laptop#12432] opened 2017-12-28 16:44 UTC
### Description

There needs to be a way to opt out of the wallet feature all together, without being reminded every time I use the browser. "Maybe later" isn't enough.

### Steps to Reproduce

  1. Use Brave.
  2. Wait for it.
  3. "Would you like to blablabla, etc, etc, etc?" click "Maybe Later"
  4. Get mad, because it will pop up again.

**Actual result:**

See above.

**Expected result:**
It doesn't pop up again, and I can enable it when I'm ready or never bother to at all.

**Reproduces how often:**

100%.

### Brave Version

**about:brave info:**

Any.

**Reproducible on current live release:**

Yes.

**Comment by srirambv** [comment] 2017-12-28 16:56
Closing as dupe of #12226.

**Comment by srirambv** [comment] 2017-12-28 16:56
Way to disable notification is listed here https://github.com/brave/browser-laptop/issues/12226#issuecomment-350309486

**Comment by rolandixor** [comment] 2017-12-28 16:59
It doesn't work:

![selection_534](https://user-images.githubusercontent.com/558147/34417432-e2353230-ebce-11e7-9a71-993ad880741f.png)

**Comment by srirambv** [comment] 2017-12-28 17:00
Like mentioned in https://github.com/brave/browser-laptop/issues/12226#issuecomment-350309486 You need to enable payment and then go to advance settings and disable notifications. Once that is done you will stop receiving notifications and you can turn off payments.

**Comment by rolandixor** [comment] 2017-12-28 17:13
Sorry I'd misread the comment earlier.

It should be more simple than this though. The toggle should show in preferences by default.

**Comment by bsclifton** [comment] 2017-12-28 17:13
@rolandixor thanks for the report- this is definitely an issue on our side

You should be able to opt-out without having to enable payments.  That's a good work-around for now, but I re-opened the issue because we need to expose this setting

@bradleyrichter @davidtemkin can you help recommend a way to disable payment notifications WITHOUT enabling payments? Ex: should we add a new setting "Disable payment notifications" to the general settings?

**Comment by bradleyrichter** [comment] 2017-12-28 21:18
There is one easy way to fix this. 

On the first invitation, provide a "Not yet" button.

On the second notification, provide a "No thanks" button and don't show the alert again.


@rolandixor Would this approach have been acceptable for you?

**Comment by rolandixor** [comment] 2017-12-29 16:28
@bradleyrichter not quite. If there's a "first" notification, it should offer to reject this all together.

A better idea would be a dialogue with the options:

"Enable Payments", "More Info", "No Thanks"

**Comment by pongraczi** [comment] 2018-01-29 12:44
It seems it appears every 24th hours. Cannot opt-out. I understand, it is a fundamental feature or brave, even it would be nice to not annoy users who don't want to open a wallet, even with free tokens.

Still exists in:
 
Brave: 0.19.147 
rev: f1b90a31643cad8f4d76a4f729939d4f303b9a00 
Muon: 4.7.6 
libchromiumcontent: 64.0.3282.119 
V8: 6.4.388.40 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.13.0-32-generic 
OS Architecture: x64

I will check, what will happen tomorrow, as I did the mentioned workaround:
* enable wallet
* in advanced -> disable notification
* disable wallet

Otherwise, opt-out should work without magic or enable-disable wallet, thank you.

**Comment by NejcZdovc** [comment] 2018-04-09 06:16
closing this one as we added no option in #13465

**Closed by NejcZdovc** 2018-04-09 06:16 UTC
Labels: feature/ledger, needs-discussion, product/user-happiness, usability
