### ISSUE TITLE
Drop-down doesn't render; selecting blank item crashes browser

### ISSUE THREAD

**Issue by capouch** [brave/browser-laptop#4597] opened 2016-10-06 22:59 UTC
**Describe the issue you encountered:**
Font dropdown selector does not populate; choosing any (blank) item crashes browser

**Expected behavior:**
Select font from drop-down
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Linux Slackware
- Brave Version:
  0.12.3
- Steps to reproduce:
  1. Go to [https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html](url)
  2. Select "Launcher Icons"
  3. Choose "TEXT"
  4. Put some text in "TEXT" input box
  5. Click on "Font" drop-down (nothing shows)
  6. Select any blank line
  7. Browser crashes

Works fine on Chrome.
- Screenshot if needed:
  ![notext](https://cloud.githubusercontent.com/assets/5156230/19173634/afeefb3c-8bf6-11e6-9189-9e026c5e61af.png)

**Comment by Liunkae** [comment] 2016-11-19 18:42
Duplicate of #5213.

**Closed by Liunkae** 2016-11-19 18:42 UTC
Labels: crash, verified
