### ISSUE TITLE
PDF gets downloaded instead of opening 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10954] opened 2017-09-14 11:39 UTC
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
PDF gets downloaded instead of opening 
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 
- Brave Version (revision SHA):
0.18.29
- Steps to reproduce:
    1.  Visit this link http://www.fina.org/content/swimming-world-ranking
    2. Generate report, doesnt display
    3. Enable all cookies, pdf downloads
    4. Open same link in Chrome, loads the pdf and doesn't download
    
- Actual result:
PDF gets downloaded instead of opening 
- Expected result:
Should open 

- Is this an issue in the currently released version?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
https://community.brave.com/t/unable-to-create-report-in-fina/7092

**Comment by tbates** [comment] 2017-10-10 11:09
Confirmed on MacOS also.

The issue is that `prefs:extensions:Uses HTML5 to display PDF files directly in the browser` is either ON or OFF. When off, the file is treated as not having inline support, ergo, it is downloaded.

**Solution**: Offer third option "use system renderer…" which on Mac is the very capable preview. No doubt windows has similar.

**Comment by jamesray1** [comment] 2017-12-20 05:33
+1 for me, e.g. for: http://www.sungrowpower.com.au/files/Web_Files/Products/SH5K-_Quick%20User%20Manual%20v.1.4_201708.pdf

 
Brave: 0.19.121 
rev: 9e8ffc423a7061e5cafd262bb46c1ada17971db0 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64

**Comment by eljuno** [comment] 2018-05-21 17:47
+1 from community https://community.brave.com/t/pdfs-downloading-when-they-should-display/22376?u=eljuno

**Comment by srirambv** [comment] 2018-06-29 19:14
+1 from https://community.brave.com/t/pdf-not-opening-within-browser-for-few-websites/26552

**Comment by kelua6** [comment] 2018-09-22 23:41
+1 for me; it works in other browsers. https://pdfs.semanticscholar.org/5dcf/762f8d59d7eef039505e3d824787408d25bb.pdf

Brave : 0.24.0
V8 : 6.9.427.23
rev : f657f15
Muon : 8.1.6
OS Release : 10.0.17134
Update Channel : Release
OS Architecture : x64
OS Platform : Microsoft Windows
Node.js : 7.9.0
Tor : 0.3.4.8 (git-da95b91355248ad8)
Brave Sync : v1.4.2
libchromiumcontent : 69.0.3497.100

**Comment by bsclifton** [comment] 2018-09-24 22:29
Closing in favor of https://github.com/brave/brave-browser/issues/1264

**Closed by bsclifton** 2018-09-24 22:29 UTC
Labels: plugin/pdfjs, webcompat
