### ISSUE TITLE
Top context menu item for right-clicking on a hyperlink should be "open in new tab"

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#431] opened 2016-01-29 13:44 UTC
I almost never need "reload" when right-clicking a link. 90 percent of the time I want to open it in a new tab, 10 percent of the time I want to copy the target URL. I'm not sure how widespread those preferences are, but my muscle memory is programmed to find "open in new tab" at the top of the list. Having "reload" there is tripping me up.

**Comment by bbondy** [comment] 2016-01-29 14:35
Dupe of #407

**Closed by bbondy** 2016-01-29 14:35 UTC
