### ISSUE TITLE
Bookmarks are renamed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2486] opened 2016-07-14 15:43 UTC
From support:
> Some bookmarks display the wrong name in the drop down window, repeating the titles for other bookmarks.
>
>  it renamed itself “ESPN” from “Deadspin.” Curious that both websites that were changed were Gawker URLs. Probably a coincidence.
>
> ![](https://cloud.githubusercontent.com/assets/3362943/16845758/0120ca94-4a25-11e6-98e1-e4b5219fc924.jpg)

#2114

**Comment by bsclifton** [comment] 2016-08-30 18:27
I'd like to close this issue since I am not able to reproduce... but I'd encourage anyone reading this to please re-open the issue if you experience it too :smile: 

Here are the results I had (in bookmarks manager) when trying to repro:
![screen shot 2016-08-30 at 11 26 30 am](https://cloud.githubusercontent.com/assets/4733304/18101731/b81ebe10-6ea4-11e6-8168-0f9c01627389.png)

**Closed by bsclifton** 2016-08-30 18:27 UTC
Labels: bookmarks, bug
