### ISSUE TITLE
Audio indicator shows for any playing video / image

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#257] opened 2016-01-22 22:10 UTC
It should only show for playing audio, not for embedded GIF etc.

**Comment by luixxiul** [comment] 2016-05-13 17:51
Was this fixed?

**Comment by bbondy** [comment] 2016-05-13 18:10
no we still show it anytime there is playing video I think even when the audio is not there and muted.

**Comment by cezaraugusto** [comment] 2016-06-15 16:09
@bbondy what is the expected behavior? Should it include a muted icon if its muted and a video icon when its video?

Also, would it be a `good first bug`?

**Comment by bbondy** [comment] 2016-06-15 17:18
Probably no icon for video only with no sound.  But I think this might not be the best of first bugs unless you want to look into electron for a fix.

**Comment by paanvaannd** [comment] 2016-08-13 16:19
Something else I noticed about this behavior: my pinned [NYtimes](http://www.nytimes.com/?WT.z_jog=1&hF=t&vS=undefined) tab shows a blank spot (refer to screenshot below) where the audio playback status showed previously.

OS: macOS 10.12 Beta 4

About the issue:

* there was no audio or video playing in the main page but for an animation (I assume it was a GIF, as I saw no playback controls for it) on the main page
* the audio indicator showed that there was audio for the animation though there was not
* upon refreshing the page a couple hours later, the animation is no longer there on the front page though there is another GIF further down the page (definitely a GIF, no playback controls there)
* the pinned tab now has a blank area where the indicator was previously though there is no indicator there now
* unpinning and re-pinning the tab does not fix the gap issue
* creating a new tab for the same URL and pinning it results in a normally pinned tab without the gap as mentioned above

![tab](https://cloud.githubusercontent.com/assets/16567134/17644286/0d1929c6-6150-11e6-9253-ac73c894a24b.png)

**Comment by cgjones** [comment] 2016-09-24 03:13
I'm seeing the narrower issue of a gap remaining in the pinned tab area in Brave 0.12.1, OS X 10.11.6, when chatting in gmail pinned tab:
<img width="89" alt="screen shot 2016-09-23 at 8 05 30 pm" src="https://cloud.githubusercontent.com/assets/325916/18805695/a3009a84-81c9-11e6-84eb-6808f517dca3.png">
The audio snippets from chat notifications are pretty quick, so this smells like some kind of race condition.

Since this is happening after the audio-playing indicator is being displayed correctly, should we file a separate issue for this rendering glitch?  (In other words, this issue could be resolved, but most likely the intermittent rendering glitch would remain.)

**Comment by bsclifton** [comment] 2016-12-31 09:43
+1 from https://github.com/brave/browser-laptop/issues/6488

> Steps to reproduce:
> - Navigate to https://twitter.com/ThePracticalDev/status/814551019522785280
> - Click the blue play button
> - Observe tab contents as GIF plays

**Comment by aleclarson** [comment] 2017-07-20 15:08
Getting an audio indicator for a `<video>` element with `muted` (and no audio track to begin with).

**Comment by bsclifton** [comment] 2018-08-06 20:06
Closing as `wontfix` since this is fixed with [Brave Core](https://github.com/brave/brave-browser)

**Closed by bsclifton** 2018-08-06 20:06 UTC
Labels: bug, fixed-with-brave-core, wontfix
