### ISSUE TITLE
Fresh Install of Brave Advertises Brave Properties

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7655] opened 2017-03-11 17:48 UTC
## Test plan

https://github.com/brave/browser-laptop/pull/7753#issue-214852343

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
A fresh install of Brave yields advertisements for Brave. This took at least one user by surprise when they tried the browser. Their feedback is available [on Twitter](https://twitter.com/JulianNorton/status/840614856919252994):

![image](https://cloud.githubusercontent.com/assets/815158/23825495/6a380f8c-0650-11e7-8783-88215b669214.png)

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
0.13.5

- Steps to reproduce:
    1. Install Brave
    2. Type 'facebook' into address bar
    3. Brave auto-completes to 'facebook.com/brave'
    
- Actual result:
Brave _advertises_ its own properties on a fresh install.

- Expected result:
User expects no advertisements or promotion

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Steps repro for 'twitter'
    2. Steps repro for 'youtube'
    3. Steps repro for 'itunes'

#5594

**Comment by bsclifton** [comment] 2017-03-12 04:48
Duplicate of https://github.com/brave/browser-laptop/issues/5892

cc: @bradleyrichter, @bbondy, @alexwykoff (in case we wanted to take action other than closing as a dupe)

**Comment by bradleyrichter** [comment] 2017-03-12 11:16
This is the worst (or best) example of this "bug" and we should block on it. 

Of course this is a side effect of preloading top sites in the dashboard. 

In this example, the search result suggestion should not be pre-filled but rather presented in the list and require a down arrow to access. 

We may want to also create a new issue to mask out the preloaded top sites from the search suggestions so that this unintentional advertising is not perceived as intentional.

**Comment by diracdeltas** [comment] 2017-03-13 23:43
Seems like the user is asking for the preloaded Brave sites to not be in the urlbar suggestions at all

**Comment by bsclifton** [comment] 2017-03-13 23:56
@diracdeltas yup- we should be able to edit the site details to include a "leave me out of suggestions" flag. If the user then chooses to bookmark that site, we'd just want to clear that 😄

**Comment by bsclifton** [comment] 2017-03-16 19:10
Reopening and removing milestone since the fix for this was reverted with https://github.com/brave/browser-laptop/commit/e23e25112a091a078aa49b810d1d6222c978bc99

**Comment by luixxiul** [comment] 2017-03-23 03:55
On the latest master on macOS I still see the URL.

<img width="401" alt="screenshot 2017-03-23 12 53 48" src="https://cloud.githubusercontent.com/assets/3362943/24231408/e31f935e-0fc7-11e7-9769-acf21db47015.png">

I'm reopening the issue in case. Please close it if it is related with another issue, thanks.

**Comment by diracdeltas** [comment] 2017-03-23 04:13
@luixxiul it works for me on master. do you have 23d813cdcd4b06f37d0d51ff40c4154ac0aa7832 ?

**Comment by luixxiul** [comment] 2017-03-23 04:23
The branch was not updated, sorry for confusion!

**Closed by luixxiul** 2017-03-23 04:23 UTC
Labels: bug, feature/newtab, QA/steps-specified, release-notes/include
