### ISSUE TITLE
Non-functional Column ordering in Brave Payments Tab

### ISSUE THREAD

**Issue by aliakyurek** [brave/browser-laptop#12724] opened 2018-01-19 10:12 UTC
### Description
The leftmost column in Brave Payments tab indicates whether the web site/Youtube channel is verified or not. When I click the header of this column I'd expect the entries to be ordered depending on verified status.

### Steps to Reproduce
  1. Open Settings -> Payments
  2. Click the header of leftmost column in the table showing websites/Youtube channels.

**Actual result:**
Order indicator arrow is shown, but has no effect.
![image](https://user-images.githubusercontent.com/5635699/35145660-c3cff486-fd19-11e7-9202-712f0abe4678.png)

**Expected result:**
Entries to be ordered as per their verified status.

**Reproduces how often:**
Always

### Brave Version
**about:brave info:**
Brave: 0.19.134 
rev: 316cfa522ffe6a558fe9f2f3f299c0c602dfb691 
Muon: 4.5.38 
libchromiumcontent: 63.0.3239.132 
V8: 6.3.292.49 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 6.1.7601 
OS Architecture: x64

**Reproducible on current live release:**
Yes

**Comment by NejcZdovc** [comment] 2018-01-20 07:56
hi, thank you for the report. We already have an issue for this and will be fixed soon.

Closing as dupe of #10752

**Closed by NejcZdovc** 2018-01-20 07:56 UTC
Labels: feature/ledger
