### ISSUE TITLE
Moving First Bookmark in Expanded Bookmarks Moves Entire Window

### ISSUE THREAD

**Issue by sjlehn** [brave/browser-laptop#10323] opened 2017-08-07 14:17 UTC
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
My bookmarks toolbar has enough entries to trigger the overflow chevrons.  If I try to move the first bookmark out of that menu, the entire browser window moves, and not only the bookmark

- Platform (Win7, 8, 10? macOS? Linux distro?):
OSX 10.11.6 (15G1611) (El Capitan)

- Brave Version (revision SHA):
ad92d02

- Steps to reproduce:
    1. Add enough bookmarks to bookmark bar to trigger overflow
    2. Open the overflow menu and attempt to drag the first (top) entry back to the bookmarks bar
    
- Actual result:
Entire browser window moves

- Expected result:
Bookmark moves, as it does in other positions

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
It should - I'd only imported bookmarks on a clean install

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
On my machine, it happens every time

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by pullingour** [comment] 2017-08-08 20:03
Same problem here.

- Platform (Win7, 8, 10? macOS? Linux distro?):
OSX 10.11.6 (El Capitan)  

- Brave Version (revision SHA):
0.18.14 https://github.com/brave/browser-laptop/commit/ad92d029e184c4cff01b2e9f4916725ba675e3c8  
- Can this issue be consistently reproduced?
Yes  
- Any related issues:
folder size has unnecessary length after put into bookmark
- Screenshot if needed:  

![bug2](https://user-images.githubusercontent.com/7346730/29091666-a61dc642-7cbe-11e7-8b06-5200fb2194b5.gif)

**Comment by NoirKamui** [comment] 2017-08-15 09:03
This doesn't happen when there is an open tab under it. In other words, if the tab bar has not an open tab, every click above it is perceived as clicking on the tab, even if its on a link that's above it.
PS: I would advise to make it possible to move the tab bar all together to the top. Thank you for your efforts.

**Comment by NejcZdovc** [comment] 2017-08-15 09:39
@sjlehn @pullingour @NoirKamui could be this the same one as #9088?

**Comment by NoirKamui** [comment] 2017-08-15 10:20
@NejcZdovc Yes, that seems to be exactly it. Thank you for finding it. I guess it's an ongoing issue.

PS: I installed Brave yesterday and the tabs-bar can be quite annoying to new people I guess. I will come back to Brave in a few weeks. I would like to have a safe independent browser once it gets polished :) Good luck team!

**Comment by NejcZdovc** [comment] 2017-08-15 10:40
@NoirKamui we will work hard to provide best experience ASAP. Right now most of the team is intensively working on performance part and after that we will shift focus back on UI/UX. We would live to give you a browser that you will enjoy using it and be safe at the same time.

closing this as dupe of #9088

**Closed by NejcZdovc** 2017-08-15 10:40 UTC
Labels: bug, feature/bookmarks, feature/context-menu, misc/drag-and-drop

**Comment by luixxiul** [comment] 2017-08-15 11:25
do not forget to add the duplicate label. I did for you this time. thanks
