### ISSUE TITLE
Keyboard shortcut(s) activating the menu bar

### ISSUE THREAD

**Issue by slmeyer** [brave/browser-laptop#13937] opened 2018-04-25 10:47 UTC
I Have searched here and on the net for similar issues!

### Description

The menu system should for productivity and accessibility reasons (for me specifically access to the bookmarks without using the mouse) have associated keyboard shortcuts ('Alt+<a..z>') activating and transferring focus to the different menus and the menus should be marked with an underscore under the actual <a..z> in the menu name.

Alternatively 'F10' or another shortcut (even 'Alt') should not only make the menu visible but also transfer focus so the arrow keys can be used for navigating the menus

### Steps to Reproduce

  1. Open Brave
  2. verify that 'Alt' toggles the menu bar on and off
  3. verify that even when on, it has no focus
  4. verify that 'F10', 'Alt+f' or 'Alt+b' does nothing

**Expected result:**
  1. Open Brave
  2. 'Alt+f' activates the menu bar making it visible, drops down the file menu and lets it hold focus for the keyboard cursor
  3. 'Alt+b' activates the menu bar making it visible, drops down the bookmark menu and lets it hold focus for the keyboard cursor
  4. etc for all menus

Alternatively

  1. Open Brave
  2. 'Alt' toggles the menu bar on and transfers focus for the keyboard cursor 
  3. verify that activating the arrow keys navigate the menu system

**Reproduces how often:**

Always

### Brave Version

**Reproducible on current live release:**

**Comment by bsclifton** [comment] 2018-04-26 17:09
Thanks for the report, @slmeyer ! I'm going to close this issue as it's a duplicate of https://github.com/brave/browser-laptop/issues/2949

**Comment by bsclifton** [comment] 2018-04-26 17:10
Actually- there are some details here which are not duplicates. Being able to navigate using keyboard should work

**Comment by bsclifton** [comment] 2018-09-07 16:18
This will no longer be a problem with our [Developer channel](https://brave.com/download-dev) 😄

**Closed by bsclifton** 2018-09-07 16:18 UTC
Labels: OS/Windows, addressed-with-brave-core, feature/keyboard-shortcuts, windows-important

**Comment by slmeyer** [comment] 2018-09-07 19:43
I tried to install the brave-git version, but it does not appear - maybe it is not the correct version to try it out:

Name | Version
-- | --
Brave | 0.25.0
V8 | 6.8.275.24
rev | 4fd01a8

**Comment by bsclifton** [comment] 2018-09-08 07:39
@slmeyer our developer channel switches from this code-base (`browser-laptop`) to a new code-base (called `brave-core`, which has issues tracked in the `brave-browser` repo)

You can try downloading this new build here:
https://brave.com/download-dev
