### ISSUE TITLE
wrong alert bar used for app-level alerts:

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#8934] opened 2017-05-18 17:55 UTC
![image](https://cloud.githubusercontent.com/assets/13509546/26216318/7b482daa-3bb8-11e7-8650-e33a77a3dc4f.png)
The original alert bar should be used. (the one which is located above the tabs bar, and does not include the orange bottom border.

**Comment by luixxiul** [comment] 2017-10-04 17:20
adding the milestone just in case.

**Comment by diracdeltas** [comment] 2017-10-04 18:30
This isn't a problem for all app alerts - for instance the update alert bar appears in the right place. 

https://github.com/brave/browser-laptop/issues/11256 is probably a duplicate of this

**Comment by bsclifton** [comment] 2017-10-04 18:33
Closing this issue as a duplicate of https://github.com/brave/browser-laptop/issues/11256 (the issue you created @diracdeltas has much better info / requirements 😄 )

**Closed by bsclifton** 2017-10-04 18:33 UTC
Labels: bug, feature/ledger, feature/notificationbar, needs-triage
