### ISSUE TITLE
Selecting URL with right arrow key from the pulldown on URL bar re-selects the 1st entry

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8899] opened 2017-05-17 03:56 UTC
**Describe the issue you encountered:** Selecting URL with right arrow key from the pulldown on URL bar re-selects the 1st entry.

![autocomplete](https://cloud.githubusercontent.com/assets/3362943/26137777/459191ba-3aff-11e7-8edd-1a30702c6ea8.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?): debian

- Brave Version (revision SHA): 0.15.304

- Steps to reproduce:
    1. Open https://github.com
    2. Open several pages from the menu
    3. Close the tabs
    4. Input `github` to URL bar
    5. Hit <kbd>down arror key</kbd>
    5. Try selecting a URL from the pulldown with <kbd>right arrow key</kbd>
    
- Actual result: the 1st URL is always re-selected

- Expected result:

- Is this an issue in the currently released version?
  No. The issue cannot reproduced on .300. I tried .303 and it can be reproduced. 

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by bsclifton** [comment] 2017-05-17 17:43
reproduced on dev-channel (which is just a bit ahead of .304).  Will look into this

**Comment by bsclifton** [comment] 2017-05-17 21:15
Removing milestone and closing as a duplicate of https://github.com/brave/browser-laptop/issues/5767

**Comment by bsclifton** [comment] 2017-05-17 21:15
removed regression tag also, as this has been an issue for a while

**Comment by luixxiul** [comment] 2017-05-18 00:09
I don't think this is the duplicate. This time with right arrow key you cannot select nothing than the 1st item. Here's a better STR:

1. Visit github.com
2. Visit github.com/brave/browser-laptop/issues/8899#issuecomment-302233759
3. Input `github.com`
4. Select github.com/brave/browser-laptop/issues/8899#issuecomment-302233759 with the down arrow key
5. Hit right arrow key
6. github.com is re-selected

**Comment by luixxiul** [comment] 2017-05-18 00:10
CC @srirambv for reproduction

**Comment by bbondy** [comment] 2017-05-18 18:36
This seems to be fixed with my various commits for work on suggestions. Closing but please test.

**Closed by bbondy** 2017-05-18 18:36 UTC
Labels: bug, feature/URLbar
