### ISSUE TITLE
Some YouTube ads can leak through

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1088] opened 2016-03-16 13:57 UTC
<img width="758" alt="screenshot 2016-03-16 09 56 26" src="https://cloud.githubusercontent.com/assets/831718/13814642/6edefd8e-eb5d-11e5-884e-67af67397f59.png">

https://www.youtube.com/watch?v=5QpB607FdB4

**Comment by thebagmaster** [comment] 2016-05-24 16:24
Looks like google has circumvented your adblock on youtube. They play anyways, always for me.

**Comment by brianroach** [comment] 2016-06-21 20:58
@thebagmaster ALL youtube ads play for me as well. Such a bummer.

**Comment by arturdpo** [comment] 2016-06-23 12:42
Two days ago started to play ads on youtube to me.

**Comment by cezaraugusto** [comment] 2016-07-13 05:32
Related: #1513 #1601

Can't reproduce it with v0.11.0.

I think sites (specially the ones related to Google) will always find ways to unblock ads.

Closing until someone reports that it's still happening.

**Closed by cezaraugusto** 2016-07-13 05:32 UTC

**Comment by Spreadyy** [comment] 2016-07-18 08:06
![2016-07-18 10_00_19-to know ted cruz is to wish you didn t - youtube](https://cloud.githubusercontent.com/assets/12650063/16908862/e571fc08-4cce-11e6-8d5d-c23aa02fa05d.png)
Problem still happens, uBlock origin is able to block these ads.

**Comment by arturdpo** [comment] 2016-07-18 12:30
It's true.

To me too.

[image: Imagem inline 1]

The version of Brave

[image: Imagem inline 2]


Shalom,

Artur Oliveira
http://lattes.cnpq.br/8376259030692921
arturdpo@gmail.com
arturrn@hotmail.com
Skype: artur.mjrn

2016-07-18 5:06 GMT-03:00 Spreadyy <notifications@github.com>:

**Comment by luixxiul** [comment] 2016-07-18 12:37
Maybe local filter will be required here

**Comment by bbondy** [comment] 2016-07-18 12:45
Does anyone know of a video that will always give an ad? I tried the original poster's URL and it has no ads for me even when adblock is off. Links are more useful than screenshots for this one, thx.

**Comment by arturdpo** [comment] 2016-07-18 12:50
​Try this: https://www.youtube.com/watch?v=3zOc1brriIE

Regards​.


Shalom,

Artur Oliveira
http://lattes.cnpq.br/8376259030692921
arturdpo@gmail.com
arturrn@hotmail.com
Skype: artur.mjrn

2016-07-18 9:45 GMT-03:00 Brian R. Bondy <notifications@github.com>:

**Comment by bbondy** [comment] 2016-07-19 12:31
Sorry no ads there for me, I think we are suffering from regional problems w/ reproducing.  I think maybe localized adblock definition files will help though like @luixxiul suggested.

**Comment by Spreadyy** [comment] 2016-07-20 15:17
@bbondy can you use a proxy to reproduce the issue?

**Comment by vjdhama** [comment] 2016-07-29 15:57
The youtube ads still play on brave. I think youtube found a way circumvent brave.

**Comment by arturdpo** [comment] 2016-08-04 14:41
Ir's true.

https://www.youtube.com/watch?v=wOetESDvVZw&index=1&list=PLxSX2wcsldqbuuyw4QY8TtJ2kerilDfPQ

Whe i've used ad block this never happened.


Shalom,

Artur Oliveira
http://lattes.cnpq.br/8376259030692921
arturdpo@gmail.com
arturrn@hotmail.com
Skype: artur.mjrn

2016-07-29 12:58 GMT-03:00 Vijay Dhama <notifications@github.com>:

**Comment by hallzy** [comment] 2017-03-10 21:19
https://www.google.ca/search?q=trying+to+get+ads&gws_rd=cr&ei=ahfDWLCeGKmW0gLqnI9Q

![2](https://cloud.githubusercontent.com/assets/5404143/23813528/21544cac-0594-11e7-9ad7-b9731c0aea4a.png)

**Comment by luixxiul** [comment] 2017-03-11 04:20
that issue is duping to #344
