### ISSUE TITLE
What is this ? Update

### ISSUE THREAD

**Issue by Kzeir** [brave/browser-laptop#1044] opened 2016-03-09 14:34 UTC
When I update my browser, apear this. I don't know Java Script so I don't understand this ... 
![error](https://cloud.githubusercontent.com/assets/17557010/13638393/d1aec44e-e5ea-11e5-823a-ae4ff07d7c06.png)

**Comment by bbondy** [comment] 2016-03-09 14:42
Is it persistent or did it just appear once?

**Comment by Kzeir** [comment] 2016-03-09 14:44
It appear before I update and restart the browser, only in this situation.

**Comment by bbondy** [comment] 2016-03-09 14:48
ok this is a dupe of #729 so I'll close it in favour of that bug.

**Closed by bbondy** 2016-03-09 14:48 UTC
