### ISSUE TITLE
Copying from Brave intermittently doesn't work, restart fixes.

### ISSUE THREAD

**Issue by alex-wilmer** [brave/browser-laptop#1060] opened 2016-03-11 15:16 UTC
Any text I copy from a webpage does not get added to my clipboard. I can copy the url from the address bar but not any page content.

Yosemite 10.10.5, macbook pro

**Comment by bbondy** [comment] 2016-03-11 15:42
Which page? I'm copying tedxt from your comment above OK. I think I have seen this before though and am not sure how to reproduce.

**Comment by alex-wilmer** [comment] 2016-03-11 15:46
Doesn't look like any of them.. I noticed because I was trying to copy a branch name from github, but just checked reddit and can't copy anything from there either.

```
Version: 0.8.0
Electron: 0.36.8
libchromiumcontent: 47.0.2526.110
Channel: dev
```

I could make a video out of it if that helps. I'm also a JS / React developer so I can work on this over the weekend.

**Comment by bbondy** [comment] 2016-03-11 15:52
that'd be great, I have seen this before but it's working now so it's intermittent.  If you close your browser and re-open it might go away.

**Comment by alex-wilmer** [comment] 2016-03-11 15:58
Ah restarting fixed this indeed. Any idea why?

**Comment by bbondy** [comment] 2016-03-11 16:01
no but if you find something that triggers it pls let me know!  Command+Alt+J gives you the browser level dev tools (+I gives you the per web page one). Next time you're in that state maybe you could poke around and try things.

**Comment by bbondy** [comment] 2016-03-11 16:07
I'll attempt a fix for 0.8.1 but not sure if it'll work or not.

**Comment by alex-wilmer** [comment] 2016-03-11 16:08
Ah thanks! I was looking for those dev tools! I've been using Brave for a few hours now and thought to myself.. "funny, I can't dock the dev tools!".

I'll go through the Readme and any developer docs after work.

**Comment by bbondy** [comment] 2016-03-11 16:10
You can only doc the browser level ones due to a limitation in electron, we'll fix it in electron when we have a bit more time so you can doc the more common content level dev tools too.

**Comment by bbondy** [comment] 2016-03-11 16:11
If you see this in 0.8.1 please comment here and we'll re-open.

**Comment by bbondy** [comment] 2016-03-17 13:13
This is still an intermittent issue so re-opening.

**Comment by bbondy** [comment] 2016-03-17 13:14
We need to find more information about how to reproduce this, or investigate while it's reproduced to get it fixed.

**Comment by bbondy** [comment] 2016-03-26 19:16
Had this happen again, adding another observation:
When Command+C (Control+C) doesn't work you can right click on the text and select Copy on the context menu. That copies the text successfully and also makes the copy of selected text work again from Command+C.

**Comment by bbondy** [comment] 2016-04-06 02:49
Had this happen again, got a lot more info:

Opening dev tools this works:
var clipboard = require('electron').clipboard;
clipboard.writeText('test')
Successfully copies text to the clipboard but the problem persists

Selecting the main menu item:
Reproduces the problem

Control+C:
Reproduces the problem
Even if you press Control+C various times in a  row.

Using the context menu to copy:
Successfully copies text to the clipboard and the problem goes away moving forward
Even just right clicking fixes the problem.

Using the paste top level menu item works fine.

**Comment by adamcmacdonald** [comment] 2016-04-14 17:16
+1 able to fully reproduce problems on OSX 10.11.4

**Comment by kenorb** [comment] 2016-05-07 00:46
Same here on OS X 10.11.2 with Brave 0.9.4.

Basically CMD-C does nothing (even on this page), apart of copying URL. Pasting works fine, but it's just pasting the old thing.

**Comment by something99** [comment] 2016-05-26 22:53
Same, OSX 10.11.4 and Brave 0.10.0. 
I've encountered this issue for a second time in a week. Can't copy anything new on Brave, pastes the old thing, other browsers and Word are fine though. Last time restarting the browser solved it.

**Comment by bbondy** [comment] 2016-05-30 14:52
More information on this.
When it happens the top level menu item doesn't work either for Copy.
But the menu and shortcut does work for Cut.

I suspect it's something relating to the menu itself or the role we use for it.

**Comment by bbondy** [comment] 2016-06-04 14:15
This seems to be fixed in 0.10.2 with @diracdeltas 's change. Closing for now.

**Closed by bbondy** 2016-06-04 14:15 UTC

**Comment by joshbabier** [comment] 2017-08-23 13:10
Still happening. MacOS 10.12.6

**Comment by bsclifton** [comment] 2017-09-17 06:17
@joshbabier we should have a fix for this soon- we're tracking with https://github.com/brave/browser-laptop/issues/10563 if you wanted to follow along 😄
