### ISSUE TITLE
Add cut/copy/paste to hamburger menu

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1421] opened 2016-04-20 19:49 UTC
For parity, it's there in both firefox and Chrome.

**Comment by bbondy** [comment] 2016-04-20 20:43
Was going to slip this one in 0.9.2 but there was a complication with when you click the menu button it takes away the focus of the selection.


WIP for whoever does this in the future:


```
diff --git a/js/contextMenus.js b/js/contextMenus.js
index 52b0b43..882cad7 100644
--- a/js/contextMenus.js
+++ b/js/contextMenus.js
@@ -449,6 +449,29 @@ function hamburgerTemplateInit (braverySettings, location, e) {
       ]
     },
     CommonMenu.separatorMenuItem,
+    {
+      l10nLabelId: 'edit',
+      type: 'multi',
+      submenu: [{
+        l10nLabelId: 'cut',
+        click: () => {
+          remote.getCurrentWindow().webContents.cut()
+          console.log('cut')
+        }
+      }, {
+        l10nLabelId: 'copy',
+        click: () => {
+          remote.getCurrentWindow().webContents.copy()
+          console.log('copy')
+        }
+      }, {
+        l10nLabelId: 'paste',
+        click: () => {
+          remote.getCurrentWindow().webContents.paste()
+          console.log('paste')
+        }
+      }]
+    },
     CommonMenu.findOnPageMenuItem(),
     CommonMenu.printMenuItem(),
     CommonMenu.separatorMenuItem,

```

**Comment by bkilrain** [comment] 2017-01-20 21:27
I'm happy to give this a go~

**Comment by bsclifton** [comment] 2017-01-20 22:47
@bkilrain great! Let me know if you have any questions :smile:

**Comment by bsclifton** [comment] 2017-03-13 05:05
I was thinking about removing the `good first bug` label, since there are some complications with regard to focus... but this is a good discrete issue.  I'd love to help anyone who would like to give it a go

You can see a previous contributor, @bkilrain, and his commits above.  He was really close- the problem is that clicking the menu takes away focus from what is highlighted (for cut/copy/paste). However, you can look at the Windows `menubar` control for an example of how to properly handle this 😄

**Comment by LaurenWags** [comment] 2017-08-21 13:20
+1 from community: https://community.brave.com/t/add-a-paste-menu-entry-button-to-the-3-dot-menu-in-the-tab-bar/6370

**Comment by eljuno** [comment] 2018-01-03 20:02
+1 from community https://community.brave.com/t/cut-and-past-function-in-menu/13089?u=eljuno

**Comment by srirambv** [comment] 2018-05-10 15:12
Removing milestone as its going to be fixed with brave-core

**Closed** 2018-07-25 06:43 UTC
Labels: fixed-with-brave-core, misc/clipboard, parity, wontfix
