### ISSUE TITLE
Issue with Unidentified Application Developer on OSX

### ISSUE THREAD

**Issue by weems** [brave/browser-laptop#733] opened 2016-02-11 18:45 UTC
1. Issue with Application which whose Developer Certificate is not "Identified" with OSX: <img width="504" alt="screen shot 2016-02-11 at 12 38 57 pm" src="https://cloud.githubusercontent.com/assets/470705/12986443/e85cc562-d0bc-11e5-959a-82795d117824.png">
2. Application OSX Security Settings are such that only Mac App Store Applications are allowed to run:<img width="446" alt="screen shot 2016-02-11 at 12 38 24 pm" src="https://cloud.githubusercontent.com/assets/470705/12986446/ea78cf1c-d0bc-11e5-89da-2b85fa63af66.png">

1 May be fixed by changing OSX Security Settings to allow Apps other than Mac Store Applications to Run in System Preferences. I had previously allowed Brave to run so I was able to run it, but if a User had not allowed the Application in System Preferences -> Security they would have to enable it there before it can run as Brave is not a "Identified Developer" to OSX.

**Comment by luixxiul** [comment] 2016-05-17 04:24
Already fixed? I cannot reproduce this as I don't have OS X machine

**Comment by Liunkae** [comment] 2016-09-26 07:08
Brave is currently signed with a developer ID. This is the most secure way to distribute applications outside the Mac App Store.

Since:
1. Brave should automatically work for most macOS users (with "App Store and identified developers" selected), and
2. there is an easy workaround for when it doesn't work (select "App Store and identified developers"),
I'm going to close this issue.

**Closed by Liunkae** 2016-09-26 07:08 UTC
Labels: macOS-only
