### ISSUE TITLE
Bookmark Icons are not displayed in toolbar

### ISSUE THREAD

**Issue by decode-dev** [brave/browser-laptop#10671] opened 2017-08-26 08:24 UTC
- Did you search for similar issues before submitting this one?
 Yes

- Describe the issue you encountered:
Bookmark Icons are not displayed in the toolbar even though it has lot of space to be shown

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10 x64

- Brave Version (revision SHA):
0.18.23 Dev

- Steps to reproduce:
    1.Open Brave, have lots of bookmarks.
    2.Display bookmarks on toolbar.
    3.You will find some bookmark icons are not displayed on the toolbar even though it has space to display them.
    
- Actual result:
Should show bookmark icons in the toolbar 
- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![brave](https://user-images.githubusercontent.com/6382146/29739854-0154bd4a-8a66-11e7-9cfd-49b3067bb206.JPG)

- Any related issues:

**Comment by luixxiul** [comment] 2017-08-26 08:29
duplicate of https://github.com/brave/browser-laptop/issues/9939#issue-241757039

**Closed by luixxiul** 2017-08-26 08:29 UTC
Labels: feature/bookmarks
