### ISSUE TITLE
When I open Brave this loads: file:///C:/Users/steve/AppData/Local/brave/app-0.12.14/Brave.exe

### ISSUE THREAD

**Issue by Skiiowa** [brave/browser-laptop#6189] opened 2016-12-13 18:42 UTC
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment] 2016-12-14 01:15
Hi folks - 

This issue has been captured with https://github.com/brave/browser-laptop/issues/6075 and we are testing a fix for this right now. I'll close this issue out since it's a duplicate, but please stay tuned :smile: 

If you're curious about the root cause, full issue details can be found here:
https://github.com/Squirrel/Squirrel.Windows/issues/900

cc: @bdukes, @Brendon-Coombes

**Closed by bsclifton** 2016-12-14 01:15 UTC
