### ISSUE TITLE
CTRL + PgUp|PgDown has stopped working (switching opened tabs)

### ISSUE THREAD

**Issue by crysman** [brave/browser-laptop#7790] opened 2017-03-20 10:35 UTC
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
CTRL + PgUp|PgDown has stopped working, that is switching opened tabs, as it used to do, and as is standard in FF or Chromium

- Platform (Win7, 8, 10? macOS? Linux distro?):
Xubuntu

- Brave Version (revision SHA):
Brave	0.13.5 rev	1db81cb

- Steps to reproduce:
    1. open at least two tabs
    2. try to switch between them via CTRL+PgUp/Down
    
- Actual result:
nothing happens at all

- Expected result:
tab is switched to the left/right as it does in other browsers

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
don't know

- Is this an issue in the currently released version?
don't know, but I'm fetching Brave automatically via PPA

- Can this issue be consistently reproduced?
I believe so.

- Any related issues:
Maybe #6593

**Comment by NejcZdovc** [comment] 2017-03-20 10:42
@crysman Can you pleas try out our latest preview https://github.com/brave/browser-laptop/releases/tag/v0.14.0dev-Preview3

Maybe this commit https://github.com/brave/browser-laptop/commit/5a889ccd6198906537f0c29d4b28067292a4ef78 fixed issue this as well

**Comment by bsclifton** [comment] 2017-03-20 16:36
@NejcZdovc yes- this issue was fixed with that commit 😄  This issue is a duplicate of https://github.com/brave/browser-laptop/issues/7491.

@crysman we'll have this fixed with our next release (hopefully this week?) Stay tuned

**Closed by bsclifton** 2017-03-20 16:36 UTC
Labels: feature/keyboard-shortcuts, info-needed

**Comment by crysman** [comment] 2017-03-21 17:54
Alt+LEFT|RIGHT arrow to history -> back/forward also has stopped working :/ Is that the same issue?

**Comment by bsclifton** [comment] 2017-03-21 18:42
@crysman yup- that is correct.  Our latest release (preview 4) is fairly stable if you wanted to check it out https://github.com/brave/browser-laptop/releases/tag/v0.14.0dev-Preview4
