### ISSUE TITLE
Issue with webex meetings

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1675] opened 2016-05-11 12:00 UTC
Hello Dev team,

please note that i can't start a webex meeting from the browser it self.
its showing that it detected a chrome browser.
Please note that webex is part of my daily job to support customers remotely.
im actually misleaded here , is brave based on chrome ?

OS : windows 7 64 bit (SP1)
Brave : 0.9.4

When i click add webe to chrome nothing happens:

![webexissue](https://cloud.githubusercontent.com/assets/17910355/15180254/15cf9764-1789-11e6-89a9-6337416b70c4.PNG)

**Comment by diracdeltas** [comment] 2016-05-11 14:21
We don't yet support the WebEx chrome extension; cc @bridiver for thoughts on whether we should eventually

**Comment by Haze-Aulaian** [comment] 2016-05-11 14:44
But i mean if you want to reach out to more wider user space this is going to be essential :/

**Comment by bridiver** [comment] 2016-05-11 17:53
We don't have general support for extensions right now and no extensions are user installable. We are continuing to expand API support and the goal is to allow user installable extensions, but right now we are focusing on implementing APIs based on supporting particular extensions that are very popular with our users. The extension does appear to have a large number of users on Chrome, but this is the first request we've seen for it. We'll leave it open for now and keep it on our "watch list". Thanks!

**Comment by Haze-Aulaian** [comment] 2016-05-11 18:02
@bridiver im sorry but at work the browser is an essential tool for me , you are not dealing with 1 person , im trying to migrate the whole community of jordan , middle-east , etc to use this browser .
you are in era where add-ons and extensions are essential.
part of my work requires greasemonkey as we are installing alot of javascripts.
im able to report some bugs/enhancement that normal users wont be reporting it.
i think this browser should be targeted to businesses as well.
are you targeting certain user base ?
i mean if flash games are not supported, ads are being blocked for certain site/services , with all due respect , what is left ?

**Comment by bridiver** [comment] 2016-05-11 19:17
@Haze-Aulaian I completely understand your position and we want to expand support, but we also have very limited resources and a long list of things we need to do. I haven't looked at the WebEx extension to see what APIs it uses, but it's entirely possible that it works right now with our existing support. The problem is that we need to spend time testing every extension to make sure everything works correctly with our limited API support. We don't want to open up the ability to allow users to install extensions yet because we don't have full support and we haven't adequately tested the security controls that would prevent malicious extensions from gaining unauthorized access to resources. 

Flash support for some sites is in the works and ad blocking can be disabled if it is preventing access to to a particular site. We also have workarounds for several sites that are normally broken or restricted when ad blocking is enabled. What is left depends on how you use the web, but this is still a dev release and we don't claim to be feature complete. Brave is open-source and if someone wants to test the webex extension and either verify that it works or implement any missing API support we would be very happy to pull in the contribution. I wish I could do more for you, but right now all I can do is put it on the list of extensions that we are looking at. It will be supported eventually, but right now I can't give you a solid timeline.

**Comment by Haze-Aulaian** [comment] 2016-05-12 06:24
@bridiver thanks for the detailed feedback , i completely understand , what i meant by ad blocking is the fact that brave is advertising that its capable for ad blocking yet alot of ads are escaping.
im not pushing for anything and i do realize that this is an early release.
you guys are doing a terrific achievement so far :)
i will be crossing my fingers then until things gets implemented.

**Comment by 3CirclesChurchCommunity** [comment] 2016-05-21 15:52
I too use Webex for my meetings.  Would suggest there are many more of us and it would be worth making it possible via an extension.

**Comment by cezaraugusto** [comment] 2016-06-20 23:36
Closing for now since it's an issue regarding an yet unsupported extension.

**Closed by cezaraugusto** 2016-06-20 23:36 UTC

**Comment by vernonk** [comment] 2018-10-29 18:51
For anyone coming here like I did in my process of trying to get WebEx working in Brave, this comment I posted from here, https://github.com/brave/browser-laptop/issues/12877#issuecomment-434034356, might help:

> For what it's worth, I'm using latest Brave on Chromium and still am unable to join a WebEx meeting within Brave using the standard approach. Depending on WebEx version (which luckily I have this option) there is a "Launch in Browser" link on the join/start page. This approach _does_ work for attending and running WebEx meetings in-browser.
