### ISSUE TITLE
With auto-include disabled, sites still being added

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7850] opened 2017-03-23 00:33 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
User reports that even after having disabled _Auto Include_, sites are still being added to their list of sites to be funded by the Brave Wallet.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.13.5

- Steps to reproduce:
    1. Disable auto-include
    2. Meet inclusion criteria for new domain
    3. Note that domain is automatically included
    
- Actual result:
Even after having disabled _Auto Include_, sites are still being added to list of sites to be funded by the Brave Wallet.

- Expected result:
With auto-include disabled, no sites should be automatically included.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
N/A

- Is this an issue in the currently released version?
Reportedly.

- Can this issue be consistently reproduced?
Reportedly.

**Comment by bsclifton** [comment] 2017-03-23 06:03
Happy to report that this is a dupe of https://github.com/brave/browser-laptop/issues/7451 and was fixed by @NejcZdovc in 0.14.0 😄

**Closed by bsclifton** 2017-03-23 06:03 UTC
Labels: bug, feature/ledger
