### ISSUE TITLE
Show DPI value on about:brave

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10841] opened 2017-09-07 13:09 UTC
**Describe the issue you encountered:** Show DPI value on about:brave.

There are several issues which seem to be related with the system DPI setting: https://github.com/brave/browser-laptop/labels/bug%2Fdpi
There could be more, as the issues caused by the setting are not always tagged with that label.

It would help us to troubleshoot and narrow down the issue by displaying the setting.

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by bsclifton** [comment] 2017-09-26 07:54
Closing as a dupe of https://github.com/brave/browser-laptop/issues/6856

(since it had a misleading title, I renamed it to use your title instead 😄 👍 )

**Closed by bsclifton** 2017-09-26 07:54 UTC
Labels: bug/dpi, feature/about-pages, suggestion
