### ISSUE TITLE
Brave dies instantly

### ISSUE THREAD

**Issue by swasical** [brave/browser-laptop#6181] opened 2016-12-13 16:47 UTC
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
When I run Brave.exe off of a fresh install, it dies instantly. It runs correctly once (right after the install), but every subsequent time I click on Brave.exe, it spins for a minute and then dies.

**Expected behavior:**
It should load up.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win7

- Brave Version:
Latest - I think it's app-0.12.14

- Steps to reproduce:
    1. Uninstall Brave.
    2. Reinstall Brave.
    3. Close the Brave browser. 
    4. Double-click on the Brave icon (or run Brave.exe from Explorer).

- Screenshot if needed:

- Any related issues:

**Comment by hockey97** [comment] 2016-12-13 16:58
This is the same thing I have.  It's not dying but the window crashes. Something in the launcher is causing the browser to crash.

**Comment by bsclifton** [comment] 2016-12-14 01:40
Duplicate of this issue: https://github.com/brave/browser-laptop/issues/6105

@hockey97 I know you were resolved by the work-around. @swasical, can you please try the work around listed at the bottom of #6105?

**Closed by bsclifton** 2016-12-14 01:40 UTC

**Comment by swasical** [comment] 2016-12-14 17:44
That workaround does work. Thanks for the follow up!

**Comment by swasical** [comment] 2016-12-16 23:42
C:\Users\brian\AppData\Local\brave\Update.exe --processStart "Brave.exe"
