### ISSUE TITLE
UX/UI suggestion: Mouse location takes precedence over 'Enter' key opening a site

### ISSUE THREAD

**Issue by arunsathiya** [brave/browser-laptop#13209] opened 2018-02-20 17:54 UTC
**Steps to reproduce**: Follow the steps below to reproduce the issue. 

1. Hover your mouse just below the address bar
2. Feature cursor location to the address bar
3. Enter a site address and click the 'Enter' key

**What's expected**: The site address typed on the address bar is to be loaded

**What happens**: The site suggestion over which the mouse hovers loads instead

![ezgif com-gif-maker](https://user-images.githubusercontent.com/18581859/36440228-37e5a9b2-1695-11e8-96ab-78e9280ae11e.gif)

#painpoints

**Comment by btlechowski** [comment] 2018-02-24 13:14
Indeed this is annoying.

UX is consistent between browsers (checked Chrome and Firefox) and we should follow their model:
autocomplete best answer from suggestion list
allow user to choose other item from the list with mouse

**Comment by bsclifton** [comment] 2018-02-28 07:05
@arunsathiya thanks for the report 😄  I'm going to close this as a duplicate of https://github.com/brave/browser-laptop/issues/12530

**Closed by bsclifton** 2018-02-28 07:05 UTC
Labels: feature/URLbar

**Comment by arunsathiya** [comment] 2018-02-28 07:07
@bsclifton Thank you for confirming this! I missed seeing the other issue.
