### ISSUE TITLE
Autofill Credit Card section could benefit from validation (length, content, etc)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3370] opened 2016-08-24 08:34 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Credit Card field should not take more than standard 19 characters. No check done for only numeric values. 

**Expected behavior:**
Should only accept numbers and max length should be 19.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.6 Beta 3
- Steps to reproduce:
  1. Open auttofill and add an entry under credit card
  2. Accepts more than 19 char in card field. Also able to enter char and save it. (Should not allow)
- Screenshot if needed:
  ![creditcard](https://cloud.githubusercontent.com/assets/17010094/17923852/fe5310be-69dd-11e6-8a71-ae4926cb5caf.gif)
- Any related issues:

**Comment by srirambv** [comment] 2016-08-24 08:35
cc: @darkdh

**Comment by darkdh** [comment] 2016-08-24 12:01
Could you separate the editing issue and update it to https://github.com/brave/browser-laptop/issues/3368? It's the same root cause and it might be better to leave field length issue here. Thanks.

**Comment by srirambv** [comment] 2016-08-24 13:55
Done

**Comment by alexwykoff** [comment] 2016-08-24 15:25
Perhaps we could concern ourselves with validating the number and tie the activation of the save control to a positive result? 
https://gist.github.com/DiegoSalazar/4075533

**Comment by bsclifton** [comment] 2016-08-24 15:35
Just a heads up on validation- we'll want to consider the card type before giving a hard "no" to the user (we could maybe instead give a warning):
https://stackoverflow.com/questions/7863058/does-the-luhn-algorithm-work-for-all-mainstream-credit-cards-discover-visa-m

**Comment by bsclifton** [comment] 2016-08-24 15:54
The validation would be a nice touch- I created a separate issue for it so we can discuss more :smile: 
https://github.com/brave/browser-laptop/issues/3377

**Comment by darkdh** [comment] 2016-08-25 12:01
I should mention that Chrome do not check the validation of the field.
<img width="378" alt="screen shot 2016-08-25 at 19 59 17" src="https://cloud.githubusercontent.com/assets/11330831/17968277/7f2b0de2-6afe-11e6-8b7a-e75e1f455fe8.png">
I think it's better to save whatever user input for this milestone

**Comment by bsclifton** [comment] 2016-08-25 15:17
@darkdh has tested and verified that Chrome does not validate length

@alexwykoff what would you think about closing this issue in favor of a wider scope validation story (https://github.com/brave/browser-laptop/issues/3377)?  Since we're matching Chrome, I believe the behavior is OK and that validation might be an enhancement :smile:

**Comment by bridiver** [comment] 2016-08-25 15:21
maybe move this into a general data validation ticket for another release? Chrome doesn't do any validation and I can enter letters into the CC field if I want

**Comment by bsclifton** [comment] 2016-08-25 15:33
Updated title- this would be a great one to hear input from @bradleyrichter 

This is a potential opportunity to give us an advantage over other browsers by performing validation and catching user errors with the information provided

Besides length check, we can also consider the approach @alexwykoff has mentioned of not allowing to save input (or giving a warning maybe) if the input doesn't pass a validation test.  If we did that some questions:
- What should the warning message(s) look like?
- Should the validation be toggle-able, for getting around edge cases or if it's bothersome for the user?

**Comment by bridiver** [comment] 2016-08-25 15:34
I think it's a good idea, just wanted to move out of 0.11.6

**Comment by bsclifton** [comment] 2016-08-25 15:36
Totally agree- Since milestone was removed, I closed #3377 and will put the details in the post above :smile:

**Comment by bradleyrichter** [comment] 2016-08-25 16:45
Checkbox idea is good here since we don't yet know of reasons why validation may be problematic.   [x] "validate card number as I type" 

Regarding improvements over the competition, (thanks @bsclifton ) how about showing the user which sites contain the expiring credit card number ahead of time so they can update them all with a low pain threshold before auto-payments fail? (assuming this is not a privacy concern.)

**Comment by srirambv** [comment] 2016-09-06 22:05
Would it be possible to show logo/name of the card provider next to the card number. When you have multiple card details stored the dropdown looks very empty with just the ` ...card number`


![image](https://cloud.githubusercontent.com/assets/17010094/18292546/c1e73abc-7485-11e6-9d92-58fb5e463570.png)

**Comment by bsclifton** [comment] 2016-09-06 22:13
@srirambv great suggestion! I'm not sure if there are legal requirements around the logo and how it's displayed, but showing a logo is possible for sure

cc: @bradleyrichter

**Comment by bradleyrichter** [comment] 2016-09-06 22:50
SGTM - here are the fontawesome icons:

![image](https://cloud.githubusercontent.com/assets/13509546/18293707/77efab56-7449-11e6-9d7d-15d64f917f82.png)

![image](https://cloud.githubusercontent.com/assets/13509546/18293718/80e7cf54-7449-11e6-9f90-5e0391e6d207.png)

![image](https://cloud.githubusercontent.com/assets/13509546/18293729/8bde421c-7449-11e6-8d43-f5ffe74c2bac.png)

![image](https://cloud.githubusercontent.com/assets/13509546/18293735/961aeea6-7449-11e6-9ec0-8c8cc274ec1b.png)

**Comment by bridiver** [comment] 2016-09-07 01:23
Actually I'm pretty sure those are already available from the auto fill client and we just need to use them

**Comment by MargarytaChepiga** [comment] 2018-03-04 19:40
I would love to tackle this! 
As I understand we still want to do a validation for the credit card ( at least min and max characters? ). But what about the Credit card name and expiry dates?

**Comment by bsclifton** [comment] 2018-03-10 18:17
@MargarytaChepiga one approach could be to disable the save button until the number provided is valid.  You could then run validation on keydown / keyup for the text field (and also with expiration)

**Comment by MargarytaChepiga** [comment] 2018-03-21 05:36
Thank you so much @bsclifton for clarifying things for me! :smiley:
So far I have completed a simple length and numeric validation for credit card number:
![fix 1](https://user-images.githubusercontent.com/15698572/37694813-6d900488-2ca0-11e8-8f9b-a9777ba1ad42.gif)
Where length should be between 13 and 19 characters (according to this [credit card validator](https://www.freeformatter.com/credit-card-number-generator-validator.html)).
I can also detect a credit card type, for example:
![fix 2](https://user-images.githubusercontent.com/15698572/37695483-ef0cb830-2ca5-11e8-91d7-f70310f00c76.gif)
Where the UI change is only for the debugging purposes :sweat_smile:
However, I haven't got to the icon part yet. 

I also looked up for some React components, some of them are really cool and it looks like we could consider using them. Please take a look at these ones, and let me know what you think:

- [Credit Card Validation](https://www.npmjs.com/package/credit-card-validation)

- [Credit Card Validator](https://www.npmjs.com/package/credit-card-validator)

-  [This one](https://www.npmjs.com/package/react-credit-card) looks really great, but as I understand it provides more of UI rather than validation ( had an icon though :sweat_smile: )

**Comment by bsclifton** [comment] 2018-06-18 06:19
I feel safe saying that we won't be able to address this with browser-laptop. Closing as `wontfix` in favor of attempted a fix in Brave Core:
https://github.com/brave/brave-browser/issues/369

**Closed by bsclifton** 2018-06-18 06:19 UTC
Labels: feature/autofill, polish, suggestion
