### ISSUE TITLE
Blue lines around the border of video in fullscreen

### ISSUE THREAD

**Issue by Falken19** [brave/browser-laptop#5119] opened 2016-10-25 14:37 UTC
**Did you search for similar issues before submitting this one?**

Yes.

**Describe the issue you encountered:**

Whenever I put a video in fullscreen there's a blue border around the entire screen ever since the last update.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

Windows 10

- Brave Version:

0.12.6

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

http://imgur.com/I6QJUsp

- Any related issues:

**Comment by ETapia1** [comment] 2016-10-26 14:51
have you figured anything out? I'm having the exact same issue.

**Comment by luixxiul** [comment] 2016-10-27 04:18
@bsclifton would you mind taking this?

**Comment by luixxiul** [comment] 2016-10-27 04:20
this could be caused by #4856 fyi

**Comment by bsclifton** [comment] 2016-10-27 04:47
Already fixed (PR submitted :smile:). That PR did not cause the issue, but made it noticeable

**Comment by luixxiul** [comment] 2016-10-27 05:20
@bsclifton Thanks! Was it fixed with #5170?

**Comment by bsclifton** [comment] 2016-10-27 06:26
@luixxiul yes it was :smile:

**Comment by bsclifton** [comment] 2016-10-27 06:27
Closing this issue as it is a duplicate of https://github.com/brave/browser-laptop/issues/5152. This issue was just fixed in master :smile:

**Closed by bsclifton** 2016-10-27 06:27 UTC
Labels: OS/Windows
