### ISSUE TITLE
Still failing on foxnews.com live stream.

### ISSUE THREAD

**Issue by zeg-io** [brave/browser-laptop#2159] opened 2016-06-11 00:38 UTC
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
When you go to the live video, it prompts you for your provider, I select mine, DirectTV.
I log in, accept that form data will be sent non-secured, and it returns me to the video site, as expected...
HOWEVER, it just shows me the provider list again rather than taking me to live video like safari and chrome do.

**Expected behavior:**
Safari and Chrome return to the main page and refresh it somehow to show the live stream.
- Platform (Win7, 8, 10? OS X? Linux distro?):
  OSX
- Brave Version:
  10.3 
- Steps to reproduce:
  1. See above.
     2.
     3.
- Screenshot if needed:
- Any related issues:

**Comment by zeg-io** [comment] 2017-01-31 21:36
Any status on this?  Been a few months.

**Comment by bbondy** [comment] 2017-02-01 04:17
cc @lukemulks

**Comment by lukemulks** [comment] 2017-02-01 04:20
Thanks @bbondy - will investigate!

**Comment by lukemulks** [comment] 2017-02-01 08:56
@zeg-io & @bbondy I've been able to reproduce in Windows 10, and have a workaround that is worth trying. 

The root cause of this issue is that there's a protocol mixing error between the foxnews livestream page URL, the cable provider sign-in page, and the livestream content and player configuration.

By default, with Shields up, Brave will attempt to upgrade the page URL to secure (`https://`) protocol if it is available. 

Since FoxNews doesn't have https:// enabled by default consistently across their content and resources,  but does have `https://` enabled by default for their page URL and authentication. The additional tracking/ad protections are also causing an issue when attempting to sign in and navigate back to foxnews to view the clip. 

These inconsistencies cause mixed content and protocol mismatching errors, which are blocking the playback process from behaving as expected.

See below: 
![brave-foxnews-issue-02012017](https://cloud.githubusercontent.com/assets/8979240/22500191/c35f8b32-e817-11e6-9a89-7ff4e6a2541a.PNG)

**I was able to get around this issue, and successfully view the livestream by doing the following:** 

1. Click on the **Brave Shield Panel** (the brave lion icon menu in the upper right corner of the window), and adjust the switch to take **Brave Shields down**. 

2. In the browser URL field, change `https://video.foxnews.com/v/1241186546001/?#sp=watch-live` to `http://video.foxnews.com/v/1241186546001/?#sp=watch-live` and hit enter to reload the page. 

3. Click play, and sign into your provider. 

4. Once you complete the sign-in, you should be successfully redirected back to the insecure version of the foxnews page, and should be able to view the livestream as expected.

@zeg-io can you follow the steps above, and attempt to reproduce? 

It's unfortunate that shields have to be taken down for this workaround, but until Fox is able to update all their endpoints in the livestream video configuration to use https:// by default, the mixed protocol/content errors that occur between the page load, login page and video content cause the playback failure (until shields are down, and you are able to force the insecure version of the fox page to load).

**Comment by lukemulks** [comment] 2017-02-02 07:56
@zeg-io given that I've been able to apply the workaround above to resolve the issue, I'm going to close the issue. 

That said, if you attempt the workaround above and are still unable to view the stream, let me know and I can re-open the issue. Thanks!

**Closed by lukemulks** 2017-02-02 07:56 UTC
Labels: webcompat
