### ISSUE TITLE
Switching Linux workspaces issue while in Brave

### ISSUE THREAD

**Issue by carlito-brigante** [brave/browser-laptop#10535] opened 2017-08-16 10:59 UTC
- Did you search for similar issues before submitting this one? Yes. Doesn't mean it isn't there but rather I could not find it. :-)

- Describe the issue you encountered: I am a Linux user and prefer to use  "CTRL ALT left/right arrow" for switching workspaces. This seems to be a feature of Brave to switch tabs. I'd like to know if the keyboard shortcuts can be modified so as to modify or disable this behavior.

- Version Info
Brave | 0.18.16
rev | 8003c66
Muon | 4.3.6
libchromiumcontent | 60.0.3112.78
V8 | 6.0.286.44
Node.js | 7.9.0
Update Channel | dev
OS Platform | Linux, Ubuntu MATE 17.04
OS Release | 4.10.0-32-generic
OS Architecture | x64

- Steps to reproduce:
    1. Run Linux
    2. Click into an open Brave tab
    3. Press _CTRL ALT Arrow _key__ 
    4. Some times the workspace will change but more times than not it is the Brave tab that cycles.
    
- Actual result: Brave tab switches tab

- Expected result:Per Brave documentation on the Wiki this is behaving properly. However this is a pretty big detriment for Linux workspaces.

- Will the steps above reproduce in a fresh profile? If not what other info can be added? Yes, this is not specific to a profile.

- Is this an issue in the currently released version? Yes.

- Can this issue be consistently reproduced? Yes, the only item of note is that focus needs to be inside of a tab.

**Comment by voobscout** [comment] 2017-09-04 11:04
super annoying indeed! ctrl-shift-[hjkl] is the only way to go, unless customization is provided. Having ctrl-alt-[arrows] occupied makes no sense! Have the authors ever used linux?

**Comment by MarkOSullivan94** [comment] 2017-10-02 09:04
This is my biggest pain with Brave for Linux. It would be awesome to allow us flexibility to customise it or just remove it, ctrl+<num> or ctrl+tab is enough for me to switch tabs.

**Comment by bsclifton** [comment] 2017-12-13 06:05
I believe this is a duplicate of https://github.com/brave/browser-laptop/issues/1374 and/or https://github.com/brave/browser-laptop/issues/2026

**Closed by bsclifton** 2017-12-13 06:05 UTC
Labels: bug, feature/keyboard-shortcuts, OS/unix-like/linux
