### ISSUE TITLE
Consider Adblock element picker to choose content to block

### ISSUE THREAD

**Issue by chris1000** [brave/browser-laptop#14340] opened 2018-06-06 14:38 UTC
Like with Adblockers such as uBlock Origin and many other popular ones, I propose a feature to allow users to select elements on a page they'd like to block. Personally, I think this would make brave perfect, because other than that it has all the features I need.

Thank you!

**Comment by srirambv** [comment] 2018-06-06 16:48
This is a dupe of https://github.com/brave/browser-laptop/issues/7521

**Closed by srirambv** 2018-06-06 16:48 UTC
