### ISSUE TITLE
Repeatedly asking for cerifate Error

### ISSUE THREAD

**Issue by abilng** [brave/browser-laptop#1333] opened 2016-04-11 10:22 UTC
When I gave exception for a ERR_CERT_AUTHORITY_INVALID, for a domain, brave does give exception other pages in same domain,

For example if I gave exception for https://google.com, barve is giving "ERR_CERT_AUTHORITY_INVALID"  even for loading https://google.com/css.css

**Comment by diracdeltas** [comment] 2016-04-12 18:39
duplicate of #1074

**Closed** 2016-04-13 22:42 UTC
Labels: duplicate
