### ISSUE TITLE
partially missing app icon

### ISSUE THREAD

**Issue by edmundlaugasson** [brave/browser-laptop#14442] opened 2018-06-19 00:46 UTC
### Description
When to run Brave then in taskbar or switching between apps using ALT+TAB there is icon missing. In main menu, desktop and quick launchbar there is that icon. The running command is:
`sh -c "brave --user-data-dir-name=brave -- %U"`
Actually while opened properties of Brave choice in main menu and when to click the icon button then the file `/usr/share/pixmaps/brave.png` exist and also default permissions, ownership are fine:
`$ stat -c '%A %a %U %G %n' /usr/share/pixmaps/brave.png`
`-rw-rw-r-- 664 root root /usr/share/pixmaps/brave.png`
... but it does not show in taskbar or while switching apps.

### Steps to Reproduce

  1. install Brave in Linux (using 64-bit Linux Mint 18.3 MATE)
  2. open it
  3. try to switch between apps

**Actual result:**
 in taskbar or switching between apps using ALT+TAB the is icon missing

**Expected result:**
 in taskbar or switching between apps using ALT+TAB the is icon is present

**Reproduces how often:**
all the time

### Brave Version
Name | Version
Brave | 0.22.810
V8 | 6.7.288.43
rev | 8f30eeb
Muon | 7.0.6
OS Release | 4.15.18-041518-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.71

**Reproducible on current live release:**
yes

**Comment by hugobuddel** [comment] 2018-06-29 13:47
Same issue as #13031?

Still the case in 0.23.19
 
Brave: 0.23.19 
V8: 6.7.288.46 
rev: 178c3fbc045a0cbdbe098db08307503cce952081 
Muon: 7.1.3 
OS Release: 3.10.0-862.3.2.el7.x86_64 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Tor: 0.3.3.7 (git-035a35178c92da94) 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.87

**Comment by bsclifton** [comment] 2018-06-29 16:52
Closing as a dupe of https://github.com/brave/browser-laptop/issues/13031 - thanks for the report, @edmundlaugasson

**Closed by bsclifton** 2018-06-29 16:52 UTC
