### ISSUE TITLE
{{ downloadPercent }} on tooltip of download item bug

### ISSUE THREAD

**Issue by joelwass** [brave/browser-laptop#14596] opened 2018-06-28 18:46 UTC
### Steps to Reproduce

  1. Download a large file
  2. Pause the download
  3. Hover over the download item in the download bar at foot of browser, it will display {{ downloadPercent }} instead of the actual download percent

**Actual result:**

{{ downloadPercent }}

**Expected result:**
Paused: 9%

**Reproduces how often:**

100% of the time

### Brave Version

**about:brave info:**

Brave | 0.22.810
-- | --
V8 | 6.7.288.43
rev | 8f30eeb
Muon | 7.0.6
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.71

**Reproducible on current live release:**

Yes

**Comment by btlechowski** [comment] 2018-06-28 19:19
Dupe of #13920.

**Closed** 2018-06-28 19:22 UTC
Labels: bug/good-first-bug, feature/download
