### ISSUE TITLE
Brave process not terminated after bookmarking a page and closing through titlebar

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#13277] opened 2018-02-23 13:35 UTC
### Steps to Reproduce

  1. Clean Install
  2. Open Brave
  3. Bookmark page through the star
  4. Close Brave through titlebar's close button (x)

**Actual result:**
BraveBeta processes are running

**Expected result:**
BraveBeta processes are NOT running

**Reproduces how often:**
100%

### Brave Version
```
Brave: 0.21.12 
V8: 6.4.388.41 
rev: 246f9008be47dbdcc6dc9ded5690a847eee8a4e0 
Muon: 5.0.5 
OS Release: 6.1.7601 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
```

**Comment by kjozwiak** [comment] 2018-02-23 17:28
I also managed to reproduce this on the following platforms:

* Win 10 x64 VM - Reproduced
* Ubuntu 17.10 x64 VM - Reproduced

Great catch @btlechowski 👍

**Comment by kjozwiak** [comment] 2018-02-23 17:55
Looks like this is also present in `0.20.42 ` 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed. I managed to reproduce it under Win 10 and Ubuntu 17.10.

Not a new regression, but I think we should probably get this fixed in this milestone as #13233 was also fixed. @petemill @bsclifton thoughts?

**Comment by petemill** [comment] 2018-02-23 18:00
I"ll give it 1 try

**Comment by bsclifton** [comment] 2018-02-23 20:46
Per @petemill: this is related to browser window being created for measurements (related to calculating the bookmark toolbar width?)

**Comment by petemill** [comment] 2018-02-24 07:42
Removing release/blocking since it's already an issue in 0.20

**Comment by kjozwiak** [comment] 2018-03-20 15:19
Just a reminder, when this gets fixed, please take a look at #13422 which is most likely the same issue.

**Comment by jonathansampson** [comment] 2018-03-30 18:26
I believe I just ran into this same issue today:

1. Started with a fresh brave profile
2. Started brave and navigated to brave.com
3. Bookmark brave.com, leaving it in the bookmarks toolbar
4. Close brave via the top-right [x]

Observe in Task Manager that several Brave processes are still running.

**Closed** 2018-04-10 18:28 UTC
Labels: 0.20.x, bug, priority/P3, release-notes/exclude

**Comment by kjozwiak** [comment] 2018-04-11 04:53
@petemill should this particular issue be moved into the `0.22.x Release 3` as well? Looks like #13758 fix is in that milestone as well.

**Comment by btlechowski** [comment] 2018-04-11 12:38
Verified Win7 x64 v0.22.108

**Comment by kjozwiak** [comment] 2018-05-15 05:37
Verified on `Mint 18.3 x64` using the following build:
 
* 0.22.711 `31d6bccb220485dc44f0ce0c65ed797f0160c8a7`
* Muon: 6.0.9 
* libchromiumcontent: 66.0.3359.139
