### ISSUE TITLE
Align buttons on the notification bar w/o float:right

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6749] opened 2017-01-19 22:07 UTC
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Language restart buttons are way big for Japanese

**Expected behavior:**
The button size should be same for all languages

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	c60b783

- Steps to reproduce:
    1. Do  a clean install of 0.13.0 preview 10
    2. Change browser language from English to Japanese
    3.  Notice the size of the buttons on the notification bar
![image](https://cloud.githubusercontent.com/assets/17010094/22127239/0c8bc19c-de93-11e6-9aa0-2d11bd5fd44d.png)
   4. Restart the browser to make the language change
   5. Change language from Japanese to any other language to trigger the notification bar
   6. The size of the buttons is big
![image](https://cloud.githubusercontent.com/assets/17010094/22127323/6278cc80-de93-11e6-9ba8-487e0a9c0f7a.png)

- Extra QA steps:
    1. Do  a clean install of 0.13.0 preview 10
    2. Change browser language from English to Japanese
    3.  Notice the size of the buttons on the notification bar
    4. Restart the browser to make the language change
    5. Change language from Japanese to any other language to trigger the notification bar
    6. Ensure the button size is same as in step 3

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment] 2017-01-20 03:16
This may be due to the font which is installed on your PC. You would need to install several Japanese fonts. On my environment I haven't noticed the issue.

I will try later on my VM in Japanese and will let you know this should be `wontfix`.

**Comment by luixxiul** [comment] 2017-01-20 03:29
Also is it a regression from 0.12 series?

**Comment by luixxiul** [comment] 2017-01-20 15:18
This is essentially the same issue with https://github.com/brave/browser-laptop/issues/5799#issue-191128832

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/22154395/ada28a44-df6e-11e6-8760-5a7e1973b818.png)

The issue here is not the font size, but the one which is common among the buttons aligned with `float: right`.

With some additional modifications the buttons can be aligned at the center, setting margin-top and margin-bottom on the buttons like this:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/22154495/2242677a-df6f-11e6-83d8-61284f14eb4b.png)

**Comment by luixxiul** [comment] 2017-01-20 15:20
I'll work on it later

**Closed** 2017-03-23 23:11 UTC
Labels: misc/button, polish, QA/steps-specified
