### ISSUE TITLE
after update today 2/8/2017 favicons missing

### ISSUE THREAD

**Issue by eskimatticas** [brave/browser-laptop#7133] opened 2017-02-08 15:45 UTC
- Did you search for similar issues before submitting this one?
yes, all other issues seemed to be related to importing

- Describe the issue you encountered:
updated to latest build and favicons/text bookmarks bar is blank

- Platform (Win7, 8, 10? macOS? Linux distro?):
win7

- Brave Version (revision SHA):

- Steps to reproduce:
    1.  update to latest build
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?  uninstalled and reinstalled and experienced same issue

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment] 2017-02-08 22:39
Are you sure you are connected to the Internet when you open Brave? The favicons are retrieved when a new window is opened, and I've noticed that they don't load when my computer is still connecting to the Internet.

**Comment by eskimatticas** [comment] 2017-02-09 13:32
yeah guaranteed connected to the internet....really strange, if I check bookmarks it shows none there either, when I'm clearly adding them repeatedly.

**Comment by bsclifton** [comment] 2018-05-01 06:52
I'm going to close this issue as I've been unable to reproduce and there haven't been any more reports since this was opened

For folks reading this, please re-open if you experience the issue 😄 Thanks!

**Closed by bsclifton** 2018-05-01 06:52 UTC
Labels: misc/favicon
