### ISSUE TITLE
Two finger swipe for backwards/forwards does not work in C69

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#15114] opened 2018-08-29 13:09 UTC
### Description
On macOS you can use a gesture to go backwards and forwards in your page history. This is a two finger swipe which you do to either left or right. If the input is not registering, you can go into Advanced > Swipe Options to adjust the sensitivity

With the Chromium 69 upgrade, this functionality is not working

### Steps to Reproduce

  1. Be on a laptop with a trackpad
  2. Open a tab and generate tab history by visiting sites or navigating around one site
  3. Go back in the tab history a few pages so you can go forward or backward
  4. Do two finger swipe from left to right (this should be going back) or right to left (this should be going forward)

**Actual result:**
Back/Forward arrows get larger to indicate you're trying to navigate, but the page does not change:

https://drive.google.com/file/d/1cSfVBdR62Ho7LjbJCr98bAdqXfMQ0kJR/view?usp=sharing

**Expected result:**
Should be able to navigate back and forth as we can on 0.23.104
![swiping-023104](https://user-images.githubusercontent.com/28145373/44789597-f92a9280-ab6a-11e8-8963-b219b01f4f57.gif)

**Reproduces how often:**
easily

### Brave Version
 
Brave: 0.23.201 
V8: 6.9.427.17 
rev: 17d2d17a64b6ea5e85ff8fbe324798447887e81b 
Muon: 8.1.0 
OS Release: 16.7.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.57

**Reproducible on current live release:**
no

### Additional Information
cc @kjozwiak to give it a try
Same thing happened on c65 update: https://github.com/brave/browser-laptop/issues/13433

**Comment by kjozwiak** [comment] 2018-08-29 16:06
Reproduced on my machine as well. The arrow animations seem to be working but the pages never actually switch when swiping. Double checked `0.23.104` and confirmed that it's working there. Looks like a C69 regression.

**Comment by darkdh** [comment] 2018-08-30 00:35
fixed by https://github.com/brave/browser-laptop/commit/69851d114a327b3bfefab0ab7ba9649b7b5a4b1a

**Closed by darkdh** 2018-08-30 00:35 UTC
Labels: OS/macOS, cr69, regression

**Comment by LaurenWags** [comment] 2018-09-04 14:16
Verified with macOS 10.12.6 using
* 0.23.203 16c2c19
* Muon 8.1.2
* libchromiumcontent 69.0.3497.72
