### ISSUE TITLE
Extension icons are not displayed in v0.19.95

### ISSUE THREAD

**Issue by FirefoxWas** [brave/browser-laptop#12036] opened 2017-11-19 18:09 UTC
### Description

[Description of the issue]

When I follow the steps at https://medium.com/@jonathansampson/testing-chrome-extensions-in-brave-8e25d1f7386d and did a restart brave browser, the to extensions dose not show up the icons in the toolbar on top of the page.

### Steps to Reproduce

  1. I added Noscrip light and Betterttv extension icons and the two extensions dose not show up on the toolbar at the top of page

**Actual result:**

![1heukxv](https://user-images.githubusercontent.com/32176749/32993709-d4b6797a-cd10-11e7-96d3-6c39dd6f4579.png)

![ch5ddwq](https://user-images.githubusercontent.com/32176749/32993712-db4550ea-cd10-11e7-9710-27f0703834f2.png)

**Reproduces how often:**

What percentage of the time does it reproduce?

Everytime I install Noscrip light and Betterttv extensions.

### Brave Version

**about:brave info:**

Brave	0.19.95
rev	cc0ebad
Muon	4.5.16
libchromiumcontent	62.0.3202.94
V8	6.2.414.42
Node.js	7.9.0
Update Channel	Release
OS Platform	Microsoft Windows
OS Release	10.0.16299
OS Architecture	x64

**Reproducible on current live release:**

Yes

### Additional Information

I tryed the other extensions to add Noscrip light and Betterttv extensions and it dose not work on other extensions. Only on 3 extensions under extensions.

**Comment by luixxiul** [comment] 2017-11-19 18:16
would you let us know what the output on the devtool console is like?

**Comment by FirefoxWas** [comment] 2017-11-19 19:44
Hi luixxiul,

I copy the elements under the preferences where the extensions are at. If not can you send me the steps on what you need on the  devtool console.

![screen shot](https://user-images.githubusercontent.com/32176749/32994574-3f970428-cd1e-11e7-9b25-069514c6580e.jpg)

![screen shot](https://user-images.githubusercontent.com/32176749/32994579-4687f756-cd1e-11e7-918d-fd119b3ffd9d.png)

Thanks

**Comment by bsclifton** [comment] 2017-11-20 18:28
I wonder if this would be solved with https://github.com/brave/browser-laptop/pull/11143

**Comment by bsclifton** [comment] 2018-01-08 06:44
This should be fixed in 0.20.x with https://github.com/brave/browser-laptop/pull/11143

**Closed by bsclifton** 2018-01-08 06:44 UTC
Labels: 0.19.x, feature/extensions, needs-info

**Comment by bsclifton** [comment] 2018-01-23 21:14
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/11142
