### ISSUE TITLE
All Pages White, Maybe Crash?

### ISSUE THREAD

**Issue by Pontianak** [brave/browser-laptop#4113] opened 2016-09-19 16:53 UTC
So it looks like Brave has started not rendering/loading webpages, or certain menus such as the settings menu. The page will just be a solid white, and the tabs title will eventually change to about:error, but not right away. Ctrl-A and Ctrl-Alt-J do nothing. Reinstall did not resolve either. 

**Expected behavior:**
- Platform: Win 10 64bit
- Brave Version: 0.12.1
- Steps to reproduce:
  1. Open Brave
  2. Try to load any webpage, including the home page. 
  3. Bug happens. Never successfully loads any pages.
  4. Clicking the lastpass icon just brings up a blank white box in the lower right corner of the browser window. As I can't get into settings, I can't disable it. 
  5. The green number in the upper left corner. I think this is related to the Nvidia Geforce Experience FPS overlay in games. I disabled the FPS overlay but the number still appears and the number randomly changes live as you're doing things. It's never stopped me from browsing before so... I dunno. 

![capture5](https://cloud.githubusercontent.com/assets/16515849/18640804/5652560e-7e5f-11e6-9fa4-03ba30e7b0ad.PNG)

**Comment by MikeFoden** [comment] 2016-09-22 23:24
I'm also experiencing this issue. Only started occurring once the latest Windows Anniversary Update installed.

A re-install did not work.

**Comment by bsclifton** [comment] 2016-09-23 03:44
@Pontianak @MikeFoden would you all be able to provide more information about your system? For example, I'm interested in what kind of video card you have and what display driver you're using. You should be able to see the info in device manager or by using a utility like dxdiag

One thing that's worth a shot would be to start Brave via command line and see if anything is output.  Here's how you do that:

1. Start > Run, cmd.exe
2. cd "%userprofile\AppData\Local\brave\app-0.12.1"
3. Brave.exe

Once the tabs load and you're seeing the above, please go back to the command window and see if there are any logs.  Additionally, you can check the electron renderer's logs by pressing Shift + F8. This will pop up a dev toolkit on the right (toolkit is for Brave, not for the websites you are viewing). In there, go to the console tab and see if there are any logs

@MikeFoden Good to know that Brave worked at least before the anniversary update. I'm hoping more info can be uncovered so we can get you all up and running :smile:

**Comment by MikeFoden** [comment] 2016-09-23 03:55
@bsclifton My video card is a Nvida Geforce GTX 850M. As for the console output, all I received was 

> running without secp256k1 acceleration

I cannot get the Electron Renderer's logs to load either. Any page load will throw a blank about:error page.

**Comment by willy-b** [comment] 2016-09-24 03:01
I'm seeing this intermittently too on recent master (commit f51e1a3456bc9d468f388749ae9172e789d5c42b) , Ubuntu 14.04. 
Hardware: Lenovo Ideapad with integrated graphics (Haswell-ULT Integrated Graphics Controller, Lenovo Device 3978).

**Comment by luixxiul** [comment] 2016-09-24 03:13
@willy-b do you see the issue just recently? I was wondering if this was related with #1471.

**Comment by willy-b** [comment] 2016-09-24 03:32
I saw this earlier this week, and went back to an earlier commit which seemed to fix it. 

Minutes ago, though I got a clue that this is related to webpack.  `browser-laptop/extensions/brave/gen` was not getting re-generated by `npm run watch`. Running `npm postinstall` before `npm run watch` seemed to fix.

**Comment by ConorIA** [comment] 2016-09-28 13:54
I've been experiencing this too on Manjaro Linux. In my case, I suspect that it started after changing from the proprietary catalyst drivers to the open source ati driver. I also updated my X-org server to 1.18.x.

The interesting thing is that the page does load, it just fails to display the content. 
![screenshot from 2016-09-28 09-45-14](https://cloud.githubusercontent.com/assets/870746/18916188/934d37dc-8561-11e6-8c09-a8034cfcc5e6.png)

Even the links are 'clickable', but they will send you to another blank page. 
![screenshot from 2016-09-28 09-47-17](https://cloud.githubusercontent.com/assets/870746/18916195/98639b80-8561-11e6-8177-1ebd5e89e2f4.png)

Only message on the console is: 
```
no pubinfo avaialble   chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/content/scripts/pageInformation.js:139 
```

I have __not__ encountered this issue on my laptop, which used the Nvidia-340xx proprietary drivers (also Manjaro Linux)

**Comment by lo-co** [comment] 2016-09-30 17:08
I am seeing this too on Windows 10, NVIDIA Geforce 745M and Brave v0.12.1.  This issue usually pops up after the browser has been open a while but inactive (as in, computer may have gone to sleep).  I believe that I am also seeing this on Ubuntu 14.x LTS.

**Comment by bsclifton** [comment] 2016-09-30 23:11
@Pontianak @lo-co @MikeFoden @ConorIA 
We may have found the root cause for this- I can't guarantee it will work, but we plan to have a release out sometime soon.

If you're feeling extra **Brave**, you can try a pre-release version here and report back:
https://github.com/brave/browser-laptop/releases/tag/0.12.3dev-RC5

@willy-b if you redo your npm install on master, you should get the new electron which may or may not fix this.

**Comment by willy-b** [comment] 2016-10-01 04:23
@bsclifton, sweet thanks! 
I should have updated here, but whatever was causing this for me goes away if I manually do either a `npm install` (or, to save time, a `rm -rf app/extensions/brave/gen/* && npm run postinstall`)

**Comment by bsclifton** [comment] 2017-01-30 07:03
I've created a [brand new wiki entry](https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page) which I hope helps 😄  Folks, can you please try the following steps for me?

1. Install latest version of Brave (as of now, this is 0.13.0)
2. See if you have the issue; Chromium always includes bug fixes which may resolve the issue
3. If you still have the issue, please close Brave and edit your shortcut to add the command line argument `--ignore-gpu-blacklist`. Relaunch and see if this resolves the issue
4. If this does not resolve the issue, please edit the shortcut and instead try `--disable-gpu`

Thanks in advance to anyone who can try this- your time is very much appreciated and will help other users.

cc: @willy-b @lo-co @ConorIA @MikeFoden @Pontianak

**Comment by dsbw** [comment] 2017-03-08 05:00
I'm using 0.13.5, which I believe is the latest.

Tried the switches from the command-line to no effect. Tried by editing shortcut, just in case there was some difference. (There wasn't.) Got a bunch of errors on the command-line:

> [10920:14332:0307/205703.015:ERROR:CONSOLE(0)] "(WEBUI context) chrome://brave/C
:/Users/edward/AppData/Local/brave/app-0.13.5/resources/app.asar/app/extensions/
brave/gen/app.entry.js:67746: Uncaught TypeError: Cannot read property 'getIn' o
f undefined{TypeError: Cannot read property 'getIn' of undefined
    at NavigationBar.get publisherId [as publisherId] (chrome://brave/C:/Users/e
dward/AppData/Local/brave/app-0.13.5/resources/app.asar/app/extensions/brave/gen
/app.entry.js:67746:36)
    at NavigationBar.get visiblePublisher [as visiblePublisher] (chrome://brave/
C:/Users/edward/AppData/Local/brave/app-0.13.5/resources/app.asar/app/extensions
/brave/gen/app.entry.js:67754:53)
    at NavigationBar.get isPublisherButtonEnabled [as isPublisherButtonEnabled]
(chrome://brave/C:/Users/edward/AppData/Local/brave/app-0.13.5/resources/app.asa
r/app/extensions/brave/gen/app.entry.js:67761:63)
    at NavigationBar.render (chrome://brave/C:/Users/edward/AppData/Local/brave/
app-0.13.5/resources/app.asar/app/extensions/brave/gen/app.entry.js:67856:30)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrCon
text (chrome://brave/C:/Users/edward/AppData/Local/brave/app-0.13.5/resources/ap
p.asar/app/extensions/brave/gen/app.entry.js:45757:31)
    at ReactCompositeComponentWrapper._renderValidatedComponent (chrome://brave/
C:/Users/edward/AppData/Local/brave/app-0.13.5/resources/app.asar/app/extensions
/brave/gen/app.entry.js:45780:33)
    at ReactCompositeComponentWrapper.performInitialMount (chrome://brave/C:/Use
rs/edward/AppData/Local/brave/app-0.13.5/resources/app.asar/app/extensions/brave
/gen/app.entry.js:45320:31)
    at ReactCompositeComponentWrapper.mountComponent (chrome://brave/C:/Users/ed
ward/AppData/Local/brave/app-0.13.5/resources/app.asar/app/extensions/brave/gen/
app.entry.js:45216:22)
    at Object.mountComponent (chrome://brave/C:/Users/edward/AppData/Local/brave
/app-0.13.5/resources/app.asar/app/extensions/brave/gen/app.entry.js:14084:36)
    at ReactDOMComponent.mountChildren (chrome://brave/C:/Users/edward/AppData/L
ocal/brave/app-0.13.5/resources/app.asar/app/extensions/brave/gen/app.entry.js:4
8933:45)}", source: chrome://brave/C:/Users/edward/AppData/Local/brave/app-0.13.
5/resources/app.asar/app/extensions/brave/index.html (0)
[10920:14332:0307/205703.080:ERROR:CONSOLE(45703)] "Uncaught TypeError: Cannot r
ead property '_currentElement' of null", source: chrome://brave/C:/Users/edward/
AppData/Local/brave/app-0.13.5/resources/app.asar/app/extensions/brave/gen/app.e
ntry.js (45703)
[10920:14332:0307/205703.241:ERROR:CONSOLE(46384)] "Uncaught TypeError: Cannot r
ead property '_idCounter' of null", source: chrome://brave/C:/Users/edward/AppDa
ta/Local/brave/app-0.13.5/resources/app.asar/app/extensions/brave/gen/app.entry.
js (46384)
[10920:14332:0307/205703.263:ERROR:CONSOLE(46384)] "Uncaught TypeError: Cannot r
ead property '_idCounter' of null", source: chrome://brave/C:/Users/edward/AppDa
ta/Local/brave/app-0.13.5/resources/app.asar/app/extensions/brave/gen/app.entry.
js (46384)
[10920:14332:0307/205706.507:ERROR:CONSOLE(46384)] "Uncaught TypeError: Cannot r
ead property '_idCounter' of null", source: chrome://brave/C:/Users/edward/AppDa
ta/Local/brave/app-0.13.5/resources/app.asar/app/extensions/brave/gen/app.entry.
js (46384)
[10920:14332:0307/205706.606:ERROR:CONSOLE(46384)] "Uncaught TypeError: Cannot r
ead property '_idCounter' of null", source: chrome://brave/C:/Users/edward/AppDa
ta/Local/brave/app-0.13.5/resources/app.asar/app/extensions/brave/gen/app.entry.
js (46384)
[10920:14332:0307/205706.624:ERROR:CONSOLE(46384)] "Uncaught TypeError: Cannot r
ead property '_idCounter' of null", source: chrome://brave/C:/Users/edward/AppDa
ta/Local/brave/app-0.13.5/resources/app.asar/app/extensions/brave/gen/app.entry.
js (46384)
[10920:14332:0307/205708.726:ERROR:CONSOLE(46384)] "Uncaught TypeError: Cannot r
ead property '_idCounter' of null", source: chrome://brave/C:/Users/edward/AppDa
ta/Local/brave/app-0.13.5/resources/app.asar/app/extensions/brave/gen/app.entry.
js (46384)

**Comment by bsclifton** [comment] 2017-03-14 08:45
Moving to 0.13.7

**Comment by bsclifton** [comment] 2017-03-14 22:50
@dsbw the issue you're reporting should be intermittent (it's a race condition) and can be worked around by turning off Brave Payments for now.  We have a fix which will be in our next release (0.14.0)

**Comment by bsclifton** [comment] 2017-03-14 22:51
Since this issue is largely related to driver issues (and not the payment issue reported above), I'm going to remove the milestone.  As stated above, the wiki entry would be the best case for folks on Linux having the driver issue

**Comment by dsbw** [comment] 2017-03-16 01:31
Thanks, @bsclifton--how would I turn off Brave Payments when I have no screen? Is there a command-line switch somewhere?

**Comment by bsclifton** [comment] 2017-03-17 21:27
@dsbw I don't think there's an easy way- you might want to try out latest build (which is a preview build).  
https://github.com/brave/browser-laptop/releases/tag/v0.14.0dev-Preview3

Worst case scenario:
- download / install preview build
- launch Brave and disable payments
- reinstall latest stable version 0.13.5 😄

**Comment by bsclifton** [comment] 2018-07-25 07:46
Since we have a [documented workaround](https://community.brave.com/t/window-is-solid-black-or-solid-white-looks-like-a-blank-page/10003) and also because we're moving to [Brave Core](https://github.com/brave/brave-browser) and won't be addressing this before then, I believe it makes sense to close this issue

**Closed by bsclifton** 2018-07-25 07:46 UTC
Labels: bug/driver, needs-investigation
