### ISSUE TITLE
Can't easily select top bookmark in bookmark bar folders

### ISSUE THREAD

**Issue by andrewcole50** [brave/browser-laptop#12097] opened 2017-11-24 12:49 UTC
### Description
While using folders in bookmark bar, top bookmark within said folder is only accessible via a small sliver of pixels.

### Steps to Reproduce
  1. Create folder in bookmarks bar
  2. Add links to folder
  3. Attempt to select the top link in folder.

**Actual result:**
Can only select top link via top or bottom few pixels (seems to be pixels above or below tab bar)

**Expected result:**
Able to select link via entire box

**Reproduces how often:**
100% of the time

### Brave Version
0.19.95

**Reproducible on current live release:**
Yes

### Additional Information
Update Channel: Release
OS Platform: Microsoft Windows
OS Release: 10.0.16299
OS Architecture: x64

I'm having trouble capturing a screenshot that shows my mouse pointer. If needed I can take screenshots if someone suggests a way for me to capture my mouse.

**Comment by eljuno** [comment] 2017-12-03 18:34
Duplicate of #9088?

**Comment by andrewcole50** [comment] 2017-12-03 18:44
Yeah duplicate. Didn't see that one when I searched

**Closed** 2017-12-04 00:15 UTC
