### ISSUE TITLE
Allow site to autoplay media dialogue doesn't go away and doesn't register yes or no button click

### ISSUE THREAD

**Issue by joshbabier** [brave/browser-laptop#10637] opened 2017-08-23 02:29 UTC
Allow site to autoplay media dialogue doesn't go away and doesn't register yes or no button click.

<img width="1680" alt="screen shot 2017-08-22 at 10 10 05 pm" src="https://user-images.githubusercontent.com/3300450/29596070-4a293fa8-8789-11e7-97f3-3e44f537a91a.png">
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment] 2017-08-23 12:33
Dupe of #9171 . Fix is marked for 0.20.x

**Closed by srirambv** 2017-08-23 12:33 UTC
