### ISSUE TITLE
HTML5 push notifications not working in Windows 10

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1556] opened 2016-05-04 03:12 UTC
Doesn't seem to work in Chrome either for me.  Also previous versions doesn't work.

**Comment by bbondy** [comment] 2016-05-04 03:31
This was tested on Windows 7 by the way, it might work on win8 and win10.

**Comment by diracdeltas** [comment] 2016-05-04 16:51
Both notifications from the page and notifications from the browser context?

**Comment by bbondy** [comment] 2016-05-04 17:02
both I suspect just win7 but I haven't tried on win10 yet.
The permissions all work correctly before the no-op notification though.

**Comment by bbondy** [comment] 2016-05-05 14:12
Tested in Windws 10 x64 and from the content dev tools new Notification('hi') works.
However the browser level ones in the browser console have no effect.

This differs than OS X where it works with both consoles.

**Comment by jonathansampson** [comment] 2016-05-22 03:46
I just tested http://www.bennish.net/web-notifications.html on Windows 10 (10586.318), and it appears to be working correctly.

Brave: 0.10.0
Electron: 0.37.8
libchromiumcontent: 50.0.2661.102
V8: 5.0.71.48
Node.js: 5.10.0
Update channel: dev

![brave notifications](https://cloud.githubusercontent.com/assets/815158/15452035/b71bd25a-1f94-11e6-88f5-6b4e5a45f01d.gif)

**Comment by bsclifton** [comment] 2016-05-22 16:03
Confirmed too! It works and looks great :) And because of the recent chromium updates... like @jonathansampson noticed yesterday, it uses the Windows 10 noticiation center!  I'll open an issue for that, since it shows a bad app name

**Comment by luixxiul** [comment] 2016-05-23 00:17
On my Windows 10 (build 14342) the test causes a crash. I don't know why.

STR
1. Allow Scripts
2. click "Show"
3. click "Allow"

**Comment by bsclifton** [comment] 2016-05-23 00:24
Thanks for trying and also capturing the version info. I updated my post above to capture what I have (which does work). I'm guessing you're in the Windows Insider program (if so, which track)?

**Comment by luixxiul** [comment] 2016-05-23 00:25
> I'm guessing you're in the Windows Insider program (if so, which track)?

Yes, Slow ring. I'm not sure the crash happens on the Fast ring version.

**Comment by bridiver** [comment] 2016-07-29 04:02
I retested on win7 and still no notifications

**Comment by luixxiul** [comment] 2016-07-29 04:04
@bridiver I will check later on win10

**Comment by diracdeltas** [comment] 2016-07-29 05:35
may be related: #2297

**Comment by luixxiul** [comment] 2017-11-07 13:11
This has not caused a crash for a very long time. Closing.

**Closed by luixxiul** 2017-11-07 13:11 UTC
Labels: bug, crash, OS/Windows
