### ISSUE TITLE
Hover state of items in bookmarks bar is faint

### ISSUE THREAD

**Issue by getsetbro** [brave/browser-laptop#5798] opened 2016-11-22 20:19 UTC
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Hover state of items in bookmarks bar is faint
**Expected behavior:**
Should be more obvious, maybe like Safari 
![image](https://cloud.githubusercontent.com/assets/442793/20540308/60d6a0e4-b0be-11e6-9880-ac0fb11c7593.png)

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X
- Brave Version:
0.12.10
- Steps to reproduce:
    1. Bookmark a page
    2. Turn on Bookmarks Toolbar
    3. Hover on a bookmark

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/442793/20540248/19ea9730-b0be-11e6-81cc-315b4d8cd600.png)

- Any related issues:

**Comment by Liunkae** [comment] 2016-11-22 23:00
This was fixed with #5668 and will be included in the next release, 0.13.0. (Duplicate of #5665)

**Closed by Liunkae** 2016-11-22 23:00 UTC
