### ISSUE TITLE
Cannot create wallet with 0.14.2 preview 3

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8281] opened 2017-04-13 05:50 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
While testing 0.14.2 preview 3,I used a clean profile and attempted to create a wallet, the UI never updates. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.14.2 (f07c142)

- Steps to reproduce:
    1. With a clean profile and the latest build of Brave, attempt to create a wallet
    
- Actual result:
The UI never updates, no ledger*.json files are created.

- Expected result:
The wallet should be created without issue.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment] 2017-04-13 05:54
Duplicate of https://github.com/brave/browser-laptop/issues/8195

**Closed by bsclifton** 2017-04-13 05:54 UTC
Labels: bug, release/blocking
