### ISSUE TITLE
Not display correctly one of dropdown menu in zazzle.com

### ISSUE THREAD

**Issue by vikingkarwur** [brave/browser-laptop#811] opened 2016-02-17 23:51 UTC
![zazzle-error-dropdown-menu](https://cloud.githubusercontent.com/assets/464974/13128739/b1d8059e-d60a-11e5-9344-30f86ea7ebac.jpg)

**Comment by bbondy** [comment] 2016-02-24 04:27
Is this still happening for you? I can't reproduce?
It might be an intermittent thing, I've seen some sites not render correctly but then you close the tab and create a new one and it works correctly.

**Comment by vikingkarwur** [comment] 2016-02-24 22:38
I just tried to open in private tab and session tab, and the pull-down-menu --- it works! But in the normal tab, still the same.

**Comment by bbondy** [comment] 2016-02-25 02:49
is the difference maybe only when you are logged in?

**Comment by luixxiul** [comment] 2016-05-15 01:02
Was this fixed?

**Comment by cezaraugusto** [comment] 2016-06-16 16:06
@luixxiul I could reproduce it here.

If you click the profile icon (not logged) and get redirected to the login page, it works on that page.

BTW if you try to access the localized website (http://www.zazzle.com.br), it works on every tested page as expected.

**Comment by luixxiul** [comment] 2017-09-09 14:55
The issue seems to have been fixed by the site design change. Closing.

**Closed by luixxiul** 2017-09-09 14:55 UTC
Labels: bug, needs-info, verified, webcompat
