### ISSUE TITLE
I can not update the browser

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#3072] opened 2016-08-10 04:14 UTC
Yesterday there was the use lockups and when trying to update the browser displayed a message that could not update.

**Comment by luixxiul** [comment] 2016-08-10 09:00
Please describe the problem in detail.

**Comment by bsclifton** [comment] 2016-08-11 15:40
Going to close this for the moment, since it's ambiguous

@EuNlope please re-open if you can describe in more detail and/or have steps to reproduce :smile:

**Closed by bsclifton** 2016-08-11 15:40 UTC
Labels: info-needed
