### ISSUE TITLE
"Brave starts with Dashboard" incompatible with "A new tab shows Blank page"

### ISSUE THREAD

**Issue by Zuzu-Typ** [brave/browser-laptop#6521] opened 2017-01-04 16:33 UTC
**Did you search for similar issues before submitting this one?**
I did a quick search

**Describe the issue you encountered:**
Brave doesn't always start the Dashboard, even though it is selected in the preferences.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave 1.13.0dev RC5

- Steps to reproduce:
    1. Go to about:preferences
    2. select **_Dashboard_** for **_Brave starts with_**
    3. select something other than **_Dashboard_** for **_A new tab shows_**
    4. restart Brave

- Screenshot if needed:

- Any related issues:

**Comment by Zuzu-Typ** [comment] 2017-01-22 11:16
Here's an example scenario:
Here are the settings:
![blankpage](https://cloud.githubusercontent.com/assets/20467351/22182087/43499e60-e09c-11e6-8b71-0761d9c58547.PNG)

On restarting, this is what Brave should do:
![braveshoulddo](https://cloud.githubusercontent.com/assets/20467351/22182085/3dc11c0c-e09c-11e6-89ff-d37650f86820.png)

This is what Brave does though:
![bravedoes](https://cloud.githubusercontent.com/assets/20467351/22182084/3dc0fb28-e09c-11e6-8d3b-c86798c2bfc4.png)

**Comment by luixxiul** [comment] 2017-01-22 12:09
@bbondy does this block the release?

**Comment by bsclifton** [comment] 2017-01-23 07:50
Unable to reproduce with master; I believe this was fixed with https://github.com/brave/browser-laptop/commit/d4f79bed085c7cf83645a395915c9e72d7d4eb2f (RC5 also had an older version of Muon).

Let's re-open if this occurs in the new RC

**Comment by bsclifton** [comment] 2017-01-23 08:02
Re-opening after @NejcZdovc was able to reproduce

**Comment by bsclifton** [comment] 2017-01-23 08:58
Moving to 0.13.1 since this bug was not introduced with 0.13.0

**Comment by bsclifton** [comment] 2017-01-23 10:04
After implementing a "fix" for this, I strongly believe the fix would introduce unnecessary complexity.

I think we have two better choices we can make:

1. Don't allow folks to pick **"Brave starts with Dashboard"** if "A new tab shows" is set to **"Blank page"**
2. Break dashboard out into it's own page, `about:dashboard`. There would no longer be a conflict, but `about:newtab` and `about:dashboard` would be two separate pages.

Both options get rid of the conflict. Letting someone launch into dashboard where they can see stats and tiles is useless IMO if there's not a way for them to get back (because new tabs would only show blank). 

My personal preference would be choice 1 for now. We could create an issue for choice 2 and push to the contributor backlog

cc: @bradleyrichter

**Comment by bsclifton** [comment] 2017-01-23 20:53
Marked as release notes exclude since this new "dashboard" choice was introduced with 0.13.0 with https://github.com/brave/browser-laptop/pull/5690

**Comment by bsclifton** [comment] 2017-01-23 20:56
## Test Plan
1. Go to about:preferences
2. Ensure "Brave starts with" dropdown no longer has "Dashboard"; it should have "a new tab"

**Closed** 2017-01-23 20:56 UTC
Labels: bug, feature/newtab, QA/steps-specified, release-notes/exclude
