### ISSUE TITLE
youtube full screen doesn't behave correctly

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#726] opened 2016-02-11 16:57 UTC
Steps to reproduce:
1. Open a youtube video
2. Click the fullscreen button on the video
First part of unexpected behavior is that the tabs and urlbar are still visible
3. Exit fullscreen with the keyboard shortcut

Expected behavior:
Should return to embedded video in page
Actual behavior:
window is no longer fullscreen, but the video still takes up the entire browser window

**Comment by PFCKrutonium** [comment] 2016-02-27 17:45
Duplicate of #284 , but this one has more details

**Closed** 2016-03-20 17:27 UTC
