### ISSUE TITLE
Issue: No Flash player recognized on Ustream or the Nasa TV website

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#595] opened 2016-02-03 16:04 UTC
As the title says, Ustream or Nasa TV direct stream on the Nasa webpage are seeing Flash as "not installed"

**Comment by psimyn** [comment] 2016-02-04 04:23
Can you please add links to this wiki page?

https://github.com/brave/browser-laptop/wiki/Non-Supported-Video-Sites

**Comment by diracdeltas** [comment] 2016-02-08 20:27
duplicate of #386

**Closed** 2016-02-08 20:27 UTC
Labels: duplicate
