### ISSUE TITLE
URL is partly highlighted in autocomplete list

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2542] opened 2016-07-17 14:04 UTC
**Describe the issue you encountered:** When I was looping items in an autocomplete list on the URL bar, I noticed that the URL is partly highlighted. Just "book.com/" of facebook.com/ is highlighted.

**Expected behavior:** Either all of the URL should be highlighted or none of it should be.
- Brave Version: 0.11.1 Beta1
- Steps to reproduce:
  1. Go to facebook.com
  2. Go to your own timeline
  3. Loop items in the autocomplete list
- Screenshot if needed:
  ![screenshot 2016-07-17 22 50 21](https://cloud.githubusercontent.com/assets/3362943/16900988/f9c61be8-4c70-11e6-83be-ff8dce64859b.jpg)
- Any related issues: #2210

**Comment by bbondy** [comment] 2016-07-18 03:09
I think this is expected behaviour and matches chrome and firefox.  Can you confirm? It should select only the part that is being added for you.
Maybe I don't understand the issue you posted, let me know.

**Comment by luixxiul** [comment] 2016-07-18 04:39
On Chrome, when you choose the URL with the down arrow key, the highlight is cleared. On Brave, when you loop the list and select the first item, the highlight remains.

![facebook](https://cloud.githubusercontent.com/assets/3362943/16906131/c88497ae-4cec-11e6-8147-77c6b4d28cdd.gif)

Is this intended?

**Comment by darkdh** [comment] 2016-07-18 04:43
I thought this is the intended behavior.
Here is the screenshot after I navigate through the autocomplete and back on FF
<img width="421" alt="screen shot 2016-07-18 at 12 40 58" src="https://cloud.githubusercontent.com/assets/11330831/16906164/277ccae0-4ce5-11e6-8c6d-51d2b2672e98.png">

**Comment by bbondy** [comment] 2016-07-18 04:51
Strange, for me it clears when I press the down arrow.

**Comment by darkdh** [comment] 2016-07-18 04:52
You can navigate back to the first entry. The highlight will show up.

**Comment by bbondy** [comment] 2016-07-18 04:57
I don't mind that behaviour, it is actually navigating one past the first one.

**Comment by bsclifton** [comment] 2017-05-17 21:19
Closing as `wontfix` since this is intentional (and we've had it for so long)

**Closed by bsclifton** 2017-05-17 21:19 UTC
Labels: feature/autocomplete
