### ISSUE TITLE
Unable to add site to Pocket

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#9669] opened 2017-06-22 20:33 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Unable to add a site to Pocket. Whenever I click on the pocket icon, I get a login page that spins.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS  (asked @srirambv to confirm on Windows as well)

- Brave Version (revision SHA):
Name	Version
Brave	0.17.6
rev	30a3eee
Muon	4.1.2

- Steps to reproduce:
1. Start with clean install of 0.17.6
2. Enable Pocket in Preferences > Extensions (Pocket Version is 2.1.32)
3. Login to Pocket on tab that opens.
4. You are logged in and navigated to your list.
5. Open a new tab and navigate to a site (I used nytimes.com)
6. Click on a link to open a news article
7. Select the Pocket icon.
8. Pocket login page opens in a new tab and just spins. Site is not added to your list. See screenshot below. 
    
- Actual result:
Unable to add site to pocket, login page displays and spins

- Expected result:
Site should be added to pocket, no login page should be displayed.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![screen shot 2017-06-22 at 4 21 59 pm](https://user-images.githubusercontent.com/28145373/27454592-6a9f5822-5768-11e7-93ab-80b59517e4b5.png)

- Any related issues:
https://github.com/brave/browser-laptop/issues/9117 https://github.com/brave/browser-laptop/issues/9697

cc: @jonathansampson @kevinlawler

**Comment by srirambv** [comment] 2017-06-22 20:36
Confirmed on Windows as well.

**Comment by bsclifton** [comment] 2017-06-23 06:54
Is this the same issue as https://github.com/brave/browser-laptop/issues/9117? ex: if you exit Brave and relaunch, does the issue still happen? (or is it only on the first load)

**Comment by bsclifton** [comment] 2017-06-23 06:54
setting to same milestone as https://github.com/brave/browser-laptop/issues/9117

**Comment by LaurenWags** [comment] 2017-06-23 13:01
@bsclifton if I close and relaunch Brave I am still not able to add a site to Pocket (repeating steps 5-8 after Browser is relaunched).

**Comment by bsclifton** [comment] 2017-06-27 06:26
@jonathansampson would you be able to check this out? If Pocket isn't working on 0.17.x, should we block the release?

cc: @bbondy @bradleyrichter @alexwykoff

**Comment by srirambv** [comment] 2017-06-30 03:39
Works on 0.17.13. Able to add site in pocket when logged in. #9117 still seems to be an issue but pocket functionality seems to be back

**Comment by alexwykoff** [comment] 2017-06-30 13:32
Appears to be working, though the first time interaction needs work.

**Comment by bbondy** [comment] 2017-07-11 17:44
@jonathansampson  is going to verify if this is only for existing tabs and not for new tabs once enabled.

**Comment by jonathansampson** [comment] 2017-07-25 23:55
I think this might be a dupe of #4687.

**Comment by jonathansampson** [comment] 2017-07-26 00:05
This issue is a confirmed dupe of #4687.

**Closed by jonathansampson** 2017-07-26 00:05 UTC
Labels: bug, feature/extensions, needs-triage, QA/steps-specified, release/blocking
