### ISSUE TITLE
Can't unpin tabs that are not loading (no option to unpin)

### ISSUE THREAD

**Issue by jayeszee** [brave/browser-laptop#11154] opened 2017-09-26 16:46 UTC
### Steps to Reproduce

  1. Use a server that you have control over. (for me it was localhost)
  2. Have the server on and go to the server.
  3. Pin the website for your server.
  4. Turn off your server
  5. Try to unpin the tab after reloading, it won't let you.

**Actual result:**
No unpin option to unpin a broken link.
![image](https://user-images.githubusercontent.com/10326244/30872503-2b323a10-a29f-11e7-9d53-a219e97298de.png)
![image](https://user-images.githubusercontent.com/10326244/30872516-348ff462-a29f-11e7-9b69-e3153225da69.png)
![image](https://user-images.githubusercontent.com/10326244/30872539-48b32324-a29f-11e7-8859-35d1f67b1eac.png)
![image](https://user-images.githubusercontent.com/10326244/30872549-4f89f952-a29f-11e7-8602-88cbb74e82b6.png)

**Expected result:**
Be able to unpin tabs regardless of if it is loaded.
**Reproduces how often:**
Always
### Brave Version
0.18.36

**Reproducible on current live release:**

**Comment by bsclifton** [comment] 2017-09-26 23:43
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/4063.  The good news is we have a fix which should be merged soon 😄  See https://github.com/brave/browser-laptop/pull/10997 for more info

**Closed by bsclifton** 2017-09-26 23:43 UTC
Labels: bug, feature/pinned-tabs
