### ISSUE TITLE
Browsing history cleared when restart initiated after pref changes 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2867] opened 2016-08-02 12:06 UTC
**Describe the issue you encountered:**
Browsing history cleared when the browser restarts after changes in preferences window requests for restart.

**Expected behavior:**
Browsing history should not be cleared when the browser restarts.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64, Windows 7 Prof

- Brave Version:
0.11.2 Dev Beta 2

**Comment by luixxiul** [comment] 2016-08-02 12:13
Weren't the options to clear data on about:preferences enabled?

**Comment by bradleyrichter** [comment] 2016-08-02 12:40
Weren't the options to clear data on about:preferences enabled?

[--- Commented from Asana.com
#commenter brad richter
---[aa]

**Comment by srirambv** [comment] 2016-08-02 12:48
No only Clear Download history is enabled. Even otherwise when a restart is initiated by the browser it self it shouldn't delete history. As far as I have seen none of the browser does that even if clear private data on close is enabled.

**Comment by luixxiul** [comment] 2016-08-02 13:00
@srirambv I tried to reproduce the error by enabling clear download history and restarting the browser from the notification bar, but I cannot. Would you please provide steps to reproduce this?

**Comment by srirambv** [comment] 2016-08-02 13:23
@luixxiul @bradleyrichter 

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/17010094/17329912/9ccc031e-58bc-11e6-8b21-77e0e57931b0.gif)

**Comment by luixxiul** [comment] 2016-08-02 13:34
I think this works as intended, if you can see history from URL bar. Will you please check it? Session history is yet to be stored. /cc: @bsclifton

**Comment by srirambv** [comment] 2016-08-02 15:39
Well I think its fine if the history is being cleared if the session is closed completely. But since the restart is initiated by a change in pref it should not result in clearing of session history.

**Comment by bradleyrichter** [comment] 2016-08-02 15:55
I agree with @srirambv 

@bbondy  Can we add a flag to not-clear in the case of the pref-induced restart?

**Comment by bbondy** [comment] 2016-08-02 16:53
This adds more complexity and adds too much cases that wouldn't be tested.  If you set these settings you should be ok with frequently losing this data.  And some users might expect that after a restart they are cleared always.  At least they will understand it. Since this doesn't add value, increases complexity, and might increase confusion I'm going to mark this as wontfix.

**Closed by bbondy** 2016-08-02 16:53 UTC
