### ISSUE TITLE
Pressing Alt+F doesn't open file menu

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12458] opened 2018-01-02 10:58 UTC
### Description
Pressing Alt+F doesn't open file menu

### Steps to Reproduce
  1. Set browser focus
  2. Hide file menu by default
  3. Press <kbd>Alt+F</kbd>, file menu is not shown.

**Actual result:**
Pressing Alt+F combination should open up file menu

**Expected result:**
![altf](https://user-images.githubusercontent.com/17010094/34481734-a838e99c-efab-11e7-9e60-76f8f021d030.gif)

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.14
-- | --
Brave Sync | v1.4.2
libchromiumcontent | 63.0.3239.108
Muon | 4.5.33
Node.js | 7.9.0
OS Architecture | x64
OS Platform | Microsoft Windows
OS Release | 10.0.16299
rev | 5d75826
Update Channel | Beta
V8 | 6.3.292.48

**Reproducible on current live release:**
Yes

### Additional Information

**Comment by sergiorojasa** [comment] 2018-01-02 15:10
I would work on this issue.

**Comment by bsclifton** [comment] 2018-01-02 19:35
Because the Windows version of the app does not use a standard menu, this will **not** be a trivial change ☹️

**Comment by hugobuddel** [comment] 2018-02-05 11:36
Alt-F (or just Alt) does not open the menu either on 0.19.134 in Linux either.

**Comment by bsclifton** [comment] 2018-02-07 23:02
@hugobuddel thanks for calling that out.  I believe the menu on Linux is implemented via the Electron popup control.  This must not be setting accelerators

**Comment by jayyyin** [comment] 2018-03-24 18:29
@bsclifton do you know where the code is for this? I'd like to see if I can take a stab at this.

**Comment by jayyyin** [comment] 2018-03-24 20:32
so if I'm understanding this correctly, I need to add a new WindowAction to tell the selection to update, to do that I need a new windowStore and to do that I need a new WindowConstant, am I understanding this right?

**Comment by jayyyin** [comment] 2018-03-25 20:19
I've opened a second pull request since my first branch kind of broke and I wanted to keep it for reference since I did get somewhere with it, so I made a new branch for my second attempt at this, I'm really close I just need some feedback for how to approach actually making the submenu show up after it's been selected, any help would be appreciated.

**Comment by MargarytaChepiga** [comment] 2018-03-26 15:08
I just checked it on Win10, just ALT works perfectly.

**Comment by jayyyin** [comment] 2018-03-26 20:02
I managed to get the submenu to show up after pressing alt-f twice or pressing and holding it, currently working to get it on single (non-held) press

**Comment by bsclifton** [comment] 2018-04-25 06:04
Closing this issue as a duplicate of https://github.com/brave/browser-laptop/issues/2949

**Closed by bsclifton** 2018-04-25 06:04 UTC
Labels: OS/Windows, bug, feature/keyboard-shortcuts, feature/titlebar, parity, windows-important
