### ISSUE TITLE
New window / popups don't close through javascript

### ISSUE THREAD

**Issue by hugobuddel** [brave/browser-laptop#14812] opened 2018-07-24 07:21 UTC
Can't find a similar issue

### Description

Some sites can open popups that should be closed by pressing an in-site button. E.g. login popups that close themselves when you press the login button. Or a hangouts conversation. Those popups do not close in Brave.

I recall there is something in javascript that allows sites to close popups (or other pages) that they have opened themselves.

### Steps to Reproduce

  1. Login on gmail.com, select/start a hangouts conversation (opens in bottom right of gmail page).
  2. Click the 'pop-out' arrow on the top-right of the hangouts conversation. This opens a new window with just the chat. (In Brave this will be a new window with a single open tab; in Chromium it will be a single-page-window without tabs.)
  3. Click the 'pop-in' arrow on the newly opened conversation window. This will put the conversation back in the main gmail window, but not close the pop-up. The tab sort-of 'closes', as in, is removed from the tab-bar. But the actual page is still shown in the popup, but cannot be interacted with.

**Actual result:**
The popup stays open.

Sorry, no screenshot because it would require quite a bit of censoring since the only example I have are from gmail or from login sites. 

**Expected result:**
The popup closes.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
Brave: 0.23.39 
V8: 6.7.288.46 
rev: a38be75ccb0f699f507b66c4d44b3b21d1677e25 
Muon: 7.1.6 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**
Don't know

### Additional Information
Might be fixed when using chrome?

Perhaps it is necessary to enable popups for those sites first.

**Comment by bsclifton** [comment] 2018-07-25 07:42
related: https://github.com/brave/browser-laptop/issues/9622, https://github.com/brave/browser-laptop/issues/11050

**Comment by hugobuddel** [comment] 2018-07-25 08:57
Oh sorry, seems that those issues have the seem root cause. It was hard to find proper terms to search for. This description is so far the only one that is not about a login popup though, so it might be a useful addition. Feel free to close this as a duplicate.

**Comment by bsclifton** [comment] 2018-07-27 21:20
Closing as a dupe of https://github.com/brave/browser-laptop/issues/13370

**Closed by bsclifton** 2018-07-27 21:20 UTC
