### ISSUE TITLE
Sticky pinned tab: new window keeps a tab pinned that was already unpinned

### ISSUE THREAD

**Issue by jenn-rhim** [brave/browser-laptop#10643] opened 2017-08-23 18:37 UTC
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Asana page (https://app.asana.com/0/409171086080319/list) is pinned persistently even though I unpinned the tab. Can't tell it's the 'pin/unpin' issue or an issue of this particular page stuck in the pinned mode. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.6
- Brave Version (revision SHA):
0.18.23
- Steps to reproduce:
    1. Pin a tab in a window
    2. Unpin the tab
    3. Open a new window, and the tab that was unpinned comes as a pinned in the new window. (same results after re-launching Brave)
    
- Actual result:
Unpin works only at the moment of the action
- Expected result:
Unpin should work persistently across windows and sessions.
- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
I'll check if the pin is still sticky after restarting my laptop.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

![1-screen_shot_2017-08-23_at_11_21_06_am](https://user-images.githubusercontent.com/4369856/29632295-6f1bb8f4-87f7-11e7-985c-2b9b300cfef2.png)

![2-screen_shot_2017-08-23_at_11_21_17_am](https://user-images.githubusercontent.com/4369856/29632300-731894b8-87f7-11e7-86f7-955450dc307a.png)

![3-screen_shot_2017-08-23_at_11_21_35_am](https://user-images.githubusercontent.com/4369856/29632304-75ebb364-87f7-11e7-8ce7-139aef52b5ec.png)

- Any related issues:

**Comment by alokpant** [comment] 2017-08-24 09:21
+1 

I also have been experiencing similar issues related to Unpin.

1. Unpinned tabs keep reappearing even once browser opens
2. When only one browser is open, Unpin does not even work. However it works when two instances of brave is open. Steps to reproduce it is:

- Open a pinned window
- Right click on Pinned tab, click on Unpin
- Nothing happens, it remains
- Open another window ( CMD + N ) :  Opens new windows with same pinned item
- Right click on Pinned tab, click on Unpin
- It is unpinned and can close it

Close previous window (with Pinned tabs)
Close new window (where all Pinned tabs are cleared)
Open brave again (Pinned tabs appear).

My configuration is: 


```
Brave | 0.18.23
-- | --
rev | 36ae2ec
Muon | 4.3.10
libchromiumcontent | 60.0.3112.90
V8 | 6.0.286.52
Node.js | 7.9.0
Update Channel | dev
OS Platform | macOS
OS Release | 16.6.0
OS Architecture | x64
```

```
MacBook Pro (Retina, 13-inch, Early 2015)
macOS Sierra Version 10.12.5 
```

This has been happening to me for few weeks now. All articles that I read, keep coming back. 

Thank you.

**Comment by petemill** [comment] 2017-11-09 00:01
Can't reproduce in master (0.22) - it's likely fixed, probably in 0.20.

**Comment by alokpant** [comment] 2017-11-09 06:54
@petemill This was already fixed with new updates. Works for me nicely now.

**Comment by bsclifton** [comment] 2017-11-10 23:57
Closing issue- @jenn-rhim please give this a re-test; I just tried with lastest 0.19.x and verified it works as expected

**Closed by bsclifton** 2017-11-10 23:57 UTC
Labels: feature/pinned-tabs

**Comment by jenn-rhim** [comment] 2017-11-11 00:35
Thanks!  I see it works fine now.
