### ISSUE TITLE
(Win10) 'maximized' window status not restored when brave is restarted.

### ISSUE THREAD

**Issue by u147865** [brave/browser-laptop#12606] opened 2018-01-11 03:52 UTC
### Description
(on Windows 10)After the browser is closed while in a 'maximized' windowed status, re-launching the browser does not restore 'maximized' windowed status. 
Instead, it opens in a slightly bigger window, and is not in full-screen windowed mode.

### Steps to Reproduce
  1. Be on windows 10
  2. Maximize the browser
  3. Close the browser
  4. Open the browser

**Actual result:**
The browser is launched without 'maximized' window status, and is slightly bigger than a 'maximized' window.

**Expected result:**
The browser to launch in a 'maximized' window status, as it was left off.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
Name | Version
-- | --
Brave | 0.19.131
rev | da2f347
Muon | 4.5.36
libchromiumcontent | 63.0.3239.132
V8 | 6.3.292.49
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
Yes. (as of JAN 10 2018)

### Additional Information
Make sure to support multiple brave windows with the status restoration code, this is crucial for the multi-monitor folk.

**Comment by 3dWrecker** [comment] 2018-01-15 07:48
Me too. Please fix! Loving brave except for this.

**Comment by NejcZdovc** [comment] 2018-01-15 08:32
Hi, thank you for the report. I think this is dupe of #8600. This issue will be fixed in 0.20.x.

**Closed by NejcZdovc** 2018-01-15 08:32 UTC
