### ISSUE TITLE
The cmd-ctrl-space keyboard shortcut on macOS doesn't bring up the emoji and symbols picker in text inputs on web pages

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#13400] opened 2018-03-07 22:41 UTC
### Description
On macOS, there's a menu item `Edit -> Emoji & Symbols`. This brings up a symbol picker. It's very handy. There's even a keyboard shortcut for it: `cmd-ctrl-space` by default. While using the menu item directly seems to work just fine everywhere in Brave, the keyboard shortcut doesn't seem to work on webpage text inputs. The keyboard shortcut *does* work in the Brave address bar, though.

### Steps to Reproduce
  1. Go to Github.com.
  2. Focus the Github search bar.
  3. Type `cmd-ctrl-space`

**Actual result:**
Nothing happens.

**Expected result:**
The `Emoji & Symbol` picker should popup, like when you select `Edit -> Emoji & Symbols` from the menu.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
```
Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
```

**Reproducible on current live release:**
Yes

**Comment by jonathansampson** [comment] 2018-03-07 22:47
May be caused by some of our _accelerator_ logic: https://github.com/brave/browser-laptop/search?utf8=%E2%9C%93&q=cmdorctrl&type=

**Comment by Liunkae** [comment] 2018-06-05 20:20
Duplicate of #13151

**Comment by Liunkae** [comment] 2018-06-05 20:21
Duplicate of #13151

**Closed** 2018-06-05 23:31 UTC
Labels: duplicate, feature/keyboard-shortcuts
