### ISSUE TITLE
Keyboard shortcuts doesn't work when the keyboard is not English on OSX

### ISSUE THREAD

**Issue by lonormaly** [brave/browser-laptop#13902] opened 2018-04-23 13:59 UTC
### Description
Keyboard shortcuts doesn't work when the keyboard is not English on OSX

### Steps to Reproduce
1. Switch to foreign language on the keyboard.
2. Use Cmd+C to copy and Cmd+V to paste

**Actual result:**
Shortcuts doesn't work

**Expected result:**
(as in rest of the OS): Copy Paste (and rest of the shortcuts) should work.

**Reproduces how often:**
Consistently

### Brave Version

**about:brave info:**
Name | Version
Brave | 0.22.22
V8 | 6.5.254.41
rev | 6303310
Muon | 5.1.2
OS Release | 17.5.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.181

**Comment by sliday** [comment] 2018-04-26 02:55
I can confirm the issue, unfortunately. Shortcuts (e.g. CMD+T, CMD+L. CMD+C, CMD+V) are not recognised when non-English layout is selected.

**Comment by sliday** [comment] 2018-05-08 05:51
Still a problem. Very annoying.

**Comment by lonormaly** [comment] 2018-05-08 20:41
Agree, really frustrating...

**Comment by DKunin** [comment] 2018-05-28 06:08
Same here.

Not sure how to approach fixing this.

**Comment by nyngwang** [comment] 2018-06-04 04:41
Same here. We need this. Why close it.

This make me want to change back to Safari.

**Comment by bsclifton** [comment] 2018-06-05 04:13
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/11908

**Closed by bsclifton** 2018-06-05 04:13 UTC
Labels: feature/keyboard-shortcuts, l10n
