### ISSUE TITLE
pressing ctrl+arrows while typing a text is naviagting browser through pages vs 

### ISSUE THREAD

**Issue by Gnaneshwar511** [brave/browser-laptop#487] opened 2016-01-31 05:27 UTC
While typing a text or when cursor is in focus, 'Ctrl + Arrow Left' and 'Ctrl + Arrow Right' should do the following operations:
Ctrl+Arrow Left [text]: Moves the text cursor to the start of the previous word or the end of the previous line, whichever is closer.

Ctrl+Arrow Right [text]: Moves the text cursor to the start of the next word or the end of the current line, whichever is closer.

But it is navigating the pages instead!

For your reference:

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=21&ved=0ahUKEwj4xcunp9PKAhWFKGMKHXTkCswQFgiCATAU&url=http%3A%2F%2Fwww.editpadpro.com%2Fmanual%2Fhelpkeyboard.html&usg=AFQjCNFg62ioQfM8w_o_ZIXV1OMw1c6o-Q&bvm=bv.113034660,d.cGc&cad=rja

**Comment by diracdeltas** [comment] 2016-01-31 22:58
duplicate of https://github.com/brave/browser-laptop/issues/378, which was fixed yesterday.

**Closed** 2016-05-17 12:59 UTC
Labels: duplicate
