### ISSUE TITLE
Pressing tab on highlighted autofill entry doesnt complete the user id field

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9170] opened 2017-05-31 09:11 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Pressing tab on highlighted autofill entry doesnt complete the user id field

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64, ia32

- Brave Version (revision SHA):
Brave	0.15.312
rev	cc653ff
Muon	3.0.202

- Steps to reproduce:
    1. Visit https://trac.torproject.org/projects/tor/login
    2. Login once so that the autofill entry is stored for the site
    3. Reopen/refresh the page and click on the login field to show the autofill suggestion to popup
    4. Highlight the autofill suggestion using down arrow button and press <kbd>Tab</kbd>
    5. Enter text is retained in the user id field, doesn't complete the user id from autofill suggestion
    6. Password gets autofilled  correctly  

- Actual result:
Pressing tab on highlighted autofill entry doesnt complete the user id field

- Expected result:
Should autocomplete the userid field when <kbd>Tab</KBD> is pressed

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Not checked yet to confirm

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Ensure password length is less or more than the user id to help count the characters. Having same amount of char for both doesn't help in knowing if the password field is getting the password or the userid
    2.
    3.

- Screenshot if needed:
![autosuggesttab1](https://cloud.githubusercontent.com/assets/17010094/26624584/3a22fe0a-45e9-11e7-8463-4d98339473be.gif)

- Any related issues:
#7132

**Comment by alexwykoff** [comment] 2017-06-13 17:51
@srirambv wdcd?

**Comment by srirambv** [comment] 2017-06-13 18:25
@alexwykoff  Chrome Behavior
![9170](https://user-images.githubusercontent.com/17010094/27098008-f9698390-506d-11e7-8573-4c0217ed73ab.gif)

**Comment by morganrallen** [comment] 2017-06-27 16:19
I'm also seeing a variation of this in Linux, even if the password isn't stored.

steps.
1) log into website
2) Don't have Brave remember password
3) log out
4) Highlight password field
4b optional) start typing email address
5) Down arrow to select desired email address
6) Press tab

expected behavior.
Email field is filled in with selected address.

actual behavior
The email field remains with what ever was (or was not) typed
The **password** field receives the email address.

Brave       0.15.314
rev   	75ffa36
Ubuntu 17.04

**Comment by patrick99e99** [comment] 2017-07-12 21:35
+1

**Comment by bsclifton** [comment] 2017-07-12 23:20
@NejcZdovc you are assigned to this (and IIRC, you originally implemented this). Would you be able to check this out?

**Comment by NejcZdovc** [comment] 2017-07-13 06:43
I did test it out and the problem is exactly what @morganrallen said. So when you press tab key focus is changed to the next input field and in this next field we put autofill content. We could easily fix this with `e.preventDefault()`, but then tab key would act as enter key and would not switch to the next input. You would need to press tab twice, first to fill the input and then to go to the next one.

**Comment by freddiehonohan** [comment] 2017-08-06 22:20
This is really annoying folks, just my two cents.

**Comment by luixxiul** [comment] 2017-08-06 22:55
@freddiehonohan it'll be fixed. please hang tight.

**Comment by nonbob** [comment] 2017-10-17 19:03
I hit this many times a day.  Sometimes my fingers remember the workaround (hit enter before tab), sometimes they don't.  But there are enough things I like about Blaze that it's now my default browser.

**Comment by srirambv** [comment] 2017-12-22 19:41
+1 from #12383

**Comment by srirambv** [comment] 2017-12-22 19:41
+1 from @paulizleet via 12383

**Closed** 2018-08-30 06:33 UTC
Labels: bug, feature/autofill, fixed-with-brave-core, regression, wontfix
