### ISSUE TITLE
implement session history context menu for back and forward buttons

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#660] opened 2016-02-08 05:00 UTC
context clicking the back and forward buttons should show session history like other browsers do.

**Comment by psimyn** [comment] 2016-02-13 15:52
I think this will need some electron changes as well: to expose history as a list, and to store title as well as url.

**Comment by luixxiul** [comment] 2016-05-15 15:40
Which browsers do show a session history?

**Comment by bbondy** [comment] 2016-05-15 21:57
I think this is a dupe of #1622.  Closing for that one since it has a screenshot.

**Closed by bbondy** 2016-05-15 21:57 UTC
