### ISSUE TITLE
Tearing off tab into window doesn't show up the pinned tabs until quit and restart

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9401] opened 2017-06-12 18:15 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Tearing off tab into window doesn't show up the pinned tabs until quit and restart

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.16.9
rev	fba98fc
Muon	4.0.3

- Steps to reproduce:
    1. Pin few tabs in a window
    2. Open a new tab and tear it off to a new window
    3. Teared off window doesn't have tab
    4. Quit and restart browser, both windows have pinned tabs now
    
- Actual result:
Tearing off tab into window doesn't show up the pinned tabs until quit and restart

- Expected result:
Tear off tab into a new window should have pinned tabs 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![tearoff](https://user-images.githubusercontent.com/17010094/27048376-7329acbc-4fa3-11e7-974b-c58d1f459c45.gif)

- Any related issues:
cc: @bbondy

**Comment by bsclifton** [comment] 2017-06-15 23:42
I'm not able to reproduce on macOS or Windows with 0.16.9...  I do see the new window (created via tear off) taking a while to load... you can see the tabs pop in and then start loading

**Comment by bsclifton** [comment] 2017-06-15 23:46
I tried a fresh session, no luck.  Closing issue until more steps can be provided

cc: @srirambv

**Closed** 2017-06-15 23:46 UTC
Labels: bug, feature/pinned-tabs, QA/steps-specified, regression
