### ISSUE TITLE
Pinned tabs duplicated on restart

### ISSUE THREAD

**Issue by Aeyoun** [brave/browser-laptop#3802] opened 2016-09-07 23:34 UTC
1. Have one window (window 1) and pin any tab to it
2. Open a second window 2
3. Close window 2, and then 1 (Brave exits)
4. Start Brave again

Your pinned tab(s) have been duplicated. Unpinning one of the duplicates remove the duplicate and leaves you with one pinned tab. Restarting Brave again will remove the duplicates. Opening more than two windows will duplicate the pinned tabs again and again and again … .

Linux, Brave 0.12.0

**Comment by bbondy** [comment] 2016-09-08 14:14
Closing as dupe of https://github.com/brave/browser-laptop/issues/3039 we want to refactor some code for pinned tabs soon which would fix this.

**Closed by bbondy** 2016-09-08 14:14 UTC
