### ISSUE TITLE
Import cookie from Chrome hangs on linux

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#11280] opened 2017-10-04 23:13 UTC
Importing cookies from either Chrome/Chromium on linux will hang and produce a crash. However, the crash doesn't take down the entire browser.

### Steps to Reproduce

  1. using a linux distro, ensure that you have either Chrome/Chromium installed
  2. install and launch Brave
  3. visit about:preferences#general and click on "Import Now.."
  4. select "Chrome" from the dropdown list and ensure "Cookies" is the only option selected
  5. click on "Import" and you'll receive the crash (see examples listed below)

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% reproducible using the above STR.
### Brave Version

> Brave: 0.19.28 
> rev: 08781a596c1a0a461c8863692e4be51ebb3babf2 
> Muon: 4.4.25 
> libchromiumcontent: 61.0.3163.100 

**Reproducible on current live release:**

`0.18.36` isn't crashing when importing cookies from Chrome/Chromium, but it looks like it's not working either... Example:

* open Chrome/Chromium
* visit http://www.html-kit.com/tools/cookietester/ and set a cookie
* close Chrome/Chromium and re-open Brave
* Import cookies via about:preferences#general -> "Import Now.."
* visit http://www.html-kit.com/tools/cookietester/ within Brave

You'll notice that the cookie information from Chrome/Chromium hasn't been imported.

### Examples of Issue:

<img width="360" alt="31145045-8d2f0106-a850-11e7-8114-e5bd72a20a6c" src="https://user-images.githubusercontent.com/2602313/31206783-087359d2-a948-11e7-8324-432c209cfe73.png">

<img width="360" alt="31145048-8fb3c9de-a850-11e7-9a92-1db3c410df89" src="https://user-images.githubusercontent.com/2602313/31206785-0a277b1e-a948-11e7-91b2-f01d4e5be1e2.png">

![31145070-a709d52e-a850-11e7-9133-4af06c561022](https://user-images.githubusercontent.com/2602313/31206771-fbb4253c-a947-11e7-8ffa-f0307cadb217.gif)

### Additional Information

cc @kjozwiak

**Comment by bsclifton** [comment] 2017-10-10 19:41
Moving to 0.19.x release 2

**Comment by bsclifton** [comment] 2017-10-10 23:21
Moving back to 0.19.x- Muon build is in progress (should be in one of the next 0.19.x builds)

**Comment by kjozwiak** [comment] 2017-10-11 15:49
@darkdh it looks like this is still happening under Ubuntu... I went through the same STR that are listed under https://github.com/brave/browser-laptop/issues/11280#issue-262959401 and received the crash reporter once I tried importing cookies from Chrome... @srirambv also tried on his Ubuntu VM and could also reproduce the issue.

Platforms used:

* Ubuntu 17.04 x64 - Reproduced (still failing)
* Ubuntu 16.04 x64 - Reproduced (still failing)

Brave being used:

> Brave: 0.19.41 
> rev: c33d1c3ead69868cd11f7625e7529ab7a202b15a 
> Muon: 4.4.27 
> libchromiumcontent: 61.0.3163.100

I'm not sure that we're going to have enough time to get this fixed by tomorrow.... If not, we can move it out and place it into https://github.com/brave/browser-laptop/milestone/84.

**Closed** 2017-10-11 18:14 UTC
Labels: bug, feature/importer, muon, OS/unix-like/linux, QA/test-plan-specified, release-notes/exclude
