### ISSUE TITLE
Add roboform extension to 'Brave' browser please

### ISSUE THREAD

**Issue by dochws** [brave/browser-laptop#14598] opened 2018-06-28 21:03 UTC
### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bsclifton** [comment] 2018-06-29 17:15
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/1511

**Closed by bsclifton** 2018-06-29 17:15 UTC
Labels: feature/extensions
