### ISSUE TITLE
Self destructing cookie option

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#7605] opened 2017-03-08 23:53 UTC
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment] 2017-03-09 00:12
Is it possible to close this in favor of #2118?

**Comment by locklin** [comment] 2017-03-09 01:00
I wrote this; self destructing cookies has a different behavior from the idle time thing. The idea is some sites you might want their cookie for the lifetime of a tab (red light in self-destructing cookie), the lifetime of a session (yellow light) or keep it forever (green light). Maybe too complex to leave up to the user.

**Comment by Liunkae** [comment] 2017-03-12 23:57
Similar to the self destructing cookies extension: https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/

**Comment by dillbyrne** [comment] 2017-09-13 08:50
I think the cookies dialogue could be expanded to have

* Block 3rd party
* Allow until base domain change (better wording needed) (block third party)
* Allow all until base domain change (better wording needed)
* Allow all cookies
* Block all cookies

This allows you to have a global option to temporary allow cookies for the duration of their use but they are deleted when they are no longer required. You can still have your site specific settings for persistent sessions. This could be a private by design default that would not impede site usage.

Personally I would use this to block all cookies and temporary allow the ones I need.

**Comment by uriesk** [comment] 2017-11-12 12:23
+1
The reason why this is needed is because some sites don't work when Cookies are disabled (examples: 4chan and github).
So my options currently are:
1. Don't allow Cookies for this site and accept that the site is broken and don't use it
2. Allow Cookies for this site forever and let it store data even thought that i really don't want that and that there is no reason to let it do that
3. Select the "Delete all Cookies when the browser gets closed" options in the Preferences and accept the fact that you are now not able to store any Cookie of any site longer than for the current Browser session
If the Cookie manager of #11107 is implemented, it adds one more option:
4. Allow Cookies for this site forever, and delete this one specific Cookie manually all the time in the Cookie Manager (i think that you will understand how this is not an acceptable option)
If #2118 is implemented, it is exactly the same as 3., just that it happens after some idle time.

**Comment by flamsmark** [comment] 2018-04-03 21:35
Between private tabs and session tabs, we cover a whole load of the core functionality requested here. More detailed options seem like a better fit for an extension than a core browser feature.

**Closed by flamsmark** 2018-04-03 21:35 UTC
Labels: privacy

**Comment by riastradh-brave** [comment] 2018-04-03 21:38
See also: https://github.com/brave/browser-laptop/issues/6684
