### ISSUE TITLE
Dashlane no longer working on new Brave update

### ISSUE THREAD

**Issue by Ben-Epstein** [brave/browser-laptop#13448] opened 2018-03-14 23:23 UTC
### Description
The dashlane plugin for brave is no longer working on V0.21.18
When attempting to click "login" on login box, or the icon on top left, new blank tab opens but nothing ever loads.

**Reproduces how often:**
What percentage of the time does it reproduce? 100%

### Brave Version 0.21.18

**about:brave info:**
 
Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:**
Issue only on newest release. This started happening immediately after updating.

**Comment by Tomatoshadow2** [comment] 2018-03-15 00:16
Duplicate of another issue https://github.com/brave/browser-laptop/issues/13384

**Comment by bsclifton** [comment] 2018-03-15 06:00
Great catch, @Tomatoshadow2; closing

**Closed by bsclifton** 2018-03-15 06:00 UTC

**Comment by Ben-Epstein** [comment] 2018-03-15 16:20
Thanks @Tomatoshadow2 I looked but must have missed it.
