### ISSUE TITLE
Profile corruption and menu bar death under Debian (confirmed for qubes, pending for "bare metal")

### ISSUE THREAD

**Issue by tonsimple** [brave/browser-laptop#9606] opened 2017-06-20 17:19 UTC
- Did you search for similar issues before submitting this one?
yes 
- Describe the issue you encountered:
I've upgraded all software in my VMs (finally) and couldn't start brave.
Only can start brave if profile folder, or, more specifically, the session-store-1 file, is deleted.
Downgrading brave helps.

Also, after upgrade, the menu bar has become completely unresponsive (not a big issue, but I like menu bars!) 

- Platform (Win7, 8, 10? macOS? Linux distro?):

Debian 8 running in a qubes app-vm

- Brave Version (revision SHA):

Brave	0.16.9

rev	fba98fc

Muon	4.0.2

libchromiumcontent	59.0.3071.86

V8	5.9.211.31

Node.js	7.9.0

Update Channel	dev

os.platform	linux

os.release	4.4.67-12.pvops.qubes.x86_64

os.arch	x64

- Steps to reproduce:
    1. Have a Debian 8 in a qubes app vm
    2. Have brave there 
    3. Update to latest (0.16.9)
    4. Now you have to delete profile to start it, and have a broken menu bar
    
- Actual result:
As described above, menu bar broken and previous session and history lost due to need to nuke profile

- Expected result:

Everything, well, working

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Well, given that the issue is centered around profile corruption...

Also, the "menu bar is completely not responsive" part does reproduce with fresh profile

- Is this an issue in the currently released version?
The latest available 

- Can this issue be consistently reproduced?
So far, yes in all my app vms including freshly created one.
I'm travelling so I don't have a bare-metal debian to test.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by srw6666** [comment] 2017-06-20 18:42
Confirmed for bare metal as well.  Running:

ii  brave                   0.17.3-1         amd64            Brave laptop and desktop browser

**Comment by thermalCat** [comment] 2017-06-20 19:11
Appol's if I'm doing this wrong.
traditional Menu at top of window unresponsive since browser installed.
Menu via 'three vertical dots' at top right of window responsive - but lacks the 'history' option.

Brave	0.16.9
rev	fba98fc
Muon	4.0.2
libchromiumcontent	59.0.3071.86
V8	5.9.211.31
Node.js	7.9.0
Update Channel	dev
os.platform	linux
os.release	3.19.0-32-generic
os.arch	x64

**Comment by oddballhero** [comment] 2017-06-20 20:43
I think this is related to issue #9470.

**Comment by Liunkae** [comment] 2017-06-20 20:57
@oddballhero I think so. @tonsimple, @srw6666, and @thermalCat, please try the latest version (0.16.12).

**Comment by srw6666** [comment] 2017-06-20 21:14
Also an issue in 0.17.3 so whatever fix was made was not ported to the 0.17.x branch

**Comment by oddballhero** [comment] 2017-06-20 22:40
0.16.11 menu bar was working (at least on fluxbox), upgraded to 0.16.12 and menu bar now not working.  While I was upgrading my machines earlier, one of my machines got 0.16.11 but when I went to upgrade my other machines, the repository was updated from 0.16.11 to 0.16.12.

**Comment by tonsimple** [comment] 2017-06-20 23:06
@Liunkae 
Tried 0.16.12, same behavior wrt menu but managed to recover old session store. Wrote down sites of interests and re-tried on clean install.

"dead menubar" issue persists on 0.16.12

**Comment by luixxiul** [comment] 2017-06-21 06:53
https://github.com/brave/browser-laptop/issues/9470#issuecomment-309980488

>> updated it to 0.16.12 and menu bar not working again
> 
> Confirmed on Debian on Gnome
>
> with 0.16.12, 72624a2

**Comment by bsclifton** [comment] 2017-06-21 06:58
This is definitely an issue we're looking into.  0.16.11 did fix the menubar issue but introduced a different (also bad) bug, which is why we release 0.16.12.  We are re-adding the proper menu fix in now and expect to have a Linux only release within the next 24 hrs 😄

**Comment by luixxiul** [comment] 2017-06-21 06:58
Fixed on 0.17.4 :-)

**Comment by srw6666** [comment] 2017-06-21 15:14
Confirmed...it is fixed in 0.17.4.

**Comment by bsclifton** [comment] 2017-06-21 18:14
Officially fixed in https://github.com/brave/browser-laptop/releases/tag/v0.16.13dev, which is now available for download.  You can also update via `apt` / `yum` / etc if you had originally installed Brave like that 😄

**Closed by bsclifton** 2017-06-21 18:14 UTC
Labels: bug, OS/linux-distros, priority/high, release/blocking

**Comment by oddballhero** [comment] 2017-06-21 19:49
Works in Debian Stable Fluxbox and Debian Stable Mate with Brave 0.16.13 without different issue seen in 0.16.11.
Thank you.

**Comment by tonsimple** [comment] 2017-06-26 09:06
Fixed for me in latest, all is fine now

**Comment by bsclifton** [comment] 2017-06-27 06:09
@oddballhero @tonsimple thanks for confirming the fix 😄
