### ISSUE TITLE
Brave not asking for permissions when loading geolocations 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11036] opened 2017-09-20 10:38 UTC
### Description
Brave not asking for permissions when loading geolocations 

### Steps to Reproduce

  1. Visit https://browserleaks.com/geo
  2. Shows location without asking for permission
  3.

**Actual result:**
Location shown without permission

**Expected result:**
Should ask permisiom before showing location

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version

Brave | 0.19.7
-- | --
rev | c8481a9
Muon | 4.4.16

### Additional Information

#10864

**Comment by luixxiul** [comment] 2017-09-20 10:46
Reproduced on Debian. See https://github.com/brave/browser-laptop/issues/10864#issuecomment-330813945 for platform info.

**Comment by luixxiul** [comment] 2017-09-20 10:48
@srirambv since the issue is not fixed or decided yet this issue should be excluded from the release note (even though this is release/blocking), I removed the release-notes/exclude label in case. Let's re-add it after it is fixed later.

**Comment by NejcZdovc** [comment] 2017-09-20 10:54
this will be fixed with #10896

**Comment by srirambv** [comment] 2017-09-20 12:50
#9451 Fails because of this.

**Comment by bbondy** [comment] 2017-09-20 14:15
Fixed by this merge, but please re-test it on the per issue testing since it had to wait to land:
https://github.com/brave/browser-laptop/issues/10864

**Closed by bbondy** 2017-09-20 14:15 UTC
Labels: bug, feature/notificationbar, regression, release/blocking
