### ISSUE TITLE
history entry without date re-appears by removing the entry

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10092] opened 2017-07-22 16:08 UTC
**Describe the issue you encountered:** history entry without date re-appears by removing the entry on about:history.

![bug](https://user-images.githubusercontent.com/3362943/28492722-4d568b1c-6f43-11e7-8389-d3476f0b85ad.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA): 0.17.17

- Steps to reproduce:
    1. Change the date to old one on your computer
    2. Visit some sites
    3. Revert the date change
    4. Visit some sites
    5. Open about:history
    6. Delete the latest entry
    
- Actual result: the entry re-appears on the bottom, without the visit date

- Expected result: The entry should not re-appear

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #5417

**Comment by luixxiul** [comment] 2017-07-22 16:08
cc @NejcZdovc

**Comment by srirambv** [comment] 2017-07-22 16:48
Dupe of #8761 #9715

**Closed by srirambv** 2017-07-22 16:48 UTC
Labels: bug, feature/history
