### ISSUE TITLE
Pinned Tab Does Not Close on Middle Click

### ISSUE THREAD

**Issue by BetaPotato** [brave/browser-laptop#4435] opened 2016-10-02 03:04 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
If a pinned tab is middle clicked on while selected, it will switch to the first tab in the first tab page. If the tab is not selected, the tab will disappear, but will reappear once a tab with a website is loaded/reloaded or when another tab is pinned.

**Expected behavior:**
Pinned tab is closed on middle click.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Window 7 (64 bit)

- Brave Version:
0.12.1

- Steps to reproduce:
    1. Pin a tab
    2. Create an unpinned tab
    3. Select the unpinned tab
    4. Middle click on pinned tab
    5. Load/reload website in unpinned tab

**Comment by luixxiul** [comment] 2016-10-02 06:14
Dupe of #2569

**Closed by luixxiul** 2016-10-02 06:14 UTC
