### ISSUE TITLE
Middle-clicking a pinned tab executes "next tab" instead fo closing the pinned tab

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#2569] opened 2016-07-18 19:34 UTC
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
A friend said when they middle-clicked pinned tabs, Brave crashed. When I tried to reproduce this, Brave didn't crash. However, middle-clicking a pinned tab doesn't close that tab, as it does for unpinned tabs. Instead, it issues a "next tab" command, and will continuously cycle through all the tabs (pinned and unpinned).

**Expected behavior:**
I expect middle-clicking a pinned tab to close that tab.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  OS X 10.11.5
- Brave Version:
  0.11.0
- Steps to reproduce:
  1. Open a Brave window. 
  2. Open a few tabs to some sites.
  3. Pin at least one tab.
  4. Middle-click any pinned tab. The tab to the right of the active tab will become active.
  5. Keep middle-clicking the pinned tab. The active tab will keep moving to the next tab. (Same as using the "Select next tab" command.)
- Screenshot if needed:
  Here's a screencast. I'm middle-clicking the pinned tab. http://quick.as/payztzjxy
- Any related issues:

**Comment by luixxiul** [comment] 2016-07-19 09:31
Also with one pinned tab if you click it Brave quits without a warning prompt, which is yet to be implemented according to #854

**Comment by luixxiul** [comment] 2016-10-02 06:17
does it work as it should? /cc: @bbondy

**Comment by bbondy** [comment] 2016-10-04 05:52
This is per design but I think there's another issue posted which suggests an alternate way from Brad.

**Comment by luixxiul** [comment] 2017-11-07 11:51
Currently clicking the middle button does nothing on 0.19.80. Has it stopped working at some timing or is it by design?

 
Brave: 0.19.80 
rev: 7d07299a5d462d3c9ae32cfbfbe7296cc57c89b9 
Muon: 4.5.13 
libchromiumcontent: 62.0.3202.75 
V8: 6.2.414.36 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.14393 
OS Architecture: x64

**Comment by bbondy** [comment] 2017-11-08 21:01
I think it was disabled at some point on purpose in favour of doing nothing. There is also a task for explicit close in context menu so I'm going to close this.

**Closed by bbondy** 2017-11-08 21:01 UTC
Labels: feature/pinned-tabs, needs-info
