### ISSUE TITLE
Opening a new window should not have pinned tabs

### ISSUE THREAD

**Issue by inian** [brave/browser-laptop#14436] opened 2018-06-16 08:23 UTC
### Description
Whenever I open a new window, I see the pinned tabs in the newly opened window as well. In Chrome, pinned tabs are not opened when opening a new browser window. I think this makes more sense since I don't want the same tabs to be opened again and again for each browser window I open. 

### Steps to Reproduce
  1. Pin sites in a browser window
  2. Open a new browser window

**Actual result:**
Pinned sites open automatically on new browser window launch

**Expected result:**
Pinned sites do not open in the newly launched browser window

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.22.810

**Reproducible on current live release:**
Yes

**Comment by srirambv** [comment] 2018-06-16 15:29
Dupe of https://github.com/brave/browser-laptop/issues/5800

**Closed by srirambv** 2018-06-16 15:29 UTC
