### ISSUE TITLE
Bug: Script blocking symbol gets not shown under certain conditions

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#2164] opened 2016-06-11 16:35 UTC
**Describe the issue you encountered:**
Sometimes, when opening a page with a middle click in a new tab, the option to allow scripts is not shown in the address bar

**Steps:**
- Go to https://www.google.at/?gws_rd=ssl#q=%22Rainforests:+facts%2C+figures%2C+news%2C+and+pictures%22

- open the page rainforests.mongabay.com with a middle click

- Noscript symbol is not shown in the address bar

**Expected behavior:**
Noscript symbol should be shown in the address bar when opening pages with a middle click

- Platform (Win7, 8, 10? OS X? Linux distro?):
Windows 8

- Brave Version:
0.10.3

**Comment by diracdeltas** [comment] 2016-06-13 20:07
dupe of  #2138

**Closed** 2016-06-13 20:20 UTC
Labels: duplicate
