### ISSUE TITLE
Regression: Brave: 0.12.1 - Lastpass doesn't open

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#3883] opened 2016-09-11 01:20 UTC
Hi,

1- I left clicked to open menu.
2- Tried to open lastpass.

See the screenshots of 1 and 2

![captura de tela de 2016-09-10 22-19-07](https://cloud.githubusercontent.com/assets/1178856/18414562/abacbd18-77a4-11e6-8cf8-f9a534158724.png)

![captura de tela de 2016-09-10 22-16-47](https://cloud.githubusercontent.com/assets/1178856/18414566/c048daae-77a4-11e6-9869-b17ebfdf9597.png)

**Comment by bbondy** [comment] 2016-09-11 01:24
@bridiver is this fixed?

**Comment by bridiver** [comment] 2016-09-11 02:20
not sure, I haven't tested on linux

**Comment by srirambv** [comment] 2016-09-11 07:40
Confirmed on Windows 10 too. Selecting user account from 1P mini app doesn't populate the user credentials.

**Comment by bsclifton** [comment] 2016-09-11 18:52
@srirambv this is for LastPass- did you post in the wrong issue?

**Comment by bbondy** [comment] 2016-09-12 14:45
@srirambv do we need another issue for it?

**Comment by aekeus** [comment] 2016-09-12 15:41
Data point - LastPass is operating correctly on osx

<img width="142" alt="screen shot 2016-09-12 at 11 39 57 am" src="https://cloud.githubusercontent.com/assets/210240/18442158/af229c76-78dd-11e6-8e97-2c3d01d8f9b6.png">

**Comment by bridiver** [comment] 2016-09-12 15:57
@srirambv - are you checking 1password or lastpass? Also, please check against RC1 because there are some extension buttons fixes from yesterday that I believe are in it. @bbondy can confirm

**Comment by srirambv** [comment] 2016-09-12 18:01
My bad got confused. It was for 1Password. Will open a separate issue for that.

**Comment by srirambv** [comment] 2016-09-12 18:24
Just an update on the 1Password. It was working in 0.12.1 preview1 build. Weirdly its now working on 0.12.1 Preview3 build as well. When checked in morning on a clean install of preview 3 didn't work at all.

**Comment by bitcoinuser** [comment] 2016-09-13 00:12
Preview3 on Ubuntu:

![captura de tela de 2016-09-12 21-10-27](https://cloud.githubusercontent.com/assets/1178856/18457266/9d654cf4-792d-11e6-9dce-c8c756604b08.png)

**Comment by bridiver** [comment] 2016-09-13 02:29
@bitcoinuser is that from the extension button or context menu?

**Comment by bitcoinuser** [comment] 2016-09-13 02:31
Extension button.

Em 12/09/2016 23:29, "Brian Johnson" <notifications@github.com> escreveu:

**Comment by ayumi** [comment] 2016-09-13 03:52
On Ubuntu 16.04 w/ Brave 0.12.1dev preview 3, confirming LastPass extension looks weird as @bitcoinuser described:

<img width="1036" alt="screen shot 2016-09-12 at 20 33 01" src="https://cloud.githubusercontent.com/assets/521861/18460697/88856332-7928-11e6-99c1-be01045d03f5.png">

**Comment by bitcoinuser** [comment] 2016-09-13 10:11
@bridiver Context menu too.

**Comment by bridiver** [comment] 2016-09-14 04:56
looks like the same thing happens on windows because neither of them get preferred size updates. I'll have to dig around to see what we can use

**Closed** 2016-09-14 05:57 UTC

**Comment by srirambv** [comment] 2016-09-14 19:43
Checked on Ubuntu. the screen flashes at the bottom and then loads 
![41](https://cloud.githubusercontent.com/assets/17010094/18527242/ce109e14-7abb-11e6-9172-5bc51c1fccdb.gif)

**Comment by bbondy** [comment] 2016-09-15 12:23
@srirambv pls post a separate issue for that, it will be prioritized differently so we can release 0.12.1

**Comment by bridiver** [comment] 2016-09-15 15:22
I'm not seeing what the issue is. The behavior in the screenshot looks correct to me
