### ISSUE TITLE
Include a browser shield settings... option in the menu/shields sub category

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7590] opened 2017-03-08 23:50 UTC

**Comment by NejcZdovc** [comment] 2017-03-09 07:09
@jonathansampson is this the same as #6350?

**Comment by jonathansampson** [comment] 2017-03-10 18:47
@NejcZdovc I'm not the author of the idea (I simply filed the issue), but I suspect the author would like to see a shortcut to about:preferences#shields from the Shields menu item. Presently, users only have a shortcut to their Brave Shields Panel, and the Brave Payments settings.

**Comment by luixxiul** [comment] 2017-03-11 19:28
@jonathansampson I thought so too.

**Comment by bsclifton** [comment] 2017-03-16 16:27
Closing as a dupe of https://github.com/brave/browser-laptop/issues/6350

**Closed by bsclifton** 2017-03-16 16:27 UTC
Labels: duplicate, feature/shields, needs-triage
