### ISSUE TITLE
bookmark text spills out of folder drop down on bookmark toolbar

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13373] opened 2018-03-02 18:33 UTC
### Description
Bookmark text is spilling out of the drop down (to the right) when you display the bookmarks in a folder on the toolbar.

### Steps to Reproduce

  1. Have a folder on the bookmarks toolbar.
  2. Add some bookmarks to it that have long names.
  3.

**Actual result:**
Bookmark text spills over to the right.
![screen shot 2018-03-02 at 1 08 28 pm](https://user-images.githubusercontent.com/28145373/36915202-dc74689e-1e1d-11e8-9934-cea82ece9b7a.png)

**Expected result:**
Bookmark text should not spill out:
![screen shot 2018-03-02 at 1 17 03 pm](https://user-images.githubusercontent.com/28145373/36915215-e6a783b4-1e1d-11e8-9771-047d101eb14c.png)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.21.654
V8 | 6.5.254.26
rev | bc6272c
Muon | 5.1.3
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.88

**Reproducible on current live release:**
No, does not reproduce on 0.21.18

### Additional Information
Reproduced by @btlechowski on Windows.

Also occurs on sub folders:
![screen shot 2018-03-02 at 1 28 11 pm](https://user-images.githubusercontent.com/28145373/36915239-fe1b4f80-1e1d-11e8-9ad3-78ab0ed804e0.png)

**Comment by MargarytaChepiga** [comment] 2018-03-09 19:32
I would love to tackle this!

**Comment by MargarytaChepiga** [comment] 2018-03-09 19:39
Can't really reproduce though...
![issue-13373-before](https://user-images.githubusercontent.com/15698572/37226347-a0b48fe8-23a7-11e8-8a64-d86ebc44be66.png)

**Comment by bsclifton** [comment] 2018-03-09 20:11
@MargarytaChepiga this is specific to Chromium 56- you should be able to reproduce by checking out / rebuilding from the `0.21.x-C65` branch. Unfortunately, the change is likely in Muon

**Comment by bsclifton** [comment] 2018-03-09 20:12
Assigning to @ltilve - he was unable to reproduce on Linux, so this may not be related to https://github.com/brave/browser-laptop/issues/13371

**Comment by bsclifton** [comment] 2018-03-13 00:14
`display:table` on the context menu is what causes the issue; should be able to square this up tonite 😄

**Comment by bsclifton** [comment] 2018-03-13 05:33
Fixed with https://github.com/brave/browser-laptop/commit/c26216f8a76cc4eb3feb8e365358d437d3e7412d

**Comment by bsclifton** [comment] 2018-03-13 06:20
per conversation in https://github.com/brave/browser-laptop/commit/c26216f8a76cc4eb3feb8e365358d437d3e7412d, the problem is not fixed actually

Will need some help fixing this up

**Comment by bsclifton** [comment] 2018-03-13 16:22
Properly fixed in 0.21.x-C65 with https://github.com/brave/browser-laptop/pull/13409/commits/0d38e87503c40ea2b07c0b74796b8efdf29d8515 (huge thanks to @cezaraugusto!)

**Closed** 2018-03-13 16:22 UTC
Labels: 0.21.x, bug, feature/bookmarks
