### ISSUE TITLE
Button text needs padding-bottom

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10501] opened 2017-08-15 11:27 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Button text needs padding-bottom

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
0.18.14/0.18.22

- Screenshot if needed:
Top : 0.18.14
Bottom : 0.18.22
![image](https://user-images.githubusercontent.com/17010094/29314167-b531dd5a-8171-11e7-9e19-0d6c1311d210.png)

- Any related issues:
cc: @luixxiul

**Comment by luixxiul** [comment] 2017-08-15 11:30
@srirambv could you please try to reproduce the issue on 0.19? thanks!

**Comment by luixxiul** [comment] 2017-08-15 11:31
also please check if the issue is reproduced on `about:styles`, thanks.

**Comment by srirambv** [comment] 2017-08-15 11:38
Checking on 0.19 but looks fine on about:styles in 0.18.22

**Comment by luixxiul** [comment] 2017-08-15 12:02
The issue is not reproduced for me.

![clipboard01](https://user-images.githubusercontent.com/3362943/29315203-de0bf978-81fc-11e7-88e4-5ceabf188266.png)

Didn't you changed the DPI setting or something?

**Comment by srirambv** [comment] 2017-08-15 13:33
This is on a clean install of 0.18.20 and no changes to UI Scale or default zoom
![image](https://user-images.githubusercontent.com/17010094/29318058-72323bd0-81c6-11e7-92f6-838cf04fd5d7.png)
This is on 0.18.22
![image](https://user-images.githubusercontent.com/17010094/29318104-9b34a96e-81c6-11e7-88bf-9c1c15ac8a09.png)

**Comment by luixxiul** [comment] 2017-08-15 13:34
maybe font rendering on chromium has changed and that could be a reason. CC @cezaraugusto do you know something on this?

**Comment by bsclifton** [comment] 2017-08-15 16:19
Is this issue a duplicate of https://github.com/brave/browser-laptop/issues/9370?

**Comment by luixxiul** [comment] 2017-08-15 16:26
@bsclifton I don't think so, as this issue discusses the padding inside the buttons. #9370 is definitely worth fixing soon, but I'm afraid I don't know how to do.

**Comment by luixxiul** [comment] 2017-09-09 15:26
@srirambv would you mind setting `display: flex` and `justify-content: center` to the button elements would fix the issue?

**Comment by srirambv** [comment] 2017-09-11 06:26
@luixxiul  No change even with the settings override that you provided.

**Comment by luixxiul** [comment] 2017-09-11 06:32
@srirambv do you see the same thing on about:styles?

**Comment by luixxiul** [comment] 2017-09-11 08:54
I think that reducing border-width of the primary button to `1px` would fix the issue most easily but I am afraid it would cause an a11y issue (white border gets less noticiable by doing so).

**Comment by bsclifton** [comment] 2018-09-09 06:55
This has been fixed a while ago

**Closed by bsclifton** 2018-09-09 06:55 UTC
Labels: misc/button, needs-investigation
