### ISSUE TITLE
Bookmark toolbar context menu not working on 0.20.x

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11728] opened 2017-10-31 09:19 UTC
### Test plan
See https://github.com/brave/browser-laptop/pull/12676

### Description
Bookmark toolbar context menu not working on 0.20.x

### Steps to Reproduce
  1. Build from a42cac1
  2. Add a bookmark to enable bookmark toolbar
  3. Right click anywhere on the tool bar, does't show toolbar context menu instead shows window context menu

**Actual result:**
![bmkcontext](https://user-images.githubusercontent.com/17010094/32216197-4bb77848-be1c-11e7-92a3-7b9d24f7f98f.gif)

**Expected result:**
Should show bookmark toolbar context menu when right clicked on toolbar

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version

**about:brave info:**

Brave | 0.20.1
-- | --
V8 | 6.2.414.36
rev | a42cac1
Muon | 4.5.11

**Reproducible on current live release:**
No

### Additional Information
Found while verifying #11672

**Comment by NejcZdovc** [comment] 2017-10-31 10:40
@srirambv if I am not mistaken this is on windows only right?

**Comment by srirambv** [comment] 2017-10-31 10:46
Correct. Found on Windows, @LaurenWags @kjozwiak could verify for macOS

**Comment by kjozwiak** [comment] 2017-11-01 01:06
> Correct. Found on Windows, @LaurenWags @kjozwiak could verify for macOS

I couldn't reproduce this on either macOS nor Ubuntu... Went through the following checks:

* macOS 10.12.6 x64 on the `0.20.x` branch using bafa261009eb51a451f8b7bceb7e39da543a1519 - Couldn't Reproduce
* Ubuntu 17.04 x64 on the `0.20.x` branch using bafa261009eb51a451f8b7bceb7e39da543a1519 - Couldn't Reproduce
* Win 10 Pro x64 on the `0.20.x` branch using bafa261009eb51a451f8b7bceb7e39da543a1519 - Reproduced

**Comment by bsclifton** [comment] 2017-11-03 20:59
This has been reported many times already- it's a known issue, root cause captured with https://github.com/brave/browser-laptop/issues/4244

**Comment by srirambv** [comment] 2017-12-21 12:57
@bsclifton this is a blocker on 0.20.8. Always shows system context menu on bookmark toolbar. Could #4244 be prioritized to 0.20.x so that it fixes the issue?

**Comment by bsclifton** [comment] 2017-12-21 16:05
@srirambv this has been existing behavior for as long as we've switched to the version without titlebar (possibly earlier).  Are you positive you're not seeing it with 0.19.x?

**Comment by srirambv** [comment] 2017-12-21 16:25
Doesn't happen on the release build 
![11728](https://user-images.githubusercontent.com/17010094/34264601-5ce316fa-e66b-11e7-9390-388d4a414e41.gif)

I remember it  got fixed by some PR a long time back but haven't seen this happen on most recent releases as adding bookmark from toolbar is part of general regression test run so it would have been captured if it happened on 0.19.x

**Comment by bsclifton** [comment] 2017-12-21 16:29
@srirambv thanks for confirming- this new release should work as good as the one before. Maybe a style update affected this. If the area is marked as draggable, it will cause that issue

@luixxiul can you help me look at the area in question? perhaps there was an unintentional regression

**Comment by srirambv** [comment] 2017-12-21 16:33
Another interesting thing is if the toolbar doesn't have any items then right at the edge of the tabs bar the context menu shows up but once you add any item to the toolbar the context menu disappears
![11728-1](https://user-images.githubusercontent.com/17010094/34265034-afb6dc44-e66c-11e7-96a3-d4a6ca52af93.gif)

**Comment by srirambv** [comment] 2018-01-09 12:53
Adding it back to 0.20.x as its blocking couple of other issue to be verified

**Comment by NejcZdovc** [comment] 2018-01-10 11:13
yeah not just bookmarks but tabs as well, more info here #12590.

**Comment by bsclifton** [comment] 2018-01-16 18:14
Likely same fix as https://github.com/brave/browser-laptop/issues/12590

**Closed** 2018-01-18 00:25 UTC
Labels: 0.20.x, OS/Windows, PR/pending-review, QA/test-plan-specified, bug, feature/bookmarks, feature/context-menu, release-notes/exclude, release/blocking
