### ISSUE TITLE
Feature request - enable Chromecasting

### ISSUE THREAD

**Issue by SamClarke2012** [brave/browser-laptop#7402] opened 2017-02-27 06:59 UTC
The ability to cast embedded video is the only reason I would use chome at all (now).  Furthermore, an ability to rival VideoStream (the leading chrome app for casting local files) would be very attractive.

**Comment by jeroen7s** [comment] 2017-03-16 11:30
yup, definitely needs this

**Comment by srirambv** [comment] 2017-04-06 19:25
+1 from community https://community.brave.com/t/its-probably-not-possible-but/2083

**Comment by mwmeyer** [comment] 2017-04-13 01:24
+1 chromecast would be great to have. Is the [chrome sender library](https://developers.google.com/cast/docs/chrome_sender_integrate) from google the SDK brave would need to implement for this?

**Comment by srirambv** [comment] 2017-05-18 17:44
+1https://community.brave.com/t/chromecast-extension/412/2

**Comment by TrueStanos** [comment] 2018-01-18 03:57
This is going to be a must for me to keep using it as a daily driver.  Pretty awesome so far!

**Comment by FluffyJack** [comment] 2018-01-31 23:40
+1 will consider working on this once work is calmer.

**Comment by pjzzzz** [comment] 2018-03-04 14:34
It's a must to keep Brave as my daily browser.

**Comment by tschier** [comment] 2018-04-21 21:51
Same here - our office switched from Chrome to Opera when it implemented this, and would likely switch to Brave if this is added.

**Comment by Alrikja** [comment] 2018-05-04 09:14
+1 Chromecasting is definitely needed to make Brave a daily browser.

**Comment by flightcom** [comment] 2018-05-04 23:48
+1 same for me, I use Chromecast everyday I need this in Brave !

**Comment by ixaeon** [comment] 2018-07-05 00:43
+1,
This is one of the most missing features of brave currently

**Comment by bsclifton** [comment] 2018-07-05 19:54
Duplicate of https://github.com/brave/browser-laptop/issues/8615

There's a large amount of work needed to get this working and I think it's safe to say that we won't deliver it with the current Muon based browser ("browser-laptop").  I'm going to close this issue as `wontfix`

However, I did create an issue for our [new Brave Core browser](https://brave.com/development-plans-for-upcoming-release/):
https://github.com/brave/brave-browser/issues/209

Getting support for Chromecasting should be easy with Brave Core since the Chromium UI has full extension support. We would just need to verify it's being included with our GN setup and determine whether we want to enable/disable by default

**Closed by bsclifton** 2018-07-05 19:54 UTC
Labels: fixed-with-brave-core, suggestion, wontfix
