### ISSUE TITLE
Cmd/Ctrl + shift + p while current tab is on a PDF opens print dialogue (instead of private tab)

### ISSUE THREAD

**Issue by alexanderkoumis** [brave/browser-laptop#11112] opened 2017-09-23 17:50 UTC
Version info:
```
Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: macOS 
OS Release: 15.6.0 
OS Architecture: x64
```
Problem also exists on Windows 7

**Comment by srirambv** [comment] 2017-09-26 03:57
Duplicate of #4024

**Closed by srirambv** 2017-09-26 03:57 UTC
Labels: feature/keyboard-shortcuts
