### ISSUE TITLE
brave doesn't launch correctly under linux

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13995] opened 2018-05-02 19:57 UTC
### Description

When launching `0.22.701` 339ffd6 under Linux, you'll notice that the UI hasn't loaded correctly. Brave is unusable in this state and will eventually crash via a `segmentation fault`.

### Steps to Reproduce

  1. launch `0.22.701` 339ffd6 using `brave-beta  --user-data-dir-name=brave-beta`

**Actual result:**

<img width="1410" alt="screen shot 2018-05-02 at 3 38 21 pm" src="https://user-images.githubusercontent.com/2602313/39545947-c6da018c-4e20-11e8-8b84-e84230d3caf3.png">

<img width="1416" alt="screen shot 2018-05-02 at 3 44 43 pm" src="https://user-images.githubusercontent.com/2602313/39545949-c88675d8-4e20-11e8-8dbd-b0b360edd033.png">

**Expected result:**

Brave under Linux should be launching without any issues.

**Reproduces how often:**

100% reproducible using the STR mentioned above.

### Brave Version

**about:brave info:**

 ```
Brave: 0.22.701 
V8: 6.6.346.26 
rev: 339ffd666e7c70b9b5e1b6d8b54f8b552e20f453 
Muon: 6.0.7 
OS Release: 17.4.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.139
```

**Reproducible on current live release:**

Nope, currently not reproducible under `0.22.669` which is the latest released version.

### Additional Information

@davidtemkin mentioned that he noticed a similar issue on macOS but I still haven't been able to reproduce the issue.

**Comment by bsclifton** [comment] 2018-05-02 20:13
possibly related to https://github.com/brave/browser-laptop/issues/13991

**Comment by matthewberryman** [comment] 2018-05-02 21:37
I'm seeing this under v0.22.702 on macOS

**Comment by matthewberryman** [comment] 2018-05-02 21:41
Confirmed, fixed in v0.22.702 on macOS

**Comment by petemill** [comment] 2018-05-02 21:46
@matthewberryman thanks, when you say it was fixed in .702 - did you get your profile back or did it start with :gulp: ...a new profile?

**Comment by bsclifton** [comment] 2018-05-02 22:35
Should have been fixed with https://github.com/brave/browser-laptop/commit/1b312a25e4b7cba19ebfda0120068516484bb3bd

**Closed** 2018-05-02 22:34 UTC
Labels: 0.22.x-single-webview, OS/unix-like/linux, bug, crash, priority/P1

**Comment by matthewberryman** [comment] 2018-05-02 22:38
@petemill Since I tried blowing away the user data folder anyway to get .701 working I decided to blow it away myself before installing .702. To test to see if .701 -> .702 keeps the user profile I then first started in .702 (since with the bug I can't make any changes in .701), added a bookmark to the bookmark toolbar, reverted to .701, saw it was still there, then swapped back to .702 and it was still there.

**Comment by kjozwiak** [comment] 2018-05-03 16:28
Verified on Mint 18.3 x64 using the following build:

* `0.22.702` e4a853d9990c62328a8a4320fec21f58c9cdc0c1 
* Muon: 6.0.7 
* libchromiumcontent: 66.0.3359.139

Verified on Ubuntu 17.10 x64 using the following build:

* `0.22.702` e4a853d9990c62328a8a4320fec21f58c9cdc0c1 
* Muon: 6.0.7 
* libchromiumcontent: 66.0.3359.139
