### ISSUE TITLE
Right click on any setup file and open in new tab doesn't download the file

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14409] opened 2018-06-14 17:08 UTC
### Description
Right click on any setup file and open in new tab doesn't download the file

### Steps to Reproduce

  1. Open brave with clean profile
  2. Open https://github.com/brave/browser-laptop/releases
  3. Right click on any setup file->Open in new tab

**Actual result:**
Right click on any setup file and open in new tab doesn't download the file>
![open in new tab reloads the same tab](https://user-images.githubusercontent.com/38657976/41426874-aef5e8f0-7022-11e8-8be5-3cd3e21ba3a5.gif)

**Expected result:**
Right click on any setup file and open in new tab should download the file

**Reproduces how often:**
Easy

### Brave Version
0.23.8
**about:brave info:**

 
Brave: 0.23.8 
V8: 6.6.346.32 
rev: 06c657bb7ee5530f93c37f51cc6b7bf158912d04 
Muon: 6.1.5 
OS Release: 10.0.17134 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.181

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment] 2018-06-20 16:25
This happens on our current release

**Comment by darkdh** [comment] 2018-06-20 16:26
And we need to test if it is reproducible in pre-single-webview release
The current behavior is download dialog does got opened but tab will be closed. You can observe that by doing "Open Link in New Window"

**Comment by bsclifton** [comment] 2018-07-28 17:12
Lots of good debugging done on this one in https://github.com/brave/browser-laptop/issues/14844

Basically, the new tab is created with the download item... but the tab doesn't attach the webview in time. The code tries to lookup what window it's associated with and there is no info, because nothing is attached. So it exits

**Comment by bsclifton** [comment] 2018-07-30 20:55
Confirmed this was introduced with 0.22.714 (our initial single webview build)

**Comment by bsclifton** [comment] 2018-07-30 23:01
Fixed with https://github.com/brave/muon/commit/4504af1ad2a704729365f0bbab821c00ea357008

This will be part of 0.23.x Release 5 (builds not available yet)

**Closed by bsclifton** 2018-07-30 23:01 UTC
Labels: 0.22.x-single-webview, feature/download, needs-investigation, priority/P3

**Comment by srirambv** [comment] 2018-08-14 16:45
Verified on Ubuntu 18 x64 using 
* 0.23.80 53a429f
* Muon	8.0.8
* libchromiumcontent	68.0.3440.84
* Verified the download completes when opening a setup link in a new tab
