### ISSUE TITLE
Scrolling makes back button grow on MacBook Pro

### ISSUE THREAD

**Issue by vaaralav** [brave/browser-laptop#14785] opened 2018-07-19 06:49 UTC
### Description

Scrolling on Mac OS by swiping up/down with two fingers on trackpad makes back button grow.

### Steps to Reproduce

  1. Open any web page that is long enough to scroll
  2. Scroll up or down with the trackpad

**Actual result:**

Back button in the toolbar grows like the swipe gesture was back, not scroll. If the back button is in disabled state it will dim instead of growing.

![jul-19-2018 09-21-26](https://user-images.githubusercontent.com/8571541/42925796-060e8054-8b38-11e8-9bb0-c247c4dc2efb.gif)

**Expected result:**
The back button shouldn't react to scroll.

**Reproduces how often:**

Every tab.

### Brave Version

**about:brave info:**

 
Brave: 0.23.39 
V8: 6.7.288.46 
rev: 3ee14b026f09d7d71c1985b4a9c9a11d78ab8f49 
Muon: 7.1.6 
OS Release: 17.6.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Comment by Alino** [comment] 2018-07-22 10:33
it's not a bug it's a feature 😆 
For me there is a bug on my mac pro early 2015, that I don't have this feature.

**Comment by bsclifton** [comment] 2018-07-22 16:16
@vaaralav @odelr005 can you try editing the sensitivity under `Swipe Navigation Distance`? Maybe turn this up a little bit (move to the right)
![screen shot 2018-07-22 at 9 15 24 am](https://user-images.githubusercontent.com/4733304/43047686-f1ad22c8-8d8f-11e8-9877-f66449eb58c1.png)

**Comment by GalacticSun** [comment] 2018-07-22 19:56
I'm also having this problem.  The "Swipe Navigation Distance" helps a little bit, but not 100%.  The fact that vertical scrolling affects the size of the Forward / Back buttons is bad.  Users shouldn't have to manage their vertical scrolling dexterity to ensure the browser doesn't suddenly jump Back / Forward ;)  I love Brave, though, keep up the great work, and thanks!

**Comment by bsclifton** [comment] 2018-07-22 20:06
cc: @petemill

**Comment by odelr005** [comment] 2018-07-23 22:16
Also when viewing pages that require vertical scrolling, if the gesture is done to scroll vertically, the browser will easily go forwards or backwards a page. The "Swipe Navigation Distance" does not seem to help much unless you swipe extremely fast. The faster you swipe the less the issue is noticed.

**Comment by joelwass** [comment] 2018-07-24 14:13
It seems to only affect my browser once I begin swiping left or right. If i exclusively swipe vertically, it doesn't affect the size of the back button, but once I've per se "broken the seal" of swiping even slightly horizontally, the button reacts to vertical swiping.

**Comment by TeoMorabito** [comment] 2018-07-29 09:13
When I scroll horizontally on a website such as a calendar, scrolling sideways makes the page go back of forward in history.

If content is scrollable horizontally, nav scroll should be disabled, or at least a setting to disable it.

Using a retina macbook pro

**Comment by joelwass** [comment] 2018-07-30 12:42
Hey @TeoMorabito , that sounds like a separate issue to me. Do you want to open another issue for it and tag me in it and I can take a look? I'm assuming that would mean just disabling nav scroll when the content on the page is horizontally scrollable.

**Comment by amclin** [comment] 2018-08-05 19:54
I can replicate this zooming of the back button consistently. Pushing the "Swipe Navigation Distance" bar to the max has no effect other than to make the zoom animation a little jerky and not always go to maximum size.

**Comment by TeoMorabito** [comment] 2018-08-23 09:42
Going into System Preference > Trackpad
and unchecking swipe between pages disables the swipe right and left gesture and thus disables the navigation swipe in brave.
(I am not able to swipe horizontally on a calendar so needed a way to disable it so it wouldn't go back and forth in the history)

**Comment by darkdh** [comment] 2018-08-30 00:34
fixed by https://github.com/brave/browser-laptop/commit/69851d114a327b3bfefab0ab7ba9649b7b5a4b1a

**Closed by darkdh** 2018-08-30 00:34 UTC
Labels: bug, needs-info

**Comment by LaurenWags** [comment] 2018-09-04 13:58
Verified with macOS 10.12.6 using
* 0.23.203 16c2c19
* Muon 8.1.2
* libchromiumcontent 69.0.3497.72
