### ISSUE TITLE
 Regression : bookmarks toolbar expansion menus are running past the right edge of the window

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8891] opened 2017-05-16 18:57 UTC

**Comment by bsclifton** [comment] 2017-05-16 19:05
Closing as dupe of https://github.com/brave/browser-laptop/issues/8891

**Comment by alexwykoff** [comment] 2017-05-16 19:06
dupe of https://github.com/brave/browser-laptop/issues/4745

**Closed by bsclifton** 2017-05-16 19:05 UTC
