### ISSUE TITLE
Favicons on brave payments list are not displayed until switching the tab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4178] opened 2016-09-22 06:45 UTC
### Test Plan
- Create a back up of your brave folder
- Delete ledger-* files in the folder and open the browser, create the wallet
- Go to https://clifton.io
- Wait for a moment until the site is listed on the brave payment list
- Open about:preferences#payments, favicon should be there

## Original issue description
Favicons on brave payments list are not displayed until switching the tab.

**Expected behavior:** They should appear before switching the tab
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.2 RC1
- Steps to reproduce:
  1. Create a back up of your brave folder
  2. Delete `ledger-*` files in the folder and open the browser, create the wallet
  3. Go to https://clifton.io
  4. Wait for a moment until the site is listed on the brave payment list
  5. Open about:preferences#payments -> **no favicon**
  6. Restart the browser
  7. Switch the tab to Brian's page
  8. Go back to about:preferences#payments -> **favicon appears**

If I disabled payments and enabling them again, the favicons appeared.
- Any related issues: #3684

**Comment by alexwykoff** [comment] 2016-10-28 00:13
Just repro'd in 0.12.7 RC1

**Comment by NejcZdovc** [comment] 2017-03-12 20:01
Just tried this on latest master 3ad0f41 and I can't reproduce this problem with a fresh profile

**Comment by mrose17** [comment] 2017-03-12 22:52
@NejcZdovc - can you also try with a profile that isn't "fresh" ? thanks!

**Comment by bsclifton** [comment] 2017-03-14 08:53
Moving to 0.13.7

**Closed** 2017-04-02 19:43 UTC
Labels: bug, feature/ledger, misc/favicon, QA/steps-specified, release-notes/include
