### ISSUE TITLE
Multiple screens , brave browser out of scope of the screen 

### ISSUE THREAD

**Issue by mohanidragel** [brave/browser-laptop#9371] opened 2017-06-09 22:07 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
I have 3 monitors, one laptop, 2 x dell 19 inches. I when closing browser and relaunching or restarting the machine, the browser sometimes opens out of the scope of the screen and can't move it back. 
The workaround I use is to change the resolution of the screen to bring the window bar back in scope and then reset or alt space on the task bar menu to move it. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 

- Brave Version (revision SHA):
0.16.6

- Steps to reproduce:
    1. Open browser on multiple screens 
    2. Use multiple tabs on the browser window 
    3. Restart the machine / close the browser and relaunch
    
- Actual result:
Expected the browser to remember the last state that I had open i.e. full screen etc. 

- Expected result:
Brave relaunches either mimimized with the window bar out of scope or completely out of the screen alignment. 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Alternatively, connect it on different screens. In my case I have 3 screens 2 dells and a laptop screen. Open brave on an external screen. Disconnect laptop from the other screens and try to launch brave on the laptop with the screens connected. 

- Is this an issue in the currently released version?
I'm on the latest production version. 

- Can this issue be consistently reproduced?
Yes

**Comment by srirambv** [comment] 2017-06-20 11:30
+2 from community 
https://community.brave.com/t/multiple-monitor-support/2584/

**Comment by srirambv** [comment] 2017-06-20 13:30
+1 from community https://community.brave.com/t/multiple-display-issue/767/2

**Comment by onuromer** [comment] 2017-06-20 19:58
Replying for the community post: https://community.brave.com/t/multiple-monitor-support/2584/

I've attached the screencast. (Sorry it is a wide video to properly show both screens to describe the situation)

I've compared the behaviour side by side with firefox as well to show you the difference. 
On screencast you will see my secondary monitor on left and primary monitor on right. 
As appeared in order:

Working Scenario
- I launched Brave and Firefox
- Moved both windows to secondary screen
- By pressing Win + P, I've changed screen projection to PC Screen Only
- Both windows successfully relocates to primary monitor

Problem Scenario:
- I've moved both windows to secondary screen again
- Now I've plugged off the HDMI cable
- Now Firefox relocates to primary monitor but not Brave (Nevermind the left side after pluging-off HDMI cable, because of the screen-recording software it shows the last image available)
- Look at the glare effect when i try to maximize the Brave's window, it still thinks that a monitor is still attached.

I hope i've managed to show you the situation.

Thanks
Onur

[2017-06-20_22-29-30.zip](https://github.com/brave/browser-laptop/files/1089461/2017-06-20_22-29-30.zip)

**Comment by abdupattoh** [comment] 2017-06-23 01:22
This is quite annoying - Win 10.  I use my notebook computer back and forth from work, and can't find my open windows when I come home, without using ALT-Space to move them back onto the primary display.

**Comment by srirambv** [comment] 2017-06-29 08:32
Also similar to https://github.com/brave/browser-laptop/issues/2438

**Comment by srirambv** [comment] 2017-06-29 08:32
+1 from https://community.brave.com/t/brave-not-remembering-screen-positioning/4369

**Comment by czebiniak** [comment] 2017-08-11 21:17
+1 I have the same issue

**Comment by bsclifton** [comment] 2017-08-21 06:26
I believe this is a duplicate of https://github.com/brave/browser-laptop/issues/3558

**Comment by princevince** [comment] 2017-10-12 10:17
What about this bug? Is it going to be resolved? I hoped somebody would've picked it up by now. It's really annoying to be unable to use your browser because it is being displayed on a detached screen. I always have to escape to another browser when this happens until I connect my second monitor again. I once tried deleting the Brave user data to resolve this issue. However this is no solution because I lose all of my settings every time I do this.

**Comment by NejcZdovc** [comment] 2017-10-12 10:26
this should be fixed with #10458 in version 0.20

**Closed by NejcZdovc** 2017-10-12 10:26 UTC
Labels: bug, settings

**Comment by srirambv** [comment] 2018-01-09 12:32
Verified on Windows. Browser window opened in previous size but on the main screen
