### ISSUE TITLE
Dropdown menu in economist.com stops working

### ISSUE THREAD

**Issue by Quinn1415** [brave/browser-laptop#5139] opened 2016-10-26 00:35 UTC
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

Click on one of the dropdown menu on http://www.economist.com/ no longer works. I think this also happens to the Google Chrome when touch is enabled on a touch screen, disabling it will make it work, except here with Brave, no way for me to set it, plus I am running it on a non-touch screen Windows 10 laptop

**Expected behavior:**

Dropdown menu should show up
- Platform (Win7, 8, 10? macOS? Linux distro?):

Windows 10 professional, current Anniversary Update
- Brave Version:

Latest dev version
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by jonathansampson** [comment] 2016-10-28 02:38
The drop-down menu (sub-menu revealed while hovering navigational items) is presently broken in Brave, Chrome, and Firefox. It does, however, work in Microsoft Edge.

![economist](https://cloud.githubusercontent.com/assets/815158/19792119/4fdc50f0-9c7c-11e6-94bd-b4a2594ce9d7.gif)

The `:hover` state is defined in http://cdn.static-economist.com/sites/default/files/css/css_6e9392aabd3c4f727a145049659314f6.css.

**Comment by jonathansampson** [comment] 2016-10-28 04:30
[Outreach has been made](https://twitter.com/BraveSampson/status/791858470182019072) to a Platform Engineer at The Economist.

**Comment by JonasEconomist** [comment] 2016-10-28 12:48
@jonathansampson thanks for reaching out. I'm unable to replicate this. Could you provide the steps to recreate this issue? Then I'll pass it along to the appropriate channels.

**Comment by Quinn1415** [comment] 2016-10-28 17:13
On the Brave version 0.12.6, and a PC desktop (Windows 10) with no touch
screen, go to http://www.economist.com/, and hover the mouse over the
dropdown menus (World Politics, Business & Finance, etc.), you will see
submenu popped up if it works properly.

**Comment by jonathansampson** [comment] 2016-10-28 19:07
@JonasEconomist @Quinn1415 I repro in Blink and Gecko browsers.

![economist-comparison](https://cloud.githubusercontent.com/assets/815158/19818861/9af23d5e-9d06-11e6-85c2-278f1f5a89ed.gif)

**Comment by Quinn1415** [comment] 2016-11-03 04:16
Brave 0.12.7 works now.
Many thanks.

**Comment by bbondy** [comment] 2016-11-04 18:44
@jonathansampson can this be closed?

**Comment by Quinn1415** [comment] 2016-11-04 19:36
Yes, please.

**Comment by jonathansampson** [comment] 2016-11-04 20:45
@bbondy I still repro the issue, in 0.12.8.

@Quinn1415 are you still using the same device as before?

**Comment by Quinn1415** [comment] 2016-11-04 20:47
Yes, I am, and somehow it works for me now.

Thanks,
Quang

**Comment by jonathansampson** [comment] 2016-11-04 20:54
@Quinn1415 Can you run the following from Brave's Developer Tools? To access them, press F12 on your keyboard, and then select the _Console_ tab. Paste, and press enter:

    document.documentElement.classList.contains("no-touch")

On Chrome and Brave, this returns `false` for me.

**Comment by Quinn1415** [comment] 2016-11-04 21:08
I am now using a touch screen latop.

no pubinfo available
document.documentElement.classList.contains("no-touch")
false

I will try my desktop later tonight.

Thanks,
Quinn

**Comment by Quinn1415** [comment] 2016-11-04 21:11
Nope, not on the touch screen laptop. As said I will try on the non-touch
PC again tonight and confirm.

Thanks,
Quinn

**Comment by jonathansampson** [comment] 2016-11-04 21:15
@Quinn1415 Sorry, I'm confused here. Let's take a step back and address the _expectations_.

I expect, on my touch-enabled/mouse-enabled Surface Book, to see the drop-down menus when my mouse passes over the navigation: **I do not see this**.

The only browser that meets my expectations is Microsoft Edge. Google Chrome, Brave, and Firefox all require me to physically reach up, and tap my screen to reveal the sub-menu. This feels incorrect, though it may be the _intended behavior_ (we'll need @JonasEconomist to confirm/deny).

**Comment by Quinn1415** [comment] 2016-11-04 21:28
The correct behavior (I believe), and that behavior has been around for a
long time on Chrome, Brave is that:

1) On touch screen, nothing happens when a mouse cursor is hovering on the
drop down menu, except we disable the touch events.

2) On non-touch screen, the drop down menu should show it sub-menus when a
mouse hovering on it.

Thanks,
Quinn

**Comment by jonathansampson** [comment] 2016-11-04 21:59
@Quinn1415 So I _should not_ expect to see a dropdown menu during mouse-over on my Surface Book? If that is the case, then this issue appears to be resolved. I was under the assumption that we wanted the drop-down menu to be visible when the user is using her mouse (regardless if her device is touch-enabled).

**Comment by Quinn1415** [comment] 2016-11-04 23:03
it can be resolved, unless you want it behave as Egde, which I think is better & more user friendly.
		_____________________________

**Comment by jonathansampson** [comment] 2016-11-04 23:21
@Quinn1415 It sounds like you and @JonasEconomist are describing the current behavior as _by design_ and _as expected_. As such, I'll close this issue down.

**Closed by jonathansampson** 2016-11-04 23:21 UTC
Labels: confirmed, outreach, reduced, webcompat

**Comment by Quinn1415** [comment] 2016-11-04 23:28
Thanks Jon, much appreciated.
Btw, Brave is getting better and better, and I am using it more and more in
preference to Chrome.

Thanks,
Quinn
