### ISSUE TITLE
Browser background process continues to run after closing the browser window

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8629] opened 2017-05-02 17:57 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Browser background process continues to run after closing the browser window 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Clean install 0.15.2 Preview 2
    2. Wait for the browser window to show up and open task manager
    3. Close the window, check task manager all process is still running
    4. Open console and try to launch browser
    5. Shows error as process is locked
    6. Kill all process and launch from console, browser starts
    
- Actual result:
Browser background process continues to run after closing the browser window

- Expected result:
Should close all background process once window is closed

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![p2](https://cloud.githubusercontent.com/assets/17010094/25631847/897f6c86-2f69-11e7-868e-c2239cfa4e07.gif)

- Any related issues:

**Comment by luixxiul** [comment] 2017-05-03 07:56
This can be reproduced on debian

**Comment by bsclifton** [comment] 2017-05-03 08:35
@srirambv @luixxiul this should have always been a bug.  Can you please confirm it happens on older releases? If so, it's a bad bug, but I don't think it's a blocker

**Comment by luixxiul** [comment] 2017-05-03 08:53
the thing is you cannot restart the browser on debian *unless you manually kill the process*.

**Comment by srirambv** [comment] 2017-05-03 11:17
@bsclifton  I verified it from 0.13.3 onward, its not an issue. Its only in this build. It works fine in the preview 1 build which was removed.

**Comment by bsclifton** [comment] 2017-05-03 15:51
@srirambv this is great info- based on that, this is indeed a blocker 😄

**Comment by luixxiul** [comment] 2017-05-06 15:00
This sould be a blocker for 0.15.3, not 0.15.4 right?

**Comment by luixxiul** [comment] 2017-05-06 15:01
This remains an issue on the latest preview on Debian.

**Comment by luixxiul** [comment] 2017-05-07 07:08
Findings:

1 - Close the window by closing all of the tabs -> process remains
2 - Close via main menu -> process closed

So I'm wondering if it is related with the tab close handling. Also might be related with: #8740

**Comment by bsclifton** [comment] 2017-05-07 07:10
Confirmed- this is a really bad one ☹️

**Comment by bsclifton** [comment] 2017-05-10 20:41
I've confirmed this is *not* fixed with https://github.com/brave/browser-laptop/pull/8782.  

However, I did narrow down the root cause. It's happening when you close the window using the X button on the top right, versus using Ctrl + Q (or picking from menu)

**Closed** 2017-05-11 17:21 UTC
Labels: bug, release/blocking
