### ISSUE TITLE
Crash every time I tried to upload file

### ISSUE THREAD

**Issue by vikingkarwur** [brave/browser-laptop#784] opened 2016-02-16 10:55 UTC
When using Brave for Mac, it Crash every time I tried to upload file.

**Comment by weems** [comment] 2016-02-16 14:58
What website does this happen on?

**Comment by vikingkarwur** [comment] 2016-02-16 15:07
- last time crashed : ultrapress.com
Before that it happen' when I tried to upload photos in facebook

**Comment by stephanebachelier** [comment] 2016-02-16 19:46
I confirm the same issue on brave for Mac.
I was uploading a zip on ghost.io to change the theme. Each time I've tried Brave crashed.

**Comment by diracdeltas** [comment] 2016-02-16 20:50
What versions are you on? I think I previously saw the crash on fb photo upload but not when I tried just now.

**Comment by diracdeltas** [comment] 2016-02-16 20:54
I'm guessing this is a duplicate of https://github.com/brave/browser-laptop/issues/475. If you upgrade to the latest electron-prebuilt (`rm -r ~/.electron`, `rm -r node_modules/electron-prebuilt`, `npm install`), it should be fixed.

**Comment by bbondy** [comment] 2016-02-21 20:36
Closing since no response for 5 days and likely a dupe.

**Closed by bbondy** 2016-02-21 20:36 UTC
Labels: duplicate
