### ISSUE TITLE
Keyboard shortcuts don't work when the keyboard is not English

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11908] opened 2017-11-11 18:39 UTC
### Description

There is a report that keyboard shortcuts on Cyrillic Keyboard do not work at all.

https://community.brave.com/t/not-working-any-shortcuts-on-cyrillic-keyboard-on-macosx/10604?u=suguru
> In Brave not working any shortcuts on Cyrillic Keyboard on MacOSX. Always need to switch to English Keyboard.

### Steps to Reproduce

  1. Set up a Cyrillic keyboard
  2. Try keyboard shortcuts
  3.

**Actual result:**

They do not work at all.

**Expected result:**

They should work.

**Reproduces how often:**

### Brave Version

**about:brave info:**

Brave	0.19.88
rev	c29eca6
Muon	4.5.15
libchromiumcontent	62.0.3202.89
V8	6.2.414.40
Node.js	7.9.0
Update Channel	Release
OS Platform	macOS
OS Release	15.6.0
OS Architecture	x64

**Reproducible on current live release:**

Yes.

**Comment by luixxiul** [comment] 2017-11-11 18:41
There is another report here: https://community.brave.com/t/shortcuts-doesnt-work-when-korean-keyboard-is-selected/9965

> I’m macOS user. In macOS, for example, cmd + W is supposed to close window or tab. When English keyboard is selected, it works fine. When Korean keyboard is selected, however, it does not work. Not just cmd + W, but any other shortcuts.
> 
> Curiously, it did work before updating to the latest version of Brave. It started to not work after updating.

The user says the keyboard shortcuts have worked properly until updating to 0.19.70.

**Comment by eljuno** [comment] 2017-12-10 21:02
+1 from community https://community.brave.com/t/hotkeys-dont-work/11928?u=eljuno

>Hello. I use OS X version. And I have some painful bug. My OS have 2 keyboard language. When i use Russian language in Brave then all my hotkeys (cmd+c, cmd+v, cmd+w, …) stop working.

**Comment by eljuno** [comment] 2017-12-16 18:51
+1 from community https://community.brave.com/t/c-v-while-on-cyrillic-keyboard/12264?u=eljuno

**Comment by eljuno** [comment] 2018-02-02 20:34
+1 from community https://community.brave.com/t/cmd-key-stops-working-after-changing-keyboard-layout-to-cyrrilic/15284?u=eljuno

**Comment by jknnr** [comment] 2018-04-03 11:03
I have to stop using Brave until this issue is solved. Very annoying.

**Comment by alekseenko** [comment] 2018-04-23 14:46
+1

**Comment by c0s** [comment] 2018-06-02 07:18
Same here - version 0.22.721 doesn't work with Cyrillic layout on Mac.
Good bye, Brave - it is a such pain in the arse!

**Comment by bsclifton** [comment] 2018-06-05 04:14
Lots of +1s from https://github.com/brave/browser-laptop/issues/13902

**Comment by bsclifton** [comment] 2018-06-05 04:15
Can folks try this in Chrome / Chromium and let us know if it works as expected? We are shifting over to a Chromium based UI (Brave Core) sometime soon and I expect this will completely resolve the issue. I don't think we'll be able to address before then

**Comment by bsclifton** [comment] 2018-06-05 04:28
Even more +1s from https://github.com/brave/browser-laptop/issues/13559

**Comment by sliday** [comment] 2018-06-17 22:41
The issue is back in :(

Brave | 0.22.810
-- | --
V8 | 6.7.288.43
rev | 8f30eeb
Muon | 7.0.6
OS Release | 18.0.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.71

**Comment by Brave-Matt** [comment] 2018-07-12 19:40
+1 from Community: https://community.brave.com/t/keyboard-shortcuts-dont-work-when-keyboard-layout-is-set-to-bulgarian-phonetic/27558

**Comment by Kouprin** [comment] 2018-07-25 12:05
same problem
it makes Brave almost useless - it takes a lot of time to change keyboard layout, then to use shortcut, then to change it back

**Comment by backmeupplz** [comment] 2018-07-30 06:08
+ very annoying. Thinking about switching browsers now.

**Comment by eljuno** [comment] 2018-08-20 18:40
+1 from community https://community.brave.com/t/use-brave-shortcut-keys-in-multi-language-systems/30352?u=eljuno

**Comment by arminoza** [comment] 2018-09-06 19:09
v0.23.105 and still not fixed.

**Comment by bsclifton** [comment] 2018-09-07 05:34
@arminoza @backmeupplz @Kouprin @sliday @c0s @alekseenko @jknnr @g-ki @lonormaly @nyngwang @DKunin 

We just released our new developer channel build today which you can try here:
https://brave.com/download-dev

We've been shifting our dev focus from the existing code-base (forked from Electron) over to this new code-base (`brave-core` - which forks the Chromium UI). If you give it a shot, this issue should be resolved 😄 👍  This build is experimental at the moment; features like payments (now called Brave Rewards) and sync are not fully functional yet. But you should be able to import your bookmarks, cookies, history, etc without any problems

As we won't be fixing this issue with our current code-base (`browser-laptop`), I'm going to close this issue

**Closed by bsclifton** 2018-09-07 05:34 UTC
Labels: 0.19.x, bug, feature/keyboard-shortcuts, fixed-with-brave-core, l10n

**Comment by DKunin** [comment] 2018-09-07 05:58
Thanks for the heads-up! I'm gonna give it a go!
