### ISSUE TITLE
brave wont start centos

### ISSUE THREAD

**Issue by Kaiz3rTool** [brave/browser-laptop#15329] opened 2018-12-08 08:19 UTC
Brave wont start on centos 7.5
try to launch it on terminal result 
`[25896:25896:1208/091621.639239:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Trace/breakpoint trap (core dumped)
`

Brave version is the one available on the repo today

**Comment by bsclifton** [comment] 2019-01-03 19:55
The instructions should have been fixed with https://github.com/brave/brave-browser/pull/1905

Since your problem is with the new version of the browser (and this repo is for the old version of Brave), I'm going to close this.  But I'd encourage searching our issue log because there have been a lot of folks experiencing `--no-sandbox` error (especially on Archlinux)

I think the root cause may be that your kernel is too old. You may need to launch with `--no-sandbox` as a work-around

**Closed by bsclifton** 2019-01-03 19:55 UTC
