### ISSUE TITLE
Brave forgets settings after session.

### ISSUE THREAD

**Issue by D0J0P** [brave/browser-laptop#3224] opened 2016-08-17 06:37 UTC
I opened a new session, and Brave forgot the settings I set in the last session, and had to do this a couple times. Settings like disabling tab preview by hovering, blocking ads, and smooth scrolling. I had to set these settings back in the new session, and did this a few times. 

Other things were also forgotten, like Facebook allowing fullscreen videos and notifications, and Gmail using it's own protocols, etc.

**Comment by gulkily** [comment] 2016-08-17 09:29
Trying to reproduce... What Brave version and OS are you using?

Do you happen to remember what you had any of the settings set to?

**Comment by D0J0P** [comment] 2016-08-17 15:36
I'm using Brave version 0.11.5 on Windows 10 x64. The only settings I have are the ones I mentioned above.

**Comment by gulkily** [comment] 2016-08-17 16:47
Could you please walk me through the exact steps you take in order to help reproduce this issue?

**Comment by D0J0P** [comment] 2016-08-17 17:12
Well, I set up the current settings I had. After quitting Brave and coming back to it later that day, my settings were gone, and I had to set them back up again. It could be because there was an update in the middle of the day, during my first session, but that's all I can think of.

**Comment by gulkily** [comment] 2016-08-17 21:52
Oh, the update might have something to do with it!

Since then, have you tried to reproduce the issue again?

**Comment by D0J0P** [comment] 2016-08-17 21:55
Not since, so I think it could be okay now. Maybe it's the update that messes it up, which would be a problem in itself. One thing with the prompts that I don't love is that it asks me if I want to go fullscreen on a video in every website possible, as opposed to just universally.

**Comment by gulkily** [comment] 2016-08-17 21:57
That is a separate issue, but I believe that is a security precaution.

Thank you for the additional information you provided for this issue.

**Comment by diracdeltas** [comment] 2016-08-17 22:57
That is definitely a bug; settings should not be lost after update

**Comment by gulkily** [comment] 2016-08-17 23:14
Hypothetical steps to reproduce:

1. Start a previous version of Brave.
2. Change the Ad-Blocking setting (or another setting) in the Preferences.
3. Wait for the new-version-available prompt to appear
4. Follow the prompts to restart the browser
5. Open the Preferences and look at the setting changed in step 2

**Comment by sanecito** [comment] 2016-08-18 17:06
I came here to report that my settings were wiped as well with the new update, but it looks like it was already reported. Specifically I had send Do Not Track header enabled as well as block all ads. Running Windows 8.1 x64.

**Comment by luixxiul** [comment] 2017-11-02 12:31
I'm going to close this issue in favor of this topic on our community 😄 

https://community.brave.com/t/discussion-https-github-com-brave-browser-laptop-issues-3224/10036

Let's keep discussion on this issue there to find steps to reproduce it 👍 Thanks!

**Closed by luixxiul** 2017-11-02 12:31 UTC
Labels: bug, needs-info
