### ISSUE TITLE
creating a wallet sometimes stalls if the backend has a hiccup/timeouts

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11591] opened 2017-10-18 06:33 UTC
### Description

When creating a wallet with a new profile and the backend has a hiccup or a timeout, users will get stuck in the "Creating Wallet" phase and at times, the process will never finish/complete. I've seen this personally happen a few times where I tried creating a new wallet with a new profile and ended up being stuck on "Creating Wallet". I waited for about 3 hours without the wallet being created.

Brave should do a better job re-pinging the server and retrying rather than getting stuck on "Creating Wallet".

### Steps to Reproduce

It's really hard to get STR, but the issue usually happens when the server is having problems and someone tries to create a wallet. As mentioned above, Brave should do a better job re-pinging the server and attempting to create another wallet/fixing the issue that is preventing the wallet from being created.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Usually reproducible when receiving errors such as:

```
Error: HTTP response 503 for GET /v2/registrar/persona
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.52\resources\app.asar\app\browser\api\ledger.js:1491:9)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.52\resources\app.asar\js\lib\request.js:55:5)
```

### Brave Version

**about:brave info:**

> Brave: 0.19.53 - Reproducible
> rev: e09025bf61debc46c03459def2501b3367f182d7 
> Muon: 4.4.29 
> libchromiumcontent: 61.0.3163.100 

**Reproducible on current live release:**

> Brave: 0.19.48 - Reproducible
> rev: de939f6dcd1647f43de544b22dfdd103585b4ec2 
> Muon: 4.4.28 
> libchromiumcontent: 61.0.3163.10

**Comment by srirambv** [comment] 2017-10-27 19:46
Reopening and moving to hotfix3 as its not completely resolved and still occurring, but not as often as before

cc: @kjozwiak @LaurenWags

**Comment by bbondy** [comment] 2017-11-01 02:57
moving to hotfix 4

**Comment by bsclifton** [comment] 2017-11-07 18:36
Duplicate of https://github.com/brave/browser-laptop/issues/11590

**Closed by bsclifton** 2017-11-07 18:36 UTC
Labels: bug, feature/ledger, needs-owner ♞
