### ISSUE TITLE
Brave Close button shows hover state when not hovered

### ISSUE THREAD

**Issue by ericlaw1979** [brave/browser-laptop#7296] opened 2017-02-16 20:07 UTC
- Did you search for similar issues before submitting this one? Yup.

- Describe the issue you encountered: Hover the red-X in Windows Vista or later. Fling mouse upward. Note hover remains.

- Platform: Windows 6.0+

- Brave Version (revision SHA): Brave	0.13.4 rev	71d8ffc

- Steps to reproduce:
    1. Hover the red-X in Windows Vista or later.
    2.  Fling mouse upward so it exits the [x] without touching anything else
    
- Actual result: [x] still shows hover

- Expected result: Hover goes away on mouse exit.

- Will the steps above reproduce in a fresh profile?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/4192774/23038850/2080d240-f451-11e6-9851-81d74242054d.png)

- Any related issues:
I fixed this bug in Chrome back in v54. https://chromium.googlesource.com/chromium/src/+/7af2fc83ecab219d9d2902db766ab0d2ba4dabf1

**Comment by bsclifton** [comment] 2017-02-16 21:33
@ericlaw1979 I believe this is the same bug as https://github.com/brave/browser-laptop/issues/4549 (if so, we can close it and track here)

This is interesting for sure- at least it may mean I did a good job 😄  For Windows, I was unable to get the behavior we wanted with raw Win32 calls (I tried [with a demo which I have here](https://github.com/bsclifton/BrowserWindowStyles)), so I ended up custom rendering the menu and caption buttons.  More details here:
https://github.com/brave/browser-laptop/wiki/Custom-titlebar-and-menu-(Windows-only)

I'd love to go back and get this working properly in the Muon level (our fork of Electron). In the meantime, I don't think this would be terribly hard to fix (just a matter of tying into the right event handlers)

**Comment by ericlaw1979** [comment] 2017-02-17 01:15
Sigh, yes, this is a dupe. I'm senile it seems.

**Comment by lucaszanella** [comment] 2017-02-18 02:39
Don't know if it's the same thing but in my brave (ubuntu) the hover icon is a big yellow box, like much bigger than a pointer.
![photo_2017-02-18_00-39-01](https://cloud.githubusercontent.com/assets/6632321/23089602/ad280246-f572-11e6-8d92-c1068b83cb23.jpg)

**Comment by luixxiul** [comment] 2017-02-19 16:54
@lucaszanella I think it's not the same issue. Please open a new issue if you can confirm it appears only on Brave, neither Chrome nor Firefox, thanks.

**Comment by bsclifton** [comment] 2017-02-22 16:30
@lucaszanella yup- definitely a different issue. I've never seen that before... you might try launching Brave with some options which we've documented (discovered when troubleshooting Ubuntu actually).

Please see https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page (I would recommend trying the `--ignore-gpu-blacklist` option)

**Comment by luixxiul** [comment] 2017-05-29 09:50
Was this issue fixed?

**Comment by bsclifton** [comment] 2017-05-29 18:59
@luixxiul it's very possible that it is fixed w/ the updates I pulled in for fixing the hitbox.  Are you able to reproduce? cc: @srirambv

**Comment by ericlaw1979** [comment] 2017-05-30 21:08
This appears to be fixed as of 
Name	Version
Brave	0.15.2.

**Closed** 2017-05-30 21:09 UTC
Labels: bug, feature/titlebar, info-needed, OS/Windows

**Comment by ericlaw1979** [comment] 2017-05-30 21:16
The fix is here: 

https://github.com/brave/browser-android-tabs/blob/master/ui/views/win/hwnd_message_handler.cc
case WM_NCMOUSELEAVE: {
      // If the DWM is rendering the window controls, we need to give the DWM's
      // default window procedure the chance to repaint the window border icons
      if (HasSystemFrame())
        handled = DwmDefWindowProc(hwnd(), WM_NCMOUSELEAVE, 0, 0, NULL) != 0;
      break;

I don't understand why this is under "browser-android-tabs" but I don't understand Brave's code organization at all.

**Comment by bsclifton** [comment] 2017-05-31 15:52
@ericlaw1979 that is the android version of our browser

Likely this was fixed by us updating the way we process our builds 😄  We have a repo https://github.com/brave/browser-laptop-bootstrap which will fetch the full Chromium source code and then also get Muon (our fork of electron) and browser-laptop (this code)

Before (~Brave version 0.12.15 and earlier) we had a compiled version of "libchromiumcontent", which had a subset of the Chromium code.  Since we are now updated to grab all of the Chromium source code directly (which isn't stored in GitHub, since we just fetch from the actual Chromium repo), I think we're good 😄 

@ericlaw1979 for informational purposes, if you wanted to see how it worked, you can try out the steps here: https://github.com/brave/browser-laptop-bootstrap/wiki
