### ISSUE TITLE
Cannot view directory on local drive

### ISSUE THREAD

**Issue by griswolf** [brave/browser-laptop#3095] opened 2016-08-10 20:44 UTC
I used two techniques to try to view a directory
1: I tried the menu File | Open File (choose a directory). That fails by insisting that I choose a file within the directory. This is the same behavior I see with other browsers, so okay.

2: I tried typing into the url bar. E.g. file:///Users/griswolf/Desktop. This gives a view of the Desktop directory with Chrome and Firefox, but nothing with Brave.

I expect to see a directory view in some format

Using Mac OS 10.9.5
- Brave Version: 0.11.4;  libchromiumcontent: 52.0.2743.116
- Steps to reproduce: See problem description
- Screenshot if needed:
  <img width="632" alt="brave-desktop" src="https://cloud.githubusercontent.com/assets/3092067/17570164/220c2326-5f00-11e6-936e-cdda9582ec04.png">
  <img width="498" alt="chrome-desktop" src="https://cloud.githubusercontent.com/assets/3092067/17570165/220c4e3c-5f00-11e6-869d-372f41187050.png">
  <img width="802" alt="firefox-desktop" src="https://cloud.githubusercontent.com/assets/3092067/17570166/22138c92-5f00-11e6-8324-ce5196d0f54c.png">

**Comment by lucidNTR** [comment] 2016-10-04 21:12
im happy to implement this if more people want it. just +1 here if you like this feature

**Comment by bsclifton** [comment] 2018-08-20 07:03
This is a duplicate of https://github.com/brave/browser-laptop/issues/1615

**Closed by bsclifton** 2018-08-20 07:03 UTC
Labels: duplicate, suggestion
