### ISSUE TITLE
Copy image via right mouse button has stopped working

### ISSUE THREAD

**Issue by crysman** [brave/browser-laptop#13122] opened 2018-02-13 11:21 UTC
I am unable to copy image into clipboard via right mouse button - nothing happens, clipboard does not cointain the image.

For example here:
https://cdn.pixabay.com/photo/2016/04/22/15/30/email-1345971_960_720.png

Using Xubuntu 17.10 and Brave 0.20.30 V8	6.4.388.40 rev	8b78402

**Comment by NejcZdovc** [comment] 2018-02-13 11:26
I think this is dupe of #7388, and resolved in #13108

**Closed by NejcZdovc** 2018-02-13 11:26 UTC
