### ISSUE TITLE
Captcha doesn't work

### ISSUE THREAD

**Issue by givanse** [brave/browser-laptop#15276] opened 2018-10-08 19:32 UTC
### Description
Captcha checkboxes do not work when clicked on. Nothing happens when you click it.

### Steps to Reproduce

  1. Go to any website that has a Captcha
  2. Click the Captcha checkbox

**Actual result:**

Nothing happens, as if you hadn't click.

**Expected result:**

Captcha images popup so you proof you are not a robot from the future.

**Reproduces how often:**
100% repro

### Brave Version

```
Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 10.0.15063 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100
```

**Reproducible on current live release:**
yes

**Comment by eljuno** [comment] 2018-10-08 19:38
Dis you have Site isolation enables under Preferences > Security?

Maybe duplicate of https://github.com/brave/browser-laptop/issues/13496

**Comment by givanse** [comment] 2018-10-08 19:40
Ah! Yeah, I do have Strict Site Isolation turned on.

**Closed** 2018-10-09 05:43 UTC
