### ISSUE TITLE
The page is spinning endlessly when going to about:non-existing

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#10495] opened 2017-08-15 10:28 UTC
Brave: 0.18.22 
rev: d850e287ace296e2c62e28ba2979cf172e41cc45 
Muon: 4.3.9 
libchromiumcontent: 60.0.3112.90 
V8: 6.0.286.52 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: macOS 
OS Release: 16.0.0 
OS Architecture: x64

I've found this the bug by making a typo by going to about:preferences (like double s) and expecting the page to load, but instead I ended up with page which I thought is loading so long.

- Steps to reproduce:
    1. Go to: about:preferencess or any other about:non-existing page.
    2. The timer shows the page is loaded, but the tab is spinning endlessly.
    
- Actual result:

The tab is redirected to about:blank and icon is spinning. For example I did mistake and I typed about properties, instead of preferences and I thought the page is just loading.

- Expected result:

The tab can be redirected to about:blank, but the icon shouldn't be spinning to avoid confusion whether it's non-existing page, or it's just loading.

**Comment by luixxiul** [comment] 2017-08-15 12:15
Regression of https://github.com/brave/browser-laptop/issues/8584 ?

**Comment by kenorb** [comment] 2017-08-15 12:27
Related: #9130, #10014

**Comment by luixxiul** [comment] 2017-08-15 12:33
I think this is a duplicate of #10014. @kenorb if you agree with me please close the issue, thanks.

**Closed** 2017-08-15 12:34 UTC
Labels: bug
