### ISSUE TITLE
right click to "open in new tab" should open tab to the right of current tab, not the end of tabs

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1423] opened 2016-04-21 03:09 UTC
Related with #2453

**Comment by eddieduro** [comment] 2016-05-12 00:12
Hey there - I am new to contributing to open source but this seems like it might be in my skill range. Would love to try and tackle this bug!

**Comment by bradleyrichter** [comment] 2016-05-12 01:17
Go for it! I am sure we can get a Brave to help if you get stuck...


Brad

**Comment by eddieduro** [comment] 2016-05-12 15:29
Awesome thanks Brad!

**Comment by mpizza** [comment] 2016-07-16 09:50
Hi, @bradleyrichter I've a quick patch for this issue, could you help to review it? Thanks.

**Comment by bbondy** [comment] 2016-07-16 14:19
Looks like this was previously fixed and due to us having a dupe in the issue tracking it wasn't closed, the earlier dupe of this was closed.

https://github.com/brave/browser-laptop/commit/9db32f039b5504febfb9fcb3eb403ba1643f3281

Let me know if you know of another way to reproduce though.

**Comment by mpizza** [comment] 2016-07-16 15:24
After checking with latest commit, I can't reproduce this issue, so I think this issue should be closed. Thanks.

**Comment by bbondy** [comment] 2016-07-18 03:45
Thanks for checking! Would love your help on another one if you get time! :)

**Closed by bbondy** 2016-07-18 03:45 UTC
Labels: bug, good-first-bug
