### ISSUE TITLE
"This site can’t be reached" when saving .torrent files while "Torrent Viewer" disabled

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13619] opened 2018-03-27 15:42 UTC
### Description

Saving `.torrent` files while `Torrent Viewer` is disabled via `about:preferences#extensions` will produce a `This site can’t be reached` tab page while the `Save as..` prompt is displayed.

Looks like this should have originally been fixed with #8452 but has regressed. 

### Steps to Reproduce

  1. launch 0.22.7 `8bb7e77`
  2. disable torrent viewer via `about:preferences#extensions`
  3. visit https://www.qubes-os.org/downloads/ and click on the `Torrent` download

You'll notice that the 'Save as..` modal will correctly be displayed, but at the same time, you'll receive the `This site can’t be reached` tab.

**Actual result:**

![torrentissue](https://user-images.githubusercontent.com/2602313/37977136-2a558b3c-31b1-11e8-9a1d-a04e953769d3.gif)

**Expected result:**

User should be prompted the `Save as...` modal but shouldn't be receiving the `This site can’t be reached` tab.

**Reproduces how often:**

100% reproducible using the STR mentioned above.

### Brave Version

**about:brave info:**

> Brave: 0.22.7 
> V8: 6.5.254.41 
> rev: 8bb7e77f69bca186429aafda4bc6ba4d82a5de47 
> libchromiumcontent: 65.0.3325.181
> Muon: 5.1.1 
> OS Release: 17.4.0 
> Update Channel: Beta 
> OS Architecture: x64 
> OS Platform: macOS 
> Node.js: 7.9.0 
> Brave Sync: v1.4.2 

**Reproducible on current live release:**

Yes, currently reproducible using `0.21.24` 19c78a1 which is the latest released version.

### Additional Information

* `0.19.147` f1b90a3 - Reproduced
* `0.21.24` 19c78a1 - Reproduced
* `0.22.7` 8bb7e77f69bca186429aafda4bc6ba4d82a5de47 - Reproduced

**Comment by bsclifton** [comment] 2018-03-27 16:30
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/10767

**Closed by bsclifton** 2018-03-27 16:30 UTC
Labels: bug, feature/torrent
