### ISSUE TITLE
Too many redirects on a page with .htaccess

### ISSUE THREAD

**Issue by ansokolov** [brave/browser-laptop#13482] opened 2018-03-16 20:48 UTC
### Description

Too many redirects on a page with .htaccess 

### Steps to Reproduce

Head over to www.ekselsio.com
The url should redirect to ekselsio.com/en/
Brave browser stops loading the page with 'too many redirects'. 

All other pages on website load fine in browser.

To be fair, it redirects from root to subdirectory in which index.php redirects to subdirectory. Nevertheless, the redirects are working on Chrome, Firefox, Edge.

**Expected result:**
Loads a page ekselsio.com/en/

**Reproduces how often:**

Everytime

### Brave Version

Brave: 0.21.19 
V8: 6.5.254.36 
rev: f359e6ed2616360456945bff01bac707895fd651 
Muon: 4.9.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Comment by ansokolov** [comment] 2018-03-16 21:21
Extension of the issue.

When trying to access ekselsio.com/en/services by manually typing a browser treats redirect differently as Chrome, Firefox, Edge. instead of oppening the desired page, it removes '/en/' and looks for ekselsio.com/services , which is not possible. When I go to the same url from a link on a website it loads the page perfectly fine. The issue occurs only, when manually typing in.

**Comment by bsclifton** [comment] 2018-09-21 05:05
Unable to reproduce (since site is down at the moment). However, I suspect this issue is fixed with our developer channel release:
https://brave.com/download-dev

**Closed by bsclifton** 2018-09-21 05:05 UTC
