### ISSUE TITLE
Protocol file:/// doesn't open system directory on browser 

### ISSUE THREAD

**Issue by kumarrishav** [brave/browser-laptop#8704] opened 2017-05-04 21:02 UTC
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
System directory didn't load in browser
- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on macOS (not sure about platform)
- Brave Version (revision SHA):
 Brave	0.15.1
 rev	ea5024d
- Steps to reproduce:
    1. Paste `file:///` on address bar and hit enter. 
    2.
    3.
    
- Actual result:
System directory didn't load
- Expected result:
System directory should be loaded in browser like how it works on chrome and firefox
- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment] 2017-05-05 23:32
Duplicate of #1615.

**Closed by Liunkae** 2017-05-05 23:32 UTC
