### ISSUE TITLE
Wrong image displayed when shields up

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#3196] opened 2016-08-16 00:14 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Navigate to http://www.popyard.com/cgi-mod/newspage.cgi?num=3206580&r=0&v=0&j=0

Notice that http://www.moremorewin.net/imgserver/imgs/2016/08/13/a2f4a819cfd28221b277e7807d8d4edd.jpg resolves to an image that is about 600+ pixels tall

I did notice there is an onload handler:

```
<img src="http://www.moremorewin.net/imgserver/imgs/2016/08/13/a2f4a819cfd28221b277e7807d8d4edd.jpg" border="1" alt="点击图片看原样大小图片" width="200" pagespeed_url_hash="363707710" onload="pagespeed.CriticalImages.checkImageForCriticality(this);">
```

It's possible this code is throwing an error.  I didn't see anything in the console. fingerprinting protection is not on.

I matched the request (including all headers) using Postman and could not reproduce.

**Expected behavior:**
With shields down, a different picture shows.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  macOS, Windows 10
- Brave Version:
  0.11.5
- Steps to reproduce:
  1. Visit http://www.popyard.com/cgi-mod/newspage.cgi?num=3206580&r=0&v=0&j=0
  2. turn shields off
  3. notice that image changed
- Screenshot if needed:
  shows incorrect picture (shields up)
  ![screen shot 2016-08-15 at 5 12 23 pm](https://cloud.githubusercontent.com/assets/4733304/17683865/812aecca-630b-11e6-9fcf-22d44225d05f.png)

correct picture shields down
![screen shot 2016-08-15 at 5 14 27 pm](https://cloud.githubusercontent.com/assets/4733304/17683899/c7813f76-630b-11e6-929c-4ccb6d80d907.png)
- Any related issues:

**Comment by jonathansampson** [comment] 2017-02-27 19:30
Duplicate of #3181

**Closed by jonathansampson** 2017-02-27 19:30 UTC
Labels: webcompat
