### ISSUE TITLE
Tab size change should have transition animation

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7001] opened 2017-02-02 13:48 UTC
### Test plan
https://github.com/brave/browser-laptop/pull/11438#issue-264491895
<hr>

**Describe the issue you encountered:** Tab size change after closing tabs should have animation.

- Brave Version (revision SHA): master branch

- Steps to reproduce:
  1. open 7-8 tabs (doesn't matter what the content is; can be empty)
  1. move your cursor to the close button of the second tab from left
  1. Now as you keep clicking it will maintain the size of the tabs
  1. The size will reset as soon as you move your cursor outside the tab area.
    
- Actual result: the size is reset without animation

- Expected result: the size should be reset with transition animation

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #6088

**Comment by luixxiul** [comment] 2017-02-02 13:49
CC @bradleyrichter for a comment

**Comment by srirambv** [comment] 2018-06-14 14:57
Verified on Windows x64 using
* 0.23.8 06c657b
* muon 6.1.5
* libchromiumcontent 66.0.3359.181

**Comment by petemill** [comment] 2018-06-20 22:41
@kjozwiak I discovered the issue you found is a regression due to some other changes, and would have happened without the animation this issue calls for, so created a new issue and will close this re-open in favor of https://github.com/brave/browser-laptop/issues/14477

**Closed by petemill** 2018-06-20 22:41 UTC
Labels: QA/test-plan-specified, feature/tabsbar, release-notes/include, suggestion

**Comment by srirambv** [comment] 2018-06-25 12:36
Verified on Windows 10 x64 using
* 0.23.16 - `2042c45`
* Muon - `7.1.1`
* libchromiumcontent - `67.0.3396.87`
