### ISSUE TITLE
devtools dont dock vertically/horizontally

### ISSUE THREAD

**Issue by serapath** [brave/browser-laptop#8716] opened 2017-05-05 13:40 UTC
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:

on inspect element the devtools open, but as a separate window.
I develop all the time and am used to dock it either vertically or horizontally next to the current browser tab, but not in a separate popup. I could not find the button to dock the devtools.
Is this supported?
If not, will/can this be supported?

- Platform (Win7, 8, 10? macOS? Linux distro?):
linux mint

- Brave Version (revision SHA):
Brave	0.15.1
rev	ea5024d
Muon	2.58.8
libchromiumcontent	58.0.3029.81
V8	5.8.283.32
Node.js	7.9.0
Update Channel	dev
os.platform	linux
os.release	4.8.0-51-generic
os.arch	x64

- Steps to reproduce:
    1. rightclick on any page
    2. select "inspect element" in the context menu
    3. cant find a way to dock the devtools vertically or horizontally
    
- Actual result:
devtools open as popup

- Expected result:
devtools dock vertically (or horizontally) next to the current page, but in the same window

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes, they will reproduce

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

**Comment by Liunkae** [comment] 2017-05-05 23:29
@serapath Thanks for the report! This is a duplicate of #3555, so please subscribe to that issue for any further updates.

**Closed by Liunkae** 2017-05-05 23:29 UTC
Labels: duplicate, feature/developer-tools
