### ISSUE TITLE
All websites black

### ISSUE THREAD

**Issue by MrDragon** [brave/browser-laptop#1053] opened 2016-03-10 16:28 UTC
Windows7, 64-bit. Any site I go to (since 7.10, i think) is black - see:
![bravecapture](https://cloud.githubusercontent.com/assets/1017487/13676082/5907e5d4-e6b2-11e5-86d0-9b49d5fbe825.PNG)

I'm on a domain and the issue is "user" dependent. It works well for:
- Local user "Frank"
- Domain Administrator
- Domain User "coworker"
  But not for "domain user\FrankDragon"

The only difference I see between my user account (with the issue) and other users is that my home directory (C:\Users\FrankM) is a Junction to the D-Drive. Compare:

> 08/13/2015  04:39    &lt;JUNCTION&gt;     FrankM [D:\Users\FrankM]
> 03/10/2016  11:14    &lt;DIR&gt;          BFord

User BFord works, user FrankM has the mentioned issue. I've run into problems with junctions before.
I'm willing to troubleshoot if someone tells me what they want me to do. BTW, this happens on the downloadable installer version as well as on the git-downloaded and compiled version of brave.

**Comment by bbondy** [comment] 2016-03-10 18:15
have you tried with the 0.8.0 release?

**Comment by MrDragon** [comment] 2016-03-14 10:32
Yes, I did try the 0.8 release, but didn't compile it myself; I used the downloadable version.

**Comment by MrDragon** [comment] 2016-04-08 20:59
0.8.3 - still the same :(
I can't run Brave at home or at work, because I have either C:\Users as a junction to D:\Users (home) or C:\Users\FrankM as a junction to D:\Users\FrankM

Following junctions can't be *that* hard :( And yes, my user has full rights to the directory and all subdirectories)

**Comment by bbondy** [comment] 2016-04-09 17:33
> Following junctions can't be that hard :( 

Sure but there's also 469 other issues at the time of this writing, would love a patch if you or someone else can do one for this.

**Comment by luixxiul** [comment] 2016-05-14 11:31
How about 0.9.6 release?

**Comment by luixxiul** [comment] 2016-05-24 04:43
I'm not sure, but might this be related with #189?

**Comment by bridiver** [comment] 2016-05-24 18:22
You could verify the path issue by moving your Brave profile. Either copy your know good profile into the junction location or vice-versa. If we can verify the cause of the issue it will be much easier to fix. Thanks!

**Comment by bsclifton** [comment] 2017-02-01 08:51
Because of how old this issue is, I'd like to close it. If you found this page and are having a similar issue, please check out wiki entry for troubleshooting steps
https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page

**Closed by bsclifton** 2017-02-01 08:51 UTC
Labels: bug, info-needed, OS/Windows
