### ISSUE TITLE
I get this error message 2000 Network error on twitch tv.

### ISSUE THREAD

**Issue by FirefoxWas** [brave/browser-laptop#11819] opened 2017-11-07 06:03 UTC
### Description
I get this error message 2000 Network error on twitch tv.

### Steps to Reproduce

1. I saw it when I use the tab and saw it on https://www.twitch.tv/stickyhamster channnel. After the screen lags on the stream 2000 Network error on the screen.  

**Actual result:**

![fhtdy6u](https://user-images.githubusercontent.com/32176749/32479775-54ae29aa-c340-11e7-9421-dd58eb769bf7.png)

**Reproduces how often:**
I saw only this time.

**Brave Version**
Brave | 0.19.80

**Comment by FirefoxWas** [comment] 2017-11-07 06:25
**Reproduces how often:**
<!--
I saw only this time.
--

### Brave Version

Name | Version
-- | --
Brave | 0.19.80
rev | 7d07299
Muon | 4.5.13
libchromiumcontent | 62.0.3202.75
V8 | 6.2.414.36
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Comment by kjozwiak** [comment] 2017-11-07 18:40
Couldn't reproduce it on my end either... Tried a bunch of different streams on several devices/platforms and didn't run into any issues... Also tried the channel mentioned in https://github.com/brave/browser-laptop/issues/11819#issue-271718849.

**Comment by MCBTVe** [comment] 2017-11-08 20:38
I also had the same issue trying to view https://twitch.tv/blockbyblock and he was 2000: Network Error for about 20 mins, until he finally hosted someone else. Don't you have logs for this sort of thing?

**Comment by MCBTVe** [comment] 2017-11-08 20:39
Here is screenshot of the error.
![screen shot 2017-11-08 at 12 38 39 pm](https://user-images.githubusercontent.com/33498522/32573143-dc1cb8ec-c481-11e7-9d88-e402a75c59c0.png)

**Comment by meadio** [comment] 2017-11-08 21:48
I keep getting the error as well. Watching DrDisrespectLive
<img width="1419" alt="screen shot 2017-11-08 at 3 46 50 pm" src="https://user-images.githubusercontent.com/12126924/32576321-3f243de2-c49c-11e7-9faf-3ca24e3e3ab0.png">

**Comment by rodasgam** [comment] 2017-11-09 15:47
i had the same problem watching imaqtpie
![capturar](https://user-images.githubusercontent.com/33024108/32614457-3623d1b6-c565-11e7-8fae-d580e17dc6b7.PNG)

**Comment by kjozwiak** [comment] 2017-11-09 17:08
Re-opening as this is being reproduced by several users. @FirefoxWas, @MCBTVe, @meadio, @rodasgam, what platforms are you guys seeing this on? Does it happen pretty often or once in a while? Does the network error happen after a few hours of streaming? Few minutes?

The more information that you guys can provide, the better!

**Comment by FirefoxWas** [comment] 2017-11-09 17:40
Hi Kamil,

what platforms are you guys seeing this on?

Am using brave browser.

Does it happen pretty often or once in a while?

Only when streamers lag issue.

Does it happen pretty often or once in a while?

 once in a while

Thanks

**Comment by kjozwiak** [comment] 2017-11-09 17:44
Thanks @FirefoxWas, which Operating System are you using? Windows 10? Windows 8? macOS? Linux?

**Comment by MCBTVe** [comment] 2017-11-09 19:00
Mac OS 10.11.6
Chrome 61.0.3163.100 64bit

Issue happened when BlockByBlock was IRL Streaming and ran into some spotty wireless coverage. The stream lagged and eventually went down with this error.

**Comment by FirefoxWas** [comment] 2017-11-09 19:57
Hi Kamil,

Windows home 1709 OS Build 16299.19

thanks

**Comment by meadio** [comment] 2017-11-09 20:16
I just realized this is for the Brave Browser. My issues are happening on Google Chrome. I apologize. I did a quick Google search and this is the first thing that came up. Anyways, here is more about the issue on my end.

It is random lagging then followed by the error.
It also starts when I first load the webpage too sometimes.
I have also been getting a 1000 error too.

Google Chrome - Version 61.0.3163.100 (Official Build) (64-bit)
https://go.twitch.tv/drdisrespectlive

**Comment by jackofsporks** [comment] 2017-11-10 23:25
2000 happened for me after watching about 1/2hr to 1hr of streaming on https://go.twitch.tv/agrecascino. Before that, i kept was getting the spinning circle lag the whole time with just a coupe secs of video every now and then. Firefox 56.0 (64-bit)

**Comment by MCBTVe** [comment] 2017-11-13 22:28
This just happened again. This time it's twitch.tv/dyannatv, first it lagged out a couple of times, and 2000: Network error occurred.

This time I'm on Win10, Chrome Version 62.0.3202.89 (Official Build) (64-bit)

**Comment by kjozwiak** [comment] 2017-11-14 00:06
I'm going to close this off as this seems like an issue with Twitch and not Brave. Looks like users are also having issues with Chrome & Firefox as well.

It looks like this particular bug is appearing as the first item when searching for `2000 Network error on twitch tv` hence all the replies above.

**Closed by kjozwiak** 2017-11-14 00:06 UTC
Labels: needs-info, needs-investigation

**Comment by lengel93** [comment] 2017-11-23 01:57
So I just had the same issue using Google Chrome. I wasn't able to watch any twitch streams. What I found was switching my Subnet Mask from 255.0.0.0 to 255.255.255.0 in my router settings fixed the issue.

**Comment by jonathansampson** [comment] 2017-11-27 01:21
@lengel93 Thank you for the feedback; sounds like it's definitely not an issue with Brave.

**Comment by johnkenjack** [comment] 2018-01-20 09:59
Hi guys. I switched to incognito on Chrome and that fixed the problem.

**Comment by luizrrodrigues** [comment] 2018-02-23 19:10
> Hi guys. I switched to incognito on Chrome and that fixed the problem.

Me too, only works in incognito mode.

**Comment by larsholmjespersen** [comment] 2018-03-03 18:05
I get this in firefox as well, repeatably

**Comment by benjiwright** [comment] 2018-04-04 18:06
I had to turn off **Ghostery** to get Twitch to work in Chrome

**Comment by lanesawyer** [comment] 2018-04-06 00:46
Started seeing this today. Turning off Ghostery fixed it for me.
- Firefox 59.0.2 (64-bit)
- Ghostery 8.1.0

**Comment by manach93** [comment] 2018-04-24 19:14
![2000 network error](https://user-images.githubusercontent.com/22284710/39208783-c1dfb0b4-47b8-11e8-9768-cd3a69a0af7e.PNG)
i'm getting it too i'm trying brave browser now tried multiple unblocked dns extensions and i even tried to flush the dns with cmd that didn't work either. can anybody help 2 error fix videos came out but didn't help me one time it started working 2 days ago. thanks if anybody can help please do.

**Comment by anonymau5** [comment] 2018-04-27 23:27
This isn't fixed, this still happens regularly. Once it starts, it refuses to stop making twitch useless for the day.

**Comment by ketonic** [comment] 2018-05-01 09:03
I am getting this error while i am using any kind AdBlocker (Adblock plus and Ghostery). 
I tried to disable each block by it self but not untill i turned off Adblock plus and marked Twitch as "Trust Site" in Ghostery it started to work.
