### ISSUE TITLE
Ubuntu : 'Search for...' missing from the input field context menu

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5454] opened 2016-11-07 15:20 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When testing the context menu in Ubuntu, it was discovered that a search option was missing.

**Expected behavior:**
Every version on every OS should have a search option in the context menu.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X and Ubuntu.

- Brave Version:
0.12.8 RC1

- Steps to reproduce:
    1. On an Ubuntu system select text and open the context menu.

- Screenshot if needed:
<img width="461" alt="screen shot 2016-11-07 at 9 12 01 am" src="https://cloud.githubusercontent.com/assets/1434040/20063039/6a2f8c7c-a4cb-11e6-80da-de06ee28bcdf.png">

- Any related issues:

**Comment by Liunkae** [comment] 2016-11-07 17:27
"Search for" is not available for text in input fields (I'm not sure if that's intended). Does it work on Ubuntu if you select and right-click normal text?

**Comment by Liunkae** [comment] 2016-11-07 18:26
This might be fixed with #5466.

**Comment by bsclifton** [comment] 2016-11-08 01:25
@Liunkae can you verify it was fixed with #5466?  If so, let's close this out. In the meantime, I'll remove the milestone. Thanks :smile:

**Comment by Liunkae** [comment] 2016-11-08 01:31
It is fixed on macOS. I don't currently have Ubuntu to test it on.

**Comment by jaydson** [comment] 2016-11-08 02:32
Ubuntu 16.10 + Brave 0.12.7

Search for in normal text (working):

![screenshot from 2016-11-08 00-26-04](https://cloud.githubusercontent.com/assets/72206/20084532/12dd1aaa-a54a-11e6-8507-0819b43bfd45.png)

Search for in a input field (not working):  

![screenshot from 2016-11-08 00-29-48](https://cloud.githubusercontent.com/assets/72206/20084621/c32cb262-a54a-11e6-8e3a-35f7903f0f5c.png)

**Comment by Liunkae** [comment] 2016-11-08 02:54
@jaydson Thanks! Normal text works as expected on Ubuntu.

Could someone please try an input field on Ubuntu with the latest master? If it works, we can close this issue.

**Comment by jaydson** [comment] 2016-11-08 02:59
I can test it @Liunkae

**Comment by jaydson** [comment] 2016-11-08 03:05
Tested with the latest master (0.12.8) and it's not working.

![screenshot from 2016-11-08 01-02-30](https://cloud.githubusercontent.com/assets/72206/20085341/5a034c88-a54f-11e6-9c44-88f788534107.png)

**Comment by Liunkae** [comment] 2016-11-08 03:53
@jaydson Just checking: was the text selected? I doesn't appear selected in the screenshot.

**Comment by jaydson** [comment] 2016-11-08 03:59
It's selected @Liunkae 
The default text is black, when select it's orange.
Sorry for the bad screenshot, but trust me, it's selected :smile:

**Comment by Liunkae** [comment] 2016-11-08 04:04
@jaydson OK, thanks for testing. 😉  We'll leave the issue open for now.

**Comment by Liunkae** [comment] 2017-01-27 17:19
With the example as above, I cannot reproduce with Brave 0.12.15 on Linux Ubuntu 16.04:
![image](https://cloud.githubusercontent.com/assets/19424103/22380246/51b554b4-e482-11e6-8341-80b48ebf57d1.png)

**Comment by Liunkae** [comment] 2017-01-28 20:07
The problem appears to be fixed. Closing.

**Closed by Liunkae** 2017-01-28 20:07 UTC
Labels: feature/context-menu, OS/linux-distros
