### ISSUE TITLE
Intermittently unable to see cursor in Brave

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10299] opened 2017-08-04 18:50 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Reported via community and internally with 0.18.x: Sometimes cursor is not visible in text boxes or URL bar when you click inside them. Doesn't always happen and close/reopen Brave seems to solve it at least temporarily.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS and Windows

- Brave Version (revision SHA):
0.18.14

- Steps to reproduce:
    1. Open Brave. 
    2. Click inside text box or URL bar.
    3. Cursor may or may not be visible.
    
- Actual result:
Sometimes cursor is not visible.

- Expected result:
Cursor should always be visible.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Fist started seeing reports with 0.18.14.

- Can this issue be consistently reproduced?
No.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by LaurenWags** [comment] 2017-08-04 18:51
+2 from community

**Comment by LaurenWags** [comment] 2017-08-04 18:59
Additional report of this - was in a long running tab after changing URL a few times. Close/Reopen of Brave did resolve issue.

**Comment by NejcZdovc** [comment] 2017-08-04 19:02
Saw this on my mac as well

**Comment by bsclifton** [comment] 2017-08-04 19:46
Saw this too, thanks for capturing @LaurenWags 😄 

The work-around for now seems to be: minimize the app then restore.  Then you'll see the cursor again

**Comment by bsclifton** [comment] 2017-08-06 06:11
I believe this is upstream (in Chromium) after experiencing this w/ Chrome 60

**Comment by luixxiul** [comment] 2017-08-06 08:02
Is this a duplicate of #10104? if so, I was wrong that I thought it has been fixed with #10165.

**Comment by bsclifton** [comment] 2017-08-06 08:50
@luixxiul possibly... did you confirm if https://github.com/brave/browser-laptop/issues/10104 was fixed? I only closed because you said it should close it (even though bookmarks modal is not related to the cursor issue)

**Comment by luixxiul** [comment] 2017-08-06 09:38
I myself did not reproduce the issue; I assumed so based on https://github.com/brave/browser-laptop/pull/10165/files#diff-0c5d92d1fbd1b7473c3e6c8dd26f5edcR116. @srirambv would you mind testing to reproduce #10104 for me? thanks!

**Comment by srirambv** [comment] 2017-08-08 08:19
@luixxiul @bsclifton  I verified #10104 but couldn't reproduce it. However I see this issue on the latest build as per this issue. I see this happen when the focus is set to an inactive tab (dead tab) by either closing the immediate/previous tab. Minimize and restore  doesn't show the cursor for me have to quit and restart the browser to function normally

**Comment by alexwykoff** [comment] 2017-08-08 20:18
If we can, having the upstream chromium issue would be really handy

**Comment by bsclifton** [comment] 2017-08-08 21:05
possibly related:
- https://bugs.chromium.org/p/chromium/issues/detail?id=751601&q=no caret&colspec=ID Pri M Stars ReleaseBlock Component Status Owner Summary OS Modified
- https://bugs.chromium.org/p/chromium/issues/detail?id=740518&can=1&q=caret hidden&colspec=ID Pri M Stars ReleaseBlock Component Status Owner Summary OS Modified

(many suspect upstream issues; hard to narrow down)

**Comment by srirambv** [comment] 2017-08-09 09:48
Found another way to reproduce this, below steps could be helpful

1. Launch an app and follow a link which open in Brave
2. Two windows are open (one from the previous session and the other following the link)
3. Close the second window which was opened following the link
4. Original window with previous session doesn't show the cursor, minimize and restore shows the cursor

**Comment by jonathansampson** [comment] 2017-08-29 06:49
I spoke with a user over Twitter recently who reported similar issues on their Fedora 26 install. Unfortunately, minimizing and restoring _did not_ resolve the problem.

**Comment by eljuno** [comment] 2017-09-07 19:39
+1 from community https://community.brave.com/t/creating-bookmarks-takes-a-long-time/1987/24?u=eljuno

**Comment by eljuno** [comment] 2017-09-08 20:43
+2 from community https://community.brave.com/t/moved-back-to-chrome-for-now/7342?u=eljuno

**Comment by eljuno** [comment] 2017-09-12 21:23
+1 from community https://community.brave.com/t/cursor-not-appearing-when-using-text-on-sites/7534?u=eljuno

**Comment by yuenanto** [comment] 2017-09-13 09:15
I encounter the same problem but **only** when Dashlane is activated.
I have never encountered this problem again since I deactivated Dashlane.

Platform: MacOS
Brave Version: 0.18.29

**Comment by diracdeltas** [comment] 2017-09-15 19:03
I don't have any extensions and I still see it occasionally, including in 0.18.36 today.
* restarting always fixes the issue
* when it happens, the URL bar is grey when focused instead of blue

**Comment by patrick99e99** [comment] 2017-09-26 21:21
+1 this just happened for me.

I copy and pasted some text from the terminal to a gmail message, and the cursor disappeared and no longer appears in any of my tabs..  However if I open a new window, then that new window has a visible cursor in all tabs, but switching back to my other window results in no cursor.

**Comment by bsclifton** [comment] 2017-11-22 18:08
@LaurenWags have you seen this recently? I haven't had it happen in quite some time

**Comment by LaurenWags** [comment] 2017-11-22 18:12
@bsclifton - same, it's been weeks since I encountered this issue.

**Comment by bsclifton** [comment] 2017-11-22 19:39
Closing- let's re-open if we experience this again 😄

**Closed by bsclifton** 2017-11-22 19:39 UTC
Labels: bug, needs-investigation, needs-STR, priority/P2, upstream
