### ISSUE TITLE
Tear off tab unmute's audio but still shows mute indicator

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13990] opened 2018-05-02 15:58 UTC
### Description
Tear off tab unmute's audio but still shows mute indicator

### Steps to Reproduce
  1. Open YT and play a video in a tab
  2. Mute the tab by clicking on the speaker icon
  3. Tear the YT tab into a window, audio starts playing but the speaker icon still shows as mute
  4. Attach the tab back to original window, audio continues to play

**Actual result:**
Tear off tab unmute's audio but still shows mute indicator

**Expected result:**
Tab should remain muted even if its teared off into a window

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.669
-- | --
V8 | 6.6.346.24
rev | 6cda2e8
Muon | 5.2.7
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.117

**Reproducible on current live release:**
Yes

### Additional Information
Different behaviour on Chrome. It mutes at domain level and not at tab.

**Comment by petemill** [comment] 2018-05-03 20:25
Duplicate of #13979

**Closed by petemill** 2018-05-03 20:25 UTC
Labels: bug, feature/tear-off-tabs
