### ISSUE TITLE
Netflix support

### ISSUE THREAD

**Issue by silverslimer** [brave/browser-laptop#1719] opened 2016-05-13 00:38 UTC
When attempting to play Netflix content, I receive the error:

"Whoops, something went wrong...

Missing Component

We cannot find all the required components to play Netflix on this device. Please visit chrome://components, locate the WidevineCdm component, and click the "Check for update" button."

**Comment by luixxiul** [comment] 2016-05-13 07:08
Closing as dupe of #1299. Thanks anyway.

**Closed by luixxiul** 2016-05-13 07:08 UTC
