### ISSUE TITLE
Cannot switch directly to parent tab after following link which opens new tab

### ISSUE THREAD

**Issue by evq** [brave/browser-laptop#8823] opened 2017-05-10 21:36 UTC
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
When following a link which opens a new tab (`target="_blank"`) one cannot switch back to the parent tab directly.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
master (a602f87822b3469c18d48e48f602d0b363ac4cca)

- Steps to reproduce:
    1. Visit https://www.w3schools.com/html/html_links.asp
    1. Click any of the "Try it Yourself" links.
    1. Notice that you are unable to switch back to the parent tab without first switching to another tab.

- Actual result:
Cannot switch back to parent.

- Expected result:
Can switch back to parent.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
Unknown.

- Can this issue be consistently reproduced?

**Comment by evq** [comment] 2017-05-10 21:49
Seems to only happen with my extensions installed (cvim, kodi, qr-code, video-speed-controller)

**Comment by evq** [comment] 2017-05-10 21:55
Actually this seems to happen unreliably even without extensions. Clicking on the newly opened tab in the tab bar also allows one to switch to the parent tab when it does happen.

**Comment by evq** [comment] 2017-05-10 22:50
It seems when this happens, "Select Previous Tab" also doesn't work (it stays on the current tab). As far as I can tell, it seems like the correct tabId is passed to `setActive` in tabs.js and the call to `tab.setActive(true)` is made. I think this is in Muon? Any chance this could be related to recent changes there by @bridiver?

**Comment by bsclifton** [comment] 2017-05-16 21:29
wow- good find @evq.  I believe we've fixed this in master- I can't reproduce.  It would likely have been fixed with https://github.com/brave/browser-laptop/pull/8863

Would you be able to give it a try again?

**Closed by bsclifton** 2017-05-16 21:29 UTC
Labels: bug

**Comment by evq** [comment] 2017-05-17 08:15
@bsclifton This issue seems fixed for me. Thanks! :)

FWIW I am seeing a few new issues with tab handling, but I'm going to hope it's related to the muon version bump and the fact that I didn't nuke my `node_modules` and `~/.electron` folders. I didn't have any obvious errors but I've heard it might cause an issue and that some people manually delete things before every build. (I wish I had their patience :D) This seems kind of sketchy to me, I wonder if theres a cleaner way to do or avoid this cleanup.

I will do a full clean build (remove node_modules etc) and search / open new issues tomorrow if they persist.

**Comment by bsclifton** [comment] 2017-05-19 00:15
@evq awesome! Yeah, there are often times new Muon versions are needed.  I'm not sure of a good way to communicate it... but if you're suspecting something, you might check the .npmrc file at the root of the repo for changes 😄  (and then compare Muon version versus what shows in about:brave)
