### ISSUE TITLE
window.prompt is not supported currently

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#94] opened 2015-12-24 06:48 UTC
## Test plan
1. Visit https://www.w3schools.com/js/tryit.asp?filename=tryjs_prompt
2. Click the `Try it` button on the right hand side
3. Confirm prompt is shown; text should be selected
4. Type `Brave` and click `OK`
5. Confirm `Hello Brave! How are you today?` is shown
6. Repeat steps 2 - 5, except press enter to submit instead of clicking `OK`
7. Click the `Try it` button on the right hand side
8. Click `Cancel` button
9. Confirm `User cancelled the prompt.` is shown
10. Repeat steps 8 and 9 except press escape instead of clicking `Cancel`

## Original issue description
We can patch here:
https://github.com/atom/electron/blob/c4931bb2d12f5905cdf434ed6ff1a755ccad053f/atom/renderer/lib/override.coffee#L92

window.prompt

**Comment by diracdeltas** [comment] 2016-05-18 01:29
looks like prompt is still not supported?

**Comment by luixxiul** [comment] 2016-05-22 11:14
So maybe is this the reason of #1723, #1311 and like that?

**Comment by bsclifton** [comment] 2016-08-22 14:53
+1 from @CliqueBait via https://github.com/brave/browser-laptop/issues/3295

**Comment by jonathansampson** [comment] 2017-01-19 06:30
+1 from Twitter; a user who would like to use Brave internally, but cannot due to the lack of `window.prompt`: https://twitter.com/jamonholmgren/status/821964305964765184

**Comment by bsclifton** [comment] 2017-02-07 16:55
@bridiver do you know if the underlying support is there for this?  If so, I can knock this out pretty easily. It should help w/ out extension support

**Comment by marktani** [comment] 2017-02-07 17:05
We are currently relying on window.prompt for our [dashboard](https://github.com/graphcool/console/), so support for this would be highly appreciated! :)

**Comment by jonathansampson** [comment] 2017-03-20 03:52
Just learned from a user today that WooCommerce (3+ million WordPress users) uses `window.prompt`.

**Comment by CliqueBait** [comment] 2017-04-01 05:47
+1 from Community: https://community.brave.com/t/dialogue-alert-pop-up-preferences/1974

**Comment by jonathansampson** [comment] 2017-04-01 17:25
Chromium to change behavior of dialogs: [Chromium policy on JavaScript dialogs](https://developers.google.com/web/updates/2017/03/dialogs-policy)

**Comment by Skayo** [comment] 2017-05-17 17:08
1+ need it for my WebApp....

**Comment by mojoaxel** [comment] 2017-05-28 12:57
It is not likely that electron is going to implement `prompt`.
see https://github.com/electron/electron/issues/472

**Comment by bridiver** [comment] 2017-05-29 00:09
@mojoaxel we don't need electron to implement prompt because we have our own fork that has diverged significantly. It wouldn't be difficult to implement prompt

**Comment by bsclifton** [comment] 2017-09-20 06:29
+1 from peterkroon via https://github.com/brave/browser-laptop/issues/11010
>Steps to Reproduce
>
> Go to: https://www.w3schools.com/js/tryit.asp?filename=tryjs_prompt
> Click on button "Try it!"

**Comment by shortstuffsushi** [comment] 2017-10-22 23:36
Plus one "wow, this is a thing?" I am pretty shocked I've run into this... to be honest, I was just messing around with getting a simple input value. Was this intentionally bypassed for any particular reason?

**Comment by bsclifton** [comment] 2017-10-29 04:57
@shortstuffsushi not bypassed for any reason- we just haven't had the time to implement it yet

I did rework a lot of the alert code and I believe it should be somewhat easy to add:

Here is the block of code that gets called when window.prompt is triggered
https://github.com/brave/browser-laptop/blob/41a0523d088f2c90a2148eafd40f52b9d10dcedf/app/browser/tabMessageBox.js#L47-L52

The smart move might be to [edit the MessageBox component](https://github.com/brave/browser-laptop/blob/41a0523d088f2c90a2148eafd40f52b9d10dcedf/app/renderer/components/common/messageBox.js#L33) to allow for an edit control and handle prompts using the existing tabMessageBox code

**Comment by jonathansampson** [comment] 2018-02-05 17:52
Calling `window.prompt('')` in Brave crashes the browser.

**Comment by Liunkae** [comment] 2018-02-06 07:03
Warning: The `Try it` button in the example [above](https://github.com/brave/browser-laptop/issues/94#issuecomment-330757595) crashes the browser. Reproduced on Brave 0.20.30 on macOS 0.13.x.

**Comment by bsclifton** [comment] 2018-02-07 22:53
Tentatively assigning to 0.23.x since this does cause a crash

**Comment by srirambv** [comment] 2018-03-14 06:13
+3 from https://community.brave.com/t/brave-crashes-upon-javascript-popup-in-google-tasks/15138/6

@bsclifton can this be moved up to 0.24.x?

**Closed** 2018-05-07 18:05 UTC
Labels: bug, crash, parity, priority/P3

**Comment by shortstuffsushi** [comment] 2018-05-07 18:20
🎉 Thanks guys. Now if I want to super lazily implement user input, I don't have to do any extra work.

**Comment by LaurenWags** [comment] 2018-05-31 20:36
+1 from community: https://community.brave.com/t/javascript-prompt-not-prompting/11315

**Comment by LaurenWags** [comment] 2018-08-14 15:55
Verified with macOS 10.12.6 using
* 0.23.80 53a429f
* Muon 8.0.8
* libchromiumcontent 68.0.3440.84
