### ISSUE TITLE
Debian Stretch "No usable sandbox"

### ISSUE THREAD

**Issue by gjhklfdsa** [brave/browser-laptop#15320] opened 2018-11-28 01:30 UTC
**Bug:** Brave only works with --no-sandbox on Debian Stretch
Log:

```
usr@LINUX:~$ brave
[18177:18177:1127/182336.650835:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Trace/breakpoint trap
usr@LINUX:~$ brave --no-sandbox

(brave:18235): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(brave:18235): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(brave:18235): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
ATTENTION: default value of option force_s3tc_enable overridden by environment.
Crash reporting enabled
usr@LINUX:~$ 
```

Steps followed for installation:
```
# $ su
# $ echo
# $ curl https://s3-us-west-2.amazonaws.com/brave-apt/keys.asc | sudo apt-key add -
# $ echo "deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt `lsb_release -sc` main" | sudo tee -a /etc/apt/sources.list.d/brave-`lsb_release -sc`.list
# $ grep lsb_release /etc/apt/sources.list.d/brave*
# $ sudo apt update
# $ sudo apt install brave
```

**Comment by Liunkae** [comment] 2018-12-05 20:43
Looks like a duplicate of brave/brave-browser#1986.

By the way, this repository is for the old Brave version. Please see brave/brave-browser for the new version.

**Closed** 2019-01-03 16:22 UTC
