### ISSUE TITLE
Audio indicator not shown on Slack call 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10625] opened 2017-08-22 14:06 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Audio indicator not shown on Slack call 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.18.23
-- | --
rev | 36ae2ec
Muon | 4.3.10

- Steps to reproduce:
    1. Open more than 30-40 tabs with tab count set to 20
    2. Launch slack call on a new tab
    3. Audio indicator is missing
    
- Actual result:
Audio indicator not shown on Slack call 

- Expected result:
Should always indicate any type of audio/video

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes 0.18.23

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
@cezaraugusto

**Comment by cezaraugusto** [comment] 2017-08-22 15:46
can you confirm if restarting the browser solves the issue? I opened #10611 which I think are the same. Not sure about the root cause yet tho, seems intermittent.

**Comment by srirambv** [comment] 2017-08-22 16:36
Restarting does work. Also I observed one of the tab had a webview crash. Once reloaded the crashed page, the audio indicator flashed. Not sure if that is related to this.

**Comment by bsclifton** [comment] 2017-08-22 20:27
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/10611

**Closed by bsclifton** 2017-08-22 20:27 UTC
Labels: bug, QA/steps-specified
