### ISSUE TITLE
sometimes tabs become unusable after being idle

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12202] opened 2017-12-06 19:12 UTC
### Description
Reported via twitter (https://twitter.com/efembis/status/938449380629237762) and internally (by @srirambv): on Windows when you leave tabs open for awhile and don't use them, when you do go to use them (i.e. read an article), sometimes those tabs are unusable. You have to restart Brave.

### Steps to Reproduce

  1. Open Brave with several sites in several tabs.
  2. Don't use some of the tabs for awhile.
  3.

**Actual result:**
When you go to use the tabs that you have not accessed for awhile, the tabs will be unusuable.

**Expected result:**
Tabs should be usable.

**Reproduces how often:**
unknown.

### Brave Version

**about:brave info:**
0.19.105

**Reproducible on current live release:**
yes

### Additional Information
possibly related to https://github.com/brave/browser-laptop/issues/9865 ?

**Comment by srirambv** [comment] 2017-12-07 08:30
I had these dead tabs quite a lot. Two possible scenarios
1. When you have both Brave and Brave Beta running simultaneously it might happen 
2. When you have memory intensive process like a VM running some of the backgrounded tabs become dead. The only option is to quit and relaunch the browser. 

Both scenario has happened quite a lot. With Brave beta running along side, there are dead tabs on both Brave and Brave beta although the number of dead tabs doesn't directly relate to the number of tabs opened. I've had only one dead tab among 10 odd tabs once and 4/5 dead tabs once as well. But the order of dead tabs is usually from the left (oldest tab opened) and if your active tab is the 4th tab out of 10 tabs, the first three tabs will be dead and not the 5-10th tab.

**Comment by srirambv** [comment] 2017-12-19 11:59
Still happens on 0.19.120. Had 5 pin tabs and 9 tabs opened. After the system being idle for about an hour two of the tabs are unresponsive. However one tab is showing the tab overview but doesn't switch, the other one is completely dead 


![12202](https://user-images.githubusercontent.com/17010094/34156175-fd1928c6-e4b3-11e7-9292-98418886d5f6.gif)
 
cc: @bsclifton @bridiver

**Comment by srirambv** [comment] 2018-01-05 13:22
+1 from @Katamori from #12516

**Comment by srirambv** [comment] 2018-01-05 13:23
@bsclifton this needs a priority bump.

**Comment by alexwykoff** [comment] 2018-01-30 18:33
closing as dupe of https://github.com/brave/browser-laptop/issues/10673

**Closed by alexwykoff** 2018-01-30 18:33 UTC
Labels: OS/Windows, bug, duplicate
