### ISSUE TITLE
Address bar hides when hovered over

### ISSUE THREAD

**Issue by iSasFTW** [brave/browser-laptop#11505] opened 2017-10-13 13:38 UTC
### Description
The address bar appears when i hover over the tabs or bookmarks, and hides immediately once i hover over the page title (where the address bar should appear).

### Steps to Reproduce

  1. Hover over the tabs or the bookmarks
  2. Try to hover over the page title

**Actual result:**
Address bar hides and is not clickable

**Expected result:** Address bar shows up when the page title is hovered over

**Reproduces how often:** 90%, unless It's right after opening a new tab, when the address bar is automatically highlighted. (Problem appears again after clicking anywhere on the page)
Edit to 90%, because i noticed it occasionally lets me use the address bar regularly if i try multiple times over and over. It's not behaving regularly in that scenario either, but at least lets me change the url.

### Brave Version

**about:brave info:**
Brave: 0.19.49 
rev: 0f0a5d6e5c1abbb5bdbf3771c0cd638fa61019b1 
Muon: 4.4.28 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Reproducible on current live release:**
Yes.

**Comment by eljuno** [comment] 2017-10-14 19:41
+1 from community https://community.brave.com/t/url-bar-problem-in-latest-version-0-19-48/9048?u=eljuno

>the URL bar (which also functions as the Title Bar) doesnt change when i hover my mouse pointer over it.

**Comment by eljuno** [comment] 2017-10-19 20:06
Related to #9850?

**Comment by iSasFTW** [comment] 2017-10-19 20:32
@eljuno Looks like the exact problem I was having. Might be the same bug appearing again in the new update.

**Comment by bsclifton** [comment] 2017-10-20 15:23
Great catch, @eljuno 😄 

I'll close this issue as a duplicate of https://github.com/brave/browser-laptop/issues/9850.  @iSasFTW you can subscribe to that issue for updates 😄

**Closed by bsclifton** 2017-10-20 15:23 UTC
Labels: feature/URLbar
