### ISSUE TITLE
Error opening Google Docs spreadsheet

### ISSUE THREAD

**Issue by pgiambat** [brave/browser-laptop#4673] opened 2016-10-11 12:48 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Opening a spreadsheet in Google Docs does not work. The spreadsheet opens, looks good for 1 to 2 senconds then fades to an error screen. Text at the tops says: "Something went wrong. Please reload.". The message in the middle of the screen (in a box) says "Unable to load file. Try to load it again or send an error report." Box also contains a "Reload" button. Also, when I click on the 'send an error report' link I do get a new reporting window and can type in the text box but cannot attach a screenshot as the 'Attach Screenshot' check box will not 'Stay' checked. It will check at the mouse-down click event but will not stay checked. 
I tried to create a new spreadsheet in Brave. A new spreadsheet did open and I could type in a cell but when hitting the enter key I got the same error as described above.

**Expected behavior:**
Spreadsheet opens, stays open and is editable.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 7

- Brave Version:
Brave: 0.12.4
Electron: 1.4.12
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0

- Steps to reproduce:
1. While Gmail screen, click on the apps waffle (top right), select 'Drive'.
2. Once in Google Docs (Drive home screen) double-click an existing spreadsheet.
3. Spreadsheet opens but errors-out, see description above for details.

- Screenshot if needed:
![googledocspreadsheeterror](https://cloud.githubusercontent.com/assets/22769367/19270571/558b4482-8f86-11e6-845a-c2e10ea01472.jpg)

- Any related issues:

**Comment by srirambv** [comment] 2016-10-11 13:03
Dupe of [2343](https://github.com/brave/browser-laptop/issues/2343). Closing in favour of [2343](https://github.com/brave/browser-laptop/issues/2343)

**Closed by srirambv** 2016-10-11 13:03 UTC
Labels: duplicate
