### ISSUE TITLE
Unable to log in to Binance site

### ISSUE THREAD

**Issue by wrightpt** [brave/browser-laptop#14836] opened 2018-07-25 03:50 UTC
### Steps to Reproduce

  1. Binance.com
  2. Enter Login and Password
  3. Unable to pass test to show i am not a computer. Only fails for Brave Browser

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bsclifton** [comment] 2018-07-25 15:43
awesome @wrightpt 😄 I'll keep this issue open as we'd like it to work without having to do anything

I'll tag it with a `workaround` label, so others that find this know what they can do in the meantime 😄

**Comment by eljuno** [comment] 2018-07-25 18:01
Dupe of #13808? Also, it may worked with _Allow all cookies_. :smile:

**Comment by bsclifton** [comment] 2018-07-25 20:16
This is indeed a dupe! Great catch, @eljuno 😄 I'll close this one out

**Closed by bsclifton** 2018-07-25 20:16 UTC
Labels: webcompat, workaround/shields-down
