### ISSUE TITLE
On Windows Brave does not (re)launch at "maximized" size when it was running as such last time

### ISSUE THREAD

**Issue by scunliffe** [brave/browser-laptop#426] opened 2016-01-29 12:48 UTC
On Windows, an app can launch at a specific size, or the full desktop size (with full window chrome around the edges) or "maximized" where the app fills the desktop and the ~8px or so window chrome borders on all sides are not rendered.

Each app on Windows tends to hold on to its last state (and / or size) and re-launch itself at that last state the next time it is opened.

Brave appears to launch at the same "size"... but not the same "state" if the last state was Maximized.

(Based on Telemetry data I have from some other apps used by 100K+ users, a large majority run each windows app maximized)

**Comment by ppetrov** [comment] 2016-01-29 16:45
That's really annoying for me too.

**Comment by bbondy** [comment] 2016-01-29 18:52
Closing this as a dupe of #146 but added in an explicit mention of maximized state.
Thanks for the extra telemetry stats too!

**Closed by bbondy** 2016-01-29 18:52 UTC
