### ISSUE TITLE
Netflix fails to stream

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11928] opened 2017-11-13 13:18 UTC
### Description
Netflix steam fails on Windows

### Steps to Reproduce

  1. Install 0.19.89
  2. Login to Netflix and try to play any video
  3. Missing component error is shown

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/32727421-63402c82-c874-11e7-807d-e1df4b5b0eb0.png)

**Expected result:**
Should stream

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.89
-- | --
rev | 20badac
Muon | 4.5.15
libchromiumcontent | 62.0.3202.89
V8 | 6.2.414.40
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
No

### Additional Information
https://help.netflix.com/en/node/27451
```
Netflix Error M7701-1003

If you experience the error code M7701-1003 on your computer, it typically points to a component on your browser that needs to be updated or that is being blocked by a security setting or program. Follow the troubleshooting steps below to resolve the issue.
```

cc: @darkdh @bbondy

**Comment by kjozwiak** [comment] 2017-11-13 15:26
Working on MacOS 10.12.6 using `0.19.89` using 20badac0c818421c22310c3805a07e2caaea20bb.

**Comment by darkdh** [comment] 2017-11-13 17:10
`brave\Extensions\WidevineCdm` is empty. Something prevents us from downloading this component. Even I fallback to 0.19.80 and 0.19.88

**Comment by darkdh** [comment] 2017-11-14 00:24
The server always respond `noupdate`
```
<?xml version="1.0" encoding="UTF-8"?><response protocol="3.1" server="prod"><daystart elapsed_days="3969" elapsed_seconds="50691"/><app appid="oimompecagnajdejgnnjijobebaeigek" cohort="" cohortname="" status="ok"><updatecheck status="noupdate"/><ping status="ok"/></app></response>
```
No matter you have older widevinecdm or no widevinecdm
Same thing applies to Chrome
The latest version on Mac is 1.4.8.1030, built-in bundle is 1.4.8.1029

update from older version
![kapture 2017-11-13 at 15 58 27](https://user-images.githubusercontent.com/11330831/32756256-121bc4be-c88e-11e7-8c4a-6c093512352e.gif)

no widevinecdm
![kapture 2017-11-13 at 14 59 55](https://user-images.githubusercontent.com/11330831/32756436-ea9fa21a-c88e-11e7-807e-e5e05ba39564.gif)

On Windows
update from older version
![kapture 2017-11-13 at 15 52 04](https://user-images.githubusercontent.com/11330831/32756279-26822e0c-c88e-11e7-915b-05eef771334f.gif)
no widevinecdm
![kapture 2017-11-13 at 15 16 35](https://user-images.githubusercontent.com/11330831/32756325-4cf9739c-c88e-11e7-91ed-3f84fb23ae56.gif)

**Comment by darkdh** [comment] 2017-11-14 01:21
request/response on Windows
```
<?xml version="1.0" encoding="UTF-8"?><request protocol="3.1" dedup="cr" acceptformat="crx2,crx3" version="-62.0.3202.89" prodversion="62.0.3202.89" requestid="{45d38630-a377-4ea9-a09c-bfa622de8dd3}" lang="" updaterchannel="stable" prodchannel="stable" os="win" arch="x64" nacl_arch="x86-64" domainjoined="0"><hw physmemory="8"/><os platform="Windows" arch="x86_64" version="10.0.15063.674"/><app appid="oimompecagnajdejgnnjijobebaeigek" version="0.0.0.0" installsource="ondemand"><updatecheck/><ping rd="-2" ping_freshness=""/></app></request>
```

```
<?xml version="1.0" encoding="UTF-8"?><response protocol="3.1" server="prod"><daystart elapsed_days="3969" elapsed_seconds="50691"/><app appid="oimompecagnajdejgnnjijobebaeigek" cohort="" cohortname="" status="ok"><updatecheck status="noupdate"/><ping status="ok"/></app></response>
```

request/response on Mac
```
<?xml version="1.0" encoding="UTF-8"?><request protocol="3.1" dedup="cr" acceptformat="crx2,crx3" version="-62.0.3202.89" prodversion="62.0.3202.89" requestid="{97c07bbd-eb11-4713-8266-4de45c316a77}" lang="" updaterchannel="stable" prodchannel="stable" os="mac" arch="x64" nacl_arch="x86-64" domainjoined="0"><hw physmemory="16"/><os platform="Mac OS X" arch="x86_64" version="10.12.6"/><app appid="oimompecagnajdejgnnjijobebaeigek" version="0.0.0.0" installsource="ondemand"><updatecheck/><ping rd="-2" ping_freshness=""/></app></request>
```

```
<?xml version="1.0" encoding="UTF-8"?><response protocol="3.1" server="prod"><daystart elapsed_days="3969" elapsed_seconds="62350"/><app appid="oimompecagnajdejgnnjijobebaeigek" cohort="" cohortname="" status="ok"><updatecheck status="ok"><urls><url codebase="http://redirector.gvt1.com/edgedl/chromewebstore/L2Nocm9tZV9leHRlbnNpb24vYmxvYnMvYjg0QUFWZFdqSWhpeGpjcXYyeUF6ZlBkQQ/"/><url codebase="http://dl.google.com/chromewebstore/L2Nocm9tZV9leHRlbnNpb24vYmxvYnMvYjg0QUFWZFdqSWhpeGpjcXYyeUF6ZlBkQQ/"/><url codebase="https://dl.google.com/chromewebstore/L2Nocm9tZV9leHRlbnNpb24vYmxvYnMvYjg0QUFWZFdqSWhpeGpjcXYyeUF6ZlBkQQ/"/><url codebase="http://www.google.com/dl/chromewebstore/L2Nocm9tZV9leHRlbnNpb24vYmxvYnMvYjg0QUFWZFdqSWhpeGpjcXYyeUF6ZlBkQQ/"/><url codebase="https://www.google.com/dl/chromewebstore/L2Nocm9tZV9leHRlbnNpb24vYmxvYnMvYjg0QUFWZFdqSWhpeGpjcXYyeUF6ZlBkQQ/"/></urls><manifest version="1.4.8.1030"><packages><package fp="1.6a07d6b3345dedc328bde717d4be556fb977ca798cc18e08283bde9fe7c2e9fe" hash_sha256="6a07d6b3345dedc328bde717d4be556fb977ca798cc18e08283bde9fe7c2e9fe" name="1.4.8.1030_oimompecagnajdejgnnjijobebaeigek.crx" required="true" size="1758871"/></packages></manifest></updatecheck><ping status="ok"/></app></response>
```

**Comment by darkdh** [comment] 2017-11-14 01:41
Here is our pdfjs extension request/response on Windows

```xml
 <?xml version="1.0" encoding="UTF-8"?>
<request protocol="3.1" dedup="cr" acceptformat="crx2,crx3" version="-62.0.3202.89" prodversion="62.0.3202.89" requestid="{cfe561aa-8f69-434b-97ea-9cb8d56dfc7d}" lang="" updaterchannel="stable" prodchannel="stable" os="win" arch="x64" nacl_arch="x86-64" domainjoined="0"><hw physmemory="8"/>
<os platform="Windows" arch="x86_64" version="10.0.15063.674"/>
<app appid="jdbefljfgobbmcidnmpjamcbhnbphjnb" version="0.0.0.0" installsource="ondemand">
  <updatecheck/>
  <ping rd="-2" ping_freshness=""/>
</app>
</request>
```

```xml
<response protocol="3.1" server="prod">
  <app appid="jdbefljfgobbmcidnmpjamcbhnbphjnb">
    <updatecheck status="ok">
      <urls>
        <url codebase="https://s3.amazonaws.com/brave-extensions/release/jdbefljfgobbmcidnmpjamcbhnbphjnb/extension_1_9_457.crx"/>
      </urls>
      <manifest version="1.9.457">
        <packages>
          <package name="extension_1_9_457.crx" hash_sha256="e28fcb7fe7ca66464973b1d86f7cd1214bf1874d9934e6cbab56aad68a8e05ca" required="true"/>
        </packages>
      </manifest>
    </updatecheck>
  </app>
</response>
```

**Comment by darkdh** [comment] 2017-11-14 02:02
If we get `noupdate`, we will not able to download the component
https://chromium.googlesource.com/chromium/src/+/62.0.3202.89/components/update_client/component.cc#339

see
The state machine representing how a CRX component changes during an update.
https://chromium.googlesource.com/chromium/src/+/62.0.3202.89/components/update_client/component.cc#29

**Comment by bbondy** [comment] 2017-11-14 18:18
since this seems like not a problem on our end, pushing to the next milestone.

**Comment by bbondy** [comment] 2017-11-16 15:23
Widevine said server issue and it should be fixed if client advertises the next chromium version, which we're pushing with this release. So moving it back to Hotfix 5.

**Comment by kjozwiak** [comment] 2017-11-16 16:12
Still failing under Win 10 x64.

**Comment by bbondy** [comment] 2017-11-17 15:25
@kjozwiak I think this can be closed as it's working now right? We can probably move it to hotfix 5 too.

**Closed** 2017-11-17 16:20 UTC
Labels: 0.19.x, bug, OS/Windows, plugin/widevine, regression, release/blocking

**Comment by bsclifton** [comment] 2017-11-17 16:21
Closed and moved it to Hotfix 5; @kjozwiak confirmed the following platforms yesterday at 9:54 EST
> * Win 10 Pro x64 VM
> * Win 10 Pro x86 VM
> * Win 10 Pro x64 Desktop
> * macOS 10.12.16 x64

**Comment by kjozwiak** [comment] 2017-11-17 16:22
> @kjozwiak I think this can be closed as it's working now right? We can probably move it to hotfix 5 too.

Yup, checked last night and made sure it was working on all the platforms.. I went through another check just to make sure... Using `0.19.95 ` rev: cc0ebadfd8950d1b5f454cb39c0c3a64028cc935, checked the following platforms:

* Win 10 x64 Pro VM - PASSED
* Win 10 x86 Pro VM - PASSED
* Win 10 x64 Pro Desktop - PASSED
* macOS 10.12.16 x64 - PASSED

@srirambv and @LaurenWags also confirmed that it's working correctly on both Win & macOS.
