### ISSUE TITLE
Remain on active tab when closing a distant tab

### ISSUE THREAD

**Issue by tschf** [brave/browser-laptop#3034] opened 2016-08-08 00:35 UTC
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
If I close a distant tab, the active tab changes
**Expected behavior:**
Would expect to remain on the same tab I was on when I closed the distant tab. 
- Platform (Win7, 8, 10? macOS? Linux distro?): Ubuntu 16.04 x64

- Brave Version: 0.11.3

- Steps to reproduce:
    1. Open 5 or more tabs
    2. Focus on the first tab
    3. Close tab 4 without focusing on it
    4. The active tab will now be switched to tab 4 (previously tab 5).

**Comment by willy-b** [comment] 2016-08-08 23:58
I think this is a duplicate of #2913 , which should be fixed in the daily build.
Can you verify that this is reproducible in a build from recent master?
Thanks!

**Comment by bsclifton** [comment] 2016-08-09 03:44
I verified this is no longer broken in the dev builds- next release will have this available :smile: 

Fixed w/ https://github.com/brave/browser-laptop/pull/2923 (thanks again for the fix, @willy-b!)

**Closed by bsclifton** 2016-08-09 03:44 UTC
