### ISSUE TITLE
loading spinner never stops spinning sometimes

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#286] opened 2016-01-24 02:32 UTC
On Twitter and Facebook tabs, it just keeps spinning.

**Comment by bbondy** [comment] 2016-01-24 02:36
Dupe of #269

**Closed by bbondy** 2016-01-24 02:36 UTC

**Comment by prkeshri** [comment] 2016-05-06 12:41
Same case here. When I do `npm start`, everything runs like butter, the facebook,google everything load successfully, but after I make a package out of it, it just keeps on spinning indefinitly. The title changes, though, but the page remains blank!
