### ISSUE TITLE
About pages right click context menu has an extra separator

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5765] opened 2016-11-21 12:20 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
About pages right click context menu has an extra separator

**Expected behavior:**
Extra separator should be removed

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.10 RC1

- Steps to reproduce:
    1. Open any about page
    2. Right click to show the context menu
    3. Has an extra separator after Find

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20482421/83ba05f4-afe4-11e6-9ffd-3c90049069fd.png)

- Any related issues:
 #5600
  cc: @bsclifton

**Comment by srirambv** [comment] 2016-11-21 12:25
Context menu in about:bookmark also has an extra separator

![image](https://cloud.githubusercontent.com/assets/17010094/20482602/64170156-afe5-11e6-89dd-f8ef5b18283d.png)

**Comment by bbondy** [comment] 2016-11-21 13:19
Moving to 0.12.11 because we won't respin an RC for this.

**Comment by luixxiul** [comment] 2016-11-21 13:52
the context menu on about:history too
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/20485030/33bacfee-b03d-11e6-84c2-e8959294924c.jpg)

**Comment by Liunkae** [comment] 2016-11-23 18:12
I cannot reproduce with 0.12.10 final release on macOS 10.12.x.
![image](https://cloud.githubusercontent.com/assets/19424103/20573566/04f7227c-b176-11e6-970c-deed54be2f62.png)

**Comment by bsclifton** [comment] 2016-11-23 20:49
@Liunkae this is only a problem on Windows / Linux; Mac strips out unneeded separators

**Comment by bbondy** [comment] 2016-11-28 04:09
Re-opening because it breaks bookmark folders.
STR:
1. Clear session storage.
2. Create a bookmark folder
3. Load a webpage and click the star button
4. In the folder drop down select the bookmark folder.
5. Try to click or hover over the bookmark folder. 

<img width="756" alt="screenshot 2016-11-27 23 03 38" src="https://cloud.githubusercontent.com/assets/831718/20656047/81aebc02-b4f6-11e6-8a45-9328bccaea27.png">

**Comment by bbondy** [comment] 2016-11-28 04:10
This also breaks bookmark tests.

**Comment by bsclifton** [comment] 2016-11-28 04:54
@bbondy doh, thanks for the catch. I'll dig into this tonite and ensure tests look good locally

**Comment by bsclifton** [comment] 2016-11-28 08:02
Root cause found! It has to do with only 1 item being in the folder... which is great that the Bookmarks toolbar test does this :smile: I'll make an explicit test for this, fix the issue, and then resubmit a PR

**Comment by srirambv** [comment] 2016-12-21 12:07
This is still an issue if the password manager/pocket extension is not enabled on 0.13.0 Preview 5 
Same on new tab also. 

related fix #5869

![image](https://cloud.githubusercontent.com/assets/17010094/21388788/ce33fb3c-c775-11e6-981c-cb7e86ce4d8c.png)

cc: @bsclifton

**Closed** 2016-12-22 07:00 UTC
Labels: enhancement

**Comment by luixxiul** [comment] 2017-01-16 12:38
Test plan: https://github.com/brave/browser-laptop/pull/6374#issue-197024290
