### ISSUE TITLE
Background process doesn't quit when data is imported

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13422] opened 2018-03-12 13:05 UTC
### Description
Background process doesn't quit when data is imported

### Steps to Reproduce

  1. Clean install 0.21.656
  2. Launch browser and close, ensure no background process are retained
  3. Import browser data/bookmarks HTML file into Brave
  4. Close browser, background process remain opened doesn't close

**Actual result:**
![bookmark import](https://user-images.githubusercontent.com/17010094/37284842-151daa22-2623-11e8-895a-10a5e7c45152.gif)

**Expected result:**
Should quit all background process when browser is closed irrespective of importing browser data

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.21.656
-- | --
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.146
Muon | 4.9.0
Node.js | 7.9.0
OS Architecture | x64
OS Platform | Microsoft Windows
OS Release | 10.0.16299
rev | c8e9925
Update Channel | Beta
V8 | 6.5.254.31

**Reproducible on current live release:**
No

### Additional Information
Killing the active background process and relaunching the browser, doesn't show the imported data

cc: @darkdh @hferreiro @bsclifton @ltilve @bridiver

**Comment by darkdh** [comment] 2018-03-12 17:07
@srirambv can you narrow down which data you import cause the problem?

**Comment by kjozwiak** [comment] 2018-03-12 23:56
@darkdh I can reproduce the above by simply importing any `.html` backup and then closing Brave via the `X` located on the toolbar.

STR: (also reproducible  with 0.21.18 580be78 which is the current release)

* launch brave `0.21.656`
* import the `.html` backup mentioned below
* close Brave using `X` via the title bar

`.html` bookmark backup: https://drive.google.com/file/d/1hTlLtP2bkNM-265ilSJGWejHtG3T1NzR/view?usp=sharing.

**Comment by bsclifton** [comment] 2018-03-13 16:26
Moving out of milestone since this is an existing issue

**Closed** 2018-04-10 18:28 UTC
Labels: 0.21.x, OS/Windows, bug, feature/importer

**Comment by btlechowski** [comment] 2018-04-11 16:59
Verified Win7 x64 v0.22.108
