### ISSUE TITLE
Re-open closed tabs should include history

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3645] opened 2016-09-01 19:28 UTC
This is probably going to be fixed by session restoring histry, but posting it separately so we remember to include it for release notes. 

/cc @bsclifton

**Comment by bsclifton** [comment] 2016-09-02 00:16
Closing as a dupe of https://github.com/brave/browser-laptop/issues/2702

**Closed by bsclifton** 2016-09-02 00:16 UTC
