### ISSUE TITLE
browser is closed with one unloaded tab unexpectedly

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9733] opened 2017-06-27 07:11 UTC
**Describe the issue you encountered:** the browser is unexpectedly closed with one unloaded tab.

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA): 0.17.10

- Steps to reproduce:
    1. Clear the browser's profile
    2. Open a new tab
    3. Click the twitter tile
    4. Open about:about
    5. Bookmark the about page
    6. Close the browser
    7. Restart the browser
    8. Close the about page tab
    
- Actual result: The browser is closed

- Expected result: the unloaded twitter tab should be loaded

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
   yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment] 2017-06-27 07:19
This is actually a duplicate of https://github.com/brave/browser-laptop/issues/9506; since it's came up a few times, I think it's worth creating a new 0.17.x release

**Closed by bsclifton** 2017-06-27 07:19 UTC
Labels: bug, crash, needs-triage

**Comment by luixxiul** [comment] 2017-06-27 07:27
weird, as this case the first tab is not loaded, while on #9506 the other tabs aren't.

**Comment by luixxiul** [comment] 2017-06-27 08:07
confirmed this was fixed
