### ISSUE TITLE
Open file doesn't open default download location

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13229] opened 2018-02-21 17:29 UTC
### Test plan
1. Launch Brave and open Menu->File->Open File...
2. Default download location should properly show (ex: `c:\Users\clifton\Downloads`)

### Description
Open file doesn't open default download location

### Steps to Reproduce

1. Menu->File->Open File...
2. The default path shown is Desktop

**Actual result:**
![11906-openfile](https://user-images.githubusercontent.com/17010094/36495181-7784df1e-175a-11e8-977b-dc2794a1cd9f.gif)

**Expected result:**
Should show default download location when file open option is selected

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.21.10
-- | --
V8 | 6.4.388.41
rev | fd80122
Muon | 5.0.2
OS Release | 10.0.16299
Update Channel |  
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
N/A

### Additional Information
Found while testing #11906

**Comment by darkdh** [comment] 2018-02-21 21:16
seems like Windows only and it will use last location you used to open file no matter fresh profile or not

**Comment by btlechowski** [comment] 2018-02-22 11:20
Opening last used location is the intended behavior. Chrome and Firefox behave the same. 

Nevertheless, when clean install is done then it should open default download location.

@kjozwiak @LaurenWags Your thoughts?

**Comment by darkdh** [comment] 2018-02-23 19:15
Just tested Chrome and Firefox by fresh profile on Windows
Both initial location will be the application install location not default download location

**Comment by darkdh** [comment] 2018-02-23 19:33
nvm, I think I have the fix for initial location

**Comment by bsclifton** [comment] 2018-03-09 22:03
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by btlechowski** [comment] 2018-03-27 21:14
The issue is still reproducible for Open File(CTRL + O).

Reproduced on Windows 7 x64
* 0.22.7  8bb7e77f
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.1

Cannot reproduce when saving a file(CTRL+S).

**Comment by bsclifton** [comment] 2018-09-07 17:32
This should be addressed in our [Developer channel release](https://brave.com/download-dev); if not, we can track it there. I can't confirm because I'm not seeing a way to open files... but the dialog does come up (and save the path) when saving pictures, etc

**Closed by bsclifton** 2018-09-07 17:32 UTC
Labels: 0.22.x, OS/Windows, QA/test-plan-specified, addressed-with-brave-core, muon, priority/P4, release-notes/exclude, wontfix
