### ISSUE TITLE
Brave update details section link not complete

### ISSUE THREAD

**Issue by vinicentus** [brave/browser-laptop#13152] opened 2018-02-15 11:15 UTC
### Description

When the update bar appears and you click details, you get this:
![screenshot 33](https://user-images.githubusercontent.com/17357504/36253734-13d3644e-1251-11e8-9469-2b064c6cc495.png)
It's a bit of a hassle to manually copy the url in the first place, but it doesn't even work (at least in dev versions). The url for v0.20.42dev should be `https://github.com/brave/browser-laptop/releases/tag/v0.20.42dev`, but it appears as `https://github.com/brave/browser-laptop/releases/tag/v0.20.42 dev`, with a space between v0.20.42 and dev.

### Steps to Reproduce

When brave indicates that there is a new update, click details

**Actual result:**

The url shows as `https://github.com/brave/browser-laptop/releases/tag/v0.20.42 dev`, with a space between v0.20.42 and dev.

**Expected result:**

The url should be `https://github.com/brave/browser-laptop/releases/tag/v0.20.42dev`, without any spaces.

**Reproduces how often:**

Always, I think?

### Brave Version

**about:brave info:**

 
Brave: 0.20.41 
V8: 6.4.388.41 
rev: 7bc4c2c8e6ef052407c581a61fc00b584b78f17d 
Muon: 4.8.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:**

Probably

**Comment by srirambv** [comment] 2018-02-15 15:28
Think this is related to #10960

**Comment by bsclifton** [comment] 2018-02-15 15:48
Good catch @srirambv - this is a duplicate of https://github.com/brave/browser-laptop/issues/10960 😄 I'll close this issue in favor and give that one a bump

**Closed by bsclifton** 2018-02-15 15:48 UTC
Labels: duplicate
