### ISSUE TITLE
Cannot log-into or access any Disqus features

### ISSUE THREAD

**Issue by grokk** [brave/browser-laptop#13632] opened 2018-03-28 03:34 UTC
Brave does not enable any functionality of Disqus commentary to articles, whatsoever - not logging in, or anything else.  The browser _does_ load Disqus with proper formatting on the subject pages, however; but this content appears as static only -- with no functionality whatsoever.

This situation has been the case for at least the past few releases on Debian; and other people appear to have had this same issue, at other times (but as of right now, I do not know).

**Comment by bsclifton** [comment] 2018-03-28 20:57
@grokk do you have some example steps for us to reproduce? ex: visit a particular site?

**Comment by jonathansampson** [comment] 2018-03-31 16:26
I just logged-in to pcgamer.com (the first site I could find that uses Disqus); didn't encounter any issues. These are my settings for pcgamer.com:

![image](https://user-images.githubusercontent.com/815158/38165259-6148f502-34d6-11e8-8e2b-1f1ba93f93ac.png)

**Comment by grokk** [comment] 2018-06-26 04:20
I believe I commented further, where this came up elsewhere: the issue has now essentially disappeared. But it was there -- consistently -- for some time.

Now, the only issue is that the pop-up window from Disqus does not go away (Disqus has introduced a Captcha) after logging-in thru their site... a small annoyance. Another annoyance which has disappeared was the need to continually on new pages on the same site. That worx fine now, AFAIK.

**Comment by bsclifton** [comment] 2018-09-21 05:32
Closing since there isn't anything actionable

**Closed by bsclifton** 2018-09-21 05:32 UTC
Labels: webcompat
