### ISSUE TITLE
Drag&Drop .webloc not supported

### ISSUE THREAD

**Issue by raisty** [brave/browser-laptop#13593] opened 2018-03-25 09:37 UTC
### Description

The .webloc Drag&Drop open two error tabs and content of webloc like text.

### Steps to Reproduce

  1. Create webloc on desktop
  2. Move the file into tab panel
  3. Brave open two error tabs and one text file with content of webloc

**Actual result:**

Two error pages and one text file

**Expected result:**
Website from webloc

**Reproduces how often:**

Always

### Brave Version

**about:brave info:**

Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Reproducible on current live release:**

yes

**Comment by kjozwiak** [comment] 2018-03-26 00:33
Thanks for the bug report @raisty! However, looks like this is a duplicate of #6847.

**Closed by kjozwiak** 2018-03-26 00:33 UTC
