### ISSUE TITLE
Loading wheel spinning after tab has loaded

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#9893] opened 2017-07-07 04:47 UTC
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Reported via Twitter: https://twitter.com/Music_Journeys/status/882809848445927424

> _another bug i've noticed that still exists in the latest Brave is i get a spinner in the tab even when a tab has fully loaded from Soundcloud.  an example is the following:  https://t.co/zVgGE9E4gy_

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 8.1 (note: I have observed in Win10 as well) 

- Brave Version (revision SHA):
Latest version (actual info the)

- Steps to reproduce:
    1. Go to soundcloud link above
    2. See tab loading wheel continuously spin after loading
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Y
- Can this issue be consistently reproduced?
Y
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
Needs investigation. May need additional info.

**Comment by bsclifton** [comment] 2017-07-13 00:00
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/9001

**Closed by bsclifton** 2017-07-13 00:00 UTC
Labels: info-needed, needs investigation
