### ISSUE TITLE
Intermittent Issues with Look Up selection

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#9627] opened 2017-06-21 04:00 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
From [a user on Twitter](https://twitter.com/shaftgunk/status/877011642499960836):
> In Brave, when highlighting word, right clicking, & selecting "Look Up", the result is frequently blank or another definition.

This issue was confirmed by both Brendan Eich and Brian Bondy.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
N/A

- Steps to reproduce:
    1. Highlight a word
    2. Right click, select "Look Up"
    
- Actual result:
Results are often blank, or incorrect.

- Expected result:
Definition for the selected term should be shown.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
N/A

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Relevant Source:

[contextMenus.js#L966](https://github.com/brave/browser-laptop/blob/f1ab9970527cbcedefe287483bf719765bd9171f/js/contextMenus.js#L966)

```js
const showDefinitionMenuItem = (selectionText) => {
  let lookupText = textUtils.ellipse(selectionText, 3)
  return {
    label: locale.translation('lookupSelection').replace(/{{\s*selectedVariable\s*}}/, lookupText),
    click: (item) => {
      webviewActions.showDefinitionForSelection()
    }
  }
}
```

**Comment by Liunkae** [comment] 2017-06-21 04:35
Related: #8554 (Show definition popup is misaligned). +1 from me.

**Comment by lzmartinico** [comment] 2017-06-25 05:08
It's a problem with electron https://github.com/electron/electron/issues/8905 for my Brave build, I get the same behaviour as described in Javan's last comment. It may be useful until Electron is fixed to call showDefinitionForSelection so as to populate the search bar in the dictionary app?

**Comment by Liunkae** [comment] 2018-02-06 06:31
Seems fixed. I cannot reproduce with Brave 0.20.30 on macOS 10.13.x. This may have been fixed with 0.18.x/0.19.x (around the same time as #8554).

**Comment by bsclifton** [comment] 2018-02-07 22:43
Closing as this appears fixed for me too 😄

**Closed** 2018-02-07 22:42 UTC
Labels: OS/macOS, bug

**Comment by bsclifton** [comment] 2018-02-07 22:44
There is a similar issue (maybe this was what was reported):
https://github.com/brave/browser-laptop/issues/12695

This issue (linked) has exact steps to repro

**Comment by jonathansampson** [comment] 2018-02-13 03:28
Appears to be working for me too.
