### ISSUE TITLE
Twitch/YouTube root domain is not added to ledger list

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13515] opened 2018-03-20 11:16 UTC
### Description
Twitch/YouTube not added to ledger list

### Steps to Reproduce
  1. Clean install 0.21.24, enable payments
  2. Visit any Twitch/YouTube video
  3. Channels gets listed in ledger table but domain doesn't get listed

**Actual result:**
Twitch/YouTube not added to ledger list

**Expected result:**
Should add the root domain and exclude from payments

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.21.24
-- | --
V8 | 6.5.254.36
rev | 19c78a1
Muon | 4.9.3
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.162

**Reproducible on current live release:**
No

### Additional Information
cc: @bsclifton @kjozwiak @LaurenWags @btlechowski

**Comment by kjozwiak** [comment] 2018-03-20 13:50
Reproduced several times as well on macOS. Seems like the initial visit after turning on ledger isn;t being added into the table. STR that I used:

* launch 0.21.23 6f9c4f7
* once launched, enable payments via `about:preferences#payments`
* open a new tab and load boardgamegeek.com
* browse through the website for 2-3 minutes and revisit `about:preferences#payments`

You'll notice that the ledger table is blank.

**Comment by kjozwiak** [comment] 2018-03-20 17:39
Decided this wasn't a blocker with @NejcZdovc and @bsclifton after a quick chat. QA will go through the manual ledger passes with `0.21.24` and if everything works as expected, this will be moved out and put into a more appropriate milestone.

**Comment by NejcZdovc** [comment] 2018-03-20 19:36
I think that we need to revisit this, because talking with people they even expect to work like this. To record root domain, when you are on root domain and don't record it when you are watching videos on this root domain.

**Comment by srirambv** [comment] 2018-03-20 20:32
Seeing the issue on prod wallet but not on staging wallet.

**Comment by NejcZdovc** [comment] 2018-04-09 08:11
closing this one as we talked about it and this is better flow, where if you are on youtube site we record youtube, but if you are watching publisher we record only that

**Closed by NejcZdovc** 2018-04-09 08:11 UTC
Labels: 0.21.x, feature/ledger, needs-info, regression
