### ISSUE TITLE
Linux Mint - Flash - Couldn't Load Plugin

### ISSUE THREAD

**Issue by DirtGrubDylan** [brave/browser-laptop#9533] opened 2017-06-16 23:48 UTC
- Did you search for similar issues before submitting this one? 
Yes

- Describe the issue you encountered:
Following the instructions here: https://github.com/brave/browser-laptop/wiki/Flash-Support-Deprecation-Proposal#troubleshooting-flash-issues. I installed PepperFlash through the apt repository. When I went to load http://homestarrunner.com/ I got an error saying `Couldn't load plugin` where the flash player was.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux Mint 18.1 Serena

- Brave Version (revision SHA):
0.15.310

- Steps to reproduce:
    1. Install Brave
    2. sudo apt install pepperflashplugin-nonfree
    3. Open Brave, and enabe Adobe flash support in Preferences.
    4. Go to http://homestarrunner.com/
    
- Actual result:
The flash plugin could not be loaded.

- Expected result:
The flash plugin to be loaded.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
I think so.

- Is this an issue in the currently released version?
I searched, but couldn't find anything related.

- Can this issue be consistently reproduced?
Haven't tried on any other computer but my own.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/7865580/27248064-ec51c26c-52bb-11e7-96d0-8f9a00efb651.png)

- Any related issues:

**Comment by alexwykoff** [comment] 2017-06-17 01:44
I believe this is a duplicate of https://github.com/brave/browser-laptop/issues/7505

**Closed** 2017-06-19 07:50 UTC
Labels: duplicate, plugin/flash
