### ISSUE TITLE
1Password Should Auto-Submit on Fill

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#5875] opened 2016-11-28 16:46 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
> In my other browsers, when I click to fill my username and password from OnePassword, it submits the login form, too. It would be nice if Brave did that, too. [[Source](https://community.brave.com/t/onepassword-extension/33?u=sampson)]

**Platform (Win7, 8, 10? macOS? Linux distro?):** N/A

**Brave Version:** N/A

**Comment by alexwykoff** [comment] 2016-11-30 21:25
This is a regression introduced in 0.12.10 which we missed.

**Comment by darkdh** [comment] 2016-12-13 02:38
0.13.0 preview 3 works for me
![456](https://cloud.githubusercontent.com/assets/11330831/21125371/082bcfec-c120-11e6-8b84-c68857fc61b6.gif)

**Comment by bbondy** [comment] 2016-12-13 14:39
Closing but please re-open if you see it on 0.13.0 preview3 or later.

**Closed by bbondy** 2016-12-13 14:39 UTC
Labels: enhancement, feature/extensions, feature/password-manager, regression, release/blocking

**Comment by luixxiul** [comment] 2017-01-17 05:10
Would anyone please add QA steps for this issue? 0.13.0 will be the largest release ever and the QA team needs clear and simple steps! Please see #6668 for more info. Thanks in advance :pray:

**Comment by srirambv** [comment] 2017-01-17 09:52
QA Steps
1. Enable 1Password as password manager from settings 
2. Visit any site which is stored in the 1Password Vault
3. Press Ctrl+\ or Cmd+\ to autofill the user credentials
