### ISSUE TITLE
verified icons don't display properly in the ledger table when site has a long name

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13334] opened 2018-02-27 19:48 UTC
### Description
Verified icons display smushed next to the favicon in the ledger table if one of the sites/youtube channel names is very long.

### Steps to Reproduce

  1. Enable payments.
  2. Visit a couple sites with verified icons (examples: duckduckgo.com, theguardian.com, vice.com, coindesk.com) and a couple without (nytimes.com, cnn.com, etc)
  3. Note that verified icons display nicely in their column.
  4. Visit https://www.youtube.com/channel/UCMtFAi84ehTSYSE9XoHefig/videos and watch a video.

**Actual result:**
When this channel gets added to the table the Site column gets wider and the verified icons don't display nicely any more. They're right up against the favicon in the Site column:
![screen shot 2018-02-27 at 2 32 22 pm](https://user-images.githubusercontent.com/28145373/36750919-b8dc1042-1bcc-11e8-9265-38a75b769d75.png)

**Expected result:**
This is how the verified icons display without the long YT channel name:
![screen shot 2018-02-27 at 2 32 06 pm](https://user-images.githubusercontent.com/28145373/36750943-c6b1d238-1bcc-11e8-9ded-a4fcb11dcfbe.png)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.21.16

**Reproducible on current live release:**
Yes, reproducible on 0.20.46

### Additional Information
@kjozwiak also experienced this

**Comment by jasonrsadler** [comment] 2018-03-02 02:23
This seems to be fixed in 0.22 from PR #13205. 

0.21
![image](https://user-images.githubusercontent.com/25326067/36880158-3879c5c8-1d95-11e8-9b42-53b3f5f5a99f.png)

0.22
![image](https://user-images.githubusercontent.com/25326067/36880243-9fd56146-1d95-11e8-8eda-594198af1e1b.png)

**Comment by NejcZdovc** [comment] 2018-03-02 04:45
closing this as a dupe of #13195

**Closed by NejcZdovc** 2018-03-02 04:45 UTC
Labels: bug, duplicate, feature/ledger, priority/P3
