### ISSUE TITLE
Feature Request: disable search engine go key case sensitivity 

### ISSUE THREAD

**Issue by scarejar** [brave/browser-laptop#8479] opened 2017-04-25 03:06 UTC
Very minor issue but sometimes I accidently type capital letters on the shortcut like ":G" opposed to ":g" for google and it doesn't work of course. I suggest we remove the case sensitivity

**Comment by luixxiul** [comment] 2017-04-25 08:28
I think @jhreis has suggested the same thing before.

**Comment by srirambv** [comment] 2017-04-25 10:13
Closing as dupe of #7749

**Closed by srirambv** 2017-04-25 10:13 UTC
Labels: duplicate, feature/search, suggestion
