### ISSUE TITLE
Can't export bookmarks

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#10587] opened 2017-08-18 22:41 UTC
- Did you search for similar issues before submitting this one?

Yes, Googled "Brave browser can't export bookmarks on dual boot windows ubuntu".

- Describe the issue you encountered:

Export bookmarks on Brave on Windows with a Linux dual boot will prompt you to save it to a location, but it doesn't save.

- Platform (Win7, 8, 10? macOS? Linux distro?):

Windows 10 x64
Ubuntu 16.04.3 LTS

- Brave Version (revision SHA):

Brave | 0.18.23
-- | --
rev | 36ae2ec
Muon | 4.3.10
libchromiumcontent | 60.0.3112.90
V8 | 6.0.286.52
Node.js | 7.9.0
Update Channel | dev
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

- Steps to reproduce:
    1. Export bookmarks and save it.
    
- Actual result:
The bookmark HTML file is not in the saved location.

- Expected result:
The bookmark HTML file should be in the saved location.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Maybe not. I reproduced on my laptop. Brave sync is on on both devices. I turned Brave Sync off on the laptop and the Windows OS desktop and got the same result. 

I will try turning Brave Sync off on the Ubuntu OS.

Also, when Brave Sync is on with the Windows OS on the desktop, nothing shows in the table.

![2017-08-19 08_39_59-preferences](https://user-images.githubusercontent.com/16969914/29480229-0f6d4cdc-84ba-11e7-9976-74be83f39d75.png)

I went to Linux Brave, and could save the bookmarks HTML file and see it in the saved location. Additionally, the bookmarks had synced from the laptop. I turned Brave Sync off to check the effect on exporting bookmarks on the laptop and Windows OS on the desktop. The bookmarks could still export with Brave sync off on Linux OS on the desktop, but still did not export on the laptop (rebooting didn't help).

The bookmarks file still did not export on Windows on the desktop.

I reset sync on the laptop, then turned Brave sync on on Windows desktop, synced a new device on the laptop. The bookmarks were not added to the laptop from Windows desktop after restarting Brave on the laptop.

- Is this an issue in the currently released version?

Yes.

- Can this issue be consistently reproduced?

No.

- Any related issues:

TBC with Brave Sync.

**Comment by JaneSmith** [comment] 2017-08-25 21:40
I'm having this issue too. I wanted to export my bookmarks so I could switch over to a more stable browser, but the exported file doesn't get created/saved...

**Comment by eljuno** [comment] 2017-09-24 18:37
+1 from community https://community.brave.com/t/regarding-backing-up-or-exporting-bookmarks/8147

>After selecting the details and click save/export and I choose desktop and I go to it and did it a few times but yet no html file there for me to see although no error messages popped up?

Brave 0.18.36
PC Windows 7

**Comment by bsclifton** [comment] 2017-09-26 16:34
@JaneSmith you can open up the session file to get the contents:
- Windows: `%APPDATA%\brave\session-store-1`
- macOS: `~/Library/Application Support/brave/session-store-1`
- Linux: `~/.config/brave/session-store-1`

When doing the export, I'm curious if we can get more info by pressing Shift + F8 to show the browser dev tools

**Comment by JaneSmith** [comment] 2017-09-26 16:52
@bsclifton Thanks, that helps... Although it's not really in the best format. I guess I'm going to have to write some kind of script to get the bookmarks out in a readable format.

**Comment by bsclifton** [comment] 2017-09-26 23:53
@JaneSmith you can try our latest beta and that might have a bug fix for what you're seeing with HTML export
https://github.com/brave/browser-laptop/releases/tag/v0.19.20beta

**Comment by byroniac** [comment] 2017-09-27 17:21
The 0.19.20 beta does not fix my issue. I am guessing there is a problem with one of my bookmarks, which only works on a company intranet system. But that is just a guess. It does show me what the HTML bookmark file would be named, but does not seem to create it. And running with the Dev tools activated does not seem to capture any useful information.

**Comment by jamesray1** [comment] 2017-09-29 08:00
I'm using 0.19.16 now and it is faster to change the location of a bookmark before saving it, which is good.

**Comment by jamesray1** [comment] 2017-09-29 08:02
I can also export the bookmarks and I can see the file in the location that I save it in.

**Comment by jamesray1** [comment] 2017-09-29 08:07
@bsclifton can you have a prompt asking if you'd like to update to the latest beta release? If no, ask how often you'd like to be asked this:
- weekly
- never.

**Comment by jamesray1** [comment] 2017-09-29 08:20
Alternatively have an option to automatically update to the latest beta release in the settings, and automatically update to the latest stable release (by default).

**Comment by byroniac** [comment] 2017-09-29 20:08
OK, not sure if the latest 0.9.24-beta fixed it, or the fact that I've done a fresh install of Windows 10 for unrelated reasons, but the bookmark export is working now. Woot!

**Comment by bsclifton** [comment] 2017-09-29 20:55
@byroniac @jamesray1 awesome! Glad you are both able to export the bookmarks 😄 

I'll mark this issue as closed.  Apologies that you both ran into some deal-breakers for daily browsing.  We'll be at work trying to prioritize and fix all the known issues we have- thanks again for the report 😄

**Comment by byroniac** [comment] 2017-09-29 21:55
Thank you. One suggestion? I wish there was a way to automatically format the export filename as YYYY-MM-DD.html or something similar. Or maybe a setting to choose the format? Would love the ISO 8601 default, personally.

**Comment by jamesray1** [comment] 2017-10-03 05:31
I also like how if you add a bookmark that has already been added to a different location it will remove the original location.

**Comment by JaneSmith** [comment] 2017-10-14 16:56
I'm still experiencing this issue with version 0.19.49 (0f0a5d6). Still unable to rescue my bookmarks almost two months later.

**Comment by bsclifton** [comment] 2017-10-16 06:34
@JaneSmith what exactly happens?  You can go to bookmarks manager

From the menu, it's `Window` > `Bookmarks...` or you can use the kabob menu (the 3 dots under the lion in the top right) and pick `Bookmarks` > `Bookmarks`

Once there, you can click the export icon (the one with the line going outside)
![screen shot 2017-10-15 at 11 22 23 pm](https://user-images.githubusercontent.com/4733304/31597908-c722d2ee-b1ff-11e7-863d-461bc623c185.png)

At that point, a dialog should show up.  Is this happening? If not, maybe we can try launching via command line to get some more info.  On Windows, you should be able to do this by hitting the Windows key, typing `cmd`, and then running:
```
%USERPROFILE%\AppData\Local\brave\app-0.19.49\Brave.exe
```

Any errors should get logged to the command window when running.  Please let us know more information about how this is failing for you and we'll get those bookmarks out 😄

**Comment by JaneSmith** [comment] 2017-10-16 11:38
Yes, the dialog shows up. I choose my desired file location and name, and click "Save". The dialog closes, but no file is created. The bookmarks are not exported.

I tried your logging instructions, but unfortunately nothing gets printed to the console. I'm not quite sure that's actually working properly though, as even if I start Brave from the command line, the command line just moves on to next prompt so I can enter another command. It doesn't "run inside" the command line in the way that I would expect (removing the prompt) and doesn't print anything at all. It just launches the browser normally as far as I can see.

**Comment by JaneSmith** [comment] 2017-11-25 19:22
Is there any update on this issue yet? I'm still experiencing it with 0.19.95 (cc0ebad).

**Comment by byroniac** [comment] 2017-11-26 18:48
I don't know if this helps or not, but I am on a fresh install of Ubuntu 17.10 and it works there (I'm using the apt repository approach), and on Windows 10 Version 1709 (Build 16299.64) it is working, but this is a new machine and I had an older version of Brave I did a fresh install on. I do remember having this problem on older Ubuntu and Windows 10 machines. I suspect there was some bookmark I had saved which was causing the problem, but that is only a guess on my part.

**Comment by JaneSmith** [comment] 2017-11-26 19:41
Thanks for the reply. Unfortunately I have quite a lot of bookmarks. I did go through the list and tried deleting a few that had Japanese characters in their titles, thinking that maybe that could be causing the problem, but it still fails to export properly.

**Comment by byroniac** [comment] 2017-11-26 20:22
Hmmm. Another idea: are any of the bookmarks extremely long? Like over 240 characters? I tried to figure out what the problem was back when I had it. To make a long story short, I am in an area affected by Hurricane Harvey so I lost the computer I had the problem on. So it is no longer possible for me to help diagnose the error, as I am now working on a fresh install.

**Comment by bsclifton** [comment] 2017-11-27 04:58
@byroniac thanks for the clues

@JaneSmith if you felt comfortable sharing your `session-store-1` file with me, I'd love to help. If you're comfortable doing this, you can zip/send to me via clifton@brave.com.  Please know that I treat user data with respect and will only use it to find the root cause and will delete all copies of it

**Comment by liquidixen** [comment] 2017-12-27 17:52
I'm having the same issue, as soon as I go to export my bookmarks and hit save the file doesn't appear. I've got my session-store-1 file, seeing as this issue still isn't resolved please tell me how I can convert this file to a HTML file.

**Comment by DuppoHosting** [comment] 2017-12-29 00:45
I'm sorry I've been waiting a for so long till this gets fixed and still nothing. I also got to the file were they're stored. And would also appriciate if you'd atleast show us how to convert it to a html file. it's been 5 months already...

**Comment by JaneSmith** [comment] 2017-12-29 01:06
I'm still experiencing this issue too. Sorry for forgetting to reply before, but I'm not comfortable with sharing that file. Privacy is very important to me (that's part of what attracted me to Brave in the first place).

**Comment by deameong** [comment] 2017-12-31 01:44
Hello, I've also been waiting a long time for this to get fixed. It would be very helpfull if you could provide us with a way to convert the session-store-1 file to html (if this is possible). with all due respect how much longer will it take to get this fixed, I have no backup of my bookmarks and it's been almost half a year.
Thanks in advance!

**Comment by bsclifton** [comment] 2018-01-02 18:12
Duplicate of https://github.com/brave/browser-laptop/issues/11744 ?

**Closed** 2018-01-03 08:19 UTC
Labels: feature/exporter, priority/P3

**Comment by bsclifton** [comment] 2018-01-03 23:19
OK folks- bear with me here.  I believe we have a fix.  It's in our BETA build (not released yet), so there are a few extra steps you'd have to do if you want to try the fix

1. **Download / install the build from https://github.com/brave/browser-laptop/releases/tag/v0.20.15beta**

2. **Run the browser. Your profile should be completely empty at this point**

3. **Close the browser**

4. **Copy over the `session-store-1` file from the `brave` folder to the `brave-beta` folder**

Your `session-store-1` file is located here (depending on platform):
- Windows: `%APPDATA%\brave\session-store-1`
- macOS: `~/Library/Application Support/brave/session-store-1`
- Linux: `~/.config/brave/session-store-1`

You're going to want to copy that file to this location:
- Windows: `%APPDATA%\brave-beta\session-store-1`
- macOS: `~/Library/Application Support/brave-beta/session-store-1`
- Linux: `~/.config/brave-beta/session-store-1`

Example of copy:
`cp ~/.config/brave/session-store-1 ~/.config/brave-beta/session-store-1`


5. **Relaunch Brave**

6. **Try exporting bookmarks**

cc: @deameong, @JaneSmith, @DuppoHosting, @liquidixen 

If the problem still persists, I did put some logging in which will happen if you launch brave-beta via the command line.  If you're not willing to try the above steps, you can wait until this release becomes more stable and is officially released.  Please let me how it goes! 😄

**Comment by JaneSmith** [comment] 2018-01-03 23:46
It seems to work with that beta version. Thanks!
