### ISSUE TITLE
Having brand new tab freezes browser and URL search bar, unable to switch to different tabs

### ISSUE THREAD

**Issue by aumars** [brave/browser-laptop#12104] opened 2017-11-26 11:10 UTC
### Description
After having initialised Brave, the new tab freezes the entire browser and takes about 2-4 seconds to unfreeze, this is has been happening in both my Linux and Windows builds ever since I've switched to Brave months ago.

### Steps to Reproduce
1. Open Brave and start immediately typing on the URL bar, or open a bookmark.
2. Open a new tab and do the same.

**Actual result:**
https://ipfstube.erindachtler.me/v/QmUEqYz589bwHP9GsPZohtrRhKRfF3qX2EUHTa96stSyAC

**Reproduces how often:**
90% of the time.

### Brave Version

**about:brave info:**
Brave: 0.21.0 
V8: 6.1.534.32 
rev: 98b430bd90bdf8cafb8682e5fe376083b3c71fa1 
Muon: 4.4.19 
OS Release: 4.13.12-1-ARCH 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.3.5 
libchromiumcontent: 61.0.3163.79

**Reproducible on current live release:**
Yes.

**Comment by bsclifton** [comment] 2017-11-27 23:27
Thanks for the report, @aumars- I'm going to close this issue as a duplicate of https://github.com/brave/browser-laptop/issues/8541.  I gave that issue a bump on your behalf and you can follow it to track progress 😄

**Closed by bsclifton** 2017-11-27 23:27 UTC
Labels: perf
