### ISSUE TITLE
I can't remove page from top sites list. I am pressing x button but page remains. I am using latest 32 bit version of the program.

### ISSUE THREAD

**Issue by Stefandjalic** [brave/browser-laptop#10750] opened 2017-08-31 19:38 UTC
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
![untitled](https://user-images.githubusercontent.com/31520209/29942003-aac0f966-8e94-11e7-9d96-d414a12f3ee1.jpg)

**Comment by eljuno** [comment] 2017-08-31 19:52
Duplicate of #10411?

**Comment by NejcZdovc** [comment] 2017-08-31 19:53
duplicate of #10411

**Closed by NejcZdovc** 2017-08-31 19:53 UTC
Labels: duplicate
