### ISSUE TITLE
Drag & drop html or image files into the main window doesn't yield response - not displaying the files as expected.

### ISSUE THREAD

**Issue by jenn-rhim** [brave/browser-laptop#11255] opened 2017-10-03 17:48 UTC
### Description

Drag & drop html or images (jpg/png) files into the main window doesn't respond.

### Steps to Reproduce

  1. Drag & drop html or images (jpg/png) files into the main window
  2. Nothing happens
  3.

**Actual result:**

No response no feedback
The files have to be dropped onto the url field to be able to display the files.

**Expected result:**
The same result should be achieved by dropping the files into the main window.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bsclifton** [comment] 2018-09-18 18:54
Closing as duplicate of https://github.com/brave/browser-laptop/issues/10497

**Closed by bsclifton** 2018-09-18 18:54 UTC
Labels: misc/drag-and-drop, priority/P3
