### ISSUE TITLE
debugger tools launched from brave do not have "dock side" menu item

### ISSUE THREAD

**Issue by sinsunsan** [brave/browser-laptop#10892] opened 2017-09-11 10:05 UTC
In brave  when  clicking on inspect : the chrome  debugger display which is great not to have to use  other debugger than chrome's.

But strangely  it is missing one very important function, that  allow to dock the  inspector : the "dock side" menu item
I have a small computer, and in "floated" mode it is very difficult for me to use the debugger;

The missing menu item 
![screen shot 2017-09-11 at 12 01 09](https://user-images.githubusercontent.com/910241/30269478-3bdc09e8-96e9-11e7-8284-3dd12ed265e6.png)

The display in brave
![screen shot 2017-09-11 at 12 01 34](https://user-images.githubusercontent.com/910241/30269477-3bd92fa2-96e9-11e7-9ec4-e0c69a370803.png)

The display in chrome
![screen shot 2017-09-11 at 12 01 40](https://user-images.githubusercontent.com/910241/30269479-3bde9186-96e9-11e7-9398-4778800aaea9.png)

**Comment by NejcZdovc** [comment] 2017-09-11 10:34
closing this as a duplicate of #3555. Thank you for the report

**Closed by NejcZdovc** 2017-09-11 10:34 UTC
