### ISSUE TITLE
Add a history sub-menu to the hamburger (kabob)

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#6934] opened 2017-01-31 00:10 UTC
similar to chrome:

![image](https://cloud.githubusercontent.com/assets/13509546/22447273/747fed3e-e706-11e6-9136-54ddb50905c4.png)

cc: @srirambv

**Comment by kumarrishav** [comment] 2017-05-06 14:57
@bradleyrichter will Options in history submenu be same as what is there in History menu at tool bar (at top) ? Because, in chrome it's not exactly same. Can we have mocks for same?

**Comment by bradleyrichter** [comment] 2017-05-08 17:20
@kumarrishav you are correct. The back-button history list only shows the history chain for that tab. The menus (in all cases) need to show the top N number of chronological history entries.

A mockup doesn't really show this well so I will dig up the other issue for main menus and link them.

**Comment by kumarrishav** [comment] 2017-05-15 09:07
Ok. Thanks @bradleyrichter

**Comment by kumarrishav** [comment] 2017-05-16 13:45
currently i have added these submenu. Is it fine? or should be add more as it is in toolbar.
@bradleyrichter 
<img width="658" alt="screen shot 2017-05-16 at 7 14 12 pm" src="https://cloud.githubusercontent.com/assets/4078325/26109095/0b305012-3a6c-11e7-9083-629978464f51.png">

**Comment by bradleyrichter** [comment] 2017-05-16 16:30
@kumarrishav This will be good. Keep in mind we will need to update it when the dynamic list is ready. (to show recently closed and recently visited history links)

**Comment by kjozwiak** [comment] 2017-11-29 04:27
Pasting feedback that I added in #10807 (which is basically a duplicate of this):

We should look into ways of improving access to `about:history` for users on Windows. Currently, these are the only ways of accessing `about:history` which isn't really intuitive for the average user:

* Pressing "ALT" and access History in the file menu
* typing in `about:history` under the URL bar
* Going into the Settings -> General and disable "Hide the menu bar by default"

Under macOS/Linux, the File Menu is usually visible the entire time so it's a lot easier to figure out where about:history can be access from.

I personally think we should add access to about:history in the following locations:

* adding History under the Brave menu
* adding History access under about:preferences#security (currently you can only clear)

**Comment by kjozwiak** [comment] 2018-03-26 02:51
+1 from my brother. He was using Brave while he was online shopping and wanted to check his history for something he was previously looking at but closed earlier. He couldn't find a way to access `History` via the kabob so ended up searching for a solution via Google.

**Comment by srirambv** [comment] 2018-06-28 12:52
+1 from https://community.brave.com/t/add-history-icon-to-url-bar/26376 for adding shortcut in URL bar

**Comment by srirambv** [comment] 2018-06-28 12:53
Btw this should be fixed in brave-core as built-in feature. @bradleyrichter still ok to keep the issue open?

**Comment by bsclifton** [comment] 2018-06-28 15:49
@srirambv I think it's fair to say we won't be able to get to this with browser-laptop. Since it's fixed with Brave Core, let's close it out 😄 👍

**Closed by bsclifton** 2018-06-28 15:49 UTC
Labels: bug/good-first-bug, feature/context-menu, help wanted, parity, priority/P5
