### ISSUE TITLE
child "platform" fails (on Ubuntu 14.04)

### ISSUE THREAD

**Issue by stuartlangridge** [brave/browser-laptop#345] opened 2016-01-26 20:33 UTC
Error message output to console after `npm start`:

    { statusCode: 400,
      error: 'Bad Request',
      message: 'child "platform" fails because ["platform" must be one of [winx64, osx]]',
      validation: { source: 'params', keys: [ 'platform' ] } }

There is no indication of what caused this, afaict; it may have appeared while browsing theguardian.com.

**Comment by Tribex** [comment] 2016-01-27 17:32
Same on Ubuntu 15.10 here.

**Comment by iamtjg** [comment] 2016-02-03 00:17
I have not been able to tie it to anything directly either yet.  Once this error occurs new sites/pages do not render but sites already loaded continue to function.

**Comment by luixxiul** [comment] 2016-05-14 17:08
Does this issue still exist for the latest version?

**Comment by luixxiul** [comment] 2016-05-22 16:31
Not reproducible on Ubuntu 14.04, closing

**Closed by luixxiul** 2016-05-22 16:31 UTC

**Comment by Tribex** [comment] 2016-05-22 19:32
Just for the record, unable to reproduce on 16.04.
