### ISSUE TITLE
Impossible to add bookmark with empty name

### ISSUE THREAD

**Issue by frenchbread** [brave/browser-laptop#8957] opened 2017-05-19 13:58 UTC
### Feature request

> It's impossible to add a bookmark without name, so that only bookmark icon is visible in the bookmarks bar, like in Google Crome.

Would like to see that feature in Brave for laptop (macOS) browser.

**Comment by bradleyrichter** [comment] 2017-05-19 17:11
@frenchbread for now, you can add a space to act as the empty name...

**Comment by sjlehn** [comment] 2017-08-07 14:12
Possible duplicate of #2972

**Comment by Liunkae** [comment] 2017-08-07 17:49
Thanks @sjlehn! Closing as duplicate of #2972.

**Closed by Liunkae** 2017-08-07 17:49 UTC
Labels: feature/bookmarks

**Comment by frenchbread** [comment] 2017-08-08 13:11
Thanks
