### ISSUE TITLE
need to toggle cookie control for some sites to display properly

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10418] opened 2017-08-10 21:20 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
In previous versions (0.17.x, 0.18.14, 0.18.20), sites used for testing like https://jsfiddle.net/bkf50r8v/13/ (and other jsfiddle sites in our test wiki) displayed normally with default shield settings. With 0.18.21, to get these sites to display properly you must change the cookie setting from 'Block 3rd party cookies' to something else and then back to 'Block 3rd party cookies'. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
0.18.21

- Steps to reproduce:
    1. Navigate to https://jsfiddle.net/bkf50r8v/13/ with default shield settings. (I was using a clean profile on 0.18.21)
    2. Notice right side of page is not displaying properly.

    
- Actual result:
Page does not display correctly with default shields. You have to toggle cookie setting to something else and then back to 'Block 3rd party cookies' (the original setting) to get it to display properly.

- Expected result:
page should display properly with default settings the first time you navigate to it.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
no

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
Actual:
![screen shot 2017-08-10 at 4 34 02 pm](https://user-images.githubusercontent.com/28145373/29192600-fa80f7ae-7def-11e7-94ab-6f7887f1180f.png)

Expected:
![expected](https://user-images.githubusercontent.com/28145373/29192666-3041fc08-7df0-11e7-84b2-49b04212f57e.png)

- Any related issues:

**Comment by luixxiul** [comment] 2017-08-11 03:59
After allowing the 3rd party cookie once and reset the setting, the issue is no longer reproduced for me.

**Comment by luixxiul** [comment] 2017-08-11 04:10
on devtool:

````
(index):92 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://fiddle.jshell.net/bkf50r8v/13/show/:92:13
analytics.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
(index):92 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://fiddle.jshell.net/bkf50r8v/13/show/light/:92:13
analytics.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
(index):92 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://fiddle.jshell.net/bkf50r8v/13/show/light/:92:13
analytics.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
````

**Comment by bsclifton** [comment] 2017-08-11 05:23
This seems to be fixed with the latest code- I'll close and we can retest when the next binary is ready 😄   Here's a screenshot
![screen shot 2017-08-10 at 10 22 48 pm](https://user-images.githubusercontent.com/4733304/29202200-90bd90ea-7e1a-11e7-9d3c-1d181a885160.png)

**Closed** 2017-08-11 05:24 UTC
Labels: bug, feature/shields, needs-triage, regression
