### ISSUE TITLE
crash with error code 3489660927

### ISSUE THREAD

**Issue by jayyyin** [brave/browser-laptop#13589] opened 2018-03-24 18:10 UTC
### Description
browser crashed after switching to other things and after waiting a while and returning to the browser it crashed

### Steps to Reproduce

  1. launch brave via npm start
  2. wait
  3. crash

**Actual result:**
crash

**Expected result:**
not crashing

**Reproduces how often:**
unsure

### Brave Version

**about:brave info:**
 
Brave: 0.22.0 
V8: 6.5.254.41 
rev: 68ecb3889d7eea6f14fb9303bb0f792258564bda 
Muon: 5.1.1 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**
master build

### Additional Information
honestly unsure how to reproduce it

**Comment by kjozwiak** [comment] 2018-03-26 00:37
Thanks for the bug report @jayyyin! However, this seems like a duplicate of #13224. If you have any more information, please add it into #13224.

**Closed by kjozwiak** 2018-03-26 00:37 UTC
