### ISSUE TITLE
Youslist (Korean adblock list) block CSS and images

### ISSUE THREAD

**Issue by zn** [brave/browser-laptop#6850] opened 2017-01-25 07:29 UTC
- Did you search for similar issues before submitting this one?
: Yes

- Describe the issue you encountered:
: Enabling Youslist from adblock setting cause website problem.

- Platform (Win7, 8, 10? macOS? Linux distro?):
  - Windows 10
  - Linux (Arch Linux with "brave-bin" package from AUR)
  - Android (Nexus 6P, downloaded latest version from Play store)
- Brave Version (revision SHA)
: 0.12.15 (Downloaded from releases page)

- Steps to reproduce:
    1. (on PC) Enable "Youslist" on "Manage Adblock settings..." page
    1. (on Android) Enable "Regional Ad block" option
    2. Visit websites below

- Affected websites:
  * http://www.naver.com/ - doesn't load CSS and images.
  * http://www.msn.com/ko-kr/ - show "This page is not available right now" error.
  * http://www.microsoft.com/en-us/ - doesn't load CSS and images.
  * https://www.youtube.com/ - doesn't load CSS and images.
  * http://www.daum.net/ - doesn't load images.
  * http://www.nate.com/ - doesn't load some images.
  * https://myanimelist.net/ - doesn't load CSS and images.
  * https://www.reddit.com/ - doesn't load CSS and images.
  * https://www.opera.com/ko - doesn't load CSS and images.
  * https://www.heroku.com/ - doesn't load CSS and images.
  * https://www.openshift.com/ - doesn't load CSS and some images.
  * https://www.haskell.org/ - doesn't load some images. (in Videos section)
  * https://www.smashingmagazine.com/ - doesn't load logo.
  * http://elixir-lang.org/ - doesn't load font.
  * https://en.wikipedia.org/ - doesn't load images. (except logo)
  * https://lifehacker.com/ - doesn't load images.
  * https://www.engadget.com/ - doesn't load CSS and images.
  * https://techcrunch.com/ - doesn't load CSS and images.
  * https://github.com/brave/ - doesn't load Brave logo and user's avatar images.

- Actual result
: described above.

- Expected result
: load CSS and images without problem like other web browers (Firefox or Chrome + ublock Origin works without problem.)

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
: Yes. I tried on fresh profile

- Is this an issue in the currently released version?
: Not sure but it seems this bug exists on old version (0.12.x)

- Can this issue be consistently reproduced?
: Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment] 2017-01-25 08:05
Because the list which ad-block uses is too strict?

**Comment by zn** [comment] 2017-01-25 08:42
After some trial, I found the problematic line: `*/RealMedia/ads/`.

Just disable all list and insert `*/RealMedia/ads/` at "Custom filters" cause same issue described above. and also `*/RealMedia/`, `*/RealM`, `*/ads` has same issue.

But, inserting one of `*/RealMedia/ad/`, `*/RealMedia/ads/blabla`, `*/RealMedii`, `*/REalMedia` has no problem.

**Comment by luixxiul** [comment] 2017-01-25 09:02
@bbondy actually when I enable `*/RealMedia/` uploading a file on this page by selecting the file is blocked. Do you think it should not happen?

**Comment by luixxiul** [comment] 2017-01-25 09:06
Also no images on a PR page: 

<img width="1052" alt="screenshot 2017-01-25 18 04 36" src="https://cloud.githubusercontent.com/assets/3362943/22284087/ecb1bb48-e328-11e6-854a-b4c7cdab3944.png">

**Comment by luixxiul** [comment] 2017-01-27 01:33
I opened #6883 for the custom filter issue.

**Comment by bbondy** [comment] 2017-01-27 16:11
This seems to be because of this problem:
https://github.com/brave/ad-block/issues/33

I'll try to fix for 0.13.1.  @luixxiul given this new info, I think this is a dupe of #6883, if you agree please close one of the 2. Thanks!

**Closed** 2017-01-27 16:18 UTC
Labels: feature/adblock, l10n
