### ISSUE TITLE
error page has wrong URL (or else navigating via address bar doesn't replace it)

### ISSUE THREAD

**Issue by BrendanEich** [brave/browser-laptop#2302] opened 2016-06-25 00:10 UTC
**Did you search for similar issues before submitting this one?**

Yes.

**Describe the issue you encountered:**

On presumed wifi transient outage (several tabs were hit at once), I saw an error page at first position in session history (Back and Forward buttons grayed out), offering a link to retry loading https://twitter.com, with the address bar containing "https://twitter.com".

Clicking the retry link worked, but moved forward one in session history, enabling the Back button, leaving the error page at first position in shist.

Focusing the address bar and hitting Enter did nothing.

**Expected behavior:**

Clicking the retry link replaces the current and only position in shist.

Focusing the address bar and hitting enter should load the URL shown there, but in this case that URL was not consistent with the error page contents, so perhaps we want an about:error URL?
- Platform (Win7, 8, 10? macOS? Linux distro?):

Mac OS X El Capitain
- Brave Version:

0.10.4.
- Steps to reproduce:
  1. Load twitter.com
  2. Click on notifications
  3. Turn off wifi
  4. Go back

/be

**Comment by bsclifton** [comment] 2017-07-19 21:28
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/2025

**Closed by bsclifton** 2017-07-19 21:28 UTC
Labels: bug, needs-investigation
