### ISSUE TITLE
about:newtab : date time is displayed in the wrong format

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6303] opened 2016-12-19 23:21 UTC
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
opening the new tab shows date time in the wrong format

**Expected behavior:**
date time should be in a 12 hour clock format

- Platform (Win7, 8, 10? macOS? Linux distro?):
tested on os x

- Brave Version:
0.13.0 Preview 5

- Steps to reproduce:
    1. clear the /brave folder
    2. open 0.13.0 preview 5

- Screenshot if needed:
<img width="1233" alt="screen shot 2016-12-19 at 5 18 51 pm" src="https://cloud.githubusercontent.com/assets/1434040/21332651/84947e00-c60f-11e6-90d7-8305ee402dc3.png">

- Any related issues:

**Comment by bsclifton** [comment] 2016-12-20 00:11
Duplicate of https://github.com/brave/browser-laptop/issues/5879

Will be fixed when next build uses updated muon

**Closed by bsclifton** 2016-12-20 00:11 UTC
Labels: bug, release/blocking
