### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tab' when right clicking on tabs

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#10698] opened 2017-08-29 05:29 UTC
**- Did you search for similar issues before submitting this one?**
Yes

**- Describe the issue you encountered:**
Right clicking on tabs via the tab bar under `0.20.0` will produce the following errors under the browser console:

```
Uncaught TypeError: Cannot read property 'tab' of undefined tabUtil.js:49 
    at module.exports.hasTabAsRelatedTarget.event (tabUtil.js:49)
    at Tab.onMouseLeave (tab.js:140)
    at Object.ReactErrorUtils.invokeGuardedCallback (ReactErrorUtils.js:69)
    at executeDispatch (EventPluginUtils.js:85)
    at Object.executeDispatchesInOrder (EventPluginUtils.js:105)
    at executeDispatchesAndRelease (EventPluginHub.js:43)
    at executeDispatchesAndReleaseTopLevel (EventPluginHub.js:54)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (forEachAccumulated.js:24)
    at Object.processEventQueue (EventPluginHub.js:254)
```

Under Windows, you can basically reproduce it every single time you right click on any tab. With macOS, it's a bit tricker. You'll need to open about:brave and use that rather than any tab. STR are listed below.

**- Platform (Win7, 8, 10? macOS? Linux distro?):**
Win 10 x64 - Reproducible
macOS 10.12.6 x64 - Reproducible

**- Brave Version (revision SHA):**

> Brave 0.20.0 rev 6fe9849cd3aea3faddf379b96fddb7abdecdd247
> Muon 4.4.11
> libchromiumcontent 60.0.3112.101

**- Steps to reproduce under Windows 10 x64:**
    1. Open the DevTools via "SHIFT + F8" and select "Console"
    2. Right click on any tab that's currently opened

**- Steps to reproduce under macOS 10.12.6 x64:**
    1. Load about:brave
    2. Open the DevTools via "Fn + Shift + F8" and select "Console"
    3. Right click on the about:brave tab and then click inside the page
    
**- Actual result:**
Receiving a `Uncaught TypeError: Cannot read property 'tab' of undefined` error in the browser console

**- Expected result:**
There shouldn't be any error messages being logged in the browser console.

**- Will the steps above reproduce in a fresh profile? If not what other info can be added?**
Yes

**- Is this an issue in the currently released version?**
No, only reproducible under `0.20.x`

**- Can this issue be consistently reproduced?**
Yes, 100% reproducible using the above STR

**- Screenshot if needed:**

<img width="557" alt="screen shot 2017-08-29 at 12 47 25 am" src="https://user-images.githubusercontent.com/2602313/29804846-adc27196-8c53-11e7-8ea5-79c6550b4bc9.png">

**Comment by NejcZdovc** [comment] 2017-08-29 05:53
closing as a dupe of #10590

**Closed by NejcZdovc** 2017-08-29 05:53 UTC
Labels: bug, feature/context-menu
