### ISSUE TITLE
Url bar doesn't appear when i hover with mouse

### ISSUE THREAD

**Issue by rivenblades** [brave/browser-laptop#12440] opened 2017-12-29 16:46 UTC
When the url is hidden and i want to write some url link,i hover at it,
but the bar doesn't appear active so i can't write.

I have to press alt for it to make it active in order to write.

i have multiple tabs open
Reproduce:
When i press new tab,the url bar is active
but when i go into a site (let's say github.com)and getting the mouse out of the url bar,the bar gets hidden
and when i try to write a new url it doesnt get active.
Only if i hover at the small lock icon left to the (lock)"github.com | Github" it appears after hovering for 1 sec

**Comment by Alino** [comment] 2018-01-06 03:41
I cannot reproduce, can you give please more details?

I tried the following reproduce steps
1. CTRL + T (open new tab)
2. type "github.com"
3. press enter
4. CTRL + L (select url in address bar)
5. press "g" (to see suggestions for github)
6. Mouse out of the url bar

The bar is not getting hidden

**Comment by rebron** [comment] 2018-09-20 07:29
Closing. Fixed with brave-core.

**Closed by rebron** 2018-09-20 07:29 UTC
Labels: feature/URLbar, fixed-with-brave-core

**Comment by rivenblades** [comment] 2018-09-22 12:57
This is FIXED so it is closed!

**Comment by Saloha** [comment] 2018-09-22 18:55
12:30, 20 сентября 2018 г., Rafael Ebron <notifications@github.com>:Closing. Fixed with brave-core.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Saloha** [comment] 2018-09-23 20:45
22 сент. 2018 г. 11:54 ПП пользователь Саня Салоха <saloha.san@yandex.ru> написал:12:30, 20 сентября 2018 г., Rafael Ebron <notifications@github.com>:Closing. Fixed with brave-core.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Saloha** [comment] 2018-10-07 22:18
Google Photos

Александр Солонин: Этоя

View photos here:  
https://photos.google.com/share/AF1QipMNbwK2CNHkPlwWpm4vBYOPWQC_-UmZWnoSZHn0tKpwMsWhKvFk0b6LRMdM3UTbZA?key=c2JxQmZuT2lJVDRiT3J2VWdpdzZDMzZ6STFFcHJB

You received this mail because Александр Солонин shared these photos with  
you. If you no longer wish to receive email notifications of shared photos,  
unsubscribe here:  
https://notifications.google.com/unsubscribe/AJ7SsMm3cVmD0qnbl5ciMiwMQzSl1BKMSVNKnsCPvOqHGus86Ix8LV7wOdUmbkXC4eINPAON2P2xjF0xp6m6t3tg6cahZ-WQFWkvVQr-O3W-bQY5RzX3YsD0hk1hfl0k-4xHGZ8BaSHz_gTe4RxoDI5k0sGO_SP2M57dDWT_kI0MHeWagFk5_KwYx6xBh__8-lI1fvbMleNHLsUeeKktvaOxDPDkR3kTAFgQpPIxmN26b9qLloG1gOJ_vDG4D1ctE_inEVekwS8U

Get Google Photos (https://google.com/photos)

Google LLC, 1600 Amphitheatre Pkwy, Mountain View, CA 94043 USA
