### ISSUE TITLE
Brave can't scroll down in this website

### ISSUE THREAD

**Issue by Miguelcldn** [brave/browser-laptop#4508] opened 2016-10-04 17:41 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
In this website I can't scroll down https://blog.google/products/pixel/introducing-pixel-our-new-phone-made-google/

**Expected behavior:**
I should scroll down as in chrome or any other browser when using the mouse wheel, dragging the side-scroll or pressing the Down arrow / AvPag.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.3

- Steps to reproduce:
    1. Go to https://blog.google/products/pixel/introducing-pixel-our-new-phone-made-google/
    2. Try to scroll down in any way.

- Config screenshot:
![image](https://cloud.githubusercontent.com/assets/5544266/19085403/2eac8568-8a38-11e6-9c33-178fa8bf6c81.png)

**Comment by AaronLenoir** [comment] 2016-10-04 20:24
Is this different than #4472?

If I open the page you have here, I can scroll. Did you open it by clicking into it from another website? Possibly, the "target" property of the hyperlink was set there. Apparently this could cause issues with the scrolling.

**Comment by admiral142** [comment] 2016-10-04 21:37
I have had scrolling issues since the latest update as well.  They vary from not being able to scroll at all, to the page autoscrolling to the bottom of the page upon loading, to erratic scrolling.  Sometimes I have no problems at all.  It seems to happen after a certain period of time; I've found that closing the browser and reopening it fixes it for a while.

**Comment by bsclifton** [comment] 2016-10-04 23:26
@Miguelcldn I followed the link you provided (both clicking it and also pasting into URL bar) but was not able to reproduce. Do you encounter the problem if you open a new tab and paste the URL in there?

**Comment by bsclifton** [comment] 2016-10-05 00:02
Closing this issue as a duplicate (please reopen if it's not)

@Miguelcldn and others - please check out https://github.com/brave/browser-laptop/issues/4472 and subscribe to be notified of the latest status (and sorry about this bug :frowning_face: )

**Closed by bsclifton** 2016-10-05 00:02 UTC
Labels: duplicate

**Comment by Miguelcldn** [comment] 2016-10-05 19:07
Oh, I didn't consider the fact that I opened it with mouse wheel click. Guess it's a really hard-to-find bug >.<
