### ISSUE TITLE
Awful Fallback Font

### ISSUE THREAD

**Issue by Mahdyar** [brave/browser-laptop#14925] opened 2018-08-02 18:31 UTC
Hi , 
I use latest version of brave in linux , and i have a tiny problem with fallback font because it doesn't show persian texts beautifully :
![ss](https://user-images.githubusercontent.com/20593549/43603336-e998aca8-96a7-11e8-81d2-ebc45e3f06a3.png)
I guess if you'll add optional font setting in settings , we'll be okay !

**Comment by bsclifton** [comment] 2018-08-09 20:26
I have confirmed this is fixed with [brave-core](https://github.com/brave/brave-browser)! We won't be fixing before then unfortunately (so I'll close this issue as `wontfix`, since `browser-laptop` won't get the fix).

![screen shot 2018-08-09 at 1 25 00 pm](https://user-images.githubusercontent.com/4733304/43923829-b041dcba-9bd7-11e8-896e-f6c308e50346.png)

**Closed by bsclifton** 2018-08-09 20:26 UTC
Labels: fixed-with-brave-core, l10n, usability
