### ISSUE TITLE
Hide / change "Operating System" from User-Agent Strings

### ISSUE THREAD

**Issue by RobertoMalatesta** [brave/browser-laptop#1945] opened 2016-05-27 16:02 UTC
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
No way to hide or change Operating System in User-Agent Strings
**Expected behavior:**
I want to be able NOT give info on my OS to web sites
- Platform (Win7, 8, 10? OS X? Linux distro?):
  Linux in the specific but I guess all other OSes show same behavior.
- Brave Version:
  0.10
- Steps to reproduce:
  1. go to any site that can detect your browser settings, i.e.: http://www.whatsmybrowser.org/
  2. the server detects your Operating System correctly
- Screenshot if needed:
  None
- Any related issues:
  None

Thank you for all the good work.

--RM

**Comment by luixxiul** [comment] 2016-08-06 14:02
+1 from support

**Comment by bbondy** [comment] 2016-08-07 18:33
perhaps optional since the average person would probably prefer this so they are given the right download links etc.

**Comment by RobertoMalatesta** [comment] 2016-09-07 14:36
@bbondy optional for sure, but easily reachable.
Something like Chrome or Opera User-agent Switchers ann-ons.
--R

**Comment by srirambv** [comment] 2018-02-12 02:52
+1 from https://community.brave.com/t/user-agent-leak/15435/8

**Comment by bsclifton** [comment] 2018-08-07 05:41
Closing in favor of https://github.com/brave/browser-laptop/issues/14852 (which is a duplicate of this, but has some more information / discussion)

**Closed by bsclifton** 2018-08-07 05:41 UTC
Labels: privacy, suggestion

**Comment by RobertoMalatesta** [comment] 2018-08-08 22:46
No problem.
I resolved this issue by heavy   intervention in the V8 engine.
