### ISSUE TITLE
file:// browsing should show directory content

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6389] opened 2016-12-22 16:11 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When browsing my local machine, I found that it would not list local directory contents the same as Chrome. 

**Expected behavior:**
Local directory content should be visible and navigable.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.13.0 (6a1a43b22d19847c846e99e9e7c5e3242d33056d)
- Steps to reproduce:
    1. On OS X, open a location like file:///Users/

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment] 2017-04-03 03:30
Duplicate of #1615.

**Closed by Liunkae** 2017-04-03 03:30 UTC
Labels: bug
