### ISSUE TITLE
Pinned Tab remains pinned after closing it, unpinning, and restarting the browser.

### ISSUE THREAD

**Issue by ilgan** [brave/browser-laptop#15094] opened 2018-08-27 17:24 UTC
### Description
Pinned tab remains as pinned after unpinning it or closing and then restarting the browser

### Steps to Reproduce
  1. Pin a tab
  2. Unpin it or manually close it
  3. Restart the browser

**Actual result:**
Pinned tab appears as pinned again.

**Expected result:**
Pinned tab is actually closed and not pinned.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.23.79
V8 | 6.8.275.24
rev | 51b4905
Muon | 8.0.7
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Comment by eljuno** [comment] 2018-08-27 19:52
Duplicate of #13185

**Closed** 2018-08-28 05:28 UTC
