### ISSUE TITLE
Device/responsive mode (mobile inspector) in dev tools

### ISSUE THREAD

**Issue by kanatzidis** [brave/browser-laptop#7386] opened 2017-02-25 12:49 UTC
Is "Device Mode" or "Responsive Mode" available in Brave? I couldn't find an option anywhere on the dev tools and I don't see any issues about this. This is an obstacle to making Brave my default browser for development. Let me know if I missed it/if there will be plans to support this.

**Comment by SethClydesdale** [comment] 2017-03-03 18:50
I couldn't find it either ( aside from the devices in the devtools settings ), so I don't think it's currently available. I switched Brave over to my default browser recently, because it has improved a lot since the last time I used it, but the lack of a device mode forces me to switch to another browser to test responsiveness / mobile emulation while I'm designing. 

Anyway, I just want to say that I'm hoping to see this feature added in a future update, so keep up the good work.

**Comment by ChubbyNinja** [comment] 2017-04-06 13:20
Yeh this is important if web developers are going to be using the browser... having to switch back to chrome to develop responsive views now :cry:

**Comment by airbr** [comment] 2017-04-22 16:23
This issue is a not-insignificant barrier to me adopting and using Brave browser more regularly as checking on how websites appear on mobile devices is pretty important development. An update on status of this would be good

**Comment by guzgarcia** [comment] 2017-04-28 02:48
Really it's important. Do you plan implement it soon?

**Comment by ChubbyNinja** [comment] 2017-05-05 08:23
Would like some indication as to if this is going to be added? Some acknowledgement, otherwise web-developers might as well stop using Brave as their main browser and go back to FF or Chrome.

We are desperately in need of the following:

- [ ] Responsive/Mobile mode for devtools
- [ ] Ability to re-send XHR requests through devtools
- [ ] Re-focus the devtools when they are already open. If you have them open but minimised or behind a window, right click inspect on an element the devtools should come into focus

**Comment by nyedidikeke** [comment] 2017-05-06 19:18
Any update on the current state of these feature requests please?

**Comment by deathg0d** [comment] 2017-05-11 05:20
Hybrid app development without this feature was impossible for me. Also the inability to open dev tools inline with the webpage is annoying in laptops. Switching back to chrome for now. Would love to hear updates regarding this topic.

**Comment by bovas85** [comment] 2017-06-13 12:58
why is this still unassigned/

**Comment by ChubbyNinja** [comment] 2017-06-13 13:44
The lack of response from the devs is a shame, i know they're busy but this is more than just a cosmetic issue, some acknowledgement would be good

**Comment by bsclifton** [comment] 2017-06-13 18:35
Hey there folks,

Apologies that we haven't taken time to talk to this issue yet ☹️   Improving the developer tools and the developer experience is a very important thing for us.  Besides this issue, we also have a few other important issues captured:
- Allow attaching developer tools (F12) to the tab frame #3555
- Various Developer Tools features are broken #6724
- 'Inspect Element' should refocus developer tools #6605

We plan to get to these issues as soon as possible, but I can't give an ETA.  I promise these features are important to us. We do understand they are really important to our users who use Brave for development.  Thanks for your patience 😄

**Comment by luixxiul** [comment] 2017-08-10 05:52
+1 from https://github.com/brave/browser-laptop/issues/10385

**Comment by Liunkae** [comment] 2017-08-14 22:40
I noticed that the browser-level developer tools has this feature.
![image](https://user-images.githubusercontent.com/19424103/29294985-a355752e-8117-11e7-912a-888152c7cf4f.png)

**Comment by Bloggerschmidt** [comment] 2017-08-23 13:23
I cannot confirm @Liunkae note. Version 0.18.23 has not this feature, unfortunatly )-:

**Comment by Liunkae** [comment] 2017-08-23 15:35
@Bloggerschmidt There's a difference between the **content-level** dev tools (for debugging websites, `Alt+Cmd/Ctrl+I`) and the **browser-level** dev tools (for debugging the browser itself, `Shift+F8`). Since the browser-level developer tools already have the feature, I'm not sure why the content-level developer tools don't have it.

**Comment by Bloggerschmidt** [comment] 2017-08-23 15:51
@Liunkae Ah I see, thanks for clearifying the levels.

**Comment by eljuno** [comment] 2017-08-30 20:52
+1 from community https://community.brave.com/t/element-inspector-toggle-device-feature-missing/6866?u=eljuno

**Comment by datelligence** [comment] 2017-12-20 21:17
Brave as a browsing vehicle is awesome,  however when used in the context of web developing is mediocre, due to the many flaws,  brave's dev tools is full with:
1) no way to use the device - screen simulator,  which is essential.
2) devtools acreen cannot be attached to the page one is working,  is just another window.  Not comfortable.
3) the lack of Vimium / Vimperator .  We developers love it, need it,  can't live without it.

These complains have more one year going over the web,  however we don't see any commit,  any improvement.  Sad!

**Comment by tomasdev** [comment] 2018-02-12 18:48
@bsclifton I see all these issues aren't in a clear roadmap (no version tagging, most in backlog or triage)

Should we keep using Chrome for dev?

**Comment by airbr** [comment] 2018-02-14 00:58
Encouraging words/I brought this to the attention of Brendan Eich: https://twitter.com/BrendanEich/status/963577074098122753

**Comment by bsclifton** [comment] 2018-02-14 06:44
@tomasdev as folks have noticed, we definitely have work to do in this area ☹️

 I'd say to continue using what you feel comfortable with when developing for now (Firefox, Chrome, etc). We have [several issues capturing dev tools issues](https://github.com/brave/browser-laptop/labels/feature%2Fdeveloper-tools) and are slowly making progress with regards to delivering them

**Comment by bsclifton** [comment] 2018-08-09 21:03
I've confirmed this is available in [brave-core](https://github.com/brave/brave-browser) 😄 
![screen shot 2018-08-09 at 2 02 58 pm](https://user-images.githubusercontent.com/4733304/43925760-0a2eac08-9bdd-11e8-8848-fd3e38f3be1a.png)


Closing this issue (for browser-laptop/Muon) as `wontfix` since we'll get this functionality when we move over

**Closed by bsclifton** 2018-08-09 21:03 UTC
Labels: feature/developer-tools, fixed-with-brave-core
