### ISSUE TITLE
why do not you remove it?

### ISSUE THREAD

**Issue by gameb0y** [brave/browser-laptop#3486] opened 2016-08-27 18:37 UTC
![untitled](https://cloud.githubusercontent.com/assets/19530450/18029346/c0d107d4-6ca6-11e6-94ab-c40dfd26cdd5.jpg)

**Comment by diracdeltas** [comment] 2016-08-27 18:49
turn on fingerprinting protection

**Comment by diracdeltas** [comment] 2016-08-27 18:49
nvm comment above, i thought you meant the IP issue. this is a dupe of #1883

**Closed** 2016-08-27 18:49 UTC
Labels: duplicate

**Comment by gameb0y** [comment] 2016-08-28 07:03
![untitled](https://cloud.githubusercontent.com/assets/19530450/18032200/bd17e712-6cdc-11e6-83ee-3e5cdd848de6.jpg)

w7 x64 / brave x64
