### ISSUE TITLE
Balance of bitcoin can show a scary 0 value when no connection

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3785] opened 2016-09-07 02:12 UTC
1. Close browser
2. Turn internet off
3. Open browser
4. Open prefs -> Payments

Actual result: Shows balance of 0
Expected result: Shows some kind of an error that the data could not be retrieved

Likely alternate way to reproduce, turn off remote service.

**Comment by Aeyoun** [comment] 2016-09-07 11:14
Duplicate of ##3778.

**Comment by bbondy** [comment] 2016-09-07 14:30
Thanks, closing as a dupe.

**Comment by bbondy** [comment] 2016-09-07 15:09
It might have a diff fix, will re-open for now.

**Closed** 2016-09-08 05:03 UTC
Labels: duplicate, ledger integration
