### ISSUE TITLE
Unable to delete / using backspace in homepage field

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10703] opened 2017-08-29 11:40 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Unable to delete / using backspace in homepage field

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.18.23
-- | --
rev | 36ae2ec
Muon | 4.3.10

- Steps to reproduce:
    1. Open preferences 
    2. Ensure there is no forward slash after the URL
    3. Type | after the homepage name, / is added after | , cannot be deleted using backspace
    
- Actual result:
See attached image

- Expected result:
Should be able to delete / using backspace

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![multitabs](https://user-images.githubusercontent.com/17010094/29819000-a4475be6-8cb6-11e7-9f36-84678b76bd8e.gif)

- Any related issues:
cc: @NejcZdovc

**Comment by NejcZdovc** [comment] 2017-08-29 12:57
closing as a dupe of #10657

**Comment by srirambv** [comment] 2017-08-29 13:08
Actually this is not a dupe of #10657. Multiple home pages do work on the latest build and on 0.19.x, the only issue being not able to delete the forward slash that is automatically added after the url.

**Comment by NejcZdovc** [comment] 2017-08-29 13:10
ok then closing it as fixed in #10657

**Closed by NejcZdovc** 2017-08-29 13:10 UTC
Labels: OS/Windows, polish, priority/low, QA/steps-specified
