### ISSUE TITLE
Speaker icon in tab when there is a muted autoplay element

### ISSUE THREAD

**Issue by SpikeShape** [brave/browser-laptop#606] opened 2016-02-04 07:23 UTC
I just noticed this: If there is a video autoplaying in my Facebook timeline the icon for playing sound is shown in the tab. Since there videos are on mute by default the icon should not be there.

The same with the vine homepage, so I assume this happens when there is some multimedia element that is playing automatically no matter if muted or not.
Just as an example: https://vine.co/

**Comment by bbondy** [comment] 2016-02-04 11:44
Dupe of #257

**Comment by bbondy** [comment] 2016-02-04 11:44
Thanks for posting though!

**Closed by bbondy** 2016-02-04 11:44 UTC

**Comment by SpikeShape** [comment] 2016-02-04 12:37
Oh... Sorry. Its rather difficult to avoid duplicates but I will try to find similar tickets next time.

**Comment by bbondy** [comment] 2016-02-04 12:39
no worries, happens to everyone! :)

**Comment by bbondy** [comment] 2016-02-04 12:40
Also the posting of dupes helps link back to the original issue with different search terms more easily.
