### ISSUE TITLE
Auto Popup is not working

### ISSUE THREAD

**Issue by jemspatel** [brave/browser-laptop#3143] opened 2016-08-12 05:24 UTC
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
auto popup is not working
it's block popup's which open after page load
but if popup is open through button click then it's working fine
**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  win10, Linux
- Brave Version:
  0.11.4
- Steps to reproduce:
  1. open site http://popuptest.com/
  2. click on Multi-PopUp Test 
  3. no popup open 
- Screenshot if needed:
- Any related issues: #94

**Comment by mistrimehul** [comment] 2016-08-17 05:25
same here, auto window popup not working on page load.

**Comment by bsclifton** [comment] 2017-08-14 17:28
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/3752

**Closed** 2017-08-14 17:29 UTC
Labels: bug, duplicate
