### ISSUE TITLE
Using Alt+Tab in windows sometimes shows the File/Edit/View/History menu

### ISSUE THREAD

**Issue by tetrode** [brave/browser-laptop#1157] opened 2016-03-23 22:24 UTC
Scenario:
- start brave
- switch from brave using Alt-Tab to e.g. Windows Explorer
All is working OK
- start brave
- create a new window (ctrl+N)
- switch between windows using Alt-Tab
Depending on which key is released first, sometimes the File/Edit/... menu shows. When clicking in the window, the menu disappears
Expected behaviour 
- Menu only appears when pressing and them releasing the Alt key
Actual behaviour
- Menu also appears in this use case (Alt+Tab key)

**Comment by luixxiul** [comment] 2016-05-22 08:31
Do you still encounter this error? I cannot reproduce it.

**Comment by tetrode** [comment] 2016-05-23 09:47
no can't reproduce it anymore

**Comment by luixxiul** [comment] 2016-05-23 09:48
I see, closing for now. If you encounter this error again please leave a comment to reopen this issue. Thanks.

**Closed by luixxiul** 2016-05-23 09:48 UTC
