### ISSUE TITLE
MP4 not loading in Win10

### ISSUE THREAD

**Issue by joshuaHutton** [brave/browser-laptop#3120] opened 2016-08-11 09:26 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When viewing a gif on various websites including 9gag, imgur and facebook the gif does not load it and goes black. 

**Expected behavior:**
It should play the gif
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win10
- Brave Version:
  0.11.4
- Screenshot if needed:
  ![capture](https://cloud.githubusercontent.com/assets/17587215/17584309/0f50283e-5fb6-11e6-8e8c-82fb8c9b2d7a.PNG)
- Any related issues:

**Comment by neeklamy** [comment] 2016-08-11 10:05
I’m seeing that post content just fine ([9GAG: To be good to be athlete!](http://9gag.com/gag/aK3EWX3/to-be-good-to-be-athlete)). As I said on a comment to #2676, **this isn’t a GIF, despite what the surrounding content may tell us.**

Open up the developer tools → Inspect Element (and search for “.mp4”).

@joshuaHutton, what do you have Brave set to block? As it is, I can’t get Brave to *not* show that MP4 video (I’m using OS X), maybe it’s an issue with Windows 10.

Dupe of #257

**Comment by joshuaHutton** [comment] 2016-08-11 10:15
-The webM plays the mp4 version does not. 
-Everything is still in default settings I have not set it up to block anything.
- The issue also appears an windows 8

**Comment by neeklamy** [comment] 2016-08-11 13:52
Just to confirm, if you go to [HTML5test](https://html5test.com/), look at Multimedia, Video, does is say that both H.264 and WebM are supported?

This could be related to #189 (“3d acceleration sometimes causing black window instead of content to render on Windows”), you could try temporarily disabling 3D, here’s a brief guide:[How to lower hardware acceleration in Windows 7/8/10](https://help.aol.com/articles/how-to-lower-hardware-acceleration-in-windows-7-8).

**Comment by bsclifton** [comment] 2016-08-11 14:50
Thanks for digging in on this one @neeklamy :smile: 

I agree- this is not an issue w/ GIFs (I updated the issue title).  @joshuaHutton does the page load fine in other browsers (Chrome)? Also, please do try @neeklamy's suggestion of temporarily disabling 3D

**Comment by joshuaHutton** [comment] 2016-08-12 06:24
My PC is running hybrid intel AMD graphics it does not allow disabling hardware acceleration. 
The mp4's work in chrome, firefox and even internet explorer.
The html 5 test shows H.264 and webM are supported.

**Comment by luixxiul** [comment] 2017-01-21 17:07
Closing this due to lack of info

**Closed by luixxiul** 2017-01-21 17:07 UTC
Labels: info-needed, OS/Windows
