### ISSUE TITLE
Ever 30 minutes or under the browser will run at 3 fps for no reason. 

### ISSUE THREAD

**Issue by LethalManBoob** [brave/browser-laptop#13016] opened 2018-02-05 12:35 UTC
Zilch. Nada. Nothing in my task manager nor deleting all the caches and history's in the world fixes it. 

Didnt happen until before the "major optimization" update

**Comment by srirambv** [comment] 2018-02-05 12:50
Could you provide more info on this.

**Comment by LethalManBoob** [comment] 2018-02-05 18:33
There's not much more to it. I run brave for about 20 minutes and then
suddenly it runs at 3fps. A reboot being required. Cpu does spike and stay
at 30% on my 6700k though. I reinstalled and haven't had the issue since.
But it could happen at any moment so i dunno. I tried turning on and off
the experimental security option but no change.

Anyway if it happens again i will rule out it being due to a corrupted
update install.

**Comment by LethalManBoob** [comment] 2018-02-06 22:26
It happened again. I even tried updating to the dev version. This needs
addressing.

**Comment by bsclifton** [comment] 2018-02-07 01:05
@LethalManBoob can you visit `about:brave` and copy/paste the details there? Having details about your setup (Operating system, etc) would be useful to help us narrow down the issue. Thanks 😄

**Comment by LethalManBoob** [comment] 2018-02-07 17:40
My Brave Stats


Name
Version
Brave 0.20.30
V8 6.4.388.40
rev 8b78402
<https://github.com/brave/browser-laptop/commit/8b78402e7b3b91d44d8146cbe4dc8013592c33fd>
Muon 4.7.9
OS Release 10.0.16299
Update Channel Release
OS Architecture x64
OS Platform Microsoft Windows
Node.js 7.9.0
Brave Sync v1.4.2
libchromiumcontent 64.0.3282.119

My system stats straight from my dxdiag text save file

https://pastebin.com/raw/XnAhvgZf

**Comment by bsclifton** [comment] 2018-02-14 17:19
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/13087

We are looking into the issue- you can subscribe to that issue for updates

**Closed by bsclifton** 2018-02-14 17:19 UTC
Labels: needs-info, perf
