### ISSUE TITLE
ability to turn off tear off tabs

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11789] opened 2017-11-04 19:36 UTC
### Description
Requested via twitter: (https://twitter.com/ChainMyBlocks/status/926597758215127040)
it would be a _very_ nice feature to have a setting to disable detaching tabs.

### Steps to Reproduce
No STR - just a suggestion to have some kind of setting to disable detach tabs. Would need to ensure tabs could not be detached/reattached using context menu or drag/drop.

**Comment by srirambv** [comment] 2017-11-07 13:24
++1 on this feature

**Comment by luixxiul** [comment] 2017-11-07 13:28
IMHO, after the browser gets so responsive that we would not have to wait until the teared off tabs are able to be re-attached, the option would not become necessary.

**Comment by LaurenWags** [comment] 2018-04-26 13:14
+1 from community: https://community.brave.com/t/click-and-drag-tabs/20851

**Comment by LaurenWags** [comment] 2018-05-17 12:01
+1s from community: https://community.brave.com/t/disable-open-tab-in-new-window-by-dragging-the-tab/13104

**Comment by SilverPuppy** [comment] 2018-06-08 02:07
More community: https://community.brave.com/t/request-to-remove-the-tab-popout-feature/7645/6

This should be able to be disabled. It should NOT go away completely. I actually think it's pretty cool, and can conceive of use-case scenarios for it.

As for the community, I find it slightly amusing and more than a little sad that people want to disable features because they can't slow down enough to watch where they're clicking and dragging. I refrained from saying that in the community, but we're all adults here, right? ;)

**Comment by tarbear123** [comment] 2018-07-26 02:54
or at the least, have a on or off button for it

**Comment by LaurenWags** [comment] 2018-08-27 13:46
+1 from community: https://community.brave.com/t/turning-off-click-and-drag-tabs/30698

**Comment by bsclifton** [comment] 2018-09-03 06:17
This is something we won't fix- but the behavior is much (MUCH) better with [brave-core](https://github.com/brave/brave-browser)

**Closed by bsclifton** 2018-09-03 06:17 UTC
Labels: addressed-with-brave-core, feature/tear-off-tabs, priority/P4, settings, suggestion, wontfix

**Comment by VosWouter87** [comment] 2018-12-07 08:08
I'd like reply to SilverPuppy's comment:

> This should absolutely, positively NOT be removed. This is a pretty cool feature. I agree that it should be able to be disabled. I do occasionally do it by accident, but it really is very easy to pop it right back where it was. Grab the tab itself, not the title bar of the new window.
> 
> Also, while I agree it should be able to be disabled, if you’re popping tabs out into new windows 5 times a day by accident, you may need to adjust what the touchpad on your device interprets as a click-and-drag. Brave’s feature may just be revealing that your touchpad is doing a lot of click-and-drag for no good reason.
> 

This comment was made on the [original thread](https://community.brave.com/t/request-to-remove-the-tab-popout-feature/7645/25) requesting this change, but for some reason I'm unable to comment there.
My reply:
Nobody is asking for the feature to be removed entirely. The problem is that the pop-out is too sensitive. A single pixel change will cause the pop-out, that happens far too easily by accident. Also when you have pinned tabs, simply popping the tab back in still leaves you with an extra window that needs to be closed.

**Comment by bsclifton** [comment] 2019-01-03 16:09
@VosWouter87 I think it's reasonable to ask for disabling this feature

This issue is associated with the older deprecated version of Brave. With the new version (is that what you're using?) the closest issue I found was this (feel free to comment there):
https://github.com/brave/brave-browser/issues/1210

I can help create a new issue for you, just let me know
