### ISSUE TITLE
Brave blocks amazon video as ads

### ISSUE THREAD

**Issue by Mephiztopheles** [brave/browser-laptop#9367] opened 2017-06-09 19:21 UTC
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Brave ad blocks blocks amazon video stream
- Platform (Win7, 8, 10? macOS? Linux distro?):
win 10
- Brave Version (revision SHA):
newest stable?
- Steps to reproduce:
    1. go to amazon.com / amazon.de
    2. go to prime video
    3. start any video with ad block on
    4. disable ad block and retry ... works
    
- Actual result:
video is not loading
- Expected result:
video is loading
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
ya
- Is this an issue in the currently released version?
ya
- Can this issue be consistently reproduced?
ya

**Comment by mkhl** [comment] 2018-09-09 11:09
Has this been fixed? I’m still seeing the problem with version 0.23.105.

**Comment by mkhl** [comment] 2018-09-09 12:01
Without further comment event…
@bsclifton So what now?

**Comment by bsclifton** [comment] 2018-09-09 16:35
\

**Comment by bsclifton** [comment] 2018-09-09 16:38
Hi folks

As we move from the Muon product over to [brave-core](https://github.com/brave/brave-browser), I'm analyzing our issue log (and trying to get the count to 0). I identified this as stale because there weren't any comments on here and the issue had no updates in over 1 year

Can you please try our [developer channel release](https://brave.com/download-dev) and let us know if this is still a problem? If so, I'll move this issue over to the [brave-core](https://github.com/brave/brave-browser) issue backlog and tag you both in it

Please let me know- thanks 😄

**Comment by mkhl** [comment] 2018-09-09 16:48
@bsclifton Yes it’s still an issue in
> Version 0.55.2 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)

> I identified this as stale because there weren't any comments on here and the issue had no updates in over 1 year

There’s a trivially reproducible test case, I’d have assumed that the next step would have been someone working on it?

**Comment by bsclifton** [comment] 2018-09-09 16:50
@mkhl OK great - thanks for the update!  There are a lot of issues (before I started migrating issues over or closing issues, there were over 2,600!) so it's very easy for them to get lost in the mix. As a company, we tend to meet and prioritize the work. With the Muon based browser, a lot of that work was trying to catch up and be feature parity with Chrome/FireFox/etc.  I suspect we'll have a better turn around time in brave-core for this issue

**Comment by bsclifton** [comment] 2018-09-09 16:54
Thanks again for testing on our dev build - I created a new issue to track this work. We won't be able to fix it with our Muon based product (ex: the code in `browser-laptop`).  You can now track this issue here:
https://github.com/brave/brave-browser/issues/1064

**Closed by bsclifton** 2018-09-09 16:54 UTC
Labels: feature/adblock, site-bug, webcompat
