### ISSUE TITLE
Incorrect downloading tooltip message

### ISSUE THREAD

**Issue by gagarin55** [brave/browser-laptop#15197] opened 2018-09-13 14:10 UTC
### Description
Downloading tooltip message doesn't show correct percentage.

### Steps to Reproduce

  1. Start to download a file
  2. Move mouse over download info in the bottom of window
  3. Wait until tooltip message appears

**Actual result:**

![image](https://user-images.githubusercontent.com/18405789/45493328-24220280-b777-11e8-9209-46a56a21694a.png)

**Expected result:**
It is expected to see download percentage instead of **{{ downloadPercent }}** template 

**Reproduces how often:**

### Brave Version

 
Brave: 0.23.107 
V8: 6.8.275.24 
rev: 6f2fc65b3c7db0b260ad154fbef5919902495387 
Muon: 8.0.10 
OS Release: 4.15.0-33-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Reproducible on current live release:**

**Comment by bsclifton** [comment] 2018-09-15 08:02
Duplicate of https://github.com/brave/browser-laptop/issues/13920

**Closed by bsclifton** 2018-09-15 08:02 UTC
