### ISSUE TITLE
Option to hide download panel

### ISSUE THREAD

**Issue by ncihnegn** [brave/browser-laptop#11548] opened 2017-10-16 02:19 UTC
### Description
The download panel occupies a lot of space. It will be nice not to show the panel.
### Steps to Reproduce
  1. Download a file
  2.
  3.

**Actual result:**
The download panel stays.
**Expected result:**
Option to hide the download panel
**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time
### Brave Version
0.19.48
**about:brave info:**
Brave | 0.19.48
rev | de939f6
Muon | 4.4.28
libchromiumcontent | 61.0.3163.100
V8 | 6.1.534.41
Node.js | 7.9.0
Update Channel | Release
OS Platform | macOS
OS Release | 17.0.0
OS Architecture | x64

**Reproducible on current live release:**

**Comment by luixxiul** [comment] 2017-10-16 04:30
Closing as duplicate of https://github.com/brave/browser-laptop/issues/10548

**Closed by luixxiul** 2017-10-16 04:30 UTC
