### ISSUE TITLE
Auto-fill of bookmarks sometimes deletes characters being typed into the url

### ISSUE THREAD

**Issue by Oliphaunte** [brave/browser-laptop#4952] opened 2016-10-19 15:35 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Auto-fill from bookmarks deletes characters being typed.  For example, I have a bookmark with a github url, so when I try to type out `www.github.com`, it sometimes becomes something like `www.githubcom` (deleted dot before com). I've always checked multiple times to make sure I'm not just typing wrong, and the dot definitely gets deleted sometimes.

**Expected behavior:**
Typing in url without having characters be deleted

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS X El Capitan - 10.11.6

- Brave Version:
Version - 0.12.5

- Steps to reproduce:
    1. Bookmark a page, with a preferably long url
    2. Type in same url as the bookmark, fast, but with occasional split-second pauses to let the url auto-fill. It's very tricky and will need to be done a couple of times to replicate. Naturally, it always happens when I'm not trying to do it and then is perfect when I am. 
    3. You should see characters sometimes deleted after the auto-fill loads with you still typing in the url.

- Screenshot if needed:

- Any related issues:
This started happening to me after the v0.12.5 release.

**Comment by Sh1d0w** [comment] 2016-10-19 15:42
Duplicate of https://github.com/brave/browser-laptop/issues/4731 . It is not related to bookmarking a website, rather than fast typing.

**Closed** 2016-10-19 15:42 UTC
