### ISSUE TITLE
Brave hangs, eventually crashes, when importing Firefox browsing history

### ISSUE THREAD

**Issue by MartenKahr** [brave/browser-laptop#7646] opened 2017-03-10 09:10 UTC
- Did you search for similar issues before submitting this one? Yes, found #6604, but issue is with History, not Bookmarks or Cookies.

- Describe the issue you encountered: Importing data from Firefox hangs and eventually crashes. Turning off Import Browsing History and importing only bookmarks and cookies is successful. Importing only history, or History + Bookmarks/Cookies consistently hangs and crashes. Memory usage skyrockets to over 1.5GB prior to crash.

- Platform (Win7, 8, 10? macOS? Linux distro?): Win7

- Brave Version (revision SHA): 1db81cb

- Steps to reproduce:
    1. Have extensive browsing history in Firefox profile
    2. Import Data from Brave, select only history, disabling other import options.
    3. Begin Import
    
- Actual result: Hangs for 30 seconds up to a minute. Eventually crashes all instances of Brave even if not interrupted.

- Expected result: Import successful within five seconds.

- Will the steps above reproduce in a fresh profile? If not what other info can be added? Yes

- Is this an issue in the currently released version? Yes

- Can this issue be consistently reproduced? Unsure, haven't tested on other systems, or with other Firefox profiles.

- Any related issues: #6604 #4879

**Comment by luixxiul** [comment] 2017-03-13 05:30
Thanks for the report. Do you see the difference between this one and #6604 which you mentioned? If not, let's close this issue as a duplicate.

**Comment by MartenKahr** [comment] 2017-03-13 16:40
Yes, unlike in #6604, bookmark import does not fail. Besides that, identical behavior as far as I can tell.

**Comment by bsclifton** [comment] 2017-03-21 18:48
cc: @darkdh

**Comment by RenaudParis** [comment] 2018-02-01 15:43
Same thing here, except it crashes almost immediately. Nothing gets saved (I mean not even the options I configured prior to importing from Firefox)

I don't know for other people, but I know I can't really use Brave if I can't import all my data, it would take too much time to do it manually.

Dying to try it out though! (very good feedbacks from family members + love the money for noads)

**Comment by sammcoe** [comment] 2018-02-15 20:29
Same issue here.

**Comment by RenaudParis** [comment] 2018-02-27 21:27
Any feedback from the dev team on this critical issue?

A year has passed, and I'm waiting for this to be fixed before I can switch to Brave.

Thanks dev team! :)

**Comment by brandonserna** [comment] 2018-02-28 14:45
It seems to work if you import each individually (passwords, history and bookmarks). Brave was crashing when I tried to import all at once

_v0.20.46 - osx_

**Comment by RenaudParis** [comment] 2018-03-04 22:04
@brandonserna thanks for the input! Actually I tried what you said, and it allowed me to notice that Brave crashes when importing **cookies**. I imported everything else (except cookies, then) from Firefox, and it worked fine.

I am now using Brave, and so far, despite a few bugs like on-page anchors not working, I quite like it!! :) :+1:

**Comment by srirambv** [comment] 2018-06-29 14:58
+1 from @douglascrp via https://github.com/brave/brave-browser/issues/452

**Comment by douglascrp** [comment] 2018-07-04 13:54
I have just tried importing from Firefox without cookies, just like @rkyoku did, and it worked for me.
So the problem is really only with the cookies importer.

**Comment by bsclifton** [comment] 2018-10-19 07:40
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser

**Closed by bsclifton** 2018-10-19 07:40 UTC
Labels: bug, crash, feature/importer, perf
