### ISSUE TITLE
Suggestion: setting to not autoplay videos

### ISSUE THREAD

**Issue by mykkymk** [brave/browser-laptop#5952] opened 2016-11-30 22:19 UTC
I like to open several youtube videos on different tabs. can you do some upgrades so that when i open i video in new tab it doesn't  start playing until i click on that tab.

**Comment by pixelass** [comment] 2016-11-30 23:45
I was wondering about the same thing. Most browsers don't autoplay youtube videos. When browsing youtube on brave I always manually pause the videos.

@mykkymk I suggest changing the title to "don't autoplay youtube videos"

**Comment by Superbest** [comment] 2016-12-01 00:33
This is possible in Firefox with `about:config` by setting `media.autoplay.enabled` to `false`.

**Comment by Sh1d0w** [comment] 2016-12-01 04:47
Duplicate of https://github.com/brave/browser-laptop/issues/4045

**Closed by Sh1d0w** 2016-12-01 04:47 UTC
Labels: parity, settings, suggestion
