### ISSUE TITLE
Mac OS install creates files in user directory owned by root

### ISSUE THREAD

**Issue by brad2014** [brave/browser-laptop#1021] opened 2016-03-06 13:04 UTC
When I open the installation download "Brave.dmg" and drag Brave to the Application folder to install, 
files are created in my home directory that are owned by root:
```
$ sudo find ~ ! -user me -ls
2367388        0 drwxr--r--    4 root             staff                 136 Mar  6 04:53 /Users/me/Library/Application Support/com.electron.brave.ShipIt
2367391      416 -rw-r--r--    1 root             staff              212502 Mar  6 05:04 /Users/me/Library/Application Support/com.electron.brave.ShipIt/ShipIt_stderr.log
2367389        0 -rw-r--r--    1 root             staff                   0 Mar  6 04:53 /Users/me/Library/Application Support/com.electron.brave.ShipIt/ShipIt_stdout.log
```

Expected: only files owned by me should appear in my home directory.
Also, permissions 744 are weird - shouldn't they be 755?

Note: This may be related to #1019.
Note: ShipIt is in the Squirrel framework

**Comment by diracdeltas** [comment] 2016-03-07 20:13
Dupe of #1020

**Closed by diracdeltas** 2016-03-07 20:13 UTC

**Comment by brad2014** [comment] 2016-03-08 02:24
Oops, sorry for dupe. Not sure how that happened.

**Comment by macneo** [comment] 2016-03-08 12:16
I don't have them. I checked both on the shell with your command and visually in the Finder. I've been running 0.8.0 for a couple of days.
