### ISSUE TITLE
Lenovo shopping site doesn't open correctly

### ISSUE THREAD

**Issue by xiaohanzhu** [brave/browser-laptop#5851] opened 2016-11-26 17:44 UTC
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Go to 
http://shop.lenovo.com/us/en/laptops/thinkpad/x-series/x1-carbon/?menu-id=thinkpad_x1_carbon_gen_4
The page simply doesn't load properly
**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10
- Brave Version:
brave	0.12.9
muon	1.4.25
libchromiumcontent	53.0.2785.143
V8	5.3.332.47
Node.js	6.5.0
channel	dev
os.platform	win32
os.release	10.0.14393
os.arch	x64
- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by maxart** [comment] 2016-11-26 18:37
@xiaohanzhu toggle off HTTPS Everywhere and Block Scripts, then the site will load just fine.

**Comment by zb420** [comment] 2016-11-26 19:21
I seems to be working fine now.
zb420

#lenovoIN

**Comment by xiaohanzhu** [comment] 2016-11-26 20:11
Nope.  Still not working for me.  Already upgraded my brave to 0.12.10

**Comment by srirambv** [comment] 2017-03-21 20:30
+1 from community https://community.brave.com/t/latest-version-of-brave-fails-on-part-of-the-lenovo-website/1773/2

**Comment by diracdeltas** [comment] 2017-06-21 20:35
At least for me, it appears Lenovo has fixed the issue by having shop.lenovo.com redirect to www3.lenovo.com. can someone confirm?

**Comment by luixxiul** [comment] 2017-06-21 22:42
confirmed, closing.

**Closed by luixxiul** 2017-06-21 22:42 UTC
Labels: feature/HTTPSEverywhere, info-needed, webcompat

**Comment by xiaohanzhu** [comment] 2017-06-21 23:08
it happens in china when the site uses baidu map instead of google map

From Xiaohan Zhu's smart phone.

-------- 原始邮件 --------
主题：Re: [brave/browser-laptop] Lenovo shopping site doesn't open correctly (#5851)
发件人：Suguru Hirahara
收件人：brave/browser-laptop
抄送：xiaohanzhu ,Mention


confirmed, closing.

―
