### ISSUE TITLE
Facebook popup messages

### ISSUE THREAD

**Issue by thbtm** [brave/browser-laptop#1016] opened 2016-03-06 10:14 UTC
When I'm going to Facebook a popup with the following message appears : "www.facebook.com is requesting permission to show you notifications".  I click on "Deny". 

Then a second popup appears wit the following message : "Would you like to remember this decision on www.facebook.com until Brave closes?" I click on "Yes"

But, if I close and reopen Brave and go to Facebook again, these messages appears again.

**Comment by bbondy** [comment] 2016-03-07 18:11
@diracdeltas putting this in 0.8.1, pls take if you can.

**Comment by diracdeltas** [comment] 2016-03-07 20:11
That's the expected behavior for now. As the prompt says, your decision was remembered until Brave closed. It pops up again when Brave is re-opened.

**Comment by bbondy** [comment] 2016-03-09 14:51
Sorry I misread originally and didn't realize there was a close.  Closing this issue since it is expected for now.

**Closed by bbondy** 2016-03-09 14:51 UTC

**Comment by bogas04** [comment] 2016-05-03 18:10
Can we stop it from asking again and again ?

**Comment by diracdeltas** [comment] 2016-05-03 20:46
@bogas04 yep that's in 0.9.3
