### ISSUE TITLE
Intermittent Slowdowns

### ISSUE THREAD

**Issue by knightshousegames** [brave/browser-laptop#13194] opened 2018-02-20 00:53 UTC
### Description

Since a recent update, I've been having random periods of slowdown

There will be a few minutes where everything will act completely normally, then pages won't load, videos will buffer, and it act like the wifi is spotty or the internet is down, except all of my other internet reliant software acts completely normally, and I've tested my connection with another browser and everything looks to be completely normal. I've even run the same Twitch stream in 2 different browsers, and in the other browser the video will play without issue, but in Brave will buffer every 2-3 minutes.
Since a recent update, I've been having random periods of slowdown

### Steps to Reproduce

I usually have 2 browsers open, one on each monitor, one usually with a video open on Youtube or Twitch. Beyond this, it intermittently decides mostly at random when it wants to disconnect.

**Reproduces how often:**

Ever since the new update it has happened a few times an hour, as severely as every few minutes.

### Brave Version

**about:brave info:**

Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Comment by Liunkae** [comment] 2018-02-20 04:13
@knightshousegames Thanks for the report! This is a duplicate of #13087. Please subscribe to that issue for further updates. Good news: Brave developers have labeled it a high priority issue and are investigating it right now.

**Comment by knightshousegames** [comment] 2018-02-20 04:25
I saw that bug earlier, that sounds like a separate issue I was having. What I'm talking about isn't system resources, I'm talking what seems like almost an internet connection problem, where the actual internet connection in the browser feels like it disconnects and reconnects. I've been trying to watch a Twitch video back for the past hour or two and every few minutes the video buffers, and if I try to refresh regular web pages like message boards, they'll give me connection errors.

**Closed** 2018-02-22 07:02 UTC

**Comment by bsclifton** [comment] 2018-02-22 07:05
Thanks for the report, @knightshousegames - if the issue you saw isn't covered by #13087 then I suspect it should be covered (and fixed by) https://github.com/brave/browser-laptop/pull/13234

I marked this as a duplicate for now- we'll be having new beta releases available soon (this week) that should have a fix in case you wanted to verify.  Thanks 😄
