### ISSUE TITLE
Opening a new window with pinned tabs, the New Tab will have url of pinned tab, and focus stolen

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#13804] opened 2018-04-11 17:10 UTC
### Description
When opening a new window with pinned tabs, the unpinned tab which has focus will show the URL of one of the pinned tabs in the URL bar, and often have the URL bar focus stolen when the pinned tab has been loaded. This all depends on timing.

### Steps to Reproduce

  1. Pin at least 2 sites
  2. Open a new window with cmd-n

**Actual result:**
The new unpinned tab will display the URL of one of the pinned tabs. When the pinned tab finishes load, focus will move away from the URL bar.

**Expected result:**
The new unpinned tab does not display any URL in the URL bar, and maintains URL bar focus.

**Reproduces how often:**
~50%

### Brave Version

**about:brave info:**
0.22+

**Reproducible on current live release:**
Yes

**Comment by hugobuddel** [comment] 2018-07-25 19:03
This second sub-issue of loosing focus is very frustrating. I have 7 pinned tabs, and I basically cannot use the address bar of a new window until all 6 tabs have fully loaded. The address bar looses focus each time one of the pinned tabs loads, so it is very hard to type an address. Currently I press ctrl-L each time the focus is lost. (I don't actually know where the focus goes.)

I noticed I've been using Firefox more often lately when I want to quickly search for something in a new window. I think this is because of this problem. It takes 27 seconds before all the pinned tabs are loaded, so each new Brave window is essentially useless for half a minute.

 
Brave: 0.23.39 
V8: 6.7.288.46 
rev: a38be75ccb0f699f507b66c4d44b3b21d1677e25 
Muon: 7.1.6 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Comment by bsclifton** [comment] 2018-09-21 06:01
Can't reproduce (tried making 6 or 7 windows). If this is still a problem however, this should be fixed with brave-core 😄

**Closed by bsclifton** 2018-09-21 06:01 UTC
Labels: initiative/reduce-bugs

**Comment by rbucchi** [comment] 2018-10-25 08:03
Still happen with Jenkins with auto refresh enabled plus gmail pinned tabs.

approximately gmail reload every few minutes, while auto refresh enabled in Jenkins 30second ish. The last makes urls bar pretty much unusable

Brave: 0.25.2 
V8: 6.9.427.23 
rev: 8ea2a9ce5ca329478186e6393e07f1cf87d34a22 
Muon: 8.1.8 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Comment by hugobuddel** [comment] 2018-10-29 12:47
This is indeed addressed with brave-core. And for me the main reason to switch.

It is still a problem with brave-laptop though. Using an autorefreshing tab like Jenkings is indeed a good way to reproduce the problem. The tab doesn't even have to be pinned. As in, the focus of the url bar your typing in will be lost once the other tab reloads.

But it seems brave-browser is now the default from brave.com, so this is irrelevant now it seems.
