### ISSUE TITLE
Address bar context menu doesn't work when it has no text

### ISSUE THREAD

**Issue by cfumante** [brave/browser-laptop#1130] opened 2016-03-19 19:00 UTC
The cut/copy/paste menu doesn't work in a new tab - this prevents you from copyig text in one tab and doing a search in a new tab

**Comment by bbondy** [comment] 2016-03-19 19:17
I think it does work across tabs but you're probably experiencing this issue which we're trying to get STR.  Let me know if you know exact steps to reproduce after starting the browser. That would be very helpful. Thanks!
https://github.com/brave/browser-laptop/issues/1060

Closing for now but if this turns out to be different I can re-open.

**Comment by cfumante** [comment] 2016-03-19 19:52
1. open browser  (mine opens to Brave.com)
2. select text ( I used It's your device)
 
3. right click mouse to open menu
 
4. select copy and click
 
5 open the "3-bar"  Brave menu at the far right
 
6. select New tab or new Private Tab
 
7. move to the new tab
 
8. place the cursor in the address box
 
9. right click to bring up the cut/copy/paste menu so you can do a
search on the selected text
 
10. the menu does not appear.
 
The menu never appears in a new tab until a page has been loaded.
Ctrl-c, -v, & -x still work as work-arounds
 
 
/c/

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by bbondy** [comment] 2016-03-19 20:48
Reproduced and updated the title, thanks!

**Comment by cfumante** [comment] 2016-03-19 20:51
Mahalo for the quick response... and on a weekend...
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Closed** 2016-03-20 17:48 UTC

**Comment by cfumante** [comment] 2016-03-23 21:34
Tested this issue in 8.2 - fix worked. all good
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----
