### ISSUE TITLE
Brave crashes when accessing details from mybrowserinfo.com

### ISSUE THREAD

**Issue by lxrocks** [brave/browser-laptop#15161] opened 2018-09-05 21:29 UTC
### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bsclifton** [comment] 2018-09-07 05:53
Closing as I'm unable to reproduce with latest release. We'll need more info in order to diagnose

**Closed by bsclifton** 2018-09-07 05:53 UTC

**Comment by lxrocks** [comment] 2018-09-10 03:28
No worries Brian, you are correct, it does not occur with lates browser.
Cheers
