### ISSUE TITLE
Brave ad-blocking detected

### ISSUE THREAD

**Issue by bn0785ac** [brave/browser-laptop#13613] opened 2018-03-27 00:45 UTC
Simetimes brave adblocker its detected
and  i cant use some streaming sites

**Comment by kjozwiak** [comment] 2018-03-27 04:16
@bn0785ac could you please add some more actionable information? Which OS did you experience the issue with? Which website is detecting Brave's adblocker? Some STR (steps to reproduce)?

We'll need more information from you so we can investigate the problem.

**Comment by bsclifton** [comment] 2018-03-28 21:18
Closing issue - let's re-open once we have examples of websites. It's important to share the examples because we'll need to see how the detection is being done (like @kjozwiak mentions, there isn't anything actionable for us)

**Closed by bsclifton** 2018-03-28 21:18 UTC
Labels: needs-info

**Comment by bn0785ac** [comment] 2018-03-28 23:42
Duplicated again :dagger: 
```

f3d5c5a66275dc2d551db31239fdc7d268385fced2e8d03669eb279b4751aceb  brave-snapshot-bin-0.22.7.tar.bz2
f3d5c5a66275dc2d551db31239fdc7d268385fced2e8d03669eb279b4751aceb  brave-snapshot-bin-0.22.8.tar.bz2
f3d5c5a66275dc2d551db31239fdc7d268385fced2e8d03669eb279b4751aceb  brave-snapshot-bin-0.22.9.tar.bz2

```
