### ISSUE TITLE
Back state not updating after keyboard shortcut nav

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1460] opened 2016-04-25 04:22 UTC
https://twitter.com/bipolarmike/status/724274590915002369
[- +] @BipolarMike
@brave Bug: On PC (Win10), when using Backspace to go back, the Foward button stays transparent and I cannot go forward.

**Comment by diracdeltas** [comment] 2016-04-25 05:16
duplicate of https://github.com/brave/browser-laptop/issues/1349 i think

**Closed** 2016-04-25 14:51 UTC
Labels: duplicate
