### ISSUE TITLE
About pages doesn't open in Private tabs

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6259] opened 2016-12-16 17:20 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
About pages doesn't open in Private tabs

**Expected behavior:**
Should open about pages in private tabs

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7 x32/Windows 10 x64

- Brave Version:
0.12.15

- Steps to reproduce:
    1. Open a private tab
    2. Try opening any of the about pages, doesn't load

- Screenshot if needed:
0.12.15 (Win 7 x32)
![image](https://cloud.githubusercontent.com/assets/17010094/21271590/77f129b8-c3b3-11e6-8c2f-6c5cfc57a8d2.png)

  0.13.0 (Win 10 x64)
   ![image](https://cloud.githubusercontent.com/assets/17010094/21271556/5a05203a-c3b3-11e6-9ef4-b3808cb983bd.png)

- Any related issues:
Setting 0.13.0 for now. Please change if required

**Comment by bsclifton** [comment] 2016-12-16 18:05
Duplicate of https://github.com/brave/browser-laptop/issues/1817

**Closed by bsclifton** 2016-12-16 18:05 UTC
Labels: bug
