### ISSUE TITLE
Modify search engine and some other features

### ISSUE THREAD

**Issue by BlackEagle001** [brave/browser-laptop#5065] opened 2016-10-22 19:48 UTC
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
Hi. I post here because can't use the Submit Feedback. I have no mail program on my computer.
I would like to add a other search engine (Ecosia in my situation) in the Preferences but there is no possibility.
I use this post to propose some other possibilities. Indeed, the keyboard shortcut f6 doesn't work to access easily to the url bar.
I use my computer very late in the day and the white of the bar up is not really pleasant. The possibility to use a black one can be really nice.
I don't know if is it normal but I can't find my navigation history with mouse or with ctrl+h keyboard shortcut.
When the program start, it never start in full screen mode.
**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win10
- Brave Version:
  0.12.5
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

Sorry for my bad English. I hope to have correctly made this post. Good continuation.
BL.

**Comment by Liunkae** [comment] 2016-10-23 00:32
Hello @BlackEagle001! Thanks for the feedback. Here is some information about the changes you mentioned:

1. There are plans to add more search engines (#1103) and allow users to add custom search engines (#3053). These enhancements are currently planned for Brave 1.1.0.
2. The F6 shortcut might be added in the future (#4464). In the meantime, you can use Ctrl+L.
3. A dark theme will be added in the future (#271).
4. Browsing history can be viewed by selecting Menu > History > Show History or Ctrl+Y.
5. I'm not sure what the expected behavior for Windows full screen mode is.

I hope this helps.

**Comment by srirambv** [comment] 2017-02-05 09:26
+1 from community for Ecosia 
https://community.brave.com/t/add-ecosia-search/1072

**Comment by chrischik** [comment] 2017-02-06 09:47
I was hopeful when I saw "Additional Search Engines added" for the Brave iOS 1.2.20 Release, but it seems like Ecosia is still missing in the search engine list. Could you please add it?

Ecosia is much more widely used than Qwant for example, which is available in the list. (See www.alexa.com/siteinfo/ecosia.org vs www.alexa.com/siteinfo/qwant.com).


(Disclaimer: I work at Ecosia, but I use Brave as default browser on my private phone)

**Comment by Liunkae** [comment] 2017-02-06 19:54
@chrischik Please submit an issue at https://github.com/brave/browser-ios (the Brave iOS app repository). Thanks!

**Comment by Liunkae** [comment] 2017-02-10 06:10
I posted a separate issue for Ecosia at #7158.

**Comment by bsclifton** [comment] 2017-03-13 22:52
Closing this issue as a duplicate of https://github.com/brave/browser-laptop/issues/3053

For requesting other search engines, let's post in https://github.com/brave/browser-laptop/issues/790 😄

**Closed by bsclifton** 2017-03-13 22:52 UTC
Labels: feature/search, suggestion
