### ISSUE TITLE
Users are getting an error page with a black and white flicker strobe-like effect

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4502] opened 2016-10-04 14:33 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Some users after updating to 0.12.3 are experiencing screen flicker.

**Expected behavior:**
The content should render normally.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  This has been found primarily on Windows devices.
- Brave Version:
  0.12.3
- Steps to reproduce:
  1. Unknown. Needs investigation.
- Screenshot if needed:
- Any related issues:

**Comment by alexwykoff** [comment] 2016-10-04 14:34
User report:
Operating system: Windows 10 Pro x64
CPU : Intel Core i3-4005U @ 1.70Ghz
RAM : 4Gb
Graphics : Intel HD Graphics

**Comment by rajakvk** [comment] 2016-10-04 15:04
- Steps to reproduce
Starts flickering immediately after launching browser. I can see "about:error" in the address bar.

**Comment by alexwykoff** [comment] 2016-10-04 17:05
cc : @srirambv @bridiver

**Comment by bsclifton** [comment] 2016-10-04 18:32
Will be checking this out- might be related to calculations w/ the window frame, per comment by @zcbenz when I upstreamed this (it was reverted after merge)

https://github.com/electron/electron/pull/7416

**Comment by bridiver** [comment] 2016-10-04 18:49
are these all anniversary edition?

**Comment by bridiver** [comment] 2016-10-04 18:59
this is slightly different from what @srirambv reported. He said he only sees the issue in tabs opened from links

**Comment by bridiver** [comment] 2016-10-04 19:00
@rajakvk do you have the anniversary edition update? What is your screen resolution?

**Comment by bsclifton** [comment] 2016-10-04 19:22
Per the [Twitter convo @jonathansampson had with an affected user](https://twitter.com/anatudor/status/783196461941088256):
Surface Book
175% DPI

**Comment by bsclifton** [comment] 2016-10-04 23:09
@rajakvk do you still see the issue? @jonathansampson was working with someone who had seen the issue previously and it may have been related to Windows Defender

**Comment by jonathansampson** [comment] 2016-10-04 23:49
@bsclifton I don't believe the issue was related to Windows Defender; I suspect the update to Defender they saw was a mere coincidence, coinciding with the passing of several hours between opening Brave, as well as a new Session, and a restart of their machine.

**Comment by bbondy** [comment] 2016-10-06 17:21
Can we close this? 
BrianJ said afaik a restart fixed it.  
We could close for now and re-open if needed after?

**Comment by jonathansampson** [comment] 2016-10-06 17:31
@bbondy The user I was speaking to reported that the issue had gone away by the next day. There was one other user who reported this issue; I'll check with them as well to see if it has resolved itself by now.

**Comment by alexwykoff** [comment] 2016-10-11 12:59
+1 from support : https://linkbubble.zendesk.com/agent/tickets/5830

> Oct 03 14:22
> I attempted to download & install brave today.
> 
> After the install initially appears to work, the browser immediately opens to a strobing (as in flashing rapidly black & white - inducing nausea) about:error page. Attempting to open a new tab only opens further strobing about:error pages.
> 
> Windows 7 SP1 64bit

**Comment by alexwykoff** [comment] 2016-10-11 14:44
+1 from support : https://linkbubble.zendesk.com/agent/tickets/5837

> I just installed the Brave Browser, as soon as the browser loads the tab window flashes like crazy and not matter what I do it keeps flashing. I am running Windows 10

**Comment by D-m-L** [comment] 2016-10-11 16:39
Hello, I am the user from the report of Oct 03, 14:22.

A complete power cycle did not fix this issue.
Build was downloaded report date.
1920x1080, 16gigs ram
Nvidia 660 with recent display driver (can confirm exact driver if necessary)

**Comment by bridiver** [comment] 2016-10-11 16:42
Have you tried with 0.12.4? We identified an issue with the chrome 53 upgrade that caused some related problems, but we couldn't replicate your issue to test

**Comment by D-m-L** [comment] 2016-10-11 16:50
I don't know what version is being tested. Where do I download a specific version?

I just redownloaded and reinstalled from the download page at brave.com and same issue.

**Comment by D-m-L** [comment] 2016-10-11 16:52
I don't know if this is helpful, but briefly when the window first opened it appeared that the flashing/strobing box grew from the upper left corner to full the window over the course of a few frames

**Comment by squarenuts** [comment] 2016-10-15 17:34
I had the same problem. I am running Windows 10 pro on an NVidia 980 card. The fix I found to work was setting the COMPATIBILITY MODE to windows 8. (right click short cut on the desktop and  go to the compatibility tab) Seems to have fix the problem but have no idea what its long term effects will be.

**Comment by bridiver** [comment] 2016-10-15 18:22
thanks for the info and the temporary workaround @squarenuts. @alexwykoff I see you listed a report with `Intel HD Graphics` but that is often paired with dedicated graphics and switches between them as required. Can you check to see if it's also nvidia? The COMPATIBILITY_MODE setting is also interesting. I'll keep investigating.

**Comment by bsclifton** [comment] 2016-10-20 15:45
Please see https://github.com/brave/browser-laptop/issues/4943 for another report, including hardware information + attached dxdiag. Issue was solved by user by rebooting

**Comment by D-m-L** [comment] 2016-10-20 16:32
Again, where do I download a specific version?  It *appears* from the appdata, that I am using version 0.12.4, but the download page just says "0.12.dev" so I'm not sure.

No combination of compatibility choices made any difference.

**Comment by D-m-L** [comment] 2016-10-20 16:38
Just downloaded "0.12.dev" again. This time appdata reports 0.12.5. Same flickering issue. Tried x32 just in case, same issue.

**Comment by bsclifton** [comment] 2016-10-20 16:40
@D-m-L you should be able to force an update check under the hamburger menu
![screen shot 2016-10-20 at 9 37 43 am](https://cloud.githubusercontent.com/assets/4733304/19569054/0867681e-96a9-11e6-9723-cf61a9de5123.png)

And as I'm typing this you already responded and found 0.12.5! Thanks for trying it out and confirming the problem still exists

**Comment by D-m-L** [comment] 2016-10-20 16:56
Update check appeared to work, (though obviously it didn't find a new one) so I will try to update it every day or so and see what happens.

**Comment by bsclifton** [comment] 2016-10-27 07:11
I'm curious if this was fixed with https://github.com/brave/browser-laptop/issues/5177?

**Comment by jonathansampson** [comment] 2016-10-27 21:23
Video shared today by a user on Twitter: https://twitter.com/BulletSpongeRTR/status/791736293273182208

**Comment by bsclifton** [comment] 2016-11-16 08:29
+1 from support https://linkbubble.zendesk.com/agent/tickets/6652

@bbondy @bradleyrichter @jonathansampson as a work-around, we could offer a command-line option to disable the new slim titlebar.  This work-around would then likely fix the issue for folks experiencing.  I believe the differences in a regular window and a frameless window electron are causing this issue

**Comment by MutantOctopus** [comment] 2016-11-21 23:52
Signing on to report that I'm having the same issue in the most current stable update - OS is Win10 anniversary x64, CPU is Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz, 8GB (7.88G usable) RAM, Intel HD graphics.

I don't know if this is related, but my computer was having startup issues and had to scan/repair the C: drive when I booted it today. Brave worked fine prior.

**Comment by bsclifton** [comment] 2016-11-29 16:12
+1 from support
https://linkbubble.zendesk.com/agent/tickets/7030

> Hi,
>
> hard to describe. After a computer crash (blue screen) I fired up brave.
> It's not loading ANY pages, it just flickers the window - really crazy.
> Removed Brave, deleted everything in shared folder, re-installed.
> This is how it looks like:
> <private video link redacted>

**Comment by jbmonroe** [comment] 2016-12-04 20:29
While Brave was in the fugue state it was leaking about 5MB/sec.  Rebooting did clear up the issue, resulting in two tabs of "about:error" that indicated (oddly enough) that an error had occurred.

**Comment by CyrexCore2k** [comment] 2016-12-21 21:34
I just had the same issue in 12.15. Rebooting didn't work for me but I was able to get it working by switching to compatibility mode for windows 7. I'm using windows 8.1 pro.

A few things:
1. Prior to a recent reboot Brave was showing the brave installation executable in the path and a download window on load. Closing the download window allowed me to use Brave normally.
2. I was downloading a file that had no progress indicator. I closed brave (using the window control) just prior to rebooting.

Not sure if either of those have anything to do with why this started.

What didn't work:
1. Uninstalling and re-installing brave
2. Opening up new tabs

This is a pretty strange bug. I did look through the source code a bit trying to figure out if there was a possible about:error infinite redirect but I see there's already been some code changes to prevent that from happening.

Is there a debug mode or a log file I can look at?

**Comment by bridiver** [comment] 2016-12-21 22:13
does it only happen when upgrading Brave? Can't tell if anyone had this happen with a fresh install or not. @bsclifton maybe another squirrel updater issue?

**Comment by bsclifton** [comment] 2016-12-21 22:40
@bridiver I don't think this issue is related to Squirrel; it seems fresh install vs upgrade doesn't matter

I believe the problem is GPU / driver related. Something definitely broke after Anniversary Update.  @CyrexCore2k, @jbmonroe - do you both have Intel integrated graphics? (if not, what kind of graphics card do you have?)

**Comment by jbmonroe** [comment] 2016-12-21 23:45
GeForce GTX770, driver 376.19, although it might have been an earlier driver release earlier when this occurred--one of the 375._xx_ releases.

**Comment by CyrexCore2k** [comment] 2016-12-23 19:24
I have an Intel integrated graphics.

To clarify: I believe the browser was updating successfully. I did not confirm the version number prior to the reboot but I experienced the symptoms I described in item 1 over a few update notifications. The update notifications were disappearing after I clicked update even though the download dialog issue persisted.

@bsclifton - Even if the issue is driver related I'm surprised there seems to be an endless loop of error/load error tab/error/load error tab... I would expect the code [here](https://github.com/brave/browser-laptop/blob/901d28cf5d752d707bd6ab2cb4351547749d6096/js/components/frame.js#L777) would prevent that from happening. 

I have some free time next week thanks to the holidays I'm gonna see if I can pull the code down and make a couple tweaks to capture more information about the error.

**Comment by boozedog** [comment] 2016-12-26 18:55
I've had this problem intermittently on Win10. No problems on macOS.

Also I saw similar issue that @CyrexCore2k mentions above: https://github.com/brave/browser-laptop/issues/4502#issuecomment-268646359

That is, I was seeing executable path of Brave in the address bar of Brave.

That might be a separate issue though.

@CyrexCore2k 's solution of setting Compatibility to Win7 for the Brave executable took care of the strobe effect for me too.

I have Radeon R9 380 series display adapter.

**Comment by D-m-L** [comment] 2017-01-13 15:18
Did the in-browser upgrade today. No difference.

**Comment by luixxiul** [comment] 2017-01-13 15:28
Because it's not fixed yet

**Comment by D-m-L** [comment] 2017-01-13 15:37
You may have misunderstood the nature of my comment. As it has been ~10 minor updates since I last posted, I am offering clarifying information on my case.  If this is not desired I will unsubscribe from the issue.

**Comment by bsclifton** [comment] 2017-01-13 15:39
@D-m-L apologies- this is still a work in progress... I believe I have found a fix for this :smile: 

When we have new builds available, would you be interested in testing this for us? We might have something as early as today

**Comment by D-m-L** [comment] 2017-01-13 15:46
Happy to help. Don't want to be a bother. I know we're all busy.

**Comment by bsclifton** [comment] 2017-01-13 15:49
@D-m-L definitely not a bother; it would actually be a huge help for us! :smile: 

Regarding the above, I had accidentally closed the issue by checking in code. I used a message like "this code might fix #4502" which then closed it.  Thanks for your patience- stay tuned! :smile:

**Comment by bsclifton** [comment] 2017-01-20 17:05
@D-m-L (and others too! @boozedog @CyrexCore2k) we have a release candidate available if you wanted to try it out :smile: 
https://github.com/brave/browser-laptop/releases/tag/v0.13.0dev-RC1

I believe this may fix the issue for you!  Please let me know :smile:

**Comment by jbmonroe** [comment] 2017-01-20 19:55
The install was very quiet, and afterward Brave starts two processes which shut down almost immediately.  I used both the 64-bit msi and exe installers with the same results for both.  This was on a Windows 7 machine; I'll try again on my Win10 box a little later.

**Comment by bsclifton** [comment] 2017-01-20 21:04
@jbmonroe I've seen this before and had a problem with Squirrel (what's used for installing).

You might try going to add/remove programs, uninstalling Brave (if it shows there), then rebooting.  After reboot, install should work OK

**Comment by jbmonroe** [comment] 2017-01-20 21:16
Yes, I was thinking of doing that next--clean install instead of just
running it.  I'll have something to report in a couple of minutes.

**Comment by bsclifton** [comment] 2017-01-20 21:24
@jbmonroe awesome- thanks for trying.  I was able to reproduce. We're going to try a new build here in a few mins which may help (release candidate 2)

**Comment by jbmonroe** [comment] 2017-01-20 21:56
I'll be on the lookout later tonight.  Thanks!

**Comment by D-m-L** [comment] 2017-01-23 03:29
Installed RC1 from the link above, got the install problem, uninstalled, rebooted, same thing. Creates window frame but closes before filling with anything. (Probably preferable to the flashing! : ) Will await RC2.

**Comment by luixxiul** [comment] 2017-01-23 03:42
Please try with the latest build, RC5: https://github.com/brave/browser-laptop/releases/tag/v0.13.0dev-RC5

**Comment by jbmonroe** [comment] 2017-01-23 11:48
Clean install, up and running.  Now if I can just figure out how I
triggered the black/white flashing.....

**Comment by jbmonroe** [comment] 2017-01-23 11:48
And thanks! :)

**Comment by bsclifton** [comment] 2017-01-23 16:35
@jbmonroe everything working ok?

@D-m-L you can try the latest release above, that @luixxiul linked to :smile:

**Comment by jbmonroe** [comment] 2017-01-23 17:10
I haven't noticed anything awry so far.

**Comment by CyrexCore2k** [comment] 2017-01-25 18:45
I'm afraid I won't be able to assist with testing the fix. I switched off compatibility mode prior to installing RC5 to verify I am still experiencing the issue and it seems to have resolved itself?

Here's what I have in my Help -> About

Brave	0.12.15
Muon	1.4.31
libchromiumcontent	53.0.2785.143
V8	5.3.332.47
Node.js	6.5.0
Update Channel	dev
os.platform	win32
os.release	6.3.9600
os.arch	x64

Regardless many thanks to @bsclifton for your work on this. Loving the browser :)

**Comment by D-m-L** [comment] 2017-01-28 02:41
Was able to install and run RC5 with no errors. Came up with an empty about:error page in the same position and window size as previously.  Browsed to Google and Facebook (without logging in) and their homepages were displayed without error!  Looks like you've squashed this one!

**Comment by Liunkae** [comment] 2017-01-28 06:55
Multiple reports that this problem is fixed. Closing as fixed in 0.13.0.

**Closed by Liunkae** 2017-01-28 06:55 UTC
Labels: needs investigation, OS/Windows

**Comment by LeeGDavis** [comment] 2017-11-23 21:36
I'm getting what I believe is this issue on Win 10 pro x64 since updating to 0.19.95.
In my situation the browser simply flashes from solid black to solid white and continues back and forth like this until you kill the process.  It is not a fast flicker, but sits on all black screen, then flickers all white quickly, then back to black and so on.  You can still click where the exit button would be and close it down without having to kill the process.

Running in compatibility mode does indeed work around this issue.

Likely relevant based on info above... I have an nvidia optimus card, m2200 paired to a intel P630 on chip.  

Please let me know if I can capture any relevant information to help debug.

**Comment by jonathansampson** [comment] 2017-11-27 01:19
@LeeGDavis Would you be able to capture a screen recording of this issue?

**Comment by LeeGDavis** [comment] 2017-11-28 17:13
@jonathansampson I'll try and get a screen recording up later today, but here are a couple screen shots of what it flashes back and forth with:
![image](https://user-images.githubusercontent.com/3057514/33333172-15447102-d41b-11e7-9878-fe06e4759b74.png)
![image](https://user-images.githubusercontent.com/3057514/33333196-2447d4b4-d41b-11e7-910e-afed790cb928.png)
You can resize the window, you can close it naturally if you click where the buttons are... it just flashes back and forth between these two states. The background is just another browser open to the brave website, the black or white box is the entirety of the brave browser window.

**Comment by LeeGDavis** [comment] 2018-08-10 15:30
Following the instructions at https://community.brave.com/t/window-is-solid-black-or-solid-white-looks-like-a-blank-page/10003/3 and using the disable gpu flag, `--disable-gpu`, the problem goes away.  I don't how badly this impacts performance, but it certainly resolves this issue.  The only exception a relaunch after an update leaves it in a solid black window and it no longer flips back and forth between white and black.
