### ISSUE TITLE
Certificate cannot be shown

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3081] opened 2016-08-10 07:07 UTC
**Describe the issue you encountered:** Certificate cannot be shown

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.11.4 RC2
- Steps to reproduce:
  1. Navigate to https://expired.badssl.com
  2. Click "Show Certificate"
- Screenshot if needed:
- Any related issues: #3075

**Comment by bbondy** [comment] 2016-08-10 13:29
It is showing for me. 
Could you try again?

**Comment by bbondy** [comment] 2016-08-10 13:29
I was on macOS though.

**Comment by luixxiul** [comment] 2016-08-10 13:44
Yes it is displayed now. Not quite sure the reason

**Comment by darkdh** [comment] 2016-08-10 13:49
I probably know the problem. 
STR
1. You can preserve the error page and restart Brave.
2. Click `Show Certificate` in the error page.

This is because we didn't cache the certificate when error.

**Comment by luixxiul** [comment] 2016-08-10 14:09
You're right, I can reproduce the issue following the STR

**Comment by bsclifton** [comment] 2016-11-15 16:28
I can't repro this w/ the steps above... but I can repro by:

1. Visit https://badssl.clifton.io/
2. You should see `net::ERR_CERT_AUTHORITY_INVALID`
3. Click Advanced > Show Certificate
4. Nothing happens :frowning_face:

**Comment by bcdady** [comment] 2016-12-11 17:27
I encountered this issue from a different, 'live' site, and can reproduce it testing some of the URLs listed above:


Name	Version
Brave	0.12.13
Muon	1.4.30
libchromiumcontent	53.0.2785.143
V8	5.3.332.47
Node.js	6.5.0
Update Channel	dev
os.platform	win32
os.release	6.1.7601
os.arch	x64

Clicking [Show Certificate] button does nothing.

**Comment by diracdeltas** [comment] 2016-12-15 19:43
closing in favor of https://github.com/brave/browser-laptop/issues/2611

**Closed by diracdeltas** 2016-12-15 19:43 UTC
Labels: bug
