### ISSUE TITLE
Devtool via context menu cannot be displayed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10249] opened 2017-08-02 09:57 UTC
**Describe the issue you encountered:** devtool via context menu cannot be displayed due to this error:

````
[26861:775:0802/182721.667654:ERROR:CONSOLE(0)] "(WEBUI context) http://localhost:8080/gen/app.entry.js:52874: Uncaught TypeError: webview.inspectElement is not a function{TypeError: webview.inspectElement is not a function
    at Object.inspectElement (http://localhost:8080/gen/app.entry.js:52874:16)
    at click (http://localhost:8080/gen/app.entry.js:73957:25)
    at CallbacksRegistry.apply (extensions::callbacks-registry:61:39)
    at EventEmitter.<anonymous> (extensions::remote:284:21)
    at emitThree (extensions::event_emitter:115:13)
    at EventEmitter.emit (extensions::event_emitter:196:7)
    at EventEmitter.ipcRenderer.emit (extensions::ipc_utils:31:22)}", source: chrome://brave/Users/Suguru/browser-laptop/app/extensions/brave/index-dev.html (0)
````

It can be displayed via menubar.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): master branch

- Steps to reproduce:
    1. Open context menu
    2. Click `Inspect Element`
    
- Actual result: nothing happens

- Expected result: devtool should be displayed

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by jonathansampson** [comment] 2017-08-10 02:06
+1 This is pretty important.

**Comment by alexwykoff** [comment] 2017-08-15 17:19
if we could have a regression range check on this that'd be great

**Comment by luixxiul** [comment] 2017-08-16 13:30
The devtool is displayed via the context menu on:

Brave: 0.18.23 
rev: 36ae2ec06efed0057ae16351108bf4d4c10a7ab4 
Muon: 4.3.10 
libchromiumcontent: 60.0.3112.90 
V8: 6.0.286.52 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Linux 
OS Release: 4.9.0-3-amd64 
OS Architecture: x64

**Comment by luixxiul** [comment] 2017-08-16 13:31
escalating the milestone for QA

**Comment by bsclifton** [comment] 2017-08-16 19:38
Moving to 0.19.x because this doesn't happen on 0.18.x (tested on Windows and macOS using 0.18.23).  If issue isn't present in 0.19.x, let's push back to 0.20.x and test

**Comment by kjozwiak** [comment] 2017-08-17 03:37
I managed to reproduce the issue with the 0.19.x branch and found the regression range using `git bisect`:

> Bisecting: 0 revisions left to test after this (roughly 0 steps)
> [386b34d08698937cb83fc30754849896a73e666e] Update Muon to 4.4.0

It appears that the update to muon 4.4.0 is causing the regression. Anything before the muon 4.4.0 update works without any issues.

@bridiver could you please take a look?

I received the same results as @bsclifton while testing the 0.18.x branch. I couldn't reproduce the issue using both macOS 10.12.6 x64 and Win 10 x64.

- Brave 0.18.14 rev ad92d029e184c4cff01b2e9f4916725ba675e3c8 - couldn't reproduce the issue
- Brave 0.18.15 rev 2ca81b89f24a28b05ff78738e790eec7cee2bbab - couldn't reproduce the issue
- Brave 0.18.17 rev ed669174c8a9be987caa1fccd507d4a7e4b11987 - couldn't reproduce the issue
- Brave 0.18.18 rev f3f5cc6ca729f9081e6beb94630dc5b6f23afb78 - couldn't reproduce the issue
- Brave 0.18.19 rev 66c3027f9e319706838aa782a716c9e6d7056718 - couldn't reproduce the issue
- Brave 0.18.20 rev 60bb9e64f43f1b078e1a3276bfbc3d08125249e5 - couldn't reproduce the issue
- Brave 0.18.21 rev 263b6d548c9fa2b5000d087173e63a4ce514247e - couldn't reproduce the issue
- Brave 0.18.22 rev d850e287ace296e2c62e28ba2979cf172e41cc45 - couldn't reproduce the issue
- Brave 0.18.23 rev 36ae2ec06efed0057ae16351108bf4d4c10a7ab4 - couldn't reproduce the issue

**Comment by bridiver** [comment] 2017-08-25 00:08
webview.inspectElement no longer exists. `webviewActions.inspectElement(nodeProps.x, nodeProps.y)` should be converted to an appAction that passes tabId, x, y to call `inspectElement` on the webContents along with everything else in webviewActions. `webview` methods are deprecated in general and we should be converting them to actions that run on the browser process

**Comment by bridiver** [comment] 2017-08-25 23:38
`inspectElement` was removed because I didn't notice the usage when I was searching for webview methods, but at this point a browser-laptop fix is faster and better and @NejcZdovc already has one

**Closed** 2017-08-26 08:38 UTC
Labels: bug, feature/developer-tools, QA/steps-specified, release/blocking
