### ISSUE TITLE
site-level saved username menu overlaying upper-left corner of the active tab

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#14867] opened 2018-07-29 04:59 UTC
### Description

On Windows10, I'm consistently seeing my site-level saved credential options display in the upper left corner of the active tab. 

I see this in addition to the expected behavior; populating in-page, within a form field. 

This is what I'm observing - 
![brave-creds-taboverlay-07282018](https://user-images.githubusercontent.com/8979240/43363060-75931136-92b0-11e8-906b-75eb1a06c1c7.PNG)

I'm using the Brave password manager in the browser. 

The accurate username will display per domain, as expected. 

The overlay in the upper left is unexpected. 

When I selected the saved username that displayed over the tab, the authentication did not take place as expected. 

I'm able to consistently repro this on more than one win10 machine. 
### Steps to Reproduce

  1. Using win10, open Brave and authenticate with a domain. Save the password (using the Brave password manager. 
  2. Login to the domain. 
  3. Sign out of the domain. 
  4. Repeat for another domain. 
  5. Relaunch Brave. 
  6. Navigate to one of the two domains, and you will likely see the saved username display in the upper left corner of the active tab. 

**Actual result:**

see above. 

**Expected result:**
no overlay menu on the tab. menu only appears in-page in the form field, where expected. 

**Reproduces how often:**

100% for me

### Brave Version

**about:brave info:**

 
Brave: 0.23.39 
V8: 6.7.288.46 
rev: a38be75ccb0f699f507b66c4d44b3b21d1677e25 
Muon: 7.1.6 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**

Yes

**Comment by eljuno** [comment] 2018-07-29 20:03
#12733?

**Comment by bsclifton** [comment] 2018-08-06 18:36
@eljuno great catch- this is a dupe of #12733 - per the following comment, this is expected behavior:
https://github.com/brave/browser-laptop/issues/12733#issuecomment-359529333

**Closed by bsclifton** 2018-08-06 18:36 UTC
Labels: OS/Windows, feature/tabsbar
