### ISSUE TITLE
lots of regions on the titlebar can't be dragged but should be able to be dragged

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#4235] opened 2016-09-23 12:24 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Some important areas of the Window are not draggable on Windows.

**Expected behavior:**
The expected areas in the screenshot should allow dragging.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7

- Brave Version:
0.12.2

- Steps to reproduce:
    1. Try to drag one of the areas in the screenshot
    2. It doesn't drag.

- Screenshot if needed:
<img width="1018" alt="screenshot 2016-09-23 08 16 09" src="https://cloud.githubusercontent.com/assets/831718/18785439/3c23eb12-8166-11e6-949f-57de42c040cd.png">

- Any related issues:
https://github.com/brave/browser-laptop/issues/3036

**Comment by bsclifton** [comment] 2016-09-23 16:49
Reproduced- only happened when magnification was set to 150%

**Comment by srirambv** [comment] 2016-09-24 13:23
Similar issue with RC3 build on Windows 10. System magnification is set at 125%. Irrespective of the magnification level same result on Win 10.

![drag](https://cloud.githubusercontent.com/assets/17010094/18808743/67f689a0-8262-11e6-9531-809081f669c6.gif)

**Comment by srirambv** [comment] 2016-09-24 21:43
Similar drag issue on Linux. When trying to drag in titlebar regions it shows bookmark contents 

![4235](https://cloud.githubusercontent.com/assets/17010094/18811473/2dc98f02-82a8-11e6-8bd4-437cbb8fe57a.gif)

**Comment by luixxiul** [comment] 2016-09-25 04:31
You cannot drag the area in the screenshot.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18813029/58c08176-8324-11e6-91dd-8c416c4b794c.png)

**Comment by bsclifton** [comment] 2016-09-25 05:55
Some of these areas are going to be REALLY hard to get working. There are problems to be aware of with marking every single pixel as draggable on Windows:
1. when it's close to the edge, the cursor won't allow resize unless your mouse is directly over the very edge pixel. Marking as non-draggable gives more leniency (maybe 5px hitbox for resizing)
2. any areas marked as draggable will show the windows system menu (min/max/restore/close/etc) when right clicked. This means we can't show custom menus here. This is why the bookmarks toolbar area is not draggable, same with the tabs row. If we make them draggable, the right click -> add bookmark/add folder/etc context menu will no longer show up
3. Areas being marked as draggable alter divs which overlap it, even if the div has a higher z order. This broke the menus (making the first item not selectable unless you were near the bottom)

CC: @bbondy and @bradleyrichter - what is the acceptable criteria with respect to dragging? I'm hesitant to make any changes because I've spent hours compromising between draggability and fixing bugs (which might seem unrelated) caused by dragging :frowning:

**Comment by bbondy** [comment] 2016-09-25 11:20
re 1: We want to work like normal windows, which should be possible considering chrome does the same. 
re 2: that's fine, we don't have bookmarks toolbar draggable already in older builds on windows.
re 3: disable the draggability when the menu is expanded.

**Comment by bbondy** [comment] 2016-09-25 11:31
Note that there is an area above the urlbar that has no resize cursor and the window is not draggable.

**Comment by bbondy** [comment] 2016-09-25 11:46
I'm still having the following areas that are not draggable in 150% DPI. 
It feels like the app is completely broken right now because it feels like the window can't be dragged, I have to work hard to successfully move the window, usually after about 30 seconds of trying to drag it in various locations. After spending more time I figured out the draggable and non draggable areas. In pink is the parts I can't drag at all, in yellow is the parts I can usually drag but sometimes doesn't work because it changes to a text input cursor:

<img width="602" alt="screenshot 2016-09-25 07 40 20" src="https://cloud.githubusercontent.com/assets/831718/18815076/64eebf52-82f3-11e6-97a6-ba0918a0951d.png">


I don't want to do it because there are a lot of changesets but we might need to revert titlebar out of master if we can't get this solved so we can get 0.12.2 out the door and reland when the draggable region is working.   Anyone who experiences the above that I did would stop using the browser so let me know your preferences if we should revert for now or not.  125% DPI seems not so bad, but there is an area above the urlinput that can't be dragged and it's not a resize region either. I suspect some code in electron that is responsible for the drag region on windows is not taking dpi into consideration.

**Closed** 2016-09-27 04:55 UTC
Labels: regression, titlebar, verified
