### ISSUE TITLE
URL Not letting me change in the middle of text

### ISSUE THREAD

**Issue by pietercdevries** [brave/browser-laptop#7770] opened 2017-03-17 21:21 UTC
- Did you search for similar issues before submitting this one?
No

- Describe the issue you encountered:
When trying to modify in the middle of a url it won't let me.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win7 PO

- Brave Version (revision SHA):
Newest

- Steps to reproduce:
    1. 
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by pietercdevries** [comment] 2017-03-17 22:02
I guess it works but I have to move my mouse up to be in the middle of the textbox. It would be better to just click in the textbox anywhere. Thanks

**Comment by Liunkae** [comment] 2017-03-18 04:56
Is this behavior found in other browsers?

**Comment by pietercdevries** [comment] 2017-03-18 06:27
No Chrome does not have this issue. It is just that your mouse can be in the bottom of the textbox and the mouse is still a pointer. It should let me change the url since the top of the mouse has entered the textbox. It is a minor problem but is quite annoying. Thanks for your response.

**Comment by Liunkae** [comment] 2017-03-18 17:28
Is this the problem you are talking about? Screencast:
![untitled](https://cloud.githubusercontent.com/assets/19424103/24074420/2894993e-0bd6-11e7-8477-127a7f897d27.gif)

**Comment by pietercdevries** [comment] 2017-03-20 16:36
No try to have dual screen on windows 7 pro. Both 27".
When you load the program it works fine but the close maximize are not completely visible.
When you make the window go to maximize the behavior changes and the url is not clickable but way up higher in the box.

Here is a screen shot on how the program loads.
![untitled](https://cloud.githubusercontent.com/assets/25603029/24110425/a28501c2-0d50-11e7-9677-ae36107c47c0.png)

**Comment by Liunkae** [comment] 2017-03-20 19:02
@pietercdevries OK, now I understand. What is the DPI of your display? There are a few issues when the DPI is not 100%: #4561, #7648.

Looks the problem I mentioned above is separate, and I'll post a separate issue.

Side note: I cropped your screenshot to only show the relevant UI and remove personal info. (I hope you don't mind. 😉 )

**Comment by pietercdevries** [comment] 2017-03-21 01:20
That is fine. 
I do have dpi at 100% tho

**Comment by Liunkae** [comment] 2017-03-21 01:39
OK, good to know. I'm pretty sure there's a related issue with multiple displays, but I can't seem to find it at the moment…

**Comment by bsclifton** [comment] 2017-05-05 17:08
Closing this as a duplicate of https://github.com/brave/browser-laptop/issues/7641

**Closed by bsclifton** 2017-05-05 17:08 UTC
Labels: bug, feature/URLbar, OS/Windows
