### ISSUE TITLE
Hover over tab: Increase time before showing preview

### ISSUE THREAD

**Issue by christopherjenness** [brave/browser-laptop#3617] opened 2016-08-31 17:30 UTC
When hovering over the tab, the preview appears so quickly that it often happens on accident and is not desirable.  It would be good to lengthen the time, or perhaps have an option for length in the preferences for the user to set.

**Comment by Sh1d0w** [comment] 2016-08-31 17:35
Closing as duplicate of #3271

**Closed by Sh1d0w** 2016-08-31 17:35 UTC
