### ISSUE TITLE
Open multiple windows by default

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5553] opened 2016-11-11 00:06 UTC
This came in from support but I'm not very familiar with the feature. With internet explorer you can have essentially multiple home pages that all open when you launch the browser. So you could say have your four favorite tabs all open every time you launch.

This user is wanting that added as an enhancement for Brave.

**Comment by Liunkae** [comment] 2016-11-11 08:02
Same feature as #3110?

**Comment by srirambv** [comment] 2016-11-11 08:28
@jkup You can advice users to use the steps mentioned here https://github.com/brave/browser-laptop/issues/3110#issuecomment-239388042 

This works all the time.

**Comment by bsclifton** [comment] 2017-01-30 07:18
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/3110

**Closed by bsclifton** 2017-01-30 07:18 UTC
Labels: enhancement
