### ISSUE TITLE
UX: new-tab URL bar blocked for ~12ms

### ISSUE THREAD

**Issue by shaunlebron** [brave/browser-laptop#12130] opened 2017-11-29 00:33 UTC
### Description
When starting a new tab for a search, I often type my query in quick succession of pressing <kbd>⌘</kbd>+<kbd>T</kbd>.  But this does not work in Brave, because the URL bar for the new tab takes ~12ms to focus, which hurts the UX of this flow ever so slightly to frustrate.  (There is no delay in Chome/Firefox/Safari.)

### Gifs

Gif demos shown below at 0.1x.  Notice that the new-tab URL bar is focused immediately in Chrome/Firefox/Safari but not Brave.

browser | delay | demo at 0.1x speed
---|---|---
Brave | ~12ms | ![brave-slow-tab](https://user-images.githubusercontent.com/116838/33351431-6d92ab50-d469-11e7-90dd-bde1ed4da68b.gif)
Chrome | 0 | ![chrome-fast-tab](https://user-images.githubusercontent.com/116838/33351432-6da0d9c8-d469-11e7-8313-ca745932d32c.gif)
Firefox | 0 | ![firefox-fast-tab](https://user-images.githubusercontent.com/116838/33351433-6daee25c-d469-11e7-95da-8ec4eaa4e96a.gif)
Safari | 0 | ![safari-fast-tab](https://user-images.githubusercontent.com/116838/33351434-6dbff998-d469-11e7-96ec-d2ac1eb19b0a.gif)

### Steps to Reproduce

  1. <kbd>⌘</kbd>+<kbd>T</kbd>
  2. immediately type `hello`

**Actual result:**
new-tab URL bar reads `llo`

**Expected result:**
new-tab URL bar reads `hello`

**Reproduces how often:**
everytime

### Brave Version

**about:brave info:**
 
Brave: 0.19.95 
rev: cc0ebadfd8950d1b5f454cb39c0c3a64028cc935 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Reproducible on current live release:**
(haven't tried)

**Comment by pllearns** [comment] 2017-11-29 22:02
FWIW: I have OS Release at 17.2.0 and I can't reproduce this issue.

**Comment by bsclifton** [comment] 2018-08-23 21:07
Closing as I believe this was fixed when we did the single webview improvement (unable to reproduce)

**Closed by bsclifton** 2018-08-23 21:07 UTC
Labels: initiative/perf, perf, priority/P4, usability
