### ISSUE TITLE
Brave always launches on monitor 3

### ISSUE THREAD

**Issue by sirjorj** [brave/browser-laptop#14901] opened 2018-08-01 22:39 UTC
### Description

Ever since the last update (0.23.73), launching brave will make it spawn its first window on monitor 3 on my 3-monitor LInux Mint system.

### Steps to Reproduce

  1. Launch Brave
  2. Mutter some unkind words
  3. Drag window from Monitor 3 to Monitor 1 (or 2)

**Actual result:**

New windows always launch on monitor 1

**Expected result:**
New window launches on whatever monitor it was last closed on

**Reproduces how often:**

Every time since last update (0.23.73)

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.23.73
V8 | 6.8.275.24
rev | 50bdb6d
Muon | 8.0.3
OS Release | 4.15.0-29-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.75

**Reproducible on current live release:**

I dont know

**Comment by bsclifton** [comment] 2018-08-01 23:04
@sirjorj just to confirm: this worked great before?

**Comment by sirjorj** [comment] 2018-08-01 23:11
Yeah - now browser windows always open on my tv and not the 2 monitors on my desk.

**Comment by bsclifton** [comment] 2018-08-06 22:08
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/2438

**Closed by bsclifton** 2018-08-06 22:08 UTC
Labels: bug/dpi/monitor
