### ISSUE TITLE
Allow a per-site preference for popups

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4698] opened 2016-10-12 06:16 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user from support (https://linkbubble.zendesk.com/agent/tickets/6137) uses a site which requires popups and would like the ability to allow popups for that particular site.

**Expected behavior:**
We should allow users to per-site affordances to utilize their chosen sites effectively.
- Platform (Win7, 8, 10? macOS? Linux distro?):
- Brave Version:
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by Sh1d0w** [comment] 2016-10-12 07:47
Isn't this duplicate of https://github.com/brave/browser-laptop/issues/3752 :) ?

**Comment by srirambv** [comment] 2016-10-19 04:21
+1 from support (https://linkbubble.zendesk.com/agent/tickets/6124)

**Comment by srirambv** [comment] 2017-05-02 11:53
+1 from community https://community.brave.com/t/how-to-enable-popups/2567/2

**Comment by bsclifton** [comment] 2017-06-13 23:01
Closing as a dupe of https://github.com/brave/browser-laptop/issues/3752

**Closed by bsclifton** 2017-06-13 23:01 UTC
Labels: suggestion
