### ISSUE TITLE
Importing data from Firefox not working

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6604] opened 2017-01-11 11:56 UTC
**Describe the issue you encountered:**

https://community.brave.com/t/doesnt-import-bookmarks-from-firefox/179/15?u=suguru

> First, I tried to import the bookmarks only, no history, no cookies (failed as stated above). Now I tried to import all options – brave crashed (application is not responding). Then I tried to import bookmarks and browser history (no cookies) – brave crashed. Then I tried to import bookmarks and cookies (no browser history): It says, bookmarks successfuly imported, which is not true (same error as stated above).

And https://community.brave.com/t/importing-data-from-firefox-causes-a-crash/664

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Screenshot if needed:

- Any related issues: #4506 

CC @darkdh

**Comment by bsclifton** [comment] 2017-03-14 08:43
Moving to 0.13.7

**Comment by bsclifton** [comment] 2017-04-05 06:57
moving to 0.14.3

**Comment by bbondy** [comment] 2017-04-17 16:04
I think this is a 1 user issue, but if this is a general issue let's prioritize higher. Removing from 0.15.1 for now.

**Comment by Jochumdeer** [comment] 2017-05-30 19:49
I've had the same issue. Now it doesn't even help to reinstall Brave. It's somehow saved the import of data. This is with data imported from FF. Only I didn't import cookies, just bookmarks and history. 
Any way to delete so I at least can use Brave without importing, until the problem is solved?

**Comment by luixxiul** [comment] 2017-10-05 05:24
Several users are reporting the issue here: https://community.brave.com/t/firefox-bookmarks-wont-import/6720

**Comment by nateritter** [comment] 2018-01-10 16:51
@bbondy Definitely not a 1 user issue. I'm experiencing this on same exact issue.


Brave | 0.19.131
-- | --
rev | da2f347
Muon | 4.5.36
libchromiumcontent | 63.0.3239.132
V8 | 6.3.292.49
Node.js | 7.9.0
Update Channel | Release
OS Platform | macOS
OS Release | 17.3.0
OS Architecture | x64

Tried:
* directly importing everything from FF
* directly importing just bookmarks from FF
* exported FF bookmarks to HTML file and importing from that file

All attempts hang Brave and eventually crash it.

**Comment by fermulator** [comment] 2018-01-20 04:20
Same here :( - blocking me from switching
```
Brave: 0.19.139 
rev: 99aa17da28e040543b4ba217d2c4dd6633bf1446 
Muon: 4.7.2 
libchromiumcontent: 64.0.3282.85 
V8: 6.4.388.20 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.10.0-42-generic 
OS Architecture: x64
```

**Comment by bsclifton** [comment] 2018-01-22 06:12
cc: @darkdh

**Comment by darkdh** [comment] 2018-01-23 00:16
@fermulator would you mind provide the latest crash dump located in `~/config/brave/CrashPad` when crash happens?

**Comment by fermulator** [comment] 2018-01-23 03:41
@darkdh I don't think we'll get one as this is an OOM crash.
```
$ ll ./.config/brave/CrashPad
total 8
drwx------  2 fermulator fermulator 4096 Jan 17 18:15 ./
drwx------ 15 fermulator fermulator 4096 Jan 22 21:38 ../
```

**Comment by fermulator** [comment] 2018-01-23 03:48
FYI: I dropped in a standard ubuntu apport submission:
 * https://errors.ubuntu.com/oops/6bca32c8-ffef-11e7-b27e-fa163eec78fa

**Comment by fermulator** [comment] 2018-02-02 02:41
@darkdh , @bsclifton 

I don't think I'd like to sit on this too much longer (anxious to move forward).

I may be able to provide a fix, but need a "kick start" for how to debug this. Would anyone on your team be available to have a short session with me (or add comments here) as to some reasonable next steps to:
 A) provide more debug/isolation for root cause
 B) solution a fix in the code

**Comment by darkdh** [comment] 2018-02-03 02:35
@fermulator does it happen only import bookmark?
can you help me to narrow down which data imported cause this crash?
(choose only one thing to import from history, bookmark, cookies or save password each time you import from firefox)

**Comment by eljuno** [comment] 2018-02-21 20:57
+1 from community https://community.brave.com/t/brave-crashes-upon-import-of-firefox-data/16627?u=eljuno

Select ‘Browser history’, ‘Bookmarks’, ‘Cookies’, ‘Saved Passwords’ - crashed.
Select ‘Browser history’, ‘Bookmarks’, ‘Cookies’ - crashed.
Select ‘Browser history’, ‘Bookmarks’ - did not crash.

Brave: 0.20.42
V8: 6.4.388.41
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed
Muon: 4.8.2
OS Release: 6.1.7601
Update Channel: Release
OS Architecture: x64
OS Platform: Microsoft Windows
Node.js: 7.9.0
Brave Sync: v1.4.2
libchromiumcontent: 64.0.3282.140

**Comment by eljuno** [comment] 2018-02-23 18:59
+1 from community on macOS https://community.brave.com/t/brave-crashing-when-importing-data-from-firefox/16768?u=eljuno

> I clicked the import button with all options (bookmarks, cookies, etc.) selected. It ran for a few seconds, then the browser crashed completely...

**Comment by RenaudParis** [comment] 2018-03-04 22:06
Brave also crashes on my computer (Windows 7) when importing cookies (and only for cookies) from Firefox.

**Comment by eljuno** [comment] 2018-03-19 19:31
+1 from community https://community.brave.com/t/importing-from-firefox-crashes-brave/18151?u=eljuno

> When I tried just importing bookmarks, that seemed to work. I then tried to import cookies and it crashed. Upon restart, the imported bookmarks had gone.

**Comment by merryHunter** [comment] 2018-03-22 08:29
+1 Ubuntu 16.04 Brave 0.21.24, importing cookies, bookmarks , passwords

**Comment by riegelstamm** [comment] 2018-04-02 00:37
+1 macOS 10.13.3 Brave 0.21.24 importing from Firefox bookmarks, cookies, history, together and separately

**Comment by hasufell** [comment] 2018-06-11 22:23
Same here, happening on cookies. Lots of `Error: Setting cookie failed` in the console and then
```
Crash dump id: 839dee8ff123a969
Segmentation fault
```

**Comment by Barthelemy** [comment] 2018-06-20 06:42
Same with 0.22.810 on mac.

**Comment by etnevels** [comment] 2018-06-23 22:29
Same problem, try to import Firefox and Brave closes, nothing imported. Windows 7 professional

**Comment by pk27734** [comment] 2018-06-24 08:39
I experience the same issue on macOS, importing only Cookies from Firefox makes Brave crash. Do you need any crashdumps/logs?

**Comment by 5umm1t** [comment] 2018-07-03 17:38
Same problem. Win 10 Pro.

**Comment by Appalbarry** [comment] 2018-07-25 04:34
Here too. Mint Cinnamon Linux 19 from the current version of Firefox.

Brave: 0.23.39 
V8: 6.7.288.46 
rev: 3ee14b026f09d7d71c1985b4a9c9a11d78ab8f49 
Muon: 7.1.6 
OS Release: 4.15.0-29-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Comment by miasmaejuices** [comment] 2018-09-15 04:01
Confirmed the issue also exists on:

Brave | 0.23.107
V8 | 6.8.275.24
rev | 6f2fc65
Muon | 8.0.10
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Tor | 0.3.3.8 (git-99f9816efa08ab83)
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

Thanks :)

**Comment by bsclifton** [comment] 2018-09-15 07:54
This issue should be resolved if you use our new [Developer channel release](https://brave.com/download-dev). We won't be fixing this with our current Muon based browser

**Closed by bsclifton** 2018-09-15 07:54 UTC
Labels: bug, crash, feature/importer, fixed-with-brave-core

**Comment by hasufell** [comment] 2018-09-16 07:00
> This issue should be resolved if you use our new [Developer channel release](https://brave.com/download-dev).

That new brave browser seems to be based on chromium, which is known to be privacy invasive (look at the patch work from [inox](https://github.com/gcarq/inox-patchset) and [ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium)). Have you done similar work to fix this? If not, how would I trust that browser?

**Comment by bsclifton** [comment] 2018-09-21 06:14
@hasufell yes, we have taken steps to neutralize those features. If you wanted to see specifics, you can check out the issue where items were called out:
https://github.com/brave/brave-browser/issues/13
