### ISSUE TITLE
Crash: clicking on links in Youtube mails or links posted in Twitter posts

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#469] opened 2016-01-30 18:43 UTC
Browser is crashing when clicking for example on a song link in a Soundcloud info mail which has arrived on Google mail. Browser is just instantly closing without any error message.

**Comment by SJ-Diamond** [comment] 2016-01-30 21:13
Another page with a crash which can be reliable produced here under Windows 8:

https://soundcloud.com/fod-steve - on the right on the link for his fodxm page, make middle mouseclick to open it in a new tab, the browser is instantly closing.

**Comment by bbondy** [comment] 2016-01-31 03:02
Possible dupe of #412

**Comment by bridiver** [comment] 2016-01-31 16:44
twitter links are fixed with https://github.com/brave/electron/pull/7 but I'm not sure how to replicate the other issue.

**Comment by SJ-Diamond** [comment] 2016-01-31 17:01
As written, go to https://soundcloud.com/fod-steve and look out for the link to "fodxm" on the right under followers/following/tracks - make a middle mouse click on it and the browser is closing instantly. Happens everytime here on Windows 8 - Can also reproduce this behavior on various bandcamp links on the bandcamp link page, for example when clicking on my profile and making a middle click to open one of the releases in my collection in a new tab.

Browser is instantly closing.

**Comment by bridiver** [comment] 2016-01-31 17:24
I was looking at the soundcloud info email and missed info in the second message. Working on a related issue right now that should fix this

**Comment by SJ-Diamond** [comment] 2016-01-31 17:32
Thank you, you guys are really fast in fixing things!

**Closed** 2016-01-31 19:16 UTC
