### ISSUE TITLE
Add cookie count in site shield metrics

### ISSUE THREAD

**Issue by dhiva** [brave/browser-laptop#6429] opened 2016-12-26 22:37 UTC
**Did you search for similar issues before submitting this one?**
yes

Please add the ability to see the number of cookies created when visiting the site in the site shield info drop down. Also a way to see all the cookie names and its contents when the cookie metrics is clicked for detailed view.

**Comment by luixxiul** [comment] 2017-11-05 09:01
I'm going to close this as duplicate of https://github.com/brave/browser-laptop/issues/2398

For now I'm going to close this issue in favor of this topic on our community site.

If you are still around here, would you please join https://community.brave.com? :smile: There is a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!

**Closed by luixxiul** 2017-11-05 09:01 UTC
Labels: suggestion
