### ISSUE TITLE
Remove Single Item from URL Suggestion

### ISSUE THREAD

**Issue by shortstuffsushi** [brave/browser-laptop#11398] opened 2017-10-09 16:17 UTC
I searched a bit for this, as did @jonathansampson, and wasn't able to find a similar issue. Feel free to close if duplicated.

The URL suggestion bar sometimes picks up specific site links I don't want. In my case, I have some "newson6.com" link -- not even sure where it's from, and I don't want it to be suggested when I start a search term "news." Similar things seem to happen where I get results with specific query strings appended that aren't relevant, or URL paths instead of root... the list goes on.

Ultimately, I would like a function allowing me to clear individual suggestions, either via a keyboard shortcut (delete, shift delete, ctrl delete, etc) or via right-click + delete option.

**Comment by bsclifton** [comment] 2017-10-30 16:10
Thanks for the report, @shortstuffsushi 😄 

I'll close this as a dupe of https://github.com/brave/browser-laptop/issues/9094 and give that one a bump on your behalf.  Thanks for capturing the issue in good detail

**Closed by bsclifton** 2017-10-30 16:10 UTC
