### ISSUE TITLE
printToPDF doesn't do anything

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#11471] opened 2017-10-12 01:05 UTC
This one doesn't have an easy STR because we only call it from the contribution statement.

**Comment by darkdh** [comment] 2017-10-12 03:37
@bridiver, we can use `npm run add-simulated-payment-history` to generated fake payment history.

**Comment by LaurenWags** [comment] 2017-10-25 14:38
Verified using these steps:
Had a profile with 0.19.66 where payments were enabled, closed Brave.
Renamed profile to be brave-development.
Built 0.19.x from source. 
Ran npm run add-simulated-payment-history. 
Renamed brave-development back to brave.
Opened 0.19.66 again.
Went to about:preferences#payments.
Opened payment history and clicked on a link.
On the new tab that opened with the contribution statement, verified I was prompted to save my statement. Verified I could save a statement. Verified I could cancel saving a statement.

cc @bridiver @darkdh @kjozwiak for confirmation these steps are sufficient for testing.

**Comment by srirambv** [comment] 2017-10-25 14:52
Verification fails on Windows
STR
1. Clean install 0.19.66 and enable payments and close the browser
2. Build from source and run `npm run add-simulated-payments-history 50`
3. Copied the `ledger-state.json` from `%appdata%/brave-development` to `%appdata%/brave`
4. Launch the browser, click on payment history button
5. Click on any entry, opens a new tab with the contribution statement
6. No save prompt shown for the contribution statement tab

**Comment by srirambv** [comment] 2017-10-25 14:53
@bridiver @darkdh  any steps that I missed?

**Comment by darkdh** [comment] 2017-10-25 16:56
@LaurenWags, @srirambv you are both right. 
I just verified printToPDF doesn't work on Windows.

**Comment by srirambv** [comment] 2017-10-25 18:19
@kjozwiak confirmed save prompt shown on Linux. Seems to be still an issue only on Windows

cc: @darkdh

**Comment by luixxiul** [comment] 2017-10-26 03:49
I also confirmed it worked for me on Debian.

**Comment by bbondy** [comment] 2017-10-26 14:51
Moving to hotfix 3

**Comment by bbondy** [comment] 2017-10-31 19:37
Moving to hotfix 4

**Closed** 2017-11-01 03:52 UTC
Labels: bug, cr62, QA/test-plan-specified, regression, release/blocking

**Comment by srirambv** [comment] 2017-11-01 13:55
Works fine on 0.19.72 for Windows. Prompts save file option when opening the payment statement

**Comment by kjozwiak** [comment] 2017-11-01 15:24
@LaurenWags, can you double check and make sure this is working on macOS? I want to make sure the new fix hasn't regressed the other platforms as well. I'll check on Ubuntu.

**Comment by LaurenWags** [comment] 2017-11-01 15:36
Still works on MacOS @kjozwiak
