### ISSUE TITLE
Title is not updated when using navigation buttons

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8908] opened 2017-05-17 11:43 UTC
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Title is not updated when using navigation buttons
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
8bb62f7
- Steps to reproduce:
    1. go to site clifton.io
    2. create a history
    3. click on back/forward buttons

![18](https://cloud.githubusercontent.com/assets/9574457/26152295/a5ff8eba-3b06-11e7-85b3-ecddc9a8b7c4.gif)

    
- Actual result:
sometimes tab title is not display (location is shown)
- Expected result:
title should be displayed
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
no
- Can this issue be consistently reproduced?
not all the time but with few clicks you can see a problem

**Comment by bsclifton** [comment] 2017-05-19 16:40
Closing as a dupe of https://github.com/brave/browser-laptop/issues/7765.  If I'm wrong about this (ex: title does not update on mouse over) please reopen.  Thanks 😄

**Comment by NejcZdovc** [comment] 2017-05-20 08:43
This is not a dupe, because as you can see in a gif if you hover over it nothing changes. I debug it a little bit and title is not set in our state (in #7765 everything is set ok, just DOM is not displayed correctly). So this regressed somewhere (race condition or something is not updating) when we were refactoring tabs. I think that this needs to be fixed in 0.15.30x, because this is something that is not happening in 0.15.2 and it's really bad.

**Comment by bsclifton** [comment] 2017-05-21 07:15
This is what causes the title to change:
https://github.com/brave/browser-laptop/blob/master/app/renderer/components/main/main.js#L323

Looking at the code here, it looks like this was a known issue and a hacky work-around was put in place:
https://github.com/brave/browser-laptop/blob/master/app/renderer/components/frame/frame.js#L654

cc: @NejcZdovc @bridiver

**Closed** 2017-05-22 19:01 UTC
Labels: feature/navbar, feature/tabsbar, regression
