### ISSUE TITLE
Alt Gtr(Right Alt Key) doesn't show File Menu on Windows 7.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2885] opened 2016-08-02 17:41 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Pressing Alt-Gtr  key on Windows 7 doesn't show the file menu.
Keyboard settings:  EN-US, EN-UK, EN-IN, EN-IR

**Expected behavior:**
Pressing Alt key (right/left) show show the file menu when hide menu bar is enabled in pref
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7 x32/64 Professional

- Brave Version:
0.11.2 Dev Beta 2

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment] 2016-08-11 17:33
This appears to be the root cause:
https://github.com/brave/electron/blob/master/atom/browser/native_window_views.cc#L83

If we want the right ALT button sent also, which has a different virtual key code, we'd need to update the code like so:
```
bool IsAltKey(const content::NativeWebKeyboardEvent& event) {
  return event.windowsKeyCode == ui::VKEY_MENU || event.windowsKeyCode == VKEY_ALTGR;
}
```

Searching the electron code, this doesn't seem like it would have a large impact.  It would also enable keyboard accelerators to work with the right alt (that is something else you can test, @srirambv)

Good find :smile:

**Comment by bsclifton** [comment] 2016-10-20 15:40
Closing this as we don't want this behavior.  For more info, see https://github.com/brave/browser-laptop/issues/4626

**Closed by bsclifton** 2016-10-20 15:40 UTC
Labels: feature/keyboard-shortcuts, OS/Windows, suggestion
