### ISSUE TITLE
Crashes on wral.com articles

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-laptop#2047] opened 2016-06-03 12:55 UTC
http://www.wral.com/waterlogged-texas-braces-for-more-rain-as-flooding-continues/15747854/
Consistently result in "Unexpected Error Occurred," but usually work fine on "Retry."

**Comment by SergeyZhukovsky** [comment] 2016-06-03 12:56
I've tried it and Brave just closes for me with the above link.

**Comment by SergeyZhukovsky** [comment] 2016-06-03 13:10
Also I have a crash on http://www.thelakewoodscoop.com/
very often. But it crashes only when you click on the link from other tab. For example send it to your gmail and open from your gmail inbox(just click on it). If I paste it to URL bar it works great always.

**Comment by luixxiul** [comment] 2016-06-03 13:12
I cannot reproduce it on Windows 10.

**Comment by SergeyZhukovsky** [comment] 2016-06-03 13:15
I did on OSX.

**Comment by luixxiul** [comment] 2016-06-03 17:04
Reproducible on v0.10.1 Dev Channel RC3, on Windows 10

**Comment by bridiver** [comment] 2016-06-07 21:57
@SergeyZhukovsky the gmail issue was another bug that is now fixed. I'm not sure what fixed this, but I'm not able to reproduce with latest master for browser and electron

**Closed** 2016-06-14 03:14 UTC
Labels: crash

**Comment by luixxiul** [comment] 2016-06-14 11:58
Me neither, on Ubuntu 14.04.
