### ISSUE TITLE
Feature: Allow multiple instances / windows

### ISSUE THREAD

**Issue by SpikeShape** [brave/browser-laptop#5706] opened 2016-11-17 07:25 UTC
I would like to either pull a tab from one window and have it as a separate instance or just open a new window from the Dock. This way I can have it on different desktop instances.

MacOS Yosemite 10.10.5

**Comment by Liunkae** [comment] 2016-11-18 06:28
Duplicate of #405. This feature is already planned to be implemented (see the issue for more details).

**Closed by Liunkae** 2016-11-18 06:28 UTC
