### ISSUE TITLE
Bug: Session gets wiped out when clicking on the x (close) button

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#881] opened 2016-02-23 22:36 UTC
If i click on the "x" closing symbol, all open tabs are lost and the next time i start the browser, i have an empty session. If i click instead on the Hamburger button and Quit Brave, the session stays also for the next browser start.

**Comment by bbondy** [comment] 2016-02-24 00:15
I think this is a dupe of your bug here:
https://github.com/brave/browser-laptop/issues/758

**Comment by bbondy** [comment] 2016-02-24 00:16
It's planned for 0.7.16 btw

**Closed by bbondy** 2016-02-24 00:15 UTC

**Comment by SJ-Diamond** [comment] 2016-02-24 08:01
Not really a dupe. Sorry, somehow i have forgotten a part what i wanted to write. This special bug appears especially when i close the broswer window before the tabs have been all loaded into memory.

In that case session is also lost when closing and reopening.

**Comment by bbondy** [comment] 2016-02-25 21:34
Still a problem with 0.7.16? If so I'll re-open

**Comment by SJ-Diamond** [comment] 2016-02-25 21:45
Does now work fine, tried it right now, fixed and thanks :)
