### ISSUE TITLE
Not work Custom filters (macOS, 0.12.5dev)

### ISSUE THREAD

**Issue by roman-kosov** [brave/browser-laptop#4733] opened 2016-10-13 08:19 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
I do not understand how it works of _Custom filters_.
1. I'm putting in filters of Adblock
2. I'm putting in URLs of filters of Adblock

**Expected behavior:**
Need a work
- Platform:
  macOS 10.10.5
- Brave Version:
  Brave: 0.12.5
  Electron: 1.4.13
  libchromiumcontent: 53.0.2785.143
  V8: 5.3.332.47
  Node.js: 6.5.0
- Screenshot if needed:
  [https://gfycat.com/BitterImpracticalIberianchiffchaff](https://gfycat.com/BitterImpracticalIberianchiffchaff)

**Comment by bsclifton** [comment] 2018-10-01 03:01
Duplicate of https://github.com/brave/browser-laptop/issues/12308

**Closed by bsclifton** 2018-10-01 03:01 UTC
Labels: feature/adblock
