### ISSUE TITLE
Option to completely disable URL bar autocomplete

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7628] opened 2017-03-08 23:57 UTC
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment] 2017-06-04 15:44
Now https://github.com/brave/browser-laptop/pull/9063 was merged, `Brave Page` is the only one which cannot be disabled, and I am wondering if it should be at all.

**Comment by srirambv** [comment] 2017-06-20 15:56
+1 from community https://community.brave.com/t/disable-address-bar-autofill/4110

**Comment by luixxiul** [comment] 2017-11-05 16:09
Closing as duplicate of #3631.

**Closed by luixxiul** 2017-11-05 16:09 UTC
Labels: feature/autocomplete, feature/URLbar, needs-info

**Comment by cup** [comment] 2018-08-26 12:31
http://github.com/brave/brave-browser/issues/843
http://github.com/brave/browser-laptop/issues/3631
http://github.com/brave/browser-laptop/issues/7628
