### ISSUE TITLE
Show downloaded size on download

### ISSUE THREAD

**Issue by CardealRusso** [brave/browser-laptop#13124] opened 2018-02-13 18:17 UTC
### Description
When the download have no file size in header, Brave just say "Downloading". Could be better to show the size downloaded, something like "123 MB..."

### Steps to Reproduce

  1. Open https://drive.google.com/uc?id=14eeKZUzAlr707dWTCJehBmCmZvKPQyXN&export=download
  2. Click download anyway
  3. See the thing

**Actual result:**
"Downloading..."

**Expected result:**
"1MB..."

**Reproduces how often:**
100%

### Brave Version

Brave: 0.20.40 
V8: 6.4.388.41 
rev: 87c8d0c56d629aa23df0d4abfe7d804e13592669 
Muon: 4.8.2 
OS Release: 6.3.9600 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Comment by bsclifton** [comment] 2018-02-28 07:30
@eljuno yup- great catch. @CardealRusso I'll close this as a duplicate of https://github.com/brave/browser-laptop/issues/7082. Thanks for the report 😄

**Closed by bsclifton** 2018-02-28 07:30 UTC
