### ISSUE TITLE
Closing tab switches to the second tab from root tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11981] opened 2017-11-15 20:07 UTC
### Description
Closing tab switches to the second tab from root tab

### Steps to Reproduce
   1. Open 3 tab pages
   2. Close a tab 
   3. Second tab from closed tab is set to focus instead of the immediate tab next to the closed one

**Actual result:**
![11632](https://user-images.githubusercontent.com/17010094/32857543-0ed861be-ca40-11e7-9255-383e03974dc2.gif)

**Expected result:**
Should set focus to the immediate tab 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.93
-- | --
rev | d2708a0
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**

### Additional Information
https://github.com/brave/browser-laptop/issues/11632#issuecomment-344521477
cc: @cezaraugusto

**Comment by LaurenWags** [comment] 2017-11-15 21:13
Seeing image below on the same build when closing (non-active) tab page, per discussion with @srirambv thought maybe it was related to this issue.
![screen shot 2017-11-15 at 4 02 15 pm](https://user-images.githubusercontent.com/28145373/32860519-d65f9b9c-ca1f-11e7-9245-3a31f54737ce.png)

**Comment by cezaraugusto** [comment] 2017-11-15 22:05
@LaurenWags changes added to fix this issue only created another check to ensure the preview is canceled, no changing for tab closing logic. Could you please open a new issue for that? Feel free to assign me too

**Comment by LaurenWags** [comment] 2017-11-15 22:16
Done @cezaraugusto :) logged https://github.com/brave/browser-laptop/issues/11985

**Comment by srirambv** [comment] 2017-12-05 17:28
This happens on the C63 build of 0.19.106
![11981](https://user-images.githubusercontent.com/17010094/33621111-ae22b1f6-d9e1-11e7-81cf-08aa9cc1b63a.gif)

**Comment by petemill** [comment] 2017-12-05 19:36
@srirambv I'm unable to see any regression here for the original description of this issue - from what I can tell the code is doing what it should - selecting the parent tab of the closed tab, which is the default setting:
![image](https://user-images.githubusercontent.com/741836/33626796-7f2f485e-d9b0-11e7-8743-b70b04103bee.png)

Did you open all these tabs by clicking links from an original window? Perhaps you could give more detailed steps that I could reproduce - most importantly how you are opening the 3 tab pages of tabs, and which tab you are closing? Thanks

**Comment by srirambv** [comment] 2017-12-05 21:11
@petemill  Opened tabs by pressing and holding down the `Ctrl+T ` to create tab pages. On 0.19.106 used Ctlr+Click to open tabs from the new tab tiles

**Comment by petemill** [comment] 2017-12-05 21:17
thanks @srirambv I see

**Comment by petemill** [comment] 2017-12-05 21:38
Confirmed reproducible on master + Windows and not macOS...

**Comment by NumDeP** [comment] 2017-12-07 03:21
Hi @petemill I made mention of this here #11526 

Perhaps I titled it incorrectly, though I only did so for the feature issues in Tab Settings to be merged and fixed together because I thought they were linked.

**Comment by NumDeP** [comment] 2017-12-07 03:22
Hi @petemill I made mention of this here #11526

Perhaps I titled it incorrectly, though I only did so for the feature issues in Tab Settings to be merged and fixed together because I thought they were linked.

**Closed** 2017-12-22 05:54 UTC
Labels: 0.19.x, bug, feature/tabsbar, PR/pending-review, priority/P4, regression

**Comment by btlechowski** [comment] 2018-02-20 21:54
Verified 0.21.9 Win64

**Comment by srirambv** [comment] 2018-03-22 17:09
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
