### ISSUE TITLE
Gmail -> Contacts -> Crash!

### ISSUE THREAD

**Issue by jpr48** [brave/browser-laptop#1749] opened 2016-05-14 04:07 UTC
If I'm looking at my gmail page 
https://mail.google.com/mail/u/0/#inbox
and I ask to see my contacts, Brave crashes. No error. It just goes away.

**Comment by luixxiul** [comment] 2016-05-14 04:13
Not reproducible on my PC. Would you please confirm that you are running the latest version of Brave?

**Comment by jpr48** [comment] 2016-05-14 12:33
'About...' reports 0.9.6
Is there anything resembling a log or crash dump that I could send you?

**Comment by jpr48** [comment] 2016-05-14 12:36
Oh boy. I noticed this problem many days ago. I would try it every few days to see if it had been fixed. Yesterday I tried right after the update to Brave and it still crashed. 
But, I tried it just now and it worked.
I hate these kind of problems. I'm a programmer. I guess you can ignore this one and close it.

**Comment by Haze-Aulaian** [comment] 2016-05-14 12:45
@luixxiul 
i have just tested on 0.9.6  x64
OS :windows 7 64 bit (sp1)
its reproducible

**Comment by luixxiul** [comment] 2016-05-14 12:53
CC: @bbondy

**Comment by Haze-Aulaian** [comment] 2016-05-14 13:06
@luixxiul you are welcome :)

**Comment by Haze-Aulaian** [comment] 2016-05-15 18:23
@bbondy  @luixxiul  btw this is specific to 64bit win7 , tested on 32 bit but it didnt happen. not sure if its specific to service pack1 though.

**Comment by bridiver** [comment] 2016-05-18 22:31
I couldn't reproduce this in master using win7 SP1 x64. Not sure what fixed it, but I'm going to close this for now. Please let us know if you see the same problem in the next release. Thanks!

**Closed by bridiver** 2016-05-18 22:31 UTC
Labels: crash

**Comment by Haze-Aulaian** [comment] 2016-05-19 06:07
@bridiver sure

**Comment by Haze-Aulaian** [comment] 2016-05-22 10:12
i confirm that this is fixed in 0.10.0 64bit
