### ISSUE TITLE
Bookmarks Manager Columns Should Scroll Independently

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8441] opened 2017-04-22 17:14 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
If a user has many folders, they may need to scroll to the bottom of the Bookmarks Manager to select their target folder, and then scroll all the way back up to the top to select their target bookmark.

Source: https://gab.ai/UncleKennyTx/posts/7172597

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.15.0

- Steps to reproduce:
    1. Navigate to the Bookmarks Manager (or press Ctrl+Shift+O)
    2. Add enough folders/bookmarks to cause the page to scroll
    3. Try to move items to/from the last folder
    
- Actual result:
The process requires too much moving around the viewport. The user has to scroll down, then up, then possibly back down again.

- Expected result:
Managing bookmarks should be simple.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Any related issues: #4201

**Comment by Liunkae** [comment] 2017-04-22 19:15
Duplicate of #5076.

**Closed by Liunkae** 2017-04-22 19:15 UTC
Labels: design, feature/bookmarks, polish
