### ISSUE TITLE
Dragging texts, crashes the browser

### ISSUE THREAD

**Issue by Kzeir** [brave/browser-laptop#2328] opened 2016-06-29 03:34 UTC
When I drag some text, even for acident, the browser crashes and restart, and I lost some pages that I was open. 

I search for similars and I didn't find so...
- Platform Win 10
- Brave Version:
  0.10.4

**Comment by luixxiul** [comment] 2016-06-30 10:32
I experience this sometimes. Not sure steps to reproduce

**Comment by Kzeir** [comment] 2016-06-30 16:08
My browser sometime crash, when I select a text with the cursor, and drag
it, just a little...

*Att: Alessandro Tetsuo More*

2016-06-30 7:32 GMT-03:00 Suguru Hirahara <notifications@github.com>:

**Comment by Kzeir** [comment] 2016-07-06 00:09
Seems been fixed, in this new update 0.11.0

**Comment by luixxiul** [comment] 2016-07-06 01:45
OK, let's see it was really fixed...

**Comment by Kzeir** [comment] 2016-07-06 02:24
No, Still there. I was in the messenger.com and drag a text by acident and the browser crashed.

**Comment by pixelass** [comment] 2016-12-12 19:42
This happens to me a lot when I try to cancel a click on a link.

#### Reproduce:
1. mousedown on link
2. move away from link
3. mouseup outside link

#### Expected behavior:
Nothing should happen. The link should not be triggered.

#### This happens
The browser crashes

#### Versions
OS X Sierra | 10.12.1 (16B2555)
Brave desktop | 0.12.14

**Comment by srirambv** [comment] 2017-02-03 14:56
Still an issue with 0.13.1

Click and drag a highlighted URL causes the webview to crash. Most easily reproducible(but not always) .

This is what happened to me on 0.13.1

1. Highlight text on a webpage/pdf, click and drag the highlighted text which causes the webview renderer to crash(Blank white screen)
2. Close the browser and reopen, all tabs and history gone but retains bookmarks and settings
3. `session-store-1` file which was ~200KB before the render crash is now 22KB

This should be addressed at least by 1.0 as users can loose their entire session data if this happens. @bbondy thoughts.

**Comment by bbondy** [comment] 2017-02-03 15:35
I think probably the session storage thing is just that it didn't auto save yet since you did an import? Probably if it saved at least once then it would be preserved.   Same as if you import and directly crash fast.

**Comment by pixelass** [comment] 2017-02-03 15:55
This was my main reason why I stopped using brave. dragging resulted in a loss of everything that was open or saved in brave's cache. I tried several approaches to at least get an updated version after a crash but eventually gave up.

**Comment by pixelass** [comment] 2017-02-03 15:59
I now use brave for issue testing only. 
Happy to test and reproduce this issue if more info is given.

**Comment by luixxiul** [comment] 2017-02-06 08:35
From my experience the issue only has happened when the link was dragged and dropped fast (by accident). When I drag and drop the link slowly, I could not reproduce the issue.

**Comment by pixelass** [comment] 2017-02-06 09:04
I was able to reproduce it with slow drags too. as mentioned. 90%+ of the
times i clicked a button an decided to cancel by dragging away and then
releasing.

Gregor Adams

**Comment by luixxiul** [comment] 2017-02-06 09:13
Thanks for report. Then the speed does not matter here.

**Comment by alexwykoff** [comment] 2017-02-27 21:42
I have tried to repro with 0.13.5 preview 3 to no avail. 
I used OS X and a trackpad.

Perhaps there is a confounding factor we did take into account?
Having a specific site which reproduces for others would be helpful.

**Comment by jonathansampson** [comment] 2017-03-14 05:10
I also cannot repro on Windows, running 0.13.5 :(

**Comment by bsclifton** [comment] 2017-03-14 08:48
moving to 0.13.7

**Comment by bsclifton** [comment] 2017-04-05 06:56
moving to 0.14.3

**Comment by Liunkae** [comment] 2017-04-07 04:21
Perhaps this was fixed with #7266.

**Comment by luixxiul** [comment] 2017-04-07 15:53
#7266 is related with only macOS while the error happens on Windows.

**Comment by jonathansampson** [comment] 2017-04-09 06:08
@bsclifton I vote we close this. I cannot repro via any of the above STR.

**Comment by bsclifton** [comment] 2017-04-10 08:10
@jonathansampson ++ on that

If you're reading this and experiencing the above symptoms, please comment or reopen the issue. Thanks 😄

**Closed by bsclifton** 2017-04-10 08:10 UTC
Labels: bug, crash, misc/drag-and-drop, needs investigation, needs-owner
