### ISSUE TITLE
Not a bot box unclickable

### ISSUE THREAD

**Issue by egferro** [brave/browser-laptop#14509] opened 2018-06-21 22:47 UTC
Hi the box that many sites require to tick in order to show that you are not a bot is unclickable
Brave 0.22.810 OS: windows 10.
Thanks.
EF
--

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by srirambv** [comment] 2018-06-22 01:12
Dupe of https://github.com/brave/browser-laptop/issues/13496. Please disabel site isolation and check

**Closed by srirambv** 2018-06-22 01:12 UTC
