### ISSUE TITLE
Maximized window has a White border around 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6258] opened 2016-12-16 16:00 UTC
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Maximzed window has a White border around 

**Expected behavior:**
Should not have thick border when browser window is maximized

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 4

- Steps to reproduce:
    1. Do a clean install of 0.13.0 preivew 4
    2. Maximize the browser window
    3. Thick white border is shown around the browser window

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/21268889/81482bca-c3a8-11e6-99a5-dbf6612a4da6.png)

- Any related issues:
cc: @bsclifton

**Comment by bsclifton** [comment] 2016-12-20 21:34
I think the issue involves the `thickFrame` setting for BrowserWindow (which is defaulting to true):
```
thickFrame Boolean (optional) - Use WS_THICKFRAME style for frameless windows on Windows, which adds standard window frame. Setting it to false will remove window shadow and window animations. Default is true.
```

**Comment by bsclifton** [comment] 2016-12-20 21:54
Setting thickFrame to false does resolve the padding around the borders... but it introduces a new set of problems. Window is not responding to being double clicked as maximized anymore, like the above states, it removes animations... it doesn't feel right.  Also (didn't investigate too much), it doesn't seem to properly fire the maximize/unmaximize events when this is set

Will look into the actual window styles being passed in via NativeWindowViews

**Comment by bsclifton** [comment] 2016-12-26 16:59
Adding a ton more logging in here; here's what I've found so far.  Some good clues I think :smile: 

- Using Spy++, I determined the Win32 window styles (regular and extended) between Brave 0.12.15 (Chromium 53) and HEAD (Chromium 54) are **exactly the same** when window is regular and maximized.
- Also using Spy++, the window sizes appear to be consistent between Brave 0.12.15 (Chromium 53) and HEAD (Chromium 54).  This includes the window rect and the client rect.
- Using HEAD (Chromium 54), the window looks fine when **not maximized**. When **maximized**, it gets the borders. However, when set to **fullscreen**, it does **NOT** have the borders.
- NativeWindowViews (electron) is the implementation for electron's BrowserWindow. It uses the underlying Google Chromium views::Widget class to implement the window. For the init params, there is a window type called "TYPE_WINDOW_FRAMELESS" but NativeWindowViews always uses TYPE_WINDOW.  If we change this to be frameless, it crashes without logging any errors.

**Comment by bsclifton** [comment] 2016-12-27 05:28
Reproduced in a bare-bones app; I copied the pre-built binaries over the ones included with @jonathansampson's [Muon Quick repo](https://github.com/jonathansampson/muon-quick) and was able to reproduce the issue.  Only tweaks were:
- setting `frame:false` in the new BrowserWindow call
- calling maximize explicitly (since there are no min/max buttons)

![screen shot 2016-12-26 at 10 25 35 pm](https://cloud.githubusercontent.com/assets/4733304/21491522/9aeb7a54-cbba-11e6-9cd6-a4f3ca801161.png)

**Comment by bsclifton** [comment] 2016-12-27 08:56
OK I'm knee deep in this one (gotta be really close).  The problem appears to be the following:
- Window is in NORMAL state; everything is OK
- User maximizes window, triggering the following:
  - NativeWindowViews::Maximize
  - NativeWindow::GetContentSizeConstraints
  - Window::OnWindowResize
  - Window::GetSize
  - NativeWindow::GetSize
  - NativeWindowViews::GetBounds
  - Widget::GetWindowBoundsInScreen
 - ... need to keep digging...
 

- Something is then setting the bounds incorrectly.  For example, on my monitor (100% DPI) with resolution of 2560 x 1319, Maximize is consistently setting its size as 2576 x 1295.

**Comment by bsclifton** [comment] 2016-12-28 00:51
Got it! Fix coming up...

**Comment by bsclifton** [comment] 2016-12-28 01:35
Fixed with https://github.com/brave/muon/pull/134.  Closing out issue

**Comment by bsclifton** [comment] 2016-12-31 07:21
Reopening after @jonathansampson found this happens when on 200% DPI.  Also there are two DPI related issues (both happening at 125%).  I'll need to dig deeper into the Electron code.  Here are the two possibly related browser-laptop issues:
https://github.com/brave/browser-laptop/issues/6462
https://github.com/brave/browser-laptop/issues/6468

My best guess at the moment is the root cause may be related to this commit:
https://github.com/brave/muon/commit/182fe6df4115aa3aaa0058fa36e6366b98ca5113

I believe I properly solved this issue but the commit above may have masked it with Chromium 53.  When I upstreamed it with https://github.com/electron/electron/pull/7416 it was reverted because the tests failed.

**Comment by bsclifton** [comment] 2017-01-01 16:13
I removed the code and it didn't fix the issue... but the fact that it's still shows the borders means there's another bug (which may be the actual root cause for what I was trying to solve in the muon commit above).  Got some debug statements in there, gonna hunt it down :smile:

**Comment by bsclifton** [comment] 2017-01-10 17:13
I believe the two issues I referenced above are NOT related to this issue (at least not directly).  They may have a different root cause
https://github.com/brave/browser-laptop/issues/6468
https://github.com/brave/browser-laptop/issues/6462

**Closed** 2017-01-12 18:29 UTC
Labels: chromium54, OS/Windows

**Comment by luixxiul** [comment] 2017-01-16 18:43
Test plan: available on the 1st post.

**Comment by luixxiul** [comment] 2017-01-16 18:43
I added `release-notes/exclude` as the issue appeared and was fixed within the same milestone.
