### ISSUE TITLE
Brave browser gets closed when user switch between the ~20 tabs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14777] opened 2018-07-18 11:07 UTC
### Description
When videos are not completely loaded in  20 or more than 20 tabs, if user switch between the tabs by mouse click the browser is getting closed. 

### Steps to Reproduce

  1. Open Brave with Clean profile from CLI "~/appdata/local/bravebeta/bravebeta.exe --user-data-dir-name=brave-beta"
  2. Open Youtube.com
  3. Right click on each videos and open the videos in New tab
  4. Open the videos in more than 20 tabs
  5. Switch between the tabs by mouse click from right to left

Please find the Crash Id below:
e1b13451-8c29-4b46-9fdd-b51c1cbbb2a0.dmp

**Actual result:**
When user switch between the tabs the browser is getting closed
https://drive.google.com/open?id=1TcUJhlWXzXwdsFZrpsjmY7GXVEbqKgya

https://drive.google.com/open?id=1Duk10f1y7uSXnJTcmR7tDYvmostrhhdR

**Expected result:**
Browser should not get close

**Reproduces how often:**
60% Reproducible rate

### Brave Version
0.23.69
**about:brave info:**
 
Brave: 0.23.69 
V8: 6.8.275.21 
rev: 167e67d8f110c841cc1a09bd35c6f4d867e61613 
Muon: 8.0.0 
OS Release: 10.0.17134 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.59

**Reproducible on current live release:**
No

**Comment by kjozwiak** [comment] 2018-07-18 19:58
@GeetaSarvadnya was this a specific CR68 bug? If so, please add the `CR68` tag so the issue isn't removed from the milestone when triaging 👍

**Comment by GeetaSarvadnya** [comment] 2018-07-20 12:59
@kjozwiak Provided the required information in the defect. Please let me know if anything is missing

**Comment by alexwykoff** [comment] 2018-07-24 17:10
@bridiver the crash id mentioned in the issue is e1b13451-8c29-4b46-9fdd-b51c1cbbb2a0.dmp 
 If you could, please take a look.

**Comment by bsclifton** [comment] 2018-07-26 18:43
I looked into stats.brave.com and wasn't able to find the crash details

@GeetaSarvadnya if you're able to reproduce this, can you verify that the upload of the report happens by visiting chrome://crashes? Worst case, you can copy the file on disk and share with us via Slack

Basically, I don't think we can take any action until we have a crash report (since others aren't able to reproduce)

**Comment by kjozwiak** [comment] 2018-07-27 03:04
Just for some more context, @srirambv and myself couldn't reproduce this. I personally spent about an hour trying to reproduce but didn't have any luck. I did notice performance issues when I had ~20 YT videos going at the same time which wasn't surprising. However, Brave never crashed.

Seems like @GeetaSarvadnya's machine is the only one that can reproduce this!

**Comment by GeetaSarvadnya** [comment] 2018-07-27 05:43
@bsclifton Please find the Chrome crash ID below:

![image](https://user-images.githubusercontent.com/38657976/43303610-1a4b7728-918e-11e8-96bd-425f323695a0.png)

**Comment by kjozwiak** [comment] 2018-07-27 06:10
@bsclifton the above crash that @GeetaSarvadnya reported is https://stats.brave.com/dashboard#crash/5b5aae562a89d0001f7c0904.

Search doesn't seem to be working under stats.brave. I went through a few pages and looked for crashes that belonged to `0.23.72`.

**Comment by bsclifton** [comment] 2018-08-09 07:27
Confirmed this is a dupe of https://github.com/brave/browser-laptop/issues/14955

Symbolized crash dump looks like this:
```
1  brave.exe!resource_coordinator::TabLifecycleUnitSource::TabLifecycleUnit::FinishDiscard(resource_coordinator::DiscardReason) [tab_lifecycle_unit.cc : 434 + 0x9]
    rsp = 0x000000d0482fe3d0   rip = 0x00007ff64be282e7
    Found by: stack scanning
 2  ntdll.dll + 0x10428
    rsp = 0x000000d0482fe3e0   rip = 0x00007ff917350428
    Found by: stack scanning
 3  brave.exe!resource_coordinator::TabLifecycleUnitSource::TabLifecycleUnit::Discard(resource_coordinator::DiscardReason) [tab_lifecycle_unit.cc : 360 + 0x8]
    rsp = 0x000000d0482fe4e0   rip = 0x00007ff64be28836
    Found by: stack scanning
 4  brave.exe!resource_coordinator::TabManager::DiscardTabImpl(resource_coordinator::DiscardReason) [tab_manager.cc : 642 + 0x1a]
    rsp = 0x000000d0482fe520   rip = 0x00007ff64be2af9f
    Found by: stack scanning
 5  brave.exe!resource_coordinator::TabManager::LogMemoryAndDiscardTab(resource_coordinator::DiscardReason) [tab_manager.cc : 308 + 0x22]
    rsp = 0x000000d0482fe590   rip = 0x00007ff64be2b064
    Found by: stack scanning
 6  brave.exe!resource_coordinator::TabManager::OnMemoryPressure(base::MemoryPressureListener::MemoryPressureLevel) [tab_manager.cc : 530 + 0x10]
    rsp = 0x000000d0482fe5b0   rip = 0x00007ff64be2ab0f
    Found by: stack scanning
```

**Closed by bsclifton** 2018-08-09 07:27 UTC
Labels: bug, cr68, feature/tabsbar

**Comment by kjozwiak** [comment] 2018-08-09 14:33
Awesome work figuring this one out @bsclifton 👍
