### ISSUE TITLE
Add option to enable/disable HTML5 autoplay

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#4045] opened 2016-09-16 05:35 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
It would be nice if Brave had built in way to enable/disable eighter globally or per website the HTML5 autoplay attribute.

If in future we have something like website permissions where the user can choose to enable per website:
- Allow microphone
- Allow video camera
- Allow GPS

This option could be put there as well.
#2227

**Comment by Liunkae** [comment] 2016-12-02 06:30
There are some good comments #5952, a duplicate of this issue.

**Closed** 2017-05-05 19:56 UTC
Labels: parity, settings, suggestion
