### ISSUE TITLE
Brave doesn't remember last position and size if you set it to start with homepage

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#3754] opened 2016-09-06 05:14 UTC
## Test plan
1. Open preferences > general
2. Set `Brave starts with` to `My homepage`
3. Move the window to a unique position and resize it also
4. Close Brave and reopen
5. Window should have retained its position

## Original issue description
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
When closed Brave does not retain last window position and size as it should be when re-launched.

_**This happens only if**_ in Settings -> General you set the value for `Brave starts with` to `My homepage`. If you select `Session and tabs from last time` it correctly remembers the position and the size of the window.

**Expected behavior:**
Brave should remember the last window position and size regardless what I choose Brave to load initially.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Linux, Fedora 24
- Brave Version:
  0.12.0dev downloaded from [here](https://github.com/brave/browser-laptop/releases/download/0.12.0dev-RC2/brave-0.12.0.amd64.rpm)
- Steps to reproduce:
  1. In settings -> general set `Brave starts with` to `My homepage`
  2. https://s11.postimg.org/y5tetpkkj/window_bug.gif
- Screenshot if needed:
- Any related issues:

**Comment by bsclifton** [comment] 2016-10-04 20:24
Good call, @Sh1d0w! I just manually tested and confirmed #4482 does seem to fix this issue

Since this issue was fixed in 0.12.3 (with a different issue), I'll mark this as 0.12.3 milestone

**Comment by Sh1d0w** [comment] 2016-10-08 15:01
Unfortunately after I installed 0.12.4 it does not seem to fix this issue. The problem still exists if you follow the STR in the issue above.

**Comment by bbondy** [comment] 2016-10-10 14:20
if you select my home page then no last window state is saved. I guess we need to use the last window size / pos in that case for the next new Window.

**Comment by Sh1d0w** [comment] 2016-10-26 04:06
@bsclifton Here is a video from latest master https://github.com/brave/browser-laptop/commit/af38d76dced4a1124762a12377340c1a925c1989

http://webm.land/media/Q5tA.webm

Does not seem to work for me :(

**Comment by srirambv** [comment] 2016-10-26 08:59
Verified on Windows. Its loading the window in the default restore down position when home page is set to start.

**Comment by bsclifton** [comment] 2016-10-26 17:35
@srirambv code has not been included in a preview or release yet

@Sh1d0w I'll dig in more

**Comment by bsclifton** [comment] 2016-10-26 17:39
@Sh1d0w it looks like you've launched one of our releases; this hasn't been included in a built yet.  I'm going to close this, but please try it from source; I can't reproduce.

**Comment by bsclifton** [comment] 2016-10-26 18:40
OK I missed the above being master (@Sh1d0w had packaged the build and is running that)

If he moves the session out of the way, it works fine.  But with session in place, it's not working.

Re-opening issue...

**Comment by Sh1d0w** [comment] 2016-10-27 05:01
Reopening since it is still not fixed. @bsclifton Ping me in slack so we can cooperate to resolve this.

**Comment by bbondy** [comment] 2016-10-27 05:08
Going to spin rc1 so moving this to 0.12.8.  If we do an rc2 which is probably likely we'll get it in.

**Comment by bsclifton** [comment] 2016-11-17 00:27
Removing milestone for the time being

**Comment by srirambv** [comment] 2016-12-01 15:17
Two more reports from support on not remembering window position
https://linkbubble.zendesk.com/agent/tickets/7082
https://linkbubble.zendesk.com/agent/tickets/7079

**Comment by srirambv** [comment] 2017-05-30 15:38
+1 from community https://community.brave.com/t/brave-forgets-window-size-on-opening/3233

**Closed** 2017-08-28 20:48 UTC
Labels: bug, QA/steps-specified, release-notes/include
