### ISSUE TITLE
One password fill in private tab

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#7080] opened 2017-02-05 07:12 UTC
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
One password fill is not working in a private tab. Was working in version 0.12.x.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
c320129

- Steps to reproduce:
    1. open a private tab with a page that you have saved password  in one password
    2. try to fill this form
    
- Actual result:
fill is not working

- Expected result:
login data should be filled into the login form

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

**Comment by bridiver** [comment] 2017-02-23 21:33
technically this is a regression, but Chrome doesn't allow extensions in private tabs by default. Extensions could potentially leak data in private  browsing mode and the following options are being considered:
1. Do nothing
2. Always enable
3. Add a checkbox like chrome with default enabled
4. Add a checkbox like chrome with default disabled

**Comment by NumDeP** [comment] 2017-10-28 23:27
@bridiver does Brave's Built-In feature function like an extension because the same thing happens?

At first I though it was a bug but I sort of like how it functions. It doesn't immediately fill in the username and pass but as soon as you enter the first letter of the username and press enter, it signs in with both the username and pass. Perhaps you can allow this functionality for the others

**Comment by bsclifton** [comment] 2018-08-25 05:34
You'll have to go to chrome://extensions and allow use in private tabs, but this is fixed with [brave-core](https://github.com/brave/brave-browser) 😄

**Closed by bsclifton** 2018-08-25 05:34 UTC
Labels: bug, feature/password-manager, feature/private-tabs, fixed-with-brave-core, needs-owner ♞, regression, wontfix
