### ISSUE TITLE
Copy/paste sometimes pastes page's URL instead of selected text

### ISSUE THREAD

**Issue by sanderaarts** [brave/browser-laptop#10422] opened 2017-08-11 01:51 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
I noticed that on some occasions when I try to copy a selected text and copy it elsewhere, that instead of the text the page's URL is pasted. Sometimes it works correct, sometimes it doesn't and sometimes it works correct on the second or third try.

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X 10.10.5 (Yosemite)

- Brave Version (revision SHA):
Brave: 0.18.14 
rev: ad92d029e184c4cff01b2e9f4916725ba675e3c8

- Steps to reproduce:
    1. Select a text on a page
    2. CMD+C
    3. Put the cursor in an input/textarea and hit CMD+V
    
- Actual result:
Sometimes the selected text, sometimes the URL of the page the text is on.

- Expected result:
The selected text.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Didn't try.

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
No

**Comment by Liunkae** [comment] 2017-08-11 03:26
Duplicate of #10214.

This problem was just fixed (around an hour before you posted!) and will be included in the next stable release of Brave 0.18.x 😉

**Closed by Liunkae** 2017-08-11 03:26 UTC
