### ISSUE TITLE
Allow for easy profile switching

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10542] opened 2017-08-16 15:04 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
QA and general users who share machines would both benefit from profile switch capability.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
> 0.21.0

**Comment by bsclifton** [comment] 2017-08-16 16:30
@alexwykoff is this a duplicate of https://github.com/brave/browser-laptop/issues/10324 ?

**Comment by alexwykoff** [comment] 2017-09-08 18:59
"Let's pony up and do it right" - @bradleyrichter

**Comment by bsclifton** [comment] 2017-11-22 18:00
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/10324

**Closed by bsclifton** 2017-11-22 18:00 UTC
Labels: design, duplicate, suggestion

**Comment by dausoc** [comment] 2018-12-13 19:05
good
