### ISSUE TITLE
detaching tab issue

### ISSUE THREAD

**Issue by roslan12** [brave/browser-laptop#10063] opened 2017-07-19 16:49 UTC
- Did you search for similar issues before submitting this one?

yes

- Describe the issue you encountered:

when detaching tab the window that got the tab detached from it will stay blank and you need to click on a tab, also it will show the url of the tab but not display it.

- Platform (Win7, 8, 10? macOS? Linux distro?):

windows 10

- Brave Version (revision SHA):

app-0.17.18

- Steps to reproduce:
    1. open two or more tabs
    2. right click on a tab and detach
  
    
- Actual result:
 window that got a tab detached from it stays blank until clicking on a tab

- Expected result: 
the window should auto select a tab like every other browser

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
not sure, just incase I will link my settings

http://imgur.com/a/bGkNx

- Is this an issue in the currently released version?
newest version with the update to preview releases enabled
- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
https://imgur.com/oPO3WFI

**Comment by bsclifton** [comment] 2017-07-19 21:03
@bbondy I know you're looking at the white page issue (https://github.com/brave/browser-laptop/issues/9671)- is this a duplicate? (or a different issue)

**Comment by bbondy** [comment] 2017-07-27 14:06
Closing as dupe of:
https://github.com/brave/browser-laptop/issues/9671

**Closed by bbondy** 2017-07-27 14:06 UTC
Labels: feature/tear-off-tabs, suggestion
