### ISSUE TITLE
Add built-in password maker to Brave

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10162] opened 2017-07-26 21:13 UTC
Requested via community: https://community.brave.com/t/password-maker-built-in/5042

I use Password Maker (see passwordmaker.org for more info) as a password generator rather than 1Pass or LastPass or any of the others. I.e.: I calculate my password every time I log in using a formula, rather than store a list of passwords some where.

It would be totally awesome if Password Maker functionality was integrated directly into Brave. I think this fits really well with the mission of privacy and security. In Google Chrome there’s a few extensions that provide that functionality but it’s so simple it could be integrated.

In Brave > Preferences > Security > Passwords and Forms there could be an additional choice in the drop-down for Password Maker Built-in and the Manage Passwords… link would take you a page to fill-in the parameters for the Password Maker formula.

Thanks for your consideration!

**Comment by eljuno** [comment] 2017-12-11 20:23
Duplicate of #5037?

**Comment by bsclifton** [comment] 2017-12-11 20:24
@eljuno good catch, yes! 😄

**Closed by bsclifton** 2017-12-11 20:24 UTC
Labels: feature/password-manager
