### ISSUE TITLE
Pause "time spent" counter when users are idle for 60+ seconds

### ISSUE THREAD

**Issue by Aeyoun** [brave/browser-laptop#3692] opened 2016-09-03 12:08 UTC
I left my browser open as I normally do and was surprised to see that I’d spent 22+ minutes on a website when I returned. The counter should pause when there is no user activity is detected (and browser is not in fullscreen).

Update: Brave even continues counting when I focus another program, or focus another Brave window.

Brave 0.11.6 on Linux.

**Comment by mrose17** [comment] 2016-09-14 16:57
not really a duplicate of https://github.com/brave/browser-laptop/issues/3696 -- but being closed in favor of consolidating timing issues there..

**Closed by mrose17** 2016-09-14 16:57 UTC
Labels: ledger integration
