### ISSUE TITLE
Brave is not asking for Password on ftp login/router configuration or others

### ISSUE THREAD

**Issue by swarnava** [brave/browser-laptop#593] opened 2016-02-03 13:39 UTC
Example:
Go to: https://login.mozilla.com/

Expected Behavior: 
it should ask for LDAP login password.

Actual Behavior: 
It is not asking for credential.

**Comment by bbondy** [comment] 2016-02-03 13:52
Dupe of #370

**Closed by bbondy** 2016-02-03 13:52 UTC
