### ISSUE TITLE
photos & pictures showing

### ISSUE THREAD

**Issue by RichD2016** [brave/browser-laptop#5153] opened 2016-10-26 12:36 UTC
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:** 

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.I use Brave for my Facebook as I like your ADD blocking  & it run smother & faster than Google , This morning for some reason when I go to my Facebook page no ( any kind )  photos are showing ( my profile photo - my friends photos - photos or pictures on post are not showing  ) I've tried reloading Brave , but it hasn't helped . 
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by privatzee** [comment] 2016-10-26 13:48
Hi, @RichD2016 You can try to click the lion in the upper right, then click to Allow Ads and Tracking, like this:

![image](https://cloud.githubusercontent.com/assets/22591438/19728324/f3b414c8-9b60-11e6-808d-1364a2b1dc2f.png)

That will allow Ads and Tracking on Facebook only. Also, it would be helpful if you could reply back as to whether that works for you or not. Thanks for reporting.

**Comment by privatzee** [comment] 2016-10-26 13:50
Keyword: CDN

...because images from fbcdn.net are blocked. This is another in an series of CDNs which could be allowed in an intermediate privacy setting. 

E.g.: https://developers.facebook.com/?ref=pf

![image](https://cloud.githubusercontent.com/assets/22591438/19728011/d1a07814-9b5f-11e6-8aec-4ff9297f7953.png)

**Comment by RichD2016** [comment] 2016-10-26 16:17
Thanks  that fixed the problem ... 

    On Wednesday, October 26, 2016 8:48 AM, privatzee <notifications@github.com> wrote:
 

 Hi, @RichD2016 You can try to click the lion in the upper right, then click to Allow Ads and Tracking, like this:That will allow Ads and Tracking on Facebook only. Also, it would be helpful if you could reply back as to whether that works for you or not. Thanks for reporting.—

**Comment by privatzee** [comment] 2016-10-26 16:40
@RichD2016  It seems that the next Brave update will fix the problem (#5151), and so after that comes out, you can undo the way that you just did _Allow Ads and Tracking_

**Comment by bridiver** [comment] 2016-10-26 16:57
we can put ad blocking/tracking changes between releases, but seems strange that `fbcdn.net` isn't allowed by default on facebook.com. @bbondy ?

**Comment by bbondy** [comment] 2016-10-26 16:59
Dupe of https://github.com/brave/browser-laptop/issues/5151 and should be fixed now with a new data file

**Closed by bbondy** 2016-10-26 16:59 UTC

**Comment by privatzee** [comment] 2016-10-26 17:21
"...should be fixed now..."

It's still happening at this moment. E.g., I can still toggle all the images on https://developers.facebook.com/?ref=pf by toggling the Ad Control between _Allow Ads and Tracking_ and _Block Ads_.

Win7 x64 
Brave 0.12.6

![image](https://cloud.githubusercontent.com/assets/22591438/19736820/eea1cf34-9b7e-11e6-8486-72d1f3b6d5a3.png)
