### ISSUE TITLE
Brave has been slow all day, while Firefox has been normal

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#13053] opened 2018-02-07 06:53 UTC
I have 15 tabs open in Brave at the moment. I then opened Firefox and am typing this message in it, the internet is a normal speed in Firefox.

**Comment by jamesray1** [comment] 2018-02-07 06:57
I closed the browser and reopened it, it was then a normal speed. Hmm.

**Comment by jamesray1** [comment] 2018-02-07 06:58
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 4.13.0-32-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

Seems like it has automatically updated without realising it.

**Comment by srirambv** [comment] 2018-02-07 07:36
@jamesray1  was the browser speed sluggish before the update and fixed when restarted for update?

**Comment by jamesray1** [comment] 2018-02-07 07:49
No it wasn't updated today.

**Comment by jamesray1** [comment] 2018-02-07 07:49
I haven't restarted the computer today.

**Comment by jamesray1** [comment] 2018-02-07 07:49
I guess that it updated when Ubuntu did an update during a shutdown.

**Comment by jamesray1** [comment] 2018-02-07 07:50
It was slow from the beginning of the day, as far as I can remember.

**Comment by jamesray1** [comment] 2018-02-07 08:11
In fact, now it seems faster! How bizarre...

**Comment by jamesray1** [comment] 2018-02-07 09:02
I think I know what the cause is, and can reproduce it.

Go to https://tokensale.civic.com/

Click the Read full whitepaper button, or just click this: https://tokensale.civic.com/CivicTokenSaleWhitePaper.pdf.

Brave slows right down, and won't speed up until you close the Brave/Nautilus window prompting where to save the White Paper.

**Comment by bsclifton** [comment] 2018-02-07 22:51
Closing as a dupe of https://github.com/brave/browser-laptop/issues/8541

Thanks for the repro steps- I shared them there too 😄 👍

**Closed by bsclifton** 2018-02-07 22:51 UTC
Labels: needs-info, perf
