### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by roscoau** [brave/browser-laptop#2341] opened 2016-06-30 06:47 UTC
OSx 10.11.5
Brave: 0.10.4

When using Google Maps site only the base map loads; none of the other functionality works. No search, routing, satellite view etc. 

This began with the latest release.

**Comment by luixxiul** [comment] 2016-06-30 11:14
Confirmed. It starts working by disabling the bravery shields.

**Comment by diracdeltas** [comment] 2016-07-21 05:35
Not sure we should do anything about this, since fingerprinting protection is off by default with a warning that it will break some sites.

**Comment by lucidNTR** [comment] 2016-10-04 20:58
works in the latest master for me now. maybe close
@luixxiul

**Comment by bsclifton** [comment] 2016-10-04 21:01
Closing this issue; it's basically a duplicate of https://github.com/brave/browser-laptop/issues/2965. I made sure to add the domain to that issue

**Closed by bsclifton** 2016-10-04 21:01 UTC
Labels: site-bug
