### ISSUE TITLE
Selected text in URL bar stays when typing

### ISSUE THREAD

**Issue by jansensan** [brave/browser-laptop#5190] opened 2016-10-27 16:18 UTC
**Did you search for similar issues before submitting this one?**
Yes, found similar one, but steps to reproduce differed.

**Describe the issue you encountered:**
With a URL already present in the URL bar, the user selects the text and starts to type any other URL. New typings are not replacing the selected text, but rather added at the end of the selected text.

**Expected behavior:**
Just like any text edition, the selected text should be replaced by the new typings of the user.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.10.5

- Brave Version:
0.12.6

- Steps to reproduce:
    1. With a URL already present in URL bar, select text
    2. Starts to type any other URL

- Any related issues:
https://github.com/brave/browser-laptop/issues/5189

**Comment by Liunkae** [comment] 2016-10-29 07:32
I would argue that this is a major issue; I have encountered this problem quite frequently. However, it is hard to reproduce since it doesn't happen every time.

**Comment by Liunkae** [comment] 2016-10-29 18:06
Duplicate of #5036.

**Closed by Liunkae** 2016-10-29 18:06 UTC
Labels: bug, confirmed, feature/URLbar
