### ISSUE TITLE
Update aphrodite to 1.2.4

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10062] opened 2017-07-19 16:42 UTC
## Test plan
https://github.com/brave/browser-laptop/issues/10234
1. Make sure the issue reported on #10029 does not happen again

----

See https://github.com/Khan/aphrodite/blob/master/CHANGELOG.md for changelog

**Comment by bsclifton** [comment] 2017-07-25 23:21
Removing milestone and marking as `reverted`. This was removed with  which was needed to fix https://github.com/brave/browser-laptop/issues/10029.

We should be able to consider upgrading again once https://github.com/brave/browser-laptop/issues/10133 is finished

Please note that per semver, the ^ means any compatible version.  Having `^1.0.0` was already grabbing the latest 1.0 release.  More info available at https://docs.npmjs.com/files/package.json

**Comment by luixxiul** [comment] 2017-07-26 03:58
why don't we report the bug to the upstream? :-)

**Comment by cezaraugusto** [comment] 2017-07-26 04:07
@luixxiul actually that's not a bug with Aphrodite. It's not clear where it was added but Aphrodite checks for production env var and concatenates strings. It should be nothing for us be we still rely on legacy code that depends on className. 

For example in main.js we are checking matches against `classList` like `node.matches('[class^="popupWindow"]')`. It works in dev but as soon as build is ready, there's no class starting with `popupWindow`, so we always return false for such checks in production.

The fastest take to unblock next release was to freeze Aphrodite before that addition. But short term is to eliminate all class-dependent code as they're fragile and just re-use Aphrodite at latest.

**Comment by bsclifton** [comment] 2017-07-31 16:17
@luixxiul if you upgrade, please be sure not to use the ^ in the version 😄  (ex: prefer "1.2.3" over "^1.2.3")

**Comment by luixxiul** [comment] 2017-08-01 02:49
Here's a discussion if another variable should be applied to minify classname: https://github.com/Khan/aphrodite/pull/246#issuecomment-319047097

**Comment by bsclifton** [comment] 2017-08-29 17:44
Removing milestone.  We can attempt this once https://github.com/brave/browser-laptop/issues/10551 is completed

**Comment by luixxiul** [comment] 2017-10-05 08:07
aphrodite was updated to `1.2.4`.

https://github.com/Khan/aphrodite/blob/master/CHANGELOG.md#124

**Closed** 2018-10-01 03:16 UTC
Labels: release-notes/exclude, wontfix
