### ISSUE TITLE
bitwarden extension icon is not displayed on a web page

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9592] opened 2017-06-20 03:56 UTC
**Describe the issue you encountered:** The bitwarden icon is not displayed on a web page, while it is on an about page such as about:preferences.

![a](https://user-images.githubusercontent.com/3362943/27315921-8805a8c4-55b7-11e7-9413-7063dcd7fbee.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA): 0.17.3

- Steps to reproduce:
    1. Enable bitwarden
    2. Open a web page
    
- Actual result: the icon dispappears from the navigation bar

- Expected result: it should be kept displayed there

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: https://github.com/brave/browser-laptop/issues/7921#issuecomment-309637864

**Comment by srirambv** [comment] 2017-06-20 05:03
Dupe of https://github.com/brave/browser-laptop/issues/9437

**Closed by srirambv** 2017-06-20 05:03 UTC
Labels: bug, feature/extensions, feature/password-manager
