### ISSUE TITLE
Update check fails

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8147] opened 2017-04-09 13:51 UTC
**Describe the issue you encountered:**
Updating using BRAVE_UPDATE_VERSION=0.14.0 does not work
````
2017-04-09T13:49:04.344Z - checkForUpdates
2017-04-09T13:49:04.365Z - lastCheckYMD = 2017-04-09
2017-04-09T13:49:04.402Z - https://brave-laptop-updates.global.ssl.fastly.net/1/releases/dev/0.14.0/winia32?daily=false&weekly=false&monthly=false&first=false
2017-04-09T13:49:04.380Z - lastCheckWOY = 90
2017-04-09T13:49:04.391Z - lastCheckMonth = 4
2017-04-09T13:49:04.402Z - firstCheckMade = true
2017-04-09T13:49:04.691Z - Metadata: {"version":"0.14.1","name":"Brave 0.14.1","pub_date":"2017-04-01T06:00:15.036Z","notes":"Fixed a copy and paste issue, fixed the lion badge position, and improved security. More details: https://github.com/brave/browser-laptop/releases/tag/v0.14.1dev"}
2017-04-09T13:49:05.086Z - update not available
````

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.14.2 preview 1

- Steps to reproduce:
    1. Update from the menu
    
- Actual result: the latest update cannot be found

- Expected result: it should be found

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment] 2017-04-10 02:30
@aekeus could you triage this? Thanks!

**Comment by aekeus** [comment] 2017-04-10 02:58
Strange. The metadata was retrieved in the above example. Will look into it.

**Comment by luixxiul** [comment] 2017-04-10 11:41
With the Preview 2 the update check passes. Maybe is it the issue on the server side?

**Comment by aekeus** [comment] 2017-04-10 13:01
I cannot reproduce this. The update works as expected on PR2.

**Comment by aekeus** [comment] 2017-04-10 13:16
It is possible that this is a server side issue, but more likely the download failed (network issue?) and the updater reported no update available. Closing for now. Please re-open if this is encountered again.

**Closed by aekeus** 2017-04-10 13:16 UTC
Labels: bug

**Comment by luixxiul** [comment] 2017-04-17 18:54
This works fine on the latest RC build.
