### ISSUE TITLE
Duped bookmarks cannot be removed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5636] opened 2016-11-15 16:45 UTC
**Describe the issue you encountered:** Bookmarks can be duped, and cannot be removed

**Expected behavior:** Bookmarks should not be duped

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1. Open ``about:bookmarks``
    2. Create bookmark 1 (title: null, location: https://clifton.io)
    3. Create bookmark 2 (title: null, location: http://clifton.io)
    4. Edit bookmark 1 (title: null, location: http://clifton.io)
    5. Try to delete both bookmarks -> one of them cannot be removed

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment] 2016-11-15 22:00
@bsclifton mind taking this?

**Comment by bsclifton** [comment] 2016-11-17 00:39
@luixxiul I am not able to reproduce- do you have more specific steps?  Here is what I tried:

1. Launch Brave (HEAD from master branch) and open Bookmark Manager
2. Click star icon to add bookmark for https://clifton.io (leave title blank)
3. Click star icon again to add bookmark for http://clifton.io
4. Right click the http one and pick edit
5. Click remove

I am able to remove both. I also tried removing by doing right click and then choosing delete bookmark (from both bookmarks toolbar and also in bookmarks manager)

**Comment by luixxiul** [comment] 2016-11-17 02:29
How about will it be after removing history? Would you please try it?

**Comment by bsclifton** [comment] 2016-11-21 19:03
I still am not able to repro; I put a lot of extra logging in place and tried several variations of the step above. I'm going to close this, but please feel free to re-open if you have some solid steps to reproduce.  I'm wondering if this is related to how you needed to do a fresh npm install to get proper electron version (for another issue?)

**Closed by bsclifton** 2016-11-21 19:03 UTC
Labels: bug, feature/bookmarks

**Comment by luixxiul** [comment] 2016-11-22 01:19
@bsclifton I think so, I cannot reproduce it anymore after reinstalling muon.
