### ISSUE TITLE
Notification bar is still visible after restart

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8435] opened 2017-04-22 01:18 UTC
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Notification bar is still visible after restart
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
570587f 
- Steps to reproduce:
    1. go to about:preferences#extensions
    2. disable PDF viewer (notification about restart is shown)
    3. restart your browser by clicking on a X
    4. start your browser again
    
- Actual result:
Notification is still visible
- Expected result:
Notification shouldn't be visible, because you just restarted your browser

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
yes

**Comment by luixxiul** [comment] 2017-04-22 02:17
Is this specific to the extension pane ie after changing the lang setting as well?

**Comment by NejcZdovc** [comment] 2017-04-23 21:56
didn't test with the language

**Comment by cezaraugusto** [comment] 2017-04-24 20:24
which X should I click? I hit "yes" to restart but couldn't reproduce. Notification was hidden as expected. 

Running SHA 506036edeaae6678380898fae067469193150490, macOS Sierra.

![apr-24-2017 17-19-15](https://cloud.githubusercontent.com/assets/4672033/25356871/47997c56-2912-11e7-9d53-bc0d9427d7af.gif)

**Comment by NejcZdovc** [comment] 2017-04-24 20:27
@cezaraugusto X as in aplication X :smiley: don't click anything on the notification
![image](https://cloud.githubusercontent.com/assets/9574457/25357176/2a53d440-293d-11e7-9f5a-f8795d74c1ad.png)

**Comment by cezaraugusto** [comment] 2017-04-24 22:22
ok I think that's because window closing on Mac isn't necessarily a restart. Unless you <kbd>cmd</kbd>+<kbd>q</kbd> to close, window will be _refreshed_ but app is not restarted. That would work with Win/Linux where close icon really means closing the app, but not on mac.

You could check that by disabling webtorrent and closing with the X, then try to download a torrent. On restart, notification is still active (bug per this issue) but that's because webtorrent is still active, since clicking on the download file would redirect to webtorrent page. So notification is still on because extension is still on -- until you restart.

**Comment by cezaraugusto** [comment] 2017-04-24 22:23
btw there's a conditional in our code indicating that behavior on mac here: https://github.com/brave/browser-laptop/blob/master/app/index.js#L235

you can see that app will quit on all OSes except darwin (mac)

**Comment by alexwykoff** [comment] 2017-04-25 17:23
working as designed see above ^

**Closed by alexwykoff** 2017-04-25 17:23 UTC
Labels: bug, feature/extensions

**Comment by srirambv** [comment] 2017-05-03 12:42
I am not able  to verify this on Win x64 preview 2 due to #8629. Tried building it from source and packaged build.

**Comment by NejcZdovc** [comment] 2017-05-03 12:54
@srirambv this is invalid. It's working as designed.
