### ISSUE TITLE
Weird bug where search bar disappears and bookmarks overlap with window buttons?

### ISSUE THREAD

**Issue by patrick99e99** [brave/browser-laptop#9843] opened 2017-07-03 00:27 UTC
This has happened to me several times now, so I thought I should report it...  Don't know exactly how to reproduce, but this last time I simply command-T to open a new window, and began typing into the address bar for a search, and then all of a sudden the search bar disappeared and my bookmarks become strangely underneath the window buttons.  When clicking my through other tabs, the window is permanently like this-- no way to fix it other than to quit Brave and relaunch.

<img width="1280" alt="screen shot 2017-07-02 at 5 21 48 pm" src="https://user-images.githubusercontent.com/28946/27774688-9c57d0ac-5f4b-11e7-82f3-af47c5a849bc.png">
 
Brave: 0.17.13 
rev: f7242c7ae683191b59388f567ccbd13d938b23d4 
Muon: 4.1.7 
libchromiumcontent: 59.0.3071.109 
V8: 5.9.211.38 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: darwin 
os.release: 16.0.0 
os.arch: x64

**Comment by srirambv** [comment] 2017-07-03 11:55
@patrick99e99  Does any of the tabs have a webview crash (black page with a frown face)? This looks similar to #8574

**Comment by patrick99e99** [comment] 2017-07-06 17:53
@srirambv this just now happened to me again..  It happened immediately after opening a new tab and typing in a url.  As soon as I pressed return the tab bars jumped up to the top border of the window, lost my search bar and navigation buttons...  only the close window, hide and maximize/minimize buttons are there (as shown in my previous screenshot).

To answer your question, all of the tabs work fine...  The content is there in every tab, the pages behave normally..  One of the tabs is a youtube video page and I can still watch the video fine.

**Comment by patrick99e99** [comment] 2017-08-04 18:29
This just now happened to me again...  This time it happened when I was typing into the url bar, and was presented with a search suggestion and then I pressed option-delete a few times to remove the last few paths from the url and then starting to type in a new path.

http://lol.com/foo/bar/baz --> changed /foo/bar/baz to foo/qux for example.

**Comment by bsclifton** [comment] 2017-08-07 20:01
This has happened to me a few times today
- It seems that typing into the URL bar causes the issue
- a suggestion is displayed and I think that is what is shifting the UI chrome down
- if you stop typing after you notice it, you can still see the tabs (like in the screenshot above). If you switch between tabs enough, you'll eventually get one that re-opens the URL bar
- if you keep typing, the UI chrome goes completely off the screen and the page you're visiting takes up the entire screen

**Comment by bsclifton** [comment] 2017-08-08 21:49
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/8574

**Closed by bsclifton** 2017-08-08 21:49 UTC
Labels: bug, feature/navbar, feature/URLbar, needs-investigation
