### ISSUE TITLE
Mouse cursor visible while in full screen

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#7966] opened 2017-03-29 18:36 UTC
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Mouse is still visable after entering fullscreen in youtube...
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10Pro  x64
- Brave Version (revision SHA):
0.13.5 but also found it working on 1.14.0 RC2
- Steps to reproduce:
    1. Open a youtube video (Example: https://www.youtube.com/watch?v=ylTPgMi9SEo )
    2. Open fullscreen
    3. Mouve the mouse so it isn´t on the bar at the bottom
    4. Keep the mouse stationary
    
- Actual result:
Mouse is still visable
- Expected result:
Mouse should be hidden when not moving it
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

**Comment by jonathansampson** [comment] 2017-04-03 05:44
Thank you for filing!

Browser | Behavior
-|-
Chrome | Hides mouse
Firefox | Hides mouse
Edge | Hides mouse
Brave | Displays mouse

**Comment by bsclifton** [comment] 2017-04-04 16:07
Moving to 0.14.3

**Comment by alexwykoff** [comment] 2017-04-18 18:31
Hey @srirambv if you can reproduce please let us know, thanks :)

**Comment by srirambv** [comment] 2017-04-18 19:40
Confirmed cursor not hidden in full screen.

**Comment by alexwykoff** [comment] 2017-04-25 17:48
@srirambv could you check vs slack fullscreen?

**Comment by srirambv** [comment] 2017-04-25 18:12
Same on slack fullscreen as well. Cursor is not hidden.

**Comment by srirambv** [comment] 2017-05-08 09:00
I think this is fixed in 0.15.3 preview 3. I do not see mouse pointer when viewing full screen video. But will keep the issue open just in case.

**Comment by Jacalz** [comment] 2017-05-08 12:17
Yes it looks as to be fixed with 0.15.3, I wonder what fixed it :+1: :confused:

**Comment by Jacalz** [comment] 2017-05-08 12:18
If we found what commit fixed it we can have it in the release notes in my oppinion :+1:

**Comment by jonathansampson** [comment] 2017-05-08 15:28
@darkdh @bridiver Are either of you aware of a change that would have resolved this issue?

**Comment by bsclifton** [comment] 2017-05-08 16:07
@Jacalz can you check if it still happens in 0.15.2? We did update Chromium in that release; perhaps it was fixed there

**Comment by Jacalz** [comment] 2017-05-08 16:28
Does not happen in 0.15.2 strange :confused: @bsclifton

**Comment by Jacalz** [comment] 2017-05-08 16:30
Can somebody also confirm that it got fixed with 0.15.2 so we can close this? :smile:

**Comment by luixxiul** [comment] 2017-05-08 16:38
I confirmed that, closing.

**Closed by luixxiul** 2017-05-08 16:38 UTC
Labels: bug, misc/fullscreen-option, needs-owner, OS/Windows

**Comment by bsclifton** [comment] 2017-05-08 16:59
@Jacalz not too unbelievable- a Chromium update also introduced it 😄   Thanks for checking all

**Comment by Jacalz** [comment] 2017-05-08 17:19
Oh, had no idea that it was introduced by a chromium update 😅 No problem 🤗

**Comment by Jacalz** [comment] 2017-05-08 17:21
Also wich release notes should this be put on? Since @bsclifton removed the milestone 😅

**Comment by bsclifton** [comment] 2017-05-08 17:41
@Jacalz we can keep a milestone if we want release notes.  Sorry- I had removed it since there wasn't any fix

**Comment by Jacalz** [comment] 2017-05-08 17:55
Don't be sorry it was more meant as a question if the release notes include tag should be removed or not 😉 @bsclifton

**Comment by luixxiul** [comment] 2017-05-09 01:00
> I had removed it since there wasn't any fix

I would say that the app fixed itself ;-)
