### ISSUE TITLE
Not all bookmarks are shown in bookmarks bar.

### ISSUE THREAD

**Issue by Spammie** [brave/browser-laptop#1339] opened 2016-04-11 21:42 UTC
Hello so I imported my bookmarks and on my laptop not all bookmarks are shown until the little arrows on right side in bookmarks bar. I think this is related to the laptops resolution (1366x768) because on my second screen at 1600x900 this issue is not present.
![capture](https://cloud.githubusercontent.com/assets/17462930/14443363/689c5f08-0047-11e6-8fb7-190e426a5151.PNG)

**Comment by luixxiul** [comment] 2016-05-13 07:22
@bbondy maybe this has been fixed with #1567?

**Comment by bbondy** [comment] 2016-05-13 13:16
Yep, dupe of that and fixed in 0.9.5.

**Closed by bbondy** 2016-05-13 13:16 UTC
