### ISSUE TITLE
Reloading a "view source" window shows the page instead

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#4096] opened 2016-09-18 16:11 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When I press Cmd+R on a "view source" page, rendered page is shown instead.

**Expected behavior:**
Should reload the source and show it again.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.12.1

- Steps to reproduce:
    1. Load a page
    2. Press Cmd+Shift+U to view the page source
    3. Press Cmd+R to reload the page

**Comment by Sh1d0w** [comment] 2016-09-18 17:36
This is caused by #2772 , so I am closing this.

**Closed by Sh1d0w** 2016-09-18 17:36 UTC
