### ISSUE TITLE
Twitter login fails each time (not a password problem)

### ISSUE THREAD

**Issue by DeltaZone** [brave/browser-laptop#5182] opened 2016-10-27 06:36 UTC
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by DeltaZone** [comment] 2016-10-27 06:39
I am just evaluating this browser, and the main motivation for that is its built-in security features. I do not want to be forced to disable all protection even for Twitter, just to be able to log in. I think that this browser should have default settings that permits login on trusted sites, which I assume includes Twitter.com and Tweetdeck.Twitter.com? 

Meanwhile, I would like to know which parts of the defence I should put disable in order to log into Twitter?

**Comment by DeltaZone** [comment] 2016-10-27 06:45
Here is the URL that I am redirected to - without any error message shown on-screen, every time I try to log into Twitter: https://twitter.com/login/error?username_or_email=[myUserNameShowsHere]&redirect_after_login=https%3A%2F%2Ftweetdeck.twitter.com%2F%3Fvia_twitter_login%3Dtrue

When login fails in other browsers, Twitter puts an error message explaining that there is a problem with either user name or password, but in the case of Brave, no message, just redirected to the login screen with a subtle indication in the URL, yet I KNOW that it is the correct user name and password, I am logging successfully into that account in other browsers (tried several times) and it only fails in Brave - every time.

**Comment by DeltaZone** [comment] 2016-10-27 06:49
The only setting I have changed in Brave, to no avail, is to allow scripts on Twitter.com. I just moved the slider for "Block Scripts" to the left so it is inactive/uncolored. But still the same login problem. 

BTW, I also think that Brave should let me allow one by one of the scripts, like I do with the ScriptSafe browser extension for Chrome, or with NoScripts for Firefox. I am not comfortable with allowing all or none for each site. I normally know which scripts are related to logins etc., and which are not neccessary, so I would like to be able to control that. In the interface of the top-right menu panel, you show each script URL, but sadly there are no option to allow one by one.

**Comment by srirambv** [comment] 2016-10-27 06:50
[+1 from support ](https://linkbubble.zendesk.com/agent/tickets/6343)

**Comment by DeltaZone** [comment] 2016-10-27 06:51
(I am on Linux Ubuntu 16.04, btw.)

**Comment by jonathansampson** [comment] 2016-10-27 07:55
Dupe of #4877

**Closed by jonathansampson** 2016-10-27 07:55 UTC

**Comment by an00nymous** [comment] 2016-11-07 16:35
I've been clicking the login button like a madman with my user/pass saved and turning on/off all sorts of Brave settings to no avail. 

I then synced my Twitter via IFTTT using the API login, and now I'm finally in!
