### ISSUE TITLE
startup time gets longer and longer, use a Splash Screen

### ISSUE THREAD

**Issue by privatzee** [brave/browser-laptop#5820] opened 2016-11-23 18:15 UTC
It's now at least 10 seconds with nothing showing, often longer. Users won't know if it's actually starting or what.

**Comment by Liunkae** [comment] 2016-11-23 19:42
Related: #3025

**Comment by bsclifton** [comment] 2018-09-09 08:04
Closing as duplicate of https://github.com/brave/browser-laptop/issues/3025 (which is fixed with brave-core)

**Closed by bsclifton** 2018-09-09 08:04 UTC
Labels: perf, suggestion
