### ISSUE TITLE
Javascript error when attempting to save a password

### ISSUE THREAD

**Issue by mjoyce4550** [brave/browser-laptop#1180] opened 2016-03-26 17:08 UTC
![brave javascript error when attempting to save a password](https://cloud.githubusercontent.com/assets/18089335/14061318/7344414a-f34b-11e5-95b1-1f900c8806f1.PNG)

**Comment by diracdeltas** [comment] 2016-03-28 07:58
Duplicate of #1165

**Closed** 2016-03-30 06:58 UTC
Labels: duplicate
