### ISSUE TITLE
Window buttons looks different on CR65 build

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13349] opened 2018-03-01 11:01 UTC
### Description
Window buttons looks different on CR65 build

### Steps to Reproduce
  1. Install 0.21651
  2. Window buttons looks different even on small screen
  3.

**Actual result:**
Maximized button and close button looks bad 
0.21.651 (top) vs 0.21.18(bottom)
![image](https://user-images.githubusercontent.com/17010094/36841142-6910f080-1d6d-11e8-9508-ea9329bca92d.png)
Restore button looks wrong 0.21.651 (top) vs 0.21.18(bottom)
![image](https://user-images.githubusercontent.com/17010094/36841226-ab99ef92-1d6d-11e8-9aa9-210a188085ac.png)

**Expected result:**
Should show proper buttons

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.21.651
-- | --
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.88
Muon | 5.1.2
Node.js | 7.9.0
OS Architecture | x64
OS Platform | Microsoft Windows
OS Release | 10.0.16299
rev | 32c9686
Update Channel | Beta
V8 | 6.5.254.26

**Reproducible on current live release:**
No

### Additional Information
cc: @bsclifton

**Comment by bsclifton** [comment] 2018-03-09 17:37
Confirmed this issue doesn't happen at 100% DPI; only at 125 or greater

**Comment by bsclifton** [comment] 2018-03-09 17:53
Assigned to @ltilve to investigate; since I've experienced and solved similar Windows issues before, I'll try to help look into this too

**Comment by bsclifton** [comment] 2018-03-12 15:51
Doesn't look like this is DPI related. Might be related to the breaking CSS changes we've found:
https://github.com/brave/browser-laptop/issues/13373
https://github.com/brave/browser-laptop/issues/13371

**Comment by bsclifton** [comment] 2018-03-12 20:11
Problem worked around by updating the viewport size. Fix in commit https://github.com/brave/browser-laptop/commit/9a6ca8bc8453c3d3aad1cf382176f25eefa98b4c

**Closed by bsclifton** 2018-03-12 20:11 UTC
Labels: 0.21.x, OS/Windows, bug/dpi/monitor, misc/button, regression

**Comment by srirambv** [comment] 2018-03-13 09:35
Verified on 125%, 150% and looks fine
