### ISSUE TITLE
Window title isn't updating after closing tab in Win7

### ISSUE THREAD

**Issue by JAffleck** [brave/browser-laptop#2358] opened 2016-07-01 03:58 UTC
**Did you search for similar issues before submitting this one?**
Yes, briefly
**Describe the issue you encountered:**
In Windows, the window title for Brave seemed to keep the first tab I had opened even after closing that tab (and having opened others)
**Expected behavior:**
I presume the window title would reflect only the currently active tab. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 7 x64
- Brave Version: 0.10.4

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment] 2016-07-02 12:35
@bsclifton would you mind taking a look?

**Comment by bsclifton** [comment] 2016-07-02 18:47
Will be able to look at this later today :smile:

**Comment by bsclifton** [comment] 2016-07-04 03:35
Unable to reproduce on my Win7 x64 laptop w/ 0.10.4 :frowning: 

@JAffleck do you have any specific steps I can try? For example, if you close all of your windows and exit... does it still happen?

**Comment by JAffleck** [comment] 2016-07-06 16:44
Sorry, I just noticed this email.  I'll try this at home tonight and reply
back.

James

**Comment by bsclifton** [comment] 2016-07-09 20:01
Closing for now. @JAffleck please re-open and share more details if you continue to see this issue. Thanks :smile:

**Closed by bsclifton** 2016-07-09 20:01 UTC
Labels: info-needed, windows-only
