### ISSUE TITLE
Regression: Toggling shields does not re-enable HTTPSE

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4220] opened 2016-09-23 05:58 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When toggling the shield, HTTPSE was not re-enabled. 

**Expected behavior:**
If the shields are up and HTTPSE is enabled, the site should load via https.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on OS X
- Brave Version:
  0.12.2 rc2 
- Steps to reproduce:
  1. Visit http://www.apple.com, notice it becomes https://www.apple.com
  2. Turn off HTTPSE via the shield
  3. Visit http://www.apple.com, notice it stays http://www.apple.com
  4. Turn on HTTPSE via the shield
  5. Visit http://www.apple.com, notice it becomes https://www.apple.com
  6. Toggle 'Shields Down' 
  7. Visit http://www.apple.com, notice it stays http://www.apple.com
  8. Toggle 'Shields Up'
  9. Visit http://www.apple.com, notice it stays http://www.apple.com 
- Screenshot if needed:
  ![https_screen_toggle](https://cloud.githubusercontent.com/assets/1434040/18775656/cfa57416-8128-11e6-9299-53fe5d6071cd.gif)
- Any related issues:

**Comment by bbondy** [comment] 2016-09-23 11:41
This is a URLbar update problem, the state shows it is actually upgrading to HTTPS

**Comment by bridiver** [comment] 2016-09-23 18:45
this actually doesn't appear to be a urlbar update problem. When I look at the network traffic it is still going to `http://www.apple.com` after enabling shields. The brave panel should 13 upgrades, but `http://www.apple.com` is not one of them

**Comment by bridiver** [comment] 2016-09-23 18:48
it does work correctly on `http://https-everywhere.badssl.com/` and updates the address bar which is unfortunate because I don't want to use http://www.apple.com in the test, but I'll figure out what the issue is first

**Comment by bbondy** [comment] 2016-09-24 16:27
This was reverted here, so re-opening
https://github.com/brave/browser-laptop/commit/1d65e0bc9c7f9a3e36ef33ce3ef1e793520918b5

**Comment by bbondy** [comment] 2016-09-24 16:27
Also moving this to 0.12.3 since it's just an intermittent race condition that probably happened before as well.

**Comment by bridiver** [comment] 2016-09-24 20:05
It is defiantly an intermittent issue. It is intermittent on Apple.com and not reproducible at badssl

**Comment by bridiver** [comment] 2016-09-24 20:08
I had actually identified a general race condition before this bug and I verified it when testing this

**Comment by bridiver** [comment] 2016-09-24 20:10
also as notes below the page is still on http and only the subresouces that loaded after the race were upgraded

**Comment by bridiver** [comment] 2016-09-24 20:20
I didn't actually check this because I had already verified the race condition with other methods, but you should see a different number of upgrades when it shows http vs https because some of the upgrades were Apple.com subresouces that should already be https when the page loads as https

**Comment by diracdeltas** [comment] 2016-09-28 21:31
i can no longer repro the original bug - turning shields off then on again and going to http://apple.com updates to https://apple.com as expected.

**Comment by bridiver** [comment] 2016-09-28 21:44
@diracdeltas there is a race condition so the issue is intermittent and we haven't done anything that would fix the underlying issue

**Comment by bbondy** [comment] 2016-10-10 13:47
@bridiver you had a PR for this that we had to backout, did you ever get back to that?

**Comment by bsclifton** [comment] 2016-10-13 16:18
original commit was done w/ https://github.com/brave/browser-laptop/commit/35de6cf76a3cf95b6c8cda5179c661242b747a01

and revert done w/ https://github.com/brave/browser-laptop/commit/1d65e0bc9c7f9a3e36ef33ce3ef1e793520918b5

IIRC, this caused some issues... one of them being the ledger not properly considering the status code (I believe because it doesn't get the response)

**Comment by luixxiul** [comment] 2017-11-07 11:54
As Apple enables HTTPS by default, let's close this issue. If the issue is still experienced on other sites, let's open a new issue for that.

**Closed by luixxiul** 2017-11-07 11:54 UTC
Labels: needs-info, regression
