### ISSUE TITLE
Captcha on payment screen not working

### ISSUE THREAD

**Issue by sepeiFH** [brave/browser-laptop#14350] opened 2018-06-07 06:48 UTC
### Description

The captcha on the payment screen is not solveable. Error happened on an low specificated Windows 10 PC and on an high performance Windows 10 PC. It did work on Mac without problems (There was a green plus on the brave logo which isn't in the windows version. 
On the first PC I could solve the captcha by draging it to an random location where the triangle was not positined.

### Steps to Reproduce

  1. Open Brave
  2. Go to payment
  3. Claim free funds
  4. Try to solve captcha

**Actual result:**

![brave](https://user-images.githubusercontent.com/22662993/41082536-fd39f334-6a2e-11e8-8058-491252c9250f.gif)

**Expected result:**
To solve the captcha.

**Reproduces how often:**

Everytime

### Brave Version

**about:brave info:**

 
Brave: 0.22.727 
V8: 6.6.346.32 
rev: 2c94bbad00d70b87328f04574725979960e18f9f 
Muon: 6.0.12 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Reproducible on current live release:**

Yes

**Comment by srirambv** [comment] 2018-06-07 14:16
Is the browser maximized when claiming the grant? If not could you maximize the window and try again?

**Comment by sepeiFH** [comment] 2018-06-07 15:49
The window was maximized. Tried it again still same error. I probably got now an IP ban.....

**Comment by Miyayes** [comment] 2018-06-08 19:50
@sepeiFH See if this helps:

(3) If you cannot complete the CAPTCHA: Are you on a Windows (PC)? If so, please check your interface scaling settings. For example, if you are using a higher resolution screen, Windows may scale up your UI by 200% to magnify items and text on your screen. This may distort the pixel location of the CAPTCHA target. 

Solution: Turn your interface scaling settings back to 100% to complete the CAPTCHA.

The IP-based rate-limiting should lift after a few hours (or after 24h for sure). You can also try enabling a VPN.

**Comment by NejcZdovc** [comment] 2018-06-09 05:44
closing as dupe of #14361

**Closed by NejcZdovc** 2018-06-09 05:44 UTC
Labels: feature/rewards, needs-info
