### ISSUE TITLE
Certificate Transparency errors causing problems on common sites

### ISSUE THREAD

**Issue by jimfenton** [brave/browser-laptop#6199] opened 2016-12-14 00:54 UTC
**Did you search for similar issues before submitting this one?**
Yes: saw #6106 and others

**Describe the issue you encountered:**
http://nytimes.com is not rendering properly because their CSS file is hosted on https://a1.nyt.com which is getting a certificate transparency error. Most of the other images, etc. on the page are hitting the same thing.

**Expected behavior:**
Page renders properly (as it does with Brave 0.12.14 on my Mac)

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 14.04.LTS

- Brave Version:
0.12.6 (is this the latest or is this old? I tried updating and it says it's the latest but it's a lot lower version number than on my Mac.

- Steps to reproduce:
    1. Visit http://nytimes.com and observe that it isn't rendering properly
    2. Visit https://a1.nyt.com and get net::ERR_CERTIFICATE_TRANSPARENCY_REQUIRED

- Screenshot if needed:
N/A

- Any related issues:
The Brave website should show what the latest version numbers are for each platform.

**Comment by Liunkae** [comment] 2016-12-14 05:51
@jimfenton: Please manually update to the latest version (0.12.14). [Here are some new instructions for Linux installations/updates](https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md).

Linux does not have automatic updates yet (#1470).

I'll close this issue as a duplicate of #6106.

**Closed by Liunkae** 2016-12-14 05:51 UTC

**Comment by jimfenton** [comment] 2016-12-14 06:47
There seem to be some problems with the automatic update process. I'm getting:

`W: Failed to fetch https://s3-us-west-2.amazonaws.com/brave-apt/dists/trusty/InRelease  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)`

even though I'm on amd64 architecture:

```
root@kernel:/etc/apt/apt.conf.d# dpkg --print-architecture
amd64
```

But the manual update was successful.

Nevertheless, it would be good if the Brave website said what the current version is, and if the "check updates" option didn't always say "no updates".

**Comment by Liunkae** [comment] 2016-12-14 07:35
In addition to #1470 (show update and manual installation link), I've filed two issues: #6208 (show Brave version on website) and #6209 (the update error you described).
