### ISSUE TITLE
Bookmarks cannot be exported

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11744] opened 2017-11-01 13:56 UTC
### Description

There are several reports on that issue that bookmarks cannot be exported.

- https://github.com/brave/browser-laptop/pull/6652#issuecomment-341107631
- https://community.brave.com/t/is-there-a-way-to-export-bookmarks/9975

> Same question here. The export functionality appears to have broken in 0.19.70. Clicking on Export does not generate a file.

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

0.19.70

**Reproducible on current live release:**

Yes.

**Comment by eljuno** [comment] 2017-11-10 19:07
+1 from community https://community.brave.com/t/export-bookmarks-not-working/10535?u=eljuno

‘Export Bookmarks’ is not saving the HTML file

>Brave: 0.19.88
rev: c29eca63249e3d43584ca1dcc47f3e7a7e904324
Muon: 4.5.15
libchromiumcontent: 62.0.3202.89
V8: 6.2.414.40
Node.js: 7.9.0
Update Channel: Release
OS Platform: Microsoft Windows
OS Release: 10.0.15063
OS Architecture: x64

**Comment by bsclifton** [comment] 2017-11-11 23:28
Moving to the 0.20.x milestone- exporting bookmarks is a critical feature

**Comment by kjozwiak** [comment] 2017-11-22 18:39
> Moving to the 0.20.x milestone- exporting bookmarks is a critical feature

Agreed... I'm going to reach out to the users that had the above issues and see if we can nail down some STR.... From what I remember, @srirambv @LaurenWags and myself never ended up reproducing the issue.

**Comment by bsclifton** [comment] 2018-01-02 22:03
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/10587

**Closed by bsclifton** 2018-01-02 22:03 UTC
Labels: 0.19.x, bug, feature/bookmarks, feature/exporter, needs-info, needs-investigation, priority/P3, regression
