### ISSUE TITLE
Dropdown list has thick left border

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6468] opened 2016-12-30 13:12 UTC
**Did you search for similar issues before submitting this one?** 
Yes

**Describe the issue you encountered:**
Dropdown list has thick left border

**Expected behavior:**
Border should be same on all the sides 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
``` 
Brave: 0.13.0 
rev: 0c7a64d6917b6e7e72d074b05e1d7488466418a9 
Muon: 2.0.8 
libchromiumcontent: 54.0.2840.100 
V8: 5.4.500.41 
Node.js: 7.0.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64
```

- Steps to reproduce:
    1. Open any drop down list in pref page all of them have a thick left border

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/21565532/2c3c8c18-ce91-11e6-96fb-e631179e1570.png)

- Any related issues:
cc: @bradleyrichter

**Comment by bbondy** [comment] 2016-12-30 21:15
@srirambv can you confirm if this is also present in 0.12.15?

**Comment by srirambv** [comment] 2016-12-30 21:31
Here's how it looks on 0.12.15
![image](https://cloud.githubusercontent.com/assets/17010094/21572971/53da98d2-ced7-11e6-9843-1074c159a09d.png)

Issue specific to 0.13.0

**Comment by bsclifton** [comment] 2016-12-30 23:02
caused by https://bugs.chromium.org/p/chromium/issues/detail?id=395425
I have a fix, working on incorporating it now...

**Comment by bsclifton** [comment] 2017-01-05 16:20
OK it appears this issue is NOT caused by https://github.com/brave/browser-laptop/issues/6258, since it happens when not maximized.

The possible fix I had mentioned above does work (fix being pass Brave.exe two extra params; `--high-dpi-support=1 --force-device-scale-factor=1`)... but it works by forcing the Brave window to render at 100% DPI. It's important to note that this fix does NOT work at 200% (and also, the window is so small it's unreadable).

The magnification is expected- Chrome 54 introduced that (in 53 and prior, 125% or less DPI were hardcoded to 100%, avoiding this issue completely for those resolutions).

It appears there is a larger issue with DPI which causes this to happen which needs to be investigated.

**Comment by bsclifton** [comment] 2017-01-13 01:10
Confirmed this was fixed with https://github.com/brave/muon/commit/30fd6ff5ac772cb645b0d4be78fae49d84fbbb19 :smile:

**Closed by bsclifton** 2017-01-13 01:10 UTC
Labels: polish, release/not-blocking, settings

**Comment by luixxiul** [comment] 2017-01-13 01:15
Please remove the milestone and add labels `QA/no qa needed` and `release-note/exclude` if this appeared and was fixed within the same milestone, thanks!

**Comment by bsclifton** [comment] 2017-01-13 01:23
@luixxiul labels updated; keeping milestone for tracking purposes
