### ISSUE TITLE
investigate shield settings on capitalone.com

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#15231] opened 2018-09-26 16:23 UTC
### Description

Received a report from Twitter from a user that has encountered issues with capitalone.com loading due to our shield settings. 

User mentions not encountering the same issue with uBO. 

Capitalone.com displays a white page in Brave. 

### Steps to Reproduce

  1. Go to https://capitalone.com
  2. See white screen.
![brave-capitalone-09262018](https://user-images.githubusercontent.com/8979240/46093907-70087a80-c16d-11e8-8b0f-33cd2e509745.png)

  3.

**Actual result:**

**Expected result:**
Brave should display the page.

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

```
 
Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100
```

**Reproducible on current live release:**

Yes

### Additional Information

Appears we are blocking: 
```
https://nexus.ensighten.com/capitalone/Bootstrap.js

https://capitaloneservices.tt.omtrdc.net/m2/capitaloneservices/mbox/json?mbox=target-global-mbox&mboxSession=910e680fb4f542909c0815c835a12df9&mboxPC=910e680fb4f542909c0815c835a12df9.28_68&mboxPage=f736c2ac1d31461eb7ec231d4e5a5a2e&mboxRid=f4f070a8079e47ee81c6cd240cf63252&mboxVersion=1.5.0&mboxCount=1&mboxTime=1537952601589&mboxHost=www.capitalone.com&mboxURL=https%3A%2F%2Fwww.capitalone.com%2F&mboxReferrer=&mboxXDomain=enabled&browserHeight=1055&browserWidth=1477&browserTimeOffset=-420&screenHeight=1152&screenWidth=2048&colorDepth=24&devicePixelRatio=1.25&screenOrientation=landscape&webGLRenderer=ANGLE%20(Intel(R)%20HD%20Graphics%20520%20Direct3D11%20vs_5_0%20ps_5_0)&ssotgt=undefined&profile.SIC_lob=undefined&profile.KM2=false&mboxMCSDID=0A127E08B0AA98D1-4F2EA621D7C70606&vst.trk=metrics.capitalone.com&vst.trks=smetrics.capitalone.com&mboxMCGVID=39252072600372888523967213941905598313&mboxAAMB=RKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y&mboxMCGLH=9

https://js-agent.newrelic.com/nr-spa-1071.min.js
```

**Comment by bsclifton** [comment] 2018-09-27 00:06
Closing as a dupe of https://github.com/brave/browser-laptop/issues/15148

@lukemulks we're tracking on brave-core with https://github.com/brave/brave-browser/issues/1180. In that issue, I link to a few others which have similar behavior (maybe they're using the same ad-blocker-blocker library)

**Closed by bsclifton** 2018-09-27 00:06 UTC
Labels: feature/shields, site-bug
