### ISSUE TITLE
Honey: Support browserAction.setBadgeBackgroundColor

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#5367] opened 2016-11-03 02:50 UTC
## Test Plan:
1. Enable the LastPass extension
2. From chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/tabDialog.html?dialog=createAccountSimple, open Developer Tools (Ctrl+Shift+I)
3. From console, run `chrome.browserAction.setBadgeBackgroundColor({color:'#FF0000'})`

## Original issue description
Honey (and other extensions) may often communicate valuable information by way of badge icon background colors. Honey uses this API to indicate the presence of deals available for the domain.

**Screenshot:** (Left: Chrome, Right: Brave)
![image](https://cloud.githubusercontent.com/assets/815158/19954231/dc46778a-a133-11e6-9f61-0a09c27f0054.png)

**Documentation:** https://developer.chrome.com/extensions/browserAction#method-setBadgeBackgroundColor

**Related Issues:** #5366, #5362

**Comment by bsclifton** [comment] 2017-03-14 15:29
moving to 0.13.7

**Closed** 2017-04-03 06:39 UTC
Labels: feature/extensions, QA/steps-specified, release-notes/include

**Comment by alexwykoff** [comment] 2017-04-17 18:54
Could not reproduce on OS X.

**Comment by jonathansampson** [comment] 2017-05-04 04:13
Blocked #8671
