### ISSUE TITLE
Right click on multiple selected bookmarks should show the selection

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5164] opened 2016-10-26 18:04 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Right clicking on multiple selected bookmarks doesn't show the selection

**Expected behavior:**
Should highlight the selected bookmarks when right click on multiple bookmarks are selected
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.7 Preview 1
- Steps to reproduce:
  1. Open about:bookmark
  2. Select multiple bookmarks using Shift button
  3. Right click on the selected bookmarks, doesn't show the selection. This could make the user think that none of the bookmarks are selected. 
- Screenshot if needed:
  ![multibkmrkdelete](https://cloud.githubusercontent.com/assets/17010094/19738256/9f030774-9bae-11e6-9075-38da00d504e1.gif)
- Any related issues:

cc: @bsclifton

**Comment by bsclifton** [comment] 2016-10-26 21:25
I think this is a dupe of https://github.com/brave/browser-laptop/issues/4738

It should still delete, but sometimes selection is lost

**Comment by bbondy** [comment] 2016-10-31 20:34
#4378 is closed, moving to 0.12.9 but will move back if it gets fixed.

**Comment by bsclifton** [comment] 2016-11-08 01:19
Removed milestone- while the cosmetic behavior could be better, it doesn't cause an issue.  Let's discuss if you feel strongly / want to readd

**Closed** 2018-09-09 08:06 UTC
Labels: feature/bookmarks, fixed-with-brave-core, suggestion, wontfix
