### ISSUE TITLE
Sometimes Brave eats lots of CPU on OS X

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-laptop#861] opened 2016-02-22 17:16 UTC
<img width="643" alt="screen shot 2016-02-22 at 12 07 14 pm" src="https://cloud.githubusercontent.com/assets/12011303/13226049/9a532ea2-d95d-11e5-8946-17413128a283.png">
I don't know exact steps yet, but sometimes, when it stays open for several hours, it starts eating CPU lots. It just sits in the background for several hours without any problems and in one moment it starts to consume processor time lots.

**Comment by weems** [comment] 2016-02-22 17:40
Are you running from .App? Or can you run via npm command to get a more verbose log you can time with high cpu usage to figure out what is being executed at the time of high usage?

**Comment by SergeyZhukovsky** [comment] 2016-02-22 23:21
Yes, from .App. I use that version 0.7.15. Will try to reproduce with logs.

**Comment by jussihuotari** [comment] 2016-08-10 18:34
Same here. One of the `node` processes is taking ~30% cpu on OS X. Looks like this is pretty constant from the start. If I actively browse the net, the node process stays at 30% but the CPU consumption for Brave* processes peaks up (as expected).

FWIW, I think I didn't see the node process eating this much CPU before upgrading from v0.11.2dev.

@weems which 'verbose log' are you referring to? I'm running via npm.

**Comment by cwre** [comment] 2017-03-04 20:40
Just chiming in, saying that I've just noticed the issue, too.

**Comment by franzos** [comment] 2017-04-07 06:53
I have the same problem with Brave on Mac OS. Unfortunately the issue is rather easy to reproduce (literally: use the browser ...) and makes Brave almost unusable on a Laptop compared to Firefox / Chrome / Safari.

I'm on 0.14.1, with a couple of tabs open. CPU is at over 100% and memory consumption probably tops 6GB. Firefox, with the same set of tabs, is using just under 0,7% CPU with around 2GB of memory.

<img width="912" alt="screen shot 2017-04-07 at 8 44 17 am" src="https://cloud.githubusercontent.com/assets/2619225/24788764/8f00ff48-1b6f-11e7-8088-cfc1f9e9ed3e.png">
<img width="912" alt="screen shot 2017-04-07 at 8 41 47 am" src="https://cloud.githubusercontent.com/assets/2619225/24788765/8f01e386-1b6f-11e7-8497-9b00099083ae.png">

**Comment by jussihuotari** [comment] 2017-04-07 08:24
For me, since I wasn't using the packaged version but cloned the latest source code from github, the solution was to disable Webpack hot module replacement. After changing `--hot` to `--lazy`, the CPU load went down and I became a happy Brave user.

https://github.com/brave/browser-laptop/blob/master/package.json#L46

ref: https://webpack.github.io/docs/webpack-dev-server.html

**Comment by franzos** [comment] 2017-04-07 08:49
That's a great start @jussihuotari, thanks! I'll try to compile it myself to see if this makes a difference. In any case, why is the Webpack enabled by default?

**Comment by Alino** [comment] 2017-10-24 16:11
Brave Browser version 0.19.53
on MacOS High Sierra
16% to 31% CPU usage with one tab opened (to this github issue).

Installed extensions:
-1Password
-Metamask

![image](https://user-images.githubusercontent.com/763194/31954671-7e5056a2-b8e6-11e7-97cf-1ec34aeb0e71.png)

**Comment by FabioEleuterio** [comment] 2017-11-14 00:43
I have 100% cpu ... and every time consumes alot


Brave | 0.19.88
-- | --
rev | c29eca6
Muon | 4.5.15
libchromiumcontent | 62.0.3202.89
V8 | 6.2.414.40
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 6.3.9600
OS Architecture | x64

**Comment by FabioEleuterio** [comment] 2017-11-14 00:50
I just closed the Brave and reopened, with the 102 + - tabs open and dropped from 100% of the cpu to 3%

**Comment by gojomo** [comment] 2017-12-14 20:59
It's likely linked to something happening in the tab associated with that PID - so an "about:tabs" that includes native process-IDs would help narrow down what's making Brave so slow and unresponsive in these cases, and (as a temporary workaround) allow closing the offending tab.

**Comment by rhubarbwibble** [comment] 2018-05-23 08:49
I'm using an online tool (webflow) that puts the Brave Helper CPU usage through the roof...

![screen shot 2018-05-23 at 09 41 13](https://user-images.githubusercontent.com/32165953/40413682-5de3990a-5e6e-11e8-8a54-21788f9ecf5d.png)

Any ideas? Console points to a bug that they're looking at. Pretty unusable in Brave but it doesn't render the page at all in Safari.

**Comment by al2suarez** [comment] 2018-06-04 03:28
I have about 60 tabs open.  A couple of youtube tabs... only one tab is active playing a youtube video... my macbook.pro.retina.2.3GHzi7.16GBMem is pegged!  Why?  Even when no youtube videos playing, its still pegged at high... 
<img width="1920" alt="screen shot 2018-06-03 at 10 21 11 pm" src="https://user-images.githubusercontent.com/11946184/40896850-390c2648-677d-11e8-9604-e690d4ecd012.png">

**Comment by rhubarbwibble** [comment] 2018-06-04 08:36
Just to update, the folks at Webflow fixed the bug for me. It's now stable to use in Brave. Although, I still see CPU usage spike with Brave from time to time.

**Comment by Crushhhhhhh** [comment] 2018-07-18 06:35
Using Activity Monitor on OSX (Macbook retina):

- Brave Helper; and 
- Brave (to a lesser extent)

Consuming a lot of resources. Also left Brave running for an hour with 20-30 tabs while I was out. Macbook was super hot when returned.

Brave Helper seems to consume most resources. If force quit, it automatically re-opens.

**Comment by AshTex** [comment] 2018-08-02 04:57
I can confirm this happens to mine as well. Seems to have only started since I started using bitwarden as my password manager? I have no other extensions installed. Restart of the browser fixes it. 

MacOS 10.13.6 (17G65)
 
Brave: 0.23.73 
V8: 6.8.275.24 
rev: 50bdb6df42550dd14f5636770ec8585aa26e361b 
Muon: 8.0.3 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.75

**Comment by bsclifton** [comment] 2018-09-03 06:57
Closing as there isn't really anything actionable we can do. As a troubleshooting step, you might try [downloading brave-core](https://github.com/brave/brave-browser/releases) to see if the behavior persists there. If so, [we can open an issue for that repo](https://github.com/brave/brave-browser/issues)

**Closed by bsclifton** 2018-09-03 06:57 UTC
Labels: perf
