### ISSUE TITLE
Can't click the top bookmark unless the bookmark is over a tab

### ISSUE THREAD

**Issue by ntun** [brave/browser-laptop#10597] opened 2017-08-19 20:09 UTC
- Did you search for similar issues before submitting this one?  
Yes.   
- Describe the issue you encountered:  
I can't click the top bookmark inside a folder on the bookmark bar. If there is a tab opened under the bookmark, I will be able to click it.   
  
- Platform (Win7, 8, 10? macOS? Linux distro?):  
Windows 10 - 64bit   

- Brave Version (revision SHA):
Brave | 0.18.23  
rev | 36ae2ec  
  
- Steps to reproduce:
    1. Enable bookmark bar
    2. Create folders on the bookmark bar (4-5 folders)
    3. Create a bookmark on the far right folder 
    4. Try to click the bookmark without a tab under it. 
    
- Actual result:
It doesn't highlight or allow us to click the bookmark. There is a tiny area where I can move the mouse cursor to click it, but it is not practical to use. 

- Expected result:
I should be able to click the top bookmark without a tab under it. 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
It is a fresh brave install. 

- Is this an issue in the currently released version?
Yes, 

- Can this issue be consistently reproduced?
Not sure. My screen resolution is 1366x768. 

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
https://gfycat.com/gifs/detail/temptingopulentiguanodon

- Any related issues:

**Comment by eljuno** [comment] 2017-08-19 22:13
Duplicate of #9088 ?

**Closed** 2017-08-20 01:21 UTC
