### ISSUE TITLE
New tab dropdown menu should respect window width.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5784] opened 2016-11-22 01:30 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user in the field has reported that when enough tabs are open, the new tab menu is truncated by the right of the window.

**Expected behavior:**
The tab menu should probably flip horizontally when the + icon is beyond a certain % of window width.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.12.10

- Steps to reproduce:
    1. Open enough tabs to push the new tab icon to the far right of the window.
    2. Long click on the new tab icon.

- Screenshot if needed:
![new_tab_menu_truncated](https://cloud.githubusercontent.com/assets/1434040/20507553/ed32b26a-b020-11e6-9b92-67c3be197ec0.png)

- Any related issues:

**Comment by Liunkae** [comment] 2016-11-22 04:35
Duplicate of #5763.

**Closed by Liunkae** 2016-11-22 04:35 UTC
Labels: bug
