### ISSUE TITLE
"Default Browser" setting lost upon update

### ISSUE THREAD

**Issue by joekaiser** [brave/browser-laptop#6987] opened 2017-02-01 16:08 UTC
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
The "Default browser" setting is lost when the browser is updated to a new version

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win10

- Brave Version (revision SHA):
9dd06f9

- Steps to reproduce:
    1. install an older version, and set the browser as your default
    2. Update to a newer version
    
- Actual result:
The default browser setting was lost and brave asked you to make it default again.

- Expected result:
I expect the setting to persist across updates. Other major browsers behave this way. I admit it is a small issue (it doesn't really bother me). I just thought I would file it anyway.

I experienced this when upgrading to 13.0 and again when updating to 13.1 today.

**Comment by Liunkae** [comment] 2017-02-01 16:32
This is a duplicate of #5246 (Default browser setting gets reset after upgrade).

The problem is currently planned to be fixed by version 1.0.0.

**Closed by Liunkae** 2017-02-01 16:32 UTC
Labels: OS/Windows
