### ISSUE TITLE
Bookmarks are imported to a folder instead to bookmarks bar keeping order the same

### ISSUE THREAD

**Issue by agilob** [brave/browser-laptop#14532] opened 2018-06-23 06:17 UTC
### Description
I have over 100 bookmarks in firefox, when I imported them all folders and links went to a single folder "Imported From Firefox". Instead they should be imported to bookmarks bar in the same order as were exported from Firefox.

The same features was discussed on [Reddit](https://www.reddit.com/r/BATProject/comments/828jfg/how_to_import_bookmarks_from_chrome_to_brave/)

**Comment by eljuno** [comment] 2018-06-23 19:55
Dupe of #9569?

**Closed** 2018-06-24 09:45 UTC
