### ISSUE TITLE
regression : cannot remove top sites tile from new tab page

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10916] opened 2017-09-12 22:26 UTC
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
attempting to remove a top sites tile gave a confirmation modal, but the tile was not removed

- Platform (Win7, 8, 10? macOS? Linux distro?):
repro'd on Win7 & macOS

- Brave Version (revision SHA):
0.18.23

- Steps to reproduce:
    1. open the new tab page
    2. try to delete a tile
    
- Actual result:
tile is not removed

- Expected result:
the tile should be removed

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by hiddensanctum** [comment] 2017-09-12 23:20
I'm seeing the same issue on version 0.18.32

**Comment by bsclifton** [comment] 2017-09-12 23:50
This is similar to https://github.com/brave/browser-laptop/issues/10411... but I think it's different 

When running on master, the icon will actually remove itself when the X is clicked (after ~5 seconds).  With 0.18.x, nothing happens at all

**Comment by bsclifton** [comment] 2017-09-12 23:59
On second thought, closing as a duplicate of https://github.com/brave/browser-laptop/issues/10411 since only one post mentions running from master

**Closed by bsclifton** 2017-09-12 23:59 UTC
Labels: bug, needs-triage, regression
