### ISSUE TITLE
Tab moving needs a better ui

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#8291] opened 2017-04-13 12:25 UTC
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Brave handles draging of tabs strangly where you drag the whole tab if you want to move it, it should be done like chrome where it slides over in my oppinion
- Platform (Win7, 8, 10? macOS? Linux distro?):
Every platform
- Brave Version (revision SHA):
Every brave version
- Steps to reproduce:
    1. Open a couple of tabs in Brave and move them so they change their place
    2. Open a couple of tabs in Chrome and move them so they change their place

Related issues:
https://github.com/brave/browser-laptop/issues/8288

**Comment by bsclifton** [comment] 2017-04-19 04:38
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/6242

**Closed by bsclifton** 2017-04-19 04:38 UTC
Labels: feature/tabsbar, suggestion
