### ISSUE TITLE
0.18.x regression - Lastpass menu choices aren't working

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10129] opened 2017-07-25 20:15 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
After signing into Lastpass, the URLbar menu was found to be inoperative. Using the same profile on 0.17.19 worked.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.18.10

- Steps to reproduce:
    1. Enable the Lastpass extension
    2. Login
    3. Attempt to use the Lastpass extension menu on the URLbar
    
- Actual result:
Nothing happens

- Expected result:
The selected menu item should work

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment] 2017-07-25 20:29
Duplicate of https://github.com/brave/browser-laptop/issues/10029. I'll rename the original issue since this title is better

**Closed by bsclifton** 2017-07-25 20:29 UTC
Labels: bug, regression, release/blocking
