### ISSUE TITLE
Wallet creation fails on 0.19.89

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11929] opened 2017-11-13 13:32 UTC
### Description
Wallet creation fails on 0.19.89

### Steps to Reproduce
  1. Clean install 0.19.89
  2. Close and launch from console
  3. Enable payment, shows error as mentioned below and wallet doesn't get created

**Actual result:**
```
ledger client boot error:  { Error: Cannot find module './babel-core'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.89\resources\electron.asar\common\reset-search-paths.js:41:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at module.exports (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.89\resources\app.asar\node_modules\ast-types\def\babel.js:2:12)
    at use (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.89\resources\app.asar\node_modules\ast-types\fork.js:11:31)
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.89\resources\app.asar\node_modules\ast-types\fork.js:20:10)
    at C:\Users\Sriram BV\AppData\Local\brave\app-0.19.89\resources\app.asar\node_modules\ast-types\main.js:1:182
    at Object.<anonymous> (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.89\resources\app.asar\node_modules\ast-types\main.js:18:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
```
![walletcreation](https://user-images.githubusercontent.com/17010094/32728024-b049adb2-c876-11e7-81fa-da65c1605108.gif)

**Expected result:**
Should create wallet

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.89
-- | --
rev | 20badac
Muon | 4.5.15
libchromiumcontent | 62.0.3202.89
V8 | 6.2.414.40
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
No

### Additional Information
#11925

**Comment by LaurenWags** [comment] 2017-11-13 15:07
Unable to reproduce on MacOS.

**Comment by kjozwiak** [comment] 2017-11-13 15:11
> Unable to reproduce on MacOS.

Same results here. I couldn't reproduce this under macOS but managed to reproduce on both Win and Ubuntu using the STR that @srirambv added above. Went through the following platforms:

* Win 10 x64 - **_Reproduced_**
* Ubuntu 16.04.3 LTS - **_Reproduced_** 
* macOS 10.12.6 x64 - **_Couldn't reproduce_**

**Comment by bsclifton** [comment] 2017-11-13 19:25
Fixed with https://github.com/brave/browser-laptop/commit/e7165b52dd6aa1e5c03f2e082283b271e96e5344

**Closed by bsclifton** 2017-11-13 19:25 UTC
Labels: 0.19.x, bug, feature/ledger, OS/unix-like/linux, OS/Windows, regression, release/blocking
