### ISSUE TITLE
Undo/Redo enabled by default in right click context menu.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2811] opened 2016-07-29 19:17 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Undo/Redo enabled by default on all text input fields even on new page opened in a new tab

**Expected behavior:**
Should be enabled only when text is entered in the input field
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 64bit 
- Brave Version:
  0.11.2 Dev Beta1
- Steps to reproduce:
  1. Open any webpage which has input field
  2. Right click inside the input field
  3. Undo/Redo option enabled by default. 
- Screenshot if needed:
- Any related issues:

**Comment by Liunkae** [comment] 2016-11-07 00:51
Duplicate of #777.

**Closed by Liunkae** 2016-11-07 00:51 UTC
