### ISSUE TITLE
Brave does not interact well with xfce window manager

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#5842] opened 2016-11-25 16:03 UTC
User from support mentioned that we don't work well with xfce window manager.
https://linkbubble.zendesk.com/agent/tickets/5854

**Comment by Liunkae** [comment] 2017-01-27 19:29
Related: #3180

**Comment by luixxiul** [comment] 2017-11-07 20:10
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/does-brave-not-run-on-linux-mint-with-xfce/10420

Let's reopen if someone tells us that the issue is reproducible 👍

**Closed by luixxiul** 2017-11-07 20:10 UTC
Labels: bug, OS/unix-like/linux
