### ISSUE TITLE
increase font size in URL text to match chrome

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#7848] opened 2017-03-22 21:21 UTC

**Comment by bsclifton** [comment] 2017-03-30 17:33
@bradleyrichter is this a dupe of https://github.com/brave/browser-laptop/issues/1937?

**Comment by bradleyrichter** [comment] 2017-03-30 20:26
no. This is to increase the URL bar font size by 1 point permanently for the default zoom level.

**Closed** 2017-04-20 07:51 UTC
Labels: accessibility
