### ISSUE TITLE
Toolbar and UI elements scale setting change is applied before restarting

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10483] opened 2017-08-15 02:59 UTC
**Describe the issue you encountered:** Toolbar and UI elements scale setting change is applied before restarting.

Brave: 0.18.22 
rev: d850e287ace296e2c62e28ba2979cf172e41cc45 
Muon: 4.3.9 
libchromiumcontent: 60.0.3112.90 
V8: 6.0.286.52 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Linux 
OS Release: 4.9.0-3-amd64 
OS Architecture: x64

![bug](https://user-images.githubusercontent.com/3362943/29300449-6a20402e-81b0-11e7-8c82-3f377891f8b3.gif)

It is reproduced on Windows 10 as well.

- Steps to reproduce:
    1. Open about:preferences#advanced
    2. Change `Toolbar and UI elements scale settings`
    
- Actual result: See above

- Expected result: the change should be applied either a) instantly without the notification bar or b) after restart with the notification bar

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #10410

**Comment by bsclifton** [comment] 2017-08-18 06:21
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/10089

**Closed by bsclifton** 2017-08-18 06:21 UTC
Labels: bug, needs-triage, settings
