### ISSUE TITLE
Hotkey CTRL + W on last tab of many closes the entire browser

### ISSUE THREAD

**Issue by hoffination** [brave/browser-laptop#9364] opened 2017-06-09 16:40 UTC
- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered: 
When I have multiple tabs open and press CTRL + W on the last tab the entire browser closes

- Platform (Win7, 8, 10? macOS? Linux distro?): Win 10

- Brave Version (revision SHA): 0.16.6

- Steps to reproduce:
    1. Open more than one tab
    2. Navigate to the last tab
    3. Type CTRL + W
    
- Actual result: Closes the Browser when hotkey closing the last tab

- Expected result: Closes the Browser when hotkey closing the last tab

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Not Sure
- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
No

**Comment by bsclifton** [comment] 2017-06-11 06:02
@hoffination do you have more information about this?  I've tried to reproduce and haven't had any luck.  I did notice if you hold Ctrl + W down for a few seconds, it will quickly close the tabs and once none are left, it closes the browser

**Comment by hoffination** [comment] 2017-06-12 15:15
@bsclifton I reproduced it this morning on the last tab when I navigate to an nginx hosted website on localhost:80. I also was able to reproduce it on the produced about:error page when the server was shutdown.

When closing that tab and trying to make another tab to reproduce it I am unable to. Anyway for me to grab a stacktrace from a log file or something if it happens again?

**Comment by kroppt** [comment] 2017-06-13 05:47
I was able to reproduce it.

1. Open tabs, turn on "tabs from last time" startup
2. Close the window.
3. Open Brave again.
4. Ctrl+W or close out the tab.
5. Window closes.

On startup again, the tab was never closed, just the window. So, close tab was replaced with close window.

**Comment by alexkillen** [comment] 2017-06-15 09:35
I have this issue as well, and it also happens if I close the last tab when clicking the X.  

One thing I did note is that the tab before it needs to NOT be loaded to reproduce the bug.  If you switch between the last few tabs to ensure they are all loaded and then close the last tab it works fine.

**Comment by Gleiphnir** [comment] 2017-06-15 15:13
Can confirm that the bug can be reproduced
-when 'tabs from last time' is enabled
-upon opening Brave, if there are any tabs that are not loaded, closing the current tab will close brave.

Seems like it's not checking the unloaded tabs and closes because it 'thinks' that there are no more tabs.

**Comment by GreenRecycleBin** [comment] 2017-06-18 13:34
Relevant code is at https://github.com/brave/browser-laptop/blob/c5968c5ea2a8eaab1834d638aa4ead5af5d517e2/app/browser/reducers/tabsReducer.js#L164. 

Inactive pinned/non-pinned tabs have `windowId` set to `-1`. Therefore, they're not counted in `tabState#getNonPinnedTabsByWindowId` or `tabState#getPinnedTabsByWindowId`.

I've been looking for a way to count the number of all tabs that belong to a window but couldn't find any existing code that does this.

I'm not sure how to add this functionality (preferably via a minimal change).

@bsclifton I'd appreciate some pointers. Thank you.

**Comment by credej** [comment] 2017-06-26 00:21
Also having this issue on macOS. Has happened both with ctrl + w, and just clicking the close button. However I'm fairly certain my windows had already loaded. 

When reopening after this bug, all previously opened tabs are lost even if you have the option ticked to open tabs from last time.

**Comment by bsclifton** [comment] 2017-06-27 06:15
@GreenRecycleBin sorry for not responding sooner- you nailed it 😄  The windowId needed to be set in the tabState in order for that method to return the proper number of results

I'm going to close this issue as a duplicate of https://github.com/brave/browser-laptop/issues/9506 which was closed by https://github.com/brave/browser-laptop/pull/9507/commits/e261b9ea12485ef91ad24774d51e2a3831bb7aec and https://github.com/brave/muon/commit/4189da5f457b577ad374ef1a52d619ef2bfbe042... but if anyone is still encountering it after our next release, please comment and/or reopen this issue 😄

**Closed by bsclifton** 2017-06-27 06:15 UTC
Labels: needs investigation, OS/Windows
