### ISSUE TITLE
getUserMedia() allowed without a first prompt?

### ISSUE THREAD

**Issue by ibc** [brave/browser-laptop#617] opened 2016-02-04 22:45 UTC
So first time I open Brave. Go to https://apprtc.appspot.com/ and press `Join` button.

The browser MUST prompt me about permission to use my webcam and mic. Then, if I accept, such a setting should be stored for the given domain.

But... Brave automatically opens the webcam and mic without asking me...

**Comment by psimyn** [comment] 2016-02-04 22:57
Duplicate of https://github.com/brave/browser-laptop/issues/472 - awaiting electron update

**Comment by diracdeltas** [comment] 2016-02-04 23:04
yep, update coming soon

**Comment by diracdeltas** [comment] 2016-03-02 02:05
Fixed by 35efd0ecdcaf98deee1d29c1a319fbbfe04a0c59

**Closed by diracdeltas** 2016-03-02 02:05 UTC
Labels: duplicate
