### ISSUE TITLE
Can't install brave on Ubuntu 18.04

### ISSUE THREAD

**Issue by rgonnering** [brave/browser-laptop#13861] opened 2018-04-18 21:45 UTC
### Description

$ sudo apt update
Get:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease [235 kB]
Hit:2 http://archive.canonical.com/ubuntu bionic InRelease                     
Hit:3 https://packages.microsoft.com/repos/vscode stable InRelease             
Hit:4 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Hit:5 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease           
Err:6 https://s3-us-west-2.amazonaws.com/brave-apt bionic InRelease            
  403  Forbidden [IP: 52.218.212.128 443]
...

### Steps to Reproduce

Followed 'brave install' steps from
     https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md

$ sudo echo

$ curl https://s3-us-west-2.amazonaws.com/brave-apt/keys.asc | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1828  100  1828    0     0   1971      0 --:--:-- --:--:-- --:--:--  1969
OK

$ echo "deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt `lsb_release -sc` main" | sudo tee -a /etc/apt/sources.list.d/brave-`lsb_release -sc`.list
deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt bionic main

$ cat /etc/apt/sources.list.d/brave-*.list
deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt bionic main

$ grep lsb_release /etc/apt/sources.list.d/brave*

$ sudo apt update

$ sudo apt install brave
...
Err:6 https://s3-us-west-2.amazonaws.com/brave-apt bionic InRelease            
  403  Forbidden [IP: 52.218.212.128 443]

**Actual result:**

~$ sudo apt update
Get:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease [235 kB]
Hit:2 http://archive.canonical.com/ubuntu bionic InRelease                     
Hit:3 https://packages.microsoft.com/repos/vscode stable InRelease             
Hit:4 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Hit:5 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease           
Err:6 https://s3-us-west-2.amazonaws.com/brave-apt bionic InRelease            
  403  Forbidden [IP: 52.218.212.128 443]
Get:7 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,023 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu bionic/main i386 Packages [1,012 kB]
Hit:9 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Get:10 http://us.archive.ubuntu.com/ubuntu bionic/main Translation-en [517 kB] 
Get:11 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 DEP-11 Metadata [469 kB]
Get:12 http://us.archive.ubuntu.com/ubuntu bionic/main DEP-11 64x64 Icons [254 kB]
Get:13 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [8,561 kB]
Get:14 http://us.archive.ubuntu.com/ubuntu bionic/universe i386 Packages [8,525 kB]
Get:15 http://us.archive.ubuntu.com/ubuntu bionic/universe Translation-en [4,941 kB]
Get:16 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 DEP-11 Metadata [3,002 kB]
Get:17 http://us.archive.ubuntu.com/ubuntu bionic/universe DEP-11 64x64 Icons [8,125 kB]
Get:18 http://us.archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [150 kB]
Get:19 http://us.archive.ubuntu.com/ubuntu bionic/multiverse i386 Packages [143 kB]
Get:20 http://us.archive.ubuntu.com/ubuntu bionic/multiverse amd64 DEP-11 Metadata [40.8 kB]
Get:21 http://us.archive.ubuntu.com/ubuntu bionic/multiverse DEP-11 64x64 Icons [216 kB]
Reading package lists... Done                                                  
E: Failed to fetch https://s3-us-west-2.amazonaws.com/brave-apt/dists/bionic/InRelease  403  Forbidden [IP: 52.218.212.128 443]
E: The repository 'https://s3-us-west-2.amazonaws.com/brave-apt bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Expected result:**
Brave should install.

**Reproduces how often:**
100%

### Brave Version
N/A. Can't install. Attempted install 4-18-2018, if that helps.

**Reproducible on current live release:**

**Comment by kjozwiak** [comment] 2018-04-19 01:37
@rgonnering could you please provide us with some more information? Which method are you using to install Brave? I believe Ubuntu 18 is still in the early BETA phase. I'll try downloading one of the daily builds and see if I can reproduce.

**Comment by rgonnering** [comment] 2018-04-19 01:42
Hi kjozwiak,

The method steps are listed in the ### Steps to Reproduce Section, as specified in the Brave Installation Instructions for Ubuntu. Are you asking for something else?

Thanks,
Roger

**Comment by kjozwiak** [comment] 2018-04-19 02:14
Thanks @rgonnering, should be enough info to reproduce. Your original report basically had `
Brave should install.` and that's pretty much it. Usually the more information the better 👍

**Comment by retrocausal** [comment] 2018-04-27 13:08
I weigh in here. just felt helpless trying to install brave on a brand new ubuntu 18.04 system. the errors, exactly similar to the one detailed above when I try an apt install. 

I could possibly use snap install, since bionic beaver is snappy, but I had had issues in the past , and have opened tickets as well, where the snaps were not released in time and never kept up with the updates of the latest desktop releases.

**Comment by plaxer** [comment] 2018-04-28 00:40
Having the same error on Kubuntu 18.04 LTS as well.

```
**user@pc-name**:~$ sudo apt-get update && sudo apt-get upgrade 
Hit:1 http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                                
Get:3 http://gb.archive.ubuntu.com/ubuntu bionic InRelease [242 kB]                                                              
Get:4 http://im.archive.ubuntu.com/ubuntu bionic InRelease [242 kB]                                                              
Hit:5 http://ppa.launchpad.net/papirus/papirus/ubuntu bionic InRelease                                                           
Hit:6 https://updates.signal.org/desktop/apt xenial InRelease                                                                    
Hit:7 http://ppa.launchpad.net/system76/pop/ubuntu bionic InRelease                                                              
Hit:8 http://gb.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                               
Hit:9 http://im.archive.ubuntu.com/ubuntu bionic-updates InRelease                            
Err:10 https://s3-us-west-2.amazonaws.com/brave-apt bionic InRelease                           
  403  Forbidden [IP: 52.218.201.112 443]
Hit:11 http://gb.archive.ubuntu.com/ubuntu bionic-backports InRelease                          
Hit:12 http://im.archive.ubuntu.com/ubuntu bionic-backports InRelease    
Reading package lists... Done                      
E: Failed to fetch https://s3-us-west-2.amazonaws.com/brave-apt/dists/bionic/InRelease  403  Forbidden [IP: 52.218.201.112 443]
E: The repository 'https://s3-us-west-2.amazonaws.com/brave-apt bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by WalkingSouth** [comment] 2018-04-28 02:41
Hi, I had the same issue when attempting the steps you specified yesterday, which was the release date of Ubuntu 18.04 "Bionic". I have found this article to be useful, which states to use the code

`snap find brave
sudo snap install brave`

https://ubuntuforums.org/showthread.php?t=2388431

> This is my first comment, made the account to say this. That being said, if my response is misformatted and/or breaks community guidelines or ToS et. al, please let me know and I will fix it.

**Comment by mikran** [comment] 2018-05-03 08:30
I just upgraded to 18.04 and this happened to me too.

**Comment by kjozwiak** [comment] 2018-05-04 03:40
I'm moving this into the `0.22.x Release 3 (Beta channel)` milestone. Ubuntu 18.04 is now an `LTS` version which means most folks are going to start using or started upgrading to it. From all the above comments, it sounds like we have issues that need to be resolved here.

We should fix this before pushing a new version of Brave. We're going to frustrate a lot of Ubuntu users as it's one, if not the most popular distro on the market.

**Comment by bsclifton** [comment] 2018-05-04 16:56
I believe I know how to solve this- will check and share findings

**Comment by bsclifton** [comment] 2018-05-04 22:15
re-opening until I can run out deploy job and test the fix 😄

**Comment by JR1994** [comment] 2018-05-06 21:03
I am having the same issue on Ubuntu-MATE 18.04

**Comment by bsclifton** [comment] 2018-05-07 22:36
Verified fix for deb (pushed for `brave-beta`); working through the RPM side with help from @evq

**Comment by bsclifton** [comment] 2018-05-08 16:11
@rgonnering @JR1994 @mikran @WalkingSouth @gabrieldnzs @plaxer @retrocausal this issue should now be fixed 😄 I've tested it myself using a fresh install of Ubuntu 18. I made sure to update both `brave` and `brave-beta` (and tested both)

Please let us know how it goes 😄

**Closed by bsclifton** 2018-05-08 16:11 UTC
Labels: OS/unix-like/linux

**Comment by plaxer** [comment] 2018-05-08 16:29
Can confirm its working fine now. Thanks Clifton.

**Comment by kjozwiak** [comment] 2018-05-09 13:29
Thanks for working and getting this done @bsclifton! I'm sure the community will really appreciate it 👍

**Comment by rgonnering** [comment] 2018-05-09 19:59
Thanks for the help.

I have not been able to install Brave, but that is not related to this
ticket. Once I get that resolved, I will try to install Brave again.

Thanks,
Roger

**Comment by gabrieldnzs** [comment] 2018-05-10 01:33
@bsclifton @kjozwiak  It's working on Kubuntu 18.04 LTS! Thanks for the help! I'm using Brave as my primary navigator for a week and i'm very happy with the browser. Keep the good work :+1:

**Comment by rgonnering** [comment] 2018-05-10 01:39
Brave installation on 18.04 confirmed good.

Thanks

**Comment by bitcoinuser** [comment] 2018-10-21 14:14
Hi, I'm having this problem trying to install Brave Browser on Ubuntu 18.10:

leonardo@leonardo-Aspire-V5-471:/etc/apt/sources.list.d$ sudo apt update
Atingido:1 https://deb.opera.com/opera-stable stable InRelease                 
Atingido:2 http://security.ubuntu.com/ubuntu cosmic-security InRelease         
Atingido:3 http://archive.canonical.com/ubuntu wily InRelease                  
Atingido:4 http://ppa.launchpad.net/webupd8team/java/ubuntu cosmic InRelease   
Atingido:5 https://dl.yarnpkg.com/debian stable InRelease                      
Atingido:6 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease   
Atingido:7 http://br.archive.ubuntu.com/ubuntu cosmic InRelease                
Atingido:8 http://br.archive.ubuntu.com/ubuntu cosmic-updates InRelease        
Atingido:9 http://br.archive.ubuntu.com/ubuntu cosmic-backports InRelease      
Err:10 https://brave-browser-apt-release.s3.brave.com cosmic InRelease         
  403  Forbidden [IP: 151.101.94.217 443]
Lendo listas de pacotes... Pronto
E: Falhou ao buscar https://brave-browser-apt-release.s3.brave.com/dists/cosmic/InRelease  403  Forbidden [IP: 151.101.94.217 443]
E: The repository 'https://brave-browser-apt-release.s3.brave.com cosmic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
leonard

**Comment by iizno** [comment] 2018-10-23 07:43
Same issue here, same error on Ubuntu 18.10.

403 Forbidden on beta and release repository.

**Comment by k0pernicus** [comment] 2018-10-24 17:36
Same thing for me (Ubuntu 18.10)

**Comment by msaglietto** [comment] 2018-10-29 03:16
Hey guys...
After following the instruction on the download page I get this errors (beta and dev) on ubuntu 18.10
```
Err:10 https://brave-browser-apt-dev.s3.brave.com cosmic InRelease                                                                                                                                                             
  503  Connection timed out [IP: 151.101.134.217 443]
Err:15 https://brave-browser-apt-beta.s3.brave.com cosmic InRelease                                                   
  503  Connection timed out [IP: 151.101.134.217 443]
```

**Comment by kt1024** [comment] 2018-10-30 08:29
same issue on ubuntu 18.04. with release channel. @bsclifton

**Comment by bsclifton** [comment] 2018-10-30 15:25
Hi there folks

This code-base is deprecated; we've replaced it with "brave-core" which is what is present on https://brave.com.  The GitHub repository for this new code-base is https://github.com/brave/brave-browser

Can you please give the instructions at https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux a try and let us know how it works? Thanks 😄

**Comment by msaglietto** [comment] 2018-10-30 20:20
Thanks @bsclifton  .. sorry google search brought me here 

Those are the instructions I followed to have this problem .. should we open a new issue on brave-core ?

Also there is this cat on the instruction of development channel that I think is not need it =P
```
cat /etc/apt/sources.list.d/brave-xenial.list
```

**Comment by kt1024** [comment] 2018-10-31 02:07
@bsclifton  I'm exactly following https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux 

and I found the reason why I failed.
I'm using elementary OS 5.0 Juno(based on ubuntu 18.04), the script on 1st step will generate a file with 'juno' name,
<pre>
/etc/apt/sources.list.d/brave-browser-release-juno.list 
deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ juno main
</pre>
change 'juno' in list file to 'bionic' fix the problem.

pls consider those people using elementary OS. thanks.

**Comment by blackweta** [comment] 2018-11-01 04:12
Tried on Ubuntu 19 - and got error The repository 'https://brave-browser-apt-release.s3.brave.com cosmic InRelease' is not signed.

E: Failed to fetch https://brave-browser-apt-release.s3.brave.com/dists/cosmic/InRelease  403  Forbidden [IP: 151.101.194.217 443]
E: The repository 'https://brave-browser-apt-release.s3.brave.com cosmic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@zaphod42:~#

**Comment by avndp** [comment] 2018-11-10 03:11
Hey, I'm using Ubuntu 18.10 Cosmic, and I'm facing the same issue:

![image](https://user-images.githubusercontent.com/32923858/48296967-4492e280-e4c4-11e8-9c88-4315b010f14d.png)

I've followed these instructions: https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

Neither these worked, nor the default instructions worked. How to solve the issue?

**Comment by srirambv** [comment] 2018-11-10 03:41
@avndp https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux is for new brave-browser not for browser laptop. The instructions mentioned [here](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux) wont work for browser laptop.

**Comment by msaglietto** [comment] 2018-11-16 15:42
Since brave-browser is the main repo check  https://github.com/brave/brave-browser/issues/1981  for solutions .. there is a workaround now to try
