### ISSUE TITLE
Browser autocomplete's URL if you're typing it in manually

### ISSUE THREAD

**Issue by dginovker** [brave/browser-laptop#14633] opened 2018-07-02 18:09 UTC
### Description
Let's say one day you typed Reddit.com/r/BATproject/new'. No problem, you go back and delete the apostrophe.

But now, every single goddamn time you type "Reddit.com/r/BATProject/ne..." it auto completes to "/new'", and the bloody thing is still there! I have autocomplete turned off, but goddamn this makes me want to shoot somebody.

### GIF of feature in action

https://i.imgur.com/WcqevLX.gifv

Also I'm unsure how you add flairs/tags to the issue. Sorry bout that!

Also, here's an issue from July 2017 with the same thing: https://github.com/brave/browser-laptop/issues/9892, I dunno if you want to close and merge them but it didn't get fixed there

**Comment by bsclifton** [comment] 2018-09-07 07:35
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/9892

**Closed by bsclifton** 2018-09-07 07:35 UTC
