### ISSUE TITLE
add funds dialog shows up even if I have BAT already

### ISSUE THREAD

**Issue by Alino** [brave/browser-laptop#12078] opened 2017-11-23 11:18 UTC
## Test plan
See https://github.com/brave/browser-laptop/pull/12154

## Original issue description
v0.19.95

I got this message from time to time
![image](https://user-images.githubusercontent.com/763194/33170317-34150a46-d048-11e7-8fbe-088f5c34a5d9.png)

even though if I click on add funds button, I do have some BAT in the brave wallet
![image](https://user-images.githubusercontent.com/763194/33170350-54fd85c6-d048-11e7-8951-aa21eaa55bfc.png)

**Comment by disfit** [comment] 2017-11-28 11:28
I can confirm this behavior and am using the same version (0.19.95 on linux). For me it popped up one or two days before my contribution was due.

**Comment by disfit** [comment] 2017-11-28 19:33
Adding screenshot since it happened again as further confirmation:

![screenshot from 2017-11-28 20-12-11](https://user-images.githubusercontent.com/25134539/33340090-64af740c-d47b-11e7-8ad5-c3c1e1743c87.png)

**Comment by LaurenWags** [comment] 2017-11-30 22:35
+1 reproduced on 0.19.104 (using Staging Payments Server). Here are my steps:
Clean profile. Enabled payments. Visited some sites so that I have ledger entries. Funded wallet. Closed Brave. Updated `reconcileStamp`. Launched Brave again, waited for contribution to be made and saw this instead. 

![screen shot 2017-11-30 at 5 25 10 pm](https://user-images.githubusercontent.com/28145373/33458578-c5b1ac5a-d5f4-11e7-84e2-c991fa047bed.png)

**Comment by eljuno** [comment] 2017-12-03 21:35
+1 from community https://community.brave.com/t/bogus-account-waiting-for-a-deposit-notification/11555?u=eljuno

**Comment by Alino** [comment] 2018-01-04 10:05
this has just reoccurred to me.
version 0.19.123

**Comment by LaurenWags** [comment] 2018-01-16 22:54
This is still being reported with 0.19.134 in Community: https://community.brave.com/t/monthly-budget-tab-still-defaulting-to-25-bat/13461/7

**Comment by NejcZdovc** [comment] 2018-01-23 06:54
I can't reproduce this with steps in the PR. I will close this one and let's open a new one when we have STR.

**Closed by NejcZdovc** 2018-01-23 06:54 UTC
Labels: 0.19.x, QA/test-plan-specified, feature/ledger, initiative/bat-payments, priority/P4, release-notes/include

**Comment by Alino** [comment] 2018-08-21 09:49
this has just reoccurred to me again.

Name | Version
-- | --
Brave | 0.23.79
V8 | 6.8.275.24
rev | 51b4905
Muon | 8.0.7
OS Release | 17.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84
