### ISSUE TITLE
Brave force closed after clicking receipt link of Brave Payment

### ISSUE THREAD

**Issue by syafiqmazli-mcpayment** [brave/browser-laptop#4567] opened 2016-10-06 02:08 UTC
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

Brave force closed after clicking receipt link of Brave Payment

**Expected behavior:**

Open new dialog for download .csv file

- Platform (Win7, 8, 10? macOS? Linux distro?):

Windows 10

- Brave Version:

0.12.3 

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

![brave force closed 20160610](https://cloud.githubusercontent.com/assets/7637336/19138223/d4e7ffa0-8bac-11e6-9cb4-f0484dd0a11e.png)

- Any related issues:

**Comment by diracdeltas** [comment] 2016-10-06 03:48
duplicate of #4433

**Comment by willy-b** [comment] 2016-10-06 05:18
Installer still hasn't been updated (sha256sum beginning `2394f`) with Oct 3rd 5:30am PST release yet

**Comment by willy-b** [comment] 2016-10-06 05:22
@bbondy when will the next installer / auto-update go out?

**Comment by bbondy** [comment] 2016-10-06 16:49
we should have 0.12.4 rc1 out today, possible release tomorrow.

**Comment by diracdeltas** [comment] 2016-10-07 18:14
closing as dupe

**Closed by diracdeltas** 2016-10-07 18:14 UTC
Labels: duplicate, feature/ledger
