### ISSUE TITLE
Exit of fullscreen view when a tab is closed

### ISSUE THREAD

**Issue by romuloalves** [brave/browser-laptop#2618] opened 2016-07-20 21:15 UTC
**Describe the issue you encountered:** When I am with Brave in fullscreen view and close a tab, Brave exits of fullscreen.

**Expected behavior:** Just close the tab and don't exit of fullscreen view.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.11.1

- Steps to reproduce:
    1. Enter in fullscreen view
    2. Close a tab

**Comment by bbondy** [comment] 2016-07-21 00:07
We had the opposite request in the past. Can you describe a use case? Do any other browsers do this?

**Comment by romuloalves** [comment] 2016-07-21 01:00
I don't know if I expressed myself correctly.
I think what is happening is a problem.

I'm with Brave open in fullscreen view:
![Brave in fullscreen view](https://cloud.githubusercontent.com/assets/3952526/17008094/c0212904-4ec4-11e6-8b68-a32e6fbbd86b.png)

I just close a tab:
![Tab that will be closed](https://cloud.githubusercontent.com/assets/3952526/17008113/d7caf652-4ec4-11e6-9be3-f9520b61effa.png)

And Brave exits from fullscreen view by itself:
![Brave exists fullscreen by itself](https://cloud.githubusercontent.com/assets/3952526/17008128/ea2007e8-4ec4-11e6-8a37-70c51ceeed74.png)

No other browser has this behavior.

**Comment by molinadavid** [comment] 2016-07-21 02:10
I can confirm the same and it should be a bug, it was introduced on version 0.11.1

Brave: 0.11.1
Electron: 1.2.7
libchromiumcontent: 51.0.2704.103
V8: 5.1.281.65
Node.js: 6.1.0
Update Channel: dev

whenever you have the browser on full screen mode (distraction free) "ctrl+command+f" and close a tab from the browser the browser itself will trigger the event to go out of full screen mode and back into normal desktop mode.

The opposite is not true, if I close a tab while on desktop mode it will not enter full screen mode.

**Comment by benmosher** [comment] 2016-07-21 11:03
from #2404:

> Expected behavior:
> I expect Brave to revert into non fullscreen mode or _whatever mode I had before._

(emphasis mine)

I think the point of this new issue that closing a tab should not exit fullscreen mode unless the current tab (only) promoted the window to fullscreen. And it's not clear to me how you could even know that.

I think 8cded9c should be reverted until it can be made more targeted to apply only to #2404.

I use Brave in fullscreen (OSX, split screen with two windows) exclusively, and now I can't ever close tabs without having to drag it back to a fullscreen space. 😓

**Comment by benmosher** [comment] 2016-07-21 11:19
BTW, I can confirm that at least Opera doesn't always leave fullscreen if any tab is closed.

**Comment by bbondy** [comment] 2016-07-21 14:48
I think maybe html5 (e.g. video) fullscreen should exit full screen and full screen mode at the browser level should not.
Can someone check with how chrome works with the 2 different types of fullscreen?

**Comment by benmosher** [comment] 2016-07-21 15:00
Chrome exits fullscreen if it was prompted by YouTube, but not in normal fullscreen.

Seems like `ctrl-w` should close the tab + trigger the same event as`esc` when in a full-screen _video_. That would match Chrome and satisfy both this issue and #2404.

**Comment by bbondy** [comment] 2016-07-21 15:01
that sounds best, thanks

**Comment by JikkuJose** [comment] 2016-07-24 04:29
I am also confirming the issue. Simply closing a tab takes the browser off from full screen mode.

**Comment by bbondy** [comment] 2016-07-24 13:31
closing since this is fixed and will be in the next version.

**Comment by luixxiul** [comment] 2016-07-29 06:32
Is this only for macOS? I cannot confirm this was fixed for Windows 7

#2768

**Comment by srirambv** [comment] 2016-07-29 06:57
Issue confirmed on 0.11.2 Beta1 for Windows x64 install. Closing of any tab exits full screen and back to restore size.

**Comment by benmosher** [comment] 2016-07-29 10:51
It appears my commits are not present in the tag for v0.11.2dev-beta1: https://github.com/brave/browser-laptop/compare/v0.11.2dev-beta1...benmosher:keep-fullscreen?expand=1

I can't speak for whether they will fix Windows as well, but given the little familiarity I have now with the code, I think odds are good.

**Comment by benmosher** [comment] 2016-07-29 10:54
Actually, the commits/changes don't appear to be present on `dev-channel` anymore, either?

**Comment by benmosher** [comment] 2016-07-29 10:57
So my PR was against the `dev-channel` branch (#2631), was that wrong? did it get reset to `master` at some point?

I can rebase against wherever and resubmit if needed, commits are on `benmosher:keep-fullscreen`.

**Comment by luixxiul** [comment] 2016-07-29 11:13
I think it's merged to master, @bbondy ?

**Comment by benmosher** [comment] 2016-07-29 11:21
Changes don't appear to be present on `master`, just looking in the files. Also, [commits aren't there either](https://github.com/brave/browser-laptop/compare/master...benmosher:keep-fullscreen?expand=1).

**Comment by bbondy** [comment] 2016-07-29 14:00
Oh I didn't notice that @benmosher, I'll try to watch that in case a contributor does that again.
dev-channel is not meant for doing PRs to, it gets reset to master every release.

**Comment by bbondy** [comment] 2016-07-29 14:00
I'll pull it in now.

**Comment by bbondy** [comment] 2016-07-29 14:00
into master+dev-channel and it'll be in the next respin.

**Comment by bbondy** [comment] 2016-07-29 14:02
90dcd8ab8a4f01c54db3d5908c0994f862b0363e
af7ffb146bdcdac78d477e961f6ad646eda4d451

**Closed** 2016-07-29 14:01 UTC

**Comment by benmosher** [comment] 2016-07-29 15:04
Ah, sorry about that! 

When I based the first PR on `master` after forking from the `v0.11.1dev` tag, there were [some extra commits on `dev-channel`](https://github.com/brave/browser-laptop/pull/2630) that weren't on `master`. Will remember for next time. 😅

**Comment by bbondy** [comment] 2016-07-29 15:55
np thanks for noticing!

**Comment by kingscott** [comment] 2016-07-29 15:58
I noticed this today as well. I closed my [issue](https://github.com/brave/browser-laptop/issues/2799), but I was able to repro.

**Comment by alexwykoff** [comment] 2016-08-01 19:50
Looks good!
