### ISSUE TITLE
1px of "noise" (gap) on the by taskbar when Brave is maximized

### ISSUE THREAD

**Issue by jez9999** [brave/browser-laptop#10599] opened 2017-08-19 23:39 UTC
I'm running Windows 7; Brave 0.18.23 rev 36ae2ec.  I have a bug with Brave where it sometimes renders 1px of "noise" to the side of the browser window when I maximize it.  I have a dual-screen setup.

Steps to reproduce:
1. Drag browser window so it spans both screens.
2. Maximize the window.

Actual result:
If maximized to the left window, 1px of "noise" is rendered on the right window, and vice versa.

Expected result:
No "noise" should be rendered.

Will the steps above reproduce in a fresh profile?
Yes.

Is this an issue in the currently released version?
Yes.

Can this issue be consistently reproduced?
Yes.

Screenshot is attached.
![screenie](https://user-images.githubusercontent.com/793830/29490822-fc2fc48e-853f-11e7-8d5c-61b7ef5fe8be.png)

**Comment by luixxiul** [comment] 2017-08-20 05:48
sorry but could I know what "noise" means?

**Comment by jez9999** [comment] 2017-08-20 11:40
It's a line of vertical pixels that seem to be some kind of rendering artifact.

**Comment by luixxiul** [comment] 2017-08-20 12:43
Ah right, there is a blurred stuff on the tabs bar and the URL bar.

**Comment by bsclifton** [comment] 2017-12-27 17:08
+1 from @Alan-FGR via https://github.com/brave/browser-laptop/issues/12410
![image](https://user-images.githubusercontent.com/8399299/34385670-7a29e3e8-eb0b-11e7-89d4-3da06c22cf6c.png)

> Also, when I minimize and restore the window this happens:
![17-12-27-116](https://user-images.githubusercontent.com/8399299/34386634-c90aa574-eb10-11e7-8484-b22d807c3837.gif)

**Comment by jez9999** [comment] 2018-01-15 11:49
@bsclifton Uh, my issue was different.  The noise was to the side of the browser window, not at the bottom.

**Comment by warpdesign** [comment] 2018-04-05 14:11
I noticed the same problem:

![brave_leak](https://user-images.githubusercontent.com/199648/38371133-f7a691b2-38eb-11e8-95e6-b70331c6734b.png)

**Comment by nishay77** [comment] 2018-04-25 16:27
Is not an issue if the browser window starts maximized.  Seems like the act of maximizing a window is causing the 1px overlap to other monitors due to incorrect screen dpi/resolution detection

**Comment by nishay77** [comment] 2018-04-25 16:29
Leaving a window in "fullscreen" mode also prevents this from happening for now.  (type F11)

**Comment by jez9999** [comment] 2018-07-04 10:29
I can't believe this bug still isn't fixed, LOL.  Brendan Eich, I love you for creating JS, but I'm not using the Brave browser.  What a waste of time.

**Comment by bsclifton** [comment] 2018-08-06 19:59
This will be fixed when we move over to [Brave Core](https://github.com/brave/browser-laptop). This is(or was) also a bug in upstream electron and although I've dug into this issue, I had never found the root cause ☹️

**Closed by bsclifton** 2018-08-06 19:59 UTC
Labels: OS/Windows, bug/dpi/monitor, fixed-with-brave-core
