### ISSUE TITLE
Add support for additional mouse buttons.

### ISSUE THREAD

**Issue by gutigen** [brave/browser-laptop#7127] opened 2017-02-08 03:40 UTC
- Did you search for similar issues before submitting this one?

Yes.

- Describe the issue you encountered:

Add support for additional mouse buttons like MOUSE4 or 5. Example: pressing MOUSE4 or 5 in Chromium and many other apps calls `Go Back` and `Go Forward`.

- Platform (Win7, 8, 10? macOS? Linux distro?):

Arch Linux with GNOME 3.20 (`libinput` driver).

- Brave Version (revision SHA):

35d52c7

- Steps to reproduce:

Press MOUSE4 or MOUSE5.
   
- Actual result:

Nothing.

- Expected result:

`Go Back` and `Go Forward`

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes.

**Comment by Liunkae** [comment] 2017-02-08 22:36
Thanks for the report! This is a duplicate of #3101 (Go back/forward in browser history with mouse buttons). I'll close this issue, but you can keep track at #3101 from now on.

**Closed by Liunkae** 2017-02-08 22:36 UTC
