### ISSUE TITLE
ctrl/cmd-click should show some loading indication if the new tab is not in the current tab set

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#494] opened 2016-01-31 19:49 UTC
If you ctrl/cmd-click with a full tab group, the new tab will open in another tab group but it's not clear that anything actually happened
cc @bradleyrichter

**Comment by bbondy** [comment] 2016-02-01 12:35
I think this is a duplicate of: 
https://github.com/brave/browser-laptop/issues/358
Closing for now.

**Closed by bbondy** 2016-02-01 12:35 UTC
Labels: design
