### ISSUE TITLE
cannot see SSL certificate information

### ISSUE THREAD

**Issue by crysman** [brave/browser-laptop#7102] opened 2017-02-06 16:05 UTC
Problem:
cannot see SSL certificate detailed information

Debug Info:
Name	Version
Brave	0.13.1
rev	9dd06f9
Muon	2.0.18
libchromiumcontent	54.0.2840.100
V8	5.4.500.41
Node.js	7.0.0
Update Channel	dev
os.platform	linux
os.release	4.8.0-37-generic
os.arch	x64
(Brave installed via apt on Xubuntu Yaketty)

- Steps to reproduce:
    1. click on the lock icon by the URL
    2. try to get/read SSL certificate details
    
- Actual result:
    1. I can only see very rough info

- Expected result:
    1. detailed certificate info like Chromium or Firefox provides

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
I believe so

- Any related issues:
https://github.com/brave/browser-laptop/issues/2611

**Comment by Liunkae** [comment] 2017-02-06 20:00
This is something that is currently in the backlog of things to be fixed in the future.

Closing as duplicate of #6157 (Show more details on secure connections).

**Closed by Liunkae** 2017-02-06 20:00 UTC
