### ISSUE TITLE
I just updated to the new version of Brave, and lost nearly all tabs.

### ISSUE THREAD

**Issue by ktd99** [brave/browser-laptop#6131] opened 2016-12-10 21:16 UTC
**Did you search for similar issues before submitting this one?**  No...too news.

**Describe the issue you encountered:**  When I restarted  Brave to implement the new update, the update hung...totally white screen persisted.  I finally ended the task and restarted Brave, to find only one screen of tabs still available, with no ability to Restore my last session.

**Expected behavior:**  The update should have been installed, and my previous session restored.

- Platform (Win7, 8, 10? macOS? Linux distro?):  Win 7

- Brave Version: 0.12.14

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by ktd99** [comment] 2016-12-10 21:18
Now the system won't allow me to Edit!  Correction to Q#1:  No...too new.

**Comment by privatzee** [comment] 2016-12-12 19:37
Every time I start **since last update**, Brave wants to open Brave.exe

![image](https://cloud.githubusercontent.com/assets/22591438/21113600/3a98f598-c078-11e6-9154-c7189ed8ab5c.png)

**Comment by bsclifton** [comment] 2016-12-12 21:23
@ktd99 can you please try the work-around outlined here? https://github.com/brave/browser-laptop/issues/5512#issuecomment-266117565

If Brave crashes, it doesn't always save the final version of the session properly and we don't have an automated way to detect the save failed (so we can recover)

**Comment by bsclifton** [comment] 2016-12-12 21:32
@privatzee the issue you're seeing is captured with https://github.com/brave/browser-laptop/issues/6075

As of right now, we don't know the root cause and can use help understanding more about the problem

Can you paste a screenshot of what's in your `C:\Users\Master\AppData\Local\brave\` folder in that thread?  I am guessing you have 0.12.13 but not 0.12.14 (and the updated squirrel is confused).  The auto-updater is tied to the shortcut which you've likely pinned to the taskbar (should be pointing at update.exe)

**Comment by bsclifton** [comment] 2016-12-13 04:20
Since this issue is better captured in #5512, I'm going to close this one out.  I'm sorry this happened, @ktd99 :frowning_face:

**Closed by bsclifton** 2016-12-13 04:20 UTC
Labels: info-needed, OS/Windows
