### ISSUE TITLE
0.18.20: Cannot create a new private/session tab without an active window

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#10371] opened 2017-08-09 18:03 UTC
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
If there is no active window, you cannot create a private or session tab. The bug started occurring in Brave 0.18.20. Could it be due to #10305?

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.x

- Brave Version (revision SHA):
0.18.20 (60bb9e6)

- Steps to reproduce:
    1. Open Brave.
    2. Close the window without quitting the app.
    3. Select Menubar > New Private Tab or press Shift+Cmd/Ctrl+P.
    
- Actual result:
A new window with a normal tab is created.

- Expected result:
A new window with a private tab is created.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
No.

- Can this issue be consistently reproduced?
Yes.

**Comment by Liunkae** [comment] 2017-08-09 21:39
Likely related: #10376

**Comment by bbondy** [comment] 2017-08-10 04:20
Dupe of https://github.com/brave/browser-laptop/issues/10376

**Closed by bbondy** 2017-08-10 04:20 UTC
Labels: bug, needs-triage, release-notes/exclude
