### ISSUE TITLE
Downloads can't be resumed w/cache after browser restart

### ISSUE THREAD

**Issue by u147865** [brave/browser-laptop#12607] opened 2018-01-11 04:16 UTC
### Description
You're in the middle of a 3.4GB file download, and windows forces an auto-update, your computer reboots without much thought at all. You take a seat for a few minutes while things "get themselves ready". You load into your desktop interface, and relaunch brave. You click resume, and then the. download. starts. all. over. again. and. doesnt. resume. from. where. it. left. off. Since you live in america, the best speed you can afford is a 10Mbps connection. It left off at 65% complete when brave relaunched, but since it's started all over, you basically have to wait 16 minutes extra for this file to download because brave didn't use the existing download cache.

### Steps to Reproduce
  1. Start downloading a big file (android ROM for example)
  2. Wait until the download gets to around 90% or so, and then close the browser.
  3. Open the brave browser
  4. Click "retry" on the download
  5. Suffer.

**Actual result:**
Brave restarts the download and doesn't use the existing cache

**Expected result:**
Brave to continue the download where it left off

**Reproduces how often:**
100% of the time a download has not completed.

### Brave Version

**about:brave info:**
Name | Version
-- | --
Brave | 0.19.131
rev | da2f347
Muon | 4.5.36
libchromiumcontent | 63.0.3239.132
V8 | 6.3.292.49
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
Yes. (as of JAN 10 2018)

### Additional Information
please make sure to cache torrent downloads as well.

**Comment by srirambv** [comment] 2018-01-11 09:08
This is a dupe of #6508

**Closed by srirambv** 2018-01-11 09:08 UTC
Labels: feature/download
