### ISSUE TITLE
"Look up" dialog on macOS appears above

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10728] opened 2017-08-31 02:05 UTC
**Describe the issue you encountered:** "Look up" dialog on macOS appears above.

Brave: 0.20.0 
V8: 6.0.286.54 
rev: f4b456a16115fc879096d11d9e8c02371ecde750 
Muon: 4.4.9 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.3.5 
libchromiumcontent: 60.0.3112.101
    
- Actual result:

  <img width="500" alt="screenshot 2017-08-31 11 02 31" src="https://user-images.githubusercontent.com/3362943/29902954-2b8b5b76-8e3c-11e7-8a4d-6e718f1af781.png">

- Expected result: 

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by Liunkae** [comment] 2017-08-31 05:04
Duplicate of #8554

**Closed** 2017-08-31 05:24 UTC
Labels: bug, feature/context-menu, OS/macOS
