### ISSUE TITLE
misspellings underline

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2590] opened 2016-07-19 19:30 UTC
**Describe the issue you encountered:** underline of misspellings are cleared when focus is off

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version: 0.11.0

- Steps to reproduce:
    1. Log in to https://github.com
    2. Input random 2 words and 1 whitespace in the search box above (eg. ``testa testo``)
    3. Click anywhere outside of the box and the underlines are gone
 
Also, if you click anywhere inside of it, remove the whitespace and ``o`` and input them with a whitespace, only ``testo`` is underlined.

- Screenshot if needed:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/16963680/930ba954-4e32-11e6-9e39-1f8fe64593f5.jpg)

- Any related issues:

**Comment by Liunkae** [comment] 2016-09-20 06:32
Duplicate of #2027.

**Closed by Liunkae** 2016-09-20 06:32 UTC
Labels: bug
