### ISSUE TITLE
Brave forgets that it was maximized

### ISSUE THREAD

**Issue by jez9999** [brave/browser-laptop#11563] opened 2017-10-16 18:36 UTC
When you close a maximized Brave on Windows 7 and open again, the window is not Maximized.  It should remember.

**Comment by bsclifton** [comment] 2017-10-16 21:01
Thanks for the report, @jez9999 😄 

This has been fixed and will be in our next major release, 0.20.x (we'll have a few hotfixes before reaching that release).  I'll close this issue as a duplicate of https://github.com/brave/browser-laptop/issues/8600 (which was fixed with https://github.com/brave/browser-laptop/pull/10458)

**Closed by bsclifton** 2017-10-16 21:01 UTC
