### ISSUE TITLE
Phantom Tab appears when middle clicking on a link with `Switch to new tabs immediately`

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11070] opened 2017-09-21 16:16 UTC
### Description
Sometimes when clicking a URL link in another application (like Slack) a phantom tab appears.

### Steps to Reproduce

1. Go to `about:preferences#tabs`
2. Turn on `Switch to new tabs immediately`
3. Go to any sites in new tab
4. Middle click on any links on the page
5. Go back to the tab in step 3
6. Middle click on any links on the page

**Actual result:**
![kapture 2017-09-21 at 9 01 39](https://user-images.githubusercontent.com/28145373/30706578-c0c3c1b6-9ec6-11e7-9a66-69beee9853e4.gif)

**Expected result:**
No phantom tab.

**Reproduces how often:** 
Unsure. I have not been able to repro yet but this was reported by @darkdh 

### Brave Version

**about:brave info:**
Brave | 0.19.12
rev | 063f110
Muon | 4.4.19

**Reproducible on current live release:**
no. cannot be reproduced in 0.18.36. 

### Additional Information
See https://github.com/brave/browser-laptop/issues/11070#issuecomment-332621681
Issue seems as though it was introduced with 0.19.7 because it cannot be reproduced with 0.19.6.

**Comment by darkdh** [comment] 2017-09-26 00:32
I think it is because I have a site data contains only favicon like this
`"https://medium.com/|0|0":{"favicon":"https://cdn-static-1.medium.com/_/fp/icons/favicon-rebrand-medium.3Y6xpZ-0FSdWDnPM3hSBIA.ico"}`

**Comment by darkdh** [comment] 2017-09-27 01:24
favicon only entry is addressed in #11161

**Comment by darkdh** [comment] 2017-09-27 17:26
solid STR (reproducible on fresh profile):
1. Go to `about:preferences#tabs`
2. Turn on `Switch to new tabs immediately`
3. Go to any sites
4. Middle click on any links on the page

**Comment by bsclifton** [comment] 2017-09-27 18:41
Reproduced- this can be cause a crash if you right click the phantom tab (or drag it- anything which doesn't handle null properly).  This causes you to force quit the app

**Comment by LaurenWags** [comment] 2017-09-27 18:56
I can repro in 0.19.7 but not 0.19.6.

**Comment by darkdh** [comment] 2017-09-27 19:35
This commit is the culprit 
https://github.com/brave/browser-laptop/commit/5d38cc1b66feb74dcb32224c7b3ea7cb81c92ced

**Closed** 2017-09-28 12:51 UTC
Labels: bug, priority/P4, regression
