### ISSUE TITLE
Unable to click-select text in URL

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9872] opened 2017-07-05 14:55 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
>When I want to edit the url, I generally click at the location I want to edit the text at (or even select the portion of text), and I don't expect the whole URL to be selected.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.16.9
rev	fba98fc
Muon	4.0.3

- Steps to reproduce:
    1. Open any site in a new tab
    2. Click and release, highlights the entire URL
    3. Click/hold and move, doesn't select text retains complete URL selection
    
- Actual result:
Unable to click-select text in URL

- Expected result:
Should be able to click select a portion of URL text

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1. Same effect irrespective of system DPI 
    2.
    3.

- Screenshot if needed:
community.brave.com/t/click-in-url-bar-is-annoying/4506/3

- Any related issues:
https://community.brave.com/t/click-in-url-bar-is-annoying/4506/6

**Comment by Liunkae** [comment] 2017-07-05 16:30
Related: #7792

**Comment by bsclifton** [comment] 2017-08-16 16:39
I confirmed it does not happen on 100% DPI but does happen on 125% DPI.  I wonder if this is failing a hit test? Will be digging in more

**Comment by bsclifton** [comment] 2017-08-16 20:12
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/8472

**Closed by bsclifton** 2017-08-16 20:12 UTC
Labels: bug, bug/dpi, feature/URLbar
