### ISSUE TITLE
Going to Redflagdeals.ca results in a black screen

### ISSUE THREAD

**Issue by Tombsmen** [brave/browser-laptop#440] opened 2016-01-29 17:10 UTC
Going to Redflagdeals.ca results in a black screen, I'm not sure if this is pushing things but some times I want to do some online shopping and I'm cheap so I look at Redflagdeals.ca. If this black screen is intentional attempt to help me save money, thanks. But I'm sure it is more likely a conflict between the site and  Brave's built in advertisement blocking.

**Comment by bbondy** [comment] 2016-01-29 17:12
Check the "Bravery" main menu by hitting Alt for:
Block Tracking

vs 

Block Ads

Would be curious to see which is the cause.

**Comment by Tombsmen** [comment] 2016-01-29 18:39
You must have fixed it as it now works, or did you simply white list the site?

**Comment by Tombsmen** [comment] 2016-01-29 20:08
So I left the tab open for a bit and eventualy it went to a black page, so I then turned off Block Ads, still goes to a black page. Then I turned off Ad replacement Engine, still after a few seconds black out page.   After which I turned of Block Tracking, still after a few second completely black page. I have been closing the tab between attempts and leaving each feature disabled untill the end.

**Comment by luixxiul** [comment] 2016-05-14 17:17
Not reproducible on the latest version. Closing for the moment.

**Closed by luixxiul** 2016-05-14 17:17 UTC
