### ISSUE TITLE
"Check for Updates..." on Debian appears non-functional

### ISSUE THREAD

**Issue by keverets** [brave/browser-laptop#6136] opened 2016-12-11 11:37 UTC
Running brave 0.12.9-1, from the Hamburger menu, "Help -> Check for Updates..."  creates a status bar that says "Not yet! Sorry, there are no updates yet. Please check back soon." However, visiting https://brave.com/downloads.html and following the "Download Brave for Debian/Ubuntu" button (through the opaque https://laptop-updates.brave.com/latest/debian64 link) downloads brave_0.12.14_amd64.deb.

I would expect that the "Check for Updates..." menu item would provide information that a new version of brave is available (and a link to download it, if it is not auto-updating).

- Platform (Win7, 8, 10? macOS? Linux distro?):
Debian stable

- Brave Version:
0.12.9

- Steps to reproduce:
    1. Hamburger menu, Help, About Brave (note that 0.12.9 is listed)
    2. Hamburger menu, Help, Check for Updates..." (note the "Not yet!" bar appears)
    3. Verify that a new version does in fact exist.

**Comment by Liunkae** [comment] 2016-12-12 18:14
BTW, a repo was set up recently (https://github.com/brave/browser-laptop/issues/1170#issuecomment-262835161). See the updated instructions [here](https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md).

I'll close this particular issue as a duplicate of #1470.

**Closed by Liunkae** 2016-12-12 18:14 UTC
