### ISSUE TITLE
[OSX] How to dock the dev tools ?

### ISSUE THREAD

**Issue by bogas04** [brave/browser-laptop#1173] opened 2016-03-25 08:42 UTC
I don't own a large screen so docking makes sense on my laptop. Is it possible to do that with brave? 

Being so lightweight and being backed by chromium, brave also becomes a great browser for debugging purposes!

**Comment by rahilwazir** [comment] 2016-03-25 10:28
@bogas04 It has option to dock just like the Chrome browser, make sure you are using the latest version.

**Comment by bogas04** [comment] 2016-03-25 10:30
Am I missing something? Chrome has it next to 3 dots AFAIK 
![screen shot 2016-03-25 at 3 59 30 pm](https://cloud.githubusercontent.com/assets/6177621/14042715/986b25a0-f2a2-11e5-83e0-1a14427bdd85.png)

**Comment by rahilwazir** [comment] 2016-03-25 10:49
I'm guessing you are using Mac? Not sure about that though but at least on Windows you can see:

![brave](https://cloud.githubusercontent.com/assets/1818941/14042975/05597b28-f2a1-11e5-91ff-b014828eb24d.jpg)

**Comment by bogas04** [comment] 2016-03-25 10:50
In that case it might be OS dependent!

**Comment by rahilwazir** [comment] 2016-03-25 17:48
FWIW, Linux has dock support too :)

**Comment by weems** [comment] 2016-03-25 23:34
is it possible nix and Windows support docking dev tools, but for some reason OSX does not?

**Comment by bbondy** [comment] 2016-03-26 02:18
What's happening here is you are talking about 2 different types of dev tools.

The one that can currently be docked  (CommandOrControl + Alt + J) is the browser level dev tools. You can use it to debug the actual browser.

The one that cannot currently be docked (CommandOrControl + Alt + I) is the content level dev tools. You can use it to debug webpages you are visiting.

Being able to dock the content level dev tools is a dupe of:
https://github.com/brave/browser-laptop/issues/688

**Closed by bbondy** 2016-03-26 02:18 UTC

**Comment by dwcdev** [comment] 2016-07-05 23:56
@rahilwazir - how did you dock with Linux?  I don't have the dock option (or I can't seem to find it).

**Comment by bsclifton** [comment] 2016-07-06 00:32
@dwcdev like @bbondy mentioned, there are two kinds of dev tools.  The first one (which is dockable) is basically the dev tools that are part of chromium- used for debugging the electron app. The end-user dev tools are not dockable at this time (but you can follow https://github.com/brave/browser-laptop/issues/688 to get notifications when it is)
