### ISSUE TITLE
Task Bar Settings (Hamburger) Icon Broken

### ISSUE THREAD

**Issue by karthicks** [brave/browser-laptop#363] opened 2016-01-27 18:20 UTC
Click on the hamburger icon on the right hand side of the task bar, anytime, anywhere you're in brave. Nothing happens. I was hoping to see a settings menu or something along those lines.

**Comment by damengilland** [comment] 2016-01-27 19:23
Duplicate of #310

**Comment by trouserless** [comment] 2016-01-27 21:13
additionally, navigating through the menus to preferences (Brave->Preferences) is greyed out and therefore non-selectable.  Nor is the keyboard shortcut working as referenced by #366 

tldr; no way to see/edit preferences.

**Comment by diracdeltas** [comment] 2016-01-28 19:42
As mentioned in #366, we don't have a preferences menu yet. Closing this as a dupe of #310 and #366.

**Closed by diracdeltas** 2016-01-28 19:42 UTC

**Comment by bbondy** [comment] 2016-01-28 20:23
Fixed in 0.7.10 (which is available now)
