### ISSUE TITLE
Brave is not launching with Home Page address

### ISSUE THREAD

**Issue by Brave-Matt** [brave/browser-laptop#15125] opened 2018-08-29 23:20 UTC
**Did you I look for similar issues?**
Yes

### Description

When settings are configured to start brave with home page, Brave starts with about:blank instead.
Home button on URL bar _does_ route to proper address but opening a new window will also open with about:blank

### Steps to Reproduce
1. Fresh install (ideally, I don't think it matters) of Brave *.104/105
2. Open Settings
3. In "General" settings, change  **Brave Starts with** --> **Homepage**
4. Ensure there is _some_ URL in *My Homepage Is* input box
5 (*optional). Add "Home button" to URL bar.
6. Close/reopen
**Actual**: Brave opens about:blank (*goes to Home page when Home button on URL is clicked)

**Expected**: Brave opens to homepage specified in Settings (*goes to Home page when Home button on URL is clicked)

**Reproduces how often:**

Consistently

### Brave Version

**about:brave info:**
Present on 0.23.104, 0.23.105
Tested on Windows 7 and Windows 10, MacOS (waiting on user info to confirm exact OS)
-->
**Reproducible on current live release:**
<!--
Yes

### Additional Information
The issue isn't present on 0.23.79, homepage opens on launch.

**Comment by bsclifton** [comment] 2018-08-29 23:51
Having trouble reproducing this... I tried on macOS and Windows (both the actual 0.23.104 release and building a binary from 0.23.x source)

**Comment by kjozwiak** [comment] 2018-08-30 00:41
Can't seem to reproduce this either on a clean `0.23.105` install. @Brave-Matt does this always reproduce for you on a clean profile?

**Comment by Brave-Matt** [comment] 2018-08-30 02:15
Possibly related : https://community.brave.com/t/cant-connect-online-through-email-links/30999
https://community.brave.com/t/cant-connect-online-through-email-links/30999

**Comment by kjozwiak** [comment] 2018-08-30 02:33
@Brave-Matt does this always reproduce for you on a clean profile?

**Comment by bsclifton** [comment] 2018-08-30 05:07
Possibly caused by https://github.com/brave/browser-laptop/pull/15047

**Comment by eljuno** [comment] 2018-08-30 16:40
+1 from community https://community.brave.com/t/browser-loading-about-blank-on-startup-while-homepage-is-selected/31087?u=eljuno

**Comment by diracdeltas** [comment] 2018-09-13 20:29
I think this was fixed by https://github.com/brave/browser-laptop/pull/15194

cc @bsclifton

**Closed as completed** 2018-09-13 22:24 UTC
Labels: bug, QA/test-plan-specified, QA/checked-macOS, QA/checked-Win64, QA/checked-Linux, regression, release-notes/include

**Comment by LaurenWags** [comment] 2018-09-14 14:15
Verified with macOS 10.12.6 using
* 0.23.206 80a5ac1
* Muon 8.1.5
* libchromiumcontent 69.0.3497.92

**Comment by kjozwiak** [comment] 2018-09-18 04:18
@btlechowski can you please check this against linux? Thanks!
