### ISSUE TITLE
The system cannot find message text for message number 0x%1 in the message file for %2.

### ISSUE THREAD

**Issue by caofb** [brave/browser-laptop#350] opened 2016-01-27 02:19 UTC
App threw an error when running [Error: The system cannot find message text for
message number 0x%1 in the message file for %2.
\?\E:\SourceCode\browser-laptop\node_modules\sqlite3\lib\binding\node-v47-win32
-x64\node_sqlite3.node]

**Comment by bbondy** [comment] 2016-01-27 03:52
Likely you need node 5.5, and delete your node_modules, then npm install.

**Comment by caofb** [comment] 2016-01-27 07:59
@bbondy update to node 5.5 didn't solve the problem

**Comment by bbondy** [comment] 2016-01-27 11:51
Which version of visual studio (and service pack) are you using?

**Comment by AlienHack** [comment] 2016-01-27 12:57
I got the same problem, 

using Visual Studio 2015 Update 1, Windows 7 64 bit Professional SP1

App threw an error when running [Error: The system cannot find message text for
message number 0x%1 in the message file for %2.
\\?\E:\Brave\browser-laptop\node_modules\sqlite3\lib\binding\node-v47-win32-x64\
node_sqlite3.node]

**Comment by AlienHack** [comment] 2016-01-27 12:59
Here is the error message by running npm start

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\E:\Brave\browser-laptop\node_modules\sqlite3\lib\binding\node-v47-win32-x64\node_sqlite3.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:153:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:153:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (E:\Brave\browser-laptop\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:425:26)

[OK]

**Comment by Chtewa** [comment] 2016-01-27 14:28
Hi,
I got the same problem, and I fixed it by adding "C:\Python27" in the path variable in the environment variables. and delete the node_modules, then npm install.

**Comment by AlienHack** [comment] 2016-01-27 14:39
@Chtewa Haha, I was just looking into the error detail after npm install failed and found that the command python was not found. Going to post the solution here but you already posted. :+1:

**Comment by AlienHack** [comment] 2016-01-27 15:17
After adding the environment variable, and npm install, the problem is still persisted

![image](https://cloud.githubusercontent.com/assets/8213866/12617791/ced97592-c543-11e5-8477-82c1128adbc6.png)

**Comment by AlienHack** [comment] 2016-01-27 15:37
![image](https://cloud.githubusercontent.com/assets/8213866/12618449/79b12490-c546-11e5-8665-0c5a2fbfdb79.png)

Got new issue

**Comment by Chtewa** [comment] 2016-01-27 15:44
@AlienHack for this we should wait for the fix, look at #189.

**Comment by diracdeltas** [comment] 2016-02-24 23:53
Is this fixed now in 0.7.16 since we got rid of sqlite3?

**Comment by prkeshri** [comment] 2016-05-11 06:35
This is happening with tracking-protection.

[Content]
Uncaught Exception:
Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\C:\win\browser-laptop\node_modules\tracking-protection\build\Release\tp_node_addon.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\win\browser-laptop\app\trackingProtection.js:8:28)
    at Module._compile (module.js:413:34)

Any solution?

What I am using is:
Node. v6.1.0
VS-2013

**Comment by bbondy** [comment] 2016-05-11 06:36
this happens if you compile a node native module as 32-bit and try to run it n 64-bit. The reverse is probably true as well.

**Comment by prkeshri** [comment] 2016-05-11 08:00
But the tracking-protection is compiled for the same arch. (32-bit) only. Same is the case with abp-parser-cpp too! Any solution?

**Comment by woodev01** [comment] 2016-09-19 19:00
I've just had this same error message using node-usb. I am running windows 7 with 64bit arch. If bbondy is correct, is there any way around this issue?

**Comment by mamiu** [comment] 2016-09-22 14:58
Same error on windows 7 64bit.
Any suggestions?

**Comment by ganeshdevkate** [comment] 2016-09-23 04:27
Same error on windows 10 64 bit.
is it related to npm install?
I am using Golang.

**Comment by bsclifton** [comment] 2016-11-09 21:24
Updated labels based on issue (since this is relating to running from source, not the packaged build)

**Comment by luixxiul** [comment] 2017-11-07 12:59
Closing as stale. Let's reopen if we still experience the issue 👍

**Closed by luixxiul** 2017-11-07 12:59 UTC
Labels: dev-setup, needs-info
