### ISSUE TITLE
Memory leak makes RAM utilization close to 4GB

### ISSUE THREAD

**Issue by unsystemizer** [brave/browser-laptop#5311] opened 2016-11-01 11:05 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Brave leaks memory at https://chain.so/

**Expected behavior:**
Memory usage remain consistent

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10 x64

- Brave Version:
0.12.7

- Steps to reproduce:
    1. Close down all tabs but one, visit https://chain.so/ 
    2. Restart Brave
    3. Initially it will consume < 200 MB. Few hours later, 400 MB. I left it overnight and it got to 3,900 MB (one process) with 2-3 other processes of about 50-70 MB each.

- Any related issues:
https://github.com/brave/browser-laptop/issues/3836#issuecomment-246015532

**Comment by privatzee** [comment] 2016-11-01 14:16
Nice find, @unsystemizer.

What I'm seeing via a short test ~1hr in w7x64 is that two active renderers are mostly doing the growing. The main (pid 8896 below) is doing all the net I/O to the linode server and is not growing.

![image](https://cloud.githubusercontent.com/assets/22591438/19892516/9cfbd1b0-a01b-11e6-82a3-58a5ca255d53.png)

**Comment by privatzee** [comment] 2016-11-01 15:30
Nice find, @unsystemizer 

On a short w7x64 test: that one active renderer accounts for most of the growing, while the main (pid 6744 below) doesn't grow. There seems to be only one socket for all the xhr. There is no Service Worker.

On Brave startup with only the chain.so tab (and the main thread is selected):

![image](https://cloud.githubusercontent.com/assets/22591438/19894288/d2ca86b8-a022-11e6-842f-cdd0876e6854.png)


After 1/2 hr:

![image](https://cloud.githubusercontent.com/assets/22591438/19894305/e4d814ce-a022-11e6-91f9-0d58cc9a995c.png)


P.S.: if it helps, any associated devtools grows about the same as the underlying renderer.

/cc @bridiver

**Comment by privatzee** [comment] 2016-11-01 15:46
Well this is unexpected, after 1 hr total the renderer has decreased.

![image](https://cloud.githubusercontent.com/assets/22591438/19895720/3a787f5e-a028-11e6-87a4-49605f6a6d0f.png)

And... before I posted this comment the memory jumped back up to 240MB, so you have to be careful about when you sample this.

**Comment by privatzee** [comment] 2016-11-01 19:53
Something to do with MozWebSocket ?

**Comment by privatzee** [comment] 2016-11-04 14:54
If anybody wants to someday do local testing, here is an active nodejs package:
https://github.com/websockets/ws

**Comment by bridiver** [comment] 2016-11-04 17:35
a few hundred MB is normal for Brave and Chrome, but 4GB for one process is not unless the page itself has a memory leak. Does this only happen on Brave and not on Chrome?

**Comment by unsystemizer** [comment] 2016-11-04 19:12
With just that chain.so tab open, Chrome holds steady at (only) 35 MB (2 hours now).

**Comment by privatzee** [comment] 2016-11-11 17:01
Before I forget: that 4GB figure is no accident. According to Process Explorer, that's the max memory usage for Brave renderers.

![image](https://cloud.githubusercontent.com/assets/22591438/20222972/54479a98-a805-11e6-9707-08e44dbb79dc.png)


---
There is no limit set for the main process.

---
Also, I set up a test and ran 200,000 WebSocket messages back and forth through Brave and a plain http WebSocket Server. It took 1-2 minutes, there was no big increase in memory usage in Brave.

---
The chain.so site doesn't seem to have been functioning lately?

**Comment by bridiver** [comment] 2016-11-11 18:07
a Chrome renderer is only using 35MB? Are you sure you're looking at the renderer process? I see higher than that for a blank page. There are substantial changes coming with chromium 54 which should be ready soon

**Comment by unsystemizer** [comment] 2016-11-11 19:48
I have 1 tab and that's all I can see in Task Manager 
![image](https://cloud.githubusercontent.com/assets/13134193/20228046/6fe9f96e-a88a-11e6-9400-631acf71af70.png)

**Comment by bridiver** [comment] 2016-11-11 19:57
Chrome will always have at least two processes running (more in most cases). There will be a browser process and at least one renderer process. I'm not that familiar with task manager, but it looks like it's displaying the browser process pid and memory and not displaying the child renderer process. It looks like process explorer splits them out

**Comment by unsystemizer** [comment] 2016-11-11 20:45
I was hoping I'm not the only guy who has Chrome installed, but I was wrong :-) 
Okay so I downloaded Process Explorer and captured its output. So yes, there's more to it: this is Chrome Version `54.0.2840.87 m` with 1 tab on the site https://chain.so/. 
![image](https://cloud.githubusercontent.com/assets/13134193/20229622/7ca01578-a892-11e6-9eda-77ec8d4c4e96.png)

 (I reported the high memory utilization of Brave using Windows 10 Task Manager, so I reported Chrome's utilization the same way.)

**Comment by luixxiul** [comment] 2017-11-05 19:54
I'm going to close this in favor of https://github.com/brave/browser-laptop/issues/3836 😄 

Let's reopen if this issue is still reproduced -> "it got to 3,900 MB (one process)".

**Closed by luixxiul** 2017-11-05 19:54 UTC
Labels: perf
