### ISSUE TITLE
Favicons are displayed without image

### ISSUE THREAD

**Issue by comodoro** [brave/browser-laptop#12996] opened 2018-02-02 17:26 UTC
After install and importing bookmarks from Chrome everything imported correctly, but favicons have been the generic grey sheets without image. This is on the bookmarks toolbar as well as the bookmarks menu. 

Current Brave 0.20.30, Windows 10.

![image](https://user-images.githubusercontent.com/925466/35745886-1b5985c4-0845-11e8-8712-f3bdb7d3ea93.png)

**Comment by eljuno** [comment] 2018-02-02 20:46
Duplicate of #11203?

**Comment by comodoro** [comment] 2018-02-03 06:45
Definitely not, this is the one I have looked at. In #11203 favicons are
not displayed at all, while I have them as the grey generic images. Might
be related to #7133 though.

Dne 2. 2. 2018 9:47 odpoledne napsal uživatel "Eljuno Kasih" <
notifications@github.com>:

Duplicate of #11203 <https://github.com/brave/browser-laptop/issues/11203>?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/brave/browser-laptop/issues/12996#issuecomment-362702635>,
or mute the thread

**Comment by bsclifton** [comment] 2018-05-01 06:47
@comodoro I strongly believe this issue is the same as https://github.com/brave/browser-laptop/issues/11203 (good catch, @eljuno!) so I'm going to close as a duplicate

In the screenshot in https://github.com/brave/browser-laptop/issues/11203, the icons aren't showing in the bookmarks toolbar (which is the default setting, matching Safari behavior).  However, @LaurenWags had enabled that, you'd see the empty document icon.  The history page (shown) uses the same icon, which is also that empty document icon

The icon should populate after visiting the bookmark once, but losing that icon isn't ideal

**Closed by bsclifton** 2018-05-01 06:47 UTC
