### ISSUE TITLE
Browser crashes when trying to login to GitHub

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9138] opened 2017-05-30 13:57 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Browser crashes when trying to login to GitHub

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.16.0
rev	be76cd3
Muon	3.2.101

- Steps to reproduce:
    1. Clean install 0.16.0
    2. Open github.com/signin
    3. Enter User ID/Password and click signin browser crashes
    
- Actual result:
Browser crashes when trying to login to GitHub

- Expected result:
Should not crash

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Having pinned tabs doesn't crash but only causes webview crash
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment] 2017-05-30 18:23
Disabling password manager doesn't causes the crash when signing into GitHub.

**Comment by darkdh** [comment] 2017-05-30 20:37
hmm, I can't reproduce even with built-in password manager enabled

**Comment by srirambv** [comment] 2017-05-31 15:00
Unable to reproduce the issue after upgrade from 0.15.310 or clean install on 0.16.0. Closing the issue for now. Will reopen if I can get reliable STR.

Closing #9138

**Comment by srirambv** [comment] 2017-06-09 15:20
Reopening the issue based on community thread https://community.brave.com/t/typing-password-makes-brave-crash/3702/

cc: @darkdh

**Comment by bsclifton** [comment] 2017-06-09 15:25
possibly related: https://github.com/brave/browser-laptop/issues/9356

**Comment by alexwykoff** [comment] 2017-06-11 05:58
Closing this issue as all reports thus far have shown the crash to be gone.

**Comment by frk2** [comment] 2017-06-11 21:10
I'm still experiencing this crash on Ubuntu 17.04 with brave 0.16.9 rev fba98fc. Let me know how I can help?

**Comment by luixxiul** [comment] 2017-06-12 02:37
Re-opening just in case.

**Comment by alexwykoff** [comment] 2017-06-16 05:30
It seems as though another Linux user is experiencing login issues as well : https://community.brave.com/t/bug-report-login-crashes-brave/3947

**Comment by lundsted** [comment] 2017-06-16 07:25
> It seems as though another Linux user is experiencing login issues as well : 

Linux user here, also experiencing this issue, fx with Facebook.

**Comment by frk2** [comment] 2017-06-21 14:05
Seems like this is such is now fixed with the latest update!

**Comment by bsclifton** [comment] 2017-06-21 16:19
@frk2 that is correct- we have fixed this with our latest release 😄  Menus on Gnome are still broken (we're working on a hot-fix for that)

The root cause was: 0.16.9 shipped with Muon version 4.0.2 instead of 4.0.3 because of a build problem (the fix for login happened in 4.0.3). 

Closing as this issue is now resolved

**Closed by bsclifton** 2017-06-21 16:19 UTC
Labels: bug, cr59, crash, needs investigation

**Comment by luixxiul** [comment] 2017-06-21 16:29
@srirambv @LaurenWags @alexwykoff please test the issue was fixed.
