### ISSUE TITLE
Arrow should not be allowed to drag and drop on Brave Payments BAT logo page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14274] opened 2018-05-30 12:44 UTC
### Description
Arrow should not be allowed to drag and drop on Brave Payments BAT logo page

### Steps to Reproduce

1. Drag and drop the arrow
2. Verify Arrow can be drag and drop

**Actual result:**

After  drag and drop of Arrow (->), 'Hmm..not quite Please try again' message is   displayed

![arrow drag and drop issue](https://user-images.githubusercontent.com/38657976/40723284-315d6c3e-643c-11e8-924e-80130c908896.gif)

**Expected result:**

Arrow   should not be drag and dropped and message should be displayed only for BAT   logo drag and drop

**Reproduces how often:**
100%

### Brave Version
0.22.723

**about:brave info:**

Brave | 0.22.723
V8 | 6.6.346.32
rev | edb3e88
Muon | 6.0.12
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.170

**Reproducible on current live release:**

**Comment by GeetaSarvadnya** [comment] 2018-05-30 12:47
![arrow drag and drop issue](https://user-images.githubusercontent.com/38657976/40720836-a386c226-6435-11e8-9224-fb9ba1ecd425.gif)

**Comment by srirambv** [comment] 2018-05-30 13:00
Drag and drop arrow sometimes allow to claim the grant (Please watch the full recording its at the end)
![captcha arrow](https://user-images.githubusercontent.com/17010094/40721589-e5f2c8f6-63e7-11e8-887b-8b6ef23c89aa.gif)

**Comment by srirambv** [comment] 2018-05-31 21:38
![drag arrow](https://user-images.githubusercontent.com/17010094/40809679-4b79bb14-64f9-11e8-86f3-85e821cf4cd7.gif)

Really hard to drag and drop on the target because of the arrow is also dragged.

**Comment by NejcZdovc** [comment] 2018-06-01 09:03
@srirambv can't reproduce it on windows 

```
Brave: 0.22.725 
V8: 6.6.346.32 
rev: e6dd17f1f9a6bf52dfcee059d6dac3f92197849b 
Muon: 6.0.12 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170
```

**Comment by GeetaSarvadnya** [comment] 2018-06-01 09:46
@NejcZdovc @srirambv Retested on new build, Issue fixed now on 725 build.

**Comment by NejcZdovc** [comment] 2018-06-01 10:49
closing issue based on @GeetaSarvadnya comment

**Closed** 2018-06-01 10:48 UTC
Labels: QA/checked-Win64, QA/test-plan-specified, bug, feature/rewards, release-notes/exclude
