### ISSUE TITLE
Unable to create wallet when payments is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7464] opened 2017-03-02 22:37 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Unable to create wallet when payments is enabled

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	84e45bd

- Steps to reproduce:
    1. Do a clean install of 0.13.5 RC2
    2. Enable payments from preference
    3. Wallet is not created
    
- Actual result:
Wallet creation fails on 0.13.5 RC2

- Expected result:
Should create wallet

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/23530147/6ffe71fe-ff98-11e6-983e-b4d40084ed25.png)
![image](https://cloud.githubusercontent.com/assets/17010094/23530177/89be58de-ff98-11e6-9c0d-c6a8156bcd29.png)

- Any related issues:
cc: @mrose17 @cezaraugusto

**Comment by bsclifton** [comment] 2017-03-03 00:34
Should be fixed with https://github.com/brave/browser-laptop/commit/a3de55a927b6c27f4223daa2cbeb06ed9ea0da29

**Comment by bsclifton** [comment] 2017-03-03 00:38
Confirmed fix on my Win10 VM 👍  Since update is already merged I'll close this out

**Closed by bsclifton** 2017-03-03 00:38 UTC
Labels: bug, feature/ledger, QA/steps-specified, regression

**Comment by srirambv** [comment] 2017-03-03 07:58
Working on 0.13.5 RC3
