### ISSUE TITLE
Opening Brave while offline invalidate all open tab URLs (replacing with about:error)

### ISSUE THREAD

**Issue by kolipka** [brave/browser-laptop#10042] opened 2017-07-18 21:11 UTC
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
I have not stable internet connection. When it is lost, tab will display about:error with DNS problem. When I close Brave and open again, original tab URL is lost, and replaced with about:error. This is especially problematic when I have a lot of tabs and those are rendered for preview when no connection. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win10

- Brave Version (revision SHA):
0.17.16 / 2d2ee2f

- Steps to reproduce:
    1. disable internet connection
    2. in Brave open new tab with page, eg.: brave.com (about:error will be displayed)
    3. close Brave
    4. enable internet connection
    5. open Brave
    
- Actual result:
original brave.com URL will be lost, empty about:error will be present

- Expected result:
Brave retry to open original URL - brave.com in above example

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by kolipka** [comment] 2017-07-18 21:12
As a side note: awesome product :) Keep up the good work!

**Comment by bsclifton** [comment] 2017-07-19 21:25
@kolipka thanks for the report (and super glad you like the browser 😄 )

@bridiver @diracdeltas I've noticed this issue a few times also... I seem to remember that we were going to fix about:error pages so they retain their URL.  Do you have some more information?

BTW- I marked as `priority/high` since this does cause loss of data (which is bad)

**Comment by bsclifton** [comment] 2017-07-19 21:27
Related / possible duplicate of: https://github.com/brave/browser-laptop/issues/8996, https://github.com/brave/browser-laptop/issues/2302, https://github.com/brave/browser-laptop/issues/2025

**Comment by LaurenWags** [comment] 2017-12-19 19:31
+1 from twitter: https://twitter.com/G_Sapia_Ruffin/status/942942031902662656

**Comment by eljuno** [comment] 2018-06-27 19:02
+1 from community https://community.brave.com/t/tabs-not-saved-between-sessions/26348?u=eljuno

**Comment by tanev** [comment] 2018-08-23 07:10
+1 from me as well, just reproduced, actually came here to report, but found this bug report.

**Comment by bsclifton** [comment] 2018-08-23 21:25
I just tried a few scenarios using [brave-core](https://github.com/brave/brave-browser) and verified that it works as expected 😄 The URLs stay intact and once connectivity is restored, they load

Closing for our current product as `wontfix` since this is already addressed in brave-core

**Closed by bsclifton** 2018-08-23 21:25 UTC
Labels: fixed-with-brave-core, initiative/reduce-bugs, priority/P2, product/user-happiness
