### ISSUE TITLE
Right clicking tab being previewed causes focus to change

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7327] opened 2017-02-20 16:21 UTC
## Test plan
1. Open two tabs. Set focus to tab 2
2. Right click tab 1 and verify context menu appears
3. Press ESC (if your keyboard has it 🤣  )
4. verify menu closes and focus did NOT change
5. Right click tab 1 so that context menu appears
6. Right click another place in tab 1 so that the context menu closes then reopens
7. Verify focus did NOT change
8. Push ESC and verify menu closes / focus did not change

**Comment by Jacalz** [comment] 2017-02-20 16:26
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Having 2 or more tabs and hovering over the first tab and right clicking on it and then pressing "Escape" on the keyboard switches you to the tab you right clicked.
- Platform (Win7, 8, 10? macOS? Linux distro?):
I found it working on Windows 10 pro on two different pc:s and it and this only seems to be a problem on windows because i could not reproduce it on MacOS Sierra. Linux i don´t know...
- Brave Version (revision SHA):
0.13.4
- Steps to reproduce:
    1. Open 2 or more tabs with different websites (Doesent matter how many)
    2. Make sure you are in the second tab
    3. Hover over the first tab and right click on it
    4. Press "Esc" on your keyboard and you are sudenly on the first tab
    
- Actual result:
You are on the first tab after pressing "Esc"
- Expected result:
You should be left on the second tab
- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Jacalz** [comment] 2017-02-20 16:29
It would be great if you assigned me to this issue :D

**Comment by bsclifton** [comment] 2017-02-20 17:01
@Jacalz the issue is yours if you'd like it 😄   Let me know and I'll self-assign it (to reserve it)

**Comment by Jacalz** [comment] 2017-02-20 17:12
Oh, I really didnt mean it the way i wrote it, thats why i removed the comment. :sweat: What I meant what that i should be able to edit the text not fix the issue :sweat_smile: But i can do without that :+1:

**Comment by bsclifton** [comment] 2017-02-20 17:13
@Jacalz ah ok- no problem 😄  understood.  Please do update the text to be as accurate and easy to understand as you'd like 😄  Thanks!

**Comment by Jacalz** [comment] 2017-02-20 17:16
@bsclifton Can you try this out also to comfirm it working?

**Comment by bsclifton** [comment] 2017-05-12 05:58
Closing as I can't reproduce on latest build.  @Jacalz can you please retest to make sure I didn't misunderstand the steps?

**Comment by Jacalz** [comment] 2017-05-12 06:18
Will see later today 😉

**Comment by Jacalz** [comment] 2017-05-12 15:26
Still an issue: @bsclifton 
1. Open two tabs
2. Right click on the tab that isn´t in focus so the context menu apears
3. Press Esc, it switches to the tab that wasn´t in focus...

**Comment by bsclifton** [comment] 2017-05-12 15:45
@Jacalz are you on Windows?

**Comment by Jacalz** [comment] 2017-05-12 16:12
I am on Windows 10 and I tested on 0.15.303 because npm run watch fails on the latest master 😬

**Closed** 2017-06-13 03:54 UTC
Labels: bug, feature/tabsbar, polish
