### ISSUE TITLE
Multiple issue with top tiles removal in new tab page

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12568] opened 2018-01-09 11:03 UTC
### Description
Multiple issue with top tiles in new tab page
1. Pinned tile cannot be closed without unpinning it first
2. Unpinning a tile and closing it doesn't close but show the restore message
3. Closing a different tile after unpinning the pinned tile causes the previous tile to be removed

### Steps to Reproduce
Scenario  1  & 2
   1. Clean install 0.20.16 
   2. Click on remove button on the pinned tile, nothing happens, message is shown that its removed but tile is still retained
   3. Close browser and restart, tile is still present

Scenario 3
   1. Clean install 0.20.16 
   2. Unpin the pinned tile and close the tile nothing happens
   3. Remove the second tile next to the unpinned tile, removes the pinned tile which was unpinned
   4. Remove the third tile, removes the second tile (which is now the first tile)

Scenario 4
   1. Clean install 0.20.16 
   2. Remove all tiles and on the notification click `Restore all tiles`, nothing is restored
   3. Close browser and restart, all tiles are restored

**Actual result:**
![pinnedtile](https://user-images.githubusercontent.com/17010094/34717552-809873f4-f559-11e7-9719-935aa8ee8ffd.gif)

**Expected result:**
1. Should be able to close the pinned tile without having to unpin
2. Unpinning a tile and removing it should remove the tile instantly
3. Close should remove the tile on which the close button is clicked
4. Clicking on restore all tile should immediately restore the tiles and not wait for browser restart

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.16
-- | --
V8 | 6.3.292.49
rev | 0c42d0b
Muon | 4.5.36
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 63.0.3239.132

**Reproducible on current live release:**
No

### Additional Information
Even after clicking the remove tile button and waiting for ~10secs the pinned tile isn't removed. Same after browser restart. Unpinned tiles doesn't get removed until browser restart.
Found while testing https://github.com/brave/browser-laptop/pull/12470 for top tiles
cc: @kjozwiak @LaurenWags @bsclifton

**Comment by bsclifton** [comment] 2018-01-11 22:45
Closing as a dupe of https://github.com/brave/browser-laptop/issues/10411

**Closed by bsclifton** 2018-01-11 22:45 UTC
Labels: 0.20.x, bug, feature/newtab, feature/topsites, priority/P4, regression
