### ISSUE TITLE
Brave can't edit cells in Google Sheets on Mac

### ISSUE THREAD

**Issue by thepup** [brave/browser-laptop#607] opened 2016-02-04 08:15 UTC
I could not edit or even select cells in a Google Sheet when using Brave on Mac. I could select the text _in_ cells, as if it was one big text file, but nothing else.

**Comment by bbondy** [comment] 2016-02-04 11:44
I think this is a dupe of #402 and should be fixed in the next update.

**Comment by bbondy** [comment] 2016-02-07 04:21
Fixed in 0.7.13 which will be coming out soon.

**Closed by bbondy** 2016-02-07 04:21 UTC
