### ISSUE TITLE
"Print" button on Google Calendar opens a new window throwing an error

### ISSUE THREAD

**Issue by SilverPuppy** [brave/browser-laptop#5688] opened 2016-11-16 18:17 UTC
**Describe the issue you encountered:** "Print" button on the Google Calender does not work. Here is the output on devtool:

````
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT static/3ed9ce8af0e9c1d0d763a066f187eef8doozercompiled_vr.css
static/3ed9ce8af0e9c1d0d763a066f187eef8delayloadedcompiled_vr.css Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
rs=ANwU0p4awk1Fr2euocPjD7MmSbo1y621WA Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
render:3 Uncaught ReferenceError: gcal is not defined
    at initPrintDialog (render:3)
    at onload (render#main_7:1)
````

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.14.1

- Steps to reproduce:
    1. Visit https://calendar.google.com
    2. Click "More" 
    3. Select "Print"
    
- Actual result: The new window with print preview is opened with no preview and infinite loading. The URL on the URL bar is ``about:blank``. Disabling the shield does not work.

- Expected result: The preview should be displayed

- Is this an issue in the currently released version? Yes

- Can this issue be consistently reproduced? Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/24580337/47748cee-1741-11e7-85e5-b806c503b392.jpg)

- Any related issues:

**Comment by SilverPuppy** [comment] 2016-11-22 17:34
I can confirm that as of the most recent update today the issue still exists.

**Comment by Liunkae** [comment] 2016-11-22 17:41
@SilverPuppy Have you tried disabling shields? While on the site, click the Brave lion logo in the top right corner and switch Shields to Down.

**Comment by SilverPuppy** [comment] 2016-11-22 18:21
I just tried that, and the result was the same. If it matters it's Win7 64.

I would not expect the shields to have any effect on this issue, as it seems to be a compatibility issue between the PDF.js viewer being used in Brave and the PDF content being generated by Google.

If I had my way, we wouldn't be using Google Calendar, or any other Google product, for that matter, but I'm not the manager.

**Comment by Liunkae** [comment] 2016-11-22 18:27
@SilverPuppy If you think the PDF viewer is the problem, could you try turning it off? Open Preferences and select Advanced. Under the Extensions section, turn off Enable HTML5 PDF reader.

**Comment by SilverPuppy** [comment] 2016-11-22 19:59
Turning off the built-in PDF reader allows the printable view PDF to be successfully downloaded, viewed, and printed externally with Adobe Reader.

**Comment by Liunkae** [comment] 2016-11-22 23:20
That could be the issue. Since Brave uses the same reader as Firefox (pdfJS), maybe the Brave version has a bug that doesn't exist in the Firefox version. I'm not sure, though.

**Comment by SilverPuppy** [comment] 2016-11-23 15:46
More details:

"PDF.js v1.5.444 (build: b9e60a2)
Message: Invalid PDF structure"

**Comment by SilverPuppy** [comment] 2016-11-23 16:45
I just realized that Firefox says that the document may not be displayed correctly when the document is opened. It is, but obviously there is something in the PDF that the Firefox version doesn't understand as well, but the FF version ignores the error and continues to render, whereas the Brave version just fails.

**Comment by SilverPuppy** [comment] 2016-11-29 15:48
Nobody is paying any attention to this, apparently, which is puzzling, since it affects a widely-used tool and a widely-used data format. Is there perhaps a flag that can be passed to the PDF.js viewer when it is invoked to cause it to continue on errors instead of aborting? It looks to me like there is, and Firefox is doing so, which would be a good thing to do.

**Comment by luixxiul** [comment] 2016-11-29 17:48
cc @diracdeltas

**Comment by SilverPuppy** [comment] 2016-12-05 18:53
Still present after today's update

**Comment by Liunkae** [comment] 2016-12-14 05:58
Maybe related: #6188

**Comment by SilverPuppy** [comment] 2017-01-27 19:48
Looks related to me. Issue still present as of build downloaded today.

**Comment by SilverPuppy** [comment] 2017-02-01 15:17
Issue still present at most recent update 5 minutes ago.

**Comment by luixxiul** [comment] 2017-02-01 15:26
OK thanks for pinging

**Comment by SilverPuppy** [comment] 2017-03-02 18:12
Still not working. Occasionally other PDFs do not open properly as well.

**Comment by SilverPuppy** [comment] 2017-03-03 19:08
That is because of another bug https://github.com/brave/browser-laptop/issues/7326 which has been resolved but not in the current released build.

**Comment by SilverPuppy** [comment] 2017-03-03 19:09
I think your #7480 bug is a duplicate of this one, exacerbated by the unreleased resolution on #7326

**Comment by Liunkae** [comment] 2017-03-03 19:14
@SilverPuppy Maybe not. It's still not working in 0.13.5 RC3 either.

**Comment by SilverPuppy** [comment] 2017-03-03 19:17
I think I misread your bug report originally. #7326 pertained to a Windows printing system error, but #7480 looks like a page load issue with the main page.

**Comment by SilverPuppy** [comment] 2017-03-06 14:59
Still present after update yesterday

**Comment by SilverPuppy** [comment] 2017-03-31 13:36
Still present after update today.

**Comment by SilverPuppy** [comment] 2017-04-01 14:41
Still present after update today. 2 updates in 2 days.....rapid progress or swatting a nasty bug? ;)

**Comment by luixxiul** [comment] 2017-04-01 15:59
Will you paste here the output of console on devtool?
You can open it by clicking Inspect Elements on context menu.

The output will let the team troubleshoot (ie. without additional information the team cannot know where the bug is). Thanks.

**Comment by luixxiul** [comment] 2017-04-01 16:10
@SilverPuppy I updated the 1st post to make the bug reproducible more easily

**Comment by Liunkae** [comment] 2017-04-02 02:28
@luixxiul I think there are two separate problems here. This issue is about PDF.js not opening PDFs generated by Google Calendar. The issue I filed (#7480) is about the Google Calendar print window error.

**Comment by bsclifton** [comment] 2017-04-04 16:00
Moving to 0.14.3

**Comment by SilverPuppy** [comment] 2017-05-05 21:06
Still not working as of update today.

**Comment by SilverPuppy** [comment] 2017-05-27 15:08
Working as of update today! Thanks everyone! I no longer have to keep FireFox open just for Google Calendar!

**Comment by bsclifton** [comment] 2017-05-29 18:52
Thanks for the update, @SilverPuppy!  Please re-open this issue if you experience the issue again 😄

**Closed** 2017-05-29 18:52 UTC
Labels: bug, needs-owner, webcompat
