### ISSUE TITLE
YouTube embeds not working with site isolation

### ISSUE THREAD

**Issue by Nikedi** [brave/browser-laptop#13905] opened 2018-04-23 16:23 UTC
EDIT: I fixed it by changing the run every tab in its own process

So Youtube embeds are broken because they don't seem to notice that there is user input. For example i can't even play a video (unless it's set to auto play) and when the  video plays it doesn't even show the onscreen controls when i hover over it

### Steps to Reproduce

  1. Open a website that has a youtube embed on it (not youtube)
  2.  try to click on it

**Actual result:**

Doesn't show on screen controls and can't use them!

**Expected result:**
Showing on screen controls and working ones

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

 
Brave: 0.22.22 
V8: 6.5.254.41 
rev: 63033109963be0a995b3d1ed9723870beeb191c4 
Muon: 5.1.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**

IDK

**Comment by NejcZdovc** [comment] 2018-04-24 05:14
@bsclifton not sure if this is ledger issue, will try it out

**Comment by ryanml** [comment] 2018-04-24 05:32
@Nikedi thanks for filing this issue :)

Could you possible list the site(s) you experienced this issue on? Were Brave shields active at the time? An extra info can help us diagnose exactly what's happening.

Let me know if you have any questions :) thanks.

**Comment by diracdeltas** [comment] 2018-04-24 18:11
This is a known issue with Site Isolation enabled.

**Comment by diracdeltas** [comment] 2018-04-24 18:12
Closing of duplicate of https://github.com/brave/browser-laptop/issues/13716 since OP says they had site isolation enabled

**Closed by diracdeltas** 2018-04-24 18:12 UTC
