### ISSUE TITLE
Basic auth causing continuous spin

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#2818] opened 2016-07-30 05:30 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Visited https://portal.adp.com/wps/employee/employee.jsp and http://browserspy.dk/password.php per https://github.com/brave/browser-laptop/issues/1997, page continued to spin.

**Expected behavior:**
The page should load or otherwise provide status.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X and Ubuntu

- Brave Version:
0.11.2

- Steps to reproduce:
    1. Visit either http://browserspy.dk/password.php and login or https://portal.adp.com/wps/employee/employee.jsp

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-laptop/issues/1997

**Comment by darkdh** [comment] 2016-07-30 08:59
This prompt issue should have been fixed in 866ed3ce555e23082a83ad75317451ed70f091a3

CC @bbondy

**Comment by luixxiul** [comment] 2016-07-30 09:30
@alexwykoff I think https://portal.adp.com/wps/employee/employee.jsp is sometimes just too slow. If you wait for some seconds it should work (I confirmed)

The issue on http://browserspy.dk/password.php is another one: #2807

**Comment by darkdh** [comment] 2016-07-30 09:35
@luixxiul, but I think the commit is not include in 0.11.2.
I manually tested it on 0.11.2 and it's not working.

**Comment by luixxiul** [comment] 2016-07-30 11:08
It seems it's not working in the same tab. Opening it in a new tab works for me.

**Comment by bbondy** [comment] 2016-08-01 12:34
This will be in the next build, RC1, so closing this.

**Closed by bbondy** 2016-08-01 12:34 UTC

**Comment by bbondy** [comment] 2016-08-01 12:59
By RC1 I mean next 0.11.2 build, it could be beta2.

**Comment by alexwykoff** [comment] 2016-08-01 20:05
Looks good!
