### ISSUE TITLE
Two brave windows are launched when clicking a hyperlink in an email

### ISSUE THREAD

**Issue by vrms** [brave/browser-laptop#13378] opened 2018-03-03 05:55 UTC
### Description
Brave is my default browser on a W7, 64 bit system
Each time clicking a hyperlink in an email i.e. **two** brave windows are being launched.  
1 opens the link click, the second window opens the homepage

When Brave is already running while clicking on a hypelink exernally the linked site opens in a new tab in the open instance as expected
### Steps to Reproduce

  1. make brave your default browser (W7, 64 bit)
  2. close brave
  3. click on a hyperlink (which opens brave as the default browser) in any other docment (email i.e) 

**Actual result:**

2 windows are opened, one with the link clicked, the second one with the brave homepage

**Expected result:**
only one window (opening the link) is being launched

**Reproduces how often:**

100%

### Brave Version

Brave | 0.21.18

**about:brave info:**

**Reproducible on current live release:**

**Comment by jamesray1** [comment] 2018-03-04 11:08
Related but not the same as https://github.com/brave/browser-laptop/issues/12715.

**Comment by xsilas43** [comment] 2018-03-07 19:39
Same issue.

Brave | 0.21.18
-- | --
V8 | 6.4.388.41
rev | 580be78
Muon | 4.8.2
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Comment by bsclifton** [comment] 2018-03-10 06:26
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/4197 - please subscribe to that issue for updates 😄

**Closed by bsclifton** 2018-03-10 06:26 UTC
