### ISSUE TITLE
Bookmarks dropdown menu appears to the right offscreen, where it isn't visible

### ISSUE THREAD

**Issue by cdubose** [brave/browser-laptop#5956] opened 2016-12-01 00:12 UTC
**Describe the issue you encountered:**

I recently imported all of my bookmarks (which include many nested bookmarks) from Firefox without an issue. However, when I select a bookmark category at the right edge of the screen from the bookmark bar, the dropdown menu continues to present the bookmark selections to the right of the visible part of the screen. 

**Expected behavior:**

I would like to be able to select the bookmarks that are at the right edge of the screen on the bookmark bar and have the dropdown menu present the bookmark selections to the left, so I can see them in the visible part of the screen.

- Platform (Win7, 8, 10? macOS? Linux distro?):

I am running Windows 8 on a Lenovo G70 laptop.

- Brave Version:

![screenshot 6](https://cloud.githubusercontent.com/assets/7341616/20776756/90c32bf6-b730-11e6-9723-040043d6d590.png)

- Steps to reproduce:
    1. Have a full bookmarks bar (14 folders) with nested folders 
    2. Try to open the dropdown menu of the rightmost or second-to-rightmost bookmark category on the bookmark bar.
    3. See if you can see the bookmark selections on the dropdown menu.

- Screenshot if needed:

![screenshot 7](https://cloud.githubusercontent.com/assets/7341616/20776786/c422d744-b730-11e6-8b06-29c5302c4a28.png)

- Any related issues:

When rearranging bookmarks, there is no indication of where the bookmark selected by the pointer will end up until you release the pointer. (e.g. - In Firefox, there is a small blue line indicating where the new position of the bookmark will end up when rearranging bookmarks)

**Comment by Liunkae** [comment] 2016-12-01 04:26
Related issue: #5589 (drag and drop in the Bookmarks Manager)

I'll file an issue for drag and drop in the bookmarks bar.

**Comment by bsclifton** [comment] 2016-12-03 22:15
Another similar issue (menus going offscreen when they're nested deeply):
https://github.com/brave/browser-laptop/issues/4745

**Comment by bsclifton** [comment] 2017-05-16 19:05
Closing as a dupe of https://github.com/brave/browser-laptop/issues/4745

**Closed by bsclifton** 2017-05-16 19:05 UTC
Labels: bug, feature/bookmarks
