### ISSUE TITLE
downloading images within a modal fails (Twitter example)

### ISSUE THREAD

**Issue by modusops** [brave/browser-laptop#12537] opened 2018-01-07 04:07 UTC
Description
Noticed while downloading (right-clicking) an image in Twitter via direct messages, the download fails. Downloading via an image URL address also fails. 

Steps to Reproduce
  1. Open up a message w/ an image
  2. Right click to save the image
  3. Notice image download failure 
      - if downloading via the image URL, no error alert is presented to the user
      - if downloading via the message modal, user gets an 'interrupted' message

Actual result
1. if downloading via the image URL, no error alert is presented to the user
2. if downloading via the message modal, user gets an 'interrupted' message
3. Right click to save an image in the feed works as expected.

**Expected result:**
Image should download

**Reproduces how often:**
100% of the time w/ Twitter.

Sample URLs from Twitter:
https://ton.twitter.com/i/ton/data/dm/948405781958832137/948405775294128128/241-V6iT.jpg:large
https://ton.twitter.com/i/ton/data/dm/945367755028606983/945367749097807872/EVb5vqiD.jpg

**about:brave info:**

Brave: 0.19.123 
rev: f45cb3a2b308ea1c893f8b2db6143958b8e8d0ac 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.3.0 
OS Architecture: x64

![screen shot 2018-01-06 at 10 32 03 pm](https://user-images.githubusercontent.com/7923023/34646442-19179bc6-f336-11e7-99a0-4cd1722594c9.jpg)
![brave download fail](https://user-images.githubusercontent.com/7923023/34646443-485860dc-f336-11e7-9847-0e60d0577059.gif)

**Comment by bsclifton** [comment] 2018-05-01 06:01
Hi there @modusops - I believe this issue is fixed.  I tried several variations of the steps above and was unable to reproduce (sorry for not responding sooner)

I'm going to close this out as it has been fixed. If you're still encountering the issue, please reopen and include some more notes 😄 👍 Thanks!

**Closed by bsclifton** 2018-05-01 06:01 UTC
Labels: webcompat
