### ISSUE TITLE
Control+W does not work on tabs opened by clicking go back button

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8974] opened 2017-05-20 11:31 UTC
## Test plan
    1. Open about:preferences#tabs
    2. Change "When closing an active tab" setting to `Select the last viewed tab`
    3. Open a new tab
    1. Visit https://github.com on the tab
    2. Click 'Features' on the menu
    3. Click Go back button **two times** with the middle mouse button on the navigation bar
    4. Select the last tab
    5. <kbd><kbd>Control</kbd> + <kbd>W</kbd></kbd>
    6. Repeat ^

Focus should go form last tab to the parent tab (since it was last active).

Since the fix involved refactoring the logic for close tab, you may wish to test that all 3 of these options work as expected:
![screen shot 2017-05-25 at 8 54 51 am](https://cloud.githubusercontent.com/assets/4733304/26458365/dafede82-4127-11e7-8b3a-340ae1d224c6.png)

## Description
**Describe the issue you encountered**: By changing the tab setting to `Select the last closed tab`, Control+W does not work on tabs opened by clicking go back button.

- Platform (Win7, 8, 10? macOS? Linux distro?): tested on debian

- Brave Version (revision SHA): 0.15.306

- Steps to reproduce:
    1. Open about:preferences#tabs
    2. Change "When closing an active tab" setting to `Select the last closed tab`
    3. Open a new tab
    1. Visit https://github.com on the tab
    2. Click 'Features' on the menu
    3. Click Go back button **two times** with the middle mouse button on the nagivation bar
    4. Select the last tab
    5. <kbd><kbd>Control</kbd> + <kbd>W</kbd></kbd>
    6. Repeat ^
    
- Actual result: only 1 tab can be closed

- Expected result: both tabs should be closed

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
  

- Any related issues:

**Comment by bsclifton** [comment] 2017-05-23 01:01
When the tab is closed, we do calculate a new active frame (and this is correct).  However, the tab state is never updated (ex: `appState.get('tabs')`.  When any action happens which tries to use the `TAB_ID_ACTIVE`, it will then fail (because no tabs are marked as active).

Working on a fix...

**Comment by bsclifton** [comment] 2017-05-23 21:31
Findings I had while making a work-around:

 The underlying problem has these steps:
 - tab is cloned two times
 - focus is given to the 2nd cloned tab
 - ctrl + w happens; this triggers `APP_TAB_CLOSE_REQUESTED`
   - window is closed as expected
 - `WINDOW_CLOSE_FRAME` is fired + picked up by frameReducer
   - new active frame is picked
   - new frame state is committed to appState
   - `APP_TAB_ACTIVATE_REQUESTED` is fired
     - `APP_FRAME_CHANGED` fires (which includes tabState with active = false)

 At this point, we're *expecting* `APP_TAB_UPDATED`
 because it's changed above (`tabs.setActive(action.get('tabId'))`)
 ..but it never happens..

**Comment by bridiver** [comment] 2017-05-25 01:38
the expected behavior in this issue is actually wrong. With a setting of `Select the last viewed tab` (there is no Select the last closed tab setting), it should go back to the original github page, not the second clone

**Comment by luixxiul** [comment] 2017-05-25 01:49
> `Select the last closed tab`

I don't remember correctly if I misread something (sorry it was confusing), yet the point is you cannot close the 2 tabs consecutively.

**Comment by bridiver** [comment] 2017-05-25 01:50
there are actually 2 bugs here. The first is (with that setting) it should return to the original github.com tab. The second is the issue with closing the second tab

**Comment by bsclifton** [comment] 2017-05-25 21:24
Fixed in `dev-channel` with https://github.com/brave/browser-laptop/pull/9023/
Fixed in `master` with https://github.com/brave/browser-laptop/pull/9057

**Closed by bsclifton** 2017-05-25 21:24 UTC
Labels: bug, feature/keyboard-shortcuts, feature/navbar, QA/steps-specified, regression, release-notes/exclude

**Comment by luixxiul** [comment] 2017-05-26 05:05
The test plan works, still I found another issue (which should not be a blocker I think) by following the STR with one about page (about:preferences) opened. I'm going to log the issue as a follow-up.

**Comment by luixxiul** [comment] 2017-05-26 05:11
I logged here: https://github.com/brave/browser-laptop/issues/9065
