### ISSUE TITLE
user input is sometimes lost because of race conditions with state updates

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#3158] opened 2016-08-12 20:29 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A few examples are in #2197 and #2812, but issues have also been reported in the find box and at other times with the address bar
- Brave Version:
  0.11.4

**Comment by bbondy** [comment] 2016-08-13 20:53
dupe of https://github.com/brave/browser-laptop/issues/3162 ?

**Comment by bbondy** [comment] 2016-08-13 20:53
or dupe that one to this one

**Comment by bridiver** [comment] 2016-08-13 22:08
well #3162 is also about testability for that particular fix

**Comment by luixxiul** [comment] 2017-05-28 12:57
CC @NejcZdovc for checking this is/was fixed with recent redux update (being not sure if this issue is related with that update).

**Closed** 2018-08-26 09:30 UTC
Labels: bug, feature/URLbar, fixed-with-brave-core, wontfix
