### ISSUE TITLE
Navigating back retains the URL and shows about:newtab in title

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5813] opened 2016-11-23 14:41 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Navigating back retains the URL and shows about:newtab in title

**Expected behavior:**
Should not retain the URL and should show the Newtab in the title

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
Master

- Steps to reproduce:
    1. Open new tab
    2. Click on any of the pinned top sites
    3. Click the back nav button, retains the URL and shows tab title as about:newtab

- Screenshot if needed:
![aboutnewtab](https://cloud.githubusercontent.com/assets/17010094/20565791/c9a37d5a-b18a-11e6-90e0-466b7de0eab8.gif)

- Any related issues:

**Comment by bbondy** [comment] 2016-11-24 19:17
Hrm I just tried these steps and it showed a blank url for me.  Can you reproduce this even after pressing CmdOrCtrl+T and then trying in a new tab?  Or does it have to do with previously input text in the input field?

**Comment by bsclifton** [comment] 2016-11-30 08:08
@bbondy I was able to repro- I tried with a blank session on Windows and it only happened when I followed the Twitter link which happens to be pinned (not the others).

The part to watch for is the tab title:
![screen shot 2016-11-30 at 1 05 55 am](https://cloud.githubusercontent.com/assets/4733304/20744477/73dd3280-b699-11e6-80d0-f83ec5450c4b.png)

**Comment by bbondy** [comment] 2016-12-01 15:34
repro'd thanks. It was a terminology problem I was thinking pinned tab.  The wording we should use for that is pinned top site to avoid confusion.  I updated the original STR. It's my fault though I was thinking the screenshot was wrong because it didn't have pinned tabs.

**Comment by cezaraugusto** [comment] 2017-02-01 21:05
Issue #6927 is a dupe of this, but since fix (#6990) for both mentions the former, I'll close this one. sorry and thanks.

**Closed by cezaraugusto** 2017-02-01 21:05 UTC
Labels: feature/newtab
