### ISSUE TITLE
Brave inresponsible without any visible reason while opening new tab and start typing search phrase

### ISSUE THREAD

**Issue by pongraczi** [brave/browser-laptop#11194] opened 2017-09-28 08:22 UTC
### Description

Brave getting inresponsible for user interaction. I can write into the search bar, but nothing else working: clicking, right-clicking, pressing enter etc.
Only resize is working and in the background, it seems still working.
I suspect the drop-down is the reason (shoot-in-the-dark).
Video about the situation is here: https://youtu.be/HypwmU_fVXI

### Steps to Reproduce

It is random, cannot provide steps to reproduce. It happened 2 times.
Conditions were: Several open tabs, about 24+ hours running -> open a new tab and start to type search phrase -> thing just happened.

**Actual result:**

Video: https://youtu.be/HypwmU_fVXI

**Expected result:**
Working brave without this issue.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Rare, but annoying :) 
I remember exactly 2 times.

### Brave Version

**about:brave info:**

 
Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Linux 
OS Release: 4.11.0-14-lowlatency 
OS Architecture: x64

### Additional Information

Dual monitor, Mate DE, Linuxmint 18.2

**Comment by NejcZdovc** [comment] 2017-09-28 08:25
@pongraczi thank you for your report. Can you please next time that this happens open dev tools (Shift+F8) and print screen it. Maybe there will be an error that could help us out determinate what is going on

**Comment by pongraczi** [comment] 2017-09-28 08:36
Sure, if it will response for Shift+F8 :)
I tried some keyboard combinations, too, no effect, but Shift+F8 was not in my list before.
Next time :)

**Comment by bsclifton** [comment] 2017-10-17 00:09
Closing this issue for now, since there aren't enough steps to reproduce (so that we can debug or take action).  Shift+F8 and viewing the console will have the detailed errors which can be screenshotted or copy/pasted 😄 👍

**Closed by bsclifton** 2017-10-17 00:09 UTC
