### ISSUE TITLE
Menu should not be activated with ALT key (Linux)

### ISSUE THREAD

**Issue by stefanos1019** [brave/browser-laptop#5540] opened 2016-11-10 16:25 UTC
Pressing `Alt+Shift` to change system language opens the browser `Menu Bar`.

It's not such an important issue but still is annoying!

- Platform: Linux Debian 8 (jessie)

- Brave Version:
        Brave: 0.12.8
        Electron: 1.4.23
        libchromiumcontent: 53.0.2785.143
        V8: 5.3.332.47
        Node.js: 6.5.0
        Update Channel: dev

**Comment by bsclifton** [comment] 2016-11-11 09:28
Notes for someone who wanted to grab this:

I solved this problem on Windows with https://github.com/brave/browser-laptop/pull/5450

This would only be affecting distros which don't have the global system menu.  The solution would likely be a modification of what was done in the PR

**Comment by Superbest** [comment] 2016-12-01 00:20
Brave 0.12.10 on Win 7 Enterprise SP1 x64. Cannot reproduce. Language change key is `Alt+Shift` and multiple languages present. `Menu Bar` is not opened contrary to @stefanos1019 's report.

**Comment by Liunkae** [comment] 2016-12-01 04:14
@Superbest It appears that this problem is Linux-only, and only on some Linux distros (as @bsclifton said above).

**Comment by Superbest** [comment] 2016-12-01 20:18
@Liunkae Ah, that explains it. Looks like I misread his comment, sorry.

**Comment by srirambv** [comment] 2017-02-21 11:15
+1 from community user Alexey https://community.brave.com/t/shift-alt-behaviour/1247

**Comment by bsclifton** [comment] 2017-03-04 00:47
Windows should be good to go now after the following PRs:
- https://github.com/brave/browser-laptop/pull/5450
- https://github.com/brave/browser-laptop/pull/7485

Unless we implement a custom titlebar, the ALT processing may be picked up by the OS (before keypress handlers pick it up). Definitely need more info before this can be solved

**Comment by Attrash-Islam** [comment] 2017-03-26 09:12
+1

**Comment by zolk3ri** [comment] 2017-05-17 18:17
Is it possible to hide the menu bar permanently so that not even pressing ALT would show it?

**Comment by bsclifton** [comment] 2017-05-17 23:35
@zolk3ri that's a great idea- I just captured https://github.com/brave/browser-laptop/issues/8924 to track that

**Comment by webdinislam** [comment] 2017-05-27 05:53
I have the same problem and it's confusing. Because I need to switch from English to Russian and this is very annoying. And I do something like that: holding **SHIFT** and press **ALT**, so this way menu will not be opened. But it is not so good... Hope you'll fix this problem.

**Comment by eljuno** [comment] 2017-06-29 19:12
+1 [from community.](https://community.brave.com/t/alt-shift-brings-some-menu-but-the-keys-are-commonly-used-to-swap-layouts/4351/)

User on Linux Mint 18.1 Cinnamon 18.1 64bit

> Name	Version
Brave	0.16.13
rev	7869803
Muon	4.0.4
libchromiumcontent	59.0.3071.104
V8	5.9.211.35
Node.js	7.9.0
Update Channel	dev
os.platform	linux
os.release	4.4.0-81-generic
os.arch	x64

**Comment by eljuno** [comment] 2017-07-02 21:29
+1 [from community](https://community.brave.com/t/pressing-alt-shift-to-switch-language-opens-the-file-menu/2919)

**Comment by wavic** [comment] 2018-06-02 23:30
Still not fixed? The menu should be triggered by a single ALT key on release. Not by any ALT+??? key combination. It's really annoying for someone like me changing from the native to English language a lot.

**Comment by big50000** [comment] 2018-08-25 07:28
Still exists in 0.23.79.

**Comment by bsclifton** [comment] 2018-09-10 18:51
This should be resolved with our new [developer channel release](https://brave.com/download-dev) 😄

**Closed by bsclifton** 2018-09-10 18:51 UTC
Labels: OS/unix-like/linux, feature/keyboard-shortcuts
