### ISSUE TITLE
Login to Linkedin, autocomplete problem

### ISSUE THREAD

**Issue by JimSEOW** [brave/browser-laptop#5144] opened 2016-10-26 08:08 UTC
When login in to linkedin, when prompted for email, when I type the first alphabet of the email, the popup menu appear to select the email, the popup closes before I have chance to select the email.

**Comment by getsetbro** [comment] 2016-12-16 15:35
This happens to me on stackoverflow: http://quick.as/lrvkfzgwx

**Comment by Liunkae** [comment] 2016-12-16 18:38
Duplicate of #5438. This problem is planned to be fixed by version 0.13.2.

**Closed by Liunkae** 2016-12-16 18:38 UTC
Labels: feature/autofill, needs investigation
