### ISSUE TITLE
Right-click in developer tools no longer work

### ISSUE THREAD

**Issue by da2x** [brave/browser-laptop#14403] opened 2018-06-14 01:30 UTC
### Steps to Reproduce
  1. Open developer tools
  2. Right-click on anything you expect  to see a context menu from (such as a node element)

**Actual result:**
Nothing.

**Expected result:**
Context menus.

**Reproduces how often:**
Every time on macOS and Windows.

### Brave Version
0.22.810

This used to work not too long ago.

**Reproducible on current live release:** Y

**Comment by bsclifton** [comment] 2018-06-14 17:59
@da2x this hasn't worked for as long as I've known - it does work if you open the browser developer tools (shift+f8), but it doesn't work for the actual content developer tools ☹️ 

Closing as a duplicate of https://github.com/brave/browser-laptop/issues/6724

**Closed by bsclifton** 2018-06-14 17:59 UTC
