### ISSUE TITLE
Feature request: multiple users saved

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#12270] opened 2017-12-13 02:22 UTC
### Description
I'd like to be able to have multiple accounts saved, with a different taskbar icon for each acocunt. Avira Scout has this feature, but the browser is not maintained. At the moment I use different browsers for each account.

**Comment by bsclifton** [comment] 2017-12-13 05:53
Thanks for the report, @jamesray1 😄  I'm going to close this issue as a duplicate of https://github.com/brave/browser-laptop/issues/10324

Please subscribe to that issue for updates.  Thanks!

**Closed by bsclifton** 2017-12-13 05:53 UTC

**Comment by jamesray1** [comment] 2017-12-13 07:39
Thanks! I did search, but maybe not enough.

**Comment by kenorb** [comment] 2017-12-13 11:13
> At the moment I use different browsers for each account.

Same as me. I've got over 13 web browser installed on my macOS.
