### ISSUE TITLE
Hide Menu Bar does not always stick between restarts

### ISSUE THREAD

**Issue by ryanmusante** [brave/browser-laptop#13179] opened 2018-02-19 01:22 UTC
### Description
Hide Menu Bar by Default does not stick sometimes on setting and will cause crash

### Steps to Reproduce
1. Set hide menu bar by default
2. exit brave
3. load brave

**Actual result:**
traps: brave[16512] general protection ip:32e7b10 sp:7ffe20345518 error:0 in brave[1999000+4851000]

**Expected result:**

### Brave Version
Brave | 0.20.42
V8 | 6.4.388.41
OS Release | 4.15.4-2-MANJARO

**Comment by srirambv** [comment] 2018-02-19 03:43
Dupe of https://github.com/brave/browser-laptop/issues/5086

**Closed by srirambv** 2018-02-19 03:43 UTC
