### ISSUE TITLE
New windows for sharing are not closed automatically

### ISSUE THREAD

**Issue by raisty** [brave/browser-laptop#13603] opened 2018-03-26 14:22 UTC
### Description

I try to share twitter or facebook and the windows are not closing after sharing and are white.

### Steps to Reproduce

  1. Click on tweet somewhere on website, for example: https://www.nytimes.com/2018/03/20/business/energy-environment/bmw-diesel-emissions.html?hpw&rref=automobiles&action=click&pgtype=Homepage&module=well-region&region=bottom-well&WT.nav=bottom-well
  2. Share article
  3. Window will stay opened and blank

**Actual result:**

Opened window blank

**Expected result:**
Window will close

**Reproduces how often:**

Anytime

### Brave Version

**about:brave info:**

 
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Reproducible on current live release:**

yes

**Comment by jonathansampson** [comment] 2018-03-27 20:51
I am able to reproduce this issue; in fact, I believe this is a duplicate.

As a quick primer to the root issue, when there is but only one tab in a window, and `window.close()` is called on that tab, closing this tab will not result in the window itself being closed.

![image](https://user-images.githubusercontent.com/815158/37994258-9d59094a-31d6-11e8-9b6a-fe42fd1909f9.png)

If the user clicks the [x] on the tab, the Window itself will close with the last tab closing.

**Comment by jonathansampson** [comment] 2018-03-27 20:54
Closing as dupe to https://github.com/brave/browser-laptop/issues/13370

**Closed by jonathansampson** 2018-03-27 20:54 UTC
