### ISSUE TITLE
Detach loaded tab displays as new tab

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10365] opened 2017-08-09 15:53 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When detaching a loaded tab, it displays as a new tab instead of the site you had loaded.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
Brave | 0.18.20
rev | 60bb9e6
Muon | 4.3.9

- Steps to reproduce:
    1. Open a new tab and load a site (I used nytimes.com).
    2. Tear off/detach the tab.
    3. Detached tab is displaying the new tab page, not the site.
    4. Window the tab was torn from displays white page (known issue)
    
- Actual result:
New tab is displayed instead of loaded site.

- Expected result:
Loaded site should be displayed in torn off tab.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![tearofftab](https://user-images.githubusercontent.com/28145373/29130916-30d85092-7cf9-11e7-8c29-70da96fe0453.gif)

- Any related issues:

**Comment by bbondy** [comment] 2017-08-10 04:20
Duplicate of https://github.com/brave/browser-laptop/issues/10376

**Closed by bbondy** 2017-08-10 04:20 UTC
Labels: bug, feature/tear-off-tabs, QA/steps-specified, regression
