### ISSUE TITLE
user should be notified if app state cannot be restored

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#1517] opened 2016-04-30 18:54 UTC
Currently if there is an issue restoring app state, it silently fails and reverts to a fresh app state. There should be a clear notice that app state (all settings) has been lost

**Comment by bsclifton** [comment] 2018-09-01 06:52
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/2727

**Closed by bsclifton** 2018-09-01 06:52 UTC
