### ISSUE TITLE
Command-H key combination to hide the app stopped working

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7199] opened 2017-02-11 15:56 UTC
**Describe the issue you encountered:**

https://community.brave.com/t/mac-os-10-command-h-not-working-and-fullscreen-default/1180?u=suguru

> The Mac ⌘-H key combination to hide the app isn't working with Brave 0.13.2. Could this feature be restored?

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): 0.13.2

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment] 2017-02-12 20:54
Brave 0.13.2 on macOS 10.12.x
When not in full screen mode, <kbd>Command+H</kbd> still works for me.
When in full screen mode, the shortcut does not work.
This is the intended behavior on macOS (see Safari, etc.). Closing.

**Closed by Liunkae** 2017-02-12 20:54 UTC
Labels: OS/macOS, regression
