### ISSUE TITLE
2-finger scrolling too fast on Windows?

### ISSUE THREAD

**Issue by BraveSupporter** [brave/browser-laptop#12759] opened 2018-01-20 22:57 UTC
I'm on a Lenovo Edge 2 laptop. The 2 finger scrolling is simply too responsive. I scroll too much at any given time, no matter how gentle I am with the trackpad. And this is honestly the primary thing that's keeping me from using it as my default browser. I've tried changing the scroll sensitivity but no matter how low I change it to, it remains too fast.

The scrolling works okay on firefox, edge, chrome. Anyone have the same problem? 

Steps to Reproduce
Open Brave browser.
Scroll.

Actual result:

Expected result:

Reproduces how often:
Every page that needs scrolling
Brave Version

Brave | 0.19.139
-- | --
rev | 99aa17d
Muon | 4.7.2
libchromiumcontent | 64.0.3282.85
V8 | 6.4.388.20
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

Reproducible on current live release:
Yes.

**Comment by srirambv** [comment] 2018-01-23 12:12
Dupe of #3669

**Closed by srirambv** 2018-01-23 12:12 UTC
