### ISSUE TITLE
Middle mouse drag selects text instead of just scrolling

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10405] opened 2017-08-10 15:40 UTC
**Describe the issue you encountered:** https://community.brave.com/t/middle-mouse-drag-selects-text-instead-of-just-scrolling/5583?u=suguru

> Is there a way to stop middle mouse dragging from selecting all of the text as if I’m left click and dragging? I use a pen tablet on my PC instead of a mouse so use middle mouse drag as a substitute for scroll wheel functionality. Chrome scrolls using middle mouse drag appropriately but Brave selects text as it scrolls.

![middlebutton](https://user-images.githubusercontent.com/3362943/29178743-6b337aca-7e2d-11e7-87f9-07025def35da.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version (revision SHA): master 

- Steps to reproduce:
    1. Drag the page with middle mouse
    
- Actual result: it selects the text

- Expected result: it should not select the text

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment] 2017-08-15 12:04
+1 from here https://community.brave.com/t/hidden-customization-options-or-possible-suggestions/5866

**Comment by JaneSmith** [comment] 2017-08-18 00:46
I experience the same issue.

I think this might also be related... When viewing a large image on its own (e.g. https://upload.wikimedia.org/wikipedia/commons/4/4e/Pleiades_large.jpg), if I middle-click and HOLD the button, I can't scroll across the image - nothing happens when I move the mouse. It only works if I middle-click and then release the button.

**Comment by LaurenWags** [comment] 2017-08-18 12:50
+1 from community https://community.brave.com/t/middle-click-selecting-text/6145

**Comment by eljuno** [comment] 2017-08-20 19:55
+1 from this one https://community.brave.com/t/mouse-gestures-extensions/290/12?u=eljuno

**Comment by NejcZdovc** [comment] 2017-08-21 20:32
+1 from #10613

**Comment by mantasink** [comment] 2017-12-21 09:13
+1
This issue seems very underrated. It's the main reason why I might stop using Brave after been trying it for several days. And I'm probably not the only one being annoyed.

**Comment by Mynuber** [comment] 2017-12-22 07:00
This is literally the main reason why 4 people in our office no longer use this browser. They actually love the speed/look and feel. But this is extremely annoying. There has to be a setting to turn it off or something

**Comment by reformstudios** [comment] 2018-01-16 14:23
Any news on this? I also have the same problem and find it a major headache.

**Comment by eljuno** [comment] 2018-01-17 22:16
+1 from community https://community.brave.com/t/middle-click-scroll-highlights-everything-need-option-to-disable/13920?u=eljuno

**Comment by Zak757** [comment] 2018-01-19 22:04
+1, I always use the middle mouse to scroll. This is killing Brave for me.

**Comment by srirambv** [comment] 2018-02-01 06:22
+1 from community https://community.brave.com/t/pressing-mouse-3-down-the-scroll-wheel-highlights-everything/15156

**Comment by MBLHarrison** [comment] 2018-03-15 14:56
+1 @bsclifton May I be cheeky and ask for a gentle pointer to where this issue occurs in the code. I would like to have a look at it.

**Comment by hcapmedia** [comment] 2018-03-17 21:03
I have found a workaround for this issue which has been working flawlessly. An added bonus is that auto-scroll functionality is added into Linux/macOS, a massive bonus for me at least! The fix involves installing this chrome extension named AutoScroll by kaescripts.blogspot using this tutorial. You can then configure the AutoScroll extension by going to the following address: chrome-extension://“root_extension_directory”/data/options.html. Replace “root_extension_directory” with the long, 32 character directory name. For example: bmnlcjabgnpnenekpadlanbbkooimhnj. I found that just changing the scroll speed to 2 is very comfortable for me.

As a side note, installing this extension in any chromium based browser adds autoscrolling functionality to Linux/macOS. Also, to avoid rooting around in Chrome’s directories, you may just download the AutoScroll extension using an extension like Get CRX by Adam Carbonell.

**Comment by LaurenWags** [comment] 2018-05-10 13:33
+1s from community:
https://community.brave.com/t/scroll-wheel-bug-highlights-entire-page/21820
https://community.brave.com/t/scroll-wheel-bug/11589

**Comment by BigWillBlue** [comment] 2018-05-16 07:16
I'm new to brave and I love every single thing about it except this one quirk. I would really like to see an option to remove this from both MMB and RMB.

**Comment by MBLHarrison** [comment] 2018-05-16 08:57
@bsclifton Has these been discussed internally? It is a huge UX degradation.

**Comment by rinsitah** [comment] 2018-06-11 10:19
+1
I've started using Brave and I find it good, however- this scroll wheel highlighting everything is a deal breaker! How long until it is fixed? I have to go back to chrome until then as I can't function properly with this issue.

Thanks!

**Comment by GilHacco** [comment] 2018-06-13 01:44
Glad to find that I'm not the only one who finds this to be a problem. 

I generally use a tablet at work and the middle mouse button / hold-drag is the only viable way to scroll without a mouse-wheel and needless to say.. I really don't want to be highlighting all the contents of a page while scrolling. It's not only undesired, it's aggravating.

**Comment by eljuno** [comment] 2018-06-20 19:59
+1 from community https://community.brave.com/t/annoying-highlighting/25198?u=eljuno

**Comment by hcapmedia** [comment] 2018-06-21 16:13
I'm guessing that this will be an issue until the 1.0 release which will use Chromium's native UI.  I can think of a number of positives in this move (bookmarking...).
https://brave.com/development-plans-for-upcoming-release/

**Comment by bsclifton** [comment] 2018-06-21 17:30
@hcapmedia you are correct- this is fixed with our new UI (Brave Core). I just confirmed it works great there

Thanks everybody for your patience- I know this has been an annoying one. There are a number of reasons we're moving to the Chromium based UI instead of the Electron/Muon based one we're currently using. As @hcapmedia shared, you can read more about it on our blog 😄 
https://brave.com/development-plans-for-upcoming-release/

I'm going to close this issue as `wontfix` since we won't fix it with our current UI. However, it's already fixed with the new Chromium UI:
https://github.com/brave/brave-browser

**Closed by bsclifton** 2018-06-21 17:30 UTC
Labels: bug, fixed-with-brave-core, priority/P3, usability, wontfix
