### ISSUE TITLE
Removing top site tiles is buggy

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#10411] opened 2017-08-10 19:25 UTC
# Test Plan
    1. Visit few sites
    2. Open the dashboard page in a new tab.
    3. Click the "X" button to remove any page tile.
    4. The tile should be removed immediately.
# 
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
When I try to remove top site tiles on the dashboard page, the tile is not removed immediately. It sometimes gets removed later randomly, when I navigate to another website, open a new tab, etc. Sometimes it does not get removed even after trying multiple things. Refreshing the dashboard page does not help.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.x

- Brave Version (revision SHA):
0.18.21 (263b6d5). I've had this problem for several major versions.

- Steps to reproduce:
    1. Visit any site.
    2. Open the dashboard page in a new tab.
    3. Click the "X" button to remove any page tile.
    
- Actual result:
The tile is not removed immediately.

- Expected result:
The tile should be removed immediately.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Not sure.

- Is this an issue in the currently released version?
I think I've had the problem throughout 0.18.x, so yes.

- Can this issue be consistently reproduced?
Almost all the time.

- Extra QA steps:
    1. Visit any site.
    2. Open the dashboard page in a new tab.
    3. Click the "X" button to remove any page tile.
    4. Make sure the tile is removed immediately.

- Screenshot if needed:
None.

- Any related issues:
None.

**Comment by Jacalz** [comment] 2017-08-10 19:51
+1 from me, Noticed this in 0.18.21 today

**Comment by NejcZdovc** [comment] 2017-08-10 20:02
We added 5s delay for generating topSites https://github.com/brave/browser-laptop/blob/master/app/browser/api/topSites.js#L143. We optimised this in version 0.21, so it should be better.

**Comment by LaurenWags** [comment] 2017-08-16 17:27
+1 from me, I repro'd today with 0.18.23

**Comment by LaurenWags** [comment] 2017-08-16 18:44
Added regression label and milestone, this is working in 0.18.14.

**Comment by NejcZdovc** [comment] 2017-08-16 18:46
@LaurenWags this is not a regression, we added that intentionally (that 5s delay), so I wouldn't add this to the 0.18 hotfix

**Comment by LaurenWags** [comment] 2017-08-16 18:47
ok, since my tiles aren't being removed at all (like they were in previous version) I thought it was a regression. will remove milestone.

**Comment by NejcZdovc** [comment] 2017-08-16 18:47
if they are not removed at all, then this is a regression, but would still put it into 0.19 and not block 0.18 on it

**Comment by NejcZdovc** [comment] 2017-08-18 05:50
+1 from #10576

**Comment by happyhero0** [comment] 2017-08-22 08:21
+1 Same problem

**Comment by NejcZdovc** [comment] 2017-08-22 08:24
+1 from #10622

**Comment by alexwykoff** [comment] 2017-08-22 17:19
This needs some design and engineering consideration @bradleyrichter

**Comment by Cyrkhan** [comment] 2017-08-30 08:12
Quite different question, nevertheless also regarding dashboard's tabs : how to add new tiles or replacing default tiles by new ones ? I observed that when I set Brave to erase histories, caches or cookies at shutdown, the dashboard shows no more any tile, even the default ones (Twitter, Facebook and so on), but I cannot add new tiles, or don't know how to proceed.

**Comment by bsclifton** [comment] 2017-08-30 16:38
@Cyrkhan here's the issue for that (with some discussion already, including a prototype of what adding a site would look like). We'd love to hear your comments 😄 
https://github.com/brave/browser-laptop/issues/7742

**Comment by Jacalz** [comment] 2017-08-31 14:26
+1 from community https://github.com/brave/browser-laptop/issues/10411

**Comment by NejcZdovc** [comment] 2017-08-31 19:54
+1 from #10750

**Comment by pongraczi** [comment] 2017-09-05 07:43
+1 Linuxmint 17 64 bit, Mate desktop, Brave | 0.18.23  rev | 36ae2ec

Customization of tiles (I hate that word, it has windows feeling), including user specified icons support and removing default icons once and forever.

**Comment by LaurenWags** [comment] 2017-09-07 12:55
+1 from twitter - https://twitter.com/DisinfectantIII/status/905760552332472321

**Comment by jonathansampson** [comment] 2017-09-12 03:34
+1 from twitter: https://twitter.com/DynCorpKidsClub/status/907426559388262402

**Comment by bsclifton** [comment] 2017-09-13 00:01
+1 from @alexwykoff via https://github.com/brave/browser-laptop/issues/10916

@NejcZdovc you mention this does work in 0.21.x (although, with a 5s delay).  With 0.18.x it just doesn't work at all.  

I'm going to bump up the milestone on this issue because this problem doesn't exist in 0.21.x... that build has a different issue (takes 5 seconds to remove)

**Comment by NejcZdovc** [comment] 2017-09-13 06:27
@bsclifton sure, make sense

**Comment by NejcZdovc** [comment] 2017-09-13 13:01
@brave/qa can you please retest this issue on 0.19.x build, because I just tried it and it's working correctly. You need to wait 5s as already mentioned above, but after that site is removed

**Comment by srirambv** [comment] 2017-09-18 08:29
+2 from community https://community.brave.com/t/thumb-not-being-removed-when-removing-page-from-top-sites/7766

**Comment by NejcZdovc** [comment] 2017-09-18 08:35
note that this 5s was removed for delete and pin in 0.21.x

**Comment by srirambv** [comment] 2017-09-18 09:39
Verified on 0.19.6. Top tile does gets removed after 5 sec delay. But I feel this should be instantaneous and the notification message should show up after the tile is removed. One option would be to gray out the tile when clicked on the delete button so as to make it inactive and when removed show the message.

Showing the thumb removed message when the tile is still being shown is an odd behaviour.

**Comment by NejcZdovc** [comment] 2017-09-18 09:46
@srirambv agree, that's why I fixed this behaviour so that is instant for delete and pin in 0.21.x. Question is not if we want to create patch only for 0.19 and 0.20?

**Comment by NejcZdovc** [comment] 2017-09-19 17:17
fixed with #10136

**Comment by luixxiul** [comment] 2017-11-06 09:52
manually tried, it look good to me 👍

**Comment by LaurenWags** [comment] 2018-01-11 22:32
On MacOS - I click the X, wait 5-10s, nothing happens (tile is not removed). I open a new tab, click the x again, now the tile is removed:
![10411-02016](https://user-images.githubusercontent.com/28145373/34850798-5d149ee2-f6f5-11e7-8ff3-608a5c256313.gif)

**Comment by bsclifton** [comment] 2018-01-11 22:45
+1 from @srirambv via https://github.com/brave/browser-laptop/issues/12568

**Comment by LaurenWags** [comment] 2018-01-23 19:07
Reopening - removed tile is not replaced after it is removed. 

STR: so my steps were: clean profile. visit 6 different sites. open new tab with dashboard. see 1 pinned tile (default) and 5 unpinned new tiles for a total of 6 tiles. click the x for one of the new tiles. now you have 5 tiles (1 pinned and 4 un-pinned). visit 7th new site. open new tab with dashboard. Still have 5 tiles on new tab page. Close/Restart Brave. Still have 5 tiles on new tab page.

**Closed** 2018-01-23 21:17 UTC
Labels: QA/test-plan-specified, bug, feature/newtab, regression, release-notes/include
