### ISSUE TITLE
Pinning a tab causes tab to disappear and reload when pinned

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6745] opened 2017-01-19 18:54 UTC
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Pinning a tab causes tab to disappear and reload when pinned

**Expected behavior:**
Pinning a tab should just convert the normal tab to a pinned tab without reloading.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	c60b783
Not happening on previous 0.13.0 builds/ 0.12.15

- Steps to reproduce:
    1. Open a bunch of websites in individual tabs
    2. Right click and pin the tabs
    3. Tab disappears before getting pinned which causes the tab to reload the page which was already loaded in step 1

- QA Steps:
    1. Open a bunch of websites in individual tabs
    2. Right click and pin the tabs
    3. Normal tab should be converted to pinned tab without causing it to disappear and reload

- Screenshot if needed:
![pintabs](https://cloud.githubusercontent.com/assets/17010094/22120600/4fe05f7c-de78-11e6-96c7-9b668dc6ff67.gif)

- Any related issues:
cc: @bbondy

**Comment by bbondy** [comment] 2017-01-19 21:22
Steps to reproduce:

1. Clean session store
2. Start browser
3. Command+T
4. brianbondy.com
5. right click it and try to pin

It doesn't reload.

I also tried opening multiple sites in step 4 but it still doesn't reproduce. 
Better steps are needed pls.

**Comment by bbondy** [comment] 2017-01-19 21:22
Also since it doesn't reproduce for me I wonder if it's a regression at all?

**Comment by srirambv** [comment] 2017-01-19 21:35
Not able to reproduce with a new session. Also adding pinned tabs is causing the browser to crash frequently.

**Comment by srirambv** [comment] 2017-01-19 21:48
Sending the session-store file to @bbondy

**Comment by bbondy** [comment] 2017-01-20 02:37
I'm not able to reproduce, I need more steps above and beyond what I did in https://github.com/brave/browser-laptop/issues/6745#issuecomment-273902584

I'm going to triage this out because I can't reproduce and I think it's probably some edge case also in the production version.

**Comment by srirambv** [comment] 2017-02-06 20:53
Still an issue on 0.13.2. Shared the `session-store-1` file from 0.13.1 & 0.13.2  with @darkdh 

0.13.2
![7091_1](https://cloud.githubusercontent.com/assets/17010094/22665848/35fc94ec-ecae-11e6-8887-efe095bfd4a2.gif)
0.13.1
![7091_2](https://cloud.githubusercontent.com/assets/17010094/22665852/38fe4e4c-ecae-11e6-8992-ce0fd34154cc.gif)

**Comment by bsclifton** [comment] 2018-02-23 17:53
Closing as I can't reproduce this with 0.20.42

**Closed by bsclifton** 2018-02-23 17:53 UTC
Labels: bug, feature/pinned-tabs, needs-STR, regression
