### ISSUE TITLE
Bravery bug greys out - inoperable after a few sites visited

### ISSUE THREAD

**Issue by cfumante** [brave/browser-laptop#1946] opened 2016-05-27 17:00 UTC
Tried the Bravery menu button after receiving an email letting me know about the function in 0.10.0

Went to several sites and tried it - worked fine

Went to another site and the button to call up the menu was greyed out. It has stayed inoperable ever since even though I shut Brave down and restarted it,

<additional note - just noticed it works on the github site - still greyed out on other sites>

<additional info - cause is private sessions - works in unsecured tabs, does not work in private tabs>

Running Win10.

-

**Comment by bbondy** [comment] 2016-05-29 13:39
Please let us know the URL where it is grayed out.

**Comment by bbondy** [comment] 2016-05-29 13:40
Closing this issue for now because not enough info, but if there is more info given I'll re-open.

**Comment by cfumante** [comment] 2016-05-29 16:15
I entered an update to the issue shortly after I opened it. It is not a
site-related problem - it works for all the sites I tried in a
non-private tab, It does not work for any of those sites in a private
tab. 
 
The title of the issue should probably be "Bravery bug greys out in
private tabs"
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by DcyMatrix** [comment] 2016-06-02 03:47
I can confirm this issue on Ubuntu 14.04LTS

The orange "Brave" logo is grayed out when opening a private tab, and going to any site. Includes the buildt in duckduckgo.com search engine. The grayed out logo does not respond to mouse click. As it normally would do when not grayed out.

**Comment by bbondy** [comment] 2016-06-02 13:07
yes you currently can't use the Bravery panel in private sites, we'll get to it soon though.

**Comment by cfumante** [comment] 2016-06-02 16:22
thanks
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by diracdeltas** [comment] 2016-06-14 21:58
closing this as a duplicate of https://github.com/brave/browser-laptop/issues/1824

**Closed by diracdeltas** 2016-06-14 21:58 UTC
