### ISSUE TITLE
Mojave: Crash when downloading any file

### ISSUE THREAD

**Issue by da2x** [brave/browser-laptop#14346] opened 2018-06-06 23:44 UTC
1. Go to https://developer.apple.com/safari/download/(or any other download page)
2. Click to download the file, choose where to save it, and confirm

Expected: file download.

Actual: instant crash.

Brave: 0.22.727

Environment: macOS 10.14 Mojave beta (18A293u)

Stack trace: https://gist.github.com/da2x/401faa345503837684c62e304ddc9e46

**Comment by coasttech** [comment] 2018-06-08 23:47
same issue

**Comment by coasttech** [comment] 2018-06-08 23:47
No issue with Chrome

**Comment by da2x** [comment] 2018-06-09 01:53
No issue with Vivaldi either (another Chromium browser).

**Comment by rojour** [comment] 2018-07-19 13:45
same issue here.
No issues with Chrome, Chrome Canary, Opera Developer, Safari.

**Comment by LaurenWags** [comment] 2018-07-19 22:15
+1 from community: https://community.brave.com/t/brave-crashes-to-desktop-on-download-macos/27280

**Comment by Hyracan** [comment] 2018-07-26 16:17
Same here, issue only with Brave

**Comment by mdaneri** [comment] 2018-07-28 23:35
Same problem here

**Comment by mitchwagner** [comment] 2018-07-28 23:52
I also have this issue. MacOS 10.14 Beta. Brave 0.23.39. Firefox and Chrome do not have the problem.

**Comment by bsclifton** [comment] 2018-07-31 16:05
Possibly fixed by https://github.com/brave/muon/commit/4504af1ad2a704729365f0bbab821c00ea357008 (which is scheduled for 0.23.x Release 5).  I'll assign that milestone so we can test

**Comment by LaurenWags** [comment] 2018-08-02 19:51
@da2x @coasttech @rojour @Hyracan @mdaneri @mitchwagner mind downloading https://github.com/brave/browser-laptop/releases/tag/v0.23.74dev and seeing if this issue is resolved? note - there are some crashes in this build which we're working through viahttps://github.com/brave/browser-laptop/issues/14893 , so be advised if you give it a spin.

**Comment by LaurenWags** [comment] 2018-08-03 16:38
from @rojour over on another issue, using 0.23.77 on Mojave is still crashing once the download is complete https://github.com/brave/browser-laptop/issues/14893#issuecomment-410307879

**Comment by eljuno** [comment] 2018-08-05 17:27
+1 from community https://community.brave.com/t/mojave-beta-browser-force-closes-when-attempting-to-download-files/29133?u=eljuno

**Comment by bsclifton** [comment] 2018-09-09 06:12
I don't have Mojave so I can't test this... but I suspect the issue is fixed with our new [developer channel release](https://brave.com/download-dev) (brave-core). Can someone please give this a shot?

Closing here as `wontfix` because we won't be fixing in this code-base

**Closed by bsclifton** 2018-09-09 06:12 UTC
Labels: OS/macOS, QA/test-plan-specified, crash

**Comment by mitchwagner** [comment] 2018-09-09 13:32
@bsclifton

Using the following:
MacOS: 10.14 Beta (18A365a)
Brave: 0.23.105

I was able to download several files without issue.

I also tried the new developer channel release: 
MacOS: 10.14 Beta (18A365a)
Brave: Version 0.55.2 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)

I was again able to download files without issue.

**Comment by bsclifton** [comment] 2018-09-09 16:40
@mitchwagner awesome! Thanks for the update 😄 👍

**Comment by stshank** [comment] 2018-09-09 23:50
No problems downloading on Brave Core Dev on MacOS Mojave beta 10 for me.

**Comment by kjozwiak** [comment] 2018-09-10 00:11
awesome, thanks for checking/verifying @stshank 👍 Really appreciate the update.
