### ISSUE TITLE
Pinned Tabs are Present in all Windows

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6483] opened 2016-12-31 01:23 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Brave displays pinned tabs in ad-hoc popup windows. As a result, popup documents with a "Close window" link do not close the window, but rather than the active tab.

**Expected behavior:**
Popup windows should probably not show pinned tabs.

**Platform:** macOS/Windows

**Brave Version (revision SHA):** 0.13.0

**Steps to reproduce:**
1. (With at least one pinned tab) Navigate to https://www.amazon.com/gp/navigation/redirector.html
2. Click "Details" link
3. In popup, click "Close window"

**Comment by bbondy** [comment] 2016-12-31 19:56
Moving to .13.1 because I think this has been there always and we're only accepting introduced from  .12.15 regressions at this point for this release.

**Comment by jonathansampson** [comment] 2017-01-08 01:55
+1 from Twitter:

> Alan Plum @lnplum
> Pain points after 1 day of @Brave
> - **pinned tabs are reopened in all windows**
> - freeze on reopening w 20 tabs but YT autoplays w no way 2 stop

Source: https://twitter.com/lnplum/status/817861336088637440

**Comment by darkdh** [comment] 2017-01-25 09:37
+1 from me because it is painful for oauth popup window.
it will slow down oauth tab loading when pinned tabs are loading simultaneously.

**Comment by darkdh** [comment] 2017-01-25 16:38
This is actually regression
Popup window don't show pinned tab in 0.12.15
Try http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_open5

**Closed** 2017-01-25 16:38 UTC
Labels: feature/pinned-tabs, feature/tabsbar, regression
