### ISSUE TITLE
About pages shows a dot in the page load timer 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6441] opened 2016-12-28 12:10 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
About pages shows a dot in the page load timer 

**Expected behavior:**
Should not show the dot 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Master 

- Steps to reproduce:
    1. Build from master
    2. Open any about page
    3. Shows a dot in the page load timer 

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/21521556/0aaca55c-ccf6-11e6-8e93-2e49482fb2f5.png)

- Any related issues:
@jkup 
  Please change the milestone if required

**Comment by bsclifton** [comment] 2016-12-29 18:54
I can't reproduce; I've done a full build of browser-laptop-bootstrap and I'm running latest browser-laptop.  [Per this code](https://github.com/brave/browser-laptop/blob/master/js/components/urlBar.js#L530), the "loadTime" span won't show on about pages

Closing issue- if you see it again, please use shift+f8 to load the DOM and let's get more information about the element that's being shown

**Comment by luixxiul** [comment] 2016-12-30 03:29
I could reproduce the error.

STR:
1. Open a new tab
2. Do not click anywhere
3. Seleft a new tab
4. Do not click anywhere

**Comment by bbondy** [comment] 2016-12-30 03:35
I can reproduce too.
Regression range wanted, this is new since preview 5 isn't it?

**Comment by luixxiul** [comment] 2016-12-30 03:41
For me, yes it is.

**Comment by jkup** [comment] 2016-12-30 03:45
@bsclifton feel free to assign to me if you are busy with other stuff!

**Comment by luixxiul** [comment] 2016-12-30 11:17
I think this displays the dot:
https://github.com/brave/browser-laptop/blob/55604ccb5289d78b0185a33a855ead6b991fb903/less/navigationBar.less#L673

Also the input area overflows, which I think is a regression.

1 Copy the URL above
2 Paste it into the URL input area
3 Hit the right arrow key

**Comment by bsclifton** [comment] 2016-12-30 19:17
@jkup that would be great thanks! :smile:

**Closed** 2017-01-06 00:06 UTC
Labels: bug, feature/URLbar, release/not-blocking

**Comment by luixxiul** [comment] 2017-01-16 18:37
Test plan: https://github.com/brave/browser-laptop/pull/6546#issue-199085537
