### ISSUE TITLE
Right click "Search for" action creates incorrect search

### ISSUE THREAD

**Issue by sirhamster** [brave/browser-laptop#5646] opened 2016-11-15 21:26 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When using right click context menu "Search for ...", if the selected text includes a "." at the end, it will create an incorrect Google search.

The search is incorrect as "https://www.google.com/search?q=" is prefixed to the desired text, and the Google results will not match the desired search text.   

**Expected behavior:**
The Google search created should match the selected text.   

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win7

- Brave Version:
0.12.9

- Steps to reproduce:
    1. Select text that ends with a period using mouse left click.
    2. Right click to open context menu.
    3. Click 'Search for "<text>."'
    4. Created search page shows issue.

- Screenshot if needed:

Using right click menu to search for "term."
![image](https://cloud.githubusercontent.com/assets/19482933/20324665/31467f62-ab36-11e6-94d1-042b3a015b08.png)

The expected search for "term."
![image](https://cloud.githubusercontent.com/assets/19482933/20324760/9ed05346-ab36-11e6-9ff2-c01242ee9e81.png)

- Any related issues:

**Comment by Liunkae** [comment] 2016-11-16 01:14
This is a duplicate of issue #5083. I'll make a note there about this issue.

**Closed by Liunkae** 2016-11-16 01:14 UTC
