### ISSUE TITLE
Drag and Drop Tab to Bookmark Folder Create a New Window

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#10007] opened 2017-07-16 21:40 UTC
- Did you search for similar issues before submitting this one?
Yes, but maybe I missed the existing issue

- Describe the issue you encountered:
[From community](https://community.brave.com/t/possible-bug-cant-drag-open-tabs-into-bookmark-folder/4794)

> If you attempt to click, drag, and drop an open tab into a bookmark folder in the bookmark menu ... I cant seem to prevent it from moving that open tab into a new window.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows. Reproduce in Win8.1

- Brave Version (revision SHA):
0.17.16

- Steps to reproduce:
    1. Create new bookmark folder
    2. Open a new tab
    3. Drag and drop tab to bookmark folder/bookmark folder pulldown
    
- Actual result:
Dragging tab to folder only create a new window.
Dragging tab to folder pulldown create bookmark and a new window.

- Expected result:
Tab is bookmarked without creating new window

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![brave-drag-tab-to-folder-bug](https://user-images.githubusercontent.com/25360853/28251474-e61079e4-6aa7-11e7-884a-c7ad2904c457.gif)

- Any related issues:
Maybe related to #5193 (for drag and drop tab to bookmark folder)

**Comment by bsclifton** [comment] 2017-07-22 06:52
This is a duplicate of https://github.com/brave/browser-laptop/issues/9211

I'll capture some notes there and give it a +1 😄

**Closed by bsclifton** 2017-07-22 06:52 UTC
Labels: feature/bookmarks, misc/drag-and-drop
