### ISSUE TITLE
Pin tabs which are loaded causes a crash

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7187] opened 2017-02-11 07:07 UTC
**Describe the issue you encountered:**
Pinning tabs which are loaded causes a crash.

- Platform (Win7, 8, 10? macOS? Linux distro?): WIndows 10 32 bit

- Brave Version (revision SHA): 0.13.3 RC1

- Steps to reproduce:
    1. Clear your brave folder
    2. Open https://github.com
    3. Click the menu on the page to open 4 tabs
    4. Pin all of them **fast**, before they are loaded completely
    
- Actual result: the browser crashes

![crash](https://cloud.githubusercontent.com/assets/3362943/22851918/f2d5c80e-f073-11e6-8445-5dda7a929482.gif)

- Expected result: the browser should not crash

- Will the steps above reproduce in a fresh profile? Yes

- Can this issue be consistently reproduced? Yes

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment] 2017-02-11 07:11
If you pin tabs after they are loaded, the browser does not crash.

![crash](https://cloud.githubusercontent.com/assets/3362943/22851939/a106f97a-f074-11e6-859d-51cbe2a844c3.gif)

**Comment by Liunkae** [comment] 2017-02-12 20:57
I can't reproduce with 0.13.2. Probably introduced during 0.13.3.

**Comment by bsclifton** [comment] 2017-03-14 16:20
Moving to 0.14.1 (aka 0.13.7)

**Comment by bbondy** [comment] 2017-04-10 02:24
I think this crash should be gone now
https://github.com/brave/browser-laptop/pull/8084

**Closed by bbondy** 2017-04-10 02:24 UTC
Labels: bug, crash, feature/pinned-tabs

**Comment by luixxiul** [comment] 2017-04-10 12:14
I cannot reproduce the error on the latest build.
