### ISSUE TITLE
Dont show an ad without opt-in and disabled

### ISSUE THREAD

**Issue by jasonrsadler** [brave/browser-laptop#14415] opened 2018-06-14 20:29 UTC
supplement to #14413 

Ads are being shown without opt-in and also turned off.
brave-intl/internal#57

cc: @mandar-brave @mrose17

**Comment by mrose17** [comment] 2018-06-14 20:33
dupe of https://github.com/brave/browser-laptop/issues/14413

**Closed by mrose17** 2018-06-14 20:33 UTC
Labels: initiative/bat-ads, initiative/bat-ads/ads-test
