### ISSUE TITLE
Bug? : Autoplay button in youtube

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1728] opened 2016-05-13 17:28 UTC
Hello Dev Team,

im sure you are familiar with autoplay button in youtube on the right corner.

![autoplay](https://cloud.githubusercontent.com/assets/17910355/15256222/271dd44c-1949-11e6-855d-12c9eb2696ea.PNG)

whenever i switch it off it always resets when i open a new video or close and reopen the browser.

is this expected because im blocking the cookies or its a bug in brave ?

/Haze

**Comment by luixxiul** [comment] 2016-05-14 09:01
On my PC it works properly. If possible, would you please clear all cookies and site data and try again?

**Comment by stianjensen** [comment] 2016-06-14 15:45
I have the same behavior – also after allowing all cookies on youtube.com

I haven't managed to track down exactly how this happens, because after turning off autoplay it stays off for a while, but when I come back to YouTube later it might be on again.

Restarting the browser does not necessarily mean that autoplay is reset, so there must be something else going on.

**Comment by neeklamy** [comment] 2016-07-24 11:46
I’ve been seeing the exact same thing, after some indeterminate period of time autoplay switches off, and it doesn’t seem to matter whether I’m logged into YouTube or not.

This is being set through a Local Storage object.

Steps to reproduce:

1. Go to a YouTube video, for example there’s this rather nice video:  
[Brave: Potential to be the best modern web browser?](https://www.youtube.com/watch?v=WPDymX-0VeI)
2. Right click on an empty part of the page → Inspect Element.
3. Switch to the resources tab → view Local Storage → https\://www&period;youtube&period;com
4. Look for this key: `yt.autonav::autonav_disabled`, if it exists, delete it.
5. Close the developer tools window (just to be sure we have an up to date view later).
6. Reload the video page, you should find autoplay is enabled.
7. Toggle the autoplay switch back off.
8. Reload the video page one last time.
9. Again, bring up the dev tools and go back to the Local Storage section.
10. The `yt.autonav::autonav_disabled` key will have been recreated. The value will be in this form: `{"data":true,"expiration":1500461214120,"creation":1469357214120}`

By contrast, in Google Chrome, they set the same Local Storage object alongside a sort-of-cookie. This is Chrome with autoplay disabled:

![Google Chrome, YouTube autoplay status cookie?](https://cloud.githubusercontent.com/assets/155358/17083483/568ff1cc-519a-11e6-8efe-38781847d9a8.png)

Incidentally, the “Local storage” and “Session storage” sections in Chrome’s cookie inspector offer no further info, once again, that’s hidden away inside the dev tools.

So is the “cookie” really just a pointer to the LSO? It looks like it.

**Comment by luixxiul** [comment] 2017-02-07 14:13
I haven't seen this for a long time, so I'm going to close this one. Please reopen if this still can be reproduced.

**Closed by luixxiul** 2017-02-07 14:13 UTC
Labels: info-needed

**Comment by patertmg** [comment] 2017-03-06 20:06
I have the same problem. Is there a solution?

**Comment by SLJNilsson** [comment] 2017-04-12 10:48
Having the exact same issue. Any solution in sight?

**Comment by patertmg** [comment] 2017-07-10 08:22
In the meantime I reinstalled macOS Sierra 3 times from scratch, even now on a new MacBook Pro (someone spilled juice over my old one...). Thus, also Brave installed from scratch - but I'm having the same issue over and over again: Youtube autoplay is on and next video plays automatically (aaarrrrgggghhh!!). When I switch it off, after some time (or next time I log in) it's back on again - no matter whether I prohibit or allow cookies (generally, or specifically for youtube.com)... Does someone have a solution for this...??

**Comment by NejcZdovc** [comment] 2017-07-10 08:31
cc @darkdh for this thoughts

**Comment by srirambv** [comment] 2017-07-10 10:11
@patertmg  have you set the browser to clear cache after exit? I have seen that happen when the browser cache gets removed or when you open a new session tab.

**Comment by patertmg** [comment] 2017-07-10 11:30
@srirambv Thanks for helping: No, everything is checked off in preferences:
<img width="420" alt="screenshot" src="https://user-images.githubusercontent.com/17692078/28016241-cde12d3e-6573-11e7-85fb-e2e4a860c213.png">

**Comment by n8udd** [comment] 2018-05-21 13:38
Still an issue. Every time I set 'Auto-Play' to off in YouTube, the browser forgets my option, and it's reset next time I visit YT.
