### ISSUE TITLE
Link for Release Notes leads to 404

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#10370] opened 2017-08-09 17:58 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Clicking the _Release Notes_ link in `about:brave` leads to a GitHub 404.

[Reported on Twitter](https://twitter.com/halfwrittensong/status/895340766582657030).

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.18.20 ([tweet](https://twitter.com/halfwrittensong/status/895340766582657030)), 0.19.1

- Steps to reproduce:
    1. Navigate to `about:brave`
    2. Click _Release Notes_ link
    
- Actual result:
A 404 is presented

- Expected result:
Release notes are presented

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by Liunkae** [comment] 2017-08-09 18:09
0.19.x is still in beta, so there's no release notes yet.

**Comment by jonathansampson** [comment] 2017-08-09 18:11
@Liunkae This happened for a user on 18.20 as well. See [this tweet](https://twitter.com/halfwrittensong/status/895340766582657030). If we have a link there, it should lead someplace other than a 404.

**Comment by Liunkae** [comment] 2017-08-09 18:12
0.18.20 is still in beta too. 😉  0.18.14 is the current release.

**Comment by luixxiul** [comment] 2017-08-09 18:15
It works for me on 0.18.20.

Maybe the link was not correctly applied when the user opened `about:brave`. I remember I experienced the similar issue, and for me the link was not defined, ie `https://github.com/brave/browser-laptop/releases/tag/undefined`. I'm not sure how to reproduce the issue.

**Comment by clairelo** [comment] 2017-08-11 23:44
Versions etc are in my tweet thread, but I didn't open about. It was from your most recent dev version and it was the message that popped up after I updated (not from about). It's been happening for a few versions now for me. Try signing out of GitHub to reproduce.

**Comment by bsclifton** [comment] 2017-08-22 20:06
Closing this as a dupe of https://github.com/brave/browser-laptop/issues/10515.  I believe the problem is that Beta builds have never worked properly on Windows.  Because they were marked as `dev` instead of beta, they would be linking to a non-existent version of the issue

**Closed by bsclifton** 2017-08-22 20:06 UTC
Labels: bug, feature/about-pages
