### ISSUE TITLE
Saved form values not useable on windows

### ISSUE THREAD

**Issue by JAffleck** [brave/browser-laptop#5856] opened 2016-11-27 00:21 UTC
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
When typing a form value in, an autocomplete (or saved form values pop up) but are unusable.

**Expected behavior:**
I assume when typing in a value that matches a previous value entered (such as a username in a form field) that the old values should be selectable in some fashion (either with the mouse, or by hitting arrow keys and enter), but on my laptop they just show up and disappear immediately (it's a touchpad on a Toshiba laptop)

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 7
- Brave Version:
0.12.10
- Steps to reproduce:
    1. Go to a url with a form (e.g. github login)
    2. start typing a form value that was previously entered
    3. (the saved values immediately disappear)

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment] 2016-11-27 21:08
Duplicate of #5438. This bug is planned to fixed in the next release, 0.13.0.

**Closed by Liunkae** 2016-11-27 21:08 UTC
