### ISSUE TITLE
Need a whitelist for the "block script" option

### ISSUE THREAD

**Issue by mickaphd** [brave/browser-laptop#15233] opened 2018-09-26 22:10 UTC
The option is useless without a real whitelist compared to the real extension in Firefox for example. For now we can just "Allow this time" or "Allow until restart" some specific scripts. Please add an option "For ever!!". 
Thanks

**Comment by eljuno** [comment] 2018-09-27 19:52
Duplicate of #5117 and #9307?

**Comment by bsclifton** [comment] 2018-09-28 07:08
@eljuno yup- good catch. Closing as a duplicate

@mickaphd if you'd like to try out new Beta release, this should be partially addressed (ex: you should be able to choose "Forever")
https://brave.com/download-beta

Option available in the Beta would look like this:
![screen shot 2018-09-20 at 11 10 44 pm](https://user-images.githubusercontent.com/4733304/45863340-9ae86e00-bd2a-11e8-93e7-8d3ec409252f.png)

**Closed by bsclifton** 2018-09-28 07:08 UTC
