### ISSUE TITLE
tabs on about:preferences cannot be switched

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5250] opened 2016-10-29 09:21 UTC
**Describe the issue you encountered:** tabs on ``about:preferences`` cannot be switched.

![preferences](https://cloud.githubusercontent.com/assets/3362943/19828562/40578990-9e04-11e6-9dc2-38ab11eadb85.gif)

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.7

- Any related issues:

**Comment by luixxiul** [comment] 2016-10-29 09:23
````
Uncaught TypeError: Cannot read property 'className' of null
4about-preferences.html#payments:1 (BLESSED_EXTENSION context for mnojpmjdmbbfmejpflffifhffcmidifd) chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/gen/aboutPages.entry.js:12656: Uncaught TypeError: Cannot read property 'getHostNode' of null{TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/gen/aboutPages.entry.js:12656:29)
    at ReactCompositeComponentWrapper.getHostNode (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/gen/aboutPages.entry.js:47034:29)
    at Object.getHostNode (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/gen/aboutPages.entry.js:12656:30)
    at Object.updateChildren (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/gen/aboutPages.entry.js:46570:49)
    at ReactDOMComponent._reconcilerUpdateChildren (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/gen/aboutPages.entry.js:50817:29)
    at ReactDOMComponent._updateChildren (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/gen/aboutPages.entry.js:50916:32)
    at ReactDOMComponent.updateChildren (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/gen/aboutPages.entry.js:50903:13)
    at ReactDOMComponent._updateDOMChildren (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/gen/aboutPages.entry.js:48646:13)
    at ReactDOMComponent.updateComponent (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/gen/aboutPages.entry.js:48464:11)
    at ReactDOMComponent.receiveComponent (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/gen/aboutPages.entry.js:48422:11)}
````

This seems to be duping to #5236 /cc: @bsclifton

**Comment by bsclifton** [comment] 2016-10-29 09:38
Dupe of https://github.com/brave/browser-laptop/issues/5236

Was fixed with https://github.com/brave/browser-laptop/pull/5237

**Closed by bsclifton** 2016-10-29 09:38 UTC
Labels: regression
