### ISSUE TITLE
Spotify no longer plays music

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#6881] opened 2017-01-26 23:19 UTC
- Did you search for similar issues before submitting this one?

Yes

- Describe the issue you encountered:

Spotify is no longer working. When I go to the web player, it get an error. See screenshot.

There are JS errors. I'll attach a second screenshot showing them.

- Platform (Win7, 8, 10? macOS? Linux distro?):

OS X 10.11.6

- Brave Version (revision SHA):

0.12.15 and 0.13.0

- Steps to reproduce:
    1. Go to play.spotify.com
    2. Login to Spotify
    3. You'll be redirected to open.spotify.com
    4. You should see the error in the screenshot below and songs will not play. You should also see the JS errors in the console.
    
- Actual result:

Songs don't play. Error is displayed.

- Expected result:

Songs should play without error.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes

- Is this an issue in the currently released version?

Yes

- Can this issue be consistently reproduced?

Yes

- Screenshot if needed:

<img width="436" alt="screen shot 2017-01-26 at 5 13 14 pm" src="https://cloud.githubusercontent.com/assets/133786/22354558/7992b806-e3eb-11e6-80c8-5c2f4082eb2a.png">

<img width="1063" alt="screen shot 2017-01-26 at 5 18 07 pm" src="https://cloud.githubusercontent.com/assets/133786/22354563/7de41efe-e3eb-11e6-8d9f-3f70d2e39fe0.png">

**Comment by echosa** [comment] 2017-01-26 23:20
The multiple `NO_TRACK_PLAYER` errors are there because I clicked "play" multiple times. Each click of "play" results in another error.

**Comment by echosa** [comment] 2017-01-27 14:50
No different with shields off. In fact, I'd already turned shields off before reloading that taking those screenshots. I forgot to mention that in the initial issue. Sorry about that.

**Comment by Liunkae** [comment] 2017-01-27 18:39
Please try again with version 0.13.0 now that it's out.

**Comment by echosa** [comment] 2017-01-27 18:47
Not fixed. Still happening in 0.13.0.

**Comment by starkos** [comment] 2017-02-05 18:47
FWIW, this is happening in Musicality too. The Spotify redesign seems to be looking for something Chrome specific, and getting unhappy when it can't find it. Not sure what it is yet though…

**Comment by starkos** [comment] 2017-02-19 17:33
Found the problem, but not sure how to fix it yet. This code:

```javascript
n = {
                initDataType: void 0,
                audioCapabilities: [{
                    contentType: 'audio/mp4; codecs="mp4a.40.2"',
                    robustness: ""
                }],
                distinctiveIdentifier: "optional",
                persistenceState: "optional",
                sessionTypes: ["temporary"]
            };

navigator.requestMediaKeySystemAccess("com.widevine.alpha", [n])
```

Succeeds in Chrome, but fails with an uncaught DOMException "Unsupported keySystem" in Electron.

**Comment by starkos** [comment] 2017-02-19 18:02
Okay, I found the source of the error, though I'm not sure how to fix it. This code in web-player.js:

```javascript
n = {
                initDataType: void 0,
                audioCapabilities: [{
                    contentType: 'audio/mp4; codecs="mp4a.40.2"',
                    robustness: ""
                }],
                distinctiveIdentifier: "optional",
                persistenceState: "optional",
                sessionTypes: ["temporary"]
            };

return t.navigator.requestMediaKeySystemAccess("com.widevine.alpha", [n]).then(function(e) {
                return e.createMediaKeys()
            }).then(function(t) {
                return e._mediaKeys = t,
                e._player.setMediaKeys(t)
            }).then(function() {
                return e._trySetServerCertificate()
            });
```

…works in Chrome, but throws a DOMException "Unsupported keySystem" in Electron.

Electron does [provide a way to use Chrome's WideVine plugin](http://electron.atom.io/docs/tutorial/using-widevine-cdm-plugin/). But when I tried this, the Spotify code continued to throw the same exception, even though running the code in the Devtools Console worked fine. Not sure what's going on there.

**Comment by luixxiul** [comment] 2017-02-19 18:07
@starkos Brave has the option to enable Widevine on about:preferences#security. Would you please try with the option enabled?

**Comment by starkos** [comment] 2017-02-21 13:35
I don't have access to the redesign myself, I was given access to someone's machine via a screen share to try and figure it out. Not sure when I'll get the chance to try again, but I'm hoping to send them a WideVine-enable builds (via the Electron command-line options) shortly.

@echosa, can you give it a try?

**Comment by echosa** [comment] 2017-02-21 14:18
Spotify works with Widevine enabled! Even with shields up! <3

**Comment by luixxiul** [comment] 2017-02-21 14:46
@diracdeltas Is it possible to display Widevine control dialog on Spotify automatically as we do on Netflix?

**Comment by Liunkae** [comment] 2017-02-21 17:01
@luixxiul We need to add Spotify [here](https://github.com/brave/browser-laptop/blob/master/js/components/frame.js#L586).

**Comment by diracdeltas** [comment] 2017-02-21 19:29
cc @bbondy on adding widevine

**Comment by bbondy** [comment] 2017-02-22 18:06
should be straightforward to add for 0.13.6, I'll check.

**Comment by bsclifton** [comment] 2017-03-14 08:50
Moving to 0.13.7

**Comment by bsclifton** [comment] 2017-04-04 16:14
Moving to 0.14.2... @bbondy I know you added the Amazon check- please feel free to pull this back in if you have a solution 😄

**Comment by Liunkae** [comment] 2017-04-07 05:37
PR: #8111 Note: The PR is a possible solution, and I did not verify if it works.

**Closed** 2017-04-13 02:23 UTC
Labels: plugin/widevine

**Comment by bbondy** [comment] 2017-04-13 02:27
Moved back to 0.14.2 since there's not much risk here and alex tried the PR and confirmed fixed.

**Comment by alexwykoff** [comment] 2017-04-22 00:42
I wasn't prompted for the Widevine player but it worked anyway.

**Comment by srirambv** [comment] 2017-04-24 11:35
Shows the prompt immediately on visit similar to Netflix
