### ISSUE TITLE
Drag-and-dropping files kills the browser (everything goes white)

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#7431] opened 2017-03-01 17:37 UTC
- Did you search for similar issues before submitting this one?

Yes. The closest I've found is this, but not sure if its the same issue I'm experiencing: 
https://github.com/brave/browser-laptop/issues/7266

- Describe the issue you encountered:

When I try to drag-and-drop a file from my desktop into a webpage that accepts drag-and-drop (for instance, GitHub or Jira), the brave window goes *completely* white (no URL bar or anything) and I have to quite and restart Brave. This just happened again as I was testing it, and I lost my open tabs when I restarted Brave.

- Platform (Win7, 8, 10? macOS? Linux distro?):

OS X 10.11.6

- Brave Version (revision SHA):

0.13.5 (e01a2a9c5e8ecc36d6902e77d50361f14ce58e48)

- Steps to reproduce:
    1. Go to a site that allows for drag-and-drop.
    2. Drag and drop a file.
    
- Actual result:

It should work.

- Expected result:

Brave goes completely white. See screenshot.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes

- Is this an issue in the currently released version?

Yes

- Can this issue be consistently reproduced?

Yes (happens to me every time)

- Screenshot if needed:

<img width="1478" alt="screen shot 2017-03-01 at 11 30 47 am" src="https://cloud.githubusercontent.com/assets/133786/23472704/6905bbf8-fe73-11e6-8214-f5f54b2ebbe5.png">

- Any related issues:

As stated before, this might be related: https://github.com/brave/browser-laptop/issues/7266

**Comment by bsclifton** [comment] 2017-03-01 21:24
@echosa if you can narrow it down to an exact set of steps or use a software like LICEcap to record this happening (so we can see the details of the steps you take), that would be awesome!

This is indeed a dupe of https://github.com/brave/browser-laptop/issues/7266; I'll give that one a bump and share your screenshot.

I've had this happen too and it's super annoying.  @NejcZdovc and I have been trying to find a definitive set of steps to reproduce without luck

**Closed** 2017-03-01 21:25 UTC
Labels: duplicate
