### ISSUE TITLE
Hopely and Lilo as Search Engine option please.

### ISSUE THREAD

**Issue by Hempthusiast** [brave/browser-laptop#13388] opened 2018-03-05 13:09 UTC
Everything said in the title; I normally use Hopely and a friend use Lilo. Thank you everymuch!

**Comment by bn0785ac** [comment] 2018-03-05 18:22
i want some   *extotic/edgy* search engines too

* disconnect (its used by tor)

* searx

* metager

* peekier (its cute )

* startpage / lxquick

**Comment by Hempthusiast** [comment] 2018-03-05 19:17
So you find that Hopely, a search engine that gives fund to Doctor without Border, World Wide Fund and Bread for the World... and also Lilo, who fund projects from NGO; edgy ?

**Comment by Tomatoshadow2** [comment] 2018-03-05 20:20
Searx and Startpage are already options to pick from for search.

**Comment by srirambv** [comment] 2018-03-06 19:58
Dupe of https://github.com/brave/browser-laptop/issues/3053  ?

**Comment by Tomatoshadow2** [comment] 2018-03-07 12:19
@srirambv Yes, it is.

**Closed** 2018-03-07 14:49 UTC
Labels: feature/search, suggestion
