### ISSUE TITLE
Add a Task Manager, à la Google Chrome

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#10338] opened 2017-08-08 17:12 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Brave presently does not offer a way to identify PID for tabs and memory/CPU usage.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Screenshot if needed:

![image](https://user-images.githubusercontent.com/815158/29084677-6d88145e-7c32-11e7-8668-5e0e9a86fb5a.png)

**Comment by gojomo** [comment] 2017-08-08 18:19
Even an "about:processes" tab, with a single snapshot of PID->tab mappings, would be a great help/start.

**Comment by Liunkae** [comment] 2017-08-08 20:38
Duplicate of #1547. See also #4368.

**Closed** 2017-08-08 23:13 UTC
Labels: duplicate, enhancement
