### ISSUE TITLE
File menu opens when pressing alt+shift to change keyboard layout (Archlinux)

### ISSUE THREAD

**Issue by koukjo** [brave/browser-laptop#1855] opened 2016-05-21 18:30 UTC
**Did you search for similar issues before submitting this one?**
similar to #1210 that is resolved

**Describe the issue you encountered:**
When pressing alt+shift to change keyboard layout file menu appears immediately after you press shift button.

**Expected behavior:**
As soon as alt_shift is pressed you should be able to type using the new layout.
- Platform (Win7, 8, 10? OS X? Linux distro?):
  Archlinux
- Brave Version:
  0.10.0
- Steps to reproduce:
  1. Open brave browser
  2. Press alt+shift
- Screenshot if needed:
  N/A
- Any related issues:

**Comment by luixxiul** [comment] 2016-05-22 12:03
On Windows 10, this cannot be reproduced.

**Comment by bbondy** [comment] 2016-05-22 13:25
Do you mean the menu bar? Or does the File menu actually get expanded?

**Comment by koukjo** [comment] 2016-05-23 16:30
Thank you for your reply.

File menu gets expanded. 
I hope the screenshot below may help you better than my explenation.

![brave_file_menu](https://cloud.githubusercontent.com/assets/19242352/15477276/5a9eaf64-211c-11e6-97e9-68d4c719ff89.png)

Thank you for your time.

**Comment by bsclifton** [comment] 2016-05-24 03:28
This might be intentional (see https://github.com/brave/browser-laptop/issues/1210#issuecomment-221156335)

Pressing alt should be toggling the menu as part of the default behavior for electron's browser window

**Comment by bbondy** [comment] 2016-05-24 14:31
@bsclifton I think showing the menu bar might be intentional but not expanding the File menu right?

**Comment by bsclifton** [comment] 2016-05-24 14:52
@bbondy ah, good call- correct, the File menu should definitely not be expanding

**Comment by bsclifton** [comment] 2017-03-04 00:50
Closing this issue as a duplicate of https://github.com/brave/browser-laptop/issues/5540

Please subscribe to that issue to get updates. Thanks! 😄

**Closed by bsclifton** 2017-03-04 00:50 UTC
Labels: OS/linux-distros
