### ISSUE TITLE
Integration of tabs with title dragbar and other *important* UI considerations

### ISSUE THREAD

**Issue by RobertoMalatesta** [brave/browser-laptop#1953] opened 2016-05-28 07:28 UTC
Hi guys, a few things hoping to help:

**Application Titlebar not integrable with UI**
At least on KDE Linux, the title-bar of the program shows up unnecessarily stealing space from page.
Chromium build integrate tabs into it resulting more consistent and freeing pixel for the content.

![Chromium Tab+Address and Titlebar Integration](https://cloud.githubusercontent.com/assets/11835025/15625651/4fbdea60-24af-11e6-9f56-eb11d53c37c3.jpg)

**Tab->Address Hierarchy is the universal standard**

Since the address bar value is dependent on the selected tab, the address should be INSIDE the tab itself (it is a tab-related value).
That's the way most web browsers organize tabs and address info and that's the kind of hierarchy today's user are accustomed to. Even Firefox got it right (!)

Breaking it goes against a well-established flow of attention concerning muscular memory (both fingers and eyes involved).

You had it right for free in chromium CVS and I don't know why you decided to spend time into reverse-implementing it.

The result seems really sub-optimal and hackish to me (I know it's a beta) 
reminding of a **\* CDF/Motif X11 Mosaic interface from 1994***.
Well, maybe I'exagerating a tad bit... but when something starts fixed I never see a reason to break it.

With a lesser effort than full reorganization of the tab UI you could have simply customized the L&F of tabs and the position of the main menu (topmost corner left) just like Vivaldi does, resulting in a fresh take of the somehow outdated beveled skewy tabs chrome has.

![Vivaldi's tabs are the nicest part of it. A simple well-thought restyle resulted in a more modern and happy interface -- the only reason I sometime still use it](https://cloud.githubusercontent.com/assets/11835025/15625703/6311ca12-24b1-11e6-9405-b7af03dce7d5.jpg)

Besides, you should think to enterprise users (Wally from Dilbert being one of the most skilled ones), those who have have been held on captivity for eons into IE and now were relocated to Chrome, Firefox and started feeling comfortable with the tab -> address paradigm.
The less you change the more chance companies will adopt Brave.

Apart this and a few other tidbits your work is SUPER.

Thank you for your time and for a great product.

-- RM

PS: I feel really guilty for not following the guidelines for contributing.
Next time for sure.

**Comment by luixxiul** [comment] 2016-05-28 09:14
If you have an idea please send a PR to contribute, thanks :-)

**Comment by SJ-Diamond** [comment] 2016-05-28 09:57
Tabs on top. I really dislike that. Only as optionally function please. Chromium way is not the only way to do it.

**Comment by RobertoMalatesta** [comment] 2016-05-28 11:35
@luixxiul what do you need in a PR ?

**Comment by luixxiul** [comment] 2016-05-28 12:01
Anything.. at first you would need to check out the source code, create an concept of UI, and propose it to the dev team before sending a PR, so that the team could discuss it.

**Comment by RobertoMalatesta** [comment] 2016-05-28 13:31
Time's tight on my side but I'll definitely check it.
Don't hold your breath. --R

**Comment by luixxiul** [comment] 2016-05-29 10:22
@SJ-Diamond PRs from you are also welcomed if you have any idea to improve

**Comment by bsclifton** [comment] 2016-09-19 15:42
@RobertoMalatesta Partial progress will be made towards this goal once https://github.com/brave/browser-laptop/pull/3854 is accepted

([basically fixes the Windows custom titlebar, getting rid of the wasted space](https://github.com/brave/browser-laptop/issues/3036))

There is a Linux equivalent for this- be sure to leave a comment or +1 the original post so we can prioritize it accordingly :smile: 
https://github.com/brave/browser-laptop/issues/3126

**Comment by RobertoMalatesta** [comment] 2016-09-19 16:26
Great @bsclifton. I will follow the thing down and feedback. :beers: 
--R

**Comment by bsclifton** [comment] 2016-09-19 16:50
5 +1's this morning from Twitter:
https://twitter.com/mmdts/status/777903090112589824
https://twitter.com/jwmcpeak/status/777909376162013185
https://twitter.com/egavrin/status/777895261351841792
https://twitter.com/Seboss/status/777909914140368896
https://twitter.com/waddlesplash/status/777894374684459008

**Comment by RobertoMalatesta** [comment] 2016-09-19 16:53
I'm more on having the tabs topmost 
(just like https://twitter.com/mmdts/status/777903090112589824 says)
but your fix goes in the right way anyway.

--R

**Comment by davewallace** [comment] 2016-09-21 22:20
Perhaps to maximise viewport real estate while allowing for cross-browser UX familiarity (if that is even the goal), consider adopting a mobile-first approach for the desktop app that is evident in some other mobile OS browsers, by transitioning the entire URL bar into a condensed or hidden format when the page has been scrolled by some configurable value (configuration might also disable this behaviour).

**Comment by luixxiul** [comment] 2017-11-04 12:40
Closing as duplicate of https://github.com/brave/browser-laptop/issues/973

**Closed by luixxiul** 2017-11-04 12:40 UTC
Labels: design, suggestion
