### ISSUE TITLE
Bookmarks title changes when navigating around the page

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#3646] opened 2016-09-01 19:39 UTC
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
It seems like the title in the bookmarks bar changes as you navigate around the site. For example, I bookmarked twitter.com so the title says Twitter. When I navigate to twitter's notifications tab the title changes in my bookmarks bar to Twitter / Notifications.

**Expected behavior:**

It should stay the same.
- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS
- Brave Version:

0.11.6
- Steps to reproduce:
  1. Bookmark twitter.com
  2. Make sure bookmarks bar is showing
  3. Visit twitter.com and then go to notifications
  4. Notice the title changes, causing the bookmarks to visibly move around
- Screenshot if needed:

![bug](https://cloud.githubusercontent.com/assets/490294/18181661/0f84a208-7041-11e6-8ced-710f5b48bad6.gif)
- Any related issues:

**Comment by charbelrami** [comment] 2016-09-01 20:58
Reproduced on macOS
I'm not able to reproduce on Win 10

**Comment by srirambv** [comment] 2016-09-26 12:01
+1 from [support ](https://linkbubble.zendesk.com/agent/tickets/5591)

>The favorites I have chosen change their names every time I click on something on that page

**Comment by NejcZdovc** [comment] 2017-07-20 11:49
This should be fixed in #9979

**Closed** 2017-08-04 16:17 UTC
Labels: bug, feature/bookmarks
