### ISSUE TITLE
Not keeping browser height after close-reopen

### ISSUE THREAD

**Issue by fast928** [brave/browser-laptop#5537] opened 2016-11-10 16:02 UTC
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Does not keep closing height after reopen. Only keeps width when height not changed.
**Expected behavior:**
Keep width & height & position on screen when opened as when last closed
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10
- Brave Version:
0.12.8
- Steps to reproduce:
    1. Open brave, drag corner to change height/width
    2.close browser
    3.reopen browser

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment] 2017-11-05 07:41
I see a similar issue related this one.

STR:

1. Have two windows opened (with one pinned tab for both windows)
2. Open several tabs and load pages on both windows
3. Change Window 1 height
4. Close and restart the browser

Expected result: Window 1 height should be restored
Actual result: **Window 2** height is changed to that window 1 height

I have not tried with a clean profile. Neither am I sure if this can be reproduced on previous versions.

Does anyone see the issue?

**Comment by luixxiul** [comment] 2017-11-06 09:23
It looks like the issue has been fixed on 0.20.x. I'm going to close the issue 😄

**Closed by luixxiul** 2017-11-06 09:23 UTC
Labels: needs-investigation, settings
