### ISSUE TITLE
After manual check for update the hide button take multiple clicks to function

### ISSUE THREAD

**Issue by Tombsmen** [brave/browser-laptop#598] opened 2016-02-03 17:14 UTC
If you manually check for update and no update is found the Hide button take about 3 clicks before it acknowledges it has been clicked and closes the notification bar.

**Comment by bbondy** [comment] 2016-02-05 15:59
Not able to reproduce this one

**Comment by Tombsmen** [comment] 2016-02-05 16:48
Please wait for follow up video.

**Comment by Tombsmen** [comment] 2016-02-05 18:09
I will ahve to do a screen share sesion with something like Join.me or team viewer VLC keeps crashing when I try to record my screen, just let me know when Brian.

**Comment by bbondy** [comment] 2016-02-05 19:46
I'll take a look at the code later to see if I can find a work around without reproducing.

**Comment by luixxiul** [comment] 2016-05-16 13:58
Closing for now. If someone could reproduce please tell us how to.

**Closed by luixxiul** 2016-05-16 13:58 UTC
