### ISSUE TITLE
URL and tab bar do not hide in full screen mode

### ISSUE THREAD

**Issue by satnatantas** [brave/browser-laptop#11463] opened 2017-10-11 22:11 UTC
*Requires #2775 to be fixed*

### Description
URL and tab bar are not hidden in full screen mode while Windows' task bar gets hidden (i.e. browser is indeed going into full screen mode).

### Steps to Reproduce
I cannot get rid of this bug.

**Actual result:**
Bars are present.

**Expected result:**
They should not.

**Reproduces how often:** 
Reproducible on my machine 100% of cases.

### Brave Version
Brave | 0.19.44
rev | e391af1
Muon | 4.4.28
libchromiumcontent | 61.0.3163.100
V8 | 6.1.534.41
Node.js | 7.9.0
Update Channel | Beta
OS Platform | Microsoft Windows
OS Release | 6.1.7601
OS Architecture | x64

Same on 0.18.36.

**Reproducible on current live release:**
Yes.

### Additional Information
https://imgur.com/a/jbLSt
It worked for few days first. Restart, reboot or installing Brave for different user changes nothing. It is very interesting how can there be any state saved between users which causes this bug. I can provide more information and try to debug this if there are guides about that.

**Comment by hugobuddel** [comment] 2017-10-17 08:33
How do you trigger full screen? I'm trying F11, but it will just maximize the window.

What I'm looking for is a way to just show the page on the screen, nothing else, no tab-bar, title-bar, any-other-bar, as well as no bars/panels from the desktop/window manager.

**Comment by luixxiul** [comment] 2017-10-17 08:46
@hugobuddel 
> What I'm looking for is a way to just show the page on the screen, nothing else, no tab-bar, title-bar, any-other-bar, as well as no bars/panels from the desktop/window manager.

How about enhancing these options on https://github.com/brave/browser-laptop/pull/11547#issue-265603202 to achieve https://github.com/brave/browser-laptop/issues/6928#issuecomment-331791272?

> ![clipboard01](https://user-images.githubusercontent.com/3362943/30795460-9c478a80-a208-11e7-9dd0-f140ca0de05d.png)

the menubar will also be able to be hidden (to achieve that we need to figure out how and where to display the menu bar)

**Comment by luixxiul** [comment] 2017-10-17 08:56
that issue on about:brave is a duplicate of https://github.com/brave/browser-laptop/issues/10711

please close this issue if the issue is covered with that. thanks!

**Comment by hugobuddel** [comment] 2017-10-17 11:45
That seems to be almost like fullscreen @luixxiul, although it still shows the menu bar in your example. And I suppose it would also show the windows taskbar and such?

Also, it seems that what is described in #11547 would require quite some manual steps to remove everything and put everything back, but perhaps I don't understand it.

What I would like is something similar to the F11 key in most other browsers (firefox, chrome, edge). That is, a quick way to maximizes the viewport of the page (to the entire screen) and to minimize distractions. E.g. when reading a long read, or when composing text.

Currently F11 maximizes/'demaximizes' the Brave window (at least in Windows). I don't think I ever needed a keyboard shortcut for that, but apparently there is one already in Windows: winkey + arrow up (or arrow down), so F11 for that is superfluous.

**Comment by luixxiul** [comment] 2017-10-17 12:48
> Also, it seems that what is described in #11547 would require quite some manual steps to remove everything and put everything back, but perhaps I don't understand it.
>
> What I would like is something similar to the <kbd>F11</kbd> key in most other browsers (firefox, chrome, edge)

Yes, I understand what you mean. Pushing F11 on Fx hides everything but the webview. The actual blocker for that seems to me is https://github.com/brave/browser-laptop/issues/2775:

> Display menubar on hover in fullscreen mode. Unlike Mac, Windows does not show you a menubar when you hover the top part of the window. You cannot escape from fullscreen mode UNLESS either you push F11 or kill the program.

> That seems to be almost like fullscreen @luixxiul, although it still shows the menu bar in your example. And I suppose it would also show the windows taskbar and such?

I follow the Fx's practice to customize the toolbar. which I now think is irrelevant to the fullscreen option.

**Comment by hugobuddel** [comment] 2017-10-17 13:16
Could you tell me what Fx is @luixxiul?

The behavior of my Brave installation (0.19.54, Windows 10) is very different from what is described in #2775, and also very different from the screenshot you posted. Almost nothing happens when I press F11. The window maximizes or turns back to a normal window and that's it. But it is hard to spot the difference since the windowed version is almost the same size as the maximized version. See the below two screenshots:

Before hitting F11, Brave is not maximized: you can see the black of my desktop wallpaper, and the windowing button (next to the close button on the top right) shows that I can maximize the window.
![screenshot 161](https://user-images.githubusercontent.com/1306453/31666516-d263a572-b34c-11e7-8c0e-1dd4903f2bb6.png)

After hitting F11, the windows is now maximized: no wallpaper visible and the windowing button now shows that I can turn the application back to windowed mode.
![screenshot 162](https://user-images.githubusercontent.com/1306453/31666544-eebc3c2a-b34c-11e7-8f8d-17ed717fa9fb.png)

I can go back and forth between those two modes by either: a) hitting F11, b) clicking the window-icon next to the close-icon on the top right, or c) pressing windows-key + up-arrow and windows-key + down-arrow. These all three do almost the same thing (the difference is the size of the window when not maximized). I'd like F11 to be different: not show anything except the page.

So where #2775 talks about difficulty of leaving full screen, I have a problem entering full screen. From the screenshot from @satnatantas it seems that they have the same problem.

**Comment by luixxiul** [comment] 2017-10-17 13:37
I see, let me explain: what I mean is that it is quite easy to code to hide everything to block on F11 mode, but we often forget which key you have to push to go out of the fullscreen mode until we know the browser well. 

On Firefox the toolbar is displayed when you move your mouse cursor on the top of the monitor, and you can click the caption button to go out of the issue.

Without that hint, for new users, sometimes it becomes hard to do so. We could easily imagine that they might think "how to go out the fullscreen mode?" (whether they actually would say so or not) Without solving the usability issue, hiding everything from the fullscreen mode can be an issue for them (not for you; I know you're an advanced user).

Please forget about my screenshot. I found It was irrelevant with the fullscreen option.

**Comment by hugobuddel** [comment] 2017-10-17 14:18
Ah thank you @luixxiul, I misunderstood you. I thought that there were all these people using Brave full screen with only minor problems 😃. Other issues seem to indicate that such a full screen mode has indeed existed in the past.

E.g. #11558 has a checkbox next to "Test that entering full screen window works View -> Toggle Full Screen. And exit back (Not Esc)." This lead me to conclude that it _should_ be possible to go to full screen mode. Actually toggling full screen mode through the view menu does nothing.

You are right, it should be clear how to leave full screen mode. If that's not clear, then it is better to not have a full screen mode at all. I've also been through that, putting something full screen by accident with no clue how to get back. But then we should not check that checkbox in #11558 until it works. And perhaps remove the option from the menu until then.

Made me wonder what other browsers do, perhaps we can do something similar:

- Firefox shows the bars at the top again when you move the mouse cursor to the top of the screen.
- Chromium/chrome has a message 'Press F11 to leave full screen'. (Nothing happens when moving the mouse to the top of the screen.)
- Edge shows the top right window buttons when you move the mouse to the end of the screen.

**Comment by hugobuddel** [comment] 2017-10-17 14:32
Ah, learned something. Pressing F11 or using view->full screen _does_ do something: it does not show the windows task bar.

I've always got the windows taskbar to automatically hide (on the right side of the screen), so there was no real visible change for me when going to full screen mode. I only noticed that something was different because the taskbar doesn't unhide when moving the mouse cursor to it in full screen mode.

Hence the confusion. So perhaps the checkbox in #11558 is then technically correct, even though the full screen option (as it is now) is irrelevant for me.

**Comment by satnatantas** [comment] 2017-10-18 12:53
I am very afraid to be hallucinating but I was very sure that full screen mode hid all bars when I activated it with F11. If there are good reasons to suppose that I am wrong do not hesitate to do it.

If it the case then treat this issue like request for implementing full screen mode without bars (which appear upon hovering the border).

**Comment by satnatantas** [comment] 2017-10-18 16:44
I now understand my eff-up. I did not activate full screen mode on Periscope (the only site which I used in full screen mode) with F11, I used deicated page button instead (for whatever reason). Sorry for confusion.

Would still like to see better full screen mode.

**Comment by hugobuddel** [comment] 2017-10-18 17:26
Hmm yes, that button on periscope does exactly what I'd want F11 to do (at least on Linux). Brave even asks whether it allows the site to go full screen and shows 'press Esc to exit' on top. Youtube can also go full screen, but that'll just show the movie unlike periscope. So apparently all the necessary functionality for full screen is already in Brave.

So it is totally unclear to me why F11 (on any page) does not do the same as that full screen button on periscope. @luixxiul do you know?

**Comment by NumDeP** [comment] 2017-10-28 23:05
+1 I'd also like a feature for tab bar to hide under the url bar and either appears when scrolling upwards or clicking something on the browser.

Slightly different to 'Automatically hide the taskbar in desktop mode', perhaps you could allow a fun feature of when it is allowed to hide under the url bar moving the mouse upwards doesn't have to always display the entire bar but also allowing it to be displayed like a piano keys, so moving the mouse upwards shows the tab that would originate to wherever you're pointing the mouse and moving right to left displays the tabs like a piano.

The reason why I'd like a feature like this would be because there are some occasions where I'd like to take screenshots/vids and I would prefer to keep the numerous tabs that are open private but have no choice but to close every tab and then reopening every single tab and I don't think I have to mention the fact that the bookmaking feature isn't appreciated just yet. 

Another reason for this feature would be for better screen maximization not just for small screen issues but also the fact it sometimes looks neater so you can concentrate on just the page rather than having numerous titles and different colours presented along a line which can cause distraction. 

I suppose this could be an added benefit as well given over time more user extensions will be presented and it may be best to have two or three rows, one, for pinned/bookmarked items, one for the tabs and the other for extensions, unless the team have decided to opt for something better. from a design perspective.

**Comment by ftruzzi** [comment] 2017-12-07 12:50
+1 to this, it's a very important feature to be able to focus without getting distracted and finding yourself on another website

**Comment by eljuno** [comment] 2017-12-14 18:02
+1 from community https://community.brave.com/t/what-about-a-real-fullscreen-mode/12096?u=eljuno

> when we enter in full screen (F11), it’s not a real full screen because we can still see the URL and all open tabs…

**Comment by bradleyrichter** [comment] 2018-01-25 00:34
@bsclifton If this is an easy enough change, let's do it soon.

**Comment by bradleyrichter** [comment] 2018-01-25 00:40
This user really likes true full screen:  ;   )

https://www.youtube.com/watch?v=-iP9-Et5mv4

**Comment by bradleyrichter** [comment] 2018-01-25 00:54
So the desire, to summarize, is to change our current implementation of full-screen (not to be confused with a FS video view) to hide all UI elements with an expanded view of the content area.

(no toolbars visible)

**Comment by hugobuddel** [comment] 2018-01-31 08:16
I'm using Brave 0.19.147 on windows with the windows taskbar hidden. I just noted that full screen currently results in a *smaller* viewport than non-full screen.

Normal, maximized. Notice that on the right the 'window' seems to extend a bit out of the screen, as can be seen from the arrows on the scrollbar that touch the edge of the screen. The taskbar is hidden on that side of the screen, not sure whether that matters.
![screenshot 190](https://user-images.githubusercontent.com/1306453/35611837-af86f7bc-0666-11e8-88e9-0d8a9158386c.png)

'Full screen', now the viewport is slightly smaller. The arrows on the scrollbar are now fully visible.
![screenshot 191](https://user-images.githubusercontent.com/1306453/35611843-b26c7b50-0666-11e8-9b26-e860f0fef59d.png)

Brave is the very first program where full screen is smaller than non full screen :-).

**Comment by satnatantas** [comment] 2018-01-31 17:31
@hugobuddel looks very much like erratic window size calculation because the scrollbar is slightly cropped on first shot.

**Comment by mduliszewski** [comment] 2018-03-16 09:07
This problem is probably the only thing keeping me from using Brave, thanks everyone for working on issue.

**Comment by peeech** [comment] 2018-03-25 21:00
+1 from Mac user.

**Comment by DesertDwarf** [comment] 2018-04-01 19:03
+1 from me (Windows 10) user. This is the only thing keeping me from using this as my default browser.

**Comment by Dendystale** [comment] 2018-04-02 17:05
+1 from Mac use. Though I use it as default now. I really like it. Fingers crossed on this thing getting fixed! Cheers everyone

**Comment by camelloman** [comment] 2018-04-25 01:59
+1 Mac user. I love brave, but writing in it is a pain. Without full screen I can't concentrate.

**Comment by Gurran** [comment] 2018-05-08 15:08
I have the same problem on latest release. Key F11 for fullscreen doesn't remove url bar, rest is fullscreen. (Meaning the Windows taskbar gets hidden, meaning fullscreen started)
OS: Windows 10

 Brave: 0.22.669 
V8: 6.6.346.24 
rev: 6cda2e84f749e66409e9e3bca63f5796422e7edf 
Muon: 5.2.7 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.117

**Comment by MikeJWms** [comment] 2018-05-20 20:46
+1 from a Mac user. Really like Brave so far but this is a problem that might cause me to jump back to another browser... Thanks for all the hard work on this project!

**Comment by elmarkruitwagen** [comment] 2018-06-02 10:18
+1 from a Mac User

**Comment by mangomadness** [comment] 2018-06-05 05:20
+1 from another Mac user. Brave seems great but not having 'true' full screen (URL and tabs hidden) is almost a (trivial) deal breaker

**Comment by droumis** [comment] 2018-06-06 05:08
+1 mac

**Comment by Rencer** [comment] 2018-06-09 22:27
+1 Manjaro Linux. I really like to go into TRUE fullscreen!

**Comment by WuerfelDev** [comment] 2018-06-10 13:32
+1 Ubuntu&Windows&Android

**Comment by mangomadness** [comment] 2018-06-12 12:17
+1 ubuntu

**Comment by bsclifton** [comment] 2018-06-15 08:08
@srirambv is this fixed with Brave Core?

**Comment by betegon** [comment] 2018-06-18 07:22
+1 Ubuntu

**Comment by srirambv** [comment] 2018-06-18 12:06
This will be fixed in Brave-core. Closing as `wont fix`.

**Closed by srirambv** 2018-06-18 12:06 UTC
Labels: feature/URLbar, feature/tabsbar, misc/fullscreen-option, priority/P5

**Comment by hugobuddel** [comment] 2018-06-18 14:00
Can we follow the progress of the full screen feature somewhere? Or the process of replacing Muon with Brave Core?

This issue is now closed, but full screen does not work yet. Brave-core does not seem to have an issue tracker of its own, so it is not clear what the status of the full screen feature is, or where to discuss it.

**Comment by bbondy** [comment] 2018-06-18 14:51
We're tracking issues for brave-core in the parent repo:
https://github.com/brave/brave-browser

While most work goes here:
https://github.com/brave/brave-core

I believe this issue in particular will be covered with brave-core and isn't planned to be fixed before that is released which is this year within the next few months.  You can compare for example to what Chrome does and if you think that behaviour isn't right then you can post an issue on the `brave/brave-browser` repo. Thanks!

For cases like this, we're going with the process of adding a `fixed-with-brave-core` label and closing the issue.  Thanks for your understanding.

**Comment by hugobuddel** [comment] 2018-06-18 18:47
OK, so brave-core will behave more 'Chromium-like' than muon? 

It's not directly clear from the project descriptions: "Brave Core is a set of changes, APIs, and scripts used for customizing Chromium [..]" and "Muon is a framework that leverages the full power of Chromium [..]".

Seeing all the issues this will fix, it seems like a good change, even though you're probably giving something up in the process too.
