### ISSUE TITLE
Add option to delete the cookie of a web page when the tab is closed

### ISSUE THREAD

**Issue by uriesk** [brave/browser-laptop#11915] opened 2017-11-12 11:20 UTC
There are many sites that don't work without local storage. 4chan and github (if you want to be logged in) are two of them.
In order to provide an "No Cookie" option for pages that break without Cookies, it would be nice to have an option to accept the Cookie, but to delete it right after the tab (or the session) is closed.
Cookie managing Extensions for other Browsers (like the popular "Self-destructing Cookies" for Firefox) work exactly like that and provide this option.

**Comment by luixxiul** [comment] 2017-11-12 11:52
Closing as duplicate of https://github.com/brave/browser-laptop/issues/7605 and https://github.com/brave/browser-laptop/issues/2118. You'll be able to remove cookies manually on the cookie manager: https://github.com/brave/browser-laptop/pull/11107.

**Closed by luixxiul** 2017-11-12 11:52 UTC

**Comment by luixxiul** [comment] 2017-11-12 11:54
For feature suggestions, please have a look at our community first 😄

https://community.brave.com

There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!

**Comment by uriesk** [comment] 2017-11-12 12:12
@luixxiul thank you,
i see that it is a duplicate of #7605, sorry.
But i hope that you see the difference between self-destructing cookies and deleting a cookies manually in a Cookie Manager.
