### ISSUE TITLE
UI becomes unresponsive when rapidly creating tabs via `CTRL + T`

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#10749] opened 2017-08-31 18:15 UTC
**- Did you search for similar issues before submitting this one?**

Yes

**- Describe the issue you encountered:**

When rapidly opening a bunch of tabs via "CTRL + T", the Brave UI becomes completely unresponsive after opening 6-15 tabs.

**- Platform (Win7, 8, 10? macOS? Linux distro?):**

Win 10 x64 - Reproduced
macOS 10.12.6 x64 - Reproduced

**- Brave Version (revision SHA):**

> Brave 0.18.24 rev | 1853c35eeeac8ae271755f5aef71a06ebeef7e83
> Muon 4.3.14
> libchromiumcontent 60.0.3112.101

**- Steps to reproduce:**

1. Open Brave 0.18.24 rev | 1853c35eeeac8ae271755f5aef71a06ebeef7e83
2. Rapidly opened a bunch of tabs using `CTRL + T`
    
**- Actual result:**

The entire Brave UI becomes unresponsive

**- Expected result:**

The Brave UI shouldn't become unresponsive when rapidly opening tabs via `CTRL + T`

**- Will the steps above reproduce in a fresh profile? If not what other info can be added?**

Yes

**- Is this an issue in the currently released version?**

No

**- Can this issue be consistently reproduced?**

Yes, using the above STR, the issue is 100% reproducible

**- Screenshot if needed:**

![unresponsiveissue](https://user-images.githubusercontent.com/2602313/29938179-f153a246-8e55-11e7-8862-74b79583d5f1.gif)

![rapidtabs](https://user-images.githubusercontent.com/2602313/29938189-f6eeb0f6-8e55-11e7-972c-d759b8a7739a.PNG)

**Comment by srirambv** [comment] 2017-09-04 05:06
App is quite slow when opening a lot of tabs on Windows. CPU usage spikes a lot while loading pages on all tabs.

**Comment by luixxiul** [comment] 2017-09-07 01:46
@kjozwiak what is the issue not fixed here?

**Comment by Liunkae** [comment] 2017-09-09 06:26
+1 from me (#10866)

**Comment by bbondy** [comment] 2017-09-11 15:20
@neeklamy is this the same as #10866 or no? I can't reproduce this one but I can reproduce #10866.

**Comment by bbondy** [comment] 2017-09-11 20:05
Seems different from #10866 (who's fix is to queue events until window is ready).  This fix is after window is ready so won't be fixed by a fix like that.  Moving this one since @kjozwiak says it's rare to 0.20.x for re-assessment later.

**Comment by NumDeP** [comment] 2017-09-16 18:49
This issue has become too common of an occurrence  and it seems its happening more regularly than before with fewer tabs than usual as well. The unresponsiveness was always an issue but the crashes weren't as regular as they have been recently meaning before they used to wither because there was a lot of tabs available or very few tabs but the browser not having been refresh in long while.

Strange thing is I can still access the contents within the page, essentially make the last viewed website function almost properly with the exception of the url bar as you can see from the gif.

![2017-09-16_07h54_01](https://user-images.githubusercontent.com/31957540/30514965-92f0dab0-9b17-11e7-9e43-a169c21ab5ab.gif)

**Comment by bsclifton** [comment] 2017-09-16 22:24
Based on the screenshot by @kjozwiak, I believe this is the line causing the problem:
https://github.com/brave/browser-laptop/blob/b47daf7c30c817c1a602342e9e07c736ab1fffa8/js/stores/windowStore.js#L131

`state` needs to be checked before calling `.get`

**Comment by bsclifton** [comment] 2017-09-16 22:33
From the screenshot by @kjozwiak, this is where it's crashing at:
https://github.com/brave/browser-laptop/blob/b47daf7c30c817c1a602342e9e07c736ab1fffa8/js/stores/windowStore.js#L131

This is fired when processing the `APP_NEW_WEB_CONTENTS_ADDED` action.  It seems one of the reducers is returning null or undefined

**Comment by kevinp2** [comment] 2017-11-03 15:46
@kjozwiak , what software did you use to record the video / image / animation of the Brave tabs above?

**Comment by kjozwiak** [comment] 2017-11-03 15:58
> @kjozwiak , what software did you use to record the video / image / animation of the Brave tabs above?

@kevinp2 using a tool called Licecap [1] which captures an area of your desktop and turns it into a .gif file. Really useful tool!

* [1] https://www.cockos.com/licecap/

**Closed** 2018-09-18 22:30 UTC
Labels: bug, feature/newtab, priority/P4, release-notes/include, wontfix
