### ISSUE TITLE
Window positioning is non-existant.

### ISSUE THREAD

**Issue by pmo** [brave/browser-laptop#12053] opened 2017-11-21 14:16 UTC
### Description
When brave is closed in fullscreen and you open brave again, it is not in fullscreen, but the window is still in the same size offcentered on the monitor. Tested on several different machines running windows10.

### Steps to Reproduce

  1. Open Brave
  2. make fullscreen
  3. close Brave
  4. open Brave

**Actual result:**
Brave will open up in a windowed mode, same size as fullscreen, but offcentered.

**Expected result:**

That it will open in fullscreen again, or as an alternative, the default windowed mode size.

**Reproduces how often:**
100%

### Brave Version
Pick any, has always been this way.

**about:brave info:**

cc0ebad
--

### Additional Information
Please do NOT mark this as solved, and please do NOT link this post to other posts.
This is NOT fixed and has never been.

**Comment by hugobuddel** [comment] 2017-11-21 15:23
The first Brave window seems to position itself in the same location as a new window would through Ctrl-N.

I find this only a minor nuisance because it is quite easily resolved by clicking the maximize button. It did confuse me in the past though, because sometimes the difference is so marginal that it is hard to notice. So it does give a bad first impression.

**Comment by bsclifton** [comment] 2017-11-21 16:01
Thanks for the report, @pmo! This is a known issue and has been fixed in newer versions (not released yet).  The fixes will be released with our next major version

Specifically, this was fixed by @NejcZdovc with https://github.com/brave/browser-laptop/pull/10458 in 0.20.x.  I believe this issue itself is a duplicate of https://github.com/brave/browser-laptop/issues/9709

**Closed by bsclifton** 2017-11-21 16:01 UTC

**Comment by pmo** [comment] 2017-11-21 17:48
The post you linked this to is not the same issue, maybe caused by the same error tho.

**Comment by bsclifton** [comment] 2017-11-21 17:52
@pmo ah- after re-reading, I think maybe it was captured with https://github.com/brave/browser-laptop/issues/8600 which that pull request also fixes

**Comment by hugobuddel** [comment] 2017-11-22 09:03
Is there a roadmap somewhere that shows what the main plan is with these minor (~major) version numbers?

I upgraded to 0.19 to try out BAT, and could upgrade to 0.20 for these kind of bug fixes, but would like to know whether there is something big as the BAT change was, before deciding whether the risk of upgrading to a beta version is worth it.

The links on https://github.com/brave/browser-laptop/wiki/Release-channels show what has changed, but not really what the big things are that are planned for the new release.

**Comment by luixxiul** [comment] 2017-11-22 09:12
This wiki should tell you what is planned for the next versions: https://github.com/brave/browser-laptop/wiki/Brave-Development-Timeline, but I think personally that you should not upgrade to beta or developer channels if you don't want to lose your browser's profile data, unless you back up the data.

If you know what kind of enhancements and fixes will be available on the next version, the milestone list will tell you them: https://github.com/brave/browser-laptop/issues?q=is%3Aclosed+milestone%3A%220.20.x+%28Beta+Channel%29%22
