### ISSUE TITLE
Amazon pages go black

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5881] opened 2016-11-28 21:22 UTC
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
Visiting certain pages on Amazon are causing the view to go black.
Ex : https://www.amazon.com/Furby-B6084-Connect-Teal/dp/B01EARLUZW/ref=sr_1_1?s=toys-and-games&ie=UTF8&qid=1480367999&sr=1-1&keywords=furby displays without issue.
Clicking on the manufacturer page (https://www.amazon.com/Furby/b/ref=bl_dp_s_web_3028964011?ie=UTF8&node=3028964011&field-lbr_brands_browse-bin=Furby) goes black. 

**Expected behavior:**
All pages should display as usual.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.13.0 Preview 1

- Steps to reproduce:
    1. Visit https://www.amazon.com/Furby-B6084-Connect-Teal/dp/B01EARLUZW/ref=sr_1_1?s=toys-and-games&ie=UTF8&qid=1480367999&sr=1-1&keywords=furby
    2. Click on 'Furby' link to visit https://www.amazon.com/Furby/b/ref=bl_dp_s_web_3028964011?ie=UTF8&node=3028964011&field-lbr_brands_browse-bin=Furby

- Screenshot if needed:
<img width="1439" alt="screen shot 2016-11-28 at 2 04 51 pm" src="https://cloud.githubusercontent.com/assets/1434040/20686387/108d81e2-b57e-11e6-87de-f51ce5e7fe0a.png">

- Any related issues:
https://github.com/brave/browser-laptop/issues/5877

**Comment by bbondy** [comment] 2016-12-01 16:58
cc @bridiver

**Comment by alexwykoff** [comment] 2016-12-01 19:05
https://web.basemark.com/run/tests/30/graphics_suite/svg_test/ will consistently produce the black page

**Comment by bbondy** [comment] 2016-12-05 07:42
I'll take a look

**Comment by bbondy** [comment] 2016-12-05 08:09
n/m BrianJ says he's already looking at it

**Comment by bradleyrichter** [comment] 2016-12-06 19:46
FWIW, I can't reproduce this in master.

**Comment by bsclifton** [comment] 2016-12-06 21:52
@bradleyrichter I believe this issue is specific to Chrome 54 (I just now added the missing label :smile: )

**Comment by posix4e** [comment] 2016-12-08 20:40
I replicated it on linux. If you lower shields the page renders

**Comment by darkdh** [comment] 2016-12-16 10:41
It's been fixed on latest commit.

**Closed by darkdh** 2016-12-16 10:41 UTC
Labels: chromium54, release/blocking

**Comment by luixxiul** [comment] 2017-01-16 17:53
I added `release-notes/exclude` as the issue appeared and was fixed within the same milestone.

**Comment by luixxiul** [comment] 2017-01-16 18:57
Test plan: available on the 1st post.
