### ISSUE TITLE
Right clicking devtools not working

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#3832] opened 2016-09-08 23:17 UTC
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
I'm not sure why this is but none of the right-click functionality works in our devtools. Maybe we're swallowing the onClick event? There are a lot of tools that I can't access at the moment.

**Expected behavior:**

Right clicking should open context menus for each devtools panel.
- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS
- Brave Version:
  0.12.0
- Steps to reproduce:
  1. Open devtools (cmd+option+i)
  2. Try right clicking
- Screenshot if needed:

Here is an example of what you get on Chrome
<img width="443" alt="screen shot 2016-09-08 at 4 15 51 pm" src="https://cloud.githubusercontent.com/assets/490294/18370151/c616d7e0-75df-11e6-820d-c35e64e77715.png">
- Any related issues:

**Comment by charbelrami** [comment] 2016-09-09 01:29
On Win 10 64-bit, right clicking doesn't show the context menu.

**Comment by Liunkae** [comment] 2016-09-09 06:00
Possibly related to #45.

**Comment by Aeyoun** [comment] 2016-09-20 15:41
Same issue on Linux.

**Comment by jonathansampson** [comment] 2016-12-01 21:10
Also reported by a user (as their final blocker) on gab.ai:

![image](https://cloud.githubusercontent.com/assets/815158/20812731/4995aecc-b7d8-11e6-8c39-235c00d3668e.png)

**Comment by bsclifton** [comment] 2017-03-10 07:32
closing as a dupe of https://github.com/brave/browser-laptop/issues/6724

**Closed by bsclifton** 2017-03-10 07:32 UTC
Labels: bug, duplicate, feature/developer-tools
