### ISSUE TITLE
1Password Autofill

### ISSUE THREAD

**Issue by leepeterson** [brave/browser-laptop#4334] opened 2016-09-27 19:16 UTC
When attempting to log in to http://wpsitesync.com/wp-login.php by way of 1Password autofill (as well as other WordPress sites), the username and password fields do not fill in. This doesn't occur with all websites or form fields, and it's been very sporadic. 

I'm using Brave: 0.12.1, Electron: 1.3.15, libchromiumcontent: 52.0.2743.116, V8: 5.2.361.49, Node.js: 6.3.0, Update Channel: dev 

OS is macOS Sierra 10.12 (16A323) on a MacBook Air (13-inch, Mid 2013) 1.3 GHz Intel Core i5
 4 GB 1600 MHz DDR3

1Password 6, Version 6.5.BETA-19 (650019), AgileBits Beta

**Comment by bridiver** [comment] 2016-09-27 19:29
fixed in 0.12.3, but please comment if you still have the problem after upgrading. 0.12.3 is currently a release candidate and should be released soon

**Closed by bridiver** 2016-09-27 19:29 UTC

**Comment by luixxiul** [comment] 2016-09-28 16:58
1pw autofill seems to have stopped auto-logging in by clicking a candidate since 0.12.3 RC2 (or RC1) /cc: @bridiver

**Comment by bridiver** [comment] 2016-09-28 18:14
@luixxiul can you provide steps to replicate? I just tried with and without autosubmit for sites that had both a single login (autoselected) and multiple logins (manual select) and didn't see any issues

**Comment by luixxiul** [comment] 2016-09-28 23:43
reproduced by following STR in #4359
