### ISSUE TITLE
Ledger table doesnt auto populate the publishers

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11273] opened 2017-10-04 08:56 UTC
### Description
Ledger table doesnt auto populate the publishers

### Steps to Reproduce

  1. Clean install 0.19.28
  2. enable payments
  3. keep the payments tab open
  2. Visit brianbondy.com in a new tab 
  3. Wait for a minute,
  3. switch to payments tab,
  4. publisher is not shown in ledger table
  4. Reload the preferences page
  4. publisher is shown in the ledger table
  5. Visit clifton.io in a new tab, 
  5. stay on the tab for a minute,
  5. switch to preferences tab,
  5. publisher not shown,
  5. reload the preferences tab,
  5. publisher shows up

**Actual result:**

![autoincludepuubs](https://user-images.githubusercontent.com/17010094/31167454-0463cb00-a8ea-11e7-94b6-d4c273b380f6.gif)

**Expected result:**
Should auto-refresh ledger table when criteria is met

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version

**about:brave info:**

Brave | 0.19.28
-- | --
rev | 08781a5
Muon | 4.4.25
libchromiumcontent | 61.0.3163.100
V8 | 6.1.534.41
Node.js | 7.9.0
Update Channel | Beta
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**

No
### Additional Information

cc: @LaurenWags @kjozwiak

**Comment by NejcZdovc** [comment] 2017-10-04 09:03
@srirambv can you please open new tab and then switch to preference tab?

**Comment by srirambv** [comment] 2017-10-04 09:07
No change in opening a new tab and switching to preferences tab. Either the tab or preferences tab need to be refreshed in order for the ledger table to show the publisher

**Comment by LaurenWags** [comment] 2017-10-04 16:54
I have run into this as well, but not consistently. I've found that my table is more likely to be updated when opening a new tab as you mention here @NejcZdovc https://github.com/brave/browser-laptop/issues/11273#issuecomment-334094012 but not always.

**Comment by bsclifton** [comment] 2017-10-11 22:35
Moving to 0.19.x release 2

**Closed** 2017-10-23 19:02 UTC
Labels: bug, feature/ledger, PR/pending-review, priority/P5

**Comment by kjozwiak** [comment] 2017-10-24 01:44
@NejcZdovc, can we remove the `PR/pending-review` label as it looks like the https://github.com/brave/browser-laptop/pull/11592 PR has been reviewed and merged?

QA: Test cases can be found under https://github.com/brave/browser-laptop/pull/11592#issue-266394313.

**Comment by kjozwiak** [comment] 2017-10-27 20:13
Removing the `release-notes/include` as @srirambv mentioned this wasn't reproducible on the live release build in https://github.com/brave/browser-laptop/issues/11273#issue-262712510.
