### ISSUE TITLE
Tabs are not updated after tabpage close

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#9922] opened 2017-07-09 07:27 UTC
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
When you close the last tab in a page tab you get empty tabs toolbar.
- Platform (Win7, 8, 10? macOS? Linux distro?):
all
- Brave Version (revision SHA):
dc76f0a
- Steps to reproduce:
    1. open two tab pages
    2. close the last tab in the tab page
    
- Actual result:
![image](https://user-images.githubusercontent.com/9574457/27991984-ce582c04-6488-11e7-83ba-707dfd00c491.png)

- Expected result:
Tab page is switched correctly.
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
no
- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment] 2017-07-09 16:33
I think this is a duplicate of something. CC @srirambv for confirmation

**Comment by srirambv** [comment] 2017-07-09 19:52
This is a duplicate of #3092 and a regression. The issue had got fixed with some change and has now resurfaced.

**Comment by LaurenWags** [comment] 2017-07-12 13:56
+1 from me

**Comment by osyed** [comment] 2017-07-12 17:21
This is not a duplicate of #3092. That issue is about setting the focus after a tab is closed. This issue is about updating the tabs bar after the last tab is closed.

When the last (the right most) tab is closed the width of the remaining tabs is not updated right away. It updates when the mouse moves down and out of the tab bar or moves to the left and over the new last tab. This can be very annoying if trying to close several tabs on the right side of the tab bar. When you close the last tab, the remaining tabs are not updated so that the new last tab is under the mouse pointer. So you move the mouse pointer to the left to close attempting to close the last tab, but as soon as the pointer moves over the last tab the tabs are updated and the last tab shifts to the right and away from the pointer. Now you have to move the pointer to the right to close the last tab. The UI would feel much smoother if the tab bar was updated as soon as the last tab is closed.

**Comment by luixxiul** [comment] 2017-07-12 21:59
> When the last (the right most) tab is closed the width of the remaining tabs is not updated right away.

I believe that is another issue.

**Comment by NejcZdovc** [comment] 2017-07-13 06:45
Based on our discussion with @cezaraugusto this PR is probably causing this regression #9809

**Closed** 2017-07-18 20:36 UTC
Labels: bug, feature/tabsbar, regression
