### ISSUE TITLE
Tab contents do not resize after moving to different monitor

### ISSUE THREAD

**Issue by FWDekker** [brave/browser-laptop#15236] opened 2018-09-27 17:34 UTC
### Description
The contents of a tab do not resize if the tab is moved from one monitor to another that has a different resolution.

### Steps to Reproduce

  1. Get yourself two monitors; this behaviour does not occur with two windows on the same monitor.
  2. Open a Brave window on both monitors. The windows should have a different size—the bigger the difference the easier it is to notice. It does not matter if they are maximised.
  4. Drag a tab from one window to the other, so that one of the windows now has two tabs.

**Actual result:**
![Actual result](https://user-images.githubusercontent.com/13442533/46163432-860c5d00-c28b-11e8-9290-d8d9fefb5d18.png)

**Expected result:**
![Expected results](https://user-images.githubusercontent.com/13442533/46163503-a6d4b280-c28b-11e8-879c-36b2ac10d3a9.png)

**Reproduces how often:**
100% of the time.

### Brave Version

**about:brave info:**

| Name | Version |
|---|---|
| Brave | 0.24.0  |
| V8 | 6.9.427.23  |
| rev | f657f15bf7e0e0c50a2b854c6b05edb59bfc556c  |
| Muon | 8.1.6  |
| OS Release | 10.0.17134  |
| Update Channel | Release  |
| OS Architecture | x64  |
| OS Platform | Microsoft Windows  |
| Node.js | 7.9.0  |
| Brave Sync | v1.4.2  |
| libchromiumcontent | 69.0.3497.100 |

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment] 2018-09-28 20:52
I believe this has the same root cause as https://github.com/brave/browser-laptop/issues/10502

Unfortunately, we won't be fixing this with the `browser-laptop` code-base. You can try out our Beta channel available here:
https://brave.com/download-beta

**Closed by bsclifton** 2018-09-28 20:52 UTC
