### ISSUE TITLE
Wordpress not working

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2754] opened 2016-07-28 17:07 UTC
> Also, it simply doesn’t work with WordPress. Brave threw errors as I tried to create posts for my blog. My advice?

Source: http://aetherczar.com/?p=4418

**Comment by luixxiul** [comment] 2017-07-01 11:09
+1 https://community.brave.com/t/can-post-articles-on-wordpress-com-on-chrome-but-not-on-brave/4390?u=suguru

**Comment by srirambv** [comment] 2017-07-03 10:12
User confirms changing cookie setting to allow all cookies works. This is similar to downloading files from Google Drive 
https://community.brave.com/t/can-post-articles-on-wordpress-com-on-chrome-but-not-on-brave/4390/4?u=sriram

**Comment by luixxiul** [comment] 2017-11-19 10:26
Closing as the issue is avoided by allowing cookies.

**Closed by luixxiul** 2017-11-19 10:26 UTC
Labels: webcompat
