### ISSUE TITLE
brave loads sooooo slow on mbp

### ISSUE THREAD

**Issue by wixster** [brave/browser-laptop#6834] opened 2017-01-24 15:09 UTC
- Did you search for similar issues before submitting this one?
yes...saw same comments
- Describe the issue you encountered:
see title (im back to chrome cuz it blows it outta the water...)
- Platform (Win7, 8, 10? macOS? Linux distro?):
mac (mbp 13" retina 2014)
- Brave Version (revision SHA):
012.15
- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by alexwykoff** [comment] 2017-01-25 04:42
duplicate of https://github.com/brave/browser-laptop/issues/3025

**Closed by alexwykoff** 2017-01-25 04:42 UTC
Labels: duplicate

**Comment by wixster** [comment] 2017-01-25 13:59
cool brother....hop you guys figure it out. brave is actually well put together for the most part imho...

just dreadfully slow....which i just cant deal with...(no offense)

fix it and im a user.....  ;)
