### ISSUE TITLE
Counters should be selectable on about:newtab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5666] opened 2016-11-16 03:52 UTC
The counters should be selectable on about:newtab to make it easier to share them on twitter/facebook :-)

- Brave Version: 0.12.9

- Any related issues:

**Comment by bsclifton** [comment] 2016-11-16 04:21
This would be my fault 😄 What do you think, @bradleyrichter ? I had made them non-selectable to appear more like an app... but sharing is great 😄

**Comment by bradleyrichter** [comment] 2016-11-16 07:35
Sounds reasonable. Share away!

**Comment by srirambv** [comment] 2016-11-16 07:59
Dupe of #5452

**Comment by bsclifton** [comment] 2016-11-16 08:00
@srirambv seems a little different- this is for copy/paste purposes

**Closed** 2016-11-16 08:01 UTC
Labels: feature/newtab, suggestion
