### ISSUE TITLE
Fix canvas fingerprinting

### ISSUE THREAD

**Issue by yipoduyoy** [brave/browser-laptop#694] opened 2016-02-09 21:18 UTC
PLEASE REMOVE WEBRTC AND CANVAS

http://www.browserleaks.com/webrtc
https://www.perfect-privacy.com/webrtc-leaktest/

http://www.browserleaks.com/canvas
http://venturebeat.com/2014/07/30/canvas-fingerprinting-is-tracking-you-and-you-dont-even-know-what-it-is/

**Comment by diracdeltas** [comment] 2016-02-09 22:06
Duplicate of #260 #242

**Comment by diracdeltas** [comment] 2016-04-05 22:42
Actually the canvas fingerprinting issue would be a huge win and is not duplicated in the other issues above. Changing the title to reflect that.

**Comment by diracdeltas** [comment] 2016-04-05 23:30
Proposal:
* Don't allow canvas fingerprinting by third parties (perhaps tied to the third party cookies pref), a la Privacy Badger.
* Show a permissions prompt for canvas fingerprinting by the first party, a la https://trac.torproject.org/projects/tor/ticket/6253.

**Closed** 2016-04-17 12:51 UTC
Labels: duplicate, hackathon

**Comment by jussihuotari** [comment] 2016-05-17 09:44
fwiw, I've enabled "Block HTML canvas and WebGL fingerprinting" on v0.9.6

However, both https://www.browserleaks.com/canvas and https://panopticlick.eff.org/ show a unique canvas fingerprint for me. 

Hash of WebGL fingerprint is `undetermined`, as expected.

**Comment by diracdeltas** [comment] 2016-05-17 17:34
@jussihuotari The panopticlick canvas fingerprinting value should be `891f3debe00dbd3d1f0457a70d2f5213` (same for all Brave users). With fingerprinting defense turned off, panopticlick says that 1/20,000 browsers have my canvas hash value. With fingerprinting defense on, only 1/800 browsers have this value, which is a great improvement.

**Comment by diracdeltas** [comment] 2016-05-17 17:37
I think you're right that we are missing some of the canvas methods in https://www.browserleaks.com/canvas#how-does-it-work though. I'll fix; thanks!

**Comment by diracdeltas** [comment] 2016-05-17 18:12
Looks like the problem is that browserleaks creates a canvas element in an iframe and somehow we are properly stubbing canvas.toDataURL in the page but not in child frames:

```
var a = document.createElement('canvas')
> undefined
a
> <canvas>​
a.toDataURL
> function () {
            console.log('trapping', item.propName)
            var script_url = getOriginatingScriptUrl()
            var msg = {
              obj: item.objName,
              prop: ite…
var a = document.getElementById("iframe").contentDocument.createElement("canvas")
> undefined
a.toDataURL
> function toDataURL() { [native code] }
```

**Comment by HLFH** [comment] 2016-05-17 18:19
@diracdeltas hi. so maybe we should reopen the issue for this moment.

**Comment by diracdeltas** [comment] 2016-05-17 18:23
i'll open a new one
