### ISSUE TITLE
unable to generate new window session using  current open tab 

### ISSUE THREAD

**Issue by sahasrara62** [brave/browser-laptop#2622] opened 2016-07-20 23:48 UTC
**unable to generate new window session using current opened tab  **

**Expected behavior:   as i click on tab and try to drag it down from it default position than a new window session should open where  that dragged tab should open as default **

- Platform  : ubuntu 14.04 LTS

- Brave Version:  0.11.1
 

- Steps to reproduce:
    1. go to a tab and open any website .
    2. click on the tab and try to drag it from it's original position .
    3. instead of opening new window ,nothing new is happening .

**Comment by bbondy** [comment] 2016-07-21 00:05
duplicate of https://github.com/brave/browser-laptop/issues/405 so closing this.

**Closed by bbondy** 2016-07-21 00:05 UTC
