### ISSUE TITLE
sometimes channel name appears aligned right instead of left in ledger

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11960] opened 2017-11-14 23:03 UTC
### Description
Sometimes channel name looks like it's left aligned (or just displays oddly) in ledger.

### Steps to Reproduce

  1. Have payments enabled.
  2. Watch a couple of videos on YT.
  3. sometimes some channel names (especially if they're longer) will display oddly.

**Actual result:**
![screen shot 2017-11-14 at 5 30 59 pm](https://user-images.githubusercontent.com/28145373/32809609-6dabbd84-c965-11e7-9dd7-a7814a0aef0a.png)

**Expected result:**
If it needs to wrap, as the one above might, it should wrap on the other side (left side)

**Reproduces how often:**
unknown, attempted to reproduce and ran into https://github.com/brave/browser-laptop/issues/11953

### Brave Version

**about:brave info:**

Brave | 0.19.91
rev | a308504
Muon | 4.5.15

**Reproducible on current live release:**
n/a

**Comment by kjozwiak** [comment] 2017-11-15 03:37
Reproduced under Ubuntu 16.04.3 LTS using https://www.youtube.com/user/latenight, example:

<img width="454" alt="screen shot 2017-11-14 at 10 27 23 pm" src="https://user-images.githubusercontent.com/2602313/32817428-9a1aab7a-c98b-11e7-9897-a393f4bf2323.png">

I think we should fix this within `hotfix5`.... There's quite a few channels that have long names, especially the late night talk shows as shown above... These channels tend to me really popular, which means users will most likely run into these UI issues. I don't think this is going to be hard to fix and shouldn't introduce much risk.

It's highly possible that the media/journalist might run into this off that bat if they install Brave and try this feature out... The late night talk shows usually tend to be featured on the default YT page when not signed in.

If someone feels differently, please remove this from this hotfix.

**Comment by mrose17** [comment] 2017-11-15 05:40
@LaurenWags - this is a rather odd effect. the next time it happens, can you `Inspect Element` so we can see what the underlying markup is for that title? thanks1

**Comment by luixxiul** [comment] 2017-11-15 05:42
Based on https://github.com/brave/browser-laptop/pull/10789, it'll be fixed into:

<img width="839" alt="screenshot 2017-11-15 14 40 39" src="https://user-images.githubusercontent.com/3362943/32820685-0d83b1e2-ca13-11e7-81cb-d713e6fd08bd.png">

**Comment by kjozwiak** [comment] 2017-11-15 06:29
> can you `Inspect Element` so we can see what the underlying markup is for that title?

@mrose17 added incase it's still needed, however it looks like @luixxiul is working on it.

<img width="1625" alt="screen shot 2017-11-15 at 1 27 19 am" src="https://user-images.githubusercontent.com/2602313/32822010-6ee332e2-c9a4-11e7-94b4-a224884b0ce7.png">

**Comment by NejcZdovc** [comment] 2017-11-15 07:38
@mrose17 @bbondy @kjozwiak @bsclifton should we create a quick fix for this one, for hotfix 5 or should we wait for #10789 to land?

**Comment by luixxiul** [comment] 2017-11-15 08:18
FYI #10789 is based on the other PRs on sortableTable: https://github.com/brave/browser-laptop/pulls?q=is%3Apr+sortableTable+is%3Aclosed

**Comment by NejcZdovc** [comment] 2017-11-15 08:22
@luixxiul not sure that understand

**Comment by luixxiul** [comment] 2017-11-15 08:25
I just mean #10789 cannot be landed until 0.20

**Comment by NejcZdovc** [comment] 2017-11-15 08:38
gotcha, so yeah the question is if we want to fix this in  hotfix 5 or not

**Closed** 2017-11-15 13:16 UTC
Labels: 0.19.x, bug, feature/ledger

**Comment by kjozwiak** [comment] 2017-11-15 18:41
Channel names are being aligned correctly but caused #11978 when using the English locale.
