### ISSUE TITLE
Bookmarking a site removes entry from history

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#6160] opened 2016-12-12 14:12 UTC
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
Bookmarking a visited site removes it from about:history

**Expected behavior:**
Bookmark action should not remove its history entry

- Platform (Win7, 8, 10? macOS? Linux distro?): all

- Brave Version: master (0.13.0)

- Steps to reproduce:
    1. Visit a site
    2. Go to about:history and ensure site is there
    3. Bookmark
    4. Entry is removed

**Comment by bsclifton** [comment] 2016-12-12 16:09
@cezaraugusto is the lastAccessTime timestamp updated when bookmark happens?

Important notes about siteDetail behavior can be found here: https://github.com/brave/browser-laptop/issues/5590

**Comment by bsclifton** [comment] 2016-12-12 16:10
I also believe this is the same issue as https://github.com/brave/browser-laptop/issues/5413

**Comment by darkdh** [comment] 2016-12-13 05:54
@cezaraugusto , it is the root cause.
Regarding our discussion, I believe `lastAccessedTime = newSiteDetail.get('lastAccessedTime') || oldSiteDetail.get('lastAccessedTime') || 0` will fix it

**Comment by cezaraugusto** [comment] 2016-12-13 22:15
@darkdh correct, but it crashes Brave if you bookmark an about page (like about:history itself), so seems more complex than expected.

**Comment by bsclifton** [comment] 2017-01-11 18:32
Fixed with https://github.com/brave/browser-laptop/pull/6211 which was merged into branch `0.13.1-branch`.

**Closed by bsclifton** 2017-01-11 18:32 UTC
Labels: feature/bookmarks, feature/history
