### ISSUE TITLE
Add pref to allow Pinned tabs to function in single-window mode

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#5800] opened 2016-11-22 22:24 UTC
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

If I have tabs pinned in a window and open a new window, the pinned tabs are automatically loaded in the new window.

**Expected behavior:**

The new window should not have pinned tabs from other windows. Each window should have its own set of pinned tabs.

- Platform (Win7, 8, 10? macOS? Linux distro?):

OS X 10.11.6

- Brave Version:

0.12.10

- Steps to reproduce:
    1. Open a Brave window.
    2. Pin one or more tabs.
    3. Open a second Brave window.
    4. Notice that the pinned tabs are in the new Brave window.

- Any related issues:

Related to https://github.com/brave/browser-laptop/issues/3817

**Comment by bradleyrichter** [comment] 2016-11-23 03:06
@echosa This is by design so I changed the title to reflect a request for a preference setting. Most of the feedback on how pinned tabs work differently has been positive but I can see adding an option to use the old approach. 

Thanks for the feedback.

Brad

**Comment by Liunkae** [comment] 2017-03-12 23:40
Suggestion from #7632: "have a windows id sct so that pinned tabs are not autoloaded in new windows. only load pinned tabs on the first window."

Two duplicates were set for 0.13.6, so I'll set this one accordingly.

**Comment by bsclifton** [comment] 2017-03-13 07:47
+1 from user who DMed me
> Pinned tabs are always pinned, across all windows. This made them unusable for me, since pinning to me is typically reserved for things that I want to keep open in a single session (I treat windows like sessions basically). So for instance, I have a window open right now with two pinned tabs, a JIRA board for work I'm doing, and a Pandora tab, because music. If I open a new window, I don't want a second instance of Pandora, and typically this new window would be for an entirely different session like testing a project I'm working on where the first window would be like searching SO for a fix for whatever I just did wrong.

**Comment by bsclifton** [comment] 2017-03-14 08:44
Moving to 0.13.7

**Comment by bradleyrichter** [comment] 2017-03-16 06:22
We should not load pinned tabs on non-active windows. @bbondy did some improvements here as well?

I use pinned tabs like super-bookmarks and love having them on any window I have open and more importantly, new windows after I close all and start fresh. 

But I fully understand the pref for session-style windowing and pinning so we need a pref for this option.

**Comment by bbondy** [comment] 2017-04-10 02:23
most of the ground work for this is done but there are some problems with it still.  I'm not sure if we'll get to this by 1.0 so I'm clearing the milestone for now.  Pinned tabs work a lot better in general now though from various changes.

**Comment by bsclifton** [comment] 2017-05-09 07:23
+1 from https://github.com/brave/browser-laptop/issues/8675

**Comment by srirambv** [comment] 2017-07-10 08:25
Quite a few +1 from community https://community.brave.com/t/pinned-tabs-should-stay-in-the-window-they-were-pinned-in/1143/7

**Comment by luixxiul** [comment] 2017-08-01 06:23
+1 from here: https://community.brave.com/t/cannot-unpin-tabs/2369/9?u=suguru

**Comment by iamhenry** [comment] 2017-10-12 21:14
+1 for this. Please add this to the settings in Brave

**Comment by briatte** [comment] 2017-10-30 11:15
+1

Would also very much like if it had a shortcut, e.g. Cmd-Shift-N / Ctrl-Shift-N, which is unused as of now (v0.19.70).

**Comment by scottrepreneur** [comment] 2017-11-21 00:05
+1 would be helpful

**Comment by afong94** [comment] 2018-01-12 09:49
+1 this would definitely help to avoid duplicate tabs and unnecessary memory usage. An option to enable this would be great!

**Comment by gnarlyman** [comment] 2018-01-25 03:55
+1 please add this option

**Comment by eljuno** [comment] 2018-03-08 18:44
+1 from community https://community.brave.com/t/pinned-tab-behaviour-when-dragging-and-separating-a-non-pinned-tab-to-a-new-isolated-window/17553?u=eljuno

**Comment by NihilistZealot** [comment] 2018-03-09 03:23
+1 from me as well, I've recently started using Brave and this 'feature' is jarring and not friendly. Additionally, why is it that pinned tabs are unable to be unpinned?

**Comment by echosa** [comment] 2018-03-09 03:49
@NihilistZealot You're unable to unpin tabs that are pinned? Do you not see this when you right-click a pinned tab?

<img width="282" alt="screen shot 2018-03-08 at 9 48 22 pm" src="https://user-images.githubusercontent.com/133786/37189527-860d8d8a-231a-11e8-81c7-c74a2480797c.png">

**Comment by pettys** [comment] 2018-04-12 13:59
+1. Chrome and Edge both work as +1'ers expect.

The current pinning behavior is confusing in this use case: I like to pin Pandora. If multiple windows are open, and they all have a Pandora tab, I wonder which one of them is actually playing the music right now.

The confusion shows up as bug: Today if I pin Pandora, switch to a non-pinned tab, then hit Ctrl+N to open a new window, Pandora stops playing, even though no Pandora window actually has focus right now. This makes pinned tabs unusable for Pandora. (Brave for Windows 0.22.13)

@bradleyrichter, regarding your comment a year ago supporting the current Brave pinning function, "I use pinned tabs like super-bookmarks and love having them on any window I have open and more importantly, new windows after I close all and start fresh." Does using pinned tabs in this way give you a significant advantage over using the bookmarks toolbar? I think there's an important technical difference between a bookmark and a pinned tab, and that technical/semantic difference is what the +1'ers here are reacting to.

Here's my Brave with both bookmarks and pinned tabs... they look pretty similar, but they mean very different things to me:
![image](https://user-images.githubusercontent.com/784669/38681897-706d481e-3e2f-11e8-8726-d164707065df.png)

**Comment by bfinney-thoughtworks** [comment] 2018-04-12 22:39
Another reason to want exactly 1 instance of each pinned tab: Many pages are resource-intensive. I don't want more copies of a high-CPU tab than are needed: when I pin it once, it should exist once and new windows should not attempt to have another running copy.

**Comment by farmerdoe** [comment] 2018-05-25 20:10
hi, is there any update on this? this is the one missing feature that is stopping me from using brave as my main browser

**Comment by bsclifton** [comment] 2018-05-29 18:54
Hi folks - this issue has been fixed with Brave Core (the Chromium UI that we're working on which will replace our current Muon based product). For our current product, I think it's safe to say that we won't fix the issue ☹️ We anticipate the release of the new version in a few months time

**Closed by bsclifton** 2018-05-29 18:54 UTC
Labels: bug, feature/pinned-tabs, fixed-with-brave-core, polish, priority/P5, suggestion

**Comment by Liunkae** [comment] 2018-06-18 21:05
+1 from https://medium.com/@PaulRBerg/constructive-feedback-for-the-brave-browser-9f08b422a05

**Comment by grezeaux** [comment] 2018-07-12 04:30
I would also love to have pinned tabs only open on the first instance of opening the browser. I have six pinned tabs, and none of them are useful to have open multiple times (e.g., Gmail, JIRA, etc.).

**Comment by Ovadia-B** [comment] 2018-08-30 13:18
This hack can open a new window without the pinned tabs. 
Just run this JS code in Developer Tools console.
`window.open("https://www.brave.com", "_blank", "width=400,height=400");`

**Comment by bsclifton** [comment] 2018-09-10 18:49
For folks subscribed to this or who find this page, we've recently launched the new version of our product 😄 (which fixes this issue) You can grab it here:
https://brave.com/download-dev
