### ISSUE TITLE
Twitch.tv streams play twice

### ISSUE THREAD

**Issue by jeifour** [brave/browser-laptop#2119] opened 2016-06-07 11:36 UTC
**Did you search for similar issues before submitting this one?** Yes. And it's exceptionally hard to search for issues with twitch because the site name is mentioned in every "manual tests" issue.

**Describe the issue you encountered:** When watching a stream on twitch.tv there seem to be 2 players on top of another, with only the top one manipulatable by the user. It leads to more bandwidth consumption and hearing the audio feed twice. Also makes muting the stream not work because the other stream is still playing in the background.

**Expected behavior:** If I open only one tab with one stream it should play only once.

- Platform (Win7, 8, 10? OS X? Linux distro?): I'm using Linux (Manjaro).

- Brave Version: 0.10.0

- Steps to reproduce:
    1. Go to a stream on twitch.tv that's currently online (for example right now https://www.twitch.tv/dotamajor exhibits this behavior)
    2. Try to mute the audio by using the player audio control.
    3. Notice that the audio is still playing.

- Screenshot if needed:

- Any related issues:

**Comment by cezaraugusto** [comment] 2016-06-07 19:36
Hey there,

Couldn't reproduce your issue on version 0.10.0dev. 

Please notice that v0.10.2 is the currently stable version with several bug fixes related to Windows. Please try updating Brave and check if the issue remains. 

I'll close it for now. Let me know if the issue persists.

**Comment by jeifour** [comment] 2016-06-08 09:16
Ok I've updated to 0.10.2 now.
![_2016-06-08_18-15-02](https://cloud.githubusercontent.com/assets/3247063/15889160/f677125c-2da4-11e6-8472-f7a3434115f9.png)

The issue still persists. The reproducability is not 100%, but it happens at least 50% of the time for me. Sadly I couldn't figure out a pattern yet, it seems to be random.
I made a 20 second video to show it: https://my.mixtape.moe/zdkbro.mp4

**Comment by bbondy** [comment] 2016-06-08 17:43
I can reproduce this.

**Closed** 2016-06-08 19:03 UTC
Labels: bug
