### ISSUE TITLE
Significant lag until tab title is displayed when the page is reloaded

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8294] opened 2017-04-13 15:02 UTC
**Describe the issue you encountered:** There is a significant lag until tab title is displayed when the page is reloaded.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.14.2 Preview2

- Steps to reproduce:
    1. Open https://github.com
    2. Reload the page
    
- Actual result: 
  ![lag](https://cloud.githubusercontent.com/assets/3362943/25010552/710e8254-20a5-11e7-9933-500c22a99378.gif)

- Expected result: there should be no lag

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by srirambv** [comment] 2017-04-13 15:21
This is similar to #8247

**Comment by luixxiul** [comment] 2017-04-17 18:57
should this be fixed with 0.14.2 or 0.15.1?

**Comment by bsclifton** [comment] 2017-04-18 17:39
I'll look at a fix for this- may have been caused by https://github.com/brave/browser-laptop/commit/fa919c0c4b7f2619b78a55b90bb178a734be18e9

**Closed** 2017-04-18 20:56 UTC
Labels: bug, feature/tabsbar, needs-triage, regression

**Comment by bsclifton** [comment] 2017-04-18 21:04
Since change was made with 0.14.2 / 0.15.0, I added release notes exclude. This was a bad fix on my part.
