### ISSUE TITLE
Drag & drop of file should have a better filename

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#14435] opened 2018-06-16 01:02 UTC
### Description

I'm on macOS, and when I'm dropping the files into Desktop (by dragging the fav icon in Brave), the files got unexpected filenames.

For example (all of these files exists):

- `file:///etc/hosts` -> `etc/hosts.fileloc`
- `file:///Users/myuser/Downloads/file.txt` -> `Users/myuser/Downloads/file.txt.fileloc`
- `file:///Users/myuser/Downloads/_Chrome/_foo/_bar/foo-bar_buzz.html` -> `Users/.fileloc`

### Steps to Reproduce

  1. `mkdir -p ~/Downloads/_Chrome/_foo/_bar/`
  2. `touch ~/Downloads/_Chrome/_foo/_bar/foo-bar_buzz.html`
  3. Drag & drop into Desktop.

**Actual result:**

The filename is: `Users/.fileloc`

**Expected result:**

The file should be like: `foo-bar_buzz.html.fileloc`

**Reproduces how often:**

Always.

### Brave Version
 
Brave: 0.22.810 
V8: 6.7.288.43 
rev: 8f30eeba0c2d6cccf1920a360b4774f820adbc58 
Muon: 7.0.6 
OS Release: 17.3.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.71

----

### Chrome

<img width="769" alt="screen shot 2018-06-18 at 22 24 20" src="https://user-images.githubusercontent.com/266306/41563421-6f66d532-7347-11e8-9152-41d6e2b39c7f.png">

### Brave

<img width="816" alt="screen shot 2018-06-18 at 22 25 18" src="https://user-images.githubusercontent.com/266306/41563440-79025e04-7347-11e8-9d03-445bcb82f17f.png">

**Comment by Liunkae** [comment] 2018-06-18 21:00
Could you please clarify how this problem is caused by Brave?

**Comment by kenorb** [comment] 2018-06-18 21:33
I've added screenshots for the clarification.

**Comment by bsclifton** [comment] 2018-09-07 07:52
Verified this is fixed with our Developer channel 😄 (brave-core)
https://brave.com/download-dev

**Closed by bsclifton** 2018-09-07 07:52 UTC
Labels: fixed-with-brave-core, wontfix
