### ISSUE TITLE
Browser crashes when opening a new window

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13543] opened 2018-03-21 10:20 UTC
### Description
Browser crashes when opening a new window

### Steps to Reproduce

  1. Build from aa9db3c41b1f966342aa166fe9dcc2c42e798c48
  2. Launch browser via `npm run start`
  3. Open a new window via keyboard shortcut browser crashes

**Actual result:**
Browser crashes when opening a new window with the log 
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v9.7.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle brave@0.22.5~prestart: brave@0.22.5
6 info lifecycle brave@0.22.5~start: brave@0.22.5
7 verbose lifecycle brave@0.22.5~start: unsafe-perm in lifecycle true
8 verbose lifecycle brave@0.22.5~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\work\browser-laptop\node_modules\.bin;C:\Users\bellurs\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\bellurs\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\python27;C:\Users\bellurs\AppData\Local\Microsoft\WindowsApps;C:\Users\bellurs\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle brave@0.22.5~start: CWD: C:\work\browser-laptop
10 silly lifecycle brave@0.22.5~start: Args: [ '/d /s /c',
10 silly lifecycle   'node ./tools/start.js --user-data-dir-name=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck' ]
11 silly lifecycle brave@0.22.5~start: Returned: code: 2147483651  signal: null
12 info lifecycle brave@0.22.5~start: Failed to exec start script
13 verbose stack Error: brave@0.22.5 start: `node ./tools/start.js --user-data-dir-name=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck`
13 verbose stack Exit status 2147483651
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:127:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:127:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid brave@0.22.5
15 verbose cwd C:\work\browser-laptop
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v9.7.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2147483651
22 error brave@0.22.5 start: `node ./tools/start.js --user-data-dir-name=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck`
22 error Exit status 2147483651
23 error Failed at the brave@0.22.5 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2147483651, true ]
```

**Expected result:**
Should not crash when opening a new window via keyboard shortcut 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.5
-- | --
V8 | 6.5.254.36
rev | aa9db3c
Muon | 5.1.0
OS Release | 10.0.16299
Update Channel |  
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.162

**Reproducible on current live release:**
no

### Additional Information
No crash when creating new window via file menu or kabob menu. Console throws the following error everytime a new window is launched
```
[10412:17536:0321/102114.208:ERROR:CONSOLE(28526)] "(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.", source: http://localhost:8080/gen/app.entry.js (28526)
```

**Comment by srirambv** [comment] 2018-03-21 11:38
Also seeing crash consistently when resizing browser window and typing in URL bar.

**Comment by Tomatoshadow2** [comment] 2018-03-21 13:04
Does the browser have to be launched with npm run start? Couldn't reproduce the issue on Mac. I just launch from my applications though.

**Comment by srirambv** [comment] 2018-03-21 15:26
@Tomatoshadow2  yes building from source needs to be launched with `npm run start`. This could be a Windows only issue. 

Could you try building from source and see if it happens on mac too?

cc: @LaurenWags @kjozwiak

**Comment by petemill** [comment] 2018-03-21 20:21
Looks like same exit code as https://github.com/brave/browser-laptop/issues/13224, is this a more reproducible STR for the same issue?

**Comment by srirambv** [comment] 2018-03-21 20:26
I can consistently crash when trying to resize the browser window or open a new window using keyboard shortcuts.

**Comment by bsclifton** [comment] 2018-03-23 06:14
This has to be a duplicate of https://github.com/brave/browser-laptop/issues/13224

Definitely does not occur on macOS

**Closed by bsclifton** 2018-03-23 06:14 UTC
Labels: 0.22.x, crash, feature/keyboard-shortcuts
