### ISSUE TITLE
Oauth into Asana leaves a blank window open.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#11050] opened 2017-09-20 17:15 UTC
### Description

When logging into Asana, it allows for a user to use Oauth & their Google account. 
After the handshake is complete, the new, smaller Oauth window is left open and is blank.

### Steps to Reproduce

  1. Log into Google
  2. Log into Asana with Google

**Actual result:**
<img width="612" alt="screen shot 2017-09-20 at 12 10 20 pm" src="https://user-images.githubusercontent.com/1434040/30657431-36b481aa-9dfd-11e7-8c9b-f518c255796d.png">

**Expected result:**
Since the handshake is complete, the window should close.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version

**about:brave info:**
 
Brave: 0.19.9 
rev: 2a9a56f7736ec47559d2ed112872f973f983b646 
Muon: 4.4.19 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Reproducible on current live release:**
Unsure, needs investigation.

**Comment by jamesray1** [comment] 2017-09-20 23:33
Yes I get the same result (a blank small window after clicking to sign in with Google) for OAuth with Google on about.me.
Twitter OAuth works, but Facebook and Google doesn't.

**Comment by luixxiul** [comment] 2017-09-21 07:24
me too. I noticed that when I logged in with Facebook.

**Comment by eduardonunesp** [comment] 2017-09-21 16:13
Hummm interesting maybe something related to the `window.close()`, after the handshake completed some `window.close()` should be called. Maybe some reference to the `window.opener` isn't passed to the new window.

**Comment by bsclifton** [comment] 2017-09-21 18:20
I believe this is related to window.close not working as expected

cc: @jonathansampson @kevinlawler

**Comment by jonathansampson** [comment] 2017-10-27 18:22
I don't think this is an issue with `window.close` necessarily. Note that the tab it closed, but the window doesn't know that all tabs are closed. As such, the window stays open.

**Comment by jrmoreau** [comment] 2018-03-27 02:55
Any update on this? Experiencing the same. Also experiencing after I confirm a tx on MEW with Trezor

**Comment by bsclifton** [comment] 2018-07-27 21:21
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/13370

**Closed by bsclifton** 2018-07-27 21:21 UTC
Labels: bug

**Comment by bsclifton** [comment] 2018-07-30 06:19
The original issue was https://github.com/brave/browser-laptop/issues/9610 which was closed in favor of #13370 since it had more detail 😄
