### ISSUE TITLE
Strict Site Isolations Breaks U2F 2FA 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14794] opened 2018-07-21 12:19 UTC
## Description 

Enabling "Strict Site Isolation" breaks Yubikey U2F 2FA.

## Steps to Reproduce

   1. Enable Strict Site Isolation
   2. Login to ex) google mail
   3. Enter username
   4. Enter password
   5. Enter 2FA. Prompts user with error. See attached pics.

## Actual result:

![screen shot 2018-07-20 at 1 31 29 pm](https://user-images.githubusercontent.com/8204597/43024117-0ef92e40-8c22-11e8-9333-1b1bee734d0f.png)
![screen shot 2018-07-20 at 1 30 54 pm](https://user-images.githubusercontent.com/8204597/43024118-0f1003c2-8c22-11e8-97f8-446a98ff7899.png)

## Brave version (about:brave info) 

![screen shot 2018-07-20 at 1 38 13 pm](https://user-images.githubusercontent.com/8204597/43024148-2e49d862-8c22-11e8-9baf-beb292d93e58.png)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

Nope.

### Additional Information
Cross posting issue from https://github.com/brave/brave-browser/issues/615 logged by @stefanperson

**Comment by bsclifton** [comment] 2018-07-22 05:41
I believe this is a duplicate of https://github.com/brave/browser-laptop/issues/12612

U2F support should be coming from an extension we bundle with Brave:
![screen shot 2018-07-21 at 10 40 37 pm](https://user-images.githubusercontent.com/4733304/43042583-21522d1a-8d37-11e8-9045-2e5e075adbc0.png)

**Closed by bsclifton** 2018-07-22 05:41 UTC
Labels: bug, settings
