### ISSUE TITLE
Brave crashes my Mac

### ISSUE THREAD

**Issue by Pacerier** [brave/browser-laptop#11691] opened 2017-10-27 09:40 UTC
Anyone have had the same issue?  Postrestart version: 
![image](https://user-images.githubusercontent.com/626558/32099385-ab378e5c-bb42-11e7-978c-7d0eb15fbede.png)

![image](https://user-images.githubusercontent.com/626558/32099434-d933417a-bb42-11e7-9c89-4c21b112480d.png)

OS was running fine for past weeks/months; few days ago I installed and softswitched to Brave  (I'm using Brave alongside Chrome.); came back home yesterday OS crashrestarted. ~90% probability its due to Brave.

Btw, how many tabs can Brave support? Does it use the same safe multiprocessing architecture as Chromium? (On Chrome I don't have this problem even with over 1000 tabs.)

**Comment by srirambv** [comment] 2017-10-27 09:46
Do you have any steps that you can give? Which version are you running? Was it a hard crash or a web view crash?

Request to use the template in future as it gives us more information to analyse the issue

**Comment by luixxiul** [comment] 2017-10-27 10:14
@Pacerier You'll need to provide quite a bit more context and also explain where is a problem.

The same request as https://github.com/whatwg/html/issues/3156#issuecomment-338573028 .

**Comment by Pacerier** [comment] 2017-10-27 10:21
OS was running fine for past weeks/months; few days ago I installed Brave; came back home yesterday OS restarted. ~90% probability its due to Brave.

How many tabs can Brave support btw, and does it use the same as safe multiprocessing architecture as Chromium?

**Comment by luixxiul** [comment] 2017-10-27 15:56
> ~90% probability its due to Brave.

How did you find that? Is it your guess (it is ok) or based on statistics?

**Comment by Pacerier** [comment] 2017-10-27 17:39
@luixxiul, by fair heuristics.

**Comment by luixxiul** [comment] 2017-10-29 05:17
Let's discuss the issue on the community (https://community.brave.com/c/qa/) until you would be able to find certain steps to reproduce the issue. Closing the issue for now.

**Closed by luixxiul** 2017-10-29 05:17 UTC
Labels: needs-info

**Comment by Pacerier** [comment] 2017-11-26 06:52
> discuss the issue on the community (https://community.brave.com/c/qa/)

'guess that gotta wait. 'don't got time to invest in learning yetanother UI at the moment.

**Comment by Pacerier** [comment] 2017-11-26 06:54
Slightly related issue: https://apple.stackexchange.com/q/306820/6533 (Brave was noted)

**Comment by Aelay** [comment] 2018-02-26 22:43
I have a similar problem. I have an old Macbook Pro that is running fine, the only problem with it is that the battery is out of lifecycles, so it dies very quickly, when not connected to power, sometimes this happens when there are a lot of heavy processes launched.

I have noticed that this happens pretty much every time I try to do something with Brave+Metamask in Brave. I tried closing every other application running before opening Brave. But the issue seems to persist.

Switching away from using Brave, because my laptop crashes unexpectedly when I use it.
Seems to have to do something with performance. Seems like something in Brave/Metamask loads the computer so heavily that OS pulls the panic cord.

I can post system info and try to reproduce the issue and send crash report if need be.
