### ISSUE TITLE
https://riot.im/app/ never loads

### ISSUE THREAD

**Issue by agilob** [brave/browser-laptop#11545] opened 2017-10-15 19:06 UTC
### Description
Some webpages never load or render, eg. https://riot.im/app/ never fully loads, it just show rotating circle.

### Steps to Reproduce
  1. Visit https://riot.im/app/

**Actual result:**
Webpage doesnt load

**Reproduces how often:** 10/10

### Brave Version

**about:brave info:**
 
Brave: 0.19.48 
rev: de939f6dcd1647f43de544b22dfdd103585b4ec2 
Muon: 4.4.28 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.13.5-1-ARCH 
OS Architecture: x64

**Comment by Liunkae** [comment] 2017-10-15 22:18
Did you try with shields down? The problem could be caused by adblock and/or HTTPSEverywhere.

**Comment by bsclifton** [comment] 2017-10-16 06:03
@Liunkae I tried it with shields down and still ran into an error.  I'm on macOS and when I visit the URL above, it's just a white page with a spinner.  With shields down, a fresh reload shows the following in the console:
```
h1.js:25 Uncaught Error: cannot enable cancellation after promises are in use
    at Function.n.config (h1.js:25)
    at Object.<anonymous> (h1.js:98)
    at t (h1.js:1)
    at h1.js:1
    at h1.js:1
n.config @ h1.js:25
(anonymous) @ h1.js:98
t @ h1.js:1
(anonymous) @ h1.js:1
(anonymous) @ h1.js:1
rageshake.js:65 Initialised rageshake: See https://bugs.chromium.org/p/chromium/issues/detail?id=583193 to fix line numbers on Chrome.
rageshake.js:65 set language to en-us
index.js:218 GET https://riot.im/app/config.riot.im.json 404 (Not Found)
t @ index.js:218
e @ index.js:179
l @ index.js:193
(anonymous) @ index.js:270
r @ runtime.js:65
(anonymous) @ runtime.js:299
e.(anonymous function) @ runtime.js:117
o @ util.js:16
l._promiseFulfilled @ generators.js:97
i._settlePromise @ promise.js:574
i._settlePromise0 @ promise.js:614
i._settlePromises @ promise.js:693
r._drainQueue @ async.js:133
r._drainQueues @ async.js:143
drainQueues @ async.js:17
Promise resolved (async)
i @ schedule.js:18
r._queueTick @ async.js:152
a @ async.js:88
i._fulfill @ promise.js:640
i._resolveCallback @ promise.js:432
(anonymous) @ promise.js:484
(anonymous) @ languageHandler.js:257
l @ index.js:294
r @ index.js:244
XMLHttpRequest.send (async)
t @ index.js:218
e @ index.js:179
(anonymous) @ languageHandler.js:250
e._execute @ debuggability.js:300
i._resolveFromExecutor @ promise.js:483
i @ promise.js:79
m @ languageHandler.js:249
(anonymous) @ languageHandler.js:169
o @ util.js:16
i._settlePromiseFromHandler @ promise.js:512
i._settlePromise @ promise.js:569
i._settlePromise0 @ promise.js:614
i._settlePromises @ promise.js:693
r._drainQueue @ async.js:133
r._drainQueues @ async.js:143
drainQueues @ async.js:17
Promise resolved (async)
i @ schedule.js:18
r._queueTick @ async.js:152
a @ async.js:88
i._fulfill @ promise.js:640
i._resolveCallback @ promise.js:432
(anonymous) @ promise.js:484
(anonymous) @ languageHandler.js:257
l @ index.js:294
r @ index.js:244
XMLHttpRequest.send (async)
t @ index.js:218
e @ index.js:179
(anonymous) @ languageHandler.js:250
e._execute @ debuggability.js:300
i._resolveFromExecutor @ promise.js:483
i @ promise.js:79
m @ languageHandler.js:249
(anonymous) @ languageHandler.js:160
o @ util.js:16
i._settlePromiseFromHandler @ promise.js:512
i._settlePromise @ promise.js:569
i._settlePromise0 @ promise.js:614
i._settlePromises @ promise.js:693
r._drainQueue @ async.js:133
r._drainQueues @ async.js:143
drainQueues @ async.js:17
Promise resolved (async)
i @ schedule.js:18
r._queueTick @ async.js:152
a @ async.js:88
i._fulfill @ promise.js:640
i._resolveCallback @ promise.js:432
(anonymous) @ promise.js:484
(anonymous) @ languageHandler.js:242
l @ index.js:294
r @ index.js:244
XMLHttpRequest.send (async)
t @ index.js:218
e @ index.js:179
(anonymous) @ languageHandler.js:235
e._execute @ debuggability.js:300
i._resolveFromExecutor @ promise.js:483
i @ promise.js:79
p @ languageHandler.js:234
s @ languageHandler.js:145
(anonymous) @ index.js:340
r @ runtime.js:65
(anonymous) @ runtime.js:299
e.(anonymous function) @ runtime.js:117
o @ util.js:16
l._promiseFulfilled @ generators.js:97
(anonymous) @ generators.js:201
(anonymous) @ bundle.js:350
(anonymous) @ index.js:237
r @ runtime.js:65
(anonymous) @ runtime.js:299
e.(anonymous function) @ runtime.js:117
o @ util.js:16
l._promiseFulfilled @ generators.js:97
(anonymous) @ generators.js:201
(anonymous) @ bundle.js:303
(anonymous) @ index.js:346
(anonymous) @ bundle.js:563
t @ bootstrap 70d391c5f35b24369fa7:49
(anonymous) @ bootstrap 70d391c5f35b24369fa7:92
(anonymous) @ bootstrap 70d391c5f35b24369fa7:92
rageshake.js:65 Vector starting at https://riot.im/app/
rageshake.js:65 No previous session found.
rageshake.js:65 Doing guest login on https://matrix.org
rageshake.js:65 Initialised anonymous analytics
rageshake.js:65 Registered as guest: @402895:matrix.org
rageshake.js:65 setLoggedIn: mxid: @402895:matrix.org deviceId: guest_device guest: true hs: https://matrix.org
rageshake.js:65 Removing indexeddb instance: matrix-js-sdk:crypto
rageshake.js:65 Removed indexeddb instance: matrix-js-sdk:crypto
rageshake.js:65 IndexedDB worker is ready
indexeddb-local-backend.js?79bc:193 
```

**Comment by agilob** [comment] 2017-10-16 10:40
>Did you try with shields down?

Yes, I did. riot never worked in brave, I remember it not working in version ~0.17, so I dont think it's a regression btw. I'll provide you with console screenshot from syncthing later today.

**Comment by luixxiul** [comment] 2017-11-13 20:16
Closing as duplicate of https://github.com/brave/browser-laptop/issues/10685

**Closed by luixxiul** 2017-11-13 20:16 UTC
Labels: webcompat

**Comment by moratar** [comment] 2018-01-05 14:58
Is there any solution to use RIOT with brave browser?
