### ISSUE TITLE
Brave update on Mac OS X fails silently with non-admin user

### ISSUE THREAD

**Issue by justsee** [brave/browser-laptop#12991] opened 2018-02-02 01:40 UTC
### Description

Attempting to do an in-browser update of Brave on Mac OS X Sierra / High Sierra with a non-admin user account appears to fail silently, rather than prompting with an admin authentication request to update the app.

### Steps to Reproduce

  1. Install Brave-0.20.29.dmg on a user account that is not an admin account
  2. Open Brave and check for updates to trigger the in-browser alert
  3. Click to upgrade the browser using the in-browser alert button

**Actual result:**

  1. On Brave restart the version is still 0.20.29 and the upgrade alert  re-appears

**Expected result:**

  1. An authentication request to update the application should appear
  1. On Brave restart the version should be 0.20.30

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**
 
Brave: 0.20.29 
V8: 6.4.388.40 
rev: 4fc3c8ff3bcb6af75088b125e00d3a70382b9bec 
Muon: 4.7.9 
OS Release: 17.3.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Reproducible on current live release:**

No - it requires a newer version than the existing browser to confirm the behaviour.

### Additional Information

This has been the case on 2 machines across multiple versions. Upgrading in-browser has never worked so each time a fresh download and install is undertaken manually.

The only [similar issue](https://community.brave.com/t/updates-are-available-but-applying-them-doesnt-work-on-macos/9996/2) on the community site does not appear to be relevant to this issue.

**Comment by Liunkae** [comment] 2018-02-02 18:49
Looks like a duplicate of #10100

**Comment by bsclifton** [comment] 2018-02-14 06:58
@Liunkae yup- duplicate for sure! Closing this one.  Thanks for the report, @justsee 😄

**Closed by bsclifton** 2018-02-14 06:58 UTC
