### ISSUE TITLE
Beta & Developer Channel only open on frist time

### ISSUE THREAD

**Issue by vaguiners** [brave/browser-laptop#11815] opened 2017-11-06 23:40 UTC
v0.21.2 and v0.20.5 opens normally here on windows 7 sp1 x64, but when i close the browser and try to open again, the mouse keeps blinking a loading and nothing happens

is not a problem withu profiles folder. if i remove the profiles folder, the problem keeps on. but if i reinstall brave, opens normally lol

**Comment by srirambv** [comment] 2017-11-07 12:23
Dupe of #11791.

**Closed by srirambv** 2017-11-07 12:23 UTC
