### ISSUE TITLE
installing brave-beta creates both "brave" & "brave-beta" folders

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12046] opened 2017-11-21 06:54 UTC
### Description

When installing `0.20.7` under either Ubuntu or Windows, both `brave` and `brave-beta` folders are being created... Example:

Under Windows, the `brave` folder includes the following:

* `CrashPad`
* `Extensions`
* `CrashPadMetrics.pma`
* `CrashPadMetrics-active.pma`

Under Ubuntu, the `brave` folder includes the following:

* `CrashPad`
* `Extensions`
* `ShaderCache`

### Steps to Reproduce

Install `0.20.7` and check the following locations:

* `C:\Users\kjozwiak\AppData\Roaming\` (under Win 10)
* `~./config` (under Ubuntu)

You'll notice both `brave` and `brave-beta` folders being created.

**Actual result:**

When installing `0.20.7`, brave-beta creates both `brave` & `brave-beta` folders.

**Expected result:**

When you're installing the BETA channel, `brave-beta` should be the only folder being created.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

 
> Brave: 0.20.7 
> rev: a2ba3e8c4c86f029b73b47c8185e9e851825e04a 
> Muon: 4.5.16 
> libchromiumcontent: 62.0.3202.94

**Reproducible on current live release:**

N/A

### Additional Information

This doesn't seem to be reproducible under macOS. Installing `0.20.7` only creates `brave-beta` under `~/Library/Application\ Support/`.

CC'ing @darkdh

**Comment by bsclifton** [comment] 2017-11-21 07:02
@darkdh is this related to https://github.com/brave/browser-laptop/issues/11760 ?

**Comment by darkdh** [comment] 2017-11-21 17:18
I can't reproduce #11760 so I won't say it is related.
@kjozwiak did you launch brave-beta from console without any args?

**Comment by darkdh** [comment] 2017-11-21 17:23
Here is the thing, we require `--user-data-dir-name` on Windows and Linux for multi-channel thing.
And we will automatically relaunch to append the switch but it has already been launched once without it. So that is probably why it will create a `brave` folder first if there isn't one.
It is inevitable on the first launch after installation on Windows.

**Comment by srirambv** [comment] 2018-02-23 16:12
![image](https://user-images.githubusercontent.com/17010094/36603923-49c01bd2-18e2-11e8-9d87-b8333e15d30a.png)

Launching from shortcut i can still reproduce this issue. When there is only Brave beta installed and after closing the browser, a brave folder with crashpad metrics folder .pma files are created along with beta profile folder

**Comment by darkdh** [comment] 2018-02-23 18:51
yeah, after installation it will automatically launch without user-data-dir-name switch and then re launch with the switch.
We can address this at https://github.com/brave/Squirrel.Windows
@bsclifton, @petemill

**Closed** 2018-08-06 23:04 UTC
Labels: 0.20.x, OS/Windows, OS/unix-like/linux, bug, fixed-with-brave-core, installation, priority/P5, wontfix
