### ISSUE TITLE
Verified checkmark not showing next to all verified publishers

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#11986] opened 2017-11-15 23:20 UTC
## Test plan
1. Enable payments
2. Visit https://www.youtube.com/watch?v=7CFlMfkEYsg and watch for a while
3. `alexwykoff on Youtube` should show in Preferences > Payments
4. Look and verify the green "verified" checkmark is next to the channel

### Description
Some publishers are not being displayed as verified. In this screenshot, `alexwykoff on YouTube` should be verified
![image](https://user-images.githubusercontent.com/4733304/32865548-d0c050fe-ca20-11e7-8744-16b2c5f28487.png)

**Comment by bsclifton** [comment] 2017-11-15 23:53
master 67b1d5d23f952bfbc38a0cc6d2f2ab5f96faab68
0.21.x 3b96e8dfe02aea13523d22b47acc8d9694d6f83d
0.20.x eaeec2522a214c7a7b92d1b2f7467c9abfa61c37
0.19.x c15e27e63b51ab1c61679189871c997ec635444a

**Comment by kjozwiak** [comment] 2017-11-16 04:04
This isn't working on macOS... Watched the video from https://github.com/brave/browser-laptop/issues/11986#issue-274340310 several times on macOS and the verified badge never appeared... @aekeus also reproduced the issue on his macOS machine. Works under Ubuntu/Win.

Platforms checked:

* macOS 10.12.6 x64 using `0.19.95`- **_FAILED_** (verified badge not being displayed)
* Win 10 x64 using `0.19.95` - **_PASSED_** (verified badge is being displayed)
* Ubuntu Ubuntu 17.04 x64 - **_PASSED_** (verified badge is being displayed)

**Comment by kjozwiak** [comment] 2017-11-16 04:20
I'm going to leave this opened just incase we find another issue before release that might result in a new build.. If that's the case, we should fix this as well.

If we don't create another build, we should still leave this in the current build and release either way. It's working on Win/Linux and I don't think we have any "official" verified content providers. By the time we get people onboard, we should be releasing `hotfix6` which would resolve the remaining issue with macOS...

If someone disagree's, please let me know!

**Comment by NejcZdovc** [comment] 2017-11-16 06:28
will check out what is going on

**Comment by srirambv** [comment] 2017-11-16 08:13
Verified on Windows
![image](https://user-images.githubusercontent.com/17010094/32880549-017d4898-caa6-11e7-8e20-6d01be232fff.png)

**Comment by kjozwiak** [comment] 2017-11-16 18:19
QA will re-test this once the macOS issue has been resolved. Verified badges for YT channels are only appearing under Win/Linux under `0.19.95` at the moment.

**Comment by Alino** [comment] 2017-11-21 00:05
I confirm the issue is present on my machine with MacOS high sierra.

**Comment by NejcZdovc** [comment] 2017-11-23 13:11
@kjozwiak can you please retest it on the latest 0.19 version, 0.19.96. Thank you

**Comment by kjozwiak** [comment] 2017-11-27 06:41
@NejcZdovc, looks like this is working under `0.19.98`:

<img width="846" alt="screen shot 2017-11-26 at 11 18 05 pm" src="https://user-images.githubusercontent.com/2602313/33252241-db854bb4-d30a-11e7-97d5-522dd9280ab9.png">

Checked using the following platforms:

* macOS 10.12.6 x64 - PASSED (verified icon was being displayed in the ledger table)
* Ubuntu 17.10 x64 - PASSED (verified icon was being displayed in the ledger table)
* Win 10 Pro x64 - PASSED (verified icon was being displayed in the ledger table)

**Comment by NejcZdovc** [comment] 2017-11-27 07:41
great, closing it

**Closed by NejcZdovc** 2017-11-27 07:41 UTC
Labels: 0.19.x, bug, feature/ledger, initiative/bat-payments, release-notes/exclude

**Comment by kjozwiak** [comment] 2017-11-29 04:34
Double checked using `0.19.99`:

macOS 10.12.6 x64 - PASSED (verified icon was being displayed in the ledger table)
Ubuntu 17.10 x64 - PASSED (verified icon was being displayed in the ledger table)
Win 10 Pro x64 - PASSED (verified icon was being displayed in the ledger table)
