### ISSUE TITLE
URL not opening from external application in Fedora 25

### ISSUE THREAD

**Issue by pvital** [brave/browser-laptop#9714] opened 2017-06-26 13:29 UTC
When clicking in a link URL from external application in Fedora 25, like Thunderbird or Slack, Brave is not able to: 1) opening a new tab (as configured to handle new links); and 2) load the URL link. 

Instead of open the desired link in a new tab, Brave only came up to screen and nothing happens. Brave is the default browser in this system.

Brave: 0.16.9 
rev: fba98fcb091b3abfa18aba7c6c0db0c7aa343589 
Muon: 4.0.2 
libchromiumcontent: 59.0.3071.86 
V8: 5.9.211.31 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: linux 
os.release: 4.11.5-200.fc25.x86_64 
os.arch: x64

- Steps to reproduce:
    1. Click in any link from external app, like Thunderbird or Slack;
    
- Actual result:
Brave came up to screen and nothing happens.

- Expected result:
Brave came up to screen and load the URL link clicked from external app in a new tab.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes. It happens every time I click in URL link from an external app.

**Comment by brianpatrickreavey** [comment] 2017-06-27 02:07
Same issue here:
- fedora 25
- brave 0.16.13 installed from `dnf`

Also will not open from CLI if brave is already running (same behavior as from another application).

If Brave is not yet running, CLI launches previous tabs (per config) and a new window with the URL specified on the CLI.

**Comment by DivineOmega** [comment] 2017-07-11 09:35
I've discovered this appears to be a problem with the `brave.desktop` file that ships with Brave.

You can fix this with the following steps.

1. `sudo updatedb`
2. `locate brave.desktop`
3. `sudo nano /path/to/brave.desktop`
4. Change the line `Exec=brave %U` to `Exec=brave -- %U
5. Save & exit nano (CTRL + O, CTRL + X).

**Comment by brianpatrickreavey** [comment] 2017-07-11 13:25
Worked for me as well.  Thanks!

**Comment by pvital** [comment] 2017-07-11 13:38
Works for me also. Will check the source code and submit a PR if not implemented yet.

**Comment by Liunkae** [comment] 2017-07-11 15:22
PR #9890 will fix this.

**Comment by bsclifton** [comment] 2017-08-09 17:51
Closing this issue as a duplicate of https://github.com/brave/browser-laptop/issues/9193

Please note: this should be fixed with https://github.com/brave/browser-laptop/pull/10215

Some folks are reporting that even with this fix though, there are still issues (see work-around using `xdg-settings`

**Closed by bsclifton** 2017-08-09 17:51 UTC
Labels: bug, OS/linux-distros
