### ISSUE TITLE
Extension icons are not displayed due to "Not allowed load local resource"

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11797] opened 2017-11-06 07:46 UTC
### Description

Extension icons are not displayed due to "Not allowed load local resource".

### Test plan / Steps to Reproduce

  1. Install 0.20.5
  2. `$ brave-beta`
  3. Open `about:preferences#extensions`
  4. Enable Metamask

**Actual result:**

The icon is not displayed. Restarting the browser does not help.

![clipboard01](https://user-images.githubusercontent.com/3362943/32430257-e0f9bd40-c311-11e7-8211-488ae3371836.png)

**Expected result:**

It should be displayed

**Reproduces how often:**

Consistently

### Brave Version

**about:brave info:**

Brave: 0.20.5 
V8: 6.2.414.36 
rev: 0cc4f80e759d303fa109ab427ce862d5720dd97b 
Muon: 4.5.14 
OS Release: 4.9.0-3-amd64 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 62.0.3202.75

**Reproducible on current live release:**

No.

**Comment by darkenvy** [comment] 2017-11-20 01:25
![https://puu.sh/ypCnG/34d8101b55.png](https://puu.sh/ypCnG/34d8101b55.png)

**Comment by darkenvy** [comment] 2017-11-20 02:26
Quick workaround solution for development is posted here: https://github.com/electron/electron/issues/5107 . It was to add `webSecurity: false` in the `webPreferences` object in windowReducer.js. Obviously this is not ideal as this drops web securities such as local file access.

I will be waiting for a real fix.

**Comment by bsclifton** [comment] 2017-11-20 06:15
@luixxiul is this a dupe of https://github.com/brave/browser-laptop/issues/11142? If so, there is a PR waiting for review:
https://github.com/brave/browser-laptop/pull/11143

**Comment by luixxiul** [comment] 2017-11-20 06:42
I'm not quite sure as I experienced the issue on Debian.

**Comment by bsclifton** [comment] 2017-11-20 16:12
@luixxiul can you check on macOS?

**Comment by darkenvy** [comment] 2017-11-20 22:09
I am on OSX btw. I should have mentioned that.

**Comment by bsclifton** [comment] 2018-01-23 21:13
Fixed w/ https://github.com/brave/browser-laptop/pull/11143

**Closed by bsclifton** 2018-01-23 21:13 UTC
Labels: 0.20.x, QA/test-plan-specified, bug, feature/extensions, regression, release-notes/exclude
