### ISSUE TITLE
Error at opening any .pdf

### ISSUE THREAD

**Issue by eiyey** [brave/browser-laptop#13068] opened 2018-02-08 09:00 UTC
Hi,

Opening any .pdf link shows the same error:

This site can’t be reached
The webpage at chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/web/viewer.html?file=http%3A%2F%2Fwww.pdf995.com%2Fsamples%2Fpdf.pdf might be temporarily down or it may have moved permanently to a new web address.
ERR_FAILED

![pdferror](https://user-images.githubusercontent.com/36115757/35964004-bc5c671e-0cb6-11e8-8b05-df58daa5d848.png)

 
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 6.3.9600 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Comment by srirambv** [comment] 2018-02-08 09:29
Is the PDF extension enabled on the browser? seems to work for me without any issues
![image](https://user-images.githubusercontent.com/17010094/35965323-94ea2c8c-0ce0-11e8-80e2-e9ac963d30b5.png)

**Comment by eiyey** [comment] 2018-02-08 09:44
I can't see that extension so I guess it's not enabled.
![pdferror1](https://user-images.githubusercontent.com/36115757/35966042-fd906ca2-0cbc-11e8-8d42-89d174939299.png)

**Comment by srirambv** [comment] 2018-02-08 12:11
Do you mind checking if you have any folders listed under `%AppData%\brave\Extensions`

**Comment by eiyey** [comment] 2018-02-08 20:59
Yeah I have 1 folder in %AppData%\Roaming\brave\Extensions called: jdbefljfgobbmcidnmpjamcbhnbphjnb

![system](https://user-images.githubusercontent.com/36115757/35997892-4091aeea-0d1b-11e8-9925-f22a721a8a22.png)

**Comment by bsclifton** [comment] 2018-02-08 22:08
wow- that's weird... I'm not sure why it's not showing for you @eiyey 

Can you try the following steps?
1. Quit Brave completely
2. Move, rename, or delete the `%APPDATA%\brave\Extensions\jdbefljfgobbmcidnmpjamcbhnbphjnb` folder
3. Start Brave back up- give it a few minutes
4. Extension should be re-downloaded

At that point, it should work fine

**Comment by eiyey** [comment] 2018-02-09 11:07
Did it step by step and the problem persists. There is no new extension and therefore I'm still unable to view pdfs. I'm going to test it on virtual machines. Let's see how it goes.

**Comment by eiyey** [comment] 2018-02-09 11:20
Before testing it on a virtual machine I tried it first on another user account in the same computer and surprisingly the PDF viewer extension is there and I can view pdfs. I will keep trying it on my main user account to see what the problem can be. Any help is appreciated.

**Comment by srirambv** [comment] 2018-02-09 11:44
@eiyey  just to confirm when you rename the folder under `%appdata% and relaunch Brave you are still not able to see the extension listed ?

**Comment by eiyey** [comment] 2018-02-09 13:34
Yes @srirambv , I can't still see the extension listed. I've tried renaming it and then relaunching it, deleting it and the relaunching it, uninstalling it and re-installing it, turning off the antivirus and firewall, etc etc etc.

**Comment by eiyey** [comment] 2018-02-11 13:43
I still can't find a solution but I noticed a user made a post about this some months ago.
https://community.brave.com/t/no-pdf-viewer-extension/9419

**Comment by eiyey** [comment] 2018-02-23 23:43
Any solution guys? I'm eager to use Brave but I can't because of this trouble.

**Comment by LukasGI** [comment] 2018-03-21 09:40
I can confirm that I have exactly the same problem on several computers (Windows 7 Pro 64bit). Please find the solution as soon as possible.

**Comment by Altaren** [comment] 2018-05-31 19:28
Sorry to dig up this old post but I also get the error and it's quite annoying.

I'm really not sure but the issue could come from a user folder that contains non-ASCII characters inside its name. 
@eiyey Is your user folder contains such character ? If yes, does the other user-account on which you tried to use the extension successfully contain this kind of character too ?

**Comment by eiyey** [comment] 2018-06-01 22:30
That's a really good point. The name of the user account in which the pdf extension is not showing contains a non-ASCII character and the account that works properly doesn't have this non-ASCII character. I'm going to create another user account with this non-ASCII character and see if this could be the problem.

**Comment by eiyey** [comment] 2018-06-01 23:35
You are completely right @Altaren . When the user folder name contains a non-ASCII character the pdf extension is not shown.

So thanks to you we have finally discovered the origin of the problem. I hope @srirambv and @bsclifton can take a look at this.

**Comment by srirambv** [comment] 2018-06-02 00:19
We are tracking the issue with non-ASCII profile characters here https://github.com/brave/browser-laptop/issues/9425.

**Comment by bsclifton** [comment] 2018-08-03 00:02
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/9425

**Closed by bsclifton** 2018-08-03 00:02 UTC
Labels: needs-info, plugin/pdfjs, windows-important
