### ISSUE TITLE
Hitbox of the top-left corner (for resizing) is split

### ISSUE THREAD

**Issue by Zuzu-Typ** [brave/browser-laptop#6654] opened 2017-01-15 20:29 UTC
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
The cut-off-edges seem to also affect the hitbox of the top-left corner, meaning that you cannot use the mouse to resize it diagonally as intended,

**Expected behavior:**
Even the very peek of the top-left corner should be resizeable.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
1.13.0 Preview 8

- Steps to reproduce:
    1. Open Brave as a non-maximized window
    2. Try resizing it on the top-left corner on it's peek

- Screenshot if needed:
![Corner](https://cloud.githubusercontent.com/assets/20467351/21965912/88502d2c-db69-11e6-9829-9b2d4bab3529.gif)

- Any related issues:
https://github.com/brave/browser-laptop/issues/4216

- May be related:
https://github.com/brave/browser-laptop/issues/6445
https://github.com/brave/browser-laptop/issues/3036

**Comment by bsclifton** [comment] 2017-01-16 04:08
@Zuzu-Typ you must be at 200% DPI :smile: Like you have discovered, this issue is a duplicate of https://github.com/brave/browser-laptop/issues/4216

**Closed by bsclifton** 2017-01-16 04:08 UTC
