### ISSUE TITLE
Add automated tests for ledger backup and recovery

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#4657] opened 2016-10-10 23:13 UTC
Splitting this out into a separate ticket. I'm not sure how to go about adding automated tests for the new recovery functionality but it seems like we should definitely have some.

I'm more than happy to work on this with some guidance from someone else but also happy if someone with a good idea for approach wants to take it!

**Comment by mrose17** [comment] 2017-03-07 18:03
duplicate of #6890

**Closed by mrose17** 2017-03-07 18:03 UTC
Labels: automated-tests, feature/ledger
