### ISSUE TITLE
Exporting manually added bookmark and importing shows wrong date

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7814] opened 2017-03-21 18:53 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Exporting manually added bookmark and importing shows wrong date

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.0
rev	64b381a
- Steps to reproduce:
    1. Manually add a bookmark from about:bookmark, do not visit the site by clicking on the bookmark
    2. Export the bookmark to a file
    3. Import the bookmark file from step 2
    4. Last visited date shows as `1/1/1970`
    
- Actual result:
Wrong date shown when bookmark is imported

- Expected result:
Should only show date if the bookmark is opened 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Not checked

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![bookamrk](https://cloud.githubusercontent.com/assets/17010094/24165163/9b04ac82-0e67-11e7-8775-00f1475f5ef4.gif)

- Any related issues:
Please change milestone if required

**Comment by bsclifton** [comment] 2017-04-05 06:58
Moving to backlog- this is a good first bug 😄

**Comment by kumarrishav** [comment] 2017-05-04 07:05
Hey @srirambv Can you confirm this bug again? I am unable to reproduce it on 
Name	Version
Brave	0.15.1
rev	ea5024d

**Comment by srirambv** [comment] 2017-05-04 09:00
@kumarrishav  Yes it is still an issue with ea5024d. Here is the proper STR 
1. Add a bookmark with https:// 
2. Export the bookmark to a file
3. Delete the bookmark added in step 1
4. Import the file  created in step 2
5. Bookmark imports from 1970

One thing I found is this doesn't happen if you add a site as http:// instead of https:// . So the URL has to proper for it to happen. Here is a screen record for both https:// and http://
![7814](https://cloud.githubusercontent.com/assets/17010094/25696811/71ce41b4-30b0-11e7-9ad6-c11f3d5fded4.gif)

**Comment by kumarrishav** [comment] 2017-05-05 00:51
Oh, it's issue in Windows platform. Okay. In macOS, it's working fine.

**Comment by jasonrsadler** [comment] 2018-03-01 22:37
"Last Date Visited" doesn't show on mine. Was this removed?

**Comment by bsclifton** [comment] 2018-03-02 06:23
Good catch, @jasonrsadler - appears it was removed by @ayumi with https://github.com/brave/browser-laptop/commit/9295e1e99a61aa7246d7a04fa2bed910e126573c#diff-bae3b166a025002f1427212efda5497b

**Closed** 2018-08-26 08:54 UTC
Labels: OS/Windows, bug, feature/bookmarks, fixed-with-brave-core, wontfix
