### ISSUE TITLE
Can't log into one of my 3 gmail accounts

### ISSUE THREAD

**Issue by bkarlan** [brave/browser-laptop#5471] opened 2016-11-07 21:21 UTC
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
I can log in, in Firefox or Safari, but not in brave.  I have 3 gmail accounts.  I can log into 2 of them, but never the third.  This despite the fact that the password section correctly identifies the correct email.  Additionally, when trying to log into another of my 2 gmail accounts, it is random as to which email it will log into, regardless of what email and password I type.  Very bizzare.  It doesn't happen on other browsers.
**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
mac Sierra
- Brave Version:
12.8
- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/2250480/20076338/ac0e6b7c-a4fd-11e6-99c2-702db419aed4.png)
![image](https://cloud.githubusercontent.com/assets/2250480/20076350/b65e223e-a4fd-11e6-9e0e-6909d3748468.png)
![image](https://cloud.githubusercontent.com/assets/2250480/20076380/cf0c8640-a4fd-11e6-8570-4e8089084ab3.png)

- Any related issues:

**Comment by srirambv** [comment] 2016-11-07 21:23
Duplicate of #2001. Closing the issue

**Comment by bkarlan** [comment] 2016-11-07 21:24
Why did you close this?

**Closed by srirambv** 2016-11-07 21:23 UTC

**Comment by srirambv** [comment] 2016-11-07 22:01
There is already an issue logged for the same thing which is being tracked.
