### ISSUE TITLE
flash of selected tab when hovering across the border between two unselected tabs

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#720] opened 2016-02-11 06:31 UTC
With tab preview on hover enabled, 0.7.14 build on Mac.

1. open three tabs, mozilla.com, brave.com, and cnn.com
2. select the mozilla tab.
3. hover over the brave tab and see a brave preview
4. hover over the cnn.com tab and see a cnn preview
5. hover over the space between the brave and cnn tabs and see no preview, just the mozilla.com tab. 

A common behavior I find is to sweep across several tabs looking at the previews to locate a lost tab. As I slide my mouse across the tab strip, each time it moves across the gap between tabs there's a flash of the selected tab that's really jarring. I think for the purposes of tab preview on hover, there should be no gap between tabs.

**Comment by weems** [comment] 2016-02-11 07:54
This preview feature is useful, but between two tabs, I have confirmed the steps to recreate are valid inbetween: 

1. tweetdeck.twitter.com
2. vox.com
3. yahoo.com
4. github.com 

(Though the code at hand, relates to all tab preview functionality so it does not depend on specific URLs)

**Comment by bbondy** [comment] 2016-02-12 01:50
I think this is a dupe of #142. I'm thinking we can solve this without changing tab width just by debouncing the clear / show previews by something like 100ms.

**Comment by bbondy** [comment] 2016-02-12 01:51
@bradleyrichter would you prefer a timeout here or to remove the margin between tabs?

**Comment by weems** [comment] 2016-02-12 07:57
@bbondy perhaps it is @bradleyrichter expertise required but it would seem to me that the most serious issue is caused by failure of margin between tabs to function properly.

**Comment by psimyn** [comment] 2016-02-12 14:53
I think debouncing makes the most sense. even if there was no margin there is still that tabbar area above them that would have the same effect.

timeout will prevent the flicker of preview->non-preview->preview when mousing between tabs

**Comment by weems** [comment] 2016-02-12 16:49
perhaps timeout + margin will mitigate both of those issues, @psimyn

**Comment by bradleyrichter** [comment] 2016-02-12 21:56
@bbondy I think there are a few ways to solve it. Adding may will still fail when either moving slowly or accidentally drifting slowly between tabs. Adding enough of a delay to cover that slow-move case might be annoying.

We do need to maintain a visual gap between tabs and I may also add a border or even a side-border  style to non-selected tabs. Could we nest the tab in a clear DIV that allows for no gutters, and assign the function there? 

Let's try a few things in a branch and I'll play around with it until it feels right.

The problem would still exist above the tabs though as @psimyn mentioned.


Thanks for the ideas guys!

**Comment by bbondy** [comment] 2016-02-13 00:41
invisible div and have hover on that div sounds idea.  Slight debounce as well. Thanks.

**Comment by psimyn** [comment] 2016-02-13 01:16
Invisible div still has the downside of a tab being hovered when your mouse doesn't appear to be over it.

**Comment by bbondy** [comment] 2016-04-20 21:01
CSS fade animation mentioned in another ticket I think would solve this.

**Comment by bradleyrichter** [comment] 2016-04-20 22:51
I think that fade was for the URL/title bar but we could apply it to both and try to reduce the harring flicker if timing doesn't work. But I think I have made a few suggestions that would also solve it above...

**Comment by cezaraugusto** [comment] 2016-06-16 14:06
hey guys, any agreement on this?

cc @bradleyrichter @bbondy

**Comment by luixxiul** [comment] 2016-06-16 14:15
I think I have fixed this with #2063

**Closed** 2016-06-18 04:50 UTC
Labels: enhancement, info-needed
