### ISSUE TITLE
When going fullscreen, nav bar should be hidden (and show when mouse enters top of screen)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4371] opened 2016-09-29 14:15 UTC
When going fullscreen, the navigation bar, URL bar, etc should be hidden.  If you move the mouse in the area they used to occupy, we can have them slide down.

Since some folks may not want this functionality (instead preferring to always show the navigation controls), we may want to make this a preference.

**Expected behavior:**
Should show top bar every time there is mouse over at the top of the screen
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.3 RC3
- Steps to reproduce:
  1.  Set system magnification at 100%
  2. Go full screen(F11)
  3. Mouse over doesn't always shows the top bar
  4. Repeat steps 1-3 with maginification set at 125%,150% same result. At 150% is a little better, top bar is shown more often than at 100% or 125%
- Screenshot if needed:
  ![e07baf22-8622-11e6-9602-cc28a232402d](https://cloud.githubusercontent.com/assets/17010094/18957600/9db0613a-8657-11e6-93ce-4b194c065b87.gif)
- Any related issues:
  #4193 #4234

**Comment by srirambv** [comment] 2016-09-29 14:19
cc: @Sh1d0w

**Comment by bbondy** [comment] 2016-09-29 14:49
Reverted here:
#4372

It can be re-added once we have a fix for Windows. Sorry about this but this is holding up RC3 from releasing and we need it out today so it is the best option.

**Comment by Sh1d0w** [comment] 2016-10-12 18:15
Unfortunately I do not own Windows machine nor I have time to install and debug it in VM. If anyone wants to pick up my work (which is working just fine under Linux) and fix the windows magnification issue it will be much appreciated, so we can all have this nice feature.

**Comment by srirambv** [comment] 2016-10-18 03:50
@Sh1d0w @bbondy @bsclifton 

Can only the URL bar be shown in full screen mode hiding bookmarks toolbar and tabs. On windows it can become a bit confusing whether the browser is in full screen or maximized window with the current behavior( reverted to show top bar). There is no significant difference between full screen and maximized window, only the browser covers the taskbar in full screen mode.

**Comment by bbondy** [comment] 2016-10-24 21:09
Moving to 0.12.8

**Comment by Sh1d0w** [comment] 2016-10-25 03:56
Can I kindly ask @bradleyrichter for suggestions how it should behave?

Brad please see https://github.com/brave/browser-laptop/issues/4234

**Comment by bsclifton** [comment] 2016-10-31 20:28
Removing milestone for now

@bbondy @bradleyrichter please feel free to re-assign a milestone (also, see @Sh1d0w's question in last post)

**Comment by Seferi** [comment] 2017-03-17 20:23
Hi, i was wondering when it will be implemented back.. I think full screen is a very important feature especially for smaller screens. It should be a priority imho..

**Comment by bsclifton** [comment] 2017-03-24 22:46
@Seferi good question... priority-wise, this is likely something we'll get to after version 1.0.  However, I agree: this would be a great one to have.  I wonder if any of our contributors are interested?

Let me clean up the issue a bit (so the description of what we'd like is clear) and I'll tag with "Help wanted" 😄

**Comment by bsclifton** [comment] 2017-03-24 22:49
@Seferi please check the original issue above (which I edited). Anything I missed? 😄

**Comment by Seferi** [comment] 2017-03-28 19:47
@bsclifton Thanks mate!

**Comment by michaelrule4** [comment] 2017-11-05 04:17
Hi,

I'm a new user to Brave and while playing some .io games and I am in F11 mode the entire nav-bar is shown as seen below:

![image](https://user-images.githubusercontent.com/4140097/32411929-b1baa5c0-c1be-11e7-8ed5-88d45b55eebf.png)

Firefox & Chrome hide the nav-bar (although in different fashions) when in F11 mode. It would be really nice if Brave could also do the same thing. I would appreciate if something could be done about this :S

**Comment by bsclifton** [comment] 2017-12-26 16:41
+1 from @Kasmetski via https://github.com/brave/browser-laptop/issues/12399
> Fullscreen option doesn't work. It hides only the menubar and topbar.
I'm expecting to hide everything like Chrome & Firefox. It should hide bookmarks, url bar and everything other except opened page.

**Comment by chrishobcroft** [comment] 2018-08-18 17:12
For me, this is one of the main drawbacks of Brave over e.g. Chromium or Firefox on Ubuntu.

The beauty of surfing the web without any kind of navigation bar is really appealing, and having to "waste" about 13% (rough estimate) of the screen real-estate is disappointing.

Expected behaviour is that when you press F11, the full screen becomes dedicated to the webpage that you are viewing. And if you move the mouse to the top, or press Ctrl-T to open a new tab, then it should show the address bar (not the bookmarks bar / tabs bar).

**Comment by bsclifton** [comment] 2018-09-21 06:06
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/11463 (which is marked as `fixed-with-brave-core`).  You can download the developer channel release here:
https://brave.com/download-dev

**Closed by bsclifton** 2018-09-21 06:06 UTC
Labels: misc/fullscreen-option, usability
