### ISSUE TITLE
"Stop seeding" button on torrent viewer

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6815] opened 2017-01-23 02:33 UTC
**Describe the issue you encountered:**
"Stop seeding" button on torrent viewer should be implemented

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.13.0 RC5

- Steps to reproduce:
    1. Open https://codepen.io/ferossity/full/qaezaB/
    2. Click "sintel.mp4"
    3. Click "Start download"
    4. Wait until the download is finished
    5. The button "seeding" which cannot be clicked appears
    5. Close the tab
    6. Reopen the tab
    7. The button still remains
    
- Actual result:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/22189305/27e9e9b8-e15f-11e6-8f44-adbb978110c1.png)

- Expected result:
There should be a stop seeding button

- Any related issues: #3256 

CC @feross @dcposch: Is stopping not intended?

**Comment by dcposch** [comment] 2017-01-23 06:14
When you close all tabs for a given torrent, after a timeout of a few seconds, that torrent will be removed. In other words, it'll stop downloading or seeding.

@feross any reason why the button is disabled? What if the button was just a toggle, so that people could stop an in-progress download or stop seeding without closing the tab?

**Comment by srirambv** [comment] 2017-01-23 10:07
same as #6768

**Comment by feross** [comment] 2017-01-23 21:15
The button starts out as "Start Download". After it's clicked, we disable it.

That's totally arbitrary though. It would be fine as a toggle. Does the button pause the download, or remove it entirely from the filesystem?

Also, we need to make sure that when another tab is opened (which will re-add the torrent), that the previously paused tab gets it's state updated correctly.

**Comment by feross** [comment] 2017-03-02 21:37
Closing as duplicate of #6768

**Closed by feross** 2017-03-02 21:37 UTC
Labels: feature/torrent, misc/button, suggestion
