### ISSUE TITLE
ZenHub: Popup background is transparent

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#5998] opened 2016-12-03 01:22 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The popup window for the ZenHub extension has a transparent background, making it hard to discern the contents of the popup.

**Expected behavior:**
ZenHub should have a solid background, clearly distinguishing its content from the content beneath.

**Screenshot if needed:**

![image](https://cloud.githubusercontent.com/assets/815158/20855587/8c8cc3e0-b8c4-11e6-8c36-eeb0e3cea7c4.png)

- Any related issues:

**Comment by bsclifton** [comment] 2018-08-24 07:43
This may be a duplicate of https://github.com/brave/browser-laptop/issues/13633

ZenHub functionality will definitely be fixed when moving to [brave-core](https://github.com/brave/brave-browser)

**Closed by bsclifton** 2018-08-24 07:43 UTC
Labels: bug, feature/extensions
