### ISSUE TITLE
dropdown items not displayed

### ISSUE THREAD

**Issue by davidak** [brave/browser-laptop#6362] opened 2016-12-21 11:23 UTC
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**

I have elementary OS on my Macbook Pro (Retina) with 2 external Displays.

When i have a Brave window on one of the external displays, the items of a dropdown menu are just white. (see screenshot)

The items are correctly shown on the integrated display.

**Expected behavior:**

Dropdown menu items should be displayed regardless of the display the window is on.

- Platform (Win7, 8, 10? macOS? Linux distro?):

elementary OS 0.4 Loki (64-bit), based on Ubuntu 16.04 LTS

- Brave Version:

Name	Version
Brave	0.12.15
Muon	1.4.31
libchromiumcontent	53.0.2785.143
V8	5.3.332.47
Node.js	6.5.0
Update Channel	dev
os.platform	linux
os.release	4.4.0-53-generic
os.arch	x64

- Steps to reproduce:
    1. open Brave
    2. ensure the window is on an external display
    3. click on any dropdown, for example the Brave settings

- Screenshot if needed:

![bildschirmfoto von 2016-12-21 12 14 33](https://cloud.githubusercontent.com/assets/91113/21387464/026444fa-c778-11e6-8704-f77ea7bee5b4.png)

- Any related issues:

https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1638618

**Comment by bsclifton** [comment] 2017-05-12 06:19
Closing as I can't reproduce.  Checking the issue reported, the root cause was upstream in Chromium and was fixed with version 55.0.2883.87 😄

**Closed by bsclifton** 2017-05-12 06:19 UTC
Labels: help wanted, OS/linux-distros, settings
