### ISSUE TITLE
Bookmark toolbar context menu missing

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10999] opened 2017-09-18 06:45 UTC
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Bookmark toolbar context menu missing
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64
- Brave Version (revision SHA):
Master
- Steps to reproduce:
    1. Build from source master
    2. Add a bookmark to show bookmark toolbar
    3. Right click on bookmark toolbar, Shows browser context menu. 
    
- Actual result:
See screenshot
- Expected result:
Should show bookmark toolbar context menu
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![bmktoolbar](https://user-images.githubusercontent.com/17010094/30531290-e477a630-9c6a-11e7-9be3-55bd171ce2ff.gif)

- Any related issues:

**Comment by bsclifton** [comment] 2017-09-19 17:37
I believe this is a duplicate of https://github.com/brave/browser-laptop/issues/4244

**Comment by bsclifton** [comment] 2017-09-19 17:38
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/4244

**Closed by bsclifton** 2017-09-19 17:38 UTC
Labels: bug, duplicate, feature/bookmarks, OS/Windows
