### ISSUE TITLE
Private tabs not truly private

### ISSUE THREAD

**Issue by SilverPuppy** [brave/browser-laptop#10742] opened 2017-08-31 15:22 UTC
I have used private tabs as a way to keep multiple accounts signed in at the same time. However, when I open a new private tab and go to Youtube, it remembers me and I'm signed in with the account I used last time I used YT in a private tab. This should not be. Closing a private tab should make it forget everything associated with it.

In my case it's actually rather convenient, but it illustrates a glaring issue.

**Comment by Liunkae** [comment] 2017-08-31 15:55
Related: #6684

**Comment by SilverPuppy** [comment] 2017-08-31 16:37
Yes, that's the same issue. I didn't see it when I was looking to see if someone had already posted this issue.

**Comment by diracdeltas** [comment] 2017-08-31 19:22
closing as a duplicate of #6684 and https://github.com/brave/browser-laptop/issues/597

**Closed by diracdeltas** 2017-08-31 19:22 UTC
Labels: feature/private-tabs
