### ISSUE TITLE
Brave Keyboard Shortcuts interfere with OS Keyboard Shortcuts 

### ISSUE THREAD

**Issue by tommyquite** [brave/browser-laptop#10085] opened 2017-07-21 06:49 UTC
I am running the latest OS X software on a mac.
And I am using the latest version of Brave browser:
 
Brave: 0.17.16 
rev: 2d2ee2fba6a494eb63d0cabb8d5f3e709278c147 
Muon: 4.1.8 
libchromiumcontent: 59.0.3071.115 
V8: 5.9.211.38 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: darwin 
os.release: 16.6.0 
os.arch: x64

**Problem**
The brave browser comes with built in command key shortcuts for OSX. 
See:
![image](https://user-images.githubusercontent.com/26521436/28452030-0e99b7da-6df1-11e7-9314-676925209ab3.png)

But they interfare with my OS X set command shortcuts. For example it toggles my screen when im trying to make a selective screenshot, preventing me from using the command I intent to use. Is there  way to alter or delete this commands in the Brave browser?

If not, I think it should be updated, for me personally it's unworkable, and I imagine it's the same for other potential OS X users. And I desperately want to use Brave and the whole world to use Brave ; )

Thanks in advance.

Tom

**Comment by LaurenWags** [comment] 2017-07-21 13:01
Original community post with some additional information:
https://community.brave.com/t/mac-keyboard-cmd-shortcuts-toggle-browser-unintented/4872

**Comment by Liunkae** [comment] 2017-07-21 15:47
Default shortcuts:
![](https://user-images.githubusercontent.com/19424103/28470678-106bc238-6e00-11e7-85f2-54f239cfe05d.png)
Cmd+number is not a shortcut by default, so @tommyquite must have customized the screenshot shortcuts.

Safari uses the same shortcuts as Brave (Cmd + number), but it does not use them if the user has set the shortcuts to something else.

Steps to reproduce:

1. Go to System Preferences > Keyboard > Shortcuts > Screenshots.
2. Change "Save picture of screen as a file" to Cmd+3.
3. Open Brave, open three tabs, and activate the first tab.
4. Press Cmd+3.
5. **Notice that Brave still switches tabs**, and a screenshot is saved to the desktop.
6. Open Safari, open three tabs, and activate the first tab.
7. Press Cmd+3.
8. **Notice that Safari does not change tabs**, and a screenshot is saved to the desktop.


Brave should use Safari's behavior in this case.

**Comment by tommyquite** [comment] 2017-07-21 16:23
Yes @Liunkae, I have customized my OSX keyboard shortcuts.

Hoping there will be a way to resolve this soon. Thanks so far!

**Comment by tommyquite** [comment] 2018-04-15 17:36
I have raised this a couple of times over the last 9 months. Sorry for becoming impatient, but are there any plans of fixing this?

It's really preventing me from using the browser and I know many other mac users with me. 

Thanks!

**Comment by andrewgioia** [comment] 2018-04-16 14:45
+1 This issue unfortunately makes Brave a nonstarter for me and I really want to use it. 

I also remap Cmd+# to switch desktop spaces and Brave is nonfunctional for me without either operating the same way as Safari or letting me re-assign Brave's hotkeys.

**Comment by aljets** [comment] 2018-05-18 23:09
This affects me as well. I'm trying to use shortcuts on "Select Next Tab" and "Select Previous Tab" (`cmd`+`←` and `cmd`+`→`) . Works for other apps (iTerm, Chrome). Doesn't work on Brave. When looking at these two menu items in Brave I can see my custom shortcut (that it overrode the default ctrl-tab), but using it just goes through history, and the originals don't work either.

**Comment by krmbzds** [comment] 2018-06-04 01:49
+1

I resize my browser to the right half of the screen (using [Spectacle](https://www.spectacleapp.com/)) and it switches to the next tab. This non-feature is doing something I never intended to do.

There should either be a way to disable/change these shortcuts (#545) or Brave should have more sensible defaults. I use a lot of different apps and none of them conflicted with ⌥ + ⌘ + → so far.

**Comment by CaltrixCapital** [comment] 2018-06-20 16:40
Still seems unsolved? Is this being worked on? Still waiting for this to change, so I can use Brave. Almost been a year now.

**Comment by Gitsomelearnsome** [comment] 2018-06-20 16:44
When will this be solved? Have been waiting for almost a year now for this functionality..

**Comment by Liunkae** [comment] 2018-06-20 22:21
@Gitsomelearnsome It may be fixed when the new Chromium-based version of Brave comes out in a few months.

**Comment by v-p-b** [comment] 2018-09-28 07:53
I have very similar issues on Linux (vs. KDE based apps and even urxvt). Unfortunately it's non-deterministic (I know it's Brave because I all shortcuts start working after I close the browser) so I can't provide repro steps yet.

**Comment by bsclifton** [comment] 2018-09-28 20:39
Closing as `wontfix`; for folks affected by this, can you please try our Beta channel release?
https://brave.com/download-beta

**Closed by bsclifton** 2018-09-28 20:39 UTC
Labels: bug, feature/keyboard-shortcuts

**Comment by aljets** [comment] 2018-09-28 20:45
@bsclifton , tried the beta release, this is fixed there for me.
