### ISSUE TITLE
Brave always uses MacBook Pro discrete GPU

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#12112] opened 2017-11-27 23:29 UTC
### Description
Brave uses power-hungry discrete GPU when it doesn't need to.

### Steps to Reproduce

  1. Launch Brave on Mac

**Actual result:**
Brave activates discrete GPU on launch before any website is opened.

**Expected result:**
Discrete GPU should only be active on graphics-intense sites.

**Reproduces how often:**
Always

### Brave Version

**about:brave info:**
Name | Version
-- | --
Brave | 0.19.95
rev | cc0ebad
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | macOS
OS Release | 17.3.0
OS Architecture | x64

**Reproducible on current live release:**
Yes, but I'm on dev channel. Using late-2016 Touch Bar-equipped MacBook Pro.

### Additional Information
Previously, Brave would leave the discrete GPU active after it was called upon (WebGL sites I believe; use Google Maps to test) but even after the website tab was closed. Now it activates the discrete GPU when I just launch the browser, before any website is shown. (My only tab on launch was Gmail, but the discrete GPU launched before it was shown.) I monitor discrete/integrated graphics use using the gfxcardstatus utility: https://gfx.io/

**Comment by luixxiul** [comment] 2017-11-28 08:23
Is the issue maybe related with that the CPU (or GPU) usage gets higher when you open a docx file on dropbox web page?

**Comment by stshank** [comment] 2017-11-29 00:29
No, this is different. This solely concerns use of discrete GPU when it shouldn't be used. Brave upon launch activates the GPU long before the first website loads.

**Comment by bsclifton** [comment] 2017-11-29 06:12
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/6443

Apologies that this has been a long-standing issue ☹️

**Closed by bsclifton** 2017-11-29 06:12 UTC
Labels: bug/driver, initiative/perf, perf, priority/P3
