### ISSUE TITLE
Uncloseable (scam) modal dialog box

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#3535] opened 2016-08-29 19:03 UTC
**Describe the issue you encountered:**

I didn't get the full URL redirect chain, but I started here:

http://seclists.org/interesting-people/2006/Dec/55

Which had a link here (a truncated link to a news.com.com domain that CNET used to use): 
http://news.com.com/IBM+to+give+birth+to+Second+Life+business+group/

Just plain old news.com.com gets the same results, too: a redirect to:
http://go.sealthatleak.com/fly?enk=JqHmkQahj6GPiY+5JrEmkY+JhrlGoSexB7lG4ybjhg==

That redirected here (but I'm not sure it always does), but I think to other URLs too:
https://downloadopensoftware.com/campaign/manyobey8/?ID=adcmscrr&sub=adcmscrr&subid=66076-news.com.com&S2=1472497446630_1472497519624_89_747272_175956937_1

It popped up an uncloseable scam dialog box. Screenshot attached.

I had to force-quit Brave with Windows Task Manager. (All of Brave, not just the tab in question.)

**Expected behavior:**

Ideally, scam doesn't appear, but failing that, dialog box closes when I click its close box, or the tab closes when I hit Ctrl-W.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  0.11.5
- Steps to reproduce:
  1. Go to http://news.com.com/IBM+to+give+birth+to+Second+Life+business+group/
     <img width="433" alt="uncloseable modal dialog box" src="https://cloud.githubusercontent.com/assets/16833251/18063626/a4aecb6e-6de0-11e6-9fc6-8cdb7539431b.PNG">

**Comment by Liunkae** [comment] 2016-11-19 07:54
Duplicate of #2755 (prevent js alert spoofing attacks). More details are available there.

**Closed by Liunkae** 2016-11-19 07:54 UTC
