### ISSUE TITLE
Twitch 2000: Network Error in specific stream replay

### ISSUE THREAD

**Issue by jaebeumlee24** [brave/browser-laptop#14686] opened 2018-07-07 11:55 UTC
Today I streamed fortnite for 3 hours. However, when I tried to watch the stream again, this message popped up.
![image](https://user-images.githubusercontent.com/40914938/42410644-e52f79a6-8227-11e8-86e5-af8c56d6cdca.png)

I tried restarting my browser, restarting Computer, Incognito mode, turning off adblock(removed it), trying other browsers but none of it worked. 

However, other streams and other stream replay by myself is not corrupted.

I am using MacOS and streamed in Windows 10 by Xsplit.

**Comment by jonathansampson** [comment] 2018-07-07 17:40
Closing as a dupe of #11819; this doesn't appear to be limited to Brave.

**Closed by jonathansampson** 2018-07-07 17:40 UTC
