### ISSUE TITLE
Cookies are not persisted across restart

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#14683] opened 2018-07-07 01:25 UTC
### Description
On a fresh profile, logging in to a site (or any other operation that creates cookies that can be read back later) does not persist after a browser restart.

#### Explicit cookie check
  1. Fresh profile (delete existing)
  2. Start browser
  3. Open http://www.html-kit.com/tools/cookietester/
  4. Click 'Set Test Cookie'
  5. Restart browser
  6. Visit http://www.html-kit.com/tools/cookietester/ again

**Actual result:**
`Number of cookies received: 0`

**Expected result:**
`Number of cookies received: 1`

**Reproduces how often:**
100%

#### Real world login check

  1. Fresh profile (delete existing)
  2. Start browser
  3. Open http://www.google.com
  4. Sign-in with valid credentials
  5. Observe correctly logged in with avatar icon on google.com
  5. Restart browser
  6. Visit http://www.google.com again

**Actual result:**
No avatar present. 'Sign In' button is there instead.

**Expected result:**
Avatar shown for user which was used to login before restart. No 'Sign In' button present.

**Reproduces how often:**
100% however see notes below re: opening another site before the restart.

### Brave Version

**about:brave info:**
 
Brave: 0.23.19 
V8: 6.7.288.46 
rev: 178c3fbc045a0cbdbe098db08307503cce952081 
Muon: 7.1.3 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Tor: 0.3.3.7 (git-035a35178c92da94) 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.87

**Reproducible on current live release:**
Yes

### Additional Information
This may be more restricted to the most recently visited site as does not seem to reproduce 100% on the 2nd or 3rd most recently visited site that sets cookies. Or it could be to do with which tab is active. @srirambv reports that he can retain login when he has a different tab active for approx. 1 minute before closing the browser.

**Comment by btlechowski** [comment] 2018-07-07 01:39
Is this dupe of #13030?

**Comment by srirambv** [comment] 2018-07-07 01:47
@btlechowski yes this is exactly what @kjozwiak mentioned in https://github.com/brave/browser-laptop/issues/13030#issuecomment-390801968

**Comment by srirambv** [comment] 2018-07-07 01:49
Closing as dupe of #13030

**Closed by srirambv** 2018-07-07 01:49 UTC
Labels: bug, feature/cookies, priority/P2, regression, regression-range-wanted
