### ISSUE TITLE
YouTube has infinitely spinning favicon

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12233] opened 2017-12-08 21:42 UTC
### Description
YT favicon spins infinitely.

### Steps to Reproduce

  1. Use 0.19.110
  2. Open YT in a new tab
  3.

**Actual result:**
Favicon is infinitely spinning. If you take shields down, this stops. If you open a video and go back to YT main page, this stops.
![yt](https://user-images.githubusercontent.com/28145373/33786262-6c638bf8-dc36-11e7-8723-6930e27c3c8f.gif)

**Expected result:**
YT favicon should load.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.19.110
rev | f4deace
Muon | 4.5.23

**Reproducible on current live release:**
no

### Additional Information
Reproduced on Windows - @srirambv 
Reproduced on Ubuntu - @kjozwiak 
Reproduced on MacOS - me

**Comment by darkdh** [comment] 2017-12-08 22:13
<img width="147" alt="screen shot 2017-12-08 at 2 12 53 pm" src="https://user-images.githubusercontent.com/11330831/33787402-ed15b650-dc21-11e7-8099-e0ecf689d91c.png">
but I saw empty favicon

**Comment by LaurenWags** [comment] 2017-12-09 02:03
In the gif in the description I see an empty favicon for a few seconds after turning shields off, but then the YT favicon loads.

**Comment by bsclifton** [comment] 2017-12-12 18:09
Also easy to reproduce by visiting http://www.benzworld.org/forums/w126-s-se-sec-sel-sd/

**Comment by bsclifton** [comment] 2017-12-13 00:58
I think this is a dupe of this issue:
https://github.com/brave/browser-laptop/issues/9001

Loading icon won't go away... but instead of trying to reload the icon, it seems to give up / use a default document icon

**Comment by bridiver** [comment] 2017-12-13 23:54
I don't think this is a dupe. This is a new issue in 63

**Closed** 2017-12-15 04:42 UTC
Labels: 0.19.x, bug, priority/P4, regression
