### ISSUE TITLE
Search gets caught in <textarea>

### ISSUE THREAD

**Issue by ballo** [brave/browser-laptop#1710] opened 2016-05-12 17:32 UTC
If I search a document which has the search term both in the regular body and in a `<textarea>`, the search will get 'caught' in the `<textarea>` and will not cycle back into the main document

**Comment by luixxiul** [comment] 2016-11-10 15:12
I cannot reproduce the issue on this page, editing `<input>` to `<textarea>`. At some point it could have been fixed. Closing.

**Closed by luixxiul** 2016-11-10 15:12 UTC
Labels: bug
