### ISSUE TITLE
Audio notification on Facebook page when clicked on GIF image

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2676] opened 2016-07-23 06:08 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Facebook tab display audio notification when a GIF image is clicked.

**Expected behavior:**
No notification should be shown on tab as its an image clicked.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version:
0.11.1

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:
![ezgif-586655061](https://cloud.githubusercontent.com/assets/17010094/17076204/5c3e0826-50a4-11e6-8de0-a4efdcbd28d2.gif)

- Any related issues:

**Comment by neeklamy** [comment] 2016-07-23 20:47
That almost certainly isn’t a GIF, despite what all of the cues on that page say. Inspect the element (right click → Inspect Element) and you’ll find it’s an MP4.

Here’s an example on Twitter, notice in the bottom left corner it’s marked as a “GIF”? Maybe it falls back to the original GIF on older web browsers that aren’t capable of playing H.264 or more recent codecs, but they do this because modern video codecs are going to be a lot better all around (size, streaming, playback control, hardware support):

![Twitters-not-really-a-GIF, gif](https://cloud.githubusercontent.com/assets/155358/17080222/01c8b1f4-511f-11e6-8949-6b8f85d7566e.jpg)

Duplicate of #257

**Comment by joshuaHutton** [comment] 2016-08-11 09:29
This issue appears on 9gag and imgur too

**Comment by bbondy** [comment] 2016-08-12 20:19
Duping to https://github.com/brave/browser-laptop/issues/257

**Closed by bbondy** 2016-08-12 20:19 UTC
