### ISSUE TITLE
Option to close an entire tabset 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7264] opened 2017-02-15 16:21 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Option to close an entire tabset 

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.13.4
rev	71d8ffc

- Steps to reproduce:
    1. Open the enough tabs to create a tab set
    2. Right click on the tab set 
    3. Only option to mute/unmute tabs, no option to close all the tabs in that tabset
    
- Actual result:
No option to close all tabs in a tab set

- Expected result:
Would be nice to have a close tabs in the tabset option in context menu

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/22983520/40b50eda-f39a-11e6-84c9-4ec1277dee8b.png)

- Any related issues:
cc: @bradleyrichter

**Comment by NejcZdovc** [comment] 2017-02-15 16:26
This is a duplicate of #5489 and PR is already ready #6570

**Closed by NejcZdovc** 2017-02-15 16:26 UTC
Labels: feature/context-menu, suggestion

**Comment by bradleyrichter** [comment] 2017-02-15 17:36
This will be a great start to future tab-page options such as:

- close tabs in this page
- open these tabs in a new window
- new bookmark folder with these tabs
- lock this tab page
