### ISSUE TITLE
Battery (Status API) Fingerprinting

### ISSUE THREAD

**Issue by gameb0y** [brave/browser-laptop#4721] opened 2016-10-12 18:57 UTC
![untitled](https://cloud.githubusercontent.com/assets/19530450/19323722/f986e4c8-9072-11e6-95d2-1dc5e3caa00c.jpg)

https://www.theguardian.com/technology/2016/aug/02/battery-status-indicators-tracking-online

http://www.itpro.co.uk/mobile/27033/websites-can-track-your-online-activity-via-your-battery-status

https://www.bestvpn.com/audio-battery-fingerprinting/

PLEASE BLOCK.

**Comment by Liunkae** [comment] 2016-10-12 22:27
Duplicate of #1885

**Closed by Liunkae** 2016-10-12 22:27 UTC
