### ISSUE TITLE
Preview on hover over tab is done at 100% not at the percentage chosen for that tab

### ISSUE THREAD

**Issue by tetrode** [brave/browser-laptop#1881] opened 2016-05-23 10:10 UTC
Issue: Preview on hover over tab is done at 100% not at the percentage chosen for that tab

Steps to reproduce:
- start brave :-)
- open a webpage from a site
- increase the font size using Ctrl +
- create a new tab
- open a webpage from another site
- Hover over the first tab

Expected behaviour
- First tab is shown in increased font size

Actual behaviour
First tab is shown in 100% font size
- Platform Win 7
- Brave Version:
  Brave: 0.10.0
  Electron: 0.37.8
  libchromiumcontent: 50.0.2661.102
  V8: 5.0.71.48
  Node.js: 5.10.0
  Update channel: dev

**Comment by bbondy** [comment] 2016-05-23 13:04
Also if you zoom from a 150% page, it shows previews at 150%.

**Comment by Liunkae** [comment] 2016-10-03 05:54
I cannot reproduce with 0.12.1 on macOS. Fixed?

**Comment by Liunkae** [comment] 2016-11-20 07:32
I'm still not able to reproduce. Closing due to a lack of recent reports.

**Closed by Liunkae** 2016-11-20 07:32 UTC
