### ISSUE TITLE
Open In Google Docs Doesn't Render, File Appears

### ISSUE THREAD

**Issue by chris-remus** [brave/browser-laptop#10173] opened 2017-07-27 13:37 UTC
- Did you search for similar issues before submitting this one?

Sorry, no.

- Describe the issue you encountered:

Upload MS Office doc to Google Docs, try to open MS Office doc in Google Doc application, doc never renders in Google Doc application, however does appear in Google Drive as Google Doc and you're able to open it fine.

- Platform (Win7, 8, 10? macOS? Linux distro?):

MacOS

- Brave Version (revision SHA):

Brave | 0.17.19
-- | --
rev | 4e46480
Muon | 4.1.9
libchromiumcontent | 59.0.3071.115
V8 | 5.9.211.38
Node.js | 7.9.0
Update Channel | dev
os.platform | darwin
os.release | 16.6.0
os.arch | x64

- Steps to reproduce:
    1. See "Describe the Issue" section
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

Yes

- Can this issue be consistently reproduced?

Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment] 2018-07-02 07:53
Unable to reproduce on our latest build. It's likely this was fixed with https://github.com/brave/browser-laptop/pull/13820

**Closed by bsclifton** 2018-07-02 07:53 UTC
Labels: webcompat
