### ISSUE TITLE
Focus is always set to first tab, Page view not shown for single tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10532] opened 2017-08-16 09:33 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Focus is always set to first tab

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.18.23
-- | --
rev | 36ae2ec
Muon | 4.3.10

- Steps to reproduce:
    1. Clean install 0.18.23
    2. Close existing tabs and open a new tab and visit a new domain
    3. Close the browser and reopen
    4. Webview is not shown only blank page is shown, hover over tab, shows page view
    5. Open a second tab, visit a different domain
    6. Keep focus on the second tab and close/quit the browser
    7. Relaunch the browser, focus is set to the first tab
    
- Actual result:
Watch attached video

- Expected result:
Focus should remain on the last active tab and for a single tab page view should be shown when launched

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Not on 0.18.14, Found the issue from 0.18.20 onward

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
https://vid.me/XXmXP

- Any related issues:
cc: @bbondy @bridiver @bsclifton

**Comment by srirambv** [comment] 2017-08-16 09:51
With a single tab in window, after relaunch if navigated to other domain, page view is still not shown until mouse over the tab

**Comment by bsclifton** [comment] 2017-08-16 19:43
I believe this is a duplicate of https://github.com/brave/browser-laptop/issues/10038 which should be fixed with https://github.com/brave/browser-laptop/pull/10095

Moving to 0.19.x and assigning to @bbondy

**Closed** 2017-08-31 03:08 UTC
Labels: bug, OS/Windows, QA/steps-specified
