### ISSUE TITLE
Pinned tab revert to default pinned site after relaunch of browser

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2632] opened 2016-07-21 12:25 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
On a pinned tab if you navigate to a different site and then close the browser and launch again the pinned tab goes back to site which was originally pinned. This should not happen when Start browser with is set to my windows/tabs from last time. 

**Expected behavior:**
After navigating to a new site and closing and relaunching the browser the pinned tab should be on the new site not revert to the original site which was pinned.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version:

- Steps to reproduce:
    1. Open a site and pin the tab
    2. Navigate to an external site from the pinned tab
    3. Close the browser and restart it
    4.  The pinned tab should start with previous site before closing
    5. Tab reverts to the original site for which the tab was pinned.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment] 2016-07-21 14:58
This is by design and I think i works the way it should. An explicit pin is an action of wanting to keep a specific site forever.  Other browsers losing your pinned site by accident is common and makes pinned sites not very useful.  I think we should close as wontfix but CC'ing @bradleyrichter

**Comment by bradleyrichter** [comment] 2016-07-21 15:14
Agree. @srirambv Please keep us posted if you find other issues with pinned tabs during daily use.

**Closed by bradleyrichter** 2016-07-21 15:14 UTC
