### ISSUE TITLE
Keyboard shortcut key CTRL+Z is not functioning on Brave

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14238] opened 2018-05-24 14:56 UTC
### Description
Keyboard shortcut   key CTRL+Z is not functioning on Brave

### Steps to Reproduce

1. Launch Brave
2. Open a new tab and enter google.com in URL bare
3. Enter some random text next to google.com in URL bar (e.g:   Google.com   fdfdsfgdjshgfjdsg)
4. Press CTRL+Z to undo random text which was entered on URL bar

**Actual result:**
Random text is not   removed from CTRL+Z shortcut key

**Expected result:**
Random text should   be removed

**Reproduces how often:**
100%

### Brave Version
0.23.7
**Reproducible on current live release:**
Yes

### Additional Information
@LaurenWags and @btlechowski :  please validate the issue on mac and Linux OS.

**Comment by bsclifton** [comment] 2018-06-05 04:48
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/11908

**Closed by bsclifton** 2018-06-05 04:48 UTC
Labels: bug, feature/keyboard-shortcuts
