### ISSUE TITLE
Ledger is broken (worker)

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8884] opened 2017-05-16 10:51 UTC
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
You can't create a wallet
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOs
- Brave Version (revision SHA):
99e8a2
- Steps to reproduce:
    1. go to payments
    2. create a wallet
    
- Actual result:
```
! >>> worker error: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at fn (extensions::node-anonize2-relic-emscripten/./anonize2-jumbo.js:55:28)
    at define (extensions::muon/module_system/commonjs:69:10)
    at Object.commonjs [as require] (extensions::muon/module_system/commonjs:54:3)
    at extensions::node-anonize2-relic-emscripten/./anonize2-jumbo.js:57912:43
    at requireProxy (extensions::muon/module_system/commonjs:64:22)
    at fn (extensions::node-anonize2-relic-emscripten:3:16)
    at define (extensions::muon/module_system/commonjs:69:10)
    at Object.commonjs [as require] (extensions::muon/module_system/commonjs:54:3)
    at extensions::node-anonize2-relic-emscripten:325:43
    at requireProxy (extensions::muon/module_system/commonjs:64:22)
! >>> worker error: Cannot read property 'binding' of undefined
TypeError: Cannot read property 'binding' of undefined
    at requireProxy (extensions::muon/module_system/commonjs:65:20)
    at fn (extensions::node-anonize2-relic-emscripten:3:16)
    at define (extensions::muon/module_system/commonjs:69:10)
    at Object.commonjs [as require] (extensions::muon/module_system/commonjs:54:3)
    at extensions::node-anonize2-relic-emscripten:325:43
    at requireProxy (extensions::muon/module_system/commonjs:64:22)
    at fn (extensions::ledger-client/worker.js:4:15)
    at define (extensions::muon/module_system/commonjs:69:10)
    at Object.commonjs [as require] (extensions::muon/module_system/commonjs:54:3)
    at extensions::ledger-client/worker.js:46:43
! >>> worker error: Cannot read property 'binding' of undefined
TypeError: Cannot read property 'binding' of undefined
    at requireProxy (extensions::muon/module_system/commonjs:65:20)
    at fn (extensions::ledger-client/worker.js:4:15)
    at define (extensions::muon/module_system/commonjs:69:10)
    at Object.commonjs [as require] (extensions::muon/module_system/commonjs:54:3)
    at extensions::ledger-client/worker.js:46:43
```
- Expected result:
Wallet is created
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
no
- Can this issue be consistently reproduced?
yes

**Comment by bridiver** [comment] 2017-05-16 13:59
didn't @bbondy fix this in muon?

**Comment by cezaraugusto** [comment] 2017-05-16 14:06
fyi I reverted commit that broke it and reopened #7344. Since ledger is working again I'm closing this one for now

**Comment by NejcZdovc** [comment] 2017-05-16 14:08
Let's keep this open so that we can track this problem

**Comment by cezaraugusto** [comment] 2017-05-16 14:12
which problem? ledger is working again and the fix that broke it was fot #7344. Please educate me if I'm wrong

**Comment by NejcZdovc** [comment] 2017-05-16 14:20
#7344 here the problem was only on windows and the problem was different than that one. What you reverted was just a switch for a worker, so this specific problem was not fixed. Problem that I experienced is happening on macOS and probably on all other platforms. That's why I will close #7344 and keep this one opened.

**Comment by cezaraugusto** [comment] 2017-05-16 15:16
> so this specific problem

Per issue description, there isn't a problem anymore. The issue is described as _You can't create a wallet_, which is now possible, and describes an error log that no longer exists. 

Could you update overall steps to reproduce to match it as a tracking issue, referencing what you gently described to me? Since we still want that feature and worker is failing only on linux/mac. This would make QA job easier.

In fact, I was going to create an issue to track the revert but since you reopened it for the same reason, a new one would be a dupe 🙂  thanks

**Comment by bridiver** [comment] 2017-06-07 19:22
I think this is fixed by @bbondy ?

**Comment by bsclifton** [comment] 2017-06-10 06:57
Fixed with https://github.com/brave/browser-laptop/pull/9221/

**Closed by bsclifton** 2017-06-10 06:57 UTC
Labels: feature/ledger
