### ISSUE TITLE
Pressing Enter doesn't load the typed in URL or search term

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8741] opened 2017-05-06 17:56 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Pressing Enter doesn't load the typed in URL or search term

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.3
rev	1c04c53

- Steps to reproduce:
    1. Upgrade to 0.15.3 from 0.15.2 
    2. Open a new tab and type in a search item or url and press enter, doesn't load
    3. Open a second tab and type in URL/Search term and press enter, doesnt load
    4. Close and reopen browser, hover over the tabs from step 2 & 3, page loads
    
- Actual result:
Page doesn't load when typed in URL and pressing enter

- Expected result:
Should load the site

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
No was able to repro on Upgrade from 0.15.2

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Not all the time but I did find this issue on several instance

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
cc: @luixxiul @alexwykoff  can you try on Debian and macOS and confirm if it happens on upgarde

**Comment by NejcZdovc** [comment] 2017-05-06 18:20
I just tried it on macOS and it's working for me

**Comment by srirambv** [comment] 2017-05-06 18:44
I think its an issue after preference change restart. I can replicate the issue on a new profile as well

**Comment by Jacalz** [comment] 2017-05-06 19:28
I had the same issue on Mac yesterday on the master branch 😅

**Comment by NejcZdovc** [comment] 2017-05-07 06:29
@srirambv do you have more specific STR (which preference)? One described above doesn't work for me.

**Comment by luixxiul** [comment] 2017-05-07 06:40
I'm not sure STR but for me it is experienced on 0.15.3 on Debian.

**Comment by NejcZdovc** [comment] 2017-05-07 06:42
I notice this bug when I was working on navigator, but I thought that it was my code, that was problematic. After some changes it was working correctly for me. I will try it now on Windows VM.

**Comment by srirambv** [comment] 2017-05-07 09:40
> do you have more specific STR (which preference)? One described above doesn't work for me.

Any preference change which requires restart. I also have this issue when I open a private tab and then any subsequent normal tabs doesn't register the Enter. This I think is a blocker for 0.15.3 as the browser becomes unuseable. I had to set homepage for each tab and use it. Will try to get exact STR in the mean time.

**Comment by bsclifton** [comment] 2017-05-08 06:09
I can repro fairly easily.  I agree about it being a blocker.  It seems to happen on any site which has not been visited before

STR:
1. Open a new tab
2. Type URL of a site that you have never been to before into the URL bar
3. Hit enter
4. Observe nothing happens

**Comment by NejcZdovc** [comment] 2017-05-08 06:38
@bsclifton can you take this one, I still can't reproduce it on mac.

**Comment by NejcZdovc** [comment] 2017-05-08 09:08
Ok I manage to reproduce it (only with luck). Problem is that tab is undefined in this line https://github.com/brave/browser-laptop/blob/master/app/browser/tabs.js#L419

**Comment by NejcZdovc** [comment] 2017-05-08 09:14
It's strange, because tabId is in the state

![image](https://cloud.githubusercontent.com/assets/9574457/25797901/6a971bbe-33df-11e7-8850-476178d7f791.png)

![image](https://cloud.githubusercontent.com/assets/9574457/25797907/727c8242-33df-11e7-8131-d59a17dbecc1.png)

We send in 61, but function `getWebContents` will return undefined

**Comment by NejcZdovc** [comment] 2017-05-08 09:21
ok maybe I found where the problem is

![image](https://cloud.githubusercontent.com/assets/9574457/25798099/26ada96c-33e0-11e7-8a0e-85fb74b5012d.png)


as you can see we have 3 items in tabs and we have two active tabs. When we click enter we get active tab and in this case we would get 29, even though this tab is not opened

![image](https://cloud.githubusercontent.com/assets/9574457/25798108/2e4e7bf6-33e0-11e7-981a-8c87913d0133.png)

This is what we have in `webContents`, as you can see we are requesting 29 from `webContents` even though that we should be requesting 69

![image](https://cloud.githubusercontent.com/assets/9574457/25798137/4397ead8-33e0-11e7-8e12-76e3fc0867a6.png)

**Comment by NejcZdovc** [comment] 2017-05-08 09:21
note I have preview tab turned **OFF**

**Comment by srirambv** [comment] 2017-05-08 09:35
@NejcZdovc  Do you also see a new tab with back button enabled? I see this on each new tab after disabling tab preview

**Comment by NejcZdovc** [comment] 2017-05-08 09:39
Yeah back button is here, because browser thinks that 29 is active which had history, but 69 is completely new tab without history. This back button shouldn't be here.

**Comment by NejcZdovc** [comment] 2017-05-08 09:41
I think that when we fix this app state problem we will fix this one, #8740 and #8741.

**Comment by bsclifton** [comment] 2017-05-08 18:33
I don't know what caused the problem, but this was fixed with https://github.com/brave/browser-laptop/commit/0da7b64c311ac8f9075cf850551318b353d9a6ab.  If you check out the commit prior (https://github.com/brave/browser-laptop/commit/5fc6dff2aaf6b5c82323696da8a882bebc89093f), it doesn't work.

The important steps to reproduce:
1. Open new tab (important- existing tabs on launch seem to work)
2. Type the term or URL
3. Hit enter

**Comment by bsclifton** [comment] 2017-05-08 18:49
reopening because 0.15.3 preview 3 came AFTER this and has the issue

**Comment by bsclifton** [comment] 2017-05-08 22:20
OK issue has been discovered.  I'd like to capture it with a scenario I did

1. I launch Brave; I have 3 pinned tabs and 1 `about:newtab`. Each tab has a tabId set (9, 12, 15, 5)
2. I manually create a newtab by clicking the + in the tab row; this gets tabId 21. Searching in it (via the URL bar) works.
3. I close this tab.
4. I click new tab button, get another tab. This ALSO gets tabId 21!!! This one is broken

**Comment by bsclifton** [comment] 2017-05-10 20:22
Fixed with https://github.com/brave/browser-laptop/pull/8782

**Closed by bsclifton** 2017-05-10 20:22 UTC
Labels: bug, release-notes/exclude, release/blocking
