### ISSUE TITLE
Brave is not fit screen

### ISSUE THREAD

**Issue by BlackHat26** [brave/browser-laptop#8765] opened 2017-05-08 21:02 UTC
As U see, I have 2 screen, but browser is not fit when I full screen (the red part) . My resolution of 2 screen is 1920x1080.
![a2b74af2-32c5-11e7-8418-6fc7905b1d5f](https://cloud.githubusercontent.com/assets/15937173/25825189/eaa79812-33f6-11e7-909e-544520e28da0.png)

**Comment by bsclifton** [comment] 2017-05-09 21:28
This is likely a duplicate of https://github.com/brave/browser-laptop/issues/7215 which was fixed recently (but the fix is not yet released)

@luixxiul has already marked as a dupe; I'll close it out.  Stay tuned for a fix 😄

**Closed by bsclifton** 2017-05-09 21:28 UTC
Labels: duplicate, misc/fullscreen-option
