### ISSUE TITLE
Missing keyboard shortcuts

### ISSUE THREAD

**Issue by fabricedesre** [brave/browser-laptop#7174] opened 2017-02-10 23:10 UTC
- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered: Alt-1...Alt-9 keyboard shortcuts to directly access tabs are missing. These shortcuts are crucial muscle memory in my workflow. Alt-1...Alt-8 should switch to Tab #N, and Alt-9 switch to the last tab.

- Platform (Win7, 8, 10? macOS? Linux distro?): Tested on Linux only

- Brave Version (revision SHA): 25b1199 (0.13.2)

**Comment by Liunkae** [comment] 2017-02-11 02:28
Thanks for the report! This is a duplicate of #1092 (Alt+Tab_Number To Select Tabs). I'll close this issue, but you can keep track at #1092 from now on.

**Closed by Liunkae** 2017-02-11 02:28 UTC
