### ISSUE TITLE
Dragging a link to the tab bar should open the link in a new tab or open in the tab you dragged it

### ISSUE THREAD

**Issue by TJFJefroy** [brave/browser-laptop#2452] opened 2016-07-12 09:30 UTC
**Expected behavior:**
In most browsers when you drag a link to the tab bar it will open the link in a new tab or the tab you dragged it to.
**Brave behavior:**
Dragging a link only work when you drag it to the url bar and than an error occurred.

**Comment by Liunkae** [comment] 2016-11-19 19:20
Duplicate of #1644

**Closed by Liunkae** 2016-11-19 19:20 UTC
Labels: suggestion
