### ISSUE TITLE
Password manager set to LastPass, still get "would you like brave to remember the password for ____" 

### ISSUE THREAD

**Issue by tarasglek** [brave/browser-laptop#3469] opened 2016-08-27 03:22 UTC
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:
latest
- Steps to reproduce:
1)    Go to a page with login form
2) choose password from lastpass menu
3) login and have brave ask to remember password :(

Should not get prompted if brave is set to use 3rd party pw manager :(

**Comment by bsclifton** [comment] 2016-08-27 15:34
@tarasglek this might be a duplicate of https://github.com/brave/browser-laptop/issues/3109

Can you try switching back to "Built-in" and then BACK to LastPass?  Thanks and apologies for the inconvenience :frowning:

**Comment by bsclifton** [comment] 2016-08-29 22:21
This may be fixed with https://github.com/brave/browser-laptop/pull/3540.  I'll try to reproduce and ensure the fix does work

**Comment by bsclifton** [comment] 2016-08-29 23:53
Confirmed this fixes it :smile: Since https://github.com/brave/browser-laptop/issues/3516 also captures this issue (and has more details), I'll mark this issue as a dupe and close

**Closed by bsclifton** 2016-08-29 23:53 UTC
Labels: info-needed
