### ISSUE TITLE
Bookmark title is not updated unbookmarking/rebookmarking

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3284] opened 2016-08-21 02:13 UTC
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7 64 bit

- Brave Version: 0.11.6 Beta1

- Steps to reproduce:
    1. Move away your brave folder temporarily
    2. Navigate to https://github.com/brave/browser-laptop/issues/3283
    3. Bookmark the page

- Screenshot if needed:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17834897/278ff3e8-6790-11e6-9ec2-222e412d40b0.jpg)

- Any related issues: #3283

**Comment by bbondy** [comment] 2016-08-23 04:12
> iii. Bookmark the page

For steps to reproduce pls be super specific, thanks.  In which way did you bookmark, maybe the star button?

**Comment by bbondy** [comment] 2016-08-23 04:13
This is working for me

**Comment by bbondy** [comment] 2016-08-23 04:14
What is the "actual results" and "expected results"?

**Comment by luixxiul** [comment] 2016-08-23 07:59
I can reproduce the issue by bookmarking this page with pushing <kbd><kbd>CTRL</kbd>+<kbd>D</kbd></kbd> and clicking ``Save``.

The actual result is that the bookmark is saved with the title ``Issues · brave/browser-laptop``, while the expected one is the title ``Bookmark name is wrongly saved on GitHub issue page · Issue #3284 · brave/browser-laptop``.

**Comment by luixxiul** [comment] 2016-08-23 15:07
I assume that database files were corrupted at some point, but this seems to me not an accident because I experienced the same issue on Windows 10 too. On clean install I cannot reproduce this.

**Comment by bsclifton** [comment] 2016-08-23 16:48
I believe I understand the issue and why we are not able to reproduce it

Bookmark names are saved after they are changed, even after you remove the bookmark. The only way to truly clear the item out is to clear the history.

Here are some steps you can try to reproduce
1) Bookmark any page
2) Edit the bookmark, give it a custom title of "ABC"
3) Remove the bookmark
4) Re-bookmark the page
5) Notice the name is now "ABC"

**Comment by bsclifton** [comment] 2016-08-23 16:52
Working on a fix for this now...

**Comment by BrendanEich** [comment] 2016-08-23 21:13
Dup of #3080?

**Comment by bsclifton** [comment] 2016-08-23 23:22
We want the behavior of keeping the **custom** title-

I believe after pulling hairs out I have characterized the problem (thanks @BrendanEich!)
- bookmark a page (let's say it has title "old title")
- remove bookmark. You no longer have this item bookmarked.
- [time goes by]
- bookmark the page again (same URL as before; this page has title "new title")
- title is being set to the OLD title ("old title")

The title of a web page is not changeable by a user; we should always use the latest title available. Custom titles however are fair game.

In the add/edit modal, any text changes to the title will automatically re-calculate the custom title of the bookmark (and this does work).

**Comment by bsclifton** [comment] 2016-08-24 04:07
Fixed with https://github.com/brave/browser-laptop/pull/3339, ready for review :smile:

**Comment by luixxiul** [comment] 2016-08-30 16:18
It seems that the issue started to appear on the latest beta again..
![bookmark](https://cloud.githubusercontent.com/assets/3362943/18097405/a58501f0-6f18-11e6-9f93-9698ce207063.gif)

**Comment by bbondy** [comment] 2016-08-30 16:30
won't block 0.11.6 on it.

**Comment by bsclifton** [comment] 2016-08-30 16:47
@luixxiul - please see the above notes.  If you re-bookmark, the actual `title` of the bookmark IS properly updated.  However, it **will** copy the custom title.  Your original issue above shows the old (now incorrect) title being assigned to a new bookmark of the page.

I'd like to ask @bradleyrichter what is his preferred behavior, but my understanding is that we want to preserve the custom titles that are given to bookmarks

**Comment by bradleyrichter** [comment] 2016-08-30 21:33
@bsclifton I don't think any users would be upset if we don't auto-restore their long lost custom title, but many will be annoyed that the old title seems stuck to the page.

My suggestion is to toss the title when a BM is removed, and monitor user feedback in general for bookmarking.

**Closed** 2016-09-02 00:35 UTC
Labels: bookmarks, bug, checked by qa - os x, checked by qa - windows - ia-32, checked by qa - windows - x64
