### ISSUE TITLE
Pasting a URL (same domain) over an existing URL in the location bar and pressing enter doesn't load the new URL

### ISSUE THREAD

**Issue by scunliffe** [brave/browser-laptop#1081] opened 2016-03-15 20:28 UTC
Working on web apps all day long I often copy a URL to the clipboard when I know I'm going to need it... then (re)login to a particular we app.  Once logged in (e.g. passed authentication) I then paste the URL in the location bar (or adress bar as MSFT calls it) and press [Enter] I expect the browser to navigate me to that URL.

However Brave does not load the page, keeps me where I am, and overwrites the location bar back to what the page had previously displayed.

Both URLs are on the same domain/port.

e.g.
base URL
http://localhost:8080/home.php

pasted URL
http://localhost:8080/some/other/page/that/is/painful/to/navigate/to/bazinga.php

**Comment by bbondy** [comment] 2016-03-16 13:53
Can you reproduce with a page that is on the web?  I tried with a random site but couldn't reproduce.

**Comment by scunliffe** [comment] 2016-03-16 14:29
I'll try to find one.  It may be something to do with URLs with a port number.

**Comment by luixxiul** [comment] 2016-05-15 14:05
Closing for now. If you find one please leave a comment to reopen this, thanks.

**Closed by luixxiul** 2016-05-15 14:05 UTC
