### ISSUE TITLE
Add drag and drop to open links in new tab like Chrome

### ISSUE THREAD

**Issue by manueltorrez** [brave/browser-laptop#14738] opened 2018-07-14 02:23 UTC
### Description

I'm suggesting to add drag and drop support to open links in a new tab just like Chrome. I've included a more self-explanatory gif:

![Alt Text](https://media.giphy.com/media/3M7zBtA4KplTQn4b0t/giphy.gif)

**Comment by eljuno** [comment] 2018-07-14 18:55
Dupe of #10600?

**Comment by manueltorrez** [comment] 2018-07-14 19:03
@eljuno indeed. I hadn't seen it, my bad

**Closed** 2018-07-14 23:19 UTC
