### ISSUE TITLE
No tabs, cant add tabs, most ui elements dont work.

### ISSUE THREAD

**Issue by MoonRubles** [brave/browser-laptop#13474] opened 2018-03-16 07:26 UTC
### Description
After a hard crash (UI completely unresponsive, restarted computer), there are NO tabs visible, and cannot add tabs. No address bar. Main menu is there, but Settings... doesnt open window. Lastpass window blank.

Note: can someone tell me what files to delete to remove the corruption? I was using Payments on this computer so I'd like not to lose all my funds.

Also: this occurred right about when payments should have happened, where Ive been having an issue #13156 

### Steps to Reproduce

  1. Wait for brave to lock up on its own. Happens every few days.
  2. If you are unlucky, when you start brave will be unusable as described above.
  3. Repeated restart does not change this.

**Actual result:**
![braveblank](https://user-images.githubusercontent.com/36520807/37508155-12307f9a-28af-11e8-8425-6de519d21f91.PNG)

every time i start brave, about 10 dmp files get created in the Crashpad folder:
![bravedmp](https://user-images.githubusercontent.com/36520807/37508304-bde08aba-28af-11e8-8804-2163addc0360.PNG)
the contents are not human readable

also, in the task mgr many processes are running:
![braveproc](https://user-images.githubusercontent.com/36520807/37508345-e71b9b18-28af-11e8-8ca8-349bcb27b9e5.PNG)

that is typically what I see when the browser is working. i had about 10 tabs open when crashed, half of which were pinned.

**Expected result:**
A working browser.

**Reproduces how often:**

### Brave Version

**about:brave info:**

Main menu does work, but About Brave does nothing. But it was probably auto updated within the last week. Win10

**Reproducible on current live release:**

**Comment by bsclifton** [comment] 2018-03-18 07:42
@MoonRubles if this happens again, can you please try opening the browser developer tools? You can do so by pressing Shift + F8.  Since Brave's UI is done via JavaScript/HTML, this browser dev tools will show errors in the app via the "Console" tab.  You should see errors when this happens

**Comment by MoonRubles** [comment] 2018-03-18 07:49
Thanks Brian. It is still happening -- here is a screengrab of the console:
![braveconsole180318](https://user-images.githubusercontent.com/36520807/37563805-0f9d529c-2a46-11e8-831a-b5b70cbc1d5c.PNG)
Let me know of any next steps youd like me to perform. thx

**Comment by bsclifton** [comment] 2018-03-19 18:22
@MoonRubles I believe this issue is a duplicate of https://github.com/brave/browser-laptop/issues/13330

@NejcZdovc has delivered a fix which we're hoping to ship soon.  In the meantime, you can try the great steps captured by @jonathansampson here:
https://jonathansampson.github.io/brave-tools/session-store-rescore.html

**Closed by bsclifton** 2018-03-19 18:22 UTC
Labels: needs-info

**Comment by LaurenWags** [comment] 2018-03-19 18:39
@MoonRubles - I can help out with your wallet if you still need it (you may not after trying the steps referenced by @bsclifton in https://github.com/brave/browser-laptop/issues/13474#issuecomment-374315485 ). If you do, let me know. Just in case, you may want to make a copy of your ledger-state.json file and save that off to the side before trying the steps referenced. This will preserve your wallet info 😄

**Comment by MoonRubles** [comment] 2018-03-19 18:48
Thank you @bsclifton, that was the problem and the helpful page by @jonathansampson fixed the browser. (I did try to search for duplicates first, honest, but "it's broken" is a difficult pattern match :) )
@LaurenWags, i did the session-store only before I saw your comment, but my wallet seems to be ok still, phew, but thank you.

**Comment by LaurenWags** [comment] 2018-03-19 18:51
glad to hear @moonrubles! since that's the case, here's my plug for backing up your wallet :) On the payments page click on the gear icon and then click on 'backup your wallet' and follow the process from there.

**Comment by MoonRubles** [comment] 2018-03-19 19:04
@LaurenWags I did, one month ago... *after* i started having problems, so you are right to remind people! I lucked out, but please keep reminding us normies.
