### ISSUE TITLE
KolabNow Webmail crashes Brave Browser

### ISSUE THREAD

**Issue by clockworkpc** [brave/browser-laptop#13948] opened 2018-04-26 03:51 UTC
### Description

**Reproduces how often:**

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.22.22
V8 | 6.5.254.41
rev | 6303310
Muon | 5.1.2
OS Release | 4.13.0-39-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.181

**Reproducible on current live release:**

**Comment by rotational467** [comment] 2018-04-26 19:46
I am similarly seeing a crash in my personal Roundcube 1.3.6 installation (Kolab is running Roundcube), specifically when attempting to save a change to a sieve filter.  When clicking the save button, Brave will immediately close with no error message.  This is reproducible on demand.

Normal mail composition works, I haven't had time to go through and find everything that does and does not generate the crash.

This behavior started for me with the latest update:
 
Brave: 0.22.667 
V8: 6.6.346.24 
rev: 0433b26a03c8daf9b181057cd2ffa7b530496faf 
Muon: 5.2.6 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.117

**Comment by bsclifton** [comment] 2018-04-26 20:28
@rotational467 that is likely due to the bug we're tracking with https://github.com/brave/browser-laptop/issues/13947 (which has been fixed and is currently building). We're going to issue a hotfix release to fix that problem

This problem for @clockworkpc is happening on our last release, 0.22.22

@clockworkpc do you have some example steps that we can try to reproduce the problem? I'm not familiar with KolabNow (is it free?)

**Comment by rotational467** [comment] 2018-04-26 20:51
@bsclifton thank you very much for the information!

**Comment by clockworkpc** [comment] 2018-04-27 01:39
@bsclifton Here is a video demonstration of what happens every time:

https://www.youtube.com/watch?v=R9GD69EIB9E

It's been a problem in Brave since I started using KolabNow webmail about 6 months ago.  It works fine in Chrome, Chromium, Vivaldi, Firefox.

KolabNow is a paid service.  I don't think you'd have access to the webmail without an account, but I assume they'd rather like their webmail to work in all major browsers.

**Comment by rotational467** [comment] 2018-04-27 12:58
@clockworkpc I have seen this same behavior in previous releases of Brave on Win10 x64 with my Roundcube installation, but only one on of my PCs.  Immediately after logging in, Brave would crash to the desktop.  I switched browsers for that PC, and just recently when I tried again saw that the issue had been resolved after some Brave updates.

I realize this isn't terribly helpful because I can't reproduce it anymore, and I never was able to determine what was different about that Win10 install than all the others.  However I have definitely seen this exact problem in older versions of Brave.

@bsclifton This is the underlying webmail platform in question for Kolab: https://roundcube.net/

**Comment by bsclifton** [comment] 2018-04-30 05:58
@rotational467 awesome- thanks for the heads up on the roundcube platform

I found/re-opened the original issue tracking crash with RoundCube and gave it a bump. I'm going to close this issue as a duplicate.  For updates, you can subscribe to https://github.com/brave/browser-laptop/issues/9580

Thanks! 😄

**Closed by bsclifton** 2018-04-30 05:58 UTC
