### ISSUE TITLE
Clicking an existing tab (with a slight drag) opens in new Window

### ISSUE THREAD

**Issue by anshumanvenkatesh** [brave/browser-laptop#9992] opened 2017-07-14 08:17 UTC
When clicking on an existing tab to open it, even a small motion opens it in a new window. Its way too sensitive for usage.

Platform: Windows 8.1 (Also seems to happen in Windows 7)

- Brave Version (revision SHA): 0.17.13 (	f7242c7)

- Steps to reproduce:
    1. Click another open tab with a slight drag
    
- Actual result:
Tab opens in a new window

- Expected result:
Tab opens in existing window

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

Suggested solution:
1. Reduce the default sensitivity of tab drag
2. Give the tab drag sensitivity as a setting

**Comment by Liunkae** [comment] 2017-07-14 16:21
@anshumanvenkatesh Thanks! This is a duplicate of issue #9211. The problem is expected to be fixed by Brave 0.19.x.

**Closed by Liunkae** 2017-07-14 16:21 UTC
