### ISSUE TITLE
1Password plugin not working at all (MacOS)

### ISSUE THREAD

**Issue by iandundas** [brave/browser-laptop#6224] opened 2016-12-15 04:33 UTC
**Did you search for similar issues before submitting this one?**
Yes 

**Describe the issue you encountered:**
Since installing Brave a couple weeks ago, the 1Password extension has never worked. The icon shows in the toolbar, but does nothing when tapped. Right-clicking on a text field and choosing "1password" also does nothing.

"Verify browser code signature" is disabled in 1Password, and I've restarted everything (browser, 1password, laptop)

I have never seen it working. However, if it's relevant, the Pocket extension does work.

**Expected behavior:**
Presumably opens a mini password picker like in other browsers.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS 10.12.1

- Brave Version:
0.12.15

- 1Password Version: 
1Password 6.5.2

- Steps to reproduce:
No idea! 

- Screenshot if needed:
n/a

- Any related issues:

**Comment by Liunkae** [comment] 2016-12-16 18:32
Related: #5523

**Comment by alexwykoff** [comment] 2017-02-20 06:07
While this has not been an issue for prior releases on my machine, running locally with e259d61b8b05041961bbff1ce456004f4dab3e4e has reproduced the issue for me.

No errors were noticed on any console. 

STR:
1. With a clean profile, enable 1password.
2. Attempt to log into github by right-clicking on the username field on the signin page and opening 1Password.

Observed: 
A new tab is opened to the same page. 
Also, the 1Password contextual menu has an entry below 'Search 1Password' which reads 'Browser could not be verified.'

**Comment by bsclifton** [comment] 2017-02-25 07:39
@alexwykoff you won't be be able to use it properly with a dev build because it's expecting a signature.  You should see something like this if the mini-1password does come up (it opens in the top right every time for me when I press cmd + \ when logging into github.com)
<img width="318" alt="screen shot 2017-02-25 at 12 37 33 am" src="https://cloud.githubusercontent.com/assets/4733304/23329286/cd5df66c-faf2-11e6-8fbd-8460fcfec2c7.png">

**Comment by bsclifton** [comment] 2017-02-27 21:53
I'm using 0.13.5 preview 3 on macOS Sierra 10.12.3 (16D32) with 1Password 6 Version 6.6.1 (661010)

Everything is working OK for me:
- Clicking the icon in the top right (pictured above- it's next to the Lion icon)
- Pressing cmd + \ when on a username or password field
- Right clicking a username or password field and picking "1Password"

@iandundas would you be able to try the latest version of Brave? I'm curious if you still have the issue. There was a point where 1Password did make a breaking change (it was around version 6.5.2).  I was never able to find where to disable signature verification in 1Password v6; IIRC, it was only available in version 4 (which I don't believe is supported)

**Comment by NejcZdovc** [comment] 2017-02-27 21:59
![image](https://cloud.githubusercontent.com/assets/9574457/23381839/48e01438-fd40-11e6-8117-6fa3dc660309.png)

 @bsclifton You can disable it here **Verify browser code signature**

**Comment by bsclifton** [comment] 2017-02-27 22:04
@NejcZdovc sweet! Thanks for the heads up 😄

**Comment by bsclifton** [comment] 2017-02-27 22:06
Removing from 0.13.5 for now, until we can get more info. It was not something caused by recent changes as this issue was originally reported with 0.12.15

**Comment by iandundas** [comment] 2017-02-28 09:09
Just tested with latest release version (0.13.4) and alas it's still broken.

It's dull but I recorded the whole thing if it helps https://www.dropbox.com/s/vmx5nxlxxwp5tna/export.mov?dl=0
- installed
- tried to open 1password to login to a webpage
- opened 1password, disabled browser authentication, 
- restarted Brave
- still not working

**Comment by iandundas** [comment] 2017-02-28 09:25
and lo! Suddenly, relaunching for a third time, it's asking me to authenticate with 1password

<img width="1445" alt="image copied on 2017-02-28 at 10 23 am" src="https://cloud.githubusercontent.com/assets/1131967/23399331/2911e216-fda0-11e6-83f7-cf3f4e428897.png">

and is now working: 
<img width="1248" alt="screen shot 2017-02-28 at 10 23 53" src="https://cloud.githubusercontent.com/assets/1131967/23399344/355c3314-fda0-11e6-898a-9581dd9687a4.png">

So that's good, however it took quite some effort to get to this place (didn't work whatsoever on first two launches), so there's something not quite right.

**Comment by srirambv** [comment] 2017-02-28 10:22
**Little off topic but a note for Windows users,** 1Password desktop app needs to be launched first and then enabled in the browser for it to validate it correctly. If 1Password is enabled first in browser and then if the desktop app is opened, it won't work. Changing the password manager and reselecting 1Password allows the widget to authorize the browser.

**Comment by bsclifton** [comment] 2017-02-28 18:18
@iandundas what version of 1Password do you have now? Are you still on 6.5.2?  I'm curious if it was upgraded and that helped resolve the issue.  If you hadn't used Brave in a while, the extension would need to update itself too (which happens in the background)

**Comment by iandundas** [comment] 2017-02-28 18:19
hey, this was with 6.6.1

**Comment by bsclifton** [comment] 2017-03-17 20:52
Closing issue since it was resolved and there aren't any actionable steps for us to take

**Closed by bsclifton** 2017-03-17 20:52 UTC
Labels: feature/password-manager, info-needed
