### ISSUE TITLE
Suggestion: Add option to disable notifications

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#10540] opened 2017-08-16 15:01 UTC
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Jacalz** [comment] 2017-08-16 19:55
+1 from community: https://community.brave.com/t/always-deny-notifications/5831/2

**Comment by luixxiul** [comment] 2017-09-13 09:56
is it ok to close this in favor of https://github.com/brave/browser-laptop/issues/2215?

**Comment by ryanml** [comment] 2018-02-27 22:48
I've laid out the initial work for such a feature on [this](https://github.com/ryanml/browser-laptop/commit/03e6a7038ab97101840bd9605c97b9484dbbcdd8) branch.

Where there will need to be some larger discussion: 

1. Naming, Help Text, and Placement within settings for this toggle.
2. Exactly what type of notifications should be covered in this settings' scope. With the work on this branch, **all** notifications would be disabled should they be switched off. This may be good, but for things like browser restart notifications we probably want to show those regardless. Per Issue #2215 it sounds like we may want this to only cover site-specific notifications.

cc: @Jacalz @luixxiul @bridiver @bsclifton 

See also:

**Comment by bsclifton** [comment] 2018-08-20 06:54
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/12467

**Closed by bsclifton** 2018-08-20 06:54 UTC
Labels: duplicate, feature/notificationbar, needs-info, suggestion
