### ISSUE TITLE
Brave will not open

### ISSUE THREAD

**Issue by maxeaus** [brave/browser-laptop#6105] opened 2016-12-09 00:26 UTC
**Describe the issue you encountered:** Brave attempts to open but is shut down as a pop up might be immediately shut down, so i see the border of the website opening then it disappears

**Expected behavior:** happing for two days now, i need to uninstall brave then reinstall it to open the browser now each time!

- Platform Win 7 Dell XPS 15z inspiron with IE

- Brave Version: Latest update

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment] 2016-12-10 00:06
@maxeaus Are you able to take a screenshot (push print screen and then paste here?)

**Comment by maxeaus** [comment] 2016-12-10 08:18
There is nothing to screen shot, basically i have to uninstall brave, go to IE/google brave browser, reinstall it and then use it, as soon as i shut down my computer it wont work again on start up, the only way i can describe it it appears as a pop up blocker is blocking it as it goes to open then just disappears just as the frame is about to open

**Comment by gravitycrusher7** [comment] 2016-12-10 13:38
I have similar issue too. 
Windows 7 x64
I've did clean unistall and used ccleaner too, but still got this issue.
It started happend since thursday update (GMT +7).
brave auto shutdown when I tried to open it. I checked the processes inside task manager, nothing left for brave proccess (it completely shut down whenever I tried to open brave).

**Comment by maxeaus** [comment] 2016-12-11 05:05
Thanks gravitycrusher7, I'm glad I'm not the only one having this issue, although obviously not glad it's happening to any of us. I tried a restore point yesterday and that didn't fix the issue either

**Comment by shlbtnk** [comment] 2016-12-11 05:21
Same for me, happened for the first time just today and now I can't use Brave anymore. Windows 7, x64, latest Brave version. After starting Brave you can see the window popping up for a very short time, then it closes immediately. You only see the boarders of the window. Rebooted, reinstalled, cleaned my system - no effort.

**Comment by bsclifton** [comment] 2016-12-11 06:41
@maxeaus @shlbtnk @gravitycrusher7 can you all check your logs for me?

Navigate to `%userprofile%\AppData\Local\brave` and check out the log file, `SquirrelSetup.log`. You should be able to double click it- if not, open it up in Notepad.  Scroll to the bottom and I'm hoping you all will see some errors or warnings

You can also try launching the Brave executable directly. It'll be in a child folder, like `0.12.14/Brave.exe`.  You may have better luck since the shortcut always launches update.exe

Let us know! Thanks

**Comment by maxeaus** [comment] 2016-12-11 07:05
100% that is whats happening, yes.

**Comment by maxeaus** [comment] 2016-12-11 07:10
That is beyond my level of technical understanding bsclifton

**Comment by shlbtnk** [comment] 2016-12-11 07:47
@bsclifton 

Launching the Brave executable directly didn't help - same problem.

Here's the last lines of my SquirrelSetup.log:

_2016-12-10 08:38:34> CheckForUpdateImpl: Downloading RELEASES file from https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64
2016-12-10 08:38:34> FileDownloader: Downloading url: https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64/RELEASES?id=brave&localVersion=0.12.13&arch=amd64
2016-12-10 08:38:34> FileDownloader: Downloading file: https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64/brave-0.12.14-full.nupkg
2016-12-10 08:38:50> UpdateInfo: Couldn't get release notes for:brave-0.12.14-full.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\MyPC\AppData\Local\Brave\packages\brave-0.12.14-full.nupkg'
   bei Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   bei Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2016-12-10 08:38:50> Program: Starting Squirrel Updater: --update https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64
2016-12-10 08:38:50> Program: Starting update, downloading from https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64
2016-12-10 08:38:50> Program: About to update to: C:\Users\MyPC\AppData\Local\Brave
2016-12-10 08:38:50> CheckForUpdateImpl: Using existing staging user ID: //obliterated
2016-12-10 08:38:51> CheckForUpdateImpl: Downloading RELEASES file from https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64
2016-12-10 08:38:51> FileDownloader: Downloading url: https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64/RELEASES?id=brave&localVersion=0.12.13&arch=amd64
2016-12-10 08:38:51> FileDownloader: Downloading file: https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64/brave-0.12.14-full.nupkg
2016-12-10 08:39:06> ApplyReleasesImpl: Writing files to app directory: C:\Users\MyPC\AppData\Local\Brave\app-0.12.14
2016-12-10 08:39:06> LogHost: Rigging execution stub for lib/net45/Brave_ExecutionStub.exe to C:\Users\MyPC\AppData\Local\Brave\Brave.exe
2016-12-10 08:39:11> LogHost: Rigging execution stub for lib/net45/resources/BraveDefaults_ExecutionStub.exe to C:\Users\MyPC\AppData\Local\Brave\app-0.12.14\BraveDefaults.exe
2016-12-10 08:39:15> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\MyPC\AppData\Local\Brave\app-0.12.14\Brave.exe]
2016-12-10 08:39:16> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-12-10 08:39:16> ApplyReleasesImpl: Examining Pin: livestreamer-twitch-gui.lnk
2016-12-10 08:39:16> ApplyReleasesImpl: Examining Pin: Microsoft Word 2010.lnk
2016-12-10 08:39:16> ApplyReleasesImpl: Examining Pin: Windows Media Player.lnk
2016-12-10 08:39:16> ApplyReleasesImpl: Fixing up tray icons
2016-12-10 08:39:16> ApplyReleasesImpl: cleanDeadVersions: for version 0.12.14
2016-12-10 08:39:16> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.12.13
2016-12-10 08:39:16> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.12.14
2016-12-10 09:27:59> Program: Starting Squirrel Updater: --processStartAndWait Brave.exe
2016-12-10 09:27:59> Program: Want to launch 'C:\Users\MyPC\AppData\Local\Brave\app-0.12.14\Brave.exe'
2016-12-10 09:27:59> Program: About to wait for parent PID 5348
2016-12-10 09:27:59> Program: About to launch: 'C:\Users\MyPC\AppData\Local\Brave\app-0.12.14\Brave.exe':_

**Comment by maxeaus** [comment] 2016-12-13 08:56
Still not working for me

**Comment by bsclifton** [comment] 2016-12-14 01:39
I believe we know the root cause for this now :smile:

@maxeaus, @shlbtnk, @gravitycrusher7: I have a temporary work-around you can try in the meantime

If you edit your shortcut, please change "Brave.exe" to "Update.exe".  For example:
`C:\Users\brian\AppData\Local\brave\Brave.exe --processStart "Brave.exe"`
change to
`C:\Users\brian\AppData\Local\brave\Update.exe --processStart "Brave.exe"`

I strongly believe this is another symptom which has the same root cause as this issue:
https://github.com/brave/browser-laptop/issues/6075

**Comment by bbondy** [comment] 2016-12-14 03:23
Closing but we can continue to investigate/communicate here and re-open if the issue is not fixed by #6075.

**Closed by bbondy** 2016-12-14 03:23 UTC
Labels: info-needed, OS/Windows, priority/high

**Comment by bsclifton** [comment] 2016-12-14 20:52
OK folks! If you can grab the latest update, the issue should be fixed :smile: Please let us know how it goes!

**Comment by bsclifton** [comment] 2016-12-14 20:53
cc: @maxeaus @shlbtnk @gravitycrusher7

**Comment by shlbtnk** [comment] 2016-12-15 00:15
@bsclifton 

I edited the shortcut as you said earlier and it works. However, if I rename it to _C:\Users\MyPC\AppData\Local\Brave\Brave.exe_ I get the same issue as before. I guess I'll just leave it _C:\Users\MyPC\AppData\Local\Brave\Update.exe --processStart "Brave.exe"_?!

**Comment by bsclifton** [comment] 2016-12-15 23:45
@shlbtnk if Brave is working for you, just keep using it how you are :smile:  If you're using Update.exe, it'll continue to work great.

Starting with 0.12.12, the installer also dropped a Brave.exe which did not work properly for folks. If those people reinstall Brave (uninstall, reinstall), they will be fixed :smile:

**Comment by alienabs** [comment] 2016-12-16 03:52
For what it's worth, I am having exactly the same problem.  Windows 7, 64 bit.  
I just now uninstalled and then reinstalled Brave, and it still has the same problem.  
The screen turns white as if Brave were starting, then it disappears.  
No workie.

**Comment by shlbtnk** [comment] 2016-12-16 07:44
@bsclifton 

Thanks. Keep up the great work!

**Comment by thekerbey** [comment] 2017-12-27 20:44
Cannot open brave. Its in task manager, but window does not appear.  https://i.gyazo.com/1f9ed887ade3b4f19e14754c7a58ab1b.gif

**Comment by higwisco** [comment] 2018-02-02 17:02
Brave will not open on my computer since last update. Running Windows 10 home version
I uninstalled and reinstalled and it opened automatically, but when I closed the window it will not re-open.

**Comment by luixxiul** [comment] 2018-02-05 14:28
mind checking on Task Manager if there are processes left?
