### ISSUE TITLE
Twitch streams don't play

### ISSUE THREAD

**Issue by Tomatoshadow2** [brave/browser-laptop#14475] opened 2018-06-20 19:10 UTC
Have you searched for similar issues? Yes

Description

No streams play on Twitch, with shields up or down.

## Test plan / Steps to Reproduce
 1. Go to https://www.twitch.tv/
 2. Try to watch a stream

### Brave Version
 
Brave: 0.23.11 
V8: 6.7.288.46 
rev: 6565c0689f8bfbd6f4d03e2e8c68c9381da157f6 
Muon: 7.1.0 
OS Release: 17.6.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.87

Reproducible on current live release:
No

Additional Information
Thought it was because fingerprinting protection was on. But even with that off, streams still don't play.

**Comment by iammeat** [comment] 2018-06-21 07:34
I'm encountering the same problem on macOS 10.13.5 beta.

 
Brave: 0.22.810 
V8: 6.7.288.43 
rev: 8f30eeba0c2d6cccf1920a360b4774f820adbc58 
Muon: 7.0.6 
OS Release: 17.6.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.71

**Comment by LaurenWags** [comment] 2018-06-21 12:27
Initially thought this might be similar to https://github.com/brave/browser-laptop/issues/12398 however, this has also been reported on twitter several times recently. One twitter user had this clear up on its own, with no action from them. Another user said if they open a new session tab then this works fine.

**Comment by LaurenWags** [comment] 2018-06-21 16:27
Internal report of issue: @alexwykoff 
Twitter report of issue:
https://twitter.com/pincho_gaming/status/1007521644078944256
https://twitter.com/stevemumford/status/1009700410024775680
https://twitter.com/Jii_El/status/1009818453052665856

**Comment by chuckreynolds** [comment] 2018-06-22 18:19
same. Twitch.tv has been broken again recently.
`macOS High Sierra v10.13.5 (17F77)`
```
Brave | 0.22.810
-- | --
V8 | 6.7.288.43
rev | 8f30eeb
Muon | 7.0.6
OS Release | 17.6.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.71
```
Some forum posts are referencing this issue: https://github.com/brave/browser-laptop/issues/14422

**Comment by eljuno** [comment] 2018-06-23 19:17
+1 from community https://community.brave.com/t/twtich-blackscreen/26023?u=eljuno

**Comment by kjozwiak** [comment] 2018-06-25 18:57
Marked this as `release/blocking` as we're getting more and more reports. As Twitch is a major component of Brave Payments, we need to figure out what is going on here.

**Comment by eljuno** [comment] 2018-06-25 19:58
+1 from Twitter https://twitter.com/YanYears/status/1011256251823427584

**Comment by bsclifton** [comment] 2018-06-26 16:41
I've tried current builds (Tor tabs), 0.24.x, and master - all fail when trying to load twitch content (shields up or down, doesn't matter). Looking more into this

**Comment by bsclifton** [comment] 2018-06-26 16:45
Looks like this error (seen via console) may be related:
> player.js:28 Uncaught (in promise) Error: Experiment `b8d1e7be-59f7-4ee3-a0c6-54ce94366d14` is deprecated
    at player.js:28

**Comment by bsclifton** [comment] 2018-06-26 17:41
This appears to be the experiment in question:
https://github.com/CommanderRoot/Twitch-experiments/blob/97cff1225bbfd6a1bb2b29b24d555cc684b9cf3c/experiments.json#L5685

(this repo is tracking changes made to https://www.twitch.tv/experiments.json)

However, I don't think this is related as Chrome gets this error logged to the console too

**Comment by bsclifton** [comment] 2018-06-26 18:53
Looks like the problem is that the player is trying to initialize the Chrome Cast APIs (chrome.cast) and (because that functionality isn't present), it's failing. Looking for a work-around...

**Comment by bsclifton** [comment] 2018-06-26 19:23
Found a fix! 😄 PR coming

**Comment by bsclifton** [comment] 2018-06-27 07:21
I thought I had a fix- but it seems that this problem is intermittent. The "fix" I had didn't actually work, I just got lucky.

The best guess I have is that whatever is breaking may be a Twitch "experiment". You can verify this intermittent behavior by deleting your profile, relaunching Brave, and visiting twitch again. Sometimes it works, sometimes it doesn't

I have gotten rid of the Chromecast errors... but the streams still consistently fail for me. I've been comparing the headers between Brave, Firefox, and Chrome and haven't made any good discoveries (yet). This definitely needs more investigation

**Comment by Tomatoshadow2** [comment] 2018-06-27 10:06
@bsclifton So you suggest testing with a new profile to see if the problem goes away?

**Comment by Tomatoshadow2** [comment] 2018-06-27 10:41
+1 https://community.brave.com/t/twitch-streams-videos-not-loading/26329

**Comment by bsclifton** [comment] 2018-06-27 15:44
@Tomatoshadow2 no- definitely not. Just noting something that @kjozwiak and myself noticed while troubleshooting. At this time, there isn't a work-around available and we're still looking into it ☹️

**Comment by Tomatoshadow2** [comment] 2018-06-27 16:22
@bsclifton  Ok, thanks, appreciate it, I just wanted to be sure I didn't miss any STR steps for you and the rest of the team.

**Comment by eljuno** [comment] 2018-06-27 19:53
+1 from community https://community.brave.com/t/twitch-streams-not-working/26385?u=eljuno

**Comment by kjozwiak** [comment] 2018-06-28 17:58
+1 from reddit https://old.reddit.com/r/brave_browser/comments/8ugewk/twitch_tv_not_working_for_anyone_else/

**Comment by sirjorj** [comment] 2018-06-29 02:38
+1 from me
I noticed this issue a few days ago.  Currently running 0.23.19 on Linux Mint.  Glad to see it is a known issue and being worked on.
Thanks!

**Comment by chuckreynolds** [comment] 2018-06-29 08:46
👍 https://github.com/bsclifton/browser-laptop/commit/a2dbd898a2ff4151c37e1d78013f7e8f0a686c17

**Comment by bsclifton** [comment] 2018-06-29 16:35
@chuckreynolds unfortunately, that doesn't seem to fix the issue (I updated the commit to note that it doesn't fix it - https://github.com/bsclifton/browser-laptop/commit/9a9212ceeacf4a31d241f64b672be2b18d3aa67b)

I believe the cause is that (even with shields down), Brave is being detected as an adblocker. When that is true, it's failing to download a resource that the player binds itself to.  The logic detecting if the browser has adblock enabled is trying to run `fetch` against a bunch of tracking pixels / advertising content

Trying this out with Brave Core (not available publicly yet), it also fails when adblocking is on. However, with shields down it does work great.

The problem is complicated by this logic intermittently working (which is what happened when I thought I had fixed it). Apologies this is taking so long to solve- it's definitely a complex problem ☹️

**Comment by BrendanEich** [comment] 2018-06-29 17:33
(For everyone's info brave-core is available at https://github.com/brave-core -- we just do not yet publish self-updating builds but those are coming next month.)

So it sounds like Twitch is (intentionally or accidentally) fingerprinting Brave based on Muon but not Brave based on the chromium front-end (brave-core). Wow. Should be possible to find out what is different in the DOM that could be involved. Idea: survey all property names to right of dot in the code that fails on Muon and see if different set of property names from what works on brave-core. If same, have to hunt through set to find what might be present in Muon-based DOM but not in brave-core. If diff then the delta could be the culprit.

**Comment by slambert92** [comment] 2018-06-30 07:01
+1 same issue, unable to resolve

also the bravecore link posted above by BrendanEich takes me to an error page

**Comment by bsclifton** [comment] 2018-07-01 05:40
@slambert92 try this one:
https://github.com/brave/brave-browser

There are instructions there for building from source. We should have builds available sometime next month

We're still looking into this issue

**Comment by KHarker** [comment] 2018-07-01 09:16
+1 on this. Read through a whole load of previous threads for a fix before I found this one - none worked. Glad to hear it's being worked on as it's the only major issue I've found since switching to Brave.

Keep up the great work!

**Comment by btlechowski** [comment] 2018-07-01 11:37
It seems that we silently fail to create an indexeddb (cvp-wasm-db).
It is part of the process of downloading and instantiating the wasm(http://cvp.twitch.tv/2.5.16/wasmworker.min.wasm).

The creation of the indexeddb is at line 227 of wasmworker.min.js [wasmworker.min.js.zip](https://github.com/brave/browser-laptop/files/2152760/wasmworker.min.js.zip):
```
var f = indexedDB.open(a, 1);
f.onerror = d;
f.onsuccess = function () {
    c(new g(f.result, b))
};
f.onupgradeneeded = function () {
    f.result.createObjectStore(b)
}
```
The debugger hangs after indexedDB.open as I cannot make the next step. It looks like script execution hangs on that call.
onerror, onsuccess, onupgradeneeded are never fired in Brave, but are fired in Chrome.
onsuccess is required to fire in order to download and instantiate the wasm at line 255:
```
return v.resolve().then(function () {
    return WebAssembly.instantiateStreaming(fetch(b),
        a)
})
```



Generally indexeddb works, so maybe execution path is what matters.
1. http://cvp.twitch.tv/2.5.16/mediaplayer.min.js creates a blob in a web worker 
```
p.createWorker = function (e, t, i) {
    var n = `\n        var Module = {\n            WASM_BINARY_URL: '${t}',\n            WASM_CACHE_MODE: ${i}\n        }\n        importScripts('${e}');\n    `;
    return new Worker(URL.createObjectURL(new Blob([n])))
},
```
2. In the blob wasmworker.min.js is loaded through importScripts
```
var Module = {
    WASM_BINARY_URL: 'https://cvp.twitch.tv/2.5.16/wasmworker.min.wasm',
    WASM_CACHE_MODE: true
}
importScripts('https://cvp.twitch.tv/2.5.16/wasmworker.min.js');
```

**Comment by NejcZdovc** [comment] 2018-07-02 04:46
@btlechowski could be related to this one https://github.com/brave/browser-laptop/issues/12463?

**Comment by btlechowski** [comment] 2018-07-02 16:21
@bsclifton @NejcZdovc  My next step was to check if indexeddb fails in a webworker.
So indeed indexeddb fails in web worker and seems to be the root cause of this issue.

**Comment by bsclifton** [comment] 2018-07-05 22:30
Got a fix for this (for real this time)! Hang tight folks

**Closed** 2018-07-06 15:42 UTC
Labels: QA/test-plan-specified, needs-investigation, priority/P2, release-notes/include, release/blocking, webcompat

**Comment by srirambv** [comment] 2018-07-06 18:47
Verified on Windows 10 x64 using
* 0.23.31 - 3148ace
* Muon - `7.1.5`
* libchromiumcontent	`67.0.3396.103`

**Comment by bsclifton** [comment] 2018-07-06 19:42
Verified on macOS using
* 0.23.31 - 3148ace
* Muon - `7.1.5`
* libchromiumcontent	`67.0.3396.103`

**Comment by chuckreynolds** [comment] 2018-07-06 20:16
ETA on production rollout?

**Comment by bsclifton** [comment] 2018-07-06 20:28
@chuckreynolds possibly today - you can upgrade now if you wanted:
https://github.com/brave/browser-laptop/releases/tag/v0.23.31dev

If you're on Windows or macOS, you can also launch Brave with the `BRAVE_ENABLE_PREVIEW_UPDATES=TRUE` environment variable set and check for updates 😄
