### ISSUE TITLE
All tooltips when brave opened are black

### ISSUE THREAD

**Issue by SudoLinux** [brave/browser-laptop#12148] opened 2017-11-30 20:43 UTC
I am using Ubuntu mate and in the browser (latest version), and by tooltips I mean [ file, about, edit, etc ] at top bar, they are black, and I have a black background for my theme which looks ugly, when I minimize and maximize it removes tooltips which I guess fixes it. Please fix this! Thanks :)

**Comment by luixxiul** [comment] 2017-12-01 02:22
Is this a same issue as https://github.com/brave/browser-laptop/issues/11109 ?

**Comment by SudoLinux** [comment] 2017-12-04 01:55
@luixxiul Yes it is, any chances you are to fix and merge it? Thanks a lot!

**Comment by luixxiul** [comment] 2017-12-04 05:31
Closing as duplicate of #11109. Let's track the issue there 😄

**Closed by luixxiul** 2017-12-04 05:31 UTC
Labels: bug, OS/unix-like/linux
