### ISSUE TITLE
Google 2-factor push immediately times out

### ISSUE THREAD

**Issue by mrfosi** [brave/browser-laptop#13747] opened 2018-04-05 13:33 UTC
Yes.

### Description

Gmail offers 2-factor authentication and one of the options is push notifications. When using this form of authentication, I get the notification on my phone immediately but Gmail simultaneously reports that the push has timed out and requires me to use another method to authenticate. This is not a problem in Firefox or Chrome, just Brave.

### Steps to Reproduce

  1. Turn on two-factor auth for your Gmail.
  2. Choose push notification as your method.
  3. Open Gmail in Brave and attempt to authenticate.
  4. Observe the push arrive on your phone and the simultaneous browser notification that the push has timed out.

**Actual result:**

Push request is immediately timed out and I must choose an alternate authentication method.

![clipboard01](https://user-images.githubusercontent.com/38105185/38368648-da3d8186-38b3-11e8-9d6d-f76539d2ed75.png)

![clipboard02](https://user-images.githubusercontent.com/38105185/38368653-dba275f4-38b3-11e8-9c2a-9f805e60c13e.png)

**Expected result:**

Sufficient time to hit "yes" on the push request, followed by immediate login to Gmail.

**Reproduces how often:**

Every time.

### Brave Version

**about:brave info:**

 
Brave: 0.22.13 
V8: 6.5.254.41 
rev: a8cfb160479f1d00d0769368eb440030182bb83b 
Muon: 5.1.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**

Not sure how to answer this.

### Additional Information

Not that I'm aware.

**Comment by eljuno** [comment] 2018-06-28 20:35
Duplicate of #7866?

**Comment by bsclifton** [comment] 2018-06-28 23:15
@eljuno yup- closing as a duplicate

**Closed by bsclifton** 2018-06-28 23:15 UTC
Labels: duplicate

**Comment by jrmoreau** [comment] 2018-06-30 14:43
Any update on this? Had to restore my laptop and now can't use Brave as my primary browser anymore  because of this.

**Comment by stevenchu** [comment] 2018-11-10 04:47
Just happened to me too - Kept saying yes on my phone, BRAVE google auth kept saying timed out, retry?

**Comment by bsclifton** [comment] 2019-01-03 16:12
locking since there are other threads capturing this

With the new version of Brave, you can subscribe to https://github.com/brave/brave-browser/issues/1356 for updates
