### ISSUE TITLE
tab menu at top right doesn't do anything

### ISSUE THREAD

**Issue by mwessels** [brave/browser-laptop#369] opened 2016-01-27 22:34 UTC
the three line button at the top right, right underneath the Brave logo will not do anything.  Running off of mac

**Comment by diracdeltas** [comment] 2016-01-28 19:41
duplicate of #310

**Closed by diracdeltas** 2016-01-28 19:41 UTC

**Comment by bbondy** [comment] 2016-01-28 20:23
Fixed in  0.7.10 (which is available now)
