### ISSUE TITLE
U2F Not Working for AWS MFA

### ISSUE THREAD

**Issue by freimer** [brave/browser-laptop#15239] opened 2018-09-27 21:28 UTC
### Description
U2F does not work with AWS as a MFA.  It does work with AWS using Chrome.

### Steps to Reproduce

  1. Login to AWS account
  2. Navigate to IAM console
  3. Select a user and remove any existing MFA
4. Select Manage MFA, and U2F security key

**Actual result:**
![image](https://user-images.githubusercontent.com/6484459/46175495-278ab300-c27a-11e8-9206-032ad1396c34.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/6484459/46175582-789aa700-c27a-11e8-86e7-1407b89465f6.png)

**Reproduces how often:**
100% reproducable

### Brave Version

**about:brave info:**
 
Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Reproducible on current live release:**
Not sure

### Additional Information
U2F used is Yubikey 4C

**Comment by bsclifton** [comment] 2018-09-28 07:02
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/13564

@freimer can you please try our new Beta release? This has support for extensions and U2F support should work great. You can grab a copy here:
https://brave.com/download-beta

**Closed by bsclifton** 2018-09-28 07:02 UTC
