### ISSUE TITLE
Don't playing music on vk.com

### ISSUE THREAD

**Issue by vlntnbr** [brave/browser-laptop#12000] opened 2017-11-16 11:34 UTC
### Description

Don't playing audio on vk.com

### Steps to Reproduce

  1. open "audio" on vk.com (for example my playlist https://vk.com/audios43550408)
  2. click "play"
  3. see error window

**Actual result:**

![audio vk com](https://user-images.githubusercontent.com/33719816/32889084-43d5bac8-caeb-11e7-92ba-77bae62c4971.jpg)

**Expected result:**

**Reproduces how often:**

alltime

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.19.95
rev | cc0ebad
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**

### Additional Information

in about:preferences#plugins adobe flash is "on"

**Comment by srirambv** [comment] 2017-11-16 12:12
Dupe of #11988

**Closed by srirambv** 2017-11-16 12:12 UTC
