### ISSUE TITLE
Right hand menu icon not working

### ISSUE THREAD

**Issue by Cromian** [brave/browser-laptop#357] opened 2016-01-27 13:27 UTC
Mac OS 10.11.3 - the right hand (3 bar) menu does nothing when you click on it.

**Comment by bbondy** [comment] 2016-01-27 13:51
Yep this is a dupe of #310 which was already implemented just not released.
I'll leave this open until it's released though to avoid dupes.

**Comment by Cromian** [comment] 2016-01-27 14:51
Ah sorry bout that.

**Comment by bbondy** [comment] 2016-01-28 20:23
Fixed in 0.7.10 (which is available now)

**Closed** 2016-01-28 20:51 UTC
