### ISSUE TITLE
Add more privacy respecting search engines

### ISSUE THREAD

**Issue by privacytoolsIO** [brave/browser-laptop#6295] opened 2016-12-19 00:57 UTC
Hi guys,

first of all thanks for working on Brave, it's a great Browser. I've noticed that some privacy respecting search engines are missing in the search settings. Do you consider adding more? 

https://www.privacytools.io/#search

My Suggestions:
- www.searx.me (open source, self-hosted, meta search)
- www.metager.de (open source, meta search, based in germany)

Please let me know what you think.
Bye

**Comment by bsclifton** [comment] 2017-03-13 22:50
Hi there @privacytoolsIO,

We absolutely will add more search engines (see https://github.com/brave/browser-laptop/issues/790 which this is a duplicate of).  We also would like to allow users to add their own search engines (which is captured with https://github.com/brave/browser-laptop/issues/3053)

Some good news is: searx.me was just added with https://github.com/brave/browser-laptop/issues/7658 😄 

I'm going to close this particular issue as a duplicate, but please follow one of the above issues to track progress.  Thanks! 😄

**Closed by bsclifton** 2017-03-13 22:50 UTC
Labels: feature/search, privacy, suggestion
