### ISSUE TITLE
Browser UI goes off screen when autocomplete comes up

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8574] opened 2017-04-29 14:02 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Page runs in browser window when a tab has webview crash

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7 ia32
- Brave Version (revision SHA):
Brave	0.15.1
rev	0598ddf
- Steps to reproduce:
    1. Visit https://github.com/brave/browser-laptop in a new tab
    2. Open http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=4085067&tag=1 in a new tab. Wait for the page to load and crash webview
    3. Open a third tab and type `github.com/br` and see the browser window
    
- Actual result:
Browser window loads page when a tab has webview crash

- Expected result:
Should not do that 
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![browser2](https://cloud.githubusercontent.com/assets/17010094/25556029/c0d4651c-2cec-11e7-87a1-4866c491f25a.gif)

- Any related issues:
cc: @diracdeltas @bbondy

**Comment by diracdeltas** [comment] 2017-04-29 14:08
It doesn't appear to be loading outside the sandbox in the screenshot; the webview is just too high up by ~20 pixels.

**Comment by alexwykoff** [comment] 2017-04-29 21:01
@srirambv I couldn't reproduce on OS X perhaps its Windows only?

**Comment by alexwykoff** [comment] 2017-04-29 21:39
The ieee link provided looks like a pdf in your screenshot, but commonly visiting the page does not show a pdf.  Since the pdf crash has been fixed in 0.15.1 will this reproduce?

**Comment by bbondy** [comment] 2017-04-30 00:56
I think the window renderer is still inside sandbox btw.

**Comment by alexwykoff** [comment] 2017-04-30 02:13
@srirambv let's circle back on this during the week and see if there is more to do.

**Comment by bsclifton** [comment] 2017-08-08 21:55
Issue renamed after discovering that https://github.com/brave/browser-laptop/issues/9843 is a dupe.  

<img width="1039" alt="screen shot 2017-07-06 at 10 54 09 am" src="https://user-images.githubusercontent.com/28946/27925435-928f95d2-6239-11e7-9aeb-c07239346deb.png">

I had some good notes about this issue:
- It seems that typing into the URL bar causes the issue
- a suggestion is displayed and I think that is what is shifting the UI chrome down
- if you stop typing after you notice it, you can still see the tabs (like in the screenshot above). If you switch between tabs enough, you'll eventually get one that re-opens the URL bar
- if you keep typing, the UI chrome goes completely off the screen and the page you're visiting takes up the entire screen

**Comment by bsclifton** [comment] 2017-08-31 06:30
+1 from @jonathansampson via https://github.com/brave/browser-laptop/issues/10729

**Comment by NejcZdovc** [comment] 2017-09-20 11:14
+1 from #11038

**Closed** 2017-09-20 13:44 UTC
Labels: bug, muon, priority/P3, usability

**Comment by bbondy** [comment] 2017-09-20 13:46
master: e1066fd21ff5db269d059af52d2a70b4a18822ca
0.20.x: a2cf1b5925c1f7329021d5d1ecec949dcf4c78b1
0.19.x: 2636521abaad66c32d1c5ba673bcda12c49ebae0

**Comment by LaurenWags** [comment] 2017-09-27 21:22
url in step 2 doesn't crash webview for me, is there another way to check this? cc: @kjozwiak

**Comment by kjozwiak** [comment] 2017-09-27 21:54
> url in step 2 doesn't crash webview for me, is there another way to check this? cc: @kjozwiak

@jonathansampson added some STR in #10729 which was a duplicate of this bug but requires you to be on the master branch to get access to `chrome://crash` which isn't available in the preview builds. Other than checking master, I'm not 100% sure how we can get this tested in `0.19.20` as we don't have STR that are working. As @LaurenWags mentioned, the webview doesn't crash anymore when visiting the website from the STR that @srirambv added in the original comment.

@bsclifton added some notes above from a user that ran into this issue a few times. I tried following the notes and spent about an hour or so on different websites, launching suggestions from the URL but could never reproduce the original issue.

@jonathansampson, @bsclifton, @bbondy any idea's what we can do to get this tested? Because `chrome://crash` isn't accessible, I was thinking maybe we can find a page/tool that can crash the current webview, which might make this easier to test using @jonathansampson STR from #10729.

@srirambv did you find another way to test this earlier?

**Comment by srirambv** [comment] 2017-09-28 02:27
@kjozwiak  Used `chrome://crash` on a new tab to crash the browser webview.
