### ISSUE TITLE
Zoom level indicator in address bar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2646] opened 2016-07-21 19:36 UTC
Currently there no way to know if  zoom level of  a the page is if its changed from the default zoom. (Unless its really zoomed in). Providing an option to reset to default along with magnifying glass (if the default zoom is changed) in address bar will be a good option.

**Comment by alexwykoff** [comment] 2016-08-02 15:19
I think this is a duplicate of https://github.com/brave/browser-laptop/issues/1623

**Closed** 2016-08-02 15:20 UTC
Labels: duplicate
