### ISSUE TITLE
Importing bookmarks on a new install automatically adds the top site tiles

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6217] opened 2016-12-14 22:21 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Importing bookmarks on a new install automatically adds the top site tiles

**Expected behavior:**
Should add top tiles only if the user visits the bookmarked sites

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.15

- Steps to reproduce:
    1. Do a clean install of brave
    2. Once the browser opens after install import bookmarks from HTML file
    3. Bookmarks get added as top tiles automatically

- Screenshot if needed:
![toptiles](https://cloud.githubusercontent.com/assets/17010094/21203612/2b5dc638-c24b-11e6-9574-3626580c6a55.gif)

- Any related issues:
cc: @cezaraugusto 
   Please change the milestone if required

**Comment by luixxiul** [comment] 2016-12-15 02:48
I don't hate that.

**Comment by bsclifton** [comment] 2017-01-17 22:18
Closing as this was fixed with https://github.com/brave/browser-laptop/pull/6655 and merged into `0.13.1-branch`

**Comment by cezaraugusto** [comment] 2017-01-18 01:06
Steps to reproduce:

1. On a fresh session, remove some default topSites
2. Import bookmarks
3. Imported bookmarks shouldn't populate topSites grid

**Comment by aekeus** [comment] 2017-02-04 01:30
The tiles were shown on the newtab page after following the steps above.

**Comment by cezaraugusto** [comment] 2017-02-04 15:04
I couldn't reproduce on macOS running [0.13.2dev-RC3](https://github.com/brave/browser-laptop/releases/tag/v0.13.2dev-RC3). Also tested on master latest (54ac442).

![imported_bm_newtab](https://cloud.githubusercontent.com/assets/4672033/22619366/51b14046-eada-11e6-9b77-e78ee932f829.gif)

**Comment by cezaraugusto** [comment] 2017-02-04 15:07
Also test is still passing: 

```npm run test -- --grep="does not include imported bookmarks"```

Do we at some point changed how we check if bookmark is imported (`lastAccessedTime === 0`)? 

/cc @darkdh

**Comment by darkdh** [comment] 2017-02-04 15:36
I can't reproduce either

**Comment by bbondy** [comment] 2017-02-05 02:11
since 3 reports of it working I think this is probably a testing problem, but please try again @aekeus.  Possibly what happened was you did the update manual test before this one?
If you can still reproduce though please re-open and we'll just move it into 0.13.3.

**Closed by bbondy** 2017-02-05 02:11 UTC
Labels: feature/importer, feature/newtab, QA/checked-macOS, QA/steps-specified, release-notes/include

**Comment by srirambv** [comment] 2017-02-05 12:12
Works fine on Windows 
![6217](https://cloud.githubusercontent.com/assets/17010094/22626043/1ae951c6-eb9c-11e6-9dde-9e067c4ff021.gif)

**Comment by aekeus** [comment] 2017-02-06 14:36
Confirmed, this was a testing issue. Sorry for the confusion.
