### ISSUE TITLE
Pinned tabs occasionally duplicate when Brave is opened.

### ISSUE THREAD

**Issue by JFrankfurt** [brave/browser-laptop#12995] opened 2018-02-02 16:21 UTC
### Description
I will occasionally (70% of the time) open brave and see that any tabs I've pinned have been duplicated. Tab growth is exponential. Help.

### Steps to Reproduce
  1. pin a tab(s)
  2. close brave
  3. open it again later and see multiples of the pinned tab(s)

https://photos.app.goo.gl/hABPrbtNy5RDZcWb2

### Brave Version
0.20.30

**Comment by hugobuddel** [comment] 2018-02-02 19:13
Yup, this is happening again after upgrading to 0.20.x. Duplicate of #10179 ?

**Comment by hugobuddel** [comment] 2018-02-02 19:22
Sometimes Brave goes in some sort of crash loop when I remove one of the duplicate tabs:

```
An uncaught exception occurred in the main process Uncaught Exception:
param str (null) is not a string

Crash dump id: af789b33d93f392a
An uncaught exception occurred in the main process Uncaught Exception:
param str (null) is not a string

Crash dump id: 71b81ba79fe12c9d
[18914:18914:0202/202022.244415:ERROR:CONSOLE(0)] "Unchecked runtime.lastError while running guestViewInternal.destroyGuest: Unknown error.", source: chrome://brave/usr/lib/brave/resources/app.asar/app/extensions/brave/index.html (0)
An uncaught exception occurred in the main process Uncaught Exception:
param str (null) is not a string

Crash dump id: 9487682e6a74777b
An uncaught exception occurred in the main process Uncaught Exception:
param str (null) is not a string

Crash dump id: 3d0cfa5e90c14cf8
An uncaught exception occurred in the main process Uncaught Exception:
param str (null) is not a string

Crash dump id: 9d505e06e51b132a
An uncaught exception occurred in the main process Uncaught Exception:
param str (null) is not a string

Crash dump id: 188dd54949c25593
...
```

**Comment by hugobuddel** [comment] 2018-02-02 19:30
Luckily I cannot get the tabs to exponentiate. It is my pinboard tab that keeps reappearing in duplicate form. It doesn't matter whether I delete one of them or both, they both reappear after opening a few new windows.

I sometimes wonder whether the developers actually use Brave day to day, because every new version has its own weird problems. But you must update because otherwise the old problems aren't fixed..

**Comment by JFrankfurt** [comment] 2018-02-02 20:06
Oh I'm sure they do. I (and everyone) accidentally introduce bugs into my work when fixing things literally every day. 

Now that I've been using the current version for a few hours I'm seeing something more in line with what you described. It looks like there's a mismatch between the gui and whatever internal system is managing tab state. The gui thinks some are there, the internal system thinks they're not, but also won't let me delete the ones it knows about. 

Also getting some weird behavior when I close them. Sometimes Brave closes, sometimes not.

**Comment by bsclifton** [comment] 2018-05-01 06:54
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/12995

**Closed by bsclifton** 2018-05-01 06:54 UTC
Labels: feature/pinned-tabs
