### ISSUE TITLE
Provide right click context menu option for users to block 1st party Ads

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7521] opened 2017-03-07 22:38 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Provide right click context menu option for users to block 1st party Ads

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.13.5
rev	1db81cb

- Steps to reproduce:
    1. Visit https://rediff.com
    2. Web page shows 1st party ads which are not blocked
    3. Users should have an option to block 1st party ads
    
- Actual result:
1st party ads are not blocked on sites

- Expected result:
User should have an option to block 1st party ads on websites along with the 3rd party ads that are blocked by default

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
Highlighted 1st party ads
![image](https://cloud.githubusercontent.com/assets/17010094/23681338/948fab04-0386-11e7-9143-54dc0f0c2dc4.png)

- Any related issues:
cc: @lukemulks

**Comment by lukemulks** [comment] 2017-03-07 22:40
+1
Would also help with issues where paywall prompts block content until users whitelist the site w/their ad blocker. 

Additional adblock support for blocking inline-scripts would be helpful here too.

**Comment by Jacalz** [comment] 2017-03-10 19:16
Here is an idea of what i think it should look like: Just right clicking somewhere and pressing "block element". Then you can choose what element to block and it adds it as a filter in a "cosmetic filters" section in settings > shields > Manage Adblock Settings... :lion: Just like in Ublock Origin :+1:

**Comment by Liunkae** [comment] 2017-04-11 01:38
+1 from #8210

**Comment by pmo** [comment] 2017-04-23 18:46
I made a post that got closed and added as duplicate and pointed to this one. But this post doesnt mention anything about adding blocklists by url. [https://github.com/brave/browser-laptop/issues/8451](url)

**Comment by Jacalz** [comment] 2017-04-23 18:50
Oh sorry my bad, missed that part, will open that again 😅

**Comment by luixxiul** [comment] 2017-04-24 11:56
can this be closed in favor of #344?

**Comment by srirambv** [comment] 2017-04-24 12:27
#344 is only for cosmetic ads similar to the ones shown on Google after search. This is specifically for 1st party ads which are not blocked.

**Comment by pmo** [comment] 2017-04-24 12:42
This is what I think should be added, just to be clear.

![asdasdasd](https://cloud.githubusercontent.com/assets/571139/25337452/37eddcfe-28fc-11e7-8d8e-9393150becb5.PNG)

**Comment by Jacalz** [comment] 2017-04-27 14:38
+1 from https://community.brave.com/t/browser-still-shows-google-ad/2402

**Comment by srirambv** [comment] 2017-08-15 09:07
+1 from community https://community.brave.com/t/right-mouse-button-menu-add-block-element/5893/2

**Comment by eljuno** [comment] 2017-09-13 21:03
+1 from community https://community.brave.com/t/right-click-button-on-blocking-images-and-ads-idea/7547?u=eljuno

> right click button on the mouse to block images and ads

**Comment by pongraczi** [comment] 2017-09-19 21:31
+100000000 thanks :)
maybe including some "trivial big players" individually, like this:  


**Disable 1st party ads:**  
- [ ] Disable globally (everything)  

**Exceptions (enabled, even global disable active):**  

- [ ] Google Search
- [ ] Google Youtube
- [ ] Google Mail
- [ ] Facebook  

**Add your exception domains here:**
```
[_____________________] [  add ]
[ myfavouriteads.com ]  [remove]
[ whateveris.org     ]  [remove]
[ *.specnews.com     ]  [remove]
```

**Comment by BraveSauce** [comment] 2017-09-22 10:42
The title should change to "manually block content" and not "1st party ads".

On Chrome I use _Ublock Origin_ to block all sort of annoying things that aren't "ads", tailoring the UI of my favorite websites to suit my needs.


Examples of content I block: 

- Resilient cookie reminders that will pop up each and every time, or other kinds of modern popups.

- Annoying "Buy Premium/Upgrade" UI elements on freemium services that I don't wish to pay for.

**Comment by Jacalz** [comment] 2017-09-24 17:29
+1 on changing the title to something like "add option to right click to remove content"
I am totally agreeing with the user cases that @BraveSauce mentioned above :+1:

**Comment by candrews0** [comment] 2017-12-11 21:05
+1 this issue. It's a dealbreaker to my using Brave.

**Comment by dri94** [comment] 2017-12-12 11:52
+1 on this issue

**Comment by steph643** [comment] 2017-12-13 08:42
Very disappointed to see Google search ads not being blocked.

**Comment by PupoSDC** [comment] 2017-12-24 15:31
Is this feature being worked on? Without this Brave is not really worth it...

**Comment by AstralGeek33** [comment] 2018-02-01 11:30
Any updates? I would love to switch to Brave but can't due to the lack of this feature. (As it's nice to be able to do manual blocking.)

It would also be helpful if blocked elements were saved to the cloud so you don't have to re-block the elements upon a new installation.

**Comment by srirambv** [comment] 2018-02-02 10:28
+1 from https://community.brave.com/t/hover-block-ads/15282/2

**Comment by srirambv** [comment] 2018-06-06 16:48
+1 from @chris1000  via #14340

**Comment by StephenOwen07** [comment] 2018-06-08 06:14
+1

**Comment by corysolovewicz** [comment] 2018-07-03 20:59
+1 
I would definitely utilize this functionality as I frequently run into this type of thing (see attached)
<img width="1123" alt="screen shot 2018-07-03 at 1 58 27 pm" src="https://user-images.githubusercontent.com/19578733/42244280-43fbacd2-7ec9-11e8-8f27-871f874a23ce.png">

**Comment by bsclifton** [comment] 2018-07-10 18:29
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/344

@Snuupy is working on this for Brave Core 😄 For more info, subscribe to https://github.com/brave/brave-browser/issues/94

**Closed by bsclifton** 2018-07-10 18:29 UTC
Labels: feature/adblock, feature/context-menu, suggestion
