### ISSUE TITLE
Dashlane extension image broken on about:extension

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7093] opened 2017-02-06 13:18 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Dashlane extension image broken on about:extension

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows x64

- Brave Version (revision SHA):
Brave	0.13.2
rev	726b9d2

- Steps to reproduce:
    1. Enable Dashlane on 0.13.2 RC6
    2. Open about:extension
    3. Broken image shown for Dashlane
    
- Actual result:
Broken image shown

- Expected result:
Should show Dashlane icon

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Checked from 0.12.15 and the image is broken in all release

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/22648314/f69a0ad6-ec6d-11e6-9313-117bf9e9d453.png)

- Any related issues:

**Comment by luixxiul** [comment] 2017-02-06 13:42
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/22649235/72a0b144-ecbd-11e6-992b-42bcb5ffc183.png)

It works for me but I remember I have seen it broken with no clear reason.

**Comment by tregagnon** [comment] 2017-02-07 10:45
@luixxiul You are using an older version of the Dashlane extension, we can see in your screenshot it's the version 4.2.X. @srirambv is using the version 4.4.0, which is the latest.

I can reproduce the issue. We changed something at Dashlane about the icons packaged in the extension. It now only has the 128px version in the manifest.json. We did this after looking at some extensions created by Google and how Chrome reacts to only this icon size (it works great).

Does Brave expect a specific icon size? 
Can Brave be changed to behave like Chrome (by picking the 128px icon)?

**Comment by luixxiul** [comment] 2017-02-07 12:44
@tregagnon the issue will be fixed with #7116.

I'm just wondering if you guys have already noticed that Dashlane is not working on Windows. Please have a look at this: https://github.com/brave/browser-laptop/issues/4138

Thanks!

**Comment by srirambv** [comment] 2017-02-07 13:42
@luixxiul @tregagnon  Added update here https://github.com/brave/browser-laptop/issues/4138#issuecomment-278002507

**Comment by luixxiul** [comment] 2017-02-07 13:51
Thanks!

**Closed** 2017-02-07 20:21 UTC
Labels: feature/extensions, feature/password-manager
