### ISSUE TITLE
WebView Not Visible in Popup Window

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#9095] opened 2017-05-28 04:11 UTC
**Workround: Open a new tab then switch back to existing tab**

**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When triggering a popup window, I find that the `<webview/>` is not visible (nor does it load).

**Cause:**
The issue here is a missing `.isActive` class on the `div.frameWrapper` element. Having no `isActive` or `isPreview` class causes the webview to be `visibility: hidden`.

**Platform (Win7, 8, 10? macOS? Linux distro?):**
Windows 10

**Brave Version (revision SHA):**
https://github.com/brave/browser-laptop/commit/6b5e4e2d300959848e0e848817aa40385447f2eb

**Steps to reproduce:**
1. Navigate to https://www.dropbox.com/login
2. Click 'Sign in with Google'
    
**Actual result:**
Tab contents in popup are solid white.

**Expected result:**
Tab contents in popup contain login form.

**Will the steps above reproduce in a fresh profile? If not what other info can be added?**
TBD

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Comment by luixxiul** [comment] 2017-05-28 06:45
By disabling FP I got the log in pop up.

**Comment by jonathansampson** [comment] 2017-05-28 13:54
@luixxiul I don't have FP enabled.

**Comment by bbondy** [comment] 2017-05-28 17:29
maybe intermittent and not related to FP?
Are you both using Windows?

**Comment by jonathansampson** [comment] 2017-05-28 17:38
@bbondy Not intermittent for me; repros consistently, across multiple domains (including all OAUTH login forms that I've tested). I've only tested on Windows.

**Comment by bbondy** [comment] 2017-05-28 17:49
I can reproduce as well on both Linux and WIndows. I assume mac is the same but I don't have access to a Mac for a week.

**Comment by bridiver** [comment] 2017-05-29 00:01
I can't repro on mac in master

**Comment by bridiver** [comment] 2017-05-29 00:02
@jonathansampson/@bbondy can you reproduce on master?

**Comment by bridiver** [comment] 2017-05-29 00:10
looks like it must be windows/linux only

**Comment by bbondy** [comment] 2017-05-29 03:13
reproduces on master

**Comment by bridiver** [comment] 2017-05-30 03:55
this isn't 100% reproducible even on windows. It happens intermittently and I think it's the same race condition we are seeing in other places with the app state. I have a workaround for now

**Comment by NejcZdovc** [comment] 2017-05-30 17:38
I can reproduce this 100% on macOS

**Comment by bsclifton** [comment] 2017-05-30 17:42
@NejcZdovc same

**Comment by NejcZdovc** [comment] 2017-05-30 17:44
Just test it out and b5e55d3 fix this problem for me

**Comment by bridiver** [comment] 2017-05-30 17:45
if you can reproduce 100% of the time you need a laptop upgrade ;) I couldn't even repro 100% of the time on my windows VM

**Comment by NejcZdovc** [comment] 2017-05-30 17:47
:smile: I can only reproduce it on my bank site

**Comment by jonathansampson** [comment] 2017-05-30 21:56
@bridiver I can/could reproduce 100% of the time on my Surface Book i7 :)

**Comment by bsclifton** [comment] 2017-05-30 23:05
Marking as closed since the work-around has been committed 😄

**Closed by bsclifton** 2017-05-30 23:05 UTC
Labels: bug, impact/high, priority/high, regression, release-notes/include, release/blocking
