### ISSUE TITLE
Need to be able to organize/reorder bookmarks

### ISSUE THREAD

**Issue by jenn-rhim** [brave/browser-laptop#10918] opened 2017-09-12 23:08 UTC
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
I can't organize the bookmarks, specifically reordering the bookmarks or bookmark folders
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.6
- Brave Version (revision SHA):
0.18.29
- Steps to reproduce:
    1. Select 'Bookmarks...' from the Bookmarks menu
    2. Attempt to reorder the bookmarks or folders by drag & drop (as no GUI is apparently available)
    3.
    
- Actual result:
Bookmarks cannot be reordered by d&d
Folders can be d&d to a folder to create a new hierarchy (dragged folder gets listed last in the parent folder), but no pier reordering

- Expected result:
Being able to move the bookmark or bookmark folder anywhere with drag & drop across the pier level as well as along the hierarchy.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment] 2017-09-12 23:57
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/2171

@jenn-rhim I did notice this issue was a little bit different... in that you mention being able to drag and drop inside the bookmarks menu itself.  I don't think this is possible- Chrome and Firefox don't support it. But we definitely need a way to sort the bookmarks (either in the bookmarks toolbar or in bookmarks manager)

**Closed by bsclifton** 2017-09-12 23:57 UTC
