### ISSUE TITLE
window.alert issues

### ISSUE THREAD

**Issue by pixelass** [brave/browser-laptop#5711] opened 2016-11-17 10:01 UTC
**Did you search for similar issues before submitting this one?**

yes

**Describe the issue you encountered:**
When a script calls `window.alert()`, it is somehow prevented. 
Might be related to beforeunload

**Expected behavior:**
Some pages have alerts or prompts that open before you leave the page.
After clicking "Yes" you should be redirected to the page you requested.
If you click "No", you stay on that page.

**Platform (Win7, 8, 10? macOS? Linux distro?):**
OS X

**Brave Version:**
0.12.9

**Steps to reproduce:**

1. Open https://codepen.io/pen
2. write some code
3. Navigate away from the page
4. You cannot navigate away from the page

**Screenshot if needed:**
Here's a screencast: (usual alert works)
Navigating away from the page does not work at all.

![bravebug](https://cloud.githubusercontent.com/assets/1148334/20384675/fcc2ccc0-acb4-11e6-832a-9b713a179819.gif)

**Any related issues:**
#4079

**Comment by pixelass** [comment] 2016-11-17 10:13
After reading more about #4079 I'm pretty sure it's the same issue.
Feel free to close at any time if no new useful information is provided.

**Comment by Sh1d0w** [comment] 2016-11-17 12:30
Duplicate of https://github.com/brave/browser-laptop/issues/4079

**Closed by Sh1d0w** 2016-11-17 12:30 UTC
