### ISSUE TITLE
Unable to open private tab using keyboard shortcut from a PDF tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4024] opened 2016-09-15 14:55 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Unable to open private tab using keyboard shortcut from a PDF tab. When Ctrl+Shift+P is pressed it opens print dialogue instead of launching a private tab

**Expected behavior:**
Should open a new private tab
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.1 RC1
- Steps to reproduce:
  1. Open any pdf in a tab
  2. Press Ctrl+Shift+P to open a new private tab 
  3. Launches print dialogue instead of opening a new private tab
- Screenshot if needed:
- Any related issues:

**Comment by z-money** [comment] 2017-02-16 16:10
Also seeing this on mac osX El Capitan, for brave v 0.13.4

**Comment by srirambv** [comment] 2017-09-26 03:57
+1 from #11112

**Comment by sergiorojasa** [comment] 2018-01-24 17:07
I would like to work on this issue.

**Comment by sergiorojasa** [comment] 2018-01-24 17:15
I would like to work on this issue

**Comment by bsclifton** [comment] 2018-01-24 21:42
@sergiorojasa awesome! Go for it 😄 I've assigned the issue to myself so that nobody will grab it. Let us know if you need any help

**Comment by sergiorojasa** [comment] 2018-01-26 17:16
I found the newPrivateTab keyboard shortcut in app/common/commonMenu.js
And I reproduced the issue on my computer, but I not sure if the issue is in brave/pdf.js repository or brave/browser-laptop repository because when the browser loads a pdf the pdf.js extension logic is load and keyboard event listener.

**Comment by sergiorojasa** [comment] 2018-01-29 22:44
I found out when a user press ctrl+shift+p the pdf chrome extension is called.

**Comment by sergiorojasa** [comment] 2018-01-30 16:50
@bsclifton on line 273 - 278 is where the code executes the print command [Click to view the pdf.js repository pdf_print_service.js](https://github.com/brave/pdf.js/blob/master/web/pdf_print_service.js)

**Comment by sergiorojasa** [comment] 2018-01-30 19:45
@bsclifton I was not sure how to do the pull request in this repository or brave/pdf.js repository so I did a pull request on brave/pdf.js repository.

**Comment by diracdeltas** [comment] 2018-02-22 20:38
this will be fixed whenever https://github.com/brave/pdf.js/pull/4 is merged into master and @bsclifton does a pdf.js release :).

**Closed** 2018-04-04 17:39 UTC
Labels: bug, feature/keyboard-shortcuts, feature/private-tabs

**Comment by NejcZdovc** [comment] 2018-04-10 06:28
@bsclifton should we add to any milestone this one?

**Comment by bsclifton** [comment] 2018-05-04 19:08
@NejcZdovc good catch- yes... we are fixing this with 0.22.x release 3. Will set accordingly
