### ISSUE TITLE
Browser jumping back to previous tab

### ISSUE THREAD

**Issue by khalidhalim** [brave/browser-laptop#2094] opened 2016-06-06 02:11 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**

I have four pinned tabs
1. Google Apps Mail
2. Google Apps Calendar
3. Google Apps Drive

I have two regular open tabs
1. Github
2. Techmeme

When I switch between tabs, on the second click on the page (never the first) it jumps back to the previous tab (**edit:** this also happens if you just wait 3 or 4 seconds without clicking anything). For example I just clicked back to my google calendar tab (pinned tab) and moved the weeks forward by clicking the arrow, on the second click it jumped back to this page (full tab).

**Expected behavior:**
When I switch to a tab that it will stay on that tab and not jump back.
- Platform (Win7, 8, 10? OS X? Linux distro?):

OS X El Capitan 10.11.5
- Brave Version:

Brave: 0.10.2
- Steps to reproduce:
  1. Open several tabs of content
  2. Pin some tabs and leave some full (not sure if this matters but it is what I do)
  3. Click over to first tab and complete some actions
  4. Click over to a second tab and click at least two times (maybe more) on second tab, this should make the browser jump back to the previous tab. (**edit:** this also happens if you just wait 3 or 4 seconds without clicking anything)
- Screenshot if needed:

Video link of behavior here: http://cl.ly/3v31433U1Z2F
(clicked from this page to my pocket account... clicked two links and on second click it jumps back here)
- Any related issues:
  Makes browser unusable because always jumping around

**Comment by khalidhalim** [comment] 2016-06-10 03:30
Hi @cezaraugusto,

I just restarted and I am still getting the same behavior. I am happy to uninstall and reinstall the browser and see what happens. But will wait to see if you want to investigate this further before I do.

**Comment by cezaraugusto** [comment] 2016-06-10 03:40
Sure @khalidhalim, thanks for the feedback. 

I'm unable to test it now, going to set this as a bug until I (or someone from the team) can test it.

**Comment by Liunkae** [comment] 2017-03-31 05:05
Closing as a duplicate of #5730. Please follow any future updates there.

**Closed by Liunkae** 2017-03-31 05:05 UTC
Labels: bug, info-needed
