### ISSUE TITLE
Closing a different tab results in the current selected tab changing

### ISSUE THREAD

**Issue by JaneSmith** [brave/browser-laptop#10627] opened 2017-08-22 16:16 UTC
- Describe the issue you encountered:
When closing a different (i.e. not selected) tab, the currently selected tab changes to the next one along (i.e. the tab to the right). This is an issue because I would never expect my currently selected tab to be forcibly changed, unless I'm actually closing the tab that I'm on.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 Pro.

- Brave Version (revision SHA):
36ae2ec

- Steps to reproduce:
    1. Open a new Brave window.
    2. Press Ctrl+T twice to open two new tabs, for a total of three tabs.
    3. Click on the second/middle tab, so that you switch to that one. There is now an unselected tab on the left and on the right.
    4. Close the first tab (i.e. the left tab), either by clicking its X button or by right-clicking it and choosing to close it.
    
- Actual result:
The first tab closes, AND the currently selected tab changes from the second tab to the third tab.

- Expected result:
The first tab closes, and the second tab stays selected.

- Can this issue be consistently reproduced?
Yes.

**Comment by Liunkae** [comment] 2017-08-23 15:43
Duplicate of #10038. Looks like the problem was just fixed (brave/muon#280) and should be included in the next stable release.

**Closed** 2017-08-31 14:27 UTC
Labels: duplicate
