### ISSUE TITLE
Can't navigate to about pages using a private session

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#7719] opened 2017-03-15 00:20 UTC
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Can't navigate to about pages using a private session

- Platform (Win7, 8, 10? macOS? Linux distro?):
any

- Brave Version (revision SHA):
3ef5da3

- Steps to reproduce:
    1. Open a private tab
    2. Type about:blank
    
- Actual result:
First try do nothing, second try loads forever, no page is loaded

- Expected result:
Should load the page

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

**Comment by srirambv** [comment] 2017-03-15 09:10
Dupe of #1817

**Comment by srirambv** [comment] 2017-03-15 09:11
Closing #7719

**Closed by srirambv** 2017-03-15 09:11 UTC
Labels: feature/about-pages, privacy
