### ISSUE TITLE
Unpin should only be applied to the same window

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8675] opened 2017-05-04 03:24 UTC
**Describe the issue you encountered:** Unpin tab should only be applied to the same window, not applied globally

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Clear the profile
    1. Start the browser
    2. Click the twitter tile
    2. Pin the tab
    3. Open a new tab
    4. Detach the new tab
    5. On the new window, unpin the twitter pinned tab
    
- Actual result: the 1st window is closed and the unpinned tab is attaced to the 2nd window

- Expected result: only the pinned tab on the 2nd window should be unpinned. the pinned tab on the 1st tab should be remained pinned.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by bsclifton** [comment] 2017-05-09 07:23
Duplicate of https://github.com/brave/browser-laptop/issues/5800

**Closed by bsclifton** 2017-05-09 07:23 UTC
Labels: bug, feature/pinned-tabs
