### ISSUE TITLE
lock/unlock icon disappears when downloading from a site

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12248] opened 2017-12-11 17:25 UTC
### Description
When downloading (ex. from github.com/brave/browser-laptop/releases) the lock/unlock icon disappears from the URL bar.

### Steps to Reproduce

  1. Navigate to github.com/brave/browser-laptop/releases
  2. Click on a release to download (if you're quick, you can see the lock icon missing before the save dialog comes up)
  3. Once release starts downloading, look at the URL bar.

**Actual result:**
Lock icon disappears
![lockiconmissing](https://user-images.githubusercontent.com/28145373/33844418-44814910-de6e-11e7-9979-6a5d2b2bdbef.gif)

**Expected result:**
Lock icon should remain

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**

Brave | 0.19.113
rev | 043c506
Muon | 4.5.25

**Reproducible on current live release:**
Yes, reproduced on 0.19.105

**Comment by bsclifton** [comment] 2017-12-11 17:28
Related to https://github.com/brave/browser-laptop/issues/12177?
cc: @darkdh

**Comment by MargarytaChepiga** [comment] 2018-03-04 03:32
I really want to work on this issue. As I can see it was fixed before for Muon version 4.5.24 (or it actually wasn't?) :
https://github.com/brave/muon/commit/cdeecd9
I will dive into it, and see what I can do. I would really appreciate any suggestions though :)

**Comment by MargarytaChepiga** [comment] 2018-03-05 21:38
So I noticed that this doesn't happen when the connection is insecure:
![issue 12248-before-insecure-works](https://user-images.githubusercontent.com/15698572/37000393-485e30ba-2091-11e8-90d4-6ee4d05bf1f7.gif)
This gives me several ideas:
-  It is handled for the insecure connection, but is not handled for secure
-  It is handled for both, but the secure just doesn't work

I am trying to debug to find where exactly this process is happening. So far I think it has something to do with window state and/or download item files. Not sure if I am going the right direction.

**Comment by NejcZdovc** [comment] 2018-03-07 21:11
@MargarytaChepiga let me check this issue quickly and will let you know asap

**Comment by MargarytaChepiga** [comment] 2018-03-18 17:19
Hello! I found two ways to fix this issue. Both of them work, but I am not sure if that's a correct way of fixing this issue. 
First, in this file:
https://github.com/brave/browser-laptop/blob/fbb45d2e5260485b0f607730667c9561d1698744/js/stores/windowStore.js#L312
If I will comment out lines from 314 till 316:
![fix 1](https://user-images.githubusercontent.com/15698572/37560603-03a92e22-2a12-11e8-9c7f-86b8acf02cfa.PNG)
The result will be:
![fix 1-1](https://user-images.githubusercontent.com/15698572/37560686-5b48607a-2a13-11e8-9f5b-8c0a8fcafb73.gif)

I checked if it works on:
- Secure website with secure download
- Insecure website with an insecure download link
- Secure website with an insecure download link
- Twitter
- PDF downloads from both secure and insecure websites

But I noticed that those three lines were added on purpose in order to reset security state.
Here is the commit with the change made by @diracdeltas : https://github.com/brave/browser-laptop/commit/7990e04f52bcc514485eac230b1a05c6baa40c16#diff-733d30fbf34816322d3f25dd59c1eb99R317

The thing is when we click on download those lines of code executes and resets the security state, so isSecure becomes null etc. According to the tests though this is the expected behavior. When I comment out those three lines everything works perfectly. I also check the test plan for [this](https://github.com/brave/browser-laptop/issues/8403) since those lines were a part of the fix. Everything seems to work perfect and nothing have broken so far. However, I am not fully sure why do we need those lines but I have a strong feeling that we need them. @diracdeltas, I would really appreciate your help here. 

Since I am assuming those three lines are important and I shouldn't remove them, I found another solution. As I already mention windowState resets isSecure to null. And the reason why icon disappears is that we don't handle the situation when isSecure is null. 
So another solution could be in this file;
https://github.com/brave/browser-laptop/blob/fbb45d2e5260485b0f607730667c9561d1698744/app/renderer/components/navigation/urlBarIcon.js#L37
Here:
![4](https://user-images.githubusercontent.com/15698572/37561218-78e7d5c8-2a1f-11e8-82dc-6604c77eed10.PNG)
If we add the check for null:
![5](https://user-images.githubusercontent.com/15698572/37561237-1a5f508e-2a20-11e8-9f8e-52c950242c03.PNG)

However, this solution is not perfect too. Since the state get's reset, the certificate becomes undefined and disappears.
![fix 2-1](https://user-images.githubusercontent.com/15698572/37568644-74c4453c-2aae-11e8-8a34-5185f4bca44e.gif)

Another thing that I have noticed is that icon and certificate are not disappearing when we want to download pdf, so I think that this is handled for the pdf. However, I am still trying to figure out where and how. Any help and suggestions are highly appreciated!

**Comment by diracdeltas** [comment] 2018-03-19 16:52
@MargarytaChepiga thanks for the detailed report! I think the right solution is probably "don't reset the security state if the `windowConstants.WINDOW_WEBVIEW_LOAD_START` event corresponds to a download event". that is, add an `if` condition in https://github.com/brave/browser-laptop/blob/fbb45d2e5260485b0f607730667c9561d1698744/js/stores/windowStore.js#L309 that checks whether we are starting a download. i don't know offhand how to do this check, but i bet that it is possible.

you can start by `console.log`ging what the `action` is for a download; if there isn't enough information in there, you can try adding more properties to it.

**Comment by MargarytaChepiga** [comment] 2018-03-20 03:49
Thank you so much @diracdeltas! That was very helpful!!!

**Comment by srirambv** [comment] 2018-06-21 15:59
This happens when a torrent download is cancelled in a tor private tab. 
![tor-torrent](https://user-images.githubusercontent.com/17010094/41730768-9935f406-754a-11e8-8e63-0d9f6623dc84.gif)

**Comment by bsclifton** [comment] 2018-08-06 22:16
Closing per https://github.com/brave/browser-laptop/pull/13541#issuecomment-410869782

**Closed by bsclifton** 2018-08-06 22:16 UTC
Labels: bug, feature/URLbar, feature/download, fixed-with-brave-core, sec-low, wontfix
