### ISSUE TITLE
When right clicking the anchor tag, some times its not showing up "open in new tab" menu

### ISSUE THREAD

**Issue by Gnaneshwar511** [brave/browser-laptop#490] opened 2016-01-31 06:23 UTC
Steps to reproduce :
================
(i) Open link 'http://www.sportskeeda.com/slideshow/5-batsmen-bad-runners-between-wicket?imgid=78350'

(ii) On the right you find list of suggestd pages under 'Related Articles'

(iii) Right click on any of those. You get options that are only listed as ''Reload, View Page source"

When I open in chrome, its giving the proper options on right click.

**Comment by bbondy** [comment] 2016-01-31 06:50
To fix this we need to get a list of the parent tags sent up as nodeInfo from `app/content/webviewPreload.js and not only the closest tag.

**Comment by psimyn** [comment] 2016-02-03 09:08
duplicate of https://github.com/brave/browser-laptop/issues/248 - will be fixed by https://github.com/brave/browser-laptop/pull/566

**Comment by diracdeltas** [comment] 2016-02-12 23:10
closing by @psimyn's request

**Closed by diracdeltas** 2016-02-12 23:10 UTC
