### ISSUE TITLE
Window border not always shown on all sides (when using high DPI)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6698] opened 2017-01-17 11:19 UTC
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
Window border not shown on all sides

**Expected behavior:**
Should show the blue window border on all sides when browser is in focus

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	105a1a7
Same on preview 8 as well

- Steps to reproduce:
    1. Do a clean install of 0.13.0 Preview 8/Preview 9
    2. Ensure the browser window is active 
    3. Not all sides of the browser window has blue border
    4. Restart the browser, chances are three out of four sides have blue border 

- QA Steps
    1. Do a clean install of 0.13.0 build 
    2. Ensure browser window is active
    3. Ensure all sides of the browser window has blue border
    4. Close and restart ensure all sides still has blue border

- Screenshot if needed:
Preview 8 
![image](https://cloud.githubusercontent.com/assets/17010094/22018202/9644c52c-dca5-11e6-96d6-0fa04eb580a8.png)
![image](https://cloud.githubusercontent.com/assets/17010094/22018212/9bf1b692-dca5-11e6-824f-14958adb56ca.png)

 Preview 9
 ![image](https://cloud.githubusercontent.com/assets/17010094/22018234/bcd09194-dca5-11e6-9349-8ba8d2c54c6d.png)

- Any related issues:
cc: @bsclifton

**Comment by srirambv** [comment] 2017-01-17 11:34
Resizing the window causes the blue border to be not shown. Captured here
![blueborder](https://cloud.githubusercontent.com/assets/17010094/22018848/c984619c-dca8-11e6-83f1-0245f79c9cc4.gif)

**Comment by bsclifton** [comment] 2017-01-17 23:22
Able to repro and it may be related to https://github.com/brave/browser-laptop/issues/6462

Here's what my best guess is (which may be wrong, but hear me out).  

Frameless windows should NOT have any non-client area... but for some (in Muon) reason they do. When an approach is taken to disregard non-client area, we saw with https://github.com/brave/browser-laptop/issues/4216 that at 200% DPI, the top right / top left borders become rounded.

When the DPI is NOT 100% (or another round number, like 200%), you have an odd number of pixels. What I believe is happening is that the width/height of the window... when calculated... is not adding up to the actual width/height of the Window

I have a pretty good idea of where to look. Stay tuned...

**Comment by bsclifton** [comment] 2017-01-19 18:09
This is a fairly complex problem and will take some time to solve.  Although high DPI Windows users may have some ugliness, Brave is still very usable; I don't believe this should be a blocker for 0.13.0.  I'm going to move this to 0.13.1 :smile:

**Comment by bsclifton** [comment] 2017-01-20 07:07
## My findings so far
- Problem only happens at 125%, 150%, 175%
- HWND in `native_window_views.cc` (in electron) maps to the parent window
- there are child windows… one of which is the webview (which internally is a chromium webcontents object)
- the webview window handle (HWND) has different dimensions than the parent window handle (HWND; parent being the one created in native_window_views)

I ran a quick demo with logging and observed that:
- the parent HWND is 1467x900 (I’m at 125% DPI)
- the webcontents HWND is 1468x900 (bigger than the parent)
- the “internal” unscaled size to Windows is 1174x720 which is correct (ex: you can multiply by 1.25 and you’ll get “roughly" 1467x900)

When I’m inside the layout object, I can output the size of the view itself (I believe this is the webcontents) and the parent (the “host”).  These sizes are:
HOST: 1174,720
view: 1172,718

**Comment by bsclifton** [comment] 2017-01-23 07:19
Some data I collected when reproducing
- My DPI is set at 125%
- The unscaled bounds are 809x598
- Parent window is 1011x747
- Child window (`RenderWidgetHostViewAura`) is 1012x748

If you manually work out the conversion to 125%, it would be 1011.25 x 747.5.  It seems that any non-integer value is rounding up for the size of the HWND?

In this situation:
- Right border is present
- Bottom border is missing

**Comment by bsclifton** [comment] 2017-01-31 21:03
This one is solvable, but low priority
- only one pixel is lost on right or bottom
- problem does not exist in fullscreen or when maximized

I'm going to push it back; please feel free to re-assign milestone if you disagree

**Comment by bsclifton** [comment] 2018-08-07 00:34
Closing as `wontfix` since this is already fixed in [brave-core](https://github.com/brave/brave-browser)

**Closed by bsclifton** 2018-08-07 00:34 UTC
Labels: OS/Windows, bug, bug/dpi/monitor, fixed-with-brave-core, priority/P5, wontfix
