### ISSUE TITLE
Clicking links with Brave closed results in many new windows

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#2959] opened 2016-08-04 20:06 UTC
**Did you search for similar issues before submitting this one?**
Yep!

**Describe the issue you encountered:**
Today I noticed Brave was consuming an awful lot of memory. After troubleshooting with @bbondy we figured out I had a lot of full screen Brave windows open at the same time. It was being caused by Brave opening a new window and your old window if you click on a link with Brave closed.

**Expected behavior:**

I think it would be nice if:
1. Full screen windows were staggered a bit so you could see if you had multiple open
2. Clicking a link with Brave closed would add it as a new tab to your old window instead
- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS but I assume all desktop platforms.
- Brave Version:

Brave: 0.11.2
Electron: 1.3.0
libchromiumcontent: 52.0.2743.82
V8: 5.2.361.43
Node.js: 6.3.0
Update Channel: dev
- Steps to reproduce:
  1. Set Brave as your default browser
  2. Open one or multiple tabs
  3. Quit Brave
  4. Click on a link from another app
  5. Notice that it opens the link in a new, fullscreen window, with your old window full screen behind it.
- Screenshot if needed:
- Any related issues:

**Comment by bsclifton** [comment] 2018-10-01 02:50
Closing as dupe of https://github.com/brave/browser-laptop/issues/4197

**Closed by bsclifton** 2018-10-01 02:50 UTC
