### ISSUE TITLE
Weird things happen if you go to get.adobe.com/flashplayer/

### ISSUE THREAD

**Issue by dotnetCarpenter** [brave/browser-laptop#484] opened 2016-01-31 01:25 UTC
With Brave 0.7.11: cab14e9a487640b4f19c5dc4354f11b9bed1c58a
1. Goto https://get.adobe.com/flashplayer/
2. Watch eternal reload

**Comment by inian** [comment] 2016-01-31 14:15
This is due to a JS snippet in their index page..
An infinite redirection happens because the code assumes all Chrome like browsers will have Flash installed. 
The server is doing UA-Sniffing to find out if the browser is Chrome or not and loops through the plugins installed if it finds out it is Chrome. Since every time the page loads, the `found` variable will be false and trigger a JS re-direct again

```
// .. if browser is chrome..run this
                for (var i = 0; i < navigator.plugins.length; i++) {
                    f = navigator.plugins[i].filename;
                    if (f == "gcswf32.dll" || f == "Flash Player Plugin for Chrome.plugin" || f == "libgcflashplayer.so" || f == "pepflashplayer.dll" || f == "PepperFlashPlayer.plugin") {
                        found = true;
                    }
                }
...
 if (!found)	window.location.href = "/flashplayer/?no_redirect";
```

**Comment by luixxiul** [comment] 2016-05-15 00:31
I cannot reproduce this. This should be fixed for now, closing. If not please update to the latest version and try again.

**Closed by luixxiul** 2016-05-15 00:31 UTC

**Comment by dotnetCarpenter** [comment] 2016-05-16 14:11
Yep, just tested with 0.9.6 and I got to https://get.adobe.com/flashplayer/?no_redirect

**Comment by luixxiul** [comment] 2016-05-16 14:12
Me too :-)
