### ISSUE TITLE
Blank Page on Ubuntu

### ISSUE THREAD

**Issue by rahilwazir** [brave/browser-laptop#1471] opened 2016-04-25 15:43 UTC
I'm continuously experiencing blank page problem on Linux Ubuntu. I'm not sure how would you reproduce the problem. It just shows blank. May try the following steps:
- Open any site
- Let go the browser, minimize and wait few minutes (I'm not sure if this is needed)
- Maximize, open new tab, try visiting any site
- Blank page!! afterwards.

Now you won't be able see any new tabs page contents except the initial ones. I upgraded to the latest version but this was occurring with older versions as well.

Ubuntu: **16.04**
Brave: **0.9.2**

**Comment by luixxiul** [comment] 2016-05-14 07:52
Still persist after update to the latest version?

**Comment by rahilwazir** [comment] 2016-05-16 13:31
@luixxiul Yes even upgraded to the latest `0.9.6 dev channel`

While browsing for about 15-20 minutes issue started again.

**Comment by luixxiul** [comment] 2016-05-16 13:35
Would you please paste the log of the console here?

**Comment by rahilwazir** [comment] 2016-05-16 13:51
Tell me where could I find the log? Should I have to execute from CLI and post here?

**Comment by luixxiul** [comment] 2016-05-16 13:55
Sorry there should be a log file. Will you please tell @rahilwazir the place, @bbondy?

**Comment by rahilwazir** [comment] 2016-05-23 12:30
Issue still exists on `v0.10.0 Dev Channel`

**Comment by luixxiul** [comment] 2016-05-23 13:21
I'm trying to reproduce it but I can't yet

**Comment by luixxiul** [comment] 2016-05-23 13:54
@rahilwazir if you encounter the error, please open devtool with ``Shift+Ctrl+I`` and paste the output on Console here? Thanks.

**Comment by rahilwazir** [comment] 2016-05-24 06:36
@luixxiul Well it only opens the devtool for the current visited website. I couldn't found the option for devtool of the browser itself.

**Comment by luixxiul** [comment] 2016-05-24 07:21
> option for devtool of the browser itself.

How about ``Alt+CTRL+J``?

**Comment by rahilwazir** [comment] 2016-05-25 10:06
@luixxiul Thanks.

- While the browser devtool (`Alt+CTRL+J`) open, the blank page didn't appear.
- Without the devtool the blank appeared and instantly opened up the devtool (`Alt+CTRL+J`) and it was blank too :cry: 

![blank_page](https://cloud.githubusercontent.com/assets/1818941/15536305/39f19b68-228a-11e6-935a-32757e6485c7.png)

**Comment by luixxiul** [comment] 2016-05-25 10:40
Definitely it's not the problem of a page, but I'm not sure what the cause is, as the similar problem happens on Arch Linux and Linux Mint too (#1392)

**Comment by rahilwazir** [comment] 2016-05-25 10:55
@luixxiul Agree, @bbondy should definitely take a look.

**Comment by muchavie** [comment] 2016-05-26 20:41
I'm hitting this problem too.  (ubuntu 14.04)  Browser version 0.10.0

**Comment by luixxiul** [comment] 2016-05-26 23:29
should this be fixed in master and will be in 0.10.1, @bridiver? #1671

**Comment by bridiver** [comment] 2016-05-27 15:37
not that I am aware of. The other bug was related to dnd

**Comment by rahilwazir** [comment] 2016-06-06 07:15
Issue persists still with `0.10.2 dev`

**Comment by brbrewster** [comment] 2016-06-08 14:04
I experience the same problem on Ubuntu 14.04, but with it set to show the tabs from last time (I think that's the default), if I close and reopen the browser the pages will load. 

Here's once console error I saw:

Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError (This shows as I click through the tabs in the dev tool)

Here's a screenshot of another:
![screenshot1](https://cloud.githubusercontent.com/assets/4588647/15896804/0bd0309e-2d4f-11e6-9e04-634064d2c752.png)

I also noticed it starting when I open a link in a new tab. It doesn't seem to happen when just clicking links, but once it starts, using browser navigation like the back button or refreshing a page causes it to load a blank page.

**Comment by luixxiul** [comment] 2016-06-08 14:17
I regularly use Ubuntu 14 on VM for testing, but I've never experienced the problem :-(

**Comment by brbrewster** [comment] 2016-06-08 16:47
Interesting. It's odd that it'd show on a desktop, but not in a virtual 
machine.

I learned about the Brave browser recently, and tried it on my main 
desktop today. Since it was misbehaving, and there is a github page for 
it, I thought I'd send what i found.

If you have suggestions for something else I can test to get additional 
info for you, I'd be willing to see if I can get a bit more info about 
what's happening.

**Comment by rahilwazir** [comment] 2016-07-13 07:00
Sadly issue still exists with `0.11.0 dev` version

@bbondy Please any input, when this going to be solve? Not able to use the browser anymore.

**Comment by bridiver** [comment] 2016-07-13 07:06
I tried several times and couldn't replicate. Can you try moving ~/.config/brave to ~/.config/brave.bak and see if you can still replicate?

**Comment by rahilwazir** [comment] 2016-07-13 13:21
@bridiver Yes, after moving the folder it still shows blank page.

**Comment by luixxiul** [comment] 2016-07-13 14:24
I'm starting to think this is related with a video driver..

**Comment by bridiver** [comment] 2016-07-13 14:25
possibly, but I would think something like that would affect Chrome as well. I'm testing with virtualbox

**Comment by bridiver** [comment] 2016-07-13 14:33
just to be sure, can you verify that Chrome doesn't have a similar issue? Is this "stock" ubuntu? No kernel updates or similar?

**Comment by rahilwazir** [comment] 2016-07-13 14:43
No, Google Chrome Stable/Canary, Vivaldi all working good.

> Is this "stock" ubuntu

Yes

> No kernel updates or similar

I'm not sure, but my Ubuntu is up-to-date and yes sometimes I do get updates for Linux Kernel headers (are you referring to this?)

**Comment by bridiver** [comment] 2016-07-13 15:18
I meant any custom kernel builds that were not provided by ubuntu updates, but sounds like no. What is the output of `uname -a`?

**Comment by rahilwazir** [comment] 2016-07-14 06:41
Output of `uname -a`:

```
Linux rw 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by brbrewster** [comment] 2016-07-22 08:01
Same here.  I continue to get the same problem with the latest version, except now when I try opening dev tools, it just opens a blank spot where I'd expect a tools menu to be, and I don't experience the same problem in Chrome or Chromium. 

Here is my output for `uname -a`

`Linux computer 3.19.0-33-generic #38~14.04.1-Ubuntu SMP Fri Nov 6 18:17:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`


![brave](https://cloud.githubusercontent.com/assets/4588647/17050262/21c545ba-4faf-11e6-9ea6-507106107e7c.png)

**Comment by rahilwazir** [comment] 2016-07-22 08:22
@brbrewster Yeah it continues to have the same problem on latest version.

You can do couple of things to prevent (actually ignore) the blank screen:

- When the blank screen occurs, open new window and transfer all open tabs to that window, but blank screen will continue to occur, so you will be keep doing this.
- You can open browser dev tool <kbd>Alt</kbd>+<kbd>CTRL</kbd>+<kbd>J</kbd> and dock it side or bottom and keep it open, the blank screen won't appear again (ofcourse it will take your 10% of screen, you can't resize dock to make it fully hidden).  Ref https://github.com/brave/browser-laptop/issues/1471#issuecomment-221529713

**Comment by rahilwazir** [comment] 2016-07-22 09:26
@brbrewster  Ops I'm starting to get blank page also with dev tools open, sorry that workaround isn't working anymore.

**Comment by darwinrc** [comment] 2016-07-25 15:43
I could not tell if this has any relationship with the issue: using a 4k resolution (3840x2160) I get the error, but when switched to 1920x1080 I'm not getting blank pages, at least with some 20 tabs I tested.

**Comment by savelbr** [comment] 2016-07-28 13:09
I'm experiencing the same issue. Here's my `uname -a` output:

`Linux brecht 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by srirambv** [comment] 2016-07-29 16:48
Unable to repro this on Ubuntu16.04. Checked with different resolutions and still able to open all pages.

**Comment by bridiver** [comment] 2016-07-29 17:27
can anyone else verify that using a lower resolution fixes the problem?

**Comment by darwinrc** [comment] 2016-07-29 19:56
This could be a hint: I tested another Electron-based browser (Min) in the same machine (Ubuntu 16.04 x86_64) and got the same results. When in 1920x1080 it works fine, but in 3840x2160 I got blank pages after a few opened tabs.

**Comment by rahilwazir** [comment] 2016-07-29 20:46
@bridiver I'm using1600x900 laptop screen and the issue is there. Not sure it gonna fix, if I go below than that.

**Comment by rahilwazir** [comment] 2016-09-07 07:07
FWIW the issue still exists on `0.12.0`

**Comment by luixxiul** [comment] 2016-09-07 10:58
Thanks for your feedback, @rahilwazir. Do you experience the error after lowering the resolution?

**Comment by rahilwazir** [comment] 2016-09-07 11:36
@luixxiul Yes!

All following resolution have bug:

- 1600x900
- 1440x900
- 1366x768

**Comment by PowerInside** [comment] 2016-09-28 08:35
I get the same issue too with Brave 0.12.1 on Antergos Linux distro (based on ArchLinux).

```
Resolution: 1366x768
Kernel: 4.7.4-1-ARCH
```

This issue seems to occur only after a few minutes of using the browser (several tabs also work fine). But after sometime, opening a new tab results in this bug and subsequently, all new tabs experience this issue. Navigation is possible in 'older' tabs, but entering a new URL in one of these 'old' tabs yields the blank white page.

**What works from this stage**: Opening a new window and tabs in that new window work fine. (as mentioned here https://github.com/brave/browser-laptop/issues/1471#issuecomment-234483596)

PS: All blank pages actually have the pages rendered I think.. Confirmed this via inspector and also through the mouse pointer icon which changes here and there when I move it across the body of the 'blank' page (indication of hyperlinks, text etc). This suggests that links and content are actually down there, but white/invisible for some reason.

**Comment by marlonjames** [comment] 2016-10-03 01:41
I've been seeing this same issue since 0.11.2
3.19.0-65-generic #73~14.04.1-Ubuntu x86_64 x86_64 x86_64 GNU/Linux
Resolution:  (left) 1680x1050 + 1920x1080 (right)

**Comment by Aeyoun** [comment] 2016-10-06 09:49
If you’re experiencing this issue, could you please test [these reproduction steps](https://github.com/brave/browser-laptop/issues/3787#issuecomment-248615910) and see if they trigger the problem for you?

**Comment by rahilwazir** [comment] 2016-10-06 10:06
@Aeyoun Yes the issue appears with those steps. I think it has something to with the media elements in the DOM.

**Comment by Aeyoun** [comment] 2016-10-06 10:14
I guess that a media playback buffer from libffmpeg (?) is left on top covering the webview whenever a media element is unloaded and playback stops. That fits the observed behavior, at least.

**Comment by PowerInside** [comment] 2016-10-07 04:16
Can confirm this issue persists using the test case linked in https://github.com/brave/browser-laptop/issues/1471#issuecomment-251916315

**Comment by freemanIT** [comment] 2016-10-21 19:27
Linux freemanit 4.2.0-42-generic #49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
![screenshot from 2016-10-21 22-26-03](https://cloud.githubusercontent.com/assets/14862611/19609044/8eb7c2da-97dd-11e6-8791-f7654f365f49.png)
![screenshot from 2016-10-21 22-27-08](https://cloud.githubusercontent.com/assets/14862611/19609045/8ebab594-97dd-11e6-9253-35b95d6bfcd1.png)

**Comment by NQAT** [comment] 2016-11-06 21:41
Same problem with blank tabs on Ubuntu 16.04, 1366 x 768. Seems to to happen when the browser has to open up tabs on a fresh start.

only way for me to fix it is to close some tabs and restart the browser.

**Comment by bsclifton** [comment] 2016-12-03 22:42
With the info disclosed in https://github.com/brave/browser-laptop/issues/4928, I'm curious how many folks here have an ATI/AMD Radeon card? It seems this may be a bug in the driver (official and open source)

cc: @NQAT @darwinrc @savelbr @rahilwazir

**Comment by da2x** [comment] 2016-12-03 23:16
I've got an AMD R9 290 and have the problem with proprietary and open source drivers alike.

**Comment by rahilwazir** [comment] 2016-12-04 09:21
@bsclifton Well, I've ATI/AMD GPU but not sure that is it currently being used or not?

Following output may help:

```
$ lspci -v | grep "VGA"
$ 00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09) (prog-if 00 [VGA controller])
$ 01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Thames [Radeon HD 7550M/7570M/7650M] (rev ff) (prog-if ff)
```

I tested on other machine which have

- Fedora 25 64bit
- `Intel HD Graphics 5500 (rev 09)`

and it's working fine, no blank page issue there.

**Comment by spoo6354** [comment] 2016-12-04 15:39
I am using a AMD R7 250 with amdgpu drivers loaded.
I haven't tested Brave with any other drivers, but it works fine on Windows.
It seems that it is a driver issue, which is a shame. I hope you guys fix it ASAP.


> $ lspci -v | grep "AMD"
> 01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Oland XT [Radeon HD 8670 / R7 250/350] (prog-if 00 [VGA controller])
>

**Comment by luixxiul** [comment] 2016-12-04 17:04
FYI https://github.com/electron/electron/issues/5998#issuecomment-225756787
https://github.com/electron/electron/issues/4380 (Nvidia)

**Comment by da2x** [comment] 2016-12-06 00:21
I switched my machine temporarily from AMD R9 290 to Intel HD 4000. It works with Intel graphics, but my desktop is horribly slow and there are a lot of other things that don’t work. Please address this issue.

**Comment by posix4e** [comment] 2016-12-07 03:45
@da2x  your desktop is slow even when the browser is turned off? What about your desktop is slow. Is it just brave? What release are you using? What operating system?

**Comment by da2x** [comment] 2016-12-07 11:45
@posix4e Fedora Linux 25.x86_64. My desktop is super slow when running the Intel integrated graphics chip and drivers compared to the AMDGPU drivers and chip. Brave works great with the Intel graphics chip and drivers (no blank pages). However, I want everything else to work and be fast more than I want Brave to work, so I’m sticking with Firefox and my AMDGPU drivers until this is resolved.

**Comment by posix4e** [comment] 2016-12-08 17:56
Got it so there's no brave bug with AMDGPU drivers just the continued problems we have with ATI cards in brave. Got it!

**Comment by spoo6354** [comment] 2016-12-08 19:09
How long is it going to take to fix it?
Brave is the only good browser at the moment.

**Comment by bsclifton** [comment] 2016-12-08 21:16
I think based on the information reported and also what we've found, we might be able to deliver a "graphics card light" flag, while we're looking into the root cause.  For example, being able to turn off hardware accelleration (from the command line) and then also being able to pass extra flags when we initialize Chromium (ex: `ignore-gpu-blacklist`) could be very useful.

I'm making a post on AMD's forum right now.  I'll share the link when the post is live, in case you all wanted to provide more info :smile:

**Comment by bsclifton** [comment] 2016-12-08 21:28
Message is pending approval, but will be live here (if approved):
https://community.amd.com/message/2764862

@da2x if I was able to put together a possible fix for you, would you be willing to try it out?

**Comment by da2x** [comment] 2016-12-08 22:00
@bsclifton, absolutely.

**Comment by bsclifton** [comment] 2016-12-10 00:15
@da2x OK after some debugging and experimentation with both Electron and Chromium, I have found a work-around you can try.  This is based on the work-around that @luixxiul [found above](https://github.com/electron/electron/issues/5998#issuecomment-225454742).

When the brave executable is launched, please add the argument `--ignore-gpu-blacklist`.  There are a few others you can try too, if this doesn't work:
```
--disable-gpu-rasterization
--disable-native-gpu-memory-buffers
--disable-accelerated-2d-canvas
```

These parameters are passed directly to Chromium.  You should be able to see the value of them in Google Chrome by going to `chrome://gpu` or `chrome://flags`

**Comment by da2x** [comment] 2016-12-13 01:10
@bsclifton, no combination of those three headers have any effect on the problem; except that `--disable-accelerated-2d-canvas` on it’s own makes the browser UI unresponsive as well.

**Comment by da2x** [comment] 2016-12-13 01:13
@bsclifton and here is everything from chrome://gpu (where the problem doesn’t reproduce) from Chrome 55.0.2883.87.

https://gist.github.com/da2x/56090920e4db5227a032255f392b8c11

**Comment by ConorIA** [comment] 2016-12-13 22:33
In my case just the `--ignore-gpu-blacklist` flag was enough to solve the issue. Now I can visit http://www.quirksmode.org/html5/tests/video.html, and new tabs work fine. The only new message that I notice on the console is `Error: app.disableHardwareAcceleration() can only be called before app is ready`, which means that my poor AMD APU is working hard.

**Comment by bsclifton** [comment] 2016-12-14 00:57
@ConorIA thanks for the update :smile: Do you have specific information about your OS / card? I'll share on AMD's forums and see if there is any action which can be taken. Ultimately, it seems like the driver needs a fix

**Comment by ConorIA** [comment] 2016-12-14 01:22
@bsclifton, my system is running on Manjaro Linux, with Gnome 3.22. I was using kernel 4.7.10. 
My card is a cheap AMD Athlon 5350 APU with Radeon R3 integrated graphics. 

Relevant packages: `xorg-server 1.18.4`; `xf86-video-ati 1:7.8.0`

**Comment by Paladin45** [comment] 2016-12-30 18:00
I'm having the same problem. Brave 0.12.15 running on Solus 1.2.1. Video card is an old AMD FirePro V4900 workstation card. I've pasted console output below.

daryl@fusilier ~/bin/Brave-linux-x64 $ ./brave
could not parse data:  undefined
Crash reporting enabled
A Parser-blocking, cross-origin script, https://ssl.google-analytics.com/ga.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, https://ssl.google-analytics.com/ga.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, http://www.googletagservices.com/tag/js/gpt.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, http://www.googletagservices.com/tag/js/gpt.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, https://analytics.abbvie.com/external/nobsabouths/analytics.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, https://analytics.abbvie.com/external/nobsabouths/analytics.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, https://analytics.abbvie.com/external/nobsabouths/visitorAPI.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, https://analytics.abbvie.com/external/nobsabouths/visitorAPI.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, https://analytics.abbvie.com/external/nobsabouths/appMeasurementLib.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, https://analytics.abbvie.com/external/nobsabouths/appMeasurementPlugins.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, https://assets.adobedtm.com/ffef439a788b8741fd34c1ff9001acae5e4fae43/satelliteLib-f5c4627fbfe9a9876906c6fec55c7f826d11a5ad.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
daryl@fusilier ~/bin/Brave-linux-x64 $ ./brave
Crash reporting enabled
A Parser-blocking, cross-origin script, https://analytics.abbvie.com/external/nobsabouths/analytics.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, https://analytics.abbvie.com/external/nobsabouths/analytics.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, https://analytics.abbvie.com/external/nobsabouths/visitorAPI.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, https://analytics.abbvie.com/external/nobsabouths/visitorAPI.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, https://analytics.abbvie.com/external/nobsabouths/appMeasurementLib.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, https://analytics.abbvie.com/external/nobsabouths/appMeasurementPlugins.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, https://assets.adobedtm.com/ffef439a788b8741fd34c1ff9001acae5e4fae43/satelliteLib-f5c4627fbfe9a9876906c6fec55c7f826d11a5ad.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, http://www.googletagservices.com/tag/js/gpt.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, http://www.googletagservices.com/tag/js/gpt.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.

**Comment by AlexGilleran** [comment] 2017-01-09 09:59
--ignore-gpu-blacklist fixes this for me - Radeon HD 7970 on Arch Linux

**Comment by Paladin45** [comment] 2017-01-19 15:17
@AlexGilleran That works, thanks!

**Comment by bsclifton** [comment] 2017-01-20 06:52
Another option which should work for folks:
`--disable-gpu`

For more info, check out the electron bug for this (which has a lot more info):
https://github.com/electron/electron/issues/4380

**Comment by bsclifton** [comment] 2017-01-30 06:54
Thanks everybody for testing the above command-line options.  Based on the input here, we've created a [brand new wiki page](https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page). Please feel free to comment here or also update the wiki with your notes

Since we don't auto-detect this situation and remedy, I'll leave this issue open

**Comment by josephskrzysowski** [comment] 2017-11-22 14:54
Hey whats the status of this bug? I get it to work with --ignore-gpu-blacklist but am I going to have to start brave browser like this from now on- forever? Or is there a fix? I really don't want to go back to firefox or really any other browser.

**Comment by bsclifton** [comment] 2018-07-25 06:47
Since we have a [documented workaround](https://community.brave.com/t/window-is-solid-black-or-solid-white-looks-like-a-blank-page/10003) and also because we're moving to [Brave Core](https://github.com/brave/brave-browser) and won't be addressing this before then, I believe it makes sense to close this issue

**Closed by bsclifton** 2018-07-25 06:47 UTC
Labels: OS/unix-like/linux, bug, bug/driver

**Comment by joeybronzoni** [comment] 2018-07-25 22:16
Oh, thanks @bsclifton. Not sure how I didn't come across that workaround in my search. Appreciate that.
