### ISSUE TITLE
show search icon during page load

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#6518] opened 2017-01-03 23:15 UTC
See the empty spaces in the following GIF movie:

![slow_url_icons](https://cloud.githubusercontent.com/assets/13509546/21626679/5f47ec36-d1c7-11e6-9732-e74e37c9b226.gif)

**Comment by diracdeltas** [comment] 2017-01-04 06:38
fwiw the 'secure' icon will always have some lag because it should never be set until the TLS connection is confirmed to be secure.

**Comment by bradleyrichter** [comment] 2017-01-04 17:06
@diracdeltas That will be fine. The biggest problem here is the empty space related to the search icon.

**Comment by kaizensoze** [comment] 2017-01-05 03:50
Is this just a matter of allowing the search icon to show while loading?

**Comment by bradleyrichter** [comment] 2017-01-05 03:53
@kaizensoze I'll rename this one and add 2 more separate issues that are more specific.

**Comment by kaizensoze** [comment] 2017-01-05 04:10
Created PR.

**Comment by cezaraugusto** [comment] 2017-01-18 04:53
Closed by 2c4b720

STR:

1. Watch urlBar search icon
2. Open a tab
3. Open another tab
4. Icon should not flash between tab changing

**Closed by cezaraugusto** 2017-01-18 04:53 UTC
Labels: bug, feature/URLbar, polish, priority/high
