### ISSUE TITLE
XY coordinate for the new window when opening needs to offset slightly to make it easy to find multiple windows

### ISSUE THREAD

**Issue by jenn-rhim** [brave/browser-laptop#10914] opened 2017-09-12 18:22 UTC
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
New windows stack exactly the same position as the previous one obscuring the previous window
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.6
- Brave Version (revision SHA):
0.18.29
- Steps to reproduce:
    1. Have an existing brave window
    2. Open a new window (Ctrl N)
    3. New window stacks right on top of the window below
    
- Actual result:
New window stacks right on top of the window below, making it difficult to know that there is a window below and to get to the previous window, the user would have to move the top window out of the way before they can get to the one below.
- Expected result:
Offset the xy coordinate of where the new window instance comes up
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![4 windows of brave](https://user-images.githubusercontent.com/4369856/30341917-b2f02a32-97ac-11e7-8cab-558798a690a7.png)
![4 windows of firefox](https://user-images.githubusercontent.com/4369856/30341926-b6f15840-97ac-11e7-8453-4e3233e4cdb8.png)

- Any related issues:

**Comment by NejcZdovc** [comment] 2017-09-12 19:05
closing this as a dupe of #8925. This issue was fixed in 0.20.x with #10458

**Closed by NejcZdovc** 2017-09-12 19:05 UTC
