### ISSUE TITLE
Downloads don't save with supposed sufix (.jpg, .exe, etc)

### ISSUE THREAD

**Issue by puzzledbytheweb** [brave/browser-laptop#13484] opened 2018-03-16 21:17 UTC
### Steps to Reproduce

  1. Download any type of file

**Actual result:**

![braveissue](https://user-images.githubusercontent.com/35262512/37544924-ab9caf6e-295e-11e8-8a92-1d55854328d4.png)

**Expected result:**

The file should be saved as a .jpg, .png, etc

**Reproduces how often:**

### Brave Version

**about:brave info:**

 
Brave: 0.21.19 
V8: 6.5.254.36 
rev: f359e6ed2616360456945bff01bac707895fd651 
Muon: 4.9.2 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: ia32 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Reproducible on current live release:**

Yes

**Comment by btlechowski** [comment] 2018-03-17 01:30
Thanks for reporting the issue.

Confirmed on Win7 v0.21.19. Also reproduced on 0.21.18 and 0.20.46.

Note: When the file is saved with default name, then the downloaded file will have the suffix.
 
cc @kjozwiak @LaurenWags @srirambv

**Comment by eljuno** [comment] 2018-03-17 20:01
Dupe of #1985?

**Comment by btlechowski** [comment] 2018-03-18 00:37
Indeed. Thanks @eljuno.

We have fix for it, but it will be available in later Brave versions.

Closing as dupe of #1985.

**Closed by btlechowski** 2018-03-18 00:37 UTC
Labels: bug, feature/download
