### ISSUE TITLE
Tabbycat errors with uncaught exception.

### ISSUE THREAD

**Issue by diasdavid** [brave/browser-laptop#9871] opened 2017-07-05 14:35 UTC
- Did you search for similar issues before submitting this one? Yes
- Describe the issue you encountered: tabbycat
- Platform (Win7, 8, 10? macOS? Linux distro?): Mac OS X 10.12.15
- Brave Version (revision SHA): `db1e1bc953e83c47a08235108576d0c1dc15e3ea`
- Steps to reproduce:
    1. Follow @jonathansampson blog post https://blog.brave.com/loading-chrome-extensions-in-brave/ to install the extension
    2. npm run watch
    3. npm run start
    4. turn on tabbycat on the extensions pane
    
- Actual result: 

On step 3, we get an uncaught exception:

```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
    at Immediate.setImmediate (/Users/koruza/code/brave-browser-laptop/app/browser/windows.js:292:13)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

On step 4 we get an unlimited number of Uncaught Exceptions:

```
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
    at Immediate.setImmediate (/Users/koruza/code/brave-browser-laptop/app/browser/windows.js:292:13)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
```

- Expected result:

No errors. a new cat on each tab

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes. I've repeated this process multiple times.

- Is this an issue in the currently released version?

Yes

- Can this issue be consistently reproduced?

Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

![image](https://user-images.githubusercontent.com/1211152/27869298-65988edc-6197-11e7-8927-df13262154de.png)

![image](https://user-images.githubusercontent.com/1211152/27869310-6e52ceca-6197-11e7-9cae-98f6fb515aae.png)

- Any related issues: https://github.com/diasdavid/browser-laptop/pull/1#issuecomment-312412106

**Comment by jonathansampson** [comment] 2017-08-20 18:49
@diasdavid I was not able to reproduce the issues you experienced. If you like, we can hop on a call later (Skype or GoogleHangout) and run through the exercise together.

I tested with the following configuration:
``` 
Brave: 0.20.0 
V8: 6.0.286.44 
rev: eced5c4085b8045c3fe10fb1d389e7603decf287 
Muon: 4.4.5 
OS Release: 10.0.15063 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.3.5 
libchromiumcontent: 60.0.3112.78
```

**Comment by diasdavid** [comment] 2017-08-21 08:59
This is super weird. Just did a fresh clone and npm install from master. Went through the steps in the blog post and got the same erros:

![image](https://user-images.githubusercontent.com/1211152/29511539-57a9ee12-8657-11e7-9746-6304902b9410.png)


```
Brave: 0.20.0 
V8: 6.0.286.54 
rev: eced5c4085b8045c3fe10fb1d389e7603decf287 
Muon: 4.4.9 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.3.5 
libchromiumcontent: 60.0.3112.101
```

Could this be a MacOS thing? Let me get a VM to try it again

**Comment by diasdavid** [comment] 2017-08-21 11:47
Ok, full vm installed all all the things that Windows needs.

In windows it doesn't throw uncaught exceptions, but I don't get any cat on new tabs.

```
Brave: 0.20.0 
V8: 6.0.286.54 
rev: eced5c4085b8045c3fe10fb1d389e7603decf287 
Muon: 4.4.9 
OS Release: 10.0.15063 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.3.5 
libchromiumcontent: 60.0.3112.101
```

**Comment by diasdavid** [comment] 2017-08-22 06:04
@jonathansampson I take your invite for a Google Hangout / Zoom Call, I believe we could use some sync time to go through multiple things in the IPFS endeavour.

I'm in [Lisbon (UTC+1)](https://www.worldtimebuddy.com/?qm=1&lid=8,100,2267057,2950159&h=2267057&date=2017-8-22&sln=17-24) and I'm free in the evening today

**Comment by jonathansampson** [comment] 2017-08-22 17:59
Closing this after our call. I think the issue here was the state of the `session-store` file in your Brave directory. When you explicitly `register` and `load` the IPFS extension in `app/extensions.js`, you don't need to toggle the switch in _about:preferences#extensions_.

**Closed by jonathansampson** 2017-08-22 17:59 UTC
Labels: bug, feature/extensions
