### ISSUE TITLE
Regression : Verified pubs no longer have green badge on ledger

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7186] opened 2017-02-11 06:59 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Verified publishers were visited and they domains appear in the listing, but they are missing the verified badges as shown in https://github.com/brave/browser-laptop/issues/6986

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10 x64 and OS X

- Brave Version (revision SHA):
0.13.3 RC 1 https://github.com/brave/browser-laptop/commit/7024e09766a39e46f399dad2a84c40e086341b1f

- Steps to reproduce:
    1. With a clean profile, enable payments
    2. Visit alexwykoff.com/2/demo, play the game for a couple seconds (or visit any other verified pub)
    3. Check the ledger for the green hexagon with white checkmark to indicate alexwykoff.com is a verified publisher 
    
- Actual result:
The domain appears, but the verification badge does not.

- Expected result:
The verification badge should appear.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment] 2017-02-11 08:08
With my existing profile I have the icon:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/22852254/6fd1bf00-f07b-11e6-93dd-3e29f1c16d2f.png)

While the new profile I don't as @alexwykoff points out.

Also the inclusion button on the URL bar does not the green hexagon:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/22852309/8a430ffa-f07c-11e6-8da3-1d109d32a3b3.png)

**Comment by bbondy** [comment] 2017-02-12 04:11
```
 get verifiedPublisher () {
    let verifiedPublisher
    this.props.synopsis.map(publisher => {
      if (publisher.get('site') === this.domain && publisher.get('verified') === true) {
        verifiedPublisher = !!publisher
        return false
      }
      return true
    })
    return verifiedPublisher
  }
```
`publisher.get('site')` is brianbondy.com and `publisher.get('verified')` is false, so it displays as not verified.

my session-store-1 has `"publisherInfo":{"synopsis":[{"site":"brianbondy.com","verified":false,`

**Comment by bbondy** [comment] 2017-02-12 04:12
cc @mrose17

**Comment by bbondy** [comment] 2017-02-14 02:36
@mrose17 mentioned this doesn't need to block 0.13.3 so I'm moving to 0.13.4.

**Comment by mrose17** [comment] 2017-03-07 23:11
@alexwykoff - can you reproduce this in the current release? i can not.  however, keep in mind that updates of publisher information normally take place once a day ...

**Comment by mrose17** [comment] 2017-03-10 20:26
i'm closing this due to lack of reproducibility... if someone _can_ reproduce it, please let me know!

(we've also done a fair amount of work since this issue was created to rework the display algorithms, etc., which may explain why i can't reproduce it...)

**Closed by mrose17** 2017-03-10 20:26 UTC
Labels: bug, feature/ledger
