### ISSUE TITLE
opening a new window has a long delay before key events can be captured for the url bar

### ISSUE THREAD

**Issue by patrick99e99** [brave/browser-laptop#9877] opened 2017-07-05 21:10 UTC
If I close all my brave windows, type CMD-N for a new window, a blank window appears with no url bar for 1-2 seconds, and if I begin typing during that time, no characters appear until after the url bar actually appears, and worse, it only starts accepting my keyboard input at the moment the url bar appears, so the majority of the characters I typed get lost.

It would be lovely if the new Brave window had a url bar instantly and can begin receiving keyboard input immediately so that fast typists can input where they want to go without having to wait.

**Comment by fbettag** [comment] 2017-07-22 22:35
actually i don't think this is because of a new window.

I was just about to report, that the URL bar is unresponsive when the page is loading.

For example i type in a page that takes a few seconds to load, while it's loading i press Cmd+L for the address bar, i start typing, but it only continues after the body of the tab has been loaded.

Could this be a threading issue?

**Comment by zentagonist** [comment] 2017-08-14 17:05
@fbettag - I'm not able to reproduce this. Following the steps in your post:

1 - Close all Brave windows
2 - CMD+N to open a new window

I'm able to enter typed text to the URL bar almost immediately. Many performance improvements have been made recently. Please retest and confirm this is still an issue.

**Comment by JaneSmith** [comment] 2017-08-17 00:07
I can confirm this is still an issue. Tested on Windows 10 Pro with version 0.18.23 (36ae2ec). It's worse with new windows, but it happens with new tabs as well. It basically gets me every single time I try to open a new tab and type a URL - I end up with the first several characters gone.

**Comment by patrick99e99** [comment] 2017-09-13 18:41
apparently other people are having this complaint too...
https://www.reddit.com/r/BATProject/comments/6zve4z/slowest_browser_to_open_brave/

**Comment by luixxiul** [comment] 2017-09-13 18:49
> If I close all my brave windows, type CMD-N for a new window, a blank window appears with no url bar for 1-2 seconds

That issue is tracked on https://github.com/brave/browser-laptop/issues/8128

**Comment by yx-3s** [comment] 2019-04-16 18:36
christ how is this not fixed??

**Comment by bsclifton** [comment] 2019-04-16 18:56
@gnawh this repository is for the older version of our browser. You're likely looking for 
https://github.com/brave/brave-browser/issues/3756

There is a fix for this in review right now:
https://github.com/brave/brave-core/pull/2222

We'll have the fix merged for our next release (0.63.x)

**Closed by bsclifton** 2019-04-16 18:56 UTC
Labels: perf
