### ISSUE TITLE
Browser lags when scrolling through 1K publisher list

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13340] opened 2018-02-28 11:57 UTC
### Description
Browser lags when scrolling through 1K publisher

### Steps to Reproduce
  1. Clean install 0.21.x build
  2. Enable payments and close browser
  3. Add simulated ledger entries from `npm run add-simulated-synopsis-visits 1000`
  4. Relaunch browser. open payments
  5. Scroll through the list of 1K publishers, scrolling lags 

**Actual result:**
Browser lags when scrolling through 1K publisher list

**Expected result:**
Shouldn''t lag when scrolling through 1K publisher list

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.21.17
-- | --
V8 | 6.4.388.41
rev | 57e6145
Muon | 4.8.2
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
Yes

### Additional Information
cc: @NejcZdovc

**Comment by diracdeltas** [comment] 2018-03-01 21:14
see https://github.com/brave/browser-laptop/issues/11551

**Comment by NejcZdovc** [comment] 2018-03-17 04:29
closing this one as dupe of #11551

**Closed by NejcZdovc** 2018-03-17 04:29 UTC
Labels: bug, feature/ledger, polish
