### ISSUE TITLE
Edit bookmark doesn't show bookmark folder

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#8840] opened 2017-05-11 18:53 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When editing a bookmark which is in a folder, the editor doesn't show the folder.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
master @ 12199f903d0dafd126344b1290f3084f16377559

- Steps to reproduce:
    1. Go to twitter.com
    2. Bookmark it
    3. Create a bookmark folder
    4. Edit twitter.com bookmark to be in the bookmark folder and hit Done to save
    5. Again edit twitter.com bookmark
    6. Observe the bookmark's folder
    
- Actual result:
Folder shows as "Bookmarks Toolbar"

- Expected result:
Show the bookmark folder

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by kumarrishav** [comment] 2017-05-12 11:24
Unable to reproduce on
Brave	0.15.2
rev	af7ef42

I am able to expected folder name. Can you give more input on this? @ayumi

**Comment by NejcZdovc** [comment] 2017-05-12 12:28
@kumarrishav this could be a regress in 0.15.3, I would suggest that you checkout master and test it out there.

**Comment by luixxiul** [comment] 2017-05-29 09:23
reproduced on 0.15.310

**Comment by luixxiul** [comment] 2017-05-29 09:33
@srirambv is this the same issue you captured on https://github.com/brave/browser-laptop/issues/7032?

**Comment by srirambv** [comment] 2017-05-29 10:47
@luixxiul That is correct.. Its the same issue as #7032

**Comment by srirambv** [comment] 2017-05-29 10:48
Closing as dupe of #7032.

**Closed by srirambv** 2017-05-29 10:48 UTC
Labels: bug, feature/bookmarks
