### ISSUE TITLE
Cursor not visible

### ISSUE THREAD

**Issue by davidak** [brave/browser-laptop#11396] opened 2017-10-09 14:35 UTC
### Description
The cursor in text fields is not visible in one window. It is visible in other windows...

### Steps to Reproduce

  1. click in textfield
  2. type something
  3. be confused where the cursor is

**Actual result:**
![screenshot from 2017-10-09 16 33 02](https://user-images.githubusercontent.com/91113/31343310-8e7f5a7e-ad0f-11e7-92cb-9ca7ac9808a1.png)

(the cursor is actually at the end of the input ;)

**Expected result:**

It would be helpful to see the cursor all the time!

**Reproduces how often:** 10%

### Brave Version

**about:brave info:**
 
Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Linux 
OS Release: 4.10.0-35-generic 
OS Architecture: x64

**Reproducible on current live release:**
not tested

**Comment by bsclifton** [comment] 2017-10-09 20:27
Thanks for the report, @davidak 😄   This issue is a duplicate of https://github.com/brave/browser-laptop/issues/10299, which you can track for more information

**Closed by bsclifton** 2017-10-09 20:27 UTC
