### ISSUE TITLE
Bookmark title on bookmark toolbar is renamed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6108] opened 2016-12-09 03:23 UTC
**Describe the issue you encountered:**
Bookmark title on the bookmark toolbar is renamed after clicking the link to the notification page on GitHub.

**Expected behavior:**
The bookmark title should not be changed.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Steps to reproduce:
    1. Bookmark the notification page on GitHub
    2. Click the notification link -> the bookmark title is changed

- Screenshot if needed:
![bookmark](https://cloud.githubusercontent.com/assets/3362943/21036724/634c3ed8-be0b-11e6-871a-c0a17858af55.gif)

- Any related issues:

**Comment by luixxiul** [comment] 2016-12-09 03:33
Edited.

**Comment by bsclifton** [comment] 2016-12-09 05:07
This may or may not be expected.  This is the current behavior:
- When a site is visited, a siteDetail record will be created
- If one already exists, that will be updated
- The new title ALWAYS overwrites the old title. Custom title does not change
- If custom title is never set (which only happens if user manually does it), the user will always see the title (which will end up being the new one, OR if blank, the URL)

To keep things simple, I'd like to propose that we eliminate custom title.
- When a bookmark is added for a page, it will default to the title of the page
- Once set, the title for that bookmark will never be updated again

What do you think @luixxiul? Also, CC: @bradleyrichter @BrendanEich @bbondy @darkdh (and everyone else too :smile: )

**Comment by luixxiul** [comment] 2016-12-09 05:21
> When a bookmark is added for a page, it will default to the title of the page
> Once set, the title for that bookmark will never be updated again

If this is the default behavior on Chrome/Firefox, +1 :)

**Comment by Liunkae** [comment] 2016-12-09 08:22
+1 for your proposal. It seems like the least confusing option from a user perspective.

**Comment by NejcZdovc** [comment] 2016-12-09 10:48
+1 When you are visiting a page that is also bookmarked, this should not change bookmark title.

**Comment by luixxiul** [comment] 2016-12-09 14:42
@NejcZdovc I have reported the issue on #5738

**Comment by bsclifton** [comment] 2016-12-09 15:51
@luixxiul would this be something you'd be interested in looking at? (I'd be more than happy to help!) I bet there are at least 2 or 3 more issues related to this same root cause.  Let me know :smile:

**Comment by bradleyrichter** [comment] 2016-12-09 15:58
@bsclifton I think the custom title is a requirement. Quite often, a page is bookmarked at an entry point to a top domain but the user wants to simply the BM title to be the top domain.

For example:

![image](https://cloud.githubusercontent.com/assets/13509546/21055101/fce47ef6-bde4-11e6-981e-12c2beba6a94.png)

I wanted to rename this obscure title (when truncated) to 'CSS Tricks" which is far more recognizable/meaningful.

![image](https://cloud.githubusercontent.com/assets/13509546/21055153/2a3058e4-bde5-11e6-8768-9d6c7a8d0e92.png)


![image](https://cloud.githubusercontent.com/assets/13509546/21055178/3d8a45d0-bde5-11e6-945e-27ace997323e.png)

**Comment by bsclifton** [comment] 2016-12-09 17:11
@bradleyrichter my proposal is to eliminate the custom title field and then use title like a custom title.  Right now, the title is something that users can't change... but it causes problems because it will update if the page title updates.

I think it's a better experience to always treat the title like it's a custom title.  It should never be updated unless the person changes it themselves.  That should be consistent with other browsers

**Comment by bradleyrichter** [comment] 2016-12-09 18:27
Yes. Agree. I was confused about the meaning of Title and Custom Title. The user only sees title. 

Under the hood, we should just treat a title as a custom title and never auto-update any BM data. Only if the user updates the data manually. (as you described)

**Comment by NejcZdovc** [comment] 2016-12-10 08:27
If we remove CustomTitle then issue #6104 and PR #6111 can be closed.

**Comment by NejcZdovc** [comment] 2017-07-20 11:20
Will be fixed in #9979

**Closed** 2017-08-04 16:17 UTC
Labels: bug, feature/bookmarks
