### ISSUE TITLE
short term video freezes

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#9808] opened 2017-06-30 19:56 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
While watching a youtube video some users are reporting short term video freezes, but they are intermittent, usually occurring within 30s to 1.5 minutes of starting the video. Does not reproduce on rewind. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Reported on MacOS

- Brave Version (revision SHA):
Brave	0.17.13
rev	f7242c7
Muon	4.1.7

- Steps to reproduce:
    1. Start a youtube video. 
    2. Short term freeze (about a second or so) could occur within 30s to 1.5 minutes of starting the video.

- Actual result:
Video might have a short term lag/freeze.

- Expected result:
Video should not have any lag or freeze.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes, but not consistently.

- Is this an issue in the currently released version?
yes, 0.17.13

- Can this issue be consistently reproduced?
No. Tried pinned tabs, private tabs, full screen viewing, session tabs, did not see consistent results.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-laptop/issues/9044
https://github.com/brave/browser-laptop/issues/3885

**Comment by patrick99e99** [comment] 2017-07-03 00:30
+1 this happens all the time for me, both on my macbook pro laptop (Sierra), and my 2016 iMac (El Capitan).

**Comment by luixxiul** [comment] 2017-07-03 01:29
+1 from me too

**Comment by Zlutz** [comment] 2017-07-03 13:55
+1
Just upgraded to 0.17.13, but it was happening on a version before (I'm not using it for long)
For me, the symptoms are:
Video freezes and scrolling doesn't work, but audio keeps on playing.
Also, when just generally surfing, whole browser stops sometimes.
I tried to disable hardware acceleration, but it didn't help.
I unticked "show tab preview on hover" and it helped a bit, whole browser seems a bit faster, but I'm not really sure because the freezes are so random.

**Comment by luixxiul** [comment] 2017-07-04 17:21
> Also, when just generally surfing, whole browser stops sometimes.

Yes, it seems that video freeze just makes it noticiable.

**Comment by Zlutz** [comment] 2017-07-05 07:35
Update:
I just noticed reproducible behavior that might or might not be connected to this problem;

If I'm browsing and I simply alt-tab to something else, it works fine immediately when I go back browsing.
If I minimize the browser and then go back, the browser hangs for couple of seconds (even mouse scroll doesn't work) and it seems to redraw very quickly after those couple of seconds; doesn't matter if there was video in the current tab...

**Comment by bbondy** [comment] 2017-08-08 20:56
Duplicate of #10094

**Closed** 2017-08-08 20:56 UTC
Labels: bug, perf
