### ISSUE TITLE
Clicking links in other applications does not open URL in Brave when extra command line parameters are specified

### ISSUE THREAD

**Issue by DivineOmega** [brave/browser-laptop#7090] opened 2017-02-06 10:22 UTC
- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered: After working around [this issue](https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page) by adding `--ignore-gpu-blacklist` to the `Exec` line of `brave.desktop`, clicking links in other applications does not open the URL in Brave. It does bring Brave to focus, but that is all.

- Platform (Win7, 8, 10? macOS? Linux distro?): Ubuntu 16.04 LTS

- Brave Version (revision SHA): 0.13.1, rev: 9dd06f9463d155291efdb419ad0df4c2df16b611 

- Steps to reproduce:
1. Modify your `brave.desktop` file at `/usr/share/applications/brave.desktop` to resemble the following.

```
[Desktop Entry]
Name=brave
Comment=Brave laptop and desktop browser
GenericName=brave
Exec=brave %U --ignore-gpu-blacklist
Icon=brave
Type=Application
StartupNotify=true
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml_xml;image/webp;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;
```

2. Click a link in another program.
3. Notice that Brave is brought to focus (after a few moments), but the URL itself does not open.
    
- Actual result: Brave is brought to focus, but URL does not open.

- Expected result: Brave should be brought to focus and the URL from the clicked link should be opened.

- Will the steps above reproduce in a fresh profile? If not what other info can be added? I do not believe profile state is applicable this issue, but I have yet to test with a fresh profile to completely rule this out.

- Is this an issue in the currently released version? Yes.

- Can this issue be consistently reproduced? Yes.

**Comment by DivineOmega** [comment] 2017-02-15 17:11
I've determined this can be solved by changed the `Exec` line to the following:

```
Exec=brave --ignore-gpu-blacklist -- %U
```

**Comment by DivineOmega** [comment] 2017-02-15 17:15
I've updated the Troubleshooting article on the wiki appropriately.

https://github.com/brave/browser-laptop/wiki/Troubleshooting#linux

**Comment by bsclifton** [comment] 2017-02-15 17:43
Awesome, thanks for documenting the fix, @DivineOmega 😄 

This would be a great first bug for someone who wanted to update the desktop file

**Comment by bsclifton** [comment] 2017-07-30 22:19
Closing this as a duplicate of https://github.com/brave/browser-laptop/issues/9193 (which has more information and steps).  Thanks for helping ID the issue and fix, @DivineOmega 😄

**Closed by bsclifton** 2017-07-30 22:19 UTC
Labels: bug, bug/good-first-bug, OS/linux-distros
