### ISSUE TITLE
Back shortcut not the Backspace key like ALL other broswers

### ISSUE THREAD

**Issue by fusion01k** [brave/browser-laptop#12161] opened 2017-12-02 19:25 UTC
### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version 0.19.105

**about:brave info:**

**Reproducible on current live release:**

**Comment by eljuno** [comment] 2017-12-02 20:24
Duplicate of #6156?

**Comment by fusion01k** [comment] 2017-12-02 20:55
Yes sort of.  I wish it was like someone mentioned with the option of the default setting to be false, but to be able to turn it on.  In Opera browser in the settings you can customize any shortcut with custom hotkeys.  I know this is a separate issue but if this was incorporated then this would be taken care of.

**Comment by luixxiul** [comment] 2017-12-03 09:11
Closing as duplicate of #6156

**Closed by luixxiul** 2017-12-03 09:11 UTC
