### ISSUE TITLE
Mouse integrated back and forth button

### ISSUE THREAD

**Issue by AtjonTV** [brave/browser-laptop#13880] opened 2018-04-20 20:09 UTC
### Description
I am using the [ET D-09](https://www.aliexpress.com/item/ET-Brand-D-09-2-4Ghz-Wireless-Mouse-1600-CPI-6-Buttons-Computer-Mouse-For-Laptops/2017090370.html), its a mouse with a integrated back and forth button. When I try to use either of them in Brave its not working. I used to use them in Vivaldi to make site navigation quicker. This is a feature I would love to see in Brave.

### Brave Version

**about:brave info:**
 
>Brave: 0.22.22 
V8: 6.5.254.41 
rev: 63033109963be0a995b3d1ed9723870beeb191c4 
Muon: 5.1.2 
OS Release: 4.13.0-38-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Comment by eljuno** [comment] 2018-04-20 20:27
Dupe of #3101?

**Comment by bsclifton** [comment] 2018-04-26 18:16
@eljuno yup- this is a dupe.  Closing 😄

**Closed by bsclifton** 2018-04-26 18:16 UTC
