### ISSUE TITLE
Pinned tabs are opened in "New Window"

### ISSUE THREAD

**Issue by jason-azze** [brave/browser-laptop#6255] opened 2016-12-16 14:22 UTC
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
When opening a New Window, the new window includes all of my (many) pinned tabs. This is unexpected behavior. 

**Expected behavior:**
New window should be "bare", without pinned tabs. The user's intention is probably to create a new window to be dragged somewhere. It's unlikely that the user wants a complete replica of the session from which the new window was spawned. Also, Chrome and Firefox spawn bare new windows. :-)

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.04

- Brave Version:
Brave	0.12.15
Muon	1.4.31
libchromiumcontent	53.0.2785.143
V8	5.3.332.47
Node.js	6.5.0
Update Channel	dev
os.platform	linux
os.release	4.4.0-53-generic
os.arch	x64

- Steps to reproduce:
    1. Start with a session with one or more pinned tabs.
    2. Select "New Window" from the File menu.
    3. The new window opens along with all pinned tabs.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment] 2016-12-16 18:30
Related: #5800 (Add pref to allow Pinned tabs to function in single-window mode)

**Comment by bsclifton** [comment] 2017-02-10 23:35
Closing as a dupe of https://github.com/brave/browser-laptop/issues/5800

(preference is the solution, since this behavior is intended)

**Closed by bsclifton** 2017-02-10 23:35 UTC
Labels: feature/pinned-tabs, parity, suggestion
