### ISSUE TITLE
Maybe Bug: Can't Close Download Bar with an Active Download

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#13232] opened 2018-02-21 19:48 UTC
### Description
Originally reported on community https://community.brave.com/t/download-bar-wont-disappear-hide-from-the-bottom-of-the-screen/12056?u=eljuno

Users can't close/hide the download bar if there's still an active download. See record. :) 
It can be closed if the download's finish.

### Steps to Reproduce

  1. Try to download large file or download Brave from brave.com
  2. When downloading, try to close the download bar by clicking the X button.
  3. When downloading, try to hide the download bar by right-clicking > Hide the download bar.

**Actual result:**
Download bar closed and reappear.

![download-bar](https://user-images.githubusercontent.com/25360853/36501679-52c50698-177a-11e8-9181-20a48ca6b33b.gif)

**Expected result:**
Download bar closed as user expected.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.42
-- | --
V8 | 6.4.388.41
rev | 096c7cb
Muon | 4.8.2
OS Release | 6.3.9600
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
Yes. Also can reproduced on Beta version.

### Additional Information
NDA. cc @bsclifton

**Comment by bsclifton** [comment] 2018-02-21 19:48
this was fixed by a contributor recently... will try to find the original issue

**Comment by bsclifton** [comment] 2018-02-21 19:50
This is a dupe of https://github.com/brave/browser-laptop/issues/11923

Fixed by @jasonrsadler with https://github.com/brave/browser-laptop/pull/13040; slated for our 0.23.x release 😄

**Closed by bsclifton** 2018-02-21 19:50 UTC

**Comment by eljuno** [comment] 2018-02-21 19:59
Thanks @bsclifton . My bad. Likely I missed this when searching for existing issue. :)
