### ISSUE TITLE
Update Favicons doesnt work as expected

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4339] opened 2016-09-27 22:38 UTC
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Update Favicons works as expected

**Expected behavior:**
Favicons should be updated for both Browser import and HTML File import

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.04

- Brave Version:
0.12.3 dev-RC1

- Steps to reproduce:
    1. User created bookmarks doesn't show favicon shows title as well when show only fav icons is enabled
    2. Other existing boookmarks doesn't show icons either under nested folders or just bookmark items
    3. Imported bookmarks from HTML file doesn't show icons.

- Screenshot if needed:
![bookmarks](https://cloud.githubusercontent.com/assets/17010094/18894258/da1661a0-8509-11e6-83ca-9e5b88a459a1.gif)

- Any related issues:
#4270 #4271 

cc: @darkdh

**Comment by darkdh** [comment] 2016-09-28 03:35
I thought the bookmarks under folders will also show title is intended when `show only favicon` is on. @bsclifton ?

**Comment by bsclifton** [comment] 2016-09-28 05:21
@darkdh that is correct- it was originally implemented with only top level bookmarks hiding the titles. Now, top level folders hide the titles. Any child item should be showing the titles though

**Comment by bbondy** [comment] 2016-09-28 13:39
This is moved into 0.12.4 btw.  Users can re-import to fix.

**Comment by alexwykoff** [comment] 2016-10-03 05:41
Confirmed still an issue in 0.12.3 RC6. Re-importing did not fix the favicons.
![bookmarks_import_favicons](https://cloud.githubusercontent.com/assets/1434040/19028477/0ac78aa4-896f-11e6-96fd-45a29ea8bb92.gif)

**Comment by darkdh** [comment] 2016-10-03 11:26
because https://github.com/brave/browser-laptop/pull/4345 is not merged.

**Comment by srirambv** [comment] 2016-10-05 05:42
Reopening the issue. Website Favicons not loaded but shows an empty file icon for all bookmarks which makes it impossible to know what bookmark is for which site if only favicons is set.
0.12.4 Preview1 

![image](https://cloud.githubusercontent.com/assets/17010094/19102150/7184336e-8aeb-11e6-9582-02b5fa7dabcb.png)

**Comment by darkdh** [comment] 2016-10-05 15:50
@srirambv https://github.com/brave/electron/compare/v1.4.10...master the electron changes didn't be include in electron release for preview 1 and 2. Please hold it until RC 1

**Comment by bbondy** [comment] 2016-10-06 00:39
Closing but please test it after electron changes higher than 1.4.10.

**Closed by bbondy** 2016-10-06 00:39 UTC
Labels: feature/bookmarks, feature/importer, regression
