### ISSUE TITLE
GIFs on Twitter may cause audio indicator to flicker

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6488] opened 2016-12-31 06:58 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Some sites that display GIFs cause an audio indicator to be rendered in the tab. If the GIF is short enough, the indicator may turn on and off rapidly, causing the title text to jerk left and right.

**Expected behavior:**
Short GIFs should don't cause the user's attention to be diverted to the tab in such a jarring fashion.

**Platform (Win7, 8, 10? macOS? Linux distro?):** Windows 10, macOS

**Brave Version (revision SHA):** 0.13.0

**Steps to reproduce:**
1. Navigate to https://twitter.com/ThePracticalDev/status/814551019522785280
2. Click the blue _play_ button
3. Observe tab contents as GIF plays

**Screenshot if needed:**
![tab-indicators](https://cloud.githubusercontent.com/assets/815158/21576385/806f6c0e-cef2-11e6-8719-fdafc146bda1.gif)

**Comment by bsclifton** [comment] 2016-12-31 09:42
Closing- I think this is a duplicate of https://github.com/brave/browser-laptop/issues/257 

Please re-open if I'm mistaken

**Closed by bsclifton** 2016-12-31 09:42 UTC
Labels: bug, design, duplicate
