### ISSUE TITLE
htpasswd ("Authentication required") doesn't popup

### ISSUE THREAD

**Issue by klanjabrik** [brave/browser-laptop#920] opened 2016-02-26 04:35 UTC
401 Authorization Required page comes because there is no htpasswd popup. ![screen shot 2016-02-26 at 11 28 21 am](https://cloud.githubusercontent.com/assets/403877/13343151/27d37568-dc7c-11e5-95cc-bf26f2fef77f.png)

OS X Yosemite 10.10

**Comment by weems** [comment] 2016-02-26 06:04
What is the URL to reproduce?

**Comment by klanjabrik** [comment] 2016-02-26 06:07
@weems hi, i'm sorry i can't provide you the URL. I'm using `https://`.

**Comment by psimyn** [comment] 2016-02-26 11:59
Is this for basic auth @klanjabrik ?

I think it's a duplicate of https://github.com/brave/browser-laptop/issues/370

**Closed** 2016-02-29 04:45 UTC

**Comment by klanjabrik** [comment] 2016-02-29 04:46
@psimyn yes, it is.
