### ISSUE TITLE
Tiny Cursor on HiDPI Screen

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#9772] opened 2017-06-29 10:08 UTC
On Elementary OS (which is based on Ubuntu 16.04) and 4K screen, whenever I have the cursor within the browser window, it becomes tiny. When I move the cursor outside of the window, it goes back to normal properly scaled size. Is there any way to fix this? Many thanks!

**Comment by luixxiul** [comment] 2017-07-01 03:21
thanks for the report. we will dig in the issue.

**Comment by DougBeney** [comment] 2017-09-30 18:44
I'm experiencing the same issue on Solus Linux using a HIDPI/Retina Macbook Pro.

I installed via the Snap package.

**Comment by dearlygparted** [comment] 2017-11-08 19:54
The cursor is tiny (and ugly) on a standard 1920x1080 display as well. I'm also using the Brave Snap package on Solus. I think the problem is that the following directory is empty:

/snap/brave/current/usr/share/icons/default 

Normally, it would have an "index.theme" file:

/usr/share/icons/default/index.theme

Where index.theme, on Solus, contains:

```
[Icon Theme]
Inherits=breeze-cursor
```

The Brave Snap lacks that file and is defaulting to a really ugly and really tiny cursor theme.

**Comment by ryanrms** [comment] 2018-02-22 06:37
I'm experiencing the same issue on Ubuntu Budgie 17.04.1 installed via snap package.  In Chromium, the cursor icon theme is as expected, but in Brave it appears to be using some sort of default X cursor.

**Comment by albergh** [comment] 2018-06-01 12:03
Just installed it via snap and have the same issue, KDE Neon (Ubuntu 16.04) under Xorg

**Comment by echosa** [comment] 2018-06-29 19:22
Same issue in Pop!_OS using GNOME. 

![brave-small-mouse](https://user-images.githubusercontent.com/133786/42110742-dd3a6408-7ba7-11e8-9e7a-a1a32ff3af01.gif)

**Comment by timberfake** [comment] 2018-12-22 16:16
Having the same issue. Installed via snap on Manjaro Linux 18.

**Comment by david0178418** [comment] 2019-01-03 14:37
Actually, I forgot to mention that I've also installed via snap (on KDE neon).

**Comment by bsclifton** [comment] 2019-01-03 16:32
Closing as this version of Brave is deprecated

@posix4e did a lot of work and got the new version of Brave working with Snap - take a peek here:
https://github.com/brave/brave-browser/issues/1007

Comments in that issue definitely appreciated 😄

**Closed by bsclifton** 2019-01-03 16:32 UTC
Labels: bug/dpi/monitor
