### ISSUE TITLE
unable to view PDFs on c66 with clean profile

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13840] opened 2018-04-16 16:09 UTC
### Description
PDFs don't display within Brave when using a clean profile.

### Steps to Reproduce

  1. Launch 0.22.663 with a clean profile
  2. Navigate to a PDF (such as http://www.pdf995.com/samples/pdf.pdf )
  3. You will see an error.
  4. Navigate to about:preferences#extensions
  5. PDF Viewer is not listed.

**Actual result:**

Unable to view a PDF
![c66-pdf](https://user-images.githubusercontent.com/28145373/38821495-a24b136a-416e-11e8-88fc-eb24a313910e.gif)

**Expected result:**
Should be able to view a PDF.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.22.663
V8 | 6.6.346.23
rev | b35e0b5
Muon | 5.2.2
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.106

**Reproducible on current live release:**
no

### Additional Information
Reproduced by @btlechowski on Win
If you use a profile where PDF was enabled prior to c66, this issue does not occur
Probably related to https://github.com/brave/browser-laptop/issues/13837 and https://github.com/brave/browser-laptop/issues/13838

**Comment by ltilve** [comment] 2018-04-16 17:03
The issue is also reproducible on Linux, also when removing the existing profile.

**Comment by darkdh** [comment] 2018-04-16 17:52
fixed in muon 5.2.3

**Closed by darkdh** 2018-04-16 17:52 UTC
Labels: bug, cr66, plugin/pdfjs, release/blocking

**Comment by btlechowski** [comment] 2018-04-19 14:12
Verified Ubuntu 17.10
Version 0.22.664
Muon 5.2.4
