### ISSUE TITLE
Middle click to close pinned tab causes other tabs to look pinned until mouse over

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12379] opened 2017-12-22 11:26 UTC
### Description
Middle click to close pinned tab causes other tabs to look pinned until mouse over

### Steps to Reproduce
  1. Clean install 0.20.9
  2. Open a bunch of sites
  3. Pin one of the tabs
  4. Right click, close on pin tab, closes correctly other tabs aren't affected
  5. Pin another tab 
  6. Middle click on the pinned tab, pinned tab closes but other tabs looks pinned, mouse out from tabs bar all other tabs snap back to original size

**Actual result:**
![4063](https://user-images.githubusercontent.com/17010094/34296442-c23e52c2-e70a-11e7-8669-783c02e39f4e.gif)

**Expected result:**
Other tabs should not be affected how the pinned tabs are closed

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.9
-- | --
V8 | 6.3.292.48
rev | b5aec10
Muon | 4.5.31
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 63.0.3239.108

**Reproducible on current live release:**
No

### Additional Information
Found while testing #4063

**Comment by cezaraugusto** [comment] 2017-12-26 21:39
closing as duplicate of #11825

**Closed by cezaraugusto** 2017-12-26 21:39 UTC
Labels: 0.20.x, bug, feature/pinned-tabs, feature/tabsbar, regression, release-notes/exclude
