### ISSUE TITLE
Tabs don't resize with window

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#100] opened 2015-12-26 17:24 UTC
## Test plan

https://github.com/brave/browser-laptop/pull/6900#issue-203781822

<hr>

Steps to reproduce:
1. Open Brave and maximize it
2. Keep creating tabs until you reach 6
3. Tabs will finally resize for the window

Not sure what the correct behavior should be here with a fixed number of tabs. Currently they only expand to fit the window size when there are 6 in the tab group. Maybe they should always fit the window width and get smaller until they max out at 6? @bradleyrichter ?

**Comment by psimyn** [comment] 2016-02-14 02:14
Can alternatively set tabArea maxWidth programmatically with `calc()` - does mean that on narrow viewports with only one or two tabs they look very narrow though


```
style={{maxWidth: `calc(${100 / this.props.tabsPerTabPage}% - ${addTabButtonWidth / this.props.tabsPerTabPage}px)`}}
```

![tabstretch](https://cloud.githubusercontent.com/assets/1731922/13031299/db8476a2-d31c-11e5-83e6-b3287fcb59e5.gif)

**Comment by bridiver** [comment] 2016-02-14 02:16
@bradleyrichter and I can up with a formula to keep them from growing too large or too small, we just need to implement it. Maybe he can post the details here?

**Comment by cezaraugusto** [comment] 2016-06-15 15:27
I'm late here but the UI seems good for me at this moment and the conversation here hadn't been concluded. Can we close it?

**Comment by bsclifton** [comment] 2016-06-29 14:48
I've confirmed this still is an issue and it does seem a bit weird.

STR that make it obvious:
1) Maximize window
2) Go to prefs; set Tabs => Tabs per tab page to 6
3) Keep hitting the + next to tabs until you have 5 tabs
4) Hit the + one more time- notice that all the tabs resize themselves, becoming much wider
5) Close the 6th tab- notice all the tabs shrink back to their previous size

This problem seems to be masked because the browser (at least in my case) defaults to 10 tabs per page. That is enough tabs that it does properly fill out the window and it's not noticeable.

@bradleyrichter: are you happy with the current behavior?

**Comment by bradleyrichter** [comment] 2016-06-29 16:47
The new 10-tab default reduced the problem as you said @bsclifton but ideally we would implement a solution. I am game for trying @psimyn 's suggestion above because we are already doing this when reducing the window width.

**Comment by bridiver** [comment] 2016-06-29 17:37
@bradleyrichter and I came up with a good sizing algorithm, but I don't think it ever got implemented. Do you still have the notes?

**Comment by bridiver** [comment] 2016-06-29 17:40
I'm not sure if @psimyn will always resize correctly because it doesn't appear to leave space for an extra tab at the end when you have less than the maximum number of tabs in a page

**Comment by bradleyrichter** [comment] 2016-06-29 17:59
here are those notes:

[newtab_scaling_approach_desktop.pdf](https://github.com/brave/browser-laptop/files/339878/newtab_scaling_approach_desktop.pdf)

**Comment by bridiver** [comment] 2016-06-29 18:01
I know we came up with an actual algorithm for it. Is that all you could find?

**Comment by bradleyrichter** [comment] 2016-06-29 18:07
That was the visual explanation. I don't recall an algorithm. But I am not seeing a problem with Simon's approach based on the video snip.

**Comment by bridiver** [comment] 2016-06-29 18:14
I guess it does look like it handles the last tab space, but there was an issue with both very small windows and very large windows. We tried a similar simple sizing algorithm and it didn't handle those cases very well.

**Comment by bridiver** [comment] 2016-06-29 18:16
the large window is probably not as much of an issue with a default of 10 tabs

**Comment by cezaraugusto** [comment] 2017-02-06 13:38
ok based on previous comments I don't think we have an issue for large screens anymore, and tabArea has a max-width of 184px currently.

I referenced this issue on #6900, which addresses small screens (or when you have a lot of tabs). 

If someone think it's still an issue LMK and I'll revoke auto-closing keyword from there.

**Closed** 2017-02-07 05:04 UTC
Labels: feature/tabsbar, info-needed
