### ISSUE TITLE
Pinned tabs can't change host url

### ISSUE THREAD

**Issue by shortstuffsushi** [brave/browser-laptop#8998] opened 2017-05-22 14:35 UTC
I've searched through the issues and this seems not to have been covered yet. It's related to #8711, because each time I start my browser I have three zombie Gmail windows that I can't get rid of. I want to re-use those pins, but can't change their urls without Brave creating new tabs. Or rather, I can't seem to change the host domain I'm on -- if I stay on the same domain, no new tab, it's just different domains that trigger the new tab. Perhaps this is intentional, but I found it confusing.

OS: Windows
Commit: af7ef42
Screenshot:
![new-tab](https://cloud.githubusercontent.com/assets/1016147/26313771/860eae82-3ed1-11e7-9983-f07e0d35ca46.gif)

**Comment by srirambv** [comment] 2017-05-22 15:16
That's the expected behaviour for pinned tabs. As long as the domain remains same you can navigate on the pinned tab. Change in domain causes it to open a new tab. 

Closing the issue but can continue conversation on the same thread and reopen if required

**Closed by srirambv** 2017-05-22 15:16 UTC

**Comment by shortstuffsushi** [comment] 2017-05-22 15:28
Hmm, could you explain why this decision was made? Does the same behavior trigger when navigating within that tab? That in particular could be really jarring as a user. It seems Brave takes a different stance than most browsers about what a pinned tab really *is*, do you guys have any explanation / documentation around that for users?

**Comment by srirambv** [comment] 2017-05-23 07:45
cc: @bbondy @bsclifton

**Comment by srirambv** [comment] 2017-05-23 18:36
> Does the same behavior trigger when navigating within that tab? That in particular could be really jarring as a user. 

This is not the same behavior when navigating within a normal/session/private tab. These tabs can navigate across different domains but pinned tabs only navigate on the single domain. Different domain on the pinned tab triggers a new tab.

**Comment by shortstuffsushi** [comment] 2017-05-23 19:26
Right, that's what I'm arguing is confusing.

As a user, I expect a pinned tab to behave the same as any other tab in the window -- when I navigate within it, I expect to stay in the same tab, when I right click, I expect to be able to close it, when I close the window, I expect it to go away.

These conditions are not currently the case, and I'm confused as to why. Could someone (you or the CC'd authors) comment on why pinned tabs are considered different? It seems to have been a design choice, so I'm assuming there is some reasoning behind it.

**Comment by shortstuffsushi** [comment] 2017-05-23 19:27
> Does the same behavior trigger when navigating within that tab? That in particular could be really jarring as a user.

To clarify, what I meant was -- if you click a link in a pinned tab that would take you to another domain, are you then popped out into a new tab?

**Comment by shortstuffsushi** [comment] 2017-05-23 19:29
For what it's worth, I just tried it. It seems that navigating within a tab via links will *not* create a new a tab. It's only navigation via the URL bar that will create a new tab.

**Comment by bsclifton** [comment] 2017-06-04 22:17
@shortstuffsushi like you found, entering into URL bar is supposed to open a new tab.  Also, clicking a link which is on a different domain within a pinned tab is supposed to cause the link to open in a new tab too.  There are cases where this doesn't work, which are captured by bug https://github.com/brave/browser-laptop/issues/569

Leaving issue as closed since it's working as designed.  cc: @bradleyrichter for any additional comments 😄

**Comment by shortstuffsushi** [comment] 2017-06-04 23:23
Thanks for the previous issue link, which explains the confusing "click doesn't trigger tab" behavior I was seeing. Could someone explain why this behavior is the default though? I'd rather control my own new tab triggering rather than the browser deciding when to launch new ones for me (excluding things like window.open type links). 

As mentioned above, the way you guys treat pinned tabs is weird to me, I'd rather they behave like any other tab except that they're located in the pinned area of the browser bad -- that's it. As they exist now, they're like mini bookmarks that are loaded in every window, every time and behave unlike other tabs in their navigation behavior, etc.

As a previous Chrome user, this is weird. Is this something that was pulled across from Firefox?
