### ISSUE TITLE
Refresh, forward, and back shortcuts aren't working

### ISSUE THREAD

**Issue by MarioMaster100** [brave/browser-laptop#7509] opened 2017-03-06 02:36 UTC
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
I press F5 and nothing happens, alt + left and nothing happens, and alt + right and nothing happens.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10
- Brave Version (revision SHA):
 
Brave: 0.13.5 
rev: 1db81cb18b6919535792bb7e198ab87276bd67ea 
Muon: 2.56.8 
libchromiumcontent: 56.0.2924.87 
V8: 5.6.326.50 
Node.js: 7.4.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64
- Steps to reproduce:
    1.Press F5
    2.Press alt + left
    3.Press alt + right
    
- Actual result:
Nothing happens
- Expected result:
It should refresh the page, go back, or go forward.
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
As far as I know.
- Is this an issue in the currently released version?
Yes.
- Can this issue be consistently reproduced?
Yes.
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment] 2017-03-06 17:48
@MarioMaster100: Thanks for the report. I'll mark this as a duplicate of #7491. You can continue to track this bug in that issue.

**Closed by Liunkae** 2017-03-06 17:48 UTC
