### ISSUE TITLE
Set the file type filter when presenting a save dialog

### ISSUE THREAD

**Issue by tofuTheCat** [brave/browser-laptop#10050] opened 2017-07-19 03:03 UTC
- Describe the issue you encountered:

.tmp file of a download is visible when prompted save location

- Platform (Win7, 8, 10? macOS? Linux distro?):

Win 8.1

- Brave Version (revision SHA):

2d2ee2f

- Steps to reproduce:
    1. Downloading win.rar
    2. Downloading atom text editor
    3. Downloading anything  even saving a link as
    
- Actual result:

a TMP file is visible in the Save As screen

- Expected result:

no TMP file to be visible

- Screenshot if needed:

![tmp file](https://user-images.githubusercontent.com/28712392/28348838-3f3cb8aa-6c0d-11e7-9f42-d94300f2e64c.png)

**Comment by bsclifton** [comment] 2017-07-19 07:05
Expected result:
![screen shot 2017-07-19 at 12 02 40 am](https://user-images.githubusercontent.com/4733304/28354743-e128f270-6c15-11e7-833d-1a558a2e41e8.png)

This is a screenshot from Chrome. Notice it has a filter for `.exe` called `Application`

**Comment by bsclifton** [comment] 2017-09-08 18:39
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/8096

**Closed by bsclifton** 2017-09-08 18:39 UTC
Labels: duplicate, OS/Windows
