### ISSUE TITLE
Uploading images on Github "New Issue" fails

### ISSUE THREAD

**Issue by dignifiedquire** [brave/browser-laptop#6925] opened 2017-01-30 16:12 UTC
- Describe the issue you encountered: When either dragging and dropping or selecting an image to be uploaded to a github issue, there will be an error from Github saying that it was not able to upload the image.
- Platform (Win7, 8, 10? macOS? Linux distro?): `macOS 10.12.3`
- Brave Version (revision SHA): `719b6f89fc81ae65c4162cfcb4daba17423897ef` (`master`)
- Steps to reproduce:
    1. Visit https://github.com/brave/browser-laptop/issues/new
    2. Drag and drop image into the issue field
    3. See error message appear
- Actual result: Image is not uploaded to github
- Expected result: Image is uploaded to github and shown in the issue comment
- Will the steps above reproduce in a fresh profile? Yes
- Can this issue be consistently reproduced? Yes
- Screenshot if needed:
<img width="733" alt="screen shot 2017-01-30 at 17 12 07" src="https://cloud.githubusercontent.com/assets/790842/22430661/42620f5e-e70f-11e6-8f7f-dfd5ccc11c8e.png">

**Comment by Liunkae** [comment] 2017-01-30 17:31
All three image upload options on GitHub work fine for me with Brave 0.13.0 on macOS 10.12.3.

**Comment by NejcZdovc** [comment] 2017-01-30 17:36
Everything works ok for me as well

**Comment by dignifiedquire** [comment] 2017-01-30 17:57
Is this working for you in `master` as well?

**Comment by NejcZdovc** [comment] 2017-01-30 18:00
![image](https://cloud.githubusercontent.com/assets/9574457/22434889/3f309896-e71e-11e6-8aa8-33df6bbe28f2.png)

I was testing it with a released version, because I use it every day and today I think I uploaded about 5-6 images. But I know that @bsclifton had some problems yesterday with image upload to github

**Comment by Liunkae** [comment] 2017-01-30 19:16
Works fine for me with a14fcdf.

**Comment by luixxiul** [comment] 2017-01-31 02:05
Do you enable any custom filters on about:adblock?

**Comment by dignifiedquire** [comment] 2017-01-31 10:29
I figured out where the issue is coming from. I had enabled `JPN: ABP Japanese filters (日本用フィルタ)`and disabling those fixes things.

**Comment by luixxiul** [comment] 2017-01-31 11:51
OK then I think it is okay to close this as a duplicate of #6883

**Closed by luixxiul** 2017-01-31 11:51 UTC
