### ISSUE TITLE
ENOENT Error when running npm test

### ISSUE THREAD

**Issue by irrationalRock** [brave/browser-laptop#13343] opened 2018-02-28 22:06 UTC
### Description

I am encountering multiple errors when running tests. They all seem to be related to being unable find a directory.

### Steps to Reproduce

  
  1. run `npm run watch-test`
  2.  then run `npm test` in another terminal
  3. It starts showing the error messages

**Actual result:**

It produces this error when running `npm test` : 
```
C:\Users\mquan\Downloads\Derp\browser-laptop>npm test

> brave@0.22.0 test C:\Users\mquan\Downloads\Derp\browser-laptop
> cross-env NODE_ENV=test mocha "test/**/*Test.js"



  about:adblock
    1) "before all" hook
    2) "after all" hook

  about:bookmarks
    page content
{ Error: ENOENT: no such file or directory, scandir 'C:\Users\mquan\AppData\Local\Temp\brave-test\1519852579619660'
    at Object.fs.readdirSync (fs.js:924:18)
    at rmDir (C:/Users/mquan/Downloads/Derp/browser-laptop/test/lib/brave.js:34:20)
    at Context.cleanup (C:/Users/mquan/Downloads/Derp/browser-laptop/test/lib/brave.js:1192:26)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\mquan\\AppData\\Local\\Temp\\brave-test\\1519852579619660' }
```
**Expected result:**
No errors 

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.22.0
V8 | 6.4.388.45
rev | 2ceda21
Muon | 5.0.6
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.167

### Additional Information

I'm using windows 10.

**Comment by bsclifton** [comment] 2018-04-12 17:07
Thanks for the report- all WebDriver automated tests on Windows are all failing ☹️ 

Closing this as a duplicate of https://github.com/brave/browser-laptop/issues/10618

**Closed by bsclifton** 2018-04-12 17:07 UTC
Labels: automated-tests, dev-setup
