### ISSUE TITLE
Autocomplete should return site's home page as first result

### ISSUE THREAD

**Issue by bbrown** [brave/browser-laptop#10662] opened 2017-08-25 15:52 UTC
- Did you search for similar issues before submitting this one? **YES**

- Describe the issue you encountered:

I start typing a URL of a frequently-visited site, MacRumors in my case, and the first result of the autocomplete in the URL bar is a specific page on that site instead of the home page. In all other browsers I've used, you can start typing the URL and hit return once the autocomplete suggestions come up. In Brave, I always end up on a particular page instead if I'm not careful.

Almost never would I expect a particular page I've visited in the past to come up as the first result. Maybe if I go to it frequently enough.

- Platform (Win7, 8, 10? macOS? Linux distro?): **Mac OS X Sierra**

- Brave Version (revision SHA): **36ae2ec**

- Steps to reproduce:
    1. Go to NY Times home page, like [here](https://www.nytimes.com/)
    2. Go to some specific NY Times article, like [this one](https://www.nytimes.com/2017/08/21/us/charlottesville-council-melee.html)
    3. Open a new tab
    4. Type 'nytimes' and see what the first option is
    
- Actual result: nytimes.com/2017/08/21/us/charlottesville-council-melee.html

- Expected result: nytimes.com

- Will the steps above reproduce in a fresh profile? If not what other info can be added? **PROBABLY**

- Is this an issue in the currently released version? **YES**

- Can this issue be consistently reproduced? **YES**

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by egferro** [comment] 2017-09-07 09:15
I experience the same problem and I have to say it is pretty annoying. I am a Windows user. Please fix this issue. Tnx EF.

**Comment by maurelian** [comment] 2017-09-07 14:35
This is quite strange and unintuitive behavior, it looks like this bug has crept back in: https://github.com/brave/browser-laptop/issues/6537

**Comment by LaurenWags** [comment] 2017-09-18 18:41
+1 from community: https://community.brave.com/t/strange-address-bar-suggestions/6572

**Comment by tbates** [comment] 2017-09-22 10:30
completion lists in the search box can be very useful. Brave's behaves differently, and less helpfully, than Safari or Chrome.

If the user types the beginning of a site they visit often, Brave offers long, complete urls to deep pages in those sites. But the USER is most often not interested in that, but instead wants to go to the homepage. This is nearly always the case for sites like FB, but also for most other site, like ebay or AMZN, or your local newspaper.

1. Enter the beginning of a favorite site: schol for scholar.google,com
EXPECTED: Brave offers scholar.google,com as a top completion followed by the last visited specific page. etc.
OBTAINED: Brave offers nothing but deep urls like  amzn.com/12389723487er872987yw89r79834789

 
Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: macOS 
OS Release: 17.0.0 
OS Architecture: x64

**Comment by luixxiul** [comment] 2017-09-22 12:03
+1 from https://github.com/brave/browser-laptop/issues/6537#issuecomment-331411430

**Comment by elleryfamilia** [comment] 2017-09-22 18:34
+1

**Comment by pongraczi** [comment] 2017-09-28 08:48
Same in linux, the current behaviour is very uneffective and demoralizing.
 
Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Linux 
OS Release: 4.11.0-14-lowlatency 
OS Architecture: x64

**Comment by bsclifton** [comment] 2017-09-28 17:42
I believe this is a duplicate of https://github.com/brave/browser-laptop/issues/11057 and will be fixed with the 0.19.x release (coming soon!).  You can already try out the latest beta (which has the fix) by downloading from https://github.com/brave/browser-laptop/releases

**Closed by bsclifton** 2017-09-28 17:42 UTC
Labels: feature/autocomplete, feature/URLbar, suggestion
