### ISSUE TITLE
Text ads on Google search result

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2538] opened 2016-07-17 07:42 UTC
**Describe the issue you encountered:** Text ads on a Google search result are neither replaced nor blocked. I am wondering if they should be.

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: 0.11.1 Beta1

- Steps to reproduce:
    1. Go to google.com
    2. Search for "Bookstore"

- Screenshot if needed:
<img width="817" alt="screenshot 2016-07-17 16 28 35" src="https://cloud.githubusercontent.com/assets/3362943/16899380/0440f928-4c3d-11e6-86dd-5175806f2f24.png">

**Comment by bbondy** [comment] 2016-07-18 03:40
This is a dupe of cosmectic filters.
https://github.com/brave/browser-laptop/issues/344

**Closed by bbondy** 2016-07-18 03:40 UTC
Labels: question
