### ISSUE TITLE
Can't access to riot.im website

### ISSUE THREAD

**Issue by benpro** [brave/browser-laptop#10685] opened 2017-08-28 07:49 UTC
- Did you search for similar issues before submitting this one?

Yes.

- Describe the issue you encountered:

Trying to load the page https://riot.im/app/#/room/#riot:matrix.org. The page doesn't load.

- Platform (Win7, 8, 10? macOS? Linux distro?):

```
Distributor ID: Debian                        
Description:    Debian GNU/Linux 9.1 (stretch)
Release:        9.1                           
Codename:       stretch                       
```

- Brave Version (revision SHA):

```

Name | Version
-- | --
Brave | 0.18.23
rev | 36ae2ec
Muon | 4.3.10
libchromiumcontent | 60.0.3112.90
V8 | 6.0.286.52
Node.js | 7.9.0
Update Channel | dev
OS Platform | Linux
OS Release | 4.9.0-3-amd64
OS Architecture | x64


```

- Steps to reproduce:
    * Go to https://riot.im/app/#/room/#riot:matrix.org
    
- Actual result:

    * The page doesn't load

- Expected result:

    * The page successfully load

**Comment by gnouts** [comment] 2017-08-28 14:52
I can confirm this under Windows 10 and Manjaro, both with 0.18.23 but issue is older and not related to brave version.
Shield down doesn't change anything.

**Comment by luixxiul** [comment] 2017-08-29 05:51
It is stuck on this line on Brave:

````
indexeddb-local-backend.js?79bc:193 Removing indexeddb instance: matrix-js-sdk:riot-web-sync
````

**Comment by maciozo** [comment] 2017-09-22 18:08
Just to confirm (and hopefully bump), I'm also getting this issue.

Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.10586 
OS Architecture: x64

**Comment by luixxiul** [comment] 2017-09-23 01:59
@jonathansampson is this issue related with API support or something?

**Comment by jdjkelly** [comment] 2017-10-22 15:26
Also seeing this - nothing in console


Name	Version
Brave	0.19.53
rev	e09025b
Muon	4.4.29
libchromiumcontent	61.0.3163.100
V8	6.1.534.41
Node.js	7.9.0
Update Channel	Release
OS Platform	Linux
OS Release	4.4.0-97-generic
OS Architecture	x64

Here's a dump of the console:

``` 
Initialised rageshake: See https://bugs.chromium.org/p/chromium/issues/detail?id=583193 to fix line numbers on Chrome.
rageshake.js:65 set language to en-us
index.js:218 GET https://riot.im/app/config.riot.im.json 404 (Not Found)
t @ index.js:218
e @ index.js:179
l @ index.js:193
(anonymous) @ index.js:270
r @ runtime.js:65
(anonymous) @ runtime.js:299
e.(anonymous function) @ runtime.js:117
o @ util.js:16
l._promiseFulfilled @ generators.js:97
i._settlePromise @ promise.js:574
i._settlePromise0 @ promise.js:614
i._settlePromises @ promise.js:693
r._drainQueue @ async.js:133
r._drainQueues @ async.js:143
drainQueues @ async.js:17
Promise resolved (async)
i @ schedule.js:18
r._queueTick @ async.js:152
a @ async.js:88
i._fulfill @ promise.js:640
i._resolveCallback @ promise.js:432
(anonymous) @ promise.js:484
(anonymous) @ languageHandler.js:263
l @ index.js:294
r @ index.js:244
XMLHttpRequest.send (async)
t @ index.js:218
e @ index.js:179
(anonymous) @ languageHandler.js:256
e._execute @ debuggability.js:303
i._resolveFromExecutor @ promise.js:483
i @ promise.js:79
h @ languageHandler.js:255
(anonymous) @ languageHandler.js:175
o @ util.js:16
i._settlePromiseFromHandler @ promise.js:512
i._settlePromise @ promise.js:569
i._settlePromise0 @ promise.js:614
i._settlePromises @ promise.js:693
r._drainQueue @ async.js:133
r._drainQueues @ async.js:143
drainQueues @ async.js:17
Promise resolved (async)
i @ schedule.js:18
r._queueTick @ async.js:152
a @ async.js:88
i._fulfill @ promise.js:640
i._resolveCallback @ promise.js:432
(anonymous) @ promise.js:484
(anonymous) @ languageHandler.js:263
l @ index.js:294
r @ index.js:244
XMLHttpRequest.send (async)
t @ index.js:218
e @ index.js:179
(anonymous) @ languageHandler.js:256
e._execute @ debuggability.js:303
i._resolveFromExecutor @ promise.js:483
i @ promise.js:79
h @ languageHandler.js:255
(anonymous) @ languageHandler.js:166
o @ util.js:16
i._settlePromiseFromHandler @ promise.js:512
i._settlePromise @ promise.js:569
i._settlePromise0 @ promise.js:614
i._settlePromises @ promise.js:693
r._drainQueue @ async.js:133
r._drainQueues @ async.js:143
drainQueues @ async.js:17
Promise resolved (async)
i @ schedule.js:18
r._queueTick @ async.js:152
a @ async.js:88
i._fulfill @ promise.js:640
i._resolveCallback @ promise.js:432
(anonymous) @ promise.js:484
(anonymous) @ languageHandler.js:248
l @ index.js:294
r @ index.js:244
XMLHttpRequest.send (async)
t @ index.js:218
e @ index.js:179
(anonymous) @ languageHandler.js:241
e._execute @ debuggability.js:303
i._resolveFromExecutor @ promise.js:483
i @ promise.js:79
m @ languageHandler.js:240
l @ languageHandler.js:151
(anonymous) @ index.js:340
r @ runtime.js:65
(anonymous) @ runtime.js:299
e.(anonymous function) @ runtime.js:117
o @ util.js:16
l._promiseFulfilled @ generators.js:97
(anonymous) @ generators.js:201
(anonymous) @ bundle.js:350
(anonymous) @ index.js:237
r @ runtime.js:65
(anonymous) @ runtime.js:299
e.(anonymous function) @ runtime.js:117
o @ util.js:16
l._promiseFulfilled @ generators.js:97
(anonymous) @ generators.js:201
(anonymous) @ bundle.js:303
(anonymous) @ index.js:346
(anonymous) @ bundle.js:563
t @ bootstrap b6299a7dfd5700ed5b52:49
(anonymous) @ bootstrap b6299a7dfd5700ed5b52:92
(anonymous) @ bootstrap b6299a7dfd5700ed5b52:92
rageshake.js:65 Vector starting at https://riot.im/app/
rageshake.js:65 No previous session found.
rageshake.js:65 Doing guest login on https://matrix.org
rageshake.js:65 Initialised anonymous analytics
rageshake.js:65 Registered as guest: @412659:matrix.org
rageshake.js:65 setLoggedIn: mxid: @412659:matrix.org deviceId: guest_device guest: true hs: https://matrix.org
rageshake.js:65 Removing indexeddb instance: matrix-js-sdk:crypto
rageshake.js:65 Removed indexeddb instance: matrix-js-sdk:crypto
rageshake.js:65 IndexedDB worker is ready
indexeddb-local-backend.js?79bc:193 Removing indexeddb instance: matrix-js-sdk:riot-web-sync

**Comment by jonathansampson** [comment] 2017-10-26 18:07
@jdjkelly Our indexeddb support should be on par with Chrome's. I am noticing that our devtools show the files being loaded over `webpack://`, which I don't see in Chrome. This could be nothing at all, or it could be a thread worth pulling. I know that we prevent indexeddb access from third-parties, so I'll have to look into whether or not there might be known issues with this particular case.

**Comment by NT7S** [comment] 2018-01-10 19:05
I see the same behavior here.

I'd love to be able to use Brave as my primary browser, but I currently cannot because I use riot.im for my work. A resolution to this soon would be extremely helpful, thanks.

**Comment by ptrwllrd** [comment] 2018-02-21 09:52
There seems to be a problem with IndexedDB. See [this issue](https://github.com/brave/browser-laptop/issues/12463).

**Comment by eljuno** [comment] 2018-02-27 19:32
+1 from community https://community.brave.com/t/my-main-chat-application-doesnt-load-up-debian-buster-brave-via-snap/17002?u=eljuno

**Comment by bsclifton** [comment] 2018-03-30 04:09
+1 from @danoctavian via https://github.com/brave/browser-laptop/issues/13653

**Comment by fkbenjamin** [comment] 2018-07-02 19:55
Also see the same behavior. Loading spinner spins indefinitely.

**Comment by bsclifton** [comment] 2018-07-06 18:38
Confirmed this is fixed with https://github.com/brave/muon/pull/629

**Closed by bsclifton** 2018-07-06 18:38 UTC
Labels: bug, webcompat

**Comment by srirambv** [comment] 2018-07-06 18:49
Verified on Windows 10 x64 using
* 0.23.31 - 3148ace
* Muon - `7.1.5`
* libchromiumcontent - `67.0.3396.103`

**Comment by jasonrsadler** [comment] 2018-07-06 20:22
Verified on XUbuntu 18.04 x64 using

- 0.23.31 - 3148ace
- Muon - `7.1.5`
- libchromiumcontent - `67.0.3396.103`
