### ISSUE TITLE
URL bar context menu shows Paste Without Formatting

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6268] opened 2016-12-16 21:47 UTC
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
URL bar context menu shows Paste Without Formatting

**Expected behavior:**
Paste without formatting should not be shown in right click context menu in URL bar

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.13.0 Preview 4

- Steps to reproduce:
    1. Right click on the URL bar to bring up the context menu
    2. Shows `Paste Without Formatting`
    3. If it is to be shown then `Without` to be changed to `without` to keep in line with `Paste and Search`

- Screenshot if needed:
Brave/Opera/Chrome/Firefox
![image](https://cloud.githubusercontent.com/assets/17010094/21279598/e342bd60-c3d8-11e6-8265-19c79ae0160e.png)

- Any related issues:

**Comment by bbondy** [comment] 2016-12-19 04:14
@srirambv was this present in 0.12?

**Comment by Liunkae** [comment] 2016-12-19 05:55
This is caused by my PR #6126 (commit 433e3c9). If you want, we could just revert/move the commit to 0.13.1 (which it was originally assigned for).

**Comment by bsclifton** [comment] 2016-12-19 06:59
@Liunkae thanks for helping identify the issue :smile: I think that's a reasonable approach; I'll go ahead and revert it and re-open the original issue

You can then submit another PR which further restricts where this menu item should be shown. I believe it should only be shown for input fields inside the content area

**Comment by bsclifton** [comment] 2016-12-19 07:11
PR https://github.com/brave/browser-laptop/pull/6126 has been reverted and issue https://github.com/brave/browser-laptop/issues/5822 is reopened and ready for you to check out again (for 0.13.1 timeframe), @Liunkae :smile: 

I'll go ahead and close this issue; I manually verified it's no longer showing up after the revert

**Closed by bsclifton** 2016-12-19 07:11 UTC
Labels: feature/URLbar
