### ISSUE TITLE
Gmail — Locked Out on Brave

### ISSUE THREAD

**Issue by GarrettS** [brave/browser-laptop#12237] opened 2017-12-10 03:44 UTC
I'm locked out of Google account on Brave on Desktop. Using the same account, Chrome and Safari on the same machine work. Gmail on iOS works

  1. Go to mail.google.com
  2. Click "SIGN IN"
  3. enter my email address
  4. click "Next"

**Actual result:**

> Google couldn't verify this account belongs to you.
> 
> Try again later or use Account Recovery for help.
> 

**Expected result:**
Proceed to password screen.

**Reproduces how often:**
100% reproducible. 

### Brave Version
0.19.105

**about:brave info:**
Brave | 0.19.105
-- | --
rev | 51f8ba5
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | macOS
OS Release | 17.3.0
OS Architecture | x64

**Reproducible on current live release:**

### Additional Information
Prior to this issue, I'd logged out of Gmail and then used Chrome to log into a sub gmail account on the same machine, but logged out again. Now, I cannot log into any Google service using Brave, shields up or down.

**Comment by bsclifton** [comment] 2017-12-12 05:21
@GarrettS did you import content from Chrome? We have a known issue where cookies might have a mismatch when importing (see https://github.com/brave/browser-laptop/issues/11401). You can try clearing cookies to see if that resolves the issue in the meantime

**Comment by bsclifton** [comment] 2018-01-08 06:29
Closing as there hasn't been an update. I suspect this is a duplicate of https://github.com/brave/browser-laptop/issues/11401

**Closed by bsclifton** 2018-01-08 06:29 UTC
Labels: webcompat
