### ISSUE TITLE
Custom adblocking not working

### ISSUE THREAD

**Issue by freebrowser1** [brave/browser-laptop#7928] opened 2017-03-28 08:36 UTC
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Custom adblock not working

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux, macOS

- Brave Version (revision SHA):
0.13.5

- Steps to reproduce, fill in under about:adblock => Custom filters

One per line, a filter is described in Adblock Plus filter syntax

nu.nl^
nu.nl
http://nu.nl
http://www.nu.nl
https://nu.nl
https://www.nu.nl
||nu.nl
||nu.nl^
    
- Actual result:
   Site still loads

- Expected result:
  Site should not load

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

**Comment by srirambv** [comment] 2017-03-28 09:11
Dupe of #6243. Closing in favour of #6243

**Closed by srirambv** 2017-03-28 09:11 UTC
