### ISSUE TITLE
Import bookmark dropdown doesn't list strings properly

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6561] opened 2017-01-06 21:39 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Import bookmark dropdown is messed up 

**Expected behavior:**
Should show the drop down properly

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Name	Version
Brave	0.13.0
rev	0c7a64d

- Steps to reproduce:
    1. Launch Brave from command prompt with `brave --high-dpi-support=1 --force-device-scale-factor=1`
    2. Click on import browser data 
    3. Drop down list is messed up

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/21733749/0493d668-d458-11e6-9fc0-72413536a7eb.png)

- Any related issues:
cc: @bsclifton

**Comment by bbondy** [comment] 2017-01-08 13:58
Maybe a dupe of https://github.com/brave/browser-laptop/issues/5931 ?

**Comment by darkdh** [comment] 2017-01-09 04:40
I think @srirambv meant the width of dropdown.

**Comment by luixxiul** [comment] 2017-01-09 09:32
Though is it because that no browser is listed there?

**Comment by srirambv** [comment] 2017-01-09 11:14
@luixxiul  Even though the size of the dropdown is not right I am still able to select the options and import data.

**Comment by NejcZdovc** [comment] 2017-01-09 11:15
@srirambv can you paste html of this select element?

**Comment by srirambv** [comment] 2017-01-09 12:19
@NejcZdovc Here's the HTML for the import modal 
![image](https://cloud.githubusercontent.com/assets/17010094/21766356/cdf78b30-d665-11e6-81f7-0263a4adee11.png)

**Comment by luixxiul** [comment] 2017-01-09 14:11
so `Chrome Person 1` should have been displayed

**Comment by NejcZdovc** [comment] 2017-01-09 14:16
AFAIK there shouldn't be empty options and yes `Chrome Person 1` should be displayed.

**Comment by darkdh** [comment] 2017-01-09 14:23
empty option is the issue of https://github.com/brave/browser-laptop/issues/5931

**Comment by bsclifton** [comment] 2017-01-13 01:30
With both ICU and display fixes in place, we should be able to retest this soon :smile:

**Comment by darkdh** [comment] 2017-01-15 17:00
It looks like this after https://github.com/brave/muon/commit/fb893558261f095c695fdc43cee4a7e2239711f9 landed
<img width="930" alt="screen shot 2017-01-16 at 00 58 19" src="https://cloud.githubusercontent.com/assets/11330831/21964434/08cc247a-db87-11e6-857b-0ad9a4d5282b.png">

**Comment by bbondy** [comment] 2017-01-15 19:25
but you said you could reproduce with a packaged build locally right?

**Closed** 2017-01-15 22:55 UTC
Labels: bug, feature/importer, OS/Windows, release-notes/exclude, release/blocking

**Comment by bbondy** [comment] 2017-01-15 23:00
Fix will be in Preview9

**Comment by luixxiul** [comment] 2017-01-16 18:48
Test plan:

Launch Brave from command prompt with brave --high-dpi-support=1 --force-device-scale-factor=1
Click on import browser data
Drop down list is NOT messed up

**Comment by luixxiul** [comment] 2017-01-21 05:38
Removed `OS/Windows` as it was not confirmed that the issue was specific to Windows
