### ISSUE TITLE
Display zoom level while zooming with keyboard shortcuts

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10219] opened 2017-08-01 03:29 UTC
**Describe the issue you encountered:**  https://github.com/brave/browser-laptop/issues/10201#issuecomment-319251693 by @haflg19
> the user should probably recieve some indication of what percentage zoom they are at (ie. 70%, 90%, 110%, 200%, etc...), like every other browser displays.

+1 from me.

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version (revision SHA): master branch

- Steps to reproduce:
    1. Zoom in/out with keyboard shortcuts
    
- Actual result: Nothing is displayed which indicates the zoom percentage.

- Expected result: a tooltip should be displayed

- Any related issues:

**Comment by Liunkae** [comment] 2017-08-01 05:04
Duplicate of #1623.

**Closed by Liunkae** 2017-08-01 05:04 UTC
Labels: suggestion

**Comment by luixxiul** [comment] 2017-08-01 05:09
nice find, thanks
