### ISSUE TITLE
OSX Keyboard Shortcut for Emoji Doesn't Support

### ISSUE THREAD

**Issue by lonormaly** [brave/browser-laptop#14336] opened 2018-06-05 17:40 UTC
### Description
For OSX users the shortcut Command + Control + Spacebar to open the emoji keyboard doesn't seem to work.

### Steps to Reproduce
  1. Open Facebook and create new post
  2. On the text box press Command + Control + Spacebar

**Actual result:**
The Emoji keyboard should pop (like in Chrome)

![image](https://user-images.githubusercontent.com/3742919/40992853-99b4b6b6-6900-11e8-819a-1683cf34ac9a.png)

**Expected result:**
Nothing happens

**Reproduces how often:**
Constantly

### Brave Version

**about:brave info:**

 
Brave: 0.22.727 
V8: 6.6.346.32 
rev: 2c94bbad00d70b87328f04574725979960e18f9f 
Muon: 6.0.12 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Reproducible on current live release:**

**Comment by Liunkae** [comment] 2018-06-05 20:19
Duplicate of #13400.

**Comment by Liunkae** [comment] 2018-06-05 20:20
Duplicate of #13151

**Comment by Liunkae** [comment] 2018-06-05 20:21
Duplicate of #13151

**Closed** 2018-06-05 23:31 UTC
Labels: duplicate
