### ISSUE TITLE
entire Brave UI becomes unresponsive

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#10436] opened 2017-08-11 16:17 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Detaching/Attaching tabs right after Brave has been installed might cause the entire UI to become unresponsive. When this happens, Brave is unusable and needs to be closed using either the Task Manager or the Taskbar under Windows. When clicking on "Print" or "Find in page" via the menu, you'll receive console errors which are outlined under the screenshot section of the bug.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64 Build: 10.0.15063 (can't check other OS's right now as MBP being repaired)

- Brave Version (revision SHA):

Brave | 0.18.14 - Reproduced
rev | ad92d029e184c4cff01b2e9f4916725ba675e3c8
Muon | 4.3.6
libchromiumcontent | 60.0.3112.78

Brave | 0.18.22 - Reproduced
rev | d850e287ace296e2c62e28ba2979cf172e41cc45
Muon | 4.3.9
libchromiumcontent | 60.0.3112.90

- Steps to reproduce: (_this needs to be done fairly quickly_)
    1. Launch a clean install of Brave (either 0.18.14 or 0.18.22)
    2. Close the about:welcome tab
    3. Load duckduckgo.com within the remaining about:newtab
    4. Open a new tab using the "+" button and load about:preferences
    5. Detach the about:preferences tab into it's own separate window
    6. Quickly attach the about:preferences back into the original window where duckduckgo.com is still opened

You'll notice that the entire UI becomes unresponsive.
    
- Actual result:
The entire Brave UI becomes completely unresponsive. Basically bricks the browser.

- Expected result:
The Brave UI should never become unresponsive.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes, 100% reproducible using Brave 0.18.14 | rev: ad92d029e184c4cff01b2e9f4916725ba675e3c8 (currently live)

- Can this issue be consistently reproduced?
Yes, 100% reproducible with both 0.18.14 & 0.18.22 using the above STR.

- Screenshot if needed:

**_Example of the issue occurring:_**

![uifrozen](https://user-images.githubusercontent.com/2602313/29220481-291a9f54-7e89-11e7-94ad-a87773688279.gif)

**_Error message when attempting to select "Print" or "Find on Page" when the UI is unresponsive:_**

![error](https://user-images.githubusercontent.com/2602313/29220566-6d251670-7e89-11e7-82ef-fc9456b3e6ae.PNG)

**Comment by LaurenWags** [comment] 2017-08-11 16:30
Could not repro on MacOS. 
![10436](https://user-images.githubusercontent.com/28145373/29222521-c73d3a28-7e90-11e7-8a65-026346a8783a.gif)

**Comment by LaurenWags** [comment] 2017-08-11 16:55
On Win10 VM, didn't repro exactly. Sometimes this worked without any problems, and twice the tab I re-attached was bricked, but other tabs and the 3 dots menu worked fine.

**Comment by kjozwiak** [comment] 2017-08-11 17:19
I managed to reproduce the same issue on two different Win 10 machines that I remote accessed. I'll try getting a VM running on my desktop once I get back. I'll add more info once I've investigated further. Unless one of the developers manages to reproduce this in the meantime via a VM/physical machine.

**Comment by LaurenWags** [comment] 2017-08-11 20:44
+1 from community using 0.18.14: https://community.brave.com/t/tab-ui-becomes-completely-unresponsive-when-detaching-and-reattaching-tab/5631

**Comment by 7dskei** [comment] 2017-08-12 00:57
I've seen this issue as well.

Brave | 0.18.14
rev | ad92d02
Muon | 4.3.6
libchromiumcontent | 60.0.3112.78
V8 | 6.0.286.44
Node.js | 7.9.0
Update Channel | dev
OS Platform | Microsoft Windows [7 Ultimate]
OS Release | 6.1.7601
OS Architecture | x64

**Comment by bbondy** [comment] 2017-08-13 02:07
@kjozwiak could you attach your app.entry.js? I'd like to inspect the line numbers in the screenshot with the call stack

**Comment by stephenkru** [comment] 2017-08-13 04:44
I have been able to reproduce the bug reliably on win10. When you drag an drop the undocked tab inside of another tab it causes the browser to not function.
![test](https://user-images.githubusercontent.com/23619351/29246194-1db334ac-7fb8-11e7-88f0-a71a124f970b.gif)

**Comment by kjozwiak** [comment] 2017-08-13 04:50
> @kjozwiak could you attach your app.entry.js? I'd like to inspect the line numbers in the screenshot with the call stack

[app.entry.js.zip](https://github.com/brave/browser-laptop/files/1220255/app.entry.js.zip)

**Comment by bbondy** [comment] 2017-08-14 02:07
I think this will be fixe din 0.19.x with my index changes, so moving there. I do have a couple of cleanups I'll push that will make it less likely though.

**Comment by binhonglee** [comment] 2017-08-16 06:46
Happened to me on both Windows 10 and macOS.

Couldn't repro on MacOS as it just works when I "close it and open it again".

As for Windows 10, it work on my 3rd attempt reopening the browser. Here's a walkthrough on what I found in each attempts.
1. Refreshed, closed.
2. Disabled and reenabled Shields. Still can't see anything (white blank screen like OP) but I did realize that I can highlight the page and click on links if they are positioned so on the page.
3. Moved my mouse around. Select the only tab opened from the tab bar. Shows everything.

Not sure what does this add to the process but I hope it helps.

**Comment by LaurenWags** [comment] 2017-08-16 21:22
+1 from community https://community.brave.com/t/browser-tabs-open-up-in-a-new-window-far-too-easily/5850

**Comment by LaurenWags** [comment] 2017-08-17 19:33
+1 from community https://community.brave.com/t/detaching-reattaching-a-tab-makes-it-inaccessible/6099

**Comment by LaurenWags** [comment] 2017-08-21 13:11
+1 from community:
https://community.brave.com/t/brave-becomes-unresponsive-randomly/6343

**Comment by Linusky17** [comment] 2017-08-21 15:37
I can confirm that I am experiencing the exact same issue. Right now I have to avoid detaching tabs to prevent this...
I am using Windows 8.1 Pro Version 6.3 (Build 9600) 64 bit
UI becomes unresponsive

**Comment by kevinp2** [comment] 2017-08-22 22:58
The same thing appears on Windows 7 with Brave 0.18.23  Unsure about the root cause.

**Comment by Liunkae** [comment] 2017-08-25 18:32
Randomly happened to me with Brave 0.18.23 (36ae2ec) on maOS 10.12.x.

Browser-level console output:
![](https://user-images.githubusercontent.com/19424103/29727467-9c9f4fb8-8999-11e7-9e93-54d2736889c6.png)

**Comment by kjozwiak** [comment] 2017-08-31 14:40
@bbondy looks like this is still reproducible under Win 10 x64 using the following build:

> Brave 0.18.24 rev 1853c35eeeac8ae271755f5aef71a06ebeef7e83
> Muon 4.3.14
> libchromiumcontent 60.0.3112.101

**STR Used:**

* launch Brave 0.18.24
* Close the about:welcome tab
* Load duckduckgo.com within the remaining about:newtab
* Open a new tab using the "+" button and load about:preferences
* Start detaching each tab and putting it back into the window
* Do this a few times with each tab and you'll run into the issue where the entire UI becomes unresponsive

**Example of issue:**

![issue](https://user-images.githubusercontent.com/2602313/29929041-729be0fc-8e38-11e7-9a8f-559201407969.gif)

**Comment by kjozwiak** [comment] 2017-08-31 15:21
BTW, I managed to reproduce this a few times on macOS while using `Brave v0.18.23` so it's definitely on macOS as well. It's just harder to reproduce.

**Comment by kjozwiak** [comment] 2017-08-31 17:31
You can also reproduce this issue using the following STR:

* Launch Brave
* Hold `ctrl + t` and start spamming the browser with new tabs

After about 10-15 tabs, the entire UI will become unresponsive.

Reproduced using the following build:

> Brave 0.18.24 rev 1853c35eeeac8ae271755f5aef71a06ebeef7e83
> Muon 4.3.14
> libchromiumcontent 60.0.3112.101

Example:

![unresponsiveissue](https://user-images.githubusercontent.com/2602313/29936536-99ee9330-8e50-11e7-976c-4f0022de6273.gif)

**Comment by kjozwiak** [comment] 2017-08-31 18:28
Once #10749 is fixed, I'll retest this and see if it was fixed. If not, I'll move this back to the `0.19.x (Beta Channel)` milestone.

**Comment by bbondy** [comment] 2017-09-02 03:03
I narrowed this down more.
Window 1
  Tab 1
  Tab 2


The key thing here is if you close window 1 for a tab that originated in window 1 then it reproduces.

So if you keep window 1 open and tear off tab1 and 2 into a new window, but always return to Window 1, then it will never reproduce.

if you Move the tabs to a Window 2, and Window 1 closes (or even close it yourself without tearing off last tab), then it will always reproduce.

It seems like there's some link to the originating window that isn't updated and when the originating window is closed it causes problems like crashing and dead tab.

**Comment by bbondy** [comment] 2017-09-05 04:55
Fixed in muon 4.3.16
https://github.com/brave/muon/commit/3fccef69ca982b97f39fb2f4bdec5e1843af6687

Please wait to test this until you have a build with muon 4.3.16

**Closed by bbondy** 2017-09-05 04:55 UTC
Labels: bug, QA/test-plan-required, release-notes/include, release/blocking

**Comment by srirambv** [comment] 2017-09-06 05:08
Verified on 0.18.27 with steps mentioned here https://github.com/brave/browser-laptop/issues/10436#issuecomment-326316594. No issues found.
