### ISSUE TITLE
Speedtest fails with adblock message

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11232] opened 2017-10-02 08:18 UTC
### Description
Speedtest fails with adblock message

### Steps to Reproduce

  1. Visit speedtest.net and try running test, fails with error
  2.
  3.

**Actual result:**

![speedtest](https://user-images.githubusercontent.com/17010094/31067906-5d82a57e-a74d-11e7-8684-3ab4c945c801.png)

**Expected result:**
Should  run speedtest

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version

**about:brave info:**

Brave | 0.19.24
-- | --
rev | 3b3fba2
Muon | 4.4.25

**Reproducible on current live release:**

No

**Comment by bbondy** [comment] 2017-10-07 04:30
Fixed by
https://github.com/brave/ad-block/commit/4360345f35efcbd0b314e874ba55c40ccb7f2230

**Closed by bbondy** 2017-10-07 04:30 UTC
Labels: bug, feature/adblock

**Comment by Zuikkis** [comment] 2017-11-03 18:46
In Brave 0.19.70, beta.speedtest.net does not work at all anymore. No matter what adblock settings. Sometimes fails with "latency test error", sometimes simply returns to start with no message.

**Comment by luixxiul** [comment] 2017-11-03 19:10
Hi @Zuikkis! The issue is currently discussed on https://community.brave.com/t/why-cant-i-run-speed-test/9554. Would you please join the conversation there to talk about the issue further? :smile:

There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
