### ISSUE TITLE
Double Click to minimize does not work in OSX

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#9598] opened 2017-06-20 14:26 UTC
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
From community (https://community.brave.com/t/double-click-to-minimize-doesnt-work-in-osx/2274)

Mac OSX Sierra. There's a setting in Dock Preferences for double-clicking a window's title bar to minimize it. This is ignored in OSX. Instead, Brave seems to maximize but not go full screen.

- Platform (Win7, 8, 10? macOS? Linux distro?):
OSX

- Brave Version (revision SHA):
Reproduced on 

Name	Version
Brave	0.17.3
rev	02a7878
Muon	4.0.3

- Steps to reproduce:
    1. Navigate to System Preferences > Dock.
    2. If not already checked, select checkbox for 'Double-click a window's title bar to' and make sure the drop list says 'minimize'. Close preferences.
    3. Open Brave
    4. Double click in the space next to the URL bar.
    
- Actual result:
Brave is maximized (not full screen).

- Expected result:
Per the setting, Brave should be minimized to the dock.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Repeat with Chrome. Chrome is minimized as expected.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment] 2017-06-20 20:27
Duplicate of #2364.

**Closed by Liunkae** 2017-06-20 20:27 UTC
Labels: bug, OS/macOS
