### ISSUE TITLE
Disable tooltip

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10220] opened 2017-08-01 03:55 UTC
**Describe the issue you encountered:** https://community.brave.com/t/ux-disabling-tooltips-on-brave/5181?u=suguru

> As a Brave User, I want to …
>
> disable tooltips in the settings menu

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version (revision SHA): master branch

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by bsclifton** [comment] 2017-08-17 06:35
This is a duplicate of https://github.com/brave/browser-laptop/issues/8697

**Closed by bsclifton** 2017-08-17 06:35 UTC
Labels: suggestion
