### ISSUE TITLE
Sending chat messages in Gmail fails

### ISSUE THREAD

**Issue by rjdp** [brave/browser-laptop#14117] opened 2018-05-14 10:38 UTC
### Description
Sending chat messages in Gmail fails

### Steps to Reproduce
  1. try sending cat message in gmail

**Actual result:**
![screen shot 2018-05-14 at 4 05 07 pm](https://user-images.githubusercontent.com/7734938/39992501-a10f353e-5790-11e8-8441-5c6f640f2d13.png)

**Expected result:**
message should be sent successfully

**Reproduces how often:**
every time

### Brave Version
 
Brave: 0.22.669 
V8: 6.6.346.24 
rev: 6cda2e84f749e66409e9e3bca63f5796422e7edf 
Muon: 5.2.7 
OS Release: 17.6.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.117

**Reproducible on current live release:**
Yes

**Comment by srirambv** [comment] 2018-05-14 12:18
Closing as dupe of https://github.com/brave/browser-laptop/issues/10875.

**Closed by srirambv** 2018-05-14 12:18 UTC
