### ISSUE TITLE
Rendering with ClearType

### ISSUE THREAD

**Issue by meyesme** [brave/browser-laptop#6144] opened 2016-12-11 21:20 UTC
I'm using Brave in Windows 7. Compared to Firefox and Chrome it looks all a bit blurry in Brave, and I think it's just that I'm accustomed to ClearType and Brave seemingly doesn't use the same ClearType rendering, if at all.

**Comment by bsclifton** [comment] 2016-12-12 16:15
@meyesme are you able to show how it looks via a screenshot? Also, I am curious if you have a higher DPI setting (like UI being show at 125% of actual size, usually set for larger monitors)

**Comment by bsclifton** [comment] 2017-01-31 18:06
@meyesme we have a potential fix for this which should be coming soon!  Would you be interested in helping us test this to verify the issue is fixed? 😄

**Closed** 2017-01-31 18:38 UTC
Labels: info-needed, OS/Windows, QA/no-qa-needed
